import type { MathSubmoduleLesson } from "./math-a1-types";

export const MATH_A5_2_LESSON: MathSubmoduleLesson = {
    submoduleId: "A5-2",
    submoduleCode: "A5.2",
    theory: {
      title: { fr: "Suite de nombres à virgule", en: "Sequences of decimal numbers", ar: "متتالية أعداد عشرية", fa: "دنباله اعداد اعشاری", ti: "ተኸታተልቲ ቁጽሪ ቪርጉላ", uk: "Послідовності десяткових чисел" },
      paragraphs: {
        fr: [
          "Une suite de nombres est une liste de nombres qui suivent une règle. Avant de calculer, il faut regarder si les nombres augmentent (ordre croissant) ou diminuent (ordre décroissant) et trouver le pas (l'écart entre deux termes consécutifs).",
          "S'il y a deux nombres consécutifs — croissant : effectuez une soustraction pour trouver le pas, puis additionnez. Exemple : 2,5 ; ___ ; 3,5 ; 4 → 4 − 3,5 = 0,5 → terme manquant = 2,5 + 0,5 = 3.",
          "Décroissant : même principe, on soustrait. Exemple : 7,25 ; 7 ; ___ ; 6,5 → 7,25 − 7 = 0,25 → terme manquant = 7 − 0,25 = 6,75.",
          "S'il n'y a pas deux nombres consécutifs et deux écarts entre eux : effectuez une soustraction, puis divisez par 2. Exemple : ___ ; 7,2 ; ___ ; 9,6 → 9,6 − 7,2 = 2,4 → 2,4 ÷ 2 = 1,2 → termes : 6,0 ; 7,2 ; 8,4 ; 9,6.",
          "S'il n'y a pas deux nombres consécutifs et trois écarts entre eux : effectuez une soustraction, puis divisez par 3. Exemple : 10 ; ___ ; ___ ; 6,7 → 10 − 6,7 = 3,3 → 3,3 ÷ 3 = 1,1 → termes : 10 ; 8,9 ; 7,8 ; 6,7.",
        ],
        en: [
          "A sequence is a list of numbers following a rule. First check whether numbers increase (ascending) or decrease (descending), then find the step (gap between consecutive terms).",
          "With 2 consecutive numbers — ascending: subtract to find the step, then add. Example: 2.5; ___; 3.5; 4 → step = 0.5 → missing = 3.",
          "Descending: same idea, subtract. Example: 7.25; 7; ___; 6.5 → step = 0.25 → missing = 6.75.",
          "With 2 gaps between known numbers: subtract, then divide by 2. Example: ___; 7.2; ___; 9.6 → 2.4 ÷ 2 = 1.2 → 6.0; 7.2; 8.4; 9.6.",
          "With 3 gaps: subtract, divide by 3. Example: 10; ___; ___; 6.7 → 3.3 ÷ 3 = 1.1 → 10; 8.9; 7.8; 6.7.",
        ],
        ar: [
          "المتتالية قائمة من الأعداد تتبع قاعدة. قرر أولًا إن كانت تتزايد (تصاعدي) أو تتناقص (تنازلي) وجد الخطوة (الفرق بين حدين متتاليين).",
          "مع حدين متتاليين — تصاعدي: اطرح لتجد الخطوة ثم أجمع. مثال: 2,5; ___; 3,5; 4 → خطوة = 0,5 → الناقص = 3.",
          "تنازلي: نفس الفكرة مع الطرح. مثال: 7,25; 7; ___; 6,5 → الناقص = 6,75.",
          "مع فجوتين بين المعلومَين: اطرح ثم اقسم على 2. مثال: ___; 7,2; ___; 9,6 → 2,4 ÷ 2 = 1,2.",
          "مع ثلاث فجوات: اطرح ثم اقسم على 3. مثال: 10; ___; ___; 6,7 → 3,3 ÷ 3 = 1,1.",
        ],
        fa: [
          "دنباله فهرستی از اعداد است که قانونی را دنبال می‌کنند. ابتدا بررسی کنید آیا اعداد افزایش (صعودی) یا کاهش (نزولی) دارند و گام را بیابید.",
          "با ۲ عدد متوالی — صعودی: تفریق کنید تا گام را بیابید، سپس جمع کنید. مثال: ۲,۵; ___; ۳,۵; ۴ → گام = ۰,۵ → جمله گمشده = ۳.",
          "نزولی: همان ایده با تفریق. مثال: ۷,۲۵; ۷; ___; ۶,۵ → گمشده = ۶,۷۵.",
          "با ۲ فاصله بین اعداد معلوم: تفریق کنید، بر ۲ تقسیم کنید. مثال: ___; ۷,۲; ___; ۹,۶ → ۲,۴ ÷ ۲ = ۱,۲.",
          "با ۳ فاصله: تفریق کنید، بر ۳ تقسیم کنید. مثال: ۱۰; ___; ___; ۶,۷ → ۳,۳ ÷ ۳ = ۱,۱.",
        ],
        ti: [
          "ናይ ቁጽሪ ቪርጉላ ተኸታተልቲ ሕጊ ዝስዕቡ ቁጽሪታት ዝርዝር እዩ። ቅድሚ ምስረቲ ቁጽሪታት ይዕብዩ (ብዕብየት) ወይ ይነኣሱ (ብንኡስ) ምፍላጥ ደሊ።",
          "ክልተ ዝደምበ ቁጽሪ ምስ ዝህሉ — ብዕብየት: ምቅናስ ናይ ስጉምቲ ምርካብ። ኣብነት: 2,5; ___; 3,5; 4 → ስጉምቲ = 0,5 → ዝጎደለ = 3.",
          "ዝነኣስ: ናይ ዝነኣሰ ምቅናስ። ኣብነት: 7,25; 7; ___; 6,5 → ዝጎደለ = 6,75.",
          "ክልተ ፍርቂ ናይ ዝቐረ ምስ ዝህሉ: ቀንስ ብ2 ፈሊ። ኣብነት: ___; 7,2; ___; 9,6 → 2,4 ÷ 2 = 1,2.",
          "ሰለስተ ፍርቂ: ቀንስ ብ3 ፈሊ። ኣብነት: 10; ___; ___; 6,7 → 3,3 ÷ 3 = 1,1.",
        ],
        uk: [
          "Послідовність — список чисел, що слідують певному правилу. Спочатку визначте, чи числа зростають чи спадають, і знайдіть крок (різниця між сусідніми членами).",
          "З 2 сусідніми числами — зростаюча: відніміть для знаходження кроку, потім додайте. Приклад: 2,5; ___; 3,5; 4 → крок = 0,5 → відсутній = 3.",
          "Спадна: те саме, але віднімаємо. Приклад: 7,25; 7; ___; 6,5 → відсутній = 6,75.",
          "З 2 пропусками між відомими: відніміть, поділіть на 2. Приклад: ___; 7,2; ___; 9,6 → 2,4 ÷ 2 = 1,2.",
          "З 3 пропусками: відніміть, поділіть на 3. Приклад: 10; ___; ___; 6,7 → 3,3 ÷ 3 = 1,1.",
        ],
      },
    },
    exercises: [
      { id: "a5-2-e1", promptFr: "Suite : __ ; __ ; 3,50 ; __ ; 6,00 ; 7,25 ; __. Quel est le 7ème terme ?", type: "short_text", acceptable: ["8,50", "8.50", "8,5", "8.5"] },
      { id: "a5-2-e2", promptFr: "Suite : __ ; 1,45 ; 1,50 ; __ ; __ ; __ ; 1,70. Quel est le terme après 1,50 ?", type: "short_text", acceptable: ["1,55", "1.55"] },
      { id: "a5-2-e3", promptFr: "Suite décroissante : __ ; 5,10 ; __ ; 5,00 ; 4,95 ; __ ; __. Quel est le 1er terme ?", type: "short_text", acceptable: ["5,15", "5.15"] },
      { id: "a5-2-e4", promptFr: "Suite : 2,80 ; __ ; __ ; __ ; 7,20 ; __ ; 9,40. Quel est le 2ème terme ?", type: "short_text", acceptable: ["3,90", "3.90", "3,9", "3.9"] },
      { id: "a5-2-e5", promptFr: "Suite décroissante : 9,35 ; __ ; __ ; __ ; 4,35 ; __ ; 1,85. Quel est le 6ème terme ?", type: "short_text", acceptable: ["3,10", "3.10", "3,1", "3.1"] },
    ],
    exercisePool: [
      { id: "a5-2-p1", promptFr: "Suite : __ ; __ ; 3,50 ; __ ; 6,00 ; 7,25 ; __. Quel est le 1er terme ?", type: "short_text", acceptable: ["1,00", "1.00", "1", "1,0", "1.0"] },
      { id: "a5-2-p2", promptFr: "Suite : __ ; __ ; 3,50 ; __ ; 6,00 ; 7,25 ; __. Quel est le 4ème terme ?", type: "short_text", acceptable: ["4,75", "4.75"] },
      { id: "a5-2-p3", promptFr: "Suite : __ ; 1,45 ; 1,50 ; __ ; __ ; __ ; 1,70. Quel est le terme avant 1,45 ?", type: "short_text", acceptable: ["1,40", "1.40", "1,4", "1.4"] },
      { id: "a5-2-p4", promptFr: "Suite : __ ; 1,45 ; 1,50 ; __ ; __ ; __ ; 1,70. Quel est le terme après 1,50 ?", type: "short_text", acceptable: ["1,55", "1.55"] },
      { id: "a5-2-p5", promptFr: "Suite décroissante : __ ; 5,10 ; __ ; 5,00 ; 4,95 ; __ ; __. Quel est le 7ème terme ?", type: "short_text", acceptable: ["4,85", "4.85"] },
      { id: "a5-2-p6", promptFr: "Suite décroissante : __ ; 5,10 ; __ ; 5,00 ; 4,95 ; __ ; __. Quel est le 3ème terme ?", type: "short_text", acceptable: ["5,05", "5.05"] },
      { id: "a5-2-p7", promptFr: "Suite : 2,80 ; __ ; __ ; __ ; 7,20 ; __ ; 9,40. Quel est le 6ème terme ?", type: "short_text", acceptable: ["8,30", "8.30", "8,3", "8.3"] },
      { id: "a5-2-p8", promptFr: "Suite décroissante : 9,35 ; __ ; __ ; __ ; 4,35 ; __ ; 1,85. Quel est le 2ème terme ?", type: "short_text", acceptable: ["8,10", "8.10", "8,1", "8.1"] },
      { id: "a5-2-p9", promptFr: "Suite : __ ; __ ; __ ; 5,50 ; 6,85 ; __ ; 9,55. Quel est le 1er terme ?", type: "short_text", acceptable: ["1,45", "1.45"] },
      { id: "a5-2-p10", promptFr: "Suite : __ ; __ ; __ ; 5,50 ; 6,85 ; __ ; 9,55. Quel est le 6ème terme ?", type: "short_text", acceptable: ["8,20", "8.20", "8,2", "8.2"] },
      { id: "a5-2-p11", promptFr: "Suite décroissante : __ ; 4,35 ; __ ; 3,25 ; 2,70 ; __ ; __. Quel est le 1er terme ?", type: "short_text", acceptable: ["4,90", "4.90", "4,9", "4.9"] },
      { id: "a5-2-p12", promptFr: "Suite décroissante : __ ; 4,35 ; __ ; 3,25 ; 2,70 ; __ ; __. Quel est le dernier terme ?", type: "short_text", acceptable: ["1,60", "1.60", "1,6", "1.6"] },
      { id: "a5-2-p13", promptFr: "Suite décroissante : 7,85 ; __ ; __ ; __ ; __ ; 5,85 ; 5,45. Quel est le 2ème terme ?", type: "short_text", acceptable: ["7,45", "7.45"] },
      { id: "a5-2-p14", promptFr: "Suite décroissante : 7,85 ; __ ; __ ; __ ; __ ; 5,85 ; 5,45. Quel est le 5ème terme ?", type: "short_text", acceptable: ["6,25", "6.25"] },
      { id: "a5-2-p15", promptFr: "Suite : __ ; __ ; __ ; 4,15 ; 5,20 ; 6,25 ; __. Quel est le dernier terme ?", type: "short_text", acceptable: ["7,30", "7.30", "7,3", "7.3"] },
      { id: "a5-2-p16", promptFr: "Suite : __ ; __ ; __ ; 4,15 ; 5,20 ; 6,25 ; __. Quel est le 1er terme ?", type: "short_text", acceptable: ["1,00", "1.00", "1", "1,0", "1.0"] },
      { id: "a5-2-p17", promptFr: "Suite : __ ; __ ; 4,90 ; 4,95 ; 5,00 ; __ ; __. Quel est le 1er terme ?", type: "short_text", acceptable: ["4,80", "4.80", "4,8", "4.8"] },
      { id: "a5-2-p18", promptFr: "Suite décroissante : 3,55 ; __ ; __ ; 3,40 ; __ ; 3,30. Quel est le 5ème terme ?", type: "short_text", acceptable: ["3,35", "3.35"] },
      { id: "a5-2-p19", promptFr: "Suite décroissante : 3,55 ; __ ; __ ; 3,40 ; __ ; 3,30. Quel est le 2ème terme ?", type: "short_text", acceptable: ["3,50", "3.50", "3,5", "3.5"] },
      { id: "a5-2-p20", promptFr: "Suite décroissante : 9,25 ; __ ; __ ; __ ; 5,05 ; __ ; 2,95. Quel est le 6ème terme ?", type: "short_text", acceptable: ["4,00", "4.00", "4", "4,0", "4.0"] },
      { id: "a5-2-p21", promptFr: "Suite décroissante : 9,25 ; __ ; __ ; __ ; 5,05 ; __ ; 2,95. Quel est le 2ème terme ?", type: "short_text", acceptable: ["8,20", "8.20", "8,2", "8.2"] },
    ],
    poolSize: 5,
  };
