import type { MathSubmoduleLesson } from "./math-a1-types";
import { A1_COMPTER_EN_FRANCAIS_ROWS } from "./math-a1-readaloud-rows";

/** Contenu A1 (module « Nombres entiers naturels »), théorie multilingue et exercices. */
export const MATH_A1_LESSONS: MathSubmoduleLesson[] = [
  {
    submoduleId: "A1-1",
    submoduleCode: "A1.1",
    theory: {
      title: {
        fr: "Compter en français",
        en: "Counting in French",
        ar: "العد بالفرنسية",
        fa: "شمارش به فرانسوی",
        ti: "ምቑጻር ብፈረንሳይ",
        uk: "Лічба французькою",
      },
      paragraphs: {
        fr: [
          "Un nombre entier s’écrit avec des chiffres (0 à 9).",
          "En français, on sépare souvent les milliers par une espace fine : 125 000.",
          "En Suisse romande, on utilise souvent septante, huitante et nonante pour 70, 80 et 90.",
        ],
        ar: [
          "نكتب العدد الصحيح بأرقام من 0 إلى 9.",
          "في الفرنسية، نفصل الآلاف أحيانًا بمسافة رفيعة : 125 000.",
          "في الروماندي السويسري يقال غالبًا septante وhuitante وnonante لـ 70 و80 و90.",
        ],
        fa: [
          "عدد صحیح را با ارقام ۰ تا ۹ می‌نویسیم.",
          "در فرانسوی، هزارگان را گاه با فاصلهٔ ظریف جدا می‌کنند: ۱۲۵ ۰۰۰.",
          "در سوئیس رماند معمولاً برای ۷۰ و ۸۰ و ۹۰ می‌گویند septante، huitante، nonante.",
        ],
        ti: [
          "ኣኃዝቲ ብኣሃዝቲ 0-9 ይጽዓን።",
          "ኣብ ፈረንሳይ ሽሕታት ብልዝብ ክፈልጹ ይኽእሉ።",
          "ኣብ ስዊዘርላንድ ብ 70-80-90 septante ፡ huitante ፡ nonante ይበሃሉ ።",
        ],
        uk: [
          "Ціле число записують цифрами від 0 до 9.",
          "У французькій тисячі часто відокремлюють тонким пробілом: 125 000.",
          "У романській Швейцарії для 70, 80 і 90 часто кажуть septante, huitante, nonante.",
        ],
        en: [
          "A whole number is written with digits (0 to 9).",
          "In French, thousands are often separated by a thin space: 125 000.",
          "In French-speaking Switzerland, people often say septante, huitante and nonante for 70, 80 and 90.",
        ],
      },
      readAloud: {
        headingFr: "Enregistrement",
        legendFr: [
          {
            swatch: "red", labelFr: "Rouge : un seul son",
            labelPivot: {
              en: "Red: one sound", ar: "أحمر: صوت واحد",
              fa: "قرمز: یک صدا", uk: "Червоний: один звук", ti: "ቀይሕ: ሓደ ድምጺ",
            },
          },
          {
            swatch: "text", labelFr: "Noir : son",
            labelPivot: {
              en: "Black: sound", ar: "أسود: صوت",
              fa: "سیاه: صدا", uk: "Чорний: звук", ti: "ጸሊም: ድምጺ",
            },
          },
          {
            swatch: "gray", labelFr: "Gris : pas de son",
            labelPivot: {
              en: "Gray: silent", ar: "رمادي: بدون صوت",
              fa: "خاکستری: بی‌صدا", uk: "Сірий: без звуку", ti: "ሕምብርቲ: ድምጺ የብሉን",
            },
          },
        ],
        rows: A1_COMPTER_EN_FRANCAIS_ROWS,
        audioSrc: "/audio/a1-1-compter-fr.m4a",
      },
    },
    exercises: [
      {
        id: "a11-1",
        promptFr: "Écris en chiffres : trois cent quarante-sept.",
        promptPivot: {
          en: "Write in digits: three hundred forty-seven.",
          ar: "اكتب بالأرقام: ثلاثمئة وسبعة وأربعون.",
          fa: "به رقم بنویس: سیصد و چهل و هفت.",
          uk: "Запиши цифрами: триста сорок сім.",
        },
        type: "number",
        acceptable: ["347"],
      },
      {
        id: "a11-2",
        promptFr: "Écris en lettres (en un seul mot en français) : 508",
        promptPivot: {
          en: "Write in words as a single French word: 508",
          ar: "اكتب بالحروف (بالفرنسية): 508",
          fa: "به حروف (فرانسوی، یک کلمه): ۵۰۸",
          uk: "Одним словом французькою: 508",
        },
        type: "short_text",
        acceptable: ["cinqcenthuit", "cinqcentuit"],
      },
      {
        id: "a11-3",
        promptFr: "Combien y a-t-il d’unités dans 60 ?",
        promptPivot: {
          en: "How many units are in 60?",
          ar: "كم وحدة في العدد 60؟",
          fa: "در ۶۰ چند یکی وجود دارد؟",
          uk: "Скільки одиниць у числі 60?",
        },
        type: "number",
        acceptable: ["0"],
      },
      {
        id: "a11-4",
        promptFr: "Quel est le plus grand : 892 ou 928 ? (écris le nombre gagnant)",
        promptPivot: {
          en: "Which is greater: 892 or 928? (write the larger number)",
          ar: "أيهما أكبر: 892 أم 928؟ (اكتب العدد الأكبر)",
          fa: "کدام بزرگ‌تر است: ۸۹۲ یا ۹۲۸؟ (عدد بزرگ‌تر را بنویس)",
          uk: "Що більше: 892 чи 928? (запиши більше)",
        },
        type: "number",
        acceptable: ["928"],
      },
    ],
  },
  {
    submoduleId: "A1-2",
    submoduleCode: "A1.2",
    theory: {
      title: {
        fr: "Lire et comprendre les nombres",
        en: "Reading and understanding numbers",
        ar: "قراءة الأعداد وفهمها",
        fa: "خواندن و فهمیدن اعداد",
        ti: "ኣኃዝቲ ምንባብን ምርዳእን",
        uk: "Читати й розуміти числа",
      },
      paragraphs: {
        fr: [
          "La numération est la manière d’écrire, lire et comprendre les nombres. Dans notre système décimal, chaque chiffre a une valeur selon sa position.",
          "• Dans le nombre 452, le chiffre **2** vaut deux unités (**2**).",
          "• Dans le nombre 524, le chiffre **2** vaut deux dizaines (**20**).",
          "• Dans le nombre 245, le chiffre **2** vaut deux centaines (**200**).",
          "• Dans le nombre 2453, le chiffre **2** vaut deux milliers (**2000**).",
          "On parle aussi de milliers (**M**), centaines (**C**), dizaines (**D**), unités (**U**) pour décomposer un nombre.",
        ],
        en: [
          "Numeration is how we write, read and understand numbers. In our decimal system, each digit has a value according to its place.",
          "• In 452, the digit 2 is worth two units (2).",
          "• In 524, the digit 2 is worth two tens (20).",
          "• In 245, the digit 2 is worth two hundreds (200).",
          "• In 2453, the digit 2 is worth two thousands (2000).",
          "We also break numbers down into thousands (M), hundreds (C), tens (D) and units (U).",
        ],
        ar: [
          "الترقيم هو طريقة كتابة الأعداد وقراءتها وفهمها. في النظام العشري، لكل رقم قيمة حسب مكانه.",
          "• في العدد 452، الرقم 2 يساوي وحدتين (2).", "• في العدد 524، الرقم 2 يساوي عشرات (20).",
          "• في العدد 245، الرقم 2 يساوي مئتين (200).", "• في العدد 2453، الرقم 2 يساوي ألفين (2000).",
          "نحلّل العدد أيضًا إلى آلاف (أ)، مئات (م)، عشرات (ع)، ووحدات (و).",
        ],
        fa: [
          "عددگذاری یعنی نوشتن، خواندن و فهمیدن اعداد. در دهدهی، هر رقم بسته به جایگاهش ارزش دارد.",
          "• در ۴۵۲، رقم ۲ برابر دو یکی (۲) است.", "• در ۵۲۴، رقم ۲ برابر دو ده (۲۰) است.",
          "• در ۲۴۵، رقم ۲ برابر دویست (۲۰۰) است.", "• در ۲۴۵۳، رقم ۲ برابر دو هزار (۲۰۰۰) است.",
          "عدد را به هزارها، صدها، ده‌ها و یک‌ها هم تجزیه می‌کنیم.",
        ],
        ti: [
          "ኣኃዝቲ ምጽሓፍ ፡ ምንባብን ምርዳእን ማለት እዩ። ኣብ ዴሲማል ፡ ነፍሪ ዝርከብ ኣሃዝቲ ብኣባጺኡ ዋጋ ኣለዎ።",
          "• ኣብ 452 እቲ 2 ክልተ ውልቃት (2) ማለት እዩ።", "• ኣብ 524 እቲ 2 ክልተ ዓሰርተታት (20) ማለት እዩ።",
          "• ኣብ 245 እቲ 2 ክልተ ሚእታት (200) ማለት እዩ።", "• ኣብ 2453 እቲ 2 ክልተ ሽሕታት (2000) ማለት እዩ።",
          "ኣኃዝቲ ናብ ሽሕታት ፡ ሚእታት ፡ ዓሰርተታት ፡ ውልቃት ይፈልጹ ።",
        ],
        uk: [
          "Нумерація — це спосіб записувати, читати й розуміти числа. У десятковій системі кожна цифра має значення залежно від розряду.",
          "• У числі 452 цифра 2 означає два одиниці (2).", "• У числі 524 цифра 2 означає два десятки (20).",
          "• У числі 245 цифра 2 означає дві сотні (200).", "• У числі 2453 цифра 2 означає дві тисячі (2000).",
          "Число також розкладають на тисячі (M), сотні (C), десятки (D) та одиниці (U).",
        ],
      },
      blocks: [
        { type: "plain", fr: "La numération est la manière d’écrire, lire et comprendre les nombres. Dans notre système **décimal**, chaque chiffre a une valeur selon sa position.", pivot: { en: "Numeration is how we write, read and understand numbers. In the decimal system, each digit has a value based on its position.", ar: "الترقيم طريقة كتابة الأعداد وقراءتها. في النظام العشري لكل رقم قيمة حسب موضعه.", fa: "عددگذاری روش نوشتن و خواندن اعداد است. در دهدهی هر رقم بسته به جایگاهش ارزش دارد.", uk: "Нумерація — спосіб записувати й розуміти числа. В десятковій кожна цифра залежить від розряду." } },
        { type: "heading", fr: "Valeur positionnelle (M · C · D · U)" },
        { type: "table", headersFr: ["Nombre", "M (Milliers)", "C (Centaines)", "D (Dizaines)", "U (Unités)"], rows: [
          ["452",  "—",  "4",  "5",  "2"],
          ["524",  "—",  "5",  "2",  "4"],
          ["2 453", "2", "4",  "5",  "3"],
          ["9 102", "9", "1",  "0",  "2"],
        ], captionFr: "Chaque chiffre occupe une position précise." },
        { type: "rule", titleFr: "Comment lire la valeur d’un chiffre", itemsFr: [
          "Repère sa position : U = ×1, D = ×10, C = ×100, M = ×1000.",
          "Multiplie le chiffre par la valeur de sa position.",
          "Exemple : dans 3 864, le chiffre 8 est en position C → 8 × 100 = **800**.",
        ], pivot: { en: { title: "How to read a digit’s value", items: ["Find its position: U=×1, D=×10, C=×100, M=×1000.", "Multiply the digit by its place value.", "Example: in 3 864, digit 8 is in the C position → 8 × 100 = 800."] } } },
        { type: "example", fr: "5 682 = 5 000 + 600 + 80 + 2", pivot: { en: "5 682 = 5 000 + 600 + 80 + 2", ar: "5 682 = 5000 + 600 + 80 + 2", fa: "۵ ۶۸۲ = ۵۰۰۰ + ۶۰۰ + ۸۰ + ۲", uk: "5 682 = 5 000 + 600 + 80 + 2" } },
        { type: "note", fr: "Astuce : pour comparer deux nombres, compare d’abord le nombre de chiffres. Plus un nombre a de chiffres, plus il est grand.", pivot: { en: "Tip: to compare two numbers, first count their digits. More digits = larger number.", ar: "نصيحة: لمقارنة عددين، قارن عدد الأرقام أولاً. كلما زادت الأرقام، كان العدد أكبر.", fa: "نکته: برای مقایسه دو عدد ابتدا تعداد رقم‌ها را بشمار. بیشتر رقم = عدد بزرگ‌تر.", uk: "Підказка: щоб порівняти числа, порівняй кількість цифр. Більше цифр = більше число." } },
      ],
    },
    exercises: [
      {
        id: "a12-1",
        promptFr: "Dans 3 864, combien vaut le chiffre 8 ?",
        promptPivot: { en: "In 3 864, what is the digit 8 worth?", ar: "في 3 864، ما قيمة الرقم 8؟", fa: "در ۳ ۸۶۴، ارزش رقم ۸ چند است؟", uk: "У 3 864 яке значення цифри 8?" },
        type: "number",
        acceptable: ["800"],
      },
      {
        id: "a12-2",
        promptFr: "Dans 5 240, la valeur du chiffre 4 est :",
        promptPivot: { en: "In 5 240, the value of the digit 4 is:", ar: "في 5 240، قيمة الرقم 4 هي:", fa: "در ۵ ۲۴۰، ارزش رقم ۴:", uk: "У 5 240 значення цифри 4:" },
        type: "number",
        acceptable: ["40"],
      },
      {
        id: "a12-3",
        promptFr: "Décompose 637 : combien de centaines ? (écris seulement le nombre de centaines)",
        promptPivot: { en: "Split 637: how many hundreds? (write only the number of hundreds)", ar: "حلّل 637: كم مئة؟ (اكتب عدد المئات فقط)", fa: "۶۳۷ را تجزیه کن: چند صد؟ (فقط عدد صدها)", uk: "Розклади 637: скільки сотень? (лише число сотень)" },
        type: "number",
        acceptable: ["6"],
      },
      {
        id: "a12-4",
        promptFr: "Dans 9 102, que vaut le chiffre en position des milliers ?",
        promptPivot: { en: "In 9 102, what is the digit in the thousands place worth?", ar: "في 9 102، ما قيمة الرقم في خانة الآلاف؟", fa: "در ۹ ۱۰۲، رقم جایگاه هزارگان چند است؟", uk: "У 9 102 яке значення цифри тисяч?" },
        type: "number",
        acceptable: ["9000"],
      },
    ],
    exercisePool: [
      { id: "a12-p1",  promptFr: "Dans 3 864, combien vaut le chiffre 8 ?",  type: "number", acceptable: ["800"] },
      { id: "a12-p2",  promptFr: "Dans 5 240, la valeur du chiffre 4 est :",  type: "number", acceptable: ["40"] },
      { id: "a12-p3",  promptFr: "Dans 7 426, que vaut le chiffre 7 ?",       type: "number", acceptable: ["7000"] },
      { id: "a12-p4",  promptFr: "Dans 4 832, que vaut le chiffre 8 ?",       type: "number", acceptable: ["800"] },
      { id: "a12-p5",  promptFr: "Dans 9 105, que vaut le chiffre 1 ?",       type: "number", acceptable: ["100"] },
      { id: "a12-p6",  promptFr: "Dans 3 089, que vaut le chiffre 8 ?",       type: "number", acceptable: ["80"] },
      { id: "a12-p7",  promptFr: "Dans 657, quel est le chiffre des dizaines ?", type: "number", acceptable: ["5"] },
      { id: "a12-p8",  promptFr: "Dans 4 832, quel est le chiffre des centaines ?", type: "number", acceptable: ["8"] },
      { id: "a12-p9",  promptFr: "Dans 9 105, quel est le chiffre des unités ?", type: "number", acceptable: ["5"] },
      { id: "a12-p10", promptFr: "Dans 7 426, quel est le chiffre des milliers ?", type: "number", acceptable: ["7"] },
      { id: "a12-p11", promptFr: "Décompose 5 682 : que vaut le chiffre 5 ?", type: "number", acceptable: ["5000"] },
      { id: "a12-p12", promptFr: "Décompose 3 409 : que vaut le chiffre 4 ?", type: "number", acceptable: ["400"] },
      { id: "a12-p13", promptFr: "Décompose 7 150 : que vaut le chiffre 1 ?", type: "number", acceptable: ["100"] },
      { id: "a12-p14", promptFr: "Décompose 8 024 : que vaut le chiffre 2 ?", type: "number", acceptable: ["20"] },
      { id: "a12-p15", promptFr: "Décompose 9 731 : que vaut le chiffre 9 ?", type: "number", acceptable: ["9000"] },
      { id: "a12-p16", promptFr: "Dans 1 593, que vaut le chiffre 5 ?",       type: "number", acceptable: ["500"] },
      { id: "a12-p17", promptFr: "Dans 6 074, que vaut le chiffre 7 ?",       type: "number", acceptable: ["70"] },
      { id: "a12-p18", promptFr: "Dans 2 816, quel est le chiffre des dizaines ?", type: "number", acceptable: ["1"] },
    ],
    poolSize: 5,
  },
  {
    submoduleId: "A1-3",
    submoduleCode: "A1.3",
    theory: {
      title: {
        fr: "Droite numérique",
        en: "Number line",
        ar: "المستقيم العددي",
        fa: "خط اعداد",
        ti: "ቁፅሪ ቁጽሪ ቀጽሪ",
        uk: "Числова пряма",
      },
      blocks: [
        { type: "plain", fr: "Sur une **droite numérique**, les nombres sont placés dans l’ordre croissant de gauche à droite. L’espacement entre deux nombres consécutifs peut être 5, 10, 100… selon l’échelle.", pivot: { en: "On a number line, numbers go in increasing order left to right. The gap between consecutive numbers can be 5, 10, 100… depending on the scale." } },
        { type: "rule", titleFr: "Comparer deux nombres", itemsFr: [
          "Si les deux nombres n’ont pas le même nombre de chiffres → le plus long est le plus grand.",
          "S’ils ont le même nombre de chiffres → compare chiffre par chiffre de gauche à droite.",
          "On utilise les symboles : < (plus petit), > (plus grand), = (égal).",
        ], pivot: { en: { title: "Comparing two numbers", items: ["Different number of digits → more digits = greater.", "Same number of digits → compare left to right.", "Use: < (less than), > (greater than), = (equal)."] } } },
        { type: "example", fr: "657 □ 4 832 → 657 a 3 chiffres, 4 832 en a 4 → 657 < 4 832", pivot: { en: "657 □ 4 832 → 657 has 3 digits, 4 832 has 4 → 657 < 4 832" } },
        { type: "heading", fr: "Nombres pairs et impairs" },
        { type: "rule", titleFr: "Pair ou impair ?", itemsFr: [
          "Un nombre est **pair** s’il se termine par 0, 2, 4, 6 ou 8.",
          "Un nombre est **impair** s’il se termine par 1, 3, 5, 7 ou 9.",
          "Exemples pairs : 4, 12, 38, 100 — Exemples impairs : 3, 17, 45, 99.",
        ], pivot: { en: { title: "Even or odd?", items: ["A number is even if it ends in 0, 2, 4, 6 or 8.", "A number is odd if it ends in 1, 3, 5, 7 or 9.", "Even: 4, 12, 38 — Odd: 3, 17, 45."] } } },
      ],
      paragraphs: {
        fr: [
          "Sur une droite numérique, les nombres sont placés dans l’ordre croissant de gauche à droite. L’espacement entre deux nombres consécutifs peut être 5, 10, 100… selon l’échelle.",
          "Pour trouver un nombre « entre » deux autres, on lit l’échelle : par exemple entre 450 et 460 avec un pas de 5 unités, on peut placer 455.",
          "Un nombre est **pair** s’il se termine par 0, 2, 4, 6 ou 8. Il peut être partagé en deux groupes égaux. Exemples : 4, 12, 38.",
          "Un nombre est **impair** s’il se termine par 1, 3, 5, 7 ou 9. Il ne peut pas être partagé en deux groupes égaux. Exemples : 3, 17, 45.",
        ],
        ar: [
          "على المستقيم العددي توضع الأعداد تصاعديًا من اليسار إلى اليمين. المسافة بين عددين متتاليين قد تكون 5 أو 10 أو 100 حسب المقياس.",
          "لإيجاد عدد بين عددين آخرين نقرأ المقياس: مثلًا بين 450 و 460 بخطوة 5 وحدات نضع 455.",
          "العدد **زوجي** إذا انتهى بـ 0 أو 2 أو 4 أو 6 أو 8، ويمكن تقسيمه إلى مجموعتين متساويتين. أمثلة: 4، 12، 38.",
          "العدد **فردي** إذا انتهى بـ 1 أو 3 أو 5 أو 7 أو 9، ولا يمكن تقسيمه إلى مجموعتين متساويتين. أمثلة: 3، 17، 45.",
        ],
        fa: [
          "روی خط اعداد، اعداد به ترتیب صعودی از چپ به راست قرار می‌گیرند. فاصلهٔ گام می‌تواند ۵، ۱۰ یا ۱۰۰ باشد.",
          "برای یافتن عدد بین دو عدد، مقیاس را می‌خوانیم؛ مثلاً بین ۴۵۰ و ۴۶۰ با گام ۵ واحد، عدد ۴۵۵ جای می‌گیرد.",
          "عدد **زوج** است اگر به ۰، ۲، ۴، ۶ یا ۸ ختم شود. می‌توان آن را به دو گروه مساوی تقسیم کرد. مثال: ۴، ۱۲، ۳۸.",
          "عدد **فرد** است اگر به ۱، ۳، ۵، ۷ یا ۹ ختم شود. نمی‌توان آن را به دو گروه مساوی تقسیم کرد. مثال: ۳، ۱۷، ۴۵.",
        ],
        ti: [
          "ኣኃዝቲ ኣብ ቀጽሪ ቁፅሪ ካብ ንደቓይቕ ክሳዕ የማን ብትሑትስነት ይውሰኩ። ርሕቀት መእተዊ 1፡ 10፡ 100 ክኸውን ይኽእል ።",
          "ኣብ መንካይ ክልተ ኣኃዝቲ ናይ መስፈሪ ንንበብ፡ ንኣብነት 450ን 460 ዝኣክል 1 455 እዩ ።",
          "ቁጽሪ **ዝተፈጥዎ (pair)** እዩ ምስ 0፡ 2፡ 4፡ 6 ወይ 8 ዝዛዘም። ምሳሌ: 4፡ 12፡ 38.",
          "ቁጽሪ **ዘይተፈጥዎ (impair)** እዩ ምስ 1፡ 3፡ 5፡ 7 ወይ 9 ዝዛዘም። ምሳሌ: 3፡ 17፡ 45.",
        ],
        uk: [
          "На числовій прямій числа розташовують у порядку зростання зліва направо. Крок може бути 5, 10, 100 тощо.",
          "Щоб знайти число «між» двома, читаємо масштаб: між 450 і 460 з кроком 5 одиниць буде, наприклад, 455.",
          "Число **парне**, якщо закінчується на 0, 2, 4, 6 або 8. Його можна поділити на дві рівні групи. Приклади: 4, 12, 38.",
          "Число **непарне**, якщо закінчується на 1, 3, 5, 7 або 9. Його не можна поділити на дві рівні групи. Приклади: 3, 17, 45.",
        ],
        en: [
          "On a number line, numbers are placed in increasing order from left to right. The gap between two neighbours can be 5, 10, 100… depending on the scale.",
          "To find a number between two others, read the scale: for example between 450 and 460 with a step of 5 units, you can place 455.",
          "A number is **even** if it ends in 0, 2, 4, 6 or 8. It can be split into two equal groups. Examples: 4, 12, 38.",
          "A number is **odd** if it ends in 1, 3, 5, 7 or 9. It cannot be split into two equal groups. Examples: 3, 17, 45.",
        ],
      },
    },
    exercises: [
      {
        id: "a13-1",
        promptFr: "Quel nombre entier est juste après 899 ?",
        promptPivot: { en: "Which whole number comes right after 899?" },
        type: "number",
        acceptable: ["900"],
      },
      {
        id: "a13-2",
        promptFr: "Quel nombre est entre 12 et 14 ?",
        promptPivot: { en: "Which number is between 12 and 14?" },
        type: "number",
        acceptable: ["13"],
      },
      {
        id: "a13-3",
        promptFr: "On saute de 100 en 100 : 300, 400, ?",
        promptPivot: { en: "Count by hundreds: 300, 400, ?" },
        type: "number",
        acceptable: ["500"],
      },
      {
        id: "a13-4",
        promptFr: "Le nombre 46 est-il pair ou impair ? (écris pair ou impair)",
        promptPivot: { en: "Is 46 even or odd? (write even or odd)" },
        type: "short_text",
        acceptable: ["pair", "even"],
      },
      {
        id: "a13-5",
        promptFr: "Le nombre 35 est-il pair ou impair ? (écris pair ou impair)",
        promptPivot: { en: "Is 35 even or odd? (write even or odd)" },
        type: "short_text",
        acceptable: ["impair", "odd"],
      },
    ],
    exercisePool: [
      { id: "a13-p1",  promptFr: "Quel nombre entier est juste après 899 ?",          type: "number",     acceptable: ["900"] },
      { id: "a13-p2",  promptFr: "Quel nombre est entre 12 et 14 ?",                  type: "number",     acceptable: ["13"] },
      { id: "a13-p3",  promptFr: "On saute de 100 en 100 : 300, 400, ?",              type: "number",     acceptable: ["500"] },
      { id: "a13-p4",  promptFr: "Le nombre 46 est-il pair ou impair ?",              type: "short_text", acceptable: ["pair", "even"] },
      { id: "a13-p5",  promptFr: "Le nombre 35 est-il pair ou impair ?",              type: "short_text", acceptable: ["impair", "odd"] },
      { id: "a13-p6",  promptFr: "Le nombre 72 est-il pair ou impair ?",              type: "short_text", acceptable: ["pair", "even"] },
      { id: "a13-p7",  promptFr: "Le nombre 103 est-il pair ou impair ?",             type: "short_text", acceptable: ["impair", "odd"] },
      { id: "a13-p8",  promptFr: "Quel nombre est juste avant 1 000 ?",               type: "number",     acceptable: ["999"] },
      { id: "a13-p9",  promptFr: "On saute de 5 en 5 : 15, 20, 25, ?",               type: "number",     acceptable: ["30"] },
      { id: "a13-p10", promptFr: "Quel est le plus grand : 456 ou 462 ? (écris le nombre)", type: "number", acceptable: ["462"] },
      { id: "a13-p11", promptFr: "Quel est le plus petit : 1 245 ou 995 ? (écris le nombre)", type: "number", acceptable: ["995"] },
      { id: "a13-p12", promptFr: "Compare 789 et 789 : quel signe ? (<, > ou =)",    type: "short_text", acceptable: ["="] },
      { id: "a13-p13", promptFr: "Compare 902 et 890 : quel signe ? (<, > ou =)",    type: "short_text", acceptable: [">"] },
      { id: "a13-p14", promptFr: "Compare 324 et 342 : quel signe ? (<, > ou =)",    type: "short_text", acceptable: ["<"] },
      { id: "a13-p15", promptFr: "Le nombre 880 est-il pair ou impair ?",             type: "short_text", acceptable: ["pair", "even"] },
      { id: "a13-p16", promptFr: "On saute de 10 en 10 : 70, 80, 90, ?",             type: "number",     acceptable: ["100"] },
    ],
    poolSize: 5,
  },
  {
    submoduleId: "A1-4",
    submoduleCode: "A1.4",
    theory: {
      title: {
        fr: "Comparer les nombres",
        en: "Comparing numbers",
        ar: "مقارنة الأعداد",
        fa: "مقایسه اعداد",
        ti: "ምውድዳር ቁጽርታት",
        uk: "Порівняння чисел",
      },
      blocks: [
        { type: "plain", fr: "Comparer des nombres consiste à déterminer lequel est le plus grand, le plus petit ou s'ils sont égaux.", pivot: { en: "Comparing numbers means determining which is greatest, smallest, or if they are equal.", ar: "مقارنة الأعداد تعني تحديد أيها أكبر أو أصغر أو متساوية.", fa: "مقایسه اعداد یعنی تعیین بزرگ‌ترین، کوچک‌ترین یا مساوی بودن آن‌ها.", uk: "Порівняти числа — визначити, яке більше, менше або вони рівні." } },
        { type: "rule", titleFr: "Règle de comparaison", itemsFr: [
          "Nombres avec un nombre différent de chiffres → le plus long est le plus grand.",
          "Même nombre de chiffres → compare chiffre par chiffre depuis la **gauche**.",
          "Dès qu'un chiffre est différent, le plus grand chiffre donne le plus grand nombre.",
        ], pivot: { en: { title: "Comparison rule", items: ["Different digit counts → more digits = greater.", "Same digit count → compare left to right.", "First different digit: the larger digit wins."] } } },
        { type: "table", headersFr: ["Comparaison", "Symbole", "Exemple"], rows: [
          ["plus petit que", "<", "456 < 462"],
          ["plus grand que", ">", "902 > 890"],
          ["égal à",         "=", "789 = 789"],
        ] },
        { type: "example", fr: "3 456 □ 3 421 → même nbre de chiffres → chiffres des milliers (3=3) → centaines (4=4) → dizaines : 5 > 2 → 3 456 > 3 421", pivot: { en: "3 456 □ 3 421 → same digits → thousands equal → hundreds equal → tens: 5 > 2 → 3 456 > 3 421" } },
      ],
      paragraphs: {
        fr: [
          "Pour comparer deux nombres, on compare chiffre par chiffre en commençant par les milliers.",
          "Si les chiffres des milliers sont égaux, on compare les centaines, puis les dizaines, puis les unités.",
          "On utilise < (plus petit que), > (plus grand que) ou = (égal à).",
        ],
        en: ["To compare two numbers, compare digit by digit starting with thousands.", "If thousands digits are equal, compare hundreds, then tens, then units.", "Use < (less than), > (greater than) or = (equal to)."],
        ar: ["لمقارنة عددين، نقارن رقماً برقم بدءاً من الآلاف.", "إذا تساوت أرقام الآلاف، نقارن المئات ثم العشرات ثم الوحدات.", "نستخدم < أو > أو =."],
        fa: ["برای مقایسه دو عدد، رقم به رقم از هزارگان شروع می‌کنیم.", "اگر هزارگان برابر باشد، صدگان، سپس ده‌تاها، سپس یکان را مقایسه می‌کنیم.", "از < یا > یا = استفاده می‌کنیم."],
        ti: ["ክልተ ቁጽርታት ንምውድዳር፡ ካብ ሽሕ ጀሚርና ኣሃዝ ብኣሃዝ ንወዳደር።", "ናይ ሽሕ ኣሃዝ እንተ ማዕሪዮም፡ ሚእቲ ድሕሪኡ ዓሰርተ ድሕሪኡ ውልቂ ንወዳደር።", "< ወይ > ወይ = ንጥቀም።"],
        uk: ["Щоб порівняти два числа, порівнюємо цифру за цифрою, починаючи з тисяч.", "Якщо тисячі рівні, порівнюємо сотні, потім десятки, потім одиниці.", "Використовуємо < або > або =."],
      },
    },
    exercises: [
      { id: "a14-1", promptFr: "Quel signe mettre ? 456 □ 462", promptPivot: { en: "Which sign? 456 □ 462" }, type: "short_text", acceptable: ["<"] },
      { id: "a14-2", promptFr: "Quel signe mettre ? 789 □ 789", promptPivot: { en: "Which sign? 789 □ 789" }, type: "short_text", acceptable: ["="] },
      { id: "a14-3", promptFr: "Quel signe mettre ? 902 □ 890", promptPivot: { en: "Which sign? 902 □ 890" }, type: "short_text", acceptable: [">"] },
    ],
    exercisePool: [
      { id: "a14-p1",  promptFr: "Quel signe ? 456 □ 462",    type: "short_text", acceptable: ["<"] },
      { id: "a14-p2",  promptFr: "Quel signe ? 789 □ 789",    type: "short_text", acceptable: ["="] },
      { id: "a14-p3",  promptFr: "Quel signe ? 902 □ 890",    type: "short_text", acceptable: [">"] },
      { id: "a14-p4",  promptFr: "Quel signe ? 1 245 □ 995",  type: "short_text", acceptable: [">"] },
      { id: "a14-p5",  promptFr: "Quel signe ? 3 456 □ 3 421", type: "short_text", acceptable: [">"] },
      { id: "a14-p6",  promptFr: "Quel signe ? 7 000 □ 6 999", type: "short_text", acceptable: [">"] },
      { id: "a14-p7",  promptFr: "Quel signe ? 512 □ 521",    type: "short_text", acceptable: ["<"] },
      { id: "a14-p8",  promptFr: "Quel signe ? 4 300 □ 4 300", type: "short_text", acceptable: ["="] },
      { id: "a14-p9",  promptFr: "Quel signe ? 88 □ 880",     type: "short_text", acceptable: ["<"] },
      { id: "a14-p10", promptFr: "Quel signe ? 2 074 □ 2 740", type: "short_text", acceptable: ["<"] },
      { id: "a14-p11", promptFr: "Quel signe ? 999 □ 1 000",  type: "short_text", acceptable: ["<"] },
      { id: "a14-p12", promptFr: "Quel signe ? 5 800 □ 5 080", type: "short_text", acceptable: [">"] },
      { id: "a14-p13", promptFr: "Quel est le plus grand : 637 ou 673 ? (écris le nombre)", type: "number", acceptable: ["673"] },
      { id: "a14-p14", promptFr: "Quel est le plus petit : 4 832 ou 4 382 ? (écris le nombre)", type: "number", acceptable: ["4382"] },
    ],
    poolSize: 5,
  },
  {
    submoduleId: "A1-5",
    submoduleCode: "A1.5",
    theory: {
      title: {
        fr: "Suites numériques",
        en: "Number sequences",
        ar: "المتتاليات العددية",
        fa: "دنباله‌های عددی",
        ti: "ናይ ቁጽሪ ተኸታታሊ",
        uk: "Числові послідовності",
      },
      blocks: [
        { type: "plain", fr: "Une **suite de nombres** est une liste ordonnée où chaque terme est obtenu en appliquant la même règle.", pivot: { en: "A number sequence is an ordered list where each term follows the same rule.", ar: "المتتالية العددية قائمة مرتبة تُحسب فيها كل حلقة بتطبيق نفس القاعدة.", fa: "دنباله عددی فهرستی مرتب است که هر جمله با همان قانون به دست می‌آید.", uk: "Числова послідовність — впорядкований список, де кожен член отримується за однаковим правилом." } },
        { type: "rule", titleFr: "Comment trouver le pas et compléter une suite", itemsFr: [
          "S'il y a deux termes consécutifs (suite croissante) → soustraction → additionne le résultat.",
          "S'il y a deux termes consécutifs (suite décroissante) → soustraction → soustrais le résultat.",
          "S'il n'y a pas deux termes consécutifs et il y a deux écarts → divise la différence par 2.",
          "S'il n'y a pas deux termes consécutifs et il y a trois écarts → divise la différence par 3.",
        ], pivot: { en: { title: "How to find the step and complete a sequence", items: ["Two consecutive terms (increasing) → subtract → add the result.", "Two consecutive terms (decreasing) → subtract → subtract the result.", "No two consecutive terms, two gaps → divide difference by 2.", "No two consecutive terms, three gaps → divide difference by 3."] } } },
        { type: "example", fr: "Croissante : 2, 5, 8, 11, ? → pas = 5−2 = +3 → terme suivant = 11+3 = 14", pivot: { en: "Increasing: 2, 5, 8, 11, ? → step = 5−2 = +3 → next = 11+3 = 14" } },
        { type: "example", fr: "Décroissante : 100, 90, 80, ? → pas = 100−90 = −10 → terme suivant = 80−10 = 70", pivot: { en: "Decreasing: 100, 90, 80, ? → step = −10 → next = 80−10 = 70" } },
      ],
      paragraphs: {
        fr: [
          "Une **suite de nombres** est une liste ordonnée où chaque terme est obtenu en appliquant la même règle.",
          "Pour trouver la règle, calcule la différence entre deux termes consécutifs : c'est le **pas** (ou saut).",
          "Le pas peut être positif (suite croissante) ou négatif (suite décroissante).",
          "Exemple croissant : **2, 5, 8, 11, ?** → pas = +3 → terme suivant = **14**",
          "Exemple décroissant : **100, 90, 80, ?** → pas = −10 → terme suivant = **70**",
        ],
        en: [
          "A **number sequence** is an ordered list where each term is found by applying the same rule.",
          "To find the rule, calculate the difference between two consecutive terms — that is the **step**.",
          "The step can be positive (increasing sequence) or negative (decreasing sequence).",
          "Increasing example: **2, 5, 8, 11, ?** → step = +3 → next term = **14**",
          "Decreasing example: **100, 90, 80, ?** → step = −10 → next term = **70**",
        ],
        ar: [
          "**المتتالية العددية** قائمة مرتبة تُحسب فيها كل حلقة بتطبيق نفس القاعدة.",
          "لإيجاد القاعدة، احسب الفرق بين حلقتين متتاليتين — هذا هو **الخطوة**.",
          "يمكن أن تكون الخطوة موجبة (متتالية تصاعدية) أو سالبة (تنازلية).",
          "مثال تصاعدي: **2, 5, 8, 11, ?** → خطوة = +3 → الحد التالي = **14**",
          "مثال تنازلي: **100, 90, 80, ?** → خطوة = −10 → الحد التالي = **70**",
        ],
        fa: [
          "**دنباله عددی** فهرستی مرتب است که در آن هر جمله با اعمال همان قانون به دست می‌آید.",
          "برای یافتن قانون، تفاوت بین دو جملهٔ پشت‌سرهم را حساب کن — این **گام** است.",
          "گام می‌تواند مثبت (دنبالهٔ صعودی) یا منفی (دنبالهٔ نزولی) باشد.",
          "مثال صعودی: **2, 5, 8, 11, ?** → گام = +3 → جملهٔ بعدی = **14**",
          "مثال نزولی: **100, 90, 80, ?** → گام = −10 → جملهٔ بعدی = **70**",
        ],
        ti: [
          "**ተኸታታሊ ቁጽሪ** ስርዓታዊ ዝርዝር ኣኃዝቲ እዩ፤ ነፍሲ ወከፍ ቁጽሪ ብሓደ ሕጊ ይርከብ።",
          "ሕጊ ንምርካብ፡ ኣብ ክልተ ተኸታተምቲ ናይ ደገ ኣኃዝቲ ፍልልይ ሓስብ — ንሱ **ስጉምቲ** ይበሃል።",
          "ስጉምቲ ኣወንታዊ (ዝዓቢ ተኸታታሊ) ወይ ኣሉታዊ (ዝነኪ ተኸታታሊ) ክኸውን ይኽእል።",
          "ኣወንታዊ ኣብነት: **2, 5, 8, 11, ?** → ስጉምቲ = +3 → ዝቕጽል ቁጽሪ = **14**",
          "ኣሉታዊ ኣብነት: **100, 90, 80, ?** → ስጉምቲ = −10 → ዝቕጽል ቁጽሪ = **70**",
        ],
        uk: [
          "**Числова послідовність** — це впорядкований список, де кожен член отримується за однаковим правилом.",
          "Щоб знайти правило, обчисли різницю між двома сусідніми членами — це **крок**.",
          "Крок може бути позитивним (зростаюча послідовність) або від'ємним (спадаюча).",
          "Приклад зростаючої: **2, 5, 8, 11, ?** → крок = +3 → наступний член = **14**",
          "Приклад спадаючої: **100, 90, 80, ?** → крок = −10 → наступний член = **70**",
        ],
      },
    },
    exercises: [
      {
        id: "a15-1",
        promptFr: "Suite : 3, 6, 9, 12, ? (écris le terme suivant)",
        promptPivot: { en: "Sequence: 3, 6, 9, 12, ? (write the next term)" },
        type: "number",
        acceptable: ["15"],
      },
      {
        id: "a15-2",
        promptFr: "Suite : 50, 45, 40, 35, ?",
        promptPivot: { en: "Sequence: 50, 45, 40, 35, ?" },
        type: "number",
        acceptable: ["30"],
      },
      {
        id: "a15-3",
        promptFr: "Suite : 100, 200, 300, 400, ?",
        promptPivot: { en: "Sequence: 100, 200, 300, 400, ?" },
        type: "number",
        acceptable: ["500"],
      },
    ],
    exercisePool: [
      { id: "a15-p1",  promptFr: "Suite : 3, 6, 9, 12, ?",                type: "number", acceptable: ["15"] },
      { id: "a15-p2",  promptFr: "Suite : 50, 45, 40, 35, ?",             type: "number", acceptable: ["30"] },
      { id: "a15-p3",  promptFr: "Suite : 100, 200, 300, 400, ?",         type: "number", acceptable: ["500"] },
      { id: "a15-p4",  promptFr: "Suite : 2, 5, 8, 11, ?",                type: "number", acceptable: ["14"] },
      { id: "a15-p5",  promptFr: "Suite : 1, 4, 7, 10, ?",                type: "number", acceptable: ["13"] },
      { id: "a15-p6",  promptFr: "Suite : 20, 17, 14, 11, ?",             type: "number", acceptable: ["8"] },
      { id: "a15-p7",  promptFr: "Suite : 10, 20, 30, 40, ?",             type: "number", acceptable: ["50"] },
      { id: "a15-p8",  promptFr: "Suite : 80, 75, 70, 65, ?",             type: "number", acceptable: ["60"] },
      { id: "a15-p9",  promptFr: "Suite : 5, 10, 15, 20, ?",              type: "number", acceptable: ["25"] },
      { id: "a15-p10", promptFr: "Suite : 1 000, 900, 800, 700, ?",       type: "number", acceptable: ["600"] },
      { id: "a15-p11", promptFr: "Suite : 0, 7, 14, 21, ?",               type: "number", acceptable: ["28"] },
      { id: "a15-p12", promptFr: "Suite : 100, 95, 90, 85, ?",            type: "number", acceptable: ["80"] },
      { id: "a15-p13", promptFr: "Suite : 4, 8, 12, 16, ?",               type: "number", acceptable: ["20"] },
      { id: "a15-p14", promptFr: "Suite : 50, 100, 150, 200, ?",          type: "number", acceptable: ["250"] },
      { id: "a15-p15", promptFr: "Suite croissante : 11, ?, 21, 26 — quel est le terme manquant ?", type: "number", acceptable: ["16"] },
      { id: "a15-p16", promptFr: "Suite : 90, 80, 70, 60, ?",             type: "number", acceptable: ["50"] },
    ],
    poolSize: 5,
  },
];

export function getA1Lesson(submoduleId: string): MathSubmoduleLesson | undefined {
  return MATH_A1_LESSONS.find((l) => l.submoduleId === submoduleId);
}
