import type { MathSubmoduleLesson } from "./math-a1-types";

export const MATH_S2_LESSONS: MathSubmoduleLesson[] = [
  {
    submoduleId: "S2-1",
    submoduleCode: "S2.1",
    theory: {
      title: {
        fr: "Expérience aléatoire et univers",
        en: "Random Experiment and Sample Space",
        ar: "التجربة العشوائية وفضاء العينة",
        fa: "آزمایش تصادفی و فضای نمونه",
        ti: "ናይ ዕድል ፈተነን ዓለምን",
        uk: "Випадковий дослід і простір елементарних подій",
      },
      paragraphs: {
        fr: [
          "Une expérience aléatoire est une expérience dont le résultat ne peut pas être prédit avec certitude à l'avance, même si l'on connaît toutes les conditions.",
          "L'univers (ou espace échantillonnal), noté Ω, est l'ensemble de tous les résultats possibles de l'expérience.",
          "Un événement est un sous-ensemble de Ω. L'événement certain = Ω (toujours réalisé). L'événement impossible = ∅ (jamais réalisé).",
          "Exemples d'univers : lancer un dé à 6 faces → Ω = {1, 2, 3, 4, 5, 6}. Lancer une pièce → Ω = {pile, face}. Tirer une carte dans un jeu de 52 → Ω a 52 éléments.",
          "Un événement élémentaire est composé d'un seul résultat. Un événement composé en regroupe plusieurs.",
        ],
        en: [
          "A random experiment is one whose outcome cannot be predicted with certainty in advance, even if all conditions are known.",
          "The sample space, written Ω, is the set of all possible outcomes of the experiment.",
          "An event is a subset of Ω. The certain event = Ω (always occurs). The impossible event = ∅ (never occurs).",
          "Examples: rolling a 6-sided die → Ω = {1, 2, 3, 4, 5, 6}. Flipping a coin → Ω = {heads, tails}. Drawing a card from 52 → Ω has 52 elements.",
          "An elementary event has one outcome. A compound event groups several outcomes.",
        ],
        ar: [
          "التجربة العشوائية هي تجربة لا يمكن التنبؤ بنتيجتها مسبقًا حتى مع معرفة جميع الظروف.",
          "فضاء العينة (Ω) هو مجموعة جميع النتائج الممكنة للتجربة.",
          "الحادثة هي مجموعة جزئية من Ω. الحادثة المؤكدة = Ω. الحادثة المستحيلة = ∅.",
          "أمثلة: رمي حجر نرد → Ω = {1, 2, 3, 4, 5, 6}. قلب عملة → Ω = {صورة، كتابة}.",
          "الحادثة الأولية تحتوي على نتيجة واحدة. الحادثة المركبة تضم عدة نتائج.",
        ],
        fa: [
          "آزمایش تصادفی آزمایشی است که نتیجه آن حتی با دانستن همه شرایط قابل پیش‌بینی نیست.",
          "فضای نمونه (Ω) مجموعه تمام نتایج ممکن آزمایش است.",
          "رویداد یک زیرمجموعه از Ω است. رویداد قطعی = Ω. رویداد محال = ∅.",
          "مثال‌ها: انداختن تاس ۶ وجهی → Ω = {۱، ۲، ۳، ۴، ۵، ۶}. انداختن سکه → Ω = {شیر، خط}.",
          "رویداد ابتدایی فقط یک نتیجه دارد. رویداد مرکب چندین نتیجه را گرد می‌آورد.",
        ],
        ti: [
          "ናይ ዕድል ፈተነ ውጽኢቱ ቅድሚ ምምጽኡ ዝፍለጥ ዘይኮነ ፈተነ እዩ።",
          "ዓለም (Ω) ናይ ፈተነ ኩሎም ክኾኑ ዝኽእሉ ውጽኢታት ጉጅለ እዩ።",
          "ፍጻሜ ናይ Ω ንኡስ-ጉጅለ እዩ። ዘይተርፍ ፍጻሜ = Ω. ዘይካኣል ፍጻሜ = ∅.",
          "ኣብነታት: ሽዱሽተ-ሸነኽ ቀለዓ ምእካብ → Ω = {1, 2, 3, 4, 5, 6}. ናይ ሳንቲም ምድርባይ → Ω = {ርእሲ፣ ጭዳ}.",
          "መሰረታዊ ፍጻሜ ሓደ ውጽኢት ዘለዎ እዩ። ሓቢሩ ዝቐርብ ፍጻሜ ብዙሕ ውጽኢታት ዘለዎ እዩ።",
        ],
        uk: [
          "Випадковий дослід — це дослід, результат якого не можна передбачити наперед, навіть якщо відомі всі умови.",
          "Простір елементарних подій (Ω) — це множина всіх можливих результатів досліду.",
          "Подія — це підмножина Ω. Достовірна подія = Ω. Неможлива подія = ∅.",
          "Приклади: кидання кубика → Ω = {1, 2, 3, 4, 5, 6}. Підкидання монети → Ω = {орел, решка}.",
          "Елементарна подія містить один результат. Складна подія об'єднує кілька результатів.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-1-e1",
        promptFr: "On lance un dé à 6 faces. Écris l'univers Ω (liste tous les résultats possibles entre accolades).",
        type: "short_text",
        acceptable: ["{1,2,3,4,5,6}", "{1, 2, 3, 4, 5, 6}"],
      },
      {
        id: "s2-1-e2",
        promptFr: "On lance une pièce. Combien d'éléments contient l'univers Ω ?",
        type: "number",
        acceptable: ["2"],
      },
      {
        id: "s2-1-e3",
        promptFr: "On tire une carte dans un jeu de 52 cartes. Combien d'éléments contient Ω ?",
        type: "number",
        acceptable: ["52"],
      },
      {
        id: "s2-1-e4",
        promptFr: "L'événement 'obtenir un 7 en lançant un dé à 6 faces' est-il impossible ou certain ?",
        type: "short_text",
        acceptable: ["impossible", "Impossible"],
      },
      {
        id: "s2-1-e5",
        promptFr: "L'événement 'obtenir un nombre entre 1 et 6 en lançant un dé' est-il impossible, certain ou ni l'un ni l'autre ?",
        type: "short_text",
        acceptable: ["certain", "Certain"],
      },
    ],
  },
  {
    submoduleId: "S2-2",
    submoduleCode: "S2.2",
    theory: {
      title: {
        fr: "Probabilité classique",
        en: "Classical Probability",
        ar: "الاحتمال الكلاسيكي",
        fa: "احتمال کلاسیک",
        ti: "ክላሲካዊ ዕድል",
        uk: "Класична імовірність",
      },
      paragraphs: {
        fr: [
          "La probabilité classique s'applique quand tous les résultats possibles sont équiprobables (même chance de se produire).",
          "Formule : P(A) = (nombre de résultats favorables à A) / (nombre total de résultats possibles) = Card(A) / Card(Ω).",
          "Exemples : P(obtenir 3 avec un dé) = 1/6. P(obtenir un nombre pair) = 3/6 = 1/2. P(obtenir ≥ 5) = 2/6 = 1/3.",
          "Propriétés : 0 ≤ P(A) ≤ 1 pour tout événement A. P(∅) = 0. P(Ω) = 1.",
          "Si P(A) = 0, l'événement est impossible. Si P(A) = 1, il est certain. Plus P(A) est proche de 1, plus l'événement est probable.",
        ],
        en: [
          "Classical probability applies when all outcomes are equally likely.",
          "Formula: P(A) = (number of outcomes favourable to A) / (total number of possible outcomes) = Card(A) / Card(Ω).",
          "Examples: P(rolling a 3) = 1/6. P(rolling an even number) = 3/6 = 1/2. P(rolling ≥ 5) = 2/6 = 1/3.",
          "Properties: 0 ≤ P(A) ≤ 1 for any event A. P(∅) = 0. P(Ω) = 1.",
          "If P(A) = 0, the event is impossible. If P(A) = 1, it is certain. The closer P(A) is to 1, the more likely the event.",
        ],
        ar: [
          "الاحتمال الكلاسيكي يُطبَّق حين تكون جميع النتائج متكافئة.",
          "الصيغة: P(A) = عدد النتائج الملائمة / مجموع النتائج الممكنة.",
          "أمثلة: P(الحصول على 3 بنرد) = 1/6. P(رقم زوجي) = 1/2. P(رقم ≥ 5) = 1/3.",
          "خصائص: 0 ≤ P(A) ≤ 1. P(∅) = 0. P(Ω) = 1.",
          "إذا كان P(A) = 0 فالحادثة مستحيلة. إذا كانت P(A) = 1 فهي مؤكدة.",
        ],
        fa: [
          "احتمال کلاسیک زمانی اعمال می‌شود که همه نتایج ممکن یکسان باشند.",
          "فرمول: P(A) = تعداد نتایج مطلوب / تعداد کل نتایج ممکن.",
          "مثال‌ها: P(دیدن ۳ با تاس) = ۱/۶. P(عدد زوج) = ۱/۲. P(عدد ≥ ۵) = ۱/۳.",
          "خواص: 0 ≤ P(A) ≤ 1. P(∅) = 0. P(Ω) = 1.",
          "اگر P(A) = 0 باشد، رویداد محال است. اگر P(A) = 1 باشد، قطعی است.",
        ],
        ti: [
          "ክላሲካዊ ዕድል ኩሎም ውጽኢታት ማዕረ ዕድል ምስ ዘለዎም ይጥቀሙሉ።",
          "ቅጥዒ: P(A) = ናይ A ዝሕጉስ ውጽኢታት / ጠቅላላ ክኾኑ ዝኽእሉ ውጽኢታት.",
          "ኣብነታት: P(3 ምርካብ ብቀለዓ) = 1/6. P(ሸፈተ ቁጽሪ) = 1/2. P(≥ 5) = 1/3.",
          "ባህርያት: 0 ≤ P(A) ≤ 1. P(∅) = 0. P(Ω) = 1.",
          "P(A) = 0 ምስ ዝኾን ፍጻሜ ዘይካኣል. P(A) = 1 ምስ ዝኾን ፍጻሜ ዘይተርፍ.",
        ],
        uk: [
          "Класична імовірність застосовується, коли всі результати рівноможливі.",
          "Формула: P(A) = (кількість сприятливих результатів) / (загальна кількість можливих результатів).",
          "Приклади: P(випадіння 3) = 1/6. P(парне число) = 3/6 = 1/2. P(≥ 5) = 2/6 = 1/3.",
          "Властивості: 0 ≤ P(A) ≤ 1. P(∅) = 0. P(Ω) = 1.",
          "Якщо P(A) = 0, подія неможлива. Якщо P(A) = 1, вона достовірна.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-2-e1",
        promptFr: "On lance un dé à 6 faces équilibré. Quelle est la probabilité d'obtenir un 4 ?",
        type: "short_text",
        acceptable: ["1/6"],
      },
      {
        id: "s2-2-e2",
        promptFr: "Quelle est la probabilité d'obtenir un nombre pair en lançant un dé à 6 faces ?",
        type: "short_text",
        acceptable: ["1/2", "3/6", "0,5", "0.5"],
      },
      {
        id: "s2-2-e3",
        promptFr: "On tire une carte au hasard dans un jeu de 52 cartes. Quelle est la probabilité de tirer un as ?",
        type: "short_text",
        acceptable: ["4/52", "1/13"],
      },
      {
        id: "s2-2-e4",
        promptFr: "Un sac contient 3 billes rouges et 7 billes bleues. Quelle est la probabilité de tirer une bille rouge ?",
        type: "short_text",
        acceptable: ["3/10", "0,3", "0.3", "30%"],
      },
      {
        id: "s2-2-e5",
        promptFr: "La probabilité d'un événement A est 0,4. Quelle est la probabilité que A ne se réalise pas ?",
        type: "short_text",
        acceptable: ["0,6", "0.6", "3/5", "60%"],
      },
    ],
  },
  {
    submoduleId: "S2-3",
    submoduleCode: "S2.3",
    theory: {
      title: {
        fr: "Événement complémentaire",
        en: "Complementary Event",
        ar: "الحادثة المكملة",
        fa: "رویداد مکمل",
        ti: "ተዛማዲ ፍጻሜ",
        uk: "Доповнення події",
      },
      paragraphs: {
        fr: [
          "L'événement complémentaire de A, noté Ā ou A', est l'événement qui se réalise exactement quand A ne se réalise pas.",
          "Propriété fondamentale : P(A) + P(Ā) = 1, donc P(Ā) = 1 − P(A).",
          "Exemple : si P(pluie demain) = 0,3, alors P(pas de pluie demain) = 1 − 0,3 = 0,7.",
          "Utilité pratique : parfois il est plus facile de calculer P(Ā) et d'en déduire P(A) = 1 − P(Ā). C'est la méthode du complémentaire.",
          "Exemple d'application : P(obtenir au moins un 6 en lançant deux dés) = 1 − P(aucun 6) = 1 − (5/6)² = 1 − 25/36 = 11/36.",
        ],
        en: [
          "The complementary event of A, written Ā or A', occurs exactly when A does not occur.",
          "Fundamental property: P(A) + P(Ā) = 1, so P(Ā) = 1 − P(A).",
          "Example: if P(rain tomorrow) = 0.3, then P(no rain tomorrow) = 1 − 0.3 = 0.7.",
          "Practical use: sometimes it is easier to calculate P(Ā) and deduce P(A) = 1 − P(Ā). This is the complementary method.",
          "Application: P(at least one 6 in two dice rolls) = 1 − P(no 6) = 1 − (5/6)² = 11/36.",
        ],
        ar: [
          "الحادثة المكملة لـ A، ترمز إليها Ā، هي الحادثة التي تتحقق تمامًا حين لا تتحقق A.",
          "الخاصية الأساسية: P(A) + P(Ā) = 1، إذن P(Ā) = 1 − P(A).",
          "مثال: إذا كان P(مطر غدًا) = 0,3 فـ P(لا مطر) = 0,7.",
          "الفائدة: أحيانًا حساب P(Ā) أسهل ثم استنتاج P(A) = 1 − P(Ā).",
          "مثال: P(الحصول على 6 واحد على الأقل برميتين) = 1 − (5/6)² = 11/36.",
        ],
        fa: [
          "رویداد مکمل A، که با Ā نشان داده می‌شود، دقیقاً زمانی رخ می‌دهد که A رخ ندهد.",
          "ویژگی بنیادی: P(A) + P(Ā) = ۱، پس P(Ā) = ۱ − P(A).",
          "مثال: اگر P(باران فردا) = ۰٫۳ باشد، P(بدون باران) = ۰٫۷.",
          "کاربرد عملی: گاهی محاسبه P(Ā) آسان‌تر است و سپس P(A) = ۱ − P(Ā) به دست می‌آید.",
          "مثال: P(حداقل یک ۶ در دو تاس) = ۱ − (۵/۶)² = ۱۱/۳۶.",
        ],
        ti: [
          "ናይ A ተዛማዲ ፍጻሜ፣ Ā ዝበሃል፣ ብትኽክል ምስ A ዘይካኣል ጊዜ ዝካኣል ፍጻሜ እዩ።",
          "መሰረታዊ ባህሪ: P(A) + P(Ā) = 1, ስለዚ P(Ā) = 1 − P(A).",
          "ኣብነት: P(ናይ ጽባሕ ዝናብ) = 0,3 ምስ ዝኾን P(ዝናብ የለ) = 0,7.",
          "ምጥቃም: ሓደ ሓደ ጊዜ P(Ā) ምሕሳብ ቀሊል እዩ ድሕሪኡ P(A) = 1 − P(Ā) ትርኢ።",
          "ኣብነት: P(ሓደ ወይ ልዕሊ ሓደ 6 ኣብ ክልተ ቀለዓ) = 1 − (5/6)² = 11/36.",
        ],
        uk: [
          "Доповнення події A, позначається Ā або A', — це подія, яка відбувається саме тоді, коли A не відбувається.",
          "Основна властивість: P(A) + P(Ā) = 1, тому P(Ā) = 1 − P(A).",
          "Приклад: якщо P(дощ завтра) = 0,3, то P(без дощу) = 0,7.",
          "Практичне застосування: іноді легше обчислити P(Ā) і звідси вивести P(A) = 1 − P(Ā).",
          "Приклад: P(хоча б одна 6 при двох кидках) = 1 − (5/6)² = 11/36.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-3-e1",
        promptFr: "P(A) = 0,35. Quelle est la probabilité de l'événement complémentaire Ā ?",
        type: "short_text",
        acceptable: ["0,65", "0.65"],
      },
      {
        id: "s2-3-e2",
        promptFr: "On lance un dé. P(obtenir 1 ou 2) = 1/3. Quelle est P(ne pas obtenir 1 ni 2) ?",
        type: "short_text",
        acceptable: ["2/3"],
      },
      {
        id: "s2-3-e3",
        promptFr: "P(Ā) = 3/8. Quelle est la valeur de P(A) ?",
        type: "short_text",
        acceptable: ["5/8"],
      },
      {
        id: "s2-3-e4",
        promptFr: "Complète : P(A) + P(Ā) = ___.",
        type: "number",
        acceptable: ["1"],
      },
      {
        id: "s2-3-e5",
        promptFr: "Un sac contient 4 billes rouges et 6 billes bleues. Quelle est la probabilité de ne PAS tirer une bille bleue ?",
        type: "short_text",
        acceptable: ["4/10", "2/5", "0,4", "0.4", "40%"],
      },
    ],
  },
  {
    submoduleId: "S2-4",
    submoduleCode: "S2.4",
    theory: {
      title: {
        fr: "Événements impossibles et certains",
        en: "Impossible and Certain Events",
        ar: "الحوادث المستحيلة والمؤكدة",
        fa: "رویدادهای محال و قطعی",
        ti: "ዘይካኣሉን ዘይተርፉን ፍጻሜታት",
        uk: "Неможливі та достовірні події",
      },
      paragraphs: {
        fr: [
          "Un événement impossible est un événement qui ne peut jamais se réaliser. Sa probabilité est P(∅) = 0.",
          "Un événement certain est un événement qui se réalise toujours quelles que soient les conditions. Sa probabilité est P(Ω) = 1.",
          "Entre ces extrêmes, 0 < P(A) < 1 pour tout événement ni impossible ni certain.",
          "Exemples : P(obtenir un 7 avec un dé à 6 faces) = 0 (impossible). P(obtenir un nombre entre 1 et 6 avec un dé à 6 faces) = 1 (certain).",
          "Sur une droite des probabilités : 0 (impossible) — 0,5 (aussi probable qu'improbable) — 1 (certain). Plus P(A) est proche de 1, plus l'événement est probable.",
        ],
        en: [
          "An impossible event can never occur. Its probability is P(∅) = 0.",
          "A certain event always occurs regardless of conditions. Its probability is P(Ω) = 1.",
          "For any event that is neither impossible nor certain: 0 < P(A) < 1.",
          "Examples: P(rolling a 7 with a 6-sided die) = 0 (impossible). P(rolling a number between 1 and 6) = 1 (certain).",
          "On a probability number line: 0 (impossible) — 0.5 (equally likely/unlikely) — 1 (certain).",
        ],
        ar: [
          "الحادثة المستحيلة هي التي لا تتحقق أبدًا. احتمالها P(∅) = 0.",
          "الحادثة المؤكدة هي التي تتحقق دائمًا. احتمالها P(Ω) = 1.",
          "لأي حادثة غير مستحيلة وغير مؤكدة: 0 < P(A) < 1.",
          "أمثلة: P(الحصول على 7 برمي نرد) = 0. P(الحصول على رقم بين 1 و6) = 1.",
          "على مستقيم الاحتمالات: 0 (مستحيل) — 0,5 — 1 (مؤكد).",
        ],
        fa: [
          "رویداد محال رویدادی است که هرگز نمی‌تواند رخ دهد. احتمال آن P(∅) = ۰ است.",
          "رویداد قطعی رویدادی است که همیشه رخ می‌دهد. احتمال آن P(Ω) = ۱ است.",
          "برای هر رویداد که نه محال است و نه قطعی: ۰ < P(A) < ۱.",
          "مثال‌ها: P(دیدن ۷ با تاس ۶ وجهی) = ۰. P(دیدن عددی بین ۱ و ۶) = ۱.",
          "روی خط احتمال: ۰ (محال) — ۰٫۵ (یکسان) — ۱ (قطعی).",
        ],
        ti: [
          "ዘይካኣል ፍጻሜ ፈጺሙ ዘይካኣል ፍጻሜ እዩ። ዕድሉ P(∅) = 0.",
          "ዘይተርፍ ፍጻሜ ኩሉ ጊዜ ዝካኣል ፍጻሜ እዩ። ዕድሉ P(Ω) = 1.",
          "ንዝኾነ ፍጻሜ ዘይካኣልን ዘይተርፍን: 0 < P(A) < 1.",
          "ኣብነታት: P(7 ምርካብ ብ6-ሸነኽ ቀለዓ) = 0. P(1 ናብ 6 ዘሎ ቁጽሪ ምርካብ) = 1.",
          "ኣብ ናይ ዕድል ቐጥታ: 0 (ዘይካኣል) — 0,5 — 1 (ዘይተርፍ).",
        ],
        uk: [
          "Неможлива подія — подія, яка ніколи не може відбутися. Її імовірність P(∅) = 0.",
          "Достовірна подія — подія, яка завжди відбувається. Її імовірність P(Ω) = 1.",
          "Для будь-якої події, що не є ні неможливою, ні достовірною: 0 < P(A) < 1.",
          "Приклади: P(випадіння 7 на кубику) = 0. P(випадіння числа від 1 до 6) = 1.",
          "На числовій шкалі імовірностей: 0 (неможлива) — 0,5 — 1 (достовірна).",
        ],
      },
    },
    exercises: [
      {
        id: "s2-4-e1",
        promptFr: "Quelle est la probabilité de l'événement impossible ?",
        type: "number",
        acceptable: ["0"],
      },
      {
        id: "s2-4-e2",
        promptFr: "Quelle est la probabilité de l'événement certain ?",
        type: "number",
        acceptable: ["1"],
      },
      {
        id: "s2-4-e3",
        promptFr: "On tire une boule d'un sac contenant uniquement 5 boules rouges. Quelle est la probabilité de tirer une boule verte ?",
        type: "number",
        acceptable: ["0"],
      },
      {
        id: "s2-4-e4",
        promptFr: "On tire une boule d'un sac contenant uniquement 5 boules rouges. Quelle est la probabilité de tirer une boule rouge ?",
        type: "number",
        acceptable: ["1"],
      },
      {
        id: "s2-4-e5",
        promptFr: "P(A) = 0,75. Cet événement est-il impossible, certain ou ni l'un ni l'autre ?",
        type: "short_text",
        acceptable: ["ni l'un ni l'autre", "ni impossible ni certain", "aucun des deux"],
      },
    ],
  },
  {
    submoduleId: "S2-5",
    submoduleCode: "S2.5",
    theory: {
      title: {
        fr: "Arbre de probabilité à deux étapes",
        en: "Two-Stage Probability Tree",
        ar: "مخطط الشجرة بمرحلتين",
        fa: "درخت احتمال دو مرحله‌ای",
        ti: "ክልተ-ምዕራፍ ናይ ዕድል ዕጨይቲ",
        uk: "Двоетапне дерево імовірностей",
      },
      paragraphs: {
        fr: [
          "Un arbre de probabilité modélise une expérience en plusieurs étapes. Chaque branche représente un résultat possible à cette étape avec sa probabilité.",
          "Règle du produit : la probabilité d'un chemin (suite de branches) est le produit des probabilités de chaque branche du chemin.",
          "Règle de la somme : si un événement peut se réaliser par plusieurs chemins (incompatibles), sa probabilité est la somme des probabilités de chacun de ces chemins.",
          "Exemple : on lance un dé puis une pièce. P(obtenir 6 ET face) = P(6) × P(face) = 1/6 × 1/2 = 1/12.",
          "Vérification : la somme des probabilités de tous les chemins finaux doit être égale à 1.",
        ],
        en: [
          "A probability tree models a multi-stage experiment. Each branch represents a possible outcome at that stage with its probability.",
          "Product rule: the probability of a path (sequence of branches) is the product of the probabilities on each branch.",
          "Sum rule: if an event can occur via several (mutually exclusive) paths, its probability is the sum of the probabilities of those paths.",
          "Example: roll a die then flip a coin. P(6 AND heads) = 1/6 × 1/2 = 1/12.",
          "Check: the probabilities of all final paths must sum to 1.",
        ],
        ar: [
          "مخطط الشجرة يُنمذج تجربة متعددة المراحل. كل فرع يمثل نتيجة ممكنة في تلك المرحلة مع احتمالها.",
          "قاعدة الضرب: احتمال مسار (تسلسل فروع) = حاصل ضرب احتمالات كل فرع.",
          "قاعدة الجمع: إذا تحققت حادثة بعدة مسارات (متنافية) فاحتمالها = مجموع احتمالات تلك المسارات.",
          "مثال: رمي نرد ثم قلب عملة. P(6 و صورة) = 1/6 × 1/2 = 1/12.",
          "التحقق: مجموع احتمالات جميع المسارات النهائية = 1.",
        ],
        fa: [
          "درخت احتمال یک آزمایش چندمرحله‌ای را مدل می‌کند. هر شاخه یک نتیجه ممکن در آن مرحله با احتمالش را نشان می‌دهد.",
          "قانون ضرب: احتمال یک مسیر (دنباله‌ای از شاخه‌ها) برابر حاصل‌ضرب احتمال‌های هر شاخه است.",
          "قانون جمع: اگر یک رویداد از چند مسیر (ناسازگار) قابل تحقق باشد، احتمالش برابر مجموع احتمال‌های آن مسیرها است.",
          "مثال: انداختن تاس سپس سکه. P(۶ و شیر) = ۱/۶ × ۱/۲ = ۱/۱۲.",
          "بررسی: مجموع احتمال‌های همه مسیرهای نهایی باید برابر ۱ باشد.",
        ],
        ti: [
          "ናይ ዕድል ዕጨይቲ ናይ ብዙሕ-ምዕራፍ ፈተነ ሞዴል ይገብር። ነፍሲ ወከፍ ቅርንጫፍ ኣብቲ ምዕራፍ ዝካኣል ውጽኢት ምስ ዕድሉ ይሕብር።",
          "ሕጊ ናይ ማባዛሕ: ናይ ሓደ ምዕዳዊ (ዘዋሃሃዱ ቅርናጫፋት) ዕድሉ = ናይ ነፍሲ ወከፍ ቅርንጫፍ ዕድሎም ማባዛሕ እዩ።",
          "ሕጊ ናይ ድምር: ፍጻሜ ብብዙሕ (ዘይጸጋዓፍ) ምዕዳዊ ዝካኣል ምስ ዝኾን ዕድሉ ናይ ምዕዳዊ ዕድሎም ድምር እዩ።",
          "ኣብነት: ቀለዓ ድሕሪ ሳንቲም ምድርባይ. P(6 ን ርእሲ) = 1/6 × 1/2 = 1/12.",
          "ምምርምር: ናይ ዘለው ናይ መጨረሻ ምዕዳዊ ዕድሎም ድምር = 1 ክኸውን ኣለዎ።",
        ],
        uk: [
          "Дерево імовірностей моделює багатоетапний дослід. Кожна гілка представляє можливий результат на цьому етапі з його імовірністю.",
          "Правило добутку: імовірність шляху (послідовності гілок) — це добуток імовірностей кожної гілки.",
          "Правило суми: якщо подія може відбутися кількома (несумісними) шляхами, її імовірність — сума імовірностей цих шляхів.",
          "Приклад: кидаємо кубик, потім монету. P(6 І орел) = 1/6 × 1/2 = 1/12.",
          "Перевірка: сума імовірностей усіх кінцевих шляхів має дорівнювати 1.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-5-e1",
        promptFr: "On lance deux pièces équilibrées. Quelle est la probabilité d'obtenir deux fois face ?",
        type: "short_text",
        acceptable: ["1/4", "0,25", "0.25"],
      },
      {
        id: "s2-5-e2",
        promptFr: "On lance un dé puis une pièce. Quelle est la probabilité d'obtenir un 6 ET pile ?",
        type: "short_text",
        acceptable: ["1/12"],
      },
      {
        id: "s2-5-e3",
        promptFr: "Avec deux pièces équilibrées, quelle est la probabilité d'obtenir exactement une face (une face et un pile) ?",
        type: "short_text",
        acceptable: ["1/2", "2/4", "0,5", "0.5"],
      },
      {
        id: "s2-5-e4",
        promptFr: "Dans un arbre à deux étapes, toutes les probabilités des chemins finaux sont : 1/6, 2/6, 1/6, 2/6. Quelle est leur somme ?",
        type: "number",
        acceptable: ["1"],
      },
      {
        id: "s2-5-e5",
        promptFr: "On tire deux fois une bille d'un sac (avec remise) qui contient 3 rouges et 7 bleues. Quelle est la probabilité d'obtenir deux billes rouges ?",
        type: "short_text",
        acceptable: ["9/100", "0,09", "0.09"],
      },
    ],
  },
  {
    submoduleId: "S2-6",
    submoduleCode: "S2.6",
    theory: {
      title: {
        fr: "Simulation et fréquences",
        en: "Simulation and Frequencies",
        ar: "المحاكاة والتكرارات",
        fa: "شبیه‌سازی و فراوانی‌ها",
        ti: "ምምስሳል ን ድርጊታት",
        uk: "Симуляція та частоти",
      },
      paragraphs: {
        fr: [
          "La simulation consiste à réaliser une expérience aléatoire un grand nombre de fois (réellement ou à l'aide d'un logiciel) pour estimer des probabilités.",
          "Fréquence relative observée : f(A) = (nombre de fois où A s'est réalisé) / (nombre total d'essais). Cette fréquence est une estimation de P(A).",
          "Loi des grands nombres : plus le nombre d'essais est grand, plus la fréquence relative se rapproche de la probabilité théorique.",
          "Exemple : on lance une pièce 100 fois et on obtient 48 fois face. La fréquence observée est 48/100 = 0,48. La probabilité théorique est 0,5 — elles sont proches.",
          "Les simulations peuvent être réalisées avec un dé, des cartes, un tableur (fonction ALEA) ou un logiciel de statistiques.",
        ],
        en: [
          "Simulation involves repeating a random experiment a large number of times (physically or with software) to estimate probabilities.",
          "Observed relative frequency: f(A) = (number of times A occurred) / (total number of trials). This frequency estimates P(A).",
          "Law of Large Numbers: the more trials, the closer the relative frequency gets to the theoretical probability.",
          "Example: flip a coin 100 times, get heads 48 times. Observed frequency = 48/100 = 0.48. Theoretical probability = 0.5 — they are close.",
          "Simulations can use dice, cards, a spreadsheet (RAND function) or statistics software.",
        ],
        ar: [
          "المحاكاة تقوم بتكرار التجربة العشوائية مرات عديدة (فعليًا أو ببرنامج) لتقدير الاحتمالات.",
          "التكرار النسبي الملاحَظ: f(A) = عدد مرات تحقق A / مجموع التجارب. هذا التكرار تقدير لـ P(A).",
          "قانون الأعداد الكبيرة: كلما زادت التجارب اقترب التكرار النسبي من الاحتمال النظري.",
          "مثال: قلب عملة 100 مرة، ظهور صورة 48 مرة. التكرار = 0,48. الاحتمال النظري = 0,5.",
          "يمكن إجراء المحاكاة بالنرد أو الأوراق أو جدول إلكتروني (دالة ALEA).",
        ],
        fa: [
          "شبیه‌سازی شامل تکرار یک آزمایش تصادفی برای تعداد زیادی بار (به صورت واقعی یا با نرم‌افزار) برای تخمین احتمال‌ها است.",
          "فراوانی نسبی مشاهده‌شده: f(A) = تعداد دفعاتی که A رخ داده / تعداد کل آزمایش‌ها. این فراوانی تخمینی از P(A) است.",
          "قانون اعداد بزرگ: هرچه تعداد آزمایش‌ها بیشتر باشد، فراوانی نسبی به احتمال نظری نزدیک‌تر می‌شود.",
          "مثال: سکه را ۱۰۰ بار می‌اندازیم و ۴۸ بار شیر می‌آید. فراوانی مشاهده‌شده = ۰٫۴۸. احتمال نظری = ۰٫۵.",
          "شبیه‌سازی‌ها می‌توانند با تاس، کارت، صفحه گسترده (تابع RAND) یا نرم‌افزار آمار انجام شوند.",
        ],
        ti: [
          "ምምስሳል ናይ ዕድል ፈተነ ብዙሕ ጊዜ ምድጋም (ኣካላዊ ወይ ብሶፍትዌር) ናይ ዕድሎ ምግምጋም ማለት እዩ።",
          "ዝተዓዘበ ዝምድናዊ ድርጊት: f(A) = ናይ A ዝካኣለ ጊዜ ቁጽሪ / ጠቅላላ ፈተናታት. እዚ ናይ P(A) ምግምጋም እዩ።",
          "ሕጊ ናይ ዓብዪ ቁጽሪ: ፈተናታት ብዝዛየዱ ዝምድናዊ ድርጊት ናብ ናይ ሓሳብ ዕድሊ ቀሪቡ ይኸይድ።",
          "ኣብነት: ሳንቲም 100 ጊዜ ምድርባይ፣ 48 ጊዜ ርእሲ ምርካብ. f = 48/100 = 0,48. ናይ ሓሳብ ዕድሊ = 0,5.",
          "ምምስሳልን ብቀለዓ፣ ካርዳት፣ ሌኪ (ALEA ተርእዮ) ወይ ናይ ስታቲስቲክስ ሶፍትዌር ክፍጸም ይኽእል።",
        ],
        uk: [
          "Симуляція полягає у багатократному повторенні випадкового досліду (реально або з програмою) для оцінки імовірностей.",
          "Спостережена відносна частота: f(A) = (кількість разів, коли A відбулась) / (загальна кількість спроб). Це оцінка P(A).",
          "Закон великих чисел: що більше спроб, то ближча відносна частота до теоретичної імовірності.",
          "Приклад: підкидаємо монету 100 разів, отримуємо орел 48 разів. f = 0,48. Теоретична імовірність = 0,5 — значення близькі.",
          "Симуляції можна проводити за допомогою кубика, карт, електронної таблиці (функція RAND) або статистичного програмного забезпечення.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-6-e1",
        promptFr: "On lance une pièce 200 fois et on obtient 94 fois pile. Quelle est la fréquence relative de 'pile' ?",
        type: "short_text",
        acceptable: ["94/200", "47/100", "0,47", "0.47"],
      },
      {
        id: "s2-6-e2",
        promptFr: "On lance un dé 600 fois et on obtient un 6 exactement 95 fois. La fréquence observée de '6' est-elle proche de la probabilité théorique 1/6 ≈ 0,167 ? Réponds par oui ou non.",
        type: "short_text",
        acceptable: ["oui", "Oui", "OUI"],
      },
      {
        id: "s2-6-e3",
        promptFr: "Après 1000 lancers d'un dé équilibré, environ combien de fois devrait-on obtenir un 3 ?",
        type: "short_text",
        acceptable: ["167", "166", "about 167", "environ 167"],
      },
      {
        id: "s2-6-e4",
        promptFr: "Qu'est-ce que la loi des grands nombres nous dit sur la fréquence relative quand le nombre d'essais augmente ?",
        type: "short_text",
        acceptable: [
          "elle se rapproche de la probabilité théorique",
          "elle converge vers la probabilité",
          "elle tend vers la probabilité",
        ],
      },
      {
        id: "s2-6-e5",
        promptFr: "On observe que sur 500 essais, la fréquence de l'événement A est 0,32. Quelle est ton estimation de P(A) ?",
        type: "short_text",
        acceptable: ["0,32", "0.32", "32%", "32 %"],
      },
    ],
  },
  {
    submoduleId: "S2-7",
    submoduleCode: "S2.7",
    theory: {
      title: {
        fr: "Introduction aux combinaisons",
        en: "Introduction to Combinations",
        ar: "مقدمة في التوافيق",
        fa: "مقدمه‌ای بر ترکیب‌ها",
        ti: "መፈለምታ ናይ ጥምረታት",
        uk: "Вступ до комбінацій",
      },
      paragraphs: {
        fr: [
          "Dénombrer les résultats possibles d'une expérience est essentiel pour calculer des probabilités classiques. Plus les résultats sont nombreux, plus on a besoin de méthodes systématiques.",
          "Principe multiplicatif : si une expérience se déroule en deux étapes indépendantes avec n₁ résultats possibles à la première et n₂ à la seconde, le nombre total de résultats possibles est n₁ × n₂.",
          "Exemple : on choisit un plat parmi 3 entrées et 4 desserts → 3 × 4 = 12 menus possibles. On lance 2 dés → 6 × 6 = 36 résultats possibles.",
          "Arrangement avec répétition de k objets parmi n : nᵏ résultats. Exemple : 3 chiffres de 0 à 9 (avec répétition) → 10³ = 1000 combinaisons.",
          "Combinaison (choix sans ordre ni répétition) de k éléments parmi n : C(n,k) = n! / (k! × (n−k)!). Exemple : choisir 2 élèves parmi 5 → C(5,2) = 10.",
        ],
        en: [
          "Counting possible outcomes of an experiment is essential for calculating classical probabilities. The more outcomes, the more systematic methods are needed.",
          "Multiplication principle: if an experiment has two independent stages with n₁ possible outcomes at stage 1 and n₂ at stage 2, the total number of outcomes is n₁ × n₂.",
          "Example: choose from 3 starters and 4 desserts → 3 × 4 = 12 possible menus. Roll 2 dice → 6 × 6 = 36 outcomes.",
          "Arrangement with repetition of k objects from n: nᵏ outcomes. Example: 3 digits from 0–9 (with repetition) → 10³ = 1000 combinations.",
          "Combination (unordered, without repetition) of k elements from n: C(n,k) = n! / (k! × (n−k)!). Example: choose 2 students from 5 → C(5,2) = 10.",
        ],
        ar: [
          "عدّ النتائج الممكنة أساسي لحساب الاحتمالات الكلاسيكية. كلما كثرت النتائج احتجنا إلى أساليب منهجية أكثر.",
          "مبدأ الضرب: إذا اشتملت التجربة على مرحلتين مستقلتين بـ n₁ نتيجة في الأولى و n₂ في الثانية، فالعدد الإجمالي = n₁ × n₂.",
          "مثال: اختيار من 3 مقبلات و4 حلويات → 3 × 4 = 12 قائمة. رمي نردين → 36 نتيجة.",
          "التنسيق بتكرار لـ k عنصر من n: nᵏ نتيجة. مثال: 3 أرقام من 0-9 → 10³ = 1000.",
          "التوافيق (اختيار بدون ترتيب أو تكرار) من k من n: C(n,k) = n! / (k! × (n−k)!). مثال: اختيار 2 طلاب من 5 → C(5,2) = 10.",
        ],
        fa: [
          "شمارش نتایج ممکن یک آزمایش برای محاسبه احتمال‌های کلاسیک ضروری است.",
          "اصل ضرب: اگر آزمایش دارای دو مرحله مستقل با n₁ نتیجه در مرحله اول و n₲ در مرحله دوم باشد، تعداد کل نتایج = n₁ × n₂.",
          "مثال: انتخاب از ۳ پیش‌غذا و ۴ دسر → ۳ × ۴ = ۱۲ منو. انداختن ۲ تاس → ۶ × ۶ = ۳۶ نتیجه.",
          "چینش با تکرار k شیء از n: nᵏ نتیجه. مثال: ۳ رقم از ۰–۹ (با تکرار) → ۱۰³ = ۱۰۰۰.",
          "ترکیب (بدون ترتیب و بدون تکرار) k عنصر از n: C(n,k) = n! / (k! × (n−k)!). مثال: انتخاب ۲ دانش‌آموز از ۵ → C(5,2) = 10.",
        ],
        ti: [
          "ናይ ፈተነ ክኾኑ ዝኽእሉ ውጽኢታት ምቑጻር ናይ ክላሲካዊ ዕድሎ ምሕሳብ ኣድላዪ እዩ።",
          "ሕጊ ናይ ማባዛሕ: ፈተነ ብክልተ ናጻ ምዕራፋት ምስ ዝህሉ n₁ ኣብ ቀዳምን n₂ ኣብ ካልኣይን ጠቅላላ ውጽኢታት = n₁ × n₂.",
          "ኣብነት: ካብ 3 ቀዳሞት ምዕሶ 4 ጣፍ ምምራጽ → 3 × 4 = 12 ዝዕቐናዉ ሜኑ. ክልተ ቀለዓ ምድርባይ → 36 ውጽኢታት.",
          "ምስ ድግሚ k ካብ n ምልቃቕ: nᵏ ውጽኢታት. ኣብነት: 3 ቁጽርታት ካብ 0-9 → 10³ = 1000.",
          "ጥምረታት (ካብ k ናብ n ብዘይ ስርዓትን ድግሚን): C(n,k) = n! / (k! × (n−k)!). ኣብነት: 2 ተምሃሮ ካብ 5 → C(5,2) = 10.",
        ],
        uk: [
          "Підрахунок можливих результатів досліду є основою для обчислення класичних імовірностей.",
          "Принцип множення: якщо дослід має два незалежні етапи з n₁ результатами на першому та n₂ на другому, загальна кількість результатів = n₁ × n₂.",
          "Приклад: вибір із 3 закусок і 4 десертів → 3 × 4 = 12 меню. Кидання 2 кубиків → 36 результатів.",
          "Розміщення з повторенням k об'єктів із n: nᵏ результатів. Приклад: 3 цифри з 0–9 → 10³ = 1000.",
          "Комбінація (вибір без порядку і повторень) k елементів із n: C(n,k) = n! / (k! × (n−k)!). Приклад: вибрати 2 учнів із 5 → C(5,2) = 10.",
        ],
      },
    },
    exercises: [
      {
        id: "s2-7-e1",
        promptFr: "Un restaurant propose 4 plats et 3 desserts. Combien de repas différents (plat + dessert) peut-on former ?",
        type: "number",
        acceptable: ["12"],
      },
      {
        id: "s2-7-e2",
        promptFr: "On lance 2 dés à 6 faces. Combien de résultats possibles y a-t-il au total ?",
        type: "number",
        acceptable: ["36"],
      },
      {
        id: "s2-7-e3",
        promptFr: "Un code PIN contient 4 chiffres (0 à 9) avec répétition autorisée. Combien de codes différents existent ?",
        type: "number",
        acceptable: ["10000"],
      },
      {
        id: "s2-7-e4",
        promptFr: "On veut choisir 2 élèves parmi 5 pour représenter la classe. Combien de façons différentes y a-t-il ? (C(5,2) = ?)",
        type: "number",
        acceptable: ["10"],
      },
      {
        id: "s2-7-e5",
        promptFr: "On tire 2 billes (sans remise) d'un sac de 4 billes distinctes. Combien de paires différentes peut-on obtenir ? (C(4,2) = ?)",
        type: "number",
        acceptable: ["6"],
      },
    ],
  },
];
