import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A1_1: SubmoduleTrad = {
  submoduleId: "A1-1",
  title: {
    fr: "Compter en français",
    en: "Counting in French",
    ar: "العد بالفرنسية",
    fa: "شمارش به فرانسوی",
    ti: "ምቑጻር ብፈረንሳይ",
    uk: "Лічба французькою",
    pt: "Contar em francês",
    so: "Tirinta Faransiiska",
    tr: "Fransizca sayma",
    ps: "په فرانسوي کې شمېرل",
  },
  paragraphs: {
    fr: [
      "Un nombre entier s'écrit avec des chiffres (0 à 9).",
      "En français, on sépare souvent les milliers par une espace fine : 125 000.",
      "En Suisse romande, on utilise souvent septante, huitante et nonante pour 70, 80 et 90.",
    ],
    en: [
      "A whole number is written with digits (0 to 9).",
      "In French, thousands are often separated by a thin space: 125 000.",
      "In French-speaking Switzerland, people often say septante, huitante and nonante for 70, 80 and 90.",
    ],
    ar: [
      "نكتب العدد الصحيح بأرقام من 0 إلى 9.",
      "في الفرنسية، نفصل الآلاف أحيانًا بمسافة رفيعة : 125 000.",
      "في الروماندي السويسري يقال غالبًا septante وhuitante وnonante لـ 70 و80 و90.",
    ],
    fa: [
      "عدد صحیح را با ارقام ۰ تا ۹ می‌نویسیم.",
      "در فرانسوی، هزارگان را گاه با فاصلهٔ ظریف جدا می‌کنند: ۱۲۵ ۰۰۰.",
      "در سوئیس رماند معمولاً برای ۷۰ و ۸۰ و ۹۰ می‌گویند septante، huitante، nonante.",
    ],
    ti: [
      "ኣኃዝቲ ብኣሃዝቲ 0-9 ይጽዓን።",
      "ኣብ ፈረንሳይ ሽሕታት ብልዝብ ክፈልጹ ይኽእሉ።",
      "ኣብ ስዊዘርላንድ ብ 70-80-90 septante ፡ huitante ፡ nonante ይበሃሉ።",
    ],
    uk: [
      "Ціле число записують цифрами від 0 до 9.",
      "У французькій тисячі часто відокремлюють тонким пробілом: 125 000.",
      "У романській Швейцарії для 70, 80 і 90 часто кажуть septante, huitante, nonante.",
    ],
    pt: [
      "Um número inteiro é escrito com algarismos (0 a 9).",
      "Em francês, os milhares são frequentemente separados por um espaço fino: 125 000.",
      "Na Suíça francófona, usa-se frequentemente septante, huitante e nonante para 70, 80 e 90.",
    ],
    so: [
          "Tiro dhan waxaa lagu qoraa lambarro (0 ilaa 9).",
          "Faransiiska, kumannada badanaa waxaa lagu kala saaraa meel bannaan oo dhuuban: 125 000.",
          "Iswiiska Faransiiska lagaga hadlo, dadku badanaa waxay 70, 80 iyo 90 u yiraahdaan septante, huitante iyo nonante.",
        ],
    tr: [
          "Tam sayi rakamlarla yazilir (0 ile 9 arasi).",
          "Fransizcada binlikler cogu zaman ince bir boslukla ayrilir: 125 000.",
          "Fransizca konusulan Isvicre'de 70, 80 ve 90 icin sikca septante, huitante ve nonante denir.",
        ],
    ps: [
          "صحيح عدد د رقمونو په وسیله ليکل کېږي (له 0 تر 9).",
          "په فرانسوي کې زرګونه ډېر وخت په نري تش ځای بېلېږي: 125 000.",
          "د سويس په فرانسوي ژبو سيمه کې د 70، 80 او 90 لپاره ډېر وخت septante، huitante او nonante ويل کېږي.",
        ],
  },
  readAloud: {
    heading: {
      fr: "Enregistrement",
      en: "Recording",
      ar: "التسجيل",
      fa: "ضبط",
      ti: "ምዝገባ",
      uk: "Запис",
      pt: "Gravação",
      so: "Duubis",
      tr: "Kayit",
      ps: "ثبت",
    },
    legend: [
      {
        swatch: "red",
        label: {
          fr: "Rouge : un seul son",
          en: "Red: one sound",
          ar: "أحمر: صوت واحد",
          fa: "قرمز: یک صدا",
          uk: "Червоний: один звук",
          ti: "ቀይሕ: ሓደ ድምጺ",
          pt: "Vermelho: um som",
          so: "Casaan: hal cod",
          tr: "Kirmizi: tek ses",
          ps: "سور: يو غږ",
        },
      },
      {
        swatch: "text",
        label: {
          fr: "Noir : son",
          en: "Black: sound",
          ar: "أسود: صوت",
          fa: "سیاه: صدا",
          uk: "Чорний: звук",
          ti: "ጸሊም: ድምጺ",
          pt: "Preto: som",
          so: "Madow: cod",
          tr: "Siyah: ses",
          ps: "تور: غږ",
        },
      },
      {
        swatch: "gray",
        label: {
          fr: "Gris : pas de son",
          en: "Gray: silent",
          ar: "رمادي: بدون صوت",
          fa: "خاکستری: بی‌صدا",
          uk: "Сірий: без звуку",
          ti: "ሕምብርቲ: ድምጺ የብሉን",
          pt: "Cinza: sem som",
          so: "Cawl: cod la'aan",
          tr: "Gri: sessiz",
          ps: "خړ: بې غږه",
        },
      },
    ],
  },
};
