import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A7_3: SubmoduleTrad = {
  submoduleId: "A7-3",
  title: {
    fr: "Addition et soustraction de nombres relatifs",
    en: "Addition and subtraction of relative integers",
    ar: "جمع وطرح الأعداد الصحيحة النسبية",
    fa: "جمع و تفریق عددهای صحیح نسبی",
    pt: "Adição e subtração de inteiros relativos",
    so: "Isugeyn iyo kala-goyn tirooyin xiriir leh",
    ti: "ምድማርን ምጉዳልን ተዛማዲ ሙሉእ ቁጽርታት",
    tr: "İşaretli tam sayılarda toplama ve çıkarma",
    ps: "د نسبي صحيح عددونو جمع او تفريق",
    uk: "Додавання і віднімання відносних цілих чисел",
  },
  blocks: [
    { text: { fr: "Addition des nombres relatifs", en: "Adding relative integers", ar: "جمع الأعداد الصحيحة النسبية", fa: "جمع عددهای صحیح نسبی", pt: "Adicionar inteiros relativos", so: "Isugeynta tirooyinka xiriirka leh", ti: "ተዛማዲ ሙሉእ ቁጽርታት ምድማር", tr: "İşaretli tam sayıları toplama", ps: "د نسبي صحيح عددونو جمع", uk: "Додавання відносних цілих чисел" } },
    { text: { fr: "Mêmes signes → conserver le signe", en: "Same signs → keep the sign", ar: "الإشارات نفسها → نحتفظ بالإشارة", fa: "علامت های یکسان → همان علامت را نگه دار", pt: "Sinais iguais → conservar o sinal", so: "Calaamado isku mid ah → hay calaamadda", ti: "ሓደ ዓይነት ምልክታት → ምልክት ዓቅብ", tr: "Aynı işaretler → işareti koru", ps: "يو شان نښې → نښه وساته", uk: "Однакові знаки → зберегти знак" } },
    {
      items: {
        fr: ["Additionner les valeurs absolues et conserver le signe commun.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        en: ["Add the absolute values and keep the common sign.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        ar: ["نجمع القيم المطلقة ونحتفظ بالإشارة المشتركة.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        fa: ["قدر مطلق ها را جمع کن و علامت مشترک را نگه دار.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        pt: ["Somar os valores absolutos e conservar o sinal comum.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        so: ["Isku dar qiimayaasha mutlaq ah, calaamadda guudna hay.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        ti: ["ፍጹም ዋጋታት ደምር፡ ሓባራዊ ምልክት ድማ ዓቅብ።", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        tr: ["Mutlak değerleri topla ve ortak işareti koru.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        ps: ["مطلق ارزښتونه جمع کړه او ګډه نښه وساته.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
        uk: ["Додай абсолютні значення і збережи спільний знак.", "(+6) + (+3) = +9", "(−6) + (−3) = −9"],
      },
    },
    { text: { fr: "Signes contraires → signe du plus grand", en: "Opposite signs → sign of the larger absolute value", ar: "إشارات مختلفة → إشارة العدد ذي القيمة المطلقة الأكبر", fa: "علامت های مخالف → علامت عدد با قدر مطلق بزرگ تر", pt: "Sinais contrários → sinal do maior valor absoluto", so: "Calaamado kala duwan → calaamadda tirada qiimaheeda mutlaq ka weyn yahay", ti: "ተጻራሪ ምልክታት → ምልክት ናይ ዝዓበየ ፍጹም ዋጋ", tr: "Zıt işaretler → mutlak değeri büyük olanın işareti", ps: "مخالفې نښې → د لوی مطلق ارزښت نښه", uk: "Різні знаки → знак числа з більшим абсолютним значенням" } },
    {
      items: {
        fr: ["Soustraire les valeurs absolues et prendre le signe du nombre ayant la plus grande valeur absolue.", "(+6) + (−3) = +3   (|6| > |3| → signe +)", "(−6) + (+3) = −3   (|6| > |3| → signe −)"],
        en: ["Subtract the absolute values and take the sign of the number with the greater absolute value.", "(+6) + (−3) = +3   (|6| > |3| → + sign)", "(−6) + (+3) = −3   (|6| > |3| → − sign)"],
        ar: ["نطرح القيم المطلقة ونأخذ إشارة العدد ذي القيمة المطلقة الأكبر.", "(+6) + (−3) = +3   (|6| > |3| → إشارة +)", "(−6) + (+3) = −3   (|6| > |3| → إشارة −)"],
        fa: ["قدر مطلق ها را کم کن و علامت عددی را بگیر که قدر مطلق بزرگ تری دارد.", "(+6) + (−3) = +3   (|6| > |3| → علامت +)", "(−6) + (+3) = −3   (|6| > |3| → علامت −)"],
        pt: ["Subtrair os valores absolutos e usar o sinal do número com maior valor absoluto.", "(+6) + (−3) = +3   (|6| > |3| → sinal +)", "(−6) + (+3) = −3   (|6| > |3| → sinal −)"],
        so: ["Kala jar qiimayaasha mutlaq ah, qaadna calaamadda tirada qiimaheeda mutlaq ka weyn yahay.", "(+6) + (−3) = +3   (|6| > |3| → calaamad +)", "(−6) + (+3) = −3   (|6| > |3| → calaamad −)"],
        ti: ["ፍጹም ዋጋታት ጉድል፡ ምልክት ናይቲ ዝዓበየ ፍጹም ዋጋ ዘለዎ ቁጽሪ ውሰድ።", "(+6) + (−3) = +3   (|6| > |3| → ምልክት +)", "(−6) + (+3) = −3   (|6| > |3| → ምልክት −)"],
        tr: ["Mutlak değerleri çıkar ve mutlak değeri büyük olan sayının işaretini al.", "(+6) + (−3) = +3   (|6| > |3| → + işareti)", "(−6) + (+3) = −3   (|6| > |3| → − işareti)"],
        ps: ["مطلق ارزښتونه منفي کړه او د هغه عدد نښه واخله چې مطلق ارزښت يې لوی دی.", "(+6) + (−3) = +3   (|6| > |3| → + نښه)", "(−6) + (+3) = −3   (|6| > |3| → − نښه)"],
        uk: ["Відніми абсолютні значення і візьми знак числа з більшим абсолютним значенням.", "(+6) + (−3) = +3   (|6| > |3| → знак +)", "(−6) + (+3) = −3   (|6| > |3| → знак −)"],
      },
    },
    { text: { fr: "Soustraction des nombres relatifs", en: "Subtracting relative integers", ar: "طرح الأعداد الصحيحة النسبية", fa: "تفریق عددهای صحیح نسبی", pt: "Subtrair inteiros relativos", so: "Kala-goynta tirooyinka xiriirka leh", ti: "ተዛማዲ ሙሉእ ቁጽርታት ምጉዳል", tr: "İşaretli tam sayıları çıkarma", ps: "د نسبي صحيح عددونو تفريق", uk: "Віднімання відносних цілих чисел" } },
    {
      text: { fr: "Règle fondamentale", en: "Basic rule", ar: "القاعدة الأساسية", fa: "قاعده اصلی", pt: "Regra fundamental", so: "Xeerka aasaasiga ah", ti: "መሰረታዊ ሕጊ", tr: "Temel kural", ps: "بنسټيزه قاعده", uk: "Основне правило" },
      items: {
        fr: ["Soustraire un nombre revient à additionner son opposé.", "a − b = a + (−b)"],
        en: ["Subtracting a number means adding its opposite.", "a − b = a + (−b)"],
        ar: ["طرح عدد يعني جمع معاكسه.", "a − b = a + (−b)"],
        fa: ["کم کردن یک عدد یعنی جمع کردن قرینه آن.", "a − b = a + (−b)"],
        pt: ["Subtrair um número é o mesmo que adicionar o seu oposto.", "a − b = a + (−b)"],
        so: ["In tiro la jaro waxay la mid tahay in lidkeeda lagu daro.", "a − b = a + (−b)"],
        ti: ["ቁጽሪ ምጉዳል ማለት ተጻራሪኡ ምድማር ማለት እዩ።", "a − b = a + (−b)"],
        tr: ["Bir sayıyı çıkarmak, onun tersini eklemek demektir.", "a − b = a + (−b)"],
        ps: ["د يو عدد منفي کول يعنې د هغه مقابل جمع کول.", "a − b = a + (−b)"],
        uk: ["Відняти число означає додати протилежне до нього.", "a − b = a + (−b)"],
      },
    },
    { text: { fr: "Mêmes signes", en: "Same signs", ar: "إشارات متماثلة", fa: "علامت های یکسان", pt: "Sinais iguais", so: "Calaamado isku mid ah", ti: "ሓደ ዓይነት ምልክታት", tr: "Aynı işaretler", ps: "يو شان نښې", uk: "Однакові знаки" } },
    {},
    { text: { fr: "Signes contraires", en: "Opposite signs", ar: "إشارات مختلفة", fa: "علامت های مخالف", pt: "Sinais contrários", so: "Calaamado kala duwan", ti: "ተጻራሪ ምልክታት", tr: "Zıt işaretler", ps: "مخالفې نښې", uk: "Різні знаки" } },
    {},
    {
      text: {
        fr: "Méthode : transformer toujours la soustraction en addition de l'opposé, puis appliquer la règle d'addition.",
        en: "Method: always turn subtraction into addition of the opposite, then apply the addition rule.",
        ar: "الطريقة: حوّل الطرح دائما إلى جمع المعاكس، ثم طبّق قاعدة الجمع.",
        fa: "روش: همیشه تفریق را به جمع قرینه تبدیل کن، سپس قاعده جمع را به کار ببر.",
        pt: "Método: transformar sempre a subtração em adição do oposto e depois aplicar a regra da adição.",
        so: "Habka: mar walba kala-goynta u beddel isugeynta lidka, kadibna adeegso xeerka isugeynta.",
        ti: "ሜላ: ምጉዳል ኩሉ ግዜ ናብ ምድማር ተጻራሪ ቀይር፡ ድሕሪኡ ሕጊ ምድማር ተጠቐም።",
        tr: "Yöntem: çıkarmayı her zaman tersini eklemeye çevir, sonra toplama kuralını uygula.",
        ps: "طريقه: تفريق تل د مقابل په جمع بدل کړه، بيا د جمع قاعده وکاروه.",
        uk: "Метод: завжди перетворюй віднімання на додавання протилежного числа, а потім застосовуй правило додавання.",
      },
    },
  ],
};
