import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A3_4: SubmoduleTrad = {
  submoduleId: "A3-4",
  title: {
    fr: "Division en colonnes",
    en: "Column division",
    ar: "القسمة في الأعمدة",
    fa: "تقسیم ستونی",
    ti: "ምክፋል ብዓምዲ",
    uk: "Ділення у стовпчик",
    pt: "Divisão em colunas",
    so: "Qaybin tiirar",
    tr: "Alt alta bölme",
    ps: "ستوني وېش",
  },
  blocks: [
    {
      text: {
        fr: "La division en colonne permet de diviser de grands nombres en organisant les calculs **étape par étape**.",
        en: "Column division lets us divide large numbers by organizing the calculations **step by step**.",
        ar: "تساعد القسمة في الأعمدة على قسمة الأعداد الكبيرة بتنظيم الحسابات **خطوة بخطوة**.",
        fa: "تقسیم ستونی کمک می‌کند عددهای بزرگ را با سازمان‌دهی محاسبات **مرحله به مرحله** تقسیم کنیم.",
        ti: "ምክፋል ብዓምዲ ዓበይቲ ቁጽርታት **ብደረጃ ብደረጃ** ብምውዳብ ንምክፋል ይሕግዝ።",
        uk: "Ділення у стовпчик допомагає ділити великі числа, організовуючи обчислення **крок за кроком**.",
        pt: "A divisão em colunas permite dividir números grandes organizando os cálculos **passo a passo**.",
        so: "Qaybinta tiirarku waxay caawisaa in tirooyin waaweyn la qaybiyo iyadoo xisaabta loo habeeyo **tallaabo tallaabo**.",
        tr: "Alt alta bölme, büyük sayıları işlemleri **adım adım** düzenleyerek bölmeyi sağlar.",
        ps: "ستوني وېش د لویو عددونو وېش د حسابونو **ګام په ګام** تنظیمولو سره اسانه کوي.",
      },
    },
    {
      text: {
        fr: "Principe",
        en: "Principle",
        ar: "المبدأ",
        fa: "اصل",
        ti: "መርሕ",
        uk: "Принцип",
        pt: "Princípio",
        so: "Mabda'a",
        tr: "İlke",
        ps: "اصل",
      },
    },
    {
      items: {
        fr: [
          "On divise les chiffres du dividende de gauche à droite.",
          "À chaque étape : on cherche combien de fois le diviseur entre dans la valeur courante.",
          "On soustrait le produit et on abaisse le chiffre suivant.",
          "**Rappel :** dividende = diviseur × quotient + reste (reste < diviseur)",
        ],
        en: [
          "We divide the digits of the dividend from left to right.",
          "At each step: we find how many times the divisor fits into the current value.",
          "We subtract the product and bring down the next digit.",
          "**Reminder:** dividend = divisor × quotient + remainder (remainder < divisor)",
        ],
        ar: [
          "نقسم أرقام المقسوم من اليسار إلى اليمين.",
          "في كل خطوة: نبحث كم مرة يدخل المقسوم عليه في القيمة الحالية.",
          "نطرح الناتج وننزل الرقم التالي.",
          "**تذكير:** المقسوم = المقسوم عليه × خارج القسمة + الباقي (الباقي < المقسوم عليه)",
        ],
        fa: [
          "رقم‌های مقسوم را از چپ به راست تقسیم می‌کنیم.",
          "در هر مرحله: پیدا می‌کنیم مقسوم‌علیه چند بار در مقدار فعلی جا می‌شود.",
          "حاصل‌ضرب را کم می‌کنیم و رقم بعدی را پایین می‌آوریم.",
          "**یادآوری:** مقسوم = مقسوم‌علیه × خارج قسمت + باقی‌مانده (باقی‌مانده < مقسوم‌علیه)",
        ],
        ti: [
          "ኣሃዛት ዲቪደንድ ካብ ጸጋም ናብ የማን ንከፍል።",
          "ኣብ ነፍሲ ወከፍ ደረጃ፡ ዲቪዘር ኣብ ናይ ሕጂ ዋጋ ክንደይ ግዜ ከምዝኣቱ ንደሊ።",
          "ነቲ ፕሮዳክት ንቕንስ እሞ ነቲ ዝቕጽል ኣሃዝ ንወርድ።",
          "**መዘኻኸሪ:** ዲቪደንድ = ዲቪዘር × ኮሸንት + ተረፍ (ተረፍ < ዲቪዘር)",
        ],
        uk: [
          "Ділимо цифри діленого зліва направо.",
          "На кожному кроці шукаємо, скільки разів дільник міститься в поточному значенні.",
          "Віднімаємо добуток і зносимо наступну цифру.",
          "**Нагадування:** ділене = дільник × частка + остача (остача < дільник)",
        ],
        pt: [
          "Dividimos os algarismos do dividendo da esquerda para a direita.",
          "Em cada etapa: procuramos quantas vezes o divisor cabe no valor atual.",
          "Subtraímos o produto e baixamos o algarismo seguinte.",
          "**Lembrete:** dividendo = divisor × quociente + resto (resto < divisor)",
        ],
        so: [
          "Waxaan qaybinnaa lambarrada qaybsamaha bidix ilaa midig.",
          "Tallaabo kasta: waxaan raadinnaa inta jeer ee qaybiye ku jiro qiimaha hadda.",
          "Waxaan ka jareynaa taranta, kadibna hoos ayaan u soo dejinnaa lambarka xiga.",
          "**Xusuusin:** qaybsame = qaybiye × qayb + haraa (haraa < qaybiye)",
        ],
        tr: [
          "Bölünenin rakamlarını soldan sağa böleriz.",
          "Her adımda: bölenin mevcut değerin içine kaç kez sığdığını buluruz.",
          "Çarpımı çıkarır ve sonraki rakamı aşağı indiririz.",
          "**Hatırlatma:** bölünen = bölen × bölüm + kalan (kalan < bölen)",
        ],
        ps: [
          "د مقسوم رقمونه له کیڼ څخه ښي ته وېشو.",
          "په هر ګام کې: ګورو چې وېشونکی په اوسني ارزښت کې څو ځله ځایېږي.",
          "حاصل ضرب منفي کوو او بل رقم ښکته راولو.",
          "**یادونه:** مقسوم = وېشونکی × خارج قسمت + پاتې (پاتې < وېشونکی)",
        ],
      },
    },
    {
      text: {
        fr: "Division à 1 chiffre",
        en: "Division by 1 digit",
        ar: "القسمة على رقم واحد",
        fa: "تقسیم بر یک رقم",
        ti: "ምክፋል ብ1 ኣሃዝ",
        uk: "Ділення на 1 цифру",
        pt: "Divisão por 1 algarismo",
        so: "Qaybin hal lambar ah",
        tr: "1 basamaklı bölme",
        ps: "په 1 رقم وېش",
      },
    },
    {
      text: {
        fr: "6 385 ÷ 4",
        en: "6 385 ÷ 4",
        ar: "6 385 ÷ 4",
        fa: "6 385 ÷ 4",
        ti: "6 385 ÷ 4",
        uk: "6 385 ÷ 4",
        pt: "6 385 ÷ 4",
        so: "6 385 ÷ 4",
        tr: "6 385 ÷ 4",
        ps: "6 385 ÷ 4",
      },
    },
    {
      items: {
        en: [
          "1. Set up the numbers||Write the dividend 6 385 and the divisor 4.||Reserve the area on the right for the quotient.",
          "2. Thousands: 6 ÷ 4 = 1, remainder 2||6 ÷ 4 = 1 → write 1 in the quotient.||1 × 4 = 4 → subtract: 6 − 4 = 2.",
          "3. Hundreds: 23 ÷ 4 = 5, remainder 3||Bring down the 3: remainder 2 → 23.||23 ÷ 4 = 5 → write 5 in the quotient.||5 × 4 = 20 → subtract: 23 − 20 = 3.",
          "4. Tens: 38 ÷ 4 = 9, remainder 2||Bring down the 8: remainder 3 → 38.||38 ÷ 4 = 9 → write 9 in the quotient.||9 × 4 = 36 → subtract: 38 − 36 = 2.",
          "5. Units: 25 ÷ 4 = 6, remainder 1||Bring down the 5: remainder 2 → 25.||25 ÷ 4 = 6 → write 6 in the quotient.||6 × 4 = 24 → subtract: 25 − 24 = 1.||The remainder 1 < 4 (divisor) → we are done.||6 385 ÷ 4 = 1 596, remainder 1",
        ],
        uk: [
          "1. Записуємо числа||Записуємо ділене 6 385 і дільник 4.||Залишаємо місце праворуч для частки.",
          "2. Тисячі: 6 ÷ 4 = 1, остача 2||6 ÷ 4 = 1 → записуємо 1 у частку.||1 × 4 = 4 → віднімаємо: 6 − 4 = 2.",
          "3. Сотні: 23 ÷ 4 = 5, остача 3||Зносимо 3: остача 2 → 23.||23 ÷ 4 = 5 → записуємо 5 у частку.||5 × 4 = 20 → віднімаємо: 23 − 20 = 3.",
          "4. Десятки: 38 ÷ 4 = 9, остача 2||Зносимо 8: остача 3 → 38.||38 ÷ 4 = 9 → записуємо 9 у частку.||9 × 4 = 36 → віднімаємо: 38 − 36 = 2.",
          "5. Одиниці: 25 ÷ 4 = 6, остача 1||Зносимо 5: остача 2 → 25.||25 ÷ 4 = 6 → записуємо 6 у частку.||6 × 4 = 24 → віднімаємо: 25 − 24 = 1.||Остача 1 < 4 (дільник) → завершили.||6 385 ÷ 4 = 1 596, остача 1",
        ],
        ar: [
          "1. نضع الأعداد||نكتب المقسوم 6 385 والمقسوم عليه 4.||نترك المساحة على اليمين لخارج القسمة.",
          "2. الآلاف: 6 ÷ 4 = 1، الباقي 2||6 ÷ 4 = 1 → نكتب 1 في خارج القسمة.||1 × 4 = 4 → نطرح: 6 − 4 = 2.",
          "3. المئات: 23 ÷ 4 = 5، الباقي 3||ننزل 3: الباقي 2 → 23.||23 ÷ 4 = 5 → نكتب 5 في خارج القسمة.||5 × 4 = 20 → نطرح: 23 − 20 = 3.",
          "4. العشرات: 38 ÷ 4 = 9، الباقي 2||ننزل 8: الباقي 3 → 38.||38 ÷ 4 = 9 → نكتب 9 في خارج القسمة.||9 × 4 = 36 → نطرح: 38 − 36 = 2.",
          "5. الآحاد: 25 ÷ 4 = 6، الباقي 1||ننزل 5: الباقي 2 → 25.||25 ÷ 4 = 6 → نكتب 6 في خارج القسمة.||6 × 4 = 24 → نطرح: 25 − 24 = 1.||الباقي 1 < 4 (المقسوم عليه) → انتهينا.||6 385 ÷ 4 = 1 596، الباقي 1",
        ],
        fa: [
          "1. عددها را می‌نویسیم||مقسوم 6 385 و مقسوم‌علیه 4 را می‌نویسیم.||سمت راست را برای خارج قسمت نگه می‌داریم.",
          "2. هزارگان: 6 ÷ 4 = 1، باقیمانده 2||6 ÷ 4 = 1 → 1 را در خارج قسمت می‌نویسیم.||1 × 4 = 4 → کم می‌کنیم: 6 − 4 = 2.",
          "3. صدگان: 23 ÷ 4 = 5، باقیمانده 3||3 را پایین می‌آوریم: باقیمانده 2 → 23.||23 ÷ 4 = 5 → 5 را در خارج قسمت می‌نویسیم.||5 × 4 = 20 → کم می‌کنیم: 23 − 20 = 3.",
          "4. دهگان: 38 ÷ 4 = 9، باقیمانده 2||8 را پایین می‌آوریم: باقیمانده 3 → 38.||38 ÷ 4 = 9 → 9 را در خارج قسمت می‌نویسیم.||9 × 4 = 36 → کم می‌کنیم: 38 − 36 = 2.",
          "5. یکان: 25 ÷ 4 = 6، باقیمانده 1||5 را پایین می‌آوریم: باقیمانده 2 → 25.||25 ÷ 4 = 6 → 6 را در خارج قسمت می‌نویسیم.||6 × 4 = 24 → کم می‌کنیم: 25 − 24 = 1.||باقیمانده 1 < 4 (مقسوم‌علیه) → تمام شد.||6 385 ÷ 4 = 1 596، باقیمانده 1",
        ],
        pt: [
          "1. Colocamos os números||Escrevemos o dividendo 6 385 e o divisor 4.||Reservamos a zona à direita para o quociente.",
          "2. Milhares: 6 ÷ 4 = 1, resto 2||6 ÷ 4 = 1 → escrevemos 1 no quociente.||1 × 4 = 4 → subtraímos: 6 − 4 = 2.",
          "3. Centenas: 23 ÷ 4 = 5, resto 3||Baixamos o 3: resto 2 → 23.||23 ÷ 4 = 5 → escrevemos 5 no quociente.||5 × 4 = 20 → subtraímos: 23 − 20 = 3.",
          "4. Dezenas: 38 ÷ 4 = 9, resto 2||Baixamos o 8: resto 3 → 38.||38 ÷ 4 = 9 → escrevemos 9 no quociente.||9 × 4 = 36 → subtraímos: 38 − 36 = 2.",
          "5. Unidades: 25 ÷ 4 = 6, resto 1||Baixamos o 5: resto 2 → 25.||25 ÷ 4 = 6 → escrevemos 6 no quociente.||6 × 4 = 24 → subtraímos: 25 − 24 = 1.||O resto 1 < 4 (divisor) → terminámos.||6 385 ÷ 4 = 1 596, resto 1",
        ],
        so: [
          "1. Tirada dhig||Waxaan qornaa qaybsamaha 6 385 iyo qaybiye 4.||Meesha midigta waxaan u reebnaa qaybta.",
          "2. Kumanyaal: 6 ÷ 4 = 1, haraa 2||6 ÷ 4 = 1 → 1 waxaan ku qornaa qaybta.||1 × 4 = 4 → waan ka jareynaa: 6 − 4 = 2.",
          "3. Boqollaal: 23 ÷ 4 = 5, haraa 3||3 ayaan hoos u soo dejinnaa: haraa 2 → 23.||23 ÷ 4 = 5 → 5 waxaan ku qornaa qaybta.||5 × 4 = 20 → waan ka jareynaa: 23 − 20 = 3.",
          "4. Tobnaadyo: 38 ÷ 4 = 9, haraa 2||8 ayaan hoos u soo dejinnaa: haraa 3 → 38.||38 ÷ 4 = 9 → 9 waxaan ku qornaa qaybta.||9 × 4 = 36 → waan ka jareynaa: 38 − 36 = 2.",
          "5. Halal: 25 ÷ 4 = 6, haraa 1||5 ayaan hoos u soo dejinnaa: haraa 2 → 25.||25 ÷ 4 = 6 → 6 waxaan ku qornaa qaybta.||6 × 4 = 24 → waan ka jareynaa: 25 − 24 = 1.||Haraaga 1 < 4 (qaybiye) → waan dhammeennay.||6 385 ÷ 4 = 1 596, haraa 1",
        ],
        ti: [
          "1. ቁጽርታት ንቕምጥ||ዲቪደንድ 6 385ን ዲቪዘር 4ን ንጽሕፍ።||ኣብ የማን ንኮሸንት ቦታ ንሕዝ።",
          "2. ኣሽሓት: 6 ÷ 4 = 1፣ ተረፍ 2||6 ÷ 4 = 1 → 1 ኣብ ኮሸንት ንጽሕፍ።||1 × 4 = 4 → ንቕንስ: 6 − 4 = 2።",
          "3. ሚእትታት: 23 ÷ 4 = 5፣ ተረፍ 3||3 ንወርድ: ተረፍ 2 → 23።||23 ÷ 4 = 5 → 5 ኣብ ኮሸንት ንጽሕፍ።||5 × 4 = 20 → ንቕንስ: 23 − 20 = 3።",
          "4. ዓሰርተታት: 38 ÷ 4 = 9፣ ተረፍ 2||8 ንወርድ: ተረፍ 3 → 38።||38 ÷ 4 = 9 → 9 ኣብ ኮሸንት ንጽሕፍ።||9 × 4 = 36 → ንቕንስ: 38 − 36 = 2።",
          "5. ሓደታት: 25 ÷ 4 = 6፣ ተረፍ 1||5 ንወርድ: ተረፍ 2 → 25።||25 ÷ 4 = 6 → 6 ኣብ ኮሸንት ንጽሕፍ።||6 × 4 = 24 → ንቕንስ: 25 − 24 = 1።||ተረፍ 1 < 4 (ዲቪዘር) → ወዲእና።||6 385 ÷ 4 = 1 596፣ ተረፍ 1",
        ],
        tr: [
          "1. Sayıları yerleştiririz||Bölünen 6 385'i ve bölen 4'ü yazarız.||Sağ tarafı bölüm için ayırırız.",
          "2. Binler: 6 ÷ 4 = 1, kalan 2||6 ÷ 4 = 1 → bölüme 1 yazarız.||1 × 4 = 4 → çıkarırız: 6 − 4 = 2.",
          "3. Yüzler: 23 ÷ 4 = 5, kalan 3||3'ü aşağı indiririz: kalan 2 → 23.||23 ÷ 4 = 5 → bölüme 5 yazarız.||5 × 4 = 20 → çıkarırız: 23 − 20 = 3.",
          "4. Onlar: 38 ÷ 4 = 9, kalan 2||8'i aşağı indiririz: kalan 3 → 38.||38 ÷ 4 = 9 → bölüme 9 yazarız.||9 × 4 = 36 → çıkarırız: 38 − 36 = 2.",
          "5. Birler: 25 ÷ 4 = 6, kalan 1||5'i aşağı indiririz: kalan 2 → 25.||25 ÷ 4 = 6 → bölüme 6 yazarız.||6 × 4 = 24 → çıkarırız: 25 − 24 = 1.||Kalan 1 < 4 (bölen) → işlem bitti.||6 385 ÷ 4 = 1 596, kalan 1",
        ],
        ps: [
          "1. شمېرې ږدو||مقسوم 6 385 او وېشونکی 4 لیکو.||ښي خوا د خارج قسمت لپاره پرېږدو.",
          "2. زرګانې: 6 ÷ 4 = 1، پاتې 2||6 ÷ 4 = 1 → 1 په خارج قسمت کې لیکو.||1 × 4 = 4 → منفي کوو: 6 − 4 = 2.",
          "3. سلګانې: 23 ÷ 4 = 5، پاتې 3||3 ښکته راوړو: پاتې 2 → 23.||23 ÷ 4 = 5 → 5 په خارج قسمت کې لیکو.||5 × 4 = 20 → منفي کوو: 23 − 20 = 3.",
          "4. لسګانې: 38 ÷ 4 = 9، پاتې 2||8 ښکته راوړو: پاتې 3 → 38.||38 ÷ 4 = 9 → 9 په خارج قسمت کې لیکو.||9 × 4 = 36 → منفي کوو: 38 − 36 = 2.",
          "5. یوګانې: 25 ÷ 4 = 6، پاتې 1||5 ښکته راوړو: پاتې 2 → 25.||25 ÷ 4 = 6 → 6 په خارج قسمت کې لیکو.||6 × 4 = 24 → منفي کوو: 25 − 24 = 1.||پاتې 1 < 4 (وېشونکی) → کار پای ته ورسېد.||6 385 ÷ 4 = 1 596، پاتې 1",
        ],
      },
    },
  ],
  consignes: {
    divColumnGrid: {
      fr: "Effectuez les divisions en colonnes.",
      en: "Do the divisions in columns.",
      ar: "أنجزوا القسمة في الأعمدة.",
      fa: "تقسیم‌ها را به صورت ستونی انجام دهید.",
      pt: "Efetue as divisões em colunas.",
      so: "Samee qaybinnada tiirarka.",
      ti: "ነቲ ምክፋላት ብዓምዲ ፈጽሙ።",
      tr: "Bölmeleri alt alta yapın.",
      uk: "Виконайте ділення у стовпчик.",
      ps: "وېشونه په ستنو کې ترسره کړئ.",
    },
  },
};
