import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A3_5: SubmoduleTrad = {
  submoduleId: "A3-5",
  title: {
    fr: "Les multiples",
    en: "Multiples",
    ar: "المضاعفات",
    fa: "مضرب‌ها",
    ti: "ብዙሓት",
    uk: "Кратні числа",
    pt: "Múltiplos",
    so: "Tirooyinka labanlaabma",
    tr: "Katlar",
    ps: "مضاعفونه",
  },
  blocks: [
    {
      text: {
        fr: "Un nombre est un multiple d'un autre nombre lorsqu'on peut l'obtenir en le multipliant par un nombre entier.",
        en: "A number is a multiple of another number when we can obtain it by multiplying that number by a whole number.",
        ar: "يكون العدد مضاعفا لعدد آخر عندما يمكن الحصول عليه بضرب ذلك العدد في عدد صحيح.",
        fa: "یک عدد مضرب عددی دیگر است وقتی بتوان آن را با ضرب آن عدد در یک عدد صحیح به دست آورد.",
        ti: "ሓደ ቁጽሪ ናይ ካልእ ቁጽሪ ብዙሕ ይበሃል እንተደኣ ብምብዛሕ ብምሉእ ቁጽሪ ክንረኽቦ ንኽእል።",
        uk: "Число є кратним іншого числа, якщо його можна отримати, помноживши це число на ціле число.",
        pt: "Um número é múltiplo de outro quando o podemos obter multiplicando esse número por um número inteiro.",
        so: "Tiro waxay tahay labanlaabka tiro kale marka lagu heli karo iyadoo tiradaas lagu dhufto tiro dhan.",
        tr: "Bir sayı, başka bir sayının tam sayı ile çarpılmasıyla elde edilebiliyorsa o sayının katıdır.",
        ps: "یو عدد د بل عدد مضاعف دی که د هغه عدد په یوه صحیح عدد ضربولو سره ترلاسه شي.",
      },
    },
    {
      text: {
        fr: "12 est un multiple de 4 car :",
        en: "12 is a multiple of 4 because:",
        ar: "12 مضاعف لـ 4 لأن:",
        fa: "12 مضرب 4 است زیرا:",
        ti: "12 ናይ 4 ብዙሕ እዩ ምኽንያቱ:",
        uk: "12 є кратним 4, тому що:",
        pt: "12 é múltiplo de 4 porque:",
        so: "12 waa labanlaabka 4 sababtoo ah:",
        tr: "12, 4'ün katıdır çünkü:",
        ps: "12 د 4 مضاعف دی ځکه:",
      },
    },
    {
      items: {
        fr: ["**4** × 3 = 12"],
        en: ["**4** × 3 = 12"],
        ar: ["**4** × 3 = 12"],
        fa: ["**4** × 3 = 12"],
        ti: ["**4** × 3 = 12"],
        uk: ["**4** × 3 = 12"],
        pt: ["**4** × 3 = 12"],
        so: ["**4** × 3 = 12"],
        tr: ["**4** × 3 = 12"],
        ps: ["**4** × 3 = 12"],
      },
    },
    {
      text: {
        fr: "Les diviseurs",
        en: "Divisors",
        ar: "القواسم",
        fa: "مقسوم‌علیه‌ها",
        ti: "ከፈልቲ",
        uk: "Дільники",
        pt: "Divisores",
        so: "Qaybiyeyaasha",
        tr: "Bölenler",
        ps: "وېشونکي",
      },
    },
    {
      text: {
        fr: "Un nombre est un diviseur d'un autre nombre si la division donne un résultat entier, sans reste.",
        en: "A number is a divisor of another number if the division gives a whole-number result, with no remainder.",
        ar: "يكون العدد قاسما لعدد آخر إذا أعطت القسمة نتيجة صحيحة بلا باق.",
        fa: "یک عدد مقسوم‌علیه عددی دیگر است اگر تقسیم، نتیجه‌ای صحیح و بدون باقی‌مانده بدهد.",
        ti: "ሓደ ቁጽሪ ከፋሊ ናይ ካልእ ቁጽሪ ይኸውን እንተደኣ ምክፋል ብዘይ ተረፍ ምሉእ ውጽኢት ዝህብ።",
        uk: "Число є дільником іншого числа, якщо ділення дає цілий результат без остачі.",
        pt: "Um número é divisor de outro se a divisão dá um resultado inteiro, sem resto.",
        so: "Tiro waa qaybiye tiro kale haddii qaybintu bixiso natiijo dhan, haraa la'aan.",
        tr: "Bir sayı, başka bir sayıyı kalansız bölerse o sayının bölenidir.",
        ps: "یو عدد د بل عدد وېشونکی دی که وېش صحیح پایله ورکړي او پاتې ونه لري.",
      },
    },
    {
      text: {
        fr: "4 est un diviseur de 12 car :",
        en: "4 is a divisor of 12 because:",
        ar: "4 قاسم لـ 12 لأن:",
        fa: "4 مقسوم‌علیه 12 است زیرا:",
        ti: "4 ከፋሊ ናይ 12 እዩ ምኽንያቱ:",
        uk: "4 є дільником 12, тому що:",
        pt: "4 é divisor de 12 porque:",
        so: "4 waa qaybiye 12 sababtoo ah:",
        tr: "4, 12'nin bölenidir çünkü:",
        ps: "4 د 12 وېشونکی دی ځکه:",
      },
    },
    {
      items: {
        fr: ["12 ÷ **4** = 3"],
        en: ["12 ÷ **4** = 3"],
        ar: ["12 ÷ **4** = 3"],
        fa: ["12 ÷ **4** = 3"],
        ti: ["12 ÷ **4** = 3"],
        uk: ["12 ÷ **4** = 3"],
        pt: ["12 ÷ **4** = 3"],
        so: ["12 ÷ **4** = 3"],
        tr: ["12 ÷ **4** = 3"],
        ps: ["12 ÷ **4** = 3"],
      },
    },
    {
      text: {
        fr: "Relations",
        en: "Relationships",
        ar: "العلاقات",
        fa: "رابطه‌ها",
        ti: "ርክባት",
        uk: "Зв'язки",
        pt: "Relações",
        so: "Xiriirrada",
        tr: "İlişkiler",
        ps: "اړیکې",
      },
    },
    {
      text: {
        fr: "Si 12 = 3 × 4 alors :",
        en: "If 12 = 3 × 4, then:",
        ar: "إذا كان 12 = 3 × 4، فإن:",
        fa: "اگر 12 = 3 × 4 باشد، آنگاه:",
        ti: "12 = 3 × 4 እንተኾይኑ፣ ሽዑ:",
        uk: "Якщо 12 = 3 × 4, тоді:",
        pt: "Se 12 = 3 × 4, então:",
        so: "Haddii 12 = 3 × 4, markaas:",
        tr: "12 = 3 × 4 ise:",
        ps: "که 12 = 3 × 4 وي، نو:",
      },
    },
    {
      items: {
        fr: ["12 est un multiple de 3 et de 4.", "3 et 4 sont des diviseurs de 12."],
        en: ["12 is a multiple of 3 and 4.", "3 and 4 are divisors of 12."],
        ar: ["12 مضاعف لـ 3 و4.", "3 و4 قاسمان لـ 12."],
        fa: ["12 مضرب 3 و 4 است.", "3 و 4 مقسوم‌علیه‌های 12 هستند."],
        ti: ["12 ናይ 3ን 4ን ብዙሕ እዩ።", "3ን 4ን ከፈልቲ ናይ 12 እዮም።"],
        uk: ["12 є кратним 3 і 4.", "3 і 4 є дільниками 12."],
        pt: ["12 é múltiplo de 3 e de 4.", "3 e 4 são divisores de 12."],
        so: ["12 waa labanlaabka 3 iyo 4.", "3 iyo 4 waa qaybiyeyaasha 12."],
        tr: ["12, 3 ve 4'ün katıdır.", "3 ve 4, 12'nin bölenleridir."],
        ps: ["12 د 3 او 4 مضاعف دی.", "3 او 4 د 12 وېشونکي دي."],
      },
    },
    {
      text: {
        fr: "Critères de divisibilité",
        en: "Divisibility rules",
        ar: "قواعد القابلية للقسمة",
        fa: "قاعده‌های بخش‌پذیری",
        ti: "ሕግታት ተኸፋልነት",
        uk: "Ознаки подільності",
        pt: "Critérios de divisibilidade",
        so: "Xeerarka qaybsanaanta",
        tr: "Bölünebilme kuralları",
        ps: "د وېشل کېدو قاعدې",
      },
    },
    {
      text: {
        fr: "Les critères de divisibilité permettent de savoir rapidement si un nombre est divisible par un autre, sans poser la division.",
        en: "Divisibility rules let us quickly know whether a number is divisible by another, without doing the division.",
        ar: "تساعد قواعد القابلية للقسمة على معرفة بسرعة هل عدد يقبل القسمة على عدد آخر دون إجراء القسمة.",
        fa: "قاعده‌های بخش‌پذیری کمک می‌کنند سریع بدانیم آیا عددی بر عدد دیگر بخش‌پذیر است، بدون انجام تقسیم.",
        ti: "ሕግታት ተኸፋልነት ሓደ ቁጽሪ ብካልእ ቁጽሪ ይኸፈል ድዩ ኣይኸፈልን ብቕልጡፍ ንምፍላጥ ይሕግዙ፣ ምክፋል ከይገበርና።",
        uk: "Ознаки подільності допомагають швидко дізнатися, чи ділиться число на інше число, не виконуючи ділення.",
        pt: "Os critérios de divisibilidade permitem saber rapidamente se um número é divisível por outro, sem fazer a divisão.",
        so: "Xeerarka qaybsanaantu waxay si degdeg ah u sheegaan haddii tiro lagu qaybin karo tiro kale, adigoon qaybin sameyn.",
        tr: "Bölünebilme kuralları, bir sayının başka bir sayıya bölünüp bölünmediğini bölme yapmadan hızlıca anlamamızı sağlar.",
        ps: "د وېشل کېدو قاعدې ژر ښيي چې یو عدد په بل عدد وېشل کېږي که نه، بې له دې چې وېش وکړو.",
      },
    },
    {
      headers: {
        fr: ["", "Critère"],
        en: ["", "Rule"],
        ar: ["", "القاعدة"],
        fa: ["", "قاعده"],
        ti: ["", "ሕጊ"],
        uk: ["", "Ознака"],
        pt: ["", "Critério"],
        so: ["", "Xeer"],
        tr: ["", "Kural"],
        ps: ["", "قاعده"],
      },
      items: {
        fr: [
          "2 | Le dernier chiffre est pair.",
          "3 | La somme des chiffres est divisible par 3.",
          "4 | Le nombre formé par les deux derniers chiffres est divisible par 4.",
          "5 | Le dernier chiffre est 0 ou 5.",
          "6 | Le nombre est divisible par 2 et par 3.",
          "9 | La somme des chiffres est divisible par 9.",
          "10 | Le dernier chiffre est 0.",
        ],
        en: [
          "2 | The last digit is even.",
          "3 | The sum of the digits is divisible by 3.",
          "4 | The number formed by the last two digits is divisible by 4.",
          "5 | The last digit is 0 or 5.",
          "6 | The number is divisible by 2 and by 3.",
          "9 | The sum of the digits is divisible by 9.",
          "10 | The last digit is 0.",
        ],
        ar: [
          "2 | الرقم الأخير زوجي.",
          "3 | مجموع الأرقام يقبل القسمة على 3.",
          "4 | العدد المكوّن من آخر رقمين يقبل القسمة على 4.",
          "5 | الرقم الأخير هو 0 أو 5.",
          "6 | العدد يقبل القسمة على 2 وعلى 3.",
          "9 | مجموع الأرقام يقبل القسمة على 9.",
          "10 | الرقم الأخير هو 0.",
        ],
        fa: [
          "2 | رقم آخر زوج است.",
          "3 | مجموع رقم‌ها بر 3 بخش‌پذیر است.",
          "4 | عدد ساخته‌شده از دو رقم آخر بر 4 بخش‌پذیر است.",
          "5 | رقم آخر 0 یا 5 است.",
          "6 | عدد بر 2 و بر 3 بخش‌پذیر است.",
          "9 | مجموع رقم‌ها بر 9 بخش‌پذیر است.",
          "10 | رقم آخر 0 است.",
        ],
        ti: [
          "2 | ናይ መወዳእታ ኣሃዝ ጽምዲ እዩ።",
          "3 | ድምር ኣሃዛት ብ3 ይኸፈል።",
          "4 | ብክልተ ናይ መወዳእታ ኣሃዛት ዝተፈጥረ ቁጽሪ ብ4 ይኸፈል።",
          "5 | ናይ መወዳእታ ኣሃዝ 0 ወይ 5 እዩ።",
          "6 | ቁጽሪ ብ2ን ብ3ን ይኸፈል።",
          "9 | ድምር ኣሃዛት ብ9 ይኸፈል።",
          "10 | ናይ መወዳእታ ኣሃዝ 0 እዩ።",
        ],
        uk: [
          "2 | Остання цифра парна.",
          "3 | Сума цифр ділиться на 3.",
          "4 | Число, утворене двома останніми цифрами, ділиться на 4.",
          "5 | Остання цифра — 0 або 5.",
          "6 | Число ділиться на 2 і на 3.",
          "9 | Сума цифр ділиться на 9.",
          "10 | Остання цифра — 0.",
        ],
        pt: [
          "2 | O último algarismo é par.",
          "3 | A soma dos algarismos é divisível por 3.",
          "4 | O número formado pelos dois últimos algarismos é divisível por 4.",
          "5 | O último algarismo é 0 ou 5.",
          "6 | O número é divisível por 2 e por 3.",
          "9 | A soma dos algarismos é divisível por 9.",
          "10 | O último algarismo é 0.",
        ],
        so: [
          "2 | Lambarka ugu dambeeya waa tiro lammaane ah.",
          "3 | Wadarta lambarradu waxay u qaybsantaa 3.",
          "4 | Tirada ay sameeyaan labada lambar ee ugu dambeeya waxay u qaybsantaa 4.",
          "5 | Lambarka ugu dambeeya waa 0 ama 5.",
          "6 | Tiradu waxay u qaybsantaa 2 iyo 3.",
          "9 | Wadarta lambarradu waxay u qaybsantaa 9.",
          "10 | Lambarka ugu dambeeya waa 0.",
        ],
        tr: [
          "2 | Son rakam çifttir.",
          "3 | Rakamların toplamı 3'e bölünür.",
          "4 | Son iki rakamın oluşturduğu sayı 4'e bölünür.",
          "5 | Son rakam 0 veya 5'tir.",
          "6 | Sayı hem 2'ye hem 3'e bölünür.",
          "9 | Rakamların toplamı 9'a bölünür.",
          "10 | Son rakam 0'dır.",
        ],
        ps: [
          "2 | وروستی رقم جفت دی.",
          "3 | د رقمونو مجموعه پر 3 وېشل کېږي.",
          "4 | هغه عدد چې له وروستیو دوو رقمونو جوړ شوی پر 4 وېشل کېږي.",
          "5 | وروستی رقم 0 یا 5 دی.",
          "6 | عدد پر 2 او پر 3 وېشل کېږي.",
          "9 | د رقمونو مجموعه پر 9 وېشل کېږي.",
          "10 | وروستی رقم 0 دی.",
        ],
      },
    },
  ],
  consignes: {
    "a3-5-ep01": { fr: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (oui/non)", en: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (yes/no)", ar: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (نعم/لا)", fa: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (بله/خیر)", ti: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (yes/no)", uk: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (так/ні)", pt: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (sim/não)", so: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (yes/no)", tr: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (evet/hayır)", ps: "Exercice 1 — Reconnaître les multiples\\n6 est-il un multiple de 3 ? (yes/no)" },
    "a3-5-ep02": { fr: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (oui/non)", en: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (yes/no)", ar: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (نعم/لا)", fa: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (بله/خیر)", ti: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (yes/no)", uk: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (так/ні)", pt: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (sim/não)", so: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (yes/no)", tr: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (evet/hayır)", ps: "Exercice 1 — Reconnaître les multiples\\n10 est-il un multiple de 3 ? (yes/no)" },
    "a3-5-ep03": { fr: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", en: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", ar: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", fa: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", ti: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", uk: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", pt: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", so: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", tr: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant.", ps: "Exercice 1 — Reconnaître les multiples\\n18 = 3 × ___ : complète le facteur manquant." },
    "a3-5-ep04": { fr: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", en: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", ar: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", fa: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", ti: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", uk: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", pt: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", so: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", tr: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant.", ps: "Exercice 1 — Reconnaître les multiples\\n42 = 7 × ___ : complète le facteur manquant." },
    "a3-5-ep05": { fr: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (oui/non)", en: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (yes/no)", ar: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (نعم/لا)", fa: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (بله/خیر)", ti: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (yes/no)", uk: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (так/ні)", pt: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (sim/não)", so: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (yes/no)", tr: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (evet/hayır)", ps: "Exercice 2 — Reconnaître les diviseurs\\n4 est-il un diviseur de 20 ? (yes/no)" },
    "a3-5-ep06": { fr: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (oui/non)", en: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (yes/no)", ar: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (نعم/لا)", fa: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (بله/خیر)", ti: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (yes/no)", uk: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (так/ні)", pt: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (sim/não)", so: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (yes/no)", tr: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (evet/hayır)", ps: "Exercice 2 — Reconnaître les diviseurs\\n7 est-il un diviseur de 35 ? (yes/no)" },
    "a3-5-ep07": { fr: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (oui/non)", en: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (yes/no)", ar: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (نعم/لا)", fa: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (بله/خیر)", ti: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (yes/no)", uk: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (так/ні)", pt: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (sim/não)", so: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (yes/no)", tr: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (evet/hayır)", ps: "Exercice 2 — Reconnaître les diviseurs\\n5 divise-t-il 42 ? (yes/no)" },
    "a3-5-ep08": { fr: "Exercice 2 — Reconnaître les diviseurs\\nCombien de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", en: "Exercice 2 — Reconnaître les diviseurs\\nHow many de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", ar: "Exercice 2 — Reconnaître les diviseurs\\nكم de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", fa: "Exercice 2 — Reconnaître les diviseurs\\nچند de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", ti: "Exercice 2 — Reconnaître les diviseurs\\nHow many de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", uk: "Exercice 2 — Reconnaître les diviseurs\\nСкільки de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", pt: "Exercice 2 — Reconnaître les diviseurs\\nQuanto de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", so: "Exercice 2 — Reconnaître les diviseurs\\nHow many de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", tr: "Exercice 2 — Reconnaître les diviseurs\\nKaç de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)", ps: "Exercice 2 — Reconnaître les diviseurs\\nHow many de diviseurs a le nombre 12 ? (1, 2, 3, 4, 6, 12)" },
    "a3-5-ep09": { fr: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", en: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", ar: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", fa: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", ti: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", uk: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", pt: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", so: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", tr: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?", ps: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – ___ : quel est le terme suivant ?" },
    "a3-5-ep10": { fr: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", en: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", ar: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", fa: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", ti: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", uk: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", pt: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", so: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", tr: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?", ps: "Exercice 3 — Compléter une suite de multiples\\n3 – 6 – 9 – 12 – ___ : quel est le terme suivant ?" },
    "a3-5-ep11": { fr: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", en: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", ar: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", fa: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", ti: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", uk: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", pt: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", so: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", tr: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?", ps: "Exercice 3 — Compléter une suite de multiples\\n7 – 14 – 21 – ___ : quel est le terme suivant ?" },
    "a3-5-ep12": { fr: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", en: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", ar: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", fa: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", ti: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", uk: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", pt: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", so: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", tr: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?", ps: "Exercice 3 — Compléter une suite de multiples\\n5 – 10 – ___ – 20 : quel est le terme manquant ?" },
    "a3-5-ep13": { fr: "Exercice 4 — Trouver le multiple suivant\\nQuel est le prochain multiple de 4 après 28 ?", en: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 4 après 28 ?", ar: "Exercice 4 — Trouver le multiple suivant\\nما هو le prochain multiple de 4 après 28 ?", fa: "Exercice 4 — Trouver le multiple suivant\\nچیست le prochain multiple de 4 après 28 ?", ti: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 4 après 28 ?", uk: "Exercice 4 — Trouver le multiple suivant\\nЯкий le prochain multiple de 4 après 28 ?", pt: "Exercice 4 — Trouver le multiple suivant\\nQual é le prochain multiple de 4 après 28 ?", so: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 4 après 28 ?", tr: "Exercice 4 — Trouver le multiple suivant\\nNedir le prochain multiple de 4 après 28 ?", ps: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 4 après 28 ?" },
    "a3-5-ep14": { fr: "Exercice 4 — Trouver le multiple suivant\\nQuel est le prochain multiple de 9 après 54 ?", en: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 9 après 54 ?", ar: "Exercice 4 — Trouver le multiple suivant\\nما هو le prochain multiple de 9 après 54 ?", fa: "Exercice 4 — Trouver le multiple suivant\\nچیست le prochain multiple de 9 après 54 ?", ti: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 9 après 54 ?", uk: "Exercice 4 — Trouver le multiple suivant\\nЯкий le prochain multiple de 9 après 54 ?", pt: "Exercice 4 — Trouver le multiple suivant\\nQual é le prochain multiple de 9 après 54 ?", so: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 9 après 54 ?", tr: "Exercice 4 — Trouver le multiple suivant\\nNedir le prochain multiple de 9 après 54 ?", ps: "Exercice 4 — Trouver le multiple suivant\\nWhat is le prochain multiple de 9 après 54 ?" },
    "a3-5-ep15": { fr: "Exercice 4 — Trouver le multiple suivant\\nQuel est le plus petit multiple de 6 strictement supérieur à 40 ?", en: "Exercice 4 — Trouver le multiple suivant\\nWhat is le plus petit multiple de 6 strictement supérieur à 40 ?", ar: "Exercice 4 — Trouver le multiple suivant\\nما هو le plus petit multiple de 6 strictement supérieur à 40 ?", fa: "Exercice 4 — Trouver le multiple suivant\\nچیست le plus petit multiple de 6 strictement supérieur à 40 ?", ti: "Exercice 4 — Trouver le multiple suivant\\nWhat is le plus petit multiple de 6 strictement supérieur à 40 ?", uk: "Exercice 4 — Trouver le multiple suivant\\nЯкий le plus petit multiple de 6 strictement supérieur à 40 ?", pt: "Exercice 4 — Trouver le multiple suivant\\nQual é le plus petit multiple de 6 strictement supérieur à 40 ?", so: "Exercice 4 — Trouver le multiple suivant\\nWhat is le plus petit multiple de 6 strictement supérieur à 40 ?", tr: "Exercice 4 — Trouver le multiple suivant\\nNedir le plus petit multiple de 6 strictement supérieur à 40 ?", ps: "Exercice 4 — Trouver le multiple suivant\\nWhat is le plus petit multiple de 6 strictement supérieur à 40 ?" },
    "a3-5-ep16": { fr: "Exercice 5 — Multiples d'un nombre\\nQuel est le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", en: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", ar: "Exercice 5 — Multiples d'un nombre\\nما هو le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", fa: "Exercice 5 — Multiples d'un nombre\\nچیست le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", ti: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", uk: "Exercice 5 — Multiples d'un nombre\\nЯкий le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", pt: "Exercice 5 — Multiples d'un nombre\\nQual é le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", so: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", tr: "Exercice 5 — Multiples d'un nombre\\nNedir le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)", ps: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 2 ? (2, 4, 6, 8, 10, 12, 14, 16, 18, __)" },
    "a3-5-ep17": { fr: "Exercice 5 — Multiples d'un nombre\\nQuel est le 10ème multiple de 7 ?", en: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 7 ?", ar: "Exercice 5 — Multiples d'un nombre\\nما هو le 10ème multiple de 7 ?", fa: "Exercice 5 — Multiples d'un nombre\\nچیست le 10ème multiple de 7 ?", ti: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 7 ?", uk: "Exercice 5 — Multiples d'un nombre\\nЯкий le 10ème multiple de 7 ?", pt: "Exercice 5 — Multiples d'un nombre\\nQual é le 10ème multiple de 7 ?", so: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 7 ?", tr: "Exercice 5 — Multiples d'un nombre\\nNedir le 10ème multiple de 7 ?", ps: "Exercice 5 — Multiples d'un nombre\\nWhat is le 10ème multiple de 7 ?" },
    "a3-5-ep18": { fr: "Exercice 5 — Multiples d'un nombre\\nQuel est le plus petit multiple commun de 3 et de 5 (autre que 0) ?", en: "Exercice 5 — Multiples d'un nombre\\nWhat is le plus petit multiple commun de 3 et de 5 (autre que 0) ?", ar: "Exercice 5 — Multiples d'un nombre\\nما هو le plus petit multiple commun de 3 et de 5 (autre que 0) ?", fa: "Exercice 5 — Multiples d'un nombre\\nچیست le plus petit multiple commun de 3 et de 5 (autre que 0) ?", ti: "Exercice 5 — Multiples d'un nombre\\nWhat is le plus petit multiple commun de 3 et de 5 (autre que 0) ?", uk: "Exercice 5 — Multiples d'un nombre\\nЯкий le plus petit multiple commun de 3 et de 5 (autre que 0) ?", pt: "Exercice 5 — Multiples d'un nombre\\nQual é le plus petit multiple commun de 3 et de 5 (autre que 0) ?", so: "Exercice 5 — Multiples d'un nombre\\nWhat is le plus petit multiple commun de 3 et de 5 (autre que 0) ?", tr: "Exercice 5 — Multiples d'un nombre\\nNedir le plus petit multiple commun de 3 et de 5 (autre que 0) ?", ps: "Exercice 5 — Multiples d'un nombre\\nWhat is le plus petit multiple commun de 3 et de 5 (autre que 0) ?" },
    "a3-5-ep19": { fr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", en: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", ar: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", fa: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", ti: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", uk: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", pt: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", so: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", tr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?", ps: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 2 × 4 ?" },
    "a3-5-ep20": { fr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", en: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", ar: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", fa: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", ti: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", uk: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", pt: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", so: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", tr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?", ps: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 3 × 3 ?" },
    "a3-5-ep21": { fr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", en: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", ar: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", fa: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", ti: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", uk: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", pt: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", so: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", tr: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?", ps: "Exercice 6 — Tableau de multiples\\nDans le tableau × : que vaut 4 × 4 ?" },
    "a3-5-ep22": { fr: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (oui/non)", en: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (yes/no)", ar: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (نعم/لا)", fa: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (بله/خیر)", ti: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (yes/no)", uk: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (так/ні)", pt: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (sim/não)", so: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (yes/no)", tr: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (evet/hayır)", ps: "Exercice 7 — Associer\\n16 est-il un multiple de 4 ? (yes/no)" },
    "a3-5-ep23": { fr: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (oui/non)", en: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (yes/no)", ar: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (نعم/لا)", fa: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (بله/خیر)", ti: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (yes/no)", uk: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (так/ні)", pt: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (sim/não)", so: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (yes/no)", tr: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (evet/hayır)", ps: "Exercice 7 — Associer\\n3 est-il un diviseur de 18 ? (yes/no)" },
    "a3-5-ep24": { fr: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (oui/non)", en: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (yes/no)", ar: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (نعم/لا)", fa: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (بله/خیر)", ti: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (yes/no)", uk: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (так/ні)", pt: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (sim/não)", so: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (yes/no)", tr: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (evet/hayır)", ps: "Exercice 7 — Associer\\n45 est-il un multiple de 5 ? (yes/no)" },
    "a3-5-ep25": { fr: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (oui/non)", en: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (yes/no)", ar: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (نعم/لا)", fa: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (بله/خیر)", ti: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (yes/no)", uk: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (так/ні)", pt: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (sim/não)", so: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (yes/no)", tr: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (evet/hayır)", ps: "Exercice 8 — Tri de nombres\\n12 est-il un multiple de 2 ? (yes/no)" },
    "a3-5-ep26": { fr: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (oui/non)", en: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (yes/no)", ar: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (نعم/لا)", fa: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (بله/خیر)", ti: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (yes/no)", uk: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (так/ні)", pt: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (sim/não)", so: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (yes/no)", tr: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (evet/hayır)", ps: "Exercice 8 — Tri de nombres\\n21 est-il un multiple de 5 ? (yes/no)" },
    "a3-5-ep27": { fr: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (oui/non)", en: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (yes/no)", ar: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (نعم/لا)", fa: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (بله/خیر)", ti: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (yes/no)", uk: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (так/ні)", pt: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (sim/não)", so: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (yes/no)", tr: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (evet/hayır)", ps: "Exercice 8 — Tri de nombres\\n15 est-il un multiple de 3 ? (yes/no)" },
    "a3-5-ep28": { fr: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", en: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", ar: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", fa: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", ti: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", uk: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", pt: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", so: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", tr: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)", ps: "Exercice 9 — Multiple ou diviseur ?\\n5 est un ___ de 20. (multiple ou diviseur ?)" },
    "a3-5-ep29": { fr: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", en: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", ar: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", fa: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", ti: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", uk: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", pt: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", so: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", tr: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)", ps: "Exercice 9 — Multiple ou diviseur ?\\n20 est un ___ de 5. (multiple ou diviseur ?)" },
    "a3-5-ep30": { fr: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", en: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", ar: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", fa: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", ti: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", uk: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", pt: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", so: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", tr: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)", ps: "Exercice 9 — Multiple ou diviseur ?\\n8 est un ___ de 40. (multiple ou diviseur ?)" },
    "a3-5-ep31": { fr: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", en: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", ar: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", fa: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", ti: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", uk: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", pt: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", so: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", tr: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)", ps: "Exercice 10 — Pair ou impair\\nLes multiples de 2 sont-ils pairs ou impairs ? (pairs/impairs)" },
    "a3-5-ep32": { fr: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", en: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", ar: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", fa: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", ti: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", uk: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", pt: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", so: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", tr: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)", ps: "Exercice 10 — Pair ou impair\\nDonne le 5ème multiple impair de 3. (3, 9, 15, 21, ___)" },
    "a3-5-ep33": { fr: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (oui/non)", en: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (yes/no)", ar: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (نعم/لا)", fa: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (بله/خیر)", ti: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (yes/no)", uk: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (так/ні)", pt: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (sim/não)", so: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (yes/no)", tr: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (evet/hayır)", ps: "Exercice 11 — Divisible ou non\\n45 est-il divisible par 3 ? (somme des chiffres : 4+5=9) (yes/no)" },
    "a3-5-ep34": { fr: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (oui/non)", en: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (yes/no)", ar: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (نعم/لا)", fa: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (بله/خیر)", ti: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (yes/no)", uk: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (так/ні)", pt: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (sim/não)", so: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (yes/no)", tr: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (evet/hayır)", ps: "Exercice 11 — Divisible ou non\\n120 est-il divisible par 10 ? (yes/no)" },
    "a3-5-ep35": { fr: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (oui/non)", en: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (yes/no)", ar: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (نعم/لا)", fa: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (بله/خیر)", ti: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (yes/no)", uk: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (так/ні)", pt: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (sim/não)", so: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (yes/no)", tr: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (evet/hayır)", ps: "Exercice 11 — Divisible ou non\\n87 est-il divisible par 2 ? (yes/no)" },
    "a3-5-ep36": { fr: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (oui/non)", en: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (yes/no)", ar: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (نعم/لا)", fa: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (بله/خیر)", ti: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (yes/no)", uk: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (так/ні)", pt: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (sim/não)", so: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (yes/no)", tr: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (evet/hayır)", ps: "Exercice 11 — Divisible ou non\\n92 est-il divisible par 3 ? (somme : 9+2=11) (yes/no)" },
    "a3-5-ep37": { fr: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", en: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", ar: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", fa: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", ti: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", uk: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", pt: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", so: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", tr: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___.", ps: "Exercice 12 — Règles de divisibilité\\n246 est divisible par 2. Son dernier chiffre est ___." },
    "a3-5-ep38": { fr: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", en: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", ar: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", fa: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", ti: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", uk: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", pt: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", so: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", tr: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___.", ps: "Exercice 12 — Règles de divisibilité\\n315 est divisible par 5. Son dernier chiffre est ___." },
    "a3-5-ep39": { fr: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", en: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", ar: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", fa: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", ti: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", uk: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", pt: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", so: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", tr: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___.", ps: "Exercice 12 — Règles de divisibilité\\n123 est divisible par 3. La somme de ses chiffres est 1+2+3=___." },
    "a3-5-ep40": { fr: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", en: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", ar: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", fa: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", ti: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", uk: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", pt: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", so: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", tr: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)", ps: "Exercice 13 — Chiffre manquant\\nPour que 4_ soit divisible par 2, quel chiffre peut remplacer _ ? (donne un exemple)" },
    "a3-5-ep41": { fr: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", en: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", ar: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", fa: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", ti: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", uk: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", pt: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", so: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", tr: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)", ps: "Exercice 13 — Chiffre manquant\\nPour que 7_ soit divisible par 5, quel chiffre peut remplacer _ ? (0 ou 5)" },
    "a3-5-ep42": { fr: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", en: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", ar: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", fa: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", ti: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", uk: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", pt: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", so: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", tr: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)", ps: "Exercice 13 — Chiffre manquant\\nQuel chiffre remplace _ pour que 15_ soit divisible par 3 ? (somme divisible par 3 : 1+5+_)" },
    "a3-5-ep43": { fr: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", en: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ar: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", fa: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ti: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", uk: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", pt: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", so: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", tr: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ps: "Exercice 14 — Trouver un nombre\\nJe suis multiple de 4 et de 5. Je suis plus petit que 50. Qui suis-je ? (le plus petit tel nombre, autre que 0)" },
    "a3-5-ep44": { fr: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", en: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ar: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", fa: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ti: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", uk: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", pt: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", so: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", tr: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)", ps: "Exercice 14 — Trouver un nombre\\nJe suis divisible par 3 et par 2. Je suis plus petit que 15. Qui suis-je ? (le plus petit tel nombre, autre que 0)" },
    "a3-5-ep45": { fr: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", en: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", ar: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", fa: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", ti: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", uk: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", pt: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", so: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", tr: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)", ps: "Exercice 14 — Trouver un nombre\\nJe suis un diviseur de 36. Je suis supérieur à 12 et inférieur à 36. Qui suis-je ? (le plus petit)" },
    "a3-5-ep46": { fr: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", en: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", ar: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", fa: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", ti: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", uk: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", pt: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", so: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", tr: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)", ps: "Exercice 15 — Trouver l'intrus\\nDans la suite 6, 12, 18, 25, 30 : quel est l'intrus ? (nombre non multiple de 6)" },
    "a3-5-ep47": { fr: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", en: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", ar: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", fa: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", ti: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", uk: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", pt: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", so: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", tr: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)", ps: "Exercice 15 — Trouver l'intrus\\nDans la suite 5, 10, 15, 21, 25 : quel est l'intrus ? (nombre non multiple de 5)" },
    "a3-5-ep48": { fr: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", en: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", ar: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", fa: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", ti: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", uk: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", pt: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", so: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", tr: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?", ps: "Exercice 16 — Devinette\\nJe suis un multiple de 6. Je suis pair. Je suis entre 20 et 30. Qui suis-je ?" },
  },
};
