import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A2_1: SubmoduleTrad = {
  submoduleId: "A2-1",
  title: {
    fr: "Addition",
    en: "Addition",
    ar: "الجمع",
    fa: "جمع",
    ti: "ድምር",
    uk: "Додавання",
    pt: "Adição",
    so: "Isku darka",
    tr: "Toplama",
    ps: "جمع",
  },
  blocks: [
    {
      text: {
        fr: "L'addition permet de **réunir** plusieurs quantités **ensemble**.",
        en: "Addition lets us **combine** several quantities **together**.",
        ar: "يسمح الجمع بـ **ضم** عدة كميات **معا**.",
        fa: "جمع به ما اجازه می‌دهد چند مقدار را **با هم** **ترکیب** کنیم.",
        ti: "ድምር ብዙሓት መጠናት **ብሓባር** **ንምጥርናፍ** ይሕግዝ።",
        uk: "Додавання допомагає **об'єднати** кілька кількостей **разом**.",
        pt: "A adição permite **juntar** várias quantidades **em conjunto**.",
        so: "Isku darku wuxuu noo oggolaanayaa in aan tirooyin badan **isku geyno**.",
        tr: "Toplama, birkaç miktarı **bir araya** getirmeyi sağlar.",
        ps: "جمع څو مقدارونه **یو ځای** **راټولوي**.",
      },
    },
    {
      items: {
        fr: [
          "Le signe de l'addition est le signe « + » **plus**",
          "Les nombres à additionner sont les **termes**.",
          "Le résultat de l'addition est la **somme**.",
        ],
        en: [
          "The sign for addition is the « + » **plus** sign.",
          "The numbers being added are the **terms**.",
          "The result of an addition is the **sum**.",
        ],
        ar: [
          "رمز الجمع هو الرمز « + » **زائد**.",
          "الأعداد التي نجمعها تسمى **الحدود**.",
          "نتيجة الجمع تسمى **المجموع**.",
        ],
        fa: [
          "نشانه جمع، علامت « + » یعنی **به علاوه** است.",
          "عددهایی که جمع می‌شوند **جمله‌ها** هستند.",
          "نتیجه جمع، **مجموع** نام دارد.",
        ],
        ti: [
          "ምልክት ድምር « + » **ተወሳኺ** እዩ።",
          "እቶም ዝድመሩ ቁጽርታት **ቃላት** ይበሃሉ።",
          "ውጽኢት ድምር **ድምር** ይበሃል።",
        ],
        uk: [
          "Знак додавання — це знак « + » **плюс**.",
          "Числа, які додають, називаються **доданками**.",
          "Результат додавання називається **сумою**.",
        ],
        pt: [
          "O sinal da adição é o sinal « + » **mais**.",
          "Os números a adicionar são os **termos**.",
          "O resultado da adição é a **soma**.",
        ],
        so: [
          "Calaamadda isku darku waa calaamadda « + » **lagu daray**.",
          "Tirooyinka la isku darayo waa **qodobbada**.",
          "Natiijada isku darku waa **wadarta**.",
        ],
        tr: [
          "Toplama işareti « + » **artı** işaretidir.",
          "Toplanan sayılar **terimlerdir**.",
          "Toplamanın sonucu **toplamdır**.",
        ],
        ps: [
          "د جمع نښه « + » **جمع** ده.",
          "هغه عددونه چې جمع کېږي **حدونه** دي.",
          "د جمع پایله **مجموعه** ده.",
        ],
      },
    },
    {
      headers: {
        fr: ["5", "+", "8", "=", "13"],
        en: ["5", "+", "8", "=", "13"],
        ar: ["5", "+", "8", "=", "13"],
        fa: ["5", "+", "8", "=", "13"],
        ti: ["5", "+", "8", "=", "13"],
        uk: ["5", "+", "8", "=", "13"],
        pt: ["5", "+", "8", "=", "13"],
        so: ["5", "+", "8", "=", "13"],
        tr: ["5", "+", "8", "=", "13"],
        ps: ["5", "+", "8", "=", "13"],
      },
    },
    {
      text: {
        fr: "Propriétés de l'addition",
        en: "Properties of addition",
        ar: "خصائص الجمع",
        fa: "ویژگی‌های جمع",
        ti: "ባህርያት ድምር",
        uk: "Властивості додавання",
        pt: "Propriedades da adição",
        so: "Sifooyinka isku darka",
        tr: "Toplamanın özellikleri",
        ps: "د جمع ځانګړنې",
      },
    },
    {
      text: {
        fr: "Commutativité",
        en: "Commutativity",
        ar: "خاصية الإبدال",
        fa: "خاصیت جابه‌جایی",
        ti: "ምቅይያር",
        uk: "Переставна властивість",
        pt: "Comutatividade",
        so: "Isdhaafsanaan",
        tr: "Değişme özelliği",
        ps: "بدلېدونکې ځانګړنه",
      },
    },
    {
      items: {
        fr: ["L'ordre des termes ne change pas la somme."],
        en: ["The order of the terms does not change the sum."],
        ar: ["ترتيب الحدود لا يغيّر المجموع."],
        fa: ["ترتیب جمله‌ها، مجموع را تغییر نمی‌دهد."],
        ti: ["ቅደም ተከተል ቃላት ንድምር ኣይቅይሮን።"],
        uk: ["Порядок доданків не змінює суму."],
        pt: ["A ordem dos termos não altera a soma."],
        so: ["Kala horraynta qodobbadu ma beddesho wadarta."],
        tr: ["Terimlerin sırası toplamı değiştirmez."],
        ps: ["د حدونو ترتیب مجموعه نه بدلوي."],
      },
    },
    {},
    {
      text: {
        fr: "Associativité",
        en: "Associativity",
        ar: "خاصية التجميع",
        fa: "خاصیت شرکت‌پذیری",
        ti: "ምጥርናፍ",
        uk: "Сполучна властивість",
        pt: "Associatividade",
        so: "Kooxayn",
        tr: "Birleşme özelliği",
        ps: "یوځای کوونکې ځانګړنه",
      },
    },
    {
      items: {
        fr: ["On peut additionner plus de deux termes dans l'ordre voulu."],
        en: ["We can add more than two terms in any order we choose."],
        ar: ["يمكننا جمع أكثر من حدين بالترتيب الذي نريده."],
        fa: ["می‌توانیم بیش از دو جمله را به هر ترتیبی که می‌خواهیم جمع کنیم."],
        ti: ["ካብ ክልተ ንላዕሊ ቃላት ብዝደለናዮ ቅደም ተከተል ክንድምር ንኽእል።"],
        uk: ["Можна додавати більше ніж два доданки у вибраному порядку."],
        pt: ["Podemos adicionar mais de dois termos na ordem que quisermos."],
        so: ["Waxaan isku dari karnaa in ka badan laba qodob sida aan rabno."],
        tr: ["İkiden fazla terimi istediğimiz sırayla toplayabiliriz."],
        ps: ["له دوو څخه ډېر حدونه په خوښه ترتیب سره جمع کولای شو."],
      },
    },
    {},
    {
      text: {
        fr: "Addition en colonnes",
        en: "Column addition",
        ar: "الجمع في الأعمدة",
        fa: "جمع ستونی",
        ti: "ድምር ብዓምዲ",
        uk: "Додавання у стовпчик",
        pt: "Adição em colunas",
        so: "Isku darka tiirar",
        tr: "Alt alta toplama",
        ps: "ستوني جمع",
      },
    },
    {},
  ],
  consignes: {
    "a2-1-ep01": { fr: "Calculez : 46 + 37 = ?", en: "Calculate : 46 + 37 = ?", ar: "احسب : 46 + 37 = ?", fa: "حساب کنید : 46 + 37 = ?", ti: "Calculate : 46 + 37 = ?", uk: "Обчисліть : 46 + 37 = ?", pt: "Calcule : 46 + 37 = ?", so: "Calculate : 46 + 37 = ?", tr: "Hesaplayın : 46 + 37 = ?", ps: "Calculate : 46 + 37 = ?" },
    "a2-1-ep02": { fr: "Calculez : 125 + 248 = ?", en: "Calculate : 125 + 248 = ?", ar: "احسب : 125 + 248 = ?", fa: "حساب کنید : 125 + 248 = ?", ti: "Calculate : 125 + 248 = ?", uk: "Обчисліть : 125 + 248 = ?", pt: "Calcule : 125 + 248 = ?", so: "Calculate : 125 + 248 = ?", tr: "Hesaplayın : 125 + 248 = ?", ps: "Calculate : 125 + 248 = ?" },
    "a2-1-ep03": { fr: "Calculez : 364 + 179 = ?", en: "Calculate : 364 + 179 = ?", ar: "احسب : 364 + 179 = ?", fa: "حساب کنید : 364 + 179 = ?", ti: "Calculate : 364 + 179 = ?", uk: "Обчисліть : 364 + 179 = ?", pt: "Calcule : 364 + 179 = ?", so: "Calculate : 364 + 179 = ?", tr: "Hesaplayın : 364 + 179 = ?", ps: "Calculate : 364 + 179 = ?" },
    "a2-1-ep04": { fr: "Calculez : 507 + 286 = ?", en: "Calculate : 507 + 286 = ?", ar: "احسب : 507 + 286 = ?", fa: "حساب کنید : 507 + 286 = ?", ti: "Calculate : 507 + 286 = ?", uk: "Обчисліть : 507 + 286 = ?", pt: "Calcule : 507 + 286 = ?", so: "Calculate : 507 + 286 = ?", tr: "Hesaplayın : 507 + 286 = ?", ps: "Calculate : 507 + 286 = ?" },
    "a2-1-ep05": { fr: "Calculez : 1 234 + 567 = ?", en: "Calculate : 1 234 + 567 = ?", ar: "احسب : 1 234 + 567 = ?", fa: "حساب کنید : 1 234 + 567 = ?", ti: "Calculate : 1 234 + 567 = ?", uk: "Обчисліть : 1 234 + 567 = ?", pt: "Calcule : 1 234 + 567 = ?", so: "Calculate : 1 234 + 567 = ?", tr: "Hesaplayın : 1 234 + 567 = ?", ps: "Calculate : 1 234 + 567 = ?" },
    "a2-1-ep06": { fr: "Calculez : 2 458 + 1 375 = ?", en: "Calculate : 2 458 + 1 375 = ?", ar: "احسب : 2 458 + 1 375 = ?", fa: "حساب کنید : 2 458 + 1 375 = ?", ti: "Calculate : 2 458 + 1 375 = ?", uk: "Обчисліть : 2 458 + 1 375 = ?", pt: "Calcule : 2 458 + 1 375 = ?", so: "Calculate : 2 458 + 1 375 = ?", tr: "Hesaplayın : 2 458 + 1 375 = ?", ps: "Calculate : 2 458 + 1 375 = ?" },
    "a2-1-ep07": { fr: "Calculez : 89 + 76 = ?", en: "Calculate : 89 + 76 = ?", ar: "احسب : 89 + 76 = ?", fa: "حساب کنید : 89 + 76 = ?", ti: "Calculate : 89 + 76 = ?", uk: "Обчисліть : 89 + 76 = ?", pt: "Calcule : 89 + 76 = ?", so: "Calculate : 89 + 76 = ?", tr: "Hesaplayın : 89 + 76 = ?", ps: "Calculate : 89 + 76 = ?" },
    "a2-1-ep08": { fr: "Calculez : 4 736 + 2 189 = ?", en: "Calculate : 4 736 + 2 189 = ?", ar: "احسب : 4 736 + 2 189 = ?", fa: "حساب کنید : 4 736 + 2 189 = ?", ti: "Calculate : 4 736 + 2 189 = ?", uk: "Обчисліть : 4 736 + 2 189 = ?", pt: "Calcule : 4 736 + 2 189 = ?", so: "Calculate : 4 736 + 2 189 = ?", tr: "Hesaplayın : 4 736 + 2 189 = ?", ps: "Calculate : 4 736 + 2 189 = ?" },
    "a2-1-ep09": { fr: "Calculez : 308 + 495 = ?", en: "Calculate : 308 + 495 = ?", ar: "احسب : 308 + 495 = ?", fa: "حساب کنید : 308 + 495 = ?", ti: "Calculate : 308 + 495 = ?", uk: "Обчисліть : 308 + 495 = ?", pt: "Calcule : 308 + 495 = ?", so: "Calculate : 308 + 495 = ?", tr: "Hesaplayın : 308 + 495 = ?", ps: "Calculate : 308 + 495 = ?" },
    "a2-1-ep10": { fr: "Calculez : 1 999 + 1 = ?", en: "Calculate : 1 999 + 1 = ?", ar: "احسب : 1 999 + 1 = ?", fa: "حساب کنید : 1 999 + 1 = ?", ti: "Calculate : 1 999 + 1 = ?", uk: "Обчисліть : 1 999 + 1 = ?", pt: "Calcule : 1 999 + 1 = ?", so: "Calculate : 1 999 + 1 = ?", tr: "Hesaplayın : 1 999 + 1 = ?", ps: "Calculate : 1 999 + 1 = ?" },
    "a2-1-ep11": { fr: "Calculez : 673 + 254 = ?", en: "Calculate : 673 + 254 = ?", ar: "احسب : 673 + 254 = ?", fa: "حساب کنید : 673 + 254 = ?", ti: "Calculate : 673 + 254 = ?", uk: "Обчисліть : 673 + 254 = ?", pt: "Calcule : 673 + 254 = ?", so: "Calculate : 673 + 254 = ?", tr: "Hesaplayın : 673 + 254 = ?", ps: "Calculate : 673 + 254 = ?" },
    "a2-1-ep12": { fr: "Calculez : 3 450 + 2 675 = ?", en: "Calculate : 3 450 + 2 675 = ?", ar: "احسب : 3 450 + 2 675 = ?", fa: "حساب کنید : 3 450 + 2 675 = ?", ti: "Calculate : 3 450 + 2 675 = ?", uk: "Обчисліть : 3 450 + 2 675 = ?", pt: "Calcule : 3 450 + 2 675 = ?", so: "Calculate : 3 450 + 2 675 = ?", tr: "Hesaplayın : 3 450 + 2 675 = ?", ps: "Calculate : 3 450 + 2 675 = ?" },
  },
};
