import type { SubmoduleTrad } from "./trad-types";

const S = (fr: string, en: string, ar: string, fa: string, ti: string, uk: string, pt: string, so: string, tr: string, ps: string) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });
const A = (fr: string[], en: string[], ar: string[], fa: string[], ti: string[], uk: string[], pt: string[], so: string[], tr: string[], ps: string[]) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });

export const TRAD_G5_6: SubmoduleTrad = {
  submoduleId: "G5-6",
  title: S(
      "Cône et sphère",
      "Cone and sphere",
      "المخروط والكرة",
      "مخروط و کره",
      "ኮንን ስፌርን",
      "Конус і куля",
      "Cone e esfera",
      "Koone iyo kubad",
      "Koni ve küre",
      "مخروط او کره",
    ),
  blocks: [
    { text: S(
      "Volume du cône et de la sphère",
      "Volume of cone and sphere",
      "حجم المخروط والكرة",
      "حجم مخروط و کره",
      "ናይ ኮንን ስፌርን መጠን",
      "Об'єм конуса і кулі",
      "Volume do cone e da esfera",
      "Mugga koone iyo kubad",
      "Koni ve kürenin hacmi",
      "د مخروط او کرې حجم",
    ) },
    {},
    { text: S(
      "Cône",
      "Cone",
      "المخروط",
      "مخروط",
      "ኮን",
      "Конус",
      "Cone",
      "Koone",
      "Koni",
      "مخروط",
    ) },
    {
      label: S(
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
      "V = (π × r² × h) ÷ 3",
    ),
      items: A(
      ["Le cône a le tiers du volume d'un cylindre de même base et de même hauteur.", "r est le rayon de la base, h est la hauteur."],
      ["A cone has one third the volume of a cylinder with the same base and height.", "r is the base radius, h is the height."],
      ["للمخروط ثلث حجم أسطوانة بنفس القاعدة والارتفاع.", "r نصف قطر القاعدة، h الارتفاع."],
      ["مخروط یک‌سوم حجم استوانه‌ای با همان قاعده و ارتفاع را دارد.", "r شعاع قاعده، h ارتفاع است."],
      ["ኮን ሓደ ሳልሳይ ናይ ሲሊንደር መጠን ኣለዎ ምስ ተመሳሳሊ መሰረትን ቁመትን።", "r ራድየስ መሰረት፡ h ቁመት እዩ።"],
      ["Конус має третину об'єму циліндра з тією ж основою і висотою.", "r — радіус основи, h — висота."],
      ["O cone tem um terço do volume de um cilindro com a mesma base e altura.", "r é o raio da base, h é a altura."],
      ["Koone wuxuu leeyahay saddex-meelood meel mugga silindar isla aasaas iyo dherer.", "r waa radius aasaaska, h waa dhererka."],
      ["Koni, aynı taban ve yüksekliğe sahip bir silindirin hacminin üçte birine sahiptir.", "r taban yarıçapı, h yüksekliktir."],
      ["مخروط د ورته اساس او لوړوالي استوانې د حجم دریمه برخه لري.", "r د اساس شعاع، h لوړوالی دی."],
    ),
    },
    { text: S(
      "Cône r = 3 cm, h = 7 cm : V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 cm³.",
      "Cone r = 3 cm, h = 7 cm: V = π × 3² × 7 ÷ 3 = 21π ≈ 65.9 cm³.",
      "مخروط r = 3 سم، h = 7 سم: V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 سم³.",
      "مخروط r = ۳ cm، h = ۷ cm: V = π × ۳² × ۷ ÷ ۳ = ۲۱π ≈ ۶۵٫۹ cm³.",
      "ኮን r = 3 cm, h = 7 cm፦ V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 cm³.",
      "Конус r = 3 см, h = 7 см: V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 см³.",
      "Cone r = 3 cm, h = 7 cm: V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 cm³.",
      "Koone r = 3 cm, h = 7 cm: V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 cm³.",
      "Koni r = 3 cm, h = 7 cm: V = π × 3² × 7 ÷ 3 = 21π ≈ 65,9 cm³.",
      "مخروط r = ۳ cm، h = ۷ cm: V = π × ۳² × ۷ ÷ ۳ = ۲۱π ≈ ۶۵٫۹ cm³.",
    ) },
    { text: S(
      "Sphère",
      "Sphere",
      "الكرة",
      "کره",
      "ስፌር",
      "Куля",
      "Esfera",
      "Kubad",
      "Küre",
      "کره",
    ) },
    {
      label: S(
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
      "V = (4 × π × r³) ÷ 3",
    ),
      items: A(
      ["r est le rayon de la sphère.", "La formule utilise le rayon au cube : r × r × r."],
      ["r is the radius of the sphere.", "The formula uses the cubed radius: r × r × r."],
      ["r هو نصف قطر الكرة.", "الصيغة تستخدم نصف القطر مكعباً: r × r × r."],
      ["r شعاع کره است.", "فرمول از شعاع به توان سه استفاده می‌کند: r × r × r."],
      ["r ራድየስ ስፌር እዩ።", "ቀመር ራድየስ ኩብ ይጥቀም፦ r × r × r."],
      ["r — радіус кулі.", "Формула використовує радіус у кубі: r × r × r."],
      ["r é o raio da esfera.", "A fórmula usa o raio ao cubo: r × r × r."],
      ["r waa radius kubadda.", "Qaaciddu waxay isticmaashaa radius saddex-jibbaaran: r × r × r."],
      ["r kürenin yarıçapıdır.", "Formül yarıçapın küpünü kullanır: r × r × r."],
      ["r د کرې شعاع ده.", "فارمول د شعاع مکعب کاروي: r × r × r."],
    ),
    },
    { text: S(
      "Sphère r = 3 cm : V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 cm³.",
      "Sphere r = 3 cm: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113.1 cm³.",
      "كرة r = 3 سم: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 سم³.",
      "کره r = ۳ cm: V = ۴ × π × ۳³ ÷ ۳ = ۳۶π ≈ ۱۱۳٫۱ cm³.",
      "ስፌር r = 3 cm፦ V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 cm³.",
      "Куля r = 3 см: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 см³.",
      "Esfera r = 3 cm: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 cm³.",
      "Kubad r = 3 cm: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 cm³.",
      "Küre r = 3 cm: V = 4 × π × 3³ ÷ 3 = 36π ≈ 113,1 cm³.",
      "کره r = ۳ cm: V = ۴ × π × ۳³ ÷ ۳ = ۳۶π ≈ ۱۱۳٫۱ cm³.",
    ) },
  ],
  consignes: {
    "g5-9-e1": { fr: "Cône r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3,14)", en: "Cone r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3.14)", ar: "مخروط r=3 سم، h=4 سم. V = (1/3)π×9×4 ≈ ؟ (π≈3,14)", fa: "مخروط r=۳ cm، h=۴ cm. V = (۱/۳)π×۹×۴ ≈ ؟ (π≈۳٫۱۴)", ti: "ኮን r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3,14)", uk: "Конус r=3 см, h=4 см. V = (1/3)π×9×4 ≈ ? (π≈3,14)", pt: "Cone r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3,14)", so: "Koone r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3,14)", tr: "Koni r=3 cm, h=4 cm. V = (1/3)π×9×4 ≈ ? (π≈3,14)", ps: "مخروط r=۳ cm، h=۴ cm. V = (۱/۳)π×۹×۴ ≈ ؟ (π≈۳٫۱۴)" },
    "g5-9-e2": { fr: "Sphère r=1 cm. V = (4/3)π ≈ ? (π≈3,14)", en: "Sphere r=1 cm. V = (4/3)π ≈ ? (π≈3.14)", ar: "كرة r=1 سم. V = (4/3)π ≈ ؟ (π≈3,14)", fa: "کره r=۱ cm. V = (۴/۳)π ≈ ؟ (π≈۳٫۱۴)", ti: "ስፌር r=1 cm. V = (4/3)π ≈ ? (π≈3,14)", uk: "Куля r=1 см. V = (4/3)π ≈ ? (π≈3,14)", pt: "Esfera r=1 cm. V = (4/3)π ≈ ? (π≈3,14)", so: "Kubad r=1 cm. V = (4/3)π ≈ ? (π≈3,14)", tr: "Küre r=1 cm. V = (4/3)π ≈ ? (π≈3,14)", ps: "کره r=۱ cm. V = (۴/۳)π ≈ ؟ (π≈۳٫۱۴)" },
    "g5-9-e3": { fr: "Si un cylindre a V=90π cm³, le cône de même base et hauteur a V=?π cm³.", en: "If a cylinder has V=90π cm³, the cone with same base and height has V=?π cm³.", ar: "إذا كان للأسطوانة V=90π سم³، فالمخروط بنفس القاعدة والارتفاع له V=?π سم³.", fa: "اگر استوانه V=۹۰π cm³ داشته باشد، مخروط با همان قاعده و ارتفاع V=?π cm³.", ti: "ሲሊንደር V=90π cm³ እንተኾይኑ፡ ተመሳሳሊ መሰረትን ቁመትን ኮን V=?π cm³.", uk: "Якщо циліндр має V=90π см³, конус з тією ж основою і висотою має V=?π см³.", pt: "Se um cilindro tem V=90π cm³, o cone com a mesma base e altura tem V=?π cm³.", so: "Haddii silindar V=90π cm³ leeyahay, koone isla aasaas iyo dherer V=?π cm³.", tr: "Bir silindirin V=90π cm³ ise, aynı taban ve yükseklikteki koninin V=?π cm³.", ps: "که استوانه V=۹۰π cm³ ولري، ورته اساس او لوړوالي مخروط V=?π cm³." },
    "g5-9-e4": { fr: "Sphère r=2 cm. V = (4/3)π×8 ≈ ? (π≈3,14)", en: "Sphere r=2 cm. V = (4/3)π×8 ≈ ? (π≈3.14)", ar: "كرة r=2 سم. V = (4/3)π×8 ≈ ؟ (π≈3,14)", fa: "کره r=۲ cm. V = (۴/۳)π×۸ ≈ ؟ (π≈۳٫۱۴)", ti: "ስፌር r=2 cm. V = (4/3)π×8 ≈ ? (π≈3,14)", uk: "Куля r=2 см. V = (4/3)π×8 ≈ ? (π≈3,14)", pt: "Esfera r=2 cm. V = (4/3)π×8 ≈ ? (π≈3,14)", so: "Kubad r=2 cm. V = (4/3)π×8 ≈ ? (π≈3,14)", tr: "Küre r=2 cm. V = (4/3)π×8 ≈ ? (π≈3,14)", ps: "کره r=۲ cm. V = (۴/۳)π×۸ ≈ ؟ (π≈۳٫۱۴)" },
    "g5-9-e5": { fr: "Cône r=6 cm, h=7 cm. V ≈ ? (π≈3,14)", en: "Cone r=6 cm, h=7 cm. V ≈ ? (π≈3.14)", ar: "مخروط r=6 سم، h=7 سم. V ≈ ؟ (π≈3,14)", fa: "مخروط r=۶ cm، h=۷ cm. V ≈ ؟ (π≈۳٫۱۴)", ti: "ኮን r=6 cm, h=7 cm. V ≈ ? (π≈3,14)", uk: "Конус r=6 см, h=7 см. V ≈ ? (π≈3,14)", pt: "Cone r=6 cm, h=7 cm. V ≈ ? (π≈3,14)", so: "Koone r=6 cm, h=7 cm. V ≈ ? (π≈3,14)", tr: "Koni r=6 cm, h=7 cm. V ≈ ? (π≈3,14)", ps: "مخروط r=۶ cm، h=۷ cm. V ≈ ؟ (π≈۳٫۱۴)" },
  },
};
