import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A5_6: SubmoduleTrad = {
  submoduleId: "A5-6",
  title: {
    fr: "Division de décimaux",
    en: "Dividing decimals",
    ar: "قسمة الأعداد العشرية",
    fa: "تقسیم اعداد اعشاری",
    ti: "ዲሲማል ቁጽርታት ምክፋል",
    uk: "Ділення десяткових чисел",
    pt: "Divisão de números decimais",
    so: "Qaybinta tirooyinka tobanle",
    tr: "Ondalık sayılarda bölme",
    ps: "د اعشاري عددونو وېش",
  },
  blocks: [
    {
      text: {
        fr: "Vocabulaire",
        en: "Vocabulary",
        ar: "المفردات",
        fa: "واژگان",
        ti: "ቃላት",
        uk: "Словник",
        pt: "Vocabulário",
        so: "Erayo",
        tr: "Sözlük",
        ps: "لغتونه",
      },
    },
    {
      headers: {
        fr: ["Terme", "Rôle", "Exemple"],
        en: ["Term", "Role", "Example"],
        ar: ["المصطلح", "الدور", "مثال"],
        fa: ["واژه", "نقش", "مثال"],
        ti: ["ቃል", "ተራ", "ኣብነት"],
        uk: ["Термін", "Роль", "Приклад"],
        pt: ["Termo", "Função", "Exemplo"],
        so: ["Eray", "Doorka", "Tusaale"],
        tr: ["Terim", "Görev", "Örnek"],
        ps: ["اصطلاح", "دنده", "بېلګه"],
      },
    },
    {
      text: {
        fr: "On ne peut PAS échanger dividende et diviseur : 82,5 ÷ 6 ≠ 6 ÷ 82,5",
        en: "We CANNOT swap the dividend and the divisor: 82.5 ÷ 6 ≠ 6 ÷ 82.5",
        ar: "لا يمكن تبديل المقسوم والمقسوم عليه: 82.5 ÷ 6 ≠ 6 ÷ 82.5",
        fa: "نمی‌توان مقسوم و مقسوم‌علیه را جابه‌جا کرد: 82.5 ÷ 6 ≠ 6 ÷ 82.5",
        ti: "ድምር ዝክፈልን መካፈልን ክንቀያይሮም ኣይንኽእልን፦ 82.5 ÷ 6 ≠ 6 ÷ 82.5",
        uk: "НЕ можна міняти місцями ділене й дільник: 82,5 ÷ 6 ≠ 6 ÷ 82,5",
        pt: "NÃO podemos trocar o dividendo e o divisor: 82,5 ÷ 6 ≠ 6 ÷ 82,5",
        so: "Lama beddeli KARO qaybiyaha iyo tirada la qaybinayo: 82.5 ÷ 6 ≠ 6 ÷ 82.5",
        tr: "Bölünen ile böleni yer değiştiremeyiz: 82,5 ÷ 6 ≠ 6 ÷ 82,5",
        ps: "مقسوم او مقسوم علیه نه شو بدلولی: 82.5 ÷ 6 ≠ 6 ÷ 82.5",
      },
    },
    { text: { fr: "", en: "", ar: "", fa: "", ti: "", uk: "", pt: "", so: "", tr: "", ps: "" } },
    {
      text: {
        fr: "Méthode en 3 étapes",
        en: "Method in 3 steps",
        ar: "الطريقة في 3 خطوات",
        fa: "روش در ۳ مرحله",
        ti: "መገዲ ብ3 ደረጃታት",
        uk: "Метод у 3 кроки",
        pt: "Método em 3 etapas",
        so: "Habka 3 tallaabo",
        tr: "3 adımda yöntem",
        ps: "طریقه په ۳ پړاوونو کې",
      },
    },
    {
      items: {
        fr: [
          "1. Multiplier le dividende pour supprimer la virgule (× 10, × 100…).",
          "2. Diviser comme des entiers.",
          "3. Diviser le quotient par le même facteur → replacer la virgule.",
        ],
        en: [
          "1. Multiply the dividend to remove the decimal separator (× 10, × 100…).",
          "2. Divide like whole numbers.",
          "3. Divide the quotient by the same factor → put the decimal separator back.",
        ],
        ar: [
          "1. نضرب المقسوم لإزالة الفاصلة العشرية (× 10، × 100…).",
          "2. نقسم كما نقسم الأعداد الصحيحة.",
          "3. نقسم خارج القسمة على العامل نفسه → نعيد وضع الفاصلة.",
        ],
        fa: [
          "1. مقسوم را ضرب کن تا ممیز حذف شود (× 10، × 100…).",
          "2. مانند عددهای صحیح تقسیم کن.",
          "3. خارج قسمت را بر همان عامل تقسیم کن → ممیز را برگردان.",
        ],
        ti: [
          "1. ኮማ ንምእላይ ዝክፈል ቁጽሪ ኣባዝሕ (× 10, × 100…).",
          "2. ከም ምሉኣት ቁጽርታት ክፈል።",
          "3. ኮሺንት ብተመሳሳሊ ፋክተር ክፈል → ኮማ መልስ።",
        ],
        uk: [
          "1. Помножити ділене, щоб прибрати кому (× 10, × 100…).",
          "2. Ділити як цілі числа.",
          "3. Поділити частку на той самий множник → повернути кому.",
        ],
        pt: [
          "1. Multiplicar o dividendo para eliminar a vírgula (× 10, × 100…).",
          "2. Dividir como números inteiros.",
          "3. Dividir o quociente pelo mesmo fator → recolocar a vírgula.",
        ],
        so: [
          "1. Ku dhufo tirada la qaybinayo si aad uga saarto kala-gooyaha (× 10, × 100…).",
          "2. U qaybi sida tirooyin dhan.",
          "3. Quotient-ka u qaybi isla qodobkaas → dib u geli kala-gooyaha.",
        ],
        tr: [
          "1. Virgülü kaldırmak için bölüneni çarp (× 10, × 100…).",
          "2. Tam sayılar gibi böl.",
          "3. Bölümü aynı çarpana böl → virgülü geri koy.",
        ],
        ps: [
          "1. مقسوم ضرب کړه چې اعشاري نښه لرې شي (× 10، × 100…).",
          "2. د صحیح عددونو په څېر وېش وکړه.",
          "3. خارج قسمت په هماغه عامل وویشه → اعشاري نښه بېرته کېږده.",
        ],
      },
    },
    { text: { fr: "", en: "", ar: "", fa: "", ti: "", uk: "", pt: "", so: "", tr: "", ps: "" } },
    {
      text: {
        fr: "Vérification",
        en: "Check",
        ar: "التحقق",
        fa: "بررسی",
        ti: "ምርግጋጽ",
        uk: "Перевірка",
        pt: "Verificação",
        so: "Hubin",
        tr: "Kontrol",
        ps: "کتنه",
      },
    },
    {
      items: {
        fr: ["quotient × diviseur = dividende", "13,75 × 6 = 82,5 ✓"],
        en: ["quotient × divisor = dividend", "13.75 × 6 = 82.5 ✓"],
        ar: ["خارج القسمة × المقسوم عليه = المقسوم", "13.75 × 6 = 82.5 ✓"],
        fa: ["خارج قسمت × مقسوم‌علیه = مقسوم", "13.75 × 6 = 82.5 ✓"],
        ti: ["ኮሺንት × መካፈሊ = ዝክፈል", "13.75 × 6 = 82.5 ✓"],
        uk: ["частка × дільник = ділене", "13,75 × 6 = 82,5 ✓"],
        pt: ["quociente × divisor = dividendo", "13,75 × 6 = 82,5 ✓"],
        so: ["jawaab × qaybiye = tirada la qaybiyay", "13.75 × 6 = 82.5 ✓"],
        tr: ["bölüm × bölen = bölünen", "13,75 × 6 = 82,5 ✓"],
        ps: ["خارج قسمت × مقسوم علیه = مقسوم", "13.75 × 6 = 82.5 ✓"],
      },
    },
    { text: { fr: "", en: "", ar: "", fa: "", ti: "", uk: "", pt: "", so: "", tr: "", ps: "" } },
    {
      text: {
        fr: "Astuces pour diviser",
        en: "Tips for dividing",
        ar: "حيل للقسمة",
        fa: "نکته‌هایی برای تقسیم",
        ti: "ንምክፋል ዝሕግዙ ምኽርታት",
        uk: "Поради для ділення",
        pt: "Dicas para dividir",
        so: "Talooyin qaybin",
        tr: "Bölme ipuçları",
        ps: "د وېش لارښوونې",
      },
    },
    {
      headers: {
        fr: ["Diviseur", "Astuce", "Exemple"],
        en: ["Divisor", "Tip", "Example"],
        ar: ["المقسوم عليه", "الحيلة", "مثال"],
        fa: ["مقسوم‌علیه", "نکته", "مثال"],
        ti: ["መካፈሊ", "ምኽሪ", "ኣብነት"],
        uk: ["Дільник", "Порада", "Приклад"],
        pt: ["Divisor", "Dica", "Exemplo"],
        so: ["Qaybiye", "Talo", "Tusaale"],
        tr: ["Bölen", "İpucu", "Örnek"],
        ps: ["مقسوم علیه", "لارښوونه", "بېلګه"],
      },
    },
  ],
};
