import type { SubmoduleTrad } from "./trad-types";

const S = (fr: string, en: string, ar: string, fa: string, ti: string, uk: string, pt: string, so: string, tr: string, ps: string) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });

const P = (fr: string[], en: string[], ar: string[], fa: string[], ti: string[], uk: string[], pt: string[], so: string[], tr: string[], ps: string[]) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });

export const TRAD_G6_4: SubmoduleTrad = {
  submoduleId: "G6-4",
  title: S(
    "Rotation",
    "Rotation",
    "الدوران",
    "دوران",
    "ምምቕቃሉ",
    "Поворот",
    "Rotação",
    "Wareeg",
    "Dönme",
    "چورلول",
  ),
  paragraphs: P(
    [
      "Une rotation de centre O et d'angle α fait tourner chaque point M autour de O d'un angle α (dans le sens positif = antihoraire).",
      "Propriétés : conservation des distances, des angles et des aires. O est le seul point fixe.",
      "Cas particuliers : rotation de 90° (quart de tour) ; 180° (demi-tour = symétrie centrale) ; 360° (tour complet = identité).",
      "Construction : pour une rotation de 90° antihoraire autour de O, le point (x, y) devient (−y, x).",
    ],
    [
      "A rotation of center O and angle α rotates each point M around O by α (positive = anticlockwise).",
      "Properties: distances, angles, areas preserved. O is the only fixed point.",
      "Special cases: 90° (quarter turn); 180° (half turn = central symmetry); 360° (full turn).",
      "Construction: 90° anticlockwise about O: (x, y) → (−y, x).",
    ],
    [
      "الدوران ذو المركز O والزاوية α يدور كل نقطة M حول O بزاوية α (موجب = عكس عقارب الساعة).",
      "الخصائص: حفظ المسافات والزوايا والمساحات. O النقطة الثابتة الوحيدة.",
      "حالات خاصة: 90° (ربع دورة)؛ 180° (نصف دورة)؛ 360° (دورة كاملة).",
      "90° عكس عقارب الساعة: (x, y) → (−y, x).",
    ],
    [
      "دوران با مرکز O و زاویه α هر نقطه M را α درجه حول O می‌چرخاند (مثبت = پادساعتگرد).",
      "ویژگی‌ها: فاصله‌ها، زوایا و مساحت‌ها حفظ می‌شوند. O تنها نقطه ثابت است.",
      "حالات خاص: 90° (ربع دور)؛ 180° (نیم دور)؛ 360° (دور کامل).",
      "90° پادساعتگرد: (x, y) → (−y, x).",
    ],
    [
      "ምምቕቃሉ ናይ O ማዕኸን ን α ኩርናዕ ነፍሲ ወከፍ ነጥቢ M ናብ α ኩርናዕ ዙርያ O ዘምቕቅሎ ዩ.",
      "ንብረታት: ርሕቀት, ኩርናዓት, ሰፊሓ ዕቃቤ. O ናህሰ ቋሚ ነጥቢ ዩ.",
      "ፍሉይ ኩነታት: 90° (ናህሰ ዕዮ); 180° (ፍርቂ ዕዮ); 360° (ምሉእ ዕዮ).",
      "90° ንስኽ ካብ ሰዓት: (x, y) → (−y, x).",
    ],
    [
      "Поворот з центром O і кутом α повертає кожну точку M навколо O на кут α (позитивний = проти годинникової стрілки).",
      "Властивості: зберігаються відстані, кути, площі. O — єдина нерухома точка.",
      "Особливі випадки: 90° (чверть оберту); 180° (половина = центральна симетрія); 360° (повний оберт).",
      "90° проти годинникової: (x, y) → (−y, x).",
    ],
    [
      "Uma rotação de centro O e ângulo α roda cada ponto M em torno de O por α (positivo = anti-horário).",
      "Propriedades: distâncias, ângulos e áreas conservadas. O é o único ponto fixo.",
      "Casos especiais: 90° (quarto de volta); 180° (meia volta = simetria central); 360° (volta completa).",
      "90° anti-horário em torno de O: (x, y) → (−y, x).",
    ],
    [
      "Wareeg xarun O iyo gees α wuxuu ku wareejiyaa barta M hareeraha O gees α (toban = ka soo horjeeda saacadda).",
      "Sifooyinka: masaafo, gees iyo bedba waa la ilaaliyaa. O waa barta kaliya ee go'an.",
      "Xaalado gaar ah: 90° (rubuc wareeg); 180° (nus wareeg); 360° (wareeg buuxa).",
      "90° ka soo horjeeda saacadda: (x, y) → (−y, x).",
    ],
    [
      "O merkezli ve α açılı dönme, her M noktasını O etrafında α kadar döndürür (pozitif = saat yönünün tersi).",
      "Özellikler: uzunluklar, açılar ve alanlar korunur. O tek sabit noktadır.",
      "Özel durumlar: 90° (çeyrek tur); 180° (yarım tur); 360° (tam tur).",
      "O etrafında 90° saat yönünün tersi: (x, y) → (−y, x).",
    ],
    [
      "د O مرکز او α زاویې چورلول هر M نقطه د O شاوخوا α زاویې ته ګرځوي (مثبت = د ساعت خلاف).",
      "ځانګړتیاوې: واټن، زاویې او ساحې ساتل کېږي. O یوازینۍ ثابته نقطه ده.",
      "ځانګړي حالتونه: 90° (ربع چورلول); 180° (نیمه چورلول); 360° (بشپړ چورلول).",
      "د O شاوخوا 90° د ساعت خلاف: (x, y) → (−y, x).",
    ],
  ),
  consignes: {
    "g6-4-e1": S(
      "La rotation conserve-t-elle les distances ? (oui/non)",
      "Does rotation preserve distances? (yes/no)",
      "هل الدوران يحافظ على المسافات؟ (نعم/لا)",
      "آیا دوران فاصله‌ها را حفظ می‌کند؟ (بله/خیر)",
      "ምምቕቃሉ ርሕቀት ይቕቅብ ድዩ? (እወ/ኣይፋል)",
      "Чи зберігає поворот відстані? (так/ні)",
      "A rotação conserva as distâncias? (sim/não)",
      "Wareeggu ma ilaalisaa masaafo? (haa/maya)",
      "Dönme uzunlukları korur mu? (evet/hayır)",
      "آیا چورلول واټنونه ساتي؟ (هو/نه)",
    ),
    "g6-4-e2": S(
      "Une rotation de 360° ramène la figure à sa position initiale ? (oui/non)",
      "Does a 360° rotation bring the figure back to its initial position? (yes/no)",
      "هل دوران 360° يعيد الشكل إلى موضعه الأولي؟ (نعم/لا)",
      "آیا دوران 360° شکل را به موقعیت اولیه برمی‌گرداند؟ (بله/خیر)",
      "ምምቕቃሉ 360° ናብ መጀመርታ ቦታ ይመልሶ ድዩ? (እወ/ኣይፋል)",
      "Чи повертає поворот на 360° фігуру в початкове положення? (так/ні)",
      "Uma rotação de 360° traz a figura à posição inicial? (sim/não)",
      "Wareeg 360° ma keenaa shaxda booskeedii hore? (haa/maya)",
      "360° dönme şekli başlangıç konumuna getirir mi? (evet/hayır)",
      "آیا 360° چورلول شکل بیرته خپل لومړنی موقعیت ته راوړي؟ (هو/نه)",
    ),
    "g6-4-e3": S(
      "Rotation de 90° antihoraire : le point (3 ; 0) devient ?",
      "90° counterclockwise rotation: point (3 ; 0) becomes?",
      "دوران 90° عكس عقارب الساعة: النقطة (3 ; 0) تصبح ؟",
      "دوران 90° پادساعتگرد: نقطه (3 ; 0) می‌شود؟",
      "ምምቕቃሉ 90° ንስኽ ካብ ሰዓት: ነጥቢ (3 ; 0) ይኸውን ?",
      "Поворот на 90° проти годинникової: точка (3 ; 0) стає?",
      "Rotação de 90° anti-horário: o ponto (3 ; 0) torna-se?",
      "Wareeg 90° ka soo horjeeda saacadda: barta (3 ; 0) waxay noqotaa?",
      "90° saat yönünün tersi dönme: (3 ; 0) noktası ne olur?",
      "90° د ساعت خلاف چورلول: نقطه (3 ; 0) کېږي؟",
    ),
    "g6-4-e4": S(
      "Une rotation de 180° est équivalente à quelle transformation ?",
      "A 180° rotation is equivalent to which transformation?",
      "دوران 180° يعادل أي تحويل؟",
      "دوران 180° معادل کدام تبدیل است؟",
      "ምምቕቃሉ 180° ንኹይት ምስቅቅልዋ ይመስል ?",
      "Поворот на 180° еквівалентний якій трансформації?",
      "Uma rotação de 180° é equivalente a que transformação?",
      "Wareeg 180° wuxuu la mid yahay isbeddel noocee ah?",
      "180° dönme hangi dönüşüme eşdeğerdir?",
      "180° چورلول کوم بدلون سره برابر دی؟",
    ),
    "g6-4-e5": S(
      "Après une rotation, la figure est-elle de même taille ? (oui/non)",
      "After a rotation, is the figure the same size? (yes/no)",
      "بعد الدوران، هل الشكل بنفس الحجم؟ (نعم/لا)",
      "پس از دوران، آیا شکل همان اندازه است؟ (بله/خیر)",
      "ድሕሪ ምምቕቃሉ፣ ቅርጺ ብሓደ ዓቐን ድዩ? (እወ/ኣይፋል)",
      "Після повороту чи фігура того ж розміру? (так/ні)",
      "Após uma rotação, a figura tem o mesmo tamanho? (sim/não)",
      "Ka dib wareeg, shaxdu ma isku cabbir baa? (haa/maya)",
      "Döndükten sonra şekil aynı boyutta mı? (evet/hayır)",
      "د چورلول وروسته، ایا شکل په ورته اندازه دی؟ (هو/نه)",
    ),
  },
};
