import type { SubmoduleTrad } from "./trad-types";

const S = (fr: string, en: string, ar: string, fa: string, ti: string, uk: string, pt: string, so: string, tr: string, ps: string) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });
const A = (fr: string[], en: string[], ar: string[], fa: string[], ti: string[], uk: string[], pt: string[], so: string[], tr: string[], ps: string[]) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });

export const TRAD_G5_2: SubmoduleTrad = {
  submoduleId: "G5-2",
  title: S(
      "Volume du cube",
      "Volume of a cube",
      "حجم المكعب",
      "حجم مکعب",
      "ናይ ኩብ መጠን",
      "Об'єм куба",
      "Volume do cubo",
      "Mugga kubka",
      "Küpün hacmi",
      "د مکعب حجم",
    ),
  blocks: [
    { text: S(
      "Volume du cube",
      "Volume of a cube",
      "حجم المكعب",
      "حجم مکعب",
      "ናይ ኩብ መጠን",
      "Об'єм куба",
      "Volume do cubo",
      "Mugga kubka",
      "Küpün hacmi",
      "د مکعب حجم",
    ) },
    { text: S(
      "Un cube a **3 dimensions égales** : longueur = largeur = hauteur = côté.",
      "A cube has **3 equal dimensions**: length = width = height = side.",
      "للمكعب **3 أبعاد متساوية**: الطول = العرض = الارتفاع = الضلع.",
      "مکعب **۳ بعد مساوی** دارد: طول = عرض = ارتفاع = ضلع.",
      "ኩብ **3 ማዕረ ዓቐናት** ኣለዎ፦ ንውሓት = ጎድናይ = ቁመት = ጐኒ።",
      "Куб має **3 рівні виміри**: довжина = ширина = висота = сторона.",
      "Um cubo tem **3 dimensões iguais**: comprimento = largura = altura = lado.",
      "Kube wuxuu leeyahay **3 cabbir oo siman**: dherer = ballac = dherer sare = dhinac.",
      "Küpün **3 eşit boyutu** vardır: uzunluk = genişlik = yükseklik = kenar.",
      "مکعب **۳ مساوي اړخونه** لري: اوږدوالی = پلنوالی = لوړوالی = اړخ.",
    ) },
    {},
    { text: S(
      "Formule",
      "Formula",
      "الصيغة",
      "فرمول",
      "ቀመር",
      "Формула",
      "Fórmula",
      "Qaacidda",
      "Formül",
      "فارمول",
    ) },
    {
      label: S(
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
      "V = c × c × c = c³",
    ),
      items: A(
      ["c est la mesure du côté.", "L'unité du volume est une unité **cubique** : cm³, dm³, m³..."],
      ["c is the side length.", "Volume uses a **cubic** unit: cm³, dm³, m³..."],
      ["c هو طول الضلع.", "وحدة الحجم وحدة **مكعبة**: سم³، دسم³، م³..."],
      ["c اندازه ضلع است.", "واحد حجم یک واحد **مکعبی** است: cm³، dm³، m³..."],
      ["c ቁጽሪ ናይ ጐኒ እዩ።", "ናይ መጠን ኣሃዱ **ኩባዊ** ኣሃዱ እዩ፦ cm³, dm³, m³..."],
      ["c — довжина сторони.", "Одиниця об'єму — **кубічна**: см³, дм³, м³..."],
      ["c é a medida do lado.", "A unidade de volume é **cúbica**: cm³, dm³, m³..."],
      ["c waa cabbirka dhinaca.", "Unugga mugga waa unug **cube** ah: cm³, dm³, m³..."],
      ["c kenar uzunluğudur.", "Hacim birimi **kübik**tir: cm³, dm³, m³..."],
      ["c د اړخ اندازه ده.", "د حجم واحد **مکعبي** دی: cm³، dm³، m³..."],
    ),
    },
    { text: S(
      "Cube de côté 4 cm : V = 4 × 4 × 4 = 64 cm³.",
      "Cube of side 4 cm: V = 4 × 4 × 4 = 64 cm³.",
      "مكعب ضلعه 4 سم: V = 4 × 4 × 4 = 64 سم³.",
      "مکعب به ضلع ۴ cm: V = ۴ × ۴ × ۴ = ۶۴ cm³.",
      "ኩብ ጐኒ 4 cm፦ V = 4 × 4 × 4 = 64 cm³.",
      "Куб зі стороною 4 см: V = 4 × 4 × 4 = 64 см³.",
      "Cubo de lado 4 cm: V = 4 × 4 × 4 = 64 cm³.",
      "Kube dhinac 4 cm: V = 4 × 4 × 4 = 64 cm³.",
      "Kenarı 4 cm olan küp: V = 4 × 4 × 4 = 64 cm³.",
      "د ۴ cm اړخ مکعب: V = ۴ × ۴ × ۴ = ۶۴ cm³.",
    ) },
    { text: S(
      "Si le volume est connu, on cherche le nombre qui multiplié 3 fois par lui-même donne ce volume.",
      "If the volume is known, find the number that multiplied by itself 3 times gives that volume.",
      "إذا عُرف الحجم، نبحث عن العدد الذي إذا ضُرب بنفسه 3 مرات يعطي هذا الحجم.",
      "اگر حجم معلوم باشد، عددی را می‌جوییم که سه بار در خودش ضرب شود و این حجم را بدهد.",
      "መጠን እንተፈሊጡ፡ ሰለስተ ግዜ ብዓይኑ ተባዚሑ እቲ መጠን ዝህብ ቁጽሪ ንደሊ።",
      "Якщо об'єм відомий, шукаємо число, яке помножене на себе 3 рази дає цей об'єм.",
      "Se o volume é conhecido, procura-se o número que multiplicado 3 vezes por si mesmo dá esse volume.",
      "Haddii mugga la yaqaan, waxaan raadinnaa lambarka saddex jeer naftiisa lagu dhufto si uu u bixiyo muggaas.",
      "Hacim biliniyorsa, kendisiyle 3 kez çarpılınca bu hacmi veren sayı aranır.",
      "که حجم معلوم وي، هغه عدد لټوو چې درې ځله په ځان ضرب شي نو همدا حجم ورکړي.",
    ) },
  ],
  consignes: {
    "g5-4-e1": { fr: "Volume d'un cube de côté 3 cm.", en: "Volume of a cube with side 3 cm.", ar: "حجم مكعب ضلعه 3 سم.", fa: "حجم مکعب به ضلع ۳ cm.", ti: "ናይ ኩብ መጠን ጐኒ 3 cm.", uk: "Об'єм куба зі стороною 3 см.", pt: "Volume de um cubo de lado 3 cm.", so: "Mugga kube dhinac 3 cm.", tr: "Kenarı 3 cm olan küpün hacmi.", ps: "د ۳ cm اړخ مکعب حجم." },
    "g5-4-e2": { fr: "Volume d'un cube de côté 5 cm.", en: "Volume of a cube with side 5 cm.", ar: "حجم مكعب ضلعه 5 سم.", fa: "حجم مکعب به ضلع ۵ cm.", ti: "ናይ ኩብ መጠን ጐኒ 5 cm.", uk: "Об'єм куба зі стороною 5 см.", pt: "Volume de um cubo de lado 5 cm.", so: "Mugga kube dhinac 5 cm.", tr: "Kenarı 5 cm olan küpün hacmi.", ps: "د ۵ cm اړخ مکعب حجم." },
    "g5-4-e3": { fr: "Un cube de volume 8 cm³. Quel est son côté ?", en: "A cube of volume 8 cm³. What is its side?", ar: "مكعب حجمه 8 سم³. ما طول ضلعه؟", fa: "مکعبی به حجم ۸ cm³. ضلعش چند است؟", ti: "ኩብ መጠን 8 cm³. ጐኒኡ ምንታይ?", uk: "Куб об'ємом 8 см³. Яка його сторона?", pt: "Um cubo de volume 8 cm³. Qual é o seu lado?", so: "Kube mug 8 cm³. Dhinaciisu waa imisa?", tr: "Hacmi 8 cm³ olan bir küp. Kenarı kaçtır?", ps: "د ۸ cm³ حجم مکعب. اړخ یې څومره دی؟" },
    "g5-4-e4": { fr: "1 dm³ = combien de cm³ ?", en: "1 dm³ = how many cm³?", ar: "1 دسم³ = كم سم³؟", fa: "۱ dm³ = چند cm³؟", ti: "1 dm³ = ክንደይ cm³?", uk: "1 дм³ = скільки см³?", pt: "1 dm³ = quantos cm³?", so: "1 dm³ = imisa cm³?", tr: "1 dm³ = kaç cm³?", ps: "۱ dm³ = څو cm³؟" },
    "g5-4-e5": { fr: "Volume d'un cube de côté 10 cm en litres.", en: "Volume of a cube with side 10 cm in litres.", ar: "حجم مكعب ضلعه 10 سم باللترات.", fa: "حجم مکعب به ضلع ۱۰ cm به لیتر.", ti: "ናይ ኩብ መጠን ጐኒ 10 cm ብሊትር.", uk: "Об'єм куба зі стороною 10 см у літрах.", pt: "Volume de um cubo de lado 10 cm em litros.", so: "Mugga kube dhinac 10 cm ee litir.", tr: "Kenarı 10 cm olan küpün hacmi (litre).", ps: "د ۱۰ cm اړخ مکعب حجم په لیټرو کې." },
  },
};
