import type { SubmoduleTrad } from "./trad-types";

export const TRAD_A5_2: SubmoduleTrad = {
  submoduleId: "A5-2",
  title: {
    fr: "Suites de décimaux",
    en: "Decimal sequences",
    ar: "متتاليات عشرية",
    fa: "دنباله‌های اعشاری",
    ti: "ተኸታታሊ ዲሲማል ቁጽርታት",
    uk: "Десяткові послідовності",
    pt: "Sequências de números decimais",
    so: "Taxanaha tirooyinka tobanle",
    tr: "Ondalık sayı dizileri",
    ps: "د اعشاري عددونو لړۍ",
  },
  blocks: [
    {
      text: {
        fr: "Comment trouver l'écart",
        en: "How to find the step",
        ar: "كيف نجد الفارق",
        fa: "چگونه فاصله را پیدا کنیم",
        ti: "ፍልልይ ብኸመይ ንረኽቦ",
        uk: "Як знайти крок",
        pt: "Como encontrar a diferença",
        so: "Sida loo helo farqiga",
        tr: "Adım farkı nasıl bulunur",
        ps: "توپیر څنګه پیدا کړو",
      },
    },
    {
      text: {
        fr: "**1.** Repérer si la suite est **croissante** (augmente) ou **décroissante** (diminue).",
        en: "**1.** Identify whether the sequence is **increasing** (goes up) or **decreasing** (goes down).",
        ar: "**1.** نحدد هل المتتالية **تصاعدية** (تزداد) أم **تنازلية** (تنقص).",
        fa: "**1.** مشخص کن دنباله **صعودی** است (زیاد می‌شود) یا **نزولی** است (کم می‌شود).",
        ti: "**1.** ተኸታታሊ ቁጽሪ **ይውስኽ** ድዩ ወይ **ይንኪ** ድዩ ነለሊ።",
        uk: "**1.** Визначити, послідовність **зростає** чи **спадає**.",
        pt: "**1.** Identificar se a sequência é **crescente** (aumenta) ou **decrescente** (diminui).",
        so: "**1.** Ogoow in taxanuhu **kordhayo** ama **dhimayo**.",
        tr: "**1.** Dizinin **artan** mı yoksa **azalan** mı olduğunu belirle.",
        ps: "**1.** معلومه کړه چې لړۍ **زیاتېږي** که **کمېږي**.",
      },
    },
    {
      text: {
        fr: "**2.** Calculer l'écart entre deux valeurs consécutives.",
        en: "**2.** Calculate the step between two consecutive values.",
        ar: "**2.** نحسب الفارق بين قيمتين متتاليتين.",
        fa: "**2.** فاصله بین دو مقدار پشت سر هم را حساب کن.",
        ti: "**2.** ኣብ መንጎ ክልተ ተኸታታሊ ዋጋታት ዘሎ ፍልልይ ንሕስብ።",
        uk: "**2.** Обчислити крок між двома сусідніми значеннями.",
        pt: "**2.** Calcular a diferença entre dois valores consecutivos.",
        so: "**2.** Xisaabi farqiga u dhexeeya laba qiime oo isku xiga.",
        tr: "**2.** Ardışık iki değer arasındaki farkı hesapla.",
        ps: "**2.** د دوو پرله پسې ارزښتونو ترمنځ توپیر حساب کړه.",
      },
    },
    {
      text: {
        fr: "**3.** Appliquer l'écart pour trouver les valeurs manquantes.",
        en: "**3.** Use the step to find the missing values.",
        ar: "**3.** نستعمل الفارق لإيجاد القيم الناقصة.",
        fa: "**3.** از فاصله برای پیدا کردن مقدارهای گمشده استفاده کن.",
        ti: "**3.** ፍልልይ ተጠቒምና ዝጎደሉ ዋጋታት ንረኽብ።",
        uk: "**3.** Використати крок, щоб знайти пропущені значення.",
        pt: "**3.** Aplicar a diferença para encontrar os valores em falta.",
        so: "**3.** Isticmaal farqiga si aad u hesho qiimayaasha maqan.",
        tr: "**3.** Eksik değerleri bulmak için farkı uygula.",
        ps: "**3.** د ورکو ارزښتونو د موندلو لپاره توپیر وکاروه.",
      },
    },
    { text: { fr: "", en: "", ar: "", fa: "", ti: "", uk: "", pt: "", so: "", tr: "", ps: "" } },
    {
      text: {
        fr: "Deux valeurs consécutives connues",
        en: "Two known consecutive values",
        ar: "قيمتان متتاليتان معروفتان",
        fa: "دو مقدار پشت سر همِ معلوم",
        ti: "ክልተ ፍሉጣት ተኸታታሊ ዋጋታት",
        uk: "Два відомі сусідні значення",
        pt: "Dois valores consecutivos conhecidos",
        so: "Laba qiime oo isku xiga oo la yaqaan",
        tr: "Bilinen iki ardışık değer",
        ps: "دوه معلوم پرله پسې ارزښتونه",
      },
    },
    {
      text: {
        fr: "2,5 ; **...** ; 3,5 ; 4",
        en: "2.5 ; **...** ; 3.5 ; 4",
        ar: "2.5 ; **...** ; 3.5 ; 4",
        fa: "2.5 ; **...** ; 3.5 ; 4",
        ti: "2.5 ; **...** ; 3.5 ; 4",
        uk: "2,5 ; **...** ; 3,5 ; 4",
        pt: "2,5 ; **...** ; 3,5 ; 4",
        so: "2.5 ; **...** ; 3.5 ; 4",
        tr: "2,5 ; **...** ; 3,5 ; 4",
        ps: "2.5 ; **...** ; 3.5 ; 4",
      },
    },
    {
      items: {
        fr: [
          "Soustraire les deux valeurs connues.",
          "4 − 3,5 = 0,5 **écart**",
          "Valeur manquante = valeur connue ± **écart**",
          "Valeur manquante = 2,5 + 0,5 = **3,0**",
        ],
        en: [
          "Subtract the two known values.",
          "4 − 3.5 = 0.5 **step**",
          "Missing value = known value ± **step**",
          "Missing value = 2.5 + 0.5 = **3.0**",
        ],
        ar: [
          "نطرح القيمتين المعروفتين.",
          "4 − 3.5 = 0.5 **الفارق**",
          "القيمة الناقصة = القيمة المعروفة ± **الفارق**",
          "القيمة الناقصة = 2.5 + 0.5 = **3.0**",
        ],
        fa: [
          "دو مقدار معلوم را از هم کم کن.",
          "4 − 3.5 = 0.5 **فاصله**",
          "مقدار گمشده = مقدار معلوم ± **فاصله**",
          "مقدار گمشده = 2.5 + 0.5 = **3.0**",
        ],
        ti: [
          "ክልተ ፍሉጣት ዋጋታት ንጉድል።",
          "4 − 3.5 = 0.5 **ፍልልይ**",
          "ዝጎደለ ዋጋ = ፍሉጥ ዋጋ ± **ፍልልይ**",
          "ዝጎደለ ዋጋ = 2.5 + 0.5 = **3.0**",
        ],
        uk: [
          "Відняти два відомі значення.",
          "4 − 3,5 = 0,5 **крок**",
          "Пропущене значення = відоме значення ± **крок**",
          "Пропущене значення = 2,5 + 0,5 = **3,0**",
        ],
        pt: [
          "Subtrair os dois valores conhecidos.",
          "4 − 3,5 = 0,5 **diferença**",
          "Valor em falta = valor conhecido ± **diferença**",
          "Valor em falta = 2,5 + 0,5 = **3,0**",
        ],
        so: [
          "Kala jar labada qiime ee la yaqaan.",
          "4 − 3.5 = 0.5 **farqi**",
          "Qiimaha maqan = qiimaha la yaqaan ± **farqi**",
          "Qiimaha maqan = 2.5 + 0.5 = **3.0**",
        ],
        tr: [
          "Bilinen iki değeri çıkar.",
          "4 − 3,5 = 0,5 **fark**",
          "Eksik değer = bilinen değer ± **fark**",
          "Eksik değer = 2,5 + 0,5 = **3,0**",
        ],
        ps: [
          "دوه معلوم ارزښتونه یو له بله منفي کړه.",
          "4 − 3.5 = 0.5 **توپیر**",
          "ورک ارزښت = معلوم ارزښت ± **توپیر**",
          "ورک ارزښت = 2.5 + 0.5 = **3.0**",
        ],
      },
    },
    { text: { fr: "2,5 ; **3** ; 3,5 ; 4", en: "2.5 ; **3** ; 3.5 ; 4", ar: "2.5 ; **3** ; 3.5 ; 4", fa: "2.5 ; **3** ; 3.5 ; 4", ti: "2.5 ; **3** ; 3.5 ; 4", uk: "2,5 ; **3** ; 3,5 ; 4", pt: "2,5 ; **3** ; 3,5 ; 4", so: "2.5 ; **3** ; 3.5 ; 4", tr: "2,5 ; **3** ; 3,5 ; 4", ps: "2.5 ; **3** ; 3.5 ; 4" } },
    { text: { fr: "", en: "", ar: "", fa: "", ti: "", uk: "", pt: "", so: "", tr: "", ps: "" } },
    {
      text: {
        fr: "Pas de valeurs consécutives",
        en: "No consecutive values",
        ar: "لا توجد قيم متتالية",
        fa: "بدون مقدارهای پشت سر هم",
        ti: "ተኸታታሊ ዋጋታት የለን",
        uk: "Немає сусідніх значень",
        pt: "Sem valores consecutivos",
        so: "Ma jiraan qiimeyaal isku xiga",
        tr: "Ardışık değer yok",
        ps: "پرله پسې ارزښتونه نشته",
      },
    },
    {
      text: {
        fr: "**...** ; 7,2 ; **...** ; 9,6",
        en: "**...** ; 7.2 ; **...** ; 9.6",
        ar: "**...** ; 7.2 ; **...** ; 9.6",
        fa: "**...** ; 7.2 ; **...** ; 9.6",
        ti: "**...** ; 7.2 ; **...** ; 9.6",
        uk: "**...** ; 7,2 ; **...** ; 9,6",
        pt: "**...** ; 7,2 ; **...** ; 9,6",
        so: "**...** ; 7.2 ; **...** ; 9.6",
        tr: "**...** ; 7,2 ; **...** ; 9,6",
        ps: "**...** ; 7.2 ; **...** ; 9.6",
      },
    },
    {
      items: {
        fr: [
          "Soustraire les deux valeurs connues.",
          "9,6 − 7,2 = 2,4",
          "Diviser par le **nombre d'espaces** entre eux. Le nombre d'espaces = nombre de valeurs manquantes **+ 1**.",
          "2,4 ÷ **2** = 1,2 **écart**",
          "Valeur manquante = valeur connue ± **écart**",
          "Valeurs manquantes : 7,2 + 1,2 = **8,4** et 9,6 − 1,2 = **6,0**",
        ],
        en: [
          "Subtract the two known values.",
          "9.6 − 7.2 = 2.4",
          "Divide by the **number of spaces** between them. Number of spaces = number of missing values **+ 1**.",
          "2.4 ÷ **2** = 1.2 **step**",
          "Missing value = known value ± **step**",
          "Missing values: 7.2 + 1.2 = **8.4** and 9.6 − 1.2 = **6.0**",
        ],
        ar: [
          "نطرح القيمتين المعروفتين.",
          "9.6 − 7.2 = 2.4",
          "نقسم على **عدد الفراغات** بينهما. عدد الفراغات = عدد القيم الناقصة **+ 1**.",
          "2.4 ÷ **2** = 1.2 **الفارق**",
          "القيمة الناقصة = القيمة المعروفة ± **الفارق**",
          "القيم الناقصة: 7.2 + 1.2 = **8.4** و 9.6 − 1.2 = **6.0**",
        ],
        fa: [
          "دو مقدار معلوم را از هم کم کن.",
          "9.6 − 7.2 = 2.4",
          "بر **تعداد فاصله‌ها** بین آن‌ها تقسیم کن. تعداد فاصله‌ها = تعداد مقدارهای گمشده **+ 1**.",
          "2.4 ÷ **2** = 1.2 **فاصله**",
          "مقدار گمشده = مقدار معلوم ± **فاصله**",
          "مقدارهای گمشده: 7.2 + 1.2 = **8.4** و 9.6 − 1.2 = **6.0**",
        ],
        ti: [
          "ክልተ ፍሉጣት ዋጋታት ንጉድል።",
          "9.6 − 7.2 = 2.4",
          "ብ**ብዝሒ ክፍተታት** ኣብ መንጎኦም ንኸፍል። ብዝሒ ክፍተታት = ብዝሒ ዝጎደሉ ዋጋታት **+ 1**።",
          "2.4 ÷ **2** = 1.2 **ፍልልይ**",
          "ዝጎደለ ዋጋ = ፍሉጥ ዋጋ ± **ፍልልይ**",
          "ዝጎደሉ ዋጋታት፦ 7.2 + 1.2 = **8.4** እና 9.6 − 1.2 = **6.0**",
        ],
        uk: [
          "Відняти два відомі значення.",
          "9,6 − 7,2 = 2,4",
          "Поділити на **кількість проміжків** між ними. Кількість проміжків = кількість пропущених значень **+ 1**.",
          "2,4 ÷ **2** = 1,2 **крок**",
          "Пропущене значення = відоме значення ± **крок**",
          "Пропущені значення: 7,2 + 1,2 = **8,4** і 9,6 − 1,2 = **6,0**",
        ],
        pt: [
          "Subtrair os dois valores conhecidos.",
          "9,6 − 7,2 = 2,4",
          "Dividir pelo **número de espaços** entre eles. Número de espaços = número de valores em falta **+ 1**.",
          "2,4 ÷ **2** = 1,2 **diferença**",
          "Valor em falta = valor conhecido ± **diferença**",
          "Valores em falta: 7,2 + 1,2 = **8,4** e 9,6 − 1,2 = **6,0**",
        ],
        so: [
          "Kala jar labada qiime ee la yaqaan.",
          "9.6 − 7.2 = 2.4",
          "U qaybi **tirada meelaha bannaan** ee u dhexeeya. Tirada meelaha = tirada qiimayaasha maqan **+ 1**.",
          "2.4 ÷ **2** = 1.2 **farqi**",
          "Qiimaha maqan = qiimaha la yaqaan ± **farqi**",
          "Qiimayaasha maqan: 7.2 + 1.2 = **8.4** iyo 9.6 − 1.2 = **6.0**",
        ],
        tr: [
          "Bilinen iki değeri çıkar.",
          "9,6 − 7,2 = 2,4",
          "Aralarındaki **boşluk sayısına** böl. Boşluk sayısı = eksik değer sayısı **+ 1**.",
          "2,4 ÷ **2** = 1,2 **fark**",
          "Eksik değer = bilinen değer ± **fark**",
          "Eksik değerler: 7,2 + 1,2 = **8,4** ve 9,6 − 1,2 = **6,0**",
        ],
        ps: [
          "دوه معلوم ارزښتونه یو له بله منفي کړه.",
          "9.6 − 7.2 = 2.4",
          "د هغوی ترمنځ د **تشو شمېر** باندې یې وویشه. د تشو شمېر = د ورکو ارزښتونو شمېر **+ 1**.",
          "2.4 ÷ **2** = 1.2 **توپیر**",
          "ورک ارزښت = معلوم ارزښت ± **توپیر**",
          "ورک ارزښتونه: 7.2 + 1.2 = **8.4** او 9.6 − 1.2 = **6.0**",
        ],
      },
    },
    { text: { fr: "**6** ; 7,2 ; **8,4** ; 9,6", en: "**6** ; 7.2 ; **8.4** ; 9.6", ar: "**6** ; 7.2 ; **8.4** ; 9.6", fa: "**6** ; 7.2 ; **8.4** ; 9.6", ti: "**6** ; 7.2 ; **8.4** ; 9.6", uk: "**6** ; 7,2 ; **8,4** ; 9,6", pt: "**6** ; 7,2 ; **8,4** ; 9,6", so: "**6** ; 7.2 ; **8.4** ; 9.6", tr: "**6** ; 7,2 ; **8,4** ; 9,6", ps: "**6** ; 7.2 ; **8.4** ; 9.6" } },
  ],
  consignes: {
    "a5-2-e1": { fr: "Classez du plus petit au plus grand : 2,5 ; 2,15 ; 2,51", en: "Order from smallest to largest: 2.5; 2.15; 2.51" },
    "a5-2-e2": { fr: "Donnez le terme manquant : 1,2 ; 1,5 ; ___ ; 2,1", en: "Give the missing term: 1.2; 1.5; ___; 2.1" },
    "a5-2-e3": { fr: "Classez du plus grand au plus petit : 0,3 ; 0,13 ; 0,31", en: "Order from largest to smallest: 0.3; 0.13; 0.31" },
  },
};
