import type { SubmoduleTrad } from "./trad-types";

const S = (fr: string, en: string, ar: string, fa: string, ti: string, uk: string, pt: string, so: string, tr: string, ps: string) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });
const A = (fr: string[], en: string[], ar: string[], fa: string[], ti: string[], uk: string[], pt: string[], so: string[], tr: string[], ps: string[]) =>
  ({ fr, en, ar, fa, ti, uk, pt, so, tr, ps });

export const TRAD_G5_5: SubmoduleTrad = {
  submoduleId: "G5-5",
  title: S(
      "Cylindre",
      "Cylinder",
      "الأسطوانة",
      "استوانه",
      "ሲሊንደር",
      "Циліндр",
      "Cilindro",
      "Silindar",
      "Silindir",
      "استوانه",
    ),
  blocks: [
    { text: S(
      "Volume du cylindre",
      "Volume of a cylinder",
      "حجم الأسطوانة",
      "حجم استوانه",
      "ናይ ሲሊንደር መጠን",
      "Об'єм циліндра",
      "Volume do cilindro",
      "Mugga silindar",
      "Silindirin hacmi",
      "د استوانې حجم",
    ) },
    { text: S(
      "Un cylindre fonctionne comme un prisme dont la base est un **disque**.",
      "A cylinder works like a prism whose base is a **disk**.",
      "الأسطوانة تعمل كمنشور قاعدته **قرص**.",
      "استوانه مانند منشوری است که قاعده‌اش یک **دیسک** است.",
      "ሲሊንደር ከም ፕሪዝም ይሰርሕ መሰረቱ **ዲስክ** እዩ።",
      "Циліндр працює як призма, основа якої — **диск**.",
      "Um cilindro funciona como um prisma cuja base é um **disco**.",
      "Silindar wuxuu u shaqeeyaa sida prisma aasaaskiisu yahay **disk**.",
      "Silindir, tabanı bir **disk** olan prizma gibi çalışır.",
      "استوانه لکه منشور کار کوي چې اساس یې **ډیسک** دی.",
    ) },
    {},
    { text: S(
      "Formule",
      "Formula",
      "الصيغة",
      "فرمول",
      "ቀመር",
      "Формула",
      "Fórmula",
      "Qaacidda",
      "Formül",
      "فارمول",
    ) },
    {
      label: S(
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
      "V = π × r² × h",
    ),
      items: A(
      ["π × r² est l'aire de la base.", "h est la hauteur du cylindre."],
      ["π × r² is the area of the base.", "h is the height of the cylinder."],
      ["π × r² هي مساحة القاعدة.", "h هو ارتفاع الأسطوانة."],
      ["π × r² مساحت قاعده است.", "h ارتفاع استوانه است."],
      ["π × r² ናይ መሰረት ስፍሓት እዩ።", "h ናይ ሲሊንደር ቁመት እዩ።"],
      ["π × r² — площа основи.", "h — висота циліндра."],
      ["π × r² é a área da base.", "h é a altura do cilindro."],
      ["π × r² waa bedka aasaaska.", "h waa dhererka silindar."],
      ["π × r² tabanın alanıdır.", "h silindirin yüksekliğidir."],
      ["π × r² د اساس مساحت دی.", "h د استوانې لوړوالی دی."],
    ),
    },
    { text: S(
      "Rayon 3 cm et hauteur 10 cm : V = π × 3² × 10 = 90π ≈ 282,6 cm³.",
      "Radius 3 cm and height 10 cm: V = π × 3² × 10 = 90π ≈ 282.6 cm³.",
      "نصف القطر 3 سم والارتفاع 10 سم: V = π × 3² × 10 = 90π ≈ 282,6 سم³.",
      "شعاع ۳ cm و ارتفاع ۱۰ cm: V = π × ۳² × ۱۰ = ۹۰π ≈ ۲۸۲٫۶ cm³.",
      "ራድየስ 3 cmን ቁመት 10 cm፦ V = π × 3² × 10 = 90π ≈ 282,6 cm³.",
      "Радіус 3 см і висота 10 см: V = π × 3² × 10 = 90π ≈ 282,6 см³.",
      "Raio 3 cm e altura 10 cm: V = π × 3² × 10 = 90π ≈ 282,6 cm³.",
      "Radius 3 cm iyo dherer 10 cm: V = π × 3² × 10 = 90π ≈ 282,6 cm³.",
      "Yarıçap 3 cm ve yükseklik 10 cm: V = π × 3² × 10 = 90π ≈ 282,6 cm³.",
      "شعاع ۳ cm او لوړوالی ۱۰ cm: V = π × ۳² × ۱۰ = ۹۰π ≈ ۲۸۲٫۶ cm³.",
    ) },
  ],
  consignes: {
    "g5-7-e1": { fr: "Cylindre r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3,14)", en: "Cylinder r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3.14)", ar: "أسطوانة r=2 سم، h=5 سم. V = π×4×5 ≈ ؟ (π≈3,14)", fa: "استوانه r=۲ cm، h=۵ cm. V = π×۴×۵ ≈ ؟ (π≈۳٫۱۴)", ti: "ሲሊንደር r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3,14)", uk: "Циліндр r=2 см, h=5 см. V = π×4×5 ≈ ? (π≈3,14)", pt: "Cilindro r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3,14)", so: "Silindar r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3,14)", tr: "Silindir r=2 cm, h=5 cm. V = π×4×5 ≈ ? (π≈3,14)", ps: "استوانه r=۲ cm، h=۵ cm. V = π×۴×۵ ≈ ؟ (π≈۳٫۱۴)" },
    "g5-7-e2": { fr: "Cylindre r=5 cm, h=10 cm. V ≈ ? (π≈3,14)", en: "Cylinder r=5 cm, h=10 cm. V ≈ ? (π≈3.14)", ar: "أسطوانة r=5 سم، h=10 سم. V ≈ ؟ (π≈3,14)", fa: "استوانه r=۵ cm، h=۱۰ cm. V ≈ ؟ (π≈۳٫۱۴)", ti: "ሲሊንደር r=5 cm, h=10 cm. V ≈ ? (π≈3,14)", uk: "Циліндр r=5 см, h=10 см. V ≈ ? (π≈3,14)", pt: "Cilindro r=5 cm, h=10 cm. V ≈ ? (π≈3,14)", so: "Silindar r=5 cm, h=10 cm. V ≈ ? (π≈3,14)", tr: "Silindir r=5 cm, h=10 cm. V ≈ ? (π≈3,14)", ps: "استوانه r=۵ cm، h=۱۰ cm. V ≈ ؟ (π≈۳٫۱۴)" },
    "g5-7-e3": { fr: "Cylindre r=3 cm, V = 141,3 cm³ (π≈3,14). h = ?", en: "Cylinder r=3 cm, V = 141.3 cm³ (π≈3.14). h = ?", ar: "أسطوانة r=3 سم، V = 141,3 سم³ (π≈3,14). h = ؟", fa: "استوانه r=۳ cm، V = ۱۴۱٫۳ cm³ (π≈۳٫۱۴). h = ؟", ti: "ሲሊንደር r=3 cm, V = 141,3 cm³ (π≈3,14). h = ?", uk: "Циліндр r=3 см, V = 141,3 см³ (π≈3,14). h = ?", pt: "Cilindro r=3 cm, V = 141,3 cm³ (π≈3,14). h = ?", so: "Silindar r=3 cm, V = 141,3 cm³ (π≈3,14). h = ?", tr: "Silindir r=3 cm, V = 141,3 cm³ (π≈3,14). h = ?", ps: "استوانه r=۳ cm، V = ۱۴۱٫۳ cm³ (π≈۳٫۱۴). h = ؟" },
    "g5-7-e4": { fr: "Cylindre r=1 cm, h=1 cm. V = π ≈ ? (π≈3,14)", en: "Cylinder r=1 cm, h=1 cm. V = π ≈ ? (π≈3.14)", ar: "أسطوانة r=1 سم، h=1 سم. V = π ≈ ؟ (π≈3,14)", fa: "استوانه r=۱ cm، h=۱ cm. V = π ≈ ؟ (π≈۳٫۱۴)", ti: "ሲሊንደር r=1 cm, h=1 cm. V = π ≈ ? (π≈3,14)", uk: "Циліндр r=1 см, h=1 см. V = π ≈ ? (π≈3,14)", pt: "Cilindro r=1 cm, h=1 cm. V = π ≈ ? (π≈3,14)", so: "Silindar r=1 cm, h=1 cm. V = π ≈ ? (π≈3,14)", tr: "Silindir r=1 cm, h=1 cm. V = π ≈ ? (π≈3,14)", ps: "استوانه r=۱ cm، h=۱ cm. V = π ≈ ؟ (π≈۳٫۱۴)" },
    "g5-7-e5": { fr: "Un cylindre de rayon 4 cm et hauteur 7 cm. V ≈ ? (π≈3,14)", en: "A cylinder of radius 4 cm and height 7 cm. V ≈ ? (π≈3.14)", ar: "أسطوانة نصف قطرها 4 سم وارتفاع 7 سم. V ≈ ؟ (π≈3,14)", fa: "استوانه‌ای به شعاع ۴ cm و ارتفاع ۷ cm. V ≈ ؟ (π≈۳٫۱۴)", ti: "ሲሊንደር ራድየስ 4 cmን ቁመት 7 cm. V ≈ ? (π≈3,14)", uk: "Циліндр радіусом 4 см і висотою 7 см. V ≈ ? (π≈3,14)", pt: "Um cilindro de raio 4 cm e altura 7 cm. V ≈ ? (π≈3,14)", so: "Silindar radius 4 cm iyo dherer 7 cm. V ≈ ? (π≈3,14)", tr: "Yarıçapı 4 cm ve yüksekliği 7 cm silindir. V ≈ ? (π≈3,14)", ps: "د ۴ cm شعاع او ۷ cm لوړوالي استوانه. V ≈ ؟ (π≈۳٫۱۴)" },
  },
};
