export {
  CORRECTION_BORDER as LECTURE_CORRECTION_BORDER,
  CORRECTION_BG as LECTURE_CORRECTION_BG,
  CORRECTION_TEXT as LECTURE_CORRECTION_TEXT,
  CORRECTION_CARD as LECTURE_CORRECTION_CARD,
  CORRECTION_BUTTON as LECTURE_CORRECTION_BUTTON,
} from "@/components/correction-styles";
