import type { MathModule } from "./types";

const sm = (code: string, title: string) => ({
  id: code.replace(/\./g, "-"),
  code,
  title,
});

/**
 * Modules algèbre A1–A13 (A2 = add./soust.), géométrie G1–G10, statistiques S1–S2.
 * Renumérotation : ancien A2→A3 … ancien A12→A13.
 */
export const MATH_MODULES: MathModule[] = [
  {
    id: "A1",
    code: "A1",
    title: "Nombres naturels",
    branch: "algebra",
    prerequisiteIds: [],
    submodules: [
      sm("A1.1", "Compter en français"),
      sm("A1.2", "Valeur positionnelle"),
      sm("A1.3", "Comparer les nombres"),
      sm("A1.4", "Droite numérique"),
      sm("A1.5", "Suites numériques"),
    ],
  },
  {
    id: "A2",
    code: "A2",
    title: "Addition et soustraction",
    branch: "algebra",
    prerequisiteIds: ["A1"],
    description: "Calcul posé et mental : retenue, emprunt, estimation (PER / CSC).",
    submodules: [
      sm("A2.1", "Addition"),
      sm("A2.2", "Soustraction"),
      sm("A2.3", "Estimation et arrondi"),
      sm("A2.4", "Problèmes"),
    ],
  },
  {
    id: "A3",
    code: "A3",
    title: "Multiplication et division",
    branch: "algebra",
    prerequisiteIds: ["A2"],
    submodules: [
      sm("A3.1", "Multiplication"),
      sm("A3.2", "Multiplication en colonnes"),
      sm("A3.3", "Division"),
      sm("A3.4", "Division en colonnes"),
      sm("A3.5", "Multiples et diviseurs"),
      sm("A3.6", "PGCD et PPCM"),
    ],
  },
  {
    id: "A4",
    code: "A4",
    title: "Fractions",
    branch: "algebra",
    prerequisiteIds: ["A3"],
    submodules: [
      sm("A4.1", "Notion et représentation"),
      sm("A4.2", "Fractions équivalentes"),
      sm("A4.3", "Comparaison"),
      sm("A4.4", "Addition et soustraction"),
      sm("A4.5", "Multiplication"),
      sm("A4.6", "Division "),
      sm("A4.7", "Fractions et décimaux"),
    ],
  },
  {
    id: "A5",
    code: "A5",
    title: "Nombres décimaux",
    branch: "algebra",
    prerequisiteIds: ["A1", "A4"],
    description: "Prérequis : A1 et fin de A4 (A4.8).",
    submodules: [
      sm("A5.1", "Lire et écrire"),
      sm("A5.2", "Suite de nombres à virgule"),
      sm("A5.3", "Arrondir"),
      sm("A5.4", "Addition et soustraction"),
      sm("A5.5", "Multiplication"),
      sm("A5.6", "Division"),
    ],
  },
  {
    id: "A6",
    code: "A6",
    title: "Pourcentages et proportions",
    branch: "algebra",
    prerequisiteIds: ["A5"],
    submodules: [
      sm("A6.1", "Notion de pourcentage"),
      sm("A6.2", "Pourcentage d'un nombre"),
      sm("A6.3", "Augmentation et réduction"),
    ],
  },
  {
    id: "A7",
    code: "A7",
    title: "Nombres relatifs",
    branch: "algebra",
    prerequisiteIds: ["A1", "A3"],
    submodules: [
      sm("A7.1", "Les nombres relatifs"),
      sm("A7.2", "Comparer"),
      sm("A7.3", "Addition et soustraction"),
      sm("A7.4", "Multiplication et division"),
    ],
  },
  {
    id: "A8",
    code: "A8",
    title: "Puissances et racines",
    branch: "algebra",
    prerequisiteIds: ["A3"],
    submodules: [
      sm("A8.1", "Notion et représentation"),
      sm("A8.2", "Calcul de puissances"),
      sm("A8.3", "Puissances de 10"),
      sm("A8.4", "Racine carrée"),
      sm("A8.5", "Priorité des opérations"),
    ],
  },
  {
    id: "A9",
    code: "A9",
    title: "Expressions algébriques",
    branch: "algebra",
    prerequisiteIds: ["A5", "A7"],
    submodules: [
      sm("A9.1", "Variable et inconnue"),
      sm("A9.2", "Lire et écrire une expression"),
      sm("A9.3", "Substitution"),
      sm("A9.4", "Réduction"),
      sm("A9.5", "Développement simple"),
      sm("A9.6", "Factorisation simple"),
    ],
  },
  {
    id: "A10",
    code: "A10",
    title: "Équations du 1er degré",
    branch: "algebra",
    prerequisiteIds: ["A9"],
    submodules: [
      sm("A10.1", "Principe équation"),
      sm("A10.2", "ax = b"),
      sm("A10.3", "ax + b = c"),
      sm("A10.4", "Parenthèses"),
      sm("A10.5", "Équations avec fractions"),
      sm("A10.6", "Problèmes concrets"),
    ],
  },
  {
    id: "A11",
    code: "A11",
    title: "Inéquations",
    branch: "algebra",
    prerequisiteIds: ["A10"],
    submodules: [
      sm("A11.1", "Symboles et droite"),
      sm("A11.2", "Résolution simple"),
      sm("A11.3", "Représentation graphique"),
    ],
  },
  {
    id: "A12",
    code: "A12",
    title: "Systèmes d'équations",
    branch: "algebra",
    prerequisiteIds: ["A10"],
    submodules: [
      sm("A12.1", "Substitution"),
      sm("A12.2", "Addition / soustraction"),
      sm("A12.3", "Problèmes à 2 inconnues"),
    ],
  },
  {
    id: "A13",
    code: "A13",
    title: "Fonctions (introduction)",
    branch: "algebra",
    prerequisiteIds: ["A10", "A7"],
    submodules: [
      sm("A13.1", "Notion de fonction"),
      sm("A13.2", "Tableau de valeurs"),
      sm("A13.3", "Graphique dans un repère"),
      sm("A13.4", "Linéaire f(x)=ax"),
      sm("A13.5", "Affine f(x)=ax+b"),
      sm("A13.6", "Pente et ordonnée"),
      sm("A13.7", "Lecture graphique"),
    ],
  },
  {
    id: "G1",
    code: "G1",
    title: "Formes planes et reconnaissance visuelle",
    branch: "geometry",
    prerequisiteIds: [],
    submodules: [
      sm("G1.1", "Formes (polygones et cercle)"),
      sm("G1.2", "Propriétés et symétrie"),
      sm("G1.3", "Propriétés des formes"),
      sm("G1.4", "Angles"),
    ],
  },
  {
    id: "G2",
    code: "G2",
    title: "Périmètres",
    branch: "geometry",
    prerequisiteIds: ["G1", "A3"],
    algebraRefs: ["A3"],
    submodules: [
      sm("G2.1", "Carré"),
      sm("G2.2", "Rectangle"),
      sm("G2.3", "Triangle"),
      sm("G2.4", "Polygones réguliers"),
      sm("G2.5", "Cercle et π"),
    ],
  },
  {
    id: "G3",
    code: "G3",
    title: "Aires des figures planes",
    branch: "geometry",
    prerequisiteIds: ["G1", "G2", "A3", "A5"],
    algebraRefs: ["A3", "A5", "A8", "A4"],
    submodules: [
      sm("G3.1", "Carré"),
      sm("G3.2", "Rectangle"),
      sm("G3.3", "Triangle"),
      sm("G3.4", "Parallélogramme"),
      sm("G3.5", "Trapèze"),
      sm("G3.6", "Disque"),
      sm("G3.7", "Figures composées"),
      sm("G3.8", "Figures à trous"),
    ],
  },
  {
    id: "G4",
    code: "G4",
    title: "Constructions géométriques",
    branch: "geometry",
    prerequisiteIds: ["G1"],
    submodules: [
      sm("G4.1", "Outils : règle, compas…"),
      sm("G4.2", "Perpendiculaire, parallèle"),
      sm("G4.3", "Triangles"),
      sm("G4.4", "Carré, rectangle, losange"),
      sm("G4.5", "Cercle de rayon donné"),
      sm("G4.6", "Médiatrice, bissectrice…"),
    ],
  },
  {
    id: "G5",
    code: "G5",
    title: "Transformations du plan",
    branch: "geometry",
    prerequisiteIds: ["G1", "G4", "A3"],
    algebraRefs: ["A3", "A6"],
    submodules: [
      sm("G5.1", "Symétrie axiale"),
      sm("G5.2", "Symétrie centrale"),
      sm("G5.3", "Translation"),
      sm("G5.4", "Rotation"),
      sm("G5.5", "Homothétie"),
      sm("G5.6", "Isométries"),
      sm("G5.7", "Homothétie et longueurs"),
    ],
  },
  {
    id: "G6",
    code: "G6",
    title: "Échelles et plans",
    branch: "geometry",
    prerequisiteIds: ["G5", "A6"],
    algebraRefs: ["A3", "A6", "A5"],
    submodules: [
      sm("G6.1", "Notion d'échelle"),
      sm("G6.2", "Lire une échelle"),
      sm("G6.3", "Distance réelle"),
      sm("G6.4", "Représentation"),
      sm("G6.5", "Agrandir / réduire"),
    ],
  },
  {
    id: "G7",
    code: "G7",
    title: "Théorème de Pythagore",
    branch: "geometry",
    prerequisiteIds: ["G1", "A8"],
    algebraRefs: ["A8", "A5"],
    submodules: [
      sm("G7.1", "Triangle rectangle"),
      sm("G7.2", "Énoncé a²+b²=c²"),
      sm("G7.3", "Hypoténuse"),
      sm("G7.4", "Cathète"),
      sm("G7.5", "Réciproque"),
      sm("G7.6", "Applications"),
    ],
  },
  {
    id: "G8",
    code: "G8",
    title: "Solides et volumes",
    branch: "geometry",
    prerequisiteIds: ["G3", "G7", "A8"],
    algebraRefs: ["A3", "A8", "A4", "A5", "G3"],
    submodules: [
      sm("G8.1", "Reconnaître les solides"),
      sm("G8.2", "Patrons"),
      sm("G8.3", "Aires latérale et totale"),
      sm("G8.4", "Volume du cube"),
      sm("G8.5", "Pavé droit"),
      sm("G8.6", "Prisme"),
      sm("G8.7", "Cylindre"),
      sm("G8.8", "Pyramide"),
      sm("G8.9", "Cône et sphère"),
      sm("G8.10", "Conversions de volumes"),
    ],
  },
  {
    id: "G9",
    code: "G9",
    title: "Lecture et construction de graphiques",
    branch: "geometry",
    prerequisiteIds: ["A5", "A6"],
    algebraRefs: ["A6", "A5", "A7", "A13"],
    submodules: [
      sm("G9.1", "Repère cartésien"),
      sm("G9.2", "Lire / placer des points"),
      sm("G9.3", "Diagramme en bâtons"),
      sm("G9.4", "Diagramme en secteurs"),
      sm("G9.5", "Courbes"),
      sm("G9.6", "Construire bâtons"),
      sm("G9.7", "Construire secteurs"),
      sm("G9.8", "Interpréter"),
    ],
  },
  {
    id: "G10",
    code: "G10",
    title: "Trigonométrie (introduction)",
    branch: "geometry",
    prerequisiteIds: ["G7", "A10", "A5"],
    algebraRefs: ["A8", "A10", "A5"],
    submodules: [
      sm("G10.1", "Rappel Pythagore"),
      sm("G10.2", "sin, cos, tan"),
      sm("G10.3", "Calculer un rapport"),
      sm("G10.4", "Angle à partir du rapport"),
      sm("G10.5", "Côté inconnu"),
      sm("G10.6", "Applications"),
    ],
  },
  {
    id: "RG",
    code: "RG",
    title: "Révision — Géométrie",
    branch: "geometry",
    prerequisiteIds: ["G1"],
    submodules: [
      sm("RG.1",  "Révision G1"),
      sm("RG.2",  "Révision G2"),
      sm("RG.3",  "Révision G3"),
      sm("RG.4",  "Révision G4"),
      sm("RG.5",  "Révision G5"),
      sm("RG.6",  "Révision G6"),
      sm("RG.7",  "Révision G7"),
      sm("RG.8",  "Révision G8"),
      sm("RG.9",  "Révision G9"),
      sm("RG.10", "Révision G10"),
    ],
  },
  {
    id: "S1",
    code: "S1",
    title: "Statistiques descriptives",
    branch: "stats",
    prerequisiteIds: ["A3", "A6", "G9"],
    algebraRefs: ["A3", "A6", "G9"],
    submodules: [
      sm("S1.1", "Collecte et tableaux"),
      sm("S1.2", "Moyenne"),
      sm("S1.3", "Médiane"),
      sm("S1.4", "Mode"),
      sm("S1.5", "Étendue"),
      sm("S1.6", "Diagrammes (lien G9)"),
      sm("S1.7", "Lecture critique"),
    ],
  },
  {
    id: "S2",
    code: "S2",
    title: "Probabilités",
    branch: "stats",
    prerequisiteIds: ["A4", "A6"],
    algebraRefs: ["A4", "A6"],
    submodules: [
      sm("S2.1", "Expérience, univers"),
      sm("S2.2", "Probabilité classique"),
      sm("S2.3", "Complémentaire"),
      sm("S2.4", "Impossible / certain"),
      sm("S2.5", "Arbre à deux étapes"),
      sm("S2.6", "Simulation et fréquences"),
      sm("S2.7", "Intro combinaisons"),
    ],
  },
];

export const MATH_ALGEBRA_ORDER = MATH_MODULES.filter((m) => m.branch === "algebra").map(
  (m) => m.id,
);

export const MATH_GEOMETRY_TAB_ORDER = [
  ...MATH_MODULES.filter((m) => m.branch === "geometry").map((m) => m.id),
  "S1",
  "S2",
];

/** Ancienne numérotation A2–A12 → nouvelle A3–A13 (après insertion du nouvel A2). */
export const ALGEBRA_LEGACY_ID_MAP: Record<string, string> = {
  A1: "A1",
  A2: "A3",
  A3: "A4",
  A4: "A5",
  A5: "A6",
  A6: "A7",
  A7: "A8",
  A8: "A9",
  A9: "A10",
  A10: "A11",
  A11: "A12",
  A12: "A13",
};

export function getMathModule(id: string): MathModule | undefined {
  return MATH_MODULES.find((m) => m.id === id);
}

export function prerequisitesMet(
  module: MathModule,
  completed: Set<string>,
): { ok: true } | { ok: false; missing: string[] } {
  const missing = module.prerequisiteIds.filter((id) => !completed.has(id));
  if (missing.length === 0) return { ok: true };
  return { ok: false, missing };
}
