import type { MathSubmoduleLesson } from "./math-a1-types";

export const MATH_A2_1_LESSON: MathSubmoduleLesson = {
    submoduleId: "A2-1",
    submoduleCode: "A2.1",
    theory: {
      title: {
        fr: "Addition",
        en: "Addition",
        ar: "الجمع",
        fa: "جمع",
        ti: "ድምር",
        uk: "Додавання",
      },
      blocks: [
        { type: "plain", fr: "L'addition permet de réunir plusieurs quantités ensemble. Le signe est « + » (plus). Les nombres à additionner sont les termes. Le résultat est la somme.", pivot: { en: "Addition combines quantities. Sign: +. Numbers: terms. Result: sum.", ar: "الجمع يجمع عدة كميات. الرمز « + ». الأعداد تسمى الحدود. الناتج هو المجموع.", fa: "جمع چند مقدار را با هم ترکیب می‌کند. علامت « + ». اعداد: جملات. نتیجه: مجموع.", uk: "Додавання об'єднує кілька величин. Знак « + ». Числа: доданки. Результат: сума." } },
        { type: "rule", titleFr: "Propriétés de l'addition", itemsFr: [
          "**Commutativité** : l'ordre des termes ne change pas la somme. Ex. : 57 + 49 = 49 + 57 = 106.",
          "**Associativité** : on peut additionner plus de deux termes dans l'ordre voulu. Ex. : 15 + 37 + 22 = 74.",
        ], pivot: { en: { title: "Properties of addition", items: ["Commutativity: changing order doesn't change the sum. E.g. 57 + 49 = 49 + 57.", "Associativity: can add more than two terms in any order. E.g. 15 + 37 + 22 = 74."] } } },
        { type: "heading", fr: "Addition en colonnes — étapes" },
        { type: "rule", titleFr: "Comment additionner en colonnes", itemsFr: [
          "Écrivez les nombres en alignant **U** (unités), **D** (dizaines), **C** (centaines).",
          "Commencez par additionner les **unités**.",
          "Si la somme dépasse 9, posez le chiffre des unités et **retenez** le chiffre des dizaines.",
          "Continuez avec les **dizaines**, puis les **centaines**, en ajoutant la retenue.",
        ], pivot: { en: { title: "How to add in columns", items: ["Align U (units), D (tens), C (hundreds).", "Start by adding the units.", "If the sum exceeds 9, write the units digit and carry the tens digit.", "Continue with tens, then hundreds, adding the carry each time."] } } },
        { type: "example", fr: "579 + 24 → U: 9+4=13 (pose 3, retient 1) → D: 1+7+2=10 (pose 0, retient 1) → C: 1+5=6 → Résultat : 603", pivot: { en: "579 + 24 → U: 9+4=13 (write 3, carry 1) → D: 1+7+2=10 (write 0, carry 1) → C: 1+5=6 → Result: 603" } },
      ],
      paragraphs: {
        fr: [
          "L'addition permet de réunir plusieurs quantités. Le signe de l'addition est « + » (plus). Les nombres à additionner sont les termes. Le résultat de l'addition est la somme.",
          "Propriété 1 — Commutativité : si l'on change l'ordre des termes d'une addition, la somme ne change pas. Exemple : 57 + 49 = 49 + 57 = 106.",
          "Propriété 2 — Associativité : on peut additionner plus de deux termes dans l'ordre que l'on veut. Exemple : 15 + 37 + 22 = 52 + 22 = 74.",
          "Addition en colonnes : écrivez les nombres en alignant les unités, les dizaines, les centaines. Commencez par additionner les unités. Si la somme dépasse 9, retenez le chiffre des dizaines (retenue). Continuez avec les dizaines, puis les centaines.",
          "Exemple : 579 + 24 → unités : 9 + 4 = 13 (on pose 3, on retient 1) → dizaines : 1 + 7 + 2 = 10 (on pose 0, on retient 1) → centaines : 1 + 5 = 6 → résultat : 603.",
        ],
        en: [
          "Addition combines several quantities. The addition sign is « + » (plus). The numbers being added are called terms. The result is the sum.",
          "Property 1 — Commutativity: changing the order of the terms does not change the sum. Example: 57 + 49 = 49 + 57 = 106.",
          "Property 2 — Associativity: you can add more than two terms in any order. Example: 15 + 37 + 22 = 74.",
          "Column addition: write the numbers aligned by units, tens, hundreds. Start with the units. If the sum exceeds 9, carry the tens digit. Then do the tens, then the hundreds.",
          "Example: 579 + 24 → units: 9 + 4 = 13 (write 3, carry 1) → tens: 1 + 7 + 2 = 10 (write 0, carry 1) → hundreds: 1 + 5 = 6 → result: 603.",
        ],
        ar: [
          "الجمع يجمع عدة كميات معًا. علامة الجمع « + » (زائد). الأعداد المجموعة تسمى الحدود. الناتج يسمى المجموع.",
          "الخاصية 1 — الإبدال: تغيير ترتيب الحدود لا يغير المجموع. مثال: 57 + 49 = 49 + 57 = 106.",
          "الخاصية 2 — التجميع: يمكن جمع أكثر من حدين بأي ترتيب. مثال: 15 + 37 + 22 = 74.",
          "الجمع في أعمدة: اكتب الأعداد محاذيًا الآحاد والعشرات والمئات. ابدأ بجمع الآحاد. إذا تجاوز المجموع 9، احمل رقم العشرات. ثم العشرات، ثم المئات.",
          "مثال: 579 + 24 → آحاد: 9 + 4 = 13 (اكتب 3 واحمل 1) → عشرات: 1 + 7 + 2 = 10 (اكتب 0 واحمل 1) → مئات: 1 + 5 = 6 → الناتج: 603.",
        ],
        fa: [
          "جمع چند مقدار را با هم ترکیب می‌کند. علامت جمع « + » است. اعداد جمع‌شونده را جملات و نتیجه را مجموع می‌نامند.",
          "ویژگی ۱ — جابجایی: تغییر ترتیب مجموع را تغییر نمی‌دهد. مثال: ۵۷ + ۴۹ = ۴۹ + ۵۷ = ۱۰۶.",
          "ویژگی ۲ — انجمنی: می‌توان بیش از دو جمله را به هر ترتیبی جمع کرد. مثال: ۱۵ + ۳۷ + ۲۲ = ۷۴.",
          "جمع ستونی: اعداد را با تراز کردن یکان، دهگان، صدگان بنویسید. از یکان‌ها شروع کنید. اگر مجموع از ۹ بیشتر شد، نقل دهید. سپس دهگان‌ها و صدگان‌ها.",
          "مثال: ۵۷۹ + ۲۴ → یکان: ۹ + ۴ = ۱۳ (بنویس ۳، نقل ۱) → دهگان: ۱ + ۷ + ۲ = ۱۰ (بنویس ۰، نقل ۱) → صدگان: ۱ + ۵ = ۶ → نتیجه: ۶۰۳.",
        ],
        ti: [
          "ምደማር ብዙ መጠናት ሓቢሩ ይሰርዕ። ምልክት ምደማር « + » (ደሚርካ) እዩ። ዝጽምሙ ቁጽሪታት ድምር ይፍጠር።",
          "ኣቃውማ ፩ — ቅደም-ሰዓበ: ቅደም ምቕያር ድምር ኣይቅይርን። ኣብነት: 57 + 49 = 49 + 57 = 106.",
          "ኣቃውማ ፪ — ምጽምባር: ዝበዝሑ ቁጽርታት ብዝደለዮ ቅደም ክድምር ይከኣል። ኣብነት: 15 + 37 + 22 = 74.",
          "ኣብ ዓምዲ ምደማር: ቁጽርታት ኣሃዱ፡ ዓሰርተ፡ ሚእቲ ብምስልሳልና። ካብ ኣሃዱ ጀምር። ውጽኢቱ ካብ 9 ዝበዝሕ እንተኾነ ሃሊዝ።",
          "ኣብነት: 579 + 24 → ኣሃዱ: 9 + 4 = 13 (3 ጽሓፍ፡ 1 ሃሊዝ) → ዓሰርተ: 1+7+2=10 (0 ጽሓፍ፡ 1 ሃሊዝ) → ሚእቲ: 1+5=6 → ውጽኢት: 603.",
        ],
        uk: [
          "Додавання об'єднує кілька величин. Знак « + » (плюс). Числа — доданки. Результат — сума.",
          "Властивість 1 — Комутативність: зміна порядку не змінює суму. Приклад: 57 + 49 = 49 + 57 = 106.",
          "Властивість 2 — Асоціативність: можна додавати більше двох доданків у будь-якому порядку. Приклад: 15 + 37 + 22 = 74.",
          "Додавання в стовпчик: вирівнюйте одиниці, десятки, сотні. Починайте з одиниць. Якщо сума > 9, перенесіть. Потім десятки та сотні.",
          "Приклад: 579 + 24 → одиниці: 9+4=13 (пишемо 3, переносимо 1) → десятки: 1+7+2=10 (пишемо 0, переносимо 1) → сотні: 1+5=6 → результат: 603.",
        ],
      },
    },
    exercises: [
      { id: "a2-1-e1", promptFr: "Quel est le résultat de 57 + 49 ?",                         type: "number",     acceptable: ["106"] },
      { id: "a2-1-e2", promptFr: "Quel est le résultat de 348 + 276 ?",                        type: "number",     acceptable: ["624"] },
      { id: "a2-1-e3", promptFr: "Comment appelle-t-on le résultat d'une addition ?",          type: "short_text", acceptable: ["somme", "la somme"] },
      { id: "a2-1-e4", promptFr: "Vrai ou faux : 84 + 37 = 37 + 84 ?",                        type: "short_text", acceptable: ["vrai", "true"] },
      { id: "a2-1-e5", promptFr: "Calculez 579 + 24.",                                         type: "number",     acceptable: ["603"] },
    ],
    exercisePool: [
      { id: "a21-p1",  promptFr: "Calculez 57 + 49.",          type: "number", acceptable: ["106"] },
      { id: "a21-p2",  promptFr: "Calculez 348 + 276.",        type: "number", acceptable: ["624"] },
      { id: "a21-p3",  promptFr: "Calculez 579 + 24.",         type: "number", acceptable: ["603"] },
      { id: "a21-p4",  promptFr: "Calculez 435 + 187.",        type: "number", acceptable: ["622"] },
      { id: "a21-p5",  promptFr: "Calculez 264 + 358.",        type: "number", acceptable: ["622"] },
      { id: "a21-p6",  promptFr: "Calculez 709 + 145.",        type: "number", acceptable: ["854"] },
      { id: "a21-p7",  promptFr: "Calculez 192 + 308.",        type: "number", acceptable: ["500"] },
      { id: "a21-p8",  promptFr: "Calculez 1 245 + 378.",      type: "number", acceptable: ["1623"] },
      { id: "a21-p9",  promptFr: "Calculez 863 + 457.",        type: "number", acceptable: ["1320"] },
      { id: "a21-p10", promptFr: "Calculez 75 + 26.",          type: "number", acceptable: ["101"] },
      { id: "a21-p11", promptFr: "Calculez 500 + 298.",        type: "number", acceptable: ["798"] },
      { id: "a21-p12", promptFr: "Calculez 1 382 + 724.",      type: "number", acceptable: ["2106"] },
      { id: "a21-p13", promptFr: "Calculez 15 + 37 + 22.",     type: "number", acceptable: ["74"] },
      { id: "a21-p14", promptFr: "Calculez 120 + 45 + 38.",    type: "number", acceptable: ["203"] },
      { id: "a21-p15", promptFr: "Quel terme manque ? 56 + ? = 100", type: "number", acceptable: ["44"] },
      { id: "a21-p16", promptFr: "Quel terme manque ? 237 + ? = 500", type: "number", acceptable: ["263"] },
      { id: "a21-p17", promptFr: "Calculez 999 + 1.",          type: "number", acceptable: ["1000"] },
      { id: "a21-p18", promptFr: "Calculez 3 456 + 1 544.",    type: "number", acceptable: ["5000"] },
    ],
    poolSize: 5,
  };
