import type { MathSubmoduleLesson } from "./math-a1-types";

export const MATH_A5_5_LESSON: MathSubmoduleLesson = {
    submoduleId: "A5-5",
    submoduleCode: "A5.5",
    theory: {
      title: { fr: "Multiplication de décimaux", en: "Multiplication of decimals", ar: "ضرب الأعداد العشرية", fa: "ضرب اعشار", ti: "ዘርፊ ቁጽሪ ቪርጉላ", uk: "Множення десяткових" },
      blocks: [
        { type: "heading", fr: "Méthode en 4 étapes", black: true },
        { type: "highlight", fr: "Principe" },
        {
          type: "section", labelFr: "", itemsFr: [
            "1. **Enlever les virgules** des deux facteurs.",
            "2. **Multiplier** comme des entiers (en colonnes).",
            "3. **Compter** le total de décimales dans les deux facteurs.",
            "4. **Replacer la virgule** dans le résultat.",
          ],
        },
        {
          type: "mul2_step_cards",
          a: [0, 0, 3, 1, 4],
          b: [0, 0, 0, 2, 5],
          result: 7850,
          steps: [
            {
              numFr: "1. Poser sans virgule",
              textsFr: ["3,14 × 2,5 → on pose 314 × 25 (virgules supprimées)."],
              carries1:  [null, null, null, null, null],
              carries2:  [null, null, null, null, null],
              p1:        [null, null, null, null, null],
              p2shifted: [null, null, null, null, null],
              res:       [null, null, null, null, null],
            },
            {
              numFr: "2. 314 × 5 = 1 570",
              textsFr: [
                "5 × 4 = 20 → pose 0, retient 2",
                "5 × 1 = 5 + 2 = 7 → pose 7",
                "5 × 3 = 15 → pose 5, retient 1",
                "1er sous-total : 1 570",
              ],
              carries1:  [null, 1, null, 2, null],
              carries2:  [null, null, null, null, null],
              p1:        [null, 1, 5, 7, 0],
              p2shifted: [null, null, null, null, null],
              res:       [null, null, null, null, null],
            },
            {
              numFr: "3. 314 × 20 = 6 280",
              textsFr: [
                "2 × 4 = 8,   2 × 1 = 2,   2 × 3 = 6",
                "Décaler d'une colonne (× dizaines) → 6 280",
              ],
              carries1:  [null, 1, null, 2, null],
              carries2:  [null, null, null, null, null],
              p1:        [null, 1, 5, 7, 0],
              p2shifted: [null, 6, 2, 8, 0],
              res:       [null, null, null, null, null],
            },
            {
              numFr: "4. 1 570 + 6 280 = 7 850",
              textsFr: ["On additionne les deux sous-totaux."],
              carries1:  [null, 1, null, 2, null],
              carries2:  [null, null, null, null, null],
              p1:        [null, 1, 5, 7, 0],
              p2shifted: [null, 6, 2, 8, 0],
              res:       [null, 7, 8, 5, 0],
            },
            {
              numFr: "5. Replacer la virgule",
              textsFr: [
                "3,14 → 2 décimales   +   2,5 → 1 décimale   =   3 décimales au total",
                "7 850 → virgule 3 rangs avant la fin → 7,850 → 7,85",
              ],
              carries1:  [null, 1, null, 2, null],
              carries2:  [null, null, null, null, null],
              p1:        [null, 1, 5, 7, 0],
              p2shifted: [null, 6, 2, 8, 0],
              res:       [null, 7, 8, 5, 0],
            },
          ],
        },
        { type: "note", fr: "3,14 × 2,5 = 7,85" },
        { type: "plain", fr: "" },
        { type: "heading", fr: "Astuces avec certains facteurs", black: true },
        {
          type: "table",
          headersFr: ["Facteur", "Astuce", "Exemple"],
          accentHeader: true,
          rows: [
            ["× 0,5",   "÷ 2", "40 × 0,5 = 20"],
            ["× 0,25",  "÷ 4", "80 × 0,25 = 20"],
            ["× 0,2",   "÷ 5", "35 × 0,2 = 7"],
            ["× 0,125", "÷ 8", "24 × 0,125 = 3"],
          ],
        },
      ],
      paragraphs: { fr: [] },
    },
    exercises: [],
    exercisePool: [
      { id: "a5-5-p1", promptFr: "Calculez 4,149 × 8,4.", type: "short_text", acceptable: ["34,8516", "34.8516"] },
      { id: "a5-5-p2", promptFr: "Calculez 38,99 × 0,15.", type: "short_text", acceptable: ["5,8485", "5.8485"] },
      { id: "a5-5-p3", promptFr: "Calculez 725,2 × 65.", type: "short_text", acceptable: ["47138", "47138,0", "47138.0"] },
      { id: "a5-5-p4", promptFr: "Calculez 43,2 × 9,1.", type: "short_text", acceptable: ["393,12", "393.12"] },
      { id: "a5-5-p5", promptFr: "Calculez 3853 × 0,34.", type: "short_text", acceptable: ["1310,02", "1310.02"] },
      { id: "a5-5-p6", promptFr: "Calculez 89,98 × 6,1.", type: "short_text", acceptable: ["548,878", "548.878"] },
      { id: "a5-5-p7", promptFr: "Calculez 496,9 × 8,7.", type: "short_text", acceptable: ["4323,03", "4323.03"] },
      { id: "a5-5-p8", promptFr: "Calculez 10,5 × 5,2.", type: "short_text", acceptable: ["54,6", "54.6", "54,60", "54.60"] },
      { id: "a5-5-p9", promptFr: "Calculez 9,6 × 0,79.", type: "short_text", acceptable: ["7,584", "7.584"] },
      { id: "a5-5-p10", promptFr: "Calculez 10 × 0,125 (astuce : ÷ 8).", type: "short_text", acceptable: ["1,25", "1.25"] },
      { id: "a5-5-p11", promptFr: "Calculez 2 × 0,001.", type: "short_text", acceptable: ["0,002", "0.002"] },
      { id: "a5-5-p12", promptFr: "Calculez 6 × 0,05 (astuce : ÷ 20).", type: "short_text", acceptable: ["0,3", "0.3"] },
      { id: "a5-5-p13", promptFr: "Calculez 7 × 0,125 (astuce : ÷ 8).", type: "short_text", acceptable: ["0,875", "0.875"] },
      { id: "a5-5-p14", promptFr: "Calculez 6 × 0,01.", type: "short_text", acceptable: ["0,06", "0.06"] },
      { id: "a5-5-p15", promptFr: "Calculez 11 × 0,5 (astuce : ÷ 2).", type: "short_text", acceptable: ["5,5", "5.5"] },
      { id: "a5-5-p16", promptFr: "Calculez 10 × 0,001.", type: "short_text", acceptable: ["0,01", "0.01"] },
      { id: "a5-5-p17", promptFr: "Calculez 2 × 0,25 (astuce : ÷ 4).", type: "short_text", acceptable: ["0,5", "0.5"] },
      { id: "a5-5-p18", promptFr: "Calculez 2 × 0,2 (astuce : ÷ 5).", type: "short_text", acceptable: ["0,4", "0.4"] },
      { id: "a5-5-p19", promptFr: "Calculez 12 × 0,25 (astuce : ÷ 4).", type: "number", acceptable: ["3"] },
      { id: "a5-5-p20", promptFr: "Calculez 6 × 0,001.", type: "short_text", acceptable: ["0,006", "0.006"] },
      { id: "a5-5-p21", promptFr: "Calculez 8 × 0,2 (astuce : ÷ 5).", type: "short_text", acceptable: ["1,6", "1.6"] },
      { id: "a5-5-p22", promptFr: "Calculez 12 × 0,5 (astuce : ÷ 2).", type: "number", acceptable: ["6"] },
      { id: "a5-5-p23", promptFr: "Calculez 7 × 0,1.", type: "short_text", acceptable: ["0,7", "0.7"] },
      { id: "a5-5-p24", promptFr: "Calculez 3 × 0,25 (astuce : ÷ 4).", type: "short_text", acceptable: ["0,75", "0.75"] },
      { id: "a5-5-p25", promptFr: "Calculez 9 × 0,5 (astuce : ÷ 2).", type: "short_text", acceptable: ["4,5", "4.5"] },
      { id: "a5-5-p26", promptFr: "Calculez 12 × 0,05 (astuce : ÷ 20).", type: "short_text", acceptable: ["0,6", "0.6"] },
      { id: "a5-5-p27", promptFr: "Calculez 9 × 0,125 (astuce : ÷ 8).", type: "short_text", acceptable: ["1,125", "1.125"] },
      { id: "a5-5-p28", promptFr: "Calculez 3 × 0,1.", type: "short_text", acceptable: ["0,3", "0.3"] },
      { id: "a5-5-p29", promptFr: "Calculez 12 × 0,125 (astuce : ÷ 8).", type: "short_text", acceptable: ["1,5", "1.5"] },
      { id: "a5-5-p30", promptFr: "Calculez 10 × 0,05 (astuce : ÷ 20).", type: "short_text", acceptable: ["0,5", "0.5"] },
    ],
    poolSize: 5,
  };
