import type { MathSubmoduleLesson, MathExerciseItem } from "./math-a1-types";

const easyPool: MathExerciseItem[] = [
  { id: "a3-7-e1-01", promptFr: "Il y a 3 boîtes. Dans chaque boîte, il y a 5 crayons. Combien y a-t-il de crayons en tout ?", type: "number", acceptable: ["15"], hintFr: "3 × 5 = 15" },
  { id: "a3-7-e1-02", promptFr: "Il y a 4 sacs. Dans chaque sac, il y a 7 pommes. Combien y a-t-il de pommes en tout ?", type: "number", acceptable: ["28"], hintFr: "4 × 7 = 28" },
  { id: "a3-7-e1-03", promptFr: "On a 12 bonbons. On les partage entre 3 enfants. Combien de bonbons reçoit chaque enfant ?", type: "number", acceptable: ["4"], hintFr: "12 ÷ 3 = 4" },
  { id: "a3-7-e1-04", promptFr: "Il y a 5 équipes. Chaque équipe a 6 joueurs. Combien y a-t-il de joueurs en tout ?", type: "number", acceptable: ["30"], hintFr: "5 × 6 = 30" },
  { id: "a3-7-e1-05", promptFr: "On a 24 bonbons. On les partage entre 4 enfants. Combien de bonbons reçoit chaque enfant ?", type: "number", acceptable: ["6"], hintFr: "24 ÷ 4 = 6" },
  { id: "a3-7-e1-06", promptFr: "Il y a 8 boîtes de 9 crayons. Combien y a-t-il de crayons en tout ?", type: "number", acceptable: ["72"], hintFr: "8 × 9 = 72" },
  { id: "a3-7-e1-07", promptFr: "On met 6 livres dans chaque carton. Il y a 7 cartons. Combien y a-t-il de livres en tout ?", type: "number", acceptable: ["42"], hintFr: "6 × 7 = 42" },
  { id: "a3-7-e1-08", promptFr: "On a 18 cahiers. On les partage entre 2 élèves. Combien de cahiers reçoit chaque élève ?", type: "number", acceptable: ["9"], hintFr: "18 ÷ 2 = 9" },
  { id: "a3-7-e1-09", promptFr: "Il y a 9 rangées de 5 chaises. Combien y a-t-il de chaises en tout ?", type: "number", acceptable: ["45"], hintFr: "9 × 5 = 45" },
  { id: "a3-7-e1-10", promptFr: "On a 30 ballons. On les partage entre 6 enfants. Combien de ballons reçoit chaque enfant ?", type: "number", acceptable: ["5"], hintFr: "30 ÷ 6 = 5" },
  { id: "a3-7-e1-11", promptFr: "Il y a 4 paquets de 8 biscuits. Combien y a-t-il de biscuits en tout ?", type: "number", acceptable: ["32"], hintFr: "4 × 8 = 32" },
  { id: "a3-7-e1-12", promptFr: "On a 35 billes. On les partage entre 7 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["5"], hintFr: "35 ÷ 7 = 5" },
  { id: "a3-7-e1-13", promptFr: "Il y a 6 rangées de 4 tables. Combien y a-t-il de tables en tout ?", type: "number", acceptable: ["24"], hintFr: "6 × 4 = 24" },
  { id: "a3-7-e1-14", promptFr: "On a 40 images. On les partage entre 8 enfants. Combien d'images reçoit chaque enfant ?", type: "number", acceptable: ["5"], hintFr: "40 ÷ 8 = 5" },
  { id: "a3-7-e1-15", promptFr: "Il y a 7 boîtes de 6 bonbons. Combien y a-t-il de bonbons en tout ?", type: "number", acceptable: ["42"], hintFr: "7 × 6 = 42" },
  { id: "a3-7-e1-16", promptFr: "On a 27 fruits. On les répartit dans 3 paniers. Combien de fruits y a-t-il dans chaque panier ?", type: "number", acceptable: ["9"], hintFr: "27 ÷ 3 = 9" },
  { id: "a3-7-e1-17", promptFr: "Il y a 3 rangées de 9 arbres. Combien y a-t-il d'arbres en tout ?", type: "number", acceptable: ["27"], hintFr: "3 × 9 = 27" },
  { id: "a3-7-e1-18", promptFr: "On a 45 cartes. On les partage entre 9 enfants. Combien de cartes reçoit chaque enfant ?", type: "number", acceptable: ["5"], hintFr: "45 ÷ 9 = 5" },
  { id: "a3-7-e1-19", promptFr: "Il y a 5 sacs de 7 oranges. Combien y a-t-il d'oranges en tout ?", type: "number", acceptable: ["35"], hintFr: "5 × 7 = 35" },
  { id: "a3-7-e1-20", promptFr: "On a 54 biscuits. On les partage entre 6 amis. Combien de biscuits reçoit chaque ami ?", type: "number", acceptable: ["9"], hintFr: "54 ÷ 6 = 9" },
  { id: "a3-7-e1-21", promptFr: "Il y a 2 tables de 8 élèves. Combien y a-t-il d'élèves en tout ?", type: "number", acceptable: ["16"], hintFr: "2 × 8 = 16" },
  { id: "a3-7-e1-22", promptFr: "On a 48 crayons. On les partage entre 8 enfants. Combien de crayons reçoit chaque enfant ?", type: "number", acceptable: ["6"], hintFr: "48 ÷ 8 = 6" },
  { id: "a3-7-e1-23", promptFr: "Il y a 10 boîtes de 4 stylos. Combien y a-t-il de stylos en tout ?", type: "number", acceptable: ["40"], hintFr: "10 × 4 = 40" },
  { id: "a3-7-e1-24", promptFr: "On a 63 billes. On les partage entre 7 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["9"], hintFr: "63 ÷ 7 = 9" },
  { id: "a3-7-e1-25", promptFr: "Il y a 4 rangées de 6 chaises. Combien y a-t-il de chaises en tout ?", type: "number", acceptable: ["24"], hintFr: "4 × 6 = 24" },
  { id: "a3-7-e1-26", promptFr: "On a 56 livres. On les partage entre 8 élèves. Combien de livres reçoit chaque élève ?", type: "number", acceptable: ["7"], hintFr: "56 ÷ 8 = 7" },
  { id: "a3-7-e1-27", promptFr: "Il y a 9 boîtes de 3 crayons. Combien y a-t-il de crayons en tout ?", type: "number", acceptable: ["27"], hintFr: "9 × 3 = 27" },
  { id: "a3-7-e1-28", promptFr: "On a 36 biscuits. On les partage entre 4 amis. Combien de biscuits reçoit chaque ami ?", type: "number", acceptable: ["9"], hintFr: "36 ÷ 4 = 9" },
  { id: "a3-7-e1-29", promptFr: "Il y a 7 paquets de 8 cartes. Combien y a-t-il de cartes en tout ?", type: "number", acceptable: ["56"], hintFr: "7 × 8 = 56" },
  { id: "a3-7-e1-30", promptFr: "On a 72 images. On les partage entre 9 enfants. Combien d'images reçoit chaque enfant ?", type: "number", acceptable: ["8"], hintFr: "72 ÷ 9 = 8" },
  { id: "a3-7-e1-31", promptFr: "Il y a 6 boîtes de 7 stylos. Combien y a-t-il de stylos en tout ?", type: "number", acceptable: ["42"], hintFr: "6 × 7 = 42" },
  { id: "a3-7-e1-32", promptFr: "On a 42 oranges. On les répartit dans 7 paniers. Combien d'oranges y a-t-il dans chaque panier ?", type: "number", acceptable: ["6"], hintFr: "42 ÷ 7 = 6" },
  { id: "a3-7-e1-33", promptFr: "Il y a 8 rangées de 4 tables. Combien y a-t-il de tables en tout ?", type: "number", acceptable: ["32"], hintFr: "8 × 4 = 32" },
  { id: "a3-7-e1-34", promptFr: "On a 81 bonbons. On les partage entre 9 enfants. Combien de bonbons reçoit chaque enfant ?", type: "number", acceptable: ["9"], hintFr: "81 ÷ 9 = 9" },
  { id: "a3-7-e1-35", promptFr: "Il y a 3 paquets de 7 biscuits. Combien y a-t-il de biscuits en tout ?", type: "number", acceptable: ["21"], hintFr: "3 × 7 = 21" },
  { id: "a3-7-e1-36", promptFr: "On a 20 crayons. On les partage entre 5 enfants. Combien de crayons reçoit chaque enfant ?", type: "number", acceptable: ["4"], hintFr: "20 ÷ 5 = 4" },
  { id: "a3-7-e1-37", promptFr: "Il y a 7 sacs de 5 pommes. Combien y a-t-il de pommes en tout ?", type: "number", acceptable: ["35"], hintFr: "7 × 5 = 35" },
  { id: "a3-7-e1-38", promptFr: "On a 64 billes. On les partage entre 8 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["8"], hintFr: "64 ÷ 8 = 8" },
  { id: "a3-7-e1-39", promptFr: "Il y a 10 boîtes de 7 crayons. Combien y a-t-il de crayons en tout ?", type: "number", acceptable: ["70"], hintFr: "10 × 7 = 70" },
  { id: "a3-7-e1-40", promptFr: "On a 36 livres. On les partage entre 6 élèves. Combien de livres reçoit chaque élève ?", type: "number", acceptable: ["6"], hintFr: "36 ÷ 6 = 6" },
  { id: "a3-7-e1-41", promptFr: "Il y a 5 rangées de 8 chaises. Combien y a-t-il de chaises en tout ?", type: "number", acceptable: ["40"], hintFr: "5 × 8 = 40" },
  { id: "a3-7-e1-42", promptFr: "On a 32 bonbons. On les partage entre 4 enfants. Combien de bonbons reçoit chaque enfant ?", type: "number", acceptable: ["8"], hintFr: "32 ÷ 4 = 8" },
  { id: "a3-7-e1-43", promptFr: "Il y a 9 boîtes de 6 stylos. Combien y a-t-il de stylos en tout ?", type: "number", acceptable: ["54"], hintFr: "9 × 6 = 54" },
  { id: "a3-7-e1-44", promptFr: "On a 70 images. On les partage entre 10 enfants. Combien d'images reçoit chaque enfant ?", type: "number", acceptable: ["7"], hintFr: "70 ÷ 10 = 7" },
  { id: "a3-7-e1-45", promptFr: "Il y a 4 paquets de 9 oranges. Combien y a-t-il d'oranges en tout ?", type: "number", acceptable: ["36"], hintFr: "4 × 9 = 36" },
  { id: "a3-7-e1-46", promptFr: "On a 50 biscuits. On les partage entre 5 amis. Combien de biscuits reçoit chaque ami ?", type: "number", acceptable: ["10"], hintFr: "50 ÷ 5 = 10" },
  { id: "a3-7-e1-47", promptFr: "Il y a 6 sacs de 9 pommes. Combien y a-t-il de pommes en tout ?", type: "number", acceptable: ["54"], hintFr: "6 × 9 = 54" },
  { id: "a3-7-e1-48", promptFr: "On a 49 cartes. On les partage entre 7 enfants. Combien de cartes reçoit chaque enfant ?", type: "number", acceptable: ["7"], hintFr: "49 ÷ 7 = 7" },
  { id: "a3-7-e1-49", promptFr: "Il y a 8 boîtes de 6 crayons. Combien y a-t-il de crayons en tout ?", type: "number", acceptable: ["48"], hintFr: "8 × 6 = 48" },
  { id: "a3-7-e1-50", promptFr: "On a 90 billes. On les partage entre 9 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["10"], hintFr: "90 ÷ 9 = 10" },
];

const mediumPool: MathExerciseItem[] = [
  { id: "a3-7-e2-01", promptFr: "Une librairie a 15 étagères. Chaque étagère contient 24 livres. Combien y a-t-il de livres en tout ?", type: "number", acceptable: ["360"], hintFr: "15 × 24 = 360" },
  { id: "a3-7-e2-02", promptFr: "Un club de sport a 126 membres. On les répartit en 6 groupes égaux. Combien de membres y a-t-il dans chaque groupe ?", type: "number", acceptable: ["21"], hintFr: "126 ÷ 6 = 21" },
  { id: "a3-7-e2-03", promptFr: "Une ferme a 8 vaches. Chaque vache produit 15 litres de lait par jour. Combien de litres produit la ferme chaque jour ?", type: "number", acceptable: ["120"], hintFr: "8 × 15 = 120" },
  { id: "a3-7-e2-04", promptFr: "Tom a 144 figurines. Il les partage entre 12 amis. Combien de figurines reçoit chaque ami ?", type: "number", acceptable: ["12"], hintFr: "144 ÷ 12 = 12" },
  { id: "a3-7-e2-05", promptFr: "Un bouquet contient 24 fleurs. On fait 18 bouquets identiques. Combien y a-t-il de fleurs en tout ?", type: "number", acceptable: ["432"], hintFr: "18 × 24 = 432" },
  { id: "a3-7-e2-06", promptFr: "Quel est le double de 75 ?", type: "number", acceptable: ["150"], hintFr: "2 × 75 = 150" },
  { id: "a3-7-e2-07", promptFr: "Quelle est la moitié de 196 ?", type: "number", acceptable: ["98"], hintFr: "196 ÷ 2 = 98" },
  { id: "a3-7-e2-08", promptFr: "Un magasin vend 45 articles par jour. Combien d'articles vend-il en 12 jours ?", type: "number", acceptable: ["540"], hintFr: "45 × 12 = 540" },
  { id: "a3-7-e2-09", promptFr: "Une cantine prépare 336 repas sur 7 jours en quantités égales. Combien de repas prépare-t-elle par jour ?", type: "number", acceptable: ["48"], hintFr: "336 ÷ 7 = 48" },
  { id: "a3-7-e2-10", promptFr: "Quel est le triple de 34 ?", type: "number", acceptable: ["102"], hintFr: "3 × 34 = 102" },
  { id: "a3-7-e2-11", promptFr: "Une usine fabrique 28 pièces par heure. Combien de pièces fabrique-t-elle en 15 heures ?", type: "number", acceptable: ["420"], hintFr: "28 × 15 = 420" },
  { id: "a3-7-e2-12", promptFr: "On a 225 élèves à répartir en classes de 25. Combien y a-t-il de classes ?", type: "number", acceptable: ["9"], hintFr: "225 ÷ 25 = 9" },
  { id: "a3-7-e2-13", promptFr: "Un paquet contient 48 biscuits. On achète 12 paquets. Combien y a-t-il de biscuits en tout ?", type: "number", acceptable: ["576"], hintFr: "48 × 12 = 576" },
  { id: "a3-7-e2-14", promptFr: "Un livre contient 180 pages. Tom lit 15 pages par jour. Combien de jours lui faut-il pour finir le livre ?", type: "number", acceptable: ["12"], hintFr: "180 ÷ 15 = 12" },
  { id: "a3-7-e2-15", promptFr: "Un jardin a 16 rangées de 18 plantes. Combien y a-t-il de plantes en tout ?", type: "number", acceptable: ["288"], hintFr: "16 × 18 = 288" },
  { id: "a3-7-e2-16", promptFr: "Quelle est la moitié de 248 ?", type: "number", acceptable: ["124"], hintFr: "248 ÷ 2 = 124" },
  { id: "a3-7-e2-17", promptFr: "Un cinéma a 22 rangées de 14 places. Combien y a-t-il de places en tout ?", type: "number", acceptable: ["308"], hintFr: "22 × 14 = 308" },
  { id: "a3-7-e2-18", promptFr: "On a 252 photos à répartir dans des albums de 36 pages. Combien d'albums faut-il ?", type: "number", acceptable: ["7"], hintFr: "252 ÷ 36 = 7" },
  { id: "a3-7-e2-19", promptFr: "Quel est le double de 123 ?", type: "number", acceptable: ["246"], hintFr: "2 × 123 = 246" },
  { id: "a3-7-e2-20", promptFr: "Un restaurant prépare 35 plats par heure. Combien de plats prépare-t-il en 8 heures ?", type: "number", acceptable: ["280"], hintFr: "35 × 8 = 280" },
  { id: "a3-7-e2-21", promptFr: "Une boîte contient 48 chocolats. On achète 9 boîtes. Combien y a-t-il de chocolats en tout ?", type: "number", acceptable: ["432"], hintFr: "48 × 9 = 432" },
  { id: "a3-7-e2-22", promptFr: "On a 312 pommes à répartir dans des sacs de 8. Combien de sacs obtient-on ?", type: "number", acceptable: ["39"], hintFr: "312 ÷ 8 = 39" },
  { id: "a3-7-e2-23", promptFr: "Quel est le tiers de 126 ?", type: "number", acceptable: ["42"], hintFr: "126 ÷ 3 = 42" },
  { id: "a3-7-e2-24", promptFr: "Un avion transporte 175 passagers. Combien de passagers transportent 4 avions identiques ?", type: "number", acceptable: ["700"], hintFr: "175 × 4 = 700" },
  { id: "a3-7-e2-25", promptFr: "On a 396 livres à placer sur des étagères de 12 livres chacune. Combien d'étagères faut-il ?", type: "number", acceptable: ["33"], hintFr: "396 ÷ 12 = 33" },
  { id: "a3-7-e2-26", promptFr: "Quel est le triple de 45 ?", type: "number", acceptable: ["135"], hintFr: "3 × 45 = 135" },
  { id: "a3-7-e2-27", promptFr: "Une école a 14 classes de 28 élèves. Combien d'élèves y a-t-il à l'école ?", type: "number", acceptable: ["392"], hintFr: "14 × 28 = 392" },
  { id: "a3-7-e2-28", promptFr: "On a 270 cartes à répartir entre 9 joueurs. Combien de cartes reçoit chaque joueur ?", type: "number", acceptable: ["30"], hintFr: "270 ÷ 9 = 30" },
  { id: "a3-7-e2-29", promptFr: "Quelle est la moitié de 346 ?", type: "number", acceptable: ["173"], hintFr: "346 ÷ 2 = 173" },
  { id: "a3-7-e2-30", promptFr: "Un magasin vend 65 articles par semaine. Combien d'articles vend-il en 8 semaines ?", type: "number", acceptable: ["520"], hintFr: "65 × 8 = 520" },
  { id: "a3-7-e2-31", promptFr: "Un camion transporte 25 caisses. Chaque caisse pèse 12 kg. Combien de kilogrammes le camion transporte-t-il ?", type: "number", acceptable: ["300"], hintFr: "25 × 12 = 300" },
  { id: "a3-7-e2-32", promptFr: "On a 416 billes à répartir entre 8 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["52"], hintFr: "416 ÷ 8 = 52" },
  { id: "a3-7-e2-33", promptFr: "Quel est le quart de 120 ?", type: "number", acceptable: ["30"], hintFr: "120 ÷ 4 = 30" },
  { id: "a3-7-e2-34", promptFr: "Un constructeur bâtit 18 maisons par an. Combien de maisons construit-il en 5 ans ?", type: "number", acceptable: ["90"], hintFr: "18 × 5 = 90" },
  { id: "a3-7-e2-35", promptFr: "On dépense 325 fr. Ces dépenses sont partagées entre 5 personnes. Combien chaque personne paie-t-elle ?", type: "number", acceptable: ["65"], hintFr: "325 ÷ 5 = 65" },
  { id: "a3-7-e2-36", promptFr: "Quel est le double de 165 ?", type: "number", acceptable: ["330"], hintFr: "2 × 165 = 330" },
  { id: "a3-7-e2-37", promptFr: "Une fabrique produit 48 jouets par jour. Combien en produit-elle en 15 jours ?", type: "number", acceptable: ["720"], hintFr: "48 × 15 = 720" },
  { id: "a3-7-e2-38", promptFr: "On a 360 stylos à placer dans des boîtes de 20. Combien de boîtes obtient-on ?", type: "number", acceptable: ["18"], hintFr: "360 ÷ 20 = 18" },
  { id: "a3-7-e2-39", promptFr: "Quel est le tiers de 213 ?", type: "number", acceptable: ["71"], hintFr: "213 ÷ 3 = 71" },
  { id: "a3-7-e2-40", promptFr: "Un club a 24 membres. Chaque membre paie 15 fr. par mois. Combien le club reçoit-il par mois ?", type: "number", acceptable: ["360"], hintFr: "24 × 15 = 360" },
  { id: "a3-7-e2-41", promptFr: "On a 504 petits pains à répartir dans des paquets de 12. Combien de paquets obtient-on ?", type: "number", acceptable: ["42"], hintFr: "504 ÷ 12 = 42" },
  { id: "a3-7-e2-42", promptFr: "Quel est le double de 98 ?", type: "number", acceptable: ["196"], hintFr: "2 × 98 = 196" },
  { id: "a3-7-e2-43", promptFr: "Un train a 8 wagons. Chaque wagon peut transporter 56 passagers. Combien de passagers le train peut-il transporter ?", type: "number", acceptable: ["448"], hintFr: "8 × 56 = 448" },
  { id: "a3-7-e2-44", promptFr: "On a 432 bonbons à répartir entre 16 enfants. Combien de bonbons reçoit chaque enfant ?", type: "number", acceptable: ["27"], hintFr: "432 ÷ 16 = 27" },
  { id: "a3-7-e2-45", promptFr: "Quel est le triple de 67 ?", type: "number", acceptable: ["201"], hintFr: "3 × 67 = 201" },
  { id: "a3-7-e2-46", promptFr: "Une bibliothèque a 30 rayonnages. Chaque rayonnage contient 45 livres. Combien la bibliothèque contient-elle de livres ?", type: "number", acceptable: ["1350"], hintFr: "30 × 45 = 1 350" },
  { id: "a3-7-e2-47", promptFr: "On a 560 billes à répartir entre 7 enfants. Combien de billes reçoit chaque enfant ?", type: "number", acceptable: ["80"], hintFr: "560 ÷ 7 = 80" },
  { id: "a3-7-e2-48", promptFr: "Quelle est la moitié de 538 ?", type: "number", acceptable: ["269"], hintFr: "538 ÷ 2 = 269" },
  { id: "a3-7-e2-49", promptFr: "Un atelier produit 125 pièces par jour. Combien de pièces produit-il en 6 jours ?", type: "number", acceptable: ["750"], hintFr: "125 × 6 = 750" },
  { id: "a3-7-e2-50", promptFr: "On a 684 photos à répartir dans des albums de 18 photos. Combien d'albums peut-on remplir ?", type: "number", acceptable: ["38"], hintFr: "684 ÷ 18 = 38" },
];

const advancedPool: MathExerciseItem[] = [
  { id: "a3-7-e3-01", promptFr: "Sarah achète 4 boîtes de 12 biscuits. Elle en mange 8. Combien lui en reste-t-il ?", type: "number", acceptable: ["40"], hintFr: "4 × 12 = 48 ; 48 − 8 = 40" },
  { id: "a3-7-e3-02", promptFr: "Un cinéma a 18 rangées de 22 sièges. 127 sièges sont occupés. Combien de sièges sont libres ?", type: "number", acceptable: ["269"], hintFr: "18 × 22 = 396 ; 396 − 127 = 269" },
  { id: "a3-7-e3-03", promptFr: "Un menuisier fabrique 6 tables par semaine. Après 8 semaines, il en a vendu 23. Combien lui en reste-t-il ?", type: "number", acceptable: ["25"], hintFr: "6 × 8 = 48 ; 48 − 23 = 25" },
  { id: "a3-7-e3-04", promptFr: "Un sac contient 15 pommes. On achète 6 sacs et on distribue toutes les pommes entre 9 enfants. Combien chaque enfant reçoit-il ?", type: "number", acceptable: ["10"], hintFr: "6 × 15 = 90 ; 90 ÷ 9 = 10" },
  { id: "a3-7-e3-05", promptFr: "Un magasin vend des carnets à 4 fr. et des stylos à 3 fr. Marie achète 5 carnets et 8 stylos. Combien dépense-t-elle ?", type: "number", acceptable: ["44"], hintFr: "5 × 4 = 20 ; 8 × 3 = 24 ; 20 + 24 = 44" },
  { id: "a3-7-e3-06", promptFr: "Une école commande 24 paquets de 36 feuilles. Elle a déjà 192 feuilles en stock. Combien de feuilles au total ?", type: "number", acceptable: ["1056"], hintFr: "24 × 36 = 864 ; 864 + 192 = 1 056" },
  { id: "a3-7-e3-07", promptFr: "On partage 288 billes entre 9 enfants. Chaque enfant met ensuite le double de ses billes dans une boîte. Combien y a-t-il de billes dans la boîte d'un enfant ?", type: "number", acceptable: ["64"], hintFr: "288 ÷ 9 = 32 ; 32 × 2 = 64" },
  { id: "a3-7-e3-08", promptFr: "Un club achète 12 ballons à 15 fr. chacun et 8 maillots à 23 fr. chacun. Combien le club dépense-t-il au total ?", type: "number", acceptable: ["364"], hintFr: "12 × 15 = 180 ; 8 × 23 = 184 ; 180 + 184 = 364" },
  { id: "a3-7-e3-09", promptFr: "Une école a 15 classes de 28 élèves et 3 classes de 24 élèves. Combien y a-t-il d'élèves en tout ?", type: "number", acceptable: ["492"], hintFr: "15 × 28 = 420 ; 3 × 24 = 72 ; 420 + 72 = 492" },
  { id: "a3-7-e3-10", promptFr: "On achète 6 boîtes de 24 chocolats. On en donne 12 à chaque personne. Combien de personnes peut-on servir ?", type: "number", acceptable: ["12"], hintFr: "6 × 24 = 144 ; 144 ÷ 12 = 12" },
  { id: "a3-7-e3-11", promptFr: "Un constructeur bâtit 3 immeubles de 12 appartements et 2 immeubles de 18 appartements. Combien d'appartements a-t-il construit en tout ?", type: "number", acceptable: ["72"], hintFr: "3 × 12 = 36 ; 2 × 18 = 36 ; 36 + 36 = 72" },
  { id: "a3-7-e3-12", promptFr: "Une voiture roule à 85 km/h. Après 6 heures de route, combien de km reste-t-il si le trajet total est de 600 km ?", type: "number", acceptable: ["90"], hintFr: "85 × 6 = 510 ; 600 − 510 = 90" },
  { id: "a3-7-e3-13", promptFr: "Un boulanger prépare 144 petits pains. Il en vend 32 par heure pendant 3 heures. Combien lui en reste-t-il ?", type: "number", acceptable: ["48"], hintFr: "32 × 3 = 96 ; 144 − 96 = 48" },
  { id: "a3-7-e3-14", promptFr: "Un jardinier plante 15 rangées de 18 tulipes et 12 rangées de 22 roses. Combien de fleurs a-t-il planté en tout ?", type: "number", acceptable: ["534"], hintFr: "15 × 18 = 270 ; 12 × 22 = 264 ; 270 + 264 = 534" },
  { id: "a3-7-e3-15", promptFr: "Une école commande 28 lots de 15 cahiers. Elle distribue 3 cahiers à chaque élève. Combien d'élèves peut-elle servir ?", type: "number", acceptable: ["140"], hintFr: "28 × 15 = 420 ; 420 ÷ 3 = 140" },
  { id: "a3-7-e3-16", promptFr: "Un restaurant prépare 48 repas le midi et 63 repas le soir. En une semaine (7 jours), combien de repas prépare-t-il ?", type: "number", acceptable: ["777"], hintFr: "48 + 63 = 111 ; 111 × 7 = 777" },
  { id: "a3-7-e3-17", promptFr: "Un terrain de 45 m de long et 32 m de large est divisé en parcelles de 36 m². Combien de parcelles obtient-on ?", type: "number", acceptable: ["40"], hintFr: "45 × 32 = 1 440 ; 1 440 ÷ 36 = 40" },
  { id: "a3-7-e3-18", promptFr: "Sarah économise 35 fr. par semaine. Après 12 semaines, elle achète un article à 175 fr. Combien lui reste-t-il ?", type: "number", acceptable: ["245"], hintFr: "35 × 12 = 420 ; 420 − 175 = 245" },
  { id: "a3-7-e3-19", promptFr: "Paul gagne 45 fr. de l'heure. Il travaille 8 heures par jour pendant 5 jours. Combien gagne-t-il en tout ?", type: "number", acceptable: ["1800"], hintFr: "8 × 45 = 360 ; 360 × 5 = 1 800" },
  { id: "a3-7-e3-20", promptFr: "Une usine fabrique 240 pièces en 8 heures. Elle reçoit une commande de 900 pièces. En combien d'heures peut-elle la livrer ?", type: "number", acceptable: ["30"], hintFr: "240 ÷ 8 = 30 pièces/h ; 900 ÷ 30 = 30 h" },
  { id: "a3-7-e3-21", promptFr: "On a 756 timbres. On les colle dans des albums de 27 timbres. Combien d'albums peut-on remplir ?", type: "number", acceptable: ["28"], hintFr: "756 ÷ 27 = 28" },
  { id: "a3-7-e3-22", promptFr: "Un magasin vend 45 articles par jour pendant 5 jours, puis 72 articles par jour pendant 3 jours. Combien vend-il en tout ?", type: "number", acceptable: ["441"], hintFr: "45 × 5 = 225 ; 72 × 3 = 216 ; 225 + 216 = 441" },
  { id: "a3-7-e3-23", promptFr: "Un camion transporte 15 caisses de 24 bouteilles. On y ajoute 36 bouteilles libres. Combien y a-t-il de bouteilles en tout ?", type: "number", acceptable: ["396"], hintFr: "15 × 24 = 360 ; 360 + 36 = 396" },
  { id: "a3-7-e3-24", promptFr: "Un club a 16 membres. Chacun paie 25 fr. de cotisation et 12 fr. d'assurance. Combien le club reçoit-il en tout ?", type: "number", acceptable: ["592"], hintFr: "25 + 12 = 37 ; 16 × 37 = 592" },
  { id: "a3-7-e3-25", promptFr: "On répartit 504 livres dans des boîtes de 14. On empile ensuite les boîtes par groupes de 6. Combien de groupes obtient-on ?", type: "number", acceptable: ["6"], hintFr: "504 ÷ 14 = 36 boîtes ; 36 ÷ 6 = 6 groupes" },
  { id: "a3-7-e3-26", promptFr: "Un groupe de 56 élèves monte dans des cars de 24 places. Combien de places vides y aura-t-il en tout ?", type: "number", acceptable: ["16"], hintFr: "3 cars nécessaires : 3 × 24 = 72 ; 72 − 56 = 16 places vides" },
  { id: "a3-7-e3-27", promptFr: "On achète 8 paquets de 45 bonbons et on y ajoute 36 bonbons. On partage tout entre 12 enfants. Combien chaque enfant reçoit-il ?", type: "number", acceptable: ["33"], hintFr: "8 × 45 = 360 ; 360 + 36 = 396 ; 396 ÷ 12 = 33" },
  { id: "a3-7-e3-28", promptFr: "Un fermier a 5 champs de 36 pommiers et 3 champs de 48 poiriers. Combien d'arbres fruitiers a-t-il en tout ?", type: "number", acceptable: ["324"], hintFr: "5 × 36 = 180 ; 3 × 48 = 144 ; 180 + 144 = 324" },
  { id: "a3-7-e3-29", promptFr: "Un randonneur marche 18 km par jour. Après 4 jours, il lui reste encore 72 km. Quelle est la longueur totale du trajet ?", type: "number", acceptable: ["144"], hintFr: "4 × 18 = 72 km parcourus ; 72 + 72 = 144 km au total" },
  { id: "a3-7-e3-30", promptFr: "Une boîte contient 6 couches de 8 rangées de 5 chocolats. Combien y a-t-il de chocolats en tout ?", type: "number", acceptable: ["240"], hintFr: "6 × 8 = 48 ; 48 × 5 = 240" },
  { id: "a3-7-e3-31", promptFr: "On dispose de 480 fr. On achète 6 livres à 24 fr. chacun. Combien d'argent reste-t-il ?", type: "number", acceptable: ["336"], hintFr: "6 × 24 = 144 ; 480 − 144 = 336" },
  { id: "a3-7-e3-32", promptFr: "Un atelier produit 125 pièces par jour pendant 4 jours. On écarte le cinquième des pièces (défectueuses). Combien reste-t-il de bonnes pièces ?", type: "number", acceptable: ["400"], hintFr: "125 × 4 = 500 ; 500 ÷ 5 = 100 défectueuses ; 500 − 100 = 400" },
  { id: "a3-7-e3-33", promptFr: "Un professeur a 6 classes de 28 élèves. Il distribue 4 feuilles à chaque élève. Combien de feuilles utilise-t-il ?", type: "number", acceptable: ["672"], hintFr: "6 × 28 = 168 élèves ; 168 × 4 = 672 feuilles" },
  { id: "a3-7-e3-34", promptFr: "On achète 12 cartons de 24 bouteilles à 2 fr. la bouteille. Combien dépense-t-on ?", type: "number", acceptable: ["576"], hintFr: "12 × 24 = 288 bouteilles ; 288 × 2 = 576 fr." },
  { id: "a3-7-e3-35", promptFr: "Un bâtiment a 8 étages. Chaque étage a 6 appartements de 3 pièces. Combien y a-t-il de pièces en tout ?", type: "number", acceptable: ["144"], hintFr: "8 × 6 = 48 appartements ; 48 × 3 = 144 pièces" },
  { id: "a3-7-e3-36", promptFr: "On produit 1 350 pots de confiture. On les répartit dans des caisses de 25. Combien de caisses obtient-on ?", type: "number", acceptable: ["54"], hintFr: "1 350 ÷ 25 = 54" },
  { id: "a3-7-e3-37", promptFr: "Sur 960 spectateurs, un tiers est arrivé en avance. Combien de spectateurs sont arrivés en avance ?", type: "number", acceptable: ["320"], hintFr: "960 ÷ 3 = 320" },
  { id: "a3-7-e3-38", promptFr: "Un jus de fruits coûte 3 fr. et un sandwich 6 fr. 8 enfants prennent chacun un jus et un sandwich. Combien dépensent-ils en tout ?", type: "number", acceptable: ["72"], hintFr: "3 + 6 = 9 fr. par enfant ; 9 × 8 = 72 fr." },
  { id: "a3-7-e3-39", promptFr: "Un parc a 24 allées. Chaque allée a 15 arbres de chaque côté. Combien y a-t-il d'arbres dans le parc ?", type: "number", acceptable: ["720"], hintFr: "15 × 2 = 30 arbres par allée ; 30 × 24 = 720 arbres" },
  { id: "a3-7-e3-40", promptFr: "Un hôtel a 14 étages de 16 chambres. 35 chambres sont occupées. Combien de chambres sont libres ?", type: "number", acceptable: ["189"], hintFr: "14 × 16 = 224 chambres ; 224 − 35 = 189 libres" },
  { id: "a3-7-e3-41", promptFr: "Une famille dépense 135 fr. par semaine en nourriture. En combien de semaines dépense-t-elle 1 080 fr. ?", type: "number", acceptable: ["8"], hintFr: "1 080 ÷ 135 = 8 semaines" },
  { id: "a3-7-e3-42", promptFr: "Un ouvrier pose 45 briques par heure en 8 heures. Un autre en pose 60 par heure en 6 heures. Combien ont-ils posé de briques en tout ?", type: "number", acceptable: ["720"], hintFr: "45 × 8 = 360 ; 60 × 6 = 360 ; 360 + 360 = 720" },
  { id: "a3-7-e3-43", promptFr: "Un marchand a 250 pommes. Il en vend 15 par heure pendant 8 heures, puis il en reçoit 50 nouvelles. Combien en a-t-il maintenant ?", type: "number", acceptable: ["180"], hintFr: "15 × 8 = 120 vendues ; 250 − 120 = 130 ; 130 + 50 = 180" },
  { id: "a3-7-e3-44", promptFr: "On organise un repas pour 144 personnes. Les tables de 8 places coûtent 12 fr. de location. Combien paie-t-on pour la location de toutes les tables ?", type: "number", acceptable: ["216"], hintFr: "144 ÷ 8 = 18 tables ; 18 × 12 = 216 fr." },
  { id: "a3-7-e3-45", promptFr: "Un cycliste fait 4 tours d'un circuit de 15 km, puis 3 tours d'un circuit de 22 km. Combien de km a-t-il parcouru en tout ?", type: "number", acceptable: ["126"], hintFr: "4 × 15 = 60 ; 3 × 22 = 66 ; 60 + 66 = 126 km" },
  { id: "a3-7-e3-46", promptFr: "On fabrique 36 paires de chaussures par heure pendant 5 heures. On en vend 78. Combien de paires reste-t-il ?", type: "number", acceptable: ["102"], hintFr: "36 × 5 = 180 ; 180 − 78 = 102" },
  { id: "a3-7-e3-47", promptFr: "Une salle de spectacle a 24 rangées de 18 sièges. Chaque billet coûte 15 fr. Si la salle est pleine, quelle est la recette totale ?", type: "number", acceptable: ["6480"], hintFr: "24 × 18 = 432 places ; 432 × 15 = 6 480 fr." },
  { id: "a3-7-e3-48", promptFr: "Une bibliothèque prête 76 livres par semaine. En combien de semaines prêtera-t-elle 988 livres ?", type: "number", acceptable: ["13"], hintFr: "988 ÷ 76 = 13 semaines" },
  { id: "a3-7-e3-49", promptFr: "Un train avec 240 passagers s'arrête dans une gare : 75 descendent et 48 montent. Puis il s'arrête encore : 32 descendent et 24 montent. Combien y a-t-il de passagers dans le train ?", type: "number", acceptable: ["205"], hintFr: "240 − 75 + 48 = 213 ; 213 − 32 + 24 = 205" },
  { id: "a3-7-e3-50", promptFr: "Un magasin a 3 rangées de 8 étagères. Chaque étagère contient 45 articles. On en retire 72. Combien d'articles reste-t-il ?", type: "number", acceptable: ["1008"], hintFr: "3 × 8 = 24 étagères ; 24 × 45 = 1 080 ; 1 080 − 72 = 1 008" },
];

export const MATH_A3_7_LESSON: MathSubmoduleLesson = {
  submoduleId: "A3-7",
  submoduleCode: "A3.7",
  theory: {
    title: { fr: "Problèmes" },
    blocks: [
      { type: "heading", fr: "Problèmes : multiplication ou division", black: true },
      { type: "highlight", fr: "Règle importante" },
      { type: "plain", fr: "Je ne choisis pas l'opération avec un mot. Je la choisis avec **la question**." },
      { type: "section", labelFr: "Méthode", itemsFr: [
        "**1.** Je lis la question.",
        "**2.** Je repère ce qui se répète : une ligne, un paquet, une boîte, une équipe, un prix.",
        "**3.** Je demande : est-ce que je cherche un **total** ou une **part** ?",
      ] },
      { type: "section", labelFr: "", itemsFr: [
        "Si je cherche le total, je fais **×**.",
        "Si je cherche une part ou un nombre de groupes, je fais **÷**.",
        "Je vérifie que ma réponse est logique : un total est souvent plus grand, une part est souvent plus petite.",
      ] },
      { type: "theory_tabs", tabs: [
        {
          label: "Multiplier",
          blocks: [
            { type: "heading", fr: "Quand faut-il multiplier ?", black: true },
            { type: "highlight", fr: "Je cherche un total avec des groupes égaux" },
            { type: "plain", fr: "On multiplie quand la même quantité se répète plusieurs fois." },
            { type: "section", labelFr: "Exemple", itemsFr: [
              "Il y a 6 boîtes.",
              "Dans chaque boîte, il y a 8 crayons.",
              "Combien y a-t-il de crayons en tout ?",
              "On cherche le total.",
              "Calcul : **6 × 8 = 48**",
              "Réponse : **Il y a 48 crayons.**",
            ] },
            { type: "section", labelFr: "On multiplie souvent avec", itemsFr: [
              "des lignes et des colonnes",
              "des paquets identiques",
              "des équipes avec le même nombre de joueurs",
              "un prix répété plusieurs fois",
              "une quantité qui est **2 fois, 3 fois, 4 fois** plus grande",
            ] },
            { type: "heading", fr: "Double, triple et quadruple", black: true },
            { type: "plain", fr: "Ces termes sont utilisés pour des multiplications." },
            { type: "theory_tabs", tabs: [
              {
                label: "Double",
                blocks: [
                  { type: "plain", fr: "Pour obtenir le double d'un nombre, on le multiplie par **2**." },
                  { type: "plain", fr: "Exemple : le double de 4 est 8, car **4 × 2 = 8**." },
                ],
              },
              {
                label: "Triple",
                blocks: [
                  { type: "plain", fr: "Pour obtenir le triple d'un nombre, on le multiplie par **3**." },
                  { type: "plain", fr: "Exemple : le triple de 4 est 12, car **4 × 3 = 12**." },
                ],
              },
              {
                label: "Quadruple",
                blocks: [
                  { type: "plain", fr: "Pour obtenir le quadruple d'un nombre, on le multiplie par **4**." },
                  { type: "plain", fr: "Exemple : le quadruple de 4 est 16, car **4 × 4 = 16**." },
                ],
              },
            ] },
          ],
        },
        {
          label: "Diviser",
          blocks: [
            { type: "heading", fr: "Quand faut-il diviser ?", black: true },
            { type: "highlight", fr: "Je cherche une part ou un nombre de groupes" },
            { type: "plain", fr: "On divise quand on partage une quantité en parts égales ou quand on cherche combien de groupes identiques on peut former." },
            { type: "section", labelFr: "Exemple 1 : partager", itemsFr: [
              "On a 45 cahiers.",
              "On les partage également entre 5 élèves.",
              "Combien de cahiers reçoit chaque élève ?",
              "Calcul : **45 ÷ 5 = 9**",
              "Réponse : **Chaque élève reçoit 9 cahiers.**",
            ] },
            { type: "section", labelFr: "Exemple 2 : grouper", itemsFr: [
              "On a 72 bouteilles.",
              "On met 12 bouteilles dans chaque carton.",
              "Combien de cartons peut-on remplir ?",
              "Calcul : **72 ÷ 12 = 6**",
              "Réponse : **On peut remplir 6 cartons.**",
            ] },
            { type: "heading", fr: "Moitié, tiers et quart", black: true },
            { type: "plain", fr: "Ces termes sont utilisés pour des divisions." },
            { type: "theory_tabs", tabs: [
              {
                label: "Moitié",
                blocks: [
                  { type: "plain", fr: "Pour obtenir la moitié d'un nombre, on divise par **2**." },
                  { type: "plain", fr: "Exemple : la moitié de 12 est 6, car **12 ÷ 2 = 6**." },
                ],
              },
              {
                label: "Tiers",
                blocks: [
                  { type: "plain", fr: "Pour obtenir le tiers d'un nombre, on divise par **3**." },
                  { type: "plain", fr: "Exemple : le tiers de 12 est 4, car **12 ÷ 3 = 4**." },
                ],
              },
              {
                label: "Quart",
                blocks: [
                  { type: "plain", fr: "Pour obtenir le quart d'un nombre, on divise par **4**." },
                  { type: "plain", fr: "Exemple : le quart de 12 est 3, car **12 ÷ 4 = 3**." },
                ],
              },
            ] },
          ],
        },
      ] },
      { type: "table",
        headersFr: ["Situation", "Question", "Opération"],
        accentHeader: true,
        rows: [
          ["Il y a 6 boîtes de 8 crayons.", "Combien y a-t-il de crayons en tout ?", "6 × 8"],
          ["On a 48 crayons répartis en 6 boîtes égales.", "Combien y a-t-il de crayons par boîte ?", "48 ÷ 6"],
          ["On a 48 crayons. On les met en boîtes de 8.", "Combien de boîtes peut-on remplir ?", "48 ÷ 8"],
          ["Un prix de 7 fr. se répète 9 fois.", "Combien dépense-t-on en tout ?", "9 × 7"],
        ],
      },
      { type: "heading", fr: "Petite stratégie", black: true },
      { type: "plain", fr: "**1.** Je repère ce qui se répète (une quantité identique dans chaque groupe)." },
      { type: "plain", fr: "**2.** Je demande : est-ce que je cherche le **total** ou une **part** ?" },
      { type: "plain", fr: "**3.** Si je cherche le total, je fais **×**." },
      { type: "plain", fr: "**4.** Si je cherche une part ou un nombre de groupes, je fais **÷**." },
      { type: "plain", fr: "**5.** Je vérifie que ma réponse est logique." },
    ],
    paragraphs: { fr: [] },
  },
  exercises: [],
  exercisePool: [],
  poolSize: 0,
  exercisePools: [easyPool, mediumPool, advancedPool],
  poolSizes: [5, 5, 5],
};
