import type { TheoryBlock } from "../../grammar-data";

export const ADJECTIFS_QUALIFICATIFS_GENERALITES: TheoryBlock[] = [
    { type: "heading", text: "L'accord des adjectifs qualificatifs", trans: { en: "Agreement of qualifying adjectives", ar: "مطابقة الصفات النعتية", fa: "مطابقت صفت‌های وصفی", ti: "ስምምዕ ቅጽላት", uk: "Узгодження якісних прикметників" } },
    {
      type: "text",
      text: "L'adjectif s'accorde toujours en {a}genre{/a} (masculin / féminin) et en {a}nombre{/a} (singulier / pluriel) avec le nom qu'il qualifie.",
      transText: {
        en: "The adjective always agrees in {a}gender{/a} (masculine / feminine) and in {a}number{/a} (singular / plural) with the noun it qualifies.",
        ar: "تطابق الصفة دائماً في {a}الجنس{/a} (مذكر / مؤنث) وفي {a}العدد{/a} (مفرد / جمع) مع الاسم الذي تصفه.",
        fa: "صفت همیشه در {a}جنس{/a} (مذکر / مؤنث) و در {a}شمار{/a} (مفرد / جمع) با اسمی که توصیف می‌کند مطابقت می‌کند.",
        ti: "ቅጽል ኩሉ ግዜ ምስቲ ዝገልጾ ስም ብ{a}ጾታ{/a} (ተባዕታይ / ኣንስታይ) ከምኡውን ብ{a}ቊጽሪ{/a} (ሓደ / ብዙሕ) ይሰማማዕ።",
        uk: "Прикметник завжди узгоджується в {a}роді{/a} (чоловічий / жіночий) та в {a}числі{/a} (однина / множина) з іменником, який він означає.",
      },
    },
    {
      type: "grid",
      headers: ["", "Singulier", "Pluriel"],
      transHeaders: {
        en: ["", "Singular", "Plural"],
        ar: ["", "مفرد", "جمع"],
        fa: ["", "مفرد", "جمع"],
        ti: ["", "ሓደ", "ብዙሕ"],
        uk: ["", "Однина", "Множина"],
      },
      boldFirstCol: true,
      rows: [
        ["{a}Masculin{/a}", "grand", "grand{a}s{/a}"],
        ["{a}Féminin{/a}", "grand{a}e{/a}", "grand{a}es{/a}"],
      ],
      transRows: {
        en: [["{a}Masculine{/a}", "grand", "grand{a}s{/a}"], ["{a}Feminine{/a}", "grand{a}e{/a}", "grand{a}es{/a}"]],
        ar: [["{a}مذكر{/a}", "grand", "grand{a}s{/a}"], ["{a}مؤنث{/a}", "grand{a}e{/a}", "grand{a}es{/a}"]],
        fa: [["{a}مذکر{/a}", "grand", "grand{a}s{/a}"], ["{a}مؤنث{/a}", "grand{a}e{/a}", "grand{a}es{/a}"]],
        ti: [["{a}ተባዕታይ{/a}", "grand", "grand{a}s{/a}"], ["{a}ኣንስታይ{/a}", "grand{a}e{/a}", "grand{a}es{/a}"]],
        uk: [["{a}Чоловічий{/a}", "grand", "grand{a}s{/a}"], ["{a}Жіночий{/a}", "grand{a}e{/a}", "grand{a}es{/a}"]],
      },
    },
    { type: "heading", text: "Formation du féminin", sub: true, accent: true, trans: { en: "Formation of the feminine", ar: "تكوين المؤنث", fa: "ساخت مؤنث", ti: "ኣፈጣጥራ ኣንስታይ", uk: "Утворення жіночого роду" } },
    {
      type: "grid",
      headers: ["Règle", "Masculin", "Féminin"],
      transHeaders: {
        en: ["Rule", "Masculine", "Feminine"],
        ar: ["القاعدة", "مذكر", "مؤنث"],
        fa: ["قاعده", "مذکر", "مؤنث"],
        ti: ["ሕጊ", "ተባዕታይ", "ኣንስታይ"],
        uk: ["Правило", "Чоловічий", "Жіночий"],
      },
      boldFirstCol: true,
      rows: [
        ["Règle générale : + {a}-e{/a}", "petit", "petite"],
        ["Déjà en -e : {a}invariable{/a}", "rapide", "rapide"],
        ["{a}-eux → -euse{/a}", "heureux", "heureuse"],
        ["{a}-eur → -euse{/a} (courant)", "travailleur", "travailleuse"],
        ["{a}-eur → -eure{/a} (comparatif)", "meilleur", "meilleure"],
        ["{a}-ien → -ienne{/a}", "ancien", "ancienne"],
        ["{a}-el → -elle{/a}", "naturel", "naturelle"],
        ["{a}-er → -ère{/a}", "premier", "première"],
        ["{a}-et → -ète / -ette{/a}", "secret", "secrète"],
        ["{a}-if → -ive{/a}", "actif", "active"],
        ["{a}-al → -ale{/a}", "normal", "normale"],
      ],
      transRows: {
        en: [["General rule: + {a}-e{/a}", "petit", "petite"], ["Already in -e: {a}invariable{/a}", "rapide", "rapide"], ["{a}-eux → -euse{/a}", "heureux", "heureuse"], ["{a}-eur → -euse{/a} (common)", "travailleur", "travailleuse"], ["{a}-eur → -eure{/a} (comparative)", "meilleur", "meilleure"], ["{a}-ien → -ienne{/a}", "ancien", "ancienne"], ["{a}-el → -elle{/a}", "naturel", "naturelle"], ["{a}-er → -ère{/a}", "premier", "première"], ["{a}-et → -ète / -ette{/a}", "secret", "secrète"], ["{a}-if → -ive{/a}", "actif", "active"], ["{a}-al → -ale{/a}", "normal", "normale"]],
        ar: [["القاعدة العامة: + {a}-e{/a}", "petit", "petite"], ["ينتهي أصلاً بـ -e: {a}لا يتغير{/a}", "rapide", "rapide"], ["{a}-eux → -euse{/a}", "heureux", "heureuse"], ["{a}-eur → -euse{/a} (شائع)", "travailleur", "travailleuse"], ["{a}-eur → -eure{/a} (تفضيلي)", "meilleur", "meilleure"], ["{a}-ien → -ienne{/a}", "ancien", "ancienne"], ["{a}-el → -elle{/a}", "naturel", "naturelle"], ["{a}-er → -ère{/a}", "premier", "première"], ["{a}-et → -ète / -ette{/a}", "secret", "secrète"], ["{a}-if → -ive{/a}", "actif", "active"], ["{a}-al → -ale{/a}", "normal", "normale"]],
        fa: [["قاعده کلی: + {a}-e{/a}", "petit", "petite"], ["از قبل به -e ختم می‌شود: {a}بدون تغییر{/a}", "rapide", "rapide"], ["{a}-eux → -euse{/a}", "heureux", "heureuse"], ["{a}-eur → -euse{/a} (رایج)", "travailleur", "travailleuse"], ["{a}-eur → -eure{/a} (تفضیلی)", "meilleur", "meilleure"], ["{a}-ien → -ienne{/a}", "ancien", "ancienne"], ["{a}-el → -elle{/a}", "naturel", "naturelle"], ["{a}-er → -ère{/a}", "premier", "première"], ["{a}-et → -ète / -ette{/a}", "secret", "secrète"], ["{a}-if → -ive{/a}", "actif", "active"], ["{a}-al → -ale{/a}", "normal", "normale"]],
        ti: [["ሓፈሻዊ ሕጊ፦ + {a}-e{/a}", "petit", "petite"], ["ድሮ ብ -e ይውዳእ፦ {a}ዘይቅየር{/a}", "rapide", "rapide"], ["{a}-eux → -euse{/a}", "heureux", "heureuse"], ["{a}-eur → -euse{/a} (ልሙድ)", "travailleur", "travailleuse"], ["{a}-eur → -eure{/a} (ኣነጻጻሪ)", "meilleur", "meilleure"], ["{a}-ien → -ienne{/a}", "ancien", "ancienne"], ["{a}-el → -elle{/a}", "naturel", "naturelle"], ["{a}-er → -ère{/a}", "premier", "première"], ["{a}-et → -ète / -ette{/a}", "secret", "secrète"], ["{a}-if → -ive{/a}", "actif", "active"], ["{a}-al → -ale{/a}", "normal", "normale"]],
        uk: [["Загальне правило: + {a}-e{/a}", "petit", "petite"], ["Уже на -e: {a}незмінний{/a}", "rapide", "rapide"], ["{a}-eux → -euse{/a}", "heureux", "heureuse"], ["{a}-eur → -euse{/a} (поширене)", "travailleur", "travailleuse"], ["{a}-eur → -eure{/a} (порівняльне)", "meilleur", "meilleure"], ["{a}-ien → -ienne{/a}", "ancien", "ancienne"], ["{a}-el → -elle{/a}", "naturel", "naturelle"], ["{a}-er → -ère{/a}", "premier", "première"], ["{a}-et → -ète / -ette{/a}", "secret", "secrète"], ["{a}-if → -ive{/a}", "actif", "active"], ["{a}-al → -ale{/a}", "normal", "normale"]],
      },
    },
    { type: "heading", text: "Formation du pluriel", sub: true, accent: true, trans: { en: "Formation of the plural", ar: "تكوين الجمع", fa: "ساخت جمع", ti: "ኣፈጣጥራ ብዙሕ", uk: "Утворення множини" } },
    {
      type: "grid",
      headers: ["Règle", "Singulier", "Pluriel"],
      transHeaders: {
        en: ["Rule", "Singular", "Plural"],
        ar: ["القاعدة", "مفرد", "جمع"],
        fa: ["قاعده", "مفرد", "جمع"],
        ti: ["ሕጊ", "ሓደ", "ብዙሕ"],
        uk: ["Правило", "Однина", "Множина"],
      },
      boldFirstCol: true,
      rows: [
        ["Règle générale : + {a}-s{/a}", "grand", "grands"],
        ["Déjà en -s ou -x : {a}invariable{/a}", "heureux", "heureux"],
        ["{a}-al → -aux{/a}", "normal", "normaux"],
        ["{a}-eau → -eaux{/a}", "beau", "beaux"],
      ],
      transRows: {
        en: [["General rule: + {a}-s{/a}", "grand", "grands"], ["Already in -s or -x: {a}invariable{/a}", "heureux", "heureux"], ["{a}-al → -aux{/a}", "normal", "normaux"], ["{a}-eau → -eaux{/a}", "beau", "beaux"]],
        ar: [["القاعدة العامة: + {a}-s{/a}", "grand", "grands"], ["ينتهي أصلاً بـ -s أو -x: {a}لا يتغير{/a}", "heureux", "heureux"], ["{a}-al → -aux{/a}", "normal", "normaux"], ["{a}-eau → -eaux{/a}", "beau", "beaux"]],
        fa: [["قاعده کلی: + {a}-s{/a}", "grand", "grands"], ["از قبل به -s یا -x ختم می‌شود: {a}بدون تغییر{/a}", "heureux", "heureux"], ["{a}-al → -aux{/a}", "normal", "normaux"], ["{a}-eau → -eaux{/a}", "beau", "beaux"]],
        ti: [["ሓፈሻዊ ሕጊ፦ + {a}-s{/a}", "grand", "grands"], ["ድሮ ብ -s ወይ -x ይውዳእ፦ {a}ዘይቅየር{/a}", "heureux", "heureux"], ["{a}-al → -aux{/a}", "normal", "normaux"], ["{a}-eau → -eaux{/a}", "beau", "beaux"]],
        uk: [["Загальне правило: + {a}-s{/a}", "grand", "grands"], ["Уже на -s або -x: {a}незмінний{/a}", "heureux", "heureux"], ["{a}-al → -aux{/a}", "normal", "normaux"], ["{a}-eau → -eaux{/a}", "beau", "beaux"]],
      },
    },
    {
      type: "text",
      label: "Adjectifs invariables",
      items: [
        "Les adjectifs de couleur dérivés d'un nom sont {a}invariables{/a}.",
        "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}",
        "Exception : rose, mauve, écarlate, pourpre → accordés.",
      ],
      bulletItems: [1, 2],
      transLabel: { en: "Invariable adjectives", ar: "صفات لا تتغير", fa: "صفت‌های بدون تغییر", ti: "ዘይቅየሩ ቅጽላት", uk: "Незмінні прикметники" },
      transItems: {
        en: ["Colour adjectives derived from a noun are {a}invariable{/a}.", "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}", "Exception: rose, mauve, écarlate, pourpre → they agree."],
        ar: ["صفات الألوان المشتقة من اسم {a}لا تتغير{/a}.", "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}", "استثناء: rose, mauve, écarlate, pourpre ← تطابق."],
        fa: ["صفت‌های رنگ که از یک اسم گرفته شده‌اند {a}بدون تغییر{/a} هستند.", "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}", "استثنا: rose, mauve, écarlate, pourpre ← مطابقت می‌کنند."],
        ti: ["ካብ ስም ዝመጹ ቅጽላት ሕብሪ {a}ዘይቅየሩ{/a} እዮም።", "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}", "ፍሉይ፦ rose, mauve, écarlate, pourpre ← ይሰማምዑ።"],
        uk: ["Прикметники кольору, утворені від іменника, є {a}незмінними{/a}.", "une robe {a}orange{/a} / des chaussures {a}marron{/a} / des yeux {a}noisette{/a}", "Виняток: rose, mauve, écarlate, pourpre → узгоджуються."],
      },
    },
  ];

export const ADJECTIFS_QUALIFICATIFS_PLACE: TheoryBlock[] = [
    { type: "heading", text: "Adjectifs à trois formes masculines", trans: { en: "Adjectives with three masculine forms", ar: "صفات بثلاث صيغ مذكرة", fa: "صفت‌هایی با سه شکل مذکر", ti: "ቅጽላት ብሰለስተ ተባዕታይ ቅርጺ", uk: "Прикметники з трьома формами чоловічого роду" } },
    {
      type: "text",
      text: "Certains adjectifs ont une forme masculine spéciale devant une {a}voyelle ou h muet{/a}.",
      transText: {
        en: "Some adjectives have a special masculine form before a {a}vowel or silent h{/a}.",
        ar: "بعض الصفات لها صيغة مذكرة خاصة قبل {a}حرف علة أو h صامت{/a}.",
        fa: "برخی صفت‌ها پیش از یک {a}حرف صدادار یا h خاموش{/a} شکل مذکر ویژه‌ای دارند.",
        ti: "ገለ ቅጽላት ቅድሚ {a}ድምጻዊ ፊደል ወይ ስቕ h{/a} ፍሉይ ተባዕታይ ቅርጺ ኣለዎም።",
        uk: "Деякі прикметники мають особливу форму чоловічого роду перед {a}голосною або німим h{/a}.",
      },
    },
    {
      type: "grid",
      headers: ["Masculin devant cons.", "Masculin devant voyelle/h muet", "Féminin", "Pluriel masc."],
      transHeaders: {
        en: ["Masculine before cons.", "Masculine before vowel/silent h", "Feminine", "Masc. plural"],
        ar: ["مذكر قبل ساكن", "مذكر قبل علة/h صامت", "مؤنث", "جمع مذكر"],
        fa: ["مذکر پیش از بی‌صدا", "مذکر پیش از صدادار/h خاموش", "مؤنث", "جمع مذکر"],
        ti: ["ተባዕታይ ቅድሚ ድምጺ-ኣልቦ", "ተባዕታይ ቅድሚ ድምጻዊ/ስቕ h", "ኣንስታይ", "ብዙሕ ተባዕታይ"],
        uk: ["Чол. перед приголосною", "Чол. перед голосною/німим h", "Жіночий", "Чол. множина"],
      },
      rows: [
        ["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"],
        ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"],
        ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"],
        ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"],
        ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"],
      ],
      transRows: {
        en: [["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"], ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"], ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"], ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"], ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"]],
        ar: [["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"], ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"], ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"], ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"], ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"]],
        fa: [["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"], ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"], ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"], ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"], ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"]],
        ti: [["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"], ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"], ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"], ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"], ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"]],
        uk: [["{a}beau{/a}", "{a}bel{/a}", "belle", "beaux"], ["{a}nouveau{/a}", "{a}nouvel{/a}", "nouvelle", "nouveaux"], ["{a}vieux{/a}", "{a}vieil{/a}", "vieille", "vieux"], ["{a}fou{/a}", "{a}fol{/a}", "folle", "fous"], ["{a}mou{/a}", "{a}mol{/a}", "molle", "mous"]],
      },
    },
    {
      type: "grid",
      headers: ["Devant consonne", "Devant voyelle / h muet"],
      transHeaders: {
        en: ["Before a consonant", "Before a vowel / silent h"],
        ar: ["قبل ساكن", "قبل علة / h صامت"],
        fa: ["پیش از بی‌صدا", "پیش از صدادار / h خاموش"],
        ti: ["ቅድሚ ድምጺ-ኣልቦ", "ቅድሚ ድምጻዊ / ስቕ h"],
        uk: ["Перед приголосною", "Перед голосною / німим h"],
      },
      rows: [
        ["un {a}beau{/a} film", "un {a}bel{/a} homme"],
        ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"],
        ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"],
      ],
      transRows: {
        en: [["un {a}beau{/a} film", "un {a}bel{/a} homme"], ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"], ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"]],
        ar: [["un {a}beau{/a} film", "un {a}bel{/a} homme"], ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"], ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"]],
        fa: [["un {a}beau{/a} film", "un {a}bel{/a} homme"], ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"], ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"]],
        ti: [["un {a}beau{/a} film", "un {a}bel{/a} homme"], ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"], ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"]],
        uk: [["un {a}beau{/a} film", "un {a}bel{/a} homme"], ["un {a}nouveau{/a} livre", "un {a}nouvel{/a} appartement"], ["un {a}vieux{/a} bâtiment", "un {a}vieil{/a} arbre"]],
      },
    },
    { type: "heading", text: "La place des adjectifs", sub: true, accent: true, trans: { en: "The position of adjectives", ar: "موضع الصفات", fa: "جایگاه صفت‌ها", ti: "ቦታ ቅጽላት", uk: "Місце прикметників" } },
    {
      type: "text",
      allBullets: true,
      text: "En français, la majorité des adjectifs se placent {a}après{/a} le nom.",
      transText: {
        en: "In French, most adjectives are placed {a}after{/a} the noun.",
        ar: "في الفرنسية، توضع معظم الصفات {a}بعد{/a} الاسم.",
        fa: "در فرانسوی، بیشتر صفت‌ها {a}بعد از{/a} اسم قرار می‌گیرند.",
        ti: "ብፈረንሳ ቋንቋ፣ መብዛሕትኦም ቅጽላት {a}ድሕሪ{/a} ስም ይቕመጡ።",
        uk: "У французькій мові більшість прикметників ставляться {a}після{/a} іменника.",
      },
      items: [
        "Mais un groupe d'adjectifs courants se placent {a}avant{/a} le nom.",
      ],
      transItems: {
        en: [
          "But a group of common adjectives are placed {a}before{/a} the noun.",
        ],
        ar: [
          "لكن مجموعة من الصفات الشائعة توضع {a}قبل{/a} الاسم.",
        ],
        fa: [
          "اما گروهی از صفت‌های رایج {a}پیش از{/a} اسم قرار می‌گیرند.",
        ],
        ti: [
          "ግን ጉጅለ ልሙዳት ቅጽላት {a}ቅድሚ{/a} ስም ይቕመጡ።",
        ],
        uk: [
          "Але група поширених прикметників ставляться {a}перед{/a} іменником.",
        ],
      },
    },
    {
      type: "grid",
      headers: ["Place", "Catégorie", "Adjectifs"],
      transHeaders: {
        en: ["Position", "Category", "Adjectives"],
        ar: ["الموضع", "الفئة", "الصفات"],
        fa: ["جایگاه", "دسته", "صفت‌ها"],
        ti: ["ቦታ", "ምድብ", "ቅጽላት"],
        uk: ["Місце", "Категорія", "Прикметники"],
      },
      boldFirstCol: true,
      rows: [
        ["{a}Avant{/a} le nom", "beauté / âge / bien / mal / taille", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"],
        ["{a}Après{/a} le nom", "nationalité, couleur, forme, religion", "français, bleu, rond, catholique"],
        ["{a}Après{/a} le nom", "adjectifs longs (participiaux…)", "intéressant, fatigant, extraordinaire"],
      ],
      transRows: {
        en: [["{a}Before{/a} the noun", "beauty / age / good / bad / size", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"], ["{a}After{/a} the noun", "nationality, colour, shape, religion", "français, bleu, rond, catholique"], ["{a}After{/a} the noun", "long adjectives (participial…)", "intéressant, fatigant, extraordinaire"]],
        ar: [["{a}قبل{/a} الاسم", "الجمال / العمر / الخير / السوء / الحجم", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"], ["{a}بعد{/a} الاسم", "الجنسية، اللون، الشكل، الدين", "français, bleu, rond, catholique"], ["{a}بعد{/a} الاسم", "صفات طويلة (اسم المفعول…)", "intéressant, fatigant, extraordinaire"]],
        fa: [["{a}پیش از{/a} اسم", "زیبایی / سن / خوب / بد / اندازه", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"], ["{a}بعد از{/a} اسم", "ملیت، رنگ، شکل، دین", "français, bleu, rond, catholique"], ["{a}بعد از{/a} اسم", "صفت‌های بلند (وجه وصفی…)", "intéressant, fatigant, extraordinaire"]],
        ti: [["{a}ቅድሚ{/a} ስም", "ጽባቐ / ዕድመ / ጽቡቕ / ሕማቕ / ዓቐን", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"], ["{a}ድሕሪ{/a} ስም", "ዜግነት፣ ሕብሪ፣ ቅርጺ፣ ሃይማኖት", "français, bleu, rond, catholique"], ["{a}ድሕሪ{/a} ስም", "ነዊሕ ቅጽላት (ኣካፋዊ…)", "intéressant, fatigant, extraordinaire"]],
        uk: [["{a}Перед{/a} іменником", "краса / вік / добре / погано / розмір", "beau, joli, jeune, vieux, bon, mauvais, grand, petit, gros"], ["{a}Після{/a} іменника", "національність, колір, форма, релігія", "français, bleu, rond, catholique"], ["{a}Після{/a} іменника", "довгі прикметники (дієприкметникові…)", "intéressant, fatigant, extraordinaire"]],
      },
    },
    {
      type: "text",
      allBullets: true,
      label: "Adjectifs qui changent de sens selon la place",
      items: [
        "{a}ancien{/a} : un {a}ancien{/a} collègue (= ex-) / un bâtiment {a}ancien{/a} (= vieux)",
        "{a}cher{/a} : un {a}cher{/a} ami (= bien-aimé) / un restaurant {a}cher{/a} (= coûteux)",
        "{a}grand{/a} : un {a}grand{/a} homme (= illustre) / un homme {a}grand{/a} (= de haute taille)",
        "{a}propre{/a} : ma {a}propre{/a} voiture (= à moi) / une voiture {a}propre{/a} (= clean)",
        "{a}pauvre{/a} : ce {a}pauvre{/a} garçon (= à plaindre) / un garçon {a}pauvre{/a} (= sans argent)",
      ],
      transLabel: { en: "Adjectives that change meaning depending on position", ar: "صفات يتغير معناها حسب الموضع", fa: "صفت‌هایی که معنایشان بسته به جایگاه تغییر می‌کند", ti: "ብቦታ ትርጉሞም ዝቕይሩ ቅጽላት", uk: "Прикметники, що змінюють значення залежно від місця" },
      transItems: {
        en: ["{a}ancien{/a}: un {a}ancien{/a} collègue (= former) / un bâtiment {a}ancien{/a} (= old)", "{a}cher{/a}: un {a}cher{/a} ami (= dear) / un restaurant {a}cher{/a} (= expensive)", "{a}grand{/a}: un {a}grand{/a} homme (= great) / un homme {a}grand{/a} (= tall)", "{a}propre{/a}: ma {a}propre{/a} voiture (= my own) / une voiture {a}propre{/a} (= clean)", "{a}pauvre{/a}: ce {a}pauvre{/a} garçon (= to be pitied) / un garçon {a}pauvre{/a} (= penniless)"],
        ar: ["{a}ancien{/a}: un {a}ancien{/a} collègue (= سابق) / un bâtiment {a}ancien{/a} (= قديم)", "{a}cher{/a}: un {a}cher{/a} ami (= عزيز) / un restaurant {a}cher{/a} (= باهظ)", "{a}grand{/a}: un {a}grand{/a} homme (= عظيم) / un homme {a}grand{/a} (= طويل القامة)", "{a}propre{/a}: ma {a}propre{/a} voiture (= خاصتي) / une voiture {a}propre{/a} (= نظيفة)", "{a}pauvre{/a}: ce {a}pauvre{/a} garçon (= يُرثى له) / un garçon {a}pauvre{/a} (= فقير المال)"],
        fa: ["{a}ancien{/a}: un {a}ancien{/a} collègue (= سابق) / un bâtiment {a}ancien{/a} (= کهنه)", "{a}cher{/a}: un {a}cher{/a} ami (= عزیز) / un restaurant {a}cher{/a} (= گران)", "{a}grand{/a}: un {a}grand{/a} homme (= بزرگ‌مرد) / un homme {a}grand{/a} (= بلندقامت)", "{a}propre{/a}: ma {a}propre{/a} voiture (= مال خودم) / une voiture {a}propre{/a} (= تمیز)", "{a}pauvre{/a}: ce {a}pauvre{/a} garçon (= بیچاره) / un garçon {a}pauvre{/a} (= بی‌پول)"],
        ti: ["{a}ancien{/a}: un {a}ancien{/a} collègue (= ቀደም) / un bâtiment {a}ancien{/a} (= ኣረጊት)", "{a}cher{/a}: un {a}cher{/a} ami (= ፍቑር) / un restaurant {a}cher{/a} (= ክቡር ዋጋ)", "{a}grand{/a}: un {a}grand{/a} homme (= ዓቢ ሰብ) / un homme {a}grand{/a} (= ነዊሕ ቁመት)", "{a}propre{/a}: ma {a}propre{/a} voiture (= ናተይ) / une voiture {a}propre{/a} (= ጽሩይ)", "{a}pauvre{/a}: ce {a}pauvre{/a} garçon (= ዘሕዝን) / un garçon {a}pauvre{/a} (= ድኻ)"],
        uk: ["{a}ancien{/a}: un {a}ancien{/a} collègue (= колишній) / un bâtiment {a}ancien{/a} (= старий)", "{a}cher{/a}: un {a}cher{/a} ami (= дорогий/любий) / un restaurant {a}cher{/a} (= дорогий за ціною)", "{a}grand{/a}: un {a}grand{/a} homme (= видатний) / un homme {a}grand{/a} (= високий на зріст)", "{a}propre{/a}: ma {a}propre{/a} voiture (= власна) / une voiture {a}propre{/a} (= чиста)", "{a}pauvre{/a}: ce {a}pauvre{/a} garçon (= нещасний) / un garçon {a}pauvre{/a} (= бідний/без грошей)"],
      },
    },
  ];
