import type { ConjLesson } from "../../conjugation-data";

export const NEGATION_PASSE_COMPOSE: ConjLesson = {
  slug: "negation-passe-compose",
  code: "R5.4",
  level: "A1",
  title: "Négation au passé composé",
  theory: [
    {
      type: "plain_list",
      items: [
        "Au passé composé, la négation encadre l'auxiliaire (avoir ou être), pas le participe passé.",
      ],
      transItems: {
        en: ["In the passé composé, the negation surrounds the auxiliary (avoir or être), not the past participle."],
        ar: ["في الماضي المركّب، يحيط النفي بالفعل المساعد (avoir أو être)، وليس اسم المفعول."],
        fa: ["در گذشته‌ی نقلی، نفی فعل کمکی (avoir یا être) را احاطه می‌کند، نه اسم مفعول را."],
        ti: ["ኣብ ሕሉፍ ግዜ፣ እቲ ኣሉታ ነቲ ሓጋዚ ግሲ (avoir ወይ être) የጠቓልሎ፣ ኣይኮነን ነቲ ክፍሊ-ግሲ።"],
        uk: ["У passé composé заперечення обрамлює допоміжне дієслово (avoir або être), а не дієприкметник."],
      },
    },
    {
      type: "grid",
      headers: ["Affirmatif", "Négatif"],
      rows: [
        ["J'ai mangé", "Je n'ai pas mangé"],
        ["Tu es parti", "Tu n'es pas parti"],
        ["Elle a fini", "Elle n'a pas fini"],
        ["Nous avons vu", "Nous n'avons pas vu"],
      ],
      transHeaders: {
        en: ["Affirmative", "Negative"],
        ar: ["مثبت", "منفي"],
        fa: ["مثبت", "منفی"],
        ti: ["ኣረጋጋጺ", "ኣሉታዊ"],
        uk: ["Стверджувальний", "Заперечний"],
      },
      transRows: {
        en: [["J'ai mangé (I ate)", "Je n'ai pas mangé (I didn't eat)"], ["Tu es parti (You left)", "Tu n'es pas parti (You didn't leave)"], ["Elle a fini (She finished)", "Elle n'a pas fini (She didn't finish)"], ["Nous avons vu (We saw)", "Nous n'avons pas vu (We didn't see)"]],
        ar: [["J'ai mangé (أكلتُ)", "Je n'ai pas mangé (لم آكل)"], ["Tu es parti (غادرتَ)", "Tu n'es pas parti (لم تغادر)"], ["Elle a fini (أنهت)", "Elle n'a pas fini (لم تنتهِ)"], ["Nous avons vu (رأينا)", "Nous n'avons pas vu (لم نرَ)"]],
        fa: [["J'ai mangé (غذا خوردم)", "Je n'ai pas mangé (غذا نخوردم)"], ["Tu es parti (رفتی)", "Tu n'es pas parti (نرفتی)"], ["Elle a fini (تمام کرد)", "Elle n'a pas fini (تمام نکرد)"], ["Nous avons vu (دیدیم)", "Nous n'avons pas vu (ندیدیم)"]],
        ti: [["J'ai mangé (በሊዐ)", "Je n'ai pas mangé (ኣይበላዕኩን)"], ["Tu es parti (ከይድካ)", "Tu n'es pas parti (ኣይከድካን)"], ["Elle a fini (ወዲኣ)", "Elle n'a pas fini (ኣይወድአትን)"], ["Nous avons vu (ርኢና)", "Nous n'avons pas vu (ኣይረኣናን)"]],
        uk: [["J'ai mangé (Я поїв)", "Je n'ai pas mangé (Я не їв)"], ["Tu es parti (Ти пішов)", "Tu n'es pas parti (Ти не пішов)"], ["Elle a fini (Вона закінчила)", "Elle n'a pas fini (Вона не закінчила)"], ["Nous avons vu (Ми бачили)", "Nous n'avons pas vu (Ми не бачили)"]],
      },
    },
    {
      type: "plain_list",
      items: [
        "Structure : sujet + ne + auxiliaire + pas + participe passé",
      ],
      transItems: {
        en: ["Structure: subject + ne + auxiliary + pas + past participle"],
        ar: ["البنية: الفاعل + ne + الفعل المساعد + pas + اسم المفعول"],
        fa: ["ساختار: فاعل + ne + فعل کمکی + pas + اسم مفعول"],
        ti: ["ቅርጺ፦ ርእሲ + ne + ሓጋዚ ግሲ + pas + ክፍሊ-ግሲ"],
        uk: ["Структура: підмет + ne + допоміжне дієслово + pas + дієприкметник"],
      },
    },
    {
      type: "plain_list",
      items: [
        "Avec d'autres mots négatifs : jamais, plus, rien, personne (après le participe passé pour personne).",
      ],
      transItems: {
        en: ["With other negative words: jamais (never), plus (no longer), rien (nothing), personne (nobody) — personne goes after the past participle."],
        ar: ["مع كلمات نفي أخرى: jamais (أبداً)، plus (لم يعد)، rien (لا شيء)، personne (لا أحد) — personne توضع بعد اسم المفعول."],
        fa: ["با کلمات منفی دیگر: jamais (هرگز)، plus (دیگر نه)، rien (هیچ‌چیز)، personne (هیچ‌کس) — personne بعد از اسم مفعول می‌آید."],
        ti: ["ምስ ካልኦት ኣሉታዊ ቃላት፦ jamais (ፈጺሙ)፣ plus (ደጊም)፣ rien (ዋላ ሓንቲ)፣ personne (ዋላ ሓደ) — personne ድሕሪ ክፍሊ-ግሲ ይመጽእ።"],
        uk: ["З іншими заперечними словами: jamais (ніколи), plus (більше не), rien (нічого), personne (ніхто) — personne ставиться після дієприкметника."],
      },
    },
    {
      type: "grid",
      headers: ["Mot négatif", "Exemple"],
      rows: [
        ["jamais", "Je n'ai jamais mangé de sushi."],
        ["plus", "Il n'a plus travaillé ici."],
        ["rien", "Nous n'avons rien vu."],
        ["personne", "Elle n'a vu personne."],
      ],
      transHeaders: {
        en: ["Negative word", "Example"],
        ar: ["كلمة النفي", "مثال"],
        fa: ["کلمه‌ی منفی", "مثال"],
        ti: ["ኣሉታዊ ቃል", "ኣብነት"],
        uk: ["Заперечне слово", "Приклад"],
      },
      transRows: {
        en: [["jamais (never)", "Je n'ai jamais mangé de sushi. (I have never eaten sushi.)"], ["plus (no longer)", "Il n'a plus travaillé ici. (He no longer worked here.)"], ["rien (nothing)", "Nous n'avons rien vu. (We saw nothing.)"], ["personne (nobody)", "Elle n'a vu personne. (She saw nobody.)"]],
        ar: [["jamais (أبداً)", "Je n'ai jamais mangé de sushi. (لم آكل السوشي أبداً.)"], ["plus (لم يعد)", "Il n'a plus travaillé ici. (لم يعد يعمل هنا.)"], ["rien (لا شيء)", "Nous n'avons rien vu. (لم نرَ شيئاً.)"], ["personne (لا أحد)", "Elle n'a vu personne. (لم ترَ أحداً.)"]],
        fa: [["jamais (هرگز)", "Je n'ai jamais mangé de sushi. (هرگز سوشی نخورده‌ام.)"], ["plus (دیگر نه)", "Il n'a plus travaillé ici. (دیگر اینجا کار نکرد.)"], ["rien (هیچ‌چیز)", "Nous n'avons rien vu. (هیچ‌چیز ندیدیم.)"], ["personne (هیچ‌کس)", "Elle n'a vu personne. (هیچ‌کس را ندید.)"]],
        ti: [["jamais (ፈጺሙ)", "Je n'ai jamais mangé de sushi. (ፈጺመ ሱሺ ኣይበላዕኩን።)"], ["plus (ደጊም)", "Il n'a plus travaillé ici. (ደጊም ኣብዚ ኣይሰርሐን።)"], ["rien (ዋላ ሓንቲ)", "Nous n'avons rien vu. (ዋላ ሓንቲ ኣይረኣናን።)"], ["personne (ዋላ ሓደ)", "Elle n'a vu personne. (ዋላ ሓደ ኣይረኣየትን።)"]],
        uk: [["jamais (ніколи)", "Je n'ai jamais mangé de sushi. (Я ніколи не їв суші.)"], ["plus (більше не)", "Il n'a plus travaillé ici. (Він більше тут не працював.)"], ["rien (нічого)", "Nous n'avons rien vu. (Ми нічого не бачили.)"], ["personne (ніхто)", "Elle n'a vu personne. (Вона нікого не бачила.)"]],
      },
    },
  ],
  exercises: [
    {
      type: "fill",
      title: "Mettez les phrases au passé composé négatif (ne … pas)",
      instruction: "Complétez avec la forme négative.",
      transInstruction: { en: "Complete with the negative form.", ar: "أكمل بصيغة النفي.", fa: "با صورت منفی کامل کنید.", ti: "ብኣሉታዊ ቅርጺ ምላእ.", uk: "Доповніть заперечною формою." },
      items: [],
      poolSize: 6,
      pool: [
        { sentence: "Il ___ (ne pas finir) ses devoirs.", hint: "ne pas finir", answer: "n'a pas fini" },
        { sentence: "Nous ___ (ne pas voir) ce film.", hint: "ne pas voir", answer: "n'avons pas vu" },
        { sentence: "Elle ___ (ne pas aller) à la fête.", hint: "ne pas aller", answer: "n'est pas allée" },
        { sentence: "Tu ___ (ne pas manger) ce matin.", hint: "ne pas manger", answer: "n'as pas mangé" },
        { sentence: "Ils ___ (ne pas venir) hier.", hint: "ne pas venir", answer: "ne sont pas venus" },
        { sentence: "Je ___ (ne pas comprendre) la leçon.", hint: "ne pas comprendre", answer: "n'ai pas compris" },
        { sentence: "Vous ___ (ne pas partir) à l'heure.", hint: "ne pas partir", answer: "n'êtes pas partis" },
        { sentence: "Elle ___ (ne pas lire) ce livre.", hint: "ne pas lire", answer: "n'a pas lu" },
        { sentence: "Nous ___ (ne pas dormir) bien.", hint: "ne pas dormir", answer: "n'avons pas dormi" },
        { sentence: "Il ___ (ne pas répondre) au message.", hint: "ne pas répondre", answer: "n'a pas répondu" },
        { sentence: "Tu ___ (ne pas prendre) ton sac.", hint: "ne pas prendre", answer: "n'as pas pris" },
        { sentence: "Je ___ (ne pas rester) longtemps.", hint: "ne pas rester", answer: "ne suis pas resté" },
        { sentence: "Vous ___ (ne pas écrire) la lettre.", hint: "ne pas écrire", answer: "n'avez pas écrit" },
      ],
    },
    {
      type: "fill",
      title: "Transformez avec le mot négatif indiqué",
      instruction: "Complétez avec la forme négative indiquée.",
      transInstruction: { en: "Complete with the indicated negative form.", ar: "أكمل بصيغة النفي المحددة.", fa: "با صورت منفی مشخص‌شده کامل کنید.", ti: "ብእቲ ዝተጠቕሰ ኣሉታዊ ቅርጺ ምላእ.", uk: "Доповніть зазначеною заперечною формою." },
      items: [],
      poolSize: 6,
      pool: [
        { sentence: "Je ___ (ne jamais visiter) Paris.", hint: "ne jamais visiter", answer: "n'ai jamais visité" },
        { sentence: "Il ___ (ne plus travailler) ici.", hint: "ne plus travailler", answer: "n'a plus travaillé" },
        { sentence: "Nous ___ (ne rien comprendre) à l'examen.", hint: "ne rien comprendre", answer: "n'avons rien compris" },
        { sentence: "Elle ___ (ne jamais goûter) ce plat.", hint: "ne jamais goûter", answer: "n'a jamais goûté" },
        { sentence: "Tu ___ (ne plus sortir) le soir.", hint: "ne plus sortir", answer: "n'es plus sorti" },
        { sentence: "Ils ___ (ne rien dire) pendant la réunion.", hint: "ne rien dire", answer: "n'ont rien dit" },
        { sentence: "Je ___ (ne jamais perdre) mes clés.", hint: "ne jamais perdre", answer: "n'ai jamais perdu" },
        { sentence: "Elle ___ (ne plus entendre) cette chanson.", hint: "ne plus entendre", answer: "n'a plus entendu" },
        { sentence: "Vous ___ (ne rien faire) hier.", hint: "ne rien faire", answer: "n'avez rien fait" },
        { sentence: "Il ___ (ne jamais boire) de café.", hint: "ne jamais boire", answer: "n'a jamais bu" },
        { sentence: "Nous ___ (ne plus vivre) en France.", hint: "ne plus vivre", answer: "n'avons plus vécu" },
      ],
    },
    {
      type: "fill",
      title: "Répondez à la question à la forme négative",
      instruction: "Répondez négativement à la question.",
      transInstruction: { en: "Answer the question in the negative.", ar: "أجب على السؤال بالنفي.", fa: "به سؤال به‌صورت منفی پاسخ دهید.", ti: "ነቲ ሕቶ ብኣሉታ መልሲ.", uk: "Дайте заперечну відповідь на запитання." },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "— Tu as vu Marie hier ? — Non, je ___ (ne pas voir).", hint: "ne pas voir", answer: "ne l'ai pas vue" },
        { sentence: "— Vous êtes allés au marché ? — Non, nous ___ (ne pas aller).", hint: "ne pas aller", answer: "n'y sommes pas allés" },
        { sentence: "— Il a fini le projet ? — Non, il ___ (ne pas finir).", hint: "ne pas finir", answer: "ne l'a pas fini" },
        { sentence: "— Tu as mangé ce matin ? — Non, je ___ (ne rien manger).", hint: "ne rien manger", answer: "n'ai rien mangé" },
        { sentence: "— Elle est venue à la fête ? — Non, elle ___ (ne pas venir).", hint: "ne pas venir", answer: "n'est pas venue" },
        { sentence: "— Ils ont compris la leçon ? — Non, ils ___ (ne rien comprendre).", hint: "ne rien comprendre", answer: "n'ont rien compris" },
        { sentence: "— Tu as voyagé en train ? — Non, je ___ (ne jamais voyager).", hint: "ne jamais voyager", answer: "n'ai jamais voyagé" },
        { sentence: "— Vous avez rencontré quelqu'un ? — Non, nous ___ (ne voir personne).", hint: "ne voir personne", answer: "n'avons vu personne" },
      ],
    },
    {
      type: "classify",
      title: "Exercice 4",
      instruction: "Classez le mot négatif utilisé dans chaque phrase.",
      transInstruction: { en: "Sort the negative word used in each sentence.", ar: "صنّف كلمة النفي المستخدمة في كل جملة.", fa: "کلمه‌ی منفی به‌کاررفته در هر جمله را دسته‌بندی کنید.", ti: "ኣብ ነፍሲ ወከፍ ሓሳብ ዝተጠቀመሉ ኣሉታዊ ቃል ሸነኽ።", uk: "Розсортуйте заперечне слово, вжите в кожному реченні." },
      categories: ["ne … pas", "ne … jamais", "ne … plus", "ne … rien"],
      items: [],
      pool: [
        { word: "Je n'ai pas mangé ce matin.", categoryIdx: 0 },
        { word: "Il n'a jamais voyagé en avion.", categoryIdx: 1 },
        { word: "Elle n'a plus travaillé ici.", categoryIdx: 2 },
        { word: "Nous n'avons rien vu.", categoryIdx: 3 },
        { word: "Tu n'es pas venu à la fête.", categoryIdx: 0 },
        { word: "Ils n'ont jamais compris.", categoryIdx: 1 },
        { word: "Il n'a plus répondu.", categoryIdx: 2 },
        { word: "Elle n'a rien fait hier.", categoryIdx: 3 },
        { word: "Vous n'avez pas terminé.", categoryIdx: 0 },
        { word: "Je n'ai jamais goûté ce plat.", categoryIdx: 1 },
      ],
      poolSize: 6,
    },
    {
      type: "word_order",
      title: "Exercice 5",
      instruction: "Remettez les mots dans le bon ordre pour former une phrase négative correcte.",
      transInstruction: { en: "Put the words back in the correct order to form a correct negative sentence.", ar: "أعد ترتيب الكلمات لتكوين جملة سلبية صحيحة.", fa: "کلمات را به ترتیب درست بچینید تا جمله‌ی منفی درست بسازید.", ti: "ነተን ቃላት ቅኑዕ ኣሉታዊ ሓሳብ ንምግባር ብቅኑዕ ስርዓት መድብ።", uk: "Розставте слова у правильному порядку, щоб утворити правильне заперечне речення." },
      items: [],
      pool: [
        { sentence: "Je n'ai pas mangé ce matin.", words: ["Je", "n'ai", "pas", "mangé", "ce", "matin."] },
        { sentence: "Elle n'est pas venue à la fête.", words: ["Elle", "n'est", "pas", "venue", "à", "la", "fête."] },
        { sentence: "Ils n'ont rien vu.", words: ["Ils", "n'ont", "rien", "vu."] },
        { sentence: "Tu n'as jamais goûté ce plat.", words: ["Tu", "n'as", "jamais", "goûté", "ce", "plat."] },
        { sentence: "Nous n'avons plus travaillé ensemble.", words: ["Nous", "n'avons", "plus", "travaillé", "ensemble."] },
        { sentence: "Il n'a vu personne hier.", words: ["Il", "n'a", "vu", "personne", "hier."] },
      ],
      poolSize: 4,
    },
    {
      type: "write",
      title: "Exercice 6",
      instruction: "Écrivez une phrase au passé composé à la forme négative (ne … pas, ne … jamais, ne … plus ou ne … rien).\nUtilisez le verbe proposé.",
      transInstruction: { en: "Write a sentence in the passé composé in the negative (ne … pas, ne … jamais, ne … plus or ne … rien).\nUse the verb provided.", ar: "اكتب جملة في الماضي المركب بصيغة النفي (ne … pas، ne … jamais، ne … plus أو ne … rien).\nاستخدم الفعل المقترح.", fa: "یک جمله در گذشته‌ی مرکب به‌صورت منفی بنویسید (ne … pas، ne … jamais، ne … plus یا ne … rien).\nاز فعل پیشنهادی استفاده کنید.", ti: "ሓደ ሓሳብ ብሕሉፍ ውሁድ ብኣሉታዊ ቅርጺ (ne … pas፣ ne … jamais፣ ne … plus ወይ ne … rien) ጽሓፍ።\nእቲ ዝቐረበ ግሲ ተጠቐም።", uk: "Напишіть речення в passé composé у заперечній формі (ne … pas, ne … jamais, ne … plus або ne … rien).\nВикористайте запропоноване дієслово." },
      verbPool: ["manger", "venir", "voir", "finir", "faire", "aller", "comprendre"],
      verbPoolSize: 3,
    },
  ],
};
