import type { GrammarLesson } from "../../grammar-data";

/** Unité 13 — Le pluriel des noms (G2.3) */
export const A1_GR_PLURIEL_NOMS: GrammarLesson = {
  slug: "a1-gr-pluriel-noms",
  code: "G2.3",
  level: "A1",
  title: "Le pluriel des noms",
  theory: [
    {
      type: "heading",
      text: "Utilisation",
      trans: { en: "Usage", ar: "الاستخدام", fa: "کاربرد", ti: "ኣጠቓቕማ", uk: "Вживання" },
    },
    {
      type: "plain_list",
      items: [
        "On utilise la forme du pluriel quand le nom désigne plusieurs éléments.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["We use the plural form when the noun names several elements."],
        ar: ["نستعمل صيغة الجمع عندما يدل الاسم على عدة عناصر."],
        fa: ["وقتی اسم چند عنصر را نشان می‌دهد از صورت جمع استفاده می‌کنیم."],
        ti: ["እቲ ስም ብዙሓት ነገራት ምስ ዘመልክት፣ ባዙሕ ቅርጺ ንጥቀም።"],
        uk: ["Форму множини вживаємо, коли іменник позначає кілька елементів."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "une pomme — {a}des{/a} pomme{a}s{/a}",
      ],
      noBulletItems: [0],
    },
    {
      type: "heading",
      text: "Formes",
      trans: { en: "Forms", ar: "الصيغ", fa: "صورت‌ها", ti: "ቅርጽታት", uk: "Форми" },
    },
    {
      type: "plain_list",
      items: [
        "Un nom s'emploie toujours avec un déterminant, qui indique le nombre. Dans les dictionnaires, les noms sont au singulier.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["A noun is always used with a determiner, which shows the number. In dictionaries, nouns are in the singular."],
        ar: ["يُستعمل الاسم دائماً مع محدد يدل على العدد. في القواميس، الأسماء في المفرد."],
        fa: ["اسم همیشه با یک حرف تعریف به کار می‌رود که شمار را نشان می‌دهد. در فرهنگ لغت، اسم‌ها مفردند."],
        ti: ["ስም ኩሉ ግዜ ምስ መወሰኒ ይጥቀም፣ ቁጽሪ የመልክት። ኣብ መዝገበ-ቃላት፣ ስማት ብንጽል እዮም።"],
        uk: ["Іменник завжди вживається з означенням, яке показує число. У словниках іменники стоять в однині."],
      },
    },
    {
      type: "grid",
      headers: ["", "Indéfini", "Défini", "Nom"],
      transHeaders: {
        en: ["", "Indefinite", "Definite", "Noun"],
        ar: ["", "نكرة", "معرفة", "اسم"],
        fa: ["", "نکره", "معرفه", "اسم"],
        ti: ["", "ዘይፍሉይ", "ፍሉይ", "ስም"],
        uk: ["", "Неозначений", "Означений", "Іменник"],
      },
      boldFirstCol: true,
      rows: [
        ["Singulier", "{a}une{/a}", "{a}la{/a}", "tasse"],
        ["Pluriel", "{a}des{/a}", "{a}les{/a}", "tasse{a}s{/a}"],
      ],
    },
    {
      type: "heading",
      text: "Cas général",
      trans: { en: "General case", ar: "الحالة العامة", fa: "مورد کلی", ti: "ሓፈሻዊ ኩነት", uk: "Загальний випадок" },
    },
    {
      type: "plain_list",
      items: [
        "Nom pluriel = nom singulier + {a}-s{/a}.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["Plural noun = singular noun + {a}-s{/a}."],
        ar: ["الاسم الجمع = الاسم المفرد + {a}-s{/a}."],
        fa: ["اسم جمع = اسم مفرد + {a}-s{/a}."],
        ti: ["ባዙሕ ስም = ንጽል ስም + {a}-s{/a}."],
        uk: ["Іменник у множині = іменник в однині + {a}-s{/a}."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "un fruit → des fruit{a}s{/a}",
        "une banane → des banane{a}s{/a}",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "plain_list",
      items: [
        "Si le nom singulier se termine par {a}s{/a}, {a}x{/a} ou {a}z{/a}, le pluriel ne change pas.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["If the singular noun ends in {a}s{/a}, {a}x{/a} or {a}z{/a}, the plural does not change."],
        ar: ["إذا انتهى الاسم المفرد بـ {a}s{/a} أو {a}x{/a} أو {a}z{/a}، لا يتغيّر الجمع."],
        fa: ["اگر اسم مفرد به {a}s{/a}، {a}x{/a} یا {a}z{/a} ختم شود، جمع تغییر نمی‌کند."],
        ti: ["እቲ ንጽል ስም ብ {a}s{/a}፣ {a}x{/a} ወይ {a}z{/a} እንተወዲኡ፣ እቲ ባዙሕ ኣይቕየርን።"],
        uk: ["Якщо іменник в однині закінчується на {a}s{/a}, {a}x{/a} або {a}z{/a}, множина не змінюється."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "le bra{a}s{/a} → les bra{a}s{/a}",
        "une noi{a}x{/a} → des noi{a}x{/a}",
        "un ne{a}z{/a} → des ne{a}z{/a}",
      ],
      noBulletItems: [0, 1, 2],
    },
    {
      type: "heading",
      text: "Formes particulières",
      trans: { en: "Special forms", ar: "صيغ خاصة", fa: "صورت‌های خاص", ti: "ፍሉያት ቅርጽታት", uk: "Особливі форми" },
    },
    {
      type: "plain_list",
      items: [
        "Certains noms forment leur pluriel autrement selon leur terminaison. Choisissez une terminaison pour voir les exemples et les exceptions.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["Some nouns form their plural differently depending on their ending. Choose an ending to see the examples and the exceptions."],
        ar: ["بعض الأسماء تكوّن جمعها بطريقة مختلفة بحسب نهايتها. اختر نهاية لرؤية الأمثلة والاستثناءات."],
        fa: ["برخی اسم‌ها بسته به پایان‌شان جمع متفاوتی می‌سازند. یک پایان را انتخاب کنید تا مثال‌ها و استثناها را ببینید."],
        ti: ["ገለ ስማት ከም መወዳእታኦም ባዙሖም ብኻልእ መገዲ ይሰርሑ። ኣብነታትን ፍሉያትን ንምርኣይ ሓደ መወዳእታ ምረጽ።"],
        uk: ["Деякі іменники утворюють множину інакше залежно від закінчення. Оберіть закінчення, щоб побачити приклади та винятки."],
      },
    },
    {
      type: "selector",
      buttonCols: 4,
      tabs: [
        {
          label: "-al",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-al{/a} au singulier changent en {a}-aux{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-al{/a} in the singular change to {a}-aux{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-al{/a} في المفرد تصبح {a}-aux{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-al{/a} ختم می‌شوند در جمع به {a}-aux{/a} تغییر می‌کنند."],
                ti: ["ብንጽል ብ {a}-al{/a} ዝውድኡ ቃላት ኣብ ባዙሕ ናብ {a}-aux{/a} ይቕየሩ።"],
                uk: ["Слова на {a}-al{/a} в однині змінюються на {a}-aux{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un anim{a}al{/a}", "des anim{a}aux{/a}"],
                ["un journ{a}al{/a}", "des journ{a}aux{/a}"],
                ["un chev{a}al{/a}", "des chev{a}aux{/a}"],
              ],
            },
            {
              type: "highlight",
              label: "Exceptions",
              transLabel: {
                en: "Exceptions",
                ar: "استثناءات",
                fa: "استثناها",
                ti: "ፍሉያት",
                uk: "Винятки",
              },
              items: [
                "un b{a}al{/a} → des bal{a}s{/a}",
                "un carnav{a}al{/a} → des carnaval{a}s{/a}",
                "un festiv{a}al{/a} → des festival{a}s{/a}",
                "un récit{a}al{/a} → des récital{a}s{/a}",
              ],
              noBulletItems: [0, 1, 2, 3],
            },
          ],
        },
        {
          label: "-ail",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-ail{/a} au singulier prennent un {a}-s{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-ail{/a} in the singular take an {a}-s{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-ail{/a} في المفرد تأخذ {a}-s{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-ail{/a} ختم می‌شوند در جمع {a}-s{/a} می‌گیرند."],
                ti: ["ብንጽል ብ {a}-ail{/a} ዝውድኡ ቃላት ኣብ ባዙሕ {a}-s{/a} ይወስዱ።"],
                uk: ["Слова на {a}-ail{/a} в однині отримують {a}-s{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un déta{a}il{/a}", "des déta{a}ils{/a}"],
                ["un porta{a}il{/a}", "des porta{a}ils{/a}"],
                ["un éventa{a}il{/a}", "des éventa{a}ils{/a}"],
              ],
            },
            {
              type: "highlight",
              label: "Exceptions",
              transLabel: {
                en: "Exceptions",
                ar: "استثناءات",
                fa: "استثناها",
                ti: "ፍሉያት",
                uk: "Винятки",
              },
              items: [
                "un trav{a}ail{/a} → des trav{a}aux{/a}",
                "un vitr{a}ail{/a} → des vitr{a}aux{/a}",
                "un cor{a}ail{/a} → des cor{a}aux{/a}",
                "un b{a}ail{/a} → des b{a}aux{/a}",
              ],
              noBulletItems: [0, 1, 2, 3],
            },
          ],
        },
        {
          label: "-eau",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-eau{/a} au singulier changent en {a}-eaux{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-eau{/a} in the singular change to {a}-eaux{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-eau{/a} في المفرد تصبح {a}-eaux{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-eau{/a} ختم می‌شوند در جمع به {a}-eaux{/a} تغییر می‌کنند."],
                ti: ["ብንጽል ብ {a}-eau{/a} ዝውድኡ ቃላት ኣብ ባዙሕ ናብ {a}-eaux{/a} ይቕየሩ።"],
                uk: ["Слова на {a}-eau{/a} в однині змінюються на {a}-eaux{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un bat{a}eau{/a}", "des bat{a}eaux{/a}"],
                ["un gât{a}eau{/a}", "des gât{a}eaux{/a}"],
                ["un chap{a}eau{/a}", "des chap{a}eaux{/a}"],
              ],
            },
          ],
        },
        {
          label: "-au",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-au{/a} au singulier changent en {a}-aux{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-au{/a} in the singular change to {a}-aux{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-au{/a} في المفرد تصبح {a}-aux{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-au{/a} ختم می‌شوند در جمع به {a}-aux{/a} تغییر می‌کنند."],
                ti: ["ብንጽል ብ {a}-au{/a} ዝውድኡ ቃላት ኣብ ባዙሕ ናብ {a}-aux{/a} ይቕየሩ።"],
                uk: ["Слова на {a}-au{/a} в однині змінюються на {a}-aux{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un tuy{a}au{/a}", "des tuy{a}aux{/a}"],
                ["un noy{a}au{/a}", "des noy{a}aux{/a}"],
                ["un boy{a}au{/a}", "des boy{a}aux{/a}"],
              ],
            },
            {
              type: "highlight",
              label: "Exceptions",
              transLabel: {
                en: "Exceptions",
                ar: "استثناءات",
                fa: "استثناها",
                ti: "ፍሉያት",
                uk: "Винятки",
              },
              items: [
                "un land{a}au{/a} → des landau{a}s{/a}",
                "un sarr{a}au{/a} → des sarrau{a}s{/a}",
              ],
              noBulletItems: [0, 1],
            },
          ],
        },
        {
          label: "-eu",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-eu{/a} au singulier changent en {a}-eux{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-eu{/a} in the singular change to {a}-eux{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-eu{/a} في المفرد تصبح {a}-eux{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-eu{/a} ختم می‌شوند در جمع به {a}-eux{/a} تغییر می‌کنند."],
                ti: ["ብንጽል ብ {a}-eu{/a} ዝውድኡ ቃላት ኣብ ባዙሕ ናብ {a}-eux{/a} ይቕየሩ።"],
                uk: ["Слова на {a}-eu{/a} в однині змінюються на {a}-eux{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un f{a}eu{/a}", "des f{a}eux{/a}"],
                ["un j{a}eu{/a}", "des j{a}eux{/a}"],
                ["un li{a}eu{/a}", "des li{a}eux{/a}"],
              ],
            },
            {
              type: "highlight",
              label: "Exceptions",
              transLabel: {
                en: "Exceptions",
                ar: "استثناءات",
                fa: "استثناها",
                ti: "ፍሉያት",
                uk: "Винятки",
              },
              items: [
                "un pn{a}eu{/a} → des pneu{a}s{/a}",
                "un bl{a}eu{/a} → des bleu{a}s{/a}",
              ],
              noBulletItems: [0, 1],
            },
          ],
        },
        {
          label: "-ou",
          content: [
            {
              type: "plain_list",
              items: [
                "Les mots terminant par {a}-ou{/a} au singulier prennent un {a}-s{/a} au pluriel.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Words ending in {a}-ou{/a} in the singular take an {a}-s{/a} in the plural."],
                ar: ["الكلمات المنتهية بـ {a}-ou{/a} في المفرد تأخذ {a}-s{/a} في الجمع."],
                fa: ["کلماتی که در مفرد به {a}-ou{/a} ختم می‌شوند در جمع {a}-s{/a} می‌گیرند."],
                ti: ["ብንጽል ብ {a}-ou{/a} ዝውድኡ ቃላት ኣብ ባዙሕ {a}-s{/a} ይወስዱ።"],
                uk: ["Слова на {a}-ou{/a} в однині отримують {a}-s{/a} у множині."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un tr{a}ou{/a}", "des trou{a}s{/a}"],
                ["un cl{a}ou{/a}", "des clou{a}s{/a}"],
                ["un c{a}ou{/a}", "des cou{a}s{/a}"],
              ],
            },
            {
              type: "highlight",
              label: "Exceptions",
              transLabel: {
                en: "Exceptions",
                ar: "استثناءات",
                fa: "استثناها",
                ti: "ፍሉያት",
                uk: "Винятки",
              },
              items: [
                "un bij{a}ou{/a} → des bij{a}oux{/a}",
                "un caill{a}ou{/a} → des caill{a}oux{/a}",
                "un ch{a}ou{/a} → des ch{a}oux{/a}",
                "un gen{a}ou{/a} → des gen{a}oux{/a}",
                "un hib{a}ou{/a} → des hib{a}oux{/a}",
                "un jouj{a}ou{/a} → des jouj{a}oux{/a}",
                "un p{a}ou{/a} → des p{a}oux{/a}",
              ],
              noBulletItems: [0, 1, 2, 3, 4, 5, 6],
            },
          ],
        },
        {
          label: "Autres",
          content: [
            {
              type: "plain_list",
              items: [
                "Certains noms ont un pluriel irrégulier.",
              ],
              noBulletItems: [0],
              transItems: {
                en: ["Some nouns have an irregular plural."],
                ar: ["لبعض الأسماء جمع غير منتظم."],
                fa: ["برخی اسم‌ها جمع بی‌قاعده دارند."],
                ti: ["ገለ ስማት ዘይስሩዕ ባዙሕ ኣለዎም።"],
                uk: ["Деякі іменники мають неправильну множину."],
              },
            },
            {
              type: "grid",
              headers: ["Singulier", "Pluriel"],
              transHeaders: {
                en: ["Singular", "Plural"],
                ar: ["المفرد", "الجمع"],
                fa: ["مفرد", "جمع"],
                ti: ["ንጽል", "ባዙሕ"],
                uk: ["Однина", "Множина"],
              },
              rows: [
                ["un {a}œil{/a}", "des {a}yeux{/a}"],
                ["un {a}monsieur{/a}", "des {a}messieurs{/a}"],
                ["{a}madame{/a}", "{a}mesdames{/a}"],
                ["{a}mademoiselle{/a}", "{a}mesdemoiselles{/a}"],
              ],
            },
          ],
        },
      ],
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Exercice 1",
      instruction: "Choisissez la forme plurielle correcte.",
      transInstruction: { en: "Choose the correct plural form.", ar: "اختر صيغة الجمع الصحيحة.", fa: "صورت جمع درست را انتخاب کنید.", ti: "እቲ ቅኑዕ ባዙሕ ቅርጺ ምረጽ።", uk: "Оберіть правильну форму множини." },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "une pomme → des ___", choices: ["pommes", "pomme", "pommeses"], correctIdx: 0 },
        { sentence: "un fruit → des ___", choices: ["fruits", "fruit", "fruites"], correctIdx: 0 },
        { sentence: "une banane → des ___", choices: ["bananes", "banane", "bananex"], correctIdx: 0 },
        { sentence: "une tasse → des ___", choices: ["tasses", "tasse", "tassex"], correctIdx: 0 },
        { sentence: "un livre → des ___", choices: ["livres", "livre", "livrex"], correctIdx: 0 },
        { sentence: "une voiture → des ___", choices: ["voitures", "voiture", "voiturex"], correctIdx: 0 },
        { sentence: "un village → des ___", choices: ["villages", "village", "villagex"], correctIdx: 0 },
        { sentence: "le bras → les ___", choices: ["bras", "brases", "braux"], correctIdx: 0 },
        { sentence: "une noix → des ___", choices: ["noix", "noixes", "nois"], correctIdx: 0 },
        { sentence: "un nez → des ___", choices: ["nez", "nezes", "neux"], correctIdx: 0 },
        { sentence: "un animal → des ___", choices: ["animaux", "animals", "animales"], correctIdx: 0 },
        { sentence: "un journal → des ___", choices: ["journaux", "journals", "jornales"], correctIdx: 0 },
        { sentence: "un cheval → des ___", choices: ["chevaux", "chevals", "chevales"], correctIdx: 0 },
        { sentence: "un bal → des ___", choices: ["bals", "baux", "bales"], correctIdx: 0 },
        { sentence: "un carnaval → des ___", choices: ["carnavals", "carnavaux", "carnavales"], correctIdx: 0 },
        { sentence: "un festival → des ___", choices: ["festivals", "festivaux", "festivales"], correctIdx: 0 },
        { sentence: "un récital → des ___", choices: ["récitals", "récitaux", "récitales"], correctIdx: 0 },
        { sentence: "un détail → des ___", choices: ["détails", "détaux", "détailes"], correctIdx: 0 },
        { sentence: "un portail → des ___", choices: ["portails", "portaux", "portailes"], correctIdx: 0 },
        { sentence: "un éventail → des ___", choices: ["éventails", "éventaux", "éventailes"], correctIdx: 0 },
        { sentence: "un travail → des ___", choices: ["travaux", "travails", "travailes"], correctIdx: 0 },
        { sentence: "un vitrail → des ___", choices: ["vitraux", "vitrails", "vitrailes"], correctIdx: 0 },
        { sentence: "un corail → des ___", choices: ["coraux", "corails", "corailes"], correctIdx: 0 },
        { sentence: "un bail → des ___", choices: ["baux", "bails", "bailes"], correctIdx: 0 },
        { sentence: "un bateau → des ___", choices: ["bateaux", "bateaus", "bateaues"], correctIdx: 0 },
        { sentence: "un gâteau → des ___", choices: ["gâteaux", "gâteaus", "gateaux"], correctIdx: 0 },
        { sentence: "un chapeau → des ___", choices: ["chapeaux", "chapeaus", "chapeaues"], correctIdx: 0 },
        { sentence: "un cadeau → des ___", choices: ["cadeaux", "cadeaus", "cadeaues"], correctIdx: 0 },
        { sentence: "un tuyau → des ___", choices: ["tuyaux", "tuyaus", "tuyaues"], correctIdx: 0 },
        { sentence: "un landau → des ___", choices: ["landaus", "landaux", "landaues"], correctIdx: 0 },
        { sentence: "un sarrau → des ___", choices: ["sarraus", "sarraux", "sarraues"], correctIdx: 0 },
        { sentence: "un feu → des ___", choices: ["feux", "feus", "feues"], correctIdx: 0 },
        { sentence: "un jeu → des ___", choices: ["jeux", "jeus", "jeues"], correctIdx: 0 },
        { sentence: "un lieu → des ___", choices: ["lieux", "lieus", "lieues"], correctIdx: 0 },
        { sentence: "un pneu → des ___", choices: ["pneus", "pneux", "pneues"], correctIdx: 0 },
        { sentence: "un bleu → des ___", choices: ["bleus", "bleux", "bleues"], correctIdx: 0 },
        { sentence: "un trou → des ___", choices: ["trous", "troux", "troues"], correctIdx: 0 },
        { sentence: "un clou → des ___", choices: ["clous", "cloux", "cloues"], correctIdx: 0 },
        { sentence: "un cou → des ___", choices: ["cous", "coux", "coues"], correctIdx: 0 },
        { sentence: "un bijou → des ___", choices: ["bijoux", "bijous", "bijoues"], correctIdx: 0 },
        { sentence: "un caillou → des ___", choices: ["cailloux", "caillous", "cailloues"], correctIdx: 0 },
        { sentence: "un chou → des ___", choices: ["choux", "chous", "choues"], correctIdx: 0 },
        { sentence: "un genou → des ___", choices: ["genoux", "genous", "genoues"], correctIdx: 0 },
        { sentence: "un hibou → des ___", choices: ["hiboux", "hibous", "hiboues"], correctIdx: 0 },
        { sentence: "un joujou → des ___", choices: ["joujoux", "joujous", "joujoues"], correctIdx: 0 },
        { sentence: "un pou → des ___", choices: ["poux", "pous", "poues"], correctIdx: 0 },
        { sentence: "un œil → des ___", choices: ["yeux", "œils", "oeils"], correctIdx: 0 },
        { sentence: "un monsieur → des ___", choices: ["messieurs", "monsieurs", "monsieures"], correctIdx: 0 },
        { sentence: "madame → ___", choices: ["mesdames", "madames", "mesdame"], correctIdx: 0 },
        { sentence: "mademoiselle → ___", choices: ["mesdemoiselles", "mademoiselles", "mesdemoiselle"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Écrivez la forme plurielle du nom.",
      transInstruction: { en: "Write the plural form of the noun.", ar: "اكتب صيغة الجمع للاسم.", fa: "صورت جمع اسم را بنویسید.", ti: "እቲ ባዙሕ ቅርጺ ናይ ስም ጽሓፍ።", uk: "Напишіть форму множини іменника." },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "une pomme → des ___", hint: "+ s", answer: "pommes" },
        { sentence: "un fruit → des ___", hint: "+ s", answer: "fruits" },
        { sentence: "une banane → des ___", hint: "+ s", answer: "bananes" },
        { sentence: "une tasse → des ___", hint: "+ s", answer: "tasses" },
        { sentence: "un livre → des ___", hint: "+ s", answer: "livres" },
        { sentence: "une voiture → des ___", hint: "+ s", answer: "voitures" },
        { sentence: "un village → des ___", hint: "+ s", answer: "villages" },
        { sentence: "le bras → les ___", hint: "inchangé", answer: "bras" },
        { sentence: "une noix → des ___", hint: "inchangé", answer: "noix" },
        { sentence: "un nez → des ___", hint: "inchangé", answer: "nez" },
        { sentence: "un animal → des ___", hint: "-al → -aux", answer: "animaux" },
        { sentence: "un journal → des ___", hint: "-al → -aux", answer: "journaux" },
        { sentence: "un cheval → des ___", hint: "-al → -aux", answer: "chevaux" },
        { sentence: "un bal → des ___", hint: "exception + s", answer: "bals" },
        { sentence: "un carnaval → des ___", hint: "exception + s", answer: "carnavals" },
        { sentence: "un festival → des ___", hint: "exception + s", answer: "festivals" },
        { sentence: "un récital → des ___", hint: "exception + s", answer: "récitals" },
        { sentence: "un détail → des ___", hint: "+ s", answer: "détails" },
        { sentence: "un portail → des ___", hint: "+ s", answer: "portails" },
        { sentence: "un éventail → des ___", hint: "+ s", answer: "éventails" },
        { sentence: "un travail → des ___", hint: "-ail → -aux", answer: "travaux" },
        { sentence: "un vitrail → des ___", hint: "-ail → -aux", answer: "vitraux" },
        { sentence: "un corail → des ___", hint: "-ail → -aux", answer: "coraux" },
        { sentence: "un bail → des ___", hint: "-ail → -aux", answer: "baux" },
        { sentence: "un bateau → des ___", hint: "-eau → -eaux", answer: "bateaux" },
        { sentence: "un gâteau → des ___", hint: "-eau → -eaux", answer: "gâteaux" },
        { sentence: "un chapeau → des ___", hint: "-eau → -eaux", answer: "chapeaux" },
        { sentence: "un cadeau → des ___", hint: "-eau → -eaux", answer: "cadeaux" },
        { sentence: "un tuyau → des ___", hint: "-au → -aux", answer: "tuyaux" },
        { sentence: "un landau → des ___", hint: "exception + s", answer: "landaus" },
        { sentence: "un sarrau → des ___", hint: "exception + s", answer: "sarraus" },
        { sentence: "un feu → des ___", hint: "-eu → -eux", answer: "feux" },
        { sentence: "un jeu → des ___", hint: "-eu → -eux", answer: "jeux" },
        { sentence: "un lieu → des ___", hint: "-eu → -eux", answer: "lieux" },
        { sentence: "un pneu → des ___", hint: "exception + s", answer: "pneus" },
        { sentence: "un bleu → des ___", hint: "exception + s", answer: "bleus" },
        { sentence: "un trou → des ___", hint: "+ s", answer: "trous" },
        { sentence: "un clou → des ___", hint: "+ s", answer: "clous" },
        { sentence: "un cou → des ___", hint: "+ s", answer: "cous" },
        { sentence: "un bijou → des ___", hint: "+ x", answer: "bijoux" },
        { sentence: "un caillou → des ___", hint: "+ x", answer: "cailloux" },
        { sentence: "un chou → des ___", hint: "+ x", answer: "choux" },
        { sentence: "un genou → des ___", hint: "+ x", answer: "genoux" },
        { sentence: "un hibou → des ___", hint: "+ x", answer: "hiboux" },
        { sentence: "un joujou → des ___", hint: "+ x", answer: "joujoux" },
        { sentence: "un pou → des ___", hint: "+ x", answer: "poux" },
        { sentence: "un œil → des ___", hint: "irrégulier", answer: "yeux" },
        { sentence: "un monsieur → des ___", hint: "irrégulier", answer: "messieurs" },
        { sentence: "madame → ___", hint: "irrégulier", answer: "mesdames" },
        { sentence: "mademoiselle → ___", hint: "irrégulier", answer: "mesdemoiselles" },
      ],
    },
    {
      type: "fill",
      title: "Exercice 3",
      instruction: "Réécrivez les phrases au pluriel.",
      transInstruction: { en: "Rewrite the sentences in the plural.", ar: "أعد كتابة الجمل في صيغة الجمع.", fa: "جمله‌ها را به صورت جمع بازنویسی کنید.", ti: "እተን ሓሳባት ብባዙሕ ደጊምካ ጽሓፍ።", uk: "Перепишіть речення у множині." },
      items: [],
      poolSize: 5,
      inputWidth: "w-[32rem]",
      pool: [
        { sentence: "Une pomme tombe de l'arbre.\n___", hint: "pluriel", answer: "Des pommes tombent des arbres." },
        { sentence: "Un fruit est sur la table.\n___", hint: "pluriel", answer: "Des fruits sont sur les tables." },
        { sentence: "Une banane coûte un euro.\n___", hint: "pluriel", answer: "Des bananes coûtent des euros." },
        { sentence: "Une tasse est dans le placard.\n___", hint: "pluriel", answer: "Des tasses sont dans les placards." },
        { sentence: "Un livre est sur la table.\n___", hint: "pluriel", answer: "Des livres sont sur les tables." },
        { sentence: "Une voiture est dans la rue.\n___", hint: "pluriel", answer: "Des voitures sont dans les rues." },
        { sentence: "Un village est près de la mer.\n___", hint: "pluriel", answer: "Des villages sont près des mers." },
        { sentence: "Le bras fait mal.\n___", hint: "pluriel", answer: "Les bras font mal." },
        { sentence: "Une noix est dans le panier.\n___", hint: "pluriel", answer: "Des noix sont dans les paniers." },
        { sentence: "Un nez saigne.\n___", hint: "pluriel", answer: "Des nez saignent." },
        { sentence: "Un animal vit dans la forêt.\n___", hint: "pluriel", answer: "Des animaux vivent dans les forêts." },
        { sentence: "Un journal est sur la table.\n___", hint: "pluriel", answer: "Des journaux sont sur les tables." },
        { sentence: "Un cheval court dans le pré.\n___", hint: "pluriel", answer: "Des chevaux courent dans les prés." },
        { sentence: "Un bal a lieu samedi.\n___", hint: "pluriel", answer: "Des bals ont lieu samedi." },
        { sentence: "Un carnaval attire les touristes.\n___", hint: "pluriel", answer: "Des carnavals attirent les touristes." },
        { sentence: "Un festival commence demain.\n___", hint: "pluriel", answer: "Des festivals commencent demain." },
        { sentence: "Un récital a lieu ce soir.\n___", hint: "pluriel", answer: "Des récitals ont lieu ce soir." },
        { sentence: "Un détail est important.\n___", hint: "pluriel", answer: "Des détails sont importants." },
        { sentence: "Un portail est ouvert.\n___", hint: "pluriel", answer: "Des portails sont ouverts." },
        { sentence: "Un éventail est sur la table.\n___", hint: "pluriel", answer: "Des éventails sont sur les tables." },
        { sentence: "Un travail est difficile.\n___", hint: "pluriel", answer: "Des travaux sont difficiles." },
        { sentence: "Un vitrail est magnifique.\n___", hint: "pluriel", answer: "Des vitraux sont magnifiques." },
        { sentence: "Un corail pousse dans la mer.\n___", hint: "pluriel", answer: "Des coraux poussent dans les mers." },
        { sentence: "Un bail dure un an.\n___", hint: "pluriel", answer: "Des baux durent des ans." },
        { sentence: "Un bateau arrive au port.\n___", hint: "pluriel", answer: "Des bateaux arrivent aux ports." },
        { sentence: "Un gâteau est sur la table.\n___", hint: "pluriel", answer: "Des gâteaux sont sur les tables." },
        { sentence: "Un chapeau est sur la chaise.\n___", hint: "pluriel", answer: "Des chapeaux sont sur les chaises." },
        { sentence: "Un cadeau est sous le sapin.\n___", hint: "pluriel", answer: "Des cadeaux sont sous les sapins." },
        { sentence: "Un tuyau fuit dans la cuisine.\n___", hint: "pluriel", answer: "Des tuyaux fuient dans les cuisines." },
        { sentence: "Un landau est dans le jardin.\n___", hint: "pluriel", answer: "Des landaus sont dans les jardins." },
        { sentence: "Un sarrau est propre.\n___", hint: "pluriel", answer: "Des sarraus sont propres." },
        { sentence: "Un feu brûle dans la cheminée.\n___", hint: "pluriel", answer: "Des feux brûlent dans les cheminées." },
        { sentence: "Un jeu est amusant.\n___", hint: "pluriel", answer: "Des jeux sont amusants." },
        { sentence: "Un lieu est fermé.\n___", hint: "pluriel", answer: "Des lieux sont fermés." },
        { sentence: "Un pneu est crevé.\n___", hint: "pluriel", answer: "Des pneus sont crevés." },
        { sentence: "Un bleu orne le tableau.\n___", hint: "pluriel", answer: "Des bleus ornent les tableaux." },
        { sentence: "Un trou est dans le mur.\n___", hint: "pluriel", answer: "Des trous sont dans les murs." },
        { sentence: "Un clou est dans le mur.\n___", hint: "pluriel", answer: "Des clous sont dans les murs." },
        { sentence: "Un cou est long.\n___", hint: "pluriel", answer: "Des cous sont longs." },
        { sentence: "Un bijou brille au soleil.\n___", hint: "pluriel", answer: "Des bijoux brillent aux soleils." },
        { sentence: "Un caillou est sur le chemin.\n___", hint: "pluriel", answer: "Des cailloux sont sur les chemins." },
        { sentence: "Un chou pousse dans le jardin.\n___", hint: "pluriel", answer: "Des choux poussent dans les jardins." },
        { sentence: "Un genou est blessé.\n___", hint: "pluriel", answer: "Des genoux sont blessés." },
        { sentence: "Un hibou chante la nuit.\n___", hint: "pluriel", answer: "Des hiboux chantent les nuits." },
        { sentence: "Un joujou est cassé.\n___", hint: "pluriel", answer: "Des joujoux sont cassés." },
        { sentence: "Un pou est très petit.\n___", hint: "pluriel", answer: "Des poux sont très petits." },
        { sentence: "Un œil est fermé.\n___", hint: "pluriel", answer: "Des yeux sont fermés." },
        { sentence: "Un monsieur attend à la porte.\n___", hint: "pluriel", answer: "Des messieurs attendent aux portes." },
        { sentence: "Madame arrive demain.\n___", hint: "pluriel", answer: "Mesdames arrivent demain." },
        { sentence: "Mademoiselle parle français.\n___", hint: "pluriel", answer: "Mesdemoiselles parlent français." },
      ],
    },
  ],
};
