import type { GrammarLesson } from "../../grammar-data";

export const A1_GR_L10: GrammarLesson = {
  slug: "a1-gr-l10",
  code: "RI.4",
  level: "A1",
  title: "Les mots interrogatifs",
  theory: [
    { type: "heading", text: "Les mots interrogatifs", trans: { en: "Question words", ar: "أدوات الاستفهام", fa: "کلمات پرسشی", ti: "ናይ ሕቶ ቃላት", uk: "Питальні слова" } },
    {
      type: "plain_list",
      items: [
        "Les mots interrogatifs permettent de poser des questions précises.",
        "Ils se placent en début de question (ou à la fin à l'oral informel).",
      ],
      transItems: {
        en: ["Question words let you ask precise questions.", "They are placed at the start of the question (or at the end in informal speech)."],
        ar: ["أدوات الاستفهام تتيح لك طرح أسئلة دقيقة.", "توضع في بداية السؤال (أو في نهايته في الكلام غير الرسمي)."],
        fa: ["کلمات پرسشی به شما اجازه می‌دهند سؤالات دقیق بپرسید.", "آن‌ها در ابتدای سؤال قرار می‌گیرند (یا در پایان در گفتار غیررسمی)."],
        ti: ["ናይ ሕቶ ቃላት ቅኑዓት ሕቶታት ንምሕታት የኽእሉ።", "ኣብ መጀመርታ ሕቶ ይቕመጡ (ወይ ኣብ መወዳእታ ኣብ ዘይወግዓዊ ዘረባ)።"],
        uk: ["Питальні слова дозволяють ставити точні запитання.", "Вони ставляться на початку запитання (або в кінці в неформальному мовленні)."],
      },
    },
    {
      type: "grid",
      headers: ["Mot", "Sens", "Exemple"],
      boldFirstCol: true,
      transHeaders: {
        en: ["Word", "Meaning", "Example"],
        ar: ["الكلمة", "المعنى", "مثال"],
        fa: ["کلمه", "معنی", "مثال"],
        ti: ["ቃል", "ትርጉም", "ኣብነት"],
        uk: ["Слово", "Значення", "Приклад"],
      },
      transRows: {
        en: [["{a}Où ?{/a}", "place", "Où est-ce que tu habites ? (Where do you live?)"], ["{a}Quand ?{/a}", "time", "Quand est-ce qu'il arrive ? (When does he arrive?)"], ["{a}Qui ?{/a}", "person", "Qui est-ce que tu appelles ? (Who are you calling?)"], ["{a}Qu'est-ce que ?{/a}", "thing", "Qu'est-ce que tu manges ? (What are you eating?)"], ["{a}Comment ?{/a}", "manner / state", "Comment tu t'appelles ? (What is your name?)"], ["{a}Pourquoi ?{/a}", "reason", "Pourquoi tu étudies le français ? (Why do you study French?)"], ["{a}Combien ?{/a}", "quantity", "Combien d'enfants vous avez ? (How many children do you have?)"], ["{a}Quel / Quelle ?{/a}", "choice among several", "Quel bus prends-tu ? (Which bus do you take?)"]],
        ar: [["{a}Où ?{/a}", "المكان", "Où est-ce que tu habites ؟ (أين تسكن؟)"], ["{a}Quand ?{/a}", "الزمان", "Quand est-ce qu'il arrive ؟ (متى يصل؟)"], ["{a}Qui ?{/a}", "الشخص", "Qui est-ce que tu appelles ؟ (من تتصل به؟)"], ["{a}Qu'est-ce que ?{/a}", "الشيء", "Qu'est-ce que tu manges ؟ (ماذا تأكل؟)"], ["{a}Comment ?{/a}", "الطريقة / الحالة", "Comment tu t'appelles ؟ (ما اسمك؟)"], ["{a}Pourquoi ?{/a}", "السبب", "Pourquoi tu étudies le français ؟ (لماذا تدرس الفرنسية؟)"], ["{a}Combien ?{/a}", "الكمية", "Combien d'enfants vous avez ؟ (كم طفلاً لديك؟)"], ["{a}Quel / Quelle ?{/a}", "الاختيار من بين عدة", "Quel bus prends-tu ؟ (أي حافلة تأخذ؟)"]],
        fa: [["{a}Où ?{/a}", "مکان", "Où est-ce que tu habites ? (کجا زندگی می‌کنی؟)"], ["{a}Quand ?{/a}", "زمان", "Quand est-ce qu'il arrive ? (کِی می‌رسد؟)"], ["{a}Qui ?{/a}", "شخص", "Qui est-ce que tu appelles ? (به چه کسی زنگ می‌زنی؟)"], ["{a}Qu'est-ce que ?{/a}", "چیز", "Qu'est-ce que tu manges ? (چه می‌خوری؟)"], ["{a}Comment ?{/a}", "شیوه / حالت", "Comment tu t'appelles ? (نامت چیست؟)"], ["{a}Pourquoi ?{/a}", "دلیل", "Pourquoi tu étudies le français ? (چرا فرانسوی می‌خوانی؟)"], ["{a}Combien ?{/a}", "مقدار", "Combien d'enfants vous avez ? (چند فرزند دارید؟)"], ["{a}Quel / Quelle ?{/a}", "انتخاب از میان چند", "Quel bus prends-tu ? (کدام اتوبوس را می‌گیری؟)"]],
        ti: [["{a}Où ?{/a}", "ቦታ", "Où est-ce que tu habites ? (ኣበይ ትቕመጥ?)"], ["{a}Quand ?{/a}", "ግዜ", "Quand est-ce qu'il arrive ? (መዓስ ይመጽእ?)"], ["{a}Qui ?{/a}", "ሰብ", "Qui est-ce que tu appelles ? (ንመን ትድውል?)"], ["{a}Qu'est-ce que ?{/a}", "ነገር", "Qu'est-ce que tu manges ? (እንታይ ትበልዕ?)"], ["{a}Comment ?{/a}", "ኣገባብ / ኩነታት", "Comment tu t'appelles ? (መን ትብሃል?)"], ["{a}Pourquoi ?{/a}", "ምኽንያት", "Pourquoi tu étudies le français ? (ስለምንታይ ፈረንሳይ ትመሃር?)"], ["{a}Combien ?{/a}", "መጠን", "Combien d'enfants vous avez ? (ክንደይ ቆልዑ ኣለዉኻ?)"], ["{a}Quel / Quelle ?{/a}", "ካብ ብዙሕ ምርጫ", "Quel bus prends-tu ? (ኣየናይ ኣውቶቡስ ትወስድ?)"]],
        uk: [["{a}Où ?{/a}", "місце", "Où est-ce que tu habites ? (Де ти живеш?)"], ["{a}Quand ?{/a}", "час", "Quand est-ce qu'il arrive ? (Коли він приїжджає?)"], ["{a}Qui ?{/a}", "особа", "Qui est-ce que tu appelles ? (Кому ти телефонуєш?)"], ["{a}Qu'est-ce que ?{/a}", "річ", "Qu'est-ce que tu manges ? (Що ти їси?)"], ["{a}Comment ?{/a}", "спосіб / стан", "Comment tu t'appelles ? (Як тебе звати?)"], ["{a}Pourquoi ?{/a}", "причина", "Pourquoi tu étudies le français ? (Чому ти вивчаєш французьку?)"], ["{a}Combien ?{/a}", "кількість", "Combien d'enfants vous avez ? (Скільки у вас дітей?)"], ["{a}Quel / Quelle ?{/a}", "вибір з кількох", "Quel bus prends-tu ? (Який автобус ти береш?)"]],
      },
      rows: [
        ["{a}Où ?{/a}", "lieu", "Où est-ce que tu habites ?"],
        ["{a}Quand ?{/a}", "temps", "Quand est-ce qu'il arrive ?"],
        ["{a}Qui ?{/a}", "personne", "Qui est-ce que tu appelles ?"],
        ["{a}Qu'est-ce que ?{/a}", "chose", "Qu'est-ce que tu manges ?"],
        ["{a}Comment ?{/a}", "manière / état", "Comment tu t'appelles ?"],
        ["{a}Pourquoi ?{/a}", "raison", "Pourquoi tu étudies le français ?"],
        ["{a}Combien ?{/a}", "quantité", "Combien d'enfants vous avez ?"],
        ["{a}Quel / Quelle ?{/a}", "choix parmi plusieurs", "Quel bus prends-tu ?"],
      ],
    },
    { type: "heading", text: "Deux façons de construire la question", sub: true, trans: { en: "Two ways to build the question", ar: "طريقتان لبناء السؤال", fa: "دو روش برای ساختن سؤال", ti: "ሕቶ ንምስራሕ ክልተ መንገድታት", uk: "Два способи побудувати запитання" } },
    {
      type: "highlight",
      label: "Registre neutre",
      items: [
        "Mot interrogatif + {a}est-ce que{/a} + sujet + verbe ?",
        "Où est-ce que tu habites ?",
        "Quand est-ce qu'il arrive ?",
        "Comment est-ce que vous vous appelez ?",
      ],
      noBulletItems: [0],
      transLabel: { en: "Neutral register", ar: "المستوى المحايد", fa: "سطح خنثی", ti: "ገለልተኛ ደረጃ", uk: "Нейтральний регістр" },
      transItems: {
        en: ["Question word + {a}est-ce que{/a} + subject + verb?", "Où est-ce que tu habites ? (Where do you live?)", "Quand est-ce qu'il arrive ? (When does he arrive?)", "Comment est-ce que vous vous appelez ? (What is your name?)"],
        ar: ["أداة الاستفهام + {a}est-ce que{/a} + الفاعل + الفعل؟", "Où est-ce que tu habites ؟ (أين تسكن؟)", "Quand est-ce qu'il arrive ؟ (متى يصل؟)", "Comment est-ce que vous vous appelez ؟ (ما اسمك؟)"],
        fa: ["کلمه‌ی پرسشی + {a}est-ce que{/a} + فاعل + فعل؟", "Où est-ce que tu habites ? (کجا زندگی می‌کنی؟)", "Quand est-ce qu'il arrive ? (کِی می‌رسد؟)", "Comment est-ce que vous vous appelez ? (نامتان چیست؟)"],
        ti: ["ናይ ሕቶ ቃል + {a}est-ce que{/a} + ርእሲ + ግሲ?", "Où est-ce que tu habites ? (ኣበይ ትቕመጥ?)", "Quand est-ce qu'il arrive ? (መዓስ ይመጽእ?)", "Comment est-ce que vous vous appelez ? (መን ትብሃሉ?)"],
        uk: ["Питальне слово + {a}est-ce que{/a} + підмет + дієслово?", "Où est-ce que tu habites ? (Де ти живеш?)", "Quand est-ce qu'il arrive ? (Коли він приїжджає?)", "Comment est-ce que vous vous appelez ? (Як вас звати?)"],
      },
    },
    {
      type: "highlight",
      label: "Registre informel (oral)",
      items: [
        "Sujet + verbe + mot interrogatif ?",
        "Tu habites où ?",
        "Il arrive quand ?",
        "Tu t'appelles comment ?",
      ],
      noBulletItems: [0],
      transLabel: { en: "Informal register (spoken)", ar: "المستوى غير الرسمي (المحكي)", fa: "سطح غیررسمی (گفتاری)", ti: "ዘይወግዓዊ ደረጃ (ኣፋዊ)", uk: "Неформальний регістр (усний)" },
      transItems: {
        en: ["Subject + verb + question word?", "Tu habites où ? (Where do you live?)", "Il arrive quand ? (When does he arrive?)", "Tu t'appelles comment ? (What is your name?)"],
        ar: ["الفاعل + الفعل + أداة الاستفهام؟", "Tu habites où ؟ (أين تسكن؟)", "Il arrive quand ؟ (متى يصل؟)", "Tu t'appelles comment ؟ (ما اسمك؟)"],
        fa: ["فاعل + فعل + کلمه‌ی پرسشی؟", "Tu habites où ? (کجا زندگی می‌کنی؟)", "Il arrive quand ? (کِی می‌رسد؟)", "Tu t'appelles comment ? (نامت چیست؟)"],
        ti: ["ርእሲ + ግሲ + ናይ ሕቶ ቃል?", "Tu habites où ? (ኣበይ ትቕመጥ?)", "Il arrive quand ? (መዓስ ይመጽእ?)", "Tu t'appelles comment ? (መን ትብሃል?)"],
        uk: ["Підмет + дієслово + питальне слово?", "Tu habites où ? (Де ти живеш?)", "Il arrive quand ? (Коли він приїжджає?)", "Tu t'appelles comment ? (Як тебе звати?)"],
      },
    },
    {
      type: "highlight",
      label: "Quel / Quelle — accord",
      items: [
        "{a}Quel{/a} + nom masculin singulier : Quel jour ?",
        "{a}Quelle{/a} + nom féminin singulier : Quelle heure ?",
        "{a}Quels{/a} + nom masculin pluriel : Quels films ?",
        "{a}Quelles{/a} + nom féminin pluriel : Quelles langues ?",
      ],
      transLabel: { en: "Quel / Quelle — agreement", ar: "Quel / Quelle — التطابق", fa: "Quel / Quelle — مطابقت", ti: "Quel / Quelle — ምስምማዕ", uk: "Quel / Quelle — узгодження" },
      transItems: {
        en: ["{a}Quel{/a} + masculine singular noun: Quel jour ? (Which day?)", "{a}Quelle{/a} + feminine singular noun: Quelle heure ? (What time?)", "{a}Quels{/a} + masculine plural noun: Quels films ? (Which films?)", "{a}Quelles{/a} + feminine plural noun: Quelles langues ? (Which languages?)"],
        ar: ["{a}Quel{/a} + اسم مذكر مفرد: Quel jour ؟ (أي يوم؟)", "{a}Quelle{/a} + اسم مؤنث مفرد: Quelle heure ؟ (أي ساعة؟)", "{a}Quels{/a} + اسم مذكر جمع: Quels films ؟ (أي أفلام؟)", "{a}Quelles{/a} + اسم مؤنث جمع: Quelles langues ؟ (أي لغات؟)"],
        fa: ["{a}Quel{/a} + اسم مذکر مفرد: Quel jour ? (کدام روز؟)", "{a}Quelle{/a} + اسم مؤنث مفرد: Quelle heure ? (چه ساعتی؟)", "{a}Quels{/a} + اسم مذکر جمع: Quels films ? (کدام فیلم‌ها؟)", "{a}Quelles{/a} + اسم مؤنث جمع: Quelles langues ? (کدام زبان‌ها؟)"],
        ti: ["{a}Quel{/a} + ተባዕታይ ነጠላ ስም፦ Quel jour ? (ኣየናይ መዓልቲ?)", "{a}Quelle{/a} + ኣንስታይ ነጠላ ስም፦ Quelle heure ? (ክንደይ ሰዓት?)", "{a}Quels{/a} + ተባዕታይ ብዙሕ ስም፦ Quels films ? (ኣየኖት ፊልምታት?)", "{a}Quelles{/a} + ኣንስታይ ብዙሕ ስም፦ Quelles langues ? (ኣየኖት ቋንቋታት?)"],
        uk: ["{a}Quel{/a} + іменник чоловічого роду однини: Quel jour ? (Який день?)", "{a}Quelle{/a} + іменник жіночого роду однини: Quelle heure ? (Котра година?)", "{a}Quels{/a} + іменник чоловічого роду множини: Quels films ? (Які фільми?)", "{a}Quelles{/a} + іменник жіночого роду множини: Quelles langues ? (Які мови?)"],
      },
    },
  ],
  exercises: [
    {
      type: "fill",
      title: "Exercice 1",
      instruction: "Complétez avec le bon mot interrogatif : où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle.",
      transInstruction: { en: "Complete with the correct question word: où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle.", ar: "أكمل بأداة الاستفهام الصحيحة: où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle.", fa: "با کلمه‌ی پرسشی درست کامل کنید: où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle.", ti: "ብቅኑዕ ናይ ሕቶ ቃል ምላእ፦ où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle.", uk: "Доповніть правильним питальним словом: où, quand, qui, comment, pourquoi, combien, qu'est-ce que, quel/quelle." },
      items: [],
      poolSize: 5,
      pool: [
        // A1 — questions simples, contexte très direct
        { sentence: "___ vous habitez ?", hint: "lieu", answer: "Où" },
        { sentence: "___ tu t'appelles ?", hint: "identité", answer: "Comment" },
        { sentence: "___ il arrive ?", hint: "moment", answer: "Quand" },
        { sentence: "___ vient avec nous ?", hint: "personne", answer: "Qui" },
        { sentence: "___ ça coûte ?", hint: "quantité/prix", answer: "Combien" },
        { sentence: "___ tu étudies le français ?", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ tu fais ?", hint: "action/chose", answer: "Qu'est-ce que" },
        { sentence: "___ est ton livre ?", hint: "lieu", answer: "Où" },
        { sentence: "___ bus prends-tu ?", hint: "choix", answer: "Quel" },
        { sentence: "___ heure est-il ?", hint: "choix féminin", answer: "Quelle" },
        // A2 — contexte quotidien, est-ce que présent
        { sentence: "___ est-ce que vous travaillez le week-end ?", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ de personnes habitent dans cet appartement ?", hint: "quantité", answer: "Combien" },
        { sentence: "___ est-ce que tu rentres à la maison ?", hint: "moment", answer: "Quand" },
        { sentence: "___ langue parlez-vous à la maison ?", hint: "choix féminin", answer: "Quelle" },
        { sentence: "___ est-ce qu'elle fait comme travail ?", hint: "action/chose", answer: "Qu'est-ce qu'" },
        { sentence: "___ s'occupait des enfants pendant ton absence ?", hint: "personne", answer: "Qui" },
        { sentence: "___ est-ce que tu te sens à Genève ?", hint: "manière/état", answer: "Comment" },
        { sentence: "___ est la pharmacie la plus proche ?", hint: "lieu", answer: "Où" },
        { sentence: "___ sont tes cours de français ?", hint: "choix pluriel", answer: "Quels" },
        { sentence: "___ tu n'as pas dormi cette nuit ?", hint: "raison", answer: "Pourquoi" },
        // B1 — thèmes d'intégration, vocabulaire précis
        { sentence: "___ vous a recommandé cette formation linguistique ?", hint: "personne", answer: "Qui" },
        { sentence: "___ de langues parlez-vous couramment ?", hint: "quantité", answer: "Combien" },
        { sentence: "___ est-ce que vous avez entendu parler de ce programme ?", hint: "manière/état", answer: "Comment" },
        { sentence: "___ emploi recherchez-vous exactement ?", hint: "choix", answer: "Quel" },
        { sentence: "___ est la date limite pour déposer le dossier ?", hint: "choix féminin", answer: "Quelle" },
        { sentence: "___ est-ce que vous souhaitez faire à long terme ?", hint: "action/chose", answer: "Qu'est-ce que" },
        { sentence: "___ est-ce que vous préférez vivre dans ce quartier ?", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ est-ce que vos enfants vont à l'école ?", hint: "lieu", answer: "Où" },
        { sentence: "___ vous êtes arrivé(e) en Suisse ?", hint: "moment", answer: "Quand" },
        { sentence: "___ documents faut-il fournir pour ce dossier ?", hint: "choix pluriel", answer: "Quels" },
      ],
    },
    {
      type: "qcm",
      title: "Exercice 2",
      instruction: "Choisissez le bon mot interrogatif.",
      transInstruction: { en: "Choose the correct question word.", ar: "اختر أداة الاستفهام الصحيحة.", fa: "کلمه‌ی پرسشی درست را انتخاب کنید.", ti: "ቅኑዕ ናይ ሕቶ ቃል ምረጽ.", uk: "Виберіть правильне питальне слово." },
      items: [],
      poolSize: 5,
      pool: [
        // A1
        { sentence: "___ tu habites ? — À Lyon.", choices: ["Où", "Quand", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ ça coûte ? — 20 euros.", choices: ["Combien", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ tu t'appelles ? — Marie.", choices: ["Comment", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ est-ce qu'il arrive ? — Demain matin.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ vient avec nous ? — Mon frère.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ tu fais ? — Je lis un livre.", choices: ["Qu'est-ce que", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ bus prends-tu ? — Le numéro 5.", choices: ["Quel", "Qui", "Combien", "Quand"], correctIdx: 0 },
        { sentence: "___ heure est-il ? — Il est 14h.", choices: ["Quelle", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ est la gare ? — À droite.", choices: ["Où", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ vous parlez ? — Je parle doucement.", choices: ["Comment", "Où", "Qui", "Combien"], correctIdx: 0 },
        // A2
        { sentence: "___ de personnes habitent ici ? — Quatre.", choices: ["Combien", "Qui", "Où", "Quel"], correctIdx: 0 },
        { sentence: "___ tu ne travailles pas ? — Parce que je suis malade.", choices: ["Pourquoi", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ est-ce que tu rentres ? — À 18h.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ langue parles-tu à la maison ? — L'arabe.", choices: ["Quelle", "Qui", "Combien", "Où"], correctIdx: 0 },
        { sentence: "___ est-ce qu'il fait comme sport ? — Il joue au foot.", choices: ["Qu'est-ce qu'", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ s'occupait des enfants ? — La grand-mère.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ est la pharmacie ? — Juste là.", choices: ["Où", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ est-ce que vous vous sentez ? — Très bien.", choices: ["Comment", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ sont tes cours ? — Le lundi et le mercredi.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ vous préférez, le matin ou le soir ?", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        // B1
        { sentence: "___ vous a orienté vers cette formation ? — Mon assistante sociale.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ de langues parlez-vous ? — Trois.", choices: ["Combien", "Qui", "Où", "Comment"], correctIdx: 0 },
        { sentence: "___ est-ce que vous avez entendu parler de ce programme ? — Par un ami.", choices: ["Comment", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ emploi recherchez-vous ? — Un poste d'assistant.", choices: ["Quel", "Qui", "Où", "Quand"], correctIdx: 0 },
        { sentence: "___ est la date limite ? — C'est le 30 juin.", choices: ["Quelle", "Qui", "Où", "Comment"], correctIdx: 0 },
        { sentence: "___ vous souhaitez faire après cette formation ? — Trouver un emploi.", choices: ["Qu'est-ce que", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ vous préférez habiter ici ? — Pour mes enfants.", choices: ["Pourquoi", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ est votre ville de naissance ? — Kaboul.", choices: ["Quelle", "Qui", "Où", "Comment"], correctIdx: 0 },
        { sentence: "___ êtes-vous arrivé(e) en Suisse ? — En 2022.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ documents avez-vous besoin ? — Un permis et une pièce d'identité.", choices: ["Quels", "Qui", "Combien", "Comment"], correctIdx: 0 },
      ],
    },
  ],

  evalExercises: [
    {
      type: "fill",
      title: "Évaluation — Question 1",
      instruction: "Complétez avec le bon mot interrogatif.",
      transInstruction: { en: "Complete with the correct question word.", ar: "أكمل بأداة الاستفهام الصحيحة.", fa: "با کلمه‌ی پرسشی درست کامل کنید.", ti: "ብቅኑዕ ናይ ሕቶ ቃል ምላእ.", uk: "Доповніть правильним питальним словом." },
      items: [],
      poolSize: 5,
      pool: [
        // A1
        { sentence: "___ tu habites ?", hint: "lieu", answer: "Où" },
        { sentence: "___ tu t'appelles ?", hint: "identité", answer: "Comment" },
        { sentence: "___ est-ce que tu travailles ?", hint: "moment", answer: "Quand" },
        { sentence: "___ vient avec nous ?", hint: "personne", answer: "Qui" },
        { sentence: "___ ça coûte ?", hint: "quantité/prix", answer: "Combien" },
        { sentence: "___ tu ne manges pas ?", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ tu fais ce soir ?", hint: "action/chose", answer: "Qu'est-ce que" },
        { sentence: "___ parle français ici ?", hint: "personne", answer: "Qui" },
        { sentence: "___ vous arrivez ?", hint: "moment", answer: "Quand" },
        { sentence: "___ vous allez ? À Paris.", hint: "lieu", answer: "Où" },
        // A2
        { sentence: "___ est-ce que vous cherchez comme logement ?", hint: "action/chose", answer: "Qu'est-ce que" },
        { sentence: "___ est votre date de naissance ?", hint: "choix féminin", answer: "Quelle" },
        { sentence: "___ de frères et sœurs avez-vous ?", hint: "quantité", answer: "Combien" },
        { sentence: "___ est-ce que vous ne voulez pas venir ? — Je suis occupé.", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ s'appelle votre médecin traitant ?", hint: "personne", answer: "Comment" },
        { sentence: "___ vous êtes-vous installé(e) ici ?", hint: "moment", answer: "Quand" },
        { sentence: "___ est le bureau de l'aide sociale ?", hint: "lieu", answer: "Où" },
        { sentence: "___ enfants avez-vous ?", hint: "quantité", answer: "Combien" },
        { sentence: "___ cours suivez-vous en ce moment ?", hint: "choix pluriel", answer: "Quels" },
        { sentence: "___ préférez-vous — le matin ou l'après-midi ?", hint: "choix féminin", answer: "Quelle" },
        // B1
        { sentence: "___ vous a aidé à remplir le formulaire ?", hint: "personne", answer: "Qui" },
        { sentence: "___ est-ce que vous comptez rester dans cette région ?", hint: "durée/moment", answer: "Combien de temps" },
        { sentence: "___ est-ce que vous souhaiteriez améliorer en priorité ?", hint: "action/chose", answer: "Qu'est-ce que" },
        { sentence: "___ est-ce que vous avez rencontré des difficultés au début ?", hint: "raison", answer: "Pourquoi" },
        { sentence: "___ formation vous intéresse le plus pour l'avenir ?", hint: "choix féminin", answer: "Quelle" },
        { sentence: "___ est-ce que vos enfants ont commencé l'école ici ?", hint: "moment", answer: "Quand" },
        { sentence: "___ autorité délivre le permis de séjour dans ce canton ?", hint: "choix féminin", answer: "Quelle" },
        { sentence: "___ documents justificatifs faut-il fournir pour ce dossier ?", hint: "choix pluriel", answer: "Quels" },
        { sentence: "___ avez-vous contacté pour obtenir ce renseignement ?", hint: "personne", answer: "Qui" },
        { sentence: "___ est votre niveau de français actuellement ?", hint: "choix", answer: "Quel" },
      ],
    },
    {
      type: "qcm",
      title: "Évaluation — Question 2",
      instruction: "Choisissez le bon mot interrogatif.",
      transInstruction: { en: "Choose the correct question word.", ar: "اختر أداة الاستفهام الصحيحة.", fa: "کلمه‌ی پرسشی درست را انتخاب کنید.", ti: "ቅኑዕ ናይ ሕቶ ቃል ምረጽ.", uk: "Виберіть правильне питальне слово." },
      items: [],
      poolSize: 5,
      pool: [
        // A1
        { sentence: "___ tu habites ? — À Lyon.", choices: ["Où", "Quand", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ ça coûte ? — 20 euros.", choices: ["Combien", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ tu ne viens pas ? — Je suis malade.", choices: ["Pourquoi", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ est-ce que tu fais ? — Je lis.", choices: ["Qu'est-ce que", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ arrive demain ? — Mon frère.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ tu t'appelles ? — Marie.", choices: ["Comment", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ commence le cours ? — À 9h.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ tu vas ? — Je vais bien.", choices: ["Comment", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ est-ce que tu viens ? — Du Congo.", choices: ["D'où", "Quand", "Qui", "Comment"], correctIdx: 0 },
        { sentence: "___ de frères as-tu ? — Deux.", choices: ["Combien", "Qui", "Où", "Comment"], correctIdx: 0 },
        // A2
        { sentence: "___ langues parles-tu ? — Trois langues.", choices: ["Combien de", "Qui", "Où", "Quelle"], correctIdx: 0 },
        { sentence: "___ est votre adresse ? — 10 rue du Lac.", choices: ["Quelle", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ est-ce que vous préférez manger ? — Des pâtes.", choices: ["Qu'est-ce que", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ est-ce qu'il est parti ? — Parce qu'il était fatigué.", choices: ["Pourquoi", "Où", "Quand", "Qui"], correctIdx: 0 },
        { sentence: "___ s'occupe de vos enfants le soir ? — Ma sœur.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ cours avez-vous cette semaine ? — Grammaire et vocabulaire.", choices: ["Quels", "Qui", "Combien", "Quand"], correctIdx: 0 },
        { sentence: "___ est-ce que vous travaillez ? — À l'hôpital.", choices: ["Où", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ vous êtes-vous rencontrés ? — À Genève.", choices: ["Où", "Qui", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ vous avez besoin de ce document ? — Pour le renouvellement.", choices: ["Pourquoi", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ est disponible le médecin ? — Le mercredi.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
        // B1
        { sentence: "___ vous a conseillé cette démarche ? — Mon assistante sociale.", choices: ["Qui", "Où", "Quand", "Comment"], correctIdx: 0 },
        { sentence: "___ de temps faut-il pour obtenir le permis ? — Environ trois mois.", choices: ["Combien", "Qui", "Où", "Comment"], correctIdx: 0 },
        { sentence: "___ est-ce que vous comptez faire après la formation ? — Chercher un emploi.", choices: ["Qu'est-ce que", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ est-ce que vous avez choisi ce quartier ? — Pour les écoles.", choices: ["Pourquoi", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ formation correspond le mieux à votre profil ?", choices: ["Quelle", "Qui", "Où", "Comment"], correctIdx: 0 },
        { sentence: "___ avez-vous soumis votre dossier ? — En ligne.", choices: ["Comment", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ autorité faut-il contacter pour ce problème ?", choices: ["Quelle", "Qui", "Où", "Combien"], correctIdx: 0 },
        { sentence: "___ est-ce que vos compétences ont été reconnues ici ?", choices: ["Comment", "Où", "Qui", "Quand"], correctIdx: 0 },
        { sentence: "___ services sociaux sont disponibles dans ce canton ?", choices: ["Quels", "Qui", "Combien", "Où"], correctIdx: 0 },
        { sentence: "___ avez-vous le rendez-vous avec le conseiller ? — Lundi prochain.", choices: ["Quand", "Où", "Qui", "Comment"], correctIdx: 0 },
      ],
    },
  ],
};
