import type { GrammarLesson } from "../../grammar-data";

/** Unité 27 — Les adjectifs indéfinis (G3.7) */
export const A1_GR_ADJECTIFS_INDEFINIS: GrammarLesson = {
  slug: "a1-gr-adjectifs-indefinis",
  code: "G3.7",
  level: "A1",
  title: "Les adjectifs indéfinis",
  theory: [
    {
      type: "heading",
      text: "Utilisation",
      trans: {
        en: "Uses",
        ar: "الاستخدام",
        fa: "کاربرد",
        pt: "Utilização",
        so: "Isticmaalka",
        ti: "ኣጠቓቕማ",
        tr: "Kullanım",
        ps: "کارونه",
        uk: "Вживання",
      },
    },
    {
      type: "text",
      text: "Les adjectifs indéfinis expriment en général une quantité",
      transText: {
        en: "Indefinite adjectives generally express a quantity.",
        ar: "تعبّر الصفات غير المحددة عمومًا عن كمية.",
        fa: "صفت‌های نامعین معمولاً یک مقدار را بیان می‌کنند.",
        pt: "Os adjetivos indefinidos geralmente expressam uma quantidade.",
        so: "Sifooyinka aan cayimanayn guud ahaan waxay muujiyaan tiro ama qaddar.",
        ti: "ቅጽልታት ዘይተወሰኑ ብሓፈሻ መጠን የመልክቱ።",
        tr: "Belgisiz sıfatlar genel olarak bir miktarı ifade eder.",
        ps: "ناټاکلي صفتونه عموماً یو مقدار څرګندوي.",
        uk: "Неозначені прикметники зазвичай виражають кількість.",
      },
    },
    {
      type: "text",
      label: "Tout",
      text: "{a}Tout{/a} exprime la totalité d'un ensemble. Il est suivi d'un {a}nom avec déterminant{/a} et {a}s'accorde{/a} en genre et en nombre.",
      transText: {
        en: "{a}Tout{/a} expresses the totality of a group. It is followed by a {a}noun with a determiner{/a} and {a}agrees{/a} in gender and number.",
        ar: "تعبّر {a}Tout{/a} عن مجموعة كاملة. وتأتي بعدها {a}اسم مع محدد{/a} و{a}تتطابق{/a} معه في الجنس والعدد.",
        fa: "{a}Tout{/a} تمامیت یک مجموعه را بیان می‌کند. بعد از آن {a}اسم همراه با تعیین‌کننده{/a} می‌آید و از نظر جنس و تعداد با آن {a}مطابقت دارد{/a}.",
        pt: "{a}Tout{/a} exprime a totalidade de um conjunto. É seguido de um {a}nome com determinante{/a} e {a}concorda{/a} em género e número.",
        so: "{a}Tout{/a} wuxuu muujinayaa dhammaan qaybaha koox. Waxaa ka dambeeya {a}magac leh tilmaame{/a}, wuxuuna {a}la jaanqaadaa{/a} jinsiga iyo tirada.",
        ti: "{a}Tout{/a} ንምሉእ ሓደ ስብስብ የመልክት። ድሕሪኡ {a}ስም ምስ መወሰኒ{/a} ይመጽእ እሞ ብጾታን ብብዝሕን {a}ይሰማማዕ{/a}።",
        tr: "{a}Tout{/a} bir grubun tamamını ifade eder. Ardından {a}belirleyicili bir isim{/a} gelir ve isimle cinsiyet ve sayı bakımından {a}uyum sağlar{/a}.",
        ps: "{a}Tout{/a} د یوې ډلې بشپړوالی څرګندوي. له دې وروسته {a}د ټاکونکي سره نوم{/a} راځي او له نوم سره په جنس او شمېر کې {a}سمون خوري{/a}.",
        uk: "{a}Tout{/a} виражає всю сукупність. Після нього вживається {a}іменник із визначником{/a}, з яким він {a}узгоджується{/a} в роді та числі.",
      },
    },
    {
      type: "grid",
      headers: ["", "Forme", "Exemple"],
      transHeaders: {
        en: ["", "Form", "Example"],
        ar: ["", "الصيغة", "مثال"],
        fa: ["", "شکل", "مثال"],
        pt: ["", "Forma", "Exemplo"],
        so: ["", "Qaab", "Tusaale"],
        ti: ["", "ቅርጺ", "ኣብነት"],
        tr: ["", "Biçim", "Örnek"],
        ps: ["", "بڼه", "بېلګه"],
        uk: ["", "Форма", "Приклад"],
      },
      boldFirstCol: true,
      rows: [
        ["Masculin", "{a}tout{/a}", "{a}Tout{/a} le livre est intéressant."],
        ["Masc. pluriel", "{a}tous{/a}", "{a}Tous{/a} les enfants jouent."],
        ["Féminin", "{a}toute{/a}", "{a}Toute{/a} la classe travaille."],
        ["Fem. pluriel", "{a}toutes{/a}", "{a}Toutes{/a} les pommes sont rouges."],
      ],
    },
    {
      type: "text",
      text: "{a}Tout le monde{/a} est suivi d'un {a}verbe au singulier{/a}.",
      transText: {
        en: "{a}Tout le monde{/a} is followed by a {a}singular verb{/a}.",
        ar: "تأتي {a}Tout le monde{/a} مع {a}فعل مفرد{/a}.",
        fa: "{a}Tout le monde{/a} با یک {a}فعل مفرد{/a} به کار می‌رود.",
        pt: "{a}Tout le monde{/a} é seguido de um {a}verbo no singular{/a}.",
        so: "{a}Tout le monde{/a} waxaa ku xiga {a}fal keli ah{/a}.",
        ti: "{a}Tout le monde{/a} ብ{a}ንጽል ግሲ{/a} ይስዕብ።",
        tr: "{a}Tout le monde{/a} sözcüğünden sonra {a}tekil bir fiil{/a} gelir.",
        ps: "{a}Tout le monde{/a} څخه وروسته {a}مفرد فعل{/a} راځي.",
        uk: "Після {a}Tout le monde{/a} вживається {a}дієслово в однині{/a}.",
      },
      items: [
        "{a}Tout le monde{/a} chante.",
      ],
      noBulletItems: [0]
    }
    {
      type: "text",
      label: "Chaque",
      text : "{a}Chaque{/a} présente les éléments un par un. Il est {a}invariable{/a} et suivi d'un {a}nom singulier{/a}.",
      transText: {
        en: "{a}Chaque{/a} presents the elements one by one. It is {a}invariable{/a} and is followed by a {a}singular noun{/a}.",
        ar: "تُقدّم {a}Chaque{/a} العناصر واحدًا تلو الآخر. وهي {a}ثابتة{/a} وتتبعها {a}أسماء مفردة{/a}.",
        fa: "{a}Chaque{/a} عناصر را یکی‌یکی بیان می‌کند. این واژه {a}تغییرناپذیر{/a} است و پس از آن {a}اسم مفرد{/a} می‌آید.",
        pt: "{a}Chaque{/a} apresenta os elementos um por um. É {a}invariável{/a} e é seguido de um {a}nome no singular{/a}.",
        so: "{a}Chaque{/a} wuxuu soo bandhigaa walxaha mid mid. Waa {a}aan isbeddelin{/a} waxaana ka dambeeya {a}magac keli ah{/a}.",
        ti: "{a}Chaque{/a} ነፍሲ ወከፍ ነገር በበይኑ የቕርብ። ንሱ {a}ዘይልወጥ{/a} እዩ እሞ ብድሕሪኡ {a}ንጽል ስም{/a} ይመጽእ።",
        tr: "{a}Chaque{/a} unsurları tek tek ifade eder. {a}Değişmez{/a} ve ardından {a}tekil bir isim{/a} gelir.",
        ps: "{a}Chaque{/a} توکي یو په یو وړاندې کوي. دا {a}نه بدلېدونکی{/a} دی او وروسته ترې {a}مفرد نوم{/a} راځي.",
        uk: "{a}Chaque{/a} представляє елементи один за одним. Це {a}незмінне{/a} слово, після якого вживається {a}іменник в однині{/a}.",
      },
      items: [
        "Le chanteur a présenté {a}chaque{/a} musicien de son groupe.",
      ],
      noBulletItems: [0],
    },
    {
      type: "text",
      label: "Aucun",
      text: "{a}Aucun{/a} indique l'absence d'une personne ou d'une chose. Il est suivi d'un {a}nom singulier{/a} et s'utilise toujours avec {a}ne{/a}.",
      transText: {
        en: "{a}Aucun{/a} indicates the absence of a person or thing. It is followed by a {a}singular noun{/a} and is always used with {a}ne{/a}.",
        ar: "تدل {a}Aucun{/a} على غياب شخص أو شيء. وتأتي بعدها {a}اسم مفرد{/a} وتُستخدم دائمًا مع {a}ne{/a}.",
        fa: "{a}Aucun{/a} نبود یک شخص یا چیز را نشان می‌دهد. پس از آن {a}اسم مفرد{/a} می‌آید و همیشه با {a}ne{/a} استفاده می‌شود.",
        pt: "{a}Aucun{/a} indica a ausência de uma pessoa ou de uma coisa. É seguido de um {a}nome no singular{/a} e é sempre usado com {a}ne{/a}.",
        so: "{a}Aucun{/a} wuxuu muujinayaa maqnaanshaha qof ama shay. Waxaa ka dambeeya {a}magac keli ah{/a}, waxaana had iyo jeer lala isticmaalaa {a}ne{/a}.",
        ti: "{a}Aucun{/a} ናይ ሓደ ሰብ ወይ ነገር ዘይምህላው የመልክት። ድሕሪኡ {a}ንጽል ስም{/a} ይመጽእ እሞ ኩሉ ግዜ ምስ {a}ne{/a} ይጥቀም።",
        tr: "{a}Aucun{/a} bir kişinin veya şeyin bulunmadığını ifade eder. Ardından {a}tekil bir isim{/a} gelir ve her zaman {a}ne{/a} ile kullanılır.",
        ps: "{a}Aucun{/a} د یو کس یا شي نشتوالی څرګندوي. وروسته ترې {a}مفرد نوم{/a} راځي او تل له {a}ne{/a} سره کارېږي.",
        uk: "{a}Aucun{/a} указує на відсутність особи або речі. Після нього вживається {a}іменник в однині{/a}, і він завжди використовується з {a}ne{/a}.",
      },
      items: [
        "{a}Aucun{/a} élève n'est absent.",
        "Il n'y a aucune fille dans la salle.",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "text",
      label: "Plusieurs",
      text: "{a}Plusieurs{/a} indique une quantité supérieure à deux, sans préciser le nombre. Il est {a}invariable{/a}, toujours au {a}pluriel{/a} et suivi d'un {a}nom sans article{/a}.",
      transText: {
        en: "{a}Plusieurs{/a} indicates a quantity greater than two without specifying the exact number. It is {a}invariable{/a}, always {a}plural{/a}, and is followed by a {a}noun without an article{/a}.",
        ar: "تدل {a}Plusieurs{/a} على كمية أكبر من اثنين دون تحديد العدد بدقة. وهي {a}ثابتة{/a} وتأتي دائمًا في {a}صيغة الجمع{/a}، ويتبعها {a}اسم بدون أداة{/a}.",
        fa: "{a}Plusieurs{/a} مقداری بیشتر از دو را بدون مشخص کردن تعداد دقیق نشان می‌دهد. این واژه {a}تغییرناپذیر{/a} است، همیشه به صورت {a}جمع{/a} می‌آید و پس از آن {a}اسم بدون حرف تعریف{/a} قرار می‌گیرد.",
        pt: "{a}Plusieurs{/a} indica uma quantidade superior a dois, sem precisar o número exato. É {a}invariável{/a}, está sempre no {a}plural{/a} e é seguido de um {a}nome sem artigo{/a}.",
        so: "{a}Plusieurs{/a} wuxuu muujinayaa tiro ka badan laba, iyada oo aan la sheegin tirada saxda ah. Waa {a}aan isbeddelin{/a}, mar walbana wuxuu ku jiraa {a}jamac{/a}, waxaana ka dambeeya {a}magac aan lahayn maqaal{/a}.",
        ti: "{a}Plusieurs{/a} ካብ ክልተ ዝበልጽ መጠን እንተላይ እዩ ዘመልክት፣ ትክክለኛ ቁጽሪ ግን ኣይገልጽን። {a}ዘይልወጥ{/a} እዩ፣ ኩሉ ግዜ {a}ብዙሕ{/a} እዩ ዝኸውን፣ ድሕሪኡ ድማ {a}ብዘይ ኣንቀጽ ስም{/a} ይመጽእ።",
        tr: "{a}Plusieurs{/a} kesin sayıyı belirtmeden ikiden fazla bir miktarı ifade eder. {a}Değişmez{/a}, her zaman {a}çoğul{/a} kullanılır ve ardından {a}artikelsiz bir isim{/a} gelir.",
        ps: "{a}Plusieurs{/a} له دوو څخه د زیات شمېر اندازه ښيي، پرته له دې چې دقیق شمېر معلوم کړي. دا {a}نه بدلېدونکی{/a} دی، تل په {a}جمع{/a} کې راځي او وروسته ترې {a}بې له ټاکونکي نوم{/a} راځي.",
        uk: "{a}Plusieurs{/a} указує на кількість, більшу за два, без уточнення точної кількості. Це {a}незмінне{/a} слово, яке завжди вживається у {a}множині{/a} та перед {a}іменником без артикля{/a}.",
      },
      items: [
        "J'ai {a}plusieurs{/a} amis.",
        "Il y a {a}plusieurs{/a} livres sur la table.",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "text",
      label: "Quelques",
      text: "{a}Quelques{/a} indique un petit nombre de personnes ou de choses. Il est {a}invariable{/a}, toujours au {a}pluriel{/a} et suivi d'un {a}nom sans article{/a}.",
      transText: {
        en: "{a}Quelques{/a} indicates a small number of people or things. It is {a}invariable{/a}, always {a}plural{/a}, and is followed by a {a}noun without an article{/a}.",
        ar: "تدل {a}Quelques{/a} على عدد قليل من الأشخاص أو الأشياء. وهي {a}ثابتة{/a} وتأتي دائمًا في {a}صيغة الجمع{/a}، ويتبعها {a}اسم بدون أداة{/a}.",
        fa: "{a}Quelques{/a} تعداد کمی از افراد یا چیزها را نشان می‌دهد. این واژه {a}تغییرناپذیر{/a} است، همیشه به صورت {a}جمع{/a} می‌آید و پس از آن {a}اسم بدون حرف تعریف{/a} قرار می‌گیرد.",
        pt: "{a}Quelques{/a} indica um pequeno número de pessoas ou coisas. É {a}invariável{/a}, está sempre no {a}plural{/a} e é seguido de um {a}nome sem artigo{/a}.",
        so: "{a}Quelques{/a} wuxuu muujinayaa tiro yar oo dad ama waxyaabo ah. Waa {a}aan isbeddelin{/a}, mar walbana wuxuu ku jiraa {a}jamac{/a}, waxaana ka dambeeya {a}magac aan lahayn maqaal{/a}.",
        ti: "{a}Quelques{/a} ውሑድ ቁጽሪ ሰባት ወይ ነገራት የመልክት። {a}ዘይልወጥ{/a} እዩ፣ ኩሉ ግዜ {a}ብዙሕ{/a} እዩ ዝኸውን፣ ድሕሪኡ ድማ {a}ብዘይ ኣንቀጽ ስም{/a} ይመጽእ።",
        tr: "{a}Quelques{/a} az sayıda insanı veya şeyi ifade eder. {a}Değişmez{/a}, her zaman {a}çoğul{/a} kullanılır ve ardından {a}artikelsiz bir isim{/a} gelir.",
        ps: "{a}Quelques{/a} د خلکو یا شیانو لږ شمېر ښيي. دا {a}نه بدلېدونکی{/a} دی، تل په {a}جمع{/a} کې راځي او وروسته ترې {a}بې له ټاکونکي نوم{/a} راځي.",
        uk: "{a}Quelques{/a} указує на невелику кількість людей або речей. Це {a}незмінне{/a} слово, яке завжди вживається у {a}множині{/a} та перед {a}іменником без артикля{/a}.",
      },
      items: [
        "J'ai {a}quelques{/a} amis.",
        "Il y a {a}quelques{/a} pommes dans le panier.",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "text",
      label: "Même(s)",
      text: "{a}Même{/a} indique une ressemblance. Il peut être au {a}singulier{/a} ou au {a}pluriel{/a} et est suivi d'un {a}nom avec déterminant{/a}.",
      transText: {
        en: "{a}Même{/a} indicates similarity. It can be {a}singular{/a} or {a}plural{/a} and is followed by a {a}noun with a determiner{/a}.",
        ar: "تدل {a}Même{/a} على التشابه. ويمكن أن تكون في {a}المفرد{/a} أو {a}الجمع{/a}، ويتبعها {a}اسم مع محدد{/a}.",
        fa: "{a}Même{/a} شباهت را نشان می‌دهد. می‌تواند به صورت {a}مفرد{/a} یا {a}جمع{/a} بیاید و پس از آن {a}اسم همراه با تعیین‌کننده{/a} قرار می‌گیرد.",
        pt: "{a}Même{/a} indica uma semelhança. Pode estar no {a}singular{/a} ou no {a}plural{/a} e é seguido de um {a}nome com determinante{/a}.",
        so: "{a}Même{/a} wuxuu muujinayaa isku ekaansho. Wuxuu noqon karaa {a}keli{/a} ama {a}jamac{/a}, waxaana ka dambeeya {a}magac leh tilmaame{/a}.",
        ti: "{a}Même{/a} ምስሳል የመልክት። ኣብ {a}ንጽል{/a} ወይ {a}ብዙሕ{/a} ክኸውን ይኽእል፣ ድሕሪኡ ድማ {a}ስም ምስ መወሰኒ{/a} ይመጽእ።",
        tr: "{a}Même{/a} benzerliği ifade eder. {a}Tekil{/a} veya {a}çoğul{/a} olabilir ve ardından {a}belirleyicili bir isim{/a} gelir.",
        ps: "{a}Même{/a} ورته والی څرګندوي. دا په {a}مفرد{/a} یا {a}جمع{/a} کې راتلای شي او وروسته ترې {a}د ټاکونکي سره نوم{/a} راځي.",
        uk: "{a}Même{/a} виражає схожість. Воно може бути в {a}однині{/a} або {a}множині{/a}, після нього вживається {a}іменник із визначником{/a}.",
      },
      items: [
        "J'aime {a}la même{/a} chanson que toi.",
        "Nous avons {a}les mêmes{/a} chaussures.",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "text",
      label: "Autre(s)",
      text: "{a}Autre{/a} indique une différence. Il peut être au {a}singulier{/a} ou au {a}pluriel{/a} et est suivi d'un {a}nom avec déterminant{/a}. Au pluriel, on utilise {a}d'autres{/a}.",
      transText: {
        en: "{a}Autre{/a} indicates a difference. It can be {a}singular{/a} or {a}plural{/a} and is followed by a {a}noun with a determiner{/a}. In the plural, we use {a}d'autres{/a}.",
        ar: "تدل {a}Autre{/a} على الاختلاف. ويمكن أن تكون في {a}المفرد{/a} أو {a}الجمع{/a}، ويتبعها {a}اسم مع محدد{/a}. في الجمع، نستخدم {a}d'autres{/a}.",
        fa: "{a}Autre{/a} تفاوت را نشان می‌دهد. می‌تواند به صورت {a}مفرد{/a} یا {a}جمع{/a} بیاید و پس از آن {a}اسم همراه با تعیین‌کننده{/a} قرار می‌گیرد. در جمع از {a}d'autres{/a} استفاده می‌کنیم.",
        pt: "{a}Autre{/a} indica uma diferença. Pode estar no {a}singular{/a} ou no {a}plural{/a} e é seguido de um {a}nome com determinante{/a}. No plural, usa-se {a}d'autres{/a}.",
        so: "{a}Autre{/a} wuxuu muujinayaa kala duwanaansho. Wuxuu noqon karaa {a}keli{/a} ama {a}jamac{/a}, waxaana ka dambeeya {a}magac leh tilmaame{/a}. Jamaca waxaa loo isticmaalaa {a}d'autres{/a}.",
        ti: "{a}Autre{/a} ፍልልይ የመልክት። ኣብ {a}ንጽል{/a} ወይ {a}ብዙሕ{/a} ክኸውን ይኽእል፣ ድሕሪኡ ድማ {a}ስም ምስ መወሰኒ{/a} ይመጽእ። ኣብ ብዙሕ ን{a}d'autres{/a} ንጥቀም።",
        tr: "{a}Autre{/a} farklılığı ifade eder. {a}Tekil{/a} veya {a}çoğul{/a} olabilir ve ardından {a}belirleyicili bir isim{/a} gelir. Çoğulda {a}d'autres{/a} kullanılır.",
        ps: "{a}Autre{/a} توپیر څرګندوي. دا په {a}مفرد{/a} یا {a}جمع{/a} کې راتلای شي او وروسته ترې {a}د ټاکونکي سره نوم{/a} راځي. په جمع کې {a}d'autres{/a} کاروو.",
        uk: "{a}Autre{/a} виражає відмінність. Воно може бути в {a}однині{/a} або {a}множині{/a}, після нього вживається {a}іменник із визначником{/a}. У множині використовуємо {a}d'autres{/a}.",
      },
      items: [
        "Mon frère a {a}une autre{/a} voiture.",
        "J'aimerais écouter {a}d'autres{/a} chansons.",
      ],
      noBulletItems: [0, 1],
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Adjectifs indéfinis",
      instruction: "Choisissez la forme correcte.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "J'ai vu ___ les films de Godard.", choices: ["tous", "tout", "toutes"], correctIdx: 0 },
        { sentence: "Elle écoute cette chanson ___ la journée.", choices: ["toute", "tout", "tous"], correctIdx: 0 },
        { sentence: "___ le monde chante.", choices: ["Tout", "Tous", "Toute"], correctIdx: 0 },
        { sentence: "Il a présenté ___ musicien.", choices: ["chaque", "chacun", "tous"], correctIdx: 0 },
        { sentence: "Il n'y a ___ fille dans le groupe.", choices: ["aucune", "aucun", "chaque"], correctIdx: 0 },
        { sentence: "J'ai ___ amis musiciens. (plus de deux)", choices: ["plusieurs", "chaque", "aucun"], correctIdx: 0 },
        { sentence: "J'ai ___ amis musiciens. (pas beaucoup)", choices: ["quelques", "chaque", "tout"], correctIdx: 0 },
        { sentence: "J'aime la ___ chanson que toi.", choices: ["même", "mêmes", "autre"], correctIdx: 0 },
        { sentence: "J'aimerais écouter ___ chansons.", choices: ["d'autres", "des autres", "autres"], correctIdx: 0 },
        { sentence: "Il va au concert ___ trois mois.", choices: ["tous les", "chaque", "toutes les"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Complétez",
      instruction: "Écrivez l'adjectif indéfini qui convient.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "Vous avez vu ___ le spectacle.", hint: "totalité ms", answer: "tout" },
        { sentence: "Vous avez aimé ___ ces chansons ?", hint: "totalité fp", answer: "toutes" },
        { sentence: "Il a présenté ___ musicien.", hint: "un par un", answer: "chaque" },
        { sentence: "Il n'y a ___ musicienne.", hint: "zéro + fs", answer: "aucune" },
        { sentence: "J'ai ___ amis musiciens. (> 2)", hint: "pluralité", answer: "plusieurs" },
        { sentence: "J'ai ___ amis musiciens. (peu)", hint: "petit nombre", answer: "quelques" },
        { sentence: "nous aimons les ___ chanteurs.", hint: "ressemblance", answer: "mêmes" },
        { sentence: "mon ___ frère est guitariste.", hint: "différence", answer: "autre" },
        { sentence: "écouter ___ chansons (pluriel de un autre)", hint: "d'autres", answer: "d'autres" },
        { sentence: "___ les mois (= chaque mois)", hint: "répétition", answer: "tous" },
      ],
    },
  ],
};
