import type { GrammarLesson } from "../../grammar-data";

export const A2_GR_L09: GrammarLesson = {
  slug: "a2-gr-l09",
  code: "RX.13",
  level: "A2",
  title: "Répondre aux questions fermées",
  theory: [
    { type: "heading", text: "Oui, Non, Si", trans: { en: "Oui (yes), Non (no), Si (yes, to a negative)", ar: "Oui (نعم)، Non (لا)، Si (بلى)", fa: "Oui (بله)، Non (خیر)، Si (چرا)", ti: "Oui (እወ)፣ Non (ኣይፋል)፣ Si (እወ ንኣሉታ)", uk: "Oui (так), Non (ні), Si (так, на заперечне)" } },
    {
      type: "grid",
      headers: ["Réponse", "Quand l'utiliser", "Exemple"],
      boldFirstCol: true,
      rows: [
        ["{a}Oui{/a}", "Réponse {a}affirmative{/a}", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café."],
        ["{a}Non{/a}", "Réponse {a}négative{/a}", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café."],
        ["{a}Si{/a}", "Réponse {a}affirmative{/a} à une question {a}négative{/a}", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français !"],
      ],
      transHeaders: {
        en: ["Answer", "When to use it", "Example"],
        ar: ["الإجابة", "متى نستخدمها", "مثال"],
        fa: ["پاسخ", "زمان استفاده", "مثال"],
        ti: ["መልሲ", "መዓስ ከም ዝጥቀመሉ", "ኣብነት"],
        uk: ["Відповідь", "Коли вживати", "Приклад"],
      },
      transRows: {
        en: [["{a}Oui{/a}", "{a}Affirmative{/a} answer", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café. (Do you like coffee? — Yes, I like coffee.)"], ["{a}Non{/a}", "{a}Negative{/a} answer", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café. (Do you like coffee? — No, I don't.)"], ["{a}Si{/a}", "{a}Affirmative{/a} answer to a {a}negative{/a} question", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français ! (Don't you speak French? — Yes, I do!)"]],
        ar: [["{a}Oui{/a}", "إجابة {a}مثبتة{/a}", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café. (هل تحب القهوة؟ — نعم، أحب القهوة.)"], ["{a}Non{/a}", "إجابة {a}منفية{/a}", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café. (هل تحب القهوة؟ — لا.)"], ["{a}Si{/a}", "إجابة {a}مثبتة{/a} على سؤال {a}منفي{/a}", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français ! (ألا تتكلم الفرنسية؟ — بلى، أتكلمها!)"]],
        fa: [["{a}Oui{/a}", "پاسخ {a}مثبت{/a}", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café. (قهوه دوست داری؟ — بله، قهوه دوست دارم.)"], ["{a}Non{/a}", "پاسخ {a}منفی{/a}", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café. (قهوه دوست داری؟ — خیر.)"], ["{a}Si{/a}", "پاسخ {a}مثبت{/a} به پرسش {a}منفی{/a}", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français ! (فرانسوی صحبت نمی‌کنی؟ — چرا، می‌کنم!)"]],
        ti: [["{a}Oui{/a}", "ኣረጋጋጺ {a}መልሲ{/a}", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café. (ቡን ትፈቱ ዶ? — እወ፣ ቡን እፈቱ።)"], ["{a}Non{/a}", "{a}ኣሉታዊ{/a} መልሲ", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café. (ቡን ትፈቱ ዶ? — ኣይፋል።)"], ["{a}Si{/a}", "ኣረጋጋጺ {a}መልሲ{/a} ናብ {a}ኣሉታዊ{/a} ሕቶ", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français ! (ፈረንሳይ ኣይትዛረብን ዲኻ? — እወ፣ ፈረንሳይ እዛረብ!)"]],
        uk: [["{a}Oui{/a}", "{a}Стверджувальна{/a} відповідь", "Tu aimes le café ?\n— {a}Oui{/a}, j'aime le café. (Ти любиш каву? — Так, люблю.)"], ["{a}Non{/a}", "{a}Заперечна{/a} відповідь", "Tu aimes le café ?\n— {a}Non{/a}, je {a}n'{/a}aime {a}pas{/a} le café. (Ти любиш каву? — Ні.)"], ["{a}Si{/a}", "{a}Стверджувальна{/a} відповідь на {a}заперечне{/a} питання", "Tu {a}ne{/a} parles {a}pas{/a} français ?\n— {a}Si{/a}, je parle français ! (Хіба ти не говориш французькою? — Так, говорю!)"]],
      },
    },
    {
      type: "highlight",
      label: "SI : le mot clé",
      items: [
        "{a}Si{/a} s'utilise uniquement pour contredire une question négative.",
        "Tu ne viens pas ? — {a}Si{/a}, je viens ! (pas Oui !)",
        "Il ne travaille pas ? — {a}Si{/a}, il travaille !",
      ],
      noBulletItems: [0],
      transLabel: { en: "SI: the key word", ar: "SI: الكلمة المفتاحية", fa: "SI: کلمه‌ی کلیدی", ti: "SI: እታ ቁልፊ ቃል", uk: "SI: ключове слово" },
      transItems: {
        en: ["{a}Si{/a} is used only to contradict a negative question.", "Tu ne viens pas ? — {a}Si{/a}, je viens ! (Aren't you coming? — Yes, I am!) (not Oui!)", "Il ne travaille pas ? — {a}Si{/a}, il travaille ! (Doesn't he work? — Yes, he does!)"],
        ar: ["{a}Si{/a} يُستخدم فقط للرد على سؤال منفي.", "Tu ne viens pas ? — {a}Si{/a}, je viens ! (ألا تأتي؟ — بلى، آتي!) (ليس Oui!)", "Il ne travaille pas ? — {a}Si{/a}, il travaille ! (ألا يعمل؟ — بلى، يعمل!)"],
        fa: ["{a}Si{/a} فقط برای رد کردن یک پرسش منفی به کار می‌رود.", "Tu ne viens pas ? — {a}Si{/a}, je viens ! (نمی‌آیی؟ — چرا، می‌آیم!) (نه Oui!)", "Il ne travaille pas ? — {a}Si{/a}, il travaille ! (کار نمی‌کند؟ — چرا، می‌کند!)"],
        ti: ["{a}Si{/a} ንኣሉታዊ ሕቶ ንምቅዋም ጥራይ ይጥቀም።", "Tu ne viens pas ? — {a}Si{/a}, je viens ! (ኣይትመጽእን ዲኻ? — እወ፣ እመጽእ!) (ኣይኮነን Oui!)", "Il ne travaille pas ? — {a}Si{/a}, il travaille ! (ኣይሰርሕን ድዩ? — እወ፣ ይሰርሕ!)"],
        uk: ["{a}Si{/a} вживається лише для заперечення заперечного питання.", "Tu ne viens pas ? — {a}Si{/a}, je viens ! (Хіба ти не йдеш? — Так, іду!) (не Oui!)", "Il ne travaille pas ? — {a}Si{/a}, il travaille ! (Хіба він не працює? — Так, працює!)"],
      },
    },
    { type: "heading", text: "Moi aussi / Moi non plus / Moi si / Moi pas", sub: true, accent: true, trans: { en: "Moi aussi / Moi non plus / Moi si / Moi pas (Me too / Me neither / Yes I do / Not me)", ar: "Moi aussi / Moi non plus / Moi si / Moi pas (أنا أيضاً / ولا أنا / بلى أنا / ليس أنا)", fa: "Moi aussi / Moi non plus / Moi si / Moi pas (من هم / من هم نه / چرا من / من نه)", ti: "Moi aussi / Moi non plus / Moi si / Moi pas (ኣነ እውን / ኣነ እውን ኣይኮንኩን / እወ ኣነ / ኣነ ኣይኮንኩን)", uk: "Moi aussi / Moi non plus / Moi si / Moi pas (Я теж / Я теж ні / Я так / Я ні)" } },
    {
      type: "grid",
      headers: ["Situation", "Réaction accord", "Réaction désaccord"],
      boldFirstCol: true,
      rows: [
        ["Affirmation {a}positive{/a}", "{a}Moi aussi !{/a}", "Moi pas. / Pas moi."],
        ["Affirmation {a}négative{/a}", "{a}Moi non plus !{/a}", "Moi si !"],
      ],
      transHeaders: {
        en: ["Situation", "Agreeing reaction", "Disagreeing reaction"],
        ar: ["الموقف", "رد الموافقة", "رد الاعتراض"],
        fa: ["موقعیت", "واکنش موافق", "واکنش مخالف"],
        ti: ["ኩነታት", "ናይ ስምምዕ ግብረ-መልሲ", "ናይ ዘይምስምማዕ ግብረ-መልሲ"],
        uk: ["Ситуація", "Реакція згоди", "Реакція незгоди"],
      },
      transRows: {
        en: [["{a}Positive{/a} statement", "{a}Moi aussi !{/a} (Me too!)", "Moi pas. / Pas moi. (Not me.)"], ["{a}Negative{/a} statement", "{a}Moi non plus !{/a} (Me neither!)", "Moi si ! (I do!)"]],
        ar: [["تأكيد {a}إيجابي{/a}", "{a}Moi aussi !{/a} (أنا أيضاً!)", "Moi pas. / Pas moi. (ليس أنا.)"], ["تأكيد {a}سلبي{/a}", "{a}Moi non plus !{/a} (ولا أنا!)", "Moi si ! (بلى أنا!)"]],
        fa: [["جمله‌ی {a}مثبت{/a}", "{a}Moi aussi !{/a} (من هم!)", "Moi pas. / Pas moi. (من نه.)"], ["جمله‌ی {a}منفی{/a}", "{a}Moi non plus !{/a} (من هم نه!)", "Moi si ! (چرا، من!)"]],
        ti: [["{a}ኣወንታዊ{/a} ኣረጋግጻ", "{a}Moi aussi !{/a} (ኣነ እውን!)", "Moi pas. / Pas moi. (ኣነ ኣይኮንኩን።)"], ["{a}ኣሉታዊ{/a} ኣረጋግጻ", "{a}Moi non plus !{/a} (ኣነ እውን ኣይኮንኩን!)", "Moi si ! (እወ ኣነ!)"]],
        uk: [["{a}Стверджувальне{/a} твердження", "{a}Moi aussi !{/a} (Я теж!)", "Moi pas. / Pas moi. (Я ні.)"], ["{a}Заперечне{/a} твердження", "{a}Moi non plus !{/a} (Я теж ні!)", "Moi si ! (А я так!)"]],
      },
    },
    {
      type: "grid",
      headers: ["Ce qu'il dit", "Tu es d'accord", "Tu n'es pas d'accord"],
      rows: [
        ["J'aime le café.", "{a}Moi aussi !{/a}", "Moi pas."],
        ["Je ne fume pas.", "{a}Moi non plus !{/a}", "Moi si !"],
        ["Je n'aime pas ça.", "{a}Moi non plus !{/a}", "Moi si."],
        ["J'ai faim.", "{a}Moi aussi !{/a}", "Pas moi."],
      ],
      transHeaders: {
        en: ["What he says", "You agree", "You disagree"],
        ar: ["ما يقوله", "أنت توافق", "أنت تعترض"],
        fa: ["آنچه می‌گوید", "موافقی", "مخالفی"],
        ti: ["ዝብሎ", "ትሰማማዕ", "ኣይትሰማማዕን"],
        uk: ["Що він каже", "Ти згоден", "Ти не згоден"],
      },
      transRows: {
        en: [["J'aime le café. (I like coffee.)", "{a}Moi aussi !{/a} (Me too!)", "Moi pas. (Not me.)"], ["Je ne fume pas. (I don't smoke.)", "{a}Moi non plus !{/a} (Me neither!)", "Moi si ! (I do!)"], ["Je n'aime pas ça. (I don't like that.)", "{a}Moi non plus !{/a} (Me neither!)", "Moi si. (I do.)"], ["J'ai faim. (I'm hungry.)", "{a}Moi aussi !{/a} (Me too!)", "Pas moi. (Not me.)"]],
        ar: [["J'aime le café. (أحب القهوة.)", "{a}Moi aussi !{/a} (أنا أيضاً!)", "Moi pas. (ليس أنا.)"], ["Je ne fume pas. (لا أدخّن.)", "{a}Moi non plus !{/a} (ولا أنا!)", "Moi si ! (بلى أنا!)"], ["Je n'aime pas ça. (لا أحب ذلك.)", "{a}Moi non plus !{/a} (ولا أنا!)", "Moi si. (بلى أنا.)"], ["J'ai faim. (أنا جائع.)", "{a}Moi aussi !{/a} (أنا أيضاً!)", "Pas moi. (ليس أنا.)"]],
        fa: [["J'aime le café. (قهوه دوست دارم.)", "{a}Moi aussi !{/a} (من هم!)", "Moi pas. (من نه.)"], ["Je ne fume pas. (سیگار نمی‌کشم.)", "{a}Moi non plus !{/a} (من هم نه!)", "Moi si ! (چرا، من!)"], ["Je n'aime pas ça. (آن را دوست ندارم.)", "{a}Moi non plus !{/a} (من هم نه!)", "Moi si. (چرا، من.)"], ["J'ai faim. (گرسنه‌ام.)", "{a}Moi aussi !{/a} (من هم!)", "Pas moi. (من نه.)"]],
        ti: [["J'aime le café. (ቡን እፈቱ።)", "{a}Moi aussi !{/a} (ኣነ እውን!)", "Moi pas. (ኣነ ኣይኮንኩን።)"], ["Je ne fume pas. (ኣይትክኽን።)", "{a}Moi non plus !{/a} (ኣነ እውን ኣይኮንኩን!)", "Moi si ! (እወ ኣነ!)"], ["Je n'aime pas ça. (ንሱ ኣይፈቱን።)", "{a}Moi non plus !{/a} (ኣነ እውን ኣይኮንኩን!)", "Moi si. (እወ ኣነ።)"], ["J'ai faim. (ጠምየ ኣለኹ።)", "{a}Moi aussi !{/a} (ኣነ እውን!)", "Pas moi. (ኣነ ኣይኮንኩን።)"]],
        uk: [["J'aime le café. (Я люблю каву.)", "{a}Moi aussi !{/a} (Я теж!)", "Moi pas. (Я ні.)"], ["Je ne fume pas. (Я не палю.)", "{a}Moi non plus !{/a} (Я теж ні!)", "Moi si ! (А я палю!)"], ["Je n'aime pas ça. (Мені це не подобається.)", "{a}Moi non plus !{/a} (Мені теж ні!)", "Moi si. (А мені так.)"], ["J'ai faim. (Я голодний.)", "{a}Moi aussi !{/a} (Я теж!)", "Pas moi. (Я ні.)"]],
      },
    },
    { type: "heading", text: "Répondre avec des pronoms", sub: true, accent: true, trans: { en: "Answering with pronouns", ar: "الإجابة باستخدام الضمائر", fa: "پاسخ دادن با ضمایر", ti: "ብጸጋ ቃላት ምምላስ", uk: "Відповідь із займенниками" } },
    {
      type: "grid",
      headers: ["Question", "Réponse courte"],
      rows: [
        ["Tu viens ce soir ?", "Oui, j'y viens. / Non, je n'y viens pas."],
        ["Elle a mangé ?", "Oui, elle a mangé. / Non, elle n'a pas mangé."],
        ["Vous avez des questions ?", "Oui, j'en ai une. / Non, je n'en ai pas."],
      ],
      transHeaders: {
        en: ["Question", "Short answer"],
        ar: ["السؤال", "إجابة قصيرة"],
        fa: ["پرسش", "پاسخ کوتاه"],
        ti: ["ሕቶ", "ሓጺር መልሲ"],
        uk: ["Питання", "Коротка відповідь"],
      },
      transRows: {
        en: [["Tu viens ce soir ? (Are you coming tonight?)", "Oui, j'y viens. / Non, je n'y viens pas. (Yes, I'm coming. / No, I'm not.)"], ["Elle a mangé ? (Has she eaten?)", "Oui, elle a mangé. / Non, elle n'a pas mangé. (Yes, she has. / No, she hasn't.)"], ["Vous avez des questions ? (Do you have any questions?)", "Oui, j'en ai une. / Non, je n'en ai pas. (Yes, I have one. / No, I don't.)"]],
        ar: [["Tu viens ce soir ? (هل تأتي هذا المساء؟)", "Oui, j'y viens. / Non, je n'y viens pas. (نعم، آتي. / لا، لا آتي.)"], ["Elle a mangé ? (هل أكلت؟)", "Oui, elle a mangé. / Non, elle n'a pas mangé. (نعم، أكلت. / لا، لم تأكل.)"], ["Vous avez des questions ? (هل لديك أسئلة؟)", "Oui, j'en ai une. / Non, je n'en ai pas. (نعم، لديّ واحد. / لا، ليس لديّ.)"]],
        fa: [["Tu viens ce soir ? (امشب می‌آیی؟)", "Oui, j'y viens. / Non, je n'y viens pas. (بله، می‌آیم. / خیر، نمی‌آیم.)"], ["Elle a mangé ? (آیا غذا خورده؟)", "Oui, elle a mangé. / Non, elle n'a pas mangé. (بله، خورده. / خیر، نخورده.)"], ["Vous avez des questions ? (سؤالی دارید؟)", "Oui, j'en ai une. / Non, je n'en ai pas. (بله، یکی دارم. / خیر، ندارم.)"]],
        ti: [["Tu viens ce soir ? (ሎሚ ምሸት ትመጽእ ዶ?)", "Oui, j'y viens. / Non, je n'y viens pas. (እወ፣ እመጽእ። / ኣይፋል፣ ኣይመጽእን።)"], ["Elle a mangé ? (በሊዓ ዶ?)", "Oui, elle a mangé. / Non, elle n'a pas mangé. (እወ፣ በሊዓ። / ኣይፋል፣ ኣይበልዐትን።)"], ["Vous avez des questions ? (ሕቶታት ኣለኩም ዶ?)", "Oui, j'en ai une. / Non, je n'en ai pas. (እወ፣ ሓንቲ ኣላትኒ። / ኣይፋል፣ የብለይን።)"]],
        uk: [["Tu viens ce soir ? (Ти прийдеш сьогодні ввечері?)", "Oui, j'y viens. / Non, je n'y viens pas. (Так, прийду. / Ні, не прийду.)"], ["Elle a mangé ? (Вона поїла?)", "Oui, elle a mangé. / Non, elle n'a pas mangé. (Так, поїла. / Ні, не поїла.)"], ["Vous avez des questions ? (У вас є запитання?)", "Oui, j'en ai une. / Non, je n'en ai pas. (Так, є одне. / Ні, немає.)"]],
      },
    },
  ],
  exercises: [],
};
