import type { ConjLesson } from "../../conjugation-data";

export const A2_CONJ_L04: ConjLesson = {
  slug: "a2-conj-l04",
  code: "R6.1",
  level: "A2",
  title: "Le conditionnel de politesse",
  theory: [
    { type: "heading", text: "Le conditionnel présent", trans: { en: "The present conditional", ar: "الشرطي الحاضر", fa: "وجه شرطی حال", ti: "ህሉው ቅድመ-ኩነታዊ", uk: "Теперішній умовний спосіб" } },
    {
      type: "plain_list",
      items: [
        "Le conditionnel exprime une action {a}hypothétique, souhaitée ou polie{/a}.",
        "Formation : {a}base du futur{/a} + terminaisons de l'imparfait",
        "Terminaisons : {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}",
      ],
      transItems: {
        en: ["The conditional expresses a {a}hypothetical, wished-for or polite{/a} action.", "Formation: {a}future stem{/a} + imperfect endings", "Endings: {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}"],
        ar: ["الشرطي يعبّر عن فعل {a}افتراضي أو مرغوب أو مؤدّب{/a}.", "التكوين: {a}جذر المستقبل{/a} + نهايات الماضي الناقص", "النهايات: {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}"],
        fa: ["وجه شرطی بیانگر عملی {a}فرضی، خواسته‌شده یا مودبانه{/a} است.", "ساختن: {a}ریشه‌ی آینده{/a} + پایانه‌های ماضی استمراری", "پایانه‌ها: {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}"],
        ti: ["ቅድመ-ኩነታዊ {a}ግምታዊ፣ ዝድለ ወይ ኣኽብሮታዊ{/a} ተግባር የመልክት።", "ኣፈጣጥራ፦ {a}መሰረት ናይ መጻኢ{/a} + መወዳእታታት ናይ ሕሉፍ ቀጻሊ", "መወዳእታታት፦ {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}"],
        uk: ["Умовний спосіб виражає {a}гіпотетичну, бажану або ввічливу{/a} дію.", "Утворення: {a}основа майбутнього{/a} + закінчення imparfait", "Закінчення: {a}-ais / -ais / -ait / -ions / -iez / -aient{/a}"],
      },
    },
    {
      type: "table",
      tables: [
        {
          verb: "aimer (conditionnel)",
          accentForms: true,
          rows: [
            { pronoun: "j'", form: "aimerais" },
            { pronoun: "tu", form: "aimerais" },
            { pronoun: "il / elle / on", form: "aimerait" },
            { pronoun: "nous", form: "aimerions" },
            { pronoun: "vous", form: "aimeriez" },
            { pronoun: "ils / elles", form: "aimeraient" },
          ],
        },
      ],
    },
    { type: "heading", text: "Bases irrégulières au conditionnel", sub: true, accent: true, trans: { en: "Irregular stems in the conditional", ar: "جذور شاذة في الشرطي", fa: "ریشه‌های بی‌قاعده در وجه شرطی", ti: "ዘይስሩዓት መሰረታት ኣብ ቅድመ-ኩነታዊ", uk: "Неправильні основи в умовному способі" } },
    {
      type: "grid",
      headers: ["Infinitif", "Base conditionnel", "Exemple"],
      boldFirstCol: true,
      rows: [
        ["être", "{a}ser-{/a}", "je serais"],
        ["avoir", "{a}aur-{/a}", "j'aurais"],
        ["aller", "{a}ir-{/a}", "j'irais"],
        ["faire", "{a}fer-{/a}", "je ferais"],
        ["pouvoir", "{a}pourr-{/a}", "je pourrais"],
        ["vouloir", "{a}voudr-{/a}", "je voudrais"],
        ["venir", "{a}viendr-{/a}", "je viendrais"],
        ["devoir", "{a}devr-{/a}", "je devrais"],
        ["savoir", "{a}saur-{/a}", "je saurais"],
      ],
      transHeaders: {
        en: ["Infinitive", "Conditional stem", "Example"],
        ar: ["المصدر", "جذر الشرطي", "مثال"],
        fa: ["مصدر", "ریشه‌ی شرطی", "مثال"],
        ti: ["መሰረታዊ ግሲ", "መሰረት ቅድመ-ኩነታዊ", "ኣብነት"],
        uk: ["Інфінітив", "Основа умовного способу", "Приклад"],
      },
    },
    { type: "heading", text: "Emplois du conditionnel", sub: true, accent: true, trans: { en: "Uses of the conditional", ar: "استخدامات الشرطي", fa: "کاربردهای وجه شرطی", ti: "ኣጠቓቕማ ቅድመ-ኩነታዊ", uk: "Вживання умовного способу" } },
    {
      type: "grid",
      headers: ["Usage", "Exemple"],
      boldFirstCol: true,
      rows: [
        ["Demande polie", "Je {a}voudrais{/a} un café, s'il vous plaît."],
        ["Conseil", "Tu {a}devrais{/a} consulter un médecin."],
        ["Souhait", "J'{a}aimerais{/a} voyager en Italie."],
        ["Hypothèse (si + imparfait)", "Si j'avais le temps, je {a}ferais{/a} du sport."],
        ["Information non confirmée", "Il {a}serait{/a} malade. (selon la rumeur)"],
      ],
      transHeaders: {
        en: ["Use", "Example"],
        ar: ["الاستخدام", "مثال"],
        fa: ["کاربرد", "مثال"],
        ti: ["ኣጠቓቕማ", "ኣብነት"],
        uk: ["Вживання", "Приклад"],
      },
      transRows: {
        en: [["Polite request", "Je {a}voudrais{/a} un café, s'il vous plaît. (I would like a coffee, please.)"], ["Advice", "Tu {a}devrais{/a} consulter un médecin. (You should see a doctor.)"], ["Wish", "J'{a}aimerais{/a} voyager en Italie. (I would like to travel to Italy.)"], ["Hypothesis (si + imperfect)", "Si j'avais le temps, je {a}ferais{/a} du sport. (If I had time, I would do sport.)"], ["Unconfirmed information", "Il {a}serait{/a} malade. (He is said to be ill.) (according to rumour)"]],
        ar: [["طلب مؤدّب", "Je {a}voudrais{/a} un café, s'il vous plaît. (أريد قهوة من فضلك.)"], ["نصيحة", "Tu {a}devrais{/a} consulter un médecin. (ينبغي أن ترى طبيباً.)"], ["أمنية", "J'{a}aimerais{/a} voyager en Italie. (أودّ السفر إلى إيطاليا.)"], ["افتراض (si + الماضي الناقص)", "Si j'avais le temps, je {a}ferais{/a} du sport. (لو كان لديّ وقت، لمارست الرياضة.)"], ["معلومة غير مؤكدة", "Il {a}serait{/a} malade. (يُقال إنه مريض.) (حسب الإشاعة)"]],
        fa: [["درخواست مودبانه", "Je {a}voudrais{/a} un café, s'il vous plaît. (یک قهوه می‌خواهم، لطفاً.)"], ["نصیحت", "Tu {a}devrais{/a} consulter un médecin. (باید به پزشک مراجعه کنی.)"], ["آرزو", "J'{a}aimerais{/a} voyager en Italie. (دوست دارم به ایتالیا سفر کنم.)"], ["فرض (si + ماضی استمراری)", "Si j'avais le temps, je {a}ferais{/a} du sport. (اگر وقت داشتم، ورزش می‌کردم.)"], ["اطلاعات تأیید‌نشده", "Il {a}serait{/a} malade. (گفته می‌شود او بیمار است.) (بر اساس شایعه)"]],
        ti: [["ኣኽብሮታዊ ሕቶ", "Je {a}voudrais{/a} un café, s'il vous plaît. (በጃኹም ሓደ ቡን እደሊ።)"], ["ምኽሪ", "Tu {a}devrais{/a} consulter un médecin. (ሓኪም ክትርኢ ኣለካ።)"], ["ድሌት", "J'{a}aimerais{/a} voyager en Italie. (ናብ ኢጣልያ ክገይሽ እደሊ።)"], ["ግምት (si + ሕሉፍ ቀጻሊ)", "Si j'avais le temps, je {a}ferais{/a} du sport. (ግዜ እንተዝህልወኒ፣ ስፖርት ምገበርኩ።)"], ["ዘይተረጋገጸ ሓበሬታ", "Il {a}serait{/a} malade. (ሓሚሙ ይብሃል።) (ከም ወረ)"]],
        uk: [["Ввічливе прохання", "Je {a}voudrais{/a} un café, s'il vous plaît. (Я хотів би каву, будь ласка.)"], ["Порада", "Tu {a}devrais{/a} consulter un médecin. (Тобі варто звернутися до лікаря.)"], ["Бажання", "J'{a}aimerais{/a} voyager en Italie. (Я хотів би поїхати до Італії.)"], ["Гіпотеза (si + imparfait)", "Si j'avais le temps, je {a}ferais{/a} du sport. (Якби я мав час, я б займався спортом.)"], ["Непідтверджена інформація", "Il {a}serait{/a} malade. (Кажуть, він хворий.) (за чутками)"]],
      },
    },
    {
      type: "highlight",
      label: "Politesse : impératif vs conditionnel",
      items: [
        "{a}Impératif{/a} (direct) : Donnez-moi un café !",
        "{a}Conditionnel{/a} (poli) : Je voudrais un café, s'il vous plaît.",
        "En contexte formel ou professionnel, privilégiez toujours le conditionnel.",
      ],
      transLabel: { en: "Politeness: imperative vs conditional", ar: "التأدّب: الأمر مقابل الشرطي", fa: "ادب: امری در برابر شرطی", ti: "ምኽባር፦ ትእዛዝ ኣንጻር ቅድመ-ኩነታዊ", uk: "Ввічливість: наказовий проти умовного" },
      transItems: {
        en: ["{a}Imperative{/a} (direct): Donnez-moi un café ! (Give me a coffee!)", "{a}Conditional{/a} (polite): Je voudrais un café, s'il vous plaît. (I would like a coffee, please.)", "In a formal or professional context, always prefer the conditional."],
        ar: ["{a}الأمر{/a} (مباشر): Donnez-moi un café ! (أعطني قهوة!)", "{a}الشرطي{/a} (مؤدّب): Je voudrais un café, s'il vous plaît. (أريد قهوة من فضلك.)", "في السياق الرسمي أو المهني، فضّل دائماً الشرطي."],
        fa: ["{a}امری{/a} (مستقیم): Donnez-moi un café ! (به من یک قهوه بده!)", "{a}شرطی{/a} (مودبانه): Je voudrais un café, s'il vous plaît. (یک قهوه می‌خواهم، لطفاً.)", "در بافت رسمی یا حرفه‌ای، همیشه شرطی را ترجیح دهید."],
        ti: ["{a}ትእዛዝ{/a} (ቀጥታዊ)፦ Donnez-moi un café ! (ሓደ ቡን ሃበኒ!)", "{a}ቅድመ-ኩነታዊ{/a} (ኣኽብሮታዊ)፦ Je voudrais un café, s'il vous plaît. (በጃኹም ሓደ ቡን እደሊ።)", "ኣብ ወግዓዊ ወይ ሞያዊ ኩነት፣ ኩሉ ግዜ ንቅድመ-ኩነታዊ ኣቐድሞ።"],
        uk: ["{a}Наказовий{/a} (прямий): Donnez-moi un café ! (Дайте мені каву!)", "{a}Умовний{/a} (ввічливий): Je voudrais un café, s'il vous plaît. (Я хотів би каву, будь ласка.)", "У формальному чи професійному контексті завжди надавайте перевагу умовному способу."],
      },
    },
  ],
  exercises: [
    {
      type: "fill",
      title: "Exercice 1",
      instruction: "Conjuguez le verbe au conditionnel présent.",
      items: [],
      pool: [
        { sentence: "J'___ (aimer) voyager en Italie.", hint: "aimer + -ais", answer: "aimerais" },
        { sentence: "Tu ___ (vouloir) un café, s'il te plaît ?", hint: "voudr- + -ais", answer: "voudrais" },
        { sentence: "Elle ___ (devoir) consulter un médecin.", hint: "devr- + -ait", answer: "devrait" },
        { sentence: "Nous ___ (pouvoir) partir demain.", hint: "pourr- + -ions", answer: "pourrions" },
        { sentence: "Vous ___ (préférer) aller au restaurant.", hint: "préférer + -iez", answer: "préféreriez" },
        { sentence: "Ils ___ (être) contents de vous voir.", hint: "ser- + -aient", answer: "seraient" },
        { sentence: "Je ___ (faire) du sport si j'avais le temps.", hint: "fer- + -ais", answer: "ferais" },
        { sentence: "Tu ___ (avoir) une meilleure note.", hint: "aur- + -ais", answer: "aurais" },
        { sentence: "Il ___ (venir) avec nous.", hint: "viendr- + -ait", answer: "viendrait" },
        { sentence: "Nous ___ (savoir) la réponse.", hint: "saur- + -ions", answer: "saurions" },
      ],
      poolSize: 7,
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Transformez la demande directe en demande polie au conditionnel.",
      items: [],
      pool: [
        { sentence: "Donnez-moi un café ! → Je ___ (vouloir) un café, s'il vous plaît.", hint: "voudr- + -ais", answer: "voudrais" },
        { sentence: "Aide-moi ! → Tu ___ (pouvoir) m'aider ?", hint: "pourr- + -ais", answer: "pourrais" },
        { sentence: "Dis-moi la vérité ! → Tu ___ (devoir) me dire la vérité.", hint: "devr- + -ais", answer: "devrais" },
        { sentence: "Passez-moi le sel ! → Vous ___ (pouvoir) me passer le sel ?", hint: "pourr- + -iez", answer: "pourriez" },
        { sentence: "Fais moins de bruit ! → Tu ___ (faire) moins de bruit.", hint: "fer- + -ais", answer: "ferais" },
      ],
      poolSize: 4,
    },
    {
      type: "classify",
      title: "Exercice 3",
      instruction: "Classez chaque phrase selon l'usage du conditionnel.",
      categories: ["Demande polie", "Conseil", "Souhait / rêve"],
      items: [],
      pool: [
        { word: "Je voudrais un café, s'il vous plaît.", categoryIdx: 0 },
        { word: "Tu devrais consulter un médecin.", categoryIdx: 1 },
        { word: "J'aimerais voyager en Italie.", categoryIdx: 2 },
        { word: "Vous pourriez m'aider ?", categoryIdx: 0 },
        { word: "Tu ferais mieux de te reposer.", categoryIdx: 1 },
        { word: "Nous voudrions avoir une grande maison.", categoryIdx: 2 },
        { word: "Pourriez-vous fermer la fenêtre ?", categoryIdx: 0 },
        { word: "Il devrait travailler plus sérieusement.", categoryIdx: 1 },
      ],
      poolSize: 6,
    },
    {
      type: "word_order",
      title: "Exercice 4",
      instruction: "Remettez les mots dans le bon ordre pour former une phrase au conditionnel.",
      items: [],
      pool: [
        { sentence: "Je voudrais un café, s'il vous plaît.", words: ["Je", "voudrais", "un", "café,", "s'il", "vous", "plaît."] },
        { sentence: "Tu devrais consulter un médecin.", words: ["Tu", "devrais", "consulter", "un", "médecin."] },
        { sentence: "Elle aimerait voyager en Italie.", words: ["Elle", "aimerait", "voyager", "en", "Italie."] },
        { sentence: "Vous pourriez m'aider, s'il vous plaît ?", words: ["Vous", "pourriez", "m'aider,", "s'il", "vous", "plaît", "?"] },
        { sentence: "Ils seraient contents de vous voir.", words: ["Ils", "seraient", "contents", "de", "vous", "voir."] },
      ],
      poolSize: 4,
    },
    {
      type: "color_highlight",
      title: "Exercice 5",
      instruction: "Sélectionnez une couleur, puis identifiez les verbes au conditionnel dans chaque phrase.",
      colors: ["Conditionnel"],
      items: [
        {
          words: ["Je", "voudrais", "un", "café,", "s'il", "vous", "plaît."],
          answers: [null, 0, null, null, null, null, null],
        },
        {
          words: ["Tu", "devrais", "consulter", "un", "médecin."],
          answers: [null, 0, null, null, null],
        },
        {
          words: ["Ils", "seraient", "contents", "et", "elle", "viendrait", "aussi."],
          answers: [null, 0, null, null, null, 0, null],
        },
      ],
    },
    {
      type: "write",
      title: "Exercice 6",
      instruction: "Écrivez une demande polie ou un souhait au conditionnel.\nCommencez par « Je voudrais… », « Tu pourrais… » ou « J'aimerais… ».",
      verbPool: ["vouloir", "pouvoir", "aimer", "devoir", "préférer", "faire"],
      verbPoolSize: 2,
    },
  ],
};
