import type { GrammarLesson } from "../../grammar-data";

export const A1_GR_INTERRO: GrammarLesson = {
  slug: "a1-gr-interro",
  code: "G.8",
  level: "A1",
  title: "L'interrogation de base",
  theory: [
    { type: "heading", text: "Poser une question", trans: { en: "Asking a question", ar: "طرح سؤال", fa: "پرسیدن سوال", ti: "ሕቶ ምሓታት", uk: "Постановка питання" } },
    {
      type: "plain_list",
      items: [
        "Il y a plusieurs façons de poser une question en français.",
        "La plus simple : monter la voix à la fin.",
        "La plus courante : utiliser {a}est-ce que{/a}.",
      ],
      transItems: {
        en: ["There are several ways to ask a question in French.", "The simplest: raise your voice at the end.", "The most common: use {a}est-ce que{/a}."],
        ar: ["هناك عدة طرق لطرح سؤال بالفرنسية.", "الأبسط: رفع الصوت في النهاية.", "الأكثر شيوعاً: استخدام {a}est-ce que{/a}."],
        fa: ["روش‌های مختلفی برای پرسیدن سوال در فرانسه وجود دارد.", "ساده‌ترین: بالا بردن صدا در پایان.", "رایج‌ترین: استفاده از {a}est-ce que{/a}."],
        ti: ["ኣብ ፈረንሳዊ ሕቶ ንምሓታት ብዙሕ መንገድታት ኣሎ.", "ዝቐለለ: ድምጺ ኣብ መወዳእታ ምድራዕ.", "ዝበዝሐ: {a}est-ce que{/a} ምጥቃም."],
        uk: ["Є кілька способів поставити питання французькою.", "Найпростіший: підвищити голос наприкінці.", "Найпоширеніший: використовувати {a}est-ce que{/a}."],
      },
    },
    {
      type: "plain_list",
      items: [
        "{a}Est-ce que{/a} + sujet + verbe ?",
        "Devant une voyelle : {a}est-ce qu'{/a}",
      ],
      transItems: {
        en: ["{a}Est-ce que{/a} + subject + verb ?", "Before a vowel: {a}est-ce qu'{/a}"],
        ar: ["{a}Est-ce que{/a} + الفاعل + الفعل ?", "قبل حرف علة: {a}est-ce qu'{/a}"],
        fa: ["{a}Est-ce que{/a} + فاعل + فعل ?", "قبل از حرف صدادار: {a}est-ce qu'{/a}"],
        ti: ["{a}Est-ce que{/a} + ሓካይ + ግሲ ?", "ቅድሚ ሞዓዝ: {a}est-ce qu'{/a}"],
        uk: ["{a}Est-ce que{/a} + підмет + дієслово ?", "Перед голосною: {a}est-ce qu'{/a}"],
      },
    },
    {
      type: "grid",
      headers: ["Affirmatif", "Question"],
      rows: [
        ["Tu parles français.", "Est-ce que tu parles français ?"],
        ["Il est libre.", "Est-ce qu'il est libre ?"],
        ["Elle a cours.", "Est-ce qu'elle a cours ?"],
        ["Vous êtes prêts.", "Est-ce que vous êtes prêts ?"],
      ],
      transHeaders: {
        en: ["Affirmative", "Question"],
        ar: ["الإيجاب", "السؤال"],
        fa: ["مثبت", "سوال"],
        ti: ["ኣወንታ", "ሕቶ"],
        uk: ["Стверджувальна", "Питання"],
      },
      transRows: {
        en: [["You speak French.", "Do you speak French?"], ["He is free.", "Is he free?"], ["She has class.", "Does she have class?"], ["You are ready.", "Are you ready?"]],
        ar: [["تتكلم الفرنسية.", "هل تتكلم الفرنسية؟"], ["هو حر.", "هل هو حر؟"], ["هي لديها دروس.", "هل لديها دروس؟"], ["أنتم مستعدون.", "هل أنتم مستعدون؟"]],
        fa: [["تو فرانسه صحبت می‌کنی.", "آیا فرانسه صحبت می‌کنی؟"], ["او آزاد است.", "آیا او آزاد است؟"], ["او کلاس دارد.", "آیا او کلاس دارد؟"], ["شما آماده‌اید.", "آیا آماده‌اید؟"]],
        ti: [["ፈረንሳዊ ትዛረብ.", "ፈረንሳዊ ትዛረብ ዶ?"], ["ናጻ እዩ.", "ናጻ ዶ እዩ?"], ["ትምህርቲ ኣሎዋ.", "ትምህርቲ ኣሎዋ ዶ?"], ["ቅሩባት ኢኹም.", "ቅሩባት ዶ ኢኹም?"]],
        uk: [["Ти говориш французькою.", "Ти говориш французькою?"], ["Він вільний.", "Він вільний?"], ["У неї заняття.", "У неї заняття?"], ["Ви готові.", "Ви готові?"]],
      },
    },
    {
      type: "highlight",
      label: "Intonation montante",
      transLabel: { en: "Rising intonation", ar: "التنغيم الصاعد", fa: "آهنگ صعودی", ti: "ዝልዓለ ቃና", uk: "Висхідна інтонація" },
      items: [
        "Pour une question très simple, on monte la voix à la fin.",
        "Tu parles français ?",
        "Il est libre ?",
      ],
      transItems: {
        en: ["For a very simple question, raise your voice at the end.", "You speak French?", "He is free?"],
        ar: ["لسؤال بسيط جداً، ارفع صوتك في النهاية.", "تتكلم الفرنسية؟", "هو حر؟"],
        fa: ["برای یک سوال بسیار ساده، صدای خود را در پایان بالا ببرید.", "فرانسه صحبت می‌کنی؟", "او آزاد است؟"],
        ti: ["ንሓደ ቀሊል ሕቶ ድምጺ ኣብ መወዳእታ ኣልዕሎ.", "ፈረንሳዊ ትዛረብ?", "ናጻ እዩ?"],
        uk: ["Для дуже простого питання підвищте голос наприкінці.", "Ти говориш французькою?", "Він вільний?"],
      },
      noBulletItems: [0],
    },
  ],
  exercises: [
    // ── Exercise 1 — QCM toggle: Affirmative / Interrogative ─────────────────
    {
      type: "qcm",
      title: "Exercice 1",
      instruction: "Sélectionnez la forme de la phrase.",
      toggleChoices: true,
      items: [],
      pool: [
        // être — affirmative
        { sentence: "Je suis content.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Tu es à l'école.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Il est médecin.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elle est fatiguée.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Nous sommes en France.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Vous êtes en retard.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Ils sont heureux.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elles sont ici.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        // être — interrogative
        { sentence: "Est-ce que tu es content ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'il est à l'école ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elle est médecin ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que nous sommes en retard ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que vous êtes prêts ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'ils sont ici ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elle est fatiguée ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        // avoir — affirmative
        { sentence: "J'ai faim.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Tu as raison.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Il a soif.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elle a peur.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Nous avons chaud.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Vous avez tort.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Ils ont froid.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elles ont envie.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        // avoir — interrogative
        { sentence: "Est-ce que tu as faim ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'il a raison ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elle a soif ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que vous avez peur ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'ils ont chaud ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que nous avons tort ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elles ont froid ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        // -er — affirmative
        { sentence: "Je parle français.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Tu aimes la musique.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Il travaille beaucoup.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elle chante bien.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Nous mangeons ensemble.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Vous regardez la télé.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Ils jouent au foot.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        { sentence: "Elles dansent souvent.", choices: ["Affirmative", "Interrogative"], correctIdx: 0 },
        // -er — interrogative
        { sentence: "Est-ce que tu parles français ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'il aime la musique ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elle travaille beaucoup ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que vous chantez bien ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce que nous mangeons ensemble ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'ils regardent la télé ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
        { sentence: "Est-ce qu'elles jouent au foot ?", choices: ["Affirmative", "Interrogative"], correctIdx: 1 },
      ],
      poolSize: 8,
    },
    // ── Exercise 2 — Fill: Mettez à la forme interrogative ───────────────────
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Transformez la phrase en question avec « Est-ce que » ou « Est-ce qu' ».",
      items: [],
      pool: [
        // être (15)
        { sentence: "Tu es content. → ___ tu es content ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il est à l'école. → ___ il est à l'école ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle est médecin. → ___ elle est médecin ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous sommes en retard. → ___ nous sommes en retard ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous êtes prêts. → ___ vous êtes prêts ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils sont heureux. → ___ ils sont heureux ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles sont fatiguées. → ___ elles sont fatiguées ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Je suis libre. → ___ je suis libre ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Tu es à la maison. → ___ tu es à la maison ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il est absent. → ___ il est absent ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle est contente. → ___ elle est contente ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous sommes prêts. → ___ nous sommes prêts ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous êtes en vacances. → ___ vous êtes en vacances ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils sont là. → ___ ils sont là ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles sont ici. → ___ elles sont ici ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        // avoir (15)
        { sentence: "Tu as faim. → ___ tu as faim ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il a raison. → ___ il a raison ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle a soif. → ___ elle a soif ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous avons peur. → ___ nous avons peur ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous avez tort. → ___ vous avez tort ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils ont froid. → ___ ils ont froid ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles ont chaud. → ___ elles ont chaud ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Tu as sommeil. → ___ tu as sommeil ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il a honte. → ___ il a honte ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle a de la chance. → ___ elle a de la chance ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous avons le temps. → ___ nous avons le temps ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous avez confiance. → ___ vous avez confiance ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils ont faim. → ___ ils ont faim ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles ont raison. → ___ elles ont raison ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "J'ai envie. → ___ j'ai envie ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        // -er verbs (15)
        { sentence: "Tu parles français. → ___ tu parles français ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il aime la musique. → ___ il aime la musique ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle travaille beaucoup. → ___ elle travaille beaucoup ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous mangeons ensemble. → ___ nous mangeons ensemble ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous regardez la télé. → ___ vous regardez la télé ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils jouent au foot. → ___ ils jouent au foot ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles dansent souvent. → ___ elles dansent souvent ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Je travaille ici. → ___ je travaille ici ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Tu écoutes la radio. → ___ tu écoutes la radio ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Il habite à Paris. → ___ il habite à Paris ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elle chante le matin. → ___ elle chante le matin ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Nous habitons ici. → ___ nous habitons ici ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Vous aimez le sport. → ___ vous aimez le sport ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce que" },
        { sentence: "Ils parlent anglais. → ___ ils parlent anglais ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
        { sentence: "Elles mangent ensemble. → ___ elles mangent ensemble ?", hint: "Est-ce que / Est-ce qu'", answer: "Est-ce qu'" },
      ],
      poolSize: 8,
    },
    // ── Exercise 3 — Classify: S / V / C (phrases interrogatives) ────────────
    {
      type: "classify",
      title: "Exercice 3",
      instruction: "Classez chaque mot ou groupe en gras dans la bonne catégorie.",
      categories: ["Sujet", "Verbe", "Complément"],
      items: [],
      pool: [
        { word: "Est-ce que {a}tu{/a} parles français ?", categoryIdx: 0 },
        { word: "Est-ce que tu {a}parles{/a} français ?", categoryIdx: 1 },
        { word: "Est-ce que tu parles {a}français{/a} ?", categoryIdx: 2 },
        { word: "Est-ce qu'{a}il{/a} est médecin ?", categoryIdx: 0 },
        { word: "Est-ce qu'il {a}est{/a} médecin ?", categoryIdx: 1 },
        { word: "Est-ce qu'il est {a}médecin{/a} ?", categoryIdx: 2 },
        { word: "Est-ce que {a}nous{/a} avons faim ?", categoryIdx: 0 },
        { word: "Est-ce que nous {a}avons{/a} faim ?", categoryIdx: 1 },
        { word: "Est-ce que nous avons {a}faim{/a} ?", categoryIdx: 2 },
        { word: "Est-ce qu'{a}elle{/a} habite à Paris ?", categoryIdx: 0 },
        { word: "Est-ce qu'elle {a}habite{/a} à Paris ?", categoryIdx: 1 },
        { word: "Est-ce qu'elle habite {a}à Paris{/a} ?", categoryIdx: 2 },
        { word: "Est-ce que {a}vous{/a} mangez ensemble ?", categoryIdx: 0 },
        { word: "Est-ce que vous {a}mangez{/a} ensemble ?", categoryIdx: 1 },
        { word: "Est-ce que vous mangez {a}ensemble{/a} ?", categoryIdx: 2 },
      ],
      poolSize: 6,
    },
    // ── Exercise 4 — Word order (phrases interrogatives) ─────────────────────
    {
      type: "word_order",
      title: "Exercice 4",
      instruction: "Remettez les mots dans le bon ordre pour former une question correcte.",
      items: [
        {
          sentence: "Est-ce que tu parles français ?",
          words: ["Est-ce que", "tu", "parles", "français"],
        },
        {
          sentence: "Est-ce qu'elle est médecin ?",
          words: ["Est-ce qu'", "elle", "est", "médecin"],
        },
        {
          sentence: "Est-ce que nous avons faim ?",
          words: ["Est-ce que", "nous", "avons", "faim"],
        },
      ],
    },
    // ── Exercise 5 — Color highlight (phrases interrogatives) ────────────────
    {
      type: "color_highlight",
      title: "Exercice 5",
      instruction: "Sélectionnez une couleur, puis cliquez sur chaque mot pour l'identifier : Sujet (jaune), Verbe (rouge), Complément (vert).",
      colors: ["Sujet", "Verbe", "Complément"],
      items: [
        {
          words: ["Est-ce que", "tu", "parles", "français", "?"],
          answers: [null, 0, 1, 2, null],
        },
        {
          words: ["Est-ce qu'", "il", "est", "médecin", "?"],
          answers: [null, 0, 1, 2, null],
        },
        {
          words: ["Est-ce que", "nous", "avons", "faim", "?"],
          answers: [null, 0, 1, 2, null],
        },
      ],
    },
    // ── Exercise 6 — Write interrogative sentence with given verb ─────────────
    {
      type: "write",
      title: "Exercice 6",
      instruction: "Écrivez une question avec le verbe proposé en utilisant « Est-ce que ».\nLa phrase doit avoir un sujet et un verbe conjugué.\nElle commence par « Est-ce que » et se termine par un point d'interrogation (?).",
      verbPool: [
        "parler", "manger", "habiter", "aimer", "écouter",
        "regarder", "travailler", "chanter", "danser", "jouer",
        "chercher", "marcher", "oublier", "penser", "porter",
        "rester", "tomber", "voyager", "arriver", "préparer",
        "cuisiner", "dessiner", "laver", "rentrer", "nager",
      ],
      verbPoolSize: 5,
    },
  ],
};
