import type { GrammarLesson } from "../../grammar-data";

export const A1_GR_L01: GrammarLesson = {
  slug: "a1-gr-l01",
  code: "R1.1",
  level: "A1",
  title: "Pronoms sujets et le verbe être",
  theory: [
    { type: "heading", text: "Les pronoms sujets", trans: { en: "Subject pronouns", ar: "ضمائر الفاعل", fa: "ضمایر فاعلی", ti: "ናይ ርእሲ ጸጋ ቃላት", uk: "Особові займенники" } },
    {
      type: "table",
      tables: [
        {
          verb: "être",
          rows: [
            { pronoun: "je", form: "suis" },
            { pronoun: "tu", form: "es" },
            { pronoun: "il / elle", form: "est" },
            { pronoun: "nous", form: "sommes" },
            { pronoun: "vous", form: "êtes" },
            { pronoun: "ils / elles", form: "sont" },
          ],
        },
      ],
    },
    {
      type: "rule",
      text: "J'utilise ÊTRE pour la nationalité, la profession ou un adjectif.",
      examples: [
        { correct: "Je suis française." },
        { correct: "Il est professeur." },
        { correct: "Nous sommes étudiants." },
      ],
    },
    {
      type: "rule",
      text: "TU = informel (amis, famille) ; VOUS = formel ou pluriel.",
      examples: [
        { correct: "Salut ! Tu es française ? (informel)" },
        { correct: "Bonjour Madame, vous êtes française ? (formel)" },
      ],
    },
    {
      type: "note",
      text: "s'appeler : je m'appelle, tu t'appelles, il/elle s'appelle, nous nous appelons, vous vous appelez, ils/elles s'appellent",
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Pronoms et être",
      instruction: "Choisissez la forme correcte de ÊTRE.",
      transInstruction: { en: "Choose the correct form of ÊTRE (to be).", ar: "اختر الصيغة الصحيحة للفعل ÊTRE (يكون).", fa: "صورت درست فعل ÊTRE (بودن) را انتخاب کنید.", ti: "ምረጽ ቅኑዕ ቅርጺ ናይ ÊTRE (ምዃን).", uk: "Виберіть правильну форму ÊTRE (бути)." },
      items: [],
      poolSize: 5,
      pool: [
        // A1 — simple, présent, vocabulaire très fréquent
        { sentence: "Je ___ étudiant.", choices: ["suis", "est", "es", "sommes"], correctIdx: 0 },
        { sentence: "Tu ___ content(e) ?", choices: ["es", "est", "suis", "sont"], correctIdx: 0 },
        { sentence: "Elle ___ française.", choices: ["est", "suis", "es", "êtes"], correctIdx: 0 },
        { sentence: "Nous ___ en retard.", choices: ["sommes", "êtes", "suis", "est"], correctIdx: 0 },
        { sentence: "Ils ___ absents.", choices: ["sont", "est", "suis", "sommes"], correctIdx: 0 },
        { sentence: "Vous ___ prêts ?", choices: ["êtes", "sont", "suis", "est"], correctIdx: 0 },
        { sentence: "Il ___ médecin.", choices: ["est", "suis", "êtes", "sont"], correctIdx: 0 },
        { sentence: "Tu ___ algérien(ne) ?", choices: ["es", "est", "suis", "sont"], correctIdx: 0 },
        { sentence: "Elles ___ absentes.", choices: ["sont", "est", "suis", "êtes"], correctIdx: 0 },
        { sentence: "Je ___ à Paris.", choices: ["suis", "est", "êtes", "sont"], correctIdx: 0 },
        // A2 — contexte plus riche, deux informations liées
        { sentence: "Mon frère ___ très sportif.", choices: ["est", "suis", "sommes", "êtes"], correctIdx: 0 },
        { sentence: "Nous ___ contents parce que l'examen est fini.", choices: ["sommes", "êtes", "suis", "sont"], correctIdx: 0 },
        { sentence: "Tu ___ fatiguée parce que tu travailles beaucoup.", choices: ["es", "est", "suis", "sont"], correctIdx: 0 },
        { sentence: "Vous ___ tous les deux étudiants en médecine.", choices: ["êtes", "sont", "suis", "est"], correctIdx: 0 },
        { sentence: "Il ___ souvent absent le lundi.", choices: ["est", "suis", "es", "êtes"], correctIdx: 0 },
        { sentence: "Elles ___ très heureuses de voir leurs amis.", choices: ["sont", "est", "suis", "êtes"], correctIdx: 0 },
        { sentence: "Je ___ né(e) en Afghanistan.", choices: ["suis", "est", "es", "êtes"], correctIdx: 0 },
        { sentence: "On ___ tous ensemble aujourd'hui.", choices: ["est", "suis", "es", "êtes"], correctIdx: 0 },
        { sentence: "Elle ___ infirmière dans un grand hôpital.", choices: ["est", "suis", "es", "sont"], correctIdx: 0 },
        { sentence: "Nous ___ de nationalité érythréenne.", choices: ["sommes", "êtes", "suis", "est"], correctIdx: 0 },
        // B1 — plus longue, vocabulaire précis, connecteurs variés
        { sentence: "Nous ___ convaincus que la formation est importante.", choices: ["sommes", "êtes", "suis", "sont"], correctIdx: 0 },
        { sentence: "Ils ___ originaires du Congo mais ils habitent à Genève.", choices: ["sont", "est", "suis", "êtes"], correctIdx: 0 },
        { sentence: "Tu ___ la seule personne qui comprend ma situation.", choices: ["es", "est", "suis", "sont"], correctIdx: 0 },
        { sentence: "Je ___ persuadé(e) que cette opportunité est unique.", choices: ["suis", "est", "es", "sont"], correctIdx: 0 },
        { sentence: "Vous ___ invités à participer à la réunion.", choices: ["êtes", "sont", "suis", "est"], correctIdx: 0 },
        { sentence: "Elle ___ reconnue pour son travail exceptionnel.", choices: ["est", "suis", "es", "sont"], correctIdx: 0 },
        { sentence: "Ils ___ déterminés à réussir malgré les difficultés.", choices: ["sont", "est", "suis", "êtes"], correctIdx: 0 },
        { sentence: "Je ___ ravi(e) de vous rencontrer dans ce contexte.", choices: ["suis", "est", "es", "sont"], correctIdx: 0 },
        { sentence: "Nous ___ heureux que les efforts portent leurs fruits.", choices: ["sommes", "êtes", "suis", "est"], correctIdx: 0 },
        { sentence: "On ___ tous responsables de notre avenir.", choices: ["est", "suis", "es", "sont"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Complétez avec être ou s'appeler",
      instruction: "Conjuguez le verbe entre parenthèses.",
      transInstruction: { en: "Conjugate the verb in parentheses.", ar: "صرّف الفعل الموجود بين القوسين.", fa: "فعل داخل پرانتز را صرف کنید.", ti: "ኣብ ቅንፍ ዘሎ ግሲ ኣጻርይ.", uk: "Відмінюйте дієслово в дужках." },
      items: [],
      poolSize: 5,
      pool: [
        // A1 — phrases très courtes, verbes de base
        { sentence: "Je ___ (être) étudiant.", hint: "être → je", answer: "suis" },
        { sentence: "Tu ___ (être) français(e) ?", hint: "être → tu", answer: "es" },
        { sentence: "Il ___ (s'appeler) Paulo.", hint: "s'appeler → il", answer: "s'appelle" },
        { sentence: "Nous ___ (être) à Lyon.", hint: "être → nous", answer: "sommes" },
        { sentence: "Vous ___ (être) prêts ?", hint: "être → vous", answer: "êtes" },
        { sentence: "Elles ___ (être) contentes.", hint: "être → elles", answer: "sont" },
        { sentence: "Je ___ (s'appeler) Leila.", hint: "s'appeler → je", answer: "m'appelle" },
        { sentence: "Tu ___ (s'appeler) comment ?", hint: "s'appeler → tu", answer: "t'appelles" },
        { sentence: "Il ___ (être) belge.", hint: "être → il", answer: "est" },
        { sentence: "Ils ___ (être) absents.", hint: "être → ils", answer: "sont" },
        // A2 — contexte quotidien, informations liées
        { sentence: "Nous ___ (s'appeler) Ahmed et Khalil.", hint: "s'appeler → nous", answer: "nous appelons" },
        { sentence: "Tu ___ (être) content parce que l'examen est fini.", hint: "être → tu", answer: "es" },
        { sentence: "Elle ___ (s'appeler) Amina et elle est médecin.", hint: "s'appeler → elle", answer: "s'appelle" },
        { sentence: "Il ___ (être) souvent en retard le matin.", hint: "être → il", answer: "est" },
        { sentence: "Vous ___ (s'appeler) comment, madame ?", hint: "s'appeler → vous", answer: "vous appelez" },
        { sentence: "Je ___ (être) de nationalité érythréenne.", hint: "être → je", answer: "suis" },
        { sentence: "Ils ___ (être) tous les deux très travailleurs.", hint: "être → ils", answer: "sont" },
        { sentence: "Tu ___ (s'appeler) vraiment Marc ?", hint: "s'appeler → tu", answer: "t'appelles" },
        { sentence: "On ___ (être) ensemble depuis longtemps.", hint: "être → on", answer: "est" },
        { sentence: "Elle ___ (être) disponible chaque soir.", hint: "être → elle", answer: "est" },
        // B1 — plus longue, vocabulaire précis, proposition relative possible
        { sentence: "Je ___ (s'appeler) Sonia et je travaille dans le domaine de la santé.", hint: "s'appeler → je", answer: "m'appelle" },
        { sentence: "Nous ___ (être) persuadés que l'intégration est possible.", hint: "être → nous", answer: "sommes" },
        { sentence: "Tu ___ (être) capable de réussir si tu travailles régulièrement.", hint: "être → tu", answer: "es" },
        { sentence: "Ils ___ (s'appeler) Viktor et Iryna et ils viennent d'Ukraine.", hint: "s'appeler → ils", answer: "s'appellent" },
        { sentence: "Elle ___ (être) reconnue pour ses compétences professionnelles.", hint: "être → elle", answer: "est" },
        { sentence: "Vous ___ (être) invités à présenter votre projet demain.", hint: "être → vous", answer: "êtes" },
        { sentence: "On ___ (s'appeler) par nos prénoms dans cette équipe.", hint: "s'appeler → on", answer: "s'appelle" },
        { sentence: "Ils ___ (être) déterminés à trouver une solution durable.", hint: "être → ils", answer: "sont" },
        { sentence: "Je ___ (être) ravi(e) de faire partie de cette association.", hint: "être → je", answer: "suis" },
        { sentence: "Tu ___ (s'appeler) différemment dans ta langue d'origine ?", hint: "s'appeler → tu", answer: "t'appelles" },
      ],
    },
  ],
};
