import type { GrammarLesson } from "../../grammar-data";

/** Unité 2 — Le verbe avoir (G1.3) */
export const A1_GR_AVOIR: GrammarLesson = {
  slug: "a1-gr-avoir",
  code: "G1.3",
  level: "A1",
  title: "Le verbe avoir",
  theory: [
    {
      type: "heading",
      text: "Utilisation",
      trans: { en: "Usage", ar: "الاستخدام", fa: "کاربرد", ti: "ኣጠቓቕማ", uk: "Вживання" },
    },
    {
      type: "plain_list",
      items: [
        "Le verbe AVOIR sert à dire l'âge, de parler de la famille et des amis, de dire ce qu'on possède ou d'exprimer une sensation.",
      ],
      transItems: {
        en: ["The verb AVOIR is used to state age, talk about family and friends, say what one owns, or express a sensation."],
        ar: ["يُستخدم الفعل AVOIR لذكر العمر، والتحدث عن العائلة والأصدقاء، وقول ما نملكه، أو التعبير عن إحساس."],
        fa: ["فعل AVOIR برای بیان سن، صحبت دربارهٔ خانواده و دوستان، گفتن آنچه در اختیار داریم یا بیان یک احساس به کار می‌رود."],
        ti: ["ግሲ AVOIR ዕድመ ንምግላጽ፣ ብዛዕባ ስድራቤትን ኣዕሩኽን ንምዝራብ፣ ዘለና ነገር ንምግላጽ ወይ ስምዒት ንምግላጽ ይጥቀም።"],
        uk: ["Дієслово AVOIR вживається, щоб назвати вік, розповісти про сім'ю та друзів, сказати, чим хтось володіє, або висловити відчуття."],
      },
    },
    {
      type: "heading",
      text: "Exemple",
      sub: true,
      accent: true,
      trans: { en: "Example", ar: "مثال", fa: "مثال", ti: "ኣብነት", uk: "Приклад" },
    },
    {
      type: "grid",
      headers: ["", "Exemple"],
      transHeaders: {
        en: ["", "Example"],
        ar: ["", "مثال"],
        fa: ["", "مثال"],
        ti: ["", "ኣብነት"],
        uk: ["", "Приклад"],
      },
      boldFirstCol: true,
      rows: [
        ["Possession", "J'{a}ai{/a} un téléphone."],
        ["Âge", "Elle {a}a{/a} 25 ans."],
        ["Sensations", "Nous {a}avons{/a} faim."],
        ["Expressions", "Il {a}a{/a} de la chance."],
      ],
      transRows: {
        en: [["Possession", "J'{a}ai{/a} un téléphone."], ["Age", "Elle {a}a{/a} 25 ans."], ["Sensations", "Nous {a}avons{/a} faim."], ["Expressions", "Il {a}a{/a} de la chance."]],
        ar: [["الملكية", "J'{a}ai{/a} un téléphone."], ["العمر", "Elle {a}a{/a} 25 ans."], ["الأحاسيس", "Nous {a}avons{/a} faim."], ["التعبيرات", "Il {a}a{/a} de la chance."]],
        fa: [["مالکیت", "J'{a}ai{/a} un téléphone."], ["سن", "Elle {a}a{/a} 25 ans."], ["احساس‌ها", "Nous {a}avons{/a} faim."], ["عبارت‌ها", "Il {a}a{/a} de la chance."]],
        ti: [["ዋንነት", "J'{a}ai{/a} un téléphone."], ["ዕድመ", "Elle {a}a{/a} 25 ans."], ["ስምዒታት", "Nous {a}avons{/a} faim."], ["መግለጺታት", "Il {a}a{/a} de la chance."]],
        uk: [["Володіння", "J'{a}ai{/a} un téléphone."], ["Вік", "Elle {a}a{/a} 25 ans."], ["Відчуття", "Nous {a}avons{/a} faim."], ["Вирази", "Il {a}a{/a} de la chance."]],
      },
    },
    {
      type: "heading",
      text: "Conjugaison",
      trans: { en: "Conjugation", ar: "التصريف", fa: "صرف", ti: "ምጽራይ", uk: "Дієвідміна" },
    },
    {
      type: "grid",
      headers: ["Pronom sujet", "Verbe", "Exemple"],
      transHeaders: {
        en: ["Subject pronoun", "Verb", "Example"],
        ar: ["ضمير الفاعل", "الفعل", "مثال"],
        fa: ["ضمیر فاعلی", "فعل", "مثال"],
        ti: ["ተካኢ ስም ተግባሪ", "ግሲ", "ኣብነት"],
        uk: ["Займенник-підмет", "Дієслово", "Приклад"],
      },
      boldFirstCol: true,
      rows: [
        ["J'", "ai", "une sœur."],
        ["Tu", "as", "30 ans."],
        ["Il / Elle / On", "a", "faim."],
        ["Nous", "avons", "un chat."],
        ["Vous", "avez", "quel âge ?"],
        ["Ils / Elles", "ont", "chaud."],
      ],
    },
    {
      type: "heading",
      text: "Prononciation et orthographe",
      trans: { en: "Pronunciation and spelling", ar: "النطق والإملاء", fa: "تلفظ و املا", ti: "ኣደማምጻን ኣጸሓሕፋን", uk: "Вимова та правопис" },
    },
    {
      type: "plain_list",
      items: ["{a}1.{/a} On ne prononce pas le {a}e{/a} final de {a}elle{/a}."],
      transItems: {
        en: ["{a}1.{/a} The final {a}e{/a} in {a}elle{/a} is not pronounced."],
        ar: ["{a}1.{/a} لا يُنطق حرف {a}e{/a} الأخير في {a}elle{/a}."],
        fa: ["{a}1.{/a} حرف {a}e{/a} پایانی در {a}elle{/a} تلفظ نمی‌شود."],
        ti: ["{a}1.{/a} እቲ ናይ መወዳእታ {a}e{/a} ኣብ {a}elle{/a} ኣይድመጽን።"],
        uk: ["{a}1.{/a} Кінцева літера {a}e{/a} у слові {a}elle{/a} не вимовляється."],
      },
    },
    {
      type: "plain_list",
      items: ["{a}2.{/a} On fait la liaison."],
      transItems: {
        en: ["{a}2.{/a} A liaison is made."],
        ar: ["{a}2.{/a} نقوم بالوصل الصوتي."],
        fa: ["{a}2.{/a} پیوند آوایی انجام می‌شود."],
        ti: ["{a}2.{/a} ምትእስሳር ድምጺ ንገብር።"],
        uk: ["{a}2.{/a} Робимо зв'язування звуків (liaison)."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: ["O{li}n|a{/li}, nou{li}s|a{/li}vons, vou{li}s|a{/li}vez, il{li}s|o{/li}nt, elle{li}s|o{/li}nt."],
      noBulletItems: [0],
    },
    {
      type: "plain_list",
      items: ["{a}3.{/a} Le pronom {a}je{/a} devient {a}j'{/a} devant une voyelle."],
      transItems: {
        en: ["{a}3.{/a} The pronoun {a}je{/a} becomes {a}j'{/a} before a vowel."],
        ar: ["{a}3.{/a} يتحول الضمير {a}je{/a} إلى {a}j'{/a} قبل حرف متحرك."],
        fa: ["{a}3.{/a} ضمیر {a}je{/a} پیش از یک حرف صدادار به {a}j'{/a} تبدیل می‌شود."],
        ti: ["{a}3.{/a} ተካኢ ስም {a}je{/a} ቅድሚ ኣድማጺ ፊደል ናብ {a}j'{/a} ይቕየር።"],
        uk: ["{a}3.{/a} Перед голосною займенник {a}je{/a} перетворюється на {a}j'{/a}."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: ["{s}Je ai{/s} → {a}J'ai{/a} 20 ans."],
      noBulletItems: [0],
      inlineArrows: true,
    },
    {
      type: "heading",
      text: "Expressions avec AVOIR",
      trans: { en: "Expressions with AVOIR", ar: "تعبيرات مع AVOIR", fa: "عبارت‌های همراه با AVOIR", ti: "መግለጺታት ምስ AVOIR", uk: "Вирази з AVOIR" },
    },
    {
      type: "grid",
      headers: ["Expression", "Signification"],
      transHeaders: {
        en: ["Expression", "Meaning"],
        ar: ["التعبير", "المعنى"],
        fa: ["عبارت", "معنی"],
        ti: ["መግለጺ", "ትርጉም"],
        uk: ["Вираз", "Значення"],
      },
      equalCols: true,
      rows: [
        ["{a}Avoir faim{/a}", "vouloir manger"],
        ["{a}Avoir soif{/a}", "vouloir boire"],
        ["{a}Avoir froid{/a}", "ressentir le froid"],
        ["{a}Avoir chaud{/a}", "ressentir la chaleur"],
        ["{a}Avoir peur{/a}", "être effrayé(e)"],
        ["{a}Avoir mal{/a}", "ressentir une douleur"],
        ["{a}Avoir raison{/a}", "être correct(e)"],
        ["{a}Avoir tort{/a}", "se tromper"],
      ],
      transRows: {
        en: [["{a}Avoir faim{/a}", "to want to eat"], ["{a}Avoir soif{/a}", "to want to drink"], ["{a}Avoir froid{/a}", "to feel cold"], ["{a}Avoir chaud{/a}", "to feel hot"], ["{a}Avoir peur{/a}", "to be afraid"], ["{a}Avoir mal{/a}", "to feel pain"], ["{a}Avoir raison{/a}", "to be right"], ["{a}Avoir tort{/a}", "to be wrong"]],
        ar: [["{a}Avoir faim{/a}", "الرغبة في الأكل"], ["{a}Avoir soif{/a}", "الرغبة في الشرب"], ["{a}Avoir froid{/a}", "الشعور بالبرد"], ["{a}Avoir chaud{/a}", "الشعور بالحر"], ["{a}Avoir peur{/a}", "الشعور بالخوف"], ["{a}Avoir mal{/a}", "الشعور بالألم"], ["{a}Avoir raison{/a}", "أن يكون المرء محقًا"], ["{a}Avoir tort{/a}", "أن يكون المرء مخطئًا"]],
        fa: [["{a}Avoir faim{/a}", "میل به غذا خوردن"], ["{a}Avoir soif{/a}", "میل به نوشیدن"], ["{a}Avoir froid{/a}", "احساس سرما کردن"], ["{a}Avoir chaud{/a}", "احساس گرما کردن"], ["{a}Avoir peur{/a}", "ترسیدن"], ["{a}Avoir mal{/a}", "احساس درد کردن"], ["{a}Avoir raison{/a}", "حق داشتن"], ["{a}Avoir tort{/a}", "اشتباه کردن"]],
        ti: [["{a}Avoir faim{/a}", "ክትበልዕ ምድላይ"], ["{a}Avoir soif{/a}", "ክትሰቲ ምድላይ"], ["{a}Avoir froid{/a}", "ቁሪ ምስማዕ"], ["{a}Avoir chaud{/a}", "ሙቐት ምስማዕ"], ["{a}Avoir peur{/a}", "ምፍራሕ"], ["{a}Avoir mal{/a}", "ቃንዛ ምስማዕ"], ["{a}Avoir raison{/a}", "ቅኑዕ ምዃን"], ["{a}Avoir tort{/a}", "ምግጋይ"]],
        uk: [["{a}Avoir faim{/a}", "хотіти їсти"], ["{a}Avoir soif{/a}", "хотіти пити"], ["{a}Avoir froid{/a}", "відчувати холод"], ["{a}Avoir chaud{/a}", "відчувати спеку"], ["{a}Avoir peur{/a}", "боятися"], ["{a}Avoir mal{/a}", "відчувати біль"], ["{a}Avoir raison{/a}", "мати рацію"], ["{a}Avoir tort{/a}", "помилятися"]],
      },
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Conjugaison d'avoir",
      instruction: "Choisissez la forme correcte du verbe avoir.",
      transInstruction: {
        en: "Choose the correct form of avoir (to have).",
        ar: "اختر الصيغة الصحيحة للفعل avoir.",
        fa: "صورت درست فعل avoir را انتخاب کنید.",
        ti: "ምረጽ ቅኑዕ ቅርጺ ናይ avoir.",
        uk: "Виберіть правильну форму avoir.",
      },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "J'___ une sœur.", choices: ["ai", "as", "a", "ont"], correctIdx: 0 },
        { sentence: "Tu ___ 30 ans.", choices: ["as", "ai", "a", "avez"], correctIdx: 0 },
        { sentence: "Il ___ faim.", choices: ["a", "as", "ai", "ont"], correctIdx: 0 },
        { sentence: "Nous ___ un chat.", choices: ["avons", "avez", "ont", "ai"], correctIdx: 0 },
        { sentence: "Vous ___ quel âge ?", choices: ["avez", "avons", "as", "ont"], correctIdx: 0 },
        { sentence: "Ils ___ chaud.", choices: ["ont", "a", "avez", "avons"], correctIdx: 0 },
        { sentence: "Elle ___ un portable.", choices: ["a", "as", "ai", "ont"], correctIdx: 0 },
        { sentence: "On ___ soif.", choices: ["a", "as", "ont", "ai"], correctIdx: 0 },
        { sentence: "Elles ___ deux frères.", choices: ["ont", "a", "avez", "ai"], correctIdx: 0 },
        { sentence: "Tu ___ une amie française ?", choices: ["as", "a", "ai", "avez"], correctIdx: 0 },
        { sentence: "J'___ froid.", choices: ["ai", "suis", "as", "a"], correctIdx: 0 },
        { sentence: "Nous ___ peur.", choices: ["avons", "sommes", "avez", "ont"], correctIdx: 0 },
        { sentence: "Il ___ 20 ans.", choices: ["a", "est", "as", "ont"], correctIdx: 0 },
        { sentence: "Vous ___ mal ?", choices: ["avez", "êtes", "as", "ont"], correctIdx: 0 },
        { sentence: "Elle ___ une tablette.", choices: ["a", "est", "as", "ont"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Complétez avec avoir",
      instruction: "Conjuguez le verbe avoir au présent.",
      transInstruction: {
        en: "Conjugate the verb avoir in the present tense.",
        ar: "صرّف الفعل avoir في المضارع.",
        fa: "فعل avoir را در زمان حال صرف کنید.",
        ti: "ግሲ avoir ኣብ ሕጂ ግዜ ኣጻርይ.",
        uk: "Відмінюйте avoir у теперішньому часі.",
      },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "J'___ (avoir) une sœur.", hint: "avoir → je", answer: "ai" },
        { sentence: "Tu ___ (avoir) 25 ans.", hint: "avoir → tu", answer: "as" },
        { sentence: "Elle ___ (avoir) faim.", hint: "avoir → elle", answer: "a" },
        { sentence: "Nous ___ (avoir) un chien.", hint: "avoir → nous", answer: "avons" },
        { sentence: "Vous ___ (avoir) soif ?", hint: "avoir → vous", answer: "avez" },
        { sentence: "Ils ___ (avoir) chaud.", hint: "avoir → ils", answer: "ont" },
        { sentence: "On ___ (avoir) peur.", hint: "avoir → on", answer: "a" },
        { sentence: "Elles ___ (avoir) un portable.", hint: "avoir → elles", answer: "ont" },
        { sentence: "Il ___ (avoir) mal à la tête.", hint: "avoir → il", answer: "a" },
        { sentence: "Tu ___ (avoir) une amie ?", hint: "avoir → tu", answer: "as" },
      ],
    },
    // Anciens exercices dynamiques conjugaison (avoir)
    {
      type: "qcm",
      title: "Exercice 1 — Être ou avoir ?",
      instruction: "Choisis le bon verbe pour compléter la phrase.",
      transInstruction: { en: "Choose the correct verb to complete the sentence.", ar: "اختر الفعل الصحيح لإكمال الجملة.", fa: "فعل درست را برای کامل کردن جمله انتخاب کنید.", ti: "ንሓሳብ ንምምላእ ቅኑዕ ግሲ ምረጽ።", uk: "Оберіть правильне дієслово, щоб доповнити речення." },
      items: [],
      poolSize: 5,
      toggleChoices: true,
      pool: [
        { sentence: "Fatima ♀ ___ 23 ans.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Je ___ étudiant.", choices: ["suis", "ai", "est"], correctIdx: 0 },
        { sentence: "Nous ___ faim.", choices: ["sommes", "avons", "sont"], correctIdx: 1 },
        { sentence: "Viktor ♂ ___ ukrainien.", choices: ["est", "a", "ont"], correctIdx: 0 },
        { sentence: "Ils ___ un appartement à Genève.", choices: ["sont", "ont", "avez"], correctIdx: 1 },
        { sentence: "Tu ___ peur ?", choices: ["es", "as", "est"], correctIdx: 1 },
        { sentence: "Elle ___ professeure.", choices: ["est", "a", "ont"], correctIdx: 0 },
        { sentence: "Vous ___ soif ?", choices: ["êtes", "avez", "ont"], correctIdx: 1 },
        { sentence: "On ___ fatigués.", choices: ["est", "a", "ont"], correctIdx: 0 },
        { sentence: "Ils ___ afghans.", choices: ["ont", "sont", "avons"], correctIdx: 1 },
        { sentence: "J'___ froid.", choices: ["suis", "ai", "est"], correctIdx: 1 },
        { sentence: "Hamid ♂ ___ un vélo.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Nous ___ érythréens.", choices: ["avons", "sommes", "sont"], correctIdx: 1 },
        { sentence: "Tu ___ raison.", choices: ["es", "as", "est"], correctIdx: 1 },
        { sentence: "Elle ___ chaud.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Nous ___ étudiants.", choices: ["avons", "sommes", "sont"], correctIdx: 1 },
        { sentence: "J'___ soif.", choices: ["ai", "suis", "est"], correctIdx: 0 },
        { sentence: "Elles ___ françaises.", choices: ["sont", "ont", "avez"], correctIdx: 0 },
        { sentence: "Il ___ un frère.", choices: ["est", "a", "sont"], correctIdx: 1 },
        { sentence: "Tu ___ médecin ?", choices: ["as", "est", "es"], correctIdx: 2 },
        { sentence: "J'___ mal à la tête.", choices: ["suis", "ai", "est"], correctIdx: 1 },
        { sentence: "Vous ___ ukrainiens.", choices: ["êtes", "avez", "sont"], correctIdx: 0 },
        { sentence: "On ___ chaud.", choices: ["est", "sont", "a"], correctIdx: 2 },
        { sentence: "Ils ___ ingénieurs.", choices: ["ont", "sont", "avons"], correctIdx: 1 },
        { sentence: "Elle ___ une sœur.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Tu ___ congolais ?", choices: ["as", "es", "est"], correctIdx: 1 },
        { sentence: "Nous ___ une question.", choices: ["avons", "sommes", "ont"], correctIdx: 0 },
        { sentence: "Je ___ français(e).", choices: ["ai", "est", "suis"], correctIdx: 2 },
        { sentence: "Vous ___ tort.", choices: ["êtes", "avez", "sont"], correctIdx: 1 },
        { sentence: "Elle ___ infirmière.", choices: ["a", "est", "ont"], correctIdx: 1 },
        { sentence: "Il ___ 40 ans.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Nous ___ à Paris.", choices: ["sommes", "avons", "sont"], correctIdx: 0 },
        { sentence: "Elles ___ faim.", choices: ["sont", "avez", "ont"], correctIdx: 2 },
        { sentence: "J'___ peur du chien.", choices: ["suis", "ai", "est"], correctIdx: 1 },
        { sentence: "Tu ___ grand(e).", choices: ["es", "as", "est"], correctIdx: 0 },
        { sentence: "Ils ___ un rendez-vous.", choices: ["sont", "ont", "avons"], correctIdx: 1 },
        { sentence: "On ___ à Genève.", choices: ["a", "est", "sont"], correctIdx: 1 },
        { sentence: "Vous ___ fatigués ?", choices: ["avez", "êtes", "sont"], correctIdx: 1 },
        { sentence: "Elle ___ 15 ans.", choices: ["est", "a", "ont"], correctIdx: 1 },
        { sentence: "Il ___ étudiant.", choices: ["est", "a", "ont"], correctIdx: 0 },
        { sentence: "Nous ___ raison.", choices: ["sommes", "avons", "ont"], correctIdx: 1 },
        { sentence: "J'___ une voiture.", choices: ["ai", "suis", "est"], correctIdx: 0 },
        { sentence: "Elles ___ soif.", choices: ["sont", "ont", "avez"], correctIdx: 1 },
        { sentence: "Tu ___ chaud ?", choices: ["as", "es", "est"], correctIdx: 0 },
        { sentence: "Ils ___ algériens.", choices: ["ont", "avons", "sont"], correctIdx: 2 },
        { sentence: "On ___ mal au dos.", choices: ["est", "a", "sont"], correctIdx: 1 },
        { sentence: "Vous ___ un appartement ?", choices: ["êtes", "avez", "sont"], correctIdx: 1 },
        { sentence: "Elle ___ à Lyon.", choices: ["est", "a", "ont"], correctIdx: 0 },
        { sentence: "Il ___ froid.", choices: ["est", "sont", "a"], correctIdx: 2 },
        { sentence: "Nous ___ contents.", choices: ["avons", "sommes", "sont"], correctIdx: 1 },
      ],
    },
    {
      type: "fill",
      title: "Exercice 3 — Complétez avec avoir",
      instruction: "Écris la bonne forme du verbe avoir.",
      transInstruction: { en: "Write the correct form of the verb avoir.", ar: "اكتب الصيغة الصحيحة للفعل avoir.", fa: "صورت درست فعل avoir را بنویسید.", ti: "ቅኑዕ ቅርጺ ናይቲ ግሲ avoir ጽሓፍ።", uk: "Напишіть правильну форму дієслова avoir." },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "J'___ 19 ans.", hint: "j' → ai", answer: "ai" },
        { sentence: "Tu ___ faim ?", hint: "tu → as", answer: "as" },
        { sentence: "Il ___ un vélo.", hint: "il → a", answer: "a" },
        { sentence: "Elle ___ soif.", hint: "elle → a", answer: "a" },
        { sentence: "Nous ___ faim.", hint: "nous → avons", answer: "avons" },
        { sentence: "Vous ___ un rendez-vous ?", hint: "vous → avez", answer: "avez" },
        { sentence: "Ils ___ peur.", hint: "ils → ont", answer: "ont" },
        { sentence: "Elles ___ chaud.", hint: "elles → ont", answer: "ont" },
        { sentence: "On ___ froid.", hint: "on → a", answer: "a" },
        { sentence: "J'___ un téléphone.", hint: "j' → ai", answer: "ai" },
        { sentence: "Tu ___ une question ?", hint: "tu → as", answer: "as" },
        { sentence: "Il ___ 35 ans.", hint: "il → a", answer: "a" },
        { sentence: "Nous ___ soif.", hint: "nous → avons", answer: "avons" },
        { sentence: "Elle ___ raison.", hint: "elle → a", answer: "a" },
        { sentence: "Vous ___ tort.", hint: "vous → avez", answer: "avez" },
        { sentence: "Ils ___ un appartement.", hint: "ils → ont", answer: "ont" },
        { sentence: "J'___ froid.", hint: "j' → ai", answer: "ai" },
        { sentence: "Tu ___ chaud ?", hint: "tu → as", answer: "as" },
        { sentence: "Elle ___ 20 ans.", hint: "elle → a", answer: "a" },
        { sentence: "Nous ___ peur.", hint: "nous → avons", answer: "avons" },
        { sentence: "On ___ mal.", hint: "on → a", answer: "a" },
        { sentence: "Vous ___ froid ?", hint: "vous → avez", answer: "avez" },
        { sentence: "Ils ___ faim.", hint: "ils → ont", answer: "ont" },
        { sentence: "J'___ 25 ans.", hint: "j' → ai", answer: "ai" },
        { sentence: "Il ___ mal à la tête.", hint: "il → a", answer: "a" },
        { sentence: "Tu ___ peur ?", hint: "tu → as", answer: "as" },
        { sentence: "Elles ___ tort.", hint: "elles → ont", answer: "ont" },
        { sentence: "Nous ___ de la chance.", hint: "nous → avons", answer: "avons" },
        { sentence: "Elle ___ chaud.", hint: "elle → a", answer: "a" },
        { sentence: "Vous ___ une voiture ?", hint: "vous → avez", answer: "avez" },
        { sentence: "J'___ raison.", hint: "j' → ai", answer: "ai" },
        { sentence: "Tu ___ soif ?", hint: "tu → as", answer: "as" },
        { sentence: "Ils ___ chaud.", hint: "ils → ont", answer: "ont" },
        { sentence: "On ___ soif.", hint: "on → a", answer: "a" },
        { sentence: "Elle ___ un frère.", hint: "elle → a", answer: "a" },
        { sentence: "Nous ___ tort.", hint: "nous → avons", answer: "avons" },
        { sentence: "Vous ___ faim ?", hint: "vous → avez", answer: "avez" },
        { sentence: "J'___ peur.", hint: "j' → ai", answer: "ai" },
        { sentence: "Il ___ de la chance.", hint: "il → a", answer: "a" },
        { sentence: "Tu ___ un rendez-vous ?", hint: "tu → as", answer: "as" },
        { sentence: "Elles ___ froid.", hint: "elles → ont", answer: "ont" },
        { sentence: "Nous ___ raison.", hint: "nous → avons", answer: "avons" },
        { sentence: "On ___ raison.", hint: "on → a", answer: "a" },
        { sentence: "Je ___ mal au dos.", hint: "j' → ai", answer: "ai" },
        { sentence: "Elle ___ un téléphone.", hint: "elle → a", answer: "a" },
        { sentence: "Vous ___ raison.", hint: "vous → avez", answer: "avez" },
        { sentence: "Ils ___ soif.", hint: "ils → ont", answer: "ont" },
        { sentence: "Tu ___ mal ?", hint: "tu → as", answer: "as" },
        { sentence: "Il ___ une sœur.", hint: "il → a", answer: "a" },
        { sentence: "Elles ___ peur.", hint: "elles → ont", answer: "ont" },
      ],
    },
    {
      type: "fill",
      title: "Exercice 4 — Conjuguez le verbe",
      instruction: "Écris la bonne forme de être ou avoir.",
      transInstruction: { en: "Write the correct form of être or avoir.", ar: "اكتب الصيغة الصحيحة من être أو avoir.", fa: "صورت درست être یا avoir را بنویسید.", ti: "ቅኑዕ ቅርጺ être ወይ avoir ጽሓፍ።", uk: "Напишіть правильну форму être або avoir." },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "Ali ♂ ___ ingénieur.", hint: "il → est", answer: "est" },
        { sentence: "Nous ___ à Genève.", hint: "nous → sommes", answer: "sommes" },
        { sentence: "J'___ 30 ans.", hint: "j' → ai", answer: "ai" },
        { sentence: "Elles ___ faim.", hint: "elles → ont", answer: "ont" },
        { sentence: "Tu ___ érythréen ?", hint: "tu → es", answer: "es" },
        { sentence: "Vous ___ un rendez-vous ?", hint: "vous → avez", answer: "avez" },
        { sentence: "On ___ froid.", hint: "on → a", answer: "a" },
        { sentence: "Iryna ♀ ___ ukrainienne.", hint: "elle → est", answer: "est" },
        { sentence: "Ils ___ tort.", hint: "ils → ont", answer: "ont" },
        { sentence: "Je ___ étudiant(e).", hint: "je → suis", answer: "suis" },
        { sentence: "Hamid ♂ ___ 28 ans.", hint: "il → a", answer: "a" },
        { sentence: "Nous ___ peur.", hint: "nous → avons", answer: "avons" },
        { sentence: "Viktor ♂ ___ médecin.", hint: "il → est", answer: "est" },
        { sentence: "Tu ___ soif ?", hint: "tu → as", answer: "as" },
        { sentence: "Elles ___ afghanes.", hint: "elles → sont", answer: "sont" },
        { sentence: "Vous ___ érythréens.", hint: "vous → êtes", answer: "êtes" },
        { sentence: "Elles ___ congolaises.", hint: "elles → sont", answer: "sont" },
        { sentence: "Je ___ à Lyon.", hint: "je → suis", answer: "suis" },
        { sentence: "Tu ___ 22 ans.", hint: "tu → as", answer: "as" },
        { sentence: "Ils ___ peur.", hint: "ils → ont", answer: "ont" },
        { sentence: "Elle ___ grande.", hint: "elle → est", answer: "est" },
        { sentence: "Nous ___ prêts.", hint: "nous → sommes", answer: "sommes" },
        { sentence: "J'___ chaud.", hint: "j' → ai", answer: "ai" },
        { sentence: "Vous ___ raison.", hint: "vous → avez", answer: "avez" },
        { sentence: "Ils ___ à Genève.", hint: "ils → sont", answer: "sont" },
        { sentence: "Elle ___ 30 ans.", hint: "elle → a", answer: "a" },
        { sentence: "Je ___ faim.", hint: "j' → ai", answer: "ai" },
        { sentence: "Tu ___ à Paris.", hint: "tu → es", answer: "es" },
        { sentence: "On ___ algérien.", hint: "on → est", answer: "est" },
        { sentence: "Nous ___ mal.", hint: "nous → avons", answer: "avons" },
        { sentence: "Vous ___ à l'école.", hint: "vous → êtes", answer: "êtes" },
        { sentence: "Elles ___ soif.", hint: "elles → ont", answer: "ont" },
        { sentence: "Il ___ infirmier.", hint: "il → est", answer: "est" },
        { sentence: "Je ___ suisse.", hint: "je → suis", answer: "suis" },
        { sentence: "Tu ___ de la chance.", hint: "tu → as", answer: "as" },
        { sentence: "Elle ___ professeure.", hint: "elle → est", answer: "est" },
        { sentence: "Ils ___ un appartement.", hint: "ils → ont", answer: "ont" },
        { sentence: "Nous ___ contents.", hint: "nous → sommes", answer: "sommes" },
        { sentence: "J'___ raison.", hint: "j' → ai", answer: "ai" },
        { sentence: "Vous ___ fatigués.", hint: "vous → êtes", answer: "êtes" },
        { sentence: "On ___ chaud.", hint: "on → a", answer: "a" },
        { sentence: "Elles ___ françaises.", hint: "elles → sont", answer: "sont" },
        { sentence: "Il ___ un frère.", hint: "il → a", answer: "a" },
        { sentence: "Tu ___ belge ?", hint: "tu → es", answer: "es" },
        { sentence: "Nous ___ une voiture.", hint: "nous → avons", answer: "avons" },
        { sentence: "Je ___ en retard.", hint: "je → suis", answer: "suis" },
        { sentence: "Elle ___ peur.", hint: "elle → a", answer: "a" },
        { sentence: "Ils ___ étudiants.", hint: "ils → sont", answer: "sont" },
        { sentence: "J'___ mal à la tête.", hint: "j' → ai", answer: "ai" },
      ],
    },
    {
      type: "write",
      title: "Exercice 6 — Écrivez avec avoir",
      instruction: "Écrivez 2 phrases avec le verbe avoir.",
      transInstruction: { en: "Write 2 sentences with the verb avoir.", ar: "اكتب جملتين باستخدام الفعل avoir.", fa: "۲ جمله با فعل avoir بنویسید.", ti: "2 ሓሳባት ብግሲ avoir ጽሓፍ።", uk: "Напишіть 2 речення з дієсловом avoir." },
      prompts: ["Phrase 1 :", "Phrase 2 :"],
      verb: "avoir",
    },

  ],
};