import type { GrammarLesson } from "../../grammar-data";

export const A1_GR_PRONOMINAUX_PASSE: GrammarLesson = {
  slug: "a1-gr-pronominaux-passe-compose",
  code: "R5.6",
  level: "A1",
  title: "Les verbes pronominaux au passé composé",
  theory: [
    { type: "heading", text: "Les verbes pronominaux au passé composé", trans: { en: "Reflexive verbs in the passé composé", ar: "الأفعال الانعكاسية في الماضي المركب", fa: "افعال انعکاسی در گذشته مرکب", ti: "ናይ ሕሉፍ ጊዜ ርእሰ-ጠቓሚ ግሳት", uk: "Займенникові дієслова в passé composé" } },
    {
      type: "highlight",
      label: "Formation",
      transLabel: { en: "Formation", ar: "التكوين", fa: "ساختار", ti: "ቅርጺ", uk: "Утворення" },
      items: [
        "Tous les verbes pronominaux utilisent l'auxiliaire {a}être{/a}.",
        "Sujet + pronom réfléchi + être + participe passé.",
        "Je me suis levé(e). / Nous nous sommes préparé(e)s.",
      ],
      transItems: {
        en: ["All reflexive verbs use the auxiliary {a}être{/a}.", "Subject + reflexive pronoun + être + past participle.", "Je me suis levé(e). (I got up.) / Nous nous sommes préparé(e)s. (We got ready.)"],
        ar: ["جميع الأفعال الانعكاسية تستخدم الفعل المساعد {a}être{/a}.", "الفاعل + الضمير الانعكاسي + être + اسم المفعول.", "Je me suis levé(e). (قمت.) / Nous nous sommes préparé(e)s. (استعددنا.)"],
        fa: ["تمام افعال انعکاسی از فعل کمکی {a}être{/a} استفاده می‌کنند.", "فاعل + ضمیر انعکاسی + être + صفت مفعولی.", "Je me suis levé(e). (بلند شدم.) / Nous nous sommes préparé(e)s. (آماده شدیم.)"],
        ti: ["ኩሎም ርእሰ-ጠቓሚ ግሳት ሓጋዚ {a}être{/a} ይጥቀሙ።", "ርእሲ + ናይ ርእሲ ጸጋ + être + ናይ ሕሉፍ ተሳታፋይ.", "Je me suis levé(e). (ተንሲኤ.) / Nous nous sommes préparé(e)s. (ተዳሊና.)"],
        uk: ["Усі займенникові дієслова вживаються з допоміжним {a}être{/a}.", "Підмет + зворотний займенник + être + дієприкметник.", "Je me suis levé(e). (Я встав/встала.) / Nous nous sommes préparé(e)s. (Ми приготувалися.)"],
      },
    },
    {
      type: "plain_list",
      items: [
        "Le participe passé s'accorde avec le sujet réel lorsque le pronom réfléchi est complément direct.",
        "Elle s'est lavée. / Ils se sont rencontrés.",
        "Il reste invariable lorsqu'un COD est placé après le verbe : elle s'est lavé les mains.",
      ],
      transItems: {
        en: ["The past participle agrees with the real subject when the reflexive pronoun is a direct object.", "Elle s'est lavée. (She washed herself.) / Ils se sont rencontrés. (They met.)", "It stays invariable when a COD comes after the verb: elle s'est lavé les mains. (She washed her hands.)"],
        ar: ["يتطابق اسم المفعول مع الفاعل الحقيقي عندما يكون الضمير الانعكاسي مفعولاً مباشراً.", "Elle s'est lavée. (اغتسلت.) / Ils se sont rencontrés. (التقيا.)", "يبقى ثابتاً عندما يأتي مفعول به مباشر بعد الفعل: elle s'est lavé les mains. (غسلت يديها.)"],
        fa: ["صفت مفعولی با فاعل اصلی مطابقت دارد وقتی ضمیر انعکاسی مفعول مستقیم باشد.", "Elle s'est lavée. (خودش را شست.) / Ils se sont rencontrés. (ملاقات کردند.)", "اگر مفعول مستقیم بعد از فعل بیاید، صفت مفعولی تغییر نمی‌کند: elle s'est lavé les mains. (دست‌هایش را شست.)"],
        ti: ["ናይ ሕሉፍ ተሳታፋይ ምስ ኣካላዊ ርእሲ ይሰማማዕ ናይ ርእሲ ጸጋ ቀጥታዊ ዕላማ ከሎ.", "Elle s'est lavée. (ነብሳ ተሓጺባ.) / Ils se sont rencontrés. (ተራኺቦም.)", "COD ድሕሪ ግሲ ምስ ዝመጽእ ኣይቕየርን: elle s'est lavé les mains. (ኣእዳዋ ሓጺባ.)"],
        uk: ["Дієприкметник узгоджується з реальним підметом, коли зворотний займенник є прямим додатком.", "Elle s'est lavée. (Вона помилася.) / Ils se sont rencontrés. (Вони зустрілися.)", "Залишається незмінним, коли прямий додаток стоїть після дієслова: elle s'est lavé les mains. (Вона помила руки.)"],
      },
    },
    {
      type: "highlight",
      label: "Négation",
      transLabel: { en: "Negation", ar: "النفي", fa: "نفی", ti: "ምኽፋል", uk: "Заперечення" },
      items: [
        "La négation encadre le pronom réfléchi et l'auxiliaire.",
        "Je {a}ne me suis pas{/a} levé tôt.",
        "Elles {a}ne se sont jamais{/a} rencontrées.",
      ],
      transItems: {
        en: ["The negation surrounds the reflexive pronoun and the auxiliary.", "Je {a}ne me suis pas{/a} levé tôt. (I didn't get up early.)", "Elles {a}ne se sont jamais{/a} rencontrées. (They have never met.)"],
        ar: ["تحيط النفي بالضمير الانعكاسي والفعل المساعد.", "Je {a}ne me suis pas{/a} levé tôt. (لم أستيقظ مبكراً.)", "Elles {a}ne se sont jamais{/a} rencontrées. (لم يلتقيا أبداً.)"],
        fa: ["نفی، ضمیر انعکاسی و فعل کمکی را در بر می‌گیرد.", "Je {a}ne me suis pas{/a} levé tôt. (زود از خواب بیدار نشدم.)", "Elles {a}ne se sont jamais{/a} rencontrées. (هرگز ملاقات نکرده‌اند.)"],
        ti: ["ምኽፋል ናይ ርእሲ ጸጋን ሓጋዚን ይኸብቦ.", "Je {a}ne me suis pas{/a} levé tôt. (ቀልጢፈ ኣይተንሳእኩን.)", "Elles {a}ne se sont jamais{/a} rencontrées. (ኣፍ ርእሰን ዳዕ ተራኺበን ኣይፈልጣን.)"],
        uk: ["Заперечення оточує зворотний займенник і допоміжне дієслово.", "Je {a}ne me suis pas{/a} levé tôt. (Я не вставав рано.)", "Elles {a}ne se sont jamais{/a} rencontrées. (Вони ніколи не зустрічалися.)"],
      },
    },
  ],
  exercises: [
    {
      type: "fill",
      title: "Exercice 1",
      instruction: "Conjuguez le verbe pronominal au passé composé. Accordez le participe passé si nécessaire.",
      transInstruction: { en: "Conjugate the reflexive verb in the passé composé. Agree the past participle if necessary.", ar: "صرّف الفعل الانعكاسي في الماضي المركب. أعرب اسم المفعول عند الضرورة.", fa: "فعل انعکاسی را در گذشته‌ی مرکب صرف کنید. در صورت لزوم صفت مفعولی را مطابقت دهید.", ti: "ነቲ ርእሰ-ግሲ ኣብ ሕሉፍ ውሁድ ኣጻርይ። ኣድላዪ እንተኾነ ናይ ሕሉፍ ተሳታፋይ ኣሰማማዕ።", uk: "Відмінюйте зворотне дієслово в passé composé. Узгодьте дієприкметник за потреби." },
      items: [],
      pool: [
        { sentence: "Je ___ (se lever) tôt. [masc.]", hint: "me suis levé", answer: "me suis levé" },
        { sentence: "Elle ___ (se lever) tôt.", hint: "s'est levée", answer: "s'est levée" },
        { sentence: "Ils ___ (se rencontrer).", hint: "se sont rencontrés", answer: "se sont rencontrés" },
        { sentence: "Nous ___ (se préparer). [fém. pl.]", hint: "nous sommes préparées", answer: "nous sommes préparées" },
        { sentence: "Tu ___ (se coucher) tard. [fém.]", hint: "t'es couchée", answer: "t'es couchée" },
        { sentence: "Vous ___ (se réveiller). [masc. pl.]", hint: "vous êtes réveillés", answer: "vous êtes réveillés" },
        { sentence: "Elles ___ (s'habiller).", hint: "se sont habillées", answer: "se sont habillées" },
        { sentence: "Il ___ (se souvenir) de moi.", hint: "s'est souvenu", answer: "s'est souvenu" },
        { sentence: "Nous ___ (se téléphoner). [pas d'accord]", hint: "nous nous sommes téléphoné", answer: "nous sommes téléphoné" },
      ],
      poolSize: 6,
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Accordez correctement le participe passé du verbe pronominal.",
      transInstruction: { en: "Agree the past participle of the reflexive verb correctly.", ar: "أعرب اسم المفعول للفعل الانعكاسي بشكل صحيح.", fa: "صفت مفعولی فعل انعکاسی را به‌درستی مطابقت دهید.", ti: "ናይ ሕሉፍ ተሳታፋይ ናይ ርእሰ-ግሲ ብትኽክል ኣሰማማዕ።", uk: "Правильно узгодьте дієприкметник зворотного дієслова." },
      items: [],
      pool: [
        { sentence: "Elle s'est ___ (laver).", hint: "se = COD → accord fém.", answer: "lavée" },
        { sentence: "Elle s'est ___ (laver) les mains.", hint: "COD = les mains → pas d'accord", answer: "lavé" },
        { sentence: "Ils se sont ___ (rencontrer).", hint: "se = COD → accord masc. pl.", answer: "rencontrés" },
        { sentence: "Elles se sont ___ (écrire).", hint: "se = COI → pas d'accord", answer: "écrit" },
        { sentence: "Elle s'est ___ (lever).", hint: "se = COD → accord fém. sing.", answer: "levée" },
        { sentence: "Ils se sont ___ (parler).", hint: "se = COI → pas d'accord", answer: "parlé" },
      ],
      poolSize: 5,
    },
    {
      type: "fill",
      title: "Exercice 3",
      instruction: "Mettez la phrase à la forme négative.",
      transInstruction: { en: "Put the sentence in the negative form.", ar: "حوّل الجملة إلى صيغة النفي.", fa: "جمله را به‌صورت منفی بنویسید.", ti: "ነቲ ሓሳብ ናብ ኣሉታዊ ቅርጺ ቀይር።", uk: "Поставте речення у заперечній формі." },
      items: [],
      pool: [
        { sentence: "Je ___ (ne pas se lever) tôt.", hint: "ne me suis pas levé(e)", answer: "ne me suis pas levé" },
        { sentence: "Elle ___ (ne pas se préparer) à temps.", hint: "ne s'est pas préparée", answer: "ne s'est pas préparée" },
        { sentence: "Ils ___ (ne jamais se rencontrer).", hint: "ne se sont jamais rencontrés", answer: "ne se sont jamais rencontrés" },
        { sentence: "Nous ___ (ne pas se parler) hier.", hint: "ne nous sommes pas parlé", answer: "ne nous sommes pas parlé" },
        { sentence: "Tu ___ (ne pas se coucher) tôt. [fém.]", hint: "ne t'es pas couchée", answer: "ne t'es pas couchée" },
      ],
      poolSize: 4,
    },
    {
      type: "classify",
      title: "Exercice 4",
      instruction: "Le pronom réfléchi est-il COD (accord du participe) ou COI (pas d'accord) ?",
      transInstruction: { en: "Is the reflexive pronoun a COD (participle agreement) or COI (no agreement)?", ar: "هل الضمير الانعكاسي مفعولاً مباشراً (إعراب اسم المفعول) أم غير مباشر (بدون إعراب)؟", fa: "آیا ضمیر انعکاسی مفعول مستقیم است (مطابقت صفت مفعولی) یا غیرمستقیم (بدون مطابقت)؟", ti: "ናይ ርእሲ ጸጋ COD (ምስማዕ ናይ ሕሉፍ ተሳታፋይ) ወይ COI (ዘይምስማዕ) ድዩ?", uk: "Зворотний займенник — COD (узгодження дієприкметника) чи COI (без узгодження)?" },
      categories: ["Pronom = COD → accord", "Pronom = COI → pas d'accord"],
      items: [
        { word: "Elle s'est lavée.", categoryIdx: 0 },
        { word: "Ils se sont parlé.", categoryIdx: 1 },
        { word: "Elles se sont rencontrées.", categoryIdx: 0 },
        { word: "Elles se sont écrit.", categoryIdx: 1 },
        { word: "Il s'est levé.", categoryIdx: 0 },
        { word: "Nous nous sommes téléphoné.", categoryIdx: 1 },
      ],
    },
    {
      type: "word_order",
      title: "Exercice 5",
      instruction: "Remettez les mots dans le bon ordre pour former une phrase correcte.",
      transInstruction: { en: "Put the words back in the correct order to form a correct sentence.", ar: "أعد ترتيب الكلمات لتكوين جملة صحيحة.", fa: "کلمات را به ترتیب درست بچینید تا جمله‌ی درستی بسازید.", ti: "ነተን ቃላት ቅኑዕ ሓሳብ ንምግባር ብቅኑዕ ስርዓት መድብ።", uk: "Розставте слова у правильному порядку, щоб утворити правильне речення." },
      items: [],
      pool: [
        { sentence: "Elle s'est levée tôt.", words: ["Elle", "s'est", "levée", "tôt."] },
        { sentence: "Ils se sont rencontrés à Paris.", words: ["Ils", "se", "sont", "rencontrés", "à", "Paris."] },
        { sentence: "Je ne me suis pas couché tôt.", words: ["Je", "ne", "me", "suis", "pas", "couché", "tôt."] },
        { sentence: "Nous nous sommes préparés rapidement.", words: ["Nous", "nous", "sommes", "préparés", "rapidement."] },
        { sentence: "Elle s'est lavé les mains.", words: ["Elle", "s'est", "lavé", "les", "mains."] },
      ],
      poolSize: 4,
    },
    {
      type: "write",
      title: "Exercice 6",
      instruction: "Écrivez une phrase avec un verbe pronominal au passé composé.\nN'oubliez pas d'accorder le participe passé si nécessaire.",
      transInstruction: { en: "Write a sentence with a reflexive verb in the passé composé.\nDon't forget to agree the past participle if necessary.", ar: "اكتب جملة بفعل انعكاسي في الماضي المركب.\nلا تنسَ إعراب اسم المفعول عند الضرورة.", fa: "یک جمله با فعل انعکاسی در گذشته‌ی مرکب بنویسید.\nدر صورت لزوم صفت مفعولی را مطابقت دهید.", ti: "ሓደ ሓሳብ ብርእሰ-ግሲ ኣብ ሕሉፍ ውሁድ ጽሓፍ።\nኣድላዪ እንተኾነ ናይ ሕሉፍ ተሳታፋይ ኣሰማማዕ።", uk: "Напишіть речення із зворотним дієсловом у passé composé.\nНе забудьте узгодити дієприкметник за потреби." },
      verbPool: ["se lever", "se coucher", "se préparer", "se rencontrer", "s'habiller", "se souvenir"],
      verbPoolSize: 2,
    },
  ],
};
