import type { GrammarLesson } from "../../grammar-data";

/** Unité 14 — Les noms composés (G2.4) */
export const A1_GR_NOMS_COMPOSES: GrammarLesson = {
  slug: "a1-gr-noms-composes",
  code: "G2.4",
  level: "A1",
  title: "Les noms composés",
  theory: [
    {
      type: "plain_list",
      items: [
        "Un nom composé est un nom formé de deux ou plusieurs mots qui créent ensemble un seul nom. Les mots peuvent être reliés par un trait d'union ou par une préposition ({a}à{/a}, {a}de{/a}, {a}en{/a} ou {a}aux{/a}).",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["A compound noun is a noun made of two or more words that together form a single noun. The words may be linked by a hyphen or by a preposition ({a}à{/a}, {a}de{/a}, {a}en{/a} or {a}aux{/a})."],
        ar: ["الاسم المركب هو اسم يتكوّن من كلمتين أو أكثر تشكّل معاً اسماً واحداً. قد تُربط الكلمات بشرطة أو بحرف جر ({a}à{/a}، {a}de{/a}، {a}en{/a} أو {a}aux{/a})."],
        fa: ["اسم مرکب اسمی است که از دو یا چند کلمه ساخته شده و با هم یک اسم واحد می‌سازند. کلمات ممکن است با خط تیره یا با حرف اضافه ({a}à{/a}، {a}de{/a}، {a}en{/a} یا {a}aux{/a}) به هم وصل شوند."],
        ti: ["ውሁድ ስም ካብ ክልተ ወይ ዝያዳ ቃላት ዝቖመ ስም እዩ፣ ብሓባር ሓደ ስም ይፈጥሩ። እቶም ቃላት ብመስመር ወይ ብቅድመ-ስም ({a}à{/a}፣ {a}de{/a}፣ {a}en{/a} ወይ {a}aux{/a}) ክተኣሳሰሩ ይኽእሉ።"],
        uk: ["Складний іменник — це іменник, утворений з двох або більше слів, які разом створюють один іменник. Слова можуть бути з’єднані дефісом або прийменником ({a}à{/a}, {a}de{/a}, {a}en{/a} чи {a}aux{/a})."],
      },
    },
    {
      type: "highlight",
      label: "Par un trait d'union",
      transLabel: {
        en: "With a hyphen",
        ar: "بشرطة",
        fa: "با خط تیره",
        ti: "ብመስመር",
        uk: "Через дефіс",
      },
      items: [
        "le sous{a}-{/a}sol",
        "une grand{a}-{/a}mère",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "highlight",
      label: "Par une préposition",
      transLabel: {
        en: "With a preposition",
        ar: "بحرف جر",
        fa: "با حرف اضافه",
        ti: "ብቅድመ-ስም",
        uk: "З прийменником",
      },
      items: [
        "une salle {a}de{/a} bains",
        "une chambre {a}à{/a} coucher",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "heading",
      text: "Orthographe",
      trans: { en: "Spelling", ar: "الإملاء", fa: "املا", ti: "ኣጸሓሕፋ", uk: "Правопис" },
    },
    {
      type: "plain_list",
      items: [
        "Le second mot peut déjà être au pluriel lorsqu'il désigne ce que contient ou ce à quoi sert l'objet.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["The second word may already be plural when it names what the object contains or what it is used for."],
        ar: ["قد تكون الكلمة الثانية في صيغة الجمع مسبقاً عندما تدل على ما يحتويه الشيء أو على ما يُستخدم من أجله."],
        fa: ["کلمهٔ دوم ممکن است از قبل جمع باشد وقتی چیزی را که شیء در خود دارد یا کاربرد آن را نشان می‌دهد."],
        ti: ["እቲ ካልኣይ ቃል ቅድም ብባዙሕ ክኸውን ይኽእል፣ እቲ ነገር እንታይ ከም ዝሓዝ ወይ ንምንታይ ከም ዝጥቀም ምስ ዘመልክት።"],
        uk: ["Друге слово вже може бути в множині, коли воно позначає те, що містить предмет, або те, для чого він служить."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "un porte-document{a}s{/a}",
        "un porte-bagage{a}s{/a}",
        "un porte-clé{a}s{/a}",
        "une boîte aux lettre{a}s{/a}",
      ],
      noBulletItems: [0, 1, 2, 3],
    },
    {
      type: "heading",
      text: "Au pluriel",
      trans: { en: "In the plural", ar: "في الجمع", fa: "در جمع", ti: "ብባዙሕ", uk: "У множині" },
    },
    {
      type: "plain_list",
      items: [
        "Les mots varient ou pas selon le type des mots.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["Words change or stay the same depending on the type of word."],
        ar: ["تتغيّر الكلمات أو تبقى كما هي بحسب نوع الكلمة."],
        fa: ["کلمات بسته به نوع کلمه تغییر می‌کنند یا ثابت می‌مانند."],
        ti: ["ቃላት ከም ዓይነቶም ይቕየሩ ወይ ከም ዘለዉ ይተርፉ።"],
        uk: ["Слова змінюються або ні залежно від типу слова."],
      },
    },
    {
      type: "plain_list",
      items: [
        "{a}1.{/a} Les verbes restent invariables.",
        "{a}2.{/a} Les prépositions restent invariables.",
        "{a}3.{/a} Les noms prennent un {a}-s{/a} si le sens le permet.",
        "{a}4.{/a} Les adjectifs s'accordent avec le nom.",
      ],
      noBulletItems: [0, 1, 2, 3],
      transItems: {
        en: [
          "{a}1.{/a} Verbs stay invariable.",
          "{a}2.{/a} Prepositions stay invariable.",
          "{a}3.{/a} Nouns take an {a}-s{/a} when the meaning allows it.",
          "{a}4.{/a} Adjectives agree with the noun.",
        ],
        ar: [
          "{a}1.{/a} الأفعال تبقى دون تغيير.",
          "{a}2.{/a} حروف الجر تبقى دون تغيير.",
          "{a}3.{/a} الأسماء تأخذ {a}-s{/a} إذا سمح المعنى بذلك.",
          "{a}4.{/a} الصفات تتوافق مع الاسم.",
        ],
        fa: [
          "{a}1.{/a} فعل‌ها تغییر نمی‌کنند.",
          "{a}2.{/a} حروف اضافه تغییر نمی‌کنند.",
          "{a}3.{/a} اسم‌ها اگر معنا اجازه دهد {a}-s{/a} می‌گیرند.",
          "{a}4.{/a} صفت‌ها با اسم مطابقت می‌کنند.",
        ],
        ti: [
          "{a}1.{/a} ግሲታት ኣይቕየሩን።",
          "{a}2.{/a} ቅድመ-ስማት ኣይቕየሩን።",
          "{a}3.{/a} ስማት ትርጉም እንተፈቒዱ {a}-s{/a} ይወስዱ።",
          "{a}4.{/a} ቅጽልታት ምስ ስም ይሰማምዑ።",
        ],
        uk: [
          "{a}1.{/a} Дієслова незмінні.",
          "{a}2.{/a} Прийменники незмінні.",
          "{a}3.{/a} Іменники отримують {a}-s{/a}, якщо дозволяє значення.",
          "{a}4.{/a} Прикметники узгоджуються з іменником.",
        ],
      },
    },
    {
      type: "grid",
      headers: ["", "Singulier", "Pluriel"],
      transHeaders: {
        en: ["", "Singular", "Plural"],
        ar: ["", "المفرد", "الجمع"],
        fa: ["", "مفرد", "جمع"],
        ti: ["", "ንጽል", "ባዙሕ"],
        uk: ["", "Однина", "Множина"],
      },
      boldFirstCol: true,
      rows: [
        ["verbe + nom", "un taille-crayon", "des taille-crayon{a}s{/a}"],
        ["adjectif + nom", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
        ["nom + nom", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
      ],
      transRows: {
        en: [
          ["verb + noun", "un taille-crayon", "des taille-crayon{a}s{/a}"],
          ["adjective + noun", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
          ["noun + noun", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
        ],
        ar: [
          ["فعل + اسم", "un taille-crayon", "des taille-crayon{a}s{/a}"],
          ["صفة + اسم", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
          ["اسم + اسم", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
        ],
        fa: [
          ["فعل + اسم", "un taille-crayon", "des taille-crayon{a}s{/a}"],
          ["صفت + اسم", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
          ["اسم + اسم", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
        ],
        ti: [
          ["ግሲ + ስም", "un taille-crayon", "des taille-crayon{a}s{/a}"],
          ["ቅጽል + ስም", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
          ["ስም + ስም", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
        ],
        uk: [
          ["дієслово + іменник", "un taille-crayon", "des taille-crayon{a}s{/a}"],
          ["прикметник + іменник", "une grand-mère", "des grand{a}s{/a}-mère{a}s{/a}"],
          ["іменник + іменник", "un canapé-lit", "des canapé{a}s{/a}-lit{a}s{/a}"],
        ],
      },
    },
    {
      type: "highlight",
      label: "Exception",
      transLabel: {
        en: "Exception",
        ar: "استثناء",
        fa: "استثنا",
        ti: "ፍሉይ",
        uk: "Виняток",
      },
      items: [],
    },
    {
      type: "plain_list",
      items: [
        "Certains noms composés ne suivent pas la règle générale.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["Some compound nouns do not follow the general rule."],
        ar: ["بعض الأسماء المركبة لا تتبع القاعدة العامة."],
        fa: ["برخی اسم‌های مرکب از قاعدهٔ کلی پیروی نمی‌کنند."],
        ti: ["ገለ ውሁዳት ስማት ነቲ ሓፈሻዊ ሕጊ ኣይስዕቡን።"],
        uk: ["Деякі складні іменники не підкоряються загальному правилу."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "{a}des{/a} porte-monnaie",
        "{a}des{/a} porte-bonheur",
      ],
      noBulletItems: [0, 1],
    },
    {
      type: "plain_list",
      items: [
        "En général, seul le dernier mot s'accorde pour les mots d'origine étrangère.",
      ],
      noBulletItems: [0],
      transItems: {
        en: ["In general, only the last word agrees for words of foreign origin."],
        ar: ["عموماً، تتوافق الكلمة الأخيرة فقط في الكلمات ذات الأصل الأجنبي."],
        fa: ["به‌طور کلی، برای واژه‌های با ریشهٔ خارجی فقط آخرین کلمه مطابقت می‌کند."],
        ti: ["ብሓፈሻ፣ ንናይ ወጻኢ መበቆል ቃላት እቲ ናይ መወዳእታ ቃል ጥራይ ይሰማማዕ።"],
        uk: ["Зазвичай для слів іноземного походження узгоджується лише останнє слово."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: [
        "un week-end → {a}des{/a} week-ends",
        "un night-club → {a}des{/a} night-clubs",
      ],
      noBulletItems: [0, 1],
      inlineArrows: true,
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Exercice 1",
      instruction: "Choisissez la forme plurielle correcte.",
      transInstruction: {
        en: "Choose the correct plural form.",
        ar: "اختر صيغة الجمع الصحيحة.",
        fa: "صورت جمع درست را انتخاب کنید.",
        ti: "እቲ ቅኑዕ ባዙሕ ቅርጺ ምረጽ።",
        uk: "Оберіть правильну форму множини.",
      },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "un ouvre-boîte → des ___", choices: ["ouvre-boîtes", "ouvres-boîtes", "ouvre-boîte"], correctIdx: 0 },
        { sentence: "un sac à main → des ___", choices: ["sacs à main", "sac à mains", "sacs à mains"], correctIdx: 0 },
        { sentence: "un taille-crayon → des ___", choices: ["taille-crayons", "tailles-crayons", "taille-crayon"], correctIdx: 0 },
        { sentence: "une grand-mère → des ___", choices: ["grands-mères", "grand-mères", "grands-mère"], correctIdx: 0 },
        { sentence: "un canapé-lit → des ___", choices: ["canapés-lits", "canapé-lits", "canapés-lit"], correctIdx: 0 },
        { sentence: "un porte-monnaie → des ___", choices: ["porte-monnaie", "portes-monnaies", "porte-monnaies"], correctIdx: 0 },
        { sentence: "une pomme de terre → des ___", choices: ["pommes de terre", "pomme de terres", "pommes de terres"], correctIdx: 0 },
        { sentence: "un week-end → des ___", choices: ["week-ends", "weeks-end", "weeks-ends"], correctIdx: 0 },
        { sentence: "un après-midi → des ___", choices: ["après-midi", "après-midis", "aprèses-midi"], correctIdx: 0 },
        { sentence: "un porte-clés → des ___", choices: ["porte-clés", "portes-clés", "porte-clé"], correctIdx: 0 },
        { sentence: "un coffre-fort → des ___", choices: ["coffres-forts", "coffre-forts", "coffres-fort"], correctIdx: 0 },
        { sentence: "un tire-bouchon → des ___", choices: ["tire-bouchons", "tires-bouchons", "tire-bouchon"], correctIdx: 0 },
        { sentence: "une salle de bains → des ___", choices: ["salles de bains", "salle de bains", "salles de bain"], correctIdx: 0 },
        { sentence: "un arc-en-ciel → des ___", choices: ["arcs-en-ciel", "arc-en-ciels", "arcs-en-ciels"], correctIdx: 0 },
        { sentence: "une boîte aux lettres → des ___", choices: ["boîtes aux lettres", "boîte aux lettres", "boîtes aux lettre"], correctIdx: 0 },
        { sentence: "un night-club → des ___", choices: ["night-clubs", "nights-club", "nights-clubs"], correctIdx: 0 },
        { sentence: "un porte-bonheur → des ___", choices: ["porte-bonheur", "portes-bonheurs", "porte-bonheurs"], correctIdx: 0 },
        { sentence: "une chambre à coucher → des ___", choices: ["chambres à coucher", "chambre à couchers", "chambres à couchers"], correctIdx: 0 },
        { sentence: "un sous-sol → des ___", choices: ["sous-sols", "sous-sol", "souss-sols"], correctIdx: 0 },
        { sentence: "un porte-documents → des ___", choices: ["porte-documents", "portes-documents", "porte-document"], correctIdx: 0 },
        { sentence: "un porte-bagages → des ___", choices: ["porte-bagages", "portes-bagages", "porte-bagage"], correctIdx: 0 },
        { sentence: "un gratte-ciel → des ___", choices: ["gratte-ciel", "gratte-ciels", "grattes-ciels"], correctIdx: 0 },
        { sentence: "un beau-frère → des ___", choices: ["beaux-frères", "beau-frères", "beaux-frère"], correctIdx: 0 },
        { sentence: "une belle-mère → des ___", choices: ["belles-mères", "belle-mères", "belles-mère"], correctIdx: 0 },
        { sentence: "un grand-père → des ___", choices: ["grands-pères", "grand-pères", "grands-père"], correctIdx: 0 },
        { sentence: "une petite-fille → des ___", choices: ["petites-filles", "petite-filles", "petites-fille"], correctIdx: 0 },
        { sentence: "un petit-fils → des ___", choices: ["petits-fils", "petit-fils", "petits-filss"], correctIdx: 0 },
        { sentence: "un rond-point → des ___", choices: ["ronds-points", "rond-points", "ronds-point"], correctIdx: 0 },
        { sentence: "une sage-femme → des ___", choices: ["sages-femmes", "sage-femmes", "sages-femme"], correctIdx: 0 },
        { sentence: "un court-métrage → des ___", choices: ["courts-métrages", "court-métrages", "courts-métrage"], correctIdx: 0 },
        { sentence: "un long-métrage → des ___", choices: ["longs-métrages", "long-métrages", "longs-métrage"], correctIdx: 0 },
        { sentence: "une basse-cour → des ___", choices: ["basses-cours", "basse-cours", "basses-cour"], correctIdx: 0 },
        { sentence: "un chou-fleur → des ___", choices: ["choux-fleurs", "chou-fleurs", "choux-fleur"], correctIdx: 0 },
        { sentence: "un poisson-chat → des ___", choices: ["poissons-chats", "poisson-chats", "poissons-chat"], correctIdx: 0 },
        { sentence: "un bateau-mouche → des ___", choices: ["bateaux-mouches", "bateau-mouches", "bateaux-mouche"], correctIdx: 0 },
        { sentence: "un oiseau-mouche → des ___", choices: ["oiseaux-mouches", "oiseau-mouches", "oiseaux-mouche"], correctIdx: 0 },
        { sentence: "un wagon-restaurant → des ___", choices: ["wagons-restaurants", "wagon-restaurants", "wagons-restaurant"], correctIdx: 0 },
        { sentence: "un auteur-compositeur → des ___", choices: ["auteurs-compositeurs", "auteur-compositeurs", "auteurs-compositeur"], correctIdx: 0 },
        { sentence: "un médecin-chef → des ___", choices: ["médecins-chefs", "médecin-chefs", "médecins-chef"], correctIdx: 0 },
        { sentence: "un chef-lieu → des ___", choices: ["chefs-lieux", "chef-lieux", "chefs-lieu"], correctIdx: 0 },
        { sentence: "un fer à repasser → des ___", choices: ["fers à repasser", "fer à repassers", "fers à repassers"], correctIdx: 0 },
        { sentence: "un moulin à café → des ___", choices: ["moulins à café", "moulin à cafés", "moulins à cafés"], correctIdx: 0 },
        { sentence: "une machine à laver → des ___", choices: ["machines à laver", "machine à lavers", "machines à lavers"], correctIdx: 0 },
        { sentence: "une machine à coudre → des ___", choices: ["machines à coudre", "machine à coudres", "machines à coudres"], correctIdx: 0 },
        { sentence: "une chemise de nuit → des ___", choices: ["chemises de nuit", "chemise de nuits", "chemises de nuits"], correctIdx: 0 },
        { sentence: "une robe de chambre → des ___", choices: ["robes de chambre", "robe de chambres", "robes de chambres"], correctIdx: 0 },
        { sentence: "un chemin de fer → des ___", choices: ["chemins de fer", "chemin de fers", "chemins de fers"], correctIdx: 0 },
        { sentence: "une carte de visite → des ___", choices: ["cartes de visite", "carte de visites", "cartes de visites"], correctIdx: 0 },
        { sentence: "un point de vue → des ___", choices: ["points de vue", "point de vues", "points de vues"], correctIdx: 0 },
        { sentence: "un fruit de mer → des ___", choices: ["fruits de mer", "fruit de mers", "fruits de mers"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Donnez la forme plurielle du nom composé.",
      transInstruction: {
        en: "Give the plural form of the compound noun.",
        ar: "أعطِ صيغة الجمع للاسم المركب.",
        fa: "صورت جمع اسم مرکب را بنویسید.",
        ti: "እቲ ናይ ውሁድ ስም ባዙሕ ቅርጺ ሃብ።",
        uk: "Напишіть форму множини складного іменника.",
      },
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "un ouvre-boîte → des ___", hint: "verbe invariable", answer: "ouvre-boîtes" },
        { sentence: "un sac à main → des ___", hint: "nom variable", answer: "sacs à main" },
        { sentence: "une grand-mère → des ___", hint: "adjectif + nom", answer: "grands-mères" },
        { sentence: "un canapé-lit → des ___", hint: "nom + nom", answer: "canapés-lits" },
        { sentence: "un porte-monnaie → des ___", hint: "exception", answer: "porte-monnaie" },
        { sentence: "une pomme de terre → des ___", hint: "nom + préposition + nom", answer: "pommes de terre" },
        { sentence: "un week-end → des ___", hint: "origine étrangère", answer: "week-ends" },
        { sentence: "un taille-crayon → des ___", hint: "verbe + nom", answer: "taille-crayons" },
        { sentence: "un après-midi → des ___", hint: "exception", answer: "après-midi" },
        { sentence: "un night-club → des ___", hint: "origine étrangère", answer: "night-clubs" },
        { sentence: "un coffre-fort → des ___", hint: "nom + adjectif", answer: "coffres-forts" },
        { sentence: "un tire-bouchon → des ___", hint: "verbe invariable", answer: "tire-bouchons" },
        { sentence: "une salle de bains → des ___", hint: "nom variable", answer: "salles de bains" },
        { sentence: "un arc-en-ciel → des ___", hint: "nom variable", answer: "arcs-en-ciel" },
        { sentence: "une boîte aux lettres → des ___", hint: "nom variable", answer: "boîtes aux lettres" },
        { sentence: "un porte-bonheur → des ___", hint: "exception", answer: "porte-bonheur" },
        { sentence: "une chambre à coucher → des ___", hint: "nom variable", answer: "chambres à coucher" },
        { sentence: "un sous-sol → des ___", hint: "+ s", answer: "sous-sols" },
        { sentence: "un porte-documents → des ___", hint: "verbe invariable", answer: "porte-documents" },
        { sentence: "un porte-clés → des ___", hint: "verbe invariable", answer: "porte-clés" },
        { sentence: "un porte-bagages → des ___", hint: "verbe invariable", answer: "porte-bagages" },
        { sentence: "un gratte-ciel → des ___", hint: "exception", answer: "gratte-ciel" },
        { sentence: "un beau-frère → des ___", hint: "adjectif + nom", answer: "beaux-frères" },
        { sentence: "une belle-mère → des ___", hint: "adjectif + nom", answer: "belles-mères" },
        { sentence: "un grand-père → des ___", hint: "adjectif + nom", answer: "grands-pères" },
        { sentence: "une petite-fille → des ___", hint: "adjectif + nom", answer: "petites-filles" },
        { sentence: "un petit-fils → des ___", hint: "adjectif + nom", answer: "petits-fils" },
        { sentence: "un rond-point → des ___", hint: "adjectif + nom", answer: "ronds-points" },
        { sentence: "une sage-femme → des ___", hint: "adjectif + nom", answer: "sages-femmes" },
        { sentence: "un court-métrage → des ___", hint: "adjectif + nom", answer: "courts-métrages" },
        { sentence: "un long-métrage → des ___", hint: "adjectif + nom", answer: "longs-métrages" },
        { sentence: "une basse-cour → des ___", hint: "adjectif + nom", answer: "basses-cours" },
        { sentence: "un chou-fleur → des ___", hint: "nom + nom", answer: "choux-fleurs" },
        { sentence: "un poisson-chat → des ___", hint: "nom + nom", answer: "poissons-chats" },
        { sentence: "un bateau-mouche → des ___", hint: "nom + nom", answer: "bateaux-mouches" },
        { sentence: "un oiseau-mouche → des ___", hint: "nom + nom", answer: "oiseaux-mouches" },
        { sentence: "un wagon-restaurant → des ___", hint: "nom + nom", answer: "wagons-restaurants" },
        { sentence: "un auteur-compositeur → des ___", hint: "nom + nom", answer: "auteurs-compositeurs" },
        { sentence: "un médecin-chef → des ___", hint: "nom + nom", answer: "médecins-chefs" },
        { sentence: "un chef-lieu → des ___", hint: "nom + nom", answer: "chefs-lieux" },
        { sentence: "un fer à repasser → des ___", hint: "nom + préposition + verbe", answer: "fers à repasser" },
        { sentence: "un moulin à café → des ___", hint: "nom + préposition + nom", answer: "moulins à café" },
        { sentence: "une machine à laver → des ___", hint: "nom + préposition + verbe", answer: "machines à laver" },
        { sentence: "une machine à coudre → des ___", hint: "nom + préposition + verbe", answer: "machines à coudre" },
        { sentence: "une chemise de nuit → des ___", hint: "nom + préposition + nom", answer: "chemises de nuit" },
        { sentence: "une robe de chambre → des ___", hint: "nom + préposition + nom", answer: "robes de chambre" },
        { sentence: "un chemin de fer → des ___", hint: "nom + préposition + nom", answer: "chemins de fer" },
        { sentence: "une carte de visite → des ___", hint: "nom + préposition + nom", answer: "cartes de visite" },
        { sentence: "un point de vue → des ___", hint: "nom + préposition + nom", answer: "points de vue" },
        { sentence: "un fruit de mer → des ___", hint: "nom + préposition + nom", answer: "fruits de mer" },
      ],
    },
    {
      type: "fill",
      title: "Exercice 3",
      instruction: "Réécrivez les phrases au pluriel.",
      transInstruction: {
        en: "Rewrite the sentences in the plural.",
        ar: "أعد كتابة الجمل في صيغة الجمع.",
        fa: "جمله‌ها را به صورت جمع بازنویسی کنید.",
        ti: "እተን ሓሳባት ብባዙሕ ደጊምካ ጽሓፍ።",
        uk: "Перепишіть речення у множині.",
      },
      items: [],
      poolSize: 5,
      inputWidth: "w-[32rem]",
      pool: [
        { sentence: "Un ouvre-boîte est dans le tiroir.\n___", hint: "pluriel", answer: "Des ouvre-boîtes sont dans les tiroirs." },
        { sentence: "Un sac à main est sur la chaise.\n___", hint: "pluriel", answer: "Des sacs à main sont sur les chaises." },
        { sentence: "Un taille-crayon est rangé dans la trousse.\n___", hint: "pluriel", answer: "Des taille-crayons sont rangés dans les trousses." },
        { sentence: "Une grand-mère raconte une histoire.\n___", hint: "pluriel", answer: "Des grands-mères racontent des histoires." },
        { sentence: "Un canapé-lit est installé dans le studio.\n___", hint: "pluriel", answer: "Des canapés-lits sont installés dans les studios." },
        { sentence: "Un porte-monnaie est dans le sac.\n___", hint: "pluriel", answer: "Des porte-monnaie sont dans les sacs." },
        { sentence: "Une pomme de terre cuit dans la casserole.\n___", hint: "pluriel", answer: "Des pommes de terre cuisent dans les casseroles." },
        { sentence: "Un week-end commence vendredi.\n___", hint: "pluriel", answer: "Des week-ends commencent vendredi." },
        { sentence: "Un après-midi est libre.\n___", hint: "pluriel", answer: "Des après-midi sont libres." },
        { sentence: "Un porte-clés est sur la table.\n___", hint: "pluriel", answer: "Des porte-clés sont sur les tables." },
        { sentence: "Un coffre-fort protège le dossier.\n___", hint: "pluriel", answer: "Des coffres-forts protègent les dossiers." },
        { sentence: "Un tire-bouchon est dans le tiroir.\n___", hint: "pluriel", answer: "Des tire-bouchons sont dans les tiroirs." },
        { sentence: "Une salle de bains est au fond du couloir.\n___", hint: "pluriel", answer: "Des salles de bains sont au fond des couloirs." },
        { sentence: "Un arc-en-ciel apparaît après l'orage.\n___", hint: "pluriel", answer: "Des arcs-en-ciel apparaissent après les orages." },
        { sentence: "Une boîte aux lettres est devant la maison.\n___", hint: "pluriel", answer: "Des boîtes aux lettres sont devant les maisons." },
        { sentence: "Un night-club ouvre le soir.\n___", hint: "pluriel", answer: "Des night-clubs ouvrent le soir." },
        { sentence: "Un porte-bonheur reste dans la poche.\n___", hint: "pluriel", answer: "Des porte-bonheur restent dans les poches." },
        { sentence: "Une chambre à coucher donne sur le jardin.\n___", hint: "pluriel", answer: "Des chambres à coucher donnent sur les jardins." },
        { sentence: "Un sous-sol sert de cave.\n___", hint: "pluriel", answer: "Des sous-sols servent de caves." },
        { sentence: "Un porte-documents est posé sur le bureau.\n___", hint: "pluriel", answer: "Des porte-documents sont posés sur les bureaux." },
        { sentence: "Un porte-bagages est fixé sur le vélo.\n___", hint: "pluriel", answer: "Des porte-bagages sont fixés sur les vélos." },
        { sentence: "Un gratte-ciel domine la ville.\n___", hint: "pluriel", answer: "Des gratte-ciel dominent les villes." },
        { sentence: "Un beau-frère arrive dimanche.\n___", hint: "pluriel", answer: "Des beaux-frères arrivent dimanche." },
        { sentence: "Une belle-mère prépare un repas.\n___", hint: "pluriel", answer: "Des belles-mères préparent des repas." },
        { sentence: "Un grand-père jardine le matin.\n___", hint: "pluriel", answer: "Des grands-pères jardinent le matin." },
        { sentence: "Une petite-fille dessine une fleur.\n___", hint: "pluriel", answer: "Des petites-filles dessinent des fleurs." },
        { sentence: "Un petit-fils téléphone souvent.\n___", hint: "pluriel", answer: "Des petits-fils téléphonent souvent." },
        { sentence: "Un rond-point ralentit la voiture.\n___", hint: "pluriel", answer: "Des ronds-points ralentissent les voitures." },
        { sentence: "Une sage-femme accompagne la naissance.\n___", hint: "pluriel", answer: "Des sages-femmes accompagnent les naissances." },
        { sentence: "Un court-métrage dure dix minutes.\n___", hint: "pluriel", answer: "Des courts-métrages durent dix minutes." },
        { sentence: "Un long-métrage passe au cinéma.\n___", hint: "pluriel", answer: "Des longs-métrages passent au cinéma." },
        { sentence: "Une basse-cour se trouve derrière la ferme.\n___", hint: "pluriel", answer: "Des basses-cours se trouvent derrière les fermes." },
        { sentence: "Un chou-fleur pousse dans le jardin.\n___", hint: "pluriel", answer: "Des choux-fleurs poussent dans les jardins." },
        { sentence: "Un poisson-chat nage dans l'aquarium.\n___", hint: "pluriel", answer: "Des poissons-chats nagent dans les aquariums." },
        { sentence: "Un bateau-mouche traverse la Seine.\n___", hint: "pluriel", answer: "Des bateaux-mouches traversent la Seine." },
        { sentence: "Un oiseau-mouche vole près de la fleur.\n___", hint: "pluriel", answer: "Des oiseaux-mouches volent près des fleurs." },
        { sentence: "Un wagon-restaurant est complet.\n___", hint: "pluriel", answer: "Des wagons-restaurants sont complets." },
        { sentence: "Un auteur-compositeur écrit une chanson.\n___", hint: "pluriel", answer: "Des auteurs-compositeurs écrivent des chansons." },
        { sentence: "Un médecin-chef dirige le service.\n___", hint: "pluriel", answer: "Des médecins-chefs dirigent les services." },
        { sentence: "Un chef-lieu accueille la préfecture.\n___", hint: "pluriel", answer: "Des chefs-lieux accueillent les préfectures." },
        { sentence: "Un fer à repasser chauffe sur la table.\n___", hint: "pluriel", answer: "Des fers à repasser chauffent sur les tables." },
        { sentence: "Un moulin à café est dans la cuisine.\n___", hint: "pluriel", answer: "Des moulins à café sont dans les cuisines." },
        { sentence: "Une machine à laver tourne dans la buanderie.\n___", hint: "pluriel", answer: "Des machines à laver tournent dans les buanderies." },
        { sentence: "Une machine à coudre répare la chemise.\n___", hint: "pluriel", answer: "Des machines à coudre réparent les chemises." },
        { sentence: "Une chemise de nuit sèche sur l'étendoir.\n___", hint: "pluriel", answer: "Des chemises de nuit sèchent sur les étendoirs." },
        { sentence: "Une robe de chambre pend derrière la porte.\n___", hint: "pluriel", answer: "Des robes de chambre pendent derrière les portes." },
        { sentence: "Un chemin de fer traverse la région.\n___", hint: "pluriel", answer: "Des chemins de fer traversent les régions." },
        { sentence: "Une carte de visite reste dans le portefeuille.\n___", hint: "pluriel", answer: "Des cartes de visite restent dans les portefeuilles." },
        { sentence: "Un point de vue change la discussion.\n___", hint: "pluriel", answer: "Des points de vue changent les discussions." },
        { sentence: "Un fruit de mer est servi en entrée.\n___", hint: "pluriel", answer: "Des fruits de mer sont servis en entrée." },
      ],
    },
  ],
};
