import type { GrammarLesson } from "../../grammar-data";

export const A2_GR_HYPOTHESE_FUTUR: GrammarLesson = {
  slug: "a2-gr-hypothese-futur",
  code: "R4.8",
  level: "A2",
  title: "L'hypothèse sur le futur",
  theory: [
    { type: "heading", text: "Si + présent → futur simple", trans: { en: "Si + present → simple future", ar: "Si + المضارع ← المستقبل البسيط", fa: "Si + حال ← آینده‌ی ساده", ti: "Si + ህሉው → ቀሊል መጻኢ", uk: "Si + теперішній → простий майбутній" } },
    {
      type: "text",
      label: "Structure",
      items: ["Condition : {a}si + présent{/a}.", "Conséquence : {a}futur simple{/a}.", "Si tu viens demain, nous mangerons ensemble."],
      transLabel: { en: "Structure", ar: "البنية", fa: "ساختار", ti: "ቅርጺ", uk: "Структура" },
      transItems: {
        en: ["Condition: {a}si + present{/a}.", "Consequence: {a}simple future{/a}.", "Si tu viens demain, nous mangerons ensemble. (If you come tomorrow, we will eat together.)"],
        ar: ["الشرط: {a}si + المضارع{/a}.", "النتيجة: {a}المستقبل البسيط{/a}.", "Si tu viens demain, nous mangerons ensemble. (إذا أتيت غداً، سنأكل معاً.)"],
        fa: ["شرط: {a}si + حال{/a}.", "نتیجه: {a}آینده‌ی ساده{/a}.", "Si tu viens demain, nous mangerons ensemble. (اگر فردا بیایی، با هم غذا می‌خوریم.)"],
        ti: ["ኩነት፦ {a}si + ህሉው{/a}።", "ሳዕቤን፦ {a}ቀሊል መጻኢ{/a}።", "Si tu viens demain, nous mangerons ensemble. (ጽባሕ እንተመጺእካ፣ ብሓባር ክንበልዕ ኢና።)"],
        uk: ["Умова: {a}si + теперішній{/a}.", "Наслідок: {a}простий майбутній{/a}.", "Si tu viens demain, nous mangerons ensemble. (Якщо ти прийдеш завтра, ми поїмо разом.)"],
      },
    },
    {
      type: "text",
      noBulletItems: [0],
      items: ["L'ordre des deux propositions peut changer : nous mangerons ensemble si tu viens demain.", "On n'utilise jamais le futur juste après si dans cette structure."],
      transItems: {
        en: ["The order of the two clauses can change: nous mangerons ensemble si tu viens demain. (we will eat together if you come tomorrow).", "The future is never used right after «si» in this structure."],
        ar: ["يمكن أن يتغير ترتيب الجملتين: nous mangerons ensemble si tu viens demain. (سنأكل معاً إذا أتيت غداً).", "لا يُستخدم المستقبل أبداً مباشرة بعد «si» في هذه البنية."],
        fa: ["ترتیب دو عبارت می‌تواند تغییر کند: nous mangerons ensemble si tu viens demain. (با هم غذا می‌خوریم اگر فردا بیایی).", "در این ساختار هرگز بعد از «si» از آینده استفاده نمی‌شود."],
        ti: ["ቅደም ተኸተል ናይ ክልቲኡ ሓሳባት ክቕየር ይኽእል፦ nous mangerons ensemble si tu viens demain. (ጽባሕ እንተመጺእካ ብሓባር ክንበልዕ ኢና)።", "ኣብዚ ቅርጺ ድሕሪ «si» ፈጺሙ መጻኢ ኣይጥቀምን።"],
        uk: ["Порядок двох частин може змінюватися: nous mangerons ensemble si tu viens demain. (ми поїмо разом, якщо ти прийдеш завтра).", "Майбутній час ніколи не вживається одразу після «si» в цій структурі."],
      },
    },
    { type: "text", label: "Élision avec il", items: ["si + il → {a}s'il{/a} : s'il pleut, nous resterons à la maison.", "On écrit si elle, si on ; « si ils » n'existe pas."],
      transLabel: { en: "Elision with «il»", ar: "الحذف مع «il»", fa: "حذف با «il»", ti: "ምሕጻር ምስ «il»", uk: "Елізія з «il»" },
      transItems: {
        en: ["si + il becomes {a}s'il{/a}: s'il pleut, nous resterons à la maison. (if it rains, we will stay at home).", "We write «si elle», «si on»; «si ils» does not exist."],
        ar: ["si + il يصبح {a}s'il{/a}: s'il pleut, nous resterons à la maison. (إذا أمطرت، سنبقى في المنزل).", "نكتب «si elle» و«si on»؛ «si ils» غير موجودة."],
        fa: ["si + il به {a}s'il{/a} تبدیل می‌شود: s'il pleut, nous resterons à la maison. (اگر باران ببارد، در خانه می‌مانیم).", "می‌نویسیم «si elle»، «si on»؛ «si ils» وجود ندارد."],
        ti: ["si + il ናብ {a}s'il{/a} ይቕየር፦ s'il pleut, nous resterons à la maison. (እንተዘንቢሉ፣ ኣብ ገዛ ክንተርፍ ኢና)።", "«si elle»፣ «si on» ንጽሕፍ፤ «si ils» የለን።"],
        uk: ["si + il стає {a}s'il{/a}: s'il pleut, nous resterons à la maison. (якщо піде дощ, ми залишимося вдома).", "Пишемо «si elle», «si on»; «si ils» не існує."],
      },
    },
    { type: "heading", text: "Exemples complets", sub: true, accent: true, trans: { en: "Complete examples", ar: "أمثلة كاملة", fa: "مثال‌های کامل", ti: "ምሉኣት ኣብነታት", uk: "Повні приклади" } },
    {
      type: "grid",
      headers: ["Condition (si + présent)", "Conséquence (futur simple)"],
      equalCols: true,
      rows: [
        ["Si tu {a}travailles{/a} bien,", "tu {a}réussiras{/a} ton examen."],
        ["Si elle {a}vient{/a} demain,", "nous {a}partirons{/a} ensemble."],
        ["S'il {a}pleut{/a},", "nous {a}resterons{/a} à la maison."],
        ["Si vous {a}avez{/a} le temps,", "vous {a}pourrez{/a} visiter le musée."],
        ["Si nous {a}partons{/a} tôt,", "nous {a}arriverons{/a} à l'heure."],
      ],
      transHeaders: {
        en: ["Condition (si + present)", "Consequence (simple future)"],
        ar: ["الشرط (si + مضارع)", "النتيجة (مستقبل بسيط)"],
        fa: ["شرط (si + حال)", "نتیجه (آینده‌ی ساده)"],
        ti: ["ኩነት (si + ህሉው)", "ሳዕቤን (ቀሊል መጻኢ)"],
        uk: ["Умова (si + теперішній)", "Наслідок (простий майбутній)"],
      },
      transRows: {
        en: [
          ["Si tu {a}travailles{/a} bien, (If you work well,)", "tu {a}réussiras{/a} ton examen. (you will pass your exam.)"],
          ["Si elle {a}vient{/a} demain, (If she comes tomorrow,)", "nous {a}partirons{/a} ensemble. (we will leave together.)"],
          ["S'il {a}pleut{/a}, (If it rains,)", "nous {a}resterons{/a} à la maison. (we will stay at home.)"],
          ["Si vous {a}avez{/a} le temps, (If you have time,)", "vous {a}pourrez{/a} visiter le musée. (you will be able to visit the museum.)"],
          ["Si nous {a}partons{/a} tôt, (If we leave early,)", "nous {a}arriverons{/a} à l'heure. (we will arrive on time.)"],
        ],
        ar: [
          ["Si tu {a}travailles{/a} bien, (إذا عملت جيداً،)", "tu {a}réussiras{/a} ton examen. (ستنجح في امتحانك.)"],
          ["Si elle {a}vient{/a} demain, (إذا أتت غداً،)", "nous {a}partirons{/a} ensemble. (سنغادر معاً.)"],
          ["S'il {a}pleut{/a}, (إذا أمطرت،)", "nous {a}resterons{/a} à la maison. (سنبقى في المنزل.)"],
          ["Si vous {a}avez{/a} le temps, (إذا كان لديكم وقت،)", "vous {a}pourrez{/a} visiter le musée. (ستتمكنون من زيارة المتحف.)"],
          ["Si nous {a}partons{/a} tôt, (إذا غادرنا مبكراً،)", "nous {a}arriverons{/a} à l'heure. (سنصل في الوقت المحدد.)"],
        ],
        fa: [
          ["Si tu {a}travailles{/a} bien, (اگر خوب کار کنی،)", "tu {a}réussiras{/a} ton examen. (در امتحانت موفق می‌شوی.)"],
          ["Si elle {a}vient{/a} demain, (اگر فردا بیاید،)", "nous {a}partirons{/a} ensemble. (با هم می‌رویم.)"],
          ["S'il {a}pleut{/a}, (اگر باران ببارد،)", "nous {a}resterons{/a} à la maison. (در خانه می‌مانیم.)"],
          ["Si vous {a}avez{/a} le temps, (اگر وقت داشتید،)", "vous {a}pourrez{/a} visiter le musée. (می‌توانید از موزه بازدید کنید.)"],
          ["Si nous {a}partons{/a} tôt, (اگر زود برویم،)", "nous {a}arriverons{/a} à l'heure. (به موقع می‌رسیم.)"],
        ],
        ti: [
          ["Si tu {a}travailles{/a} bien, (ጽቡቕ ኣንተሰሪሕካ፣)", "tu {a}réussiras{/a} ton examen. (ፈተናኻ ክትሓልፍ ኢኻ.)"],
          ["Si elle {a}vient{/a} demain, (ጽባሕ ኣንተመጺኣ፣)", "nous {a}partirons{/a} ensemble. (ብሓባር ክንወጽእ ኢና.)"],
          ["S'il {a}pleut{/a}, (ኣንተደምዩ፣)", "nous {a}resterons{/a} à la maison. (ኣብ ገዛ ክንተርፍ ኢና.)"],
          ["Si vous {a}avez{/a} le temps, (ግዜ ኣንተሃሊዩኩም፣)", "vous {a}pourrez{/a} visiter le musée. (ሙዚዩም ክትጎብዙ ክትክእሉ ኢኹም.)"],
          ["Si nous {a}partons{/a} tôt, (ቀልጢፍና ኣንተወጺኢና፣)", "nous {a}arriverons{/a} à l'heure. (ኣብ ግዜ ክንበጽሕ ኢና.)"],
        ],
        uk: [
          ["Si tu {a}travailles{/a} bien, (Якщо ти будеш добре працювати,)", "tu {a}réussiras{/a} ton examen. (ти здаси іспит.)"],
          ["Si elle {a}vient{/a} demain, (Якщо вона прийде завтра,)", "nous {a}partirons{/a} ensemble. (ми поїдемо разом.)"],
          ["S'il {a}pleut{/a}, (Якщо піде дощ,)", "nous {a}resterons{/a} à la maison. (ми залишимося вдома.)"],
          ["Si vous {a}avez{/a} le temps, (Якщо у вас є час,)", "vous {a}pourrez{/a} visiter le musée. (ви зможете відвідати музей.)"],
          ["Si nous {a}partons{/a} tôt, (Якщо ми поїдемо рано,)", "nous {a}arriverons{/a} à l'heure. (ми прибудемо вчасно.)"],
        ],
      },
    },
    { type: "heading", text: "Quand + futur", sub: true, accent: true, trans: { en: "Quand + future", ar: "quand + المستقبل", fa: "quand + آینده", ti: "quand + መጻኢ", uk: "Quand + майбутній" } },
    {
      type: "text",
      noBulletItems: [0],
      items: [
        "En français, {a}quand{/a} suivi d'un futur exprime une action future certaine.",
        "Contrairement à l'anglais (when + présent), le verbe après quand est au {a}futur simple{/a}.",
        "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin.",
        "Elle m'appellera quand elle {a}arrivera{/a}.",
      ],
      transItems: {
        en: [
          "In French, {a}quand{/a} followed by a future tense expresses a certain future action.",
          "Unlike English (when + present), the verb after quand is in the {a}simple future{/a}.",
          "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin. (When I grow up, I will become a doctor.)",
          "Elle m'appellera quand elle {a}arrivera{/a}. (She will call me when she arrives.)",
        ],
        ar: [
          "في الفرنسية، {a}quand{/a} يليه فعل مستقبل يعبّر عن فعل مستقبلي مؤكد.",
          "خلافاً للإنجليزية (when + المضارع)، الفعل بعد quand يأتي بالمستقبل البسيط.",
          "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin. (عندما أكبر، سأصبح طبيباً.)",
          "Elle m'appellera quand elle {a}arrivera{/a}. (ستتصل بي عندما تصل.)",
        ],
        fa: [
          "در فرانسه، {a}quand{/a} + آینده یک عمل آینده‌ی حتمی را بیان می‌کند.",
          "برخلاف انگلیسی (when + حال)، فعل بعد از quand در {a}آینده‌ی ساده{/a} می‌آید.",
          "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin. (وقتی بزرگ شوم، پزشک می‌شوم.)",
          "Elle m'appellera quand elle {a}arrivera{/a}. (وقتی برسد به من زنگ می‌زند.)",
        ],
        ti: [
          "ኣብ ፈረንሳ፣ {a}quand{/a} + መጻኢ ርጉጽ ናይ መጻኢ ተግባር የርኢ።",
          "ካብ ቋንቋ ብሄረ እንግሊዝ (when + ህሉው) ዝተፈለ፣ ቃል ድሕሪ quand ኣብ {a}ቀሊል መጻኢ{/a} ኢዩ።",
          "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin. (ዓቢ ምስ ዝኸውን፣ ሓኪም ክኸውን ኢየ.)",
          "Elle m'appellera quand elle {a}arrivera{/a}. (ምስ ምብጻሓ ክትድውለለይ ኢያ.)",
        ],
        uk: [
          "У французькій {a}quand{/a} + майбутній виражає певну майбутню дію.",
          "На відміну від англійської (when + теперішній), дієслово після quand стоїть у {a}простому майбутньому{/a}.",
          "Quand je {a}serai{/a} grand, je {a}deviendrai{/a} médecin. (Коли я виросту, я стану лікарем.)",
          "Elle m'appellera quand elle {a}arrivera{/a}. (Вона зателефонує мені, коли прийде.)",
        ],
      },
    },
  ],
  exercises: [
    {
      type: "fill",
      title: "Exercice 1",
      instruction: "Complétez la proposition principale avec le verbe au futur simple.",
      transInstruction: { en: "Complete the main clause with the verb in the simple future.", ar: "أكمل الجملة الرئيسية بالفعل في المستقبل البسيط.", fa: "بند اصلی را با فعل در آینده‌ی ساده کامل کنید.", ti: "ነቲ ቀንዲ ክፋል ብግሲ ኣብ ቀሊል መጻኢ ምላእ።", uk: "Доповніть головне речення дієсловом у futur simple." },
      items: [],
      pool: [
        { sentence: "Si tu travailles bien, tu ___ (réussir) ton examen.", hint: "futur simple de réussir", answer: "réussiras" },
        { sentence: "Si elle vient demain, nous ___ (partir) ensemble.", hint: "futur simple de partir", answer: "partirons" },
        { sentence: "S'il pleut, nous ___ (rester) à la maison.", hint: "futur simple de rester", answer: "resterons" },
        { sentence: "Si vous avez le temps, vous ___ (pouvoir) visiter le musée.", hint: "futur simple de pouvoir", answer: "pourrez" },
        { sentence: "Si nous partons tôt, nous ___ (arriver) à l'heure.", hint: "futur simple de arriver", answer: "arriverons" },
        { sentence: "Si tu étudies, tu ___ (savoir) la réponse.", hint: "futur simple de savoir", answer: "sauras" },
        { sentence: "S'il fait beau, on ___ (aller) à la plage.", hint: "futur simple de aller", answer: "ira" },
        { sentence: "Si je suis libre, je ___ (venir) te voir.", hint: "futur simple de venir", answer: "viendrai" },
      ],
      poolSize: 6,
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Complétez la proposition conditionnelle avec le verbe au présent.",
      transInstruction: { en: "Complete the conditional clause with the verb in the present tense.", ar: "أكمل الجملة الشرطية بالفعل في المضارع.", fa: "بند شرطی را با فعل در زمان حال کامل کنید.", ti: "ነቲ ኮንዲሲዮነል ክፋል ብግሲ ኣብ ሕጂ ግዜ ምላእ።", uk: "Доповніть умовне речення дієсловом у теперішньому часі." },
      items: [],
      pool: [
        { sentence: "Si tu ___ (travailler) bien, tu réussiras.", hint: "présent de travailler", answer: "travailles" },
        { sentence: "Si elle ___ (venir) demain, nous partirons.", hint: "présent de venir", answer: "vient" },
        { sentence: "S'il ___ (pleuvoir), nous resterons.", hint: "présent de pleuvoir", answer: "pleut" },
        { sentence: "Si vous ___ (avoir) le temps, vous pourrez visiter.", hint: "présent de avoir", answer: "avez" },
        { sentence: "Si nous ___ (partir) tôt, nous arriverons à l'heure.", hint: "présent de partir", answer: "partons" },
        { sentence: "Si tu ___ (étudier), tu sauras la réponse.", hint: "présent de étudier", answer: "étudies" },
        { sentence: "S'il ___ (faire) beau, on ira à la plage.", hint: "présent de faire", answer: "fait" },
      ],
      poolSize: 5,
    },
    {
      type: "qcm",
      title: "Exercice 3",
      instruction: "Choisissez la forme correcte dans la phrase avec « si ».",
      transInstruction: { en: "Choose the correct form in the sentence with « si ».", ar: "اختر الصيغة الصحيحة في الجملة مع « si ».", fa: "صورت درست را در جمله با « si » انتخاب کنید.", ti: "ኣብ ሓሳብ ምስ « si » ቅኑዕ ቅርጺ ምረጽ።", uk: "Оберіть правильну форму в реченні з « si »." },
      items: [],
      pool: [
        { sentence: "Si tu ___, nous pourrons partir.", choices: ["viens", "viendras", "venais"], correctIdx: 0 },
        { sentence: "S'il pleut, nous ___ à la maison.", choices: ["resterons", "restons", "resterions"], correctIdx: 0 },
        { sentence: "Si elle ___ le temps, elle nous aidera.", choices: ["a", "aura", "avait"], correctIdx: 0 },
        { sentence: "Si vous ___ tôt, vous arriverez à l'heure.", choices: ["partez", "partirez", "partiez"], correctIdx: 0 },
        { sentence: "Si je ___ libre, je viendrai.", choices: ["suis", "serai", "serais"], correctIdx: 0 },
      ],
      poolSize: 4,
    },
    {
      type: "classify",
      title: "Exercice 4",
      instruction: "Classez chaque partie de phrase selon sa fonction.",
      transInstruction: { en: "Sort each part of the sentence according to its function.", ar: "صنّف كل جزء من الجملة حسب وظيفته.", fa: "هر بخش جمله را بر اساس نقش آن دسته‌بندی کنید.", ti: "ነፍሲ ወከፍ ክፋል ሓሳብ ብተግባሩ ሸነኽ።", uk: "Розсортуйте кожну частину речення за її функцією." },
      categories: ["Proposition si (présent)", "Proposition principale (futur)"],
      items: [],
      pool: [
        { word: "Si tu travailles bien,", categoryIdx: 0 },
        { word: "tu réussiras.", categoryIdx: 1 },
        { word: "S'il pleut,", categoryIdx: 0 },
        { word: "nous resterons à la maison.", categoryIdx: 1 },
        { word: "Si elle vient demain,", categoryIdx: 0 },
        { word: "nous partirons ensemble.", categoryIdx: 1 },
        { word: "Si vous avez le temps,", categoryIdx: 0 },
        { word: "vous pourrez visiter le musée.", categoryIdx: 1 },
      ],
      poolSize: 6,
    },
    {
      type: "word_order",
      title: "Exercice 5",
      instruction: "Remettez les mots dans le bon ordre pour former une phrase hypothétique complète.",
      transInstruction: { en: "Put the words back in the correct order to form a complete hypothetical sentence.", ar: "أعد ترتيب الكلمات لتكوين جملة افتراضية كاملة.", fa: "کلمات را به ترتیب درست بچینید تا جمله‌ی فرضی کامل بسازید.", ti: "ነተን ቃላት ሙሉእ ሃይፎቴዚስ ሓሳብ ንምግባር ብቅኑዕ ስርዓት መድብ።", uk: "Розставте слова у правильному порядку, щоб утворити повне гіпотетичне речення." },
      items: [],
      pool: [
        { sentence: "Si tu viens, nous mangerons ensemble.", words: ["Si", "tu", "viens,", "nous", "mangerons", "ensemble."] },
        { sentence: "Nous resterons à la maison s'il pleut.", words: ["Nous", "resterons", "à", "la", "maison", "s'il", "pleut."] },
        { sentence: "S'il fait beau, on ira à la plage.", words: ["S'il", "fait", "beau,", "on", "ira", "à", "la", "plage."] },
        { sentence: "Si vous travaillez bien, vous réussirez.", words: ["Si", "vous", "travaillez", "bien,", "vous", "réussirez."] },
      ],
      poolSize: 3,
    },
    {
      type: "write",
      title: "Exercice 6",
      instruction: "Écrivez une phrase hypothétique complète avec « si + présent → futur ».\nUtilisez les verbes proposés.",
      transInstruction: { en: "Write a complete hypothetical sentence with « si + présent → futur ».\nUse the verbs provided.", ar: "اكتب جملة افتراضية كاملة مع « si + مضارع → مستقبل ».\nاستخدم الأفعال المقترحة.", fa: "یک جمله‌ی فرضی کامل با « si + حال → آینده » بنویسید.\nاز افعال پیشنهادی استفاده کنید.", ti: "ሓደ ሙሉእ ሃይፎቴዚስ ሓሳብ ምስ « si + ሕጂ → መጻኢ » ጽሓፍ።\nእቶም ዝቐረቡ ግሲታት ተጠቐም።", uk: "Напишіть повне гіпотетичне речення з « si + présent → futur ».\nВикористайте запропоновані дієслова." },
      verbPool: ["travailler", "partir", "venir", "avoir", "faire", "étudier"],
      verbPoolSize: 2,
    },
  ],
};
