import type { GrammarLesson } from "../../grammar-data";
import { G1_EXERCISES } from "./g1-lesson-profiles";

/** Unité 7 — Les verbes en -er : cas particuliers (G1.8) */
export const A1_GR_VERBES_ER_PART: GrammarLesson = {
  slug: "a1-gr-verbes-er-particuliers",
  code: "G1.8",
  level: "A1",
  title: "Les verbes en -er : cas particuliers",
  theory: [
    {
      type: "heading",
      text: "Le verbe aller",
      trans: { en: "The verb aller", ar: "فعل aller", fa: "فعل aller", pt: "O verbo aller", so: "Fal-ka aller", ti: "ግሲ aller", tr: "Aller fiili", ps: "د aller فعل", uk: "Дієслово aller" },
    },
    {
      type: "plain_list",
      items: [
        "Le verbe {a}aller{/a} sert à indiquer un déplacement (il est alors suivi d'un lieu ou d'un infinitif) ou à prendre et donner des nouvelles.",
      ],
      transItems: {
        en: ["The verb {a}aller{/a} is used to indicate movement (it is then followed by a place or an infinitive) or to ask for and give news."],
        ar: ["يُستخدم الفعل {a}aller{/a} للدلالة على التنقّل (ويتبع عندئذٍ بمكان أو مصدر) أو للسؤال عن الأحوال وإخبار الآخرين بها."],
        fa: ["فعل {a}aller{/a} برای نشان دادن جابه‌جایی (که در این حالت پس از آن مکان یا مصدر می‌آید) یا برای احوال‌پرسی و خبر دادن به کار می‌رود."],
        pt: ["O verbo {a}aller{/a} é usado para indicar uma deslocação (nesse caso, é seguido de um lugar ou de um infinitivo) ou para perguntar e dar notícias."],
        so: ["Fal-ka {a}aller{/a} waxaa loo isticmaalaa in lagu muujiyo dhaqaaqid (markaas waxaa raaca meel ama fal aan la rogin) ama in lagu weydiiyo oo lagu sheego war."],
        ti: ["እቲ {a}aller{/a} ዝብል ግሲ ምንቅስቓስ ንምግላጽ (ድሕሪኡ ቦታ ወይ መሰረታዊ ግሲ ይመጽእ) ወይ ዜና ንምሕታትን ንምሃብን ይጥቀም።"],
        tr: ["{a}aller{/a} fiili hareket belirtmek için kullanılır (bu durumda ardından bir yer veya mastar gelir) ya da hâl hatır sormak ve haber vermek için kullanılır."],
        ps: ["د {a}aller{/a} فعل د تګ راتګ ښودلو لپاره کارول کېږي (په دې حالت کې ورپسې ځای يا مصدر راځي) يا د احوال پوښتلو او خبر ورکولو لپاره کارول کېږي."],
        uk: ["Дієслово {a}aller{/a} вживається для позначення переміщення (тоді після нього стоїть місце або інфінітив), а також щоб запитати про справи чи повідомити новини."],
      },
    },
    {
      type: "grid",
      headers: ["Emploi", "Exemple"],
      transHeaders: {
        en: ["Use", "Example"],
        ar: ["الاستخدام", "مثال"],
        fa: ["کاربرد", "مثال"],
        pt: ["Uso", "Exemplo"],
        so: ["Isticmaal", "Tusaale"],
        ti: ["ኣጠቓቕማ", "ኣብነት"],
        tr: ["Kullanım", "Örnek"],
        ps: ["کارونه", "بېلګه"],
        uk: ["Вживання", "Приклад"],
      },
      colWidths: ["33%", "67%"],
      rows: [
        ["Déplacement", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."],
        ["Nouvelles", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."],
      ],
      transRows: {
        en: [["Movement", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["Asking how someone is", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        ar: [["تنقّل", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["السؤال عن الأحوال", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        fa: [["جابه‌جایی", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["احوال‌پرسی", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        pt: [["Deslocação", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["Perguntar como alguém está", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        so: [["Dhaqaaqid", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["Weydiinta xaaladda qof", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        ti: [["ምንቅስቓስ", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["ዜና ምሕታት", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        tr: [["Hareket", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["Birinin nasıl olduğunu sorma", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        ps: [["تګ راتګ", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["د چا د احوال پوښتنه", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
        uk: [["Переміщення", "Tu {a}vas{/a} où ?\nNous {a}allons{/a} en Espagne."], ["Запитання про справи", "Tu {a}vas{/a} bien ?\nOui, je {a}vais{/a} bien."]],
      },
    },
    {
      type: "heading",
      text: "Conjugaison",
      trans: { en: "Conjugation", ar: "التصريف", fa: "صرف", pt: "Conjugação", so: "Qorista falka", ti: "ምጽራይ", tr: "Çekim", ps: "ګردان", uk: "Дієвідміна" },
    },
    {
      type: "grid",
      headers: ["Pronom", "Aller", "Exemple"],
      transHeaders: {
        en: ["Pronoun", "Aller", "Example"],
        ar: ["الضمير", "Aller", "مثال"],
        fa: ["ضمیر", "Aller", "مثال"],
        pt: ["Pronome", "Aller", "Exemplo"],
        so: ["Magac-u-yaal", "Aller", "Tusaale"],
        ti: ["ተካኢ ስም", "Aller", "ኣብነት"],
        tr: ["Zamir", "Aller", "Örnek"],
        ps: ["ضمير", "Aller", "بېلګه"],
        uk: ["Займенник", "Aller", "Приклад"],
      },
      boldFirstCol: true,
      rows: [
        ["Je", "vais", "au cinéma."],
        ["Tu", "vas", "à la pharmacie."],
        ["Il / Elle / On", "va", "au théâtre."],
        ["Nous", "allons", "à la médiathèque."],
        ["Vous", "allez", "au gymnase."],
        ["Ils / Elles", "vont", "à la piscine."],
      ],
    },
    {
      type: "heading",
      text: "Prononciation",
      trans: { en: "Pronunciation", ar: "النطق", fa: "تلفظ", pt: "Pronúncia", so: "Ku dhawaaqid", ti: "ኣደማምጻ", tr: "Telaffuz", ps: "تلفظ", uk: "Вимова" },
    },
    {
      type: "plain_list",
      items: ["{a}1.{/a} On fait la liaison."],
      transItems: {
        en: ["{a}1.{/a} A liaison is made."],
        ar: ["{a}1.{/a} نُجري الوصل الصوتي."],
        fa: ["{a}1.{/a} پیوند آوایی انجام می‌شود."],
        pt: ["{a}1.{/a} Faz-se a liaison."],
        so: ["{a}1.{/a} Liaison ayaa la sameeyaa."],
        ti: ["{a}1.{/a} ሊያዞን ንገብር።"],
        tr: ["{a}1.{/a} Liaison yapılır."],
        ps: ["{a}1.{/a} ليازون ترسره کېږي."],
        uk: ["{a}1.{/a} Робимо лієзон."],
      },
    },
    {
      type: "highlight",
      label: "",
      items: ["Nou{li}s|a{/li}llons, vou{li}s|a{/li}llez."],
      noBulletItems: [0],
    },

    {
      type: "heading",
      text: "Verbes en -ayer, -oyer et -uyer",
      trans: { en: "Verbs in -ayer, -oyer and -uyer", ar: "أفعال -ayer / -oyer / -uyer", fa: "افعال -ayer / -oyer / -uyer", pt: "Verbos em -ayer, -oyer e -uyer", so: "Falalka ku dhammaada -ayer, -oyer iyo -uyer", ti: "ግሲያት -ayer / -oyer / -uyer", tr: "-ayer, -oyer ve -uyer ile biten fiiller", ps: "په -ayer، -oyer او -uyer پای ته رسېدونکي فعلونه", uk: "Дієслова на -ayer, -oyer і -uyer" },
    },
    {
      type: "plain_list",
      items: ["{a}1.{/a} Le {a}y{/a} devient {a}i{/a} devant une terminaison muette (je, tu, il, ils)."],
      transItems: {
        en: ["{a}1.{/a} The {a}y{/a} becomes {a}i{/a} before a silent ending (je, tu, il, ils)."],
        ar: ["{a}1.{/a} يتحول {a}y{/a} إلى {a}i{/a} قبل نهاية صامتة (je, tu, il, ils)."],
        fa: ["{a}1.{/a} حرف {a}y{/a} پیش از پایان بی‌صدا (je, tu, il, ils) به {a}i{/a} تبدیل می‌شود."],
        pt: ["{a}1.{/a} O {a}y{/a} passa a {a}i{/a} antes de uma terminação muda (je, tu, il, ils)."],
        so: ["{a}1.{/a} {a}y{/a} wuxuu isu beddelaa {a}i{/a} ka hor dhammaad aan la dhawaaqin (je, tu, il, ils)."],
        ti: ["{a}1.{/a} እቲ {a}y{/a} ቅድሚ ዘይድመጽ መወዳእታ (je, tu, il, ils) ናብ {a}i{/a} ይቕየር።"],
        tr: ["{a}1.{/a} {a}y{/a}, sessiz bir ekten önce {a}i{/a} olur (je, tu, il, ils)."],
        ps: ["{a}1.{/a} {a}y{/a} د بې غږه پای څخه مخکې په {a}i{/a} بدلېږي (je, tu, il, ils)."],
        uk: ["{a}1.{/a} {a}y{/a} перетворюється на {a}i{/a} перед німим закінченням (je, tu, il, ils)."],
      },
    },
    {
      type: "plain_list",
      items: ["{a}2.{/a} Avec {a}je, tu, il/elle/on, ils/elles{/a}, le {a}y{/a} du radical est remplacé par un {a}i{/a}."],
      transItems: {
        en: ["{a}2.{/a} With {a}je, tu, il/elle/on, ils/elles{/a}, the {a}y{/a} in the stem is replaced by an {a}i{/a}."],
        ar: ["{a}2.{/a} مع {a}je, tu, il/elle/on, ils/elles{/a}، يُستبدل {a}y{/a} في الجذر بـ {a}i{/a}."],
        fa: ["{a}2.{/a} با {a}je, tu, il/elle/on, ils/elles{/a}، حرف {a}y{/a} در بن با {a}i{/a} جایگزین می‌شود."],
        pt: ["{a}2.{/a} Com {a}je, tu, il/elle/on, ils/elles{/a}, o {a}y{/a} do radical é substituído por {a}i{/a}."],
        so: ["{a}2.{/a} Marka la joogo {a}je, tu, il/elle/on, ils/elles{/a}, {a}y{/a}-ga jirridda waxaa lagu beddelaa {a}i{/a}."],
        ti: ["{a}2.{/a} ምስ {a}je, tu, il/elle/on, ils/elles{/a}፣ እቲ ኣብ ሱር ዘሎ {a}y{/a} ብ {a}i{/a} ይትካእ።"],
        tr: ["{a}2.{/a} {a}je, tu, il/elle/on, ils/elles{/a} ile kökteki {a}y{/a}, {a}i{/a} ile değiştirilir."],
        ps: ["{a}2.{/a} له {a}je, tu, il/elle/on, ils/elles{/a} سره، د بن {a}y{/a} په {a}i{/a} بدلېږي."],
        uk: ["{a}2.{/a} З {a}je, tu, il/elle/on, ils/elles{/a} літера {a}y{/a} в основі замінюється на {a}i{/a}."],
      },
    },
    {
      type: "plain_list",
      items: ["{a}3.{/a} Les verbes en {a}-ayer{/a} ont deux orthographes possibles (paie / paye)."],
      transItems: {
        en: ["{a}3.{/a} Verbs ending in {a}-ayer{/a} have two possible spellings (paie / paye)."],
        ar: ["{a}3.{/a} للأفعال المنتهية بـ {a}-ayer{/a} طريقتان ممكنتان في الكتابة (paie / paye)."],
        fa: ["{a}3.{/a} فعل‌های پایان‌یافته به {a}-ayer{/a} دو املای ممکن دارند (paie / paye)."],
        pt: ["{a}3.{/a} Os verbos terminados em {a}-ayer{/a} têm duas grafias possíveis (paie / paye)."],
        so: ["{a}3.{/a} Falalka ku dhammaada {a}-ayer{/a} waxay leeyihiin laba higgaad oo suurtagal ah (paie / paye)."],
        ti: ["{a}3.{/a} ብ {a}-ayer{/a} ዝውድኡ ግሲታት ክልተ ናይ ኣጸሓሕፋ ኣማራጺታት ኣለዎም (paie / paye)።"],
        tr: ["{a}3.{/a} {a}-ayer{/a} ile biten fiillerin iki olası yazımı vardır (paie / paye)."],
        ps: ["{a}3.{/a} په {a}-ayer{/a} پای ته رسېدونکي فعلونه دوه ممکنه املاوې لري (paie / paye)."],
        uk: ["{a}3.{/a} Дієслова на {a}-ayer{/a} мають два можливі варіанти написання (paie / paye)."],
      },
    },
    {
      type: "verb_toggle",
      buttonCols: 3,
      verbs: [
        {
          infinitive: "payer", radical: "pay",
          rows: [
            { pronoun: "je", ending: "e", radical: "pai" },
            { pronoun: "tu", ending: "es", radical: "pai" },
            { pronoun: "il / elle / on", ending: "e", radical: "pai" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "pai" },
          ],
        },
        {
          infinitive: "nettoyer", radical: "nettoy",
          rows: [
            { pronoun: "je", ending: "e", radical: "nettoi" },
            { pronoun: "tu", ending: "es", radical: "nettoi" },
            { pronoun: "il / elle / on", ending: "e", radical: "nettoi" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "nettoi" },
          ],
        },
        {
          infinitive: "s'ennuyer", radical: "ennuy",
          reflexivePronouns: ["m'", "t'", "s'", "nous", "vous", "s'"],
          rows: [
            { pronoun: "je", ending: "e", radical: "ennui" },
            { pronoun: "tu", ending: "es", radical: "ennui" },
            { pronoun: "il / elle / on", ending: "e", radical: "ennui" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "ennui" },
          ],
        },
      ],
    },

    {
      type: "heading",
      text: "Verbes en -ger et -cer",
      trans: { en: "Verbs in -ger and -cer", ar: "أفعال -ger / -cer", fa: "افعال -ger / -cer", pt: "Verbos em -ger e -cer", so: "Falalka ku dhammaada -ger iyo -cer", ti: "ግሲያት -ger / -cer", tr: "-ger ve -cer ile biten fiiller", ps: "په -ger او -cer پای ته رسېدونکي فعلونه", uk: "Дієслова на -ger і -cer" },
    },
    {
      type: "plain_list",
      items: ["On ajoute {a}e{/a} après le {a}g{/a} à la forme {a}nous{/a} pour garder le son [ʒ]."],
      transItems: {
        en: ["An {a}e{/a} is added after {a}g{/a} in the {a}nous{/a} form to keep the [ʒ] sound."],
        ar: ["نضيف {a}e{/a} بعد {a}g{/a} في صيغة {a}nous{/a} للحفاظ على الصوت [ʒ]."],
        fa: ["برای حفظ صدای [ʒ]، در صورت {a}nous{/a} پس از {a}g{/a} یک {a}e{/a} اضافه می‌شود."],
        pt: ["Acrescenta-se um {a}e{/a} depois de {a}g{/a} na forma {a}nous{/a} para manter o som [ʒ]."],
        so: ["{a}e{/a} ayaa lagu daraa ka dib {a}g{/a} qaabka {a}nous{/a} si loo ilaaliyo dhawaaqa [ʒ]."],
        ti: ["እቲ [ʒ] ዝብል ድምጺ ንምዕቃብ፣ ኣብ ቅርጺ {a}nous{/a} ድሕሪ {a}g{/a} {a}e{/a} ንውስኽ።"],
        tr: ["[ʒ] sesini korumak için {a}nous{/a} biçiminde {a}g{/a}'den sonra bir {a}e{/a} eklenir."],
        ps: ["د [ʒ] غږ ساتلو لپاره، د {a}nous{/a} په بڼه کې له {a}g{/a} وروسته يو {a}e{/a} زياتېږي."],
        uk: ["У формі {a}nous{/a} після {a}g{/a} додається {a}e{/a}, щоб зберегти звук [ʒ]."],
      },
    },
    {
      type: "verb_toggle",
      buttonCols: 3,
      verbs: [
        {
          infinitive: "manger", radical: "mang",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "mange" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
        {
          infinitive: "voyager", radical: "voyag",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "voyage" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
        {
          infinitive: "changer", radical: "chang",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "change" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
      ],
    },
    {
      type: "plain_list",
      items: ["Le {a}c{/a} devient {a}ç{/a} devant {a}o{/a} à la forme {a}nous{/a} pour garder le son [s]."],
      transItems: {
        en: ["The {a}c{/a} becomes {a}ç{/a} before {a}o{/a} in the {a}nous{/a} form to keep the [s] sound."],
        ar: ["يتحول {a}c{/a} إلى {a}ç{/a} قبل {a}o{/a} في صيغة {a}nous{/a} للحفاظ على الصوت [s]."],
        fa: ["برای حفظ صدای [s]، در صورت {a}nous{/a} حرف {a}c{/a} پیش از {a}o{/a} به {a}ç{/a} تبدیل می‌شود."],
        pt: ["O {a}c{/a} passa a {a}ç{/a} antes de {a}o{/a} na forma {a}nous{/a} para manter o som [s]."],
        so: ["{a}c{/a} wuxuu isu beddelaa {a}ç{/a} ka hor {a}o{/a} qaabka {a}nous{/a} si loo ilaaliyo dhawaaqa [s]."],
        ti: ["እቲ [s] ዝብል ድምጺ ንምዕቃብ፣ ኣብ ቅርጺ {a}nous{/a} {a}c{/a} ቅድሚ {a}o{/a} ናብ {a}ç{/a} ይቕየር።"],
        tr: ["[s] sesini korumak için {a}nous{/a} biçiminde {a}o{/a}'dan önce {a}c{/a}, {a}ç{/a} olur."],
        ps: ["د [s] غږ ساتلو لپاره، د {a}nous{/a} په بڼه کې له {a}o{/a} مخکې {a}c{/a} په {a}ç{/a} بدلېږي."],
        uk: ["У формі {a}nous{/a} {a}c{/a} перетворюється на {a}ç{/a} перед {a}o{/a}, щоб зберегти звук [s]."],
      },
    },
    {
      type: "verb_toggle",
      buttonCols: 3,
      verbs: [
        {
          infinitive: "commencer", radical: "commenc",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "commenç" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
        {
          infinitive: "avancer", radical: "avanc",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "avanç" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
        {
          infinitive: "lancer", radical: "lanc",
          rows: [
            { pronoun: "je", ending: "e" },
            { pronoun: "tu", ending: "es" },
            { pronoun: "il / elle / on", ending: "e" },
            { pronoun: "nous", ending: "ons", radical: "lanç" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent" },
          ],
        },
      ],
    },

    {
      type: "heading",
      text: "Verbes en -eler, -eter et -érer",
      trans: { en: "Verbs in -eler, -eter and -érer", ar: "أفعال -eler / -eter / -érer", fa: "افعال -eler / -eter / -érer", pt: "Verbos em -eler, -eter e -érer", so: "Falalka ku dhammaada -eler, -eter iyo -érer", ti: "ግሲያት -eler / -eter / -érer", tr: "-eler, -eter ve -érer ile biten fiiller", ps: "په -eler، -eter او -érer پای ته رسېدونکي فعلونه", uk: "Дієслова на -eler, -eter і -érer" },
    },
    {
      type: "plain_list",
      items: [
        "{a}1.{/a} Avec {a}je, tu, il/elle/on, ils/elles{/a}, ces verbes ont une particularité orthographique qui change la prononciation.",
      ],
      transItems: {
        en: ["{a}1.{/a} With {a}je, tu, il/elle/on, ils/elles{/a}, these verbs have a spelling change that affects pronunciation."],
        ar: ["{a}1.{/a} مع {a}je, tu, il/elle/on, ils/elles{/a}، تتميز هذه الأفعال بتغيير إملائي يؤثر في النطق."],
        fa: ["{a}1.{/a} با {a}je, tu, il/elle/on, ils/elles{/a}، این فعل‌ها تغییر املایی ویژه‌ای دارند که تلفظ را عوض می‌کند."],
        pt: ["{a}1.{/a} Com {a}je, tu, il/elle/on, ils/elles{/a}, estes verbos têm uma alteração ortográfica que muda a pronúncia."],
        so: ["{a}1.{/a} Marka la joogo {a}je, tu, il/elle/on, ils/elles{/a}, ficilladani waxay leeyihiin isbeddel higgaad oo beddela ku dhawaaqidda."],
        ti: ["{a}1.{/a} ምስ {a}je, tu, il/elle/on, ils/elles{/a}፣ እዞም ግሲታት ንኣደማምጻ ዝቕይር ፍሉይ ኣጸሓሕፋ ኣለዎም።"],
        tr: ["{a}1.{/a} {a}je, tu, il/elle/on, ils/elles{/a} ile bu fiillerde telaffuzu etkileyen bir yazım değişikliği olur."],
        ps: ["{a}1.{/a} له {a}je, tu, il/elle/on, ils/elles{/a} سره، دا فعلونه يو املايي بدلون لري چې تلفظ بدلوي."],
        uk: ["{a}1.{/a} З {a}je, tu, il/elle/on, ils/elles{/a} ці дієслова мають орфографічну особливість, яка змінює вимову."],
      },
    },
    {
      type: "plain_list",
      items: [
        "{a}2.{/a} Ils ont deux radicaux : le 1er (comme l'infinitif) pour {a}nous{/a} et {a}vous{/a} ; le 2e (modifié) pour les autres personnes.",
      ],
      transItems: {
        en: ["{a}2.{/a} They have two stems: the 1st (as in the infinitive) for {a}nous{/a} and {a}vous{/a}; the 2nd (modified) for the other persons."],
        ar: ["{a}2.{/a} لها جذران: الأول (مثل المصدر) مع {a}nous{/a} و{a}vous{/a}؛ والثاني (المعدّل) مع بقية الأشخاص."],
        fa: ["{a}2.{/a} آن‌ها دو بن دارند: بن اول (مانند مصدر) برای {a}nous{/a} و {a}vous{/a}؛ بن دوم (تغییریافته) برای سایر اشخاص."],
        pt: ["{a}2.{/a} Têm dois radicais: o 1.º (como no infinitivo) para {a}nous{/a} e {a}vous{/a}; o 2.º (modificado) para as outras pessoas."],
        so: ["{a}2.{/a} Waxay leeyihiin laba jirridood: tan 1aad (sida falka aan la rogin) ee {a}nous{/a} iyo {a}vous{/a}; tan 2aad (la beddelay) ee dadka kale."],
        ti: ["{a}2.{/a} ክልተ ሱራት ኣለዎም፦ እቲ 1ይ (ከም መሰረታዊ ግሲ) ን {a}nous{/a}ን {a}vous{/a}ን፣ እቲ 2ይ (ዝተቐየረ) ንኻልኦት ሰባት።"],
        tr: ["{a}2.{/a} İki kökleri vardır: 1. kök ({a}nous{/a} ve {a}vous{/a} için mastardaki gibi); 2. kök (değişmiş) diğer kişiler için."],
        ps: ["{a}2.{/a} دوی دوه بنونه لري: لومړی (لکه په مصدر کې) د {a}nous{/a} او {a}vous{/a} لپاره؛ دوهم (بدل شوی) د نورو اشخاصو لپاره."],
        uk: ["{a}2.{/a} Вони мають дві основи: 1-шу (як в інфінітиві) для {a}nous{/a} і {a}vous{/a}; 2-гу (змінену) для інших осіб."],
      },
    },
    {
      type: "plain_list",
      items: ["{a}3.{/a} Les verbes comme {a}jeter{/a} doublent le {a}t{/a} devant une terminaison muette."],
      transItems: {
        en: ["{a}3.{/a} Verbs like {a}jeter{/a} double the {a}t{/a} before a silent ending."],
        ar: ["{a}3.{/a} الأفعال مثل {a}jeter{/a} تضاعف حرف {a}t{/a} قبل نهاية صامتة."],
        fa: ["{a}3.{/a} فعل‌هایی مانند {a}jeter{/a} پیش از پایان بی‌صدا حرف {a}t{/a} را دو برابر می‌کنند."],
        pt: ["{a}3.{/a} Verbos como {a}jeter{/a} duplicam o {a}t{/a} antes de uma terminação muda."],
        so: ["{a}3.{/a} Falalka sida {a}jeter{/a} waxay labanlaabaan {a}t{/a} ka hor dhammaad aan la dhawaaqin."],
        ti: ["{a}3.{/a} ከም {a}jeter{/a} ዝኣመሰሉ ግሲታት ቅድሚ ዘይድመጽ መወዳእታ {a}t{/a} ይደርቡ።"],
        tr: ["{a}3.{/a} {a}jeter{/a} gibi fiiller sessiz bir ekten önce {a}t{/a}'yi çift yazar."],
        ps: ["{a}3.{/a} د {a}jeter{/a} په شان فعلونه د بې غږه پای څخه مخکې {a}t{/a} دوه برابره کوي."],
        uk: ["{a}3.{/a} Дієслова на зразок {a}jeter{/a} подвоюють {a}t{/a} перед німим закінченням."],
      },
    },
    {
      type: "plain_list",
      items: ["{a}4.{/a} Les verbes comme {a}appeler{/a} doublent le {a}l{/a} devant une terminaison muette."],
      transItems: {
        en: ["{a}4.{/a} Verbs like {a}appeler{/a} double the {a}l{/a} before a silent ending."],
        ar: ["{a}4.{/a} الأفعال مثل {a}appeler{/a} تضاعف حرف {a}l{/a} قبل نهاية صامتة."],
        fa: ["{a}4.{/a} فعل‌هایی مانند {a}appeler{/a} پیش از پایان بی‌صدا حرف {a}l{/a} را دو برابر می‌کنند."],
        pt: ["{a}4.{/a} Verbos como {a}appeler{/a} duplicam o {a}l{/a} antes de uma terminação muda."],
        so: ["{a}4.{/a} Falalka sida {a}appeler{/a} waxay labanlaabaan {a}l{/a} ka hor dhammaad aan la dhawaaqin."],
        ti: ["{a}4.{/a} ከም {a}appeler{/a} ዝኣመሰሉ ግሲታት ቅድሚ ዘይድመጽ መወዳእታ {a}l{/a} ይደርቡ።"],
        tr: ["{a}4.{/a} {a}appeler{/a} gibi fiiller sessiz bir ekten önce {a}l{/a}'yi çift yazar."],
        ps: ["{a}4.{/a} د {a}appeler{/a} په شان فعلونه د بې غږه پای څخه مخکې {a}l{/a} دوه برابره کوي."],
        uk: ["{a}4.{/a} Дієслова на зразок {a}appeler{/a} подвоюють {a}l{/a} перед німим закінченням."],
      },
    },
    {
      type: "verb_toggle",
      buttonCols: 3,
      verbs: [
        {
          infinitive: "jeter", radical: "jet",
          rows: [
            { pronoun: "je", ending: "e", radical: "jett" },
            { pronoun: "tu", ending: "es", radical: "jett" },
            { pronoun: "il / elle / on", ending: "e", radical: "jett" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "jett" },
          ],
        },
        {
          infinitive: "appeler", radical: "appel",
          rows: [
            { pronoun: "j'", ending: "e", radical: "appell" },
            { pronoun: "tu", ending: "es", radical: "appell" },
            { pronoun: "il / elle / on", ending: "e", radical: "appell" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "appell" },
          ],
        },
        {
          infinitive: "préférer", radical: "préfér",
          rows: [
            { pronoun: "je", ending: "e", radical: "préfèr" },
            { pronoun: "tu", ending: "es", radical: "préfèr" },
            { pronoun: "il / elle / on", ending: "e", radical: "préfèr" },
            { pronoun: "nous", ending: "ons" },
            { pronoun: "vous", ending: "ez" },
            { pronoun: "ils / elles", ending: "ent", radical: "préfèr" },
          ],
        },
      ],
    },
  ],
  exercises: G1_EXERCISES["G1.8"](),
};
