import type { GrammarLesson } from "../../grammar-data";

/** Unité 15 — Le genre des adjectifs (G3.1) */
export const A1_GR_GENRE_ADJECTIFS: GrammarLesson = {
  slug: "a1-gr-genre-adjectifs",
  code: "G3.1",
  level: "A1",
  title: "Le genre des adjectifs",
  theory: [
    {
      type: "heading",
      text: "Les adjectifs",
      trans: { en: "Adjectives", ar: "الصفات", fa: "صفت‌ها", pt: "Adjetivos", so: "Sifooyin", ti: "ቅጽላት", tr: "Sıfatlar", ps: "صفتونه", uk: "Прикметники" },
    },
    {
      type: "text",
      noBulletItems: [0],
      items: [
        "L'adjectif donne une information sur le nom. Les adjectifs changent aussi selon le genre.",
      ],
      transItems: {
        en: ["The adjective gives information about the noun. Adjectives also change according to gender."],
        ar: ["الصفة تعطي معلومة عن الاسم. تتغير الصفات أيضًا حسب الجنس."],
        fa: ["صفت دربارهٔ اسم اطلاعات می‌دهد. صفت‌ها همچنین بر اساس جنس تغییر می‌کنند."],
        pt: ["O adjetivo dá informação sobre o nome. Os adjetivos também mudam conforme o género."],
        so: ["Sifadu waxay bixisaa macluumaad ku saabsan magaca. Sifooyinku sidoo kale way isbeddelaan iyadoo loo eegayo jinsiga."],
        ti: ["ቅጽል ብዛዕባ ስም ሓበሬታ ይህብ። ቅጽላት ከኣ ከም ጾታ ይቕየሩ።"],
        tr: ["Sıfat, isim hakkında bilgi verir. Sıfatlar cinsiyete göre de değişir."],
        ps: ["صفت د اسم په اړه معلومات ورکوي. صفتونه هم د جنس له مخې بدلېږي."],
        uk: ["Прикметник дає інформацію про іменник. Прикметники також змінюються за родом."],
      },
    },
    {
      type: "text",
      noBulletItems: [0],
      items: ["On ajoute souvent {a}-e{/a} au féminin."],
      transItems: {
        en: ["We often add {a}-e{/a} in the feminine."],
        ar: ["غالبًا نضيف {a}-e{/a} في المؤنث."],
        fa: ["اغلب برای مؤنث {a}-e{/a} اضافه می‌کنیم."],
        pt: ["Muitas vezes acrescentamos {a}-e{/a} no feminino."],
        so: ["Badanaa waxaan ku darnaa {a}-e{/a} qaabka dheddigga."],
        ti: ["ኣብ ኣንስታይ መብዛሕትኡ ግዜ {a}-e{/a} ንውስኽ።"],
        tr: ["Dişilde genellikle {a}-e{/a} ekleriz."],
        ps: ["په مؤنث کې ډېری وخت {a}-e{/a} ورزیاتوو."],
        uk: ["Часто додаємо {a}-e{/a} у жіночому роді."],
      },
    },
    {
      type: "grid",
      headers: ["Masculin", "Féminin"],
      transHeaders: {
        en: ["Masculine", "Feminine"],
        ar: ["المذكر", "المؤنث"],
        fa: ["مذکر", "مؤنث"],
        pt: ["Masculino", "Feminino"],
        so: ["Lab", "Dheddig"],
        ti: ["ተባዕታይ", "ኣንስታይ"],
        tr: ["Eril", "Dişil"],
        ps: ["مذکر", "مؤنث"],
        uk: ["Чоловічий рід", "Жіночий рід"],
      },
      equalCols: true,
      rows: [
        ["Le sac est petit.", "La voiture est petit{a}e{/a}."],
        ["Un homme français parle.", "Une femme français{a}e{/a} parle."],
      ],
    },
    {
      type: "text",
      items: [
        "Si l'adjectif masculin se termine déjà par {a}e{/a}, le féminin ne change pas.",
      ],
      transItems: {
        en: ["If the masculine adjective already ends in {a}e{/a}, the feminine does not change."],
        ar: ["إذا كانت الصفة المذكرة تنتهي أصلًا بـ {a}e{/a}، فإن المؤنث لا يتغير."],
        fa: ["اگر صفت مذکر از قبل به {a}e{/a} ختم شود، صورت مؤنث تغییر نمی‌کند."],
        pt: ["Se o adjetivo masculino já terminar em {a}e{/a}, o feminino não muda."],
        so: ["Haddii sifada lab ay hore ugu dhammaato {a}e{/a}, qaabka dheddiggu ma isbeddelo."],
        ti: ["እቲ ተባዕታይ ቅጽል ኣቐዲሙ ብ {a}e{/a} እንተወዲኡ፣ እቲ ኣንስታይ ኣይቕየርን።"],
        tr: ["Eril sıfat zaten {a}e{/a} ile bitiyorsa, dişil biçim değişmez."],
        ps: ["که مذکر صفت له مخکې په {a}e{/a} پای ته رسېږي، مؤنث یې نه بدلېږي."],
        uk: ["Якщо прикметник чоловічого роду вже закінчується на {a}e{/a}, жіноча форма не змінюється."],
      },
      noBulletItems: [0],
    },
    {
      type: "grid",
      headers: ["Masculin", "Féminin"],
      transHeaders: {
        en: ["Masculine", "Feminine"],
        ar: ["المذكر", "المؤنث"],
        fa: ["مذکر", "مؤنث"],
        pt: ["Masculino", "Feminino"],
        so: ["Lab", "Dheddig"],
        ti: ["ተባዕታይ", "ኣንስታይ"],
        tr: ["Eril", "Dişil"],
        ps: ["مذکر", "مؤنث"],
        uk: ["Чоловічий рід", "Жіночий рід"],
      },
      equalCols: true,
      rows: [
        ["Ce lit est modern{a}e{/a}.", "Cette chaise est modern{a}e{/a}."],
        ["Ce garçon est calm{a}e{/a}.", "Cette fille est calm{a}e{/a}."],
      ],
    },
    {
      type: "heading",
      text: "Cas particuliers",
      trans: { en: "Special cases", ar: "حالات خاصة", fa: "موارد خاص", pt: "Casos especiais", so: "Xaalado gaar ah", ti: "ፍሉያት ኩነታት", tr: "Özel durumlar", ps: "ځانګړي حالتونه", uk: "Особливі випадки" },
    },
    {
      type: "text",
      items: [
        "Certains adjectifs ont des terminaisons différentes au masculin et au féminin.",
      ],
      transItems: {
        en: ["Some adjectives have different endings in the masculine and feminine."],
        ar: ["بعض الصفات لها نهايات مختلفة في المذكر والمؤنث."],
        fa: ["برخی صفت‌ها در مذکر و مؤنث پایان‌های متفاوتی دارند."],
        pt: ["Alguns adjetivos têm terminações diferentes no masculino e no feminino."],
        so: ["Qaar ka mid ah sifooyinku waxay leeyihiin dhammaadyo kala duwan labka iyo dheddigga."],
        ti: ["ገለ ቅጽላት ኣብ ተባዕታይን ኣንስታይን ዝተፈላለዩ መወዳእታታት ኣለዎም።"],
        tr: ["Bazı sıfatların eril ve dişil biçimlerinde farklı son ekleri vardır."],
        ps: ["ځینې صفتونه په مذکر او مؤنث کې بېلابېلې پایې لري."],
        uk: ["Деякі прикметники мають різні закінчення в чоловічому та жіночому роді."],
      },
      noBulletItems: [0],
    },
    {
      type: "selector",
      buttonCols: 5,
      tabs: [
        {
          label: "-en",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-en{/a} au masculin changent en {a}-enne{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-en{/a} in the masculine change to {a}-enne{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-en{/a} في المذكر تصبح {a}-enne{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-en{/a} ختم می‌شوند در مؤنث به {a}-enne{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-en{/a} no masculino passam a {a}-enne{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-en{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-enne{/a}."],
                ti: ["ብተባዕታይ ብ {a}-en{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-enne{/a} ይቕየሩ።"],
                tr: ["{a}-en{/a} ile biten eril sözcükler dişilde {a}-enne{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-en{/a} پای ته رسېږي، په مؤنث کې {a}-enne{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-en{/a}, у жіночому роді змінюються на {a}-enne{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le meuble est anci{a}en{/a}.", "La table est anci{a}enne{/a}."],
                ["Le train est europé{a}en{/a}.", "La voiture est europé{a}enne{/a}."],
                ["Le prix est moy{a}en{/a}.", "La taille est moy{a}enne{/a}."],
              ],
            },
          ],
        },
        {
          label: "-on",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-on{/a} au masculin changent en {a}-onne{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-on{/a} in the masculine change to {a}-onne{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-on{/a} في المذكر تصبح {a}-onne{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-on{/a} ختم می‌شوند در مؤنث به {a}-onne{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-on{/a} no masculino passam a {a}-onne{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-on{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-onne{/a}."],
                ti: ["ብተባዕታይ ብ {a}-on{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-onne{/a} ይቕየሩ።"],
                tr: ["{a}-on{/a} ile biten eril sözcükler dişilde {a}-onne{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-on{/a} پای ته رسېږي، په مؤنث کې {a}-onne{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-on{/a}, у жіночому роді змінюються на {a}-onne{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le café est b{a}on{/a}.", "La tarte est b{a}onne{/a}."],
                ["Le chat est mign{a}on{/a}.", "La robe est mign{a}onne{/a}."],
                ["Il est bret{a}on{/a}.", "Elle est bret{a}onne{/a}."],
              ],
            },
          ],
        },
        {
          label: "-el",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-el{/a} au masculin changent en {a}-elle{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-el{/a} in the masculine change to {a}-elle{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-el{/a} في المذكر تصبح {a}-elle{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-el{/a} ختم می‌شوند در مؤنث به {a}-elle{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-el{/a} no masculino passam a {a}-elle{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-el{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-elle{/a}."],
                ti: ["ብተባዕታይ ብ {a}-el{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-elle{/a} ይቕየሩ።"],
                tr: ["{a}-el{/a} ile biten eril sözcükler dişilde {a}-elle{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-el{/a} پای ته رسېږي، په مؤنث کې {a}-elle{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-el{/a}, у жіночому роді змінюються на {a}-elle{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le parfum est natur{a}el{/a}.", "La fleur est natur{a}elle{/a}."],
                ["Le choix est personn{a}el{/a}.", "La lettre est personn{a}elle{/a}."],
                ["Le ton est form{a}el{/a}.", "La tenue est form{a}elle{/a}."],
              ],
            },
          ],
        },
        {
          label: "-er",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-er{/a} au masculin changent en {a}-ère{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-er{/a} in the masculine change to {a}-ère{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-er{/a} في المذكر تصبح {a}-ère{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-er{/a} ختم می‌شوند در مؤنث به {a}-ère{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-er{/a} no masculino passam a {a}-ère{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-er{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-ère{/a}."],
                ti: ["ብተባዕታይ ብ {a}-er{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-ère{/a} ይቕየሩ።"],
                tr: ["{a}-er{/a} ile biten eril sözcükler dişilde {a}-ère{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-er{/a} پای ته رسېږي، په مؤنث کې {a}-ère{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-er{/a}, у жіночому роді змінюються на {a}-ère{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Il est étrang{a}er{/a}.", "Elle est étrang{a}ère{/a}."],
                ["Le sac est ch{a}er{/a}.", "La robe est ch{a}ère{/a}."],
                ["C'est le premi{a}er{/a} jour.", "C'est la premi{a}ère{/a} fois."],
              ],
            },
          ],
        },
        {
          label: "-et",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-et{/a} au masculin changent en {a}-ète{/a} ou {a}-ette{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-et{/a} in the masculine change to {a}-ète{/a} or {a}-ette{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-et{/a} في المذكر تصبح {a}-ète{/a} أو {a}-ette{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-et{/a} ختم می‌شوند در مؤنث به {a}-ète{/a} یا {a}-ette{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-et{/a} no masculino passam a {a}-ète{/a} ou {a}-ette{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-et{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-ète{/a} ama {a}-ette{/a}."],
                ti: ["ብተባዕታይ ብ {a}-et{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-ète{/a} ወይ {a}-ette{/a} ይቕየሩ።"],
                tr: ["{a}-et{/a} ile biten eril sözcükler dişilde {a}-ète{/a} veya {a}-ette{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-et{/a} پای ته رسېږي، په مؤنث کې {a}-ète{/a} یا {a}-ette{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-et{/a}, у жіночому роді змінюються на {a}-ète{/a} або {a}-ette{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["L'hôtel est compl{a}et{/a}.", "La salle est compl{a}ète{/a}."],
                ["Le pull est viol{a}et{/a}.", "La robe est viol{a}ette{/a}."],
                ["Le plan est secr{a}et{/a}.", "La porte est secr{a}ète{/a}."],
              ],
            },
          ],
        },
        {
          label: "-eux",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-eux{/a} au masculin changent en {a}-euse{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-eux{/a} in the masculine change to {a}-euse{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-eux{/a} في المذكر تصبح {a}-euse{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-eux{/a} ختم می‌شوند در مؤنث به {a}-euse{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-eux{/a} no masculino passam a {a}-euse{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-eux{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-euse{/a}."],
                ti: ["ብተባዕታይ ብ {a}-eux{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-euse{/a} ይቕየሩ።"],
                tr: ["{a}-eux{/a} ile biten eril sözcükler dişilde {a}-euse{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-eux{/a} پای ته رسېږي، په مؤنث کې {a}-euse{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-eux{/a}, у жіночому роді змінюються на {a}-euse{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Il est heur{a}eux{/a}.", "Elle est heur{a}euse{/a}."],
                ["Il est séri{a}eux{/a}.", "Elle est séri{a}euse{/a}."],
                ["Il est joy{a}eux{/a}.", "Elle est joy{a}euse{/a}."],
              ],
            },
          ],
        },
        {
          label: "-eur",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-eur{/a} au masculin changent en {a}-euse{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-eur{/a} in the masculine change to {a}-euse{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-eur{/a} في المذكر تصبح {a}-euse{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-eur{/a} ختم می‌شوند در مؤنث به {a}-euse{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-eur{/a} no masculino passam a {a}-euse{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-eur{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-euse{/a}."],
                ti: ["ብተባዕታይ ብ {a}-eur{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-euse{/a} ይቕየሩ።"],
                tr: ["{a}-eur{/a} ile biten eril sözcükler dişilde {a}-euse{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-eur{/a} پای ته رسېږي، په مؤنث کې {a}-euse{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-eur{/a}, у жіночому роді змінюються на {a}-euse{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Il est travaill{a}eur{/a}.", "Elle est travaill{a}euse{/a}."],
                ["Il est ment{a}eur{/a}.", "Elle est ment{a}euse{/a}."],
                ["Il est rêv{a}eur{/a}.", "Elle est rêv{a}euse{/a}."],
              ],
            },
          ],
        },
        {
          label: "-f",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-f{/a} au masculin changent en {a}-ve{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-f{/a} in the masculine change to {a}-ve{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-f{/a} في المذكر تصبح {a}-ve{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-f{/a} ختم می‌شوند در مؤنث به {a}-ve{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-f{/a} no masculino passam a {a}-ve{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-f{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-ve{/a}."],
                ti: ["ብተባዕታይ ብ {a}-f{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-ve{/a} ይቕየሩ።"],
                tr: ["{a}-f{/a} ile biten eril sözcükler dişilde {a}-ve{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-f{/a} پای ته رسېږي، په مؤنث کې {a}-ve{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-f{/a}, у жіночому роді змінюються на {a}-ve{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le sac est neu{a}f{/a}.", "La voiture est neu{a}ve{/a}."],
                ["Il est acti{a}f{/a}.", "Elle est acti{a}ve{/a}."],
                ["Il est sporti{a}f{/a}.", "Elle est sporti{a}ve{/a}."],
              ],
            },
          ],
        },
        {
          label: "-eau",
          content: [
            {
              type: "text",
              items: [
                "Les mots terminant par {a}-eau{/a} au masculin changent en {a}-elle{/a} au féminin.",
              ],
              transItems: {
                en: ["Words ending in {a}-eau{/a} in the masculine change to {a}-elle{/a} in the feminine."],
                ar: ["الكلمات المنتهية بـ {a}-eau{/a} في المذكر تصبح {a}-elle{/a} في المؤنث."],
                fa: ["کلماتی که در مذکر به {a}-eau{/a} ختم می‌شوند در مؤنث به {a}-elle{/a} تغییر می‌کنند."],
                pt: ["As palavras terminadas em {a}-eau{/a} no masculino passam a {a}-elle{/a} no feminino."],
                so: ["Erayada ku dhammaada {a}-eau{/a} marka ay lab yihiin waxay dheddigga isu beddelaan {a}-elle{/a}."],
                ti: ["ብተባዕታይ ብ {a}-eau{/a} ዝውድኡ ቃላት ኣብ ኣንስታይ ናብ {a}-elle{/a} ይቕየሩ።"],
                tr: ["{a}-eau{/a} ile biten eril sözcükler dişilde {a}-elle{/a} olur."],
                ps: ["هغه کلمې چې په مذکر کې په {a}-eau{/a} پای ته رسېږي، په مؤنث کې {a}-elle{/a} ته بدلېږي."],
                uk: ["Слова, що в чоловічому роді закінчуються на {a}-eau{/a}, у жіночому роді змінюються на {a}-elle{/a}."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le dessin est b{a}eau{/a}.", "La peinture est b{a}elle{/a}."],
                ["Le lit est nouv{a}eau{/a}.", "La table est nouv{a}elle{/a}."],
                ["Le frère est jum{a}eau{/a}.", "La sœur est jum{a}elle{/a}."],
              ],
            },
          ],
        },
        {
          label: "Autres",
          content: [
            {
              type: "text",
              items: [
                "Certains adjectifs sont très irréguliers pour la formation du féminin.",
              ],
              transItems: {
                en: ["Some adjectives are very irregular when forming the feminine."],
                ar: ["بعض الصفات شديدة الشذوذ عند تكوين المؤنث."],
                fa: ["برخی صفت‌ها در ساختن صورت مؤنث بسیار بی‌قاعده‌اند."],
                pt: ["Alguns adjetivos são muito irregulares na formação do feminino."],
                so: ["Qaar ka mid ah sifooyinku aad bay u yihiin aan caadi ahayn marka la samaynayo qaabka dheddigga."],
                ti: ["ገለ ቅጽላት ኣብ ምፍጣር ኣንስታይ ቅርጺ ኣዝዮም ዘይስሩዓት እዮም።"],
                tr: ["Bazı sıfatlar dişil biçim oluştururken çok düzensizdir."],
                ps: ["ځینې صفتونه د مؤنث بڼې په جوړولو کې ډېر بې‌قاعده دي."],
                uk: ["Деякі прикметники дуже нерегулярні під час утворення жіночого роду."],
              },
              noBulletItems: [0],
            },
            {
              type: "grid",
              headers: ["Masculin", "Féminin"],
              transHeaders: {
                en: ["Masculine", "Feminine"],
                ar: ["المذكر", "المؤنث"],
                fa: ["مذکر", "مؤنث"],
                pt: ["Masculino", "Feminino"],
                so: ["Lab", "Dheddig"],
                ti: ["ተባዕታይ", "ኣንስታይ"],
                tr: ["Eril", "Dişil"],
                ps: ["مذکر", "مؤنث"],
                uk: ["Чоловічий рід", "Жіночий рід"],
              },
              equalCols: true,
              rows: [
                ["Le mur est ba{a}s{/a}.", "La chaise est ba{a}sse{/a}."],
                ["Le mur est blan{a}c{/a}.", "La robe est blan{a}che{/a}."],
                ["Le tissu est dou{a}x{/a}.", "La voix est dou{a}ce{/a}."],
                ["Le livre est épai{a}s{/a}.", "La couverture est épai{a}sse{/a}."],
                ["Le billet est fau{a}x{/a}.", "La clé est fau{a}sse{/a}."],
                ["Il est fo{a}u{/a}.", "Elle est fo{a}lle{/a}."],
                ["Le pain est frai{a}s{/a}.", "La salade est fraî{a}che{/a}."],
                ["Il est gent{a}il{/a}.", "Elle est gent{a}ille{/a}."],
                ["Il est gre{a}c{/a}.", "Elle est gre{a}cque{/a}."],
                ["Le chat est gro{a}s{/a}.", "La souris est gro{a}sse{/a}."],
                ["Il est jalo{a}ux{/a}.", "Elle est jalo{a}use{/a}."],
                ["Le chemin est lon{a}g{/a}.", "La rue est lon{a}gue{/a}."],
                ["Le score est nu{a}l{/a}.", "La note est nu{a}lle{/a}."],
                ["Le lieu est publi{a}c{/a}.", "La place est publi{a}que{/a}."],
                ["Il est rou{a}x{/a}.", "Elle est rou{a}sse{/a}."],
                ["Le linge est se{a}c{/a}.", "La serviette est sè{a}che{/a}."],
                ["Il est tur{a}c{/a}.", "Elle est tur{a}que{/a}."],
                ["Il est vie{a}ux{/a}.", "Elle est vie{a}ille{/a}."],
              ],
            },
          ],
        },
      ],
    },
    {
      type: "heading",
      text: "Adjectifs à trois formes masculines",
      trans: {
        en: "Adjectives with three masculine forms",
        ar: "صفات بثلاث صيغ مذكرة",
        fa: "صفت‌هایی با سه صورت مذکر",
        pt: "Adjetivos com três formas masculinas",
        so: "Sifooyin leh saddex qaab oo lab ah",
        ti: "ሰለስተ ተባዕታይ ቅርጺ ዘለዎም ቅጽላት",
        tr: "Üç eril biçimi olan sıfatlar",
        ps: "هغه صفتونه چې درې مذکرې بڼې لري",
        uk: "Прикметники з трьома формами чоловічого роду",
      },
    },
    {
      type: "text",
      items: [
        "Certains adjectifs ont une forme masculine spéciale devant une voyelle ou h muet.",
      ],
      transItems: {
        en: ["Some adjectives have a special masculine form before a vowel or silent h."],
        ar: ["بعض الصفات لها صيغة مذكرة خاصة قبل حرف متحرك أو h صامت."],
        fa: ["برخی صفت‌ها پیش از یک واکه یا h بی‌صدا صورت مذکر ویژه‌ای دارند."],
        pt: ["Alguns adjetivos têm uma forma masculina especial antes de uma vogal ou de h mudo."],
        so: ["Qaar ka mid ah sifooyinku waxay leeyihiin qaab lab oo gaar ah ka hor shaqal ama h aan la dhawaaqin."],
        ti: ["ገለ ቅጽላት ቅድሚ ናይ ድምጺ ፊደል ወይ h ዝሕባእ ፍሉይ ተባዕታይ ቅርጺ ኣለዎም።"],
        tr: ["Bazı sıfatların ünlüden veya sessiz h’den önce özel bir eril biçimi vardır."],
        ps: ["ځینې صفتونه د واکې یا بې‌غږه h مخکې ځانګړې مذکره بڼه لري."],
        uk: ["Деякі прикметники мають особливу форму чоловічого роду перед голосною або німим h."],
      },
      noBulletItems: [0],
    },
    {
      type: "grid",
      headers: [
        "Masculin\n+ Consonne",
        "Masculin\n+ Voyelle / h",
        "Féminin",
        "Pluriel\nmasculin",
      ],
      transHeaders: {
        en: [
          "Masculine + consonant",
          "Masculine + vowel / silent h",
          "Feminine",
          "Masculine plural",
        ],
        ar: [
          "المذكر + قبل حرف ساكن",
          "المذكر + قبل حرف متحرك / h صامت",
          "المؤنث",
          "جمع المذكر",
        ],
        fa: [
          "مذکر + پیش از همخوان",
          "مذکر + پیش از واکه / h بی‌صدا",
          "مؤنث",
          "جمع مذکر",
        ],
        pt: [
          "Masculino + consoante",
          "Masculino + vogal / h mudo",
          "Feminino",
          "Plural masculino",
        ],
        so: [
          "Lab + shibbane",
          "Lab + shaqal / h aan la dhawaaqin",
          "Dheddig",
          "Jamac lab",
        ],
        ti: [
          "ተባዕታይ + ተናባቢ",
          "ተባዕታይ + ናይ ድምጺ ፊደል / h ዘይድመጽ",
          "ኣንስተይቲ",
          "ብዙሕ ተባዕታይ",
        ],
        tr: [
          "Eril + ünsüz",
          "Eril + ünlü / sessiz h",
          "Dişil",
          "Eril çoğul",
        ],
        ps: [
          "مذکر + له بې‌واکه توري مخکې",
          "مذکر + له واکې / بې‌غږه h مخکې",
          "مؤنث",
          "مذکر جمع",
        ],
        uk: [
          "Чоловічий рід + перед приголосною",
          "Чоловічий рід + перед голосною / німим h",
          "Жіночий рід",
          "Множина чоловічого роду",
        ],
      },
      equalCols: true,
      rows: [
        ["beau", "bel", "belle", "beaux"],
        ["nouveau", "nouvel", "nouvelle", "nouveaux"],
        ["vieux", "vieil", "vieille", "vieux"],
        ["fou", "fol", "folle", "fous"],
        ["mou", "mol", "molle", "mous"],
      ],
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Exercice 1",
      instruction: "Choisissez la forme correcte.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "Cette fille est ___ .", choices: ["danoise", "danois", "danoises"], correctIdx: 0 },
        { sentence: "La table est ___ .", choices: ["ronde", "rond", "rondes"], correctIdx: 0 },
        { sentence: "Le bureau est ___ .", choices: ["carré", "carrée", "carrés"], correctIdx: 0 },
        { sentence: "Cette chaise est ___ .", choices: ["moderne", "modernes", "modern"], correctIdx: 0 },
        { sentence: "Une femme ___ arrive.", choices: ["française", "français", "françaises"], correctIdx: 0 },
        { sentence: "Un garçon ___ parle.", choices: ["français", "française", "françaises"], correctIdx: 0 },
        { sentence: "Ma sœur est ___ .", choices: ["heureuse", "heureux", "heureuses"], correctIdx: 0 },
        { sentence: "Mon frère est ___ .", choices: ["heureux", "heureuse", "heureuses"], correctIdx: 0 },
        { sentence: "La voisine est ___ .", choices: ["travailleuse", "travailleur", "travailleuses"], correctIdx: 0 },
        { sentence: "Le voisin est ___ .", choices: ["travailleur", "travailleuse", "travailleurs"], correctIdx: 0 },
        { sentence: "Cette robe est ___ .", choices: ["neuve", "neuf", "neuves"], correctIdx: 0 },
        { sentence: "Ce sac est ___ .", choices: ["neuf", "neuve", "neufs"], correctIdx: 0 },
        { sentence: "Une élève ___ écoute.", choices: ["sérieuse", "sérieux", "sérieuses"], correctIdx: 0 },
        { sentence: "Un élève ___ écoute.", choices: ["sérieux", "sérieuse", "sérieuses"], correctIdx: 0 },
        { sentence: "La voiture est ___ .", choices: ["blanche", "blanc", "blanches"], correctIdx: 0 },
        { sentence: "Le mur est ___ .", choices: ["blanc", "blanche", "blancs"], correctIdx: 0 },
        { sentence: "C'est une ___ maison.", choices: ["belle", "bel", "beau"], correctIdx: 0 },
        { sentence: "C'est un ___ appartement.", choices: ["bel", "belle", "beau"], correctIdx: 0 },
        { sentence: "C'est une ___ école.", choices: ["nouvelle", "nouveau", "nouveaux"], correctIdx: 0 },
        { sentence: "C'est un ___ ami.", choices: ["nouvel", "nouvelle", "nouveau"], correctIdx: 0 },
        { sentence: "La rue est ___ .", choices: ["longue", "long", "longs"], correctIdx: 0 },
        { sentence: "Le chemin est ___ .", choices: ["long", "longue", "longues"], correctIdx: 0 },
        { sentence: "La soupe est ___ .", choices: ["bonne", "bon", "bonnes"], correctIdx: 0 },
        { sentence: "Le café est ___ .", choices: ["bon", "bonne", "bons"], correctIdx: 0 },
        { sentence: "Cette actrice est ___ .", choices: ["naturelle", "naturel", "naturels"], correctIdx: 0 },
        { sentence: "Cet acteur est ___ .", choices: ["naturel", "naturelle", "naturels"], correctIdx: 0 },
        { sentence: "La réponse est ___ .", choices: ["complète", "complet", "complets"], correctIdx: 0 },
        { sentence: "Le dossier est ___ .", choices: ["complet", "complète", "complètes"], correctIdx: 0 },
        { sentence: "La robe est ___ .", choices: ["violette", "violet", "violets"], correctIdx: 0 },
        { sentence: "Le pull est ___ .", choices: ["violet", "violette", "violettes"], correctIdx: 0 },
        { sentence: "Cette femme est ___ .", choices: ["ancienne", "ancien", "anciens"], correctIdx: 0 },
        { sentence: "Ce livre est ___ .", choices: ["ancien", "ancienne", "anciennes"], correctIdx: 0 },
        { sentence: "Ma mère est ___ .", choices: ["gentille", "gentil", "gentils"], correctIdx: 0 },
        { sentence: "Mon père est ___ .", choices: ["gentil", "gentille", "gentilles"], correctIdx: 0 },
        { sentence: "La salade est ___ .", choices: ["fraîche", "frais", "fraîches"], correctIdx: 0 },
        { sentence: "Le pain est ___ .", choices: ["frais", "fraîche", "fraîches"], correctIdx: 0 },
        { sentence: "La serviette est ___ .", choices: ["sèche", "sec", "secs"], correctIdx: 0 },
        { sentence: "Le linge est ___ .", choices: ["sec", "sèche", "sèches"], correctIdx: 0 },
        { sentence: "La voix est ___ .", choices: ["douce", "doux", "douces"], correctIdx: 0 },
        { sentence: "Le tissu est ___ .", choices: ["doux", "douce", "douces"], correctIdx: 0 },
        { sentence: "La note est ___ .", choices: ["basse", "bas", "basses"], correctIdx: 0 },
        { sentence: "Le plafond est ___ .", choices: ["bas", "basse", "basses"], correctIdx: 0 },
        { sentence: "Elle est ___ .", choices: ["grecque", "grec", "grecs"], correctIdx: 0 },
        { sentence: "Il est ___ .", choices: ["grec", "grecque", "grecques"], correctIdx: 0 },
        { sentence: "Une fille ___ entre.", choices: ["rousse", "roux", "rousses"], correctIdx: 0 },
        { sentence: "Un garçon ___ entre.", choices: ["roux", "rousse", "rousses"], correctIdx: 0 },
        { sentence: "Cette histoire est ___ .", choices: ["fausse", "faux", "fausses"], correctIdx: 0 },
        { sentence: "Ce billet est ___ .", choices: ["faux", "fausse", "fausses"], correctIdx: 0 },
        { sentence: "Ma cousine est ___ .", choices: ["sportive", "sportif", "sportifs"], correctIdx: 0 },
        { sentence: "Mon cousin est ___ .", choices: ["sportif", "sportive", "sportives"], correctIdx: 0 },
      ],
    },
    {
      type: "fill",
      title: "Exercice 2",
      instruction: "Écrivez l'adjectif au féminin.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "petit → ___", hint: "+ e", answer: "petite" },
        { sentence: "grand → ___", hint: "+ e", answer: "grande" },
        { sentence: "noir → ___", hint: "+ e", answer: "noire" },
        { sentence: "bleu → ___", hint: "+ e", answer: "bleue" },
        { sentence: "joli → ___", hint: "+ e", answer: "jolie" },
        { sentence: "français → ___", hint: "+ e", answer: "française" },
        { sentence: "anglais → ___", hint: "+ e", answer: "anglaise" },
        { sentence: "danois → ___", hint: "+ e", answer: "danoise" },
        { sentence: "marocain → ___", hint: "+ e", answer: "marocaine" },
        { sentence: "brun → ___", hint: "+ e", answer: "brune" },
        { sentence: "espagnol → ___", hint: "+ e", answer: "espagnole" },
        { sentence: "allemand → ___", hint: "+ e", answer: "allemande" },
        { sentence: "américain → ___", hint: "+ e", answer: "américaine" },
        { sentence: "calme → ___", hint: "inchangé", answer: "calme" },
        { sentence: "moderne → ___", hint: "inchangé", answer: "moderne" },
        { sentence: "rapide → ___", hint: "inchangé", answer: "rapide" },
        { sentence: "jeune → ___", hint: "inchangé", answer: "jeune" },
        { sentence: "triste → ___", hint: "inchangé", answer: "triste" },
        { sentence: "ancien → ___", hint: "-en → -enne", answer: "ancienne" },
        { sentence: "italien → ___", hint: "-en → -enne", answer: "italienne" },
        { sentence: "moyen → ___", hint: "-en → -enne", answer: "moyenne" },
        { sentence: "bon → ___", hint: "-on → -onne", answer: "bonne" },
        { sentence: "mignon → ___", hint: "-on → -onne", answer: "mignonne" },
        { sentence: "breton → ___", hint: "-on → -onne", answer: "bretonne" },
        { sentence: "naturel → ___", hint: "-el → -elle", answer: "naturelle" },
        { sentence: "personnel → ___", hint: "-el → -elle", answer: "personnelle" },
        { sentence: "formel → ___", hint: "-el → -elle", answer: "formelle" },
        { sentence: "étranger → ___", hint: "-er → -ère", answer: "étrangère" },
        { sentence: "premier → ___", hint: "-er → -ère", answer: "première" },
        { sentence: "cher → ___", hint: "-er → -ère", answer: "chère" },
        { sentence: "complet → ___", hint: "-et → -ète", answer: "complète" },
        { sentence: "secret → ___", hint: "-et → -ète", answer: "secrète" },
        { sentence: "violet → ___", hint: "-et → -ette", answer: "violette" },
        { sentence: "heureux → ___", hint: "-eux → -euse", answer: "heureuse" },
        { sentence: "sérieux → ___", hint: "-eux → -euse", answer: "sérieuse" },
        { sentence: "joyeux → ___", hint: "-eux → -euse", answer: "joyeuse" },
        { sentence: "curieux → ___", hint: "-eux → -euse", answer: "curieuse" },
        { sentence: "travailleur → ___", hint: "-eur → -euse", answer: "travailleuse" },
        { sentence: "menteur → ___", hint: "-eur → -euse", answer: "menteuse" },
        { sentence: "rêveur → ___", hint: "-eur → -euse", answer: "rêveuse" },
        { sentence: "neuf → ___", hint: "-f → -ve", answer: "neuve" },
        { sentence: "actif → ___", hint: "-f → -ve", answer: "active" },
        { sentence: "sportif → ___", hint: "-f → -ve", answer: "sportive" },
        { sentence: "beau → ___", hint: "-eau → -elle", answer: "belle" },
        { sentence: "nouveau → ___", hint: "-eau → -elle", answer: "nouvelle" },
        { sentence: "jumeau → ___", hint: "-eau → -elle", answer: "jumelle" },
        { sentence: "blanc → ___", hint: "irrégulier", answer: "blanche" },
        { sentence: "long → ___", hint: "irrégulier", answer: "longue" },
        { sentence: "doux → ___", hint: "irrégulier", answer: "douce" },
        { sentence: "vieux → ___", hint: "irrégulier", answer: "vieille" },
      ],
    },
    {
      type: "fill",
      title: "Exercice 3",
      instruction: "Accordez l'adjectif si c'est nécessaire.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "Une fille ___ (sérieux).", hint: "féminin", answer: "sérieuse" },
        { sentence: "La table est ___ (rond).", hint: "féminin", answer: "ronde" },
        { sentence: "Cette robe est ___ (bleu).", hint: "féminin", answer: "bleue" },
        { sentence: "Ma sœur est ___ (petit).", hint: "féminin", answer: "petite" },
        { sentence: "La voisine est ___ (heureux).", hint: "féminin", answer: "heureuse" },
        { sentence: "Une femme est ___ (français).", hint: "féminin", answer: "française" },
        { sentence: "La voiture est ___ (neuf).", hint: "féminin", answer: "neuve" },
        { sentence: "Cette élève est ___ (actif).", hint: "féminin", answer: "active" },
        { sentence: "Ma cousine est ___ (sportif).", hint: "féminin", answer: "sportive" },
        { sentence: "Une amie est ___ (gentil).", hint: "féminin", answer: "gentille" },
        { sentence: "La maison est ___ (blanc).", hint: "féminin", answer: "blanche" },
        { sentence: "La rue est ___ (long).", hint: "féminin", answer: "longue" },
        { sentence: "Cette soupe est ___ (bon).", hint: "féminin", answer: "bonne" },
        { sentence: "La fleur est ___ (naturel).", hint: "féminin", answer: "naturelle" },
        { sentence: "La lettre est ___ (personnel).", hint: "féminin", answer: "personnelle" },
        { sentence: "La tenue est ___ (formel).", hint: "féminin", answer: "formelle" },
        { sentence: "Une touriste est ___ (étranger).", hint: "féminin", answer: "étrangère" },
        { sentence: "C'est la ___ fois (premier).", hint: "féminin", answer: "première" },
        { sentence: "La réponse est ___ (complet).", hint: "féminin", answer: "complète" },
        { sentence: "La porte est ___ (secret).", hint: "féminin", answer: "secrète" },
        { sentence: "La robe est ___ (violet).", hint: "féminin", answer: "violette" },
        { sentence: "La fille est ___ (curieux).", hint: "féminin", answer: "curieuse" },
        { sentence: "La sœur est ___ (joyeux).", hint: "féminin", answer: "joyeuse" },
        { sentence: "La voisine est ___ (travailleur).", hint: "féminin", answer: "travailleuse" },
        { sentence: "Une enfant est ___ (rêveur).", hint: "féminin", answer: "rêveuse" },
        { sentence: "Une chaise est ___ (ancien).", hint: "féminin", answer: "ancienne" },
        { sentence: "Une élève est ___ (italien).", hint: "féminin", answer: "italienne" },
        { sentence: "La taille est ___ (moyen).", hint: "féminin", answer: "moyenne" },
        { sentence: "Une chatte est ___ (mignon).", hint: "féminin", answer: "mignonne" },
        { sentence: "Une femme est ___ (breton).", hint: "féminin", answer: "bretonne" },
        { sentence: "Une robe est ___ (cher).", hint: "féminin", answer: "chère" },
        { sentence: "Une salade est ___ (frais).", hint: "féminin", answer: "fraîche" },
        { sentence: "Une serviette est ___ (sec).", hint: "féminin", answer: "sèche" },
        { sentence: "Une voix est ___ (doux).", hint: "féminin", answer: "douce" },
        { sentence: "Une dame est ___ (vieux).", hint: "féminin", answer: "vieille" },
        { sentence: "Une fille est ___ (calme).", hint: "inchangé", answer: "calme" },
        { sentence: "La classe est ___ (moderne).", hint: "inchangé", answer: "moderne" },
        { sentence: "Une voiture est ___ (rapide).", hint: "inchangé", answer: "rapide" },
        { sentence: "Une élève est ___ (jeune).", hint: "inchangé", answer: "jeune" },
        { sentence: "Une amie est ___ (triste).", hint: "inchangé", answer: "triste" },
        { sentence: "La voisine est ___ (timide).", hint: "inchangé", answer: "timide" },
        { sentence: "La sœur est ___ (malade).", hint: "inchangé", answer: "malade" },
        { sentence: "Une leçon est ___ (facile).", hint: "inchangé", answer: "facile" },
        { sentence: "Une chambre est ___ (propre).", hint: "inchangé", answer: "propre" },
        { sentence: "Une jupe est ___ (rouge).", hint: "inchangé", answer: "rouge" },
        { sentence: "Un garçon est ___ (petite).", hint: "masculin", answer: "petit" },
        { sentence: "Un chien est ___ (blanche).", hint: "masculin", answer: "blanc" },
        { sentence: "Un ami est ___ (heureuse).", hint: "masculin", answer: "heureux" },
        { sentence: "Un élève est ___ (sérieuse).", hint: "masculin", answer: "sérieux" },
        { sentence: "Un cousin est ___ (sportive).", hint: "masculin", answer: "sportif" },
      ],
    },
    {
      type: "fill",
      title: "Exercice 4",
      instruction: "Transformez les groupes nominaux au féminin.",
      items: [],
      poolSize: 5,
      inputWidth: "w-[32rem]",
      pool: [
        { sentence: "Un petit chat → ___", hint: "féminin", answer: "Une petite chatte" },
        { sentence: "Un grand frère → ___", hint: "féminin", answer: "Une grande sœur" },
        { sentence: "Un bon ami → ___", hint: "féminin", answer: "Une bonne amie" },
        { sentence: "Un vieux voisin → ___", hint: "féminin", answer: "Une vieille voisine" },
        { sentence: "Un bel acteur → ___", hint: "féminin", answer: "Une belle actrice" },
        { sentence: "Un nouveau serveur → ___", hint: "féminin", answer: "Une nouvelle serveuse" },
        { sentence: "Un chien blanc → ___", hint: "féminin", answer: "Une chienne blanche" },
        { sentence: "Un cousin sportif → ___", hint: "féminin", answer: "Une cousine sportive" },
        { sentence: "Un étudiant sérieux → ___", hint: "féminin", answer: "Une étudiante sérieuse" },
        { sentence: "Un musicien italien → ___", hint: "féminin", answer: "Une musicienne italienne" },
        { sentence: "Un boulanger français → ___", hint: "féminin", answer: "Une boulangère française" },
        { sentence: "Un danseur heureux → ___", hint: "féminin", answer: "Une danseuse heureuse" },
        { sentence: "Un chanteur joyeux → ___", hint: "féminin", answer: "Une chanteuse joyeuse" },
        { sentence: "Un vendeur poli → ___", hint: "féminin", answer: "Une vendeuse polie" },
        { sentence: "Un directeur gentil → ___", hint: "féminin", answer: "Une directrice gentille" },
        { sentence: "Un prince charmant → ___", hint: "féminin", answer: "Une princesse charmante" },
        { sentence: "Un roi ancien → ___", hint: "féminin", answer: "Une reine ancienne" },
        { sentence: "Un garçon timide → ___", hint: "féminin", answer: "Une fille timide" },
        { sentence: "Un homme calme → ___", hint: "féminin", answer: "Une femme calme" },
        { sentence: "Un élève rapide → ___", hint: "féminin", answer: "Une élève rapide" },
        { sentence: "Un voisin curieux → ___", hint: "féminin", answer: "Une voisine curieuse" },
        { sentence: "Un ami grec → ___", hint: "féminin", answer: "Une amie grecque" },
        { sentence: "Un voisin turc → ___", hint: "féminin", answer: "Une voisine turque" },
        { sentence: "Un garçon roux → ___", hint: "féminin", answer: "Une fille rousse" },
        { sentence: "Un homme doux → ___", hint: "féminin", answer: "Une femme douce" },
        { sentence: "Un garçon jaloux → ___", hint: "féminin", answer: "Une fille jalouse" },
        { sentence: "Un gros chat → ___", hint: "féminin", answer: "Une grosse chatte" },
        { sentence: "Un long chemin → ___", hint: "féminin", answer: "Une longue route" },
        { sentence: "Un café chaud → ___", hint: "féminin", answer: "Une soupe chaude" },
        { sentence: "Un sac neuf → ___", hint: "féminin", answer: "Une valise neuve" },
        { sentence: "Un meuble bas → ___", hint: "féminin", answer: "Une table basse" },
        { sentence: "Un billet faux → ___", hint: "féminin", answer: "Une pièce fausse" },
        { sentence: "Un pain frais → ___", hint: "féminin", answer: "Une salade fraîche" },
        { sentence: "Un linge sec → ___", hint: "féminin", answer: "Une serviette sèche" },
        { sentence: "Un pull violet → ___", hint: "féminin", answer: "Une robe violette" },
        { sentence: "Un bureau moderne → ___", hint: "féminin", answer: "Une chaise moderne" },
        { sentence: "Un stylo rouge → ___", hint: "féminin", answer: "Une gomme rouge" },
        { sentence: "Un livre épais → ___", hint: "féminin", answer: "Une couverture épaisse" },
        { sentence: "Un choix personnel → ___", hint: "féminin", answer: "Une question personnelle" },
        { sentence: "Un ton formel → ___", hint: "féminin", answer: "Une lettre formelle" },
        { sentence: "Un parfum naturel → ___", hint: "féminin", answer: "Une fleur naturelle" },
        { sentence: "Un prix moyen → ___", hint: "féminin", answer: "Une taille moyenne" },
        { sentence: "Un garçon mignon → ___", hint: "féminin", answer: "Une fille mignonne" },
        { sentence: "Un jeune Breton → ___", hint: "féminin", answer: "Une jeune Bretonne" },
        { sentence: "Un beau jumeau → ___", hint: "féminin", answer: "Une belle jumelle" },
        { sentence: "Un premier fils → ___", hint: "féminin", answer: "Une première fille" },
        { sentence: "Un cher oncle → ___", hint: "féminin", answer: "Une chère tante" },
        { sentence: "Un ancien ami → ___", hint: "féminin", answer: "Une ancienne amie" },
        { sentence: "Un employé actif → ___", hint: "féminin", answer: "Une employée active" },
        { sentence: "Un infirmier compétent → ___", hint: "féminin", answer: "Une infirmière compétente" },
      ],
    },
  ],
};
