import type { GrammarLesson } from "../../grammar-data";

/** Unité 19 — La place de l'adjectif (G3.4) */
export const A1_GR_PLACE_ADJECTIF: GrammarLesson = {
  slug: "a1-gr-place-adjectif",
  code: "G3.4",
  level: "A1",
  title: "La place de l'adjectif",
  theory: [
    {
      type: "heading",
      text: "Utilisation",
      trans: { en: "Usage", ar: "الاستخدام", fa: "کاربرد", pt: "Utilização", so: "Isticmaalka", ti: "ኣጠቓቕማ", tr: "Kullanım", ps: "کارونه", uk: "Вживання" },
    },
    {
      type: "text",
      text: "En général, l'adjectif qualificatif se place {a}après{/a} le nom.",
      transText: {
        en: "In general, a descriptive adjective is placed {a}after{/a} the noun.",
        ar: "عمومًا، تأتي الصفة الوصفية {a}بعد{/a} الاسم.",
        fa: "به طور کلی، صفت توصیفی {a}بعد{/a} از اسم می‌آید.",
        pt: "Em geral, o adjetivo qualificativo coloca-se {a}depois{/a} do nome.",
        so: "Guud ahaan, sifada tilmaanta waxaa la dhigaa {a}ka dib{/a} magaca.",
        ti: "ብሓፈሻ፣ ገላጺ ቅጽል {a}ድሕሪ{/a} ስም ይመጽእ።",
        tr: "Genel olarak niteleme sıfatı isimden {a}sonra{/a} gelir.",
        ps: "په عمومي ډول، توصیفي صفت د اسم {a}وروسته{/a} راځي.",
        uk: "Зазвичай описовий прикметник стоїть {a}після{/a} іменника.",
      },
      items: [
        "J'habite dans une maison {a}moderne{/a}.",
        "six milliard{a}s{/a} d'habitants",
      ],
    },
    {
      type: "text",
      text: "Les adjectifs se placent toujours après le nom lorsqu'ils indiquent :",
      transText: {
        en: "Adjectives are always placed after the noun when they indicate:",
        ar: "تأتي الصفات دائمًا بعد الاسم عندما تدل على:",
        fa: "صفت‌ها همیشه پس از اسم می‌آیند وقتی نشان‌دهندهٔ موارد زیر باشند:",
        pt: "Os adjetivos colocam-se sempre depois do nome quando indicam:",
        so: "Sifooyinka had iyo jeer waxaa la dhigaa ka dib magaca marka ay tilmaamayaan:",
        ti: "ቅጽላት ነዚ እንተመልከቱ ወትሩ ድሕሪ ስም ይመጹ፦",
        tr: "Sıfatlar şunları belirttiğinde her zaman isimden sonra gelir:",
        ps: "صفتونه تل د اسم وروسته راځي کله چې دا شیان ښيي:",
        uk: "Прикметники завжди стоять після іменника, коли вказують на:",
      },
    },
    {
      type: "grid",
      headers: ["Type", "Exemples"],
      transHeaders: {
        en: ["Type", "Examples"],
        ar: ["النوع", "أمثلة"],
        fa: ["نوع", "مثال‌ها"],
        pt: ["Tipo", "Exemplos"],
        so: ["Nooc", "Tusaalooyin"],
        ti: ["ዓይነት", "ኣብነታት"],
        tr: ["Tür", "Örnekler"],
        ps: ["ډول", "بېلګې"],
        uk: ["Тип", "Приклади"],
      },
      boldFirstCol: true,
      colWidths: ["32%", "68%"],
      rows: [
        ["la nationalité", "une amie {a}japonaise{/a}"],
        ["la couleur", "une voiture {a}rouge{/a}"],
        ["la forme", "une table {a}ronde{/a}"],
        ["la religion", "une école {a}catholique{/a}"],
        ["la matière", "une bague {a}métallique{/a}"],
        ["les adjectifs longs", "un exercice {a}intéressant{/a}"],
        ["les adjectifs participiaux", "une personne {a}fatiguée{/a}"],
      ],
      transRows: {
        en: [
          ["nationality", "une amie {a}japonaise{/a}"],
          ["color", "une voiture {a}rouge{/a}"],
          ["shape", "une table {a}ronde{/a}"],
          ["religion", "une école {a}catholique{/a}"],
          ["material", "une bague {a}métallique{/a}"],
          ["long adjectives", "un exercice {a}intéressant{/a}"],
          ["participial adjectives", "une personne {a}fatiguée{/a}"],
        ],
        ar: [
          ["الجنسية", "une amie {a}japonaise{/a}"],
          ["اللون", "une voiture {a}rouge{/a}"],
          ["الشكل", "une table {a}ronde{/a}"],
          ["الدين", "une école {a}catholique{/a}"],
          ["المادة", "une bague {a}métallique{/a}"],
          ["الصفات الطويلة", "un exercice {a}intéressant{/a}"],
          ["الصفات المشتقة من أسماء المفعول", "une personne {a}fatiguée{/a}"],
        ],
        fa: [
          ["ملیت", "une amie {a}japonaise{/a}"],
          ["رنگ", "une voiture {a}rouge{/a}"],
          ["شکل", "une table {a}ronde{/a}"],
          ["دین", "une école {a}catholique{/a}"],
          ["جنس / ماده", "une bague {a}métallique{/a}"],
          ["صفت‌های بلند", "un exercice {a}intéressant{/a}"],
          ["صفت‌های اسم مفعولی", "une personne {a}fatiguée{/a}"],
        ],
        pt: [
          ["nacionalidade", "une amie {a}japonaise{/a}"],
          ["cor", "une voiture {a}rouge{/a}"],
          ["forma", "une table {a}ronde{/a}"],
          ["religião", "une école {a}catholique{/a}"],
          ["material", "une bague {a}métallique{/a}"],
          ["adjetivos longos", "un exercice {a}intéressant{/a}"],
          ["adjetivos participiais", "une personne {a}fatiguée{/a}"],
        ],
        so: [
          ["jinsiyadda", "une amie {a}japonaise{/a}"],
          ["midabka", "une voiture {a}rouge{/a}"],
          ["qaabka", "une table {a}ronde{/a}"],
          ["diinta", "une école {a}catholique{/a}"],
          ["maaddada", "une bague {a}métallique{/a}"],
          ["sifooyinka dhaadheer", "un exercice {a}intéressant{/a}"],
          ["sifooyinka ka yimid fal-kaabayaasha", "une personne {a}fatiguée{/a}"],
        ],
        ti: [
          ["ዜግነት", "une amie {a}japonaise{/a}"],
          ["ሕብሪ", "une voiture {a}rouge{/a}"],
          ["ቅርጺ", "une table {a}ronde{/a}"],
          ["ሃይማኖት", "une école {a}catholique{/a}"],
          ["ንጥረ ነገር", "une bague {a}métallique{/a}"],
          ["ነዊሕ ቅጽላት", "un exercice {a}intéressant{/a}"],
          ["ቅጽላት ካብ ተሳታፊ ግሲ ዝመጹ", "une personne {a}fatiguée{/a}"],
        ],
        tr: [
          ["milliyet", "une amie {a}japonaise{/a}"],
          ["renk", "une voiture {a}rouge{/a}"],
          ["şekil", "une table {a}ronde{/a}"],
          ["din", "une école {a}catholique{/a}"],
          ["malzeme", "une bague {a}métallique{/a}"],
          ["uzun sıfatlar", "un exercice {a}intéressant{/a}"],
          ["ortaç kökenli sıfatlar", "une personne {a}fatiguée{/a}"],
        ],
        ps: [
          ["ملیت", "une amie {a}japonaise{/a}"],
          ["رنګ", "une voiture {a}rouge{/a}"],
          ["بڼه", "une table {a}ronde{/a}"],
          ["دین", "une école {a}catholique{/a}"],
          ["ماده", "une bague {a}métallique{/a}"],
          ["اوږده صفتونه", "un exercice {a}intéressant{/a}"],
          ["د اسم مفعول صفتونه", "une personne {a}fatiguée{/a}"],
        ],
        uk: [
          ["національність", "une amie {a}japonaise{/a}"],
          ["колір", "une voiture {a}rouge{/a}"],
          ["форма", "une table {a}ronde{/a}"],
          ["релігія", "une école {a}catholique{/a}"],
          ["матеріал", "une bague {a}métallique{/a}"],
          ["довгі прикметники", "un exercice {a}intéressant{/a}"],
          ["дієприкметникові прикметники", "une personne {a}fatiguée{/a}"],
        ],
      },
    },
    {
      type: "heading",
      text: "Les adjectifs placés avant le nom",
      trans: { en: "Adjectives placed before the noun", ar: "الصفات التي تأتي قبل الاسم", fa: "صفت‌هایی که پیش از اسم می‌آیند", pt: "Adjetivos colocados antes do nome", so: "Sifooyinka la dhigo ka hor magaca", ti: "ቅድሚ ስም ዝመጹ ቅጽላት", tr: "İsimden önce gelen sıfatlar", ps: "هغه صفتونه چې د اسم مخکې راځي", uk: "Прикметники перед іменником" },
    },
    {
      type: "text",
      text: "Certains adjectifs courts et très fréquents se placent généralement {a}avant{/a} le nom. Ils appartiennent souvent à la catégorie {a}BAGS{/a}.",
      transText: {
        en: "Some short and very common adjectives are usually placed {a}before{/a} the noun. They often belong to the {a}BAGS{/a} category.",
        ar: "بعض الصفات القصيرة والشائعة جدًا تأتي عادةً {a}قبل{/a} الاسم. وغالبًا ما تنتمي إلى فئة {a}BAGS{/a}.",
        fa: "برخی صفت‌های کوتاه و بسیار رایج معمولاً {a}پیش از{/a} اسم می‌آیند. آن‌ها اغلب به دستهٔ {a}BAGS{/a} تعلق دارند.",
        pt: "Alguns adjetivos curtos e muito frequentes colocam-se geralmente {a}antes{/a} do nome. Pertencem muitas vezes à categoria {a}BAGS{/a}.",
        so: "Qaar ka mid ah sifooyinka gaagaaban oo aad loo isticmaalo badanaa waxaa la dhigaa {a}ka hor{/a} magaca. Waxay inta badan ka tirsan yihiin qaybta {a}BAGS{/a}.",
        ti: "ገለ ሓጸርቲን ኣዝዮም ተደጋጋሚ ቅጽላትን ብሓፈሻ {a}ቅድሚ{/a} ስም ይመጹ። ብዙሕ ግዜ ናብ ምድብ {a}BAGS{/a} ይኣትዉ።",
        tr: "Bazı kısa ve çok yaygın sıfatlar genellikle isimden {a}önce{/a} gelir. Çoğu zaman {a}BAGS{/a} kategorisine girerler.",
        ps: "ځینې لنډ او ډېر کارېدونکي صفتونه عموماً د اسم {a}مخکې{/a} راځي. دوی ډېری وخت د {a}BAGS{/a} کټګورۍ پورې اړه لري.",
        uk: "Деякі короткі й дуже вживані прикметники зазвичай стоять {a}перед{/a} іменником. Вони часто належать до категорії {a}BAGS{/a}.",
      },
    },
    {
      type: "grid",
      headers: ["Catégorie", "Adjectifs fréquents"],
      transHeaders: {
        en: ["Category", "Common adjectives"],
        ar: ["الفئة", "الصفات الشائعة"],
        fa: ["دسته", "صفت‌های رایج"],
        pt: ["Categoria", "Adjetivos frequentes"],
        so: ["Qayb", "Sifooyin caadi ah"],
        ti: ["ምድብ", "ብዙሕ ዝጥቀሙሎም ቅጽላት"],
        tr: ["Kategori", "Yaygın sıfatlar"],
        ps: ["کټګوري", "عام صفتونه"],
        uk: ["Категорія", "Часті прикметники"],
      },
      boldFirstCol: true,
      colWidths: ["32%", "68%"],
      rows: [
        ["{a}B{/a}eauté", "C’est un {a}beau{/a} jardin.\nElle porte une {a}jolie{/a} robe."],
        ["{a}Â{/a}ge", "Un {a}jeune{/a} homme arrive.\nUn {a}vieux{/a} bâtiment est près d’ici.\nJ’ai un {a}nouveau{/a} téléphone.\nUn {a}ancien{/a} professeur travaille ici."],
        ["{a}G{/a}randeur", "Une {a}grande{/a} maison est à vendre.\nJ’ai un {a}petit{/a} sac.\nUn {a}gros{/a} chien court dans le parc.\nElle porte un {a}long{/a} manteau.\nIl achète un {a}court{/a} pantalon."],
        ["{a}S{/a}entiment", "Un {a}bon{/a} repas est préparé.\nUn {a}mauvais{/a} résultat arrive.\nUn {a}gentil{/a} garçon aide sa mère.\nUn {a}méchant{/a} homme crie dans la rue."],
      ],
    },
    {
      type: "heading",
      text: "Les adjectifs qui peuvent être avant ou après",
      trans: { en: "Adjectives that can be before or after", ar: "صفات يمكن أن تأتي قبل أو بعد الاسم", fa: "صفت‌هایی که می‌توانند پیش یا پس از اسم بیایند", pt: "Adjetivos que podem vir antes ou depois", so: "Sifooyin iman kara ka hor ama ka dib", ti: "ቅድሚ ወይ ድሕሪ ስም ክመጹ ዝኽእሉ ቅጽላት", tr: "Önce veya sonra gelebilen sıfatlar", ps: "هغه صفتونه چې مخکې یا وروسته راتلای شي", uk: "Прикметники, що можуть стояти перед або після іменника" },
    },
    {
      type: "text",
      text: "Certains adjectifs changent de place selon le sens recherché.",
      transText: {
        en: "Some adjectives change position depending on the intended meaning.",
        ar: "بعض الصفات تغيّر مكانها بحسب المعنى المقصود.",
        fa: "بعضی صفت‌ها بسته به معنای مورد نظر جای خود را تغییر می‌دهند.",
        pt: "Alguns adjetivos mudam de posição conforme o sentido pretendido.",
        so: "Qaar ka mid ah sifooyinka waxay beddelaan booskooda iyadoo ku xiran macnaha la rabo.",
        ti: "ገለ ቅጽላት ከከም ዝድለ ትርጉም ቦታኦም ይቕይሩ።",
        tr: "Bazı sıfatlar amaçlanan anlama göre yer değiştirir.",
        ps: "ځینې صفتونه د غوښتل شوي معنا له مخې خپل ځای بدلوي.",
        uk: "Деякі прикметники змінюють місце залежно від потрібного значення.",
      },
    },
    {
      type: "grid",
      headers: ["Adjectif", "Après le nom", "Avant le nom"],
      transHeaders: {
        en: ["Adjective", "After the noun", "Before the noun"],
        ar: ["الصفة", "بعد الاسم", "قبل الاسم"],
        fa: ["صفت", "بعد از اسم", "پیش از اسم"],
        pt: ["Adjetivo", "Depois do nome", "Antes do nome"],
        so: ["Sifo", "Ka dib magaca", "Ka hor magaca"],
        ti: ["ቅጽል", "ድሕሪ ስም", "ቅድሚ ስም"],
        tr: ["Sıfat", "İsimden sonra", "İsimden önce"],
        ps: ["صفت", "د اسم وروسته", "د اسم مخکې"],
        uk: ["Прикметник", "Після іменника", "Перед іменником"],
      },
      boldFirstCol: true,
      colWidths: ["22%", "39%", "39%"],
      rows: [
        ["ancien\nancienne", "un bâtiment ancien\n(= {a}vieux{/a})", "mon ancienne maison\n(= {a}précédente{/a})"],
        ["cher\nchère", "une voiture chère\n(= {a}coûteuse{/a})", "mon cher ami\n(= {a}bien-aimé{/a})"],
        ["curieux\ncurieuse", "des voisins curieux\n(= {a}indiscrets{/a})", "une curieuse histoire\n(= {a}étrange{/a})"],
        ["dernier\ndernière", "le mois dernier\n(= {a}précédent{/a})", "la dernière page\n(= {a}finale{/a})"],
        ["différent\ndifférente", "des exercices différents\n(= {a}variés{/a})", "différentes personnes\n(= {a}plusieurs{/a})"],
        ["grand\ngrande", "un homme grand\n(= {a}de grande taille{/a})", "un grand homme\n(= {a}célèbre{/a})"],
        ["pauvre", "un homme pauvre\n(= {a}sans argent{/a})", "ce pauvre homme\n(= {a}malheureux{/a})"],
        ["prochain\nprochaine", "la semaine prochaine\n(= {a}à venir{/a})", "le prochain train\n(= {a}le suivant{/a})"],
        ["petit\npetite", "une fille petite\n(= {a}de petite taille{/a})", "un petit cadeau\n(= {a}modeste{/a})"],
        ["propre", "une cuisine propre\n(= {a}nette{/a})", "ma propre chambre\n(= {a}à moi{/a})"],
        ["seul\nseule", "une personne seule\n(= {a}isolée{/a})", "une seule personne\n(= {a}une seule{/a})"],
        ["simple", "une idée simple\n(= {a}facile{/a})", "une simple erreur\n(= {a}seulement{/a})"],
        ["vrai\nvraie", "une histoire vraie\n(= {a}réelle{/a})", "un vrai ami\n(= {a}authentique{/a})"],
        ["brave", "un homme brave\n(= {a}courageux{/a})", "un brave homme\n(= {a}gentil{/a})"],
      ],
      transRows: {
        en: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}old{/a})", "mon ancienne maison\n(= {a}previous{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}expensive{/a})", "mon cher ami\n(= {a}beloved{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}nosy{/a})", "une curieuse histoire\n(= {a}strange{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}previous{/a})", "la dernière page\n(= {a}final{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}varied{/a})", "différentes personnes\n(= {a}several{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}tall{/a})", "un grand homme\n(= {a}famous{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}without money{/a})", "ce pauvre homme\n(= {a}unhappy{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}coming{/a})", "le prochain train\n(= {a}following{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}short{/a})", "un petit cadeau\n(= {a}modest{/a})"],
          ["propre", "une cuisine propre\n(= {a}clean{/a})", "ma propre chambre\n(= {a}my own{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}lonely{/a})", "une seule personne\n(= {a}only one{/a})"],
          ["simple", "une idée simple\n(= {a}easy{/a})", "une simple erreur\n(= {a}only{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}real{/a})", "un vrai ami\n(= {a}authentic{/a})"],
          ["brave", "un homme brave\n(= {a}courageous{/a})", "un brave homme\n(= {a}kind{/a})"],
        ],
        ar: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}قديم{/a})", "mon ancienne maison\n(= {a}سابق{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}غالي{/a})", "mon cher ami\n(= {a}محبوب{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}فضوليون{/a})", "une curieuse histoire\n(= {a}غريبة{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}سابق{/a})", "la dernière page\n(= {a}نهائية{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}متنوعة{/a})", "différentes personnes\n(= {a}عدة{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}طويل القامة{/a})", "un grand homme\n(= {a}مشهور{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}بدون مال{/a})", "ce pauvre homme\n(= {a}حزين{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}قادم{/a})", "le prochain train\n(= {a}التالي{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}قصيرة القامة{/a})", "un petit cadeau\n(= {a}متواضع{/a})"],
          ["propre", "une cuisine propre\n(= {a}نظيفة{/a})", "ma propre chambre\n(= {a}الخاصة بي{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}وحيدة{/a})", "une seule personne\n(= {a}شخص واحد فقط{/a})"],
          ["simple", "une idée simple\n(= {a}سهلة{/a})", "une simple erreur\n(= {a}فقط{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}حقيقية{/a})", "un vrai ami\n(= {a}أصيل{/a})"],
          ["brave", "un homme brave\n(= {a}شجاع{/a})", "un brave homme\n(= {a}طيب{/a})"],
        ],

        fa: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}قدیمی{/a})", "mon ancienne maison\n(= {a}قبلی{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}گران{/a})", "mon cher ami\n(= {a}عزیز{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}کنجکاو{/a})", "une curieuse histoire\n(= {a}عجیب{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}گذشته{/a})", "la dernière page\n(= {a}نهایی{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}متفاوت{/a})", "différentes personnes\n(= {a}چندین{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}قدبلند{/a})", "un grand homme\n(= {a}مشهور{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}بی‌پول{/a})", "ce pauvre homme\n(= {a}ناراحت{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}آینده{/a})", "le prochain train\n(= {a}بعدی{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}کوتاه‌قد{/a})", "un petit cadeau\n(= {a}کوچک{/a})"],
          ["propre", "une cuisine propre\n(= {a}تمیز{/a})", "ma propre chambre\n(= {a}خودم{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}تنها{/a})", "une seule personne\n(= {a}فقط یک نفر{/a})"],
          ["simple", "une idée simple\n(= {a}آسان{/a})", "une simple erreur\n(= {a}فقط{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}واقعی{/a})", "un vrai ami\n(= {a}حقیقی{/a})"],
          ["brave", "un homme brave\n(= {a}شجاع{/a})", "un brave homme\n(= {a}مهربان{/a})"],
        ],

        pt: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}velho{/a})", "mon ancienne maison\n(= {a}anterior{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}cara{/a})", "mon cher ami\n(= {a}querido{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}intrometidos{/a})", "une curieuse histoire\n(= {a}estranha{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}passado{/a})", "la dernière page\n(= {a}final{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}variados{/a})", "différentes personnes\n(= {a}várias{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}alto{/a})", "un grand homme\n(= {a}famoso{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}sem dinheiro{/a})", "ce pauvre homme\n(= {a}infeliz{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}próxima{/a})", "le prochain train\n(= {a}seguinte{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}baixa{/a})", "un petit cadeau\n(= {a}modesto{/a})"],
          ["propre", "une cuisine propre\n(= {a}limpa{/a})", "ma propre chambre\n(= {a}minha{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}isolada{/a})", "une seule personne\n(= {a}apenas uma{/a})"],
          ["simple", "une idée simple\n(= {a}fácil{/a})", "une simple erreur\n(= {a}somente{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}real{/a})", "un vrai ami\n(= {a}autêntico{/a})"],
          ["brave", "un homme brave\n(= {a}corajoso{/a})", "un brave homme\n(= {a}gentil{/a})"],
        ],
        so: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}duug{/a})", "mon ancienne maison\n(= {a}hore{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}qaali{/a})", "mon cher ami\n(= {a}la jecel yahay{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}xiisaynaya{/a})", "une curieuse histoire\n(= {a}yaab leh{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}hore{/a})", "la dernière page\n(= {a}ugu dambaysa{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}kala duwan{/a})", "différentes personnes\n(= {a}dhowr{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}dheer{/a})", "un grand homme\n(= {a}caan ah{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}sabool ah{/a})", "ce pauvre homme\n(= {a}nasiib daran{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}soo socota{/a})", "le prochain train\n(= {a}kan xiga{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}gaaban{/a})", "un petit cadeau\n(= {a}yar{/a})"],
          ["propre", "une cuisine propre\n(= {a}nadiif ah{/a})", "ma propre chambre\n(= {a}kayga{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}keligeed{/a})", "une seule personne\n(= {a}hal qof oo keliya{/a})"],
          ["simple", "une idée simple\n(= {a}fudud{/a})", "une simple erreur\n(= {a}keliya{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}dhab ah{/a})", "un vrai ami\n(= {a}run ah{/a})"],
          ["brave", "un homme brave\n(= {a}geesi{/a})", "un brave homme\n(= {a}wanaagsan{/a})"],
        ],

        ti: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}ዝጸንሐ{/a})", "mon ancienne maison\n(= {a}ቀዳማይ{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}ክብርቲ{/a})", "mon cher ami\n(= {a}ፍቱው{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}ዝግደሱ{/a})", "une curieuse histoire\n(= {a}ዘገርም{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}ዝሓለፈ{/a})", "la dernière page\n(= {a}መወዳእታ{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}ዝተፈላለዩ{/a})", "différentes personnes\n(= {a}ብዙሓት{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}ነዊሕ{/a})", "un grand homme\n(= {a}ዝነኣድ{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}ድኻ{/a})", "ce pauvre homme\n(= {a}ዘሕዝን{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}ዝመጽእ{/a})", "le prochain train\n(= {a}ዝስዕብ{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}ሓጻር{/a})", "un petit cadeau\n(= {a}ንእሽቶ{/a})"],
          ["propre", "une cuisine propre\n(= {a}ጽርይቲ{/a})", "ma propre chambre\n(= {a}ናተይ{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}በይና{/a})", "une seule personne\n(= {a}ሓደ ሰብ ጥራይ{/a})"],
          ["simple", "une idée simple\n(= {a}ቀሊል{/a})", "une simple erreur\n(= {a}ጥራይ{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}ሓቀኛ{/a})", "un vrai ami\n(= {a}ሓቀኛ{/a})"],
          ["brave", "un homme brave\n(= {a}ተባዕ{/a})", "un brave homme\n(= {a}ሕያዋይ{/a})"],
        ],

        tr: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}eski{/a})", "mon ancienne maison\n(= {a}önceki{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}pahalı{/a})", "mon cher ami\n(= {a}sevgili{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}meraklı{/a})", "une curieuse histoire\n(= {a}garip{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}geçen{/a})", "la dernière page\n(= {a}son{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}farklı{/a})", "différentes personnes\n(= {a}birkaç{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}uzun boylu{/a})", "un grand homme\n(= {a}ünlü{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}parasız{/a})", "ce pauvre homme\n(= {a}mutsuz{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}gelecek{/a})", "le prochain train\n(= {a}sonraki{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}kısa boylu{/a})", "un petit cadeau\n(= {a}küçük{/a})"],
          ["propre", "une cuisine propre\n(= {a}temiz{/a})", "ma propre chambre\n(= {a}kendi{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}yalnız{/a})", "une seule personne\n(= {a}tek bir kişi{/a})"],
          ["simple", "une idée simple\n(= {a}kolay{/a})", "une simple erreur\n(= {a}sadece{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}gerçek{/a})", "un vrai ami\n(= {a}gerçek{/a})"],
          ["brave", "un homme brave\n(= {a}cesur{/a})", "un brave homme\n(= {a}iyi{/a})"],
        ],
        ps: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}زوړ{/a})", "mon ancienne maison\n(= {a}پخوانی{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}ګران{/a})", "mon cher ami\n(= {a}ګران{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}لیواله{/a})", "une curieuse histoire\n(= {a}عجیبه{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}تېر{/a})", "la dernière page\n(= {a}وروستۍ{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}مختلف{/a})", "différentes personnes\n(= {a}څو{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}دنګ{/a})", "un grand homme\n(= {a}مشهور{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}بې وزله{/a})", "ce pauvre homme\n(= {a}بدمرغه{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}راتلونکې{/a})", "le prochain train\n(= {a}بل{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}ټیټه{/a})", "un petit cadeau\n(= {a}کوچنی{/a})"],
          ["propre", "une cuisine propre\n(= {a}پاکه{/a})", "ma propre chambre\n(= {a}زما خپله{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}یوازې{/a})", "une seule personne\n(= {a}یوازې یو کس{/a})"],
          ["simple", "une idée simple\n(= {a}اسانه{/a})", "une simple erreur\n(= {a}یوازې{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}ریښتینې{/a})", "un vrai ami\n(= {a}ریښتینی{/a})"],
          ["brave", "un homme brave\n(= {a}زړور{/a})", "un brave homme\n(= {a}ښه سړی{/a})"],
        ],

        uk: [
          ["ancien\nancienne", "un bâtiment ancien\n(= {a}старий{/a})", "mon ancienne maison\n(= {a}попередній{/a})"],
          ["cher\nchère", "une voiture chère\n(= {a}дорогий{/a})", "mon cher ami\n(= {a}любий{/a})"],
          ["curieux\ncurieuse", "des voisins curieux\n(= {a}допитливі{/a})", "une curieuse histoire\n(= {a}дивна{/a})"],
          ["dernier\ndernière", "le mois dernier\n(= {a}минулий{/a})", "la dernière page\n(= {a}остання{/a})"],
          ["différent\ndifférente", "des exercices différents\n(= {a}різні{/a})", "différentes personnes\n(= {a}кілька{/a})"],
          ["grand\ngrande", "un homme grand\n(= {a}високий{/a})", "un grand homme\n(= {a}відомий{/a})"],
          ["pauvre", "un homme pauvre\n(= {a}бідний{/a})", "ce pauvre homme\n(= {a}нещасний{/a})"],
          ["prochain\nprochaine", "la semaine prochaine\n(= {a}наступний{/a})", "le prochain train\n(= {a}наступний{/a})"],
          ["petit\npetite", "une fille petite\n(= {a}низька{/a})", "un petit cadeau\n(= {a}маленький{/a})"],
          ["propre", "une cuisine propre\n(= {a}чиста{/a})", "ma propre chambre\n(= {a}моя власна{/a})"],
          ["seul\nseule", "une personne seule\n(= {a}самотня{/a})", "une seule personne\n(= {a}лише одна{/a})"],
          ["simple", "une idée simple\n(= {a}легка{/a})", "une simple erreur\n(= {a}тільки{/a})"],
          ["vrai\nvraie", "une histoire vraie\n(= {a}справжня{/a})", "un vrai ami\n(= {a}справжній{/a})"],
          ["brave", "un homme brave\n(= {a}сміливий{/a})", "un brave homme\n(= {a}добрий{/a})"],
        ],
      }
    },
    {
      type: "heading",
      text: "Ordre des adjectifs",
      trans: { en: "Order of adjectives", ar: "ترتيب الصفات", fa: "ترتیب صفت‌ها", pt: "Ordem dos adjetivos", so: "Kala horreynta sifooyinka", ti: "ቅደም ሰዓብ ቅጽላት", tr: "Sıfatların sırası", ps: "د صفتونو ترتیب", uk: "Порядок прикметників" },
    },
    {
      type: "text",
      text: "Lorsqu'un nom est accompagné de plusieurs adjectifs, ils suivent généralement cet ordre :",
      transText: {
        en: "When a noun is accompanied by several adjectives, they generally follow this order:",
        ar: "عندما يرافق الاسم عدة صفات، فإنها تتبع عادةً هذا الترتيب:",
        fa: "وقتی یک اسم با چند صفت همراه است، آن‌ها معمولاً این ترتیب را دنبال می‌کنند:",
        pt: "Quando um nome é acompanhado por vários adjetivos, estes seguem geralmente esta ordem:",
        so: "Marka magac ay la socdaan dhowr sifo, badanaa waxay raacaan kala horreyntan:",
        ti: "ሓደ ስም ብብዙሓት ቅጽላት ምስ ዝስነ፣ ብሓፈሻ ነዚ ቅደም ሰዓብ ይኽተሉ፦",
        tr: "Bir isme birden fazla sıfat eşlik ettiğinde, genellikle şu sırayı izlerler:",
        ps: "کله چې یو اسم له څو صفتونو سره وي، عموماً دا ترتیب تعقیبوي:",
        uk: "Коли іменник має кілька прикметників, вони зазвичай дотримуються такого порядку:",
      },
    },
    {
      type: "text",
      text: "{a}1.{/a} adjectif numéral\n{a}2.{/a} adjectif BAGS\n{a}3.{/a} nom\n{a}4.{/a} adjectifs descriptifs",
      transText: {
        en: "{a}1.{/a} numeral adjective\n{a}2.{/a} BAGS adjective\n{a}3.{/a} noun\n{a}4.{/a} descriptive adjectives",
        ar: "{a}1.{/a} صفة عددية\n{a}2.{/a} صفة BAGS\n{a}3.{/a} اسم\n{a}4.{/a} صفات وصفية",
        fa: "{a}1.{/a} صفت عددی\n{a}2.{/a} صفت BAGS\n{a}3.{/a} اسم\n{a}4.{/a} صفت‌های توصیفی",
        pt: "{a}1.{/a} adjetivo numeral\n{a}2.{/a} adjetivo BAGS\n{a}3.{/a} nome\n{a}4.{/a} adjetivos qualificativos",
        so: "{a}1.{/a} sifo tiro\n{a}2.{/a} sifo BAGS\n{a}3.{/a} magac\n{a}4.{/a} sifooyin tilmaameed",
        ti: "{a}1.{/a} ቁጽራዊ ቅጽል\n{a}2.{/a} ቅጽል BAGS\n{a}3.{/a} ስም\n{a}4.{/a} ገላጺ ቅጽላት",
        tr: "{a}1.{/a} sayı sıfatı\n{a}2.{/a} BAGS sıfatı\n{a}3.{/a} isim\n{a}4.{/a} niteleme sıfatları",
        ps: "{a}1.{/a} شمېري صفت\n{a}2.{/a} د BAGS صفت\n{a}3.{/a} اسم\n{a}4.{/a} توصیفي صفتونه",
        uk: "{a}1.{/a} числівниковий прикметник\n{a}2.{/a} прикметник BAGS\n{a}3.{/a} іменник\n{a}4.{/a} описові прикметники",
      },
    },
    {
      type: "text",
      label: "Exemples",
      items: [
        "les trois petits chiens noirs",
        "les quatre nouveaux élèves français",
        "une grande maison blanche",
      ],
    },
    {
      type: "text",
      text: "L'adjectif placé le plus près du nom précise généralement sa caractéristique principale.",
      items: [
        "une élection {a}présidentielle{/a} espagnole",
        "une voiture {a}électrique{/a} allemande",
      ],
      transText: {
        en: "The adjective placed closest to the noun generally specifies its main characteristic.",
        ar: "الصفة الأقرب إلى الاسم تحدد عادةً صفته الرئيسية.",
        fa: "صفتی که نزدیک‌تر به اسم قرار می‌گیرد معمولاً ویژگی اصلی آن را مشخص می‌کند.",
        pt: "O adjetivo colocado mais perto do nome especifica geralmente a sua característica principal.",
        so: "Sifada ugu dhow magaca badanaa waxay si gaar ah u tilmaantaa astaantiisa ugu weyn.",
        ti: "እቲ ናብ ስም ቀረባ ዝተቐመጠ ቅጽል ብሓፈሻ ቀንዲ ባህርዩ ይገልጽ።",
        tr: "İsme en yakın duran sıfat genellikle onun temel özelliğini belirtir.",
        ps: "هغه صفت چې اسم ته تر ټولو نږدې ځای پر ځای شوی وي، عموماً د هغه اصلي ځانګړنه مشخصوي.",
        uk: "Прикметник, що стоїть найближче до іменника, зазвичай уточнює його головну ознаку.",
      },
    },
  ],
  exercises: [
    {
      type: "qcm",
      title: "Exercice 1",
      instruction: "Choisissez la formulation correcte.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "C'est ___ .", choices: ["une maison moderne", "une moderne maison", "une maison modernes"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un petit jardin", "un jardin petit", "une petit jardin"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une grande table", "une table grande", "un grande table"], correctIdx: 0 },
        { sentence: "J'ai ___ .", choices: ["un joli sac", "un sac joli", "une joli sac"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une nouvelle école", "une école nouvelle", "un nouvelle école"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un beau village", "un village beau", "une beau village"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un bel appartement", "un beau appartement", "une bel appartement"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un vieil arbre", "un vieux arbre", "une vieil arbre"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un vieux livre", "un livre vieux", "une vieux livre"], correctIdx: 0 },
        { sentence: "J'ai ___ .", choices: ["une petite voiture", "une voiture petite", "un petite voiture"], correctIdx: 0 },
        { sentence: "(= célèbre) C'est ___ .", choices: ["un grand homme", "un homme grand", "une grand homme"], correctIdx: 0 },
        { sentence: "(= de grande taille) C'est ___ .", choices: ["un homme grand", "un grand homme", "une homme grand"], correctIdx: 0 },
        { sentence: "Elle porte ___ .", choices: ["une robe rouge", "une rouge robe", "une robe rouges"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["des chaussures bleues", "des bleues chaussures", "des chaussures bleu"], correctIdx: 0 },
        { sentence: "Il porte ___ .", choices: ["un pantalon noir", "un noir pantalon", "une pantalon noir"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une voiture française", "une française voiture", "une voiture français"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["des amis suisses", "des suisses amis", "des ami suisses"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une table ronde", "une ronde table", "une table rond"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["des fenêtres carrées", "des carrées fenêtres", "des fenêtres carré"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une boîte métallique", "une métallique boîte", "un boîte métallique"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un exercice intéressant", "un intéressant exercice", "une exercice intéressant"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une personne fatiguée", "une fatiguée personne", "une personne fatigué"], correctIdx: 0 },
        { sentence: "(= d'avant) ___ était verte.", choices: ["Mon ancienne voiture", "Ma voiture ancienne", "Mon voiture ancienne"], correctIdx: 0 },
        { sentence: "(= vieille) Je collectionne ___ .", choices: ["une voiture ancienne", "une ancienne voiture", "un voiture ancienne"], correctIdx: 0 },
        { sentence: "(= malheureux) Je plains ___ .", choices: ["ce pauvre homme", "cet homme pauvre", "ce pauvres homme"], correctIdx: 0 },
        { sentence: "(= sans argent) C'est ___ .", choices: ["un homme pauvre", "un pauvre homme", "une homme pauvre"], correctIdx: 0 },
        { sentence: "(= à moi) J'ai ___ .", choices: ["ma propre chambre", "ma chambre propre", "mon propre chambre"], correctIdx: 0 },
        { sentence: "(= nette) C'est ___ .", choices: ["une chambre propre", "une propre chambre", "un chambre propre"], correctIdx: 0 },
        { sentence: "(= une seule) Il reste ___ .", choices: ["une seule personne", "une personne seule", "une seuls personne"], correctIdx: 0 },
        { sentence: "(= isolée) C'est ___ .", choices: ["une personne seule", "une seule personne", "une personne seuls"], correctIdx: 0 },
        { sentence: "(= seulement) C'est ___ .", choices: ["un simple détail", "un détail simple", "une simple détail"], correctIdx: 0 },
        { sentence: "(= facile) C'est ___ .", choices: ["une question simple", "une simple question", "un question simple"], correctIdx: 0 },
        { sentence: "(= authentique) C'est ___ .", choices: ["un vrai ami", "un ami vrai", "une vrai ami"], correctIdx: 0 },
        { sentence: "(= réelle) C'est ___ .", choices: ["une histoire vraie", "une vraie histoire", "un histoire vraie"], correctIdx: 0 },
        { sentence: "(= gentil) C'est ___ .", choices: ["un brave homme", "un homme brave", "une brave homme"], correctIdx: 0 },
        { sentence: "(= courageux) C'est ___ .", choices: ["un homme brave", "un brave homme", "une homme brave"], correctIdx: 0 },
        { sentence: "(= le suivant) Voici ___ .", choices: ["le prochain train", "le train prochain", "la prochain train"], correctIdx: 0 },
        { sentence: "(= à venir) C'est ___ .", choices: ["la semaine prochaine", "la prochaine semaine", "le semaine prochaine"], correctIdx: 0 },
        { sentence: "(= final) C'est ___ .", choices: ["le dernier exercice", "l'exercice dernier", "la dernier exercice"], correctIdx: 0 },
        { sentence: "(= précédent) C'était ___ .", choices: ["le mois dernier", "le dernier mois", "la mois dernier"], correctIdx: 0 },
        { sentence: "(= étrange) C'est ___ .", choices: ["une curieuse histoire", "une histoire curieuse", "un curieuse histoire"], correctIdx: 0 },
        { sentence: "(= indiscrète) C'est ___ .", choices: ["une voisine curieuse", "une curieuse voisine", "un voisine curieuse"], correctIdx: 0 },
        { sentence: "(= plusieurs) Il y a ___ .", choices: ["différentes réponses", "des réponses différentes", "différents réponses"], correctIdx: 0 },
        { sentence: "(= variées) Ce sont ___ .", choices: ["des réponses différentes", "différentes réponses", "des réponse différentes"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un bon repas", "un repas bon", "une bon repas"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une mauvaise idée", "une idée mauvaise", "un mauvaise idée"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un jeune étudiant", "un étudiant jeune", "une jeune étudiant"], correctIdx: 0 },
        { sentence: "Elle porte ___ .", choices: ["une chemise verte", "une verte chemise", "une chemise vert"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un canapé confortable", "un confortable canapé", "une canapé confortable"], correctIdx: 0 },
        { sentence: "J'achète ___ .", choices: ["un nouveau téléphone", "un téléphone nouveau", "une nouveau téléphone"], correctIdx: 0 },
      ],
    },
    {
      type: "qcm",
      title: "Exercice 2",
      instruction: "Choisissez la formulation correcte.",
      items: [],
      poolSize: 5,
      pool: [
        { sentence: "C'est ___ .", choices: ["une grande maison blanche", "une blanche grande maison", "une grande blanche maison"], correctIdx: 0 },
        { sentence: "J'ai ___ .", choices: ["un petit sac noir", "un noir petit sac", "un petit noir sac"], correctIdx: 0 },
        { sentence: "Elle porte ___ .", choices: ["une jolie robe rouge", "une rouge jolie robe", "une jolie rouge robe"], correctIdx: 0 },
        { sentence: "J'achète ___ .", choices: ["un nouveau téléphone portable", "un portable nouveau téléphone", "un nouveau portable téléphone"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un beau jardin public", "un public beau jardin", "un beau public jardin"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un bel appartement moderne", "un moderne bel appartement", "un bel moderne appartement"], correctIdx: 0 },
        { sentence: "Je regarde ___ .", choices: ["un vieil arbre vert", "un vert vieil arbre", "un vieil vert arbre"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une vieille maison suisse", "une suisse vieille maison", "une vieille suisse maison"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["les trois petits chiens", "les petits trois chiens", "les trois chiens petits"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["les deux grandes tables", "les grandes deux tables", "les deux tables grandes"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["les quatre nouveaux élèves", "les nouveaux quatre élèves", "les quatre élèves nouveaux"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["les cinq jolies fleurs", "les jolies cinq fleurs", "les cinq fleurs jolies"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["les deux beaux tableaux", "les beaux deux tableaux", "les deux tableaux beaux"], correctIdx: 0 },
        { sentence: "Je garde ___ .", choices: ["trois anciennes photos", "anciennes trois photos", "trois photos anciennes"], correctIdx: 0 },
        { sentence: "J'ai ___ .", choices: ["deux voitures rouges", "rouges deux voitures", "deux rouges voitures"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une voiture électrique allemande", "une allemande électrique voiture", "une électrique allemande voiture"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une table ronde blanche", "une blanche ronde table", "une ronde blanche table"], correctIdx: 0 },
        { sentence: "Je bois ___ .", choices: ["un bon café chaud", "un chaud bon café", "un bon chaud café"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une mauvaise réponse courte", "une courte mauvaise réponse", "une mauvaise courte réponse"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un jeune étudiant suisse", "un suisse jeune étudiant", "un jeune suisse étudiant"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une petite ville allemande", "une allemande petite ville", "une petite allemande ville"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un grand bâtiment ancien", "un ancien grand bâtiment", "un grand ancien bâtiment"], correctIdx: 0 },
        { sentence: "Je plains ___ .", choices: ["une pauvre femme fatiguée", "une fatiguée pauvre femme", "une pauvre fatiguée femme"], correctIdx: 0 },
        { sentence: "Il reste ___ .", choices: ["une seule place libre", "une libre seule place", "une seule libre place"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["ma propre chambre bleue", "ma bleue propre chambre", "ma propre bleue chambre"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un simple exercice facile", "un facile simple exercice", "un simple facile exercice"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une vraie histoire drôle", "une drôle vraie histoire", "une vraie drôle histoire"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un brave homme courageux", "un courageux brave homme", "un brave courageux homme"], correctIdx: 0 },
        { sentence: "Voici ___ .", choices: ["le dernier train suisse", "le suisse dernier train", "le dernier suisse train"], correctIdx: 0 },
        { sentence: "Voici ___ .", choices: ["le prochain bus rouge", "le rouge prochain bus", "le prochain rouge bus"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une curieuse histoire policière", "une policière curieuse histoire", "une curieuse policière histoire"], correctIdx: 0 },
        { sentence: "J'ai ___ .", choices: ["différentes idées originales", "originales différentes idées", "différentes originales idées"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["des réponses différentes difficiles", "des difficiles différentes réponses", "des réponses difficiles différentes"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un gros chien noir", "un noir gros chien", "un gros noir chien"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une longue rue droite", "une droite longue rue", "une longue droite rue"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un court message clair", "un clair court message", "un court clair message"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un gentil garçon suisse", "un suisse gentil garçon", "un gentil suisse garçon"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une méchante remarque gratuite", "une gratuite méchante remarque", "une méchante gratuite remarque"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un mauvais film américain", "un américain mauvais film", "un mauvais américain film"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un bon restaurant italien", "un italien bon restaurant", "un bon italien restaurant"], correctIdx: 0 },
        { sentence: "Elle porte ___ .", choices: ["une belle chemise verte", "une verte belle chemise", "une belle verte chemise"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["une petite fenêtre carrée", "une carrée petite fenêtre", "une petite carrée fenêtre"], correctIdx: 0 },
        { sentence: "C'est ___ .", choices: ["un joli vase métallique", "un métallique joli vase", "un joli métallique vase"], correctIdx: 0 },
        { sentence: "Il y a ___ .", choices: ["deux meubles blancs", "blancs deux meubles", "deux blancs meubles"], correctIdx: 0 },
        { sentence: "Il y a ___ .", choices: ["trois fenêtres rondes", "rondes trois fenêtres", "trois rondes fenêtres"], correctIdx: 0 },
        { sentence: "Il y a ___ .", choices: ["quatre voitures françaises", "françaises quatre voitures", "quatre françaises voitures"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["cinq grands arbres", "grands cinq arbres", "cinq arbres grands"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["deux vieux livres", "vieux deux livres", "deux livres vieux"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["trois bonnes idées", "bonnes trois idées", "trois idées bonnes"], correctIdx: 0 },
        { sentence: "Ce sont ___ .", choices: ["quatre jeunes élèves", "jeunes quatre élèves", "quatre élèves jeunes"], correctIdx: 0 },
      ],
    },
    {
      type: "word_order",
      title: "Exercice 3",
      instruction: "Remettez les mots dans le bon ordre.",
      items: [],
      poolSize: 5,
      poolMix: [
        { gabaritId: "1adj", count: 1 },
        { gabaritId: "2adj", count: 2 },
        { gabaritId: "3adj", count: 2 },
      ],
      pool: [
        { sentence: "une maison moderne", words: ["une", "maison", "moderne"], gabaritId: "1adj" },
        { sentence: "un petit jardin", words: ["un", "petit", "jardin"], gabaritId: "1adj" },
        { sentence: "une grande table", words: ["une", "grande", "table"], gabaritId: "1adj" },
        { sentence: "un joli sac", words: ["un", "joli", "sac"], gabaritId: "1adj" },
        { sentence: "une nouvelle école", words: ["une", "nouvelle", "école"], gabaritId: "1adj" },
        { sentence: "un beau village", words: ["un", "beau", "village"], gabaritId: "1adj" },
        { sentence: "un bel appartement", words: ["un", "bel", "appartement"], gabaritId: "1adj" },
        { sentence: "un vieil arbre", words: ["un", "vieil", "arbre"], gabaritId: "1adj" },
        { sentence: "un vieux livre", words: ["un", "vieux", "livre"], gabaritId: "1adj" },
        { sentence: "une petite voiture", words: ["une", "petite", "voiture"], gabaritId: "1adj" },
        { sentence: "une robe rouge", words: ["une", "robe", "rouge"], gabaritId: "1adj" },
        { sentence: "des chaussures bleues", words: ["des", "chaussures", "bleues"], gabaritId: "1adj" },
        { sentence: "un pantalon noir", words: ["un", "pantalon", "noir"], gabaritId: "1adj" },
        { sentence: "une voiture française", words: ["une", "voiture", "française"], gabaritId: "1adj" },
        { sentence: "des amis suisses", words: ["des", "amis", "suisses"], gabaritId: "1adj" },
        { sentence: "une table ronde", words: ["une", "table", "ronde"], gabaritId: "1adj" },
        { sentence: "des fenêtres carrées", words: ["des", "fenêtres", "carrées"], gabaritId: "1adj" },
        { sentence: "une boîte métallique", words: ["une", "boîte", "métallique"], gabaritId: "1adj" },
        { sentence: "un exercice intéressant", words: ["un", "exercice", "intéressant"], gabaritId: "1adj" },
        { sentence: "une personne fatiguée", words: ["une", "personne", "fatiguée"], gabaritId: "1adj" },
        { sentence: "mon ancienne voiture", words: ["mon", "ancienne", "voiture"], gabaritId: "1adj" },
        { sentence: "un homme pauvre", words: ["un", "homme", "pauvre"], gabaritId: "1adj" },
        { sentence: "ma propre chambre", words: ["ma", "propre", "chambre"], gabaritId: "1adj" },
        { sentence: "une seule personne", words: ["une", "seule", "personne"], gabaritId: "1adj" },
        { sentence: "le prochain train", words: ["le", "prochain", "train"], gabaritId: "1adj" },
        { sentence: "une grande maison blanche", words: ["une", "grande", "maison", "blanche"], gabaritId: "2adj" },
        { sentence: "un petit sac noir", words: ["un", "petit", "sac", "noir"], gabaritId: "2adj" },
        { sentence: "une jolie robe rouge", words: ["une", "jolie", "robe", "rouge"], gabaritId: "2adj" },
        { sentence: "un nouveau téléphone portable", words: ["un", "nouveau", "téléphone", "portable"], gabaritId: "2adj" },
        { sentence: "un beau jardin public", words: ["un", "beau", "jardin", "public"], gabaritId: "2adj" },
        { sentence: "un bel appartement moderne", words: ["un", "bel", "appartement", "moderne"], gabaritId: "2adj" },
        { sentence: "un vieil arbre vert", words: ["un", "vieil", "arbre", "vert"], gabaritId: "2adj" },
        { sentence: "une vieille maison suisse", words: ["une", "vieille", "maison", "suisse"], gabaritId: "2adj" },
        { sentence: "les trois petits chiens", words: ["les", "trois", "petits", "chiens"], gabaritId: "2adj" },
        { sentence: "les deux grandes tables", words: ["les", "deux", "grandes", "tables"], gabaritId: "2adj" },
        { sentence: "les quatre nouveaux élèves", words: ["les", "quatre", "nouveaux", "élèves"], gabaritId: "2adj" },
        { sentence: "les cinq jolies fleurs", words: ["les", "cinq", "jolies", "fleurs"], gabaritId: "2adj" },
        { sentence: "les deux beaux tableaux", words: ["les", "deux", "beaux", "tableaux"], gabaritId: "2adj" },
        { sentence: "trois anciennes photos", words: ["trois", "anciennes", "photos"], gabaritId: "2adj" },
        { sentence: "deux voitures rouges", words: ["deux", "voitures", "rouges"], gabaritId: "2adj" },
        { sentence: "une voiture électrique allemande", words: ["une", "voiture", "électrique", "allemande"], gabaritId: "2adj" },
        { sentence: "une table ronde blanche", words: ["une", "table", "ronde", "blanche"], gabaritId: "2adj" },
        { sentence: "un bon café chaud", words: ["un", "bon", "café", "chaud"], gabaritId: "2adj" },
        { sentence: "une mauvaise réponse courte", words: ["une", "mauvaise", "réponse", "courte"], gabaritId: "2adj" },
        { sentence: "un jeune étudiant suisse", words: ["un", "jeune", "étudiant", "suisse"], gabaritId: "2adj" },
        { sentence: "une petite ville allemande", words: ["une", "petite", "ville", "allemande"], gabaritId: "2adj" },
        { sentence: "un grand bâtiment ancien", words: ["un", "grand", "bâtiment", "ancien"], gabaritId: "2adj" },
        { sentence: "une pauvre femme fatiguée", words: ["une", "pauvre", "femme", "fatiguée"], gabaritId: "2adj" },
        { sentence: "une seule place libre", words: ["une", "seule", "place", "libre"], gabaritId: "2adj" },
        { sentence: "ma propre chambre bleue", words: ["ma", "propre", "chambre", "bleue"], gabaritId: "2adj" },
        { sentence: "les trois petits chiens noirs", words: ["les", "trois", "petits", "chiens", "noirs"], gabaritId: "3adj" },
        { sentence: "les deux grandes maisons blanches", words: ["les", "deux", "grandes", "maisons", "blanches"], gabaritId: "3adj" },
        { sentence: "les quatre nouveaux élèves français", words: ["les", "quatre", "nouveaux", "élèves", "français"], gabaritId: "3adj" },
        { sentence: "les cinq jolies robes rouges", words: ["les", "cinq", "jolies", "robes", "rouges"], gabaritId: "3adj" },
        { sentence: "les deux beaux jardins publics", words: ["les", "deux", "beaux", "jardins", "publics"], gabaritId: "3adj" },
        { sentence: "les trois vieux livres italiens", words: ["les", "trois", "vieux", "livres", "italiens"], gabaritId: "3adj" },
        { sentence: "les deux vieilles voitures vertes", words: ["les", "deux", "vieilles", "voitures", "vertes"], gabaritId: "3adj" },
        { sentence: "les six bonnes réponses courtes", words: ["les", "six", "bonnes", "réponses", "courtes"], gabaritId: "3adj" },
        { sentence: "les quatre mauvais films américains", words: ["les", "quatre", "mauvais", "films", "américains"], gabaritId: "3adj" },
        { sentence: "les trois jeunes étudiants suisses", words: ["les", "trois", "jeunes", "étudiants", "suisses"], gabaritId: "3adj" },
        { sentence: "les deux longues rues droites", words: ["les", "deux", "longues", "rues", "droites"], gabaritId: "3adj" },
        { sentence: "les cinq gros chats gris", words: ["les", "cinq", "gros", "chats", "gris"], gabaritId: "3adj" },
        { sentence: "les trois petits sacs noirs", words: ["les", "trois", "petits", "sacs", "noirs"], gabaritId: "3adj" },
        { sentence: "les deux grandes tables rondes", words: ["les", "deux", "grandes", "tables", "rondes"], gabaritId: "3adj" },
        { sentence: "les quatre jolies fleurs jaunes", words: ["les", "quatre", "jolies", "fleurs", "jaunes"], gabaritId: "3adj" },
        { sentence: "les trois nouveaux téléphones portables", words: ["les", "trois", "nouveaux", "téléphones", "portables"], gabaritId: "3adj" },
        { sentence: "les deux beaux tableaux modernes", words: ["les", "deux", "beaux", "tableaux", "modernes"], gabaritId: "3adj" },
        { sentence: "les cinq anciennes photos familiales", words: ["les", "cinq", "anciennes", "photos", "familiales"], gabaritId: "3adj" },
        { sentence: "les deux pauvres enfants fatigués", words: ["les", "deux", "pauvres", "enfants", "fatigués"], gabaritId: "3adj" },
        { sentence: "les trois seules places libres", words: ["les", "trois", "seules", "places", "libres"], gabaritId: "3adj" },
        { sentence: "mes deux propres chambres bleues", words: ["mes", "deux", "propres", "chambres", "bleues"], gabaritId: "3adj" },
        { sentence: "les trois simples exercices faciles", words: ["les", "trois", "simples", "exercices", "faciles"], gabaritId: "3adj" },
        { sentence: "les deux vraies histoires drôles", words: ["les", "deux", "vraies", "histoires", "drôles"], gabaritId: "3adj" },
        { sentence: "les quatre braves hommes courageux", words: ["les", "quatre", "braves", "hommes", "courageux"], gabaritId: "3adj" },
        { sentence: "les trois derniers trains suisses", words: ["les", "trois", "derniers", "trains", "suisses"], gabaritId: "3adj" },
      ],
    },
  ],
};
