import type { VocabTheme } from "../../vocabulary-data";

export const V10_ANIMAUX_THEME: VocabTheme = {
  slug: "v10-animaux",
  code: "V10.6",
  title: "Les animaux",
  titlePivot: {
    en: "Animals",
    ar: "الحيوانات",
    fa: "حیوانات",
    ti: "እንስሳታት",
    uk: "Тварини",
    pt: "Animais",
    so: "Xayawaanka",
    tr: "Hayvanlar",
    ps: "حیوانات",
  },
  section: "V10",
  imageFolder: "V9",
  words: [
    {
      word: "chat",
      image: "chat.webp",
      article: "le",
      gender: "m",
      group: "Animaux domestiques",
      definition: ["Petit animal domestique qui miaule."],
      definitionPivot: {
        en: "A small domestic animal that meows.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le chat sur l'image.",
          "Demain, je vais apprendre le mot chat.",
          "Ce matin, nous avons associé le chat à une image.",
          "Le professeur a expliqué le chat à la classe.",
          "Nous avons trouvé le chat dans le texte.",
          "Elle a noté chat pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot chat dans une phrase.",
          "Nous allons réviser chat avant l'évaluation.",
          "J'ai choisi chat parce que ce mot était dans la liste.",
          "Mon camarade a expliqué chat avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec chat.",
          "J'ai ajouté chat dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le chat paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme chat apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le chat, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chat, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le chat.",
          "Lorsque j'aurai mémorisé chat, je pourrai l'utiliser plus naturellement.",
          "Puisque chat est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "chien",
      image: "chien.webp",
      article: "le",
      gender: "m",
      group: "Animaux domestiques",
      definition: ["Animal domestique qui aboie."],
      definitionPivot: {
        en: "A domestic animal that barks.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le chien sur l'image.",
          "Demain, je vais apprendre le mot chien.",
          "Ce matin, nous avons associé le chien à une image.",
          "Le professeur a expliqué le chien à la classe.",
          "Nous avons trouvé le chien dans le texte.",
          "Elle a noté chien pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot chien dans une phrase.",
          "Nous allons réviser chien avant l'évaluation.",
          "J'ai choisi chien parce que ce mot était dans la liste.",
          "Mon camarade a expliqué chien avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec chien.",
          "J'ai ajouté chien dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le chien paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme chien apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le chien, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chien, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le chien.",
          "Lorsque j'aurai mémorisé chien, je pourrai l'utiliser plus naturellement.",
          "Puisque chien est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "poule",
      image: "poule.webp",
      article: "la",
      gender: "f",
      group: "Animaux de la ferme",
      definition: ["Oiseau de ferme qui pond des œufs."],
      definitionPivot: {
        en: "A farm bird that lays eggs.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu la poule sur l'image.",
          "Demain, je vais apprendre le mot poule.",
          "Ce matin, nous avons associé la poule à une image.",
          "Le professeur a expliqué la poule à la classe.",
          "Nous avons trouvé la poule dans le texte.",
          "Elle a noté poule pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot poule dans une phrase.",
          "Nous allons réviser poule avant l'évaluation.",
          "J'ai choisi poule parce que ce mot était dans la liste.",
          "Mon camarade a expliqué poule avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec poule.",
          "J'ai ajouté poule dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la poule paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme poule apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la poule, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà poule, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la poule.",
          "Lorsque j'aurai mémorisé poule, je pourrai l'utiliser plus naturellement.",
          "Puisque poule est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "coq",
      image: "coq.webp",
      article: "le",
      gender: "m",
      group: "Animaux de la ferme",
      definition: ["Oiseau de ferme, mâle de la poule."],
      definitionPivot: {
        en: "A farm bird, the male of the hen.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le coq sur l'image.",
          "Demain, je vais apprendre le mot coq.",
          "Ce matin, nous avons associé le coq à une image.",
          "Le professeur a expliqué le coq à la classe.",
          "Nous avons trouvé le coq dans le texte.",
          "Elle a noté coq pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot coq dans une phrase.",
          "Nous allons réviser coq avant l'évaluation.",
          "J'ai choisi coq parce que ce mot était dans la liste.",
          "Mon camarade a expliqué coq avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec coq.",
          "J'ai ajouté coq dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le coq paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme coq apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le coq, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà coq, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le coq.",
          "Lorsque j'aurai mémorisé coq, je pourrai l'utiliser plus naturellement.",
          "Puisque coq est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cochon",
      image: "cochon.webp",
      article: "le",
      gender: "m",
      group: "Animaux de la ferme",
      definition: ["Animal de ferme rose ou noir."],
      definitionPivot: {
        en: "A farm animal, often pink or black.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le cochon sur l'image.",
          "Demain, je vais apprendre le mot cochon.",
          "Ce matin, nous avons associé le cochon à une image.",
          "Le professeur a expliqué le cochon à la classe.",
          "Nous avons trouvé le cochon dans le texte.",
          "Elle a noté cochon pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot cochon dans une phrase.",
          "Nous allons réviser cochon avant l'évaluation.",
          "J'ai choisi cochon parce que ce mot était dans la liste.",
          "Mon camarade a expliqué cochon avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec cochon.",
          "J'ai ajouté cochon dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cochon paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme cochon apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le cochon, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cochon, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le cochon.",
          "Lorsque j'aurai mémorisé cochon, je pourrai l'utiliser plus naturellement.",
          "Puisque cochon est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "mouton",
      image: "mouton.webp",
      article: "le",
      gender: "m",
      group: "Animaux de la ferme",
      definition: ["Animal de ferme couvert de laine."],
      definitionPivot: {
        en: "A farm animal covered in wool.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le mouton sur l'image.",
          "Demain, je vais apprendre le mot mouton.",
          "Ce matin, nous avons associé le mouton à une image.",
          "Le professeur a expliqué le mouton à la classe.",
          "Nous avons trouvé le mouton dans le texte.",
          "Elle a noté mouton pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot mouton dans une phrase.",
          "Nous allons réviser mouton avant l'évaluation.",
          "J'ai choisi mouton parce que ce mot était dans la liste.",
          "Mon camarade a expliqué mouton avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec mouton.",
          "J'ai ajouté mouton dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le mouton paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme mouton apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le mouton, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà mouton, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le mouton.",
          "Lorsque j'aurai mémorisé mouton, je pourrai l'utiliser plus naturellement.",
          "Puisque mouton est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cheval",
      image: "cheval.webp",
      article: "le",
      gender: "m",
      group: "Animaux de la ferme",
      definition: ["Grand animal que l’on peut monter."],
      definitionPivot: {
        en: "A large animal that people can ride.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le cheval sur l'image.",
          "Demain, je vais apprendre le mot cheval.",
          "Ce matin, nous avons associé le cheval à une image.",
          "Le professeur a expliqué le cheval à la classe.",
          "Nous avons trouvé le cheval dans le texte.",
          "Elle a noté cheval pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot cheval dans une phrase.",
          "Nous allons réviser cheval avant l'évaluation.",
          "J'ai choisi cheval parce que ce mot était dans la liste.",
          "Mon camarade a expliqué cheval avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec cheval.",
          "J'ai ajouté cheval dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cheval paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme cheval apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le cheval, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cheval, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le cheval.",
          "Lorsque j'aurai mémorisé cheval, je pourrai l'utiliser plus naturellement.",
          "Puisque cheval est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "lapin",
      image: "lapin.webp",
      article: "le",
      gender: "m",
      group: "Animaux de la ferme",
      definition: ["Petit animal aux longues oreilles."],
      definitionPivot: {
        en: "A small animal with long ears.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le lapin sur l'image.",
          "Demain, je vais apprendre le mot lapin.",
          "Ce matin, nous avons associé le lapin à une image.",
          "Le professeur a expliqué le lapin à la classe.",
          "Nous avons trouvé le lapin dans le texte.",
          "Elle a noté lapin pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot lapin dans une phrase.",
          "Nous allons réviser lapin avant l'évaluation.",
          "J'ai choisi lapin parce que ce mot était dans la liste.",
          "Mon camarade a expliqué lapin avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec lapin.",
          "J'ai ajouté lapin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le lapin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme lapin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le lapin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà lapin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le lapin.",
          "Lorsque j'aurai mémorisé lapin, je pourrai l'utiliser plus naturellement.",
          "Puisque lapin est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "lion",
      image: "lion.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Grand félin sauvage appelé roi des animaux."],
      definitionPivot: {
        en: "A large wild cat called the king of animals.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le lion sur l'image.",
          "Demain, je vais apprendre le mot lion.",
          "Ce matin, nous avons associé le lion à une image.",
          "Le professeur a expliqué le lion à la classe.",
          "Nous avons trouvé le lion dans le texte.",
          "Elle a noté lion pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot lion dans une phrase.",
          "Nous allons réviser lion avant l'évaluation.",
          "J'ai choisi lion parce que ce mot était dans la liste.",
          "Mon camarade a expliqué lion avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec lion.",
          "J'ai ajouté lion dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le lion paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme lion apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le lion, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà lion, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le lion.",
          "Lorsque j'aurai mémorisé lion, je pourrai l'utiliser plus naturellement.",
          "Puisque lion est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "loup",
      image: "loup.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Animal sauvage proche du chien."],
      definitionPivot: {
        en: "A wild animal related to the dog.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le loup sur l'image.",
          "Demain, je vais apprendre le mot loup.",
          "Ce matin, nous avons associé le loup à une image.",
          "Le professeur a expliqué le loup à la classe.",
          "Nous avons trouvé le loup dans le texte.",
          "Elle a noté loup pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot loup dans une phrase.",
          "Nous allons réviser loup avant l'évaluation.",
          "J'ai choisi loup parce que ce mot était dans la liste.",
          "Mon camarade a expliqué loup avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec loup.",
          "J'ai ajouté loup dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le loup paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme loup apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le loup, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà loup, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le loup.",
          "Lorsque j'aurai mémorisé loup, je pourrai l'utiliser plus naturellement.",
          "Puisque loup est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "ours",
      image: "ours.webp",
      article: "l'",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Grand animal sauvage fort et poilu."],
      definitionPivot: {
        en: "A large strong furry wild animal.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu l'ours sur l'image.",
          "Demain, je vais apprendre le mot ours.",
          "Ce matin, nous avons associé l'ours à une image.",
          "Le professeur a expliqué l'ours à la classe.",
          "Nous avons trouvé l'ours dans le texte.",
          "Elle a noté ours pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot ours dans une phrase.",
          "Nous allons réviser ours avant l'évaluation.",
          "J'ai choisi ours parce que ce mot était dans la liste.",
          "Mon camarade a expliqué ours avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec ours.",
          "J'ai ajouté ours dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ours paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme ours apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ours, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ours, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ours.",
          "Lorsque j'aurai mémorisé ours, je pourrai l'utiliser plus naturellement.",
          "Puisque ours est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "renard",
      image: "renard.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Animal sauvage rusé, souvent roux."],
      definitionPivot: {
        en: "A cunning wild animal, often red.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le renard sur l'image.",
          "Demain, je vais apprendre le mot renard.",
          "Ce matin, nous avons associé le renard à une image.",
          "Le professeur a expliqué le renard à la classe.",
          "Nous avons trouvé le renard dans le texte.",
          "Elle a noté renard pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot renard dans une phrase.",
          "Nous allons réviser renard avant l'évaluation.",
          "J'ai choisi renard parce que ce mot était dans la liste.",
          "Mon camarade a expliqué renard avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec renard.",
          "J'ai ajouté renard dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le renard paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme renard apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le renard, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà renard, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le renard.",
          "Lorsque j'aurai mémorisé renard, je pourrai l'utiliser plus naturellement.",
          "Puisque renard est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "éléphant",
      image: "elephant.webp",
      article: "l'",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Très grand animal avec une trompe."],
      definitionPivot: {
        en: "A very large animal with a trunk.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu l'éléphant sur l'image.",
          "Demain, je vais apprendre le mot éléphant.",
          "Ce matin, nous avons associé l'éléphant à une image.",
          "Le professeur a expliqué l'éléphant à la classe.",
          "Nous avons trouvé l'éléphant dans le texte.",
          "Elle a noté éléphant pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot éléphant dans une phrase.",
          "Nous allons réviser éléphant avant l'évaluation.",
          "J'ai choisi éléphant parce que ce mot était dans la liste.",
          "Mon camarade a expliqué éléphant avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec éléphant.",
          "J'ai ajouté éléphant dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'éléphant paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme éléphant apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'éléphant, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà éléphant, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'éléphant.",
          "Lorsque j'aurai mémorisé éléphant, je pourrai l'utiliser plus naturellement.",
          "Puisque éléphant est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "girafe",
      image: "girafe.webp",
      article: "la",
      gender: "f",
      group: "Animaux sauvages",
      definition: ["Animal sauvage au très long cou."],
      definitionPivot: {
        en: "A wild animal with a very long neck.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu la girafe sur l'image.",
          "Demain, je vais apprendre le mot girafe.",
          "Ce matin, nous avons associé la girafe à une image.",
          "Le professeur a expliqué la girafe à la classe.",
          "Nous avons trouvé la girafe dans le texte.",
          "Elle a noté girafe pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot girafe dans une phrase.",
          "Nous allons réviser girafe avant l'évaluation.",
          "J'ai choisi girafe parce que ce mot était dans la liste.",
          "Mon camarade a expliqué girafe avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec girafe.",
          "J'ai ajouté girafe dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la girafe paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme girafe apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la girafe, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà girafe, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la girafe.",
          "Lorsque j'aurai mémorisé girafe, je pourrai l'utiliser plus naturellement.",
          "Puisque girafe est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "gorille",
      image: "gorille.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Grand singe sauvage très fort."],
      definitionPivot: {
        en: "A large strong wild ape.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le gorille sur l'image.",
          "Demain, je vais apprendre le mot gorille.",
          "Ce matin, nous avons associé le gorille à une image.",
          "Le professeur a expliqué le gorille à la classe.",
          "Nous avons trouvé le gorille dans le texte.",
          "Elle a noté gorille pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot gorille dans une phrase.",
          "Nous allons réviser gorille avant l'évaluation.",
          "J'ai choisi gorille parce que ce mot était dans la liste.",
          "Mon camarade a expliqué gorille avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec gorille.",
          "J'ai ajouté gorille dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le gorille paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme gorille apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le gorille, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà gorille, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le gorille.",
          "Lorsque j'aurai mémorisé gorille, je pourrai l'utiliser plus naturellement.",
          "Puisque gorille est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "zèbre",
      image: "zebre.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Animal sauvage avec des rayures noires et blanches."],
      definitionPivot: {
        en: "A wild animal with black and white stripes.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le zèbre sur l'image.",
          "Demain, je vais apprendre le mot zèbre.",
          "Ce matin, nous avons associé le zèbre à une image.",
          "Le professeur a expliqué le zèbre à la classe.",
          "Nous avons trouvé le zèbre dans le texte.",
          "Elle a noté zèbre pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot zèbre dans une phrase.",
          "Nous allons réviser zèbre avant l'évaluation.",
          "J'ai choisi zèbre parce que ce mot était dans la liste.",
          "Mon camarade a expliqué zèbre avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec zèbre.",
          "J'ai ajouté zèbre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le zèbre paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme zèbre apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le zèbre, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà zèbre, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le zèbre.",
          "Lorsque j'aurai mémorisé zèbre, je pourrai l'utiliser plus naturellement.",
          "Puisque zèbre est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "panda",
      image: "panda.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Animal noir et blanc qui mange du bambou."],
      definitionPivot: {
        en: "A black-and-white animal that eats bamboo.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le panda sur l'image.",
          "Demain, je vais apprendre le mot panda.",
          "Ce matin, nous avons associé le panda à une image.",
          "Le professeur a expliqué le panda à la classe.",
          "Nous avons trouvé le panda dans le texte.",
          "Elle a noté panda pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot panda dans une phrase.",
          "Nous allons réviser panda avant l'évaluation.",
          "J'ai choisi panda parce que ce mot était dans la liste.",
          "Mon camarade a expliqué panda avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec panda.",
          "J'ai ajouté panda dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le panda paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme panda apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le panda, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà panda, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le panda.",
          "Lorsque j'aurai mémorisé panda, je pourrai l'utiliser plus naturellement.",
          "Puisque panda est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "kangourou",
      image: "kangourou.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Animal qui saute et porte son petit dans une poche."],
      definitionPivot: {
        en: "An animal that jumps and carries its baby in a pouch.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le kangourou sur l'image.",
          "Demain, je vais apprendre le mot kangourou.",
          "Ce matin, nous avons associé le kangourou à une image.",
          "Le professeur a expliqué le kangourou à la classe.",
          "Nous avons trouvé le kangourou dans le texte.",
          "Elle a noté kangourou pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot kangourou dans une phrase.",
          "Nous allons réviser kangourou avant l'évaluation.",
          "J'ai choisi kangourou parce que ce mot était dans la liste.",
          "Mon camarade a expliqué kangourou avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec kangourou.",
          "J'ai ajouté kangourou dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le kangourou paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme kangourou apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le kangourou, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà kangourou, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le kangourou.",
          "Lorsque j'aurai mémorisé kangourou, je pourrai l'utiliser plus naturellement.",
          "Puisque kangourou est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "koala",
      image: "koala.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Petit animal d’Australie qui vit dans les arbres."],
      definitionPivot: {
        en: "A small Australian animal that lives in trees.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le koala sur l'image.",
          "Demain, je vais apprendre le mot koala.",
          "Ce matin, nous avons associé le koala à une image.",
          "Le professeur a expliqué le koala à la classe.",
          "Nous avons trouvé le koala dans le texte.",
          "Elle a noté koala pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot koala dans une phrase.",
          "Nous allons réviser koala avant l'évaluation.",
          "J'ai choisi koala parce que ce mot était dans la liste.",
          "Mon camarade a expliqué koala avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec koala.",
          "J'ai ajouté koala dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le koala paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme koala apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le koala, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà koala, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le koala.",
          "Lorsque j'aurai mémorisé koala, je pourrai l'utiliser plus naturellement.",
          "Puisque koala est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "rat",
      image: "rat.webp",
      article: "le",
      gender: "m",
      group: "Animaux sauvages",
      definition: ["Petit rongeur souvent gris."],
      definitionPivot: {
        en: "A small rodent, often grey.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le rat sur l'image.",
          "Demain, je vais apprendre le mot rat.",
          "Ce matin, nous avons associé le rat à une image.",
          "Le professeur a expliqué le rat à la classe.",
          "Nous avons trouvé le rat dans le texte.",
          "Elle a noté rat pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot rat dans une phrase.",
          "Nous allons réviser rat avant l'évaluation.",
          "J'ai choisi rat parce que ce mot était dans la liste.",
          "Mon camarade a expliqué rat avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec rat.",
          "J'ai ajouté rat dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le rat paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme rat apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le rat, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà rat, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le rat.",
          "Lorsque j'aurai mémorisé rat, je pourrai l'utiliser plus naturellement.",
          "Puisque rat est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "aigle",
      image: "aigle.webp",
      article: "l'",
      gender: "m",
      group: "Oiseaux",
      definition: ["Grand oiseau de proie."],
      definitionPivot: {
        en: "A large bird of prey.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu l'aigle sur l'image.",
          "Demain, je vais apprendre le mot aigle.",
          "Ce matin, nous avons associé l'aigle à une image.",
          "Le professeur a expliqué l'aigle à la classe.",
          "Nous avons trouvé l'aigle dans le texte.",
          "Elle a noté aigle pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot aigle dans une phrase.",
          "Nous allons réviser aigle avant l'évaluation.",
          "J'ai choisi aigle parce que ce mot était dans la liste.",
          "Mon camarade a expliqué aigle avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec aigle.",
          "J'ai ajouté aigle dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'aigle paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme aigle apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'aigle, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà aigle, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'aigle.",
          "Lorsque j'aurai mémorisé aigle, je pourrai l'utiliser plus naturellement.",
          "Puisque aigle est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "hibou",
      image: "hibou.webp",
      article: "le",
      gender: "m",
      group: "Oiseaux",
      definition: ["Oiseau nocturne aux grands yeux."],
      definitionPivot: {
        en: "A nocturnal bird with large eyes.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le hibou sur l'image.",
          "Demain, je vais apprendre le mot hibou.",
          "Ce matin, nous avons associé le hibou à une image.",
          "Le professeur a expliqué le hibou à la classe.",
          "Nous avons trouvé le hibou dans le texte.",
          "Elle a noté hibou pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot hibou dans une phrase.",
          "Nous allons réviser hibou avant l'évaluation.",
          "J'ai choisi hibou parce que ce mot était dans la liste.",
          "Mon camarade a expliqué hibou avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec hibou.",
          "J'ai ajouté hibou dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le hibou paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme hibou apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le hibou, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà hibou, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le hibou.",
          "Lorsque j'aurai mémorisé hibou, je pourrai l'utiliser plus naturellement.",
          "Puisque hibou est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "ibis",
      image: "ibis.webp",
      article: "l'",
      gender: "m",
      group: "Oiseaux",
      definition: ["Oiseau au long bec courbé."],
      definitionPivot: {
        en: "A bird with a long curved beak.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu l'ibis sur l'image.",
          "Demain, je vais apprendre le mot ibis.",
          "Ce matin, nous avons associé l'ibis à une image.",
          "Le professeur a expliqué l'ibis à la classe.",
          "Nous avons trouvé l'ibis dans le texte.",
          "Elle a noté ibis pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot ibis dans une phrase.",
          "Nous allons réviser ibis avant l'évaluation.",
          "J'ai choisi ibis parce que ce mot était dans la liste.",
          "Mon camarade a expliqué ibis avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec ibis.",
          "J'ai ajouté ibis dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ibis paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme ibis apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ibis, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ibis, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ibis.",
          "Lorsque j'aurai mémorisé ibis, je pourrai l'utiliser plus naturellement.",
          "Puisque ibis est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cygne",
      image: "cygne.webp",
      article: "le",
      gender: "m",
      group: "Oiseaux",
      definition: ["Grand oiseau blanc qui nage."],
      definitionPivot: {
        en: "A large white bird that swims.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le cygne sur l'image.",
          "Demain, je vais apprendre le mot cygne.",
          "Ce matin, nous avons associé le cygne à une image.",
          "Le professeur a expliqué le cygne à la classe.",
          "Nous avons trouvé le cygne dans le texte.",
          "Elle a noté cygne pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot cygne dans une phrase.",
          "Nous allons réviser cygne avant l'évaluation.",
          "J'ai choisi cygne parce que ce mot était dans la liste.",
          "Mon camarade a expliqué cygne avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec cygne.",
          "J'ai ajouté cygne dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cygne paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme cygne apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le cygne, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cygne, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le cygne.",
          "Lorsque j'aurai mémorisé cygne, je pourrai l'utiliser plus naturellement.",
          "Puisque cygne est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "canard",
      image: "canard.webp",
      article: "le",
      gender: "m",
      group: "Oiseaux",
      definition: ["Oiseau qui nage et fait coin-coin."],
      definitionPivot: {
        en: "A bird that swims and quacks.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le canard sur l'image.",
          "Demain, je vais apprendre le mot canard.",
          "Ce matin, nous avons associé le canard à une image.",
          "Le professeur a expliqué le canard à la classe.",
          "Nous avons trouvé le canard dans le texte.",
          "Elle a noté canard pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot canard dans une phrase.",
          "Nous allons réviser canard avant l'évaluation.",
          "J'ai choisi canard parce que ce mot était dans la liste.",
          "Mon camarade a expliqué canard avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec canard.",
          "J'ai ajouté canard dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le canard paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme canard apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le canard, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà canard, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le canard.",
          "Lorsque j'aurai mémorisé canard, je pourrai l'utiliser plus naturellement.",
          "Puisque canard est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "abeille",
      image: "abeille.webp",
      article: "l'",
      gender: "f",
      group: "Insectes",
      definition: ["Insecte qui produit le miel."],
      definitionPivot: {
        en: "An insect that makes honey.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu l'abeille sur l'image.",
          "Demain, je vais apprendre le mot abeille.",
          "Ce matin, nous avons associé l'abeille à une image.",
          "Le professeur a expliqué l'abeille à la classe.",
          "Nous avons trouvé l'abeille dans le texte.",
          "Elle a noté abeille pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot abeille dans une phrase.",
          "Nous allons réviser abeille avant l'évaluation.",
          "J'ai choisi abeille parce que ce mot était dans la liste.",
          "Mon camarade a expliqué abeille avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec abeille.",
          "J'ai ajouté abeille dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'abeille paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme abeille apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'abeille, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà abeille, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'abeille.",
          "Lorsque j'aurai mémorisé abeille, je pourrai l'utiliser plus naturellement.",
          "Puisque abeille est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "poisson",
      image: "poisson.webp",
      article: "le",
      gender: "m",
      group: "Animaux marins",
      definition: ["Animal qui vit dans l’eau et a des nageoires."],
      definitionPivot: {
        en: "An animal that lives in water and has fins.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le poisson sur l'image.",
          "Demain, je vais apprendre le mot poisson.",
          "Ce matin, nous avons associé le poisson à une image.",
          "Le professeur a expliqué le poisson à la classe.",
          "Nous avons trouvé le poisson dans le texte.",
          "Elle a noté poisson pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot poisson dans une phrase.",
          "Nous allons réviser poisson avant l'évaluation.",
          "J'ai choisi poisson parce que ce mot était dans la liste.",
          "Mon camarade a expliqué poisson avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec poisson.",
          "J'ai ajouté poisson dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le poisson paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme poisson apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le poisson, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà poisson, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le poisson.",
          "Lorsque j'aurai mémorisé poisson, je pourrai l'utiliser plus naturellement.",
          "Puisque poisson est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "dauphin",
      image: "dauphin.webp",
      article: "le",
      gender: "m",
      group: "Animaux marins",
      definition: ["Mammifère marin intelligent qui saute hors de l’eau."],
      definitionPivot: {
        en: "A smart sea mammal that jumps out of the water.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le dauphin sur l'image.",
          "Demain, je vais apprendre le mot dauphin.",
          "Ce matin, nous avons associé le dauphin à une image.",
          "Le professeur a expliqué le dauphin à la classe.",
          "Nous avons trouvé le dauphin dans le texte.",
          "Elle a noté dauphin pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot dauphin dans une phrase.",
          "Nous allons réviser dauphin avant l'évaluation.",
          "J'ai choisi dauphin parce que ce mot était dans la liste.",
          "Mon camarade a expliqué dauphin avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec dauphin.",
          "J'ai ajouté dauphin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le dauphin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme dauphin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le dauphin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà dauphin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le dauphin.",
          "Lorsque j'aurai mémorisé dauphin, je pourrai l'utiliser plus naturellement.",
          "Puisque dauphin est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "requin",
      image: "requin.webp",
      article: "le",
      gender: "m",
      group: "Animaux marins",
      definition: ["Grand poisson marin parfois dangereux."],
      definitionPivot: {
        en: "A large sea fish, sometimes dangerous.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu le requin sur l'image.",
          "Demain, je vais apprendre le mot requin.",
          "Ce matin, nous avons associé le requin à une image.",
          "Le professeur a expliqué le requin à la classe.",
          "Nous avons trouvé le requin dans le texte.",
          "Elle a noté requin pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot requin dans une phrase.",
          "Nous allons réviser requin avant l'évaluation.",
          "J'ai choisi requin parce que ce mot était dans la liste.",
          "Mon camarade a expliqué requin avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec requin.",
          "J'ai ajouté requin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le requin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme requin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le requin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà requin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le requin.",
          "Lorsque j'aurai mémorisé requin, je pourrai l'utiliser plus naturellement.",
          "Puisque requin est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "baleine",
      image: "baleine.webp",
      article: "la",
      gender: "f",
      group: "Animaux marins",
      definition: ["Très grand mammifère marin."],
      definitionPivot: {
        en: "A very large sea mammal.",
        ar: "حيوان.",
        fa: "یک حیوان.",
        pt: "Um animal.",
        so: "Xayawaan.",
        ti: "እንስሳ።",
        tr: "Bir hayvan.",
        ps: "حیوان.",
        uk: "Тварина.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai vu la baleine sur l'image.",
          "Demain, je vais apprendre le mot baleine.",
          "Ce matin, nous avons associé la baleine à une image.",
          "Le professeur a expliqué la baleine à la classe.",
          "Nous avons trouvé la baleine dans le texte.",
          "Elle a noté baleine pour ne pas l'oublier.",
          "Après la leçon, j'ai utilisé le mot baleine dans une phrase.",
          "Nous allons réviser baleine avant l'évaluation.",
          "J'ai choisi baleine parce que ce mot était dans la liste.",
          "Mon camarade a expliqué baleine avec ses mots.",
          "Pendant l'exercice, j'ai écrit une phrase avec baleine.",
          "J'ai ajouté baleine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la baleine paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme baleine apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la baleine, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà baleine, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la baleine.",
          "Lorsque j'aurai mémorisé baleine, je pourrai l'utiliser plus naturellement.",
          "Puisque baleine est utile, je le révise régulièrement.",
        ],
      },
    }
  ],
};
