import type { VocabTheme } from "../../vocabulary-data";

export const V5_STRUCTURE_ECOLE_THEME: VocabTheme = {
  slug: "v5-structure-ecole",
  code: "V5.3",
  title: "La structure de l'école",
  section: "V5",
  words: [
    { word: "école",        image: "ecole.webp",        article: "l'",  gender: "f", definition: "L'école est établissement où l'on apprend." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé l'école pendant l'exercice.",
          "Demain, je vais ranger l'école.",
          "Quand j'étais petit, je voyais souvent l'école à la maison.",
          "Ce matin, j'ai cherché l'école.",
          "Nous avons placé l'école près de la porte.",
          "Ils vont utiliser l'école cette semaine.",
          "J'ai choisi l'école parce que c'était pratique.",
          "Elle a nettoyé l'école avant de partir.",
          "Avant le cours, nous avons préparé l'école.",
          "Le groupe a observé l'école sur l'image.",
          "Je vais prendre l'école après le repas.",
          "Nous avons comparé l'école avec un autre objet.",
          "Hier soir, mon frère a déplacé l'école.",
          "Pendant les vacances, nous utilisions souvent l'école.",
          "Elle a oublié l'école dans la salle.",
          "Il va dessiner l'école dans son cahier.",
          "Nous avons trouvé l'école dans le placard.",
          "Ce week-end, je vais réparer l'école.",
          "L'élève a décrit l'école avec une phrase simple.",
          "J'ai compris le mot école pour la première fois.",
          "Ma sœur a montré l'école au professeur.",
          "Ils ont rangé l'école après l'activité.",
          "Nous allons revoir l'école avec la classe.",
          "Elle a noté école pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'école.",
          "Après la leçon, j'ai utilisé le mot école dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'école.",
          "Quand je lis le texte, je cherche le sens de école.",
          "Ce matin, nous avons associé l'école à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec école.",
          "Le professeur a demandé un exemple avec l'école.",
          "J'ai choisi l'école parce que ce mot était dans la liste.",
          "Nous allons réviser l'école avant l'évaluation.",
          "Mon camarade a expliqué l'école avec ses mots.",
          "J'ai ajouté école dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'école semble simple, il peut être utile dans plusieurs situations.",
          "Comme l'école était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises l'école correctement, l'activité sera plus facile.",
          "Même si je connais déjà école, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle école.",
          "La leçon que nous travaillons utilise l'école dans plusieurs exemples.",
          "Pendant que le professeur montrait l'école, les élèves prenaient des notes.",
          "Puisque l'école était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé école, tu pourras l'utiliser plus naturellement.",
          "Je pense que l'école aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, l'école peut donner une information précise.",
          "Le mot dont je parle est école, que la classe doit retenir.",
          "Tant que tu pratiqueras école, tu l'utiliseras plus facilement.",
          "Bien que l'école demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient l'école, je lirai la consigne avec attention.",
          "Bien que le mot école paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'école apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'école, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà école, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'école.",
          "Lorsque j'aurai mémorisé école, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'école.",
          "Puisque école est utile, je le révise régulièrement.",
        ],
      } },
    { word: "classe",       image: "classe.webp",       article: "la",  gender: "f", definition: "La classe est groupe d'élèves ou salle de cours." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la classe pendant l'exercice.",
          "Demain, je vais ranger la classe.",
          "Quand j'étais petit, je voyais souvent la classe à la maison.",
          "Ce matin, j'ai cherché la classe.",
          "Nous avons placé la classe près de la porte.",
          "Ils vont utiliser la classe cette semaine.",
          "J'ai choisi la classe parce que c'était pratique.",
          "Elle a nettoyé la classe avant de partir.",
          "Avant le cours, nous avons préparé la classe.",
          "Le groupe a observé la classe sur l'image.",
          "Je vais prendre la classe après le repas.",
          "Nous avons comparé la classe avec un autre objet.",
          "Hier soir, mon frère a déplacé la classe.",
          "Pendant les vacances, nous utilisions souvent la classe.",
          "Elle a oublié la classe dans la salle.",
          "Il va dessiner la classe dans son cahier.",
          "Nous avons trouvé la classe dans le placard.",
          "Ce week-end, je vais réparer la classe.",
          "L'élève a décrit la classe avec une phrase simple.",
          "J'ai compris le mot classe pour la première fois.",
          "Ma sœur a montré la classe au professeur.",
          "Ils ont rangé la classe après l'activité.",
          "Nous allons revoir la classe avec la classe.",
          "Elle a noté classe pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la classe.",
          "Après la leçon, j'ai utilisé le mot classe dans une phrase.",
          "Demain, je vais apprendre à mieux employer la classe.",
          "Quand je lis le texte, je cherche le sens de classe.",
          "Ce matin, nous avons associé la classe à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec classe.",
          "Le professeur a demandé un exemple avec la classe.",
          "J'ai choisi la classe parce que ce mot était dans la liste.",
          "Nous allons réviser la classe avant l'évaluation.",
          "Mon camarade a expliqué la classe avec ses mots.",
          "J'ai ajouté classe dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la classe semble simple, il peut être utile dans plusieurs situations.",
          "Comme la classe était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la classe correctement, l'activité sera plus facile.",
          "Même si je connais déjà classe, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle classe.",
          "La leçon que nous travaillons utilise la classe dans plusieurs exemples.",
          "Pendant que le professeur montrait la classe, les élèves prenaient des notes.",
          "Puisque la classe était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé classe, tu pourras l'utiliser plus naturellement.",
          "Je pense que la classe aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la classe peut donner une information précise.",
          "Le mot dont je parle est classe, que la classe doit retenir.",
          "Tant que tu pratiqueras classe, tu l'utiliseras plus facilement.",
          "Bien que la classe demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la classe, je lirai la consigne avec attention.",
          "Bien que le mot classe paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la classe apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la classe, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà classe, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la classe.",
          "Lorsque j'aurai mémorisé classe, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la classe.",
          "Puisque classe est utile, je le révise régulièrement.",
        ],
      } },
    { word: "salle",        image: "salle.webp",        article: "la",  gender: "f", definition: "La salle est un espace dans l'école pour une activité." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la salle pendant l'exercice.",
          "Demain, je vais ranger la salle.",
          "Quand j'étais petit, je voyais souvent la salle à la maison.",
          "Ce matin, j'ai cherché la salle.",
          "Nous avons placé la salle près de la porte.",
          "Ils vont utiliser la salle cette semaine.",
          "J'ai choisi la salle parce que c'était pratique.",
          "Elle a nettoyé la salle avant de partir.",
          "Avant le cours, nous avons préparé la salle.",
          "Le groupe a observé la salle sur l'image.",
          "Je vais prendre la salle après le repas.",
          "Nous avons comparé la salle avec un autre objet.",
          "Hier soir, mon frère a déplacé la salle.",
          "Pendant les vacances, nous utilisions souvent la salle.",
          "Elle a oublié la salle dans la salle.",
          "Il va dessiner la salle dans son cahier.",
          "Nous avons trouvé la salle dans le placard.",
          "Ce week-end, je vais réparer la salle.",
          "L'élève a décrit la salle avec une phrase simple.",
          "J'ai compris le mot salle pour la première fois.",
          "Ma sœur a montré la salle au professeur.",
          "Ils ont rangé la salle après l'activité.",
          "Nous allons revoir la salle avec la classe.",
          "Elle a noté salle pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la salle.",
          "Après la leçon, j'ai utilisé le mot salle dans une phrase.",
          "Demain, je vais apprendre à mieux employer la salle.",
          "Quand je lis le texte, je cherche le sens de salle.",
          "Ce matin, nous avons associé la salle à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec salle.",
          "Le professeur a demandé un exemple avec la salle.",
          "J'ai choisi la salle parce que ce mot était dans la liste.",
          "Nous allons réviser la salle avant l'évaluation.",
          "Mon camarade a expliqué la salle avec ses mots.",
          "J'ai ajouté salle dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la salle semble simple, il peut être utile dans plusieurs situations.",
          "Comme la salle était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la salle correctement, l'activité sera plus facile.",
          "Même si je connais déjà salle, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle salle.",
          "La leçon que nous travaillons utilise la salle dans plusieurs exemples.",
          "Pendant que le professeur montrait la salle, les élèves prenaient des notes.",
          "Puisque la salle était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé salle, tu pourras l'utiliser plus naturellement.",
          "Je pense que la salle aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la salle peut donner une information précise.",
          "Le mot dont je parle est salle, que la classe doit retenir.",
          "Tant que tu pratiqueras salle, tu l'utiliseras plus facilement.",
          "Bien que la salle demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la salle, je lirai la consigne avec attention.",
          "Bien que le mot salle paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la salle apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la salle, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà salle, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la salle.",
          "Lorsque j'aurai mémorisé salle, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la salle.",
          "Puisque salle est utile, je le révise régulièrement.",
        ],
      } },
    { word: "couloir",      image: "couloir.webp",      article: "le",  gender: "m", definition: "Le couloir est passage entre les salles." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé le couloir pendant l'exercice.",
          "Demain, je vais ranger le couloir.",
          "Quand j'étais petit, je voyais souvent le couloir à la maison.",
          "Ce matin, j'ai cherché le couloir.",
          "Nous avons placé le couloir près de la porte.",
          "Ils vont utiliser le couloir cette semaine.",
          "J'ai choisi le couloir parce que c'était pratique.",
          "Elle a nettoyé le couloir avant de partir.",
          "Avant le cours, nous avons préparé le couloir.",
          "Le groupe a observé le couloir sur l'image.",
          "Je vais prendre le couloir après le repas.",
          "Nous avons comparé le couloir avec un autre objet.",
          "Hier soir, mon frère a déplacé le couloir.",
          "Pendant les vacances, nous utilisions souvent le couloir.",
          "Elle a oublié le couloir dans la salle.",
          "Il va dessiner le couloir dans son cahier.",
          "Nous avons trouvé le couloir dans le placard.",
          "Ce week-end, je vais réparer le couloir.",
          "L'élève a décrit le couloir avec une phrase simple.",
          "J'ai compris le mot couloir pour la première fois.",
          "Ma sœur a montré le couloir au professeur.",
          "Ils ont rangé le couloir après l'activité.",
          "Nous allons revoir le couloir avec la classe.",
          "Elle a noté couloir pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le couloir.",
          "Après la leçon, j'ai utilisé le mot couloir dans une phrase.",
          "Demain, je vais apprendre à mieux employer le couloir.",
          "Quand je lis le texte, je cherche le sens de couloir.",
          "Ce matin, nous avons associé le couloir à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec couloir.",
          "Le professeur a demandé un exemple avec le couloir.",
          "J'ai choisi le couloir parce que ce mot était dans la liste.",
          "Nous allons réviser le couloir avant l'évaluation.",
          "Mon camarade a expliqué le couloir avec ses mots.",
          "J'ai ajouté couloir dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le couloir semble simple, il peut être utile dans plusieurs situations.",
          "Comme le couloir était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises le couloir correctement, l'activité sera plus facile.",
          "Même si je connais déjà couloir, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle couloir.",
          "La leçon que nous travaillons utilise le couloir dans plusieurs exemples.",
          "Pendant que le professeur montrait le couloir, les élèves prenaient des notes.",
          "Puisque le couloir était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé couloir, tu pourras l'utiliser plus naturellement.",
          "Je pense que le couloir aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, le couloir peut donner une information précise.",
          "Le mot dont je parle est couloir, que la classe doit retenir.",
          "Tant que tu pratiqueras couloir, tu l'utiliseras plus facilement.",
          "Bien que le couloir demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient le couloir, je lirai la consigne avec attention.",
          "Bien que le mot couloir paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le couloir apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le couloir, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà couloir, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le couloir.",
          "Lorsque j'aurai mémorisé couloir, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le couloir.",
          "Puisque couloir est utile, je le révise régulièrement.",
        ],
      } },
    { word: "secrétariat",  image: "secretariat.webp",  article: "le",  gender: "m", definition: "Le secrétariat est bureau administratif de l'école." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé le secrétariat pendant l'exercice.",
          "Demain, je vais ranger le secrétariat.",
          "Quand j'étais petit, je voyais souvent le secrétariat à la maison.",
          "Ce matin, j'ai cherché le secrétariat.",
          "Nous avons placé le secrétariat près de la porte.",
          "Ils vont utiliser le secrétariat cette semaine.",
          "J'ai choisi le secrétariat parce que c'était pratique.",
          "Elle a nettoyé le secrétariat avant de partir.",
          "Avant le cours, nous avons préparé le secrétariat.",
          "Le groupe a observé le secrétariat sur l'image.",
          "Je vais prendre le secrétariat après le repas.",
          "Nous avons comparé le secrétariat avec un autre objet.",
          "Hier soir, mon frère a déplacé le secrétariat.",
          "Pendant les vacances, nous utilisions souvent le secrétariat.",
          "Elle a oublié le secrétariat dans la salle.",
          "Il va dessiner le secrétariat dans son cahier.",
          "Nous avons trouvé le secrétariat dans le placard.",
          "Ce week-end, je vais réparer le secrétariat.",
          "L'élève a décrit le secrétariat avec une phrase simple.",
          "J'ai compris le mot secrétariat pour la première fois.",
          "Ma sœur a montré le secrétariat au professeur.",
          "Ils ont rangé le secrétariat après l'activité.",
          "Nous allons revoir le secrétariat avec la classe.",
          "Elle a noté secrétariat pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le secrétariat.",
          "Après la leçon, j'ai utilisé le mot secrétariat dans une phrase.",
          "Demain, je vais apprendre à mieux employer le secrétariat.",
          "Quand je lis le texte, je cherche le sens de secrétariat.",
          "Ce matin, nous avons associé le secrétariat à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec secrétariat.",
          "Le professeur a demandé un exemple avec le secrétariat.",
          "J'ai choisi le secrétariat parce que ce mot était dans la liste.",
          "Nous allons réviser le secrétariat avant l'évaluation.",
          "Mon camarade a expliqué le secrétariat avec ses mots.",
          "J'ai ajouté secrétariat dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le secrétariat semble simple, il peut être utile dans plusieurs situations.",
          "Comme le secrétariat était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises le secrétariat correctement, l'activité sera plus facile.",
          "Même si je connais déjà secrétariat, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle secrétariat.",
          "La leçon que nous travaillons utilise le secrétariat dans plusieurs exemples.",
          "Pendant que le professeur montrait le secrétariat, les élèves prenaient des notes.",
          "Puisque le secrétariat était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé secrétariat, tu pourras l'utiliser plus naturellement.",
          "Je pense que le secrétariat aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, le secrétariat peut donner une information précise.",
          "Le mot dont je parle est secrétariat, que la classe doit retenir.",
          "Tant que tu pratiqueras secrétariat, tu l'utiliseras plus facilement.",
          "Bien que le secrétariat demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient le secrétariat, je lirai la consigne avec attention.",
          "Bien que le mot secrétariat paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le secrétariat apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le secrétariat, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà secrétariat, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le secrétariat.",
          "Lorsque j'aurai mémorisé secrétariat, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le secrétariat.",
          "Puisque secrétariat est utile, je le révise régulièrement.",
        ],
      } },
    { word: "bibliothèque", image: "bibliotheque.webp", article: "la",  gender: "f", definition: "La bibliothèque est une salle avec des livres à consulter." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la bibliothèque pendant l'exercice.",
          "Demain, je vais ranger la bibliothèque.",
          "Quand j'étais petit, je voyais souvent la bibliothèque à la maison.",
          "Ce matin, j'ai cherché la bibliothèque.",
          "Nous avons placé la bibliothèque près de la porte.",
          "Ils vont utiliser la bibliothèque cette semaine.",
          "J'ai choisi la bibliothèque parce que c'était pratique.",
          "Elle a nettoyé la bibliothèque avant de partir.",
          "Avant le cours, nous avons préparé la bibliothèque.",
          "Le groupe a observé la bibliothèque sur l'image.",
          "Je vais prendre la bibliothèque après le repas.",
          "Nous avons comparé la bibliothèque avec un autre objet.",
          "Hier soir, mon frère a déplacé la bibliothèque.",
          "Pendant les vacances, nous utilisions souvent la bibliothèque.",
          "Elle a oublié la bibliothèque dans la salle.",
          "Il va dessiner la bibliothèque dans son cahier.",
          "Nous avons trouvé la bibliothèque dans le placard.",
          "Ce week-end, je vais réparer la bibliothèque.",
          "L'élève a décrit la bibliothèque avec une phrase simple.",
          "J'ai compris le mot bibliothèque pour la première fois.",
          "Ma sœur a montré la bibliothèque au professeur.",
          "Ils ont rangé la bibliothèque après l'activité.",
          "Nous allons revoir la bibliothèque avec la classe.",
          "Elle a noté bibliothèque pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la bibliothèque.",
          "Après la leçon, j'ai utilisé le mot bibliothèque dans une phrase.",
          "Demain, je vais apprendre à mieux employer la bibliothèque.",
          "Quand je lis le texte, je cherche le sens de bibliothèque.",
          "Ce matin, nous avons associé la bibliothèque à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec bibliothèque.",
          "Le professeur a demandé un exemple avec la bibliothèque.",
          "J'ai choisi la bibliothèque parce que ce mot était dans la liste.",
          "Nous allons réviser la bibliothèque avant l'évaluation.",
          "Mon camarade a expliqué la bibliothèque avec ses mots.",
          "J'ai ajouté bibliothèque dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la bibliothèque semble simple, il peut être utile dans plusieurs situations.",
          "Comme la bibliothèque était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la bibliothèque correctement, l'activité sera plus facile.",
          "Même si je connais déjà bibliothèque, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle bibliothèque.",
          "La leçon que nous travaillons utilise la bibliothèque dans plusieurs exemples.",
          "Pendant que le professeur montrait la bibliothèque, les élèves prenaient des notes.",
          "Puisque la bibliothèque était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé bibliothèque, tu pourras l'utiliser plus naturellement.",
          "Je pense que la bibliothèque aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la bibliothèque peut donner une information précise.",
          "Le mot dont je parle est bibliothèque, que la classe doit retenir.",
          "Tant que tu pratiqueras bibliothèque, tu l'utiliseras plus facilement.",
          "Bien que la bibliothèque demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la bibliothèque, je lirai la consigne avec attention.",
          "Bien que le mot bibliothèque paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la bibliothèque apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la bibliothèque, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà bibliothèque, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la bibliothèque.",
          "Lorsque j'aurai mémorisé bibliothèque, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la bibliothèque.",
          "Puisque bibliothèque est utile, je le révise régulièrement.",
        ],
      } },
    { word: "gymnase",      image: "gymnase.webp",      article: "le",  gender: "m", definition: "Le gymnase est une salle pour faire du sport." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé le gymnase pendant l'exercice.",
          "Demain, je vais ranger le gymnase.",
          "Quand j'étais petit, je voyais souvent le gymnase à la maison.",
          "Ce matin, j'ai cherché le gymnase.",
          "Nous avons placé le gymnase près de la porte.",
          "Ils vont utiliser le gymnase cette semaine.",
          "J'ai choisi le gymnase parce que c'était pratique.",
          "Elle a nettoyé le gymnase avant de partir.",
          "Avant le cours, nous avons préparé le gymnase.",
          "Le groupe a observé le gymnase sur l'image.",
          "Je vais prendre le gymnase après le repas.",
          "Nous avons comparé le gymnase avec un autre objet.",
          "Hier soir, mon frère a déplacé le gymnase.",
          "Pendant les vacances, nous utilisions souvent le gymnase.",
          "Elle a oublié le gymnase dans la salle.",
          "Il va dessiner le gymnase dans son cahier.",
          "Nous avons trouvé le gymnase dans le placard.",
          "Ce week-end, je vais réparer le gymnase.",
          "L'élève a décrit le gymnase avec une phrase simple.",
          "J'ai compris le mot gymnase pour la première fois.",
          "Ma sœur a montré le gymnase au professeur.",
          "Ils ont rangé le gymnase après l'activité.",
          "Nous allons revoir le gymnase avec la classe.",
          "Elle a noté gymnase pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le gymnase.",
          "Après la leçon, j'ai utilisé le mot gymnase dans une phrase.",
          "Demain, je vais apprendre à mieux employer le gymnase.",
          "Quand je lis le texte, je cherche le sens de gymnase.",
          "Ce matin, nous avons associé le gymnase à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec gymnase.",
          "Le professeur a demandé un exemple avec le gymnase.",
          "J'ai choisi le gymnase parce que ce mot était dans la liste.",
          "Nous allons réviser le gymnase avant l'évaluation.",
          "Mon camarade a expliqué le gymnase avec ses mots.",
          "J'ai ajouté gymnase dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le gymnase semble simple, il peut être utile dans plusieurs situations.",
          "Comme le gymnase était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises le gymnase correctement, l'activité sera plus facile.",
          "Même si je connais déjà gymnase, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle gymnase.",
          "La leçon que nous travaillons utilise le gymnase dans plusieurs exemples.",
          "Pendant que le professeur montrait le gymnase, les élèves prenaient des notes.",
          "Puisque le gymnase était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé gymnase, tu pourras l'utiliser plus naturellement.",
          "Je pense que le gymnase aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, le gymnase peut donner une information précise.",
          "Le mot dont je parle est gymnase, que la classe doit retenir.",
          "Tant que tu pratiqueras gymnase, tu l'utiliseras plus facilement.",
          "Bien que le gymnase demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient le gymnase, je lirai la consigne avec attention.",
          "Bien que le mot gymnase paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le gymnase apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le gymnase, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà gymnase, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le gymnase.",
          "Lorsque j'aurai mémorisé gymnase, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le gymnase.",
          "Puisque gymnase est utile, je le révise régulièrement.",
        ],
      } },
    { word: "cour",         image: "cour.webp",         article: "la",  gender: "f", definition: "La cour est un espace extérieur pour jouer pendant la pause." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la cour pendant l'exercice.",
          "Demain, je vais ranger la cour.",
          "Quand j'étais petit, je voyais souvent la cour à la maison.",
          "Ce matin, j'ai cherché la cour.",
          "Nous avons placé la cour près de la porte.",
          "Ils vont utiliser la cour cette semaine.",
          "J'ai choisi la cour parce que c'était pratique.",
          "Elle a nettoyé la cour avant de partir.",
          "Avant le cours, nous avons préparé la cour.",
          "Le groupe a observé la cour sur l'image.",
          "Je vais prendre la cour après le repas.",
          "Nous avons comparé la cour avec un autre objet.",
          "Hier soir, mon frère a déplacé la cour.",
          "Pendant les vacances, nous utilisions souvent la cour.",
          "Elle a oublié la cour dans la salle.",
          "Il va dessiner la cour dans son cahier.",
          "Nous avons trouvé la cour dans le placard.",
          "Ce week-end, je vais réparer la cour.",
          "L'élève a décrit la cour avec une phrase simple.",
          "J'ai compris le mot cour pour la première fois.",
          "Ma sœur a montré la cour au professeur.",
          "Ils ont rangé la cour après l'activité.",
          "Nous allons revoir la cour avec la classe.",
          "Elle a noté cour pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la cour.",
          "Après la leçon, j'ai utilisé le mot cour dans une phrase.",
          "Demain, je vais apprendre à mieux employer la cour.",
          "Quand je lis le texte, je cherche le sens de cour.",
          "Ce matin, nous avons associé la cour à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec cour.",
          "Le professeur a demandé un exemple avec la cour.",
          "J'ai choisi la cour parce que ce mot était dans la liste.",
          "Nous allons réviser la cour avant l'évaluation.",
          "Mon camarade a expliqué la cour avec ses mots.",
          "J'ai ajouté cour dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la cour semble simple, il peut être utile dans plusieurs situations.",
          "Comme la cour était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la cour correctement, l'activité sera plus facile.",
          "Même si je connais déjà cour, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle cour.",
          "La leçon que nous travaillons utilise la cour dans plusieurs exemples.",
          "Pendant que le professeur montrait la cour, les élèves prenaient des notes.",
          "Puisque la cour était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé cour, tu pourras l'utiliser plus naturellement.",
          "Je pense que la cour aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la cour peut donner une information précise.",
          "Le mot dont je parle est cour, que la classe doit retenir.",
          "Tant que tu pratiqueras cour, tu l'utiliseras plus facilement.",
          "Bien que la cour demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la cour, je lirai la consigne avec attention.",
          "Bien que le mot cour paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la cour apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la cour, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cour, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la cour.",
          "Lorsque j'aurai mémorisé cour, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la cour.",
          "Puisque cour est utile, je le révise régulièrement.",
        ],
      } },
    { word: "direction",    image: "direction.webp",    article: "la",  gender: "f", definition: "La direction est bureau du directeur ou de la directrice." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la direction pendant l'exercice.",
          "Demain, je vais ranger la direction.",
          "Quand j'étais petit, je voyais souvent la direction à la maison.",
          "Ce matin, j'ai cherché la direction.",
          "Nous avons placé la direction près de la porte.",
          "Ils vont utiliser la direction cette semaine.",
          "J'ai choisi la direction parce que c'était pratique.",
          "Elle a nettoyé la direction avant de partir.",
          "Avant le cours, nous avons préparé la direction.",
          "Le groupe a observé la direction sur l'image.",
          "Je vais prendre la direction après le repas.",
          "Nous avons comparé la direction avec un autre objet.",
          "Hier soir, mon frère a déplacé la direction.",
          "Pendant les vacances, nous utilisions souvent la direction.",
          "Elle a oublié la direction dans la salle.",
          "Il va dessiner la direction dans son cahier.",
          "Nous avons trouvé la direction dans le placard.",
          "Ce week-end, je vais réparer la direction.",
          "L'élève a décrit la direction avec une phrase simple.",
          "J'ai compris le mot direction pour la première fois.",
          "Ma sœur a montré la direction au professeur.",
          "Ils ont rangé la direction après l'activité.",
          "Nous allons revoir la direction avec la classe.",
          "Elle a noté direction pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la direction.",
          "Après la leçon, j'ai utilisé le mot direction dans une phrase.",
          "Demain, je vais apprendre à mieux employer la direction.",
          "Quand je lis le texte, je cherche le sens de direction.",
          "Ce matin, nous avons associé la direction à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec direction.",
          "Le professeur a demandé un exemple avec la direction.",
          "J'ai choisi la direction parce que ce mot était dans la liste.",
          "Nous allons réviser la direction avant l'évaluation.",
          "Mon camarade a expliqué la direction avec ses mots.",
          "J'ai ajouté direction dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la direction semble simple, il peut être utile dans plusieurs situations.",
          "Comme la direction était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la direction correctement, l'activité sera plus facile.",
          "Même si je connais déjà direction, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle direction.",
          "La leçon que nous travaillons utilise la direction dans plusieurs exemples.",
          "Pendant que le professeur montrait la direction, les élèves prenaient des notes.",
          "Puisque la direction était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé direction, tu pourras l'utiliser plus naturellement.",
          "Je pense que la direction aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la direction peut donner une information précise.",
          "Le mot dont je parle est direction, que la classe doit retenir.",
          "Tant que tu pratiqueras direction, tu l'utiliseras plus facilement.",
          "Bien que la direction demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la direction, je lirai la consigne avec attention.",
          "Bien que le mot direction paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la direction apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la direction, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà direction, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la direction.",
          "Lorsque j'aurai mémorisé direction, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la direction.",
          "Puisque direction est utile, je le révise régulièrement.",
        ],
      } },
    { word: "sonnerie",     image: "sonnerie.webp",     article: "la",  gender: "f", definition: "La sonnerie est signal sonore marquant le début ou la fin d'un cours." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la sonnerie pendant l'exercice.",
          "Demain, je vais ranger la sonnerie.",
          "Quand j'étais petit, je voyais souvent la sonnerie à la maison.",
          "Ce matin, j'ai cherché la sonnerie.",
          "Nous avons placé la sonnerie près de la porte.",
          "Ils vont utiliser la sonnerie cette semaine.",
          "J'ai choisi la sonnerie parce que c'était pratique.",
          "Elle a nettoyé la sonnerie avant de partir.",
          "Avant le cours, nous avons préparé la sonnerie.",
          "Le groupe a observé la sonnerie sur l'image.",
          "Je vais prendre la sonnerie après le repas.",
          "Nous avons comparé la sonnerie avec un autre objet.",
          "Hier soir, mon frère a déplacé la sonnerie.",
          "Pendant les vacances, nous utilisions souvent la sonnerie.",
          "Elle a oublié la sonnerie dans la salle.",
          "Il va dessiner la sonnerie dans son cahier.",
          "Nous avons trouvé la sonnerie dans le placard.",
          "Ce week-end, je vais réparer la sonnerie.",
          "L'élève a décrit la sonnerie avec une phrase simple.",
          "J'ai compris le mot sonnerie pour la première fois.",
          "Ma sœur a montré la sonnerie au professeur.",
          "Ils ont rangé la sonnerie après l'activité.",
          "Nous allons revoir la sonnerie avec la classe.",
          "Elle a noté sonnerie pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la sonnerie.",
          "Après la leçon, j'ai utilisé le mot sonnerie dans une phrase.",
          "Demain, je vais apprendre à mieux employer la sonnerie.",
          "Quand je lis le texte, je cherche le sens de sonnerie.",
          "Ce matin, nous avons associé la sonnerie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec sonnerie.",
          "Le professeur a demandé un exemple avec la sonnerie.",
          "J'ai choisi la sonnerie parce que ce mot était dans la liste.",
          "Nous allons réviser la sonnerie avant l'évaluation.",
          "Mon camarade a expliqué la sonnerie avec ses mots.",
          "J'ai ajouté sonnerie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la sonnerie semble simple, il peut être utile dans plusieurs situations.",
          "Comme la sonnerie était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la sonnerie correctement, l'activité sera plus facile.",
          "Même si je connais déjà sonnerie, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle sonnerie.",
          "La leçon que nous travaillons utilise la sonnerie dans plusieurs exemples.",
          "Pendant que le professeur montrait la sonnerie, les élèves prenaient des notes.",
          "Puisque la sonnerie était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé sonnerie, tu pourras l'utiliser plus naturellement.",
          "Je pense que la sonnerie aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la sonnerie peut donner une information précise.",
          "Le mot dont je parle est sonnerie, que la classe doit retenir.",
          "Tant que tu pratiqueras sonnerie, tu l'utiliseras plus facilement.",
          "Bien que la sonnerie demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la sonnerie, je lirai la consigne avec attention.",
          "Bien que le mot sonnerie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la sonnerie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la sonnerie, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà sonnerie, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la sonnerie.",
          "Lorsque j'aurai mémorisé sonnerie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la sonnerie.",
          "Puisque sonnerie est utile, je le révise régulièrement.",
        ],
      } },
    { word: "cantine",      image: "cantine.webp",      article: "la",  gender: "f", definition: "La cantine est restaurant scolaire pour les repas." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé la cantine pendant l'exercice.",
          "Demain, je vais ranger la cantine.",
          "Quand j'étais petit, je voyais souvent la cantine à la maison.",
          "Ce matin, j'ai cherché la cantine.",
          "Nous avons placé la cantine près de la porte.",
          "Ils vont utiliser la cantine cette semaine.",
          "J'ai choisi la cantine parce que c'était pratique.",
          "Elle a nettoyé la cantine avant de partir.",
          "Avant le cours, nous avons préparé la cantine.",
          "Le groupe a observé la cantine sur l'image.",
          "Je vais prendre la cantine après le repas.",
          "Nous avons comparé la cantine avec un autre objet.",
          "Hier soir, mon frère a déplacé la cantine.",
          "Pendant les vacances, nous utilisions souvent la cantine.",
          "Elle a oublié la cantine dans la salle.",
          "Il va dessiner la cantine dans son cahier.",
          "Nous avons trouvé la cantine dans le placard.",
          "Ce week-end, je vais réparer la cantine.",
          "L'élève a décrit la cantine avec une phrase simple.",
          "J'ai compris le mot cantine pour la première fois.",
          "Ma sœur a montré la cantine au professeur.",
          "Ils ont rangé la cantine après l'activité.",
          "Nous allons revoir la cantine avec la classe.",
          "Elle a noté cantine pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la cantine.",
          "Après la leçon, j'ai utilisé le mot cantine dans une phrase.",
          "Demain, je vais apprendre à mieux employer la cantine.",
          "Quand je lis le texte, je cherche le sens de cantine.",
          "Ce matin, nous avons associé la cantine à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec cantine.",
          "Le professeur a demandé un exemple avec la cantine.",
          "J'ai choisi la cantine parce que ce mot était dans la liste.",
          "Nous allons réviser la cantine avant l'évaluation.",
          "Mon camarade a expliqué la cantine avec ses mots.",
          "J'ai ajouté cantine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la cantine semble simple, il peut être utile dans plusieurs situations.",
          "Comme la cantine était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises la cantine correctement, l'activité sera plus facile.",
          "Même si je connais déjà cantine, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle cantine.",
          "La leçon que nous travaillons utilise la cantine dans plusieurs exemples.",
          "Pendant que le professeur montrait la cantine, les élèves prenaient des notes.",
          "Puisque la cantine était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé cantine, tu pourras l'utiliser plus naturellement.",
          "Je pense que la cantine aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, la cantine peut donner une information précise.",
          "Le mot dont je parle est cantine, que la classe doit retenir.",
          "Tant que tu pratiqueras cantine, tu l'utiliseras plus facilement.",
          "Bien que la cantine demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient la cantine, je lirai la consigne avec attention.",
          "Bien que le mot cantine paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la cantine apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la cantine, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cantine, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la cantine.",
          "Lorsque j'aurai mémorisé cantine, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la cantine.",
          "Puisque cantine est utile, je le révise régulièrement.",
        ],
      } },
    { word: "infirmerie",   image: "infirmerie.webp",   article: "l'",  gender: "f", definition: "L'infirmerie est une salle de soins dans l'école." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé l'infirmerie pendant l'exercice.",
          "Demain, je vais ranger l'infirmerie.",
          "Quand j'étais petit, je voyais souvent l'infirmerie à la maison.",
          "Ce matin, j'ai cherché l'infirmerie.",
          "Nous avons placé l'infirmerie près de la porte.",
          "Ils vont utiliser l'infirmerie cette semaine.",
          "J'ai choisi l'infirmerie parce que c'était pratique.",
          "Elle a nettoyé l'infirmerie avant de partir.",
          "Avant le cours, nous avons préparé l'infirmerie.",
          "Le groupe a observé l'infirmerie sur l'image.",
          "Je vais prendre l'infirmerie après le repas.",
          "Nous avons comparé l'infirmerie avec un autre objet.",
          "Hier soir, mon frère a déplacé l'infirmerie.",
          "Pendant les vacances, nous utilisions souvent l'infirmerie.",
          "Elle a oublié l'infirmerie dans la salle.",
          "Il va dessiner l'infirmerie dans son cahier.",
          "Nous avons trouvé l'infirmerie dans le placard.",
          "Ce week-end, je vais réparer l'infirmerie.",
          "L'élève a décrit l'infirmerie avec une phrase simple.",
          "J'ai compris le mot infirmerie pour la première fois.",
          "Ma sœur a montré l'infirmerie au professeur.",
          "Ils ont rangé l'infirmerie après l'activité.",
          "Nous allons revoir l'infirmerie avec la classe.",
          "Elle a noté infirmerie pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'infirmerie.",
          "Après la leçon, j'ai utilisé le mot infirmerie dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'infirmerie.",
          "Quand je lis le texte, je cherche le sens de infirmerie.",
          "Ce matin, nous avons associé l'infirmerie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec infirmerie.",
          "Le professeur a demandé un exemple avec l'infirmerie.",
          "J'ai choisi l'infirmerie parce que ce mot était dans la liste.",
          "Nous allons réviser l'infirmerie avant l'évaluation.",
          "Mon camarade a expliqué l'infirmerie avec ses mots.",
          "J'ai ajouté infirmerie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'infirmerie semble simple, il peut être utile dans plusieurs situations.",
          "Comme l'infirmerie était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises l'infirmerie correctement, l'activité sera plus facile.",
          "Même si je connais déjà infirmerie, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle infirmerie.",
          "La leçon que nous travaillons utilise l'infirmerie dans plusieurs exemples.",
          "Pendant que le professeur montrait l'infirmerie, les élèves prenaient des notes.",
          "Puisque l'infirmerie était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé infirmerie, tu pourras l'utiliser plus naturellement.",
          "Je pense que l'infirmerie aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, l'infirmerie peut donner une information précise.",
          "Le mot dont je parle est infirmerie, que la classe doit retenir.",
          "Tant que tu pratiqueras infirmerie, tu l'utiliseras plus facilement.",
          "Bien que l'infirmerie demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient l'infirmerie, je lirai la consigne avec attention.",
          "Bien que le mot infirmerie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'infirmerie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'infirmerie, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà infirmerie, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'infirmerie.",
          "Lorsque j'aurai mémorisé infirmerie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'infirmerie.",
          "Puisque infirmerie est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ascenseur",    image: "ascenseur.webp",    article: "l'",  gender: "m", definition: "L'ascenseur est cabine pour monter et descendre les étages." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai utilisé l'ascenseur pendant l'exercice.",
          "Demain, je vais ranger l'ascenseur.",
          "Quand j'étais petit, je voyais souvent l'ascenseur à la maison.",
          "Ce matin, j'ai cherché l'ascenseur.",
          "Nous avons placé l'ascenseur près de la porte.",
          "Ils vont utiliser l'ascenseur cette semaine.",
          "J'ai choisi l'ascenseur parce que c'était pratique.",
          "Elle a nettoyé l'ascenseur avant de partir.",
          "Avant le cours, nous avons préparé l'ascenseur.",
          "Le groupe a observé l'ascenseur sur l'image.",
          "Je vais prendre l'ascenseur après le repas.",
          "Nous avons comparé l'ascenseur avec un autre objet.",
          "Hier soir, mon frère a déplacé l'ascenseur.",
          "Pendant les vacances, nous utilisions souvent l'ascenseur.",
          "Elle a oublié l'ascenseur dans la salle.",
          "Il va dessiner l'ascenseur dans son cahier.",
          "Nous avons trouvé l'ascenseur dans le placard.",
          "Ce week-end, je vais réparer l'ascenseur.",
          "L'élève a décrit l'ascenseur avec une phrase simple.",
          "J'ai compris le mot ascenseur pour la première fois.",
          "Ma sœur a montré l'ascenseur au professeur.",
          "Ils ont rangé l'ascenseur après l'activité.",
          "Nous allons revoir l'ascenseur avec la classe.",
          "Elle a noté ascenseur pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'ascenseur.",
          "Après la leçon, j'ai utilisé le mot ascenseur dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ascenseur.",
          "Quand je lis le texte, je cherche le sens de ascenseur.",
          "Ce matin, nous avons associé l'ascenseur à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ascenseur.",
          "Le professeur a demandé un exemple avec l'ascenseur.",
          "J'ai choisi l'ascenseur parce que ce mot était dans la liste.",
          "Nous allons réviser l'ascenseur avant l'évaluation.",
          "Mon camarade a expliqué l'ascenseur avec ses mots.",
          "J'ai ajouté ascenseur dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ascenseur semble simple, il peut être utile dans plusieurs situations.",
          "Comme l'ascenseur était difficile à trouver, nous avons demandé de l'aide.",
          "Si tu utilises l'ascenseur correctement, l'activité sera plus facile.",
          "Même si je connais déjà ascenseur, je dois encore l'employer dans une phrase.",
          "L'objet que nous avons observé s'appelle ascenseur.",
          "La leçon que nous travaillons utilise l'ascenseur dans plusieurs exemples.",
          "Pendant que le professeur montrait l'ascenseur, les élèves prenaient des notes.",
          "Puisque l'ascenseur était au centre de l'image, tout le monde l'a remarqué.",
          "Lorsque tu auras mémorisé ascenseur, tu pourras l'utiliser plus naturellement.",
          "Je pense que l'ascenseur aide à comprendre la situation parce qu'il donne un repère concret.",
          "Même quand la phrase est courte, l'ascenseur peut donner une information précise.",
          "Le mot dont je parle est ascenseur, que la classe doit retenir.",
          "Tant que tu pratiqueras ascenseur, tu l'utiliseras plus facilement.",
          "Bien que l'ascenseur demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient l'ascenseur, je lirai la consigne avec attention.",
          "Bien que le mot ascenseur paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ascenseur apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ascenseur, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ascenseur, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ascenseur.",
          "Lorsque j'aurai mémorisé ascenseur, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ascenseur.",
          "Puisque ascenseur est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Les élèves jouent dans la ___ pendant la pause.",     answer: "cour" },
    { sentence: "Je mange à la ___ avec mes camarades.",               answer: "cantine" },
    { sentence: "La ___ sonne pour annoncer la fin du cours.",         answer: "sonnerie" },
    { sentence: "Je vais à la ___ emprunter des livres.",              answer: "bibliothèque" },
    { sentence: "Le directeur travaille dans son bureau à la ___.",    answer: "direction" },
  ],
};
