import type { VocabTheme } from "../../vocabulary-data";

export const V2_METEO_THEME: VocabTheme = {
  slug: "v2-meteo",
  code: "V2.4",
  title: "La météo",
  section: "V2",
  words: [
    { word: "soleil", image: "soleil.webp",       article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait du soleil toute la journée.",
          "Demain, il va y avoir du soleil.",
          "Ce matin, la météo a annoncé le soleil.",
          "Quand je suis sorti, j'ai vu le soleil.",
          "Nous avons parlé du soleil pendant le cours.",
          "Ils vont regarder le soleil sur la carte.",
          "J'ai choisi le soleil pour décrire le temps.",
          "Elle a noté le soleil dans son cahier.",
          "Avant de partir, nous avons vérifié le soleil.",
          "Le présentateur a expliqué le soleil à la télévision.",
          "Je vais regarder le soleil avant la sortie.",
          "Nous avons dessiné le soleil dans l'exercice.",
          "Hier soir, mon frère a entendu parler du soleil.",
          "Pendant l'hiver, il y avait souvent du soleil.",
          "Elle a oublié le mot soleil pendant l'exercice.",
          "Il va utiliser le soleil dans sa phrase.",
          "Nous avons trouvé le soleil dans le bulletin météo.",
          "Ce week-end, je vais observer le soleil.",
          "L'élève a ajouté le soleil dans sa réponse.",
          "J'ai compris le mot soleil pour la première fois.",
          "Ma sœur a choisi le soleil pour son exemple.",
          "Ils ont répété soleil à voix haute.",
          "Nous allons revoir le soleil avec le professeur.",
          "Elle a noté soleil pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le soleil.",
          "Après la leçon, j'ai utilisé le mot soleil dans une phrase.",
          "Demain, je vais apprendre à mieux employer le soleil.",
          "Quand je lis le texte, je cherche le sens de soleil.",
          "Ce matin, nous avons associé le soleil à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec soleil.",
          "Le professeur a demandé un exemple avec le soleil.",
          "J'ai choisi le soleil parce que ce mot était dans la liste.",
          "Nous allons réviser le soleil avant l'évaluation.",
          "Mon camarade a expliqué le soleil avec ses mots.",
          "J'ai ajouté soleil dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le soleil semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du soleil, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le soleil, je prendrai des vêtements adaptés.",
          "Même si je connais le mot soleil, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le soleil, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le soleil pour décrire le temps.",
          "Pendant que le professeur expliquait le soleil, les élèves regardaient l'image.",
          "Puisque le soleil était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris soleil, tu pourras décrire la météo plus précisément.",
          "Je pense que le soleil aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le soleil donne une information importante.",
          "Le phénomène dont je parle est le soleil, que la météo annonce souvent.",
          "Tant que le soleil restera présent, nous éviterons les activités dehors.",
          "Bien que le soleil demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le soleil, je penserai à parler de la météo.",
          "Bien que le mot soleil paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le soleil apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le soleil, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà soleil, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le soleil.",
          "Lorsque j'aurai mémorisé soleil, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le soleil.",
          "Puisque soleil est utile, je le révise régulièrement.",
        ],
      } },
    { word: "nuage", image: "nuage.webp",        article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un nuage toute la journée.",
          "Demain, il va y avoir un nuage.",
          "Ce matin, la météo a annoncé le nuage.",
          "Quand je suis sorti, j'ai vu le nuage.",
          "Nous avons parlé du nuage pendant le cours.",
          "Ils vont regarder le nuage sur la carte.",
          "J'ai choisi le nuage pour décrire le temps.",
          "Elle a noté le nuage dans son cahier.",
          "Avant de partir, nous avons vérifié le nuage.",
          "Le présentateur a expliqué le nuage à la télévision.",
          "Je vais regarder le nuage avant la sortie.",
          "Nous avons dessiné le nuage dans l'exercice.",
          "Hier soir, mon frère a entendu parler du nuage.",
          "Pendant l'hiver, il y avait souvent un nuage.",
          "Elle a oublié le mot nuage pendant l'exercice.",
          "Il va utiliser le nuage dans sa phrase.",
          "Nous avons trouvé le nuage dans le bulletin météo.",
          "Ce week-end, je vais observer le nuage.",
          "L'élève a ajouté le nuage dans sa réponse.",
          "J'ai compris le mot nuage pour la première fois.",
          "Ma sœur a choisi le nuage pour son exemple.",
          "Ils ont répété nuage à voix haute.",
          "Nous allons revoir le nuage avec le professeur.",
          "Elle a noté nuage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le nuage.",
          "Après la leçon, j'ai utilisé le mot nuage dans une phrase.",
          "Demain, je vais apprendre à mieux employer le nuage.",
          "Quand je lis le texte, je cherche le sens de nuage.",
          "Ce matin, nous avons associé le nuage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec nuage.",
          "Le professeur a demandé un exemple avec le nuage.",
          "J'ai choisi le nuage parce que ce mot était dans la liste.",
          "Nous allons réviser le nuage avant l'évaluation.",
          "Mon camarade a expliqué le nuage avec ses mots.",
          "J'ai ajouté nuage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le nuage semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du nuage, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le nuage, je prendrai des vêtements adaptés.",
          "Même si je connais le mot nuage, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le nuage, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le nuage pour décrire le temps.",
          "Pendant que le professeur expliquait le nuage, les élèves regardaient l'image.",
          "Puisque le nuage était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris nuage, tu pourras décrire la météo plus précisément.",
          "Je pense que le nuage aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le nuage donne une information importante.",
          "Le phénomène dont je parle est le nuage, que la météo annonce souvent.",
          "Tant que le nuage restera présent, nous éviterons les activités dehors.",
          "Bien que le nuage demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le nuage, je penserai à parler de la météo.",
          "Bien que le mot nuage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le nuage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le nuage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà nuage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le nuage.",
          "Lorsque j'aurai mémorisé nuage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le nuage.",
          "Puisque nuage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "lune", image: "lune.webp",         article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait une lune toute la journée.",
          "Demain, il va y avoir une lune.",
          "Ce matin, la météo a annoncé la lune.",
          "Quand je suis sorti, j'ai vu la lune.",
          "Nous avons parlé de la lune pendant le cours.",
          "Ils vont regarder la lune sur la carte.",
          "J'ai choisi la lune pour décrire le temps.",
          "Elle a noté la lune dans son cahier.",
          "Avant de partir, nous avons vérifié la lune.",
          "Le présentateur a expliqué la lune à la télévision.",
          "Je vais regarder la lune avant la sortie.",
          "Nous avons dessiné la lune dans l'exercice.",
          "Hier soir, mon frère a entendu parler de la lune.",
          "Pendant l'hiver, il y avait souvent une lune.",
          "Elle a oublié le mot lune pendant l'exercice.",
          "Il va utiliser la lune dans sa phrase.",
          "Nous avons trouvé la lune dans le bulletin météo.",
          "Ce week-end, je vais observer la lune.",
          "L'élève a ajouté la lune dans sa réponse.",
          "J'ai compris le mot lune pour la première fois.",
          "Ma sœur a choisi la lune pour son exemple.",
          "Ils ont répété lune à voix haute.",
          "Nous allons revoir la lune avec le professeur.",
          "Elle a noté lune pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la lune.",
          "Après la leçon, j'ai utilisé le mot lune dans une phrase.",
          "Demain, je vais apprendre à mieux employer la lune.",
          "Quand je lis le texte, je cherche le sens de lune.",
          "Ce matin, nous avons associé la lune à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec lune.",
          "Le professeur a demandé un exemple avec la lune.",
          "J'ai choisi la lune parce que ce mot était dans la liste.",
          "Nous allons réviser la lune avant l'évaluation.",
          "Mon camarade a expliqué la lune avec ses mots.",
          "J'ai ajouté lune dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la lune semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de la lune, nous avons décidé de reporter la sortie.",
          "Si la météo annonce la lune, je prendrai des vêtements adaptés.",
          "Même si je connais le mot lune, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait la lune, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise la lune pour décrire le temps.",
          "Pendant que le professeur expliquait la lune, les élèves regardaient l'image.",
          "Puisque la lune était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris lune, tu pourras décrire la météo plus précisément.",
          "Je pense que la lune aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, la lune donne une information importante.",
          "Le phénomène dont je parle est la lune, que la météo annonce souvent.",
          "Tant que la lune restera présent, nous éviterons les activités dehors.",
          "Bien que la lune demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient la lune, je penserai à parler de la météo.",
          "Bien que le mot lune paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la lune apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la lune, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà lune, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la lune.",
          "Lorsque j'aurai mémorisé lune, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la lune.",
          "Puisque lune est utile, je le révise régulièrement.",
        ],
      } },
    { word: "étoile", image: "etoile.webp",       article: "une", gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait une étoile toute la journée.",
          "Demain, il va y avoir une étoile.",
          "Ce matin, la météo a annoncé l'étoile.",
          "Quand je suis sorti, j'ai vu l'étoile.",
          "Nous avons parlé de l'étoile pendant le cours.",
          "Ils vont regarder l'étoile sur la carte.",
          "J'ai choisi l'étoile pour décrire le temps.",
          "Elle a noté l'étoile dans son cahier.",
          "Avant de partir, nous avons vérifié l'étoile.",
          "Le présentateur a expliqué l'étoile à la télévision.",
          "Je vais regarder l'étoile avant la sortie.",
          "Nous avons dessiné l'étoile dans l'exercice.",
          "Hier soir, mon frère a entendu parler de l'étoile.",
          "Pendant l'hiver, il y avait souvent une étoile.",
          "Elle a oublié le mot étoile pendant l'exercice.",
          "Il va utiliser l'étoile dans sa phrase.",
          "Nous avons trouvé l'étoile dans le bulletin météo.",
          "Ce week-end, je vais observer l'étoile.",
          "L'élève a ajouté l'étoile dans sa réponse.",
          "J'ai compris le mot étoile pour la première fois.",
          "Ma sœur a choisi l'étoile pour son exemple.",
          "Ils ont répété étoile à voix haute.",
          "Nous allons revoir l'étoile avec le professeur.",
          "Elle a noté étoile pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'étoile.",
          "Après la leçon, j'ai utilisé le mot étoile dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'étoile.",
          "Quand je lis le texte, je cherche le sens de étoile.",
          "Ce matin, nous avons associé l'étoile à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec étoile.",
          "Le professeur a demandé un exemple avec l'étoile.",
          "J'ai choisi l'étoile parce que ce mot était dans la liste.",
          "Nous allons réviser l'étoile avant l'évaluation.",
          "Mon camarade a expliqué l'étoile avec ses mots.",
          "J'ai ajouté étoile dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'étoile semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de l'étoile, nous avons décidé de reporter la sortie.",
          "Si la météo annonce l'étoile, je prendrai des vêtements adaptés.",
          "Même si je connais le mot étoile, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait l'étoile, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise l'étoile pour décrire le temps.",
          "Pendant que le professeur expliquait l'étoile, les élèves regardaient l'image.",
          "Puisque l'étoile était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris étoile, tu pourras décrire la météo plus précisément.",
          "Je pense que l'étoile aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, l'étoile donne une information importante.",
          "Le phénomène dont je parle est l'étoile, que la météo annonce souvent.",
          "Tant que l'étoile restera présent, nous éviterons les activités dehors.",
          "Bien que l'étoile demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient l'étoile, je penserai à parler de la météo.",
          "Bien que le mot étoile paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'étoile apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'étoile, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà étoile, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'étoile.",
          "Lorsque j'aurai mémorisé étoile, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'étoile.",
          "Puisque étoile est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pluie", image: "pluie.webp",        article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait de la pluie toute la journée.",
          "Demain, il va y avoir de la pluie.",
          "Ce matin, la météo a annoncé la pluie.",
          "Quand je suis sorti, j'ai vu la pluie.",
          "Nous avons parlé de la pluie pendant le cours.",
          "Ils vont regarder la pluie sur la carte.",
          "J'ai choisi la pluie pour décrire le temps.",
          "Elle a noté la pluie dans son cahier.",
          "Avant de partir, nous avons vérifié la pluie.",
          "Le présentateur a expliqué la pluie à la télévision.",
          "Je vais regarder la pluie avant la sortie.",
          "Nous avons dessiné la pluie dans l'exercice.",
          "Hier soir, mon frère a entendu parler de la pluie.",
          "Pendant l'hiver, il y avait souvent de la pluie.",
          "Elle a oublié le mot pluie pendant l'exercice.",
          "Il va utiliser la pluie dans sa phrase.",
          "Nous avons trouvé la pluie dans le bulletin météo.",
          "Ce week-end, je vais observer la pluie.",
          "L'élève a ajouté la pluie dans sa réponse.",
          "J'ai compris le mot pluie pour la première fois.",
          "Ma sœur a choisi la pluie pour son exemple.",
          "Ils ont répété pluie à voix haute.",
          "Nous allons revoir la pluie avec le professeur.",
          "Elle a noté pluie pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la pluie.",
          "Après la leçon, j'ai utilisé le mot pluie dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pluie.",
          "Quand je lis le texte, je cherche le sens de pluie.",
          "Ce matin, nous avons associé la pluie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pluie.",
          "Le professeur a demandé un exemple avec la pluie.",
          "J'ai choisi la pluie parce que ce mot était dans la liste.",
          "Nous allons réviser la pluie avant l'évaluation.",
          "Mon camarade a expliqué la pluie avec ses mots.",
          "J'ai ajouté pluie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pluie semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de la pluie, nous avons décidé de reporter la sortie.",
          "Si la météo annonce la pluie, je prendrai des vêtements adaptés.",
          "Même si je connais le mot pluie, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait la pluie, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise la pluie pour décrire le temps.",
          "Pendant que le professeur expliquait la pluie, les élèves regardaient l'image.",
          "Puisque la pluie était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris pluie, tu pourras décrire la météo plus précisément.",
          "Je pense que la pluie aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, la pluie donne une information importante.",
          "Le phénomène dont je parle est la pluie, que la météo annonce souvent.",
          "Tant que la pluie restera présent, nous éviterons les activités dehors.",
          "Bien que la pluie demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient la pluie, je penserai à parler de la météo.",
          "Bien que le mot pluie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pluie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pluie, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pluie, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pluie.",
          "Lorsque j'aurai mémorisé pluie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pluie.",
          "Puisque pluie est utile, je le révise régulièrement.",
        ],
      } },
    { word: "vent", image: "vent.webp",         article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait du vent toute la journée.",
          "Demain, il va y avoir du vent.",
          "Ce matin, la météo a annoncé le vent.",
          "Quand je suis sorti, j'ai vu le vent.",
          "Nous avons parlé du vent pendant le cours.",
          "Ils vont regarder le vent sur la carte.",
          "J'ai choisi le vent pour décrire le temps.",
          "Elle a noté le vent dans son cahier.",
          "Avant de partir, nous avons vérifié le vent.",
          "Le présentateur a expliqué le vent à la télévision.",
          "Je vais regarder le vent avant la sortie.",
          "Nous avons dessiné le vent dans l'exercice.",
          "Hier soir, mon frère a entendu parler du vent.",
          "Pendant l'hiver, il y avait souvent du vent.",
          "Elle a oublié le mot vent pendant l'exercice.",
          "Il va utiliser le vent dans sa phrase.",
          "Nous avons trouvé le vent dans le bulletin météo.",
          "Ce week-end, je vais observer le vent.",
          "L'élève a ajouté le vent dans sa réponse.",
          "J'ai compris le mot vent pour la première fois.",
          "Ma sœur a choisi le vent pour son exemple.",
          "Ils ont répété vent à voix haute.",
          "Nous allons revoir le vent avec le professeur.",
          "Elle a noté vent pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le vent.",
          "Après la leçon, j'ai utilisé le mot vent dans une phrase.",
          "Demain, je vais apprendre à mieux employer le vent.",
          "Quand je lis le texte, je cherche le sens de vent.",
          "Ce matin, nous avons associé le vent à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec vent.",
          "Le professeur a demandé un exemple avec le vent.",
          "J'ai choisi le vent parce que ce mot était dans la liste.",
          "Nous allons réviser le vent avant l'évaluation.",
          "Mon camarade a expliqué le vent avec ses mots.",
          "J'ai ajouté vent dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le vent semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du vent, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le vent, je prendrai des vêtements adaptés.",
          "Même si je connais le mot vent, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le vent, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le vent pour décrire le temps.",
          "Pendant que le professeur expliquait le vent, les élèves regardaient l'image.",
          "Puisque le vent était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris vent, tu pourras décrire la météo plus précisément.",
          "Je pense que le vent aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le vent donne une information importante.",
          "Le phénomène dont je parle est le vent, que la météo annonce souvent.",
          "Tant que le vent restera présent, nous éviterons les activités dehors.",
          "Bien que le vent demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le vent, je penserai à parler de la météo.",
          "Bien que le mot vent paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le vent apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le vent, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà vent, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le vent.",
          "Lorsque j'aurai mémorisé vent, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le vent.",
          "Puisque vent est utile, je le révise régulièrement.",
        ],
      } },
    { word: "neige", image: "neige.webp",        article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait de la neige toute la journée.",
          "Demain, il va y avoir de la neige.",
          "Ce matin, la météo a annoncé la neige.",
          "Quand je suis sorti, j'ai vu la neige.",
          "Nous avons parlé de la neige pendant le cours.",
          "Ils vont regarder la neige sur la carte.",
          "J'ai choisi la neige pour décrire le temps.",
          "Elle a noté la neige dans son cahier.",
          "Avant de partir, nous avons vérifié la neige.",
          "Le présentateur a expliqué la neige à la télévision.",
          "Je vais regarder la neige avant la sortie.",
          "Nous avons dessiné la neige dans l'exercice.",
          "Hier soir, mon frère a entendu parler de la neige.",
          "Pendant l'hiver, il y avait souvent de la neige.",
          "Elle a oublié le mot neige pendant l'exercice.",
          "Il va utiliser la neige dans sa phrase.",
          "Nous avons trouvé la neige dans le bulletin météo.",
          "Ce week-end, je vais observer la neige.",
          "L'élève a ajouté la neige dans sa réponse.",
          "J'ai compris le mot neige pour la première fois.",
          "Ma sœur a choisi la neige pour son exemple.",
          "Ils ont répété neige à voix haute.",
          "Nous allons revoir la neige avec le professeur.",
          "Elle a noté neige pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la neige.",
          "Après la leçon, j'ai utilisé le mot neige dans une phrase.",
          "Demain, je vais apprendre à mieux employer la neige.",
          "Quand je lis le texte, je cherche le sens de neige.",
          "Ce matin, nous avons associé la neige à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec neige.",
          "Le professeur a demandé un exemple avec la neige.",
          "J'ai choisi la neige parce que ce mot était dans la liste.",
          "Nous allons réviser la neige avant l'évaluation.",
          "Mon camarade a expliqué la neige avec ses mots.",
          "J'ai ajouté neige dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la neige semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de la neige, nous avons décidé de reporter la sortie.",
          "Si la météo annonce la neige, je prendrai des vêtements adaptés.",
          "Même si je connais le mot neige, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait la neige, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise la neige pour décrire le temps.",
          "Pendant que le professeur expliquait la neige, les élèves regardaient l'image.",
          "Puisque la neige était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris neige, tu pourras décrire la météo plus précisément.",
          "Je pense que la neige aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, la neige donne une information importante.",
          "Le phénomène dont je parle est la neige, que la météo annonce souvent.",
          "Tant que la neige restera présent, nous éviterons les activités dehors.",
          "Bien que la neige demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient la neige, je penserai à parler de la météo.",
          "Bien que le mot neige paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la neige apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la neige, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà neige, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la neige.",
          "Lorsque j'aurai mémorisé neige, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la neige.",
          "Puisque neige est utile, je le révise régulièrement.",
        ],
      } },
    { word: "orage", image: "orage.webp",        article: "l'",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait de l'orage toute la journée.",
          "Demain, il va y avoir de l'orage.",
          "Ce matin, la météo a annoncé l'orage.",
          "Quand je suis sorti, j'ai vu l'orage.",
          "Nous avons parlé de l'orage pendant le cours.",
          "Ils vont regarder l'orage sur la carte.",
          "J'ai choisi l'orage pour décrire le temps.",
          "Elle a noté l'orage dans son cahier.",
          "Avant de partir, nous avons vérifié l'orage.",
          "Le présentateur a expliqué l'orage à la télévision.",
          "Je vais regarder l'orage avant la sortie.",
          "Nous avons dessiné l'orage dans l'exercice.",
          "Hier soir, mon frère a entendu parler de l'orage.",
          "Pendant l'hiver, il y avait souvent de l'orage.",
          "Elle a oublié le mot orage pendant l'exercice.",
          "Il va utiliser l'orage dans sa phrase.",
          "Nous avons trouvé l'orage dans le bulletin météo.",
          "Ce week-end, je vais observer l'orage.",
          "L'élève a ajouté l'orage dans sa réponse.",
          "J'ai compris le mot orage pour la première fois.",
          "Ma sœur a choisi l'orage pour son exemple.",
          "Ils ont répété orage à voix haute.",
          "Nous allons revoir l'orage avec le professeur.",
          "Elle a noté orage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'orage.",
          "Après la leçon, j'ai utilisé le mot orage dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'orage.",
          "Quand je lis le texte, je cherche le sens de orage.",
          "Ce matin, nous avons associé l'orage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec orage.",
          "Le professeur a demandé un exemple avec l'orage.",
          "J'ai choisi l'orage parce que ce mot était dans la liste.",
          "Nous allons réviser l'orage avant l'évaluation.",
          "Mon camarade a expliqué l'orage avec ses mots.",
          "J'ai ajouté orage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'orage semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de l'orage, nous avons décidé de reporter la sortie.",
          "Si la météo annonce l'orage, je prendrai des vêtements adaptés.",
          "Même si je connais le mot orage, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait l'orage, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise l'orage pour décrire le temps.",
          "Pendant que le professeur expliquait l'orage, les élèves regardaient l'image.",
          "Puisque l'orage était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris orage, tu pourras décrire la météo plus précisément.",
          "Je pense que l'orage aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, l'orage donne une information importante.",
          "Le phénomène dont je parle est l'orage, que la météo annonce souvent.",
          "Tant que l'orage restera présent, nous éviterons les activités dehors.",
          "Bien que l'orage demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient l'orage, je penserai à parler de la météo.",
          "Bien que le mot orage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'orage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'orage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà orage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'orage.",
          "Lorsque j'aurai mémorisé orage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'orage.",
          "Puisque orage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "brouillard", image: "brouillard.webp",   article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait du brouillard toute la journée.",
          "Demain, il va y avoir du brouillard.",
          "Ce matin, la météo a annoncé le brouillard.",
          "Quand je suis sorti, j'ai vu le brouillard.",
          "Nous avons parlé du brouillard pendant le cours.",
          "Ils vont regarder le brouillard sur la carte.",
          "J'ai choisi le brouillard pour décrire le temps.",
          "Elle a noté le brouillard dans son cahier.",
          "Avant de partir, nous avons vérifié le brouillard.",
          "Le présentateur a expliqué le brouillard à la télévision.",
          "Je vais regarder le brouillard avant la sortie.",
          "Nous avons dessiné le brouillard dans l'exercice.",
          "Hier soir, mon frère a entendu parler du brouillard.",
          "Pendant l'hiver, il y avait souvent du brouillard.",
          "Elle a oublié le mot brouillard pendant l'exercice.",
          "Il va utiliser le brouillard dans sa phrase.",
          "Nous avons trouvé le brouillard dans le bulletin météo.",
          "Ce week-end, je vais observer le brouillard.",
          "L'élève a ajouté le brouillard dans sa réponse.",
          "J'ai compris le mot brouillard pour la première fois.",
          "Ma sœur a choisi le brouillard pour son exemple.",
          "Ils ont répété brouillard à voix haute.",
          "Nous allons revoir le brouillard avec le professeur.",
          "Elle a noté brouillard pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le brouillard.",
          "Après la leçon, j'ai utilisé le mot brouillard dans une phrase.",
          "Demain, je vais apprendre à mieux employer le brouillard.",
          "Quand je lis le texte, je cherche le sens de brouillard.",
          "Ce matin, nous avons associé le brouillard à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec brouillard.",
          "Le professeur a demandé un exemple avec le brouillard.",
          "J'ai choisi le brouillard parce que ce mot était dans la liste.",
          "Nous allons réviser le brouillard avant l'évaluation.",
          "Mon camarade a expliqué le brouillard avec ses mots.",
          "J'ai ajouté brouillard dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le brouillard semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du brouillard, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le brouillard, je prendrai des vêtements adaptés.",
          "Même si je connais le mot brouillard, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le brouillard, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le brouillard pour décrire le temps.",
          "Pendant que le professeur expliquait le brouillard, les élèves regardaient l'image.",
          "Puisque le brouillard était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris brouillard, tu pourras décrire la météo plus précisément.",
          "Je pense que le brouillard aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le brouillard donne une information importante.",
          "Le phénomène dont je parle est le brouillard, que la météo annonce souvent.",
          "Tant que le brouillard restera présent, nous éviterons les activités dehors.",
          "Bien que le brouillard demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le brouillard, je penserai à parler de la météo.",
          "Bien que le mot brouillard paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le brouillard apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le brouillard, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà brouillard, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le brouillard.",
          "Lorsque j'aurai mémorisé brouillard, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le brouillard.",
          "Puisque brouillard est utile, je le révise régulièrement.",
        ],
      } },
    { word: "gel", image: "gel.webp",          article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait du gel toute la journée.",
          "Demain, il va y avoir du gel.",
          "Ce matin, la météo a annoncé le gel.",
          "Quand je suis sorti, j'ai vu le gel.",
          "Nous avons parlé du gel pendant le cours.",
          "Ils vont regarder le gel sur la carte.",
          "J'ai choisi le gel pour décrire le temps.",
          "Elle a noté le gel dans son cahier.",
          "Avant de partir, nous avons vérifié le gel.",
          "Le présentateur a expliqué le gel à la télévision.",
          "Je vais regarder le gel avant la sortie.",
          "Nous avons dessiné le gel dans l'exercice.",
          "Hier soir, mon frère a entendu parler du gel.",
          "Pendant l'hiver, il y avait souvent du gel.",
          "Elle a oublié le mot gel pendant l'exercice.",
          "Il va utiliser le gel dans sa phrase.",
          "Nous avons trouvé le gel dans le bulletin météo.",
          "Ce week-end, je vais observer le gel.",
          "L'élève a ajouté le gel dans sa réponse.",
          "J'ai compris le mot gel pour la première fois.",
          "Ma sœur a choisi le gel pour son exemple.",
          "Ils ont répété gel à voix haute.",
          "Nous allons revoir le gel avec le professeur.",
          "Elle a noté gel pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le gel.",
          "Après la leçon, j'ai utilisé le mot gel dans une phrase.",
          "Demain, je vais apprendre à mieux employer le gel.",
          "Quand je lis le texte, je cherche le sens de gel.",
          "Ce matin, nous avons associé le gel à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec gel.",
          "Le professeur a demandé un exemple avec le gel.",
          "J'ai choisi le gel parce que ce mot était dans la liste.",
          "Nous allons réviser le gel avant l'évaluation.",
          "Mon camarade a expliqué le gel avec ses mots.",
          "J'ai ajouté gel dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le gel semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du gel, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le gel, je prendrai des vêtements adaptés.",
          "Même si je connais le mot gel, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le gel, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le gel pour décrire le temps.",
          "Pendant que le professeur expliquait le gel, les élèves regardaient l'image.",
          "Puisque le gel était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris gel, tu pourras décrire la météo plus précisément.",
          "Je pense que le gel aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le gel donne une information importante.",
          "Le phénomène dont je parle est le gel, que la météo annonce souvent.",
          "Tant que le gel restera présent, nous éviterons les activités dehors.",
          "Bien que le gel demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le gel, je penserai à parler de la météo.",
          "Bien que le mot gel paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le gel apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le gel, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà gel, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le gel.",
          "Lorsque j'aurai mémorisé gel, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le gel.",
          "Puisque gel est utile, je le révise régulièrement.",
        ],
      } },
    { word: "grêle", image: "grele.webp",        article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait de la grêle toute la journée.",
          "Demain, il va y avoir de la grêle.",
          "Ce matin, la météo a annoncé la grêle.",
          "Quand je suis sorti, j'ai vu la grêle.",
          "Nous avons parlé de la grêle pendant le cours.",
          "Ils vont regarder la grêle sur la carte.",
          "J'ai choisi la grêle pour décrire le temps.",
          "Elle a noté la grêle dans son cahier.",
          "Avant de partir, nous avons vérifié la grêle.",
          "Le présentateur a expliqué la grêle à la télévision.",
          "Je vais regarder la grêle avant la sortie.",
          "Nous avons dessiné la grêle dans l'exercice.",
          "Hier soir, mon frère a entendu parler de la grêle.",
          "Pendant l'hiver, il y avait souvent de la grêle.",
          "Elle a oublié le mot grêle pendant l'exercice.",
          "Il va utiliser la grêle dans sa phrase.",
          "Nous avons trouvé la grêle dans le bulletin météo.",
          "Ce week-end, je vais observer la grêle.",
          "L'élève a ajouté la grêle dans sa réponse.",
          "J'ai compris le mot grêle pour la première fois.",
          "Ma sœur a choisi la grêle pour son exemple.",
          "Ils ont répété grêle à voix haute.",
          "Nous allons revoir la grêle avec le professeur.",
          "Elle a noté grêle pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la grêle.",
          "Après la leçon, j'ai utilisé le mot grêle dans une phrase.",
          "Demain, je vais apprendre à mieux employer la grêle.",
          "Quand je lis le texte, je cherche le sens de grêle.",
          "Ce matin, nous avons associé la grêle à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec grêle.",
          "Le professeur a demandé un exemple avec la grêle.",
          "J'ai choisi la grêle parce que ce mot était dans la liste.",
          "Nous allons réviser la grêle avant l'évaluation.",
          "Mon camarade a expliqué la grêle avec ses mots.",
          "J'ai ajouté grêle dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la grêle semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de la grêle, nous avons décidé de reporter la sortie.",
          "Si la météo annonce la grêle, je prendrai des vêtements adaptés.",
          "Même si je connais le mot grêle, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait la grêle, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise la grêle pour décrire le temps.",
          "Pendant que le professeur expliquait la grêle, les élèves regardaient l'image.",
          "Puisque la grêle était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris grêle, tu pourras décrire la météo plus précisément.",
          "Je pense que la grêle aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, la grêle donne une information importante.",
          "Le phénomène dont je parle est la grêle, que la météo annonce souvent.",
          "Tant que la grêle restera présent, nous éviterons les activités dehors.",
          "Bien que la grêle demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient la grêle, je penserai à parler de la météo.",
          "Bien que le mot grêle paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la grêle apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la grêle, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà grêle, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la grêle.",
          "Lorsque j'aurai mémorisé grêle, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la grêle.",
          "Puisque grêle est utile, je le révise régulièrement.",
        ],
      } },
    { word: "arc-en-ciel", image: "arc-en-ciel.webp",  article: "l'",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un arc-en-ciel toute la journée.",
          "Demain, il va y avoir un arc-en-ciel.",
          "Ce matin, la météo a annoncé l'arc-en-ciel.",
          "Quand je suis sorti, j'ai vu l'arc-en-ciel.",
          "Nous avons parlé de l'arc-en-ciel pendant le cours.",
          "Ils vont regarder l'arc-en-ciel sur la carte.",
          "J'ai choisi l'arc-en-ciel pour décrire le temps.",
          "Elle a noté l'arc-en-ciel dans son cahier.",
          "Avant de partir, nous avons vérifié l'arc-en-ciel.",
          "Le présentateur a expliqué l'arc-en-ciel à la télévision.",
          "Je vais regarder l'arc-en-ciel avant la sortie.",
          "Nous avons dessiné l'arc-en-ciel dans l'exercice.",
          "Hier soir, mon frère a entendu parler de l'arc-en-ciel.",
          "Pendant l'hiver, il y avait souvent un arc-en-ciel.",
          "Elle a oublié le mot arc-en-ciel pendant l'exercice.",
          "Il va utiliser l'arc-en-ciel dans sa phrase.",
          "Nous avons trouvé l'arc-en-ciel dans le bulletin météo.",
          "Ce week-end, je vais observer l'arc-en-ciel.",
          "L'élève a ajouté l'arc-en-ciel dans sa réponse.",
          "J'ai compris le mot arc-en-ciel pour la première fois.",
          "Ma sœur a choisi l'arc-en-ciel pour son exemple.",
          "Ils ont répété arc-en-ciel à voix haute.",
          "Nous allons revoir l'arc-en-ciel avec le professeur.",
          "Elle a noté arc-en-ciel pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'arc-en-ciel.",
          "Après la leçon, j'ai utilisé le mot arc-en-ciel dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'arc-en-ciel.",
          "Quand je lis le texte, je cherche le sens de arc-en-ciel.",
          "Ce matin, nous avons associé l'arc-en-ciel à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec arc-en-ciel.",
          "Le professeur a demandé un exemple avec l'arc-en-ciel.",
          "J'ai choisi l'arc-en-ciel parce que ce mot était dans la liste.",
          "Nous allons réviser l'arc-en-ciel avant l'évaluation.",
          "Mon camarade a expliqué l'arc-en-ciel avec ses mots.",
          "J'ai ajouté arc-en-ciel dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'arc-en-ciel semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de l'arc-en-ciel, nous avons décidé de reporter la sortie.",
          "Si la météo annonce l'arc-en-ciel, je prendrai des vêtements adaptés.",
          "Même si je connais le mot arc-en-ciel, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait l'arc-en-ciel, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise l'arc-en-ciel pour décrire le temps.",
          "Pendant que le professeur expliquait l'arc-en-ciel, les élèves regardaient l'image.",
          "Puisque l'arc-en-ciel était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris arc-en-ciel, tu pourras décrire la météo plus précisément.",
          "Je pense que l'arc-en-ciel aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, l'arc-en-ciel donne une information importante.",
          "Le phénomène dont je parle est l'arc-en-ciel, que la météo annonce souvent.",
          "Tant que l'arc-en-ciel restera présent, nous éviterons les activités dehors.",
          "Bien que l'arc-en-ciel demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient l'arc-en-ciel, je penserai à parler de la météo.",
          "Bien que le mot arc-en-ciel paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'arc-en-ciel apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'arc-en-ciel, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà arc-en-ciel, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'arc-en-ciel.",
          "Lorsque j'aurai mémorisé arc-en-ciel, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'arc-en-ciel.",
          "Puisque arc-en-ciel est utile, je le révise régulièrement.",
        ],
      } },
    { word: "averse", image: "averse.webp",       article: "l'",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait une averse toute la journée.",
          "Demain, il va y avoir une averse.",
          "Ce matin, la météo a annoncé l'averse.",
          "Quand je suis sorti, j'ai vu l'averse.",
          "Nous avons parlé de l'averse pendant le cours.",
          "Ils vont regarder l'averse sur la carte.",
          "J'ai choisi l'averse pour décrire le temps.",
          "Elle a noté l'averse dans son cahier.",
          "Avant de partir, nous avons vérifié l'averse.",
          "Le présentateur a expliqué l'averse à la télévision.",
          "Je vais regarder l'averse avant la sortie.",
          "Nous avons dessiné l'averse dans l'exercice.",
          "Hier soir, mon frère a entendu parler de l'averse.",
          "Pendant l'hiver, il y avait souvent une averse.",
          "Elle a oublié le mot averse pendant l'exercice.",
          "Il va utiliser l'averse dans sa phrase.",
          "Nous avons trouvé l'averse dans le bulletin météo.",
          "Ce week-end, je vais observer l'averse.",
          "L'élève a ajouté l'averse dans sa réponse.",
          "J'ai compris le mot averse pour la première fois.",
          "Ma sœur a choisi l'averse pour son exemple.",
          "Ils ont répété averse à voix haute.",
          "Nous allons revoir l'averse avec le professeur.",
          "Elle a noté averse pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'averse.",
          "Après la leçon, j'ai utilisé le mot averse dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'averse.",
          "Quand je lis le texte, je cherche le sens de averse.",
          "Ce matin, nous avons associé l'averse à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec averse.",
          "Le professeur a demandé un exemple avec l'averse.",
          "J'ai choisi l'averse parce que ce mot était dans la liste.",
          "Nous allons réviser l'averse avant l'évaluation.",
          "Mon camarade a expliqué l'averse avec ses mots.",
          "J'ai ajouté averse dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'averse semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de l'averse, nous avons décidé de reporter la sortie.",
          "Si la météo annonce l'averse, je prendrai des vêtements adaptés.",
          "Même si je connais le mot averse, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait l'averse, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise l'averse pour décrire le temps.",
          "Pendant que le professeur expliquait l'averse, les élèves regardaient l'image.",
          "Puisque l'averse était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris averse, tu pourras décrire la météo plus précisément.",
          "Je pense que l'averse aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, l'averse donne une information importante.",
          "Le phénomène dont je parle est l'averse, que la météo annonce souvent.",
          "Tant que l'averse restera présent, nous éviterons les activités dehors.",
          "Bien que l'averse demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient l'averse, je penserai à parler de la météo.",
          "Bien que le mot averse paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'averse apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'averse, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà averse, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'averse.",
          "Lorsque j'aurai mémorisé averse, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'averse.",
          "Puisque averse est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ciel", image: "ciel.webp",         article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un ciel toute la journée.",
          "Demain, il va y avoir un ciel.",
          "Ce matin, la météo a annoncé le ciel.",
          "Quand je suis sorti, j'ai vu le ciel.",
          "Nous avons parlé du ciel pendant le cours.",
          "Ils vont regarder le ciel sur la carte.",
          "J'ai choisi le ciel pour décrire le temps.",
          "Elle a noté le ciel dans son cahier.",
          "Avant de partir, nous avons vérifié le ciel.",
          "Le présentateur a expliqué le ciel à la télévision.",
          "Je vais regarder le ciel avant la sortie.",
          "Nous avons dessiné le ciel dans l'exercice.",
          "Hier soir, mon frère a entendu parler du ciel.",
          "Pendant l'hiver, il y avait souvent un ciel.",
          "Elle a oublié le mot ciel pendant l'exercice.",
          "Il va utiliser le ciel dans sa phrase.",
          "Nous avons trouvé le ciel dans le bulletin météo.",
          "Ce week-end, je vais observer le ciel.",
          "L'élève a ajouté le ciel dans sa réponse.",
          "J'ai compris le mot ciel pour la première fois.",
          "Ma sœur a choisi le ciel pour son exemple.",
          "Ils ont répété ciel à voix haute.",
          "Nous allons revoir le ciel avec le professeur.",
          "Elle a noté ciel pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le ciel.",
          "Après la leçon, j'ai utilisé le mot ciel dans une phrase.",
          "Demain, je vais apprendre à mieux employer le ciel.",
          "Quand je lis le texte, je cherche le sens de ciel.",
          "Ce matin, nous avons associé le ciel à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ciel.",
          "Le professeur a demandé un exemple avec le ciel.",
          "J'ai choisi le ciel parce que ce mot était dans la liste.",
          "Nous allons réviser le ciel avant l'évaluation.",
          "Mon camarade a expliqué le ciel avec ses mots.",
          "J'ai ajouté ciel dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le ciel semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait du ciel, nous avons décidé de reporter la sortie.",
          "Si la météo annonce le ciel, je prendrai des vêtements adaptés.",
          "Même si je connais le mot ciel, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait le ciel, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise le ciel pour décrire le temps.",
          "Pendant que le professeur expliquait le ciel, les élèves regardaient l'image.",
          "Puisque le ciel était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris ciel, tu pourras décrire la météo plus précisément.",
          "Je pense que le ciel aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, le ciel donne une information importante.",
          "Le phénomène dont je parle est le ciel, que la météo annonce souvent.",
          "Tant que le ciel restera présent, nous éviterons les activités dehors.",
          "Bien que le ciel demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient le ciel, je penserai à parler de la météo.",
          "Bien que le mot ciel paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le ciel apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le ciel, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ciel, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le ciel.",
          "Lorsque j'aurai mémorisé ciel, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le ciel.",
          "Puisque ciel est utile, je le révise régulièrement.",
        ],
      } },
    { word: "humide", image: "humide.webp", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un humide toute la journée.",
          "Demain, il va y avoir un humide.",
          "Ce matin, la météo a annoncé humide.",
          "Quand je suis sorti, j'ai vu humide.",
          "Nous avons parlé de humide pendant le cours.",
          "Ils vont regarder humide sur la carte.",
          "J'ai choisi humide pour décrire le temps.",
          "Elle a noté humide dans son cahier.",
          "Avant de partir, nous avons vérifié humide.",
          "Le présentateur a expliqué humide à la télévision.",
          "Je vais regarder humide avant la sortie.",
          "Nous avons dessiné humide dans l'exercice.",
          "Hier soir, mon frère a entendu parler de humide.",
          "Pendant l'hiver, il y avait souvent un humide.",
          "Elle a oublié le mot humide pendant l'exercice.",
          "Il va utiliser humide dans sa phrase.",
          "Nous avons trouvé humide dans le bulletin météo.",
          "Ce week-end, je vais observer humide.",
          "L'élève a ajouté humide dans sa réponse.",
          "J'ai compris le mot humide pour la première fois.",
          "Ma sœur a choisi humide pour son exemple.",
          "Ils ont répété humide à voix haute.",
          "Nous allons revoir humide avec le professeur.",
          "Elle a noté humide pour ne pas l'oublier.",
          "La classe a demandé un exemple avec humide.",
          "Après la leçon, j'ai utilisé le mot humide dans une phrase.",
          "Demain, je vais apprendre à mieux employer humide.",
          "Quand je lis le texte, je cherche le sens de humide.",
          "Ce matin, nous avons associé humide à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec humide.",
          "Le professeur a demandé un exemple avec humide.",
          "J'ai choisi humide parce que ce mot était dans la liste.",
          "Nous allons réviser humide avant l'évaluation.",
          "Mon camarade a expliqué humide avec ses mots.",
          "J'ai ajouté humide dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que humide semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de humide, nous avons décidé de reporter la sortie.",
          "Si la météo annonce humide, je prendrai des vêtements adaptés.",
          "Même si je connais le mot humide, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait humide, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise humide pour décrire le temps.",
          "Pendant que le professeur expliquait humide, les élèves regardaient l'image.",
          "Puisque humide était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris humide, tu pourras décrire la météo plus précisément.",
          "Je pense que humide aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, humide donne une information importante.",
          "Le phénomène dont je parle est humide, que la météo annonce souvent.",
          "Tant que humide restera présent, nous éviterons les activités dehors.",
          "Bien que humide demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient humide, je penserai à parler de la météo.",
          "Bien que le mot humide paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme humide apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien humide, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà humide, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser humide.",
          "Lorsque j'aurai mémorisé humide, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec humide.",
          "Puisque humide est utile, je le révise régulièrement.",
        ],
      } },
    { word: "sec", image: "sec.webp",          feminine: "sèche", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un sec toute la journée.",
          "Demain, il va y avoir un sec.",
          "Ce matin, la météo a annoncé sec.",
          "Quand je suis sorti, j'ai vu sec.",
          "Nous avons parlé de sec pendant le cours.",
          "Ils vont regarder sec sur la carte.",
          "J'ai choisi sec pour décrire le temps.",
          "Elle a noté sec dans son cahier.",
          "Avant de partir, nous avons vérifié sec.",
          "Le présentateur a expliqué sec à la télévision.",
          "Je vais regarder sec avant la sortie.",
          "Nous avons dessiné sec dans l'exercice.",
          "Hier soir, mon frère a entendu parler de sec.",
          "Pendant l'hiver, il y avait souvent un sec.",
          "Elle a oublié le mot sec pendant l'exercice.",
          "Il va utiliser sec dans sa phrase.",
          "Nous avons trouvé sec dans le bulletin météo.",
          "Ce week-end, je vais observer sec.",
          "L'élève a ajouté sec dans sa réponse.",
          "J'ai compris le mot sec pour la première fois.",
          "Ma sœur a choisi sec pour son exemple.",
          "Ils ont répété sec à voix haute.",
          "Nous allons revoir sec avec le professeur.",
          "Elle a noté sec pour ne pas l'oublier.",
          "La classe a demandé un exemple avec sec.",
          "Après la leçon, j'ai utilisé le mot sec dans une phrase.",
          "Demain, je vais apprendre à mieux employer sec.",
          "Quand je lis le texte, je cherche le sens de sec.",
          "Ce matin, nous avons associé sec à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec sec.",
          "Le professeur a demandé un exemple avec sec.",
          "J'ai choisi sec parce que ce mot était dans la liste.",
          "Nous allons réviser sec avant l'évaluation.",
          "Mon camarade a expliqué sec avec ses mots.",
          "J'ai ajouté sec dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que sec semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de sec, nous avons décidé de reporter la sortie.",
          "Si la météo annonce sec, je prendrai des vêtements adaptés.",
          "Même si je connais le mot sec, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait sec, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise sec pour décrire le temps.",
          "Pendant que le professeur expliquait sec, les élèves regardaient l'image.",
          "Puisque sec était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris sec, tu pourras décrire la météo plus précisément.",
          "Je pense que sec aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, sec donne une information importante.",
          "Le phénomène dont je parle est sec, que la météo annonce souvent.",
          "Tant que sec restera présent, nous éviterons les activités dehors.",
          "Bien que sec demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient sec, je penserai à parler de la météo.",
          "Bien que le mot sec paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme sec apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien sec, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà sec, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser sec.",
          "Lorsque j'aurai mémorisé sec, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec sec.",
          "Puisque sec est utile, je le révise régulièrement.",
        ],
      } },
    { word: "doux", image: "doux.webp",         feminine: "douce", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un doux toute la journée.",
          "Demain, il va y avoir un doux.",
          "Ce matin, la météo a annoncé doux.",
          "Quand je suis sorti, j'ai vu doux.",
          "Nous avons parlé de doux pendant le cours.",
          "Ils vont regarder doux sur la carte.",
          "J'ai choisi doux pour décrire le temps.",
          "Elle a noté doux dans son cahier.",
          "Avant de partir, nous avons vérifié doux.",
          "Le présentateur a expliqué doux à la télévision.",
          "Je vais regarder doux avant la sortie.",
          "Nous avons dessiné doux dans l'exercice.",
          "Hier soir, mon frère a entendu parler de doux.",
          "Pendant l'hiver, il y avait souvent un doux.",
          "Elle a oublié le mot doux pendant l'exercice.",
          "Il va utiliser doux dans sa phrase.",
          "Nous avons trouvé doux dans le bulletin météo.",
          "Ce week-end, je vais observer doux.",
          "L'élève a ajouté doux dans sa réponse.",
          "J'ai compris le mot doux pour la première fois.",
          "Ma sœur a choisi doux pour son exemple.",
          "Ils ont répété doux à voix haute.",
          "Nous allons revoir doux avec le professeur.",
          "Elle a noté doux pour ne pas l'oublier.",
          "La classe a demandé un exemple avec doux.",
          "Après la leçon, j'ai utilisé le mot doux dans une phrase.",
          "Demain, je vais apprendre à mieux employer doux.",
          "Quand je lis le texte, je cherche le sens de doux.",
          "Ce matin, nous avons associé doux à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec doux.",
          "Le professeur a demandé un exemple avec doux.",
          "J'ai choisi doux parce que ce mot était dans la liste.",
          "Nous allons réviser doux avant l'évaluation.",
          "Mon camarade a expliqué doux avec ses mots.",
          "J'ai ajouté doux dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que doux semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de doux, nous avons décidé de reporter la sortie.",
          "Si la météo annonce doux, je prendrai des vêtements adaptés.",
          "Même si je connais le mot doux, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait doux, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise doux pour décrire le temps.",
          "Pendant que le professeur expliquait doux, les élèves regardaient l'image.",
          "Puisque doux était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris doux, tu pourras décrire la météo plus précisément.",
          "Je pense que doux aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, doux donne une information importante.",
          "Le phénomène dont je parle est doux, que la météo annonce souvent.",
          "Tant que doux restera présent, nous éviterons les activités dehors.",
          "Bien que doux demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient doux, je penserai à parler de la météo.",
          "Bien que le mot doux paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme doux apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien doux, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà doux, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser doux.",
          "Lorsque j'aurai mémorisé doux, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec doux.",
          "Puisque doux est utile, je le révise régulièrement.",
        ],
      } },
    { word: "chaud", image: "chaud.webp",        feminine: "chaude", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un chaud toute la journée.",
          "Demain, il va y avoir un chaud.",
          "Ce matin, la météo a annoncé chaud.",
          "Quand je suis sorti, j'ai vu chaud.",
          "Nous avons parlé de chaud pendant le cours.",
          "Ils vont regarder chaud sur la carte.",
          "J'ai choisi chaud pour décrire le temps.",
          "Elle a noté chaud dans son cahier.",
          "Avant de partir, nous avons vérifié chaud.",
          "Le présentateur a expliqué chaud à la télévision.",
          "Je vais regarder chaud avant la sortie.",
          "Nous avons dessiné chaud dans l'exercice.",
          "Hier soir, mon frère a entendu parler de chaud.",
          "Pendant l'hiver, il y avait souvent un chaud.",
          "Elle a oublié le mot chaud pendant l'exercice.",
          "Il va utiliser chaud dans sa phrase.",
          "Nous avons trouvé chaud dans le bulletin météo.",
          "Ce week-end, je vais observer chaud.",
          "L'élève a ajouté chaud dans sa réponse.",
          "J'ai compris le mot chaud pour la première fois.",
          "Ma sœur a choisi chaud pour son exemple.",
          "Ils ont répété chaud à voix haute.",
          "Nous allons revoir chaud avec le professeur.",
          "Elle a noté chaud pour ne pas l'oublier.",
          "La classe a demandé un exemple avec chaud.",
          "Après la leçon, j'ai utilisé le mot chaud dans une phrase.",
          "Demain, je vais apprendre à mieux employer chaud.",
          "Quand je lis le texte, je cherche le sens de chaud.",
          "Ce matin, nous avons associé chaud à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec chaud.",
          "Le professeur a demandé un exemple avec chaud.",
          "J'ai choisi chaud parce que ce mot était dans la liste.",
          "Nous allons réviser chaud avant l'évaluation.",
          "Mon camarade a expliqué chaud avec ses mots.",
          "J'ai ajouté chaud dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que chaud semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de chaud, nous avons décidé de reporter la sortie.",
          "Si la météo annonce chaud, je prendrai des vêtements adaptés.",
          "Même si je connais le mot chaud, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait chaud, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise chaud pour décrire le temps.",
          "Pendant que le professeur expliquait chaud, les élèves regardaient l'image.",
          "Puisque chaud était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris chaud, tu pourras décrire la météo plus précisément.",
          "Je pense que chaud aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, chaud donne une information importante.",
          "Le phénomène dont je parle est chaud, que la météo annonce souvent.",
          "Tant que chaud restera présent, nous éviterons les activités dehors.",
          "Bien que chaud demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient chaud, je penserai à parler de la météo.",
          "Bien que le mot chaud paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme chaud apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien chaud, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chaud, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser chaud.",
          "Lorsque j'aurai mémorisé chaud, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec chaud.",
          "Puisque chaud est utile, je le révise régulièrement.",
        ],
      } },
    { word: "froid", image: "froid.webp",        feminine: "froide", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait de froid toute la journée.",
          "Demain, il va y avoir de froid.",
          "Ce matin, la météo a annoncé froid.",
          "Quand je suis sorti, j'ai vu froid.",
          "Nous avons parlé de froid pendant le cours.",
          "Ils vont regarder froid sur la carte.",
          "J'ai choisi froid pour décrire le temps.",
          "Elle a noté froid dans son cahier.",
          "Avant de partir, nous avons vérifié froid.",
          "Le présentateur a expliqué froid à la télévision.",
          "Je vais regarder froid avant la sortie.",
          "Nous avons dessiné froid dans l'exercice.",
          "Hier soir, mon frère a entendu parler de froid.",
          "Pendant l'hiver, il y avait souvent de froid.",
          "Elle a oublié le mot froid pendant l'exercice.",
          "Il va utiliser froid dans sa phrase.",
          "Nous avons trouvé froid dans le bulletin météo.",
          "Ce week-end, je vais observer froid.",
          "L'élève a ajouté froid dans sa réponse.",
          "J'ai compris le mot froid pour la première fois.",
          "Ma sœur a choisi froid pour son exemple.",
          "Ils ont répété froid à voix haute.",
          "Nous allons revoir froid avec le professeur.",
          "Elle a noté froid pour ne pas l'oublier.",
          "La classe a demandé un exemple avec froid.",
          "Après la leçon, j'ai utilisé le mot froid dans une phrase.",
          "Demain, je vais apprendre à mieux employer froid.",
          "Quand je lis le texte, je cherche le sens de froid.",
          "Ce matin, nous avons associé froid à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec froid.",
          "Le professeur a demandé un exemple avec froid.",
          "J'ai choisi froid parce que ce mot était dans la liste.",
          "Nous allons réviser froid avant l'évaluation.",
          "Mon camarade a expliqué froid avec ses mots.",
          "J'ai ajouté froid dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que froid semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de froid, nous avons décidé de reporter la sortie.",
          "Si la météo annonce froid, je prendrai des vêtements adaptés.",
          "Même si je connais le mot froid, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait froid, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise froid pour décrire le temps.",
          "Pendant que le professeur expliquait froid, les élèves regardaient l'image.",
          "Puisque froid était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris froid, tu pourras décrire la météo plus précisément.",
          "Je pense que froid aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, froid donne une information importante.",
          "Le phénomène dont je parle est froid, que la météo annonce souvent.",
          "Tant que froid restera présent, nous éviterons les activités dehors.",
          "Bien que froid demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient froid, je penserai à parler de la météo.",
          "Bien que le mot froid paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme froid apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien froid, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà froid, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser froid.",
          "Lorsque j'aurai mémorisé froid, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec froid.",
          "Puisque froid est utile, je le révise régulièrement.",
        ],
      } },
    { word: "frais", image: "frais.webp",        feminine: "fraîche", exampleSentences: {
        a1: [],
        a2: [
          "Hier, il y avait un frais toute la journée.",
          "Demain, il va y avoir un frais.",
          "Ce matin, la météo a annoncé frais.",
          "Quand je suis sorti, j'ai vu frais.",
          "Nous avons parlé de frais pendant le cours.",
          "Ils vont regarder frais sur la carte.",
          "J'ai choisi frais pour décrire le temps.",
          "Elle a noté frais dans son cahier.",
          "Avant de partir, nous avons vérifié frais.",
          "Le présentateur a expliqué frais à la télévision.",
          "Je vais regarder frais avant la sortie.",
          "Nous avons dessiné frais dans l'exercice.",
          "Hier soir, mon frère a entendu parler de frais.",
          "Pendant l'hiver, il y avait souvent un frais.",
          "Elle a oublié le mot frais pendant l'exercice.",
          "Il va utiliser frais dans sa phrase.",
          "Nous avons trouvé frais dans le bulletin météo.",
          "Ce week-end, je vais observer frais.",
          "L'élève a ajouté frais dans sa réponse.",
          "J'ai compris le mot frais pour la première fois.",
          "Ma sœur a choisi frais pour son exemple.",
          "Ils ont répété frais à voix haute.",
          "Nous allons revoir frais avec le professeur.",
          "Elle a noté frais pour ne pas l'oublier.",
          "La classe a demandé un exemple avec frais.",
          "Après la leçon, j'ai utilisé le mot frais dans une phrase.",
          "Demain, je vais apprendre à mieux employer frais.",
          "Quand je lis le texte, je cherche le sens de frais.",
          "Ce matin, nous avons associé frais à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec frais.",
          "Le professeur a demandé un exemple avec frais.",
          "J'ai choisi frais parce que ce mot était dans la liste.",
          "Nous allons réviser frais avant l'évaluation.",
          "Mon camarade a expliqué frais avec ses mots.",
          "J'ai ajouté frais dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que frais semble banal, il peut changer toute l'organisation de la journée.",
          "Comme il y avait de frais, nous avons décidé de reporter la sortie.",
          "Si la météo annonce frais, je prendrai des vêtements adaptés.",
          "Même si je connais le mot frais, je dois encore l'utiliser correctement.",
          "Le bulletin, qui annonçait frais, a surpris plusieurs élèves.",
          "La phrase que nous écrivons utilise frais pour décrire le temps.",
          "Pendant que le professeur expliquait frais, les élèves regardaient l'image.",
          "Puisque frais était difficile à représenter, nous avons cherché un autre exemple.",
          "Lorsque tu auras compris frais, tu pourras décrire la météo plus précisément.",
          "Je pense que frais aide à comprendre la situation parce que le temps influence nos activités.",
          "Même quand la phrase est courte, frais donne une information importante.",
          "Le phénomène dont je parle est frais, que la météo annonce souvent.",
          "Tant que frais restera présent, nous éviterons les activités dehors.",
          "Bien que frais demande peu de mots, il décrit clairement le temps.",
          "Si l'exercice contient frais, je penserai à parler de la météo.",
          "Bien que le mot frais paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme frais apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien frais, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà frais, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser frais.",
          "Lorsque j'aurai mémorisé frais, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec frais.",
          "Puisque frais est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il fait beau, le ___ brille dans le ciel.",              answer: "soleil" },
    { sentence: "Le ciel est couvert de ___ noir, il va pleuvoir.",       answer: "nuage" },
    { sentence: "Après la ___, on peut voir un arc-en-ciel.",             answer: "pluie" },
  ],
};
