import type { VocabTheme } from "../../vocabulary-data";

export const V2_SAISONS_THEME: VocabTheme = {
  slug: "v2-saisons",
  code: "V2.3",
  title: "Les saisons",
  section: "V2",
  words: [
    { word: "printemps", image: "printemps.webp",     article: "le",  gender: "m", definition: "Le printemps est saison entre l'hiver et l'été. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le printemps.",
          "Je note le printemps.",
          "Le printemps est important.",
          "Le printemps est utile.",
          "Je regarde le printemps.",
          "Je lis le printemps.",
          "Tu écris le printemps.",
          "Il apprend le printemps.",
          "Elle répète printemps.",
          "Nous parlons du printemps.",
          "Vous utilisez le printemps.",
          "Ils choisissent le printemps.",
          "Elles écrivent printemps.",
          "Le printemps est dans le calendrier.",
          "Le printemps est au tableau.",
          "Je cherche le printemps.",
          "Je comprends printemps.",
          "Il montre le printemps.",
          "Elle demande le printemps.",
          "Le professeur explique le printemps.",
          "La classe étudie le printemps.",
          "Cette période est simple.",
          "Je répète printemps.",
          "Nous écrivons printemps.",
          "Tu apprends printemps.",
          "Aujourd'hui, je vois le printemps.",
          "Dans mon cahier, j'écris printemps.",
          "Le mot printemps est nouveau pour moi.",
          "Je répète printemps à voix haute.",
          "Tu connais le printemps.",
          "Nous dessinons le printemps.",
          "La classe regarde le printemps.",
          "Je montre le printemps au professeur.",
          "Il y a un printemps dans l'image.",
          "Cette leçon parle du printemps.",
        ],
        a2: [
          "Hier, j'ai étudié le printemps en classe.",
          "Demain, je vais revoir le printemps.",
          "Quand j'étais débutant, je confondais souvent printemps.",
          "Ce matin, le professeur a expliqué le printemps.",
          "Nous avons utilisé le printemps dans un exercice.",
          "Ils vont apprendre printemps cette semaine.",
          "J'ai choisi le printemps parce que c'était utile.",
          "Elle a écrit printemps dans son cahier.",
          "Avant le test, nous avons répété printemps.",
          "Le groupe a parlé du printemps pendant le cours.",
          "Je vais pratiquer printemps après le repas.",
          "Nous avons corrigé une phrase avec printemps.",
          "Hier soir, mon frère a révisé le printemps.",
          "Pendant les vacances, je revoyais souvent printemps.",
          "Elle a oublié printemps pendant l'exercice.",
          "Il va utiliser le printemps dans sa phrase.",
          "Nous avons trouvé printemps dans le texte.",
          "Ce week-end, je vais mémoriser printemps.",
          "L'élève a ajouté printemps dans sa réponse.",
          "J'ai compris printemps pour la première fois.",
          "Ma sœur a choisi le printemps pour son exemple.",
          "Ils ont répété printemps à voix haute.",
          "Nous allons revoir le printemps avec le professeur.",
          "Elle a noté printemps pour ne pas l'oublier.",
          "La classe a demandé le printemps au tableau.",
          "Après la leçon, j'ai utilisé le mot printemps dans une phrase.",
          "Demain, je vais apprendre à mieux employer le printemps.",
          "Quand je lis le texte, je cherche le sens de printemps.",
          "Ce matin, nous avons associé le printemps à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec printemps.",
          "Le professeur a demandé un exemple avec le printemps.",
          "J'ai choisi le printemps parce que ce mot était dans la liste.",
          "Nous allons réviser le printemps avant l'évaluation.",
          "Mon camarade a expliqué le printemps avec ses mots.",
          "J'ai ajouté printemps dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que printemps semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le printemps revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises printemps, tu comprendras mieux les textes du calendrier.",
          "Même si je connais printemps, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le printemps comme exemple.",
          "La leçon que nous travaillons utilise printemps dans plusieurs phrases.",
          "Pendant que le professeur expliquait le printemps, les élèves prenaient des notes.",
          "Puisque printemps était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé printemps, tu pourras passer à la suite.",
          "Je pense que le printemps aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, printemps peut être important.",
          "Le mot dont je parle est printemps, que la classe doit retenir.",
          "Tant que tu pratiqueras printemps, tu feras des progrès.",
          "Bien que printemps demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient printemps, je lirai la consigne avec soin.",
          "Bien que le mot printemps paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le printemps apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le printemps, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà printemps, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le printemps.",
          "Lorsque j'aurai mémorisé printemps, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le printemps.",
          "Puisque printemps est utile, je le révise régulièrement.",
        ],
      } },
    { word: "été", image: "ete.webp",           article: "l'",  gender: "m", definition: "L'été est saison la plus chaude de l'année. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'été.",
          "Je note l'été.",
          "L'été est important.",
          "L'été est utile.",
          "Je regarde l'été.",
          "Je lis l'été.",
          "Tu écris l'été.",
          "Il apprend l'été.",
          "Elle répète été.",
          "Nous parlons de l'été.",
          "Vous utilisez l'été.",
          "Ils choisissent l'été.",
          "Elles écrivent été.",
          "L'été est dans le calendrier.",
          "L'été est au tableau.",
          "Je cherche l'été.",
          "Je comprends été.",
          "Il montre l'été.",
          "Elle demande l'été.",
          "Le professeur explique l'été.",
          "La classe étudie l'été.",
          "Cette période est simple.",
          "Je répète été.",
          "Nous écrivons été.",
          "Tu apprends été.",
          "Aujourd'hui, je vois l'été.",
          "Dans mon cahier, j'écris été.",
          "Le mot été est nouveau pour moi.",
          "Je répète été à voix haute.",
          "Tu connais l'été.",
          "Nous dessinons l'été.",
          "La classe regarde l'été.",
          "Je montre l'été au professeur.",
          "Il y a un été dans l'image.",
          "Cette leçon parle de l'été.",
        ],
        a2: [
          "Hier, j'ai étudié l'été en classe.",
          "Demain, je vais revoir l'été.",
          "Quand j'étais débutant, je confondais souvent été.",
          "Ce matin, le professeur a expliqué l'été.",
          "Nous avons utilisé l'été dans un exercice.",
          "Ils vont apprendre été cette semaine.",
          "J'ai choisi l'été parce que c'était utile.",
          "Elle a écrit été dans son cahier.",
          "Avant le test, nous avons répété été.",
          "Le groupe a parlé de l'été pendant le cours.",
          "Je vais pratiquer été après le repas.",
          "Nous avons corrigé une phrase avec été.",
          "Hier soir, mon frère a révisé l'été.",
          "Pendant les vacances, je revoyais souvent été.",
          "Elle a oublié été pendant l'exercice.",
          "Il va utiliser l'été dans sa phrase.",
          "Nous avons trouvé été dans le texte.",
          "Ce week-end, je vais mémoriser été.",
          "L'élève a ajouté été dans sa réponse.",
          "J'ai compris été pour la première fois.",
          "Ma sœur a choisi l'été pour son exemple.",
          "Ils ont répété été à voix haute.",
          "Nous allons revoir l'été avec le professeur.",
          "Elle a noté été pour ne pas l'oublier.",
          "La classe a demandé l'été au tableau.",
          "Après la leçon, j'ai utilisé le mot été dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'été.",
          "Quand je lis le texte, je cherche le sens de été.",
          "Ce matin, nous avons associé l'été à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec été.",
          "Le professeur a demandé un exemple avec l'été.",
          "J'ai choisi l'été parce que ce mot était dans la liste.",
          "Nous allons réviser l'été avant l'évaluation.",
          "Mon camarade a expliqué l'été avec ses mots.",
          "J'ai ajouté été dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que été semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'été revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises été, tu comprendras mieux les textes du calendrier.",
          "Même si je connais été, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'été comme exemple.",
          "La leçon que nous travaillons utilise été dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'été, les élèves prenaient des notes.",
          "Puisque été était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé été, tu pourras passer à la suite.",
          "Je pense que l'été aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, été peut être important.",
          "Le mot dont je parle est été, que la classe doit retenir.",
          "Tant que tu pratiqueras été, tu feras des progrès.",
          "Bien que été demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient été, je lirai la consigne avec soin.",
          "Bien que le mot été paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'été apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'été, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà été, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'été.",
          "Lorsque j'aurai mémorisé été, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'été.",
          "Puisque été est utile, je le révise régulièrement.",
        ],
      } },
    { word: "automne", image: "automne.webp",       article: "l'",  gender: "m", definition: "L'automne est saison entre l'été et l'hiver. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'automne.",
          "Je note l'automne.",
          "L'automne est important.",
          "L'automne est utile.",
          "Je regarde l'automne.",
          "Je lis l'automne.",
          "Tu écris l'automne.",
          "Il apprend l'automne.",
          "Elle répète automne.",
          "Nous parlons de l'automne.",
          "Vous utilisez l'automne.",
          "Ils choisissent l'automne.",
          "Elles écrivent automne.",
          "L'automne est dans le calendrier.",
          "L'automne est au tableau.",
          "Je cherche l'automne.",
          "Je comprends automne.",
          "Il montre l'automne.",
          "Elle demande l'automne.",
          "Le professeur explique l'automne.",
          "La classe étudie l'automne.",
          "Cette période est simple.",
          "Je répète automne.",
          "Nous écrivons automne.",
          "Tu apprends automne.",
          "Aujourd'hui, je vois l'automne.",
          "Dans mon cahier, j'écris automne.",
          "Le mot automne est nouveau pour moi.",
          "Je répète automne à voix haute.",
          "Tu connais l'automne.",
          "Nous dessinons l'automne.",
          "La classe regarde l'automne.",
          "Je montre l'automne au professeur.",
          "Il y a un automne dans l'image.",
          "Cette leçon parle de l'automne.",
        ],
        a2: [
          "Hier, j'ai étudié l'automne en classe.",
          "Demain, je vais revoir l'automne.",
          "Quand j'étais débutant, je confondais souvent automne.",
          "Ce matin, le professeur a expliqué l'automne.",
          "Nous avons utilisé l'automne dans un exercice.",
          "Ils vont apprendre automne cette semaine.",
          "J'ai choisi l'automne parce que c'était utile.",
          "Elle a écrit automne dans son cahier.",
          "Avant le test, nous avons répété automne.",
          "Le groupe a parlé de l'automne pendant le cours.",
          "Je vais pratiquer automne après le repas.",
          "Nous avons corrigé une phrase avec automne.",
          "Hier soir, mon frère a révisé l'automne.",
          "Pendant les vacances, je revoyais souvent automne.",
          "Elle a oublié automne pendant l'exercice.",
          "Il va utiliser l'automne dans sa phrase.",
          "Nous avons trouvé automne dans le texte.",
          "Ce week-end, je vais mémoriser automne.",
          "L'élève a ajouté automne dans sa réponse.",
          "J'ai compris automne pour la première fois.",
          "Ma sœur a choisi l'automne pour son exemple.",
          "Ils ont répété automne à voix haute.",
          "Nous allons revoir l'automne avec le professeur.",
          "Elle a noté automne pour ne pas l'oublier.",
          "La classe a demandé l'automne au tableau.",
          "Après la leçon, j'ai utilisé le mot automne dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'automne.",
          "Quand je lis le texte, je cherche le sens de automne.",
          "Ce matin, nous avons associé l'automne à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec automne.",
          "Le professeur a demandé un exemple avec l'automne.",
          "J'ai choisi l'automne parce que ce mot était dans la liste.",
          "Nous allons réviser l'automne avant l'évaluation.",
          "Mon camarade a expliqué l'automne avec ses mots.",
          "J'ai ajouté automne dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que automne semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'automne revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises automne, tu comprendras mieux les textes du calendrier.",
          "Même si je connais automne, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'automne comme exemple.",
          "La leçon que nous travaillons utilise automne dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'automne, les élèves prenaient des notes.",
          "Puisque automne était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé automne, tu pourras passer à la suite.",
          "Je pense que l'automne aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, automne peut être important.",
          "Le mot dont je parle est automne, que la classe doit retenir.",
          "Tant que tu pratiqueras automne, tu feras des progrès.",
          "Bien que automne demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient automne, je lirai la consigne avec soin.",
          "Bien que le mot automne paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'automne apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'automne, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà automne, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'automne.",
          "Lorsque j'aurai mémorisé automne, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'automne.",
          "Puisque automne est utile, je le révise régulièrement.",
        ],
      } },
    { word: "hiver", image: "hiver.webp",         article: "l'",  gender: "m", definition: "L'hiver est saison la plus froide de l'année. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'hiver.",
          "Je note l'hiver.",
          "L'hiver est important.",
          "L'hiver est utile.",
          "Je regarde l'hiver.",
          "Je lis l'hiver.",
          "Tu écris l'hiver.",
          "Il apprend l'hiver.",
          "Elle répète hiver.",
          "Nous parlons de l'hiver.",
          "Vous utilisez l'hiver.",
          "Ils choisissent l'hiver.",
          "Elles écrivent hiver.",
          "L'hiver est dans le calendrier.",
          "L'hiver est au tableau.",
          "Je cherche l'hiver.",
          "Je comprends hiver.",
          "Il montre l'hiver.",
          "Elle demande l'hiver.",
          "Le professeur explique l'hiver.",
          "La classe étudie l'hiver.",
          "Cette période est simple.",
          "Je répète hiver.",
          "Nous écrivons hiver.",
          "Tu apprends hiver.",
          "Aujourd'hui, je vois l'hiver.",
          "Dans mon cahier, j'écris hiver.",
          "Le mot hiver est nouveau pour moi.",
          "Je répète hiver à voix haute.",
          "Tu connais l'hiver.",
          "Nous dessinons l'hiver.",
          "La classe regarde l'hiver.",
          "Je montre l'hiver au professeur.",
          "Il y a un hiver dans l'image.",
          "Cette leçon parle de l'hiver.",
        ],
        a2: [
          "Hier, j'ai étudié l'hiver en classe.",
          "Demain, je vais revoir l'hiver.",
          "Quand j'étais débutant, je confondais souvent hiver.",
          "Ce matin, le professeur a expliqué l'hiver.",
          "Nous avons utilisé l'hiver dans un exercice.",
          "Ils vont apprendre hiver cette semaine.",
          "J'ai choisi l'hiver parce que c'était utile.",
          "Elle a écrit hiver dans son cahier.",
          "Avant le test, nous avons répété hiver.",
          "Le groupe a parlé de l'hiver pendant le cours.",
          "Je vais pratiquer hiver après le repas.",
          "Nous avons corrigé une phrase avec hiver.",
          "Hier soir, mon frère a révisé l'hiver.",
          "Pendant les vacances, je revoyais souvent hiver.",
          "Elle a oublié hiver pendant l'exercice.",
          "Il va utiliser l'hiver dans sa phrase.",
          "Nous avons trouvé hiver dans le texte.",
          "Ce week-end, je vais mémoriser hiver.",
          "L'élève a ajouté hiver dans sa réponse.",
          "J'ai compris hiver pour la première fois.",
          "Ma sœur a choisi l'hiver pour son exemple.",
          "Ils ont répété hiver à voix haute.",
          "Nous allons revoir l'hiver avec le professeur.",
          "Elle a noté hiver pour ne pas l'oublier.",
          "La classe a demandé l'hiver au tableau.",
          "Après la leçon, j'ai utilisé le mot hiver dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'hiver.",
          "Quand je lis le texte, je cherche le sens de hiver.",
          "Ce matin, nous avons associé l'hiver à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec hiver.",
          "Le professeur a demandé un exemple avec l'hiver.",
          "J'ai choisi l'hiver parce que ce mot était dans la liste.",
          "Nous allons réviser l'hiver avant l'évaluation.",
          "Mon camarade a expliqué l'hiver avec ses mots.",
          "J'ai ajouté hiver dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que hiver semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'hiver revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises hiver, tu comprendras mieux les textes du calendrier.",
          "Même si je connais hiver, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'hiver comme exemple.",
          "La leçon que nous travaillons utilise hiver dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'hiver, les élèves prenaient des notes.",
          "Puisque hiver était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé hiver, tu pourras passer à la suite.",
          "Je pense que l'hiver aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, hiver peut être important.",
          "Le mot dont je parle est hiver, que la classe doit retenir.",
          "Tant que tu pratiqueras hiver, tu feras des progrès.",
          "Bien que hiver demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient hiver, je lirai la consigne avec soin.",
          "Bien que le mot hiver paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'hiver apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'hiver, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà hiver, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'hiver.",
          "Lorsque j'aurai mémorisé hiver, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'hiver.",
          "Puisque hiver est utile, je le révise régulièrement.",
        ],
      } },
    { word: "saison", image: "saison.webp",        article: "la",  gender: "f", definition: "La saison est une des quatre périodes de l'année. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais la saison.",
          "Je note la saison.",
          "La saison est importante.",
          "La saison est utile.",
          "Je regarde la saison.",
          "Je lis la saison.",
          "Tu écris la saison.",
          "Il apprend la saison.",
          "Elle répète saison.",
          "Nous parlons de la saison.",
          "Vous utilisez la saison.",
          "Ils choisissent la saison.",
          "Elles écrivent saison.",
          "La saison est dans le calendrier.",
          "La saison est au tableau.",
          "Je cherche la saison.",
          "Je comprends saison.",
          "Il montre la saison.",
          "Elle demande la saison.",
          "Le professeur explique la saison.",
          "La classe étudie la saison.",
          "Cette période est simple.",
          "Je répète saison.",
          "Nous écrivons saison.",
          "Tu apprends saison.",
          "Aujourd'hui, je vois la saison.",
          "Dans mon cahier, j'écris saison.",
          "Le mot saison est nouveau pour moi.",
          "Je répète saison à voix haute.",
          "Tu connais la saison.",
          "Nous dessinons la saison.",
          "La classe regarde la saison.",
          "Je montre la saison au professeur.",
          "Il y a une saison dans l'image.",
          "Cette leçon parle de la saison.",
        ],
        a2: [
          "Hier, j'ai étudié la saison en classe.",
          "Demain, je vais revoir la saison.",
          "Quand j'étais débutant, je confondais souvent saison.",
          "Ce matin, le professeur a expliqué la saison.",
          "Nous avons utilisé la saison dans un exercice.",
          "Ils vont apprendre saison cette semaine.",
          "J'ai choisi la saison parce que c'était utile.",
          "Elle a écrit saison dans son cahier.",
          "Avant le test, nous avons répété saison.",
          "Le groupe a parlé de la saison pendant le cours.",
          "Je vais pratiquer saison après le repas.",
          "Nous avons corrigé une phrase avec saison.",
          "Hier soir, mon frère a révisé la saison.",
          "Pendant les vacances, je revoyais souvent saison.",
          "Elle a oublié saison pendant l'exercice.",
          "Il va utiliser la saison dans sa phrase.",
          "Nous avons trouvé saison dans le texte.",
          "Ce week-end, je vais mémoriser saison.",
          "L'élève a ajouté saison dans sa réponse.",
          "J'ai compris saison pour la première fois.",
          "Ma sœur a choisi la saison pour son exemple.",
          "Ils ont répété saison à voix haute.",
          "Nous allons revoir la saison avec le professeur.",
          "Elle a noté saison pour ne pas l'oublier.",
          "La classe a demandé la saison au tableau.",
          "Après la leçon, j'ai utilisé le mot saison dans une phrase.",
          "Demain, je vais apprendre à mieux employer la saison.",
          "Quand je lis le texte, je cherche le sens de saison.",
          "Ce matin, nous avons associé la saison à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec saison.",
          "Le professeur a demandé un exemple avec la saison.",
          "J'ai choisi la saison parce que ce mot était dans la liste.",
          "Nous allons réviser la saison avant l'évaluation.",
          "Mon camarade a expliqué la saison avec ses mots.",
          "J'ai ajouté saison dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que saison semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme la saison revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises saison, tu comprendras mieux les textes du calendrier.",
          "Même si je connais saison, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi la saison comme exemple.",
          "La leçon que nous travaillons utilise saison dans plusieurs phrases.",
          "Pendant que le professeur expliquait la saison, les élèves prenaient des notes.",
          "Puisque saison était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé saison, tu pourras passer à la suite.",
          "Je pense que la saison aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, saison peut être important.",
          "Le mot dont je parle est saison, que la classe doit retenir.",
          "Tant que tu pratiqueras saison, tu feras des progrès.",
          "Bien que saison demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient saison, je lirai la consigne avec soin.",
          "Bien que le mot saison paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la saison apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la saison, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà saison, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la saison.",
          "Lorsque j'aurai mémorisé saison, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la saison.",
          "Puisque saison est utile, je le révise régulièrement.",
        ],
      } },
    { word: "climat", image: "climat.webp",        article: "le",  gender: "m", definition: "Le climat est conditions météo habituelles d'une région. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le climat.",
          "Je note le climat.",
          "Le climat est important.",
          "Le climat est utile.",
          "Je regarde le climat.",
          "Je lis le climat.",
          "Tu écris le climat.",
          "Il apprend le climat.",
          "Elle répète climat.",
          "Nous parlons du climat.",
          "Vous utilisez le climat.",
          "Ils choisissent le climat.",
          "Elles écrivent climat.",
          "Le climat est dans le calendrier.",
          "Le climat est au tableau.",
          "Je cherche le climat.",
          "Je comprends climat.",
          "Il montre le climat.",
          "Elle demande le climat.",
          "Le professeur explique le climat.",
          "La classe étudie le climat.",
          "Cette période est simple.",
          "Je répète climat.",
          "Nous écrivons climat.",
          "Tu apprends climat.",
          "Aujourd'hui, je vois le climat.",
          "Dans mon cahier, j'écris climat.",
          "Le mot climat est nouveau pour moi.",
          "Je répète climat à voix haute.",
          "Tu connais le climat.",
          "Nous dessinons le climat.",
          "La classe regarde le climat.",
          "Je montre le climat au professeur.",
          "Il y a un climat dans l'image.",
          "Cette leçon parle du climat.",
        ],
        a2: [
          "Hier, j'ai étudié le climat en classe.",
          "Demain, je vais revoir le climat.",
          "Quand j'étais débutant, je confondais souvent climat.",
          "Ce matin, le professeur a expliqué le climat.",
          "Nous avons utilisé le climat dans un exercice.",
          "Ils vont apprendre climat cette semaine.",
          "J'ai choisi le climat parce que c'était utile.",
          "Elle a écrit climat dans son cahier.",
          "Avant le test, nous avons répété climat.",
          "Le groupe a parlé du climat pendant le cours.",
          "Je vais pratiquer climat après le repas.",
          "Nous avons corrigé une phrase avec climat.",
          "Hier soir, mon frère a révisé le climat.",
          "Pendant les vacances, je revoyais souvent climat.",
          "Elle a oublié climat pendant l'exercice.",
          "Il va utiliser le climat dans sa phrase.",
          "Nous avons trouvé climat dans le texte.",
          "Ce week-end, je vais mémoriser climat.",
          "L'élève a ajouté climat dans sa réponse.",
          "J'ai compris climat pour la première fois.",
          "Ma sœur a choisi le climat pour son exemple.",
          "Ils ont répété climat à voix haute.",
          "Nous allons revoir le climat avec le professeur.",
          "Elle a noté climat pour ne pas l'oublier.",
          "La classe a demandé le climat au tableau.",
          "Après la leçon, j'ai utilisé le mot climat dans une phrase.",
          "Demain, je vais apprendre à mieux employer le climat.",
          "Quand je lis le texte, je cherche le sens de climat.",
          "Ce matin, nous avons associé le climat à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec climat.",
          "Le professeur a demandé un exemple avec le climat.",
          "J'ai choisi le climat parce que ce mot était dans la liste.",
          "Nous allons réviser le climat avant l'évaluation.",
          "Mon camarade a expliqué le climat avec ses mots.",
          "J'ai ajouté climat dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que climat semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le climat revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises climat, tu comprendras mieux les textes du calendrier.",
          "Même si je connais climat, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le climat comme exemple.",
          "La leçon que nous travaillons utilise climat dans plusieurs phrases.",
          "Pendant que le professeur expliquait le climat, les élèves prenaient des notes.",
          "Puisque climat était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé climat, tu pourras passer à la suite.",
          "Je pense que le climat aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, climat peut être important.",
          "Le mot dont je parle est climat, que la classe doit retenir.",
          "Tant que tu pratiqueras climat, tu feras des progrès.",
          "Bien que climat demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient climat, je lirai la consigne avec soin.",
          "Bien que le mot climat paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le climat apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le climat, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà climat, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le climat.",
          "Lorsque j'aurai mémorisé climat, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le climat.",
          "Puisque climat est utile, je le révise régulièrement.",
        ],
      } },
    { word: "météo", image: "meteo.webp",         article: "la",  gender: "f", definition: "La météo est prévision des conditions atmosphériques. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais la météo.",
          "Je note la météo.",
          "La météo est importante.",
          "La météo est utile.",
          "Je regarde la météo.",
          "Je lis la météo.",
          "Tu écris la météo.",
          "Il apprend la météo.",
          "Elle répète météo.",
          "Nous parlons de la météo.",
          "Vous utilisez la météo.",
          "Ils choisissent la météo.",
          "Elles écrivent météo.",
          "La météo est dans le calendrier.",
          "La météo est au tableau.",
          "Je cherche la météo.",
          "Je comprends météo.",
          "Il montre la météo.",
          "Elle demande la météo.",
          "Le professeur explique la météo.",
          "La classe étudie la météo.",
          "Cette période est simple.",
          "Je répète météo.",
          "Nous écrivons météo.",
          "Tu apprends météo.",
          "Aujourd'hui, je vois la météo.",
          "Dans mon cahier, j'écris météo.",
          "Le mot météo est nouveau pour moi.",
          "Je répète météo à voix haute.",
          "Tu connais la météo.",
          "Nous dessinons la météo.",
          "La classe regarde la météo.",
          "Je montre la météo au professeur.",
          "Il y a une météo dans l'image.",
          "Cette leçon parle de la météo.",
        ],
        a2: [
          "Hier, j'ai étudié la météo en classe.",
          "Demain, je vais revoir la météo.",
          "Quand j'étais débutant, je confondais souvent météo.",
          "Ce matin, le professeur a expliqué la météo.",
          "Nous avons utilisé la météo dans un exercice.",
          "Ils vont apprendre météo cette semaine.",
          "J'ai choisi la météo parce que c'était utile.",
          "Elle a écrit météo dans son cahier.",
          "Avant le test, nous avons répété météo.",
          "Le groupe a parlé de la météo pendant le cours.",
          "Je vais pratiquer météo après le repas.",
          "Nous avons corrigé une phrase avec météo.",
          "Hier soir, mon frère a révisé la météo.",
          "Pendant les vacances, je revoyais souvent météo.",
          "Elle a oublié météo pendant l'exercice.",
          "Il va utiliser la météo dans sa phrase.",
          "Nous avons trouvé météo dans le texte.",
          "Ce week-end, je vais mémoriser météo.",
          "L'élève a ajouté météo dans sa réponse.",
          "J'ai compris météo pour la première fois.",
          "Ma sœur a choisi la météo pour son exemple.",
          "Ils ont répété météo à voix haute.",
          "Nous allons revoir la météo avec le professeur.",
          "Elle a noté météo pour ne pas l'oublier.",
          "La classe a demandé la météo au tableau.",
          "Après la leçon, j'ai utilisé le mot météo dans une phrase.",
          "Demain, je vais apprendre à mieux employer la météo.",
          "Quand je lis le texte, je cherche le sens de météo.",
          "Ce matin, nous avons associé la météo à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec météo.",
          "Le professeur a demandé un exemple avec la météo.",
          "J'ai choisi la météo parce que ce mot était dans la liste.",
          "Nous allons réviser la météo avant l'évaluation.",
          "Mon camarade a expliqué la météo avec ses mots.",
          "J'ai ajouté météo dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que météo semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme la météo revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises météo, tu comprendras mieux les textes du calendrier.",
          "Même si je connais météo, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi la météo comme exemple.",
          "La leçon que nous travaillons utilise météo dans plusieurs phrases.",
          "Pendant que le professeur expliquait la météo, les élèves prenaient des notes.",
          "Puisque météo était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé météo, tu pourras passer à la suite.",
          "Je pense que la météo aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, météo peut être important.",
          "Le mot dont je parle est météo, que la classe doit retenir.",
          "Tant que tu pratiqueras météo, tu feras des progrès.",
          "Bien que météo demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient météo, je lirai la consigne avec soin.",
          "Bien que le mot météo paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la météo apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la météo, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà météo, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la météo.",
          "Lorsque j'aurai mémorisé météo, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la météo.",
          "Puisque météo est utile, je le révise régulièrement.",
        ],
      } },
    { word: "température", image: "temperature.webp",   article: "la",  gender: "f", definition: "La température est mesure du chaud ou du froid en degrés. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais la température.",
          "Je note la température.",
          "La température est importante.",
          "La température est utile.",
          "Je regarde la température.",
          "Je lis la température.",
          "Tu écris la température.",
          "Il apprend la température.",
          "Elle répète température.",
          "Nous parlons de la température.",
          "Vous utilisez la température.",
          "Ils choisissent la température.",
          "Elles écrivent température.",
          "La température est dans le calendrier.",
          "La température est au tableau.",
          "Je cherche la température.",
          "Je comprends température.",
          "Il montre la température.",
          "Elle demande la température.",
          "Le professeur explique la température.",
          "La classe étudie la température.",
          "Cette période est simple.",
          "Je répète température.",
          "Nous écrivons température.",
          "Tu apprends température.",
          "Aujourd'hui, je vois la température.",
          "Dans mon cahier, j'écris température.",
          "Le mot température est nouveau pour moi.",
          "Je répète température à voix haute.",
          "Tu connais la température.",
          "Nous dessinons la température.",
          "La classe regarde la température.",
          "Je montre la température au professeur.",
          "Il y a une température dans l'image.",
          "Cette leçon parle de la température.",
        ],
        a2: [
          "Hier, j'ai étudié la température en classe.",
          "Demain, je vais revoir la température.",
          "Quand j'étais débutant, je confondais souvent température.",
          "Ce matin, le professeur a expliqué la température.",
          "Nous avons utilisé la température dans un exercice.",
          "Ils vont apprendre température cette semaine.",
          "J'ai choisi la température parce que c'était utile.",
          "Elle a écrit température dans son cahier.",
          "Avant le test, nous avons répété température.",
          "Le groupe a parlé de la température pendant le cours.",
          "Je vais pratiquer température après le repas.",
          "Nous avons corrigé une phrase avec température.",
          "Hier soir, mon frère a révisé la température.",
          "Pendant les vacances, je revoyais souvent température.",
          "Elle a oublié température pendant l'exercice.",
          "Il va utiliser la température dans sa phrase.",
          "Nous avons trouvé température dans le texte.",
          "Ce week-end, je vais mémoriser température.",
          "L'élève a ajouté température dans sa réponse.",
          "J'ai compris température pour la première fois.",
          "Ma sœur a choisi la température pour son exemple.",
          "Ils ont répété température à voix haute.",
          "Nous allons revoir la température avec le professeur.",
          "Elle a noté température pour ne pas l'oublier.",
          "La classe a demandé la température au tableau.",
          "Après la leçon, j'ai utilisé le mot température dans une phrase.",
          "Demain, je vais apprendre à mieux employer la température.",
          "Quand je lis le texte, je cherche le sens de température.",
          "Ce matin, nous avons associé la température à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec température.",
          "Le professeur a demandé un exemple avec la température.",
          "J'ai choisi la température parce que ce mot était dans la liste.",
          "Nous allons réviser la température avant l'évaluation.",
          "Mon camarade a expliqué la température avec ses mots.",
          "J'ai ajouté température dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que température semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme la température revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises température, tu comprendras mieux les textes du calendrier.",
          "Même si je connais température, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi la température comme exemple.",
          "La leçon que nous travaillons utilise température dans plusieurs phrases.",
          "Pendant que le professeur expliquait la température, les élèves prenaient des notes.",
          "Puisque température était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé température, tu pourras passer à la suite.",
          "Je pense que la température aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, température peut être important.",
          "Le mot dont je parle est température, que la classe doit retenir.",
          "Tant que tu pratiqueras température, tu feras des progrès.",
          "Bien que température demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient température, je lirai la consigne avec soin.",
          "Bien que le mot température paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la température apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la température, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà température, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la température.",
          "Lorsque j'aurai mémorisé température, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la température.",
          "Puisque température est utile, je le révise régulièrement.",
        ],
      } },
    { word: "se réchauffer", image: "se-rechauffer.webp",                              definition: "Le mot se réchauffer est devenir plus chaud, augmenter en température. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais se réchauffer.",
          "Je note se réchauffer.",
          "Se réchauffer est important.",
          "Se réchauffer est utile.",
          "Je regarde se réchauffer.",
          "Je lis se réchauffer.",
          "Tu écris se réchauffer.",
          "Il apprend se réchauffer.",
          "Elle répète se réchauffer.",
          "Nous parlons de se réchauffer.",
          "Vous utilisez se réchauffer.",
          "Ils choisissent se réchauffer.",
          "Elles écrivent se réchauffer.",
          "Se réchauffer est dans le calendrier.",
          "Se réchauffer est au tableau.",
          "Je cherche se réchauffer.",
          "Je comprends se réchauffer.",
          "Il montre se réchauffer.",
          "Elle demande se réchauffer.",
          "Le professeur explique se réchauffer.",
          "La classe étudie se réchauffer.",
          "Cette période est simple.",
          "Je répète se réchauffer.",
          "Nous écrivons se réchauffer.",
          "Tu apprends se réchauffer.",
          "Aujourd'hui, je vois se réchauffer.",
          "Dans mon cahier, j'écris se réchauffer.",
          "Le mot se réchauffer est nouveau pour moi.",
          "Je répète se réchauffer à voix haute.",
          "Tu connais se réchauffer.",
          "Nous dessinons se réchauffer.",
          "La classe regarde se réchauffer.",
          "Je montre se réchauffer au professeur.",
          "Il y a un se réchauffer dans l'image.",
          "Cette leçon parle de se réchauffer.",
        ],
        a2: [
          "Hier, j'ai étudié se réchauffer en classe.",
          "Demain, je vais revoir se réchauffer.",
          "Quand j'étais débutant, je confondais souvent se réchauffer.",
          "Ce matin, le professeur a expliqué se réchauffer.",
          "Nous avons utilisé se réchauffer dans un exercice.",
          "Ils vont apprendre se réchauffer cette semaine.",
          "J'ai choisi se réchauffer parce que c'était utile.",
          "Elle a écrit se réchauffer dans son cahier.",
          "Avant le test, nous avons répété se réchauffer.",
          "Le groupe a parlé de se réchauffer pendant le cours.",
          "Je vais pratiquer se réchauffer après le repas.",
          "Nous avons corrigé une phrase avec se réchauffer.",
          "Hier soir, mon frère a révisé se réchauffer.",
          "Pendant les vacances, je revoyais souvent se réchauffer.",
          "Elle a oublié se réchauffer pendant l'exercice.",
          "Il va utiliser se réchauffer dans sa phrase.",
          "Nous avons trouvé se réchauffer dans le texte.",
          "Ce week-end, je vais mémoriser se réchauffer.",
          "L'élève a ajouté se réchauffer dans sa réponse.",
          "J'ai compris se réchauffer pour la première fois.",
          "Ma sœur a choisi se réchauffer pour son exemple.",
          "Ils ont répété se réchauffer à voix haute.",
          "Nous allons revoir se réchauffer avec le professeur.",
          "Elle a noté se réchauffer pour ne pas l'oublier.",
          "La classe a demandé se réchauffer au tableau.",
          "Après la leçon, j'ai utilisé le mot se réchauffer dans une phrase.",
          "Demain, je vais apprendre à mieux employer se réchauffer.",
          "Quand je lis le texte, je cherche le sens de se réchauffer.",
          "Ce matin, nous avons associé se réchauffer à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec se réchauffer.",
          "Le professeur a demandé un exemple avec se réchauffer.",
          "J'ai choisi se réchauffer parce que ce mot était dans la liste.",
          "Nous allons réviser se réchauffer avant l'évaluation.",
          "Mon camarade a expliqué se réchauffer avec ses mots.",
          "J'ai ajouté se réchauffer dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que se réchauffer semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme se réchauffer revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises se réchauffer, tu comprendras mieux les textes du calendrier.",
          "Même si je connais se réchauffer, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi se réchauffer comme exemple.",
          "La leçon que nous travaillons utilise se réchauffer dans plusieurs phrases.",
          "Pendant que le professeur expliquait se réchauffer, les élèves prenaient des notes.",
          "Puisque se réchauffer était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé se réchauffer, tu pourras passer à la suite.",
          "Je pense que se réchauffer aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, se réchauffer peut être important.",
          "Le mot dont je parle est se réchauffer, que la classe doit retenir.",
          "Tant que tu pratiqueras se réchauffer, tu feras des progrès.",
          "Bien que se réchauffer demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient se réchauffer, je lirai la consigne avec soin.",
          "Bien que le mot se réchauffer paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme se réchauffer apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien se réchauffer, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà se réchauffer, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser se réchauffer.",
          "Lorsque j'aurai mémorisé se réchauffer, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec se réchauffer.",
          "Puisque se réchauffer est utile, je le révise régulièrement.",
        ],
      } },
    { word: "se rafraîchir", image: "se-rafraichir.webp",                              definition: "Le mot se rafraîchir est devenir plus frais, baisser en température. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais se rafraîchir.",
          "Je note se rafraîchir.",
          "Se rafraîchir est important.",
          "Se rafraîchir est utile.",
          "Je regarde se rafraîchir.",
          "Je lis se rafraîchir.",
          "Tu écris se rafraîchir.",
          "Il apprend se rafraîchir.",
          "Elle répète se rafraîchir.",
          "Nous parlons de se rafraîchir.",
          "Vous utilisez se rafraîchir.",
          "Ils choisissent se rafraîchir.",
          "Elles écrivent se rafraîchir.",
          "Se rafraîchir est dans le calendrier.",
          "Se rafraîchir est au tableau.",
          "Je cherche se rafraîchir.",
          "Je comprends se rafraîchir.",
          "Il montre se rafraîchir.",
          "Elle demande se rafraîchir.",
          "Le professeur explique se rafraîchir.",
          "La classe étudie se rafraîchir.",
          "Cette période est simple.",
          "Je répète se rafraîchir.",
          "Nous écrivons se rafraîchir.",
          "Tu apprends se rafraîchir.",
          "Aujourd'hui, je vois se rafraîchir.",
          "Dans mon cahier, j'écris se rafraîchir.",
          "Le mot se rafraîchir est nouveau pour moi.",
          "Je répète se rafraîchir à voix haute.",
          "Tu connais se rafraîchir.",
          "Nous dessinons se rafraîchir.",
          "La classe regarde se rafraîchir.",
          "Je montre se rafraîchir au professeur.",
          "Il y a un se rafraîchir dans l'image.",
          "Cette leçon parle de se rafraîchir.",
        ],
        a2: [
          "Hier, j'ai étudié se rafraîchir en classe.",
          "Demain, je vais revoir se rafraîchir.",
          "Quand j'étais débutant, je confondais souvent se rafraîchir.",
          "Ce matin, le professeur a expliqué se rafraîchir.",
          "Nous avons utilisé se rafraîchir dans un exercice.",
          "Ils vont apprendre se rafraîchir cette semaine.",
          "J'ai choisi se rafraîchir parce que c'était utile.",
          "Elle a écrit se rafraîchir dans son cahier.",
          "Avant le test, nous avons répété se rafraîchir.",
          "Le groupe a parlé de se rafraîchir pendant le cours.",
          "Je vais pratiquer se rafraîchir après le repas.",
          "Nous avons corrigé une phrase avec se rafraîchir.",
          "Hier soir, mon frère a révisé se rafraîchir.",
          "Pendant les vacances, je revoyais souvent se rafraîchir.",
          "Elle a oublié se rafraîchir pendant l'exercice.",
          "Il va utiliser se rafraîchir dans sa phrase.",
          "Nous avons trouvé se rafraîchir dans le texte.",
          "Ce week-end, je vais mémoriser se rafraîchir.",
          "L'élève a ajouté se rafraîchir dans sa réponse.",
          "J'ai compris se rafraîchir pour la première fois.",
          "Ma sœur a choisi se rafraîchir pour son exemple.",
          "Ils ont répété se rafraîchir à voix haute.",
          "Nous allons revoir se rafraîchir avec le professeur.",
          "Elle a noté se rafraîchir pour ne pas l'oublier.",
          "La classe a demandé se rafraîchir au tableau.",
          "Après la leçon, j'ai utilisé le mot se rafraîchir dans une phrase.",
          "Demain, je vais apprendre à mieux employer se rafraîchir.",
          "Quand je lis le texte, je cherche le sens de se rafraîchir.",
          "Ce matin, nous avons associé se rafraîchir à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec se rafraîchir.",
          "Le professeur a demandé un exemple avec se rafraîchir.",
          "J'ai choisi se rafraîchir parce que ce mot était dans la liste.",
          "Nous allons réviser se rafraîchir avant l'évaluation.",
          "Mon camarade a expliqué se rafraîchir avec ses mots.",
          "J'ai ajouté se rafraîchir dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que se rafraîchir semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme se rafraîchir revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises se rafraîchir, tu comprendras mieux les textes du calendrier.",
          "Même si je connais se rafraîchir, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi se rafraîchir comme exemple.",
          "La leçon que nous travaillons utilise se rafraîchir dans plusieurs phrases.",
          "Pendant que le professeur expliquait se rafraîchir, les élèves prenaient des notes.",
          "Puisque se rafraîchir était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé se rafraîchir, tu pourras passer à la suite.",
          "Je pense que se rafraîchir aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, se rafraîchir peut être important.",
          "Le mot dont je parle est se rafraîchir, que la classe doit retenir.",
          "Tant que tu pratiqueras se rafraîchir, tu feras des progrès.",
          "Bien que se rafraîchir demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient se rafraîchir, je lirai la consigne avec soin.",
          "Bien que le mot se rafraîchir paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme se rafraîchir apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien se rafraîchir, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà se rafraîchir, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser se rafraîchir.",
          "Lorsque j'aurai mémorisé se rafraîchir, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec se rafraîchir.",
          "Puisque se rafraîchir est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Les fleurs poussent au ___.",                    answer: "printemps" },
    { sentence: "Il fait très chaud en ___, je vais à la plage.", answer: "été" },
    { sentence: "En ___, les feuilles tombent des arbres.",        answer: "automne" },
    { sentence: "On écoute la ___ pour savoir s'il va pleuvoir.", answer: "météo" },
  ],
};
