import type { VocabTheme } from "../../vocabulary-data";

export const V3_SPORT_THEME: VocabTheme = {
  slug: "v3-sport",
  code: "V3.1",
  title: "Le sport",
  section: "V3",
  words: [
    { word: "football", image: "football.webp", article: "le", gender: "m", definition: "Le football est sport collectif joué avec un ballon rond. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du football.",
          "J'aime le football.",
          "Le football est un sport.",
          "Le football est une activité.",
          "Je pratique le football.",
          "Je regarde le football.",
          "Tu fais du football.",
          "Il joue au football.",
          "Elle pratique le football.",
          "Nous faisons du football.",
          "Vous aimez le football.",
          "Ils jouent au football.",
          "Elles regardent le football.",
          "Le football est dans le gymnase.",
          "Le football est sur l'image.",
          "Je choisis le football.",
          "Je commence le football.",
          "Il apprend le football.",
          "Elle aime le football.",
          "Le professeur explique le football.",
          "La classe pratique le football.",
          "Ce sport est simple.",
          "Je parle du football.",
          "Nous essayons le football.",
          "Tu connais le football.",
          "Aujourd'hui, je vois le football.",
          "Dans mon cahier, j'écris football.",
          "Le mot football est nouveau pour moi.",
          "Je répète football à voix haute.",
          "Nous dessinons le football.",
          "La classe regarde le football.",
          "Je montre le football au professeur.",
          "Il y a le football dans l'image.",
          "Cette leçon parle du football.",
        ],
        a2: [
          "Hier, j'ai fait du football avec mes amis.",
          "Demain, je vais pratiquer le football.",
          "Quand j'étais petit, je jouais souvent au football.",
          "Ce matin, le professeur a présenté le football.",
          "Nous avons essayé le football pendant le cours.",
          "Ils vont jouer au football cette semaine.",
          "J'ai choisi le football parce que cette activité me plaît.",
          "Elle a regardé le football à la télévision.",
          "Avant l'entraînement, nous avons parlé du football.",
          "Le groupe a découvert le football au centre sportif.",
          "Je vais pratiquer le football après l'école.",
          "Nous avons appris les règles du football.",
          "Hier soir, mon frère a regardé le football.",
          "Pendant les vacances, je faisais souvent du football.",
          "Elle a oublié le mot football pendant l'exercice.",
          "Il va utiliser le football dans sa phrase.",
          "Nous avons trouvé le football dans le texte.",
          "Ce week-end, je vais essayer le football.",
          "L'élève a ajouté le football dans sa réponse.",
          "J'ai compris le mot football pour la première fois.",
          "Ma sœur a choisi le football pour son exemple.",
          "Ils ont répété football à voix haute.",
          "Nous allons revoir le football avec le professeur.",
          "Elle a noté football pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le football.",
          "Après la leçon, j'ai utilisé le mot football dans une phrase.",
          "Demain, je vais apprendre à mieux employer le football.",
          "Quand je lis le texte, je cherche le sens de football.",
          "Ce matin, nous avons associé le football à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec football.",
          "Le professeur a demandé un exemple avec le football.",
          "J'ai choisi le football parce que ce mot était dans la liste.",
          "Nous allons réviser le football avant l'évaluation.",
          "Mon camarade a expliqué le football avec ses mots.",
          "J'ai ajouté football dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le football demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le football régulièrement, je progresse peu à peu.",
          "Si tu fais du football, tu dois respecter les règles de sécurité.",
          "Même si je connais le football, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le football.",
          "L'activité que nous découvrons aujourd'hui s'appelle football.",
          "Pendant que le professeur expliquait le football, les élèves préparaient le matériel.",
          "Puisque le football était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du football, tu joueras plus facilement.",
          "Je pense que le football aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le football demande de l'attention.",
          "Le sport dont je parle est le football, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le football, tu gagneras en confiance.",
          "Bien que le football soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le football, je penserai aux règles du jeu.",
          "Bien que le mot football paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le football apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le football, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà football, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le football.",
          "Lorsque j'aurai mémorisé football, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le football.",
          "Puisque football est utile, je le révise régulièrement.",
        ],
      } },
    { word: "basket-ball", image: "basketball.webp", article: "le", gender: "m", definition: "Le basket-ball est sport collectif avec un panier. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du basket-ball.",
          "J'aime le basket-ball.",
          "Le basket-ball est un sport.",
          "Le basket-ball est une activité.",
          "Je pratique le basket-ball.",
          "Je regarde le basket-ball.",
          "Tu fais du basket-ball.",
          "Il joue au basket-ball.",
          "Elle pratique le basket-ball.",
          "Nous faisons du basket-ball.",
          "Vous aimez le basket-ball.",
          "Ils jouent au basket-ball.",
          "Elles regardent le basket-ball.",
          "Le basket-ball est dans le gymnase.",
          "Le basket-ball est sur l'image.",
          "Je choisis le basket-ball.",
          "Je commence le basket-ball.",
          "Il apprend le basket-ball.",
          "Elle aime le basket-ball.",
          "Le professeur explique le basket-ball.",
          "La classe pratique le basket-ball.",
          "Ce sport est simple.",
          "Je parle du basket-ball.",
          "Nous essayons le basket-ball.",
          "Tu connais le basket-ball.",
          "Aujourd'hui, je vois le basket-ball.",
          "Dans mon cahier, j'écris basket-ball.",
          "Le mot basket-ball est nouveau pour moi.",
          "Je répète basket-ball à voix haute.",
          "Nous dessinons le basket-ball.",
          "La classe regarde le basket-ball.",
          "Je montre le basket-ball au professeur.",
          "Il y a le basket-ball dans l'image.",
          "Cette leçon parle du basket-ball.",
        ],
        a2: [
          "Hier, j'ai fait du basket-ball avec mes amis.",
          "Demain, je vais pratiquer le basket-ball.",
          "Quand j'étais petit, je jouais souvent au basket-ball.",
          "Ce matin, le professeur a présenté le basket-ball.",
          "Nous avons essayé le basket-ball pendant le cours.",
          "Ils vont jouer au basket-ball cette semaine.",
          "J'ai choisi le basket-ball parce que cette activité me plaît.",
          "Elle a regardé le basket-ball à la télévision.",
          "Avant l'entraînement, nous avons parlé du basket-ball.",
          "Le groupe a découvert le basket-ball au centre sportif.",
          "Je vais pratiquer le basket-ball après l'école.",
          "Nous avons appris les règles du basket-ball.",
          "Hier soir, mon frère a regardé le basket-ball.",
          "Pendant les vacances, je faisais souvent du basket-ball.",
          "Elle a oublié le mot basket-ball pendant l'exercice.",
          "Il va utiliser le basket-ball dans sa phrase.",
          "Nous avons trouvé le basket-ball dans le texte.",
          "Ce week-end, je vais essayer le basket-ball.",
          "L'élève a ajouté le basket-ball dans sa réponse.",
          "J'ai compris le mot basket-ball pour la première fois.",
          "Ma sœur a choisi le basket-ball pour son exemple.",
          "Ils ont répété basket-ball à voix haute.",
          "Nous allons revoir le basket-ball avec le professeur.",
          "Elle a noté basket-ball pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le basket-ball.",
          "Après la leçon, j'ai utilisé le mot basket-ball dans une phrase.",
          "Demain, je vais apprendre à mieux employer le basket-ball.",
          "Quand je lis le texte, je cherche le sens de basket-ball.",
          "Ce matin, nous avons associé le basket-ball à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec basket-ball.",
          "Le professeur a demandé un exemple avec le basket-ball.",
          "J'ai choisi le basket-ball parce que ce mot était dans la liste.",
          "Nous allons réviser le basket-ball avant l'évaluation.",
          "Mon camarade a expliqué le basket-ball avec ses mots.",
          "J'ai ajouté basket-ball dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le basket-ball demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le basket-ball régulièrement, je progresse peu à peu.",
          "Si tu fais du basket-ball, tu dois respecter les règles de sécurité.",
          "Même si je connais le basket-ball, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le basket-ball.",
          "L'activité que nous découvrons aujourd'hui s'appelle basket-ball.",
          "Pendant que le professeur expliquait le basket-ball, les élèves préparaient le matériel.",
          "Puisque le basket-ball était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du basket-ball, tu joueras plus facilement.",
          "Je pense que le basket-ball aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le basket-ball demande de l'attention.",
          "Le sport dont je parle est le basket-ball, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le basket-ball, tu gagneras en confiance.",
          "Bien que le basket-ball soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le basket-ball, je penserai aux règles du jeu.",
          "Bien que le mot basket-ball paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le basket-ball apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le basket-ball, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà basket-ball, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le basket-ball.",
          "Lorsque j'aurai mémorisé basket-ball, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le basket-ball.",
          "Puisque basket-ball est utile, je le révise régulièrement.",
        ],
      } },
    { word: "tennis", image: "tennis.webp", article: "le", gender: "m", definition: "Le tennis est sport de raquette sur un court. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du tennis.",
          "J'aime le tennis.",
          "Le tennis est un sport.",
          "Le tennis est une activité.",
          "Je pratique le tennis.",
          "Je regarde le tennis.",
          "Tu fais du tennis.",
          "Il joue au tennis.",
          "Elle pratique le tennis.",
          "Nous faisons du tennis.",
          "Vous aimez le tennis.",
          "Ils jouent au tennis.",
          "Elles regardent le tennis.",
          "Le tennis est dans le gymnase.",
          "Le tennis est sur l'image.",
          "Je choisis le tennis.",
          "Je commence le tennis.",
          "Il apprend le tennis.",
          "Elle aime le tennis.",
          "Le professeur explique le tennis.",
          "La classe pratique le tennis.",
          "Ce sport est simple.",
          "Je parle du tennis.",
          "Nous essayons le tennis.",
          "Tu connais le tennis.",
          "Aujourd'hui, je vois le tennis.",
          "Dans mon cahier, j'écris tennis.",
          "Le mot tennis est nouveau pour moi.",
          "Je répète tennis à voix haute.",
          "Nous dessinons le tennis.",
          "La classe regarde le tennis.",
          "Je montre le tennis au professeur.",
          "Il y a le tennis dans l'image.",
          "Cette leçon parle du tennis.",
        ],
        a2: [
          "Hier, j'ai fait du tennis avec mes amis.",
          "Demain, je vais pratiquer le tennis.",
          "Quand j'étais petit, je jouais souvent au tennis.",
          "Ce matin, le professeur a présenté le tennis.",
          "Nous avons essayé le tennis pendant le cours.",
          "Ils vont jouer au tennis cette semaine.",
          "J'ai choisi le tennis parce que cette activité me plaît.",
          "Elle a regardé le tennis à la télévision.",
          "Avant l'entraînement, nous avons parlé du tennis.",
          "Le groupe a découvert le tennis au centre sportif.",
          "Je vais pratiquer le tennis après l'école.",
          "Nous avons appris les règles du tennis.",
          "Hier soir, mon frère a regardé le tennis.",
          "Pendant les vacances, je faisais souvent du tennis.",
          "Elle a oublié le mot tennis pendant l'exercice.",
          "Il va utiliser le tennis dans sa phrase.",
          "Nous avons trouvé le tennis dans le texte.",
          "Ce week-end, je vais essayer le tennis.",
          "L'élève a ajouté le tennis dans sa réponse.",
          "J'ai compris le mot tennis pour la première fois.",
          "Ma sœur a choisi le tennis pour son exemple.",
          "Ils ont répété tennis à voix haute.",
          "Nous allons revoir le tennis avec le professeur.",
          "Elle a noté tennis pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le tennis.",
          "Après la leçon, j'ai utilisé le mot tennis dans une phrase.",
          "Demain, je vais apprendre à mieux employer le tennis.",
          "Quand je lis le texte, je cherche le sens de tennis.",
          "Ce matin, nous avons associé le tennis à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec tennis.",
          "Le professeur a demandé un exemple avec le tennis.",
          "J'ai choisi le tennis parce que ce mot était dans la liste.",
          "Nous allons réviser le tennis avant l'évaluation.",
          "Mon camarade a expliqué le tennis avec ses mots.",
          "J'ai ajouté tennis dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le tennis demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le tennis régulièrement, je progresse peu à peu.",
          "Si tu fais du tennis, tu dois respecter les règles de sécurité.",
          "Même si je connais le tennis, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le tennis.",
          "L'activité que nous découvrons aujourd'hui s'appelle tennis.",
          "Pendant que le professeur expliquait le tennis, les élèves préparaient le matériel.",
          "Puisque le tennis était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du tennis, tu joueras plus facilement.",
          "Je pense que le tennis aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le tennis demande de l'attention.",
          "Le sport dont je parle est le tennis, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le tennis, tu gagneras en confiance.",
          "Bien que le tennis soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le tennis, je penserai aux règles du jeu.",
          "Bien que le mot tennis paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le tennis apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le tennis, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà tennis, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le tennis.",
          "Lorsque j'aurai mémorisé tennis, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le tennis.",
          "Puisque tennis est utile, je le révise régulièrement.",
        ],
      } },
    { word: "natation", image: "natation.webp", article: "la", gender: "f", definition: "La natation est sport de nage dans l'eau. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de la natation.",
          "J'aime la natation.",
          "La natation est un sport.",
          "La natation est une activité.",
          "Je pratique la natation.",
          "Je regarde la natation.",
          "Tu fais de la natation.",
          "Il joue à la natation.",
          "Elle pratique la natation.",
          "Nous faisons de la natation.",
          "Vous aimez la natation.",
          "Ils jouent à la natation.",
          "Elles regardent la natation.",
          "La natation est dans le gymnase.",
          "La natation est sur l'image.",
          "Je choisis la natation.",
          "Je commence la natation.",
          "Il apprend la natation.",
          "Elle aime la natation.",
          "Le professeur explique la natation.",
          "La classe pratique la natation.",
          "Ce sport est simple.",
          "Je parle de la natation.",
          "Nous essayons la natation.",
          "Tu connais la natation.",
          "Aujourd'hui, je vois la natation.",
          "Dans mon cahier, j'écris natation.",
          "Le mot natation est nouveau pour moi.",
          "Je répète natation à voix haute.",
          "Nous dessinons la natation.",
          "La classe regarde la natation.",
          "Je montre la natation au professeur.",
          "Il y a la natation dans l'image.",
          "Cette leçon parle de la natation.",
        ],
        a2: [
          "Hier, j'ai fait de la natation avec mes amis.",
          "Demain, je vais pratiquer la natation.",
          "Quand j'étais petit, je jouais souvent à la natation.",
          "Ce matin, le professeur a présenté la natation.",
          "Nous avons essayé la natation pendant le cours.",
          "Ils vont jouer à la natation cette semaine.",
          "J'ai choisi la natation parce que cette activité me plaît.",
          "Elle a regardé la natation à la télévision.",
          "Avant l'entraînement, nous avons parlé de la natation.",
          "Le groupe a découvert la natation au centre sportif.",
          "Je vais pratiquer la natation après l'école.",
          "Nous avons appris les règles de la natation.",
          "Hier soir, mon frère a regardé la natation.",
          "Pendant les vacances, je faisais souvent de la natation.",
          "Elle a oublié le mot natation pendant l'exercice.",
          "Il va utiliser la natation dans sa phrase.",
          "Nous avons trouvé la natation dans le texte.",
          "Ce week-end, je vais essayer la natation.",
          "L'élève a ajouté la natation dans sa réponse.",
          "J'ai compris le mot natation pour la première fois.",
          "Ma sœur a choisi la natation pour son exemple.",
          "Ils ont répété natation à voix haute.",
          "Nous allons revoir la natation avec le professeur.",
          "Elle a noté natation pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la natation.",
          "Après la leçon, j'ai utilisé le mot natation dans une phrase.",
          "Demain, je vais apprendre à mieux employer la natation.",
          "Quand je lis le texte, je cherche le sens de natation.",
          "Ce matin, nous avons associé la natation à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec natation.",
          "Le professeur a demandé un exemple avec la natation.",
          "J'ai choisi la natation parce que ce mot était dans la liste.",
          "Nous allons réviser la natation avant l'évaluation.",
          "Mon camarade a expliqué la natation avec ses mots.",
          "J'ai ajouté natation dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la natation demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique la natation régulièrement, je progresse peu à peu.",
          "Si tu fais de la natation, tu dois respecter les règles de sécurité.",
          "Même si je connais la natation, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi la natation.",
          "L'activité que nous découvrons aujourd'hui s'appelle natation.",
          "Pendant que le professeur expliquait la natation, les élèves préparaient le matériel.",
          "Puisque la natation était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de la natation, tu joueras plus facilement.",
          "Je pense que la natation aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, la natation demande de l'attention.",
          "Le sport dont je parle est la natation, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras la natation, tu gagneras en confiance.",
          "Bien que la natation soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient la natation, je penserai aux règles du jeu.",
          "Bien que le mot natation paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la natation apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la natation, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà natation, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la natation.",
          "Lorsque j'aurai mémorisé natation, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la natation.",
          "Puisque natation est utile, je le révise régulièrement.",
        ],
      } },
    { word: "vélo", image: "velo.webp", article: "le", gender: "m", definition: "Le vélo est sport et moyen de transport à deux roues. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du vélo.",
          "J'aime le vélo.",
          "Le vélo est un sport.",
          "Le vélo est une activité.",
          "Je pratique le vélo.",
          "Je regarde le vélo.",
          "Tu fais du vélo.",
          "Il joue au vélo.",
          "Elle pratique le vélo.",
          "Nous faisons du vélo.",
          "Vous aimez le vélo.",
          "Ils jouent au vélo.",
          "Elles regardent le vélo.",
          "Le vélo est dans le gymnase.",
          "Le vélo est sur l'image.",
          "Je choisis le vélo.",
          "Je commence le vélo.",
          "Il apprend le vélo.",
          "Elle aime le vélo.",
          "Le professeur explique le vélo.",
          "La classe pratique le vélo.",
          "Ce sport est simple.",
          "Je parle du vélo.",
          "Nous essayons le vélo.",
          "Tu connais le vélo.",
          "Aujourd'hui, je vois le vélo.",
          "Dans mon cahier, j'écris vélo.",
          "Le mot vélo est nouveau pour moi.",
          "Je répète vélo à voix haute.",
          "Nous dessinons le vélo.",
          "La classe regarde le vélo.",
          "Je montre le vélo au professeur.",
          "Il y a le vélo dans l'image.",
          "Cette leçon parle du vélo.",
        ],
        a2: [
          "Hier, j'ai fait du vélo avec mes amis.",
          "Demain, je vais pratiquer le vélo.",
          "Quand j'étais petit, je jouais souvent au vélo.",
          "Ce matin, le professeur a présenté le vélo.",
          "Nous avons essayé le vélo pendant le cours.",
          "Ils vont jouer au vélo cette semaine.",
          "J'ai choisi le vélo parce que cette activité me plaît.",
          "Elle a regardé le vélo à la télévision.",
          "Avant l'entraînement, nous avons parlé du vélo.",
          "Le groupe a découvert le vélo au centre sportif.",
          "Je vais pratiquer le vélo après l'école.",
          "Nous avons appris les règles du vélo.",
          "Hier soir, mon frère a regardé le vélo.",
          "Pendant les vacances, je faisais souvent du vélo.",
          "Elle a oublié le mot vélo pendant l'exercice.",
          "Il va utiliser le vélo dans sa phrase.",
          "Nous avons trouvé le vélo dans le texte.",
          "Ce week-end, je vais essayer le vélo.",
          "L'élève a ajouté le vélo dans sa réponse.",
          "J'ai compris le mot vélo pour la première fois.",
          "Ma sœur a choisi le vélo pour son exemple.",
          "Ils ont répété vélo à voix haute.",
          "Nous allons revoir le vélo avec le professeur.",
          "Elle a noté vélo pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le vélo.",
          "Après la leçon, j'ai utilisé le mot vélo dans une phrase.",
          "Demain, je vais apprendre à mieux employer le vélo.",
          "Quand je lis le texte, je cherche le sens de vélo.",
          "Ce matin, nous avons associé le vélo à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec vélo.",
          "Le professeur a demandé un exemple avec le vélo.",
          "J'ai choisi le vélo parce que ce mot était dans la liste.",
          "Nous allons réviser le vélo avant l'évaluation.",
          "Mon camarade a expliqué le vélo avec ses mots.",
          "J'ai ajouté vélo dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le vélo demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le vélo régulièrement, je progresse peu à peu.",
          "Si tu fais du vélo, tu dois respecter les règles de sécurité.",
          "Même si je connais le vélo, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le vélo.",
          "L'activité que nous découvrons aujourd'hui s'appelle vélo.",
          "Pendant que le professeur expliquait le vélo, les élèves préparaient le matériel.",
          "Puisque le vélo était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du vélo, tu joueras plus facilement.",
          "Je pense que le vélo aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le vélo demande de l'attention.",
          "Le sport dont je parle est le vélo, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le vélo, tu gagneras en confiance.",
          "Bien que le vélo soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le vélo, je penserai aux règles du jeu.",
          "Bien que le mot vélo paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le vélo apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le vélo, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà vélo, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le vélo.",
          "Lorsque j'aurai mémorisé vélo, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le vélo.",
          "Puisque vélo est utile, je le révise régulièrement.",
        ],
      } },
    { word: "course", image: "courir.webp", article: "la", gender: "f", definition: "La course est compétition de vitesse à pied. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de la course.",
          "J'aime la course.",
          "La course est un sport.",
          "La course est une activité.",
          "Je pratique la course.",
          "Je regarde la course.",
          "Tu fais de la course.",
          "Il joue à la course.",
          "Elle pratique la course.",
          "Nous faisons de la course.",
          "Vous aimez la course.",
          "Ils jouent à la course.",
          "Elles regardent la course.",
          "La course est dans le gymnase.",
          "La course est sur l'image.",
          "Je choisis la course.",
          "Je commence la course.",
          "Il apprend la course.",
          "Elle aime la course.",
          "Le professeur explique la course.",
          "La classe pratique la course.",
          "Ce sport est simple.",
          "Je parle de la course.",
          "Nous essayons la course.",
          "Tu connais la course.",
          "Aujourd'hui, je vois la course.",
          "Dans mon cahier, j'écris course.",
          "Le mot course est nouveau pour moi.",
          "Je répète course à voix haute.",
          "Nous dessinons la course.",
          "La classe regarde la course.",
          "Je montre la course au professeur.",
          "Il y a la course dans l'image.",
          "Cette leçon parle de la course.",
        ],
        a2: [
          "Hier, j'ai fait de la course avec mes amis.",
          "Demain, je vais pratiquer la course.",
          "Quand j'étais petit, je jouais souvent à la course.",
          "Ce matin, le professeur a présenté la course.",
          "Nous avons essayé la course pendant le cours.",
          "Ils vont jouer à la course cette semaine.",
          "J'ai choisi la course parce que cette activité me plaît.",
          "Elle a regardé la course à la télévision.",
          "Avant l'entraînement, nous avons parlé de la course.",
          "Le groupe a découvert la course au centre sportif.",
          "Je vais pratiquer la course après l'école.",
          "Nous avons appris les règles de la course.",
          "Hier soir, mon frère a regardé la course.",
          "Pendant les vacances, je faisais souvent de la course.",
          "Elle a oublié le mot course pendant l'exercice.",
          "Il va utiliser la course dans sa phrase.",
          "Nous avons trouvé la course dans le texte.",
          "Ce week-end, je vais essayer la course.",
          "L'élève a ajouté la course dans sa réponse.",
          "J'ai compris le mot course pour la première fois.",
          "Ma sœur a choisi la course pour son exemple.",
          "Ils ont répété course à voix haute.",
          "Nous allons revoir la course avec le professeur.",
          "Elle a noté course pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la course.",
          "Après la leçon, j'ai utilisé le mot course dans une phrase.",
          "Demain, je vais apprendre à mieux employer la course.",
          "Quand je lis le texte, je cherche le sens de course.",
          "Ce matin, nous avons associé la course à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec course.",
          "Le professeur a demandé un exemple avec la course.",
          "J'ai choisi la course parce que ce mot était dans la liste.",
          "Nous allons réviser la course avant l'évaluation.",
          "Mon camarade a expliqué la course avec ses mots.",
          "J'ai ajouté course dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la course demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique la course régulièrement, je progresse peu à peu.",
          "Si tu fais de la course, tu dois respecter les règles de sécurité.",
          "Même si je connais la course, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi la course.",
          "L'activité que nous découvrons aujourd'hui s'appelle course.",
          "Pendant que le professeur expliquait la course, les élèves préparaient le matériel.",
          "Puisque la course était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de la course, tu joueras plus facilement.",
          "Je pense que la course aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, la course demande de l'attention.",
          "Le sport dont je parle est la course, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras la course, tu gagneras en confiance.",
          "Bien que la course soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient la course, je penserai aux règles du jeu.",
          "Bien que le mot course paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la course apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la course, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà course, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la course.",
          "Lorsque j'aurai mémorisé course, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la course.",
          "Puisque course est utile, je le révise régulièrement.",
        ],
      } },
    { word: "danse", image: "danse.webp", article: "la", gender: "f", definition: "La danse est art de bouger le corps en rythme. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de la danse.",
          "J'aime la danse.",
          "La danse est un sport.",
          "La danse est une activité.",
          "Je pratique la danse.",
          "Je regarde la danse.",
          "Tu fais de la danse.",
          "Il joue à la danse.",
          "Elle pratique la danse.",
          "Nous faisons de la danse.",
          "Vous aimez la danse.",
          "Ils jouent à la danse.",
          "Elles regardent la danse.",
          "La danse est dans le gymnase.",
          "La danse est sur l'image.",
          "Je choisis la danse.",
          "Je commence la danse.",
          "Il apprend la danse.",
          "Elle aime la danse.",
          "Le professeur explique la danse.",
          "La classe pratique la danse.",
          "Ce sport est simple.",
          "Je parle de la danse.",
          "Nous essayons la danse.",
          "Tu connais la danse.",
          "Aujourd'hui, je vois la danse.",
          "Dans mon cahier, j'écris danse.",
          "Le mot danse est nouveau pour moi.",
          "Je répète danse à voix haute.",
          "Nous dessinons la danse.",
          "La classe regarde la danse.",
          "Je montre la danse au professeur.",
          "Il y a la danse dans l'image.",
          "Cette leçon parle de la danse.",
        ],
        a2: [
          "Hier, j'ai fait de la danse avec mes amis.",
          "Demain, je vais pratiquer la danse.",
          "Quand j'étais petit, je jouais souvent à la danse.",
          "Ce matin, le professeur a présenté la danse.",
          "Nous avons essayé la danse pendant le cours.",
          "Ils vont jouer à la danse cette semaine.",
          "J'ai choisi la danse parce que cette activité me plaît.",
          "Elle a regardé la danse à la télévision.",
          "Avant l'entraînement, nous avons parlé de la danse.",
          "Le groupe a découvert la danse au centre sportif.",
          "Je vais pratiquer la danse après l'école.",
          "Nous avons appris les règles de la danse.",
          "Hier soir, mon frère a regardé la danse.",
          "Pendant les vacances, je faisais souvent de la danse.",
          "Elle a oublié le mot danse pendant l'exercice.",
          "Il va utiliser la danse dans sa phrase.",
          "Nous avons trouvé la danse dans le texte.",
          "Ce week-end, je vais essayer la danse.",
          "L'élève a ajouté la danse dans sa réponse.",
          "J'ai compris le mot danse pour la première fois.",
          "Ma sœur a choisi la danse pour son exemple.",
          "Ils ont répété danse à voix haute.",
          "Nous allons revoir la danse avec le professeur.",
          "Elle a noté danse pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la danse.",
          "Après la leçon, j'ai utilisé le mot danse dans une phrase.",
          "Demain, je vais apprendre à mieux employer la danse.",
          "Quand je lis le texte, je cherche le sens de danse.",
          "Ce matin, nous avons associé la danse à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec danse.",
          "Le professeur a demandé un exemple avec la danse.",
          "J'ai choisi la danse parce que ce mot était dans la liste.",
          "Nous allons réviser la danse avant l'évaluation.",
          "Mon camarade a expliqué la danse avec ses mots.",
          "J'ai ajouté danse dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la danse demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique la danse régulièrement, je progresse peu à peu.",
          "Si tu fais de la danse, tu dois respecter les règles de sécurité.",
          "Même si je connais la danse, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi la danse.",
          "L'activité que nous découvrons aujourd'hui s'appelle danse.",
          "Pendant que le professeur expliquait la danse, les élèves préparaient le matériel.",
          "Puisque la danse était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de la danse, tu joueras plus facilement.",
          "Je pense que la danse aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, la danse demande de l'attention.",
          "Le sport dont je parle est la danse, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras la danse, tu gagneras en confiance.",
          "Bien que la danse soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient la danse, je penserai aux règles du jeu.",
          "Bien que le mot danse paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la danse apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la danse, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà danse, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la danse.",
          "Lorsque j'aurai mémorisé danse, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la danse.",
          "Puisque danse est utile, je le révise régulièrement.",
        ],
      } },
    { word: "yoga", image: "yoga.webp", article: "le", gender: "m", definition: "Le yoga est discipline de relaxation et de stretching. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du yoga.",
          "J'aime le yoga.",
          "Le yoga est un sport.",
          "Le yoga est une activité.",
          "Je pratique le yoga.",
          "Je regarde le yoga.",
          "Tu fais du yoga.",
          "Il joue au yoga.",
          "Elle pratique le yoga.",
          "Nous faisons du yoga.",
          "Vous aimez le yoga.",
          "Ils jouent au yoga.",
          "Elles regardent le yoga.",
          "Le yoga est dans le gymnase.",
          "Le yoga est sur l'image.",
          "Je choisis le yoga.",
          "Je commence le yoga.",
          "Il apprend le yoga.",
          "Elle aime le yoga.",
          "Le professeur explique le yoga.",
          "La classe pratique le yoga.",
          "Ce sport est simple.",
          "Je parle du yoga.",
          "Nous essayons le yoga.",
          "Tu connais le yoga.",
          "Aujourd'hui, je vois le yoga.",
          "Dans mon cahier, j'écris yoga.",
          "Le mot yoga est nouveau pour moi.",
          "Je répète yoga à voix haute.",
          "Nous dessinons le yoga.",
          "La classe regarde le yoga.",
          "Je montre le yoga au professeur.",
          "Il y a le yoga dans l'image.",
          "Cette leçon parle du yoga.",
        ],
        a2: [
          "Hier, j'ai fait du yoga avec mes amis.",
          "Demain, je vais pratiquer le yoga.",
          "Quand j'étais petit, je jouais souvent au yoga.",
          "Ce matin, le professeur a présenté le yoga.",
          "Nous avons essayé le yoga pendant le cours.",
          "Ils vont jouer au yoga cette semaine.",
          "J'ai choisi le yoga parce que cette activité me plaît.",
          "Elle a regardé le yoga à la télévision.",
          "Avant l'entraînement, nous avons parlé du yoga.",
          "Le groupe a découvert le yoga au centre sportif.",
          "Je vais pratiquer le yoga après l'école.",
          "Nous avons appris les règles du yoga.",
          "Hier soir, mon frère a regardé le yoga.",
          "Pendant les vacances, je faisais souvent du yoga.",
          "Elle a oublié le mot yoga pendant l'exercice.",
          "Il va utiliser le yoga dans sa phrase.",
          "Nous avons trouvé le yoga dans le texte.",
          "Ce week-end, je vais essayer le yoga.",
          "L'élève a ajouté le yoga dans sa réponse.",
          "J'ai compris le mot yoga pour la première fois.",
          "Ma sœur a choisi le yoga pour son exemple.",
          "Ils ont répété yoga à voix haute.",
          "Nous allons revoir le yoga avec le professeur.",
          "Elle a noté yoga pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le yoga.",
          "Après la leçon, j'ai utilisé le mot yoga dans une phrase.",
          "Demain, je vais apprendre à mieux employer le yoga.",
          "Quand je lis le texte, je cherche le sens de yoga.",
          "Ce matin, nous avons associé le yoga à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec yoga.",
          "Le professeur a demandé un exemple avec le yoga.",
          "J'ai choisi le yoga parce que ce mot était dans la liste.",
          "Nous allons réviser le yoga avant l'évaluation.",
          "Mon camarade a expliqué le yoga avec ses mots.",
          "J'ai ajouté yoga dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le yoga demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le yoga régulièrement, je progresse peu à peu.",
          "Si tu fais du yoga, tu dois respecter les règles de sécurité.",
          "Même si je connais le yoga, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le yoga.",
          "L'activité que nous découvrons aujourd'hui s'appelle yoga.",
          "Pendant que le professeur expliquait le yoga, les élèves préparaient le matériel.",
          "Puisque le yoga était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du yoga, tu joueras plus facilement.",
          "Je pense que le yoga aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le yoga demande de l'attention.",
          "Le sport dont je parle est le yoga, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le yoga, tu gagneras en confiance.",
          "Bien que le yoga soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le yoga, je penserai aux règles du jeu.",
          "Bien que le mot yoga paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le yoga apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le yoga, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà yoga, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le yoga.",
          "Lorsque j'aurai mémorisé yoga, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le yoga.",
          "Puisque yoga est utile, je le révise régulièrement.",
        ],
      } },
    { word: "randonnée", image: "marcher.webp", article: "la", gender: "f", definition: "La randonnée est longue marche en pleine nature. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de la randonnée.",
          "J'aime la randonnée.",
          "La randonnée est un sport.",
          "La randonnée est une activité.",
          "Je pratique la randonnée.",
          "Je regarde la randonnée.",
          "Tu fais de la randonnée.",
          "Il joue à la randonnée.",
          "Elle pratique la randonnée.",
          "Nous faisons de la randonnée.",
          "Vous aimez la randonnée.",
          "Ils jouent à la randonnée.",
          "Elles regardent la randonnée.",
          "La randonnée est dans le gymnase.",
          "La randonnée est sur l'image.",
          "Je choisis la randonnée.",
          "Je commence la randonnée.",
          "Il apprend la randonnée.",
          "Elle aime la randonnée.",
          "Le professeur explique la randonnée.",
          "La classe pratique la randonnée.",
          "Ce sport est simple.",
          "Je parle de la randonnée.",
          "Nous essayons la randonnée.",
          "Tu connais la randonnée.",
          "Aujourd'hui, je vois la randonnée.",
          "Dans mon cahier, j'écris randonnée.",
          "Le mot randonnée est nouveau pour moi.",
          "Je répète randonnée à voix haute.",
          "Nous dessinons la randonnée.",
          "La classe regarde la randonnée.",
          "Je montre la randonnée au professeur.",
          "Il y a la randonnée dans l'image.",
          "Cette leçon parle de la randonnée.",
        ],
        a2: [
          "Hier, j'ai fait de la randonnée avec mes amis.",
          "Demain, je vais pratiquer la randonnée.",
          "Quand j'étais petit, je jouais souvent à la randonnée.",
          "Ce matin, le professeur a présenté la randonnée.",
          "Nous avons essayé la randonnée pendant le cours.",
          "Ils vont jouer à la randonnée cette semaine.",
          "J'ai choisi la randonnée parce que cette activité me plaît.",
          "Elle a regardé la randonnée à la télévision.",
          "Avant l'entraînement, nous avons parlé de la randonnée.",
          "Le groupe a découvert la randonnée au centre sportif.",
          "Je vais pratiquer la randonnée après l'école.",
          "Nous avons appris les règles de la randonnée.",
          "Hier soir, mon frère a regardé la randonnée.",
          "Pendant les vacances, je faisais souvent de la randonnée.",
          "Elle a oublié le mot randonnée pendant l'exercice.",
          "Il va utiliser la randonnée dans sa phrase.",
          "Nous avons trouvé la randonnée dans le texte.",
          "Ce week-end, je vais essayer la randonnée.",
          "L'élève a ajouté la randonnée dans sa réponse.",
          "J'ai compris le mot randonnée pour la première fois.",
          "Ma sœur a choisi la randonnée pour son exemple.",
          "Ils ont répété randonnée à voix haute.",
          "Nous allons revoir la randonnée avec le professeur.",
          "Elle a noté randonnée pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la randonnée.",
          "Après la leçon, j'ai utilisé le mot randonnée dans une phrase.",
          "Demain, je vais apprendre à mieux employer la randonnée.",
          "Quand je lis le texte, je cherche le sens de randonnée.",
          "Ce matin, nous avons associé la randonnée à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec randonnée.",
          "Le professeur a demandé un exemple avec la randonnée.",
          "J'ai choisi la randonnée parce que ce mot était dans la liste.",
          "Nous allons réviser la randonnée avant l'évaluation.",
          "Mon camarade a expliqué la randonnée avec ses mots.",
          "J'ai ajouté randonnée dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la randonnée demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique la randonnée régulièrement, je progresse peu à peu.",
          "Si tu fais de la randonnée, tu dois respecter les règles de sécurité.",
          "Même si je connais la randonnée, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi la randonnée.",
          "L'activité que nous découvrons aujourd'hui s'appelle randonnée.",
          "Pendant que le professeur expliquait la randonnée, les élèves préparaient le matériel.",
          "Puisque la randonnée était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de la randonnée, tu joueras plus facilement.",
          "Je pense que la randonnée aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, la randonnée demande de l'attention.",
          "Le sport dont je parle est la randonnée, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras la randonnée, tu gagneras en confiance.",
          "Bien que la randonnée soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient la randonnée, je penserai aux règles du jeu.",
          "Bien que le mot randonnée paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la randonnée apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la randonnée, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà randonnée, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la randonnée.",
          "Lorsque j'aurai mémorisé randonnée, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la randonnée.",
          "Puisque randonnée est utile, je le révise régulièrement.",
        ],
      } },
    { word: "judo", image: "judo.webp", article: "le", gender: "m", definition: "Le judo est art martial japonais. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du judo.",
          "J'aime le judo.",
          "Le judo est un sport.",
          "Le judo est une activité.",
          "Je pratique le judo.",
          "Je regarde le judo.",
          "Tu fais du judo.",
          "Il joue au judo.",
          "Elle pratique le judo.",
          "Nous faisons du judo.",
          "Vous aimez le judo.",
          "Ils jouent au judo.",
          "Elles regardent le judo.",
          "Le judo est dans le gymnase.",
          "Le judo est sur l'image.",
          "Je choisis le judo.",
          "Je commence le judo.",
          "Il apprend le judo.",
          "Elle aime le judo.",
          "Le professeur explique le judo.",
          "La classe pratique le judo.",
          "Ce sport est simple.",
          "Je parle du judo.",
          "Nous essayons le judo.",
          "Tu connais le judo.",
          "Aujourd'hui, je vois le judo.",
          "Dans mon cahier, j'écris judo.",
          "Le mot judo est nouveau pour moi.",
          "Je répète judo à voix haute.",
          "Nous dessinons le judo.",
          "La classe regarde le judo.",
          "Je montre le judo au professeur.",
          "Il y a le judo dans l'image.",
          "Cette leçon parle du judo.",
        ],
        a2: [
          "Hier, j'ai fait du judo avec mes amis.",
          "Demain, je vais pratiquer le judo.",
          "Quand j'étais petit, je jouais souvent au judo.",
          "Ce matin, le professeur a présenté le judo.",
          "Nous avons essayé le judo pendant le cours.",
          "Ils vont jouer au judo cette semaine.",
          "J'ai choisi le judo parce que cette activité me plaît.",
          "Elle a regardé le judo à la télévision.",
          "Avant l'entraînement, nous avons parlé du judo.",
          "Le groupe a découvert le judo au centre sportif.",
          "Je vais pratiquer le judo après l'école.",
          "Nous avons appris les règles du judo.",
          "Hier soir, mon frère a regardé le judo.",
          "Pendant les vacances, je faisais souvent du judo.",
          "Elle a oublié le mot judo pendant l'exercice.",
          "Il va utiliser le judo dans sa phrase.",
          "Nous avons trouvé le judo dans le texte.",
          "Ce week-end, je vais essayer le judo.",
          "L'élève a ajouté le judo dans sa réponse.",
          "J'ai compris le mot judo pour la première fois.",
          "Ma sœur a choisi le judo pour son exemple.",
          "Ils ont répété judo à voix haute.",
          "Nous allons revoir le judo avec le professeur.",
          "Elle a noté judo pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le judo.",
          "Après la leçon, j'ai utilisé le mot judo dans une phrase.",
          "Demain, je vais apprendre à mieux employer le judo.",
          "Quand je lis le texte, je cherche le sens de judo.",
          "Ce matin, nous avons associé le judo à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec judo.",
          "Le professeur a demandé un exemple avec le judo.",
          "J'ai choisi le judo parce que ce mot était dans la liste.",
          "Nous allons réviser le judo avant l'évaluation.",
          "Mon camarade a expliqué le judo avec ses mots.",
          "J'ai ajouté judo dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le judo demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le judo régulièrement, je progresse peu à peu.",
          "Si tu fais du judo, tu dois respecter les règles de sécurité.",
          "Même si je connais le judo, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le judo.",
          "L'activité que nous découvrons aujourd'hui s'appelle judo.",
          "Pendant que le professeur expliquait le judo, les élèves préparaient le matériel.",
          "Puisque le judo était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du judo, tu joueras plus facilement.",
          "Je pense que le judo aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le judo demande de l'attention.",
          "Le sport dont je parle est le judo, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le judo, tu gagneras en confiance.",
          "Bien que le judo soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le judo, je penserai aux règles du jeu.",
          "Bien que le mot judo paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le judo apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le judo, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà judo, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le judo.",
          "Lorsque j'aurai mémorisé judo, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le judo.",
          "Puisque judo est utile, je le révise régulièrement.",
        ],
      } },
    { word: "gymnastique", image: "gymnastique.webp", article: "la", gender: "f", definition: "La gymnastique est sport d'agilité et de souplesse. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de la gymnastique.",
          "J'aime la gymnastique.",
          "La gymnastique est un sport.",
          "La gymnastique est une activité.",
          "Je pratique la gymnastique.",
          "Je regarde la gymnastique.",
          "Tu fais de la gymnastique.",
          "Il joue à la gymnastique.",
          "Elle pratique la gymnastique.",
          "Nous faisons de la gymnastique.",
          "Vous aimez la gymnastique.",
          "Ils jouent à la gymnastique.",
          "Elles regardent la gymnastique.",
          "La gymnastique est dans le gymnase.",
          "La gymnastique est sur l'image.",
          "Je choisis la gymnastique.",
          "Je commence la gymnastique.",
          "Il apprend la gymnastique.",
          "Elle aime la gymnastique.",
          "Le professeur explique la gymnastique.",
          "La classe pratique la gymnastique.",
          "Ce sport est simple.",
          "Je parle de la gymnastique.",
          "Nous essayons la gymnastique.",
          "Tu connais la gymnastique.",
          "Aujourd'hui, je vois la gymnastique.",
          "Dans mon cahier, j'écris gymnastique.",
          "Le mot gymnastique est nouveau pour moi.",
          "Je répète gymnastique à voix haute.",
          "Nous dessinons la gymnastique.",
          "La classe regarde la gymnastique.",
          "Je montre la gymnastique au professeur.",
          "Il y a la gymnastique dans l'image.",
          "Cette leçon parle de la gymnastique.",
        ],
        a2: [
          "Hier, j'ai fait de la gymnastique avec mes amis.",
          "Demain, je vais pratiquer la gymnastique.",
          "Quand j'étais petit, je jouais souvent à la gymnastique.",
          "Ce matin, le professeur a présenté la gymnastique.",
          "Nous avons essayé la gymnastique pendant le cours.",
          "Ils vont jouer à la gymnastique cette semaine.",
          "J'ai choisi la gymnastique parce que cette activité me plaît.",
          "Elle a regardé la gymnastique à la télévision.",
          "Avant l'entraînement, nous avons parlé de la gymnastique.",
          "Le groupe a découvert la gymnastique au centre sportif.",
          "Je vais pratiquer la gymnastique après l'école.",
          "Nous avons appris les règles de la gymnastique.",
          "Hier soir, mon frère a regardé la gymnastique.",
          "Pendant les vacances, je faisais souvent de la gymnastique.",
          "Elle a oublié le mot gymnastique pendant l'exercice.",
          "Il va utiliser la gymnastique dans sa phrase.",
          "Nous avons trouvé la gymnastique dans le texte.",
          "Ce week-end, je vais essayer la gymnastique.",
          "L'élève a ajouté la gymnastique dans sa réponse.",
          "J'ai compris le mot gymnastique pour la première fois.",
          "Ma sœur a choisi la gymnastique pour son exemple.",
          "Ils ont répété gymnastique à voix haute.",
          "Nous allons revoir la gymnastique avec le professeur.",
          "Elle a noté gymnastique pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la gymnastique.",
          "Après la leçon, j'ai utilisé le mot gymnastique dans une phrase.",
          "Demain, je vais apprendre à mieux employer la gymnastique.",
          "Quand je lis le texte, je cherche le sens de gymnastique.",
          "Ce matin, nous avons associé la gymnastique à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec gymnastique.",
          "Le professeur a demandé un exemple avec la gymnastique.",
          "J'ai choisi la gymnastique parce que ce mot était dans la liste.",
          "Nous allons réviser la gymnastique avant l'évaluation.",
          "Mon camarade a expliqué la gymnastique avec ses mots.",
          "J'ai ajouté gymnastique dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la gymnastique demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique la gymnastique régulièrement, je progresse peu à peu.",
          "Si tu fais de la gymnastique, tu dois respecter les règles de sécurité.",
          "Même si je connais la gymnastique, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi la gymnastique.",
          "L'activité que nous découvrons aujourd'hui s'appelle gymnastique.",
          "Pendant que le professeur expliquait la gymnastique, les élèves préparaient le matériel.",
          "Puisque la gymnastique était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de la gymnastique, tu joueras plus facilement.",
          "Je pense que la gymnastique aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, la gymnastique demande de l'attention.",
          "Le sport dont je parle est la gymnastique, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras la gymnastique, tu gagneras en confiance.",
          "Bien que la gymnastique soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient la gymnastique, je penserai aux règles du jeu.",
          "Bien que le mot gymnastique paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la gymnastique apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la gymnastique, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà gymnastique, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la gymnastique.",
          "Lorsque j'aurai mémorisé gymnastique, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la gymnastique.",
          "Puisque gymnastique est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ski", image: "ski.webp", article: "le", gender: "m", definition: "Le ski est sport de glisse sur la neige. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du ski.",
          "J'aime le ski.",
          "Le ski est un sport.",
          "Le ski est une activité.",
          "Je pratique le ski.",
          "Je regarde le ski.",
          "Tu fais du ski.",
          "Il joue au ski.",
          "Elle pratique le ski.",
          "Nous faisons du ski.",
          "Vous aimez le ski.",
          "Ils jouent au ski.",
          "Elles regardent le ski.",
          "Le ski est dans le gymnase.",
          "Le ski est sur l'image.",
          "Je choisis le ski.",
          "Je commence le ski.",
          "Il apprend le ski.",
          "Elle aime le ski.",
          "Le professeur explique le ski.",
          "La classe pratique le ski.",
          "Ce sport est simple.",
          "Je parle du ski.",
          "Nous essayons le ski.",
          "Tu connais le ski.",
          "Aujourd'hui, je vois le ski.",
          "Dans mon cahier, j'écris ski.",
          "Le mot ski est nouveau pour moi.",
          "Je répète ski à voix haute.",
          "Nous dessinons le ski.",
          "La classe regarde le ski.",
          "Je montre le ski au professeur.",
          "Il y a le ski dans l'image.",
          "Cette leçon parle du ski.",
        ],
        a2: [
          "Hier, j'ai fait du ski avec mes amis.",
          "Demain, je vais pratiquer le ski.",
          "Quand j'étais petit, je jouais souvent au ski.",
          "Ce matin, le professeur a présenté le ski.",
          "Nous avons essayé le ski pendant le cours.",
          "Ils vont jouer au ski cette semaine.",
          "J'ai choisi le ski parce que cette activité me plaît.",
          "Elle a regardé le ski à la télévision.",
          "Avant l'entraînement, nous avons parlé du ski.",
          "Le groupe a découvert le ski au centre sportif.",
          "Je vais pratiquer le ski après l'école.",
          "Nous avons appris les règles du ski.",
          "Hier soir, mon frère a regardé le ski.",
          "Pendant les vacances, je faisais souvent du ski.",
          "Elle a oublié le mot ski pendant l'exercice.",
          "Il va utiliser le ski dans sa phrase.",
          "Nous avons trouvé le ski dans le texte.",
          "Ce week-end, je vais essayer le ski.",
          "L'élève a ajouté le ski dans sa réponse.",
          "J'ai compris le mot ski pour la première fois.",
          "Ma sœur a choisi le ski pour son exemple.",
          "Ils ont répété ski à voix haute.",
          "Nous allons revoir le ski avec le professeur.",
          "Elle a noté ski pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le ski.",
          "Après la leçon, j'ai utilisé le mot ski dans une phrase.",
          "Demain, je vais apprendre à mieux employer le ski.",
          "Quand je lis le texte, je cherche le sens de ski.",
          "Ce matin, nous avons associé le ski à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ski.",
          "Le professeur a demandé un exemple avec le ski.",
          "J'ai choisi le ski parce que ce mot était dans la liste.",
          "Nous allons réviser le ski avant l'évaluation.",
          "Mon camarade a expliqué le ski avec ses mots.",
          "J'ai ajouté ski dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le ski demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le ski régulièrement, je progresse peu à peu.",
          "Si tu fais du ski, tu dois respecter les règles de sécurité.",
          "Même si je connais le ski, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le ski.",
          "L'activité que nous découvrons aujourd'hui s'appelle ski.",
          "Pendant que le professeur expliquait le ski, les élèves préparaient le matériel.",
          "Puisque le ski était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du ski, tu joueras plus facilement.",
          "Je pense que le ski aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le ski demande de l'attention.",
          "Le sport dont je parle est le ski, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le ski, tu gagneras en confiance.",
          "Bien que le ski soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le ski, je penserai aux règles du jeu.",
          "Bien que le mot ski paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le ski apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le ski, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ski, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le ski.",
          "Lorsque j'aurai mémorisé ski, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le ski.",
          "Puisque ski est utile, je le révise régulièrement.",
        ],
      } },
    { word: "handball", image: "handball.webp", article: "le", gender: "m", definition: "Le handball est sport collectif avec un ballon et les mains. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de l'handball.",
          "J'aime l'handball.",
          "L'handball est un sport.",
          "L'handball est une activité.",
          "Je pratique l'handball.",
          "Je regarde l'handball.",
          "Tu fais de l'handball.",
          "Il joue à l'handball.",
          "Elle pratique l'handball.",
          "Nous faisons de l'handball.",
          "Vous aimez l'handball.",
          "Ils jouent à l'handball.",
          "Elles regardent l'handball.",
          "L'handball est dans le gymnase.",
          "L'handball est sur l'image.",
          "Je choisis l'handball.",
          "Je commence l'handball.",
          "Il apprend l'handball.",
          "Elle aime l'handball.",
          "Le professeur explique l'handball.",
          "La classe pratique l'handball.",
          "Ce sport est simple.",
          "Je parle de l'handball.",
          "Nous essayons l'handball.",
          "Tu connais l'handball.",
          "Aujourd'hui, je vois l'handball.",
          "Dans mon cahier, j'écris handball.",
          "Le mot handball est nouveau pour moi.",
          "Je répète handball à voix haute.",
          "Nous dessinons l'handball.",
          "La classe regarde l'handball.",
          "Je montre l'handball au professeur.",
          "Il y a l'handball dans l'image.",
          "Cette leçon parle de l'handball.",
        ],
        a2: [
          "Hier, j'ai fait de l'handball avec mes amis.",
          "Demain, je vais pratiquer l'handball.",
          "Quand j'étais petit, je jouais souvent à l'handball.",
          "Ce matin, le professeur a présenté l'handball.",
          "Nous avons essayé l'handball pendant le cours.",
          "Ils vont jouer à l'handball cette semaine.",
          "J'ai choisi l'handball parce que cette activité me plaît.",
          "Elle a regardé l'handball à la télévision.",
          "Avant l'entraînement, nous avons parlé de l'handball.",
          "Le groupe a découvert l'handball au centre sportif.",
          "Je vais pratiquer l'handball après l'école.",
          "Nous avons appris les règles de l'handball.",
          "Hier soir, mon frère a regardé l'handball.",
          "Pendant les vacances, je faisais souvent de l'handball.",
          "Elle a oublié le mot handball pendant l'exercice.",
          "Il va utiliser l'handball dans sa phrase.",
          "Nous avons trouvé l'handball dans le texte.",
          "Ce week-end, je vais essayer l'handball.",
          "L'élève a ajouté l'handball dans sa réponse.",
          "J'ai compris le mot handball pour la première fois.",
          "Ma sœur a choisi l'handball pour son exemple.",
          "Ils ont répété handball à voix haute.",
          "Nous allons revoir l'handball avec le professeur.",
          "Elle a noté handball pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'handball.",
          "Après la leçon, j'ai utilisé le mot handball dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'handball.",
          "Quand je lis le texte, je cherche le sens de handball.",
          "Ce matin, nous avons associé l'handball à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec handball.",
          "Le professeur a demandé un exemple avec l'handball.",
          "J'ai choisi l'handball parce que ce mot était dans la liste.",
          "Nous allons réviser l'handball avant l'évaluation.",
          "Mon camarade a expliqué l'handball avec ses mots.",
          "J'ai ajouté handball dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'handball demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique l'handball régulièrement, je progresse peu à peu.",
          "Si tu fais de l'handball, tu dois respecter les règles de sécurité.",
          "Même si je connais l'handball, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi l'handball.",
          "L'activité que nous découvrons aujourd'hui s'appelle handball.",
          "Pendant que le professeur expliquait l'handball, les élèves préparaient le matériel.",
          "Puisque l'handball était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de l'handball, tu joueras plus facilement.",
          "Je pense que l'handball aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, l'handball demande de l'attention.",
          "Le sport dont je parle est l'handball, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras l'handball, tu gagneras en confiance.",
          "Bien que l'handball soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient l'handball, je penserai aux règles du jeu.",
          "Bien que le mot handball paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'handball apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'handball, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà handball, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'handball.",
          "Lorsque j'aurai mémorisé handball, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'handball.",
          "Puisque handball est utile, je le révise régulièrement.",
        ],
      } },
    { word: "volley-ball", image: "volleyball.webp", article: "le", gender: "m", definition: "Le volley-ball est sport collectif où l'on frappe un ballon par-dessus un filet. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais du volley-ball.",
          "J'aime le volley-ball.",
          "Le volley-ball est un sport.",
          "Le volley-ball est une activité.",
          "Je pratique le volley-ball.",
          "Je regarde le volley-ball.",
          "Tu fais du volley-ball.",
          "Il joue au volley-ball.",
          "Elle pratique le volley-ball.",
          "Nous faisons du volley-ball.",
          "Vous aimez le volley-ball.",
          "Ils jouent au volley-ball.",
          "Elles regardent le volley-ball.",
          "Le volley-ball est dans le gymnase.",
          "Le volley-ball est sur l'image.",
          "Je choisis le volley-ball.",
          "Je commence le volley-ball.",
          "Il apprend le volley-ball.",
          "Elle aime le volley-ball.",
          "Le professeur explique le volley-ball.",
          "La classe pratique le volley-ball.",
          "Ce sport est simple.",
          "Je parle du volley-ball.",
          "Nous essayons le volley-ball.",
          "Tu connais le volley-ball.",
          "Aujourd'hui, je vois le volley-ball.",
          "Dans mon cahier, j'écris volley-ball.",
          "Le mot volley-ball est nouveau pour moi.",
          "Je répète volley-ball à voix haute.",
          "Nous dessinons le volley-ball.",
          "La classe regarde le volley-ball.",
          "Je montre le volley-ball au professeur.",
          "Il y a le volley-ball dans l'image.",
          "Cette leçon parle du volley-ball.",
        ],
        a2: [
          "Hier, j'ai fait du volley-ball avec mes amis.",
          "Demain, je vais pratiquer le volley-ball.",
          "Quand j'étais petit, je jouais souvent au volley-ball.",
          "Ce matin, le professeur a présenté le volley-ball.",
          "Nous avons essayé le volley-ball pendant le cours.",
          "Ils vont jouer au volley-ball cette semaine.",
          "J'ai choisi le volley-ball parce que cette activité me plaît.",
          "Elle a regardé le volley-ball à la télévision.",
          "Avant l'entraînement, nous avons parlé du volley-ball.",
          "Le groupe a découvert le volley-ball au centre sportif.",
          "Je vais pratiquer le volley-ball après l'école.",
          "Nous avons appris les règles du volley-ball.",
          "Hier soir, mon frère a regardé le volley-ball.",
          "Pendant les vacances, je faisais souvent du volley-ball.",
          "Elle a oublié le mot volley-ball pendant l'exercice.",
          "Il va utiliser le volley-ball dans sa phrase.",
          "Nous avons trouvé le volley-ball dans le texte.",
          "Ce week-end, je vais essayer le volley-ball.",
          "L'élève a ajouté le volley-ball dans sa réponse.",
          "J'ai compris le mot volley-ball pour la première fois.",
          "Ma sœur a choisi le volley-ball pour son exemple.",
          "Ils ont répété volley-ball à voix haute.",
          "Nous allons revoir le volley-ball avec le professeur.",
          "Elle a noté volley-ball pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le volley-ball.",
          "Après la leçon, j'ai utilisé le mot volley-ball dans une phrase.",
          "Demain, je vais apprendre à mieux employer le volley-ball.",
          "Quand je lis le texte, je cherche le sens de volley-ball.",
          "Ce matin, nous avons associé le volley-ball à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec volley-ball.",
          "Le professeur a demandé un exemple avec le volley-ball.",
          "J'ai choisi le volley-ball parce que ce mot était dans la liste.",
          "Nous allons réviser le volley-ball avant l'évaluation.",
          "Mon camarade a expliqué le volley-ball avec ses mots.",
          "J'ai ajouté volley-ball dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le volley-ball demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique le volley-ball régulièrement, je progresse peu à peu.",
          "Si tu fais du volley-ball, tu dois respecter les règles de sécurité.",
          "Même si je connais le volley-ball, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi le volley-ball.",
          "L'activité que nous découvrons aujourd'hui s'appelle volley-ball.",
          "Pendant que le professeur expliquait le volley-ball, les élèves préparaient le matériel.",
          "Puisque le volley-ball était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles du volley-ball, tu joueras plus facilement.",
          "Je pense que le volley-ball aide les élèves parce qu'il développe la coopération.",
          "Même quand l'entraînement est court, le volley-ball demande de l'attention.",
          "Le sport dont je parle est le volley-ball, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras le volley-ball, tu gagneras en confiance.",
          "Bien que le volley-ball soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient le volley-ball, je penserai aux règles du jeu.",
          "Bien que le mot volley-ball paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le volley-ball apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le volley-ball, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà volley-ball, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le volley-ball.",
          "Lorsque j'aurai mémorisé volley-ball, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le volley-ball.",
          "Puisque volley-ball est utile, je le révise régulièrement.",
        ],
      } },
    { word: "escalade", image: "escalade.webp", article: "l'", gender: "f", definition: "L'escalade est sport consistant à grimper une paroi. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je fais de l'escalade.",
          "J'aime l'escalade.",
          "L'escalade est un sport.",
          "L'escalade est une activité.",
          "Je pratique l'escalade.",
          "Je regarde l'escalade.",
          "Tu fais de l'escalade.",
          "Il joue à l'escalade.",
          "Elle pratique l'escalade.",
          "Nous faisons de l'escalade.",
          "Vous aimez l'escalade.",
          "Ils jouent à l'escalade.",
          "Elles regardent l'escalade.",
          "L'escalade est dans le gymnase.",
          "L'escalade est sur l'image.",
          "Je choisis l'escalade.",
          "Je commence l'escalade.",
          "Il apprend l'escalade.",
          "Elle aime l'escalade.",
          "Le professeur explique l'escalade.",
          "La classe pratique l'escalade.",
          "Ce sport est simple.",
          "Je parle de l'escalade.",
          "Nous essayons l'escalade.",
          "Tu connais l'escalade.",
          "Aujourd'hui, je vois l'escalade.",
          "Dans mon cahier, j'écris escalade.",
          "Le mot escalade est nouveau pour moi.",
          "Je répète escalade à voix haute.",
          "Nous dessinons l'escalade.",
          "La classe regarde l'escalade.",
          "Je montre l'escalade au professeur.",
          "Il y a l'escalade dans l'image.",
          "Cette leçon parle de l'escalade.",
        ],
        a2: [
          "Hier, j'ai fait de l'escalade avec mes amis.",
          "Demain, je vais pratiquer l'escalade.",
          "Quand j'étais petit, je jouais souvent à l'escalade.",
          "Ce matin, le professeur a présenté l'escalade.",
          "Nous avons essayé l'escalade pendant le cours.",
          "Ils vont jouer à l'escalade cette semaine.",
          "J'ai choisi l'escalade parce que cette activité me plaît.",
          "Elle a regardé l'escalade à la télévision.",
          "Avant l'entraînement, nous avons parlé de l'escalade.",
          "Le groupe a découvert l'escalade au centre sportif.",
          "Je vais pratiquer l'escalade après l'école.",
          "Nous avons appris les règles de l'escalade.",
          "Hier soir, mon frère a regardé l'escalade.",
          "Pendant les vacances, je faisais souvent de l'escalade.",
          "Elle a oublié le mot escalade pendant l'exercice.",
          "Il va utiliser l'escalade dans sa phrase.",
          "Nous avons trouvé l'escalade dans le texte.",
          "Ce week-end, je vais essayer l'escalade.",
          "L'élève a ajouté l'escalade dans sa réponse.",
          "J'ai compris le mot escalade pour la première fois.",
          "Ma sœur a choisi l'escalade pour son exemple.",
          "Ils ont répété escalade à voix haute.",
          "Nous allons revoir l'escalade avec le professeur.",
          "Elle a noté escalade pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'escalade.",
          "Après la leçon, j'ai utilisé le mot escalade dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'escalade.",
          "Quand je lis le texte, je cherche le sens de escalade.",
          "Ce matin, nous avons associé l'escalade à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec escalade.",
          "Le professeur a demandé un exemple avec l'escalade.",
          "J'ai choisi l'escalade parce que ce mot était dans la liste.",
          "Nous allons réviser l'escalade avant l'évaluation.",
          "Mon camarade a expliqué l'escalade avec ses mots.",
          "J'ai ajouté escalade dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'escalade demande de l'énergie, beaucoup d'élèves aiment cette activité.",
          "Comme je pratique l'escalade régulièrement, je progresse peu à peu.",
          "Si tu fais de l'escalade, tu dois respecter les règles de sécurité.",
          "Même si je connais l'escalade, je dois encore améliorer ma technique.",
          "L'élève, qui voulait bouger davantage, a choisi l'escalade.",
          "L'activité que nous découvrons aujourd'hui s'appelle escalade.",
          "Pendant que le professeur expliquait l'escalade, les élèves préparaient le matériel.",
          "Puisque l'escalade était difficile, nous avons recommencé l'exercice.",
          "Lorsque tu auras compris les règles de l'escalade, tu joueras plus facilement.",
          "Je pense que l'escalade aide les élèves parce qu'elle développe la coopération.",
          "Même quand l'entraînement est court, l'escalade demande de l'attention.",
          "Le sport dont je parle est l'escalade, que plusieurs élèves pratiquent déjà.",
          "Tant que tu pratiqueras l'escalade, tu gagneras en confiance.",
          "Bien que l'escalade soit parfois exigeant, cette activité reste motivante.",
          "Si la leçon contient l'escalade, je penserai aux règles du jeu.",
          "Bien que le mot escalade paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'escalade apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'escalade, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà escalade, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'escalade.",
          "Lorsque j'aurai mémorisé escalade, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'escalade.",
          "Puisque escalade est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il joue au ___ avec ses amis dans le parc.", answer: "football" },
    { sentence: "La ___ est un sport très bon pour la santé cardio.", answer: "natation" },
    { sentence: "En hiver, beaucoup de gens pratiquent le ___ en montagne.", answer: "ski" },
    { sentence: "Elle fait du ___ chaque matin pour se détendre.", answer: "yoga" },
    { sentence: "L'___ demande beaucoup de force et de technique.", answer: "escalade" },
  ],
};
