import type { VocabTheme } from "../../vocabulary-data";

export const V1_FAMILLE_THEME: VocabTheme = {
  slug: "v1-famille",
  code: "V1.3",
  title: "La famille",
  section: "V1",
  words: [
    {
      word: "père",
      article: "le",
      gender: "m",
      image: "pere.webp",
      definition: ["Homme qui a un ou plusieurs enfants."],
      definitionPivot: {
        en: "The male parent.",
        ar: "الوالد الذكر.",
        fa: "والد مرد.",
        pt: "O progenitor masculino.",
        so: "Waalidka labka ah.",
        ti: "ወላዲ ወዲ።",
        tr: "Erkek ebeveyn.",
        ps: "نارینه مور او پلار.",
        uk: "Чоловік-батько.",
      },
      synonym: ["papa", "parent"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le père a parlé avec le professeur.",
          "Demain, le père va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le père.",
          "Ce matin, le père a pris le bus.",
          "Le père a préparé le repas hier soir.",
          "Le père va aider les enfants demain.",
          "Avant, le père habitait dans une autre ville.",
          "Le père a acheté du pain au magasin.",
          "Pendant les vacances, le père venait souvent nous voir.",
          "Le père a oublié ses clés ce matin.",
          "Je vais appeler le père après le cours.",
          "Le père a travaillé tard hier.",
          "Nous avons rencontré le père dans la rue.",
          "Le père va organiser une sortie samedi.",
          "Quand il faisait froid, le père restait à la maison.",
          "Le père a expliqué le problème calmement.",
          "Hier soir, le père a regardé un film.",
          "Le père va chercher les enfants à l'école.",
          "Ce week-end, le père a rangé la cuisine.",
          "Le père a appris une bonne nouvelle.",
          "Je pense que le père va arriver bientôt.",
          "Le père a donné un conseil utile.",
          "Avant le repas, le père a mis la table.",
          "Le père va partir en voyage demain.",
          "Le père a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot père dans une phrase.",
          "Demain, je vais apprendre à mieux employer le père.",
          "Quand je lis le texte, je cherche le sens de père.",
          "Ce matin, nous avons associé le père à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec père.",
          "Le professeur a demandé un exemple avec le père.",
          "J'ai choisi le père parce que ce mot était dans la liste.",
          "Nous allons réviser le père avant l'évaluation.",
          "Mon camarade a expliqué le père avec ses mots.",
          "J'ai ajouté père dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le père soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le père connaît bien la situation, il peut donner un conseil utile.",
          "Si le père avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le père reste calme et disponible.",
          "Le père, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le père préparait le repas, les enfants rangeaient la table.",
          "Puisque le père travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le père aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le père progresse parce qu'il pratique le français chaque jour.",
          "Tant que le père restera motivé, il continuera à faire des progrès.",
          "Même si le père ne parle pas parfaitement, il ose poser des questions.",
          "Le père a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le père depuis plusieurs années.",
          "Bien que le père ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le père, nous lui demanderons de nous accompagner.",
          "Bien que le mot père paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le père apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le père, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà père, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le père.",
          "Lorsque j'aurai mémorisé père, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le père.",
          "Puisque père est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "mère",
      article: "la",
      gender: "f",
      image: "mere.webp",
      definition: ["Femme qui a un ou plusieurs enfants."],
      definitionPivot: {
        en: "The female parent.",
        ar: "الوالدة الأنثى.",
        fa: "والد زن.",
        pt: "A progenitora feminina.",
        so: "Waalidka dhedigga ah.",
        ti: "ወላዲት ኣደ።",
        tr: "Kadın ebeveyn.",
        ps: "ښځینه مور او پلار.",
        uk: "Жінка-мати.",
      },
      synonym: ["maman", "parent"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la mère a parlé avec le professeur.",
          "Demain, la mère va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la mère.",
          "Ce matin, la mère a pris le bus.",
          "La mère a préparé le repas hier soir.",
          "La mère va aider les enfants demain.",
          "Avant, la mère habitait dans une autre ville.",
          "La mère a acheté du pain au magasin.",
          "Pendant les vacances, la mère venait souvent nous voir.",
          "La mère a oublié ses clés ce matin.",
          "Je vais appeler la mère après le cours.",
          "La mère a travaillé tard hier.",
          "Nous avons rencontré la mère dans la rue.",
          "La mère va organiser une sortie samedi.",
          "Quand il faisait froid, la mère restait à la maison.",
          "La mère a expliqué le problème calmement.",
          "Hier soir, la mère a regardé un film.",
          "La mère va chercher les enfants à l'école.",
          "Ce week-end, la mère a rangé la cuisine.",
          "La mère a appris une bonne nouvelle.",
          "Je pense que la mère va arriver bientôt.",
          "La mère a donné un conseil utile.",
          "Avant le repas, la mère a mis la table.",
          "La mère va partir en voyage demain.",
          "La mère a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot mère dans une phrase.",
          "Demain, je vais apprendre à mieux employer la mère.",
          "Quand je lis le texte, je cherche le sens de mère.",
          "Ce matin, nous avons associé la mère à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec mère.",
          "Le professeur a demandé un exemple avec la mère.",
          "J'ai choisi la mère parce que ce mot était dans la liste.",
          "Nous allons réviser la mère avant l'évaluation.",
          "Mon camarade a expliqué la mère avec ses mots.",
          "J'ai ajouté mère dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la mère soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la mère connaît bien la situation, il peut donner un conseil utile.",
          "Si la mère avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la mère reste calme et disponible.",
          "La mère, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la mère préparait le repas, les enfants rangeaient la table.",
          "Puisque la mère travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la mère aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la mère progresse parce qu'il pratique le français chaque jour.",
          "Tant que la mère restera motivé, il continuera à faire des progrès.",
          "Même si la mère ne parle pas parfaitement, il ose poser des questions.",
          "La mère a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la mère depuis plusieurs années.",
          "Bien que la mère ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la mère, nous lui demanderons de nous accompagner.",
          "Bien que le mot mère paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la mère apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la mère, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà mère, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la mère.",
          "Lorsque j'aurai mémorisé mère, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la mère.",
          "Puisque mère est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "fils",
      article: "le",
      gender: "m",
      image: "fils.webp",
      definition: ["Garçon ou homme par rapport à son père ou à sa mère."],
      definitionPivot: {
        en: "A male child in a family.",
        ar: "طفل ذكر في العائلة.",
        fa: "فرزند پسر در خانواده.",
        pt: "Um filho menino na família.",
        so: "Wiil ka tirsan qoyska.",
        ti: "ወዲ ኣብ ስድራ።",
        tr: "Ailede erkek çocuk.",
        ps: "په کورنۍ کې زوی.",
        uk: "Син у сім’ї.",
      },
      synonym: ["enfant"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le fils a parlé avec le professeur.",
          "Demain, le fils va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le fils.",
          "Ce matin, le fils a pris le bus.",
          "Le fils a préparé le repas hier soir.",
          "Le fils va aider les enfants demain.",
          "Avant, le fils habitait dans une autre ville.",
          "Le fils a acheté du pain au magasin.",
          "Pendant les vacances, le fils venait souvent nous voir.",
          "Le fils a oublié ses clés ce matin.",
          "Je vais appeler le fils après le cours.",
          "Le fils a travaillé tard hier.",
          "Nous avons rencontré le fils dans la rue.",
          "Le fils va organiser une sortie samedi.",
          "Quand il faisait froid, le fils restait à la maison.",
          "Le fils a expliqué le problème calmement.",
          "Hier soir, le fils a regardé un film.",
          "Le fils va chercher les enfants à l'école.",
          "Ce week-end, le fils a rangé la cuisine.",
          "Le fils a appris une bonne nouvelle.",
          "Je pense que le fils va arriver bientôt.",
          "Le fils a donné un conseil utile.",
          "Avant le repas, le fils a mis la table.",
          "Le fils va partir en voyage demain.",
          "Le fils a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot fils dans une phrase.",
          "Demain, je vais apprendre à mieux employer le fils.",
          "Quand je lis le texte, je cherche le sens de fils.",
          "Ce matin, nous avons associé le fils à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec fils.",
          "Le professeur a demandé un exemple avec le fils.",
          "J'ai choisi le fils parce que ce mot était dans la liste.",
          "Nous allons réviser le fils avant l'évaluation.",
          "Mon camarade a expliqué le fils avec ses mots.",
          "J'ai ajouté fils dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le fils soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le fils connaît bien la situation, il peut donner un conseil utile.",
          "Si le fils avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le fils reste calme et disponible.",
          "Le fils, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le fils préparait le repas, les enfants rangeaient la table.",
          "Puisque le fils travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le fils aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le fils progresse parce qu'il pratique le français chaque jour.",
          "Tant que le fils restera motivé, il continuera à faire des progrès.",
          "Même si le fils ne parle pas parfaitement, il ose poser des questions.",
          "Le fils a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le fils depuis plusieurs années.",
          "Bien que le fils ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le fils, nous lui demanderons de nous accompagner.",
          "Bien que le mot fils paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le fils apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le fils, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà fils, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le fils.",
          "Lorsque j'aurai mémorisé fils, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le fils.",
          "Puisque fils est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "fille",
      article: "la",
      gender: "f",
      image: "fille.webp",
      definition: ["Fille ou femme par rapport à son père ou à sa mère."],
      definitionPivot: {
        en: "A female child in a family.",
        ar: "طفلة أنثى في العائلة.",
        fa: "فرزند دختر در خانواده.",
        pt: "Uma filha menina na família.",
        so: "Gabar ka tirsan qoyska.",
        ti: "ጓል ኣብ ስድራ።",
        tr: "Ailede kız çocuk.",
        ps: "په کورنۍ کې لور.",
        uk: "Донька у сім’ї.",
      },
      synonym: ["enfant"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la fille a parlé avec le professeur.",
          "Demain, la fille va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la fille.",
          "Ce matin, la fille a pris le bus.",
          "La fille a préparé le repas hier soir.",
          "La fille va aider les enfants demain.",
          "Avant, la fille habitait dans une autre ville.",
          "La fille a acheté du pain au magasin.",
          "Pendant les vacances, la fille venait souvent nous voir.",
          "La fille a oublié ses clés ce matin.",
          "Je vais appeler la fille après le cours.",
          "La fille a travaillé tard hier.",
          "Nous avons rencontré la fille dans la rue.",
          "La fille va organiser une sortie samedi.",
          "Quand il faisait froid, la fille restait à la maison.",
          "La fille a expliqué le problème calmement.",
          "Hier soir, la fille a regardé un film.",
          "La fille va chercher les enfants à l'école.",
          "Ce week-end, la fille a rangé la cuisine.",
          "La fille a appris une bonne nouvelle.",
          "Je pense que la fille va arriver bientôt.",
          "La fille a donné un conseil utile.",
          "Avant le repas, la fille a mis la table.",
          "La fille va partir en voyage demain.",
          "La fille a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot fille dans une phrase.",
          "Demain, je vais apprendre à mieux employer la fille.",
          "Quand je lis le texte, je cherche le sens de fille.",
          "Ce matin, nous avons associé la fille à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec fille.",
          "Le professeur a demandé un exemple avec la fille.",
          "J'ai choisi la fille parce que ce mot était dans la liste.",
          "Nous allons réviser la fille avant l'évaluation.",
          "Mon camarade a expliqué la fille avec ses mots.",
          "J'ai ajouté fille dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la fille soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la fille connaît bien la situation, il peut donner un conseil utile.",
          "Si la fille avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la fille reste calme et disponible.",
          "La fille, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la fille préparait le repas, les enfants rangeaient la table.",
          "Puisque la fille travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la fille aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la fille progresse parce qu'il pratique le français chaque jour.",
          "Tant que la fille restera motivé, il continuera à faire des progrès.",
          "Même si la fille ne parle pas parfaitement, il ose poser des questions.",
          "La fille a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la fille depuis plusieurs années.",
          "Bien que la fille ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la fille, nous lui demanderons de nous accompagner.",
          "Bien que le mot fille paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la fille apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la fille, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà fille, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la fille.",
          "Lorsque j'aurai mémorisé fille, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la fille.",
          "Puisque fille est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "frère",
      article: "le",
      gender: "m",
      image: "frere.webp",
      definition: ["Garçon ou homme qui a les mêmes parents qu’une autre personne."],
      definitionPivot: {
        en: "A boy or man with the same parents.",
        ar: "ولد أو رجل له نفس الوالدين.",
        fa: "پسر یا مردی با همان پدر و مادر.",
        pt: "Um rapaz ou homem com os mesmos pais.",
        so: "Wiil ama nin aad waalid wadaagtaan.",
        ti: "ሓው፣ ተመሳሳሊ ወለዲ ዘለዎ።",
        tr: "Aynı anne babaya sahip erkek.",
        ps: "هلک يا سړی چې هماغه مور او پلار لري.",
        uk: "Хлопець або чоловік з тими самими батьками.",
      },
      synonym: ["demi-frère"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le frère a parlé avec le professeur.",
          "Demain, le frère va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le frère.",
          "Ce matin, le frère a pris le bus.",
          "Le frère a préparé le repas hier soir.",
          "Le frère va aider les enfants demain.",
          "Avant, le frère habitait dans une autre ville.",
          "Le frère a acheté du pain au magasin.",
          "Pendant les vacances, le frère venait souvent nous voir.",
          "Le frère a oublié ses clés ce matin.",
          "Je vais appeler le frère après le cours.",
          "Le frère a travaillé tard hier.",
          "Nous avons rencontré le frère dans la rue.",
          "Le frère va organiser une sortie samedi.",
          "Quand il faisait froid, le frère restait à la maison.",
          "Le frère a expliqué le problème calmement.",
          "Hier soir, le frère a regardé un film.",
          "Le frère va chercher les enfants à l'école.",
          "Ce week-end, le frère a rangé la cuisine.",
          "Le frère a appris une bonne nouvelle.",
          "Je pense que le frère va arriver bientôt.",
          "Le frère a donné un conseil utile.",
          "Avant le repas, le frère a mis la table.",
          "Le frère va partir en voyage demain.",
          "Le frère a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot frère dans une phrase.",
          "Demain, je vais apprendre à mieux employer le frère.",
          "Quand je lis le texte, je cherche le sens de frère.",
          "Ce matin, nous avons associé le frère à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec frère.",
          "Le professeur a demandé un exemple avec le frère.",
          "J'ai choisi le frère parce que ce mot était dans la liste.",
          "Nous allons réviser le frère avant l'évaluation.",
          "Mon camarade a expliqué le frère avec ses mots.",
          "J'ai ajouté frère dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le frère soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le frère connaît bien la situation, il peut donner un conseil utile.",
          "Si le frère avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le frère reste calme et disponible.",
          "Le frère, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le frère préparait le repas, les enfants rangeaient la table.",
          "Puisque le frère travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le frère aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le frère progresse parce qu'il pratique le français chaque jour.",
          "Tant que le frère restera motivé, il continuera à faire des progrès.",
          "Même si le frère ne parle pas parfaitement, il ose poser des questions.",
          "Le frère a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le frère depuis plusieurs années.",
          "Bien que le frère ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le frère, nous lui demanderons de nous accompagner.",
          "Bien que le mot frère paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le frère apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le frère, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà frère, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le frère.",
          "Lorsque j'aurai mémorisé frère, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le frère.",
          "Puisque frère est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "sœur",
      article: "la",
      gender: "f",
      image: "soeur.webp",
      definition: ["Fille ou femme qui a les mêmes parents qu’une autre personne."],
      definitionPivot: {
        en: "A girl or woman with the same parents.",
        ar: "بنت أو امرأة لها نفس الوالدين.",
        fa: "دختر یا زنی با همان پدر و مادر.",
        pt: "Uma rapariga ou mulher com os mesmos pais.",
        so: "Gabar ama haweeney aad waalid wadaagtaan.",
        ti: "ሓብቲ፣ ተመሳሳሊ ወለዲ ዘለዋ።",
        tr: "Aynı anne babaya sahip kız.",
        ps: "نجلۍ يا ښځه چې هماغه مور او پلار لري.",
        uk: "Дівчина або жінка з тими самими батьками.",
      },
      synonym: ["demi-sœur"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la sœur a parlé avec le professeur.",
          "Demain, la sœur va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la sœur.",
          "Ce matin, la sœur a pris le bus.",
          "La sœur a préparé le repas hier soir.",
          "La sœur va aider les enfants demain.",
          "Avant, la sœur habitait dans une autre ville.",
          "La sœur a acheté du pain au magasin.",
          "Pendant les vacances, la sœur venait souvent nous voir.",
          "La sœur a oublié ses clés ce matin.",
          "Je vais appeler la sœur après le cours.",
          "La sœur a travaillé tard hier.",
          "Nous avons rencontré la sœur dans la rue.",
          "La sœur va organiser une sortie samedi.",
          "Quand il faisait froid, la sœur restait à la maison.",
          "La sœur a expliqué le problème calmement.",
          "Hier soir, la sœur a regardé un film.",
          "La sœur va chercher les enfants à l'école.",
          "Ce week-end, la sœur a rangé la cuisine.",
          "La sœur a appris une bonne nouvelle.",
          "Je pense que la sœur va arriver bientôt.",
          "La sœur a donné un conseil utile.",
          "Avant le repas, la sœur a mis la table.",
          "La sœur va partir en voyage demain.",
          "La sœur a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot sœur dans une phrase.",
          "Demain, je vais apprendre à mieux employer la sœur.",
          "Quand je lis le texte, je cherche le sens de sœur.",
          "Ce matin, nous avons associé la sœur à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec sœur.",
          "Le professeur a demandé un exemple avec la sœur.",
          "J'ai choisi la sœur parce que ce mot était dans la liste.",
          "Nous allons réviser la sœur avant l'évaluation.",
          "Mon camarade a expliqué la sœur avec ses mots.",
          "J'ai ajouté sœur dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la sœur soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la sœur connaît bien la situation, il peut donner un conseil utile.",
          "Si la sœur avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la sœur reste calme et disponible.",
          "La sœur, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la sœur préparait le repas, les enfants rangeaient la table.",
          "Puisque la sœur travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la sœur aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la sœur progresse parce qu'il pratique le français chaque jour.",
          "Tant que la sœur restera motivé, il continuera à faire des progrès.",
          "Même si la sœur ne parle pas parfaitement, il ose poser des questions.",
          "La sœur a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la sœur depuis plusieurs années.",
          "Bien que la sœur ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la sœur, nous lui demanderons de nous accompagner.",
          "Bien que le mot sœur paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la sœur apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la sœur, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà sœur, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la sœur.",
          "Lorsque j'aurai mémorisé sœur, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la sœur.",
          "Puisque sœur est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "grand-père",
      article: "le",
      gender: "m",
      image: "grand-pere.webp",
      definition: ["Père du père ou de la mère."],
      definitionPivot: {
        en: "The father of a parent.",
        ar: "والد الأب أو الأم.",
        fa: "پدرِ پدر یا مادر.",
        pt: "O pai do pai ou da mãe.",
        so: "Aabbaha aabbaha ama hooyada.",
        ti: "ኣቦ ናይ ኣቦ ወይ ኣደ።",
        tr: "Anne veya babanın babası.",
        ps: "د پلار يا مور پلار.",
        uk: "Батько тата або мами.",
      },
      synonym: ["papi", "grand-parent"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le grand-père a parlé avec le professeur.",
          "Demain, le grand-père va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le grand-père.",
          "Ce matin, le grand-père a pris le bus.",
          "Le grand-père a préparé le repas hier soir.",
          "Le grand-père va aider les enfants demain.",
          "Avant, le grand-père habitait dans une autre ville.",
          "Le grand-père a acheté du pain au magasin.",
          "Pendant les vacances, le grand-père venait souvent nous voir.",
          "Le grand-père a oublié ses clés ce matin.",
          "Je vais appeler le grand-père après le cours.",
          "Le grand-père a travaillé tard hier.",
          "Nous avons rencontré le grand-père dans la rue.",
          "Le grand-père va organiser une sortie samedi.",
          "Quand il faisait froid, le grand-père restait à la maison.",
          "Le grand-père a expliqué le problème calmement.",
          "Hier soir, le grand-père a regardé un film.",
          "Le grand-père va chercher les enfants à l'école.",
          "Ce week-end, le grand-père a rangé la cuisine.",
          "Le grand-père a appris une bonne nouvelle.",
          "Je pense que le grand-père va arriver bientôt.",
          "Le grand-père a donné un conseil utile.",
          "Avant le repas, le grand-père a mis la table.",
          "Le grand-père va partir en voyage demain.",
          "Le grand-père a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot grand-père dans une phrase.",
          "Demain, je vais apprendre à mieux employer le grand-père.",
          "Quand je lis le texte, je cherche le sens de grand-père.",
          "Ce matin, nous avons associé le grand-père à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec grand-père.",
          "Le professeur a demandé un exemple avec le grand-père.",
          "J'ai choisi le grand-père parce que ce mot était dans la liste.",
          "Nous allons réviser le grand-père avant l'évaluation.",
          "Mon camarade a expliqué le grand-père avec ses mots.",
          "J'ai ajouté grand-père dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le grand-père soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le grand-père connaît bien la situation, il peut donner un conseil utile.",
          "Si le grand-père avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le grand-père reste calme et disponible.",
          "Le grand-père, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le grand-père préparait le repas, les enfants rangeaient la table.",
          "Puisque le grand-père travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le grand-père aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le grand-père progresse parce qu'il pratique le français chaque jour.",
          "Tant que le grand-père restera motivé, il continuera à faire des progrès.",
          "Même si le grand-père ne parle pas parfaitement, il ose poser des questions.",
          "Le grand-père a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le grand-père depuis plusieurs années.",
          "Bien que le grand-père ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le grand-père, nous lui demanderons de nous accompagner.",
          "Bien que le mot grand-père paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le grand-père apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le grand-père, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà grand-père, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le grand-père.",
          "Lorsque j'aurai mémorisé grand-père, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le grand-père.",
          "Puisque grand-père est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "grand-mère",
      article: "la",
      gender: "f",
      image: "grand-mere.webp",
      definition: ["Mère du père ou de la mère."],
      definitionPivot: {
        en: "The mother of a parent.",
        ar: "والدة الأب أو الأم.",
        fa: "مادرِ پدر یا مادر.",
        pt: "A mãe do pai ou da mãe.",
        so: "Hooyada aabbaha ama hooyada.",
        ti: "ኣደ ናይ ኣቦ ወይ ኣደ።",
        tr: "Anne veya babanın annesi.",
        ps: "د پلار يا مور مور.",
        uk: "Мати тата або мами.",
      },
      synonym: ["mamie", "grand-parent"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la grand-mère a parlé avec le professeur.",
          "Demain, la grand-mère va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la grand-mère.",
          "Ce matin, la grand-mère a pris le bus.",
          "La grand-mère a préparé le repas hier soir.",
          "La grand-mère va aider les enfants demain.",
          "Avant, la grand-mère habitait dans une autre ville.",
          "La grand-mère a acheté du pain au magasin.",
          "Pendant les vacances, la grand-mère venait souvent nous voir.",
          "La grand-mère a oublié ses clés ce matin.",
          "Je vais appeler la grand-mère après le cours.",
          "La grand-mère a travaillé tard hier.",
          "Nous avons rencontré la grand-mère dans la rue.",
          "La grand-mère va organiser une sortie samedi.",
          "Quand il faisait froid, la grand-mère restait à la maison.",
          "La grand-mère a expliqué le problème calmement.",
          "Hier soir, la grand-mère a regardé un film.",
          "La grand-mère va chercher les enfants à l'école.",
          "Ce week-end, la grand-mère a rangé la cuisine.",
          "La grand-mère a appris une bonne nouvelle.",
          "Je pense que la grand-mère va arriver bientôt.",
          "La grand-mère a donné un conseil utile.",
          "Avant le repas, la grand-mère a mis la table.",
          "La grand-mère va partir en voyage demain.",
          "La grand-mère a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot grand-mère dans une phrase.",
          "Demain, je vais apprendre à mieux employer la grand-mère.",
          "Quand je lis le texte, je cherche le sens de grand-mère.",
          "Ce matin, nous avons associé la grand-mère à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec grand-mère.",
          "Le professeur a demandé un exemple avec la grand-mère.",
          "J'ai choisi la grand-mère parce que ce mot était dans la liste.",
          "Nous allons réviser la grand-mère avant l'évaluation.",
          "Mon camarade a expliqué la grand-mère avec ses mots.",
          "J'ai ajouté grand-mère dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la grand-mère soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la grand-mère connaît bien la situation, il peut donner un conseil utile.",
          "Si la grand-mère avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la grand-mère reste calme et disponible.",
          "La grand-mère, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la grand-mère préparait le repas, les enfants rangeaient la table.",
          "Puisque la grand-mère travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la grand-mère aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la grand-mère progresse parce qu'il pratique le français chaque jour.",
          "Tant que la grand-mère restera motivé, il continuera à faire des progrès.",
          "Même si la grand-mère ne parle pas parfaitement, il ose poser des questions.",
          "La grand-mère a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la grand-mère depuis plusieurs années.",
          "Bien que la grand-mère ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la grand-mère, nous lui demanderons de nous accompagner.",
          "Bien que le mot grand-mère paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la grand-mère apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la grand-mère, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà grand-mère, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la grand-mère.",
          "Lorsque j'aurai mémorisé grand-mère, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la grand-mère.",
          "Puisque grand-mère est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "petit-fils",
      article: "le",
      gender: "m",
      image: "petit-fils.webp",
      definition: ["Fils du fils ou de la fille."],
      definitionPivot: {
        en: "The son of your child.",
        ar: "ابن ابنك أو ابنتك.",
        fa: "پسرِ فرزند شما.",
        pt: "O filho do seu filho ou da sua filha.",
        so: "Wiilka ilmahaaga.",
        ti: "ወዲ ናይ ውላድካ።",
        tr: "Çocuğunuzun oğlu.",
        ps: "ستاسو د اولاد زوی.",
        uk: "Син вашої дитини.",
      },
      synonym: ["petit-enfant"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le petit-fils a parlé avec le professeur.",
          "Demain, le petit-fils va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le petit-fils.",
          "Ce matin, le petit-fils a pris le bus.",
          "Le petit-fils a préparé le repas hier soir.",
          "Le petit-fils va aider les enfants demain.",
          "Avant, le petit-fils habitait dans une autre ville.",
          "Le petit-fils a acheté du pain au magasin.",
          "Pendant les vacances, le petit-fils venait souvent nous voir.",
          "Le petit-fils a oublié ses clés ce matin.",
          "Je vais appeler le petit-fils après le cours.",
          "Le petit-fils a travaillé tard hier.",
          "Nous avons rencontré le petit-fils dans la rue.",
          "Le petit-fils va organiser une sortie samedi.",
          "Quand il faisait froid, le petit-fils restait à la maison.",
          "Le petit-fils a expliqué le problème calmement.",
          "Hier soir, le petit-fils a regardé un film.",
          "Le petit-fils va chercher les enfants à l'école.",
          "Ce week-end, le petit-fils a rangé la cuisine.",
          "Le petit-fils a appris une bonne nouvelle.",
          "Je pense que le petit-fils va arriver bientôt.",
          "Le petit-fils a donné un conseil utile.",
          "Avant le repas, le petit-fils a mis la table.",
          "Le petit-fils va partir en voyage demain.",
          "Le petit-fils a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot petit-fils dans une phrase.",
          "Demain, je vais apprendre à mieux employer le petit-fils.",
          "Quand je lis le texte, je cherche le sens de petit-fils.",
          "Ce matin, nous avons associé le petit-fils à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec petit-fils.",
          "Le professeur a demandé un exemple avec le petit-fils.",
          "J'ai choisi le petit-fils parce que ce mot était dans la liste.",
          "Nous allons réviser le petit-fils avant l'évaluation.",
          "Mon camarade a expliqué le petit-fils avec ses mots.",
          "J'ai ajouté petit-fils dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le petit-fils soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le petit-fils connaît bien la situation, il peut donner un conseil utile.",
          "Si le petit-fils avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le petit-fils reste calme et disponible.",
          "Le petit-fils, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le petit-fils préparait le repas, les enfants rangeaient la table.",
          "Puisque le petit-fils travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le petit-fils aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le petit-fils progresse parce qu'il pratique le français chaque jour.",
          "Tant que le petit-fils restera motivé, il continuera à faire des progrès.",
          "Même si le petit-fils ne parle pas parfaitement, il ose poser des questions.",
          "Le petit-fils a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le petit-fils depuis plusieurs années.",
          "Bien que le petit-fils ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le petit-fils, nous lui demanderons de nous accompagner.",
          "Bien que le mot petit-fils paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le petit-fils apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le petit-fils, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà petit-fils, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le petit-fils.",
          "Lorsque j'aurai mémorisé petit-fils, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le petit-fils.",
          "Puisque petit-fils est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "petite-fille",
      article: "la",
      gender: "f",
      image: "petite-fille.webp",
      definition: ["Fille du fils ou de la fille."],
      definitionPivot: {
        en: "The daughter of your child.",
        ar: "ابنة ابنك أو ابنتك.",
        fa: "دخترِ فرزند شما.",
        pt: "A filha do seu filho ou da sua filha.",
        so: "Gabadha ilmahaaga.",
        ti: "ጓል ናይ ውላድካ።",
        tr: "Çocuğunuzun kızı.",
        ps: "ستاسو د اولاد لور.",
        uk: "Донька вашої дитини.",
      },
      synonym: ["petit-enfant"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la petite-fille a parlé avec le professeur.",
          "Demain, la petite-fille va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la petite-fille.",
          "Ce matin, la petite-fille a pris le bus.",
          "La petite-fille a préparé le repas hier soir.",
          "La petite-fille va aider les enfants demain.",
          "Avant, la petite-fille habitait dans une autre ville.",
          "La petite-fille a acheté du pain au magasin.",
          "Pendant les vacances, la petite-fille venait souvent nous voir.",
          "La petite-fille a oublié ses clés ce matin.",
          "Je vais appeler la petite-fille après le cours.",
          "La petite-fille a travaillé tard hier.",
          "Nous avons rencontré la petite-fille dans la rue.",
          "La petite-fille va organiser une sortie samedi.",
          "Quand il faisait froid, la petite-fille restait à la maison.",
          "La petite-fille a expliqué le problème calmement.",
          "Hier soir, la petite-fille a regardé un film.",
          "La petite-fille va chercher les enfants à l'école.",
          "Ce week-end, la petite-fille a rangé la cuisine.",
          "La petite-fille a appris une bonne nouvelle.",
          "Je pense que la petite-fille va arriver bientôt.",
          "La petite-fille a donné un conseil utile.",
          "Avant le repas, la petite-fille a mis la table.",
          "La petite-fille va partir en voyage demain.",
          "La petite-fille a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot petite-fille dans une phrase.",
          "Demain, je vais apprendre à mieux employer la petite-fille.",
          "Quand je lis le texte, je cherche le sens de petite-fille.",
          "Ce matin, nous avons associé la petite-fille à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec petite-fille.",
          "Le professeur a demandé un exemple avec la petite-fille.",
          "J'ai choisi la petite-fille parce que ce mot était dans la liste.",
          "Nous allons réviser la petite-fille avant l'évaluation.",
          "Mon camarade a expliqué la petite-fille avec ses mots.",
          "J'ai ajouté petite-fille dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la petite-fille soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la petite-fille connaît bien la situation, il peut donner un conseil utile.",
          "Si la petite-fille avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la petite-fille reste calme et disponible.",
          "La petite-fille, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la petite-fille préparait le repas, les enfants rangeaient la table.",
          "Puisque la petite-fille travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la petite-fille aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la petite-fille progresse parce qu'il pratique le français chaque jour.",
          "Tant que la petite-fille restera motivé, il continuera à faire des progrès.",
          "Même si la petite-fille ne parle pas parfaitement, il ose poser des questions.",
          "La petite-fille a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la petite-fille depuis plusieurs années.",
          "Bien que la petite-fille ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la petite-fille, nous lui demanderons de nous accompagner.",
          "Bien que le mot petite-fille paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la petite-fille apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la petite-fille, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà petite-fille, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la petite-fille.",
          "Lorsque j'aurai mémorisé petite-fille, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la petite-fille.",
          "Puisque petite-fille est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "oncle",
      article: "l'",
      gender: "m",
      image: "oncle.webp",
      definition: ["Frère du père ou de la mère."],
      definitionPivot: {
        en: "The brother of a parent.",
        ar: "أخ الأب أو الأم.",
        fa: "برادرِ پدر یا مادر.",
        pt: "O irmão do pai ou da mãe.",
        so: "Walaalka aabbaha ama hooyada.",
        ti: "ሓው ናይ ኣቦ ወይ ኣደ።",
        tr: "Anne veya babanın erkek kardeşi.",
        ps: "د پلار يا مور ورور.",
        uk: "Брат тата або мами.",
      },
      synonym: ["tonton"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, l'oncle a parlé avec le professeur.",
          "Demain, l'oncle va venir à la maison.",
          "Quand j'étais petit, je voyais souvent l'oncle.",
          "Ce matin, l'oncle a pris le bus.",
          "L'oncle a préparé le repas hier soir.",
          "L'oncle va aider les enfants demain.",
          "Avant, l'oncle habitait dans une autre ville.",
          "L'oncle a acheté du pain au magasin.",
          "Pendant les vacances, l'oncle venait souvent nous voir.",
          "L'oncle a oublié ses clés ce matin.",
          "Je vais appeler l'oncle après le cours.",
          "L'oncle a travaillé tard hier.",
          "Nous avons rencontré l'oncle dans la rue.",
          "L'oncle va organiser une sortie samedi.",
          "Quand il faisait froid, l'oncle restait à la maison.",
          "L'oncle a expliqué le problème calmement.",
          "Hier soir, l'oncle a regardé un film.",
          "L'oncle va chercher les enfants à l'école.",
          "Ce week-end, l'oncle a rangé la cuisine.",
          "L'oncle a appris une bonne nouvelle.",
          "Je pense que l'oncle va arriver bientôt.",
          "L'oncle a donné un conseil utile.",
          "Avant le repas, l'oncle a mis la table.",
          "L'oncle va partir en voyage demain.",
          "L'oncle a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot oncle dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'oncle.",
          "Quand je lis le texte, je cherche le sens de oncle.",
          "Ce matin, nous avons associé l'oncle à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec oncle.",
          "Le professeur a demandé un exemple avec l'oncle.",
          "J'ai choisi l'oncle parce que ce mot était dans la liste.",
          "Nous allons réviser l'oncle avant l'évaluation.",
          "Mon camarade a expliqué l'oncle avec ses mots.",
          "J'ai ajouté oncle dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'oncle soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme l'oncle connaît bien la situation, il peut donner un conseil utile.",
          "Si l'oncle avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, l'oncle reste calme et disponible.",
          "L'oncle, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que l'oncle préparait le repas, les enfants rangeaient la table.",
          "Puisque l'oncle travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque l'oncle aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que l'oncle progresse parce qu'il pratique le français chaque jour.",
          "Tant que l'oncle restera motivé, il continuera à faire des progrès.",
          "Même si l'oncle ne parle pas parfaitement, il ose poser des questions.",
          "L'oncle a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît l'oncle depuis plusieurs années.",
          "Bien que l'oncle ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons l'oncle, nous lui demanderons de nous accompagner.",
          "Bien que le mot oncle paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'oncle apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'oncle, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà oncle, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'oncle.",
          "Lorsque j'aurai mémorisé oncle, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'oncle.",
          "Puisque oncle est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "tante",
      article: "la",
      gender: "f",
      image: "tante.webp",
      definition: ["Sœur du père ou de la mère."],
      definitionPivot: {
        en: "The sister of a parent.",
        ar: "أخت الأب أو الأم.",
        fa: "خواهرِ پدر یا مادر.",
        pt: "A irmã do pai ou da mãe.",
        so: "Walaasha aabbaha ama hooyada.",
        ti: "ሓብቲ ናይ ኣቦ ወይ ኣደ።",
        tr: "Anne veya babanın kız kardeşi.",
        ps: "د پلار يا مور خور.",
        uk: "Сестра тата або мами.",
      },
      synonym: ["tata"],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la tante a parlé avec le professeur.",
          "Demain, la tante va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la tante.",
          "Ce matin, la tante a pris le bus.",
          "La tante a préparé le repas hier soir.",
          "La tante va aider les enfants demain.",
          "Avant, la tante habitait dans une autre ville.",
          "La tante a acheté du pain au magasin.",
          "Pendant les vacances, la tante venait souvent nous voir.",
          "La tante a oublié ses clés ce matin.",
          "Je vais appeler la tante après le cours.",
          "La tante a travaillé tard hier.",
          "Nous avons rencontré la tante dans la rue.",
          "La tante va organiser une sortie samedi.",
          "Quand il faisait froid, la tante restait à la maison.",
          "La tante a expliqué le problème calmement.",
          "Hier soir, la tante a regardé un film.",
          "La tante va chercher les enfants à l'école.",
          "Ce week-end, la tante a rangé la cuisine.",
          "La tante a appris une bonne nouvelle.",
          "Je pense que la tante va arriver bientôt.",
          "La tante a donné un conseil utile.",
          "Avant le repas, la tante a mis la table.",
          "La tante va partir en voyage demain.",
          "La tante a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot tante dans une phrase.",
          "Demain, je vais apprendre à mieux employer la tante.",
          "Quand je lis le texte, je cherche le sens de tante.",
          "Ce matin, nous avons associé la tante à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec tante.",
          "Le professeur a demandé un exemple avec la tante.",
          "J'ai choisi la tante parce que ce mot était dans la liste.",
          "Nous allons réviser la tante avant l'évaluation.",
          "Mon camarade a expliqué la tante avec ses mots.",
          "J'ai ajouté tante dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la tante soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la tante connaît bien la situation, il peut donner un conseil utile.",
          "Si la tante avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la tante reste calme et disponible.",
          "La tante, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la tante préparait le repas, les enfants rangeaient la table.",
          "Puisque la tante travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la tante aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la tante progresse parce qu'il pratique le français chaque jour.",
          "Tant que la tante restera motivé, il continuera à faire des progrès.",
          "Même si la tante ne parle pas parfaitement, il ose poser des questions.",
          "La tante a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la tante depuis plusieurs années.",
          "Bien que la tante ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la tante, nous lui demanderons de nous accompagner.",
          "Bien que le mot tante paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la tante apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la tante, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà tante, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la tante.",
          "Lorsque j'aurai mémorisé tante, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la tante.",
          "Puisque tante est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cousin",
      article: "le",
      gender: "m",
      image: "cousin.webp",
      definition: ["Fils de l’oncle ou de la tante."],
      definitionPivot: {
        en: "The son of an uncle or aunt.",
        ar: "ابن العم أو الخال أو العمة أو الخالة.",
        fa: "پسرِ عمو، دایی، عمه یا خاله.",
        pt: "O filho de um tio ou de uma tia.",
        so: "Wiilka adeer, abti ama eeddo.",
        ti: "ወዲ ናይ ሓው/ሓብቲ ወላዲ።",
        tr: "Amca, dayı, hala veya teyzenin oğlu.",
        ps: "د تره، ماما، عمه يا خاله زوی.",
        uk: "Син дядька або тітки.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le cousin a parlé avec le professeur.",
          "Demain, le cousin va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le cousin.",
          "Ce matin, le cousin a pris le bus.",
          "Le cousin a préparé le repas hier soir.",
          "Le cousin va aider les enfants demain.",
          "Avant, le cousin habitait dans une autre ville.",
          "Le cousin a acheté du pain au magasin.",
          "Pendant les vacances, le cousin venait souvent nous voir.",
          "Le cousin a oublié ses clés ce matin.",
          "Je vais appeler le cousin après le cours.",
          "Le cousin a travaillé tard hier.",
          "Nous avons rencontré le cousin dans la rue.",
          "Le cousin va organiser une sortie samedi.",
          "Quand il faisait froid, le cousin restait à la maison.",
          "Le cousin a expliqué le problème calmement.",
          "Hier soir, le cousin a regardé un film.",
          "Le cousin va chercher les enfants à l'école.",
          "Ce week-end, le cousin a rangé la cuisine.",
          "Le cousin a appris une bonne nouvelle.",
          "Je pense que le cousin va arriver bientôt.",
          "Le cousin a donné un conseil utile.",
          "Avant le repas, le cousin a mis la table.",
          "Le cousin va partir en voyage demain.",
          "Le cousin a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot cousin dans une phrase.",
          "Demain, je vais apprendre à mieux employer le cousin.",
          "Quand je lis le texte, je cherche le sens de cousin.",
          "Ce matin, nous avons associé le cousin à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec cousin.",
          "Le professeur a demandé un exemple avec le cousin.",
          "J'ai choisi le cousin parce que ce mot était dans la liste.",
          "Nous allons réviser le cousin avant l'évaluation.",
          "Mon camarade a expliqué le cousin avec ses mots.",
          "J'ai ajouté cousin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cousin soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le cousin connaît bien la situation, il peut donner un conseil utile.",
          "Si le cousin avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le cousin reste calme et disponible.",
          "Le cousin, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le cousin préparait le repas, les enfants rangeaient la table.",
          "Puisque le cousin travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le cousin aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le cousin progresse parce qu'il pratique le français chaque jour.",
          "Tant que le cousin restera motivé, il continuera à faire des progrès.",
          "Même si le cousin ne parle pas parfaitement, il ose poser des questions.",
          "Le cousin a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le cousin depuis plusieurs années.",
          "Bien que le cousin ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le cousin, nous lui demanderons de nous accompagner.",
          "Bien que le mot cousin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le cousin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le cousin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cousin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le cousin.",
          "Lorsque j'aurai mémorisé cousin, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le cousin.",
          "Puisque cousin est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cousine",
      article: "la",
      gender: "f",
      image: "cousine.webp",
      definition: ["Fille de l’oncle ou de la tante."],
      definitionPivot: {
        en: "The daughter of an uncle or aunt.",
        ar: "ابنة العم أو الخال أو العمة أو الخالة.",
        fa: "دخترِ عمو، دایی، عمه یا خاله.",
        pt: "A filha de um tio ou de uma tia.",
        so: "Gabadha adeer, abti ama eeddo.",
        ti: "ጓል ናይ ሓው/ሓብቲ ወላዲ።",
        tr: "Amca, dayı, hala veya teyzenin kızı.",
        ps: "د تره، ماما، عمه يا خاله لور.",
        uk: "Донька дядька або тітки.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la cousine a parlé avec le professeur.",
          "Demain, la cousine va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la cousine.",
          "Ce matin, la cousine a pris le bus.",
          "La cousine a préparé le repas hier soir.",
          "La cousine va aider les enfants demain.",
          "Avant, la cousine habitait dans une autre ville.",
          "La cousine a acheté du pain au magasin.",
          "Pendant les vacances, la cousine venait souvent nous voir.",
          "La cousine a oublié ses clés ce matin.",
          "Je vais appeler la cousine après le cours.",
          "La cousine a travaillé tard hier.",
          "Nous avons rencontré la cousine dans la rue.",
          "La cousine va organiser une sortie samedi.",
          "Quand il faisait froid, la cousine restait à la maison.",
          "La cousine a expliqué le problème calmement.",
          "Hier soir, la cousine a regardé un film.",
          "La cousine va chercher les enfants à l'école.",
          "Ce week-end, la cousine a rangé la cuisine.",
          "La cousine a appris une bonne nouvelle.",
          "Je pense que la cousine va arriver bientôt.",
          "La cousine a donné un conseil utile.",
          "Avant le repas, la cousine a mis la table.",
          "La cousine va partir en voyage demain.",
          "La cousine a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot cousine dans une phrase.",
          "Demain, je vais apprendre à mieux employer la cousine.",
          "Quand je lis le texte, je cherche le sens de cousine.",
          "Ce matin, nous avons associé la cousine à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec cousine.",
          "Le professeur a demandé un exemple avec la cousine.",
          "J'ai choisi la cousine parce que ce mot était dans la liste.",
          "Nous allons réviser la cousine avant l'évaluation.",
          "Mon camarade a expliqué la cousine avec ses mots.",
          "J'ai ajouté cousine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la cousine soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la cousine connaît bien la situation, il peut donner un conseil utile.",
          "Si la cousine avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la cousine reste calme et disponible.",
          "La cousine, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la cousine préparait le repas, les enfants rangeaient la table.",
          "Puisque la cousine travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la cousine aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la cousine progresse parce qu'il pratique le français chaque jour.",
          "Tant que la cousine restera motivé, il continuera à faire des progrès.",
          "Même si la cousine ne parle pas parfaitement, il ose poser des questions.",
          "La cousine a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la cousine depuis plusieurs années.",
          "Bien que la cousine ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la cousine, nous lui demanderons de nous accompagner.",
          "Bien que le mot cousine paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la cousine apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la cousine, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cousine, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la cousine.",
          "Lorsque j'aurai mémorisé cousine, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la cousine.",
          "Puisque cousine est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "neveu",
      article: "le",
      gender: "m",
      image: "neveu.webp",
      definition: ["Fils du frère ou de la sœur."],
      definitionPivot: {
        en: "The son of a brother or sister.",
        ar: "ابن الأخ أو الأخت.",
        fa: "پسرِ برادر یا خواهر.",
        pt: "O filho de um irmão ou de uma irmã.",
        so: "Wiilka walaalkaa ama walaashaa.",
        ti: "ወዲ ናይ ሓውካ ወይ ሓብትኻ።",
        tr: "Erkek veya kız kardeşin oğlu.",
        ps: "د ورور يا خور زوی.",
        uk: "Син брата або сестри.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, le neveu a parlé avec le professeur.",
          "Demain, le neveu va venir à la maison.",
          "Quand j'étais petit, je voyais souvent le neveu.",
          "Ce matin, le neveu a pris le bus.",
          "Le neveu a préparé le repas hier soir.",
          "Le neveu va aider les enfants demain.",
          "Avant, le neveu habitait dans une autre ville.",
          "Le neveu a acheté du pain au magasin.",
          "Pendant les vacances, le neveu venait souvent nous voir.",
          "Le neveu a oublié ses clés ce matin.",
          "Je vais appeler le neveu après le cours.",
          "Le neveu a travaillé tard hier.",
          "Nous avons rencontré le neveu dans la rue.",
          "Le neveu va organiser une sortie samedi.",
          "Quand il faisait froid, le neveu restait à la maison.",
          "Le neveu a expliqué le problème calmement.",
          "Hier soir, le neveu a regardé un film.",
          "Le neveu va chercher les enfants à l'école.",
          "Ce week-end, le neveu a rangé la cuisine.",
          "Le neveu a appris une bonne nouvelle.",
          "Je pense que le neveu va arriver bientôt.",
          "Le neveu a donné un conseil utile.",
          "Avant le repas, le neveu a mis la table.",
          "Le neveu va partir en voyage demain.",
          "Le neveu a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot neveu dans une phrase.",
          "Demain, je vais apprendre à mieux employer le neveu.",
          "Quand je lis le texte, je cherche le sens de neveu.",
          "Ce matin, nous avons associé le neveu à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec neveu.",
          "Le professeur a demandé un exemple avec le neveu.",
          "J'ai choisi le neveu parce que ce mot était dans la liste.",
          "Nous allons réviser le neveu avant l'évaluation.",
          "Mon camarade a expliqué le neveu avec ses mots.",
          "J'ai ajouté neveu dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le neveu soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme le neveu connaît bien la situation, il peut donner un conseil utile.",
          "Si le neveu avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, le neveu reste calme et disponible.",
          "Le neveu, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que le neveu préparait le repas, les enfants rangeaient la table.",
          "Puisque le neveu travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque le neveu aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que le neveu progresse parce qu'il pratique le français chaque jour.",
          "Tant que le neveu restera motivé, il continuera à faire des progrès.",
          "Même si le neveu ne parle pas parfaitement, il ose poser des questions.",
          "Le neveu a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît le neveu depuis plusieurs années.",
          "Bien que le neveu ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons le neveu, nous lui demanderons de nous accompagner.",
          "Bien que le mot neveu paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le neveu apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le neveu, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà neveu, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le neveu.",
          "Lorsque j'aurai mémorisé neveu, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le neveu.",
          "Puisque neveu est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "nièce",
      article: "la",
      gender: "f",
      image: "niece.webp",
      definition: ["Fille du frère ou de la sœur."],
      definitionPivot: {
        en: "The daughter of a brother or sister.",
        ar: "ابنة الأخ أو الأخت.",
        fa: "دخترِ برادر یا خواهر.",
        pt: "A filha de um irmão ou de uma irmã.",
        so: "Gabadha walaalkaa ama walaashaa.",
        ti: "ጓል ናይ ሓውካ ወይ ሓብትኻ።",
        tr: "Erkek veya kız kardeşin kızı.",
        ps: "د ورور يا خور لور.",
        uk: "Донька брата або сестри.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, la nièce a parlé avec le professeur.",
          "Demain, la nièce va venir à la maison.",
          "Quand j'étais petit, je voyais souvent la nièce.",
          "Ce matin, la nièce a pris le bus.",
          "La nièce a préparé le repas hier soir.",
          "La nièce va aider les enfants demain.",
          "Avant, la nièce habitait dans une autre ville.",
          "La nièce a acheté du pain au magasin.",
          "Pendant les vacances, la nièce venait souvent nous voir.",
          "La nièce a oublié ses clés ce matin.",
          "Je vais appeler la nièce après le cours.",
          "La nièce a travaillé tard hier.",
          "Nous avons rencontré la nièce dans la rue.",
          "La nièce va organiser une sortie samedi.",
          "Quand il faisait froid, la nièce restait à la maison.",
          "La nièce a expliqué le problème calmement.",
          "Hier soir, la nièce a regardé un film.",
          "La nièce va chercher les enfants à l'école.",
          "Ce week-end, la nièce a rangé la cuisine.",
          "La nièce a appris une bonne nouvelle.",
          "Je pense que la nièce va arriver bientôt.",
          "La nièce a donné un conseil utile.",
          "Avant le repas, la nièce a mis la table.",
          "La nièce va partir en voyage demain.",
          "La nièce a fini son travail à l'heure.",
          "Après la leçon, j'ai utilisé le mot nièce dans une phrase.",
          "Demain, je vais apprendre à mieux employer la nièce.",
          "Quand je lis le texte, je cherche le sens de nièce.",
          "Ce matin, nous avons associé la nièce à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec nièce.",
          "Le professeur a demandé un exemple avec la nièce.",
          "J'ai choisi la nièce parce que ce mot était dans la liste.",
          "Nous allons réviser la nièce avant l'évaluation.",
          "Mon camarade a expliqué la nièce avec ses mots.",
          "J'ai ajouté nièce dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la nièce soit occupé, il trouve toujours le temps d'aider les autres.",
          "Comme la nièce connaît bien la situation, il peut donner un conseil utile.",
          "Si la nièce avait plus de temps, il participerait davantage aux activités.",
          "Même quand la journée est difficile, la nièce reste calme et disponible.",
          "La nièce, que nous avons rencontré hier, nous a expliqué la situation.",
          "Pendant que la nièce préparait le repas, les enfants rangeaient la table.",
          "Puisque la nièce travaille beaucoup, il préfère se reposer le soir.",
          "Lorsque la nièce aura terminé son travail, il viendra nous rejoindre.",
          "Je pense que la nièce progresse parce qu'il pratique le français chaque jour.",
          "Tant que la nièce restera motivé, il continuera à faire des progrès.",
          "Même si la nièce ne parle pas parfaitement, il ose poser des questions.",
          "La nièce a expliqué qu'il voulait mieux comprendre les consignes.",
          "Le voisin dont je parle connaît la nièce depuis plusieurs années.",
          "Bien que la nièce ait changé de ville, il garde contact avec ses amis.",
          "Si nous revoyons la nièce, nous lui demanderons de nous accompagner.",
          "Bien que le mot nièce paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la nièce apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la nièce, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà nièce, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la nièce.",
          "Lorsque j'aurai mémorisé nièce, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la nièce.",
          "Puisque nièce est utile, je le révise régulièrement.",
        ],
      },
    },
  ],
  sentences: [
    { sentence: "Mon ___ travaille dur pour notre famille.", answer: "père" },
    { sentence: "Mon ___ rentre à la maison le soir.", answer: "père" },
    { sentence: "Le ___ de mon ami est médecin.", answer: "père" },
    { sentence: "Mon ___ m'apprend à conduire.", answer: "père" },
    { sentence: "Mon ___ et moi regardons le football ensemble.", answer: "père" },
    { sentence: "Le ___ de Lucas est très grand.", answer: "père" },
    { sentence: "Ma ___ me prépare de bons repas.", answer: "mère" },
    { sentence: "Ma ___ travaille à l'hôpital.", answer: "mère" },
    { sentence: "La ___ de Marie est professeure.", answer: "mère" },
    { sentence: "Ma ___ m'aide toujours quand j'ai des problèmes.", answer: "mère" },
    { sentence: "Ma ___ prépare le dîner tous les soirs.", answer: "mère" },
    { sentence: "La ___ de mon ami est très sympa.", answer: "mère" },
    { sentence: "Le ___ de ma sœur s'appelle Thomas.", answer: "fils" },
    { sentence: "Leur ___ a cinq ans.", answer: "fils" },
    { sentence: "Le ___ aîné part à l'université.", answer: "fils" },
    { sentence: "Il a un ___ qui joue au football.", answer: "fils" },
    { sentence: "Son ___ lui ressemble beaucoup.", answer: "fils" },
    { sentence: "Leur ___ a les yeux bleus.", answer: "fils" },
    { sentence: "Ma ___ est plus jeune que moi d'un an.", answer: "fille" },
    { sentence: "Leur ___ fait de la danse.", answer: "fille" },
    { sentence: "La ___ de mes voisins chante très bien.", answer: "fille" },
    { sentence: "Sa ___ a obtenu son diplôme cette année.", answer: "fille" },
    { sentence: "Leur ___ a les cheveux longs.", answer: "fille" },
    { sentence: "Mon ___ et moi allons à la même école.", answer: "frère" },
    { sentence: "Mon ___ est plus grand que moi.", answer: "frère" },
    { sentence: "Le ___ de Paul joue de la guitare.", answer: "frère" },
    { sentence: "Mon ___ m'aide toujours avec mes devoirs.", answer: "frère" },
    { sentence: "Son ___ habite à Paris.", answer: "frère" },
    { sentence: "Mon ___ est né deux ans après moi.", answer: "frère" },
    { sentence: "Ma ___ est très gentille.", answer: "sœur" },
    { sentence: "La ___ de Léa est médecin.", answer: "sœur" },
    { sentence: "Ma ___ me prête ses vêtements.", answer: "sœur" },
    { sentence: "Ma ___ chante dans une chorale.", answer: "sœur" },
    { sentence: "Sa ___ vit en Espagne.", answer: "sœur" },
    { sentence: "Mon ___ est le père de mon père.", answer: "grand-père" },
    { sentence: "Mon ___ aime raconter des histoires.", answer: "grand-père" },
    { sentence: "Mon ___ a quatre-vingts ans.", answer: "grand-père" },
    { sentence: "Le ___ de Lucie est très actif.", answer: "grand-père" },
    { sentence: "Mon ___ m'emmène à la pêche le dimanche.", answer: "grand-père" },
    { sentence: "Mon ___ a travaillé toute sa vie.", answer: "grand-père" },
    { sentence: "Ma ___ fait de bons gâteaux.", answer: "grand-mère" },
    { sentence: "La ___ de Pierre est encore très active.", answer: "grand-mère" },
    { sentence: "Ma ___ me tricote des pulls chaque hiver.", answer: "grand-mère" },
    { sentence: "Ma ___ habite à la campagne.", answer: "grand-mère" },
    { sentence: "La ___ de Clara a soixante-quinze ans.", answer: "grand-mère" },
    { sentence: "Mon ___ est le fils de mon fils.", answer: "petit-fils" },
    { sentence: "Leur ___ a deux ans.", answer: "petit-fils" },
    { sentence: "Son ___ lui ressemble beaucoup.", answer: "petit-fils" },
    { sentence: "Le ___ de la voisine est adorable.", answer: "petit-fils" },
    { sentence: "Leur ___ vient les voir chaque week-end.", answer: "petit-fils" },
    { sentence: "Ma ___ est la fille de ma fille.", answer: "petite-fille" },
    { sentence: "Leur ___ a trois ans.", answer: "petite-fille" },
    { sentence: "La ___ de Monsieur Dupont fait ses premiers pas.", answer: "petite-fille" },
    { sentence: "Sa ___ lui ressemble beaucoup.", answer: "petite-fille" },
    { sentence: "Leur ___ vient les voir tous les dimanches.", answer: "petite-fille" },
    { sentence: "Mon ___ est le frère de mon père.", answer: "oncle" },
    { sentence: "Mon ___ habite à Lyon.", answer: "oncle" },
    { sentence: "Son ___ lui offre toujours de beaux cadeaux.", answer: "oncle" },
    { sentence: "L'___ de Léa est très drôle.", answer: "oncle" },
    { sentence: "Mon ___ est ingénieur.", answer: "oncle" },
    { sentence: "Ma ___ est la sœur de ma mère.", answer: "tante" },
    { sentence: "Ma ___ m'invite souvent à dîner.", answer: "tante" },
    { sentence: "La ___ de Paul vit en Italie.", answer: "tante" },
    { sentence: "Ma ___ me donne toujours de bons conseils.", answer: "tante" },
    { sentence: "Son ___ est arrivée hier.", answer: "tante" },
    { sentence: "Mon ___ joue avec moi depuis notre enfance.", answer: "cousin" },
    { sentence: "Mon ___ est le fils de mon oncle.", answer: "cousin" },
    { sentence: "Mon ___ habite dans la même ville que moi.", answer: "cousin" },
    { sentence: "Le ___ de Marie a obtenu son permis de conduire.", answer: "cousin" },
    { sentence: "Mon ___ et moi nous voyons chaque été.", answer: "cousin" },
    { sentence: "Ma ___ est la fille de ma tante.", answer: "cousine" },
    { sentence: "La ___ de Max est très grande maintenant.", answer: "cousine" },
    { sentence: "Ma ___ m'a appelée hier soir.", answer: "cousine" },
    { sentence: "Sa ___ vit en Belgique.", answer: "cousine" },
    { sentence: "Ma ___ et moi jouons ensemble depuis l'enfance.", answer: "cousine" },
    { sentence: "Mon ___ est le fils de mon frère.", answer: "neveu" },
    { sentence: "Mon ___ a trois ans et il est adorable.", answer: "neveu" },
    { sentence: "Son ___ vient la voir chaque dimanche.", answer: "neveu" },
    { sentence: "Le ___ de Julie est très espiègle.", answer: "neveu" },
    { sentence: "Mon ___ ressemble à son père.", answer: "neveu" },
    { sentence: "La ___ de mon frère a cinq ans.", answer: "nièce" },
    { sentence: "Ma ___ est la fille de ma sœur.", answer: "nièce" },
    { sentence: "Sa ___ vient lui rendre visite.", answer: "nièce" },
    { sentence: "La ___ de Paul adore les animaux.", answer: "nièce" },
    { sentence: "Ma ___ apprend à lire cette année.", answer: "nièce" },
  ],
};
