import type { VocabTheme } from "../../vocabulary-data";

export const V9_AEROPORT_THEME: VocabTheme = {
  slug: "v9-aeroport",
  code: "V9.6",
  title: "L'aéroport",
  section: "V9",
  words: [
    { word: "passeport", image: "passeport.webp",           article: "le",  gender: "m", definition: "Le passeport est un document officiel d'identité pour voyager." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le passeport sur le plan.",
          "Demain, je vais chercher le passeport.",
          "Quand je voyage, j'utilise souvent le passeport.",
          "Ce matin, le guide a montré le passeport.",
          "Nous avons demandé où se trouvait le passeport.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le passeport parce que c'était pratique.",
          "Elle a noté passeport dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du passeport.",
          "Le groupe a trouvé le passeport près de la gare.",
          "Je vais chercher le passeport après l'arrivée.",
          "Nous avons associé le passeport à une image.",
          "Hier soir, mon frère a vérifié le passeport sur internet.",
          "Pendant les vacances, nous utilisions souvent le passeport.",
          "Elle a oublié le mot passeport pendant l'exercice.",
          "Il va utiliser passeport dans sa phrase.",
          "Nous avons trouvé le passeport dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser passeport.",
          "L'élève a ajouté passeport dans sa réponse.",
          "J'ai compris le mot passeport pour la première fois.",
          "Ma sœur a choisi le passeport pour son exemple.",
          "Ils ont répété passeport à voix haute.",
          "Nous allons revoir le passeport avec le professeur.",
          "Elle a noté passeport pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le passeport.",
          "Après la leçon, j'ai utilisé le mot passeport dans une phrase.",
          "Demain, je vais apprendre à mieux employer le passeport.",
          "Quand je lis le texte, je cherche le sens de passeport.",
          "Ce matin, nous avons associé le passeport à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec passeport.",
          "Le professeur a demandé un exemple avec le passeport.",
          "J'ai choisi le passeport parce que ce mot était dans la liste.",
          "Nous allons réviser le passeport avant l'évaluation.",
          "Mon camarade a expliqué le passeport avec ses mots.",
          "J'ai ajouté passeport dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le passeport semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le passeport se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais passeport, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà passeport, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le passeport.",
          "La leçon que nous travaillons utilise passeport dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le passeport, les élèves prenaient des notes.",
          "Puisque le passeport aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé passeport, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le passeport aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, passeport peut donner une information précise.",
          "Le mot dont je parle est passeport, que la classe doit retenir.",
          "Tant que tu pratiqueras passeport, tu comprendras mieux les dialogues de voyage.",
          "Bien que le passeport demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient passeport, je penserai au vocabulaire du déplacement.",
          "Bien que le mot passeport paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le passeport apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le passeport, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà passeport, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le passeport.",
          "Lorsque j'aurai mémorisé passeport, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le passeport.",
          "Puisque passeport est utile, je le révise régulièrement.",
        ],
      } },
    { word: "visa", image: "visa.webp",                article: "le",  gender: "m", definition: "Le visa est autorisation officielle pour entrer dans un pays." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le visa sur le plan.",
          "Demain, je vais chercher le visa.",
          "Quand je voyage, j'utilise souvent le visa.",
          "Ce matin, le guide a montré le visa.",
          "Nous avons demandé où se trouvait le visa.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le visa parce que c'était pratique.",
          "Elle a noté visa dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du visa.",
          "Le groupe a trouvé le visa près de la gare.",
          "Je vais chercher le visa après l'arrivée.",
          "Nous avons associé le visa à une image.",
          "Hier soir, mon frère a vérifié le visa sur internet.",
          "Pendant les vacances, nous utilisions souvent le visa.",
          "Elle a oublié le mot visa pendant l'exercice.",
          "Il va utiliser visa dans sa phrase.",
          "Nous avons trouvé le visa dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser visa.",
          "L'élève a ajouté visa dans sa réponse.",
          "J'ai compris le mot visa pour la première fois.",
          "Ma sœur a choisi le visa pour son exemple.",
          "Ils ont répété visa à voix haute.",
          "Nous allons revoir le visa avec le professeur.",
          "Elle a noté visa pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le visa.",
          "Après la leçon, j'ai utilisé le mot visa dans une phrase.",
          "Demain, je vais apprendre à mieux employer le visa.",
          "Quand je lis le texte, je cherche le sens de visa.",
          "Ce matin, nous avons associé le visa à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec visa.",
          "Le professeur a demandé un exemple avec le visa.",
          "J'ai choisi le visa parce que ce mot était dans la liste.",
          "Nous allons réviser le visa avant l'évaluation.",
          "Mon camarade a expliqué le visa avec ses mots.",
          "J'ai ajouté visa dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le visa semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le visa se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais visa, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà visa, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le visa.",
          "La leçon que nous travaillons utilise visa dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le visa, les élèves prenaient des notes.",
          "Puisque le visa aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé visa, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le visa aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, visa peut donner une information précise.",
          "Le mot dont je parle est visa, que la classe doit retenir.",
          "Tant que tu pratiqueras visa, tu comprendras mieux les dialogues de voyage.",
          "Bien que le visa demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient visa, je penserai au vocabulaire du déplacement.",
          "Bien que le mot visa paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le visa apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le visa, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà visa, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le visa.",
          "Lorsque j'aurai mémorisé visa, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le visa.",
          "Puisque visa est utile, je le révise régulièrement.",
        ],
      } },
    { word: "vol", image: "vol.webp",                 article: "le",  gender: "m", definition: "Le vol est trajet en avion." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le vol sur le plan.",
          "Demain, je vais chercher le vol.",
          "Quand je voyage, j'utilise souvent le vol.",
          "Ce matin, le guide a montré le vol.",
          "Nous avons demandé où se trouvait le vol.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le vol parce que c'était pratique.",
          "Elle a noté vol dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du vol.",
          "Le groupe a trouvé le vol près de la gare.",
          "Je vais chercher le vol après l'arrivée.",
          "Nous avons associé le vol à une image.",
          "Hier soir, mon frère a vérifié le vol sur internet.",
          "Pendant les vacances, nous utilisions souvent le vol.",
          "Elle a oublié le mot vol pendant l'exercice.",
          "Il va utiliser vol dans sa phrase.",
          "Nous avons trouvé le vol dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser vol.",
          "L'élève a ajouté vol dans sa réponse.",
          "J'ai compris le mot vol pour la première fois.",
          "Ma sœur a choisi le vol pour son exemple.",
          "Ils ont répété vol à voix haute.",
          "Nous allons revoir le vol avec le professeur.",
          "Elle a noté vol pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le vol.",
          "Après la leçon, j'ai utilisé le mot vol dans une phrase.",
          "Demain, je vais apprendre à mieux employer le vol.",
          "Quand je lis le texte, je cherche le sens de vol.",
          "Ce matin, nous avons associé le vol à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec vol.",
          "Le professeur a demandé un exemple avec le vol.",
          "J'ai choisi le vol parce que ce mot était dans la liste.",
          "Nous allons réviser le vol avant l'évaluation.",
          "Mon camarade a expliqué le vol avec ses mots.",
          "J'ai ajouté vol dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le vol semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le vol se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais vol, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà vol, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le vol.",
          "La leçon que nous travaillons utilise vol dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le vol, les élèves prenaient des notes.",
          "Puisque le vol aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé vol, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le vol aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, vol peut donner une information précise.",
          "Le mot dont je parle est vol, que la classe doit retenir.",
          "Tant que tu pratiqueras vol, tu comprendras mieux les dialogues de voyage.",
          "Bien que le vol demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient vol, je penserai au vocabulaire du déplacement.",
          "Bien que le mot vol paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le vol apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le vol, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà vol, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le vol.",
          "Lorsque j'aurai mémorisé vol, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le vol.",
          "Puisque vol est utile, je le révise régulièrement.",
        ],
      } },
    { word: "destination", image: "destination.webp",         article: "la",  gender: "f", definition: "La destination est un lieu où l'on se rend." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la destination sur le plan.",
          "Demain, je vais chercher la destination.",
          "Quand je voyage, j'utilise souvent la destination.",
          "Ce matin, le guide a montré la destination.",
          "Nous avons demandé où se trouvait la destination.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la destination parce que c'était pratique.",
          "Elle a noté destination dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la destination.",
          "Le groupe a trouvé la destination près de la gare.",
          "Je vais chercher la destination après l'arrivée.",
          "Nous avons associé la destination à une image.",
          "Hier soir, mon frère a vérifié la destination sur internet.",
          "Pendant les vacances, nous utilisions souvent la destination.",
          "Elle a oublié le mot destination pendant l'exercice.",
          "Il va utiliser destination dans sa phrase.",
          "Nous avons trouvé la destination dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser destination.",
          "L'élève a ajouté destination dans sa réponse.",
          "J'ai compris le mot destination pour la première fois.",
          "Ma sœur a choisi la destination pour son exemple.",
          "Ils ont répété destination à voix haute.",
          "Nous allons revoir la destination avec le professeur.",
          "Elle a noté destination pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la destination.",
          "Après la leçon, j'ai utilisé le mot destination dans une phrase.",
          "Demain, je vais apprendre à mieux employer la destination.",
          "Quand je lis le texte, je cherche le sens de destination.",
          "Ce matin, nous avons associé la destination à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec destination.",
          "Le professeur a demandé un exemple avec la destination.",
          "J'ai choisi la destination parce que ce mot était dans la liste.",
          "Nous allons réviser la destination avant l'évaluation.",
          "Mon camarade a expliqué la destination avec ses mots.",
          "J'ai ajouté destination dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la destination semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la destination se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais destination, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà destination, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la destination.",
          "La leçon que nous travaillons utilise destination dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la destination, les élèves prenaient des notes.",
          "Puisque la destination aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé destination, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la destination aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, destination peut donner une information précise.",
          "Le mot dont je parle est destination, que la classe doit retenir.",
          "Tant que tu pratiqueras destination, tu comprendras mieux les dialogues de voyage.",
          "Bien que la destination demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient destination, je penserai au vocabulaire du déplacement.",
          "Bien que le mot destination paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la destination apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la destination, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà destination, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la destination.",
          "Lorsque j'aurai mémorisé destination, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la destination.",
          "Puisque destination est utile, je le révise régulièrement.",
        ],
      } },
    { word: "avion", image: "avion.webp",               article: "l'",  gender: "m", definition: "L'avion est un véhicule aérien." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'avion sur le plan.",
          "Demain, je vais chercher l'avion.",
          "Quand je voyage, j'utilise souvent l'avion.",
          "Ce matin, le guide a montré l'avion.",
          "Nous avons demandé où se trouvait l'avion.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'avion parce que c'était pratique.",
          "Elle a noté avion dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'avion.",
          "Le groupe a trouvé l'avion près de la gare.",
          "Je vais chercher l'avion après l'arrivée.",
          "Nous avons associé l'avion à une image.",
          "Hier soir, mon frère a vérifié l'avion sur internet.",
          "Pendant les vacances, nous utilisions souvent l'avion.",
          "Elle a oublié le mot avion pendant l'exercice.",
          "Il va utiliser avion dans sa phrase.",
          "Nous avons trouvé l'avion dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser avion.",
          "L'élève a ajouté avion dans sa réponse.",
          "J'ai compris le mot avion pour la première fois.",
          "Ma sœur a choisi l'avion pour son exemple.",
          "Ils ont répété avion à voix haute.",
          "Nous allons revoir l'avion avec le professeur.",
          "Elle a noté avion pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'avion.",
          "Après la leçon, j'ai utilisé le mot avion dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'avion.",
          "Quand je lis le texte, je cherche le sens de avion.",
          "Ce matin, nous avons associé l'avion à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec avion.",
          "Le professeur a demandé un exemple avec l'avion.",
          "J'ai choisi l'avion parce que ce mot était dans la liste.",
          "Nous allons réviser l'avion avant l'évaluation.",
          "Mon camarade a expliqué l'avion avec ses mots.",
          "J'ai ajouté avion dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'avion semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'avion se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais avion, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà avion, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'avion.",
          "La leçon que nous travaillons utilise avion dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'avion, les élèves prenaient des notes.",
          "Puisque l'avion aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé avion, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'avion aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, avion peut donner une information précise.",
          "Le mot dont je parle est avion, que la classe doit retenir.",
          "Tant que tu pratiqueras avion, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'avion demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient avion, je penserai au vocabulaire du déplacement.",
          "Bien que le mot avion paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'avion apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'avion, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà avion, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'avion.",
          "Lorsque j'aurai mémorisé avion, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'avion.",
          "Puisque avion est utile, je le révise régulièrement.",
        ],
      } },
    { word: "escale", image: "escale.webp",              article: "l'",  gender: "f", definition: "L'escale est arrêt intermédiaire lors d'un vol." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'escale sur le plan.",
          "Demain, je vais chercher l'escale.",
          "Quand je voyage, j'utilise souvent l'escale.",
          "Ce matin, le guide a montré l'escale.",
          "Nous avons demandé où se trouvait l'escale.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'escale parce que c'était pratique.",
          "Elle a noté escale dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'escale.",
          "Le groupe a trouvé l'escale près de la gare.",
          "Je vais chercher l'escale après l'arrivée.",
          "Nous avons associé l'escale à une image.",
          "Hier soir, mon frère a vérifié l'escale sur internet.",
          "Pendant les vacances, nous utilisions souvent l'escale.",
          "Elle a oublié le mot escale pendant l'exercice.",
          "Il va utiliser escale dans sa phrase.",
          "Nous avons trouvé l'escale dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser escale.",
          "L'élève a ajouté escale dans sa réponse.",
          "J'ai compris le mot escale pour la première fois.",
          "Ma sœur a choisi l'escale pour son exemple.",
          "Ils ont répété escale à voix haute.",
          "Nous allons revoir l'escale avec le professeur.",
          "Elle a noté escale pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'escale.",
          "Après la leçon, j'ai utilisé le mot escale dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'escale.",
          "Quand je lis le texte, je cherche le sens de escale.",
          "Ce matin, nous avons associé l'escale à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec escale.",
          "Le professeur a demandé un exemple avec l'escale.",
          "J'ai choisi l'escale parce que ce mot était dans la liste.",
          "Nous allons réviser l'escale avant l'évaluation.",
          "Mon camarade a expliqué l'escale avec ses mots.",
          "J'ai ajouté escale dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'escale semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'escale se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais escale, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà escale, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'escale.",
          "La leçon que nous travaillons utilise escale dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'escale, les élèves prenaient des notes.",
          "Puisque l'escale aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé escale, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'escale aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, escale peut donner une information précise.",
          "Le mot dont je parle est escale, que la classe doit retenir.",
          "Tant que tu pratiqueras escale, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'escale demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient escale, je penserai au vocabulaire du déplacement.",
          "Bien que le mot escale paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'escale apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'escale, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà escale, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'escale.",
          "Lorsque j'aurai mémorisé escale, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'escale.",
          "Puisque escale est utile, je le révise régulièrement.",
        ],
      } },
    { word: "valise", image: "valise.webp",              article: "la",  gender: "f", definition: "La valise est grand bagage pour les voyages." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la valise sur le plan.",
          "Demain, je vais chercher la valise.",
          "Quand je voyage, j'utilise souvent la valise.",
          "Ce matin, le guide a montré la valise.",
          "Nous avons demandé où se trouvait la valise.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la valise parce que c'était pratique.",
          "Elle a noté valise dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la valise.",
          "Le groupe a trouvé la valise près de la gare.",
          "Je vais chercher la valise après l'arrivée.",
          "Nous avons associé la valise à une image.",
          "Hier soir, mon frère a vérifié la valise sur internet.",
          "Pendant les vacances, nous utilisions souvent la valise.",
          "Elle a oublié le mot valise pendant l'exercice.",
          "Il va utiliser valise dans sa phrase.",
          "Nous avons trouvé la valise dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser valise.",
          "L'élève a ajouté valise dans sa réponse.",
          "J'ai compris le mot valise pour la première fois.",
          "Ma sœur a choisi la valise pour son exemple.",
          "Ils ont répété valise à voix haute.",
          "Nous allons revoir la valise avec le professeur.",
          "Elle a noté valise pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la valise.",
          "Après la leçon, j'ai utilisé le mot valise dans une phrase.",
          "Demain, je vais apprendre à mieux employer la valise.",
          "Quand je lis le texte, je cherche le sens de valise.",
          "Ce matin, nous avons associé la valise à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec valise.",
          "Le professeur a demandé un exemple avec la valise.",
          "J'ai choisi la valise parce que ce mot était dans la liste.",
          "Nous allons réviser la valise avant l'évaluation.",
          "Mon camarade a expliqué la valise avec ses mots.",
          "J'ai ajouté valise dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la valise semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la valise se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais valise, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà valise, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la valise.",
          "La leçon que nous travaillons utilise valise dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la valise, les élèves prenaient des notes.",
          "Puisque la valise aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé valise, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la valise aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, valise peut donner une information précise.",
          "Le mot dont je parle est valise, que la classe doit retenir.",
          "Tant que tu pratiqueras valise, tu comprendras mieux les dialogues de voyage.",
          "Bien que la valise demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient valise, je penserai au vocabulaire du déplacement.",
          "Bien que le mot valise paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la valise apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la valise, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà valise, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la valise.",
          "Lorsque j'aurai mémorisé valise, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la valise.",
          "Puisque valise est utile, je le révise régulièrement.",
        ],
      } },
    { word: "terminal", image: "terminal.webp",            article: "le",  gender: "m", definition: "Le terminal est un bâtiment principal d'un aéroport." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le terminal sur le plan.",
          "Demain, je vais chercher le terminal.",
          "Quand je voyage, j'utilise souvent le terminal.",
          "Ce matin, le guide a montré le terminal.",
          "Nous avons demandé où se trouvait le terminal.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le terminal parce que c'était pratique.",
          "Elle a noté terminal dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du terminal.",
          "Le groupe a trouvé le terminal près de la gare.",
          "Je vais chercher le terminal après l'arrivée.",
          "Nous avons associé le terminal à une image.",
          "Hier soir, mon frère a vérifié le terminal sur internet.",
          "Pendant les vacances, nous utilisions souvent le terminal.",
          "Elle a oublié le mot terminal pendant l'exercice.",
          "Il va utiliser terminal dans sa phrase.",
          "Nous avons trouvé le terminal dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser terminal.",
          "L'élève a ajouté terminal dans sa réponse.",
          "J'ai compris le mot terminal pour la première fois.",
          "Ma sœur a choisi le terminal pour son exemple.",
          "Ils ont répété terminal à voix haute.",
          "Nous allons revoir le terminal avec le professeur.",
          "Elle a noté terminal pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le terminal.",
          "Après la leçon, j'ai utilisé le mot terminal dans une phrase.",
          "Demain, je vais apprendre à mieux employer le terminal.",
          "Quand je lis le texte, je cherche le sens de terminal.",
          "Ce matin, nous avons associé le terminal à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec terminal.",
          "Le professeur a demandé un exemple avec le terminal.",
          "J'ai choisi le terminal parce que ce mot était dans la liste.",
          "Nous allons réviser le terminal avant l'évaluation.",
          "Mon camarade a expliqué le terminal avec ses mots.",
          "J'ai ajouté terminal dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le terminal semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le terminal se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais terminal, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà terminal, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le terminal.",
          "La leçon que nous travaillons utilise terminal dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le terminal, les élèves prenaient des notes.",
          "Puisque le terminal aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé terminal, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le terminal aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, terminal peut donner une information précise.",
          "Le mot dont je parle est terminal, que la classe doit retenir.",
          "Tant que tu pratiqueras terminal, tu comprendras mieux les dialogues de voyage.",
          "Bien que le terminal demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient terminal, je penserai au vocabulaire du déplacement.",
          "Bien que le mot terminal paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le terminal apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le terminal, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà terminal, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le terminal.",
          "Lorsque j'aurai mémorisé terminal, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le terminal.",
          "Puisque terminal est utile, je le révise régulièrement.",
        ],
      } },
    { word: "douane", image: "douane.webp",              article: "la",  gender: "f", definition: "La douane est contrôle des bagages à la frontière." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la douane sur le plan.",
          "Demain, je vais chercher la douane.",
          "Quand je voyage, j'utilise souvent la douane.",
          "Ce matin, le guide a montré la douane.",
          "Nous avons demandé où se trouvait la douane.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la douane parce que c'était pratique.",
          "Elle a noté douane dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la douane.",
          "Le groupe a trouvé la douane près de la gare.",
          "Je vais chercher la douane après l'arrivée.",
          "Nous avons associé la douane à une image.",
          "Hier soir, mon frère a vérifié la douane sur internet.",
          "Pendant les vacances, nous utilisions souvent la douane.",
          "Elle a oublié le mot douane pendant l'exercice.",
          "Il va utiliser douane dans sa phrase.",
          "Nous avons trouvé la douane dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser douane.",
          "L'élève a ajouté douane dans sa réponse.",
          "J'ai compris le mot douane pour la première fois.",
          "Ma sœur a choisi la douane pour son exemple.",
          "Ils ont répété douane à voix haute.",
          "Nous allons revoir la douane avec le professeur.",
          "Elle a noté douane pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la douane.",
          "Après la leçon, j'ai utilisé le mot douane dans une phrase.",
          "Demain, je vais apprendre à mieux employer la douane.",
          "Quand je lis le texte, je cherche le sens de douane.",
          "Ce matin, nous avons associé la douane à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec douane.",
          "Le professeur a demandé un exemple avec la douane.",
          "J'ai choisi la douane parce que ce mot était dans la liste.",
          "Nous allons réviser la douane avant l'évaluation.",
          "Mon camarade a expliqué la douane avec ses mots.",
          "J'ai ajouté douane dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la douane semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la douane se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais douane, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà douane, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la douane.",
          "La leçon que nous travaillons utilise douane dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la douane, les élèves prenaient des notes.",
          "Puisque la douane aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé douane, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la douane aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, douane peut donner une information précise.",
          "Le mot dont je parle est douane, que la classe doit retenir.",
          "Tant que tu pratiqueras douane, tu comprendras mieux les dialogues de voyage.",
          "Bien que la douane demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient douane, je penserai au vocabulaire du déplacement.",
          "Bien que le mot douane paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la douane apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la douane, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà douane, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la douane.",
          "Lorsque j'aurai mémorisé douane, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la douane.",
          "Puisque douane est utile, je le révise régulièrement.",
        ],
      } },
    { word: "enregistrement", image: "enregistrement.webp",      article: "l'",  gender: "m", definition: "L'enregistrement est démarche pour valider son billet avant de voler." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'enregistrement sur le plan.",
          "Demain, je vais chercher l'enregistrement.",
          "Quand je voyage, j'utilise souvent l'enregistrement.",
          "Ce matin, le guide a montré l'enregistrement.",
          "Nous avons demandé où se trouvait l'enregistrement.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'enregistrement parce que c'était pratique.",
          "Elle a noté enregistrement dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'enregistrement.",
          "Le groupe a trouvé l'enregistrement près de la gare.",
          "Je vais chercher l'enregistrement après l'arrivée.",
          "Nous avons associé l'enregistrement à une image.",
          "Hier soir, mon frère a vérifié l'enregistrement sur internet.",
          "Pendant les vacances, nous utilisions souvent l'enregistrement.",
          "Elle a oublié le mot enregistrement pendant l'exercice.",
          "Il va utiliser enregistrement dans sa phrase.",
          "Nous avons trouvé l'enregistrement dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser enregistrement.",
          "L'élève a ajouté enregistrement dans sa réponse.",
          "J'ai compris le mot enregistrement pour la première fois.",
          "Ma sœur a choisi l'enregistrement pour son exemple.",
          "Ils ont répété enregistrement à voix haute.",
          "Nous allons revoir l'enregistrement avec le professeur.",
          "Elle a noté enregistrement pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'enregistrement.",
          "Après la leçon, j'ai utilisé le mot enregistrement dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'enregistrement.",
          "Quand je lis le texte, je cherche le sens de enregistrement.",
          "Ce matin, nous avons associé l'enregistrement à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec enregistrement.",
          "Le professeur a demandé un exemple avec l'enregistrement.",
          "J'ai choisi l'enregistrement parce que ce mot était dans la liste.",
          "Nous allons réviser l'enregistrement avant l'évaluation.",
          "Mon camarade a expliqué l'enregistrement avec ses mots.",
          "J'ai ajouté enregistrement dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'enregistrement semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'enregistrement se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais enregistrement, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà enregistrement, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'enregistrement.",
          "La leçon que nous travaillons utilise enregistrement dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'enregistrement, les élèves prenaient des notes.",
          "Puisque l'enregistrement aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé enregistrement, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'enregistrement aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, enregistrement peut donner une information précise.",
          "Le mot dont je parle est enregistrement, que la classe doit retenir.",
          "Tant que tu pratiqueras enregistrement, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'enregistrement demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient enregistrement, je penserai au vocabulaire du déplacement.",
          "Bien que le mot enregistrement paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'enregistrement apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'enregistrement, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà enregistrement, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'enregistrement.",
          "Lorsque j'aurai mémorisé enregistrement, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'enregistrement.",
          "Puisque enregistrement est utile, je le révise régulièrement.",
        ],
      } },
    { word: "réservation", image: "reservation.webp",         article: "la",  gender: "f", definition: "La réservation est action de réserver un vol ou un siège." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la réservation sur le plan.",
          "Demain, je vais chercher la réservation.",
          "Quand je voyage, j'utilise souvent la réservation.",
          "Ce matin, le guide a montré la réservation.",
          "Nous avons demandé où se trouvait la réservation.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la réservation parce que c'était pratique.",
          "Elle a noté réservation dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la réservation.",
          "Le groupe a trouvé la réservation près de la gare.",
          "Je vais chercher la réservation après l'arrivée.",
          "Nous avons associé la réservation à une image.",
          "Hier soir, mon frère a vérifié la réservation sur internet.",
          "Pendant les vacances, nous utilisions souvent la réservation.",
          "Elle a oublié le mot réservation pendant l'exercice.",
          "Il va utiliser réservation dans sa phrase.",
          "Nous avons trouvé la réservation dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser réservation.",
          "L'élève a ajouté réservation dans sa réponse.",
          "J'ai compris le mot réservation pour la première fois.",
          "Ma sœur a choisi la réservation pour son exemple.",
          "Ils ont répété réservation à voix haute.",
          "Nous allons revoir la réservation avec le professeur.",
          "Elle a noté réservation pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la réservation.",
          "Après la leçon, j'ai utilisé le mot réservation dans une phrase.",
          "Demain, je vais apprendre à mieux employer la réservation.",
          "Quand je lis le texte, je cherche le sens de réservation.",
          "Ce matin, nous avons associé la réservation à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec réservation.",
          "Le professeur a demandé un exemple avec la réservation.",
          "J'ai choisi la réservation parce que ce mot était dans la liste.",
          "Nous allons réviser la réservation avant l'évaluation.",
          "Mon camarade a expliqué la réservation avec ses mots.",
          "J'ai ajouté réservation dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la réservation semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la réservation se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais réservation, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà réservation, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la réservation.",
          "La leçon que nous travaillons utilise réservation dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la réservation, les élèves prenaient des notes.",
          "Puisque la réservation aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé réservation, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la réservation aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, réservation peut donner une information précise.",
          "Le mot dont je parle est réservation, que la classe doit retenir.",
          "Tant que tu pratiqueras réservation, tu comprendras mieux les dialogues de voyage.",
          "Bien que la réservation demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient réservation, je penserai au vocabulaire du déplacement.",
          "Bien que le mot réservation paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la réservation apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la réservation, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà réservation, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la réservation.",
          "Lorsque j'aurai mémorisé réservation, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la réservation.",
          "Puisque réservation est utile, je le révise régulièrement.",
        ],
      } },
    { word: "embarquement", image: "embarquement.webp",        article: "l'",  gender: "m", definition: "L'embarquement est montée dans l'avion." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'embarquement sur le plan.",
          "Demain, je vais chercher l'embarquement.",
          "Quand je voyage, j'utilise souvent l'embarquement.",
          "Ce matin, le guide a montré l'embarquement.",
          "Nous avons demandé où se trouvait l'embarquement.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'embarquement parce que c'était pratique.",
          "Elle a noté embarquement dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'embarquement.",
          "Le groupe a trouvé l'embarquement près de la gare.",
          "Je vais chercher l'embarquement après l'arrivée.",
          "Nous avons associé l'embarquement à une image.",
          "Hier soir, mon frère a vérifié l'embarquement sur internet.",
          "Pendant les vacances, nous utilisions souvent l'embarquement.",
          "Elle a oublié le mot embarquement pendant l'exercice.",
          "Il va utiliser embarquement dans sa phrase.",
          "Nous avons trouvé l'embarquement dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser embarquement.",
          "L'élève a ajouté embarquement dans sa réponse.",
          "J'ai compris le mot embarquement pour la première fois.",
          "Ma sœur a choisi l'embarquement pour son exemple.",
          "Ils ont répété embarquement à voix haute.",
          "Nous allons revoir l'embarquement avec le professeur.",
          "Elle a noté embarquement pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'embarquement.",
          "Après la leçon, j'ai utilisé le mot embarquement dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'embarquement.",
          "Quand je lis le texte, je cherche le sens de embarquement.",
          "Ce matin, nous avons associé l'embarquement à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec embarquement.",
          "Le professeur a demandé un exemple avec l'embarquement.",
          "J'ai choisi l'embarquement parce que ce mot était dans la liste.",
          "Nous allons réviser l'embarquement avant l'évaluation.",
          "Mon camarade a expliqué l'embarquement avec ses mots.",
          "J'ai ajouté embarquement dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'embarquement semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'embarquement se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais embarquement, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà embarquement, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'embarquement.",
          "La leçon que nous travaillons utilise embarquement dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'embarquement, les élèves prenaient des notes.",
          "Puisque l'embarquement aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé embarquement, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'embarquement aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, embarquement peut donner une information précise.",
          "Le mot dont je parle est embarquement, que la classe doit retenir.",
          "Tant que tu pratiqueras embarquement, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'embarquement demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient embarquement, je penserai au vocabulaire du déplacement.",
          "Bien que le mot embarquement paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'embarquement apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'embarquement, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà embarquement, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'embarquement.",
          "Lorsque j'aurai mémorisé embarquement, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'embarquement.",
          "Puisque embarquement est utile, je le révise régulièrement.",
        ],
      } },
    { word: "porte", image: "porte.webp",               article: "la",  gender: "f", definition: "La porte est accès à l'avion dans le terminal." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la porte sur le plan.",
          "Demain, je vais chercher la porte.",
          "Quand je voyage, j'utilise souvent la porte.",
          "Ce matin, le guide a montré la porte.",
          "Nous avons demandé où se trouvait la porte.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la porte parce que c'était pratique.",
          "Elle a noté porte dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la porte.",
          "Le groupe a trouvé la porte près de la gare.",
          "Je vais chercher la porte après l'arrivée.",
          "Nous avons associé la porte à une image.",
          "Hier soir, mon frère a vérifié la porte sur internet.",
          "Pendant les vacances, nous utilisions souvent la porte.",
          "Elle a oublié le mot porte pendant l'exercice.",
          "Il va utiliser porte dans sa phrase.",
          "Nous avons trouvé la porte dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser porte.",
          "L'élève a ajouté porte dans sa réponse.",
          "J'ai compris le mot porte pour la première fois.",
          "Ma sœur a choisi la porte pour son exemple.",
          "Ils ont répété porte à voix haute.",
          "Nous allons revoir la porte avec le professeur.",
          "Elle a noté porte pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la porte.",
          "Après la leçon, j'ai utilisé le mot porte dans une phrase.",
          "Demain, je vais apprendre à mieux employer la porte.",
          "Quand je lis le texte, je cherche le sens de porte.",
          "Ce matin, nous avons associé la porte à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec porte.",
          "Le professeur a demandé un exemple avec la porte.",
          "J'ai choisi la porte parce que ce mot était dans la liste.",
          "Nous allons réviser la porte avant l'évaluation.",
          "Mon camarade a expliqué la porte avec ses mots.",
          "J'ai ajouté porte dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la porte semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la porte se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais porte, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà porte, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la porte.",
          "La leçon que nous travaillons utilise porte dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la porte, les élèves prenaient des notes.",
          "Puisque la porte aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé porte, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la porte aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, porte peut donner une information précise.",
          "Le mot dont je parle est porte, que la classe doit retenir.",
          "Tant que tu pratiqueras porte, tu comprendras mieux les dialogues de voyage.",
          "Bien que la porte demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient porte, je penserai au vocabulaire du déplacement.",
          "Bien que le mot porte paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la porte apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la porte, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà porte, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la porte.",
          "Lorsque j'aurai mémorisé porte, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la porte.",
          "Puisque porte est utile, je le révise régulièrement.",
        ],
      } },
    { word: "bagage", image: "bagage.webp",              article: "le",  gender: "m", definition: "Le bagage est valise ou sac de voyage." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le bagage sur le plan.",
          "Demain, je vais chercher le bagage.",
          "Quand je voyage, j'utilise souvent le bagage.",
          "Ce matin, le guide a montré le bagage.",
          "Nous avons demandé où se trouvait le bagage.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le bagage parce que c'était pratique.",
          "Elle a noté bagage dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du bagage.",
          "Le groupe a trouvé le bagage près de la gare.",
          "Je vais chercher le bagage après l'arrivée.",
          "Nous avons associé le bagage à une image.",
          "Hier soir, mon frère a vérifié le bagage sur internet.",
          "Pendant les vacances, nous utilisions souvent le bagage.",
          "Elle a oublié le mot bagage pendant l'exercice.",
          "Il va utiliser bagage dans sa phrase.",
          "Nous avons trouvé le bagage dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser bagage.",
          "L'élève a ajouté bagage dans sa réponse.",
          "J'ai compris le mot bagage pour la première fois.",
          "Ma sœur a choisi le bagage pour son exemple.",
          "Ils ont répété bagage à voix haute.",
          "Nous allons revoir le bagage avec le professeur.",
          "Elle a noté bagage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le bagage.",
          "Après la leçon, j'ai utilisé le mot bagage dans une phrase.",
          "Demain, je vais apprendre à mieux employer le bagage.",
          "Quand je lis le texte, je cherche le sens de bagage.",
          "Ce matin, nous avons associé le bagage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec bagage.",
          "Le professeur a demandé un exemple avec le bagage.",
          "J'ai choisi le bagage parce que ce mot était dans la liste.",
          "Nous allons réviser le bagage avant l'évaluation.",
          "Mon camarade a expliqué le bagage avec ses mots.",
          "J'ai ajouté bagage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le bagage semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le bagage se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais bagage, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà bagage, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le bagage.",
          "La leçon que nous travaillons utilise bagage dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le bagage, les élèves prenaient des notes.",
          "Puisque le bagage aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé bagage, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le bagage aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, bagage peut donner une information précise.",
          "Le mot dont je parle est bagage, que la classe doit retenir.",
          "Tant que tu pratiqueras bagage, tu comprendras mieux les dialogues de voyage.",
          "Bien que le bagage demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient bagage, je penserai au vocabulaire du déplacement.",
          "Bien que le mot bagage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le bagage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le bagage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà bagage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le bagage.",
          "Lorsque j'aurai mémorisé bagage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le bagage.",
          "Puisque bagage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "carte d'embarquement", image: "carte-d-embarquement.webp",article: "la",  gender: "f", definition: "La carte d'embarquement est un document remis pour monter dans l'avion." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la carte d'embarquement sur le plan.",
          "Demain, je vais chercher la carte d'embarquement.",
          "Quand je voyage, j'utilise souvent la carte d'embarquement.",
          "Ce matin, le guide a montré la carte d'embarquement.",
          "Nous avons demandé où se trouvait la carte d'embarquement.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la carte d'embarquement parce que c'était pratique.",
          "Elle a noté carte d'embarquement dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la carte d'embarquement.",
          "Le groupe a trouvé la carte d'embarquement près de la gare.",
          "Je vais chercher la carte d'embarquement après l'arrivée.",
          "Nous avons associé la carte d'embarquement à une image.",
          "Hier soir, mon frère a vérifié la carte d'embarquement sur internet.",
          "Pendant les vacances, nous utilisions souvent la carte d'embarquement.",
          "Elle a oublié le mot carte d'embarquement pendant l'exercice.",
          "Il va utiliser carte d'embarquement dans sa phrase.",
          "Nous avons trouvé la carte d'embarquement dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser carte d'embarquement.",
          "L'élève a ajouté carte d'embarquement dans sa réponse.",
          "J'ai compris le mot carte d'embarquement pour la première fois.",
          "Ma sœur a choisi la carte d'embarquement pour son exemple.",
          "Ils ont répété carte d'embarquement à voix haute.",
          "Nous allons revoir la carte d'embarquement avec le professeur.",
          "Elle a noté carte d'embarquement pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la carte d'embarquement.",
          "Après la leçon, j'ai utilisé le mot carte d'embarquement dans une phrase.",
          "Demain, je vais apprendre à mieux employer la carte d'embarquement.",
          "Quand je lis le texte, je cherche le sens de carte d'embarquement.",
          "Ce matin, nous avons associé la carte d'embarquement à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec carte d'embarquement.",
          "Le professeur a demandé un exemple avec la carte d'embarquement.",
          "J'ai choisi la carte d'embarquement parce que ce mot était dans la liste.",
          "Nous allons réviser la carte d'embarquement avant l'évaluation.",
          "Mon camarade a expliqué la carte d'embarquement avec ses mots.",
          "J'ai ajouté carte d'embarquement dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la carte d'embarquement semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la carte d'embarquement se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais carte d'embarquement, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà carte d'embarquement, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la carte d'embarquement.",
          "La leçon que nous travaillons utilise carte d'embarquement dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la carte d'embarquement, les élèves prenaient des notes.",
          "Puisque la carte d'embarquement aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé carte d'embarquement, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la carte d'embarquement aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, carte d'embarquement peut donner une information précise.",
          "Le mot dont je parle est carte d'embarquement, que la classe doit retenir.",
          "Tant que tu pratiqueras carte d'embarquement, tu comprendras mieux les dialogues de voyage.",
          "Bien que la carte d'embarquement demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient carte d'embarquement, je penserai au vocabulaire du déplacement.",
          "Bien que le mot carte d'embarquement paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la carte d'embarquement apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la carte d'embarquement, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà carte d'embarquement, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la carte d'embarquement.",
          "Lorsque j'aurai mémorisé carte d'embarquement, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la carte d'embarquement.",
          "Puisque carte d'embarquement est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il présente son ___ au contrôle de sécurité.",          answer: "passeport" },
    { sentence: "L'___ commence à la porte 12.",                         answer: "embarquement" },
    { sentence: "Elle fait la queue à l'___ pour enregistrer ses bagages.", answer: "enregistrement" },
    { sentence: "Sa ___ est trop lourde, elle doit payer un supplément.", answer: "valise" },
    { sentence: "Le ___ Paris-New York fait escale à Londres.",          answer: "vol" },
  ],
};
