import type { VocabTheme } from "../../vocabulary-data";

export const V7_BOULANGERIE_THEME: VocabTheme = {
  slug: "v7-boulangerie",
  code: "V7.4",
  title: "La boulangerie",
  titlePivot: {
    en: "Bakery",
    ar: "المخبز",
    fa: "نانوایی",
    ti: "ቤት እንጌራ",
    uk: "Пекарня",
    pt: "Padaria",
    so: "Dukaanka rootiga",
    tr: "Fırın",
    ps: "نانوايي",
  },
  section: "V7",
  imageFolder: "V10",
  words: [
    {
      word: "pain",
      image: "pain.webp",
      article: "le",
      gender: "m",
      group: "Pains",
      definition: ["Aliment fait avec de la farine, de l’eau et du sel."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un pain au marché.",
          "Demain, je vais préparer le pain pour le repas.",
          "Quand j'étais petit, je mangeais souvent le pain.",
          "Ce matin, elle a lavé le pain avant de cuisiner.",
          "Nous avons ajouté le pain dans la recette.",
          "Ils vont servir le pain avec le plat principal.",
          "J'ai choisi un pain parce qu'il était frais.",
          "Elle a coupé le pain en petits morceaux.",
          "Avant le dîner, nous avons goûté le pain.",
          "Le vendeur a conseillé le pain à ma mère.",
          "Je vais acheter un pain après le travail.",
          "Nous avons gardé le pain au réfrigérateur.",
          "Hier soir, mon frère a mangé le pain.",
          "Pendant les vacances, nous préparions souvent le pain.",
          "Elle a oublié un pain dans le sac.",
          "Il va utiliser le pain pour faire une sauce.",
          "Nous avons commandé le pain au restaurant.",
          "Ce week-end, je vais cuisiner le pain.",
          "Le cuisinier a ajouté le pain dans l'assiette.",
          "J'ai goûté le pain pour la première fois.",
          "Ma sœur a choisi le pain pour le dessert.",
          "Ils ont partagé un pain à midi.",
          "Nous allons servir le pain avec du pain.",
          "Elle a acheté un pain pour la recette.",
          "Le client a demandé le pain au serveur.",
          "Après la leçon, j'ai utilisé le mot pain dans une phrase.",
          "Demain, je vais apprendre à mieux employer le pain.",
          "Quand je lis le texte, je cherche le sens de pain.",
          "Ce matin, nous avons associé le pain à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pain.",
          "Le professeur a demandé un exemple avec le pain.",
          "J'ai choisi le pain parce que ce mot était dans la liste.",
          "Nous allons réviser le pain avant l'évaluation.",
          "Mon camarade a expliqué le pain avec ses mots.",
          "J'ai ajouté pain dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le pain soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le pain était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le pain, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le pain dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le pain.",
          "La recette que nous préparons utilise le pain pour équilibrer les saveurs.",
          "Pendant que le chef coupait le pain, les autres préparaient la table.",
          "Puisque le pain était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le pain, tu pourras commencer la recette.",
          "Je pense que le pain convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le pain peut améliorer la présentation.",
          "Le produit dont je parle est le pain, que beaucoup de clients apprécient.",
          "Tant que le pain restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le pain est très demandé en cuisine.",
          "Si le restaurant propose le pain, je choisirai ce plat sans hésiter.",
          "Bien que le mot pain paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le pain apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le pain, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pain, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le pain.",
          "Lorsque j'aurai mémorisé pain, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le pain.",
          "Puisque pain est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "baguette",
      image: "baguette.webp",
      article: "la",
      gender: "f",
      group: "Pains",
      definition: ["Pain long et fin, très connu en France."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une baguette au marché.",
          "Demain, je vais préparer la baguette pour le repas.",
          "Quand j'étais petit, je mangeais souvent la baguette.",
          "Ce matin, elle a lavé la baguette avant de cuisiner.",
          "Nous avons ajouté la baguette dans la recette.",
          "Ils vont servir la baguette avec le plat principal.",
          "J'ai choisi une baguette parce qu'elle était fraîche.",
          "Elle a coupé la baguette en petits morceaux.",
          "Avant le dîner, nous avons goûté la baguette.",
          "Le vendeur a conseillé la baguette à ma mère.",
          "Je vais acheter une baguette après le travail.",
          "Nous avons gardé la baguette au réfrigérateur.",
          "Hier soir, mon frère a mangé la baguette.",
          "Pendant les vacances, nous préparions souvent la baguette.",
          "Elle a oublié une baguette dans le sac.",
          "Il va utiliser la baguette pour faire une sauce.",
          "Nous avons commandé la baguette au restaurant.",
          "Ce week-end, je vais cuisiner la baguette.",
          "Le cuisinier a ajouté la baguette dans l'assiette.",
          "J'ai goûté la baguette pour la première fois.",
          "Ma sœur a choisi la baguette pour le dessert.",
          "Ils ont partagé une baguette à midi.",
          "Nous allons servir la baguette avec du pain.",
          "Elle a acheté une baguette pour la recette.",
          "Le client a demandé la baguette au serveur.",
          "Après la leçon, j'ai utilisé le mot baguette dans une phrase.",
          "Demain, je vais apprendre à mieux employer la baguette.",
          "Quand je lis le texte, je cherche le sens de baguette.",
          "Ce matin, nous avons associé la baguette à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec baguette.",
          "Le professeur a demandé un exemple avec la baguette.",
          "J'ai choisi la baguette parce que ce mot était dans la liste.",
          "Nous allons réviser la baguette avant l'évaluation.",
          "Mon camarade a expliqué la baguette avec ses mots.",
          "J'ai ajouté baguette dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la baguette soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la baguette était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la baguette, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la baguette dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la baguette.",
          "La recette que nous préparons utilise la baguette pour équilibrer les saveurs.",
          "Pendant que le chef coupait la baguette, les autres préparaient la table.",
          "Puisque la baguette était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la baguette, tu pourras commencer la recette.",
          "Je pense que la baguette convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la baguette peut améliorer la présentation.",
          "Le produit dont je parle est la baguette, que beaucoup de clients apprécient.",
          "Tant que la baguette restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la baguette est très demandée en cuisine.",
          "Si le restaurant propose la baguette, je choisirai ce plat sans hésiter.",
          "Bien que le mot baguette paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la baguette apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la baguette, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà baguette, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la baguette.",
          "Lorsque j'aurai mémorisé baguette, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la baguette.",
          "Puisque baguette est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "sandwich",
      image: "sandwich.webp",
      article: "le",
      gender: "m",
      group: "Pains",
      definition: ["Pain coupé avec des aliments à l’intérieur."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un sandwich au marché.",
          "Demain, je vais préparer le sandwich pour le repas.",
          "Quand j'étais petit, je mangeais souvent le sandwich.",
          "Ce matin, elle a lavé le sandwich avant de cuisiner.",
          "Nous avons ajouté le sandwich dans la recette.",
          "Ils vont servir le sandwich avec le plat principal.",
          "J'ai choisi un sandwich parce qu'il était frais.",
          "Elle a coupé le sandwich en petits morceaux.",
          "Avant le dîner, nous avons goûté le sandwich.",
          "Le vendeur a conseillé le sandwich à ma mère.",
          "Je vais acheter un sandwich après le travail.",
          "Nous avons gardé le sandwich au réfrigérateur.",
          "Hier soir, mon frère a mangé le sandwich.",
          "Pendant les vacances, nous préparions souvent le sandwich.",
          "Elle a oublié un sandwich dans le sac.",
          "Il va utiliser le sandwich pour faire une sauce.",
          "Nous avons commandé le sandwich au restaurant.",
          "Ce week-end, je vais cuisiner le sandwich.",
          "Le cuisinier a ajouté le sandwich dans l'assiette.",
          "J'ai goûté le sandwich pour la première fois.",
          "Ma sœur a choisi le sandwich pour le dessert.",
          "Ils ont partagé un sandwich à midi.",
          "Nous allons servir le sandwich avec du pain.",
          "Elle a acheté un sandwich pour la recette.",
          "Le client a demandé le sandwich au serveur.",
          "Après la leçon, j'ai utilisé le mot sandwich dans une phrase.",
          "Demain, je vais apprendre à mieux employer le sandwich.",
          "Quand je lis le texte, je cherche le sens de sandwich.",
          "Ce matin, nous avons associé le sandwich à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec sandwich.",
          "Le professeur a demandé un exemple avec le sandwich.",
          "J'ai choisi le sandwich parce que ce mot était dans la liste.",
          "Nous allons réviser le sandwich avant l'évaluation.",
          "Mon camarade a expliqué le sandwich avec ses mots.",
          "J'ai ajouté sandwich dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le sandwich soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le sandwich était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le sandwich, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le sandwich dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le sandwich.",
          "La recette que nous préparons utilise le sandwich pour équilibrer les saveurs.",
          "Pendant que le chef coupait le sandwich, les autres préparaient la table.",
          "Puisque le sandwich était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le sandwich, tu pourras commencer la recette.",
          "Je pense que le sandwich convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le sandwich peut améliorer la présentation.",
          "Le produit dont je parle est le sandwich, que beaucoup de clients apprécient.",
          "Tant que le sandwich restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le sandwich est très demandé en cuisine.",
          "Si le restaurant propose le sandwich, je choisirai ce plat sans hésiter.",
          "Bien que le mot sandwich paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le sandwich apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le sandwich, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà sandwich, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le sandwich.",
          "Lorsque j'aurai mémorisé sandwich, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le sandwich.",
          "Puisque sandwich est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "viennoiserie",
      image: "viennoiserie.webp",
      article: "la",
      gender: "f",
      group: "Viennoiseries",
      definition: ["Aliment sucré de boulangerie, souvent mangé le matin."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une viennoiserie au marché.",
          "Demain, je vais préparer la viennoiserie pour le repas.",
          "Quand j'étais petit, je mangeais souvent la viennoiserie.",
          "Ce matin, elle a lavé la viennoiserie avant de cuisiner.",
          "Nous avons ajouté la viennoiserie dans la recette.",
          "Ils vont servir la viennoiserie avec le plat principal.",
          "J'ai choisi une viennoiserie parce qu'elle était fraîche.",
          "Elle a coupé la viennoiserie en petits morceaux.",
          "Avant le dîner, nous avons goûté la viennoiserie.",
          "Le vendeur a conseillé la viennoiserie à ma mère.",
          "Je vais acheter une viennoiserie après le travail.",
          "Nous avons gardé la viennoiserie au réfrigérateur.",
          "Hier soir, mon frère a mangé la viennoiserie.",
          "Pendant les vacances, nous préparions souvent la viennoiserie.",
          "Elle a oublié une viennoiserie dans le sac.",
          "Il va utiliser la viennoiserie pour faire une sauce.",
          "Nous avons commandé la viennoiserie au restaurant.",
          "Ce week-end, je vais cuisiner la viennoiserie.",
          "Le cuisinier a ajouté la viennoiserie dans l'assiette.",
          "J'ai goûté la viennoiserie pour la première fois.",
          "Ma sœur a choisi la viennoiserie pour le dessert.",
          "Ils ont partagé une viennoiserie à midi.",
          "Nous allons servir la viennoiserie avec du pain.",
          "Elle a acheté une viennoiserie pour la recette.",
          "Le client a demandé la viennoiserie au serveur.",
          "Après la leçon, j'ai utilisé le mot viennoiserie dans une phrase.",
          "Demain, je vais apprendre à mieux employer la viennoiserie.",
          "Quand je lis le texte, je cherche le sens de viennoiserie.",
          "Ce matin, nous avons associé la viennoiserie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec viennoiserie.",
          "Le professeur a demandé un exemple avec la viennoiserie.",
          "J'ai choisi la viennoiserie parce que ce mot était dans la liste.",
          "Nous allons réviser la viennoiserie avant l'évaluation.",
          "Mon camarade a expliqué la viennoiserie avec ses mots.",
          "J'ai ajouté viennoiserie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la viennoiserie soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la viennoiserie était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la viennoiserie, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la viennoiserie dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la viennoiserie.",
          "La recette que nous préparons utilise la viennoiserie pour équilibrer les saveurs.",
          "Pendant que le chef coupait la viennoiserie, les autres préparaient la table.",
          "Puisque la viennoiserie était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la viennoiserie, tu pourras commencer la recette.",
          "Je pense que la viennoiserie convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la viennoiserie peut améliorer la présentation.",
          "Le produit dont je parle est la viennoiserie, que beaucoup de clients apprécient.",
          "Tant que la viennoiserie restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la viennoiserie est très demandée en cuisine.",
          "Si le restaurant propose la viennoiserie, je choisirai ce plat sans hésiter.",
          "Bien que le mot viennoiserie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la viennoiserie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la viennoiserie, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà viennoiserie, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la viennoiserie.",
          "Lorsque j'aurai mémorisé viennoiserie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la viennoiserie.",
          "Puisque viennoiserie est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "croissant",
      image: "croissant.webp",
      article: "le",
      gender: "m",
      group: "Viennoiseries",
      definition: ["Viennoiserie en forme de lune."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un croissant au marché.",
          "Demain, je vais préparer le croissant pour le repas.",
          "Quand j'étais petit, je mangeais souvent le croissant.",
          "Ce matin, elle a lavé le croissant avant de cuisiner.",
          "Nous avons ajouté le croissant dans la recette.",
          "Ils vont servir le croissant avec le plat principal.",
          "J'ai choisi un croissant parce qu'il était frais.",
          "Elle a coupé le croissant en petits morceaux.",
          "Avant le dîner, nous avons goûté le croissant.",
          "Le vendeur a conseillé le croissant à ma mère.",
          "Je vais acheter un croissant après le travail.",
          "Nous avons gardé le croissant au réfrigérateur.",
          "Hier soir, mon frère a mangé le croissant.",
          "Pendant les vacances, nous préparions souvent le croissant.",
          "Elle a oublié un croissant dans le sac.",
          "Il va utiliser le croissant pour faire une sauce.",
          "Nous avons commandé le croissant au restaurant.",
          "Ce week-end, je vais cuisiner le croissant.",
          "Le cuisinier a ajouté le croissant dans l'assiette.",
          "J'ai goûté le croissant pour la première fois.",
          "Ma sœur a choisi le croissant pour le dessert.",
          "Ils ont partagé un croissant à midi.",
          "Nous allons servir le croissant avec du pain.",
          "Elle a acheté un croissant pour la recette.",
          "Le client a demandé le croissant au serveur.",
          "Après la leçon, j'ai utilisé le mot croissant dans une phrase.",
          "Demain, je vais apprendre à mieux employer le croissant.",
          "Quand je lis le texte, je cherche le sens de croissant.",
          "Ce matin, nous avons associé le croissant à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec croissant.",
          "Le professeur a demandé un exemple avec le croissant.",
          "J'ai choisi le croissant parce que ce mot était dans la liste.",
          "Nous allons réviser le croissant avant l'évaluation.",
          "Mon camarade a expliqué le croissant avec ses mots.",
          "J'ai ajouté croissant dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le croissant soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le croissant était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le croissant, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le croissant dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le croissant.",
          "La recette que nous préparons utilise le croissant pour équilibrer les saveurs.",
          "Pendant que le chef coupait le croissant, les autres préparaient la table.",
          "Puisque le croissant était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le croissant, tu pourras commencer la recette.",
          "Je pense que le croissant convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le croissant peut améliorer la présentation.",
          "Le produit dont je parle est le croissant, que beaucoup de clients apprécient.",
          "Tant que le croissant restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le croissant est très demandé en cuisine.",
          "Si le restaurant propose le croissant, je choisirai ce plat sans hésiter.",
          "Bien que le mot croissant paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le croissant apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le croissant, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà croissant, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le croissant.",
          "Lorsque j'aurai mémorisé croissant, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le croissant.",
          "Puisque croissant est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "pain au chocolat",
      image: "pain-au-chocolat.webp",
      article: "le",
      gender: "m",
      group: "Viennoiseries",
      definition: ["Viennoiserie avec du chocolat à l’intérieur."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un pain au chocolat au marché.",
          "Demain, je vais préparer le pain au chocolat pour le repas.",
          "Quand j'étais petit, je mangeais souvent le pain au chocolat.",
          "Ce matin, elle a lavé le pain au chocolat avant de cuisiner.",
          "Nous avons ajouté le pain au chocolat dans la recette.",
          "Ils vont servir le pain au chocolat avec le plat principal.",
          "J'ai choisi un pain au chocolat parce qu'il était frais.",
          "Elle a coupé le pain au chocolat en petits morceaux.",
          "Avant le dîner, nous avons goûté le pain au chocolat.",
          "Le vendeur a conseillé le pain au chocolat à ma mère.",
          "Je vais acheter un pain au chocolat après le travail.",
          "Nous avons gardé le pain au chocolat au réfrigérateur.",
          "Hier soir, mon frère a mangé le pain au chocolat.",
          "Pendant les vacances, nous préparions souvent le pain au chocolat.",
          "Elle a oublié un pain au chocolat dans le sac.",
          "Il va utiliser le pain au chocolat pour faire une sauce.",
          "Nous avons commandé le pain au chocolat au restaurant.",
          "Ce week-end, je vais cuisiner le pain au chocolat.",
          "Le cuisinier a ajouté le pain au chocolat dans l'assiette.",
          "J'ai goûté le pain au chocolat pour la première fois.",
          "Ma sœur a choisi le pain au chocolat pour le dessert.",
          "Ils ont partagé un pain au chocolat à midi.",
          "Nous allons servir le pain au chocolat avec du pain.",
          "Elle a acheté un pain au chocolat pour la recette.",
          "Le client a demandé le pain au chocolat au serveur.",
          "Après la leçon, j'ai utilisé le mot pain au chocolat dans une phrase.",
          "Demain, je vais apprendre à mieux employer le pain au chocolat.",
          "Quand je lis le texte, je cherche le sens de pain au chocolat.",
          "Ce matin, nous avons associé le pain au chocolat à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pain au chocolat.",
          "Le professeur a demandé un exemple avec le pain au chocolat.",
          "J'ai choisi le pain au chocolat parce que ce mot était dans la liste.",
          "Nous allons réviser le pain au chocolat avant l'évaluation.",
          "Mon camarade a expliqué le pain au chocolat avec ses mots.",
          "J'ai ajouté pain au chocolat dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le pain au chocolat soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le pain au chocolat était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le pain au chocolat, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le pain au chocolat dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le pain au chocolat.",
          "La recette que nous préparons utilise le pain au chocolat pour équilibrer les saveurs.",
          "Pendant que le chef coupait le pain au chocolat, les autres préparaient la table.",
          "Puisque le pain au chocolat était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le pain au chocolat, tu pourras commencer la recette.",
          "Je pense que le pain au chocolat convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le pain au chocolat peut améliorer la présentation.",
          "Le produit dont je parle est le pain au chocolat, que beaucoup de clients apprécient.",
          "Tant que le pain au chocolat restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le pain au chocolat est très demandé en cuisine.",
          "Si le restaurant propose le pain au chocolat, je choisirai ce plat sans hésiter.",
          "Bien que le mot pain au chocolat paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le pain au chocolat apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le pain au chocolat, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pain au chocolat, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le pain au chocolat.",
          "Lorsque j'aurai mémorisé pain au chocolat, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le pain au chocolat.",
          "Puisque pain au chocolat est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "brioche",
      image: "brioche.webp",
      article: "la",
      gender: "f",
      group: "Viennoiseries",
      definition: ["Pain sucré, tendre et moelleux."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une brioche au marché.",
          "Demain, je vais préparer la brioche pour le repas.",
          "Quand j'étais petit, je mangeais souvent la brioche.",
          "Ce matin, elle a lavé la brioche avant de cuisiner.",
          "Nous avons ajouté la brioche dans la recette.",
          "Ils vont servir la brioche avec le plat principal.",
          "J'ai choisi une brioche parce qu'elle était fraîche.",
          "Elle a coupé la brioche en petits morceaux.",
          "Avant le dîner, nous avons goûté la brioche.",
          "Le vendeur a conseillé la brioche à ma mère.",
          "Je vais acheter une brioche après le travail.",
          "Nous avons gardé la brioche au réfrigérateur.",
          "Hier soir, mon frère a mangé la brioche.",
          "Pendant les vacances, nous préparions souvent la brioche.",
          "Elle a oublié une brioche dans le sac.",
          "Il va utiliser la brioche pour faire une sauce.",
          "Nous avons commandé la brioche au restaurant.",
          "Ce week-end, je vais cuisiner la brioche.",
          "Le cuisinier a ajouté la brioche dans l'assiette.",
          "J'ai goûté la brioche pour la première fois.",
          "Ma sœur a choisi la brioche pour le dessert.",
          "Ils ont partagé une brioche à midi.",
          "Nous allons servir la brioche avec du pain.",
          "Elle a acheté une brioche pour la recette.",
          "Le client a demandé la brioche au serveur.",
          "Après la leçon, j'ai utilisé le mot brioche dans une phrase.",
          "Demain, je vais apprendre à mieux employer la brioche.",
          "Quand je lis le texte, je cherche le sens de brioche.",
          "Ce matin, nous avons associé la brioche à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec brioche.",
          "Le professeur a demandé un exemple avec la brioche.",
          "J'ai choisi la brioche parce que ce mot était dans la liste.",
          "Nous allons réviser la brioche avant l'évaluation.",
          "Mon camarade a expliqué la brioche avec ses mots.",
          "J'ai ajouté brioche dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la brioche soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la brioche était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la brioche, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la brioche dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la brioche.",
          "La recette que nous préparons utilise la brioche pour équilibrer les saveurs.",
          "Pendant que le chef coupait la brioche, les autres préparaient la table.",
          "Puisque la brioche était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la brioche, tu pourras commencer la recette.",
          "Je pense que la brioche convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la brioche peut améliorer la présentation.",
          "Le produit dont je parle est la brioche, que beaucoup de clients apprécient.",
          "Tant que la brioche restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la brioche est très demandée en cuisine.",
          "Si le restaurant propose la brioche, je choisirai ce plat sans hésiter.",
          "Bien que le mot brioche paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la brioche apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la brioche, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà brioche, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la brioche.",
          "Lorsque j'aurai mémorisé brioche, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la brioche.",
          "Puisque brioche est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "chausson",
      image: "chausson.webp",
      article: "le",
      gender: "m",
      group: "Viennoiseries",
      definition: ["Viennoiserie en forme de chausson, souvent fourrée aux pommes."],
      definitionPivot: {
        en: "A pastry shaped like a slipper, often filled with apples.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le chausson à la boulangerie.",
          "Demain, je vais préparer le chausson pour le petit-déjeuner.",
          "Ce matin, elle a mangé le chausson.",
          "Nous avons choisi le chausson parce qu'il était frais.",
          "Ils vont servir le chausson avec le café.",
          "J'ai goûté le chausson pour la première fois.",
          "Elle a coupé le chausson en petits morceaux.",
          "Avant le goûter, nous avons acheté le chausson.",
          "Le vendeur a conseillé le chausson à ma mère.",
          "Les enfants ont appris le mot chausson.",
          "Nous avons associé le chausson à une image.",
          "J'ai ajouté chausson dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le chausson soit simple, il faut savoir le décrire.",
          "Comme le chausson était très frais, nous l'avons acheté.",
          "Si tu connais chausson, tu feras mieux tes courses.",
          "Même si je connais déjà chausson, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé chausson, je pourrai l'utiliser plus naturellement.",
          "Puisque chausson est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le chausson dans une phrase claire.",
        ],
      },
    },
    {
      word: "beignet",
      image: "beignet.webp",
      article: "le",
      gender: "m",
      group: "Viennoiseries",
      definition: ["Pâte frite, souvent sucrée et ronde."],
      definitionPivot: {
        en: "A fried dough pastry, often sweet and round.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le beignet à la boulangerie.",
          "Demain, je vais préparer le beignet pour le petit-déjeuner.",
          "Ce matin, elle a mangé le beignet.",
          "Nous avons choisi le beignet parce qu'il était frais.",
          "Ils vont servir le beignet avec le café.",
          "J'ai goûté le beignet pour la première fois.",
          "Elle a coupé le beignet en petits morceaux.",
          "Avant le goûter, nous avons acheté le beignet.",
          "Le vendeur a conseillé le beignet à ma mère.",
          "Les enfants ont appris le mot beignet.",
          "Nous avons associé le beignet à une image.",
          "J'ai ajouté beignet dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le beignet soit simple, il faut savoir le décrire.",
          "Comme le beignet était très frais, nous l'avons acheté.",
          "Si tu connais beignet, tu feras mieux tes courses.",
          "Même si je connais déjà beignet, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé beignet, je pourrai l'utiliser plus naturellement.",
          "Puisque beignet est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le beignet dans une phrase claire.",
        ],
      },
    },
    {
      word: "pâtisserie",
      image: "patisserie.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Gâteau ou préparation sucrée."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une pâtisserie au marché.",
          "Demain, je vais préparer la pâtisserie pour le repas.",
          "Quand j'étais petit, je mangeais souvent la pâtisserie.",
          "Ce matin, elle a lavé la pâtisserie avant de cuisiner.",
          "Nous avons ajouté la pâtisserie dans la recette.",
          "Ils vont servir la pâtisserie avec le plat principal.",
          "J'ai choisi une pâtisserie parce qu'elle était fraîche.",
          "Elle a coupé la pâtisserie en petits morceaux.",
          "Avant le dîner, nous avons goûté la pâtisserie.",
          "Le vendeur a conseillé la pâtisserie à ma mère.",
          "Je vais acheter une pâtisserie après le travail.",
          "Nous avons gardé la pâtisserie au réfrigérateur.",
          "Hier soir, mon frère a mangé la pâtisserie.",
          "Pendant les vacances, nous préparions souvent la pâtisserie.",
          "Elle a oublié une pâtisserie dans le sac.",
          "Il va utiliser la pâtisserie pour faire une sauce.",
          "Nous avons commandé la pâtisserie au restaurant.",
          "Ce week-end, je vais cuisiner la pâtisserie.",
          "Le cuisinier a ajouté la pâtisserie dans l'assiette.",
          "J'ai goûté la pâtisserie pour la première fois.",
          "Ma sœur a choisi la pâtisserie pour le dessert.",
          "Ils ont partagé une pâtisserie à midi.",
          "Nous allons servir la pâtisserie avec du pain.",
          "Elle a acheté une pâtisserie pour la recette.",
          "Le client a demandé la pâtisserie au serveur.",
          "Après la leçon, j'ai utilisé le mot pâtisserie dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pâtisserie.",
          "Quand je lis le texte, je cherche le sens de pâtisserie.",
          "Ce matin, nous avons associé la pâtisserie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pâtisserie.",
          "Le professeur a demandé un exemple avec la pâtisserie.",
          "J'ai choisi la pâtisserie parce que ce mot était dans la liste.",
          "Nous allons réviser la pâtisserie avant l'évaluation.",
          "Mon camarade a expliqué la pâtisserie avec ses mots.",
          "J'ai ajouté pâtisserie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pâtisserie soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la pâtisserie était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la pâtisserie, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la pâtisserie dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la pâtisserie.",
          "La recette que nous préparons utilise la pâtisserie pour équilibrer les saveurs.",
          "Pendant que le chef coupait la pâtisserie, les autres préparaient la table.",
          "Puisque la pâtisserie était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la pâtisserie, tu pourras commencer la recette.",
          "Je pense que la pâtisserie convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la pâtisserie peut améliorer la présentation.",
          "Le produit dont je parle est la pâtisserie, que beaucoup de clients apprécient.",
          "Tant que la pâtisserie restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la pâtisserie est très demandée en cuisine.",
          "Si le restaurant propose la pâtisserie, je choisirai ce plat sans hésiter.",
          "Bien que le mot pâtisserie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pâtisserie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pâtisserie, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pâtisserie, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pâtisserie.",
          "Lorsque j'aurai mémorisé pâtisserie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pâtisserie.",
          "Puisque pâtisserie est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "gâteau",
      image: "gateau.webp",
      article: "le",
      gender: "m",
      group: "Pâtisseries",
      definition: ["Dessert sucré souvent préparé pour une fête."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un gâteau au marché.",
          "Demain, je vais préparer le gâteau pour le repas.",
          "Quand j'étais petit, je mangeais souvent le gâteau.",
          "Ce matin, elle a lavé le gâteau avant de cuisiner.",
          "Nous avons ajouté le gâteau dans la recette.",
          "Ils vont servir le gâteau avec le plat principal.",
          "J'ai choisi un gâteau parce qu'il était frais.",
          "Elle a coupé le gâteau en petits morceaux.",
          "Avant le dîner, nous avons goûté le gâteau.",
          "Le vendeur a conseillé le gâteau à ma mère.",
          "Je vais acheter un gâteau après le travail.",
          "Nous avons gardé le gâteau au réfrigérateur.",
          "Hier soir, mon frère a mangé le gâteau.",
          "Pendant les vacances, nous préparions souvent le gâteau.",
          "Elle a oublié un gâteau dans le sac.",
          "Il va utiliser le gâteau pour faire une sauce.",
          "Nous avons commandé le gâteau au restaurant.",
          "Ce week-end, je vais cuisiner le gâteau.",
          "Le cuisinier a ajouté le gâteau dans l'assiette.",
          "J'ai goûté le gâteau pour la première fois.",
          "Ma sœur a choisi le gâteau pour le dessert.",
          "Ils ont partagé un gâteau à midi.",
          "Nous allons servir le gâteau avec du pain.",
          "Elle a acheté un gâteau pour la recette.",
          "Le client a demandé le gâteau au serveur.",
          "Après la leçon, j'ai utilisé le mot gâteau dans une phrase.",
          "Demain, je vais apprendre à mieux employer le gâteau.",
          "Quand je lis le texte, je cherche le sens de gâteau.",
          "Ce matin, nous avons associé le gâteau à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec gâteau.",
          "Le professeur a demandé un exemple avec le gâteau.",
          "J'ai choisi le gâteau parce que ce mot était dans la liste.",
          "Nous allons réviser le gâteau avant l'évaluation.",
          "Mon camarade a expliqué le gâteau avec ses mots.",
          "J'ai ajouté gâteau dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le gâteau soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le gâteau était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le gâteau, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le gâteau dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le gâteau.",
          "La recette que nous préparons utilise le gâteau pour équilibrer les saveurs.",
          "Pendant que le chef coupait le gâteau, les autres préparaient la table.",
          "Puisque le gâteau était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le gâteau, tu pourras commencer la recette.",
          "Je pense que le gâteau convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le gâteau peut améliorer la présentation.",
          "Le produit dont je parle est le gâteau, que beaucoup de clients apprécient.",
          "Tant que le gâteau restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le gâteau est très demandé en cuisine.",
          "Si le restaurant propose le gâteau, je choisirai ce plat sans hésiter.",
          "Bien que le mot gâteau paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le gâteau apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le gâteau, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà gâteau, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le gâteau.",
          "Lorsque j'aurai mémorisé gâteau, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le gâteau.",
          "Puisque gâteau est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "tarte",
      image: "tarte.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Dessert avec une pâte et des fruits ou une garniture."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une tarte au marché.",
          "Demain, je vais préparer la tarte pour le repas.",
          "Quand j'étais petit, je mangeais souvent la tarte.",
          "Ce matin, elle a lavé la tarte avant de cuisiner.",
          "Nous avons ajouté la tarte dans la recette.",
          "Ils vont servir la tarte avec le plat principal.",
          "J'ai choisi une tarte parce qu'elle était fraîche.",
          "Elle a coupé la tarte en petits morceaux.",
          "Avant le dîner, nous avons goûté la tarte.",
          "Le vendeur a conseillé la tarte à ma mère.",
          "Je vais acheter une tarte après le travail.",
          "Nous avons gardé la tarte au réfrigérateur.",
          "Hier soir, mon frère a mangé la tarte.",
          "Pendant les vacances, nous préparions souvent la tarte.",
          "Elle a oublié une tarte dans le sac.",
          "Il va utiliser la tarte pour faire une sauce.",
          "Nous avons commandé la tarte au restaurant.",
          "Ce week-end, je vais cuisiner la tarte.",
          "Le cuisinier a ajouté la tarte dans l'assiette.",
          "J'ai goûté la tarte pour la première fois.",
          "Ma sœur a choisi la tarte pour le dessert.",
          "Ils ont partagé une tarte à midi.",
          "Nous allons servir la tarte avec du pain.",
          "Elle a acheté une tarte pour la recette.",
          "Le client a demandé la tarte au serveur.",
          "Après la leçon, j'ai utilisé le mot tarte dans une phrase.",
          "Demain, je vais apprendre à mieux employer la tarte.",
          "Quand je lis le texte, je cherche le sens de tarte.",
          "Ce matin, nous avons associé la tarte à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec tarte.",
          "Le professeur a demandé un exemple avec la tarte.",
          "J'ai choisi la tarte parce que ce mot était dans la liste.",
          "Nous allons réviser la tarte avant l'évaluation.",
          "Mon camarade a expliqué la tarte avec ses mots.",
          "J'ai ajouté tarte dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la tarte soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la tarte était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la tarte, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la tarte dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la tarte.",
          "La recette que nous préparons utilise la tarte pour équilibrer les saveurs.",
          "Pendant que le chef coupait la tarte, les autres préparaient la table.",
          "Puisque la tarte était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la tarte, tu pourras commencer la recette.",
          "Je pense que la tarte convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la tarte peut améliorer la présentation.",
          "Le produit dont je parle est la tarte, que beaucoup de clients apprécient.",
          "Tant que la tarte restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la tarte est très demandée en cuisine.",
          "Si le restaurant propose la tarte, je choisirai ce plat sans hésiter.",
          "Bien que le mot tarte paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la tarte apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la tarte, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà tarte, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la tarte.",
          "Lorsque j'aurai mémorisé tarte, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la tarte.",
          "Puisque tarte est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "éclair",
      image: "eclair.webp",
      article: "l'",
      gender: "m",
      group: "Pâtisseries",
      definition: ["Pâtisserie longue avec de la crème à l’intérieur."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un éclair au marché.",
          "Demain, je vais préparer l'éclair pour le repas.",
          "Quand j'étais petit, je mangeais souvent l'éclair.",
          "Ce matin, elle a lavé l'éclair avant de cuisiner.",
          "Nous avons ajouté l'éclair dans la recette.",
          "Ils vont servir l'éclair avec le plat principal.",
          "J'ai choisi un éclair parce qu'il était frais.",
          "Elle a coupé l'éclair en petits morceaux.",
          "Avant le dîner, nous avons goûté l'éclair.",
          "Le vendeur a conseillé l'éclair à ma mère.",
          "Je vais acheter un éclair après le travail.",
          "Nous avons gardé l'éclair au réfrigérateur.",
          "Hier soir, mon frère a mangé l'éclair.",
          "Pendant les vacances, nous préparions souvent l'éclair.",
          "Elle a oublié un éclair dans le sac.",
          "Il va utiliser l'éclair pour faire une sauce.",
          "Nous avons commandé l'éclair au restaurant.",
          "Ce week-end, je vais cuisiner l'éclair.",
          "Le cuisinier a ajouté l'éclair dans l'assiette.",
          "J'ai goûté l'éclair pour la première fois.",
          "Ma sœur a choisi l'éclair pour le dessert.",
          "Ils ont partagé un éclair à midi.",
          "Nous allons servir l'éclair avec du pain.",
          "Elle a acheté un éclair pour la recette.",
          "Le client a demandé l'éclair au serveur.",
          "Après la leçon, j'ai utilisé le mot éclair dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'éclair.",
          "Quand je lis le texte, je cherche le sens de éclair.",
          "Ce matin, nous avons associé l'éclair à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec éclair.",
          "Le professeur a demandé un exemple avec l'éclair.",
          "J'ai choisi l'éclair parce que ce mot était dans la liste.",
          "Nous allons réviser l'éclair avant l'évaluation.",
          "Mon camarade a expliqué l'éclair avec ses mots.",
          "J'ai ajouté éclair dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'éclair soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme l'éclair était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes l'éclair, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie l'éclair dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi l'éclair.",
          "La recette que nous préparons utilise l'éclair pour équilibrer les saveurs.",
          "Pendant que le chef coupait l'éclair, les autres préparaient la table.",
          "Puisque l'éclair était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé l'éclair, tu pourras commencer la recette.",
          "Je pense que l'éclair convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, l'éclair peut améliorer la présentation.",
          "Le produit dont je parle est l'éclair, que beaucoup de clients apprécient.",
          "Tant que l'éclair restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, l'éclair est très demandé en cuisine.",
          "Si le restaurant propose l'éclair, je choisirai ce plat sans hésiter.",
          "Bien que le mot éclair paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'éclair apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'éclair, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà éclair, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'éclair.",
          "Lorsque j'aurai mémorisé éclair, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'éclair.",
          "Puisque éclair est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "macaron",
      image: "macaron.webp",
      article: "le",
      gender: "m",
      group: "Pâtisseries",
      definition: ["Petit gâteau rond et coloré, croquant dehors et moelleux dedans."],
      definitionPivot: {
        en: "A small round colorful cake, crisp outside and soft inside.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le macaron à la boulangerie.",
          "Demain, je vais préparer le macaron pour le petit-déjeuner.",
          "Ce matin, elle a mangé le macaron.",
          "Nous avons choisi le macaron parce qu'il était frais.",
          "Ils vont servir le macaron avec le café.",
          "J'ai goûté le macaron pour la première fois.",
          "Elle a coupé le macaron en petits morceaux.",
          "Avant le goûter, nous avons acheté le macaron.",
          "Le vendeur a conseillé le macaron à ma mère.",
          "Les enfants ont appris le mot macaron.",
          "Nous avons associé le macaron à une image.",
          "J'ai ajouté macaron dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le macaron soit simple, il faut savoir le décrire.",
          "Comme le macaron était très frais, nous l'avons acheté.",
          "Si tu connais macaron, tu feras mieux tes courses.",
          "Même si je connais déjà macaron, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé macaron, je pourrai l'utiliser plus naturellement.",
          "Puisque macaron est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le macaron dans une phrase claire.",
        ],
      },
    },
    {
      word: "mille-feuille",
      image: "mille-feuille.webp",
      article: "le",
      gender: "m",
      group: "Pâtisseries",
      definition: ["Pâtisserie avec des couches de pâte et de crème."],
      definitionPivot: {
        en: "A pastry with layers of puff pastry and cream.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le mille-feuille à la boulangerie.",
          "Demain, je vais préparer le mille-feuille pour le petit-déjeuner.",
          "Ce matin, elle a mangé le mille-feuille.",
          "Nous avons choisi le mille-feuille parce qu'il était frais.",
          "Ils vont servir le mille-feuille avec le café.",
          "J'ai goûté le mille-feuille pour la première fois.",
          "Elle a coupé le mille-feuille en petits morceaux.",
          "Avant le goûter, nous avons acheté le mille-feuille.",
          "Le vendeur a conseillé le mille-feuille à ma mère.",
          "Les enfants ont appris le mot mille-feuille.",
          "Nous avons associé le mille-feuille à une image.",
          "J'ai ajouté mille-feuille dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le mille-feuille soit simple, il faut savoir le décrire.",
          "Comme le mille-feuille était très frais, nous l'avons acheté.",
          "Si tu connais mille-feuille, tu feras mieux tes courses.",
          "Même si je connais déjà mille-feuille, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé mille-feuille, je pourrai l'utiliser plus naturellement.",
          "Puisque mille-feuille est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le mille-feuille dans une phrase claire.",
        ],
      },
    },
    {
      word: "madeleine",
      image: "madeleine.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Petit gâteau en forme de coquillage."],
      definitionPivot: {
        en: "A small shell-shaped cake.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté la madeleine à la boulangerie.",
          "Demain, je vais préparer la madeleine pour le petit-déjeuner.",
          "Ce matin, elle a mangé la madeleine.",
          "Nous avons choisi la madeleine parce qu'il était frais.",
          "Ils vont servir la madeleine avec le café.",
          "J'ai goûté la madeleine pour la première fois.",
          "Elle a coupé la madeleine en petits morceaux.",
          "Avant le goûter, nous avons acheté la madeleine.",
          "Le vendeur a conseillé la madeleine à ma mère.",
          "Les enfants ont appris le mot madeleine.",
          "Nous avons associé la madeleine à une image.",
          "J'ai ajouté madeleine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la madeleine soit simple, il faut savoir le décrire.",
          "Comme la madeleine était très frais, nous l'avons acheté.",
          "Si tu connais madeleine, tu feras mieux tes courses.",
          "Même si je connais déjà madeleine, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé madeleine, je pourrai l'utiliser plus naturellement.",
          "Puisque madeleine est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser la madeleine dans une phrase claire.",
        ],
      },
    },
    {
      word: "meringue",
      image: "meringue.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Pâtisserie légère et sucrée faite avec des blancs d’œufs."],
      definitionPivot: {
        en: "A light sweet pastry made with egg whites.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté la meringue à la boulangerie.",
          "Demain, je vais préparer la meringue pour le petit-déjeuner.",
          "Ce matin, elle a mangé la meringue.",
          "Nous avons choisi la meringue parce qu'il était frais.",
          "Ils vont servir la meringue avec le café.",
          "J'ai goûté la meringue pour la première fois.",
          "Elle a coupé la meringue en petits morceaux.",
          "Avant le goûter, nous avons acheté la meringue.",
          "Le vendeur a conseillé la meringue à ma mère.",
          "Les enfants ont appris le mot meringue.",
          "Nous avons associé la meringue à une image.",
          "J'ai ajouté meringue dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la meringue soit simple, il faut savoir le décrire.",
          "Comme la meringue était très frais, nous l'avons acheté.",
          "Si tu connais meringue, tu feras mieux tes courses.",
          "Même si je connais déjà meringue, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé meringue, je pourrai l'utiliser plus naturellement.",
          "Puisque meringue est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser la meringue dans une phrase claire.",
        ],
      },
    },
    {
      word: "flan",
      image: "flan.webp",
      article: "le",
      gender: "m",
      group: "Pâtisseries",
      definition: ["Tarte ou dessert à la crème onctueuse."],
      definitionPivot: {
        en: "A tart or dessert with smooth cream.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le flan à la boulangerie.",
          "Demain, je vais préparer le flan pour le petit-déjeuner.",
          "Ce matin, elle a mangé le flan.",
          "Nous avons choisi le flan parce qu'il était frais.",
          "Ils vont servir le flan avec le café.",
          "J'ai goûté le flan pour la première fois.",
          "Elle a coupé le flan en petits morceaux.",
          "Avant le goûter, nous avons acheté le flan.",
          "Le vendeur a conseillé le flan à ma mère.",
          "Les enfants ont appris le mot flan.",
          "Nous avons associé le flan à une image.",
          "J'ai ajouté flan dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le flan soit simple, il faut savoir le décrire.",
          "Comme le flan était très frais, nous l'avons acheté.",
          "Si tu connais flan, tu feras mieux tes courses.",
          "Même si je connais déjà flan, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé flan, je pourrai l'utiliser plus naturellement.",
          "Puisque flan est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le flan dans une phrase claire.",
        ],
      },
    },
    {
      word: "crêpe",
      image: "crepe.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Fine galette de pâte cuite à la poêle."],
      definitionPivot: {
        en: "A thin pancake cooked in a pan.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté la crêpe à la boulangerie.",
          "Demain, je vais préparer la crêpe pour le petit-déjeuner.",
          "Ce matin, elle a mangé la crêpe.",
          "Nous avons choisi la crêpe parce qu'il était frais.",
          "Ils vont servir la crêpe avec le café.",
          "J'ai goûté la crêpe pour la première fois.",
          "Elle a coupé la crêpe en petits morceaux.",
          "Avant le goûter, nous avons acheté la crêpe.",
          "Le vendeur a conseillé la crêpe à ma mère.",
          "Les enfants ont appris le mot crêpe.",
          "Nous avons associé la crêpe à une image.",
          "J'ai ajouté crêpe dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la crêpe soit simple, il faut savoir le décrire.",
          "Comme la crêpe était très frais, nous l'avons acheté.",
          "Si tu connais crêpe, tu feras mieux tes courses.",
          "Même si je connais déjà crêpe, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé crêpe, je pourrai l'utiliser plus naturellement.",
          "Puisque crêpe est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser la crêpe dans une phrase claire.",
        ],
      },
    },
    {
      word: "gaufre",
      image: "gaufre.webp",
      article: "la",
      gender: "f",
      group: "Pâtisseries",
      definition: ["Pâtisserie croustillante cuite dans un moule à motifs."],
      definitionPivot: {
        en: "A crisp pastry cooked in a patterned iron.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté la gaufre à la boulangerie.",
          "Demain, je vais préparer la gaufre pour le petit-déjeuner.",
          "Ce matin, elle a mangé la gaufre.",
          "Nous avons choisi la gaufre parce qu'il était frais.",
          "Ils vont servir la gaufre avec le café.",
          "J'ai goûté la gaufre pour la première fois.",
          "Elle a coupé la gaufre en petits morceaux.",
          "Avant le goûter, nous avons acheté la gaufre.",
          "Le vendeur a conseillé la gaufre à ma mère.",
          "Les enfants ont appris le mot gaufre.",
          "Nous avons associé la gaufre à une image.",
          "J'ai ajouté gaufre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la gaufre soit simple, il faut savoir le décrire.",
          "Comme la gaufre était très frais, nous l'avons acheté.",
          "Si tu connais gaufre, tu feras mieux tes courses.",
          "Même si je connais déjà gaufre, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé gaufre, je pourrai l'utiliser plus naturellement.",
          "Puisque gaufre est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser la gaufre dans une phrase claire.",
        ],
      },
    },
    {
      word: "biscuit",
      image: "biscuit.webp",
      article: "le",
      gender: "m",
      group: "Biscuits et snacks",
      definition: ["Petit gâteau sec."],
      definitionPivot: {
        en: "A food sold in a bakery.",
        ar: "طعام يُباع في المخبز.",
        fa: "خوراکی که در نانوایی فروخته می‌شود.",
        pt: "Alimento vendido numa padaria.",
        so: "Cunto lagu iibiyo rooti-dubaha.",
        ti: "ኣብ መጋገሪ ዝሽየጥ መግቢ።",
        tr: "Fırında satılan yiyecek.",
        ps: "هغه خواړه چې په نانوايي کې پلورل کېږي.",
        uk: "Їжа, яку продають у пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un biscuit au marché.",
          "Demain, je vais préparer le biscuit pour le repas.",
          "Quand j'étais petit, je mangeais souvent le biscuit.",
          "Ce matin, elle a lavé le biscuit avant de cuisiner.",
          "Nous avons ajouté le biscuit dans la recette.",
          "Ils vont servir le biscuit avec le plat principal.",
          "J'ai choisi un biscuit parce qu'il était frais.",
          "Elle a coupé le biscuit en petits morceaux.",
          "Avant le dîner, nous avons goûté le biscuit.",
          "Le vendeur a conseillé le biscuit à ma mère.",
          "Je vais acheter un biscuit après le travail.",
          "Nous avons gardé le biscuit au réfrigérateur.",
          "Hier soir, mon frère a mangé le biscuit.",
          "Pendant les vacances, nous préparions souvent le biscuit.",
          "Elle a oublié un biscuit dans le sac.",
          "Il va utiliser le biscuit pour faire une sauce.",
          "Nous avons commandé le biscuit au restaurant.",
          "Ce week-end, je vais cuisiner le biscuit.",
          "Le cuisinier a ajouté le biscuit dans l'assiette.",
          "J'ai goûté le biscuit pour la première fois.",
          "Ma sœur a choisi le biscuit pour le dessert.",
          "Ils ont partagé un biscuit à midi.",
          "Nous allons servir le biscuit avec du pain.",
          "Elle a acheté un biscuit pour la recette.",
          "Le client a demandé le biscuit au serveur.",
          "Après la leçon, j'ai utilisé le mot biscuit dans une phrase.",
          "Demain, je vais apprendre à mieux employer le biscuit.",
          "Quand je lis le texte, je cherche le sens de biscuit.",
          "Ce matin, nous avons associé le biscuit à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec biscuit.",
          "Le professeur a demandé un exemple avec le biscuit.",
          "J'ai choisi le biscuit parce que ce mot était dans la liste.",
          "Nous allons réviser le biscuit avant l'évaluation.",
          "Mon camarade a expliqué le biscuit avec ses mots.",
          "J'ai ajouté biscuit dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le biscuit soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le biscuit était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le biscuit, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le biscuit dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le biscuit.",
          "La recette que nous préparons utilise le biscuit pour équilibrer les saveurs.",
          "Pendant que le chef coupait le biscuit, les autres préparaient la table.",
          "Puisque le biscuit était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le biscuit, tu pourras commencer la recette.",
          "Je pense que le biscuit convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le biscuit peut améliorer la présentation.",
          "Le produit dont je parle est le biscuit, que beaucoup de clients apprécient.",
          "Tant que le biscuit restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le biscuit est très demandé en cuisine.",
          "Si le restaurant propose le biscuit, je choisirai ce plat sans hésiter.",
          "Bien que le mot biscuit paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le biscuit apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le biscuit, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà biscuit, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le biscuit.",
          "Lorsque j'aurai mémorisé biscuit, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le biscuit.",
          "Puisque biscuit est utile, je le révise régulièrement.",
        ],
      },
    },
    {
      word: "cookie",
      image: "cookie.webp",
      article: "le",
      gender: "m",
      group: "Biscuits et snacks",
      definition: ["Biscuit souvent aux pépites de chocolat."],
      definitionPivot: {
        en: "A biscuit often with chocolate chips.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le cookie à la boulangerie.",
          "Demain, je vais préparer le cookie pour le petit-déjeuner.",
          "Ce matin, elle a mangé le cookie.",
          "Nous avons choisi le cookie parce qu'il était frais.",
          "Ils vont servir le cookie avec le café.",
          "J'ai goûté le cookie pour la première fois.",
          "Elle a coupé le cookie en petits morceaux.",
          "Avant le goûter, nous avons acheté le cookie.",
          "Le vendeur a conseillé le cookie à ma mère.",
          "Les enfants ont appris le mot cookie.",
          "Nous avons associé le cookie à une image.",
          "J'ai ajouté cookie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cookie soit simple, il faut savoir le décrire.",
          "Comme le cookie était très frais, nous l'avons acheté.",
          "Si tu connais cookie, tu feras mieux tes courses.",
          "Même si je connais déjà cookie, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé cookie, je pourrai l'utiliser plus naturellement.",
          "Puisque cookie est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le cookie dans une phrase claire.",
        ],
      },
    },
    {
      word: "muffin",
      image: "muffin.webp",
      article: "le",
      gender: "m",
      group: "Biscuits et snacks",
      definition: ["Petit gâteau individual cuit dans un moule."],
      definitionPivot: {
        en: "A small individual cake baked in a mold.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le muffin à la boulangerie.",
          "Demain, je vais préparer le muffin pour le petit-déjeuner.",
          "Ce matin, elle a mangé le muffin.",
          "Nous avons choisi le muffin parce qu'il était frais.",
          "Ils vont servir le muffin avec le café.",
          "J'ai goûté le muffin pour la première fois.",
          "Elle a coupé le muffin en petits morceaux.",
          "Avant le goûter, nous avons acheté le muffin.",
          "Le vendeur a conseillé le muffin à ma mère.",
          "Les enfants ont appris le mot muffin.",
          "Nous avons associé le muffin à une image.",
          "J'ai ajouté muffin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le muffin soit simple, il faut savoir le décrire.",
          "Comme le muffin était très frais, nous l'avons acheté.",
          "Si tu connais muffin, tu feras mieux tes courses.",
          "Même si je connais déjà muffin, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé muffin, je pourrai l'utiliser plus naturellement.",
          "Puisque muffin est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le muffin dans une phrase claire.",
        ],
      },
    },
    {
      word: "donut",
      image: "donut.webp",
      article: "le",
      gender: "m",
      group: "Biscuits et snacks",
      definition: ["Beignet rond avec un trou au milieu, souvent glacé."],
      definitionPivot: {
        en: "A round doughnut with a hole, often iced.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le donut à la boulangerie.",
          "Demain, je vais préparer le donut pour le petit-déjeuner.",
          "Ce matin, elle a mangé le donut.",
          "Nous avons choisi le donut parce qu'il était frais.",
          "Ils vont servir le donut avec le café.",
          "J'ai goûté le donut pour la première fois.",
          "Elle a coupé le donut en petits morceaux.",
          "Avant le goûter, nous avons acheté le donut.",
          "Le vendeur a conseillé le donut à ma mère.",
          "Les enfants ont appris le mot donut.",
          "Nous avons associé le donut à une image.",
          "J'ai ajouté donut dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le donut soit simple, il faut savoir le décrire.",
          "Comme le donut était très frais, nous l'avons acheté.",
          "Si tu connais donut, tu feras mieux tes courses.",
          "Même si je connais déjà donut, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé donut, je pourrai l'utiliser plus naturellement.",
          "Puisque donut est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le donut dans une phrase claire.",
        ],
      },
    },
    {
      word: "cupcake",
      image: "cupcake.webp",
      article: "le",
      gender: "m",
      group: "Biscuits et snacks",
      definition: ["Petit gâteau individuel décoré de crème."],
      definitionPivot: {
        en: "A small individual cake topped with frosting.",
        ar: "طعام من المخبز.",
        fa: "خوراکی از نانوایی.",
        pt: "Alimento de padaria.",
        so: "Cunto rooti-dubaha.",
        ti: "ካብ መጋገሪ መግቢ።",
        tr: "Fırın yiyeceği.",
        ps: "د نانوايي خواړه.",
        uk: "Виріб з пекарні.",
      },
      synonym: [],
      exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté le cupcake à la boulangerie.",
          "Demain, je vais préparer le cupcake pour le petit-déjeuner.",
          "Ce matin, elle a mangé le cupcake.",
          "Nous avons choisi le cupcake parce qu'il était frais.",
          "Ils vont servir le cupcake avec le café.",
          "J'ai goûté le cupcake pour la première fois.",
          "Elle a coupé le cupcake en petits morceaux.",
          "Avant le goûter, nous avons acheté le cupcake.",
          "Le vendeur a conseillé le cupcake à ma mère.",
          "Les enfants ont appris le mot cupcake.",
          "Nous avons associé le cupcake à une image.",
          "J'ai ajouté cupcake dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le cupcake soit simple, il faut savoir le décrire.",
          "Comme le cupcake était très frais, nous l'avons acheté.",
          "Si tu connais cupcake, tu feras mieux tes courses.",
          "Même si je connais déjà cupcake, je dois encore l'employer correctement.",
          "Lorsque j'aurai mémorisé cupcake, je pourrai l'utiliser plus naturellement.",
          "Puisque cupcake est utile, je le révise régulièrement.",
          "Le professeur nous demande d'utiliser le cupcake dans une phrase claire.",
        ],
      },
    },
  ],
  sentences: [
    { sentence: "Il achète une ___ fraîche chaque matin.",                answer: "baguette" },
    { sentence: "Je prends un ___ au chocolat pour le petit-déjeuner.",   answer: "pain au chocolat" },
    { sentence: "La ___ est très moelleuse et dorée.",                    answer: "brioche" },
    { sentence: "Elle a commandé un ___ au citron pour le goûter.",       answer: "éclair" },
    { sentence: "Le boulanger prépare des ___ fraîches pour la vitrine.", answer: "viennoiserie" },
  ],
};
