import type { VocabTheme } from "../../vocabulary-data";

export const V2_HEURE_THEME: VocabTheme = {
  slug: "v2-heure",
  code: "V2.2",
  title: "L'heure",
  section: "V2",
  words: [
    { word: "heure", image: "heure.webp",      article: "l'",  gender: "f", definition: "L'heure est unité de temps de 60 minutes." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié l'heure en classe.",
          "Demain, je vais revoir l'heure.",
          "Quand j'étais débutant, je confondais souvent heure.",
          "Ce matin, le professeur a expliqué l'heure.",
          "Nous avons utilisé l'heure dans un exercice.",
          "Ils vont apprendre heure cette semaine.",
          "J'ai choisi l'heure parce que c'était utile.",
          "Elle a écrit heure dans son cahier.",
          "Avant le test, nous avons répété heure.",
          "Le groupe a parlé de l'heure pendant le cours.",
          "Je vais pratiquer heure après le repas.",
          "Nous avons corrigé une phrase avec heure.",
          "Hier soir, mon frère a révisé l'heure.",
          "Pendant les vacances, je revoyais souvent heure.",
          "Elle a oublié heure pendant l'exercice.",
          "Il va utiliser l'heure dans sa phrase.",
          "Nous avons trouvé heure dans le texte.",
          "Ce week-end, je vais mémoriser heure.",
          "L'élève a ajouté heure dans sa réponse.",
          "J'ai compris heure pour la première fois.",
          "Ma sœur a choisi l'heure pour son exemple.",
          "Ils ont répété heure à voix haute.",
          "Nous allons revoir l'heure avec le professeur.",
          "Elle a noté heure pour ne pas l'oublier.",
          "La classe a demandé l'heure au tableau.",
          "Après la leçon, j'ai utilisé le mot heure dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'heure.",
          "Quand je lis le texte, je cherche le sens de heure.",
          "Ce matin, nous avons associé l'heure à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec heure.",
          "Le professeur a demandé un exemple avec l'heure.",
          "J'ai choisi l'heure parce que ce mot était dans la liste.",
          "Nous allons réviser l'heure avant l'évaluation.",
          "Mon camarade a expliqué l'heure avec ses mots.",
          "J'ai ajouté heure dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que heure semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'heure revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises heure, tu comprendras mieux les textes du calendrier.",
          "Même si je connais heure, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'heure comme exemple.",
          "La leçon que nous travaillons utilise heure dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'heure, les élèves prenaient des notes.",
          "Puisque heure était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé heure, tu pourras passer à la suite.",
          "Je pense que l'heure aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, heure peut être important.",
          "Le mot dont je parle est heure, que la classe doit retenir.",
          "Tant que tu pratiqueras heure, tu feras des progrès.",
          "Bien que heure demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient heure, je lirai la consigne avec soin.",
          "Bien que le mot heure paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'heure apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'heure, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà heure, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'heure.",
          "Lorsque j'aurai mémorisé heure, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'heure.",
          "Puisque heure est utile, je le révise régulièrement.",
        ],
      } },
    { word: "minute", image: "minute.webp",     article: "la",  gender: "f", definition: "La minute est unité de temps de 60 secondes." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié la minute en classe.",
          "Demain, je vais revoir la minute.",
          "Quand j'étais débutant, je confondais souvent minute.",
          "Ce matin, le professeur a expliqué la minute.",
          "Nous avons utilisé la minute dans un exercice.",
          "Ils vont apprendre minute cette semaine.",
          "J'ai choisi la minute parce que c'était utile.",
          "Elle a écrit minute dans son cahier.",
          "Avant le test, nous avons répété minute.",
          "Le groupe a parlé de la minute pendant le cours.",
          "Je vais pratiquer minute après le repas.",
          "Nous avons corrigé une phrase avec minute.",
          "Hier soir, mon frère a révisé la minute.",
          "Pendant les vacances, je revoyais souvent minute.",
          "Elle a oublié minute pendant l'exercice.",
          "Il va utiliser la minute dans sa phrase.",
          "Nous avons trouvé minute dans le texte.",
          "Ce week-end, je vais mémoriser minute.",
          "L'élève a ajouté minute dans sa réponse.",
          "J'ai compris minute pour la première fois.",
          "Ma sœur a choisi la minute pour son exemple.",
          "Ils ont répété minute à voix haute.",
          "Nous allons revoir la minute avec le professeur.",
          "Elle a noté minute pour ne pas l'oublier.",
          "La classe a demandé la minute au tableau.",
          "Après la leçon, j'ai utilisé le mot minute dans une phrase.",
          "Demain, je vais apprendre à mieux employer la minute.",
          "Quand je lis le texte, je cherche le sens de minute.",
          "Ce matin, nous avons associé la minute à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec minute.",
          "Le professeur a demandé un exemple avec la minute.",
          "J'ai choisi la minute parce que ce mot était dans la liste.",
          "Nous allons réviser la minute avant l'évaluation.",
          "Mon camarade a expliqué la minute avec ses mots.",
          "J'ai ajouté minute dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que minute semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme la minute revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises minute, tu comprendras mieux les textes du calendrier.",
          "Même si je connais minute, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi la minute comme exemple.",
          "La leçon que nous travaillons utilise minute dans plusieurs phrases.",
          "Pendant que le professeur expliquait la minute, les élèves prenaient des notes.",
          "Puisque minute était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé minute, tu pourras passer à la suite.",
          "Je pense que la minute aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, minute peut être important.",
          "Le mot dont je parle est minute, que la classe doit retenir.",
          "Tant que tu pratiqueras minute, tu feras des progrès.",
          "Bien que minute demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient minute, je lirai la consigne avec soin.",
          "Bien que le mot minute paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la minute apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la minute, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà minute, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la minute.",
          "Lorsque j'aurai mémorisé minute, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la minute.",
          "Puisque minute est utile, je le révise régulièrement.",
        ],
      } },
    { word: "seconde", image: "seconde.webp",    article: "la",  gender: "f", definition: "La seconde est unité de temps la plus courte." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié la seconde en classe.",
          "Demain, je vais revoir la seconde.",
          "Quand j'étais débutant, je confondais souvent seconde.",
          "Ce matin, le professeur a expliqué la seconde.",
          "Nous avons utilisé la seconde dans un exercice.",
          "Ils vont apprendre seconde cette semaine.",
          "J'ai choisi la seconde parce que c'était utile.",
          "Elle a écrit seconde dans son cahier.",
          "Avant le test, nous avons répété seconde.",
          "Le groupe a parlé de la seconde pendant le cours.",
          "Je vais pratiquer seconde après le repas.",
          "Nous avons corrigé une phrase avec seconde.",
          "Hier soir, mon frère a révisé la seconde.",
          "Pendant les vacances, je revoyais souvent seconde.",
          "Elle a oublié seconde pendant l'exercice.",
          "Il va utiliser la seconde dans sa phrase.",
          "Nous avons trouvé seconde dans le texte.",
          "Ce week-end, je vais mémoriser seconde.",
          "L'élève a ajouté seconde dans sa réponse.",
          "J'ai compris seconde pour la première fois.",
          "Ma sœur a choisi la seconde pour son exemple.",
          "Ils ont répété seconde à voix haute.",
          "Nous allons revoir la seconde avec le professeur.",
          "Elle a noté seconde pour ne pas l'oublier.",
          "La classe a demandé la seconde au tableau.",
          "Après la leçon, j'ai utilisé le mot seconde dans une phrase.",
          "Demain, je vais apprendre à mieux employer la seconde.",
          "Quand je lis le texte, je cherche le sens de seconde.",
          "Ce matin, nous avons associé la seconde à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec seconde.",
          "Le professeur a demandé un exemple avec la seconde.",
          "J'ai choisi la seconde parce que ce mot était dans la liste.",
          "Nous allons réviser la seconde avant l'évaluation.",
          "Mon camarade a expliqué la seconde avec ses mots.",
          "J'ai ajouté seconde dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que seconde semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme la seconde revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises seconde, tu comprendras mieux les textes du calendrier.",
          "Même si je connais seconde, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi la seconde comme exemple.",
          "La leçon que nous travaillons utilise seconde dans plusieurs phrases.",
          "Pendant que le professeur expliquait la seconde, les élèves prenaient des notes.",
          "Puisque seconde était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé seconde, tu pourras passer à la suite.",
          "Je pense que la seconde aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, seconde peut être important.",
          "Le mot dont je parle est seconde, que la classe doit retenir.",
          "Tant que tu pratiqueras seconde, tu feras des progrès.",
          "Bien que seconde demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient seconde, je lirai la consigne avec soin.",
          "Bien que le mot seconde paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la seconde apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la seconde, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà seconde, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la seconde.",
          "Lorsque j'aurai mémorisé seconde, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la seconde.",
          "Puisque seconde est utile, je le révise régulièrement.",
        ],
      } },
    { word: "matin", image: "matin.webp",      article: "le",  gender: "m", definition: "Le matin est début de la journée." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié le matin en classe.",
          "Demain, je vais revoir le matin.",
          "Quand j'étais débutant, je confondais souvent matin.",
          "Ce matin, le professeur a expliqué le matin.",
          "Nous avons utilisé le matin dans un exercice.",
          "Ils vont apprendre matin cette semaine.",
          "J'ai choisi le matin parce que c'était utile.",
          "Elle a écrit matin dans son cahier.",
          "Avant le test, nous avons répété matin.",
          "Le groupe a parlé du matin pendant le cours.",
          "Je vais pratiquer matin après le repas.",
          "Nous avons corrigé une phrase avec matin.",
          "Hier soir, mon frère a révisé le matin.",
          "Pendant les vacances, je revoyais souvent matin.",
          "Elle a oublié matin pendant l'exercice.",
          "Il va utiliser le matin dans sa phrase.",
          "Nous avons trouvé matin dans le texte.",
          "Ce week-end, je vais mémoriser matin.",
          "L'élève a ajouté matin dans sa réponse.",
          "J'ai compris matin pour la première fois.",
          "Ma sœur a choisi le matin pour son exemple.",
          "Ils ont répété matin à voix haute.",
          "Nous allons revoir le matin avec le professeur.",
          "Elle a noté matin pour ne pas l'oublier.",
          "La classe a demandé le matin au tableau.",
          "Après la leçon, j'ai utilisé le mot matin dans une phrase.",
          "Demain, je vais apprendre à mieux employer le matin.",
          "Quand je lis le texte, je cherche le sens de matin.",
          "Ce matin, nous avons associé le matin à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec matin.",
          "Le professeur a demandé un exemple avec le matin.",
          "J'ai choisi le matin parce que ce mot était dans la liste.",
          "Nous allons réviser le matin avant l'évaluation.",
          "Mon camarade a expliqué le matin avec ses mots.",
          "J'ai ajouté matin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que matin semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le matin revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises matin, tu comprendras mieux les textes du calendrier.",
          "Même si je connais matin, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le matin comme exemple.",
          "La leçon que nous travaillons utilise matin dans plusieurs phrases.",
          "Pendant que le professeur expliquait le matin, les élèves prenaient des notes.",
          "Puisque matin était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé matin, tu pourras passer à la suite.",
          "Je pense que le matin aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, matin peut être important.",
          "Le mot dont je parle est matin, que la classe doit retenir.",
          "Tant que tu pratiqueras matin, tu feras des progrès.",
          "Bien que matin demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient matin, je lirai la consigne avec soin.",
          "Bien que le mot matin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le matin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le matin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà matin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le matin.",
          "Lorsque j'aurai mémorisé matin, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le matin.",
          "Puisque matin est utile, je le révise régulièrement.",
        ],
      } },
    { word: "midi", image: "midi.webp",       article: "le",  gender: "m", definition: "Le midi est 12 heures, milieu de la journée." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié le midi en classe.",
          "Demain, je vais revoir le midi.",
          "Quand j'étais débutant, je confondais souvent midi.",
          "Ce matin, le professeur a expliqué le midi.",
          "Nous avons utilisé le midi dans un exercice.",
          "Ils vont apprendre midi cette semaine.",
          "J'ai choisi le midi parce que c'était utile.",
          "Elle a écrit midi dans son cahier.",
          "Avant le test, nous avons répété midi.",
          "Le groupe a parlé du midi pendant le cours.",
          "Je vais pratiquer midi après le repas.",
          "Nous avons corrigé une phrase avec midi.",
          "Hier soir, mon frère a révisé le midi.",
          "Pendant les vacances, je revoyais souvent midi.",
          "Elle a oublié midi pendant l'exercice.",
          "Il va utiliser le midi dans sa phrase.",
          "Nous avons trouvé midi dans le texte.",
          "Ce week-end, je vais mémoriser midi.",
          "L'élève a ajouté midi dans sa réponse.",
          "J'ai compris midi pour la première fois.",
          "Ma sœur a choisi le midi pour son exemple.",
          "Ils ont répété midi à voix haute.",
          "Nous allons revoir le midi avec le professeur.",
          "Elle a noté midi pour ne pas l'oublier.",
          "La classe a demandé le midi au tableau.",
          "Après la leçon, j'ai utilisé le mot midi dans une phrase.",
          "Demain, je vais apprendre à mieux employer le midi.",
          "Quand je lis le texte, je cherche le sens de midi.",
          "Ce matin, nous avons associé le midi à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec midi.",
          "Le professeur a demandé un exemple avec le midi.",
          "J'ai choisi le midi parce que ce mot était dans la liste.",
          "Nous allons réviser le midi avant l'évaluation.",
          "Mon camarade a expliqué le midi avec ses mots.",
          "J'ai ajouté midi dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que midi semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le midi revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises midi, tu comprendras mieux les textes du calendrier.",
          "Même si je connais midi, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le midi comme exemple.",
          "La leçon que nous travaillons utilise midi dans plusieurs phrases.",
          "Pendant que le professeur expliquait le midi, les élèves prenaient des notes.",
          "Puisque midi était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé midi, tu pourras passer à la suite.",
          "Je pense que le midi aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, midi peut être important.",
          "Le mot dont je parle est midi, que la classe doit retenir.",
          "Tant que tu pratiqueras midi, tu feras des progrès.",
          "Bien que midi demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient midi, je lirai la consigne avec soin.",
          "Bien que le mot midi paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le midi apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le midi, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà midi, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le midi.",
          "Lorsque j'aurai mémorisé midi, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le midi.",
          "Puisque midi est utile, je le révise régulièrement.",
        ],
      } },
    { word: "après-midi", image: "apres-midi.webp", article: "l'",  gender: "m", definition: "L'après-midi est une partie de la journée après midi." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié l'après-midi en classe.",
          "Demain, je vais revoir l'après-midi.",
          "Quand j'étais débutant, je confondais souvent après-midi.",
          "Ce matin, le professeur a expliqué l'après-midi.",
          "Nous avons utilisé l'après-midi dans un exercice.",
          "Ils vont apprendre après-midi cette semaine.",
          "J'ai choisi l'après-midi parce que c'était utile.",
          "Elle a écrit après-midi dans son cahier.",
          "Avant le test, nous avons répété après-midi.",
          "Le groupe a parlé de l'après-midi pendant le cours.",
          "Je vais pratiquer après-midi après le repas.",
          "Nous avons corrigé une phrase avec après-midi.",
          "Hier soir, mon frère a révisé l'après-midi.",
          "Pendant les vacances, je revoyais souvent après-midi.",
          "Elle a oublié après-midi pendant l'exercice.",
          "Il va utiliser l'après-midi dans sa phrase.",
          "Nous avons trouvé après-midi dans le texte.",
          "Ce week-end, je vais mémoriser après-midi.",
          "L'élève a ajouté après-midi dans sa réponse.",
          "J'ai compris après-midi pour la première fois.",
          "Ma sœur a choisi l'après-midi pour son exemple.",
          "Ils ont répété après-midi à voix haute.",
          "Nous allons revoir l'après-midi avec le professeur.",
          "Elle a noté après-midi pour ne pas l'oublier.",
          "La classe a demandé l'après-midi au tableau.",
          "Après la leçon, j'ai utilisé le mot après-midi dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'après-midi.",
          "Quand je lis le texte, je cherche le sens de après-midi.",
          "Ce matin, nous avons associé l'après-midi à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec après-midi.",
          "Le professeur a demandé un exemple avec l'après-midi.",
          "J'ai choisi l'après-midi parce que ce mot était dans la liste.",
          "Nous allons réviser l'après-midi avant l'évaluation.",
          "Mon camarade a expliqué l'après-midi avec ses mots.",
          "J'ai ajouté après-midi dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que après-midi semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'après-midi revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises après-midi, tu comprendras mieux les textes du calendrier.",
          "Même si je connais après-midi, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'après-midi comme exemple.",
          "La leçon que nous travaillons utilise après-midi dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'après-midi, les élèves prenaient des notes.",
          "Puisque après-midi était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé après-midi, tu pourras passer à la suite.",
          "Je pense que l'après-midi aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, après-midi peut être important.",
          "Le mot dont je parle est après-midi, que la classe doit retenir.",
          "Tant que tu pratiqueras après-midi, tu feras des progrès.",
          "Bien que après-midi demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient après-midi, je lirai la consigne avec soin.",
          "Bien que le mot après-midi paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'après-midi apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'après-midi, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà après-midi, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'après-midi.",
          "Lorsque j'aurai mémorisé après-midi, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'après-midi.",
          "Puisque après-midi est utile, je le révise régulièrement.",
        ],
      } },
    { word: "soir", image: "soir.webp",       article: "le",  gender: "m", definition: "Le soir est la fin de la journée avant la nuit." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié le soir en classe.",
          "Demain, je vais revoir le soir.",
          "Quand j'étais débutant, je confondais souvent soir.",
          "Ce matin, le professeur a expliqué le soir.",
          "Nous avons utilisé le soir dans un exercice.",
          "Ils vont apprendre soir cette semaine.",
          "J'ai choisi le soir parce que c'était utile.",
          "Elle a écrit soir dans son cahier.",
          "Avant le test, nous avons répété soir.",
          "Le groupe a parlé du soir pendant le cours.",
          "Je vais pratiquer soir après le repas.",
          "Nous avons corrigé une phrase avec soir.",
          "Hier soir, mon frère a révisé le soir.",
          "Pendant les vacances, je revoyais souvent soir.",
          "Elle a oublié soir pendant l'exercice.",
          "Il va utiliser le soir dans sa phrase.",
          "Nous avons trouvé soir dans le texte.",
          "Ce week-end, je vais mémoriser soir.",
          "L'élève a ajouté soir dans sa réponse.",
          "J'ai compris soir pour la première fois.",
          "Ma sœur a choisi le soir pour son exemple.",
          "Ils ont répété soir à voix haute.",
          "Nous allons revoir le soir avec le professeur.",
          "Elle a noté soir pour ne pas l'oublier.",
          "La classe a demandé le soir au tableau.",
          "Après la leçon, j'ai utilisé le mot soir dans une phrase.",
          "Demain, je vais apprendre à mieux employer le soir.",
          "Quand je lis le texte, je cherche le sens de soir.",
          "Ce matin, nous avons associé le soir à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec soir.",
          "Le professeur a demandé un exemple avec le soir.",
          "J'ai choisi le soir parce que ce mot était dans la liste.",
          "Nous allons réviser le soir avant l'évaluation.",
          "Mon camarade a expliqué le soir avec ses mots.",
          "J'ai ajouté soir dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que soir semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le soir revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises soir, tu comprendras mieux les textes du calendrier.",
          "Même si je connais soir, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le soir comme exemple.",
          "La leçon que nous travaillons utilise soir dans plusieurs phrases.",
          "Pendant que le professeur expliquait le soir, les élèves prenaient des notes.",
          "Puisque soir était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé soir, tu pourras passer à la suite.",
          "Je pense que le soir aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, soir peut être important.",
          "Le mot dont je parle est soir, que la classe doit retenir.",
          "Tant que tu pratiqueras soir, tu feras des progrès.",
          "Bien que soir demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient soir, je lirai la consigne avec soin.",
          "Bien que le mot soir paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le soir apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le soir, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà soir, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le soir.",
          "Lorsque j'aurai mémorisé soir, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le soir.",
          "Puisque soir est utile, je le révise régulièrement.",
        ],
      } },
    { word: "minuit", image: "minuit.webp",     article: "le",  gender: "m", definition: "Le minuit est 24 heures, milieu de la nuit." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié le minuit en classe.",
          "Demain, je vais revoir le minuit.",
          "Quand j'étais débutant, je confondais souvent minuit.",
          "Ce matin, le professeur a expliqué le minuit.",
          "Nous avons utilisé le minuit dans un exercice.",
          "Ils vont apprendre minuit cette semaine.",
          "J'ai choisi le minuit parce que c'était utile.",
          "Elle a écrit minuit dans son cahier.",
          "Avant le test, nous avons répété minuit.",
          "Le groupe a parlé du minuit pendant le cours.",
          "Je vais pratiquer minuit après le repas.",
          "Nous avons corrigé une phrase avec minuit.",
          "Hier soir, mon frère a révisé le minuit.",
          "Pendant les vacances, je revoyais souvent minuit.",
          "Elle a oublié minuit pendant l'exercice.",
          "Il va utiliser le minuit dans sa phrase.",
          "Nous avons trouvé minuit dans le texte.",
          "Ce week-end, je vais mémoriser minuit.",
          "L'élève a ajouté minuit dans sa réponse.",
          "J'ai compris minuit pour la première fois.",
          "Ma sœur a choisi le minuit pour son exemple.",
          "Ils ont répété minuit à voix haute.",
          "Nous allons revoir le minuit avec le professeur.",
          "Elle a noté minuit pour ne pas l'oublier.",
          "La classe a demandé le minuit au tableau.",
          "Après la leçon, j'ai utilisé le mot minuit dans une phrase.",
          "Demain, je vais apprendre à mieux employer le minuit.",
          "Quand je lis le texte, je cherche le sens de minuit.",
          "Ce matin, nous avons associé le minuit à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec minuit.",
          "Le professeur a demandé un exemple avec le minuit.",
          "J'ai choisi le minuit parce que ce mot était dans la liste.",
          "Nous allons réviser le minuit avant l'évaluation.",
          "Mon camarade a expliqué le minuit avec ses mots.",
          "J'ai ajouté minuit dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que minuit semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme le minuit revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises minuit, tu comprendras mieux les textes du calendrier.",
          "Même si je connais minuit, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi le minuit comme exemple.",
          "La leçon que nous travaillons utilise minuit dans plusieurs phrases.",
          "Pendant que le professeur expliquait le minuit, les élèves prenaient des notes.",
          "Puisque minuit était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé minuit, tu pourras passer à la suite.",
          "Je pense que le minuit aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, minuit peut être important.",
          "Le mot dont je parle est minuit, que la classe doit retenir.",
          "Tant que tu pratiqueras minuit, tu feras des progrès.",
          "Bien que minuit demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient minuit, je lirai la consigne avec soin.",
          "Bien que le mot minuit paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le minuit apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le minuit, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà minuit, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le minuit.",
          "Lorsque j'aurai mémorisé minuit, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le minuit.",
          "Puisque minuit est utile, je le révise régulièrement.",
        ],
      } },
    { word: "horloge", image: "horloge.webp",    article: "l'",  gender: "f", definition: "L'horloge est une grande pendule fixée au mur." , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai étudié l'horloge en classe.",
          "Demain, je vais revoir l'horloge.",
          "Quand j'étais débutant, je confondais souvent horloge.",
          "Ce matin, le professeur a expliqué l'horloge.",
          "Nous avons utilisé l'horloge dans un exercice.",
          "Ils vont apprendre horloge cette semaine.",
          "J'ai choisi l'horloge parce que c'était utile.",
          "Elle a écrit horloge dans son cahier.",
          "Avant le test, nous avons répété horloge.",
          "Le groupe a parlé de l'horloge pendant le cours.",
          "Je vais pratiquer horloge après le repas.",
          "Nous avons corrigé une phrase avec horloge.",
          "Hier soir, mon frère a révisé l'horloge.",
          "Pendant les vacances, je revoyais souvent horloge.",
          "Elle a oublié horloge pendant l'exercice.",
          "Il va utiliser l'horloge dans sa phrase.",
          "Nous avons trouvé horloge dans le texte.",
          "Ce week-end, je vais mémoriser horloge.",
          "L'élève a ajouté horloge dans sa réponse.",
          "J'ai compris horloge pour la première fois.",
          "Ma sœur a choisi l'horloge pour son exemple.",
          "Ils ont répété horloge à voix haute.",
          "Nous allons revoir l'horloge avec le professeur.",
          "Elle a noté horloge pour ne pas l'oublier.",
          "La classe a demandé l'horloge au tableau.",
          "Après la leçon, j'ai utilisé le mot horloge dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'horloge.",
          "Quand je lis le texte, je cherche le sens de horloge.",
          "Ce matin, nous avons associé l'horloge à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec horloge.",
          "Le professeur a demandé un exemple avec l'horloge.",
          "J'ai choisi l'horloge parce que ce mot était dans la liste.",
          "Nous allons réviser l'horloge avant l'évaluation.",
          "Mon camarade a expliqué l'horloge avec ses mots.",
          "J'ai ajouté horloge dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que horloge semble simple, il faut l'utiliser dans le bon contexte.",
          "Comme l'horloge revient souvent, le professeur l'a expliqué plusieurs fois.",
          "Si tu maîtrises horloge, tu comprendras mieux les textes du calendrier.",
          "Même si je connais horloge, je dois encore le placer correctement dans une phrase.",
          "L'élève, qui voulait progresser, a choisi l'horloge comme exemple.",
          "La leçon que nous travaillons utilise horloge dans plusieurs phrases.",
          "Pendant que le professeur expliquait l'horloge, les élèves prenaient des notes.",
          "Puisque horloge était difficile, nous avons fait un exercice supplémentaire.",
          "Lorsque tu auras révisé horloge, tu pourras passer à la suite.",
          "Je pense que l'horloge aide les élèves parce que cela donne un repère clair.",
          "Même quand l'exercice est court, horloge peut être important.",
          "Le mot dont je parle est horloge, que la classe doit retenir.",
          "Tant que tu pratiqueras horloge, tu feras des progrès.",
          "Bien que horloge demande de l'attention, il devient plus facile avec l'habitude.",
          "Si l'exercice contient horloge, je lirai la consigne avec soin.",
          "Bien que le mot horloge paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'horloge apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'horloge, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà horloge, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'horloge.",
          "Lorsque j'aurai mémorisé horloge, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'horloge.",
          "Puisque horloge est utile, je le révise régulièrement.",
        ],
      } },
  ],
  theory: [
    {
      type: "section",
      title: "Comment lire l'heure",
      items: [
        "Pour demander l'heure : Quelle heure est-il ? / Il est quelle heure ?",
        "Pour répondre : Il est + heure.",
      ],
    },
    {
      type: "table",
      headers: ["Heure officielle", "Heure informelle", "Expression clé"],
      rows: [
        ["8h00",  "huit heures (du matin)",      "pile"],
        ["8h15",  "huit heures et quart",         "et quart"],
        ["8h30",  "huit heures et demie",         "et demie"],
        ["8h45",  "neuf heures moins le quart",   "moins le quart"],
        ["12h00", "midi",                          "—"],
        ["0h00",  "minuit",                        "—"],
      ],
    },
    {
      type: "clocks",
      cols: 4,
      items: [
        { h: 8,  m: 0,  label: "8h00 — pile" },
        { h: 8,  m: 15, label: "8h15 — et quart" },
        { h: 8,  m: 30, label: "8h30 — et demie" },
        { h: 8,  m: 45, label: "8h45 — moins le quart" },
      ],
    },
    {
      type: "note",
      text: "Heure officielle (formelle) : 14h30 = quatorze heures trente. Heure informelle : 14h30 = deux heures et demie de l'après-midi.",
    },
  ],
  sentences: [
    { sentence: "Je me lève à sept heures du ___.",                     answer: "matin" },
    { sentence: "Il mange toujours à ___, quand les cloches sonnent.",   answer: "midi" },
    { sentence: "Mon ___ sonne à 6 h 30 chaque jour.",                  answer: "réveil" },
    { sentence: "Elle arrive souvent ___ au bureau.",                    answer: "en retard" },
    { sentence: "Il est ___, je dois rentrer à la maison.",              answer: "tard" },
  ],
};
