import type { VocabTheme } from "../../vocabulary-data";

export const V8_MALADIES_THEME: VocabTheme = {
  slug: "v8-maladies",
  code: "V8.2",
  title: "Les maladies",
  section: "V8",
  words: [
    { word: "rhume",        image: "rhume.webp",    article: "le",  gender: "m", definition: ["Petite maladie avec le nez qui coule, parfois de la toux."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du rhume au patient.",
          "Demain, je vais revoir le mot rhume.",
          "Quand j'étais malade, j'ai entendu parler du rhume.",
          "Ce matin, le pharmacien a expliqué le rhume.",
          "Nous avons utilisé rhume dans une phrase.",
          "Ils vont apprendre rhume cette semaine.",
          "J'ai choisi le rhume parce que ce mot était utile.",
          "Elle a noté rhume dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec rhume.",
          "Le groupe a parlé du rhume pendant le cours.",
          "Je vais demander des informations sur le rhume.",
          "Nous avons associé le rhume à une image.",
          "Hier soir, mon frère a cherché le sens de rhume.",
          "Pendant l'exercice, je confondais encore rhume.",
          "Elle a oublié le mot rhume pendant la dictée.",
          "Il va utiliser rhume dans sa réponse.",
          "Nous avons trouvé le rhume dans le dialogue médical.",
          "Ce week-end, je vais mémoriser rhume.",
          "L'élève a ajouté rhume dans sa phrase.",
          "J'ai compris rhume pour la première fois.",
          "Ma sœur a demandé un exemple avec rhume.",
          "Ils ont répété rhume à voix haute.",
          "Nous allons revoir le rhume avec le professeur.",
          "Elle a écrit rhume sans aide.",
          "La classe a demandé une définition de rhume.",
          "Après la leçon, j'ai utilisé le mot rhume dans une phrase.",
          "Demain, je vais apprendre à mieux employer le rhume.",
          "Quand je lis le texte, je cherche le sens de rhume.",
          "Ce matin, nous avons associé le rhume à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec rhume.",
          "Le professeur a demandé un exemple avec le rhume.",
          "J'ai choisi le rhume parce que ce mot était dans la liste.",
          "Nous allons réviser le rhume avant l'évaluation.",
          "Mon camarade a expliqué le rhume avec ses mots.",
          "J'ai ajouté rhume dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le rhume semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le rhume apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais rhume, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà rhume, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le rhume avec des mots simples.",
          "La leçon que nous travaillons utilise rhume dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du rhume, le client posait des questions.",
          "Puisque rhume est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé rhume, tu comprendras mieux les consignes du médecin.",
          "Je pense que le rhume aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, rhume peut donner une information importante.",
          "Le mot dont je parle est rhume, que la classe doit retenir.",
          "Tant que tu pratiqueras rhume, tu parleras de santé plus facilement.",
          "Bien que le rhume demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient rhume, je penserai au vocabulaire médical.",
          "Bien que le mot rhume paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le rhume apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le rhume, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le rhume.",
          "Lorsque j'aurai mémorisé rhume, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le rhume.",
          "Puisque rhume est utile, je le révise régulièrement.",
        ],
      } },
    { word: "grippe",       image: "grippe.webp",   article: "la",  gender: "f", definition: ["Maladie avec de la fièvre, de la fatigue et des douleurs."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la grippe au patient.",
          "Demain, je vais revoir le mot grippe.",
          "Quand j'étais malade, j'ai entendu parler de la grippe.",
          "Ce matin, le pharmacien a expliqué la grippe.",
          "Nous avons utilisé grippe dans une phrase.",
          "Ils vont apprendre grippe cette semaine.",
          "J'ai choisi la grippe parce que ce mot était utile.",
          "Elle a noté grippe dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec grippe.",
          "Le groupe a parlé de la grippe pendant le cours.",
          "Je vais demander des informations sur la grippe.",
          "Nous avons associé la grippe à une image.",
          "Hier soir, mon frère a cherché le sens de grippe.",
          "Pendant l'exercice, je confondais encore grippe.",
          "Elle a oublié le mot grippe pendant la dictée.",
          "Il va utiliser grippe dans sa réponse.",
          "Nous avons trouvé la grippe dans le dialogue médical.",
          "Ce week-end, je vais mémoriser grippe.",
          "L'élève a ajouté grippe dans sa phrase.",
          "J'ai compris grippe pour la première fois.",
          "Ma sœur a demandé un exemple avec grippe.",
          "Ils ont répété grippe à voix haute.",
          "Nous allons revoir la grippe avec le professeur.",
          "Elle a écrit grippe sans aide.",
          "La classe a demandé une définition de grippe.",
          "Après la leçon, j'ai utilisé le mot grippe dans une phrase.",
          "Demain, je vais apprendre à mieux employer la grippe.",
          "Quand je lis le texte, je cherche le sens de grippe.",
          "Ce matin, nous avons associé la grippe à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec grippe.",
          "Le professeur a demandé un exemple avec la grippe.",
          "J'ai choisi la grippe parce que ce mot était dans la liste.",
          "Nous allons réviser la grippe avant l'évaluation.",
          "Mon camarade a expliqué la grippe avec ses mots.",
          "J'ai ajouté grippe dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la grippe semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la grippe apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais grippe, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà grippe, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la grippe avec des mots simples.",
          "La leçon que nous travaillons utilise grippe dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la grippe, le client posait des questions.",
          "Puisque grippe est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé grippe, tu comprendras mieux les consignes du médecin.",
          "Je pense que la grippe aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, grippe peut donner une information importante.",
          "Le mot dont je parle est grippe, que la classe doit retenir.",
          "Tant que tu pratiqueras grippe, tu parleras de santé plus facilement.",
          "Bien que la grippe demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient grippe, je penserai au vocabulaire médical.",
          "Bien que le mot grippe paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la grippe apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la grippe, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la grippe.",
          "Lorsque j'aurai mémorisé grippe, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la grippe.",
          "Puisque grippe est utile, je le révise régulièrement.",
        ],
      } },
    { word: "fièvre",       image: "fievre.webp",   article: "la",  gender: "f", definition: ["Température du corps trop élevée."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la fièvre au patient.",
          "Demain, je vais revoir le mot fièvre.",
          "Quand j'étais malade, j'ai entendu parler de la fièvre.",
          "Ce matin, le pharmacien a expliqué la fièvre.",
          "Nous avons utilisé fièvre dans une phrase.",
          "Ils vont apprendre fièvre cette semaine.",
          "J'ai choisi la fièvre parce que ce mot était utile.",
          "Elle a noté fièvre dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec fièvre.",
          "Le groupe a parlé de la fièvre pendant le cours.",
          "Je vais demander des informations sur la fièvre.",
          "Nous avons associé la fièvre à une image.",
          "Hier soir, mon frère a cherché le sens de fièvre.",
          "Pendant l'exercice, je confondais encore fièvre.",
          "Elle a oublié le mot fièvre pendant la dictée.",
          "Il va utiliser fièvre dans sa réponse.",
          "Nous avons trouvé la fièvre dans le dialogue médical.",
          "Ce week-end, je vais mémoriser fièvre.",
          "L'élève a ajouté fièvre dans sa phrase.",
          "J'ai compris fièvre pour la première fois.",
          "Ma sœur a demandé un exemple avec fièvre.",
          "Ils ont répété fièvre à voix haute.",
          "Nous allons revoir la fièvre avec le professeur.",
          "Elle a écrit fièvre sans aide.",
          "La classe a demandé une définition de fièvre.",
          "Après la leçon, j'ai utilisé le mot fièvre dans une phrase.",
          "Demain, je vais apprendre à mieux employer la fièvre.",
          "Quand je lis le texte, je cherche le sens de fièvre.",
          "Ce matin, nous avons associé la fièvre à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec fièvre.",
          "Le professeur a demandé un exemple avec la fièvre.",
          "J'ai choisi la fièvre parce que ce mot était dans la liste.",
          "Nous allons réviser la fièvre avant l'évaluation.",
          "Mon camarade a expliqué la fièvre avec ses mots.",
          "J'ai ajouté fièvre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la fièvre semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la fièvre apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais fièvre, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà fièvre, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la fièvre avec des mots simples.",
          "La leçon que nous travaillons utilise fièvre dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la fièvre, le client posait des questions.",
          "Puisque fièvre est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé fièvre, tu comprendras mieux les consignes du médecin.",
          "Je pense que la fièvre aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, fièvre peut donner une information importante.",
          "Le mot dont je parle est fièvre, que la classe doit retenir.",
          "Tant que tu pratiqueras fièvre, tu parleras de santé plus facilement.",
          "Bien que la fièvre demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient fièvre, je penserai au vocabulaire médical.",
          "Bien que le mot fièvre paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la fièvre apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la fièvre, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la fièvre.",
          "Lorsque j'aurai mémorisé fièvre, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la fièvre.",
          "Puisque fièvre est utile, je le révise régulièrement.",
        ],
      } },
    { word: "douleur",      image: "douleur.webp",  article: "la",  gender: "f", definition: ["Sensation désagréable dans le corps."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la douleur au patient.",
          "Demain, je vais revoir le mot douleur.",
          "Quand j'étais malade, j'ai entendu parler de la douleur.",
          "Ce matin, le pharmacien a expliqué la douleur.",
          "Nous avons utilisé douleur dans une phrase.",
          "Ils vont apprendre douleur cette semaine.",
          "J'ai choisi la douleur parce que ce mot était utile.",
          "Elle a noté douleur dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec douleur.",
          "Le groupe a parlé de la douleur pendant le cours.",
          "Je vais demander des informations sur la douleur.",
          "Nous avons associé la douleur à une image.",
          "Hier soir, mon frère a cherché le sens de douleur.",
          "Pendant l'exercice, je confondais encore douleur.",
          "Elle a oublié le mot douleur pendant la dictée.",
          "Il va utiliser douleur dans sa réponse.",
          "Nous avons trouvé la douleur dans le dialogue médical.",
          "Ce week-end, je vais mémoriser douleur.",
          "L'élève a ajouté douleur dans sa phrase.",
          "J'ai compris douleur pour la première fois.",
          "Ma sœur a demandé un exemple avec douleur.",
          "Ils ont répété douleur à voix haute.",
          "Nous allons revoir la douleur avec le professeur.",
          "Elle a écrit douleur sans aide.",
          "La classe a demandé une définition de douleur.",
          "Après la leçon, j'ai utilisé le mot douleur dans une phrase.",
          "Demain, je vais apprendre à mieux employer la douleur.",
          "Quand je lis le texte, je cherche le sens de douleur.",
          "Ce matin, nous avons associé la douleur à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec douleur.",
          "Le professeur a demandé un exemple avec la douleur.",
          "J'ai choisi la douleur parce que ce mot était dans la liste.",
          "Nous allons réviser la douleur avant l'évaluation.",
          "Mon camarade a expliqué la douleur avec ses mots.",
          "J'ai ajouté douleur dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la douleur semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la douleur apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais douleur, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà douleur, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la douleur avec des mots simples.",
          "La leçon que nous travaillons utilise douleur dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la douleur, le client posait des questions.",
          "Puisque douleur est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé douleur, tu comprendras mieux les consignes du médecin.",
          "Je pense que la douleur aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, douleur peut donner une information importante.",
          "Le mot dont je parle est douleur, que la classe doit retenir.",
          "Tant que tu pratiqueras douleur, tu parleras de santé plus facilement.",
          "Bien que la douleur demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient douleur, je penserai au vocabulaire médical.",
          "Bien que le mot douleur paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la douleur apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la douleur, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la douleur.",
          "Lorsque j'aurai mémorisé douleur, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la douleur.",
          "Puisque douleur est utile, je le révise régulièrement.",
        ],
      } },
    { word: "toux",         image: "toux.webp",     article: "la",  gender: "f", definition: ["Action de tousser quand la gorge ou les poumons sont irrités."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la toux au patient.",
          "Demain, je vais revoir le mot toux.",
          "Quand j'étais malade, j'ai entendu parler de la toux.",
          "Ce matin, le pharmacien a expliqué la toux.",
          "Nous avons utilisé toux dans une phrase.",
          "Ils vont apprendre toux cette semaine.",
          "J'ai choisi la toux parce que ce mot était utile.",
          "Elle a noté toux dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec toux.",
          "Le groupe a parlé de la toux pendant le cours.",
          "Je vais demander des informations sur la toux.",
          "Nous avons associé la toux à une image.",
          "Hier soir, mon frère a cherché le sens de toux.",
          "Pendant l'exercice, je confondais encore toux.",
          "Elle a oublié le mot toux pendant la dictée.",
          "Il va utiliser toux dans sa réponse.",
          "Nous avons trouvé la toux dans le dialogue médical.",
          "Ce week-end, je vais mémoriser toux.",
          "L'élève a ajouté toux dans sa phrase.",
          "J'ai compris toux pour la première fois.",
          "Ma sœur a demandé un exemple avec toux.",
          "Ils ont répété toux à voix haute.",
          "Nous allons revoir la toux avec le professeur.",
          "Elle a écrit toux sans aide.",
          "La classe a demandé une définition de toux.",
          "Après la leçon, j'ai utilisé le mot toux dans une phrase.",
          "Demain, je vais apprendre à mieux employer la toux.",
          "Quand je lis le texte, je cherche le sens de toux.",
          "Ce matin, nous avons associé la toux à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec toux.",
          "Le professeur a demandé un exemple avec la toux.",
          "J'ai choisi la toux parce que ce mot était dans la liste.",
          "Nous allons réviser la toux avant l'évaluation.",
          "Mon camarade a expliqué la toux avec ses mots.",
          "J'ai ajouté toux dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la toux semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la toux apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais toux, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà toux, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la toux avec des mots simples.",
          "La leçon que nous travaillons utilise toux dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la toux, le client posait des questions.",
          "Puisque toux est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé toux, tu comprendras mieux les consignes du médecin.",
          "Je pense que la toux aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, toux peut donner une information importante.",
          "Le mot dont je parle est toux, que la classe doit retenir.",
          "Tant que tu pratiqueras toux, tu parleras de santé plus facilement.",
          "Bien que la toux demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient toux, je penserai au vocabulaire médical.",
          "Bien que le mot toux paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la toux apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la toux, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la toux.",
          "Lorsque j'aurai mémorisé toux, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la toux.",
          "Puisque toux est utile, je le révise régulièrement.",
        ],
      } },
    { word: "allergie",     image: "allergie.webp", article: "l'",  gender: "f", definition: ["Réaction du corps à quelque chose, comme le pollen ou un aliment."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de l'allergie au patient.",
          "Demain, je vais revoir le mot allergie.",
          "Quand j'étais malade, j'ai entendu parler de l'allergie.",
          "Ce matin, le pharmacien a expliqué l'allergie.",
          "Nous avons utilisé allergie dans une phrase.",
          "Ils vont apprendre allergie cette semaine.",
          "J'ai choisi l'allergie parce que ce mot était utile.",
          "Elle a noté allergie dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec allergie.",
          "Le groupe a parlé de l'allergie pendant le cours.",
          "Je vais demander des informations sur l'allergie.",
          "Nous avons associé l'allergie à une image.",
          "Hier soir, mon frère a cherché le sens de allergie.",
          "Pendant l'exercice, je confondais encore allergie.",
          "Elle a oublié le mot allergie pendant la dictée.",
          "Il va utiliser allergie dans sa réponse.",
          "Nous avons trouvé l'allergie dans le dialogue médical.",
          "Ce week-end, je vais mémoriser allergie.",
          "L'élève a ajouté allergie dans sa phrase.",
          "J'ai compris allergie pour la première fois.",
          "Ma sœur a demandé un exemple avec allergie.",
          "Ils ont répété allergie à voix haute.",
          "Nous allons revoir l'allergie avec le professeur.",
          "Elle a écrit allergie sans aide.",
          "La classe a demandé une définition de allergie.",
          "Après la leçon, j'ai utilisé le mot allergie dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'allergie.",
          "Quand je lis le texte, je cherche le sens de allergie.",
          "Ce matin, nous avons associé l'allergie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec allergie.",
          "Le professeur a demandé un exemple avec l'allergie.",
          "J'ai choisi l'allergie parce que ce mot était dans la liste.",
          "Nous allons réviser l'allergie avant l'évaluation.",
          "Mon camarade a expliqué l'allergie avec ses mots.",
          "J'ai ajouté allergie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'allergie semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'allergie apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais allergie, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà allergie, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'allergie avec des mots simples.",
          "La leçon que nous travaillons utilise allergie dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'allergie, le client posait des questions.",
          "Puisque allergie est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé allergie, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'allergie aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, allergie peut donner une information importante.",
          "Le mot dont je parle est allergie, que la classe doit retenir.",
          "Tant que tu pratiqueras allergie, tu parleras de santé plus facilement.",
          "Bien que l'allergie demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient allergie, je penserai au vocabulaire médical.",
          "Bien que le mot allergie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'allergie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'allergie, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'allergie.",
          "Lorsque j'aurai mémorisé allergie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'allergie.",
          "Puisque allergie est utile, je le révise régulièrement.",
        ],
      } },
    { word: "coupure",      image: "coupure.webp",  article: "la",  gender: "f", definition: ["Blessure faite par un objet coupant."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la coupure au patient.",
          "Demain, je vais revoir le mot coupure.",
          "Quand j'étais malade, j'ai entendu parler de la coupure.",
          "Ce matin, le pharmacien a expliqué la coupure.",
          "Nous avons utilisé coupure dans une phrase.",
          "Ils vont apprendre coupure cette semaine.",
          "J'ai choisi la coupure parce que ce mot était utile.",
          "Elle a noté coupure dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec coupure.",
          "Le groupe a parlé de la coupure pendant le cours.",
          "Je vais demander des informations sur la coupure.",
          "Nous avons associé la coupure à une image.",
          "Hier soir, mon frère a cherché le sens de coupure.",
          "Pendant l'exercice, je confondais encore coupure.",
          "Elle a oublié le mot coupure pendant la dictée.",
          "Il va utiliser coupure dans sa réponse.",
          "Nous avons trouvé la coupure dans le dialogue médical.",
          "Ce week-end, je vais mémoriser coupure.",
          "L'élève a ajouté coupure dans sa phrase.",
          "J'ai compris coupure pour la première fois.",
          "Ma sœur a demandé un exemple avec coupure.",
          "Ils ont répété coupure à voix haute.",
          "Nous allons revoir la coupure avec le professeur.",
          "Elle a écrit coupure sans aide.",
          "La classe a demandé une définition de coupure.",
          "Après la leçon, j'ai utilisé le mot coupure dans une phrase.",
          "Demain, je vais apprendre à mieux employer la coupure.",
          "Quand je lis le texte, je cherche le sens de coupure.",
          "Ce matin, nous avons associé la coupure à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec coupure.",
          "Le professeur a demandé un exemple avec la coupure.",
          "J'ai choisi la coupure parce que ce mot était dans la liste.",
          "Nous allons réviser la coupure avant l'évaluation.",
          "Mon camarade a expliqué la coupure avec ses mots.",
          "J'ai ajouté coupure dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la coupure semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la coupure apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais coupure, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà coupure, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la coupure avec des mots simples.",
          "La leçon que nous travaillons utilise coupure dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la coupure, le client posait des questions.",
          "Puisque coupure est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé coupure, tu comprendras mieux les consignes du médecin.",
          "Je pense que la coupure aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, coupure peut donner une information importante.",
          "Le mot dont je parle est coupure, que la classe doit retenir.",
          "Tant que tu pratiqueras coupure, tu parleras de santé plus facilement.",
          "Bien que la coupure demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient coupure, je penserai au vocabulaire médical.",
          "Bien que le mot coupure paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la coupure apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la coupure, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la coupure.",
          "Lorsque j'aurai mémorisé coupure, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la coupure.",
          "Puisque coupure est utile, je le révise régulièrement.",
        ],
      } },
    { word: "brûlure",      image: "brulure.webp",  article: "la",  gender: "f", definition: ["Blessure causée par le feu, la chaleur ou un produit."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la brûlure au patient.",
          "Demain, je vais revoir le mot brûlure.",
          "Quand j'étais malade, j'ai entendu parler de la brûlure.",
          "Ce matin, le pharmacien a expliqué la brûlure.",
          "Nous avons utilisé brûlure dans une phrase.",
          "Ils vont apprendre brûlure cette semaine.",
          "J'ai choisi la brûlure parce que ce mot était utile.",
          "Elle a noté brûlure dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec brûlure.",
          "Le groupe a parlé de la brûlure pendant le cours.",
          "Je vais demander des informations sur la brûlure.",
          "Nous avons associé la brûlure à une image.",
          "Hier soir, mon frère a cherché le sens de brûlure.",
          "Pendant l'exercice, je confondais encore brûlure.",
          "Elle a oublié le mot brûlure pendant la dictée.",
          "Il va utiliser brûlure dans sa réponse.",
          "Nous avons trouvé la brûlure dans le dialogue médical.",
          "Ce week-end, je vais mémoriser brûlure.",
          "L'élève a ajouté brûlure dans sa phrase.",
          "J'ai compris brûlure pour la première fois.",
          "Ma sœur a demandé un exemple avec brûlure.",
          "Ils ont répété brûlure à voix haute.",
          "Nous allons revoir la brûlure avec le professeur.",
          "Elle a écrit brûlure sans aide.",
          "La classe a demandé une définition de brûlure.",
          "Après la leçon, j'ai utilisé le mot brûlure dans une phrase.",
          "Demain, je vais apprendre à mieux employer la brûlure.",
          "Quand je lis le texte, je cherche le sens de brûlure.",
          "Ce matin, nous avons associé la brûlure à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec brûlure.",
          "Le professeur a demandé un exemple avec la brûlure.",
          "J'ai choisi la brûlure parce que ce mot était dans la liste.",
          "Nous allons réviser la brûlure avant l'évaluation.",
          "Mon camarade a expliqué la brûlure avec ses mots.",
          "J'ai ajouté brûlure dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la brûlure semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la brûlure apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais brûlure, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà brûlure, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la brûlure avec des mots simples.",
          "La leçon que nous travaillons utilise brûlure dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la brûlure, le client posait des questions.",
          "Puisque brûlure est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé brûlure, tu comprendras mieux les consignes du médecin.",
          "Je pense que la brûlure aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, brûlure peut donner une information importante.",
          "Le mot dont je parle est brûlure, que la classe doit retenir.",
          "Tant que tu pratiqueras brûlure, tu parleras de santé plus facilement.",
          "Bien que la brûlure demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient brûlure, je penserai au vocabulaire médical.",
          "Bien que le mot brûlure paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la brûlure apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la brûlure, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la brûlure.",
          "Lorsque j'aurai mémorisé brûlure, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la brûlure.",
          "Puisque brûlure est utile, je le révise régulièrement.",
        ],
      } },
    { word: "blessure",     image: "blessure.webp", article: "la",  gender: "f", definition: ["Mal ou dommage sur une partie du corps."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la blessure au patient.",
          "Demain, je vais revoir le mot blessure.",
          "Quand j'étais malade, j'ai entendu parler de la blessure.",
          "Ce matin, le pharmacien a expliqué la blessure.",
          "Nous avons utilisé blessure dans une phrase.",
          "Ils vont apprendre blessure cette semaine.",
          "J'ai choisi la blessure parce que ce mot était utile.",
          "Elle a noté blessure dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec blessure.",
          "Le groupe a parlé de la blessure pendant le cours.",
          "Je vais demander des informations sur la blessure.",
          "Nous avons associé la blessure à une image.",
          "Hier soir, mon frère a cherché le sens de blessure.",
          "Pendant l'exercice, je confondais encore blessure.",
          "Elle a oublié le mot blessure pendant la dictée.",
          "Il va utiliser blessure dans sa réponse.",
          "Nous avons trouvé la blessure dans le dialogue médical.",
          "Ce week-end, je vais mémoriser blessure.",
          "L'élève a ajouté blessure dans sa phrase.",
          "J'ai compris blessure pour la première fois.",
          "Ma sœur a demandé un exemple avec blessure.",
          "Ils ont répété blessure à voix haute.",
          "Nous allons revoir la blessure avec le professeur.",
          "Elle a écrit blessure sans aide.",
          "La classe a demandé une définition de blessure.",
          "Après la leçon, j'ai utilisé le mot blessure dans une phrase.",
          "Demain, je vais apprendre à mieux employer la blessure.",
          "Quand je lis le texte, je cherche le sens de blessure.",
          "Ce matin, nous avons associé la blessure à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec blessure.",
          "Le professeur a demandé un exemple avec la blessure.",
          "J'ai choisi la blessure parce que ce mot était dans la liste.",
          "Nous allons réviser la blessure avant l'évaluation.",
          "Mon camarade a expliqué la blessure avec ses mots.",
          "J'ai ajouté blessure dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la blessure semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la blessure apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais blessure, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà blessure, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la blessure avec des mots simples.",
          "La leçon que nous travaillons utilise blessure dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la blessure, le client posait des questions.",
          "Puisque blessure est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé blessure, tu comprendras mieux les consignes du médecin.",
          "Je pense que la blessure aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, blessure peut donner une information importante.",
          "Le mot dont je parle est blessure, que la classe doit retenir.",
          "Tant que tu pratiqueras blessure, tu parleras de santé plus facilement.",
          "Bien que la blessure demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient blessure, je penserai au vocabulaire médical.",
          "Bien que le mot blessure paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la blessure apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la blessure, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la blessure.",
          "Lorsque j'aurai mémorisé blessure, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la blessure.",
          "Puisque blessure est utile, je le révise régulièrement.",
        ],
      } },
    { word: "fracture",     image: "fracture.webp", article: "la",  gender: "f", definition: ["Os cassé."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la fracture au patient.",
          "Demain, je vais revoir le mot fracture.",
          "Quand j'étais malade, j'ai entendu parler de la fracture.",
          "Ce matin, le pharmacien a expliqué la fracture.",
          "Nous avons utilisé fracture dans une phrase.",
          "Ils vont apprendre fracture cette semaine.",
          "J'ai choisi la fracture parce que ce mot était utile.",
          "Elle a noté fracture dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec fracture.",
          "Le groupe a parlé de la fracture pendant le cours.",
          "Je vais demander des informations sur la fracture.",
          "Nous avons associé la fracture à une image.",
          "Hier soir, mon frère a cherché le sens de fracture.",
          "Pendant l'exercice, je confondais encore fracture.",
          "Elle a oublié le mot fracture pendant la dictée.",
          "Il va utiliser fracture dans sa réponse.",
          "Nous avons trouvé la fracture dans le dialogue médical.",
          "Ce week-end, je vais mémoriser fracture.",
          "L'élève a ajouté fracture dans sa phrase.",
          "J'ai compris fracture pour la première fois.",
          "Ma sœur a demandé un exemple avec fracture.",
          "Ils ont répété fracture à voix haute.",
          "Nous allons revoir la fracture avec le professeur.",
          "Elle a écrit fracture sans aide.",
          "La classe a demandé une définition de fracture.",
          "Après la leçon, j'ai utilisé le mot fracture dans une phrase.",
          "Demain, je vais apprendre à mieux employer la fracture.",
          "Quand je lis le texte, je cherche le sens de fracture.",
          "Ce matin, nous avons associé la fracture à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec fracture.",
          "Le professeur a demandé un exemple avec la fracture.",
          "J'ai choisi la fracture parce que ce mot était dans la liste.",
          "Nous allons réviser la fracture avant l'évaluation.",
          "Mon camarade a expliqué la fracture avec ses mots.",
          "J'ai ajouté fracture dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la fracture semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la fracture apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais fracture, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà fracture, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la fracture avec des mots simples.",
          "La leçon que nous travaillons utilise fracture dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la fracture, le client posait des questions.",
          "Puisque fracture est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé fracture, tu comprendras mieux les consignes du médecin.",
          "Je pense que la fracture aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, fracture peut donner une information importante.",
          "Le mot dont je parle est fracture, que la classe doit retenir.",
          "Tant que tu pratiqueras fracture, tu parleras de santé plus facilement.",
          "Bien que la fracture demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient fracture, je penserai au vocabulaire médical.",
          "Bien que le mot fracture paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la fracture apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la fracture, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la fracture.",
          "Lorsque j'aurai mémorisé fracture, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la fracture.",
          "Puisque fracture est utile, je le révise régulièrement.",
        ],
      } },
    { word: "nausée",       image: "nausee.webp",   article: "la",  gender: "f", definition: ["Envie de vomir."], definitionPivot: { en: "A health problem or symptom.", ar: "مشكلة صحية أو عَرَض.", fa: "مشکل سلامتی یا نشانه بیماری.", pt: "Problema de saúde ou sintoma.", so: "Dhibaato caafimaad ama calaamad.", ti: "ጸገም ጥዕና ወይ ምልክት።", tr: "Sağlık sorunu veya belirti.", ps: "روغتيايي ستونزه يا نښه.", uk: "Проблема зі здоров’ям або симптом." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la nausée au patient.",
          "Demain, je vais revoir le mot nausée.",
          "Quand j'étais malade, j'ai entendu parler de la nausée.",
          "Ce matin, le pharmacien a expliqué la nausée.",
          "Nous avons utilisé nausée dans une phrase.",
          "Ils vont apprendre nausée cette semaine.",
          "J'ai choisi la nausée parce que ce mot était utile.",
          "Elle a noté nausée dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec nausée.",
          "Le groupe a parlé de la nausée pendant le cours.",
          "Je vais demander des informations sur la nausée.",
          "Nous avons associé la nausée à une image.",
          "Hier soir, mon frère a cherché le sens de nausée.",
          "Pendant l'exercice, je confondais encore nausée.",
          "Elle a oublié le mot nausée pendant la dictée.",
          "Il va utiliser nausée dans sa réponse.",
          "Nous avons trouvé la nausée dans le dialogue médical.",
          "Ce week-end, je vais mémoriser nausée.",
          "L'élève a ajouté nausée dans sa phrase.",
          "J'ai compris nausée pour la première fois.",
          "Ma sœur a demandé un exemple avec nausée.",
          "Ils ont répété nausée à voix haute.",
          "Nous allons revoir la nausée avec le professeur.",
          "Elle a écrit nausée sans aide.",
          "La classe a demandé une définition de nausée.",
          "Après la leçon, j'ai utilisé le mot nausée dans une phrase.",
          "Demain, je vais apprendre à mieux employer la nausée.",
          "Quand je lis le texte, je cherche le sens de nausée.",
          "Ce matin, nous avons associé la nausée à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec nausée.",
          "Le professeur a demandé un exemple avec la nausée.",
          "J'ai choisi la nausée parce que ce mot était dans la liste.",
          "Nous allons réviser la nausée avant l'évaluation.",
          "Mon camarade a expliqué la nausée avec ses mots.",
          "J'ai ajouté nausée dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la nausée semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la nausée apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais nausée, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà nausée, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la nausée avec des mots simples.",
          "La leçon que nous travaillons utilise nausée dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la nausée, le client posait des questions.",
          "Puisque nausée est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé nausée, tu comprendras mieux les consignes du médecin.",
          "Je pense que la nausée aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, nausée peut donner une information importante.",
          "Le mot dont je parle est nausée, que la classe doit retenir.",
          "Tant que tu pratiqueras nausée, tu parleras de santé plus facilement.",
          "Bien que la nausée demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient nausée, je penserai au vocabulaire médical.",
          "Bien que le mot nausée paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la nausée apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la nausée, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la nausée.",
          "Lorsque j'aurai mémorisé nausée, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la nausée.",
          "Puisque nausée est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il a de la ___, il doit rester au lit.",                answer: "fièvre" },
    { sentence: "J'ai un ___, j'éternue et j'ai le nez qui coule.",      answer: "rhume" },
    { sentence: "La ___ lui fait mal au bras depuis sa chute.",          answer: "fracture" },
    { sentence: "Il a une ___ aux arachides, il ne peut pas en manger.", answer: "allergie" },
    { sentence: "Il a la ___ après avoir mangé quelque chose de mauvais.", answer: "nausée" },
  ],
};
