import type { VocabTheme } from "../../vocabulary-data";

export const V8_PHARMACIE_THEME: VocabTheme = {
  slug: "v8-pharmacie",
  code: "V8.4",
  title: "La pharmacie",
  section: "V8",
  words: [
    { word: "médicament", article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du médicament au patient.",
          "Demain, je vais revoir le mot médicament.",
          "Quand j'étais malade, j'ai entendu parler du médicament.",
          "Ce matin, le pharmacien a expliqué le médicament.",
          "Nous avons utilisé médicament dans une phrase.",
          "Ils vont apprendre médicament cette semaine.",
          "J'ai choisi le médicament parce que ce mot était utile.",
          "Elle a noté médicament dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec médicament.",
          "Le groupe a parlé du médicament pendant le cours.",
          "Je vais demander des informations sur le médicament.",
          "Nous avons associé le médicament à une image.",
          "Hier soir, mon frère a cherché le sens de médicament.",
          "Pendant l'exercice, je confondais encore médicament.",
          "Elle a oublié le mot médicament pendant la dictée.",
          "Il va utiliser médicament dans sa réponse.",
          "Nous avons trouvé le médicament dans le dialogue médical.",
          "Ce week-end, je vais mémoriser médicament.",
          "L'élève a ajouté médicament dans sa phrase.",
          "J'ai compris médicament pour la première fois.",
          "Ma sœur a demandé un exemple avec médicament.",
          "Ils ont répété médicament à voix haute.",
          "Nous allons revoir le médicament avec le professeur.",
          "Elle a écrit médicament sans aide.",
          "La classe a demandé une définition de médicament.",
          "Après la leçon, j'ai utilisé le mot médicament dans une phrase.",
          "Demain, je vais apprendre à mieux employer le médicament.",
          "Quand je lis le texte, je cherche le sens de médicament.",
          "Ce matin, nous avons associé le médicament à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec médicament.",
          "Le professeur a demandé un exemple avec le médicament.",
          "J'ai choisi le médicament parce que ce mot était dans la liste.",
          "Nous allons réviser le médicament avant l'évaluation.",
          "Mon camarade a expliqué le médicament avec ses mots.",
          "J'ai ajouté médicament dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le médicament semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le médicament apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais médicament, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà médicament, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le médicament avec des mots simples.",
          "La leçon que nous travaillons utilise médicament dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du médicament, le client posait des questions.",
          "Puisque médicament est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé médicament, tu comprendras mieux les consignes du médecin.",
          "Je pense que le médicament aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, médicament peut donner une information importante.",
          "Le mot dont je parle est médicament, que la classe doit retenir.",
          "Tant que tu pratiqueras médicament, tu parleras de santé plus facilement.",
          "Bien que le médicament demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient médicament, je penserai au vocabulaire médical.",
          "Bien que le mot médicament paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le médicament apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le médicament, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le médicament.",
          "Lorsque j'aurai mémorisé médicament, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le médicament.",
          "Puisque médicament est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ordonnance", article: "l'",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de l'ordonnance au patient.",
          "Demain, je vais revoir le mot ordonnance.",
          "Quand j'étais malade, j'ai entendu parler de l'ordonnance.",
          "Ce matin, le pharmacien a expliqué l'ordonnance.",
          "Nous avons utilisé ordonnance dans une phrase.",
          "Ils vont apprendre ordonnance cette semaine.",
          "J'ai choisi l'ordonnance parce que ce mot était utile.",
          "Elle a noté ordonnance dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec ordonnance.",
          "Le groupe a parlé de l'ordonnance pendant le cours.",
          "Je vais demander des informations sur l'ordonnance.",
          "Nous avons associé l'ordonnance à une image.",
          "Hier soir, mon frère a cherché le sens de ordonnance.",
          "Pendant l'exercice, je confondais encore ordonnance.",
          "Elle a oublié le mot ordonnance pendant la dictée.",
          "Il va utiliser ordonnance dans sa réponse.",
          "Nous avons trouvé l'ordonnance dans le dialogue médical.",
          "Ce week-end, je vais mémoriser ordonnance.",
          "L'élève a ajouté ordonnance dans sa phrase.",
          "J'ai compris ordonnance pour la première fois.",
          "Ma sœur a demandé un exemple avec ordonnance.",
          "Ils ont répété ordonnance à voix haute.",
          "Nous allons revoir l'ordonnance avec le professeur.",
          "Elle a écrit ordonnance sans aide.",
          "La classe a demandé une définition de ordonnance.",
          "Après la leçon, j'ai utilisé le mot ordonnance dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ordonnance.",
          "Quand je lis le texte, je cherche le sens de ordonnance.",
          "Ce matin, nous avons associé l'ordonnance à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ordonnance.",
          "Le professeur a demandé un exemple avec l'ordonnance.",
          "J'ai choisi l'ordonnance parce que ce mot était dans la liste.",
          "Nous allons réviser l'ordonnance avant l'évaluation.",
          "Mon camarade a expliqué l'ordonnance avec ses mots.",
          "J'ai ajouté ordonnance dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ordonnance semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'ordonnance apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais ordonnance, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà ordonnance, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'ordonnance avec des mots simples.",
          "La leçon que nous travaillons utilise ordonnance dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'ordonnance, le client posait des questions.",
          "Puisque ordonnance est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé ordonnance, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'ordonnance aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, ordonnance peut donner une information importante.",
          "Le mot dont je parle est ordonnance, que la classe doit retenir.",
          "Tant que tu pratiqueras ordonnance, tu parleras de santé plus facilement.",
          "Bien que l'ordonnance demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient ordonnance, je penserai au vocabulaire médical.",
          "Bien que le mot ordonnance paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ordonnance apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ordonnance, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ordonnance.",
          "Lorsque j'aurai mémorisé ordonnance, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ordonnance.",
          "Puisque ordonnance est utile, je le révise régulièrement.",
        ],
      } },
    { word: "sirop",      article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du sirop au patient.",
          "Demain, je vais revoir le mot sirop.",
          "Quand j'étais malade, j'ai entendu parler du sirop.",
          "Ce matin, le pharmacien a expliqué le sirop.",
          "Nous avons utilisé sirop dans une phrase.",
          "Ils vont apprendre sirop cette semaine.",
          "J'ai choisi le sirop parce que ce mot était utile.",
          "Elle a noté sirop dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec sirop.",
          "Le groupe a parlé du sirop pendant le cours.",
          "Je vais demander des informations sur le sirop.",
          "Nous avons associé le sirop à une image.",
          "Hier soir, mon frère a cherché le sens de sirop.",
          "Pendant l'exercice, je confondais encore sirop.",
          "Elle a oublié le mot sirop pendant la dictée.",
          "Il va utiliser sirop dans sa réponse.",
          "Nous avons trouvé le sirop dans le dialogue médical.",
          "Ce week-end, je vais mémoriser sirop.",
          "L'élève a ajouté sirop dans sa phrase.",
          "J'ai compris sirop pour la première fois.",
          "Ma sœur a demandé un exemple avec sirop.",
          "Ils ont répété sirop à voix haute.",
          "Nous allons revoir le sirop avec le professeur.",
          "Elle a écrit sirop sans aide.",
          "La classe a demandé une définition de sirop.",
          "Après la leçon, j'ai utilisé le mot sirop dans une phrase.",
          "Demain, je vais apprendre à mieux employer le sirop.",
          "Quand je lis le texte, je cherche le sens de sirop.",
          "Ce matin, nous avons associé le sirop à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec sirop.",
          "Le professeur a demandé un exemple avec le sirop.",
          "J'ai choisi le sirop parce que ce mot était dans la liste.",
          "Nous allons réviser le sirop avant l'évaluation.",
          "Mon camarade a expliqué le sirop avec ses mots.",
          "J'ai ajouté sirop dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le sirop semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le sirop apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais sirop, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà sirop, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le sirop avec des mots simples.",
          "La leçon que nous travaillons utilise sirop dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du sirop, le client posait des questions.",
          "Puisque sirop est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé sirop, tu comprendras mieux les consignes du médecin.",
          "Je pense que le sirop aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, sirop peut donner une information importante.",
          "Le mot dont je parle est sirop, que la classe doit retenir.",
          "Tant que tu pratiqueras sirop, tu parleras de santé plus facilement.",
          "Bien que le sirop demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient sirop, je penserai au vocabulaire médical.",
          "Bien que le mot sirop paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le sirop apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le sirop, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le sirop.",
          "Lorsque j'aurai mémorisé sirop, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le sirop.",
          "Puisque sirop est utile, je le révise régulièrement.",
        ],
      } },
    { word: "comprimé",   article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du comprimé au patient.",
          "Demain, je vais revoir le mot comprimé.",
          "Quand j'étais malade, j'ai entendu parler du comprimé.",
          "Ce matin, le pharmacien a expliqué le comprimé.",
          "Nous avons utilisé comprimé dans une phrase.",
          "Ils vont apprendre comprimé cette semaine.",
          "J'ai choisi le comprimé parce que ce mot était utile.",
          "Elle a noté comprimé dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec comprimé.",
          "Le groupe a parlé du comprimé pendant le cours.",
          "Je vais demander des informations sur le comprimé.",
          "Nous avons associé le comprimé à une image.",
          "Hier soir, mon frère a cherché le sens de comprimé.",
          "Pendant l'exercice, je confondais encore comprimé.",
          "Elle a oublié le mot comprimé pendant la dictée.",
          "Il va utiliser comprimé dans sa réponse.",
          "Nous avons trouvé le comprimé dans le dialogue médical.",
          "Ce week-end, je vais mémoriser comprimé.",
          "L'élève a ajouté comprimé dans sa phrase.",
          "J'ai compris comprimé pour la première fois.",
          "Ma sœur a demandé un exemple avec comprimé.",
          "Ils ont répété comprimé à voix haute.",
          "Nous allons revoir le comprimé avec le professeur.",
          "Elle a écrit comprimé sans aide.",
          "La classe a demandé une définition de comprimé.",
          "Après la leçon, j'ai utilisé le mot comprimé dans une phrase.",
          "Demain, je vais apprendre à mieux employer le comprimé.",
          "Quand je lis le texte, je cherche le sens de comprimé.",
          "Ce matin, nous avons associé le comprimé à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec comprimé.",
          "Le professeur a demandé un exemple avec le comprimé.",
          "J'ai choisi le comprimé parce que ce mot était dans la liste.",
          "Nous allons réviser le comprimé avant l'évaluation.",
          "Mon camarade a expliqué le comprimé avec ses mots.",
          "J'ai ajouté comprimé dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le comprimé semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le comprimé apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais comprimé, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà comprimé, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le comprimé avec des mots simples.",
          "La leçon que nous travaillons utilise comprimé dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du comprimé, le client posait des questions.",
          "Puisque comprimé est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé comprimé, tu comprendras mieux les consignes du médecin.",
          "Je pense que le comprimé aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, comprimé peut donner une information importante.",
          "Le mot dont je parle est comprimé, que la classe doit retenir.",
          "Tant que tu pratiqueras comprimé, tu parleras de santé plus facilement.",
          "Bien que le comprimé demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient comprimé, je penserai au vocabulaire médical.",
          "Bien que le mot comprimé paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le comprimé apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le comprimé, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le comprimé.",
          "Lorsque j'aurai mémorisé comprimé, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le comprimé.",
          "Puisque comprimé est utile, je le révise régulièrement.",
        ],
      } },
    { word: "gélule",     article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la gélule au patient.",
          "Demain, je vais revoir le mot gélule.",
          "Quand j'étais malade, j'ai entendu parler de la gélule.",
          "Ce matin, le pharmacien a expliqué la gélule.",
          "Nous avons utilisé gélule dans une phrase.",
          "Ils vont apprendre gélule cette semaine.",
          "J'ai choisi la gélule parce que ce mot était utile.",
          "Elle a noté gélule dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec gélule.",
          "Le groupe a parlé de la gélule pendant le cours.",
          "Je vais demander des informations sur la gélule.",
          "Nous avons associé la gélule à une image.",
          "Hier soir, mon frère a cherché le sens de gélule.",
          "Pendant l'exercice, je confondais encore gélule.",
          "Elle a oublié le mot gélule pendant la dictée.",
          "Il va utiliser gélule dans sa réponse.",
          "Nous avons trouvé la gélule dans le dialogue médical.",
          "Ce week-end, je vais mémoriser gélule.",
          "L'élève a ajouté gélule dans sa phrase.",
          "J'ai compris gélule pour la première fois.",
          "Ma sœur a demandé un exemple avec gélule.",
          "Ils ont répété gélule à voix haute.",
          "Nous allons revoir la gélule avec le professeur.",
          "Elle a écrit gélule sans aide.",
          "La classe a demandé une définition de gélule.",
          "Après la leçon, j'ai utilisé le mot gélule dans une phrase.",
          "Demain, je vais apprendre à mieux employer la gélule.",
          "Quand je lis le texte, je cherche le sens de gélule.",
          "Ce matin, nous avons associé la gélule à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec gélule.",
          "Le professeur a demandé un exemple avec la gélule.",
          "J'ai choisi la gélule parce que ce mot était dans la liste.",
          "Nous allons réviser la gélule avant l'évaluation.",
          "Mon camarade a expliqué la gélule avec ses mots.",
          "J'ai ajouté gélule dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la gélule semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la gélule apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais gélule, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà gélule, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la gélule avec des mots simples.",
          "La leçon que nous travaillons utilise gélule dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la gélule, le client posait des questions.",
          "Puisque gélule est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé gélule, tu comprendras mieux les consignes du médecin.",
          "Je pense que la gélule aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, gélule peut donner une information importante.",
          "Le mot dont je parle est gélule, que la classe doit retenir.",
          "Tant que tu pratiqueras gélule, tu parleras de santé plus facilement.",
          "Bien que la gélule demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient gélule, je penserai au vocabulaire médical.",
          "Bien que le mot gélule paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la gélule apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la gélule, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la gélule.",
          "Lorsque j'aurai mémorisé gélule, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la gélule.",
          "Puisque gélule est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pommade",    article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la pommade au patient.",
          "Demain, je vais revoir le mot pommade.",
          "Quand j'étais malade, j'ai entendu parler de la pommade.",
          "Ce matin, le pharmacien a expliqué la pommade.",
          "Nous avons utilisé pommade dans une phrase.",
          "Ils vont apprendre pommade cette semaine.",
          "J'ai choisi la pommade parce que ce mot était utile.",
          "Elle a noté pommade dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec pommade.",
          "Le groupe a parlé de la pommade pendant le cours.",
          "Je vais demander des informations sur la pommade.",
          "Nous avons associé la pommade à une image.",
          "Hier soir, mon frère a cherché le sens de pommade.",
          "Pendant l'exercice, je confondais encore pommade.",
          "Elle a oublié le mot pommade pendant la dictée.",
          "Il va utiliser pommade dans sa réponse.",
          "Nous avons trouvé la pommade dans le dialogue médical.",
          "Ce week-end, je vais mémoriser pommade.",
          "L'élève a ajouté pommade dans sa phrase.",
          "J'ai compris pommade pour la première fois.",
          "Ma sœur a demandé un exemple avec pommade.",
          "Ils ont répété pommade à voix haute.",
          "Nous allons revoir la pommade avec le professeur.",
          "Elle a écrit pommade sans aide.",
          "La classe a demandé une définition de pommade.",
          "Après la leçon, j'ai utilisé le mot pommade dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pommade.",
          "Quand je lis le texte, je cherche le sens de pommade.",
          "Ce matin, nous avons associé la pommade à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pommade.",
          "Le professeur a demandé un exemple avec la pommade.",
          "J'ai choisi la pommade parce que ce mot était dans la liste.",
          "Nous allons réviser la pommade avant l'évaluation.",
          "Mon camarade a expliqué la pommade avec ses mots.",
          "J'ai ajouté pommade dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pommade semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la pommade apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais pommade, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà pommade, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la pommade avec des mots simples.",
          "La leçon que nous travaillons utilise pommade dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la pommade, le client posait des questions.",
          "Puisque pommade est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé pommade, tu comprendras mieux les consignes du médecin.",
          "Je pense que la pommade aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, pommade peut donner une information importante.",
          "Le mot dont je parle est pommade, que la classe doit retenir.",
          "Tant que tu pratiqueras pommade, tu parleras de santé plus facilement.",
          "Bien que la pommade demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient pommade, je penserai au vocabulaire médical.",
          "Bien que le mot pommade paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pommade apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pommade, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pommade.",
          "Lorsque j'aurai mémorisé pommade, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pommade.",
          "Puisque pommade est utile, je le révise régulièrement.",
        ],
      } },
    { word: "crème",      article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la crème au patient.",
          "Demain, je vais revoir le mot crème.",
          "Quand j'étais malade, j'ai entendu parler de la crème.",
          "Ce matin, le pharmacien a expliqué la crème.",
          "Nous avons utilisé crème dans une phrase.",
          "Ils vont apprendre crème cette semaine.",
          "J'ai choisi la crème parce que ce mot était utile.",
          "Elle a noté crème dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec crème.",
          "Le groupe a parlé de la crème pendant le cours.",
          "Je vais demander des informations sur la crème.",
          "Nous avons associé la crème à une image.",
          "Hier soir, mon frère a cherché le sens de crème.",
          "Pendant l'exercice, je confondais encore crème.",
          "Elle a oublié le mot crème pendant la dictée.",
          "Il va utiliser crème dans sa réponse.",
          "Nous avons trouvé la crème dans le dialogue médical.",
          "Ce week-end, je vais mémoriser crème.",
          "L'élève a ajouté crème dans sa phrase.",
          "J'ai compris crème pour la première fois.",
          "Ma sœur a demandé un exemple avec crème.",
          "Ils ont répété crème à voix haute.",
          "Nous allons revoir la crème avec le professeur.",
          "Elle a écrit crème sans aide.",
          "La classe a demandé une définition de crème.",
          "Après la leçon, j'ai utilisé le mot crème dans une phrase.",
          "Demain, je vais apprendre à mieux employer la crème.",
          "Quand je lis le texte, je cherche le sens de crème.",
          "Ce matin, nous avons associé la crème à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec crème.",
          "Le professeur a demandé un exemple avec la crème.",
          "J'ai choisi la crème parce que ce mot était dans la liste.",
          "Nous allons réviser la crème avant l'évaluation.",
          "Mon camarade a expliqué la crème avec ses mots.",
          "J'ai ajouté crème dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la crème semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la crème apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais crème, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà crème, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la crème avec des mots simples.",
          "La leçon que nous travaillons utilise crème dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la crème, le client posait des questions.",
          "Puisque crème est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé crème, tu comprendras mieux les consignes du médecin.",
          "Je pense que la crème aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, crème peut donner une information importante.",
          "Le mot dont je parle est crème, que la classe doit retenir.",
          "Tant que tu pratiqueras crème, tu parleras de santé plus facilement.",
          "Bien que la crème demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient crème, je penserai au vocabulaire médical.",
          "Bien que le mot crème paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la crème apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la crème, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la crème.",
          "Lorsque j'aurai mémorisé crème, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la crème.",
          "Puisque crème est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pansement",  article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du pansement au patient.",
          "Demain, je vais revoir le mot pansement.",
          "Quand j'étais malade, j'ai entendu parler du pansement.",
          "Ce matin, le pharmacien a expliqué le pansement.",
          "Nous avons utilisé pansement dans une phrase.",
          "Ils vont apprendre pansement cette semaine.",
          "J'ai choisi le pansement parce que ce mot était utile.",
          "Elle a noté pansement dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec pansement.",
          "Le groupe a parlé du pansement pendant le cours.",
          "Je vais demander des informations sur le pansement.",
          "Nous avons associé le pansement à une image.",
          "Hier soir, mon frère a cherché le sens de pansement.",
          "Pendant l'exercice, je confondais encore pansement.",
          "Elle a oublié le mot pansement pendant la dictée.",
          "Il va utiliser pansement dans sa réponse.",
          "Nous avons trouvé le pansement dans le dialogue médical.",
          "Ce week-end, je vais mémoriser pansement.",
          "L'élève a ajouté pansement dans sa phrase.",
          "J'ai compris pansement pour la première fois.",
          "Ma sœur a demandé un exemple avec pansement.",
          "Ils ont répété pansement à voix haute.",
          "Nous allons revoir le pansement avec le professeur.",
          "Elle a écrit pansement sans aide.",
          "La classe a demandé une définition de pansement.",
          "Après la leçon, j'ai utilisé le mot pansement dans une phrase.",
          "Demain, je vais apprendre à mieux employer le pansement.",
          "Quand je lis le texte, je cherche le sens de pansement.",
          "Ce matin, nous avons associé le pansement à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pansement.",
          "Le professeur a demandé un exemple avec le pansement.",
          "J'ai choisi le pansement parce que ce mot était dans la liste.",
          "Nous allons réviser le pansement avant l'évaluation.",
          "Mon camarade a expliqué le pansement avec ses mots.",
          "J'ai ajouté pansement dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le pansement semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le pansement apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais pansement, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà pansement, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le pansement avec des mots simples.",
          "La leçon que nous travaillons utilise pansement dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du pansement, le client posait des questions.",
          "Puisque pansement est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé pansement, tu comprendras mieux les consignes du médecin.",
          "Je pense que le pansement aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, pansement peut donner une information importante.",
          "Le mot dont je parle est pansement, que la classe doit retenir.",
          "Tant que tu pratiqueras pansement, tu parleras de santé plus facilement.",
          "Bien que le pansement demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient pansement, je penserai au vocabulaire médical.",
          "Bien que le mot pansement paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le pansement apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le pansement, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le pansement.",
          "Lorsque j'aurai mémorisé pansement, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le pansement.",
          "Puisque pansement est utile, je le révise régulièrement.",
        ],
      } },
    { word: "thermomètre",article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du thermomètre au patient.",
          "Demain, je vais revoir le mot thermomètre.",
          "Quand j'étais malade, j'ai entendu parler du thermomètre.",
          "Ce matin, le pharmacien a expliqué le thermomètre.",
          "Nous avons utilisé thermomètre dans une phrase.",
          "Ils vont apprendre thermomètre cette semaine.",
          "J'ai choisi le thermomètre parce que ce mot était utile.",
          "Elle a noté thermomètre dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec thermomètre.",
          "Le groupe a parlé du thermomètre pendant le cours.",
          "Je vais demander des informations sur le thermomètre.",
          "Nous avons associé le thermomètre à une image.",
          "Hier soir, mon frère a cherché le sens de thermomètre.",
          "Pendant l'exercice, je confondais encore thermomètre.",
          "Elle a oublié le mot thermomètre pendant la dictée.",
          "Il va utiliser thermomètre dans sa réponse.",
          "Nous avons trouvé le thermomètre dans le dialogue médical.",
          "Ce week-end, je vais mémoriser thermomètre.",
          "L'élève a ajouté thermomètre dans sa phrase.",
          "J'ai compris thermomètre pour la première fois.",
          "Ma sœur a demandé un exemple avec thermomètre.",
          "Ils ont répété thermomètre à voix haute.",
          "Nous allons revoir le thermomètre avec le professeur.",
          "Elle a écrit thermomètre sans aide.",
          "La classe a demandé une définition de thermomètre.",
          "Après la leçon, j'ai utilisé le mot thermomètre dans une phrase.",
          "Demain, je vais apprendre à mieux employer le thermomètre.",
          "Quand je lis le texte, je cherche le sens de thermomètre.",
          "Ce matin, nous avons associé le thermomètre à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec thermomètre.",
          "Le professeur a demandé un exemple avec le thermomètre.",
          "J'ai choisi le thermomètre parce que ce mot était dans la liste.",
          "Nous allons réviser le thermomètre avant l'évaluation.",
          "Mon camarade a expliqué le thermomètre avec ses mots.",
          "J'ai ajouté thermomètre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le thermomètre semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le thermomètre apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais thermomètre, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà thermomètre, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le thermomètre avec des mots simples.",
          "La leçon que nous travaillons utilise thermomètre dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du thermomètre, le client posait des questions.",
          "Puisque thermomètre est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé thermomètre, tu comprendras mieux les consignes du médecin.",
          "Je pense que le thermomètre aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, thermomètre peut donner une information importante.",
          "Le mot dont je parle est thermomètre, que la classe doit retenir.",
          "Tant que tu pratiqueras thermomètre, tu parleras de santé plus facilement.",
          "Bien que le thermomètre demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient thermomètre, je penserai au vocabulaire médical.",
          "Bien que le mot thermomètre paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le thermomètre apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le thermomètre, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le thermomètre.",
          "Lorsque j'aurai mémorisé thermomètre, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le thermomètre.",
          "Puisque thermomètre est utile, je le révise régulièrement.",
        ],
      } },
    { word: "spray",      article: "le",  gender: "m", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé du spray au patient.",
          "Demain, je vais revoir le mot spray.",
          "Quand j'étais malade, j'ai entendu parler du spray.",
          "Ce matin, le pharmacien a expliqué le spray.",
          "Nous avons utilisé spray dans une phrase.",
          "Ils vont apprendre spray cette semaine.",
          "J'ai choisi le spray parce que ce mot était utile.",
          "Elle a noté spray dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec spray.",
          "Le groupe a parlé du spray pendant le cours.",
          "Je vais demander des informations sur le spray.",
          "Nous avons associé le spray à une image.",
          "Hier soir, mon frère a cherché le sens de spray.",
          "Pendant l'exercice, je confondais encore spray.",
          "Elle a oublié le mot spray pendant la dictée.",
          "Il va utiliser spray dans sa réponse.",
          "Nous avons trouvé le spray dans le dialogue médical.",
          "Ce week-end, je vais mémoriser spray.",
          "L'élève a ajouté spray dans sa phrase.",
          "J'ai compris spray pour la première fois.",
          "Ma sœur a demandé un exemple avec spray.",
          "Ils ont répété spray à voix haute.",
          "Nous allons revoir le spray avec le professeur.",
          "Elle a écrit spray sans aide.",
          "La classe a demandé une définition de spray.",
          "Après la leçon, j'ai utilisé le mot spray dans une phrase.",
          "Demain, je vais apprendre à mieux employer le spray.",
          "Quand je lis le texte, je cherche le sens de spray.",
          "Ce matin, nous avons associé le spray à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec spray.",
          "Le professeur a demandé un exemple avec le spray.",
          "J'ai choisi le spray parce que ce mot était dans la liste.",
          "Nous allons réviser le spray avant l'évaluation.",
          "Mon camarade a expliqué le spray avec ses mots.",
          "J'ai ajouté spray dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le spray semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le spray apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais spray, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà spray, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le spray avec des mots simples.",
          "La leçon que nous travaillons utilise spray dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du spray, le client posait des questions.",
          "Puisque spray est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé spray, tu comprendras mieux les consignes du médecin.",
          "Je pense que le spray aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, spray peut donner une information importante.",
          "Le mot dont je parle est spray, que la classe doit retenir.",
          "Tant que tu pratiqueras spray, tu parleras de santé plus facilement.",
          "Bien que le spray demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient spray, je penserai au vocabulaire médical.",
          "Bien que le mot spray paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le spray apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le spray, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le spray.",
          "Lorsque j'aurai mémorisé spray, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le spray.",
          "Puisque spray est utile, je le révise régulièrement.",
        ],
      } },
    { word: "goutte",     article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la goutte au patient.",
          "Demain, je vais revoir le mot goutte.",
          "Quand j'étais malade, j'ai entendu parler de la goutte.",
          "Ce matin, le pharmacien a expliqué la goutte.",
          "Nous avons utilisé goutte dans une phrase.",
          "Ils vont apprendre goutte cette semaine.",
          "J'ai choisi la goutte parce que ce mot était utile.",
          "Elle a noté goutte dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec goutte.",
          "Le groupe a parlé de la goutte pendant le cours.",
          "Je vais demander des informations sur la goutte.",
          "Nous avons associé la goutte à une image.",
          "Hier soir, mon frère a cherché le sens de goutte.",
          "Pendant l'exercice, je confondais encore goutte.",
          "Elle a oublié le mot goutte pendant la dictée.",
          "Il va utiliser goutte dans sa réponse.",
          "Nous avons trouvé la goutte dans le dialogue médical.",
          "Ce week-end, je vais mémoriser goutte.",
          "L'élève a ajouté goutte dans sa phrase.",
          "J'ai compris goutte pour la première fois.",
          "Ma sœur a demandé un exemple avec goutte.",
          "Ils ont répété goutte à voix haute.",
          "Nous allons revoir la goutte avec le professeur.",
          "Elle a écrit goutte sans aide.",
          "La classe a demandé une définition de goutte.",
          "Après la leçon, j'ai utilisé le mot goutte dans une phrase.",
          "Demain, je vais apprendre à mieux employer la goutte.",
          "Quand je lis le texte, je cherche le sens de goutte.",
          "Ce matin, nous avons associé la goutte à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec goutte.",
          "Le professeur a demandé un exemple avec la goutte.",
          "J'ai choisi la goutte parce que ce mot était dans la liste.",
          "Nous allons réviser la goutte avant l'évaluation.",
          "Mon camarade a expliqué la goutte avec ses mots.",
          "J'ai ajouté goutte dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la goutte semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la goutte apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais goutte, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà goutte, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la goutte avec des mots simples.",
          "La leçon que nous travaillons utilise goutte dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la goutte, le client posait des questions.",
          "Puisque goutte est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé goutte, tu comprendras mieux les consignes du médecin.",
          "Je pense que la goutte aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, goutte peut donner une information importante.",
          "Le mot dont je parle est goutte, que la classe doit retenir.",
          "Tant que tu pratiqueras goutte, tu parleras de santé plus facilement.",
          "Bien que la goutte demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient goutte, je penserai au vocabulaire médical.",
          "Bien que le mot goutte paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la goutte apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la goutte, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la goutte.",
          "Lorsque j'aurai mémorisé goutte, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la goutte.",
          "Puisque goutte est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pharmacie",  article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la pharmacie au patient.",
          "Demain, je vais revoir le mot pharmacie.",
          "Quand j'étais malade, j'ai entendu parler de la pharmacie.",
          "Ce matin, le pharmacien a expliqué la pharmacie.",
          "Nous avons utilisé pharmacie dans une phrase.",
          "Ils vont apprendre pharmacie cette semaine.",
          "J'ai choisi la pharmacie parce que ce mot était utile.",
          "Elle a noté pharmacie dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec pharmacie.",
          "Le groupe a parlé de la pharmacie pendant le cours.",
          "Je vais demander des informations sur la pharmacie.",
          "Nous avons associé la pharmacie à une image.",
          "Hier soir, mon frère a cherché le sens de pharmacie.",
          "Pendant l'exercice, je confondais encore pharmacie.",
          "Elle a oublié le mot pharmacie pendant la dictée.",
          "Il va utiliser pharmacie dans sa réponse.",
          "Nous avons trouvé la pharmacie dans le dialogue médical.",
          "Ce week-end, je vais mémoriser pharmacie.",
          "L'élève a ajouté pharmacie dans sa phrase.",
          "J'ai compris pharmacie pour la première fois.",
          "Ma sœur a demandé un exemple avec pharmacie.",
          "Ils ont répété pharmacie à voix haute.",
          "Nous allons revoir la pharmacie avec le professeur.",
          "Elle a écrit pharmacie sans aide.",
          "La classe a demandé une définition de pharmacie.",
          "Après la leçon, j'ai utilisé le mot pharmacie dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pharmacie.",
          "Quand je lis le texte, je cherche le sens de pharmacie.",
          "Ce matin, nous avons associé la pharmacie à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pharmacie.",
          "Le professeur a demandé un exemple avec la pharmacie.",
          "J'ai choisi la pharmacie parce que ce mot était dans la liste.",
          "Nous allons réviser la pharmacie avant l'évaluation.",
          "Mon camarade a expliqué la pharmacie avec ses mots.",
          "J'ai ajouté pharmacie dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pharmacie semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la pharmacie apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais pharmacie, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà pharmacie, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la pharmacie avec des mots simples.",
          "La leçon que nous travaillons utilise pharmacie dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la pharmacie, le client posait des questions.",
          "Puisque pharmacie est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé pharmacie, tu comprendras mieux les consignes du médecin.",
          "Je pense que la pharmacie aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, pharmacie peut donner une information importante.",
          "Le mot dont je parle est pharmacie, que la classe doit retenir.",
          "Tant que tu pratiqueras pharmacie, tu parleras de santé plus facilement.",
          "Bien que la pharmacie demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient pharmacie, je penserai au vocabulaire médical.",
          "Bien que le mot pharmacie paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pharmacie apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pharmacie, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pharmacie.",
          "Lorsque j'aurai mémorisé pharmacie, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pharmacie.",
          "Puisque pharmacie est utile, je le révise régulièrement.",
        ],
      } },
    { word: "dosette",    article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la dosette au patient.",
          "Demain, je vais revoir le mot dosette.",
          "Quand j'étais malade, j'ai entendu parler de la dosette.",
          "Ce matin, le pharmacien a expliqué la dosette.",
          "Nous avons utilisé dosette dans une phrase.",
          "Ils vont apprendre dosette cette semaine.",
          "J'ai choisi la dosette parce que ce mot était utile.",
          "Elle a noté dosette dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec dosette.",
          "Le groupe a parlé de la dosette pendant le cours.",
          "Je vais demander des informations sur la dosette.",
          "Nous avons associé la dosette à une image.",
          "Hier soir, mon frère a cherché le sens de dosette.",
          "Pendant l'exercice, je confondais encore dosette.",
          "Elle a oublié le mot dosette pendant la dictée.",
          "Il va utiliser dosette dans sa réponse.",
          "Nous avons trouvé la dosette dans le dialogue médical.",
          "Ce week-end, je vais mémoriser dosette.",
          "L'élève a ajouté dosette dans sa phrase.",
          "J'ai compris dosette pour la première fois.",
          "Ma sœur a demandé un exemple avec dosette.",
          "Ils ont répété dosette à voix haute.",
          "Nous allons revoir la dosette avec le professeur.",
          "Elle a écrit dosette sans aide.",
          "La classe a demandé une définition de dosette.",
          "Après la leçon, j'ai utilisé le mot dosette dans une phrase.",
          "Demain, je vais apprendre à mieux employer la dosette.",
          "Quand je lis le texte, je cherche le sens de dosette.",
          "Ce matin, nous avons associé la dosette à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec dosette.",
          "Le professeur a demandé un exemple avec la dosette.",
          "J'ai choisi la dosette parce que ce mot était dans la liste.",
          "Nous allons réviser la dosette avant l'évaluation.",
          "Mon camarade a expliqué la dosette avec ses mots.",
          "J'ai ajouté dosette dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la dosette semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la dosette apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais dosette, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà dosette, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la dosette avec des mots simples.",
          "La leçon que nous travaillons utilise dosette dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la dosette, le client posait des questions.",
          "Puisque dosette est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé dosette, tu comprendras mieux les consignes du médecin.",
          "Je pense que la dosette aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, dosette peut donner une information importante.",
          "Le mot dont je parle est dosette, que la classe doit retenir.",
          "Tant que tu pratiqueras dosette, tu parleras de santé plus facilement.",
          "Bien que la dosette demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient dosette, je penserai au vocabulaire médical.",
          "Bien que le mot dosette paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la dosette apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la dosette, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la dosette.",
          "Lorsque j'aurai mémorisé dosette, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la dosette.",
          "Puisque dosette est utile, je le révise régulièrement.",
        ],
      } },
    { word: "vitamine",   article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la vitamine au patient.",
          "Demain, je vais revoir le mot vitamine.",
          "Quand j'étais malade, j'ai entendu parler de la vitamine.",
          "Ce matin, le pharmacien a expliqué la vitamine.",
          "Nous avons utilisé vitamine dans une phrase.",
          "Ils vont apprendre vitamine cette semaine.",
          "J'ai choisi la vitamine parce que ce mot était utile.",
          "Elle a noté vitamine dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec vitamine.",
          "Le groupe a parlé de la vitamine pendant le cours.",
          "Je vais demander des informations sur la vitamine.",
          "Nous avons associé la vitamine à une image.",
          "Hier soir, mon frère a cherché le sens de vitamine.",
          "Pendant l'exercice, je confondais encore vitamine.",
          "Elle a oublié le mot vitamine pendant la dictée.",
          "Il va utiliser vitamine dans sa réponse.",
          "Nous avons trouvé la vitamine dans le dialogue médical.",
          "Ce week-end, je vais mémoriser vitamine.",
          "L'élève a ajouté vitamine dans sa phrase.",
          "J'ai compris vitamine pour la première fois.",
          "Ma sœur a demandé un exemple avec vitamine.",
          "Ils ont répété vitamine à voix haute.",
          "Nous allons revoir la vitamine avec le professeur.",
          "Elle a écrit vitamine sans aide.",
          "La classe a demandé une définition de vitamine.",
          "Après la leçon, j'ai utilisé le mot vitamine dans une phrase.",
          "Demain, je vais apprendre à mieux employer la vitamine.",
          "Quand je lis le texte, je cherche le sens de vitamine.",
          "Ce matin, nous avons associé la vitamine à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec vitamine.",
          "Le professeur a demandé un exemple avec la vitamine.",
          "J'ai choisi la vitamine parce que ce mot était dans la liste.",
          "Nous allons réviser la vitamine avant l'évaluation.",
          "Mon camarade a expliqué la vitamine avec ses mots.",
          "J'ai ajouté vitamine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la vitamine semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la vitamine apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais vitamine, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà vitamine, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la vitamine avec des mots simples.",
          "La leçon que nous travaillons utilise vitamine dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la vitamine, le client posait des questions.",
          "Puisque vitamine est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé vitamine, tu comprendras mieux les consignes du médecin.",
          "Je pense que la vitamine aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, vitamine peut donner une information importante.",
          "Le mot dont je parle est vitamine, que la classe doit retenir.",
          "Tant que tu pratiqueras vitamine, tu parleras de santé plus facilement.",
          "Bien que la vitamine demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient vitamine, je penserai au vocabulaire médical.",
          "Bien que le mot vitamine paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la vitamine apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la vitamine, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la vitamine.",
          "Lorsque j'aurai mémorisé vitamine, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la vitamine.",
          "Puisque vitamine est utile, je le révise régulièrement.",
        ],
      } },
    { word: "boîte",      article: "la",  gender: "f", exampleSentences: {
        a1: [],
        a2: [
          "Hier, le médecin a parlé de la boîte au patient.",
          "Demain, je vais revoir le mot boîte.",
          "Quand j'étais malade, j'ai entendu parler de la boîte.",
          "Ce matin, le pharmacien a expliqué la boîte.",
          "Nous avons utilisé boîte dans une phrase.",
          "Ils vont apprendre boîte cette semaine.",
          "J'ai choisi la boîte parce que ce mot était utile.",
          "Elle a noté boîte dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec boîte.",
          "Le groupe a parlé de la boîte pendant le cours.",
          "Je vais demander des informations sur la boîte.",
          "Nous avons associé la boîte à une image.",
          "Hier soir, mon frère a cherché le sens de boîte.",
          "Pendant l'exercice, je confondais encore boîte.",
          "Elle a oublié le mot boîte pendant la dictée.",
          "Il va utiliser boîte dans sa réponse.",
          "Nous avons trouvé la boîte dans le dialogue médical.",
          "Ce week-end, je vais mémoriser boîte.",
          "L'élève a ajouté boîte dans sa phrase.",
          "J'ai compris boîte pour la première fois.",
          "Ma sœur a demandé un exemple avec boîte.",
          "Ils ont répété boîte à voix haute.",
          "Nous allons revoir la boîte avec le professeur.",
          "Elle a écrit boîte sans aide.",
          "La classe a demandé une définition de boîte.",
          "Après la leçon, j'ai utilisé le mot boîte dans une phrase.",
          "Demain, je vais apprendre à mieux employer la boîte.",
          "Quand je lis le texte, je cherche le sens de boîte.",
          "Ce matin, nous avons associé la boîte à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec boîte.",
          "Le professeur a demandé un exemple avec la boîte.",
          "J'ai choisi la boîte parce que ce mot était dans la liste.",
          "Nous allons réviser la boîte avant l'évaluation.",
          "Mon camarade a expliqué la boîte avec ses mots.",
          "J'ai ajouté boîte dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la boîte semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la boîte apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais boîte, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà boîte, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la boîte avec des mots simples.",
          "La leçon que nous travaillons utilise boîte dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la boîte, le client posait des questions.",
          "Puisque boîte est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé boîte, tu comprendras mieux les consignes du médecin.",
          "Je pense que la boîte aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, boîte peut donner une information importante.",
          "Le mot dont je parle est boîte, que la classe doit retenir.",
          "Tant que tu pratiqueras boîte, tu parleras de santé plus facilement.",
          "Bien que la boîte demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient boîte, je penserai au vocabulaire médical.",
          "Bien que le mot boîte paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la boîte apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la boîte, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la boîte.",
          "Lorsque j'aurai mémorisé boîte, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la boîte.",
          "Puisque boîte est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Le médecin prescrit un ___ pour la toux.",             answer: "sirop" },
    { sentence: "Il faut mettre un ___ sur la coupure.",                answer: "pansement" },
    { sentence: "Elle prend sa ___ à la pharmacie avec l'ordonnance.", answer: "boîte" },
    { sentence: "Le ___ indique que tu as 38°C de fièvre.",             answer: "thermomètre" },
    { sentence: "Elle va à la ___ pour acheter ses médicaments.",       answer: "pharmacie" },
  ],
};
