import type { VocabTheme } from "../../vocabulary-data";

export const V2_METEO_THEME: VocabTheme = {
  slug: "v2-meteo",
  code: "V2.4",
  title: "La mÃ©tÃ©o",
  section: "V2",
  words: [
    { word: "soleil", image: "soleil.png",       article: "le",  gender: "m", definition: "astre qui donne lumiÃ¨re et chaleur" },
    { word: "nuage", image: "nuage.png",        article: "le",  gender: "m", definition: "masse de vapeur d'eau dans le ciel" },
    { word: "lune", image: "lune.png",         article: "la",  gender: "f", definition: "astre qui tourne autour de la Terre et brille la nuit" },
    { word: "Ã©toile", image: "etoile.png",       article: "une", gender: "f", definition: "astre lumineux visible dans le ciel la nuit" },
    { word: "pluie", image: "pluie.png",        article: "la",  gender: "f", definition: "eau qui tombe du ciel" },
    { word: "vent", image: "vent.jpg",         article: "le",  gender: "m", definition: "mouvement de l'air" },
    { word: "neige", image: "neige.jpg",        article: "la",  gender: "f", definition: "eau gelÃ©e qui tombe en flocons blancs" },
    { word: "orage", image: "orage.jpg",        article: "l'",  gender: "m", definition: "tempÃªte avec tonnerre et Ã©clairs" },
    { word: "brouillard", image: "brouillard.jpg",   article: "le",  gender: "m", definition: "nuage bas qui rÃ©duit la visibilitÃ©" },
    { word: "gel", image: "gel.jpg",          article: "le",  gender: "m", definition: "tempÃ©rature au-dessous de zÃ©ro degrÃ©" },
    { word: "grÃªle", image: "grele.jpg",        article: "la",  gender: "f", definition: "prÃ©cipitation de grains de glace" },
    { word: "arc-en-ciel", image: "arc-en-ciel.jpg",  article: "l'",  gender: "m", definition: "arc colorÃ© visible aprÃ¨s la pluie" },
    { word: "averse", image: "averse.jpg",       article: "l'",  gender: "f", definition: "pluie soudaine et abondante" },
    { word: "ciel", image: "ciel.jpg",         article: "le",  gender: "m", definition: "espace au-dessus de nos tÃªtes" },
    { word: "humide", image: "humide.jpg",                                      definition: "chargÃ© d'eau, mouillÃ©" },
    { word: "sec", image: "sec.jpg",          feminine: "sÃ¨che",            definition: "sans humiditÃ©, contraire d'humide" },
    { word: "doux", image: "doux.png",         feminine: "douce",            definition: "agrÃ©able, sans excÃ¨s de chaud ou de froid" },
    { word: "chaud", image: "chaud.png",        feminine: "chaude",           definition: "Ã  haute tempÃ©rature, contraire de froid" },
    { word: "froid", image: "froid.png",        feminine: "froide",           definition: "Ã  basse tempÃ©rature, contraire de chaud" },
    { word: "frais", image: "frais.png",        feminine: "fraÃ®che",          definition: "lÃ©gÃ¨rement froid, agrÃ©ablement frais" },
  ],
  sentences: [
    { sentence: "Il fait beau, le ___ brille dans le ciel.",              answer: "soleil" },
    { sentence: "Le ciel est couvert de ___ noir, il va pleuvoir.",       answer: "nuage" },
    { sentence: "AprÃ¨s la ___, on peut voir un arc-en-ciel.",             answer: "pluie" },
  ],
};
