import type { VocabTheme } from "../../vocabulary-data";

export const V2_JOURS_MOIS_DATES_THEME: VocabTheme = {
  slug: "v2-jours-mois-dates",
  code: "V2.1",
  title: "Jours, Mois et Dates",
  section: "V2",
  words: [
    { word: "jour",      article: "le",  gender: "m", group: "Calendrier", definition: "période de 24 heures" },
    { word: "mois",      article: "le",  gender: "m", group: "Calendrier", definition: "division de l'année en 12 parties" },
    { word: "semaine",   article: "la",  gender: "f", group: "Calendrier", definition: "période de 7 jours" },
    { word: "année",     article: "l'",  gender: "f", group: "Calendrier", definition: "durée de 12 mois" },
    { word: "lundi",      group: "Jours",  definition: "premier jour de la semaine" },
    { word: "mardi",      group: "Jours",  definition: "deuxième jour de la semaine" },
    { word: "mercredi",   group: "Jours",  definition: "troisième jour de la semaine" },
    { word: "jeudi",      group: "Jours",  definition: "quatrième jour de la semaine" },
    { word: "vendredi",   group: "Jours",  definition: "cinquième jour de la semaine" },
    { word: "samedi",     group: "Jours",  definition: "sixième jour de la semaine" },
    { word: "dimanche",   group: "Jours",  definition: "septième jour de la semaine" },
    { word: "janvier",    group: "Mois",   definition: "premier mois de l'année" },
    { word: "février",    group: "Mois",   definition: "deuxième mois de l'année" },
    { word: "mars",       group: "Mois",   definition: "troisième mois de l'année" },
    { word: "avril",      group: "Mois",   definition: "quatrième mois de l'année" },
    { word: "mai",        group: "Mois",   definition: "cinquième mois de l'année" },
    { word: "juin",       group: "Mois",   definition: "sixième mois de l'année" },
    { word: "juillet",    group: "Mois",   definition: "septième mois de l'année" },
    { word: "août",       group: "Mois",   definition: "huitième mois de l'année" },
    { word: "septembre",  group: "Mois",   definition: "neuvième mois de l'année" },
    { word: "octobre",    group: "Mois",   definition: "dixième mois de l'année" },
    { word: "novembre",   group: "Mois",   definition: "onzième mois de l'année" },
    { word: "décembre",   group: "Mois",   definition: "douzième mois de l'année" },
  ],
  sentences: [
    { sentence: "Nous avons cours de sport le ___.",               answer: "mercredi" },
    { sentence: "Mon anniversaire est en ___.",                    answer: "juin" },
    { sentence: "Le ___ est le dernier jour du week-end.",         answer: "dimanche" },
    { sentence: "Les vacances d'été commencent en ___.",           answer: "juillet" },
    { sentence: "Noël est le 25 ___.",                             answer: "décembre" },
  ],
};
