import type { VocabTheme } from "../../vocabulary-data";

export const V7_FRUITS_THEME: VocabTheme = {
  slug: "v7-fruits",
  code: "V7.1",
  title: "Les fruits",
  section: "V7",
  words: [
    { word: "pomme",      image: "pomme.webp",      article: "la",  gender: "f", definition: "fruit rouge ou vert de forme ronde" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une pomme au marché.",
          "Demain, je vais préparer la pomme pour le repas.",
          "Quand j'étais petit, je mangeais souvent la pomme.",
          "Ce matin, elle a lavé la pomme avant de cuisiner.",
          "Nous avons ajouté la pomme dans la recette.",
          "Ils vont servir la pomme avec le plat principal.",
          "J'ai choisi une pomme parce qu'elle était fraîche.",
          "Elle a coupé la pomme en petits morceaux.",
          "Avant le dîner, nous avons goûté la pomme.",
          "Le vendeur a conseillé la pomme à ma mère.",
          "Je vais acheter une pomme après le travail.",
          "Nous avons gardé la pomme au réfrigérateur.",
          "Hier soir, mon frère a mangé la pomme.",
          "Pendant les vacances, nous préparions souvent la pomme.",
          "Elle a oublié une pomme dans le sac.",
          "Il va utiliser la pomme pour faire une sauce.",
          "Nous avons commandé la pomme au restaurant.",
          "Ce week-end, je vais cuisiner la pomme.",
          "Le cuisinier a ajouté la pomme dans l'assiette.",
          "J'ai goûté la pomme pour la première fois.",
          "Ma sœur a choisi la pomme pour le dessert.",
          "Ils ont partagé une pomme à midi.",
          "Nous allons servir la pomme avec du pain.",
          "Elle a acheté une pomme pour la recette.",
          "Le client a demandé la pomme au serveur.",
          "Après la leçon, j'ai utilisé le mot pomme dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pomme.",
          "Quand je lis le texte, je cherche le sens de pomme.",
          "Ce matin, nous avons associé la pomme à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pomme.",
          "Le professeur a demandé un exemple avec la pomme.",
          "J'ai choisi la pomme parce que ce mot était dans la liste.",
          "Nous allons réviser la pomme avant l'évaluation.",
          "Mon camarade a expliqué la pomme avec ses mots.",
          "J'ai ajouté pomme dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pomme soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la pomme était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la pomme, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la pomme dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la pomme.",
          "La recette que nous préparons utilise la pomme pour équilibrer les saveurs.",
          "Pendant que le chef coupait la pomme, les autres préparaient la table.",
          "Puisque la pomme était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la pomme, tu pourras commencer la recette.",
          "Je pense que la pomme convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la pomme peut améliorer la présentation.",
          "Le produit dont je parle est la pomme, que beaucoup de clients apprécient.",
          "Tant que la pomme restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la pomme est très demandée en cuisine.",
          "Si le restaurant propose la pomme, je choisirai ce plat sans hésiter.",
          "Bien que le mot pomme paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pomme apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pomme, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pomme, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pomme.",
          "Lorsque j'aurai mémorisé pomme, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pomme.",
          "Puisque pomme est utile, je le révise régulièrement.",
        ],
      } },
    { word: "poire",      image: "poire.webp",      article: "la",  gender: "f", definition: "fruit jaune-vert de forme allongée" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une poire au marché.",
          "Demain, je vais préparer la poire pour le repas.",
          "Quand j'étais petit, je mangeais souvent la poire.",
          "Ce matin, elle a lavé la poire avant de cuisiner.",
          "Nous avons ajouté la poire dans la recette.",
          "Ils vont servir la poire avec le plat principal.",
          "J'ai choisi une poire parce qu'elle était fraîche.",
          "Elle a coupé la poire en petits morceaux.",
          "Avant le dîner, nous avons goûté la poire.",
          "Le vendeur a conseillé la poire à ma mère.",
          "Je vais acheter une poire après le travail.",
          "Nous avons gardé la poire au réfrigérateur.",
          "Hier soir, mon frère a mangé la poire.",
          "Pendant les vacances, nous préparions souvent la poire.",
          "Elle a oublié une poire dans le sac.",
          "Il va utiliser la poire pour faire une sauce.",
          "Nous avons commandé la poire au restaurant.",
          "Ce week-end, je vais cuisiner la poire.",
          "Le cuisinier a ajouté la poire dans l'assiette.",
          "J'ai goûté la poire pour la première fois.",
          "Ma sœur a choisi la poire pour le dessert.",
          "Ils ont partagé une poire à midi.",
          "Nous allons servir la poire avec du pain.",
          "Elle a acheté une poire pour la recette.",
          "Le client a demandé la poire au serveur.",
          "Après la leçon, j'ai utilisé le mot poire dans une phrase.",
          "Demain, je vais apprendre à mieux employer la poire.",
          "Quand je lis le texte, je cherche le sens de poire.",
          "Ce matin, nous avons associé la poire à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec poire.",
          "Le professeur a demandé un exemple avec la poire.",
          "J'ai choisi la poire parce que ce mot était dans la liste.",
          "Nous allons réviser la poire avant l'évaluation.",
          "Mon camarade a expliqué la poire avec ses mots.",
          "J'ai ajouté poire dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la poire soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la poire était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la poire, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la poire dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la poire.",
          "La recette que nous préparons utilise la poire pour équilibrer les saveurs.",
          "Pendant que le chef coupait la poire, les autres préparaient la table.",
          "Puisque la poire était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la poire, tu pourras commencer la recette.",
          "Je pense que la poire convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la poire peut améliorer la présentation.",
          "Le produit dont je parle est la poire, que beaucoup de clients apprécient.",
          "Tant que la poire restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la poire est très demandée en cuisine.",
          "Si le restaurant propose la poire, je choisirai ce plat sans hésiter.",
          "Bien que le mot poire paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la poire apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la poire, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà poire, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la poire.",
          "Lorsque j'aurai mémorisé poire, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la poire.",
          "Puisque poire est utile, je le révise régulièrement.",
        ],
      } },
    { word: "banane",     image: "banane.webp",     article: "la",  gender: "f", definition: "fruit jaune courbé à peau épaisse" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une banane au marché.",
          "Demain, je vais préparer la banane pour le repas.",
          "Quand j'étais petit, je mangeais souvent la banane.",
          "Ce matin, elle a lavé la banane avant de cuisiner.",
          "Nous avons ajouté la banane dans la recette.",
          "Ils vont servir la banane avec le plat principal.",
          "J'ai choisi une banane parce qu'elle était fraîche.",
          "Elle a coupé la banane en petits morceaux.",
          "Avant le dîner, nous avons goûté la banane.",
          "Le vendeur a conseillé la banane à ma mère.",
          "Je vais acheter une banane après le travail.",
          "Nous avons gardé la banane au réfrigérateur.",
          "Hier soir, mon frère a mangé la banane.",
          "Pendant les vacances, nous préparions souvent la banane.",
          "Elle a oublié une banane dans le sac.",
          "Il va utiliser la banane pour faire une sauce.",
          "Nous avons commandé la banane au restaurant.",
          "Ce week-end, je vais cuisiner la banane.",
          "Le cuisinier a ajouté la banane dans l'assiette.",
          "J'ai goûté la banane pour la première fois.",
          "Ma sœur a choisi la banane pour le dessert.",
          "Ils ont partagé une banane à midi.",
          "Nous allons servir la banane avec du pain.",
          "Elle a acheté une banane pour la recette.",
          "Le client a demandé la banane au serveur.",
          "Après la leçon, j'ai utilisé le mot banane dans une phrase.",
          "Demain, je vais apprendre à mieux employer la banane.",
          "Quand je lis le texte, je cherche le sens de banane.",
          "Ce matin, nous avons associé la banane à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec banane.",
          "Le professeur a demandé un exemple avec la banane.",
          "J'ai choisi la banane parce que ce mot était dans la liste.",
          "Nous allons réviser la banane avant l'évaluation.",
          "Mon camarade a expliqué la banane avec ses mots.",
          "J'ai ajouté banane dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la banane soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la banane était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la banane, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la banane dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la banane.",
          "La recette que nous préparons utilise la banane pour équilibrer les saveurs.",
          "Pendant que le chef coupait la banane, les autres préparaient la table.",
          "Puisque la banane était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la banane, tu pourras commencer la recette.",
          "Je pense que la banane convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la banane peut améliorer la présentation.",
          "Le produit dont je parle est la banane, que beaucoup de clients apprécient.",
          "Tant que la banane restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la banane est très demandée en cuisine.",
          "Si le restaurant propose la banane, je choisirai ce plat sans hésiter.",
          "Bien que le mot banane paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la banane apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la banane, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà banane, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la banane.",
          "Lorsque j'aurai mémorisé banane, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la banane.",
          "Puisque banane est utile, je le révise régulièrement.",
        ],
      } },
    { word: "orange",     image: "orange.webp",     article: "l'",  gender: "f", definition: "fruit rond orange à peau épaisse" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une orange au marché.",
          "Demain, je vais préparer l'orange pour le repas.",
          "Quand j'étais petit, je mangeais souvent l'orange.",
          "Ce matin, elle a lavé l'orange avant de cuisiner.",
          "Nous avons ajouté l'orange dans la recette.",
          "Ils vont servir l'orange avec le plat principal.",
          "J'ai choisi une orange parce qu'elle était fraîche.",
          "Elle a coupé l'orange en petits morceaux.",
          "Avant le dîner, nous avons goûté l'orange.",
          "Le vendeur a conseillé l'orange à ma mère.",
          "Je vais acheter une orange après le travail.",
          "Nous avons gardé l'orange au réfrigérateur.",
          "Hier soir, mon frère a mangé l'orange.",
          "Pendant les vacances, nous préparions souvent l'orange.",
          "Elle a oublié une orange dans le sac.",
          "Il va utiliser l'orange pour faire une sauce.",
          "Nous avons commandé l'orange au restaurant.",
          "Ce week-end, je vais cuisiner l'orange.",
          "Le cuisinier a ajouté l'orange dans l'assiette.",
          "J'ai goûté l'orange pour la première fois.",
          "Ma sœur a choisi l'orange pour le dessert.",
          "Ils ont partagé une orange à midi.",
          "Nous allons servir l'orange avec du pain.",
          "Elle a acheté une orange pour la recette.",
          "Le client a demandé l'orange au serveur.",
          "Après la leçon, j'ai utilisé le mot orange dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'orange.",
          "Quand je lis le texte, je cherche le sens de orange.",
          "Ce matin, nous avons associé l'orange à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec orange.",
          "Le professeur a demandé un exemple avec l'orange.",
          "J'ai choisi l'orange parce que ce mot était dans la liste.",
          "Nous allons réviser l'orange avant l'évaluation.",
          "Mon camarade a expliqué l'orange avec ses mots.",
          "J'ai ajouté orange dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'orange soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme l'orange était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes l'orange, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie l'orange dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi l'orange.",
          "La recette que nous préparons utilise l'orange pour équilibrer les saveurs.",
          "Pendant que le chef coupait l'orange, les autres préparaient la table.",
          "Puisque l'orange était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé l'orange, tu pourras commencer la recette.",
          "Je pense que l'orange convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, l'orange peut améliorer la présentation.",
          "Le produit dont je parle est l'orange, que beaucoup de clients apprécient.",
          "Tant que l'orange restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, l'orange est très demandée en cuisine.",
          "Si le restaurant propose l'orange, je choisirai ce plat sans hésiter.",
          "Bien que le mot orange paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'orange apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'orange, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà orange, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'orange.",
          "Lorsque j'aurai mémorisé orange, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'orange.",
          "Puisque orange est utile, je le révise régulièrement.",
        ],
      } },
    { word: "fraise",     image: "fraise.webp",     article: "la",  gender: "f", definition: "petit fruit rouge et sucré" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une fraise au marché.",
          "Demain, je vais préparer la fraise pour le repas.",
          "Quand j'étais petit, je mangeais souvent la fraise.",
          "Ce matin, elle a lavé la fraise avant de cuisiner.",
          "Nous avons ajouté la fraise dans la recette.",
          "Ils vont servir la fraise avec le plat principal.",
          "J'ai choisi une fraise parce qu'elle était fraîche.",
          "Elle a coupé la fraise en petits morceaux.",
          "Avant le dîner, nous avons goûté la fraise.",
          "Le vendeur a conseillé la fraise à ma mère.",
          "Je vais acheter une fraise après le travail.",
          "Nous avons gardé la fraise au réfrigérateur.",
          "Hier soir, mon frère a mangé la fraise.",
          "Pendant les vacances, nous préparions souvent la fraise.",
          "Elle a oublié une fraise dans le sac.",
          "Il va utiliser la fraise pour faire une sauce.",
          "Nous avons commandé la fraise au restaurant.",
          "Ce week-end, je vais cuisiner la fraise.",
          "Le cuisinier a ajouté la fraise dans l'assiette.",
          "J'ai goûté la fraise pour la première fois.",
          "Ma sœur a choisi la fraise pour le dessert.",
          "Ils ont partagé une fraise à midi.",
          "Nous allons servir la fraise avec du pain.",
          "Elle a acheté une fraise pour la recette.",
          "Le client a demandé la fraise au serveur.",
          "Après la leçon, j'ai utilisé le mot fraise dans une phrase.",
          "Demain, je vais apprendre à mieux employer la fraise.",
          "Quand je lis le texte, je cherche le sens de fraise.",
          "Ce matin, nous avons associé la fraise à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec fraise.",
          "Le professeur a demandé un exemple avec la fraise.",
          "J'ai choisi la fraise parce que ce mot était dans la liste.",
          "Nous allons réviser la fraise avant l'évaluation.",
          "Mon camarade a expliqué la fraise avec ses mots.",
          "J'ai ajouté fraise dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la fraise soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la fraise était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la fraise, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la fraise dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la fraise.",
          "La recette que nous préparons utilise la fraise pour équilibrer les saveurs.",
          "Pendant que le chef coupait la fraise, les autres préparaient la table.",
          "Puisque la fraise était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la fraise, tu pourras commencer la recette.",
          "Je pense que la fraise convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la fraise peut améliorer la présentation.",
          "Le produit dont je parle est la fraise, que beaucoup de clients apprécient.",
          "Tant que la fraise restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la fraise est très demandée en cuisine.",
          "Si le restaurant propose la fraise, je choisirai ce plat sans hésiter.",
          "Bien que le mot fraise paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la fraise apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la fraise, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà fraise, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la fraise.",
          "Lorsque j'aurai mémorisé fraise, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la fraise.",
          "Puisque fraise est utile, je le révise régulièrement.",
        ],
      } },
    { word: "framboise",  image: "framboise.webp",  article: "la",  gender: "f", definition: "petit fruit rouge composé de petites boules" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une framboise au marché.",
          "Demain, je vais préparer la framboise pour le repas.",
          "Quand j'étais petit, je mangeais souvent la framboise.",
          "Ce matin, elle a lavé la framboise avant de cuisiner.",
          "Nous avons ajouté la framboise dans la recette.",
          "Ils vont servir la framboise avec le plat principal.",
          "J'ai choisi une framboise parce qu'elle était fraîche.",
          "Elle a coupé la framboise en petits morceaux.",
          "Avant le dîner, nous avons goûté la framboise.",
          "Le vendeur a conseillé la framboise à ma mère.",
          "Je vais acheter une framboise après le travail.",
          "Nous avons gardé la framboise au réfrigérateur.",
          "Hier soir, mon frère a mangé la framboise.",
          "Pendant les vacances, nous préparions souvent la framboise.",
          "Elle a oublié une framboise dans le sac.",
          "Il va utiliser la framboise pour faire une sauce.",
          "Nous avons commandé la framboise au restaurant.",
          "Ce week-end, je vais cuisiner la framboise.",
          "Le cuisinier a ajouté la framboise dans l'assiette.",
          "J'ai goûté la framboise pour la première fois.",
          "Ma sœur a choisi la framboise pour le dessert.",
          "Ils ont partagé une framboise à midi.",
          "Nous allons servir la framboise avec du pain.",
          "Elle a acheté une framboise pour la recette.",
          "Le client a demandé la framboise au serveur.",
          "Après la leçon, j'ai utilisé le mot framboise dans une phrase.",
          "Demain, je vais apprendre à mieux employer la framboise.",
          "Quand je lis le texte, je cherche le sens de framboise.",
          "Ce matin, nous avons associé la framboise à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec framboise.",
          "Le professeur a demandé un exemple avec la framboise.",
          "J'ai choisi la framboise parce que ce mot était dans la liste.",
          "Nous allons réviser la framboise avant l'évaluation.",
          "Mon camarade a expliqué la framboise avec ses mots.",
          "J'ai ajouté framboise dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la framboise soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la framboise était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la framboise, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la framboise dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la framboise.",
          "La recette que nous préparons utilise la framboise pour équilibrer les saveurs.",
          "Pendant que le chef coupait la framboise, les autres préparaient la table.",
          "Puisque la framboise était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la framboise, tu pourras commencer la recette.",
          "Je pense que la framboise convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la framboise peut améliorer la présentation.",
          "Le produit dont je parle est la framboise, que beaucoup de clients apprécient.",
          "Tant que la framboise restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la framboise est très demandée en cuisine.",
          "Si le restaurant propose la framboise, je choisirai ce plat sans hésiter.",
          "Bien que le mot framboise paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la framboise apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la framboise, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà framboise, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la framboise.",
          "Lorsque j'aurai mémorisé framboise, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la framboise.",
          "Puisque framboise est utile, je le révise régulièrement.",
        ],
      } },
    { word: "raisin",     image: "raisin.webp",     article: "le",  gender: "m", definition: "fruit en grappes, violet ou vert" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un raisin au marché.",
          "Demain, je vais préparer le raisin pour le repas.",
          "Quand j'étais petit, je mangeais souvent le raisin.",
          "Ce matin, elle a lavé le raisin avant de cuisiner.",
          "Nous avons ajouté le raisin dans la recette.",
          "Ils vont servir le raisin avec le plat principal.",
          "J'ai choisi un raisin parce qu'il était frais.",
          "Elle a coupé le raisin en petits morceaux.",
          "Avant le dîner, nous avons goûté le raisin.",
          "Le vendeur a conseillé le raisin à ma mère.",
          "Je vais acheter un raisin après le travail.",
          "Nous avons gardé le raisin au réfrigérateur.",
          "Hier soir, mon frère a mangé le raisin.",
          "Pendant les vacances, nous préparions souvent le raisin.",
          "Elle a oublié un raisin dans le sac.",
          "Il va utiliser le raisin pour faire une sauce.",
          "Nous avons commandé le raisin au restaurant.",
          "Ce week-end, je vais cuisiner le raisin.",
          "Le cuisinier a ajouté le raisin dans l'assiette.",
          "J'ai goûté le raisin pour la première fois.",
          "Ma sœur a choisi le raisin pour le dessert.",
          "Ils ont partagé un raisin à midi.",
          "Nous allons servir le raisin avec du pain.",
          "Elle a acheté un raisin pour la recette.",
          "Le client a demandé le raisin au serveur.",
          "Après la leçon, j'ai utilisé le mot raisin dans une phrase.",
          "Demain, je vais apprendre à mieux employer le raisin.",
          "Quand je lis le texte, je cherche le sens de raisin.",
          "Ce matin, nous avons associé le raisin à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec raisin.",
          "Le professeur a demandé un exemple avec le raisin.",
          "J'ai choisi le raisin parce que ce mot était dans la liste.",
          "Nous allons réviser le raisin avant l'évaluation.",
          "Mon camarade a expliqué le raisin avec ses mots.",
          "J'ai ajouté raisin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le raisin soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le raisin était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le raisin, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le raisin dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le raisin.",
          "La recette que nous préparons utilise le raisin pour équilibrer les saveurs.",
          "Pendant que le chef coupait le raisin, les autres préparaient la table.",
          "Puisque le raisin était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le raisin, tu pourras commencer la recette.",
          "Je pense que le raisin convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le raisin peut améliorer la présentation.",
          "Le produit dont je parle est le raisin, que beaucoup de clients apprécient.",
          "Tant que le raisin restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le raisin est très demandé en cuisine.",
          "Si le restaurant propose le raisin, je choisirai ce plat sans hésiter.",
          "Bien que le mot raisin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le raisin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le raisin, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà raisin, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le raisin.",
          "Lorsque j'aurai mémorisé raisin, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le raisin.",
          "Puisque raisin est utile, je le révise régulièrement.",
        ],
      } },
    { word: "kiwi",       image: "kiwi.webp",       article: "le",  gender: "m", definition: "petit fruit vert à peau brune et velue" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un kiwi au marché.",
          "Demain, je vais préparer le kiwi pour le repas.",
          "Quand j'étais petit, je mangeais souvent le kiwi.",
          "Ce matin, elle a lavé le kiwi avant de cuisiner.",
          "Nous avons ajouté le kiwi dans la recette.",
          "Ils vont servir le kiwi avec le plat principal.",
          "J'ai choisi un kiwi parce qu'il était frais.",
          "Elle a coupé le kiwi en petits morceaux.",
          "Avant le dîner, nous avons goûté le kiwi.",
          "Le vendeur a conseillé le kiwi à ma mère.",
          "Je vais acheter un kiwi après le travail.",
          "Nous avons gardé le kiwi au réfrigérateur.",
          "Hier soir, mon frère a mangé le kiwi.",
          "Pendant les vacances, nous préparions souvent le kiwi.",
          "Elle a oublié un kiwi dans le sac.",
          "Il va utiliser le kiwi pour faire une sauce.",
          "Nous avons commandé le kiwi au restaurant.",
          "Ce week-end, je vais cuisiner le kiwi.",
          "Le cuisinier a ajouté le kiwi dans l'assiette.",
          "J'ai goûté le kiwi pour la première fois.",
          "Ma sœur a choisi le kiwi pour le dessert.",
          "Ils ont partagé un kiwi à midi.",
          "Nous allons servir le kiwi avec du pain.",
          "Elle a acheté un kiwi pour la recette.",
          "Le client a demandé le kiwi au serveur.",
          "Après la leçon, j'ai utilisé le mot kiwi dans une phrase.",
          "Demain, je vais apprendre à mieux employer le kiwi.",
          "Quand je lis le texte, je cherche le sens de kiwi.",
          "Ce matin, nous avons associé le kiwi à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec kiwi.",
          "Le professeur a demandé un exemple avec le kiwi.",
          "J'ai choisi le kiwi parce que ce mot était dans la liste.",
          "Nous allons réviser le kiwi avant l'évaluation.",
          "Mon camarade a expliqué le kiwi avec ses mots.",
          "J'ai ajouté kiwi dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le kiwi soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le kiwi était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le kiwi, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le kiwi dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le kiwi.",
          "La recette que nous préparons utilise le kiwi pour équilibrer les saveurs.",
          "Pendant que le chef coupait le kiwi, les autres préparaient la table.",
          "Puisque le kiwi était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le kiwi, tu pourras commencer la recette.",
          "Je pense que le kiwi convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le kiwi peut améliorer la présentation.",
          "Le produit dont je parle est le kiwi, que beaucoup de clients apprécient.",
          "Tant que le kiwi restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le kiwi est très demandé en cuisine.",
          "Si le restaurant propose le kiwi, je choisirai ce plat sans hésiter.",
          "Bien que le mot kiwi paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le kiwi apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le kiwi, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà kiwi, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le kiwi.",
          "Lorsque j'aurai mémorisé kiwi, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le kiwi.",
          "Puisque kiwi est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pêche",      image: "peche.webp",      article: "la",  gender: "f", definition: "fruit juteux à peau veloutée, orange ou jaune" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une pêche au marché.",
          "Demain, je vais préparer la pêche pour le repas.",
          "Quand j'étais petit, je mangeais souvent la pêche.",
          "Ce matin, elle a lavé la pêche avant de cuisiner.",
          "Nous avons ajouté la pêche dans la recette.",
          "Ils vont servir la pêche avec le plat principal.",
          "J'ai choisi une pêche parce qu'elle était fraîche.",
          "Elle a coupé la pêche en petits morceaux.",
          "Avant le dîner, nous avons goûté la pêche.",
          "Le vendeur a conseillé la pêche à ma mère.",
          "Je vais acheter une pêche après le travail.",
          "Nous avons gardé la pêche au réfrigérateur.",
          "Hier soir, mon frère a mangé la pêche.",
          "Pendant les vacances, nous préparions souvent la pêche.",
          "Elle a oublié une pêche dans le sac.",
          "Il va utiliser la pêche pour faire une sauce.",
          "Nous avons commandé la pêche au restaurant.",
          "Ce week-end, je vais cuisiner la pêche.",
          "Le cuisinier a ajouté la pêche dans l'assiette.",
          "J'ai goûté la pêche pour la première fois.",
          "Ma sœur a choisi la pêche pour le dessert.",
          "Ils ont partagé une pêche à midi.",
          "Nous allons servir la pêche avec du pain.",
          "Elle a acheté une pêche pour la recette.",
          "Le client a demandé la pêche au serveur.",
          "Après la leçon, j'ai utilisé le mot pêche dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pêche.",
          "Quand je lis le texte, je cherche le sens de pêche.",
          "Ce matin, nous avons associé la pêche à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pêche.",
          "Le professeur a demandé un exemple avec la pêche.",
          "J'ai choisi la pêche parce que ce mot était dans la liste.",
          "Nous allons réviser la pêche avant l'évaluation.",
          "Mon camarade a expliqué la pêche avec ses mots.",
          "J'ai ajouté pêche dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pêche soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la pêche était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la pêche, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la pêche dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la pêche.",
          "La recette que nous préparons utilise la pêche pour équilibrer les saveurs.",
          "Pendant que le chef coupait la pêche, les autres préparaient la table.",
          "Puisque la pêche était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la pêche, tu pourras commencer la recette.",
          "Je pense que la pêche convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la pêche peut améliorer la présentation.",
          "Le produit dont je parle est la pêche, que beaucoup de clients apprécient.",
          "Tant que la pêche restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la pêche est très demandée en cuisine.",
          "Si le restaurant propose la pêche, je choisirai ce plat sans hésiter.",
          "Bien que le mot pêche paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pêche apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pêche, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pêche, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pêche.",
          "Lorsque j'aurai mémorisé pêche, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pêche.",
          "Puisque pêche est utile, je le révise régulièrement.",
        ],
      } },
    { word: "abricot",    image: "abricot.webp",    article: "l'",  gender: "m", definition: "petit fruit orange et sucré" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un abricot au marché.",
          "Demain, je vais préparer l'abricot pour le repas.",
          "Quand j'étais petit, je mangeais souvent l'abricot.",
          "Ce matin, elle a lavé l'abricot avant de cuisiner.",
          "Nous avons ajouté l'abricot dans la recette.",
          "Ils vont servir l'abricot avec le plat principal.",
          "J'ai choisi un abricot parce qu'il était frais.",
          "Elle a coupé l'abricot en petits morceaux.",
          "Avant le dîner, nous avons goûté l'abricot.",
          "Le vendeur a conseillé l'abricot à ma mère.",
          "Je vais acheter un abricot après le travail.",
          "Nous avons gardé l'abricot au réfrigérateur.",
          "Hier soir, mon frère a mangé l'abricot.",
          "Pendant les vacances, nous préparions souvent l'abricot.",
          "Elle a oublié un abricot dans le sac.",
          "Il va utiliser l'abricot pour faire une sauce.",
          "Nous avons commandé l'abricot au restaurant.",
          "Ce week-end, je vais cuisiner l'abricot.",
          "Le cuisinier a ajouté l'abricot dans l'assiette.",
          "J'ai goûté l'abricot pour la première fois.",
          "Ma sœur a choisi l'abricot pour le dessert.",
          "Ils ont partagé un abricot à midi.",
          "Nous allons servir l'abricot avec du pain.",
          "Elle a acheté un abricot pour la recette.",
          "Le client a demandé l'abricot au serveur.",
          "Après la leçon, j'ai utilisé le mot abricot dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'abricot.",
          "Quand je lis le texte, je cherche le sens de abricot.",
          "Ce matin, nous avons associé l'abricot à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec abricot.",
          "Le professeur a demandé un exemple avec l'abricot.",
          "J'ai choisi l'abricot parce que ce mot était dans la liste.",
          "Nous allons réviser l'abricot avant l'évaluation.",
          "Mon camarade a expliqué l'abricot avec ses mots.",
          "J'ai ajouté abricot dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'abricot soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme l'abricot était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes l'abricot, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie l'abricot dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi l'abricot.",
          "La recette que nous préparons utilise l'abricot pour équilibrer les saveurs.",
          "Pendant que le chef coupait l'abricot, les autres préparaient la table.",
          "Puisque l'abricot était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé l'abricot, tu pourras commencer la recette.",
          "Je pense que l'abricot convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, l'abricot peut améliorer la présentation.",
          "Le produit dont je parle est l'abricot, que beaucoup de clients apprécient.",
          "Tant que l'abricot restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, l'abricot est très demandé en cuisine.",
          "Si le restaurant propose l'abricot, je choisirai ce plat sans hésiter.",
          "Bien que le mot abricot paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'abricot apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'abricot, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà abricot, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'abricot.",
          "Lorsque j'aurai mémorisé abricot, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'abricot.",
          "Puisque abricot est utile, je le révise régulièrement.",
        ],
      } },
    { word: "cerise",     image: "cerise.webp",     article: "la",  gender: "f", definition: "petit fruit rond rouge sur une tige" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une cerise au marché.",
          "Demain, je vais préparer la cerise pour le repas.",
          "Quand j'étais petit, je mangeais souvent la cerise.",
          "Ce matin, elle a lavé la cerise avant de cuisiner.",
          "Nous avons ajouté la cerise dans la recette.",
          "Ils vont servir la cerise avec le plat principal.",
          "J'ai choisi une cerise parce qu'elle était fraîche.",
          "Elle a coupé la cerise en petits morceaux.",
          "Avant le dîner, nous avons goûté la cerise.",
          "Le vendeur a conseillé la cerise à ma mère.",
          "Je vais acheter une cerise après le travail.",
          "Nous avons gardé la cerise au réfrigérateur.",
          "Hier soir, mon frère a mangé la cerise.",
          "Pendant les vacances, nous préparions souvent la cerise.",
          "Elle a oublié une cerise dans le sac.",
          "Il va utiliser la cerise pour faire une sauce.",
          "Nous avons commandé la cerise au restaurant.",
          "Ce week-end, je vais cuisiner la cerise.",
          "Le cuisinier a ajouté la cerise dans l'assiette.",
          "J'ai goûté la cerise pour la première fois.",
          "Ma sœur a choisi la cerise pour le dessert.",
          "Ils ont partagé une cerise à midi.",
          "Nous allons servir la cerise avec du pain.",
          "Elle a acheté une cerise pour la recette.",
          "Le client a demandé la cerise au serveur.",
          "Après la leçon, j'ai utilisé le mot cerise dans une phrase.",
          "Demain, je vais apprendre à mieux employer la cerise.",
          "Quand je lis le texte, je cherche le sens de cerise.",
          "Ce matin, nous avons associé la cerise à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec cerise.",
          "Le professeur a demandé un exemple avec la cerise.",
          "J'ai choisi la cerise parce que ce mot était dans la liste.",
          "Nous allons réviser la cerise avant l'évaluation.",
          "Mon camarade a expliqué la cerise avec ses mots.",
          "J'ai ajouté cerise dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la cerise soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la cerise était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la cerise, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la cerise dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la cerise.",
          "La recette que nous préparons utilise la cerise pour équilibrer les saveurs.",
          "Pendant que le chef coupait la cerise, les autres préparaient la table.",
          "Puisque la cerise était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la cerise, tu pourras commencer la recette.",
          "Je pense que la cerise convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la cerise peut améliorer la présentation.",
          "Le produit dont je parle est la cerise, que beaucoup de clients apprécient.",
          "Tant que la cerise restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la cerise est très demandée en cuisine.",
          "Si le restaurant propose la cerise, je choisirai ce plat sans hésiter.",
          "Bien que le mot cerise paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la cerise apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la cerise, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà cerise, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la cerise.",
          "Lorsque j'aurai mémorisé cerise, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la cerise.",
          "Puisque cerise est utile, je le révise régulièrement.",
        ],
      } },
    { word: "prune",      image: "prune.webp",      article: "la",  gender: "f", definition: "petit fruit violet ou rouge à noyau" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une prune au marché.",
          "Demain, je vais préparer la prune pour le repas.",
          "Quand j'étais petit, je mangeais souvent la prune.",
          "Ce matin, elle a lavé la prune avant de cuisiner.",
          "Nous avons ajouté la prune dans la recette.",
          "Ils vont servir la prune avec le plat principal.",
          "J'ai choisi une prune parce qu'elle était fraîche.",
          "Elle a coupé la prune en petits morceaux.",
          "Avant le dîner, nous avons goûté la prune.",
          "Le vendeur a conseillé la prune à ma mère.",
          "Je vais acheter une prune après le travail.",
          "Nous avons gardé la prune au réfrigérateur.",
          "Hier soir, mon frère a mangé la prune.",
          "Pendant les vacances, nous préparions souvent la prune.",
          "Elle a oublié une prune dans le sac.",
          "Il va utiliser la prune pour faire une sauce.",
          "Nous avons commandé la prune au restaurant.",
          "Ce week-end, je vais cuisiner la prune.",
          "Le cuisinier a ajouté la prune dans l'assiette.",
          "J'ai goûté la prune pour la première fois.",
          "Ma sœur a choisi la prune pour le dessert.",
          "Ils ont partagé une prune à midi.",
          "Nous allons servir la prune avec du pain.",
          "Elle a acheté une prune pour la recette.",
          "Le client a demandé la prune au serveur.",
          "Après la leçon, j'ai utilisé le mot prune dans une phrase.",
          "Demain, je vais apprendre à mieux employer la prune.",
          "Quand je lis le texte, je cherche le sens de prune.",
          "Ce matin, nous avons associé la prune à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec prune.",
          "Le professeur a demandé un exemple avec la prune.",
          "J'ai choisi la prune parce que ce mot était dans la liste.",
          "Nous allons réviser la prune avant l'évaluation.",
          "Mon camarade a expliqué la prune avec ses mots.",
          "J'ai ajouté prune dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la prune soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la prune était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la prune, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la prune dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la prune.",
          "La recette que nous préparons utilise la prune pour équilibrer les saveurs.",
          "Pendant que le chef coupait la prune, les autres préparaient la table.",
          "Puisque la prune était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la prune, tu pourras commencer la recette.",
          "Je pense que la prune convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la prune peut améliorer la présentation.",
          "Le produit dont je parle est la prune, que beaucoup de clients apprécient.",
          "Tant que la prune restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la prune est très demandée en cuisine.",
          "Si le restaurant propose la prune, je choisirai ce plat sans hésiter.",
          "Bien que le mot prune paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la prune apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la prune, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà prune, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la prune.",
          "Lorsque j'aurai mémorisé prune, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la prune.",
          "Puisque prune est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ananas",                               article: "l'",  gender: "m", definition: "grand fruit tropical avec une couronne de feuilles" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un ananas au marché.",
          "Demain, je vais préparer l'ananas pour le repas.",
          "Quand j'étais petit, je mangeais souvent l'ananas.",
          "Ce matin, elle a lavé l'ananas avant de cuisiner.",
          "Nous avons ajouté l'ananas dans la recette.",
          "Ils vont servir l'ananas avec le plat principal.",
          "J'ai choisi un ananas parce qu'il était frais.",
          "Elle a coupé l'ananas en petits morceaux.",
          "Avant le dîner, nous avons goûté l'ananas.",
          "Le vendeur a conseillé l'ananas à ma mère.",
          "Je vais acheter un ananas après le travail.",
          "Nous avons gardé l'ananas au réfrigérateur.",
          "Hier soir, mon frère a mangé l'ananas.",
          "Pendant les vacances, nous préparions souvent l'ananas.",
          "Elle a oublié un ananas dans le sac.",
          "Il va utiliser l'ananas pour faire une sauce.",
          "Nous avons commandé l'ananas au restaurant.",
          "Ce week-end, je vais cuisiner l'ananas.",
          "Le cuisinier a ajouté l'ananas dans l'assiette.",
          "J'ai goûté l'ananas pour la première fois.",
          "Ma sœur a choisi l'ananas pour le dessert.",
          "Ils ont partagé un ananas à midi.",
          "Nous allons servir l'ananas avec du pain.",
          "Elle a acheté un ananas pour la recette.",
          "Le client a demandé l'ananas au serveur.",
          "Après la leçon, j'ai utilisé le mot ananas dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ananas.",
          "Quand je lis le texte, je cherche le sens de ananas.",
          "Ce matin, nous avons associé l'ananas à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ananas.",
          "Le professeur a demandé un exemple avec l'ananas.",
          "J'ai choisi l'ananas parce que ce mot était dans la liste.",
          "Nous allons réviser l'ananas avant l'évaluation.",
          "Mon camarade a expliqué l'ananas avec ses mots.",
          "J'ai ajouté ananas dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ananas soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme l'ananas était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes l'ananas, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie l'ananas dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi l'ananas.",
          "La recette que nous préparons utilise l'ananas pour équilibrer les saveurs.",
          "Pendant que le chef coupait l'ananas, les autres préparaient la table.",
          "Puisque l'ananas était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé l'ananas, tu pourras commencer la recette.",
          "Je pense que l'ananas convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, l'ananas peut améliorer la présentation.",
          "Le produit dont je parle est l'ananas, que beaucoup de clients apprécient.",
          "Tant que l'ananas restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, l'ananas est très demandé en cuisine.",
          "Si le restaurant propose l'ananas, je choisirai ce plat sans hésiter.",
          "Bien que le mot ananas paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ananas apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ananas, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ananas, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ananas.",
          "Lorsque j'aurai mémorisé ananas, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ananas.",
          "Puisque ananas est utile, je le révise régulièrement.",
        ],
      } },
    { word: "citron",                               article: "le",  gender: "m", definition: "fruit jaune très acide" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un citron au marché.",
          "Demain, je vais préparer le citron pour le repas.",
          "Quand j'étais petit, je mangeais souvent le citron.",
          "Ce matin, elle a lavé le citron avant de cuisiner.",
          "Nous avons ajouté le citron dans la recette.",
          "Ils vont servir le citron avec le plat principal.",
          "J'ai choisi un citron parce qu'il était frais.",
          "Elle a coupé le citron en petits morceaux.",
          "Avant le dîner, nous avons goûté le citron.",
          "Le vendeur a conseillé le citron à ma mère.",
          "Je vais acheter un citron après le travail.",
          "Nous avons gardé le citron au réfrigérateur.",
          "Hier soir, mon frère a mangé le citron.",
          "Pendant les vacances, nous préparions souvent le citron.",
          "Elle a oublié un citron dans le sac.",
          "Il va utiliser le citron pour faire une sauce.",
          "Nous avons commandé le citron au restaurant.",
          "Ce week-end, je vais cuisiner le citron.",
          "Le cuisinier a ajouté le citron dans l'assiette.",
          "J'ai goûté le citron pour la première fois.",
          "Ma sœur a choisi le citron pour le dessert.",
          "Ils ont partagé un citron à midi.",
          "Nous allons servir le citron avec du pain.",
          "Elle a acheté un citron pour la recette.",
          "Le client a demandé le citron au serveur.",
          "Après la leçon, j'ai utilisé le mot citron dans une phrase.",
          "Demain, je vais apprendre à mieux employer le citron.",
          "Quand je lis le texte, je cherche le sens de citron.",
          "Ce matin, nous avons associé le citron à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec citron.",
          "Le professeur a demandé un exemple avec le citron.",
          "J'ai choisi le citron parce que ce mot était dans la liste.",
          "Nous allons réviser le citron avant l'évaluation.",
          "Mon camarade a expliqué le citron avec ses mots.",
          "J'ai ajouté citron dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le citron soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le citron était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le citron, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le citron dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le citron.",
          "La recette que nous préparons utilise le citron pour équilibrer les saveurs.",
          "Pendant que le chef coupait le citron, les autres préparaient la table.",
          "Puisque le citron était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le citron, tu pourras commencer la recette.",
          "Je pense que le citron convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le citron peut améliorer la présentation.",
          "Le produit dont je parle est le citron, que beaucoup de clients apprécient.",
          "Tant que le citron restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le citron est très demandé en cuisine.",
          "Si le restaurant propose le citron, je choisirai ce plat sans hésiter.",
          "Bien que le mot citron paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le citron apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le citron, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà citron, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le citron.",
          "Lorsque j'aurai mémorisé citron, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le citron.",
          "Puisque citron est utile, je le révise régulièrement.",
        ],
      } },
    { word: "melon",      image: "melon.webp",      article: "le",  gender: "m", definition: "gros fruit rond à chair orange et sucrée" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté un melon au marché.",
          "Demain, je vais préparer le melon pour le repas.",
          "Quand j'étais petit, je mangeais souvent le melon.",
          "Ce matin, elle a lavé le melon avant de cuisiner.",
          "Nous avons ajouté le melon dans la recette.",
          "Ils vont servir le melon avec le plat principal.",
          "J'ai choisi un melon parce qu'il était frais.",
          "Elle a coupé le melon en petits morceaux.",
          "Avant le dîner, nous avons goûté le melon.",
          "Le vendeur a conseillé le melon à ma mère.",
          "Je vais acheter un melon après le travail.",
          "Nous avons gardé le melon au réfrigérateur.",
          "Hier soir, mon frère a mangé le melon.",
          "Pendant les vacances, nous préparions souvent le melon.",
          "Elle a oublié un melon dans le sac.",
          "Il va utiliser le melon pour faire une sauce.",
          "Nous avons commandé le melon au restaurant.",
          "Ce week-end, je vais cuisiner le melon.",
          "Le cuisinier a ajouté le melon dans l'assiette.",
          "J'ai goûté le melon pour la première fois.",
          "Ma sœur a choisi le melon pour le dessert.",
          "Ils ont partagé un melon à midi.",
          "Nous allons servir le melon avec du pain.",
          "Elle a acheté un melon pour la recette.",
          "Le client a demandé le melon au serveur.",
          "Après la leçon, j'ai utilisé le mot melon dans une phrase.",
          "Demain, je vais apprendre à mieux employer le melon.",
          "Quand je lis le texte, je cherche le sens de melon.",
          "Ce matin, nous avons associé le melon à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec melon.",
          "Le professeur a demandé un exemple avec le melon.",
          "J'ai choisi le melon parce que ce mot était dans la liste.",
          "Nous allons réviser le melon avant l'évaluation.",
          "Mon camarade a expliqué le melon avec ses mots.",
          "J'ai ajouté melon dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le melon soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme le melon était très frais, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes le melon, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie le melon dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi le melon.",
          "La recette que nous préparons utilise le melon pour équilibrer les saveurs.",
          "Pendant que le chef coupait le melon, les autres préparaient la table.",
          "Puisque le melon était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé le melon, tu pourras commencer la recette.",
          "Je pense que le melon convient bien à ce menu parce qu'il reste facile à préparer.",
          "Même quand le repas est simple, le melon peut améliorer la présentation.",
          "Le produit dont je parle est le melon, que beaucoup de clients apprécient.",
          "Tant que le melon restera frais, nous pourrons l'utiliser demain.",
          "Bien qu'il coûte parfois cher, le melon est très demandé en cuisine.",
          "Si le restaurant propose le melon, je choisirai ce plat sans hésiter.",
          "Bien que le mot melon paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le melon apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le melon, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà melon, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le melon.",
          "Lorsque j'aurai mémorisé melon, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le melon.",
          "Puisque melon est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pastèque",   image: "pasteque.webp",   article: "la",  gender: "f", definition: "grand fruit vert à chair rouge et rafraîchissante" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une pastèque au marché.",
          "Demain, je vais préparer la pastèque pour le repas.",
          "Quand j'étais petit, je mangeais souvent la pastèque.",
          "Ce matin, elle a lavé la pastèque avant de cuisiner.",
          "Nous avons ajouté la pastèque dans la recette.",
          "Ils vont servir la pastèque avec le plat principal.",
          "J'ai choisi une pastèque parce qu'elle était fraîche.",
          "Elle a coupé la pastèque en petits morceaux.",
          "Avant le dîner, nous avons goûté la pastèque.",
          "Le vendeur a conseillé la pastèque à ma mère.",
          "Je vais acheter une pastèque après le travail.",
          "Nous avons gardé la pastèque au réfrigérateur.",
          "Hier soir, mon frère a mangé la pastèque.",
          "Pendant les vacances, nous préparions souvent la pastèque.",
          "Elle a oublié une pastèque dans le sac.",
          "Il va utiliser la pastèque pour faire une sauce.",
          "Nous avons commandé la pastèque au restaurant.",
          "Ce week-end, je vais cuisiner la pastèque.",
          "Le cuisinier a ajouté la pastèque dans l'assiette.",
          "J'ai goûté la pastèque pour la première fois.",
          "Ma sœur a choisi la pastèque pour le dessert.",
          "Ils ont partagé une pastèque à midi.",
          "Nous allons servir la pastèque avec du pain.",
          "Elle a acheté une pastèque pour la recette.",
          "Le client a demandé la pastèque au serveur.",
          "Après la leçon, j'ai utilisé le mot pastèque dans une phrase.",
          "Demain, je vais apprendre à mieux employer la pastèque.",
          "Quand je lis le texte, je cherche le sens de pastèque.",
          "Ce matin, nous avons associé la pastèque à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pastèque.",
          "Le professeur a demandé un exemple avec la pastèque.",
          "J'ai choisi la pastèque parce que ce mot était dans la liste.",
          "Nous allons réviser la pastèque avant l'évaluation.",
          "Mon camarade a expliqué la pastèque avec ses mots.",
          "J'ai ajouté pastèque dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la pastèque soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la pastèque était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la pastèque, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la pastèque dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la pastèque.",
          "La recette que nous préparons utilise la pastèque pour équilibrer les saveurs.",
          "Pendant que le chef coupait la pastèque, les autres préparaient la table.",
          "Puisque la pastèque était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la pastèque, tu pourras commencer la recette.",
          "Je pense que la pastèque convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la pastèque peut améliorer la présentation.",
          "Le produit dont je parle est la pastèque, que beaucoup de clients apprécient.",
          "Tant que la pastèque restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la pastèque est très demandée en cuisine.",
          "Si le restaurant propose la pastèque, je choisirai ce plat sans hésiter.",
          "Bien que le mot pastèque paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la pastèque apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la pastèque, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà pastèque, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la pastèque.",
          "Lorsque j'aurai mémorisé pastèque, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la pastèque.",
          "Puisque pastèque est utile, je le révise régulièrement.",
        ],
      } },
    { word: "mangue",     image: "mangue.webp",     article: "la",  gender: "f", definition: "fruit tropical jaune-orange très sucré" , exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai acheté une mangue au marché.",
          "Demain, je vais préparer la mangue pour le repas.",
          "Quand j'étais petit, je mangeais souvent la mangue.",
          "Ce matin, elle a lavé la mangue avant de cuisiner.",
          "Nous avons ajouté la mangue dans la recette.",
          "Ils vont servir la mangue avec le plat principal.",
          "J'ai choisi une mangue parce qu'elle était fraîche.",
          "Elle a coupé la mangue en petits morceaux.",
          "Avant le dîner, nous avons goûté la mangue.",
          "Le vendeur a conseillé la mangue à ma mère.",
          "Je vais acheter une mangue après le travail.",
          "Nous avons gardé la mangue au réfrigérateur.",
          "Hier soir, mon frère a mangé la mangue.",
          "Pendant les vacances, nous préparions souvent la mangue.",
          "Elle a oublié une mangue dans le sac.",
          "Il va utiliser la mangue pour faire une sauce.",
          "Nous avons commandé la mangue au restaurant.",
          "Ce week-end, je vais cuisiner la mangue.",
          "Le cuisinier a ajouté la mangue dans l'assiette.",
          "J'ai goûté la mangue pour la première fois.",
          "Ma sœur a choisi la mangue pour le dessert.",
          "Ils ont partagé une mangue à midi.",
          "Nous allons servir la mangue avec du pain.",
          "Elle a acheté une mangue pour la recette.",
          "Le client a demandé la mangue au serveur.",
          "Après la leçon, j'ai utilisé le mot mangue dans une phrase.",
          "Demain, je vais apprendre à mieux employer la mangue.",
          "Quand je lis le texte, je cherche le sens de mangue.",
          "Ce matin, nous avons associé la mangue à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec mangue.",
          "Le professeur a demandé un exemple avec la mangue.",
          "J'ai choisi la mangue parce que ce mot était dans la liste.",
          "Nous allons réviser la mangue avant l'évaluation.",
          "Mon camarade a expliqué la mangue avec ses mots.",
          "J'ai ajouté mangue dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la mangue soit simple, ce produit donne beaucoup de goût au plat.",
          "Comme la mangue était très fraîche, le cuisinier l'a servi immédiatement.",
          "Si tu ajoutes la mangue, la recette aura une saveur plus intéressante.",
          "Même si je n'en mange pas souvent, j'apprécie la mangue dans ce plat.",
          "Le client, qui voulait un repas léger, a choisi la mangue.",
          "La recette que nous préparons utilise la mangue pour équilibrer les saveurs.",
          "Pendant que le chef coupait la mangue, les autres préparaient la table.",
          "Puisque la mangue était déjà prêt, le service a commencé rapidement.",
          "Lorsque tu auras lavé la mangue, tu pourras commencer la recette.",
          "Je pense que la mangue convient bien à ce menu parce qu'elle reste facile à préparer.",
          "Même quand le repas est simple, la mangue peut améliorer la présentation.",
          "Le produit dont je parle est la mangue, que beaucoup de clients apprécient.",
          "Tant que la mangue restera fraîche, nous pourrons l'utiliser demain.",
          "Bien qu'elle coûte parfois chère, la mangue est très demandée en cuisine.",
          "Si le restaurant propose la mangue, je choisirai ce plat sans hésiter.",
          "Bien que le mot mangue paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la mangue apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la mangue, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà mangue, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la mangue.",
          "Lorsque j'aurai mémorisé mangue, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la mangue.",
          "Puisque mangue est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Je mange une ___ par jour pour rester en bonne santé.", answer: "pomme" },
    { sentence: "La ___ est un fruit tropical que j'adore en smoothie.", answer: "mangue" },
    { sentence: "En été, nous mangeons de la ___ pour nous rafraîchir.", answer: "pastèque" },
    { sentence: "Les enfants adorent la ___ rouge avec de la crème.",    answer: "fraise" },
    { sentence: "Elle cueille des ___ dans le jardin en juin.",          answer: "cerise" },
    { sentence: "Il mange des ___ en grappe au dessert.",                answer: "raisin" },
    { sentence: "La ___ est plus petite que la fraise mais tout aussi sucrée.", answer: "framboise" },
  ],
};
