import type { VocabTheme } from "../../vocabulary-data";

export const V8_MEDECINS_THEME: VocabTheme = {
  slug: "v8-medecins",
  code: "V8.3",
  title: "Les médecins",
  section: "V8",
  words: [
    { word: "médecin",          image: "medecin.webp",            article: "le",  gender: "m", definition: "Le médecin est professionnel de santé généraliste. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le médecin.",
          "Je parle du médecin.",
          "Le médecin est important.",
          "Le médecin explique le médecin.",
          "Le patient parle du médecin.",
          "Tu comprends médecin.",
          "Il décrit le médecin.",
          "Elle soigne ce problème.",
          "Nous étudions le médecin.",
          "Vous notez médecin.",
          "Ils décrivent le médecin.",
          "Elles répètent médecin.",
          "Le médecin est dans la leçon.",
          "Je lis le mot médecin.",
          "Je cherche le médecin.",
          "Il montre le médecin.",
          "Elle demande une explication sur le médecin.",
          "La pharmacie aide le patient.",
          "Le soignant parle du médecin.",
          "La classe apprend médecin.",
          "Je répète médecin.",
          "Nous écrivons médecin.",
          "Tu apprends médecin.",
          "Le soin concerne le médecin.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le médecin.",
          "Dans mon cahier, j'écris médecin.",
          "Le mot médecin est nouveau pour moi.",
          "Je répète médecin à voix haute.",
          "Tu connais le médecin.",
          "Nous dessinons le médecin.",
          "La classe regarde le médecin.",
          "Je montre le médecin au professeur.",
          "Il y a un médecin dans l'image.",
          "Cette leçon parle du médecin.",
        ],
        a2: [
          "Hier, le médecin a parlé du médecin au patient.",
          "Demain, je vais revoir le mot médecin.",
          "Quand j'étais malade, j'ai entendu parler du médecin.",
          "Ce matin, le pharmacien a expliqué le médecin.",
          "Nous avons utilisé médecin dans une phrase.",
          "Ils vont apprendre médecin cette semaine.",
          "J'ai choisi le médecin parce que ce mot était utile.",
          "Elle a noté médecin dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec médecin.",
          "Le groupe a parlé du médecin pendant le cours.",
          "Je vais demander des informations sur le médecin.",
          "Nous avons associé le médecin à une image.",
          "Hier soir, mon frère a cherché le sens de médecin.",
          "Pendant l'exercice, je confondais encore médecin.",
          "Elle a oublié le mot médecin pendant la dictée.",
          "Il va utiliser médecin dans sa réponse.",
          "Nous avons trouvé le médecin dans le dialogue médical.",
          "Ce week-end, je vais mémoriser médecin.",
          "L'élève a ajouté médecin dans sa phrase.",
          "J'ai compris médecin pour la première fois.",
          "Ma sœur a demandé un exemple avec médecin.",
          "Ils ont répété médecin à voix haute.",
          "Nous allons revoir le médecin avec le professeur.",
          "Elle a écrit médecin sans aide.",
          "La classe a demandé une définition de médecin.",
          "Après la leçon, j'ai utilisé le mot médecin dans une phrase.",
          "Demain, je vais apprendre à mieux employer le médecin.",
          "Quand je lis le texte, je cherche le sens de médecin.",
          "Ce matin, nous avons associé le médecin à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec médecin.",
          "Le professeur a demandé un exemple avec le médecin.",
          "J'ai choisi le médecin parce que ce mot était dans la liste.",
          "Nous allons réviser le médecin avant l'évaluation.",
          "Mon camarade a expliqué le médecin avec ses mots.",
          "J'ai ajouté médecin dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le médecin semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le médecin apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais médecin, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà médecin, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le médecin avec des mots simples.",
          "La leçon que nous travaillons utilise médecin dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du médecin, le client posait des questions.",
          "Puisque médecin est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé médecin, tu comprendras mieux les consignes du médecin.",
          "Je pense que le médecin aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, médecin peut donner une information importante.",
          "Le mot dont je parle est médecin, que la classe doit retenir.",
          "Tant que tu pratiqueras médecin, tu parleras de santé plus facilement.",
          "Bien que le médecin demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient médecin, je penserai au vocabulaire médical.",
          "Bien que le mot médecin paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le médecin apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le médecin, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le médecin.",
          "Lorsque j'aurai mémorisé médecin, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le médecin.",
          "Puisque médecin est utile, je le révise régulièrement.",
        ],
      } },
    { word: "infirmier",        image: "infirmier.webp",          article: "un",  gender: "m", feminine: "infirmière", definition: "Un infirmier est professionnel de santé qui soigne les patients. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'infirmier.",
          "Je parle de l'infirmier.",
          "L'infirmier est important.",
          "Le médecin explique l'infirmier.",
          "Le patient parle de l'infirmier.",
          "Tu comprends infirmier.",
          "Il décrit l'infirmier.",
          "Elle soigne ce problème.",
          "Nous étudions l'infirmier.",
          "Vous notez infirmier.",
          "Ils décrivent l'infirmier.",
          "Elles répètent infirmier.",
          "L'infirmier est dans la leçon.",
          "Je lis le mot infirmier.",
          "Je cherche l'infirmier.",
          "Il montre l'infirmier.",
          "Elle demande une explication sur l'infirmier.",
          "La pharmacie aide le patient.",
          "Le soignant parle de l'infirmier.",
          "La classe apprend infirmier.",
          "Je répète infirmier.",
          "Nous écrivons infirmier.",
          "Tu apprends infirmier.",
          "Le soin concerne l'infirmier.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois l'infirmier.",
          "Dans mon cahier, j'écris infirmier.",
          "Le mot infirmier est nouveau pour moi.",
          "Je répète infirmier à voix haute.",
          "Tu connais l'infirmier.",
          "Nous dessinons l'infirmier.",
          "La classe regarde l'infirmier.",
          "Je montre l'infirmier au professeur.",
          "Il y a un infirmier dans l'image.",
          "Cette leçon parle de l'infirmier.",
        ],
        a2: [
          "Hier, le médecin a parlé de l'infirmier au patient.",
          "Demain, je vais revoir le mot infirmier.",
          "Quand j'étais malade, j'ai entendu parler de l'infirmier.",
          "Ce matin, le pharmacien a expliqué l'infirmier.",
          "Nous avons utilisé infirmier dans une phrase.",
          "Ils vont apprendre infirmier cette semaine.",
          "J'ai choisi l'infirmier parce que ce mot était utile.",
          "Elle a noté infirmier dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec infirmier.",
          "Le groupe a parlé de l'infirmier pendant le cours.",
          "Je vais demander des informations sur l'infirmier.",
          "Nous avons associé l'infirmier à une image.",
          "Hier soir, mon frère a cherché le sens de infirmier.",
          "Pendant l'exercice, je confondais encore infirmier.",
          "Elle a oublié le mot infirmier pendant la dictée.",
          "Il va utiliser infirmier dans sa réponse.",
          "Nous avons trouvé l'infirmier dans le dialogue médical.",
          "Ce week-end, je vais mémoriser infirmier.",
          "L'élève a ajouté infirmier dans sa phrase.",
          "J'ai compris infirmier pour la première fois.",
          "Ma sœur a demandé un exemple avec infirmier.",
          "Ils ont répété infirmier à voix haute.",
          "Nous allons revoir l'infirmier avec le professeur.",
          "Elle a écrit infirmier sans aide.",
          "La classe a demandé une définition de infirmier.",
          "Après la leçon, j'ai utilisé le mot infirmier dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'infirmier.",
          "Quand je lis le texte, je cherche le sens de infirmier.",
          "Ce matin, nous avons associé l'infirmier à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec infirmier.",
          "Le professeur a demandé un exemple avec l'infirmier.",
          "J'ai choisi l'infirmier parce que ce mot était dans la liste.",
          "Nous allons réviser l'infirmier avant l'évaluation.",
          "Mon camarade a expliqué l'infirmier avec ses mots.",
          "J'ai ajouté infirmier dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'infirmier semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'infirmier apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais infirmier, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà infirmier, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'infirmier avec des mots simples.",
          "La leçon que nous travaillons utilise infirmier dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'infirmier, le client posait des questions.",
          "Puisque infirmier est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé infirmier, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'infirmier aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, infirmier peut donner une information importante.",
          "Le mot dont je parle est infirmier, que la classe doit retenir.",
          "Tant que tu pratiqueras infirmier, tu parleras de santé plus facilement.",
          "Bien que l'infirmier demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient infirmier, je penserai au vocabulaire médical.",
          "Bien que le mot infirmier paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'infirmier apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'infirmier, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'infirmier.",
          "Lorsque j'aurai mémorisé infirmier, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'infirmier.",
          "Puisque infirmier est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pharmacien",       image: "pharmacien.webp",         article: "un",  gender: "m", feminine: "pharmacienne", definition: "Un pharmacien est professionnel qui délivre les médicaments. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le pharmacien.",
          "Je parle du pharmacien.",
          "Le pharmacien est important.",
          "Le médecin explique le pharmacien.",
          "Le patient parle du pharmacien.",
          "Tu comprends pharmacien.",
          "Il décrit le pharmacien.",
          "Elle soigne ce problème.",
          "Nous étudions le pharmacien.",
          "Vous notez pharmacien.",
          "Ils décrivent le pharmacien.",
          "Elles répètent pharmacien.",
          "Le pharmacien est dans la leçon.",
          "Je lis le mot pharmacien.",
          "Je cherche le pharmacien.",
          "Il montre le pharmacien.",
          "Elle demande une explication sur le pharmacien.",
          "La pharmacie aide le patient.",
          "Le soignant parle du pharmacien.",
          "La classe apprend pharmacien.",
          "Je répète pharmacien.",
          "Nous écrivons pharmacien.",
          "Tu apprends pharmacien.",
          "Le soin concerne le pharmacien.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le pharmacien.",
          "Dans mon cahier, j'écris pharmacien.",
          "Le mot pharmacien est nouveau pour moi.",
          "Je répète pharmacien à voix haute.",
          "Tu connais le pharmacien.",
          "Nous dessinons le pharmacien.",
          "La classe regarde le pharmacien.",
          "Je montre le pharmacien au professeur.",
          "Il y a un pharmacien dans l'image.",
          "Cette leçon parle du pharmacien.",
        ],
        a2: [
          "Hier, le médecin a parlé du pharmacien au patient.",
          "Demain, je vais revoir le mot pharmacien.",
          "Quand j'étais malade, j'ai entendu parler du pharmacien.",
          "Ce matin, le pharmacien a expliqué le pharmacien.",
          "Nous avons utilisé pharmacien dans une phrase.",
          "Ils vont apprendre pharmacien cette semaine.",
          "J'ai choisi le pharmacien parce que ce mot était utile.",
          "Elle a noté pharmacien dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec pharmacien.",
          "Le groupe a parlé du pharmacien pendant le cours.",
          "Je vais demander des informations sur le pharmacien.",
          "Nous avons associé le pharmacien à une image.",
          "Hier soir, mon frère a cherché le sens de pharmacien.",
          "Pendant l'exercice, je confondais encore pharmacien.",
          "Elle a oublié le mot pharmacien pendant la dictée.",
          "Il va utiliser pharmacien dans sa réponse.",
          "Nous avons trouvé le pharmacien dans le dialogue médical.",
          "Ce week-end, je vais mémoriser pharmacien.",
          "L'élève a ajouté pharmacien dans sa phrase.",
          "J'ai compris pharmacien pour la première fois.",
          "Ma sœur a demandé un exemple avec pharmacien.",
          "Ils ont répété pharmacien à voix haute.",
          "Nous allons revoir le pharmacien avec le professeur.",
          "Elle a écrit pharmacien sans aide.",
          "La classe a demandé une définition de pharmacien.",
          "Après la leçon, j'ai utilisé le mot pharmacien dans une phrase.",
          "Demain, je vais apprendre à mieux employer le pharmacien.",
          "Quand je lis le texte, je cherche le sens de pharmacien.",
          "Ce matin, nous avons associé le pharmacien à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pharmacien.",
          "Le professeur a demandé un exemple avec le pharmacien.",
          "J'ai choisi le pharmacien parce que ce mot était dans la liste.",
          "Nous allons réviser le pharmacien avant l'évaluation.",
          "Mon camarade a expliqué le pharmacien avec ses mots.",
          "J'ai ajouté pharmacien dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le pharmacien semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le pharmacien apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais pharmacien, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà pharmacien, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le pharmacien avec des mots simples.",
          "La leçon que nous travaillons utilise pharmacien dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du pharmacien, le client posait des questions.",
          "Puisque pharmacien est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé pharmacien, tu comprendras mieux les consignes du médecin.",
          "Je pense que le pharmacien aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, pharmacien peut donner une information importante.",
          "Le mot dont je parle est pharmacien, que la classe doit retenir.",
          "Tant que tu pratiqueras pharmacien, tu parleras de santé plus facilement.",
          "Bien que le pharmacien demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient pharmacien, je penserai au vocabulaire médical.",
          "Bien que le mot pharmacien paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le pharmacien apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le pharmacien, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le pharmacien.",
          "Lorsque j'aurai mémorisé pharmacien, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le pharmacien.",
          "Puisque pharmacien est utile, je le révise régulièrement.",
        ],
      } },
    { word: "dentiste",         image: "dentiste.webp",           article: "le",  gender: "m", definition: "Le dentiste est médecin spécialiste des dents. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le dentiste.",
          "Je parle du dentiste.",
          "Le dentiste est important.",
          "Le médecin explique le dentiste.",
          "Le patient parle du dentiste.",
          "Tu comprends dentiste.",
          "Il décrit le dentiste.",
          "Elle soigne ce problème.",
          "Nous étudions le dentiste.",
          "Vous notez dentiste.",
          "Ils décrivent le dentiste.",
          "Elles répètent dentiste.",
          "Le dentiste est dans la leçon.",
          "Je lis le mot dentiste.",
          "Je cherche le dentiste.",
          "Il montre le dentiste.",
          "Elle demande une explication sur le dentiste.",
          "La pharmacie aide le patient.",
          "Le soignant parle du dentiste.",
          "La classe apprend dentiste.",
          "Je répète dentiste.",
          "Nous écrivons dentiste.",
          "Tu apprends dentiste.",
          "Le soin concerne le dentiste.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le dentiste.",
          "Dans mon cahier, j'écris dentiste.",
          "Le mot dentiste est nouveau pour moi.",
          "Je répète dentiste à voix haute.",
          "Tu connais le dentiste.",
          "Nous dessinons le dentiste.",
          "La classe regarde le dentiste.",
          "Je montre le dentiste au professeur.",
          "Il y a un dentiste dans l'image.",
          "Cette leçon parle du dentiste.",
        ],
        a2: [
          "Hier, le médecin a parlé du dentiste au patient.",
          "Demain, je vais revoir le mot dentiste.",
          "Quand j'étais malade, j'ai entendu parler du dentiste.",
          "Ce matin, le pharmacien a expliqué le dentiste.",
          "Nous avons utilisé dentiste dans une phrase.",
          "Ils vont apprendre dentiste cette semaine.",
          "J'ai choisi le dentiste parce que ce mot était utile.",
          "Elle a noté dentiste dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec dentiste.",
          "Le groupe a parlé du dentiste pendant le cours.",
          "Je vais demander des informations sur le dentiste.",
          "Nous avons associé le dentiste à une image.",
          "Hier soir, mon frère a cherché le sens de dentiste.",
          "Pendant l'exercice, je confondais encore dentiste.",
          "Elle a oublié le mot dentiste pendant la dictée.",
          "Il va utiliser dentiste dans sa réponse.",
          "Nous avons trouvé le dentiste dans le dialogue médical.",
          "Ce week-end, je vais mémoriser dentiste.",
          "L'élève a ajouté dentiste dans sa phrase.",
          "J'ai compris dentiste pour la première fois.",
          "Ma sœur a demandé un exemple avec dentiste.",
          "Ils ont répété dentiste à voix haute.",
          "Nous allons revoir le dentiste avec le professeur.",
          "Elle a écrit dentiste sans aide.",
          "La classe a demandé une définition de dentiste.",
          "Après la leçon, j'ai utilisé le mot dentiste dans une phrase.",
          "Demain, je vais apprendre à mieux employer le dentiste.",
          "Quand je lis le texte, je cherche le sens de dentiste.",
          "Ce matin, nous avons associé le dentiste à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec dentiste.",
          "Le professeur a demandé un exemple avec le dentiste.",
          "J'ai choisi le dentiste parce que ce mot était dans la liste.",
          "Nous allons réviser le dentiste avant l'évaluation.",
          "Mon camarade a expliqué le dentiste avec ses mots.",
          "J'ai ajouté dentiste dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le dentiste semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le dentiste apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais dentiste, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà dentiste, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le dentiste avec des mots simples.",
          "La leçon que nous travaillons utilise dentiste dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du dentiste, le client posait des questions.",
          "Puisque dentiste est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé dentiste, tu comprendras mieux les consignes du médecin.",
          "Je pense que le dentiste aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, dentiste peut donner une information importante.",
          "Le mot dont je parle est dentiste, que la classe doit retenir.",
          "Tant que tu pratiqueras dentiste, tu parleras de santé plus facilement.",
          "Bien que le dentiste demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient dentiste, je penserai au vocabulaire médical.",
          "Bien que le mot dentiste paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le dentiste apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le dentiste, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le dentiste.",
          "Lorsque j'aurai mémorisé dentiste, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le dentiste.",
          "Puisque dentiste est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ophtalmologue",    image: "ophtalmologue.webp",      article: "l'",  gender: "m", definition: "L'ophtalmologue est médecin spécialiste des yeux. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'ophtalmologue.",
          "Je parle de l'ophtalmologue.",
          "L'ophtalmologue est important.",
          "Le médecin explique l'ophtalmologue.",
          "Le patient parle de l'ophtalmologue.",
          "Tu comprends ophtalmologue.",
          "Il décrit l'ophtalmologue.",
          "Elle soigne ce problème.",
          "Nous étudions l'ophtalmologue.",
          "Vous notez ophtalmologue.",
          "Ils décrivent l'ophtalmologue.",
          "Elles répètent ophtalmologue.",
          "L'ophtalmologue est dans la leçon.",
          "Je lis le mot ophtalmologue.",
          "Je cherche l'ophtalmologue.",
          "Il montre l'ophtalmologue.",
          "Elle demande une explication sur l'ophtalmologue.",
          "La pharmacie aide le patient.",
          "Le soignant parle de l'ophtalmologue.",
          "La classe apprend ophtalmologue.",
          "Je répète ophtalmologue.",
          "Nous écrivons ophtalmologue.",
          "Tu apprends ophtalmologue.",
          "Le soin concerne l'ophtalmologue.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois l'ophtalmologue.",
          "Dans mon cahier, j'écris ophtalmologue.",
          "Le mot ophtalmologue est nouveau pour moi.",
          "Je répète ophtalmologue à voix haute.",
          "Tu connais l'ophtalmologue.",
          "Nous dessinons l'ophtalmologue.",
          "La classe regarde l'ophtalmologue.",
          "Je montre l'ophtalmologue au professeur.",
          "Il y a un ophtalmologue dans l'image.",
          "Cette leçon parle de l'ophtalmologue.",
        ],
        a2: [
          "Hier, le médecin a parlé de l'ophtalmologue au patient.",
          "Demain, je vais revoir le mot ophtalmologue.",
          "Quand j'étais malade, j'ai entendu parler de l'ophtalmologue.",
          "Ce matin, le pharmacien a expliqué l'ophtalmologue.",
          "Nous avons utilisé ophtalmologue dans une phrase.",
          "Ils vont apprendre ophtalmologue cette semaine.",
          "J'ai choisi l'ophtalmologue parce que ce mot était utile.",
          "Elle a noté ophtalmologue dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec ophtalmologue.",
          "Le groupe a parlé de l'ophtalmologue pendant le cours.",
          "Je vais demander des informations sur l'ophtalmologue.",
          "Nous avons associé l'ophtalmologue à une image.",
          "Hier soir, mon frère a cherché le sens de ophtalmologue.",
          "Pendant l'exercice, je confondais encore ophtalmologue.",
          "Elle a oublié le mot ophtalmologue pendant la dictée.",
          "Il va utiliser ophtalmologue dans sa réponse.",
          "Nous avons trouvé l'ophtalmologue dans le dialogue médical.",
          "Ce week-end, je vais mémoriser ophtalmologue.",
          "L'élève a ajouté ophtalmologue dans sa phrase.",
          "J'ai compris ophtalmologue pour la première fois.",
          "Ma sœur a demandé un exemple avec ophtalmologue.",
          "Ils ont répété ophtalmologue à voix haute.",
          "Nous allons revoir l'ophtalmologue avec le professeur.",
          "Elle a écrit ophtalmologue sans aide.",
          "La classe a demandé une définition de ophtalmologue.",
          "Après la leçon, j'ai utilisé le mot ophtalmologue dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ophtalmologue.",
          "Quand je lis le texte, je cherche le sens de ophtalmologue.",
          "Ce matin, nous avons associé l'ophtalmologue à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ophtalmologue.",
          "Le professeur a demandé un exemple avec l'ophtalmologue.",
          "J'ai choisi l'ophtalmologue parce que ce mot était dans la liste.",
          "Nous allons réviser l'ophtalmologue avant l'évaluation.",
          "Mon camarade a expliqué l'ophtalmologue avec ses mots.",
          "J'ai ajouté ophtalmologue dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ophtalmologue semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'ophtalmologue apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais ophtalmologue, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà ophtalmologue, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'ophtalmologue avec des mots simples.",
          "La leçon que nous travaillons utilise ophtalmologue dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'ophtalmologue, le client posait des questions.",
          "Puisque ophtalmologue est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé ophtalmologue, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'ophtalmologue aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, ophtalmologue peut donner une information importante.",
          "Le mot dont je parle est ophtalmologue, que la classe doit retenir.",
          "Tant que tu pratiqueras ophtalmologue, tu parleras de santé plus facilement.",
          "Bien que l'ophtalmologue demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient ophtalmologue, je penserai au vocabulaire médical.",
          "Bien que le mot ophtalmologue paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ophtalmologue apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ophtalmologue, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ophtalmologue.",
          "Lorsque j'aurai mémorisé ophtalmologue, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ophtalmologue.",
          "Puisque ophtalmologue est utile, je le révise régulièrement.",
        ],
      } },
    { word: "pédiatre",         image: "pediatre.webp",           article: "le",  gender: "m", definition: "Le pédiatre est médecin spécialiste des enfants. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le pédiatre.",
          "Je parle du pédiatre.",
          "Le pédiatre est important.",
          "Le médecin explique le pédiatre.",
          "Le patient parle du pédiatre.",
          "Tu comprends pédiatre.",
          "Il décrit le pédiatre.",
          "Elle soigne ce problème.",
          "Nous étudions le pédiatre.",
          "Vous notez pédiatre.",
          "Ils décrivent le pédiatre.",
          "Elles répètent pédiatre.",
          "Le pédiatre est dans la leçon.",
          "Je lis le mot pédiatre.",
          "Je cherche le pédiatre.",
          "Il montre le pédiatre.",
          "Elle demande une explication sur le pédiatre.",
          "La pharmacie aide le patient.",
          "Le soignant parle du pédiatre.",
          "La classe apprend pédiatre.",
          "Je répète pédiatre.",
          "Nous écrivons pédiatre.",
          "Tu apprends pédiatre.",
          "Le soin concerne le pédiatre.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le pédiatre.",
          "Dans mon cahier, j'écris pédiatre.",
          "Le mot pédiatre est nouveau pour moi.",
          "Je répète pédiatre à voix haute.",
          "Tu connais le pédiatre.",
          "Nous dessinons le pédiatre.",
          "La classe regarde le pédiatre.",
          "Je montre le pédiatre au professeur.",
          "Il y a un pédiatre dans l'image.",
          "Cette leçon parle du pédiatre.",
        ],
        a2: [
          "Hier, le médecin a parlé du pédiatre au patient.",
          "Demain, je vais revoir le mot pédiatre.",
          "Quand j'étais malade, j'ai entendu parler du pédiatre.",
          "Ce matin, le pharmacien a expliqué le pédiatre.",
          "Nous avons utilisé pédiatre dans une phrase.",
          "Ils vont apprendre pédiatre cette semaine.",
          "J'ai choisi le pédiatre parce que ce mot était utile.",
          "Elle a noté pédiatre dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec pédiatre.",
          "Le groupe a parlé du pédiatre pendant le cours.",
          "Je vais demander des informations sur le pédiatre.",
          "Nous avons associé le pédiatre à une image.",
          "Hier soir, mon frère a cherché le sens de pédiatre.",
          "Pendant l'exercice, je confondais encore pédiatre.",
          "Elle a oublié le mot pédiatre pendant la dictée.",
          "Il va utiliser pédiatre dans sa réponse.",
          "Nous avons trouvé le pédiatre dans le dialogue médical.",
          "Ce week-end, je vais mémoriser pédiatre.",
          "L'élève a ajouté pédiatre dans sa phrase.",
          "J'ai compris pédiatre pour la première fois.",
          "Ma sœur a demandé un exemple avec pédiatre.",
          "Ils ont répété pédiatre à voix haute.",
          "Nous allons revoir le pédiatre avec le professeur.",
          "Elle a écrit pédiatre sans aide.",
          "La classe a demandé une définition de pédiatre.",
          "Après la leçon, j'ai utilisé le mot pédiatre dans une phrase.",
          "Demain, je vais apprendre à mieux employer le pédiatre.",
          "Quand je lis le texte, je cherche le sens de pédiatre.",
          "Ce matin, nous avons associé le pédiatre à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec pédiatre.",
          "Le professeur a demandé un exemple avec le pédiatre.",
          "J'ai choisi le pédiatre parce que ce mot était dans la liste.",
          "Nous allons réviser le pédiatre avant l'évaluation.",
          "Mon camarade a expliqué le pédiatre avec ses mots.",
          "J'ai ajouté pédiatre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le pédiatre semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le pédiatre apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais pédiatre, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà pédiatre, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le pédiatre avec des mots simples.",
          "La leçon que nous travaillons utilise pédiatre dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du pédiatre, le client posait des questions.",
          "Puisque pédiatre est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé pédiatre, tu comprendras mieux les consignes du médecin.",
          "Je pense que le pédiatre aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, pédiatre peut donner une information importante.",
          "Le mot dont je parle est pédiatre, que la classe doit retenir.",
          "Tant que tu pratiqueras pédiatre, tu parleras de santé plus facilement.",
          "Bien que le pédiatre demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient pédiatre, je penserai au vocabulaire médical.",
          "Bien que le mot pédiatre paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le pédiatre apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le pédiatre, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le pédiatre.",
          "Lorsque j'aurai mémorisé pédiatre, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le pédiatre.",
          "Puisque pédiatre est utile, je le révise régulièrement.",
        ],
      } },
    { word: "chirurgien",       image: "chirurgien.webp",         article: "le",  gender: "m", definition: "Le chirurgien est médecin qui pratique des opérations. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le chirurgien.",
          "Je parle du chirurgien.",
          "Le chirurgien est important.",
          "Le médecin explique le chirurgien.",
          "Le patient parle du chirurgien.",
          "Tu comprends chirurgien.",
          "Il décrit le chirurgien.",
          "Elle soigne ce problème.",
          "Nous étudions le chirurgien.",
          "Vous notez chirurgien.",
          "Ils décrivent le chirurgien.",
          "Elles répètent chirurgien.",
          "Le chirurgien est dans la leçon.",
          "Je lis le mot chirurgien.",
          "Je cherche le chirurgien.",
          "Il montre le chirurgien.",
          "Elle demande une explication sur le chirurgien.",
          "La pharmacie aide le patient.",
          "Le soignant parle du chirurgien.",
          "La classe apprend chirurgien.",
          "Je répète chirurgien.",
          "Nous écrivons chirurgien.",
          "Tu apprends chirurgien.",
          "Le soin concerne le chirurgien.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le chirurgien.",
          "Dans mon cahier, j'écris chirurgien.",
          "Le mot chirurgien est nouveau pour moi.",
          "Je répète chirurgien à voix haute.",
          "Tu connais le chirurgien.",
          "Nous dessinons le chirurgien.",
          "La classe regarde le chirurgien.",
          "Je montre le chirurgien au professeur.",
          "Il y a un chirurgien dans l'image.",
          "Cette leçon parle du chirurgien.",
        ],
        a2: [
          "Hier, le médecin a parlé du chirurgien au patient.",
          "Demain, je vais revoir le mot chirurgien.",
          "Quand j'étais malade, j'ai entendu parler du chirurgien.",
          "Ce matin, le pharmacien a expliqué le chirurgien.",
          "Nous avons utilisé chirurgien dans une phrase.",
          "Ils vont apprendre chirurgien cette semaine.",
          "J'ai choisi le chirurgien parce que ce mot était utile.",
          "Elle a noté chirurgien dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec chirurgien.",
          "Le groupe a parlé du chirurgien pendant le cours.",
          "Je vais demander des informations sur le chirurgien.",
          "Nous avons associé le chirurgien à une image.",
          "Hier soir, mon frère a cherché le sens de chirurgien.",
          "Pendant l'exercice, je confondais encore chirurgien.",
          "Elle a oublié le mot chirurgien pendant la dictée.",
          "Il va utiliser chirurgien dans sa réponse.",
          "Nous avons trouvé le chirurgien dans le dialogue médical.",
          "Ce week-end, je vais mémoriser chirurgien.",
          "L'élève a ajouté chirurgien dans sa phrase.",
          "J'ai compris chirurgien pour la première fois.",
          "Ma sœur a demandé un exemple avec chirurgien.",
          "Ils ont répété chirurgien à voix haute.",
          "Nous allons revoir le chirurgien avec le professeur.",
          "Elle a écrit chirurgien sans aide.",
          "La classe a demandé une définition de chirurgien.",
          "Après la leçon, j'ai utilisé le mot chirurgien dans une phrase.",
          "Demain, je vais apprendre à mieux employer le chirurgien.",
          "Quand je lis le texte, je cherche le sens de chirurgien.",
          "Ce matin, nous avons associé le chirurgien à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec chirurgien.",
          "Le professeur a demandé un exemple avec le chirurgien.",
          "J'ai choisi le chirurgien parce que ce mot était dans la liste.",
          "Nous allons réviser le chirurgien avant l'évaluation.",
          "Mon camarade a expliqué le chirurgien avec ses mots.",
          "J'ai ajouté chirurgien dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le chirurgien semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le chirurgien apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais chirurgien, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà chirurgien, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le chirurgien avec des mots simples.",
          "La leçon que nous travaillons utilise chirurgien dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du chirurgien, le client posait des questions.",
          "Puisque chirurgien est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé chirurgien, tu comprendras mieux les consignes du médecin.",
          "Je pense que le chirurgien aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, chirurgien peut donner une information importante.",
          "Le mot dont je parle est chirurgien, que la classe doit retenir.",
          "Tant que tu pratiqueras chirurgien, tu parleras de santé plus facilement.",
          "Bien que le chirurgien demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient chirurgien, je penserai au vocabulaire médical.",
          "Bien que le mot chirurgien paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le chirurgien apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le chirurgien, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le chirurgien.",
          "Lorsque j'aurai mémorisé chirurgien, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le chirurgien.",
          "Puisque chirurgien est utile, je le révise régulièrement.",
        ],
      } },
    { word: "urgentiste",       image: "urgentiste.webp",         article: "l'",  gender: "m", definition: "L'urgentiste est médecin des urgences. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'urgentiste.",
          "Je parle de l'urgentiste.",
          "L'urgentiste est important.",
          "Le médecin explique l'urgentiste.",
          "Le patient parle de l'urgentiste.",
          "Tu comprends urgentiste.",
          "Il décrit l'urgentiste.",
          "Elle soigne ce problème.",
          "Nous étudions l'urgentiste.",
          "Vous notez urgentiste.",
          "Ils décrivent l'urgentiste.",
          "Elles répètent urgentiste.",
          "L'urgentiste est dans la leçon.",
          "Je lis le mot urgentiste.",
          "Je cherche l'urgentiste.",
          "Il montre l'urgentiste.",
          "Elle demande une explication sur l'urgentiste.",
          "La pharmacie aide le patient.",
          "Le soignant parle de l'urgentiste.",
          "La classe apprend urgentiste.",
          "Je répète urgentiste.",
          "Nous écrivons urgentiste.",
          "Tu apprends urgentiste.",
          "Le soin concerne l'urgentiste.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois l'urgentiste.",
          "Dans mon cahier, j'écris urgentiste.",
          "Le mot urgentiste est nouveau pour moi.",
          "Je répète urgentiste à voix haute.",
          "Tu connais l'urgentiste.",
          "Nous dessinons l'urgentiste.",
          "La classe regarde l'urgentiste.",
          "Je montre l'urgentiste au professeur.",
          "Il y a un urgentiste dans l'image.",
          "Cette leçon parle de l'urgentiste.",
        ],
        a2: [
          "Hier, le médecin a parlé de l'urgentiste au patient.",
          "Demain, je vais revoir le mot urgentiste.",
          "Quand j'étais malade, j'ai entendu parler de l'urgentiste.",
          "Ce matin, le pharmacien a expliqué l'urgentiste.",
          "Nous avons utilisé urgentiste dans une phrase.",
          "Ils vont apprendre urgentiste cette semaine.",
          "J'ai choisi l'urgentiste parce que ce mot était utile.",
          "Elle a noté urgentiste dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec urgentiste.",
          "Le groupe a parlé de l'urgentiste pendant le cours.",
          "Je vais demander des informations sur l'urgentiste.",
          "Nous avons associé l'urgentiste à une image.",
          "Hier soir, mon frère a cherché le sens de urgentiste.",
          "Pendant l'exercice, je confondais encore urgentiste.",
          "Elle a oublié le mot urgentiste pendant la dictée.",
          "Il va utiliser urgentiste dans sa réponse.",
          "Nous avons trouvé l'urgentiste dans le dialogue médical.",
          "Ce week-end, je vais mémoriser urgentiste.",
          "L'élève a ajouté urgentiste dans sa phrase.",
          "J'ai compris urgentiste pour la première fois.",
          "Ma sœur a demandé un exemple avec urgentiste.",
          "Ils ont répété urgentiste à voix haute.",
          "Nous allons revoir l'urgentiste avec le professeur.",
          "Elle a écrit urgentiste sans aide.",
          "La classe a demandé une définition de urgentiste.",
          "Après la leçon, j'ai utilisé le mot urgentiste dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'urgentiste.",
          "Quand je lis le texte, je cherche le sens de urgentiste.",
          "Ce matin, nous avons associé l'urgentiste à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec urgentiste.",
          "Le professeur a demandé un exemple avec l'urgentiste.",
          "J'ai choisi l'urgentiste parce que ce mot était dans la liste.",
          "Nous allons réviser l'urgentiste avant l'évaluation.",
          "Mon camarade a expliqué l'urgentiste avec ses mots.",
          "J'ai ajouté urgentiste dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'urgentiste semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'urgentiste apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais urgentiste, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà urgentiste, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'urgentiste avec des mots simples.",
          "La leçon que nous travaillons utilise urgentiste dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'urgentiste, le client posait des questions.",
          "Puisque urgentiste est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé urgentiste, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'urgentiste aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, urgentiste peut donner une information importante.",
          "Le mot dont je parle est urgentiste, que la classe doit retenir.",
          "Tant que tu pratiqueras urgentiste, tu parleras de santé plus facilement.",
          "Bien que l'urgentiste demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient urgentiste, je penserai au vocabulaire médical.",
          "Bien que le mot urgentiste paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'urgentiste apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'urgentiste, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'urgentiste.",
          "Lorsque j'aurai mémorisé urgentiste, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'urgentiste.",
          "Puisque urgentiste est utile, je le révise régulièrement.",
        ],
      } },
    { word: "kinésithérapeute", image: "kinésithérapeute.webp",   article: "le",  gender: "m", definition: "Le kinésithérapeute est professionnel en rééducation physique. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le kinésithérapeute.",
          "Je parle du kinésithérapeute.",
          "Le kinésithérapeute est important.",
          "Le médecin explique le kinésithérapeute.",
          "Le patient parle du kinésithérapeute.",
          "Tu comprends kinésithérapeute.",
          "Il décrit le kinésithérapeute.",
          "Elle soigne ce problème.",
          "Nous étudions le kinésithérapeute.",
          "Vous notez kinésithérapeute.",
          "Ils décrivent le kinésithérapeute.",
          "Elles répètent kinésithérapeute.",
          "Le kinésithérapeute est dans la leçon.",
          "Je lis le mot kinésithérapeute.",
          "Je cherche le kinésithérapeute.",
          "Il montre le kinésithérapeute.",
          "Elle demande une explication sur le kinésithérapeute.",
          "La pharmacie aide le patient.",
          "Le soignant parle du kinésithérapeute.",
          "La classe apprend kinésithérapeute.",
          "Je répète kinésithérapeute.",
          "Nous écrivons kinésithérapeute.",
          "Tu apprends kinésithérapeute.",
          "Le soin concerne le kinésithérapeute.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le kinésithérapeute.",
          "Dans mon cahier, j'écris kinésithérapeute.",
          "Le mot kinésithérapeute est nouveau pour moi.",
          "Je répète kinésithérapeute à voix haute.",
          "Tu connais le kinésithérapeute.",
          "Nous dessinons le kinésithérapeute.",
          "La classe regarde le kinésithérapeute.",
          "Je montre le kinésithérapeute au professeur.",
          "Il y a un kinésithérapeute dans l'image.",
          "Cette leçon parle du kinésithérapeute.",
        ],
        a2: [
          "Hier, le médecin a parlé du kinésithérapeute au patient.",
          "Demain, je vais revoir le mot kinésithérapeute.",
          "Quand j'étais malade, j'ai entendu parler du kinésithérapeute.",
          "Ce matin, le pharmacien a expliqué le kinésithérapeute.",
          "Nous avons utilisé kinésithérapeute dans une phrase.",
          "Ils vont apprendre kinésithérapeute cette semaine.",
          "J'ai choisi le kinésithérapeute parce que ce mot était utile.",
          "Elle a noté kinésithérapeute dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec kinésithérapeute.",
          "Le groupe a parlé du kinésithérapeute pendant le cours.",
          "Je vais demander des informations sur le kinésithérapeute.",
          "Nous avons associé le kinésithérapeute à une image.",
          "Hier soir, mon frère a cherché le sens de kinésithérapeute.",
          "Pendant l'exercice, je confondais encore kinésithérapeute.",
          "Elle a oublié le mot kinésithérapeute pendant la dictée.",
          "Il va utiliser kinésithérapeute dans sa réponse.",
          "Nous avons trouvé le kinésithérapeute dans le dialogue médical.",
          "Ce week-end, je vais mémoriser kinésithérapeute.",
          "L'élève a ajouté kinésithérapeute dans sa phrase.",
          "J'ai compris kinésithérapeute pour la première fois.",
          "Ma sœur a demandé un exemple avec kinésithérapeute.",
          "Ils ont répété kinésithérapeute à voix haute.",
          "Nous allons revoir le kinésithérapeute avec le professeur.",
          "Elle a écrit kinésithérapeute sans aide.",
          "La classe a demandé une définition de kinésithérapeute.",
          "Après la leçon, j'ai utilisé le mot kinésithérapeute dans une phrase.",
          "Demain, je vais apprendre à mieux employer le kinésithérapeute.",
          "Quand je lis le texte, je cherche le sens de kinésithérapeute.",
          "Ce matin, nous avons associé le kinésithérapeute à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec kinésithérapeute.",
          "Le professeur a demandé un exemple avec le kinésithérapeute.",
          "J'ai choisi le kinésithérapeute parce que ce mot était dans la liste.",
          "Nous allons réviser le kinésithérapeute avant l'évaluation.",
          "Mon camarade a expliqué le kinésithérapeute avec ses mots.",
          "J'ai ajouté kinésithérapeute dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le kinésithérapeute semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le kinésithérapeute apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais kinésithérapeute, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà kinésithérapeute, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le kinésithérapeute avec des mots simples.",
          "La leçon que nous travaillons utilise kinésithérapeute dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du kinésithérapeute, le client posait des questions.",
          "Puisque kinésithérapeute est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé kinésithérapeute, tu comprendras mieux les consignes du médecin.",
          "Je pense que le kinésithérapeute aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, kinésithérapeute peut donner une information importante.",
          "Le mot dont je parle est kinésithérapeute, que la classe doit retenir.",
          "Tant que tu pratiqueras kinésithérapeute, tu parleras de santé plus facilement.",
          "Bien que le kinésithérapeute demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient kinésithérapeute, je penserai au vocabulaire médical.",
          "Bien que le mot kinésithérapeute paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le kinésithérapeute apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le kinésithérapeute, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le kinésithérapeute.",
          "Lorsque j'aurai mémorisé kinésithérapeute, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le kinésithérapeute.",
          "Puisque kinésithérapeute est utile, je le révise régulièrement.",
        ],
      } },
    { word: "salle d'attente",  image: "salle-d-attente.webp",    article: "la",  gender: "f", definition: "La salle d'attente est endroit où l'on attend chez le médecin. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais la salle d'attente.",
          "Je parle de la salle d'attente.",
          "La salle d'attente est importante.",
          "Le médecin explique la salle d'attente.",
          "Le patient parle de la salle d'attente.",
          "Tu comprends salle d'attente.",
          "Il décrit la salle d'attente.",
          "Elle soigne ce problème.",
          "Nous étudions la salle d'attente.",
          "Vous notez salle d'attente.",
          "Ils décrivent la salle d'attente.",
          "Elles répètent salle d'attente.",
          "La salle d'attente est dans la leçon.",
          "Je lis le mot salle d'attente.",
          "Je cherche la salle d'attente.",
          "Il montre la salle d'attente.",
          "Elle demande une explication sur la salle d'attente.",
          "La pharmacie aide le patient.",
          "Le soignant parle de la salle d'attente.",
          "La classe apprend salle d'attente.",
          "Je répète salle d'attente.",
          "Nous écrivons salle d'attente.",
          "Tu apprends salle d'attente.",
          "Le soin concerne la salle d'attente.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois la salle d'attente.",
          "Dans mon cahier, j'écris salle d'attente.",
          "Le mot salle d'attente est nouveau pour moi.",
          "Je répète salle d'attente à voix haute.",
          "Tu connais la salle d'attente.",
          "Nous dessinons la salle d'attente.",
          "La classe regarde la salle d'attente.",
          "Je montre la salle d'attente au professeur.",
          "Il y a une salle d'attente dans l'image.",
          "Cette leçon parle de la salle d'attente.",
        ],
        a2: [
          "Hier, le médecin a parlé de la salle d'attente au patient.",
          "Demain, je vais revoir le mot salle d'attente.",
          "Quand j'étais malade, j'ai entendu parler de la salle d'attente.",
          "Ce matin, le pharmacien a expliqué la salle d'attente.",
          "Nous avons utilisé salle d'attente dans une phrase.",
          "Ils vont apprendre salle d'attente cette semaine.",
          "J'ai choisi la salle d'attente parce que ce mot était utile.",
          "Elle a noté salle d'attente dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec salle d'attente.",
          "Le groupe a parlé de la salle d'attente pendant le cours.",
          "Je vais demander des informations sur la salle d'attente.",
          "Nous avons associé la salle d'attente à une image.",
          "Hier soir, mon frère a cherché le sens de salle d'attente.",
          "Pendant l'exercice, je confondais encore salle d'attente.",
          "Elle a oublié le mot salle d'attente pendant la dictée.",
          "Il va utiliser salle d'attente dans sa réponse.",
          "Nous avons trouvé la salle d'attente dans le dialogue médical.",
          "Ce week-end, je vais mémoriser salle d'attente.",
          "L'élève a ajouté salle d'attente dans sa phrase.",
          "J'ai compris salle d'attente pour la première fois.",
          "Ma sœur a demandé un exemple avec salle d'attente.",
          "Ils ont répété salle d'attente à voix haute.",
          "Nous allons revoir la salle d'attente avec le professeur.",
          "Elle a écrit salle d'attente sans aide.",
          "La classe a demandé une définition de salle d'attente.",
          "Après la leçon, j'ai utilisé le mot salle d'attente dans une phrase.",
          "Demain, je vais apprendre à mieux employer la salle d'attente.",
          "Quand je lis le texte, je cherche le sens de salle d'attente.",
          "Ce matin, nous avons associé la salle d'attente à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec salle d'attente.",
          "Le professeur a demandé un exemple avec la salle d'attente.",
          "J'ai choisi la salle d'attente parce que ce mot était dans la liste.",
          "Nous allons réviser la salle d'attente avant l'évaluation.",
          "Mon camarade a expliqué la salle d'attente avec ses mots.",
          "J'ai ajouté salle d'attente dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la salle d'attente semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la salle d'attente apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais salle d'attente, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà salle d'attente, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la salle d'attente avec des mots simples.",
          "La leçon que nous travaillons utilise salle d'attente dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la salle d'attente, le client posait des questions.",
          "Puisque salle d'attente est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé salle d'attente, tu comprendras mieux les consignes du médecin.",
          "Je pense que la salle d'attente aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, salle d'attente peut donner une information importante.",
          "Le mot dont je parle est salle d'attente, que la classe doit retenir.",
          "Tant que tu pratiqueras salle d'attente, tu parleras de santé plus facilement.",
          "Bien que la salle d'attente demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient salle d'attente, je penserai au vocabulaire médical.",
          "Bien que le mot salle d'attente paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la salle d'attente apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la salle d'attente, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la salle d'attente.",
          "Lorsque j'aurai mémorisé salle d'attente, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la salle d'attente.",
          "Puisque salle d'attente est utile, je le révise régulièrement.",
        ],
      } },
    { word: "consultation",     image: "consultation.webp",       article: "la",  gender: "f", definition: "La consultation est rendez-vous médical chez un praticien. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais la consultation.",
          "Je parle de la consultation.",
          "La consultation est importante.",
          "Le médecin explique la consultation.",
          "Le patient parle de la consultation.",
          "Tu comprends consultation.",
          "Il décrit la consultation.",
          "Elle soigne ce problème.",
          "Nous étudions la consultation.",
          "Vous notez consultation.",
          "Ils décrivent la consultation.",
          "Elles répètent consultation.",
          "La consultation est dans la leçon.",
          "Je lis le mot consultation.",
          "Je cherche la consultation.",
          "Il montre la consultation.",
          "Elle demande une explication sur la consultation.",
          "La pharmacie aide le patient.",
          "Le soignant parle de la consultation.",
          "La classe apprend consultation.",
          "Je répète consultation.",
          "Nous écrivons consultation.",
          "Tu apprends consultation.",
          "Le soin concerne la consultation.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois la consultation.",
          "Dans mon cahier, j'écris consultation.",
          "Le mot consultation est nouveau pour moi.",
          "Je répète consultation à voix haute.",
          "Tu connais la consultation.",
          "Nous dessinons la consultation.",
          "La classe regarde la consultation.",
          "Je montre la consultation au professeur.",
          "Il y a une consultation dans l'image.",
          "Cette leçon parle de la consultation.",
        ],
        a2: [
          "Hier, le médecin a parlé de la consultation au patient.",
          "Demain, je vais revoir le mot consultation.",
          "Quand j'étais malade, j'ai entendu parler de la consultation.",
          "Ce matin, le pharmacien a expliqué la consultation.",
          "Nous avons utilisé consultation dans une phrase.",
          "Ils vont apprendre consultation cette semaine.",
          "J'ai choisi la consultation parce que ce mot était utile.",
          "Elle a noté consultation dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec consultation.",
          "Le groupe a parlé de la consultation pendant le cours.",
          "Je vais demander des informations sur la consultation.",
          "Nous avons associé la consultation à une image.",
          "Hier soir, mon frère a cherché le sens de consultation.",
          "Pendant l'exercice, je confondais encore consultation.",
          "Elle a oublié le mot consultation pendant la dictée.",
          "Il va utiliser consultation dans sa réponse.",
          "Nous avons trouvé la consultation dans le dialogue médical.",
          "Ce week-end, je vais mémoriser consultation.",
          "L'élève a ajouté consultation dans sa phrase.",
          "J'ai compris consultation pour la première fois.",
          "Ma sœur a demandé un exemple avec consultation.",
          "Ils ont répété consultation à voix haute.",
          "Nous allons revoir la consultation avec le professeur.",
          "Elle a écrit consultation sans aide.",
          "La classe a demandé une définition de consultation.",
          "Après la leçon, j'ai utilisé le mot consultation dans une phrase.",
          "Demain, je vais apprendre à mieux employer la consultation.",
          "Quand je lis le texte, je cherche le sens de consultation.",
          "Ce matin, nous avons associé la consultation à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec consultation.",
          "Le professeur a demandé un exemple avec la consultation.",
          "J'ai choisi la consultation parce que ce mot était dans la liste.",
          "Nous allons réviser la consultation avant l'évaluation.",
          "Mon camarade a expliqué la consultation avec ses mots.",
          "J'ai ajouté consultation dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la consultation semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme la consultation apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais consultation, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà consultation, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué la consultation avec des mots simples.",
          "La leçon que nous travaillons utilise consultation dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de la consultation, le client posait des questions.",
          "Puisque consultation est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé consultation, tu comprendras mieux les consignes du médecin.",
          "Je pense que la consultation aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, consultation peut donner une information importante.",
          "Le mot dont je parle est consultation, que la classe doit retenir.",
          "Tant que tu pratiqueras consultation, tu parleras de santé plus facilement.",
          "Bien que la consultation demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient consultation, je penserai au vocabulaire médical.",
          "Bien que le mot consultation paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la consultation apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la consultation, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la consultation.",
          "Lorsque j'aurai mémorisé consultation, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la consultation.",
          "Puisque consultation est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ordonnance",       image: "ordonnance.webp",         article: "l'",  gender: "f", definition: "L'ordonnance est document du médecin pour les médicaments. Elle sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais l'ordonnance.",
          "Je parle de l'ordonnance.",
          "L'ordonnance est importante.",
          "Le médecin explique l'ordonnance.",
          "Le patient parle de l'ordonnance.",
          "Tu comprends ordonnance.",
          "Il décrit l'ordonnance.",
          "Elle soigne ce problème.",
          "Nous étudions l'ordonnance.",
          "Vous notez ordonnance.",
          "Ils décrivent l'ordonnance.",
          "Elles répètent ordonnance.",
          "L'ordonnance est dans la leçon.",
          "Je lis le mot ordonnance.",
          "Je cherche l'ordonnance.",
          "Il montre l'ordonnance.",
          "Elle demande une explication sur l'ordonnance.",
          "La pharmacie aide le patient.",
          "Le soignant parle de l'ordonnance.",
          "La classe apprend ordonnance.",
          "Je répète ordonnance.",
          "Nous écrivons ordonnance.",
          "Tu apprends ordonnance.",
          "Le soin concerne l'ordonnance.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois l'ordonnance.",
          "Dans mon cahier, j'écris ordonnance.",
          "Le mot ordonnance est nouveau pour moi.",
          "Je répète ordonnance à voix haute.",
          "Tu connais l'ordonnance.",
          "Nous dessinons l'ordonnance.",
          "La classe regarde l'ordonnance.",
          "Je montre l'ordonnance au professeur.",
          "Il y a une ordonnance dans l'image.",
          "Cette leçon parle de l'ordonnance.",
        ],
        a2: [
          "Hier, le médecin a parlé de l'ordonnance au patient.",
          "Demain, je vais revoir le mot ordonnance.",
          "Quand j'étais malade, j'ai entendu parler de l'ordonnance.",
          "Ce matin, le pharmacien a expliqué l'ordonnance.",
          "Nous avons utilisé ordonnance dans une phrase.",
          "Ils vont apprendre ordonnance cette semaine.",
          "J'ai choisi l'ordonnance parce que ce mot était utile.",
          "Elle a noté ordonnance dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec ordonnance.",
          "Le groupe a parlé de l'ordonnance pendant le cours.",
          "Je vais demander des informations sur l'ordonnance.",
          "Nous avons associé l'ordonnance à une image.",
          "Hier soir, mon frère a cherché le sens de ordonnance.",
          "Pendant l'exercice, je confondais encore ordonnance.",
          "Elle a oublié le mot ordonnance pendant la dictée.",
          "Il va utiliser ordonnance dans sa réponse.",
          "Nous avons trouvé l'ordonnance dans le dialogue médical.",
          "Ce week-end, je vais mémoriser ordonnance.",
          "L'élève a ajouté ordonnance dans sa phrase.",
          "J'ai compris ordonnance pour la première fois.",
          "Ma sœur a demandé un exemple avec ordonnance.",
          "Ils ont répété ordonnance à voix haute.",
          "Nous allons revoir l'ordonnance avec le professeur.",
          "Elle a écrit ordonnance sans aide.",
          "La classe a demandé une définition de ordonnance.",
          "Après la leçon, j'ai utilisé le mot ordonnance dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ordonnance.",
          "Quand je lis le texte, je cherche le sens de ordonnance.",
          "Ce matin, nous avons associé l'ordonnance à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ordonnance.",
          "Le professeur a demandé un exemple avec l'ordonnance.",
          "J'ai choisi l'ordonnance parce que ce mot était dans la liste.",
          "Nous allons réviser l'ordonnance avant l'évaluation.",
          "Mon camarade a expliqué l'ordonnance avec ses mots.",
          "J'ai ajouté ordonnance dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ordonnance semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme l'ordonnance apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais ordonnance, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà ordonnance, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué l'ordonnance avec des mots simples.",
          "La leçon que nous travaillons utilise ordonnance dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait de l'ordonnance, le client posait des questions.",
          "Puisque ordonnance est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé ordonnance, tu comprendras mieux les consignes du médecin.",
          "Je pense que l'ordonnance aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, ordonnance peut donner une information importante.",
          "Le mot dont je parle est ordonnance, que la classe doit retenir.",
          "Tant que tu pratiqueras ordonnance, tu parleras de santé plus facilement.",
          "Bien que l'ordonnance demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient ordonnance, je penserai au vocabulaire médical.",
          "Bien que le mot ordonnance paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ordonnance apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ordonnance, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ordonnance.",
          "Lorsque j'aurai mémorisé ordonnance, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ordonnance.",
          "Puisque ordonnance est utile, je le révise régulièrement.",
        ],
      } },
    { word: "rendez-vous",      image: "rendez-vous.webp",        article: "le",  gender: "m", definition: "Le rendez-vous est heure fixée pour voir un médecin. Il sert ? nommer cette r?alit? dans la vie quotidienne, ? la reconna?tre dans une image et ? l'utiliser correctement dans une phrase." , exampleSentences: {
        a1: [
          "Je connais le rendez-vous.",
          "Je parle du rendez-vous.",
          "Le rendez-vous est important.",
          "Le médecin explique le rendez-vous.",
          "Le patient parle du rendez-vous.",
          "Tu comprends rendez-vous.",
          "Il décrit le rendez-vous.",
          "Elle soigne ce problème.",
          "Nous étudions le rendez-vous.",
          "Vous notez rendez-vous.",
          "Ils décrivent le rendez-vous.",
          "Elles répètent rendez-vous.",
          "Le rendez-vous est dans la leçon.",
          "Je lis le mot rendez-vous.",
          "Je cherche le rendez-vous.",
          "Il montre le rendez-vous.",
          "Elle demande une explication sur le rendez-vous.",
          "La pharmacie aide le patient.",
          "Le soignant parle du rendez-vous.",
          "La classe apprend rendez-vous.",
          "Je répète rendez-vous.",
          "Nous écrivons rendez-vous.",
          "Tu apprends rendez-vous.",
          "Le soin concerne le rendez-vous.",
          "Ce mot parle de la santé.",
          "Aujourd'hui, je vois le rendez-vous.",
          "Dans mon cahier, j'écris rendez-vous.",
          "Le mot rendez-vous est nouveau pour moi.",
          "Je répète rendez-vous à voix haute.",
          "Tu connais le rendez-vous.",
          "Nous dessinons le rendez-vous.",
          "La classe regarde le rendez-vous.",
          "Je montre le rendez-vous au professeur.",
          "Il y a un rendez-vous dans l'image.",
          "Cette leçon parle du rendez-vous.",
        ],
        a2: [
          "Hier, le médecin a parlé du rendez-vous au patient.",
          "Demain, je vais revoir le mot rendez-vous.",
          "Quand j'étais malade, j'ai entendu parler du rendez-vous.",
          "Ce matin, le pharmacien a expliqué le rendez-vous.",
          "Nous avons utilisé rendez-vous dans une phrase.",
          "Ils vont apprendre rendez-vous cette semaine.",
          "J'ai choisi le rendez-vous parce que ce mot était utile.",
          "Elle a noté rendez-vous dans son carnet.",
          "Avant le rendez-vous, nous avons préparé une phrase avec rendez-vous.",
          "Le groupe a parlé du rendez-vous pendant le cours.",
          "Je vais demander des informations sur le rendez-vous.",
          "Nous avons associé le rendez-vous à une image.",
          "Hier soir, mon frère a cherché le sens de rendez-vous.",
          "Pendant l'exercice, je confondais encore rendez-vous.",
          "Elle a oublié le mot rendez-vous pendant la dictée.",
          "Il va utiliser rendez-vous dans sa réponse.",
          "Nous avons trouvé le rendez-vous dans le dialogue médical.",
          "Ce week-end, je vais mémoriser rendez-vous.",
          "L'élève a ajouté rendez-vous dans sa phrase.",
          "J'ai compris rendez-vous pour la première fois.",
          "Ma sœur a demandé un exemple avec rendez-vous.",
          "Ils ont répété rendez-vous à voix haute.",
          "Nous allons revoir le rendez-vous avec le professeur.",
          "Elle a écrit rendez-vous sans aide.",
          "La classe a demandé une définition de rendez-vous.",
          "Après la leçon, j'ai utilisé le mot rendez-vous dans une phrase.",
          "Demain, je vais apprendre à mieux employer le rendez-vous.",
          "Quand je lis le texte, je cherche le sens de rendez-vous.",
          "Ce matin, nous avons associé le rendez-vous à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec rendez-vous.",
          "Le professeur a demandé un exemple avec le rendez-vous.",
          "J'ai choisi le rendez-vous parce que ce mot était dans la liste.",
          "Nous allons réviser le rendez-vous avant l'évaluation.",
          "Mon camarade a expliqué le rendez-vous avec ses mots.",
          "J'ai ajouté rendez-vous dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le rendez-vous semble simple, il faut l'expliquer avec précision dans un contexte médical.",
          "Comme le rendez-vous apparaît dans le dialogue, le patient doit comprendre ce mot.",
          "Si tu connais rendez-vous, tu pourras mieux décrire un problème de santé.",
          "Même si je connais déjà rendez-vous, je dois encore le prononcer correctement.",
          "Le médecin, qui voulait rassurer le patient, a expliqué le rendez-vous avec des mots simples.",
          "La leçon que nous travaillons utilise rendez-vous dans plusieurs situations de santé.",
          "Pendant que le pharmacien parlait du rendez-vous, le client posait des questions.",
          "Puisque rendez-vous est utile, nous le révisons avant le jeu de rôle.",
          "Lorsque tu auras mémorisé rendez-vous, tu comprendras mieux les consignes du médecin.",
          "Je pense que le rendez-vous aide les élèves parce que ce mot revient souvent dans les dialogues.",
          "Même quand la phrase est courte, rendez-vous peut donner une information importante.",
          "Le mot dont je parle est rendez-vous, que la classe doit retenir.",
          "Tant que tu pratiqueras rendez-vous, tu parleras de santé plus facilement.",
          "Bien que le rendez-vous demande de l'attention, il devient plus clair avec des exemples.",
          "Si l'exercice contient rendez-vous, je penserai au vocabulaire médical.",
          "Bien que le mot rendez-vous paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le rendez-vous apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le rendez-vous, je pourrai l'employer dans une phrase personnelle.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le rendez-vous.",
          "Lorsque j'aurai mémorisé rendez-vous, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le rendez-vous.",
          "Puisque rendez-vous est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il a pris un ___ chez le médecin pour jeudi.",          answer: "rendez-vous" },
    { sentence: "Le ___ examine les yeux des patients.",                 answer: "ophtalmologue" },
    { sentence: "Elle attend dans la ___ d'attente du docteur.",         answer: "salle d'attente" },
    { sentence: "Le médecin écrit une ___ pour les médicaments.",        answer: "ordonnance" },
    { sentence: "L'___ soigne les enfants malades.",                     answer: "infirmier" },
  ],
};
