import type { VocabTheme } from "../../vocabulary-data";

export const V9_PAYSAGE_THEME: VocabTheme = {
  slug: "v9-paysage",
  code: "V9.8",
  title: "Le paysage",
  section: "V9",
  words: [
    { word: "montagne", image: "montagne.webp", article: "la",  gender: "f", definition: "relief élevé avec des sommets" , exampleSentences: {
        a1: [
          "Je vois la montagne.",
          "Je cherche la montagne.",
          "La montagne est importante.",
          "Je note montagne.",
          "Tu connais la montagne.",
          "Il utilise la montagne.",
          "Elle regarde la montagne.",
          "Nous trouvons la montagne.",
          "Vous demandez la montagne.",
          "Ils parlent de la montagne.",
          "Elles choisissent la montagne.",
          "La montagne est sur le plan.",
          "Le voyageur cherche la montagne.",
          "Je répète montagne.",
          "Il montre la montagne.",
          "Elle prépare son voyage.",
          "La ville contient la montagne.",
          "La carte indique la montagne.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons montagne.",
          "Tu apprends montagne.",
          "La classe regarde la montagne.",
          "Je montre la montagne au professeur.",
          "Cette leçon parle de la montagne.",
          "Aujourd'hui, je vois la montagne.",
          "Dans mon cahier, j'écris montagne.",
          "Le mot montagne est nouveau pour moi.",
          "Je répète montagne à voix haute.",
          "Nous dessinons la montagne.",
          "Il y a une montagne dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la montagne sur le plan.",
          "Demain, je vais chercher la montagne.",
          "Quand je voyage, j'utilise souvent la montagne.",
          "Ce matin, le guide a montré la montagne.",
          "Nous avons demandé où se trouvait la montagne.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la montagne parce que c'était pratique.",
          "Elle a noté montagne dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la montagne.",
          "Le groupe a trouvé la montagne près de la gare.",
          "Je vais chercher la montagne après l'arrivée.",
          "Nous avons associé la montagne à une image.",
          "Hier soir, mon frère a vérifié la montagne sur internet.",
          "Pendant les vacances, nous utilisions souvent la montagne.",
          "Elle a oublié le mot montagne pendant l'exercice.",
          "Il va utiliser montagne dans sa phrase.",
          "Nous avons trouvé la montagne dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser montagne.",
          "L'élève a ajouté montagne dans sa réponse.",
          "J'ai compris le mot montagne pour la première fois.",
          "Ma sœur a choisi la montagne pour son exemple.",
          "Ils ont répété montagne à voix haute.",
          "Nous allons revoir la montagne avec le professeur.",
          "Elle a noté montagne pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la montagne.",
          "Après la leçon, j'ai utilisé le mot montagne dans une phrase.",
          "Demain, je vais apprendre à mieux employer la montagne.",
          "Quand je lis le texte, je cherche le sens de montagne.",
          "Ce matin, nous avons associé la montagne à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec montagne.",
          "Le professeur a demandé un exemple avec la montagne.",
          "J'ai choisi la montagne parce que ce mot était dans la liste.",
          "Nous allons réviser la montagne avant l'évaluation.",
          "Mon camarade a expliqué la montagne avec ses mots.",
          "J'ai ajouté montagne dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la montagne semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la montagne se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais montagne, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà montagne, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la montagne.",
          "La leçon que nous travaillons utilise montagne dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la montagne, les élèves prenaient des notes.",
          "Puisque la montagne aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé montagne, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la montagne aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, montagne peut donner une information précise.",
          "Le mot dont je parle est montagne, que la classe doit retenir.",
          "Tant que tu pratiqueras montagne, tu comprendras mieux les dialogues de voyage.",
          "Bien que la montagne demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient montagne, je penserai au vocabulaire du déplacement.",
          "Bien que le mot montagne paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la montagne apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la montagne, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà montagne, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la montagne.",
          "Lorsque j'aurai mémorisé montagne, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la montagne.",
          "Puisque montagne est utile, je le révise régulièrement.",
        ],
      } },
    { word: "mer", image: "mer.webp",      article: "la",  gender: "f", definition: "grande étendue d'eau salée" , exampleSentences: {
        a1: [
          "Je vois la mer.",
          "Je cherche la mer.",
          "La mer est importante.",
          "Je note mer.",
          "Tu connais la mer.",
          "Il utilise la mer.",
          "Elle regarde la mer.",
          "Nous trouvons la mer.",
          "Vous demandez la mer.",
          "Ils parlent de la mer.",
          "Elles choisissent la mer.",
          "La mer est sur le plan.",
          "Le voyageur cherche la mer.",
          "Je répète mer.",
          "Il montre la mer.",
          "Elle prépare son voyage.",
          "La ville contient la mer.",
          "La carte indique la mer.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons mer.",
          "Tu apprends mer.",
          "La classe regarde la mer.",
          "Je montre la mer au professeur.",
          "Cette leçon parle de la mer.",
          "Aujourd'hui, je vois la mer.",
          "Dans mon cahier, j'écris mer.",
          "Le mot mer est nouveau pour moi.",
          "Je répète mer à voix haute.",
          "Nous dessinons la mer.",
          "Il y a une mer dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la mer sur le plan.",
          "Demain, je vais chercher la mer.",
          "Quand je voyage, j'utilise souvent la mer.",
          "Ce matin, le guide a montré la mer.",
          "Nous avons demandé où se trouvait la mer.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la mer parce que c'était pratique.",
          "Elle a noté mer dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la mer.",
          "Le groupe a trouvé la mer près de la gare.",
          "Je vais chercher la mer après l'arrivée.",
          "Nous avons associé la mer à une image.",
          "Hier soir, mon frère a vérifié la mer sur internet.",
          "Pendant les vacances, nous utilisions souvent la mer.",
          "Elle a oublié le mot mer pendant l'exercice.",
          "Il va utiliser mer dans sa phrase.",
          "Nous avons trouvé la mer dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser mer.",
          "L'élève a ajouté mer dans sa réponse.",
          "J'ai compris le mot mer pour la première fois.",
          "Ma sœur a choisi la mer pour son exemple.",
          "Ils ont répété mer à voix haute.",
          "Nous allons revoir la mer avec le professeur.",
          "Elle a noté mer pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la mer.",
          "Après la leçon, j'ai utilisé le mot mer dans une phrase.",
          "Demain, je vais apprendre à mieux employer la mer.",
          "Quand je lis le texte, je cherche le sens de mer.",
          "Ce matin, nous avons associé la mer à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec mer.",
          "Le professeur a demandé un exemple avec la mer.",
          "J'ai choisi la mer parce que ce mot était dans la liste.",
          "Nous allons réviser la mer avant l'évaluation.",
          "Mon camarade a expliqué la mer avec ses mots.",
          "J'ai ajouté mer dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la mer semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la mer se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais mer, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà mer, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la mer.",
          "La leçon que nous travaillons utilise mer dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la mer, les élèves prenaient des notes.",
          "Puisque la mer aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé mer, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la mer aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, mer peut donner une information précise.",
          "Le mot dont je parle est mer, que la classe doit retenir.",
          "Tant que tu pratiqueras mer, tu comprendras mieux les dialogues de voyage.",
          "Bien que la mer demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient mer, je penserai au vocabulaire du déplacement.",
          "Bien que le mot mer paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la mer apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la mer, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà mer, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la mer.",
          "Lorsque j'aurai mémorisé mer, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la mer.",
          "Puisque mer est utile, je le révise régulièrement.",
        ],
      } },
    { word: "plage", image: "plage.webp",    article: "la",  gender: "f", definition: "bande de sable au bord de la mer" , exampleSentences: {
        a1: [
          "Je vois la plage.",
          "Je cherche la plage.",
          "La plage est importante.",
          "Je note plage.",
          "Tu connais la plage.",
          "Il utilise la plage.",
          "Elle regarde la plage.",
          "Nous trouvons la plage.",
          "Vous demandez la plage.",
          "Ils parlent de la plage.",
          "Elles choisissent la plage.",
          "La plage est sur le plan.",
          "Le voyageur cherche la plage.",
          "Je répète plage.",
          "Il montre la plage.",
          "Elle prépare son voyage.",
          "La ville contient la plage.",
          "La carte indique la plage.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons plage.",
          "Tu apprends plage.",
          "La classe regarde la plage.",
          "Je montre la plage au professeur.",
          "Cette leçon parle de la plage.",
          "Aujourd'hui, je vois la plage.",
          "Dans mon cahier, j'écris plage.",
          "Le mot plage est nouveau pour moi.",
          "Je répète plage à voix haute.",
          "Nous dessinons la plage.",
          "Il y a une plage dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la plage sur le plan.",
          "Demain, je vais chercher la plage.",
          "Quand je voyage, j'utilise souvent la plage.",
          "Ce matin, le guide a montré la plage.",
          "Nous avons demandé où se trouvait la plage.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la plage parce que c'était pratique.",
          "Elle a noté plage dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la plage.",
          "Le groupe a trouvé la plage près de la gare.",
          "Je vais chercher la plage après l'arrivée.",
          "Nous avons associé la plage à une image.",
          "Hier soir, mon frère a vérifié la plage sur internet.",
          "Pendant les vacances, nous utilisions souvent la plage.",
          "Elle a oublié le mot plage pendant l'exercice.",
          "Il va utiliser plage dans sa phrase.",
          "Nous avons trouvé la plage dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser plage.",
          "L'élève a ajouté plage dans sa réponse.",
          "J'ai compris le mot plage pour la première fois.",
          "Ma sœur a choisi la plage pour son exemple.",
          "Ils ont répété plage à voix haute.",
          "Nous allons revoir la plage avec le professeur.",
          "Elle a noté plage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la plage.",
          "Après la leçon, j'ai utilisé le mot plage dans une phrase.",
          "Demain, je vais apprendre à mieux employer la plage.",
          "Quand je lis le texte, je cherche le sens de plage.",
          "Ce matin, nous avons associé la plage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec plage.",
          "Le professeur a demandé un exemple avec la plage.",
          "J'ai choisi la plage parce que ce mot était dans la liste.",
          "Nous allons réviser la plage avant l'évaluation.",
          "Mon camarade a expliqué la plage avec ses mots.",
          "J'ai ajouté plage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la plage semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la plage se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais plage, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà plage, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la plage.",
          "La leçon que nous travaillons utilise plage dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la plage, les élèves prenaient des notes.",
          "Puisque la plage aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé plage, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la plage aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, plage peut donner une information précise.",
          "Le mot dont je parle est plage, que la classe doit retenir.",
          "Tant que tu pratiqueras plage, tu comprendras mieux les dialogues de voyage.",
          "Bien que la plage demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient plage, je penserai au vocabulaire du déplacement.",
          "Bien que le mot plage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la plage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la plage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà plage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la plage.",
          "Lorsque j'aurai mémorisé plage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la plage.",
          "Puisque plage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "campagne", image: "campagne.webp", article: "la",  gender: "f", definition: "zone rurale avec champs et nature" , exampleSentences: {
        a1: [
          "Je vois la campagne.",
          "Je cherche la campagne.",
          "La campagne est importante.",
          "Je note campagne.",
          "Tu connais la campagne.",
          "Il utilise la campagne.",
          "Elle regarde la campagne.",
          "Nous trouvons la campagne.",
          "Vous demandez la campagne.",
          "Ils parlent de la campagne.",
          "Elles choisissent la campagne.",
          "La campagne est sur le plan.",
          "Le voyageur cherche la campagne.",
          "Je répète campagne.",
          "Il montre la campagne.",
          "Elle prépare son voyage.",
          "La ville contient la campagne.",
          "La carte indique la campagne.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons campagne.",
          "Tu apprends campagne.",
          "La classe regarde la campagne.",
          "Je montre la campagne au professeur.",
          "Cette leçon parle de la campagne.",
          "Aujourd'hui, je vois la campagne.",
          "Dans mon cahier, j'écris campagne.",
          "Le mot campagne est nouveau pour moi.",
          "Je répète campagne à voix haute.",
          "Nous dessinons la campagne.",
          "Il y a une campagne dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la campagne sur le plan.",
          "Demain, je vais chercher la campagne.",
          "Quand je voyage, j'utilise souvent la campagne.",
          "Ce matin, le guide a montré la campagne.",
          "Nous avons demandé où se trouvait la campagne.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la campagne parce que c'était pratique.",
          "Elle a noté campagne dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la campagne.",
          "Le groupe a trouvé la campagne près de la gare.",
          "Je vais chercher la campagne après l'arrivée.",
          "Nous avons associé la campagne à une image.",
          "Hier soir, mon frère a vérifié la campagne sur internet.",
          "Pendant les vacances, nous utilisions souvent la campagne.",
          "Elle a oublié le mot campagne pendant l'exercice.",
          "Il va utiliser campagne dans sa phrase.",
          "Nous avons trouvé la campagne dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser campagne.",
          "L'élève a ajouté campagne dans sa réponse.",
          "J'ai compris le mot campagne pour la première fois.",
          "Ma sœur a choisi la campagne pour son exemple.",
          "Ils ont répété campagne à voix haute.",
          "Nous allons revoir la campagne avec le professeur.",
          "Elle a noté campagne pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la campagne.",
          "Après la leçon, j'ai utilisé le mot campagne dans une phrase.",
          "Demain, je vais apprendre à mieux employer la campagne.",
          "Quand je lis le texte, je cherche le sens de campagne.",
          "Ce matin, nous avons associé la campagne à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec campagne.",
          "Le professeur a demandé un exemple avec la campagne.",
          "J'ai choisi la campagne parce que ce mot était dans la liste.",
          "Nous allons réviser la campagne avant l'évaluation.",
          "Mon camarade a expliqué la campagne avec ses mots.",
          "J'ai ajouté campagne dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la campagne semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la campagne se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais campagne, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà campagne, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la campagne.",
          "La leçon que nous travaillons utilise campagne dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la campagne, les élèves prenaient des notes.",
          "Puisque la campagne aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé campagne, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la campagne aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, campagne peut donner une information précise.",
          "Le mot dont je parle est campagne, que la classe doit retenir.",
          "Tant que tu pratiqueras campagne, tu comprendras mieux les dialogues de voyage.",
          "Bien que la campagne demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient campagne, je penserai au vocabulaire du déplacement.",
          "Bien que le mot campagne paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la campagne apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la campagne, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà campagne, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la campagne.",
          "Lorsque j'aurai mémorisé campagne, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la campagne.",
          "Puisque campagne est utile, je le révise régulièrement.",
        ],
      } },
    { word: "forêt", image: "foret.webp",    article: "la",  gender: "f", definition: "grande étendue d'arbres" , exampleSentences: {
        a1: [
          "Je vois la forêt.",
          "Je cherche la forêt.",
          "La forêt est importante.",
          "Je note forêt.",
          "Tu connais la forêt.",
          "Il utilise la forêt.",
          "Elle regarde la forêt.",
          "Nous trouvons la forêt.",
          "Vous demandez la forêt.",
          "Ils parlent de la forêt.",
          "Elles choisissent la forêt.",
          "La forêt est sur le plan.",
          "Le voyageur cherche la forêt.",
          "Je répète forêt.",
          "Il montre la forêt.",
          "Elle prépare son voyage.",
          "La ville contient la forêt.",
          "La carte indique la forêt.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons forêt.",
          "Tu apprends forêt.",
          "La classe regarde la forêt.",
          "Je montre la forêt au professeur.",
          "Cette leçon parle de la forêt.",
          "Aujourd'hui, je vois la forêt.",
          "Dans mon cahier, j'écris forêt.",
          "Le mot forêt est nouveau pour moi.",
          "Je répète forêt à voix haute.",
          "Nous dessinons la forêt.",
          "Il y a une forêt dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la forêt sur le plan.",
          "Demain, je vais chercher la forêt.",
          "Quand je voyage, j'utilise souvent la forêt.",
          "Ce matin, le guide a montré la forêt.",
          "Nous avons demandé où se trouvait la forêt.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la forêt parce que c'était pratique.",
          "Elle a noté forêt dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la forêt.",
          "Le groupe a trouvé la forêt près de la gare.",
          "Je vais chercher la forêt après l'arrivée.",
          "Nous avons associé la forêt à une image.",
          "Hier soir, mon frère a vérifié la forêt sur internet.",
          "Pendant les vacances, nous utilisions souvent la forêt.",
          "Elle a oublié le mot forêt pendant l'exercice.",
          "Il va utiliser forêt dans sa phrase.",
          "Nous avons trouvé la forêt dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser forêt.",
          "L'élève a ajouté forêt dans sa réponse.",
          "J'ai compris le mot forêt pour la première fois.",
          "Ma sœur a choisi la forêt pour son exemple.",
          "Ils ont répété forêt à voix haute.",
          "Nous allons revoir la forêt avec le professeur.",
          "Elle a noté forêt pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la forêt.",
          "Après la leçon, j'ai utilisé le mot forêt dans une phrase.",
          "Demain, je vais apprendre à mieux employer la forêt.",
          "Quand je lis le texte, je cherche le sens de forêt.",
          "Ce matin, nous avons associé la forêt à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec forêt.",
          "Le professeur a demandé un exemple avec la forêt.",
          "J'ai choisi la forêt parce que ce mot était dans la liste.",
          "Nous allons réviser la forêt avant l'évaluation.",
          "Mon camarade a expliqué la forêt avec ses mots.",
          "J'ai ajouté forêt dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la forêt semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la forêt se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais forêt, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà forêt, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la forêt.",
          "La leçon que nous travaillons utilise forêt dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la forêt, les élèves prenaient des notes.",
          "Puisque la forêt aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé forêt, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la forêt aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, forêt peut donner une information précise.",
          "Le mot dont je parle est forêt, que la classe doit retenir.",
          "Tant que tu pratiqueras forêt, tu comprendras mieux les dialogues de voyage.",
          "Bien que la forêt demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient forêt, je penserai au vocabulaire du déplacement.",
          "Bien que le mot forêt paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la forêt apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la forêt, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà forêt, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la forêt.",
          "Lorsque j'aurai mémorisé forêt, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la forêt.",
          "Puisque forêt est utile, je le révise régulièrement.",
        ],
      } },
    { word: "rivière", image: "riviere.webp",  article: "la",  gender: "f", definition: "cours d'eau naturel" , exampleSentences: {
        a1: [
          "Je vois la rivière.",
          "Je cherche la rivière.",
          "La rivière est importante.",
          "Je note rivière.",
          "Tu connais la rivière.",
          "Il utilise la rivière.",
          "Elle regarde la rivière.",
          "Nous trouvons la rivière.",
          "Vous demandez la rivière.",
          "Ils parlent de la rivière.",
          "Elles choisissent la rivière.",
          "La rivière est sur le plan.",
          "Le voyageur cherche la rivière.",
          "Je répète rivière.",
          "Il montre la rivière.",
          "Elle prépare son voyage.",
          "La ville contient la rivière.",
          "La carte indique la rivière.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons rivière.",
          "Tu apprends rivière.",
          "La classe regarde la rivière.",
          "Je montre la rivière au professeur.",
          "Cette leçon parle de la rivière.",
          "Aujourd'hui, je vois la rivière.",
          "Dans mon cahier, j'écris rivière.",
          "Le mot rivière est nouveau pour moi.",
          "Je répète rivière à voix haute.",
          "Nous dessinons la rivière.",
          "Il y a une rivière dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la rivière sur le plan.",
          "Demain, je vais chercher la rivière.",
          "Quand je voyage, j'utilise souvent la rivière.",
          "Ce matin, le guide a montré la rivière.",
          "Nous avons demandé où se trouvait la rivière.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la rivière parce que c'était pratique.",
          "Elle a noté rivière dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la rivière.",
          "Le groupe a trouvé la rivière près de la gare.",
          "Je vais chercher la rivière après l'arrivée.",
          "Nous avons associé la rivière à une image.",
          "Hier soir, mon frère a vérifié la rivière sur internet.",
          "Pendant les vacances, nous utilisions souvent la rivière.",
          "Elle a oublié le mot rivière pendant l'exercice.",
          "Il va utiliser rivière dans sa phrase.",
          "Nous avons trouvé la rivière dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser rivière.",
          "L'élève a ajouté rivière dans sa réponse.",
          "J'ai compris le mot rivière pour la première fois.",
          "Ma sœur a choisi la rivière pour son exemple.",
          "Ils ont répété rivière à voix haute.",
          "Nous allons revoir la rivière avec le professeur.",
          "Elle a noté rivière pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la rivière.",
          "Après la leçon, j'ai utilisé le mot rivière dans une phrase.",
          "Demain, je vais apprendre à mieux employer la rivière.",
          "Quand je lis le texte, je cherche le sens de rivière.",
          "Ce matin, nous avons associé la rivière à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec rivière.",
          "Le professeur a demandé un exemple avec la rivière.",
          "J'ai choisi la rivière parce que ce mot était dans la liste.",
          "Nous allons réviser la rivière avant l'évaluation.",
          "Mon camarade a expliqué la rivière avec ses mots.",
          "J'ai ajouté rivière dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la rivière semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la rivière se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais rivière, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà rivière, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la rivière.",
          "La leçon que nous travaillons utilise rivière dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la rivière, les élèves prenaient des notes.",
          "Puisque la rivière aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé rivière, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la rivière aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, rivière peut donner une information précise.",
          "Le mot dont je parle est rivière, que la classe doit retenir.",
          "Tant que tu pratiqueras rivière, tu comprendras mieux les dialogues de voyage.",
          "Bien que la rivière demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient rivière, je penserai au vocabulaire du déplacement.",
          "Bien que le mot rivière paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la rivière apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la rivière, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà rivière, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la rivière.",
          "Lorsque j'aurai mémorisé rivière, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la rivière.",
          "Puisque rivière est utile, je le révise régulièrement.",
        ],
      } },
    { word: "lac", image: "lac.webp",      article: "le",  gender: "m", definition: "étendue d'eau douce entourée de terres" , exampleSentences: {
        a1: [
          "Je vois le lac.",
          "Je cherche le lac.",
          "Le lac est important.",
          "Je note lac.",
          "Tu connais le lac.",
          "Il utilise le lac.",
          "Elle regarde le lac.",
          "Nous trouvons le lac.",
          "Vous demandez le lac.",
          "Ils parlent du lac.",
          "Elles choisissent le lac.",
          "Le lac est sur le plan.",
          "Le voyageur cherche le lac.",
          "Je répète lac.",
          "Il montre le lac.",
          "Elle prépare son voyage.",
          "La ville contient le lac.",
          "La carte indique le lac.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons lac.",
          "Tu apprends lac.",
          "La classe regarde le lac.",
          "Je montre le lac au professeur.",
          "Cette leçon parle du lac.",
          "Aujourd'hui, je vois le lac.",
          "Dans mon cahier, j'écris lac.",
          "Le mot lac est nouveau pour moi.",
          "Je répète lac à voix haute.",
          "Nous dessinons le lac.",
          "Il y a un lac dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché le lac sur le plan.",
          "Demain, je vais chercher le lac.",
          "Quand je voyage, j'utilise souvent le lac.",
          "Ce matin, le guide a montré le lac.",
          "Nous avons demandé où se trouvait le lac.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le lac parce que c'était pratique.",
          "Elle a noté lac dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du lac.",
          "Le groupe a trouvé le lac près de la gare.",
          "Je vais chercher le lac après l'arrivée.",
          "Nous avons associé le lac à une image.",
          "Hier soir, mon frère a vérifié le lac sur internet.",
          "Pendant les vacances, nous utilisions souvent le lac.",
          "Elle a oublié le mot lac pendant l'exercice.",
          "Il va utiliser lac dans sa phrase.",
          "Nous avons trouvé le lac dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser lac.",
          "L'élève a ajouté lac dans sa réponse.",
          "J'ai compris le mot lac pour la première fois.",
          "Ma sœur a choisi le lac pour son exemple.",
          "Ils ont répété lac à voix haute.",
          "Nous allons revoir le lac avec le professeur.",
          "Elle a noté lac pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le lac.",
          "Après la leçon, j'ai utilisé le mot lac dans une phrase.",
          "Demain, je vais apprendre à mieux employer le lac.",
          "Quand je lis le texte, je cherche le sens de lac.",
          "Ce matin, nous avons associé le lac à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec lac.",
          "Le professeur a demandé un exemple avec le lac.",
          "J'ai choisi le lac parce que ce mot était dans la liste.",
          "Nous allons réviser le lac avant l'évaluation.",
          "Mon camarade a expliqué le lac avec ses mots.",
          "J'ai ajouté lac dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le lac semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le lac se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais lac, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà lac, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le lac.",
          "La leçon que nous travaillons utilise lac dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le lac, les élèves prenaient des notes.",
          "Puisque le lac aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé lac, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le lac aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, lac peut donner une information précise.",
          "Le mot dont je parle est lac, que la classe doit retenir.",
          "Tant que tu pratiqueras lac, tu comprendras mieux les dialogues de voyage.",
          "Bien que le lac demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient lac, je penserai au vocabulaire du déplacement.",
          "Bien que le mot lac paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le lac apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le lac, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà lac, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le lac.",
          "Lorsque j'aurai mémorisé lac, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le lac.",
          "Puisque lac est utile, je le révise régulièrement.",
        ],
      } },
    { word: "colline", image: "colline.webp",  article: "la",  gender: "f", definition: "élévation de terrain moins haute qu'une montagne" , exampleSentences: {
        a1: [
          "Je vois la colline.",
          "Je cherche la colline.",
          "La colline est importante.",
          "Je note colline.",
          "Tu connais la colline.",
          "Il utilise la colline.",
          "Elle regarde la colline.",
          "Nous trouvons la colline.",
          "Vous demandez la colline.",
          "Ils parlent de la colline.",
          "Elles choisissent la colline.",
          "La colline est sur le plan.",
          "Le voyageur cherche la colline.",
          "Je répète colline.",
          "Il montre la colline.",
          "Elle prépare son voyage.",
          "La ville contient la colline.",
          "La carte indique la colline.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons colline.",
          "Tu apprends colline.",
          "La classe regarde la colline.",
          "Je montre la colline au professeur.",
          "Cette leçon parle de la colline.",
          "Aujourd'hui, je vois la colline.",
          "Dans mon cahier, j'écris colline.",
          "Le mot colline est nouveau pour moi.",
          "Je répète colline à voix haute.",
          "Nous dessinons la colline.",
          "Il y a une colline dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la colline sur le plan.",
          "Demain, je vais chercher la colline.",
          "Quand je voyage, j'utilise souvent la colline.",
          "Ce matin, le guide a montré la colline.",
          "Nous avons demandé où se trouvait la colline.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la colline parce que c'était pratique.",
          "Elle a noté colline dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la colline.",
          "Le groupe a trouvé la colline près de la gare.",
          "Je vais chercher la colline après l'arrivée.",
          "Nous avons associé la colline à une image.",
          "Hier soir, mon frère a vérifié la colline sur internet.",
          "Pendant les vacances, nous utilisions souvent la colline.",
          "Elle a oublié le mot colline pendant l'exercice.",
          "Il va utiliser colline dans sa phrase.",
          "Nous avons trouvé la colline dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser colline.",
          "L'élève a ajouté colline dans sa réponse.",
          "J'ai compris le mot colline pour la première fois.",
          "Ma sœur a choisi la colline pour son exemple.",
          "Ils ont répété colline à voix haute.",
          "Nous allons revoir la colline avec le professeur.",
          "Elle a noté colline pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la colline.",
          "Après la leçon, j'ai utilisé le mot colline dans une phrase.",
          "Demain, je vais apprendre à mieux employer la colline.",
          "Quand je lis le texte, je cherche le sens de colline.",
          "Ce matin, nous avons associé la colline à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec colline.",
          "Le professeur a demandé un exemple avec la colline.",
          "J'ai choisi la colline parce que ce mot était dans la liste.",
          "Nous allons réviser la colline avant l'évaluation.",
          "Mon camarade a expliqué la colline avec ses mots.",
          "J'ai ajouté colline dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la colline semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la colline se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais colline, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà colline, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la colline.",
          "La leçon que nous travaillons utilise colline dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la colline, les élèves prenaient des notes.",
          "Puisque la colline aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé colline, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la colline aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, colline peut donner une information précise.",
          "Le mot dont je parle est colline, que la classe doit retenir.",
          "Tant que tu pratiqueras colline, tu comprendras mieux les dialogues de voyage.",
          "Bien que la colline demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient colline, je penserai au vocabulaire du déplacement.",
          "Bien que le mot colline paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la colline apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la colline, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà colline, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la colline.",
          "Lorsque j'aurai mémorisé colline, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la colline.",
          "Puisque colline est utile, je le révise régulièrement.",
        ],
      } },
    { word: "vallée", image: "vallee.webp",   article: "la",  gender: "f", definition: "espace plat entre deux reliefs" , exampleSentences: {
        a1: [
          "Je vois la vallée.",
          "Je cherche la vallée.",
          "La vallée est importante.",
          "Je note vallée.",
          "Tu connais la vallée.",
          "Il utilise la vallée.",
          "Elle regarde la vallée.",
          "Nous trouvons la vallée.",
          "Vous demandez la vallée.",
          "Ils parlent de la vallée.",
          "Elles choisissent la vallée.",
          "La vallée est sur le plan.",
          "Le voyageur cherche la vallée.",
          "Je répète vallée.",
          "Il montre la vallée.",
          "Elle prépare son voyage.",
          "La ville contient la vallée.",
          "La carte indique la vallée.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons vallée.",
          "Tu apprends vallée.",
          "La classe regarde la vallée.",
          "Je montre la vallée au professeur.",
          "Cette leçon parle de la vallée.",
          "Aujourd'hui, je vois la vallée.",
          "Dans mon cahier, j'écris vallée.",
          "Le mot vallée est nouveau pour moi.",
          "Je répète vallée à voix haute.",
          "Nous dessinons la vallée.",
          "Il y a une vallée dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la vallée sur le plan.",
          "Demain, je vais chercher la vallée.",
          "Quand je voyage, j'utilise souvent la vallée.",
          "Ce matin, le guide a montré la vallée.",
          "Nous avons demandé où se trouvait la vallée.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la vallée parce que c'était pratique.",
          "Elle a noté vallée dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la vallée.",
          "Le groupe a trouvé la vallée près de la gare.",
          "Je vais chercher la vallée après l'arrivée.",
          "Nous avons associé la vallée à une image.",
          "Hier soir, mon frère a vérifié la vallée sur internet.",
          "Pendant les vacances, nous utilisions souvent la vallée.",
          "Elle a oublié le mot vallée pendant l'exercice.",
          "Il va utiliser vallée dans sa phrase.",
          "Nous avons trouvé la vallée dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser vallée.",
          "L'élève a ajouté vallée dans sa réponse.",
          "J'ai compris le mot vallée pour la première fois.",
          "Ma sœur a choisi la vallée pour son exemple.",
          "Ils ont répété vallée à voix haute.",
          "Nous allons revoir la vallée avec le professeur.",
          "Elle a noté vallée pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la vallée.",
          "Après la leçon, j'ai utilisé le mot vallée dans une phrase.",
          "Demain, je vais apprendre à mieux employer la vallée.",
          "Quand je lis le texte, je cherche le sens de vallée.",
          "Ce matin, nous avons associé la vallée à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec vallée.",
          "Le professeur a demandé un exemple avec la vallée.",
          "J'ai choisi la vallée parce que ce mot était dans la liste.",
          "Nous allons réviser la vallée avant l'évaluation.",
          "Mon camarade a expliqué la vallée avec ses mots.",
          "J'ai ajouté vallée dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la vallée semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la vallée se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais vallée, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà vallée, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la vallée.",
          "La leçon que nous travaillons utilise vallée dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la vallée, les élèves prenaient des notes.",
          "Puisque la vallée aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé vallée, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la vallée aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, vallée peut donner une information précise.",
          "Le mot dont je parle est vallée, que la classe doit retenir.",
          "Tant que tu pratiqueras vallée, tu comprendras mieux les dialogues de voyage.",
          "Bien que la vallée demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient vallée, je penserai au vocabulaire du déplacement.",
          "Bien que le mot vallée paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la vallée apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la vallée, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà vallée, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la vallée.",
          "Lorsque j'aurai mémorisé vallée, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la vallée.",
          "Puisque vallée est utile, je le révise régulièrement.",
        ],
      } },
    { word: "désert", image: "desert.webp",   article: "le",  gender: "m", definition: "région très sèche et peu habitée" , exampleSentences: {
        a1: [
          "Je vois le désert.",
          "Je cherche le désert.",
          "Le désert est important.",
          "Je note désert.",
          "Tu connais le désert.",
          "Il utilise le désert.",
          "Elle regarde le désert.",
          "Nous trouvons le désert.",
          "Vous demandez le désert.",
          "Ils parlent du désert.",
          "Elles choisissent le désert.",
          "Le désert est sur le plan.",
          "Le voyageur cherche le désert.",
          "Je répète désert.",
          "Il montre le désert.",
          "Elle prépare son voyage.",
          "La ville contient le désert.",
          "La carte indique le désert.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons désert.",
          "Tu apprends désert.",
          "La classe regarde le désert.",
          "Je montre le désert au professeur.",
          "Cette leçon parle du désert.",
          "Aujourd'hui, je vois le désert.",
          "Dans mon cahier, j'écris désert.",
          "Le mot désert est nouveau pour moi.",
          "Je répète désert à voix haute.",
          "Nous dessinons le désert.",
          "Il y a un désert dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché le désert sur le plan.",
          "Demain, je vais chercher le désert.",
          "Quand je voyage, j'utilise souvent le désert.",
          "Ce matin, le guide a montré le désert.",
          "Nous avons demandé où se trouvait le désert.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le désert parce que c'était pratique.",
          "Elle a noté désert dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du désert.",
          "Le groupe a trouvé le désert près de la gare.",
          "Je vais chercher le désert après l'arrivée.",
          "Nous avons associé le désert à une image.",
          "Hier soir, mon frère a vérifié le désert sur internet.",
          "Pendant les vacances, nous utilisions souvent le désert.",
          "Elle a oublié le mot désert pendant l'exercice.",
          "Il va utiliser désert dans sa phrase.",
          "Nous avons trouvé le désert dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser désert.",
          "L'élève a ajouté désert dans sa réponse.",
          "J'ai compris le mot désert pour la première fois.",
          "Ma sœur a choisi le désert pour son exemple.",
          "Ils ont répété désert à voix haute.",
          "Nous allons revoir le désert avec le professeur.",
          "Elle a noté désert pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le désert.",
          "Après la leçon, j'ai utilisé le mot désert dans une phrase.",
          "Demain, je vais apprendre à mieux employer le désert.",
          "Quand je lis le texte, je cherche le sens de désert.",
          "Ce matin, nous avons associé le désert à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec désert.",
          "Le professeur a demandé un exemple avec le désert.",
          "J'ai choisi le désert parce que ce mot était dans la liste.",
          "Nous allons réviser le désert avant l'évaluation.",
          "Mon camarade a expliqué le désert avec ses mots.",
          "J'ai ajouté désert dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le désert semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le désert se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais désert, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà désert, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le désert.",
          "La leçon que nous travaillons utilise désert dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le désert, les élèves prenaient des notes.",
          "Puisque le désert aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé désert, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le désert aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, désert peut donner une information précise.",
          "Le mot dont je parle est désert, que la classe doit retenir.",
          "Tant que tu pratiqueras désert, tu comprendras mieux les dialogues de voyage.",
          "Bien que le désert demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient désert, je penserai au vocabulaire du déplacement.",
          "Bien que le mot désert paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le désert apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le désert, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà désert, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le désert.",
          "Lorsque j'aurai mémorisé désert, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le désert.",
          "Puisque désert est utile, je le révise régulièrement.",
        ],
      } },
    { word: "île", image: "ile.webp",      article: "l'",  gender: "f", definition: "terre entourée d'eau de tous côtés" , exampleSentences: {
        a1: [
          "Je vois l'île.",
          "Je cherche l'île.",
          "L'île est importante.",
          "Je note île.",
          "Tu connais l'île.",
          "Il utilise l'île.",
          "Elle regarde l'île.",
          "Nous trouvons l'île.",
          "Vous demandez l'île.",
          "Ils parlent de l'île.",
          "Elles choisissent l'île.",
          "L'île est sur le plan.",
          "Le voyageur cherche l'île.",
          "Je répète île.",
          "Il montre l'île.",
          "Elle prépare son voyage.",
          "La ville contient l'île.",
          "La carte indique l'île.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons île.",
          "Tu apprends île.",
          "La classe regarde l'île.",
          "Je montre l'île au professeur.",
          "Cette leçon parle de l'île.",
          "Aujourd'hui, je vois l'île.",
          "Dans mon cahier, j'écris île.",
          "Le mot île est nouveau pour moi.",
          "Je répète île à voix haute.",
          "Nous dessinons l'île.",
          "Il y a une île dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché l'île sur le plan.",
          "Demain, je vais chercher l'île.",
          "Quand je voyage, j'utilise souvent l'île.",
          "Ce matin, le guide a montré l'île.",
          "Nous avons demandé où se trouvait l'île.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'île parce que c'était pratique.",
          "Elle a noté île dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'île.",
          "Le groupe a trouvé l'île près de la gare.",
          "Je vais chercher l'île après l'arrivée.",
          "Nous avons associé l'île à une image.",
          "Hier soir, mon frère a vérifié l'île sur internet.",
          "Pendant les vacances, nous utilisions souvent l'île.",
          "Elle a oublié le mot île pendant l'exercice.",
          "Il va utiliser île dans sa phrase.",
          "Nous avons trouvé l'île dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser île.",
          "L'élève a ajouté île dans sa réponse.",
          "J'ai compris le mot île pour la première fois.",
          "Ma sœur a choisi l'île pour son exemple.",
          "Ils ont répété île à voix haute.",
          "Nous allons revoir l'île avec le professeur.",
          "Elle a noté île pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'île.",
          "Après la leçon, j'ai utilisé le mot île dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'île.",
          "Quand je lis le texte, je cherche le sens de île.",
          "Ce matin, nous avons associé l'île à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec île.",
          "Le professeur a demandé un exemple avec l'île.",
          "J'ai choisi l'île parce que ce mot était dans la liste.",
          "Nous allons réviser l'île avant l'évaluation.",
          "Mon camarade a expliqué l'île avec ses mots.",
          "J'ai ajouté île dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'île semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'île se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais île, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà île, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'île.",
          "La leçon que nous travaillons utilise île dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'île, les élèves prenaient des notes.",
          "Puisque l'île aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé île, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'île aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, île peut donner une information précise.",
          "Le mot dont je parle est île, que la classe doit retenir.",
          "Tant que tu pratiqueras île, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'île demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient île, je penserai au vocabulaire du déplacement.",
          "Bien que le mot île paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'île apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'île, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà île, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'île.",
          "Lorsque j'aurai mémorisé île, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'île.",
          "Puisque île est utile, je le révise régulièrement.",
        ],
      } },
    { word: "nature", image: "nature.webp",   article: "la",  gender: "f", definition: "l'ensemble du monde naturel" , exampleSentences: {
        a1: [
          "Je vois la nature.",
          "Je cherche la nature.",
          "La nature est importante.",
          "Je note nature.",
          "Tu connais la nature.",
          "Il utilise la nature.",
          "Elle regarde la nature.",
          "Nous trouvons la nature.",
          "Vous demandez la nature.",
          "Ils parlent de la nature.",
          "Elles choisissent la nature.",
          "La nature est sur le plan.",
          "Le voyageur cherche la nature.",
          "Je répète nature.",
          "Il montre la nature.",
          "Elle prépare son voyage.",
          "La ville contient la nature.",
          "La carte indique la nature.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons nature.",
          "Tu apprends nature.",
          "La classe regarde la nature.",
          "Je montre la nature au professeur.",
          "Cette leçon parle de la nature.",
          "Aujourd'hui, je vois la nature.",
          "Dans mon cahier, j'écris nature.",
          "Le mot nature est nouveau pour moi.",
          "Je répète nature à voix haute.",
          "Nous dessinons la nature.",
          "Il y a une nature dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la nature sur le plan.",
          "Demain, je vais chercher la nature.",
          "Quand je voyage, j'utilise souvent la nature.",
          "Ce matin, le guide a montré la nature.",
          "Nous avons demandé où se trouvait la nature.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la nature parce que c'était pratique.",
          "Elle a noté nature dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la nature.",
          "Le groupe a trouvé la nature près de la gare.",
          "Je vais chercher la nature après l'arrivée.",
          "Nous avons associé la nature à une image.",
          "Hier soir, mon frère a vérifié la nature sur internet.",
          "Pendant les vacances, nous utilisions souvent la nature.",
          "Elle a oublié le mot nature pendant l'exercice.",
          "Il va utiliser nature dans sa phrase.",
          "Nous avons trouvé la nature dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser nature.",
          "L'élève a ajouté nature dans sa réponse.",
          "J'ai compris le mot nature pour la première fois.",
          "Ma sœur a choisi la nature pour son exemple.",
          "Ils ont répété nature à voix haute.",
          "Nous allons revoir la nature avec le professeur.",
          "Elle a noté nature pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la nature.",
          "Après la leçon, j'ai utilisé le mot nature dans une phrase.",
          "Demain, je vais apprendre à mieux employer la nature.",
          "Quand je lis le texte, je cherche le sens de nature.",
          "Ce matin, nous avons associé la nature à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec nature.",
          "Le professeur a demandé un exemple avec la nature.",
          "J'ai choisi la nature parce que ce mot était dans la liste.",
          "Nous allons réviser la nature avant l'évaluation.",
          "Mon camarade a expliqué la nature avec ses mots.",
          "J'ai ajouté nature dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la nature semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la nature se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais nature, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà nature, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la nature.",
          "La leçon que nous travaillons utilise nature dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la nature, les élèves prenaient des notes.",
          "Puisque la nature aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé nature, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la nature aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, nature peut donner une information précise.",
          "Le mot dont je parle est nature, que la classe doit retenir.",
          "Tant que tu pratiqueras nature, tu comprendras mieux les dialogues de voyage.",
          "Bien que la nature demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient nature, je penserai au vocabulaire du déplacement.",
          "Bien que le mot nature paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la nature apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la nature, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà nature, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la nature.",
          "Lorsque j'aurai mémorisé nature, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la nature.",
          "Puisque nature est utile, je le révise régulièrement.",
        ],
      } },
    { word: "paysage", image: "paysage.webp",  article: "le",  gender: "m", definition: "vue d'ensemble d'un lieu naturel" , exampleSentences: {
        a1: [
          "Je vois le paysage.",
          "Je cherche le paysage.",
          "Le paysage est important.",
          "Je note paysage.",
          "Tu connais le paysage.",
          "Il utilise le paysage.",
          "Elle regarde le paysage.",
          "Nous trouvons le paysage.",
          "Vous demandez le paysage.",
          "Ils parlent du paysage.",
          "Elles choisissent le paysage.",
          "Le paysage est sur le plan.",
          "Le voyageur cherche le paysage.",
          "Je répète paysage.",
          "Il montre le paysage.",
          "Elle prépare son voyage.",
          "La ville contient le paysage.",
          "La carte indique le paysage.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons paysage.",
          "Tu apprends paysage.",
          "La classe regarde le paysage.",
          "Je montre le paysage au professeur.",
          "Cette leçon parle du paysage.",
          "Aujourd'hui, je vois le paysage.",
          "Dans mon cahier, j'écris paysage.",
          "Le mot paysage est nouveau pour moi.",
          "Je répète paysage à voix haute.",
          "Nous dessinons le paysage.",
          "Il y a un paysage dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché le paysage sur le plan.",
          "Demain, je vais chercher le paysage.",
          "Quand je voyage, j'utilise souvent le paysage.",
          "Ce matin, le guide a montré le paysage.",
          "Nous avons demandé où se trouvait le paysage.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le paysage parce que c'était pratique.",
          "Elle a noté paysage dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du paysage.",
          "Le groupe a trouvé le paysage près de la gare.",
          "Je vais chercher le paysage après l'arrivée.",
          "Nous avons associé le paysage à une image.",
          "Hier soir, mon frère a vérifié le paysage sur internet.",
          "Pendant les vacances, nous utilisions souvent le paysage.",
          "Elle a oublié le mot paysage pendant l'exercice.",
          "Il va utiliser paysage dans sa phrase.",
          "Nous avons trouvé le paysage dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser paysage.",
          "L'élève a ajouté paysage dans sa réponse.",
          "J'ai compris le mot paysage pour la première fois.",
          "Ma sœur a choisi le paysage pour son exemple.",
          "Ils ont répété paysage à voix haute.",
          "Nous allons revoir le paysage avec le professeur.",
          "Elle a noté paysage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le paysage.",
          "Après la leçon, j'ai utilisé le mot paysage dans une phrase.",
          "Demain, je vais apprendre à mieux employer le paysage.",
          "Quand je lis le texte, je cherche le sens de paysage.",
          "Ce matin, nous avons associé le paysage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec paysage.",
          "Le professeur a demandé un exemple avec le paysage.",
          "J'ai choisi le paysage parce que ce mot était dans la liste.",
          "Nous allons réviser le paysage avant l'évaluation.",
          "Mon camarade a expliqué le paysage avec ses mots.",
          "J'ai ajouté paysage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le paysage semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le paysage se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais paysage, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà paysage, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le paysage.",
          "La leçon que nous travaillons utilise paysage dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le paysage, les élèves prenaient des notes.",
          "Puisque le paysage aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé paysage, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le paysage aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, paysage peut donner une information précise.",
          "Le mot dont je parle est paysage, que la classe doit retenir.",
          "Tant que tu pratiqueras paysage, tu comprendras mieux les dialogues de voyage.",
          "Bien que le paysage demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient paysage, je penserai au vocabulaire du déplacement.",
          "Bien que le mot paysage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le paysage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le paysage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà paysage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le paysage.",
          "Lorsque j'aurai mémorisé paysage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le paysage.",
          "Puisque paysage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "côte", image: "cote.webp",     article: "la",  gender: "f", definition: "zone littorale entre terre et mer" , exampleSentences: {
        a1: [
          "Je vois la côte.",
          "Je cherche la côte.",
          "La côte est importante.",
          "Je note côte.",
          "Tu connais la côte.",
          "Il utilise la côte.",
          "Elle regarde la côte.",
          "Nous trouvons la côte.",
          "Vous demandez la côte.",
          "Ils parlent de la côte.",
          "Elles choisissent la côte.",
          "La côte est sur le plan.",
          "Le voyageur cherche la côte.",
          "Je répète côte.",
          "Il montre la côte.",
          "Elle prépare son voyage.",
          "La ville contient la côte.",
          "La carte indique la côte.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons côte.",
          "Tu apprends côte.",
          "La classe regarde la côte.",
          "Je montre la côte au professeur.",
          "Cette leçon parle de la côte.",
          "Aujourd'hui, je vois la côte.",
          "Dans mon cahier, j'écris côte.",
          "Le mot côte est nouveau pour moi.",
          "Je répète côte à voix haute.",
          "Nous dessinons la côte.",
          "Il y a une côte dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché la côte sur le plan.",
          "Demain, je vais chercher la côte.",
          "Quand je voyage, j'utilise souvent la côte.",
          "Ce matin, le guide a montré la côte.",
          "Nous avons demandé où se trouvait la côte.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la côte parce que c'était pratique.",
          "Elle a noté côte dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la côte.",
          "Le groupe a trouvé la côte près de la gare.",
          "Je vais chercher la côte après l'arrivée.",
          "Nous avons associé la côte à une image.",
          "Hier soir, mon frère a vérifié la côte sur internet.",
          "Pendant les vacances, nous utilisions souvent la côte.",
          "Elle a oublié le mot côte pendant l'exercice.",
          "Il va utiliser côte dans sa phrase.",
          "Nous avons trouvé la côte dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser côte.",
          "L'élève a ajouté côte dans sa réponse.",
          "J'ai compris le mot côte pour la première fois.",
          "Ma sœur a choisi la côte pour son exemple.",
          "Ils ont répété côte à voix haute.",
          "Nous allons revoir la côte avec le professeur.",
          "Elle a noté côte pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la côte.",
          "Après la leçon, j'ai utilisé le mot côte dans une phrase.",
          "Demain, je vais apprendre à mieux employer la côte.",
          "Quand je lis le texte, je cherche le sens de côte.",
          "Ce matin, nous avons associé la côte à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec côte.",
          "Le professeur a demandé un exemple avec la côte.",
          "J'ai choisi la côte parce que ce mot était dans la liste.",
          "Nous allons réviser la côte avant l'évaluation.",
          "Mon camarade a expliqué la côte avec ses mots.",
          "J'ai ajouté côte dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la côte semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la côte se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais côte, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà côte, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la côte.",
          "La leçon que nous travaillons utilise côte dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la côte, les élèves prenaient des notes.",
          "Puisque la côte aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé côte, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la côte aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, côte peut donner une information précise.",
          "Le mot dont je parle est côte, que la classe doit retenir.",
          "Tant que tu pratiqueras côte, tu comprendras mieux les dialogues de voyage.",
          "Bien que la côte demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient côte, je penserai au vocabulaire du déplacement.",
          "Bien que le mot côte paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la côte apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la côte, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà côte, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la côte.",
          "Lorsque j'aurai mémorisé côte, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la côte.",
          "Puisque côte est utile, je le révise régulièrement.",
        ],
      } },
    { word: "volcan", image: "volcan.webp",   article: "le",  gender: "m", definition: "montagne qui peut cracher de la lave" , exampleSentences: {
        a1: [
          "Je vois le volcan.",
          "Je cherche le volcan.",
          "Le volcan est important.",
          "Je note volcan.",
          "Tu connais le volcan.",
          "Il utilise le volcan.",
          "Elle regarde le volcan.",
          "Nous trouvons le volcan.",
          "Vous demandez le volcan.",
          "Ils parlent du volcan.",
          "Elles choisissent le volcan.",
          "Le volcan est sur le plan.",
          "Le voyageur cherche le volcan.",
          "Je répète volcan.",
          "Il montre le volcan.",
          "Elle prépare son voyage.",
          "La ville contient le volcan.",
          "La carte indique le volcan.",
          "Ce lieu est facile à trouver.",
          "Nous écrivons volcan.",
          "Tu apprends volcan.",
          "La classe regarde le volcan.",
          "Je montre le volcan au professeur.",
          "Cette leçon parle du volcan.",
          "Aujourd'hui, je vois le volcan.",
          "Dans mon cahier, j'écris volcan.",
          "Le mot volcan est nouveau pour moi.",
          "Je répète volcan à voix haute.",
          "Nous dessinons le volcan.",
          "Il y a un volcan dans l'image.",
        ],
        a2: [
          "Hier, j'ai cherché le volcan sur le plan.",
          "Demain, je vais chercher le volcan.",
          "Quand je voyage, j'utilise souvent le volcan.",
          "Ce matin, le guide a montré le volcan.",
          "Nous avons demandé où se trouvait le volcan.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le volcan parce que c'était pratique.",
          "Elle a noté volcan dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du volcan.",
          "Le groupe a trouvé le volcan près de la gare.",
          "Je vais chercher le volcan après l'arrivée.",
          "Nous avons associé le volcan à une image.",
          "Hier soir, mon frère a vérifié le volcan sur internet.",
          "Pendant les vacances, nous utilisions souvent le volcan.",
          "Elle a oublié le mot volcan pendant l'exercice.",
          "Il va utiliser volcan dans sa phrase.",
          "Nous avons trouvé le volcan dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser volcan.",
          "L'élève a ajouté volcan dans sa réponse.",
          "J'ai compris le mot volcan pour la première fois.",
          "Ma sœur a choisi le volcan pour son exemple.",
          "Ils ont répété volcan à voix haute.",
          "Nous allons revoir le volcan avec le professeur.",
          "Elle a noté volcan pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le volcan.",
          "Après la leçon, j'ai utilisé le mot volcan dans une phrase.",
          "Demain, je vais apprendre à mieux employer le volcan.",
          "Quand je lis le texte, je cherche le sens de volcan.",
          "Ce matin, nous avons associé le volcan à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec volcan.",
          "Le professeur a demandé un exemple avec le volcan.",
          "J'ai choisi le volcan parce que ce mot était dans la liste.",
          "Nous allons réviser le volcan avant l'évaluation.",
          "Mon camarade a expliqué le volcan avec ses mots.",
          "J'ai ajouté volcan dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le volcan semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le volcan se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais volcan, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà volcan, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le volcan.",
          "La leçon que nous travaillons utilise volcan dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le volcan, les élèves prenaient des notes.",
          "Puisque le volcan aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé volcan, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le volcan aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, volcan peut donner une information précise.",
          "Le mot dont je parle est volcan, que la classe doit retenir.",
          "Tant que tu pratiqueras volcan, tu comprendras mieux les dialogues de voyage.",
          "Bien que le volcan demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient volcan, je penserai au vocabulaire du déplacement.",
          "Bien que le mot volcan paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le volcan apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le volcan, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà volcan, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le volcan.",
          "Lorsque j'aurai mémorisé volcan, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le volcan.",
          "Puisque volcan est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Ils passent les vacances à la ___ pour nager.",         answer: "mer" },
    { sentence: "La ___ est couverte de pins et de chênes.",             answer: "forêt" },
    { sentence: "Le ___ du Léman est très grand et calme.",              answer: "lac" },
    { sentence: "On voit des sapins tout le long de cette ___.",         answer: "vallée" },
    { sentence: "L'___ est entourée d'eau de tous côtés.",               answer: "île" },
  ],
};
