import type { VocabTheme } from "../../vocabulary-data";

export const V1_FAMILLE_THEME: VocabTheme = {
  slug: "v1-famille",
  code: "V1.3",
  title: "La famille",
  section: "V1",
  words: [
    { word: "père",        article: "le",  gender: "m", definition: "le parent masculin" },
    { word: "mère",        article: "la",  gender: "f", definition: "le parent féminin" },
    { word: "fils",        article: "le",  gender: "m", definition: "l'enfant masculin" },
    { word: "fille",       article: "la",  gender: "f", definition: "l'enfant féminin" },
    { word: "frère",       article: "le",  gender: "m", definition: "le fils des mêmes parents" },
    { word: "sœur",        article: "la",  gender: "f", definition: "la fille des mêmes parents" },
    { word: "grand-père",  article: "le",  gender: "m", definition: "le père du père ou de la mère" },
    { word: "grand-mère",  article: "la",  gender: "f", definition: "la mère du père ou de la mère" },
    { word: "petit-fils",  article: "le",  gender: "m", definition: "le fils du fils ou de la fille" },
    { word: "petite-fille", article: "la", gender: "f", definition: "la fille du fils ou de la fille" },
    { word: "oncle",       article: "l'",  gender: "m", definition: "le frère du père ou de la mère" },
    { word: "tante",       article: "la",  gender: "f", definition: "la sœur du père ou de la mère" },
    { word: "cousin",      article: "le",  gender: "m", definition: "le fils de l'oncle ou de la tante" },
    { word: "cousine",     article: "la",  gender: "f", definition: "la fille de l'oncle ou de la tante" },
    { word: "neveu",       article: "le",  gender: "m", definition: "le fils du frère ou de la sœur" },
    { word: "nièce",       article: "la",  gender: "f", definition: "la fille du frère ou de la sœur" },
  ],
  sentences: [
    { sentence: "Mon ___ travaille dur pour notre famille.", answer: "père" },
    { sentence: "Mon ___ rentre à la maison le soir.", answer: "père" },
    { sentence: "Le ___ de mon ami est médecin.", answer: "père" },
    { sentence: "Mon ___ m'apprend à conduire.", answer: "père" },
    { sentence: "Mon ___ et moi regardons le football ensemble.", answer: "père" },
    { sentence: "Le ___ de Lucas est très grand.", answer: "père" },
    { sentence: "Ma ___ me prépare de bons repas.", answer: "mère" },
    { sentence: "Ma ___ travaille à l'hôpital.", answer: "mère" },
    { sentence: "La ___ de Marie est professeure.", answer: "mère" },
    { sentence: "Ma ___ m'aide toujours quand j'ai des problèmes.", answer: "mère" },
    { sentence: "Ma ___ prépare le dîner tous les soirs.", answer: "mère" },
    { sentence: "La ___ de mon ami est très sympa.", answer: "mère" },
    { sentence: "Le ___ de ma sœur s'appelle Thomas.", answer: "fils" },
    { sentence: "Leur ___ a cinq ans.", answer: "fils" },
    { sentence: "Le ___ aîné part à l'université.", answer: "fils" },
    { sentence: "Il a un ___ qui joue au football.", answer: "fils" },
    { sentence: "Son ___ lui ressemble beaucoup.", answer: "fils" },
    { sentence: "Leur ___ a les yeux bleus.", answer: "fils" },
    { sentence: "Ma ___ est plus jeune que moi d'un an.", answer: "fille" },
    { sentence: "Leur ___ fait de la danse.", answer: "fille" },
    { sentence: "La ___ de mes voisins chante très bien.", answer: "fille" },
    { sentence: "Sa ___ a obtenu son diplôme cette année.", answer: "fille" },
    { sentence: "Leur ___ a les cheveux longs.", answer: "fille" },
    { sentence: "Mon ___ et moi allons à la même école.", answer: "frère" },
    { sentence: "Mon ___ est plus grand que moi.", answer: "frère" },
    { sentence: "Le ___ de Paul joue de la guitare.", answer: "frère" },
    { sentence: "Mon ___ m'aide toujours avec mes devoirs.", answer: "frère" },
    { sentence: "Son ___ habite à Paris.", answer: "frère" },
    { sentence: "Mon ___ est né deux ans après moi.", answer: "frère" },
    { sentence: "Ma ___ est très gentille.", answer: "sœur" },
    { sentence: "La ___ de Léa est médecin.", answer: "sœur" },
    { sentence: "Ma ___ me prête ses vêtements.", answer: "sœur" },
    { sentence: "Ma ___ chante dans une chorale.", answer: "sœur" },
    { sentence: "Sa ___ vit en Espagne.", answer: "sœur" },
    { sentence: "Mon ___ est le père de mon père.", answer: "grand-père" },
    { sentence: "Mon ___ aime raconter des histoires.", answer: "grand-père" },
    { sentence: "Mon ___ a quatre-vingts ans.", answer: "grand-père" },
    { sentence: "Le ___ de Lucie est très actif.", answer: "grand-père" },
    { sentence: "Mon ___ m'emmène à la pêche le dimanche.", answer: "grand-père" },
    { sentence: "Mon ___ a travaillé toute sa vie.", answer: "grand-père" },
    { sentence: "Ma ___ fait de bons gâteaux.", answer: "grand-mère" },
    { sentence: "La ___ de Pierre est encore très active.", answer: "grand-mère" },
    { sentence: "Ma ___ me tricote des pulls chaque hiver.", answer: "grand-mère" },
    { sentence: "Ma ___ habite à la campagne.", answer: "grand-mère" },
    { sentence: "La ___ de Clara a soixante-quinze ans.", answer: "grand-mère" },
    { sentence: "Mon ___ est le fils de mon fils.", answer: "petit-fils" },
    { sentence: "Leur ___ a deux ans.", answer: "petit-fils" },
    { sentence: "Son ___ lui ressemble beaucoup.", answer: "petit-fils" },
    { sentence: "Le ___ de la voisine est adorable.", answer: "petit-fils" },
    { sentence: "Leur ___ vient les voir chaque week-end.", answer: "petit-fils" },
    { sentence: "Ma ___ est la fille de ma fille.", answer: "petite-fille" },
    { sentence: "Leur ___ a trois ans.", answer: "petite-fille" },
    { sentence: "La ___ de Monsieur Dupont fait ses premiers pas.", answer: "petite-fille" },
    { sentence: "Sa ___ lui ressemble beaucoup.", answer: "petite-fille" },
    { sentence: "Leur ___ vient les voir tous les dimanches.", answer: "petite-fille" },
    { sentence: "Mon ___ est le frère de mon père.", answer: "oncle" },
    { sentence: "Mon ___ habite à Lyon.", answer: "oncle" },
    { sentence: "Son ___ lui offre toujours de beaux cadeaux.", answer: "oncle" },
    { sentence: "L'___ de Léa est très drôle.", answer: "oncle" },
    { sentence: "Mon ___ est ingénieur.", answer: "oncle" },
    { sentence: "Ma ___ est la sœur de ma mère.", answer: "tante" },
    { sentence: "Ma ___ m'invite souvent à dîner.", answer: "tante" },
    { sentence: "La ___ de Paul vit en Italie.", answer: "tante" },
    { sentence: "Ma ___ me donne toujours de bons conseils.", answer: "tante" },
    { sentence: "Son ___ est arrivée hier.", answer: "tante" },
    { sentence: "Mon ___ joue avec moi depuis notre enfance.", answer: "cousin" },
    { sentence: "Mon ___ est le fils de mon oncle.", answer: "cousin" },
    { sentence: "Mon ___ habite dans la même ville que moi.", answer: "cousin" },
    { sentence: "Le ___ de Marie a obtenu son permis de conduire.", answer: "cousin" },
    { sentence: "Mon ___ et moi nous voyons chaque été.", answer: "cousin" },
    { sentence: "Ma ___ est la fille de ma tante.", answer: "cousine" },
    { sentence: "La ___ de Max est très grande maintenant.", answer: "cousine" },
    { sentence: "Ma ___ m'a appelée hier soir.", answer: "cousine" },
    { sentence: "Sa ___ vit en Belgique.", answer: "cousine" },
    { sentence: "Ma ___ et moi jouons ensemble depuis l'enfance.", answer: "cousine" },
    { sentence: "Mon ___ est le fils de mon frère.", answer: "neveu" },
    { sentence: "Mon ___ a trois ans et il est adorable.", answer: "neveu" },
    { sentence: "Son ___ vient la voir chaque dimanche.", answer: "neveu" },
    { sentence: "Le ___ de Julie est très espiègle.", answer: "neveu" },
    { sentence: "Mon ___ ressemble à son père.", answer: "neveu" },
    { sentence: "La ___ de mon frère a cinq ans.", answer: "nièce" },
    { sentence: "Ma ___ est la fille de ma sœur.", answer: "nièce" },
    { sentence: "Sa ___ vient lui rendre visite.", answer: "nièce" },
    { sentence: "La ___ de Paul adore les animaux.", answer: "nièce" },
    { sentence: "Ma ___ apprend à lire cette année.", answer: "nièce" },
  ],
};
