import type { VocabTheme } from "../../vocabulary-data";

export const V9_HOTEL_THEME: VocabTheme = {
  slug: "v9-hotel",
  code: "V9.7",
  title: "L'hôtel",
  section: "V9",
  words: [
    { word: "réception", image: "reception.webp",       article: "la",  gender: "f", definition: ["Accueil d’un hôtel où l’on demande une chambre ou des informations."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la réception sur le plan.",
          "Demain, je vais chercher la réception.",
          "Quand je voyage, j'utilise souvent la réception.",
          "Ce matin, le guide a montré la réception.",
          "Nous avons demandé où se trouvait la réception.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la réception parce que c'était pratique.",
          "Elle a noté réception dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la réception.",
          "Le groupe a trouvé la réception près de la gare.",
          "Je vais chercher la réception après l'arrivée.",
          "Nous avons associé la réception à une image.",
          "Hier soir, mon frère a vérifié la réception sur internet.",
          "Pendant les vacances, nous utilisions souvent la réception.",
          "Elle a oublié le mot réception pendant l'exercice.",
          "Il va utiliser réception dans sa phrase.",
          "Nous avons trouvé la réception dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser réception.",
          "L'élève a ajouté réception dans sa réponse.",
          "J'ai compris le mot réception pour la première fois.",
          "Ma sœur a choisi la réception pour son exemple.",
          "Ils ont répété réception à voix haute.",
          "Nous allons revoir la réception avec le professeur.",
          "Elle a noté réception pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la réception.",
          "Après la leçon, j'ai utilisé le mot réception dans une phrase.",
          "Demain, je vais apprendre à mieux employer la réception.",
          "Quand je lis le texte, je cherche le sens de réception.",
          "Ce matin, nous avons associé la réception à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec réception.",
          "Le professeur a demandé un exemple avec la réception.",
          "J'ai choisi la réception parce que ce mot était dans la liste.",
          "Nous allons réviser la réception avant l'évaluation.",
          "Mon camarade a expliqué la réception avec ses mots.",
          "J'ai ajouté réception dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la réception semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la réception se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais réception, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà réception, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la réception.",
          "La leçon que nous travaillons utilise réception dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la réception, les élèves prenaient des notes.",
          "Puisque la réception aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé réception, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la réception aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, réception peut donner une information précise.",
          "Le mot dont je parle est réception, que la classe doit retenir.",
          "Tant que tu pratiqueras réception, tu comprendras mieux les dialogues de voyage.",
          "Bien que la réception demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient réception, je penserai au vocabulaire du déplacement.",
          "Bien que le mot réception paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la réception apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la réception, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà réception, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la réception.",
          "Lorsque j'aurai mémorisé réception, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la réception.",
          "Puisque réception est utile, je le révise régulièrement.",
        ],
      } },
    { word: "clé", image: "cle.webp",             article: "la",  gender: "f", definition: ["Objet ou carte qui sert à ouvrir une porte."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la clé sur le plan.",
          "Demain, je vais chercher la clé.",
          "Quand je voyage, j'utilise souvent la clé.",
          "Ce matin, le guide a montré la clé.",
          "Nous avons demandé où se trouvait la clé.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la clé parce que c'était pratique.",
          "Elle a noté clé dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la clé.",
          "Le groupe a trouvé la clé près de la gare.",
          "Je vais chercher la clé après l'arrivée.",
          "Nous avons associé la clé à une image.",
          "Hier soir, mon frère a vérifié la clé sur internet.",
          "Pendant les vacances, nous utilisions souvent la clé.",
          "Elle a oublié le mot clé pendant l'exercice.",
          "Il va utiliser clé dans sa phrase.",
          "Nous avons trouvé la clé dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser clé.",
          "L'élève a ajouté clé dans sa réponse.",
          "J'ai compris le mot clé pour la première fois.",
          "Ma sœur a choisi la clé pour son exemple.",
          "Ils ont répété clé à voix haute.",
          "Nous allons revoir la clé avec le professeur.",
          "Elle a noté clé pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la clé.",
          "Après la leçon, j'ai utilisé le mot clé dans une phrase.",
          "Demain, je vais apprendre à mieux employer la clé.",
          "Quand je lis le texte, je cherche le sens de clé.",
          "Ce matin, nous avons associé la clé à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec clé.",
          "Le professeur a demandé un exemple avec la clé.",
          "J'ai choisi la clé parce que ce mot était dans la liste.",
          "Nous allons réviser la clé avant l'évaluation.",
          "Mon camarade a expliqué la clé avec ses mots.",
          "J'ai ajouté clé dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la clé semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la clé se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais clé, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà clé, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la clé.",
          "La leçon que nous travaillons utilise clé dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la clé, les élèves prenaient des notes.",
          "Puisque la clé aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé clé, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la clé aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, clé peut donner une information précise.",
          "Le mot dont je parle est clé, que la classe doit retenir.",
          "Tant que tu pratiqueras clé, tu comprendras mieux les dialogues de voyage.",
          "Bien que la clé demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient clé, je penserai au vocabulaire du déplacement.",
          "Bien que le mot clé paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la clé apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la clé, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà clé, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la clé.",
          "Lorsque j'aurai mémorisé clé, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la clé.",
          "Puisque clé est utile, je le révise régulièrement.",
        ],
      } },
    { word: "chambre", image: "/vocab/images/V4/chambre.webp",         article: "la",  gender: "f", definition: ["Pièce où l’on dort dans un hôtel."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la chambre sur le plan.",
          "Demain, je vais chercher la chambre.",
          "Quand je voyage, j'utilise souvent la chambre.",
          "Ce matin, le guide a montré la chambre.",
          "Nous avons demandé où se trouvait la chambre.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la chambre parce que c'était pratique.",
          "Elle a noté chambre dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la chambre.",
          "Le groupe a trouvé la chambre près de la gare.",
          "Je vais chercher la chambre après l'arrivée.",
          "Nous avons associé la chambre à une image.",
          "Hier soir, mon frère a vérifié la chambre sur internet.",
          "Pendant les vacances, nous utilisions souvent la chambre.",
          "Elle a oublié le mot chambre pendant l'exercice.",
          "Il va utiliser chambre dans sa phrase.",
          "Nous avons trouvé la chambre dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser chambre.",
          "L'élève a ajouté chambre dans sa réponse.",
          "J'ai compris le mot chambre pour la première fois.",
          "Ma sœur a choisi la chambre pour son exemple.",
          "Ils ont répété chambre à voix haute.",
          "Nous allons revoir la chambre avec le professeur.",
          "Elle a noté chambre pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la chambre.",
          "Après la leçon, j'ai utilisé le mot chambre dans une phrase.",
          "Demain, je vais apprendre à mieux employer la chambre.",
          "Quand je lis le texte, je cherche le sens de chambre.",
          "Ce matin, nous avons associé la chambre à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec chambre.",
          "Le professeur a demandé un exemple avec la chambre.",
          "J'ai choisi la chambre parce que ce mot était dans la liste.",
          "Nous allons réviser la chambre avant l'évaluation.",
          "Mon camarade a expliqué la chambre avec ses mots.",
          "J'ai ajouté chambre dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la chambre semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la chambre se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais chambre, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà chambre, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la chambre.",
          "La leçon que nous travaillons utilise chambre dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la chambre, les élèves prenaient des notes.",
          "Puisque la chambre aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé chambre, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la chambre aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, chambre peut donner une information précise.",
          "Le mot dont je parle est chambre, que la classe doit retenir.",
          "Tant que tu pratiqueras chambre, tu comprendras mieux les dialogues de voyage.",
          "Bien que la chambre demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient chambre, je penserai au vocabulaire du déplacement.",
          "Bien que le mot chambre paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la chambre apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la chambre, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chambre, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la chambre.",
          "Lorsque j'aurai mémorisé chambre, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la chambre.",
          "Puisque chambre est utile, je le révise régulièrement.",
        ],
      } },
    { word: "chambre double", image: "chambre-double.webp",  article: "la",  gender: "f", definition: ["Chambre pour deux personnes, souvent avec un grand lit ou deux lits."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la chambre double sur le plan.",
          "Demain, je vais chercher la chambre double.",
          "Quand je voyage, j'utilise souvent la chambre double.",
          "Ce matin, le guide a montré la chambre double.",
          "Nous avons demandé où se trouvait la chambre double.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la chambre double parce que c'était pratique.",
          "Elle a noté chambre double dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la chambre double.",
          "Le groupe a trouvé la chambre double près de la gare.",
          "Je vais chercher la chambre double après l'arrivée.",
          "Nous avons associé la chambre double à une image.",
          "Hier soir, mon frère a vérifié la chambre double sur internet.",
          "Pendant les vacances, nous utilisions souvent la chambre double.",
          "Elle a oublié le mot chambre double pendant l'exercice.",
          "Il va utiliser chambre double dans sa phrase.",
          "Nous avons trouvé la chambre double dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser chambre double.",
          "L'élève a ajouté chambre double dans sa réponse.",
          "J'ai compris le mot chambre double pour la première fois.",
          "Ma sœur a choisi la chambre double pour son exemple.",
          "Ils ont répété chambre double à voix haute.",
          "Nous allons revoir la chambre double avec le professeur.",
          "Elle a noté chambre double pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la chambre double.",
          "Après la leçon, j'ai utilisé le mot chambre double dans une phrase.",
          "Demain, je vais apprendre à mieux employer la chambre double.",
          "Quand je lis le texte, je cherche le sens de chambre double.",
          "Ce matin, nous avons associé la chambre double à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec chambre double.",
          "Le professeur a demandé un exemple avec la chambre double.",
          "J'ai choisi la chambre double parce que ce mot était dans la liste.",
          "Nous allons réviser la chambre double avant l'évaluation.",
          "Mon camarade a expliqué la chambre double avec ses mots.",
          "J'ai ajouté chambre double dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la chambre double semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la chambre double se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais chambre double, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà chambre double, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la chambre double.",
          "La leçon que nous travaillons utilise chambre double dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la chambre double, les élèves prenaient des notes.",
          "Puisque la chambre double aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé chambre double, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la chambre double aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, chambre double peut donner une information précise.",
          "Le mot dont je parle est chambre double, que la classe doit retenir.",
          "Tant que tu pratiqueras chambre double, tu comprendras mieux les dialogues de voyage.",
          "Bien que la chambre double demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient chambre double, je penserai au vocabulaire du déplacement.",
          "Bien que le mot chambre double paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la chambre double apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la chambre double, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chambre double, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la chambre double.",
          "Lorsque j'aurai mémorisé chambre double, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la chambre double.",
          "Puisque chambre double est utile, je le révise régulièrement.",
        ],
      } },
    { word: "chambre simple", image: "chambre-simple.webp",  article: "la",  gender: "f", definition: ["Chambre pour une seule personne."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la chambre simple sur le plan.",
          "Demain, je vais chercher la chambre simple.",
          "Quand je voyage, j'utilise souvent la chambre simple.",
          "Ce matin, le guide a montré la chambre simple.",
          "Nous avons demandé où se trouvait la chambre simple.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la chambre simple parce que c'était pratique.",
          "Elle a noté chambre simple dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la chambre simple.",
          "Le groupe a trouvé la chambre simple près de la gare.",
          "Je vais chercher la chambre simple après l'arrivée.",
          "Nous avons associé la chambre simple à une image.",
          "Hier soir, mon frère a vérifié la chambre simple sur internet.",
          "Pendant les vacances, nous utilisions souvent la chambre simple.",
          "Elle a oublié le mot chambre simple pendant l'exercice.",
          "Il va utiliser chambre simple dans sa phrase.",
          "Nous avons trouvé la chambre simple dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser chambre simple.",
          "L'élève a ajouté chambre simple dans sa réponse.",
          "J'ai compris le mot chambre simple pour la première fois.",
          "Ma sœur a choisi la chambre simple pour son exemple.",
          "Ils ont répété chambre simple à voix haute.",
          "Nous allons revoir la chambre simple avec le professeur.",
          "Elle a noté chambre simple pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la chambre simple.",
          "Après la leçon, j'ai utilisé le mot chambre simple dans une phrase.",
          "Demain, je vais apprendre à mieux employer la chambre simple.",
          "Quand je lis le texte, je cherche le sens de chambre simple.",
          "Ce matin, nous avons associé la chambre simple à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec chambre simple.",
          "Le professeur a demandé un exemple avec la chambre simple.",
          "J'ai choisi la chambre simple parce que ce mot était dans la liste.",
          "Nous allons réviser la chambre simple avant l'évaluation.",
          "Mon camarade a expliqué la chambre simple avec ses mots.",
          "J'ai ajouté chambre simple dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la chambre simple semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la chambre simple se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais chambre simple, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà chambre simple, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la chambre simple.",
          "La leçon que nous travaillons utilise chambre simple dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la chambre simple, les élèves prenaient des notes.",
          "Puisque la chambre simple aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé chambre simple, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la chambre simple aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, chambre simple peut donner une information précise.",
          "Le mot dont je parle est chambre simple, que la classe doit retenir.",
          "Tant que tu pratiqueras chambre simple, tu comprendras mieux les dialogues de voyage.",
          "Bien que la chambre simple demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient chambre simple, je penserai au vocabulaire du déplacement.",
          "Bien que le mot chambre simple paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la chambre simple apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la chambre simple, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà chambre simple, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la chambre simple.",
          "Lorsque j'aurai mémorisé chambre simple, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la chambre simple.",
          "Puisque chambre simple est utile, je le révise régulièrement.",
        ],
      } },
    { word: "piscine", image: "piscine.webp",         article: "la",  gender: "f", definition: ["Bassin rempli d’eau où l’on nage."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la piscine sur le plan.",
          "Demain, je vais chercher la piscine.",
          "Quand je voyage, j'utilise souvent la piscine.",
          "Ce matin, le guide a montré la piscine.",
          "Nous avons demandé où se trouvait la piscine.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la piscine parce que c'était pratique.",
          "Elle a noté piscine dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la piscine.",
          "Le groupe a trouvé la piscine près de la gare.",
          "Je vais chercher la piscine après l'arrivée.",
          "Nous avons associé la piscine à une image.",
          "Hier soir, mon frère a vérifié la piscine sur internet.",
          "Pendant les vacances, nous utilisions souvent la piscine.",
          "Elle a oublié le mot piscine pendant l'exercice.",
          "Il va utiliser piscine dans sa phrase.",
          "Nous avons trouvé la piscine dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser piscine.",
          "L'élève a ajouté piscine dans sa réponse.",
          "J'ai compris le mot piscine pour la première fois.",
          "Ma sœur a choisi la piscine pour son exemple.",
          "Ils ont répété piscine à voix haute.",
          "Nous allons revoir la piscine avec le professeur.",
          "Elle a noté piscine pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la piscine.",
          "Après la leçon, j'ai utilisé le mot piscine dans une phrase.",
          "Demain, je vais apprendre à mieux employer la piscine.",
          "Quand je lis le texte, je cherche le sens de piscine.",
          "Ce matin, nous avons associé la piscine à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec piscine.",
          "Le professeur a demandé un exemple avec la piscine.",
          "J'ai choisi la piscine parce que ce mot était dans la liste.",
          "Nous allons réviser la piscine avant l'évaluation.",
          "Mon camarade a expliqué la piscine avec ses mots.",
          "J'ai ajouté piscine dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la piscine semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la piscine se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais piscine, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà piscine, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la piscine.",
          "La leçon que nous travaillons utilise piscine dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la piscine, les élèves prenaient des notes.",
          "Puisque la piscine aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé piscine, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la piscine aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, piscine peut donner une information précise.",
          "Le mot dont je parle est piscine, que la classe doit retenir.",
          "Tant que tu pratiqueras piscine, tu comprendras mieux les dialogues de voyage.",
          "Bien que la piscine demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient piscine, je penserai au vocabulaire du déplacement.",
          "Bien que le mot piscine paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la piscine apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la piscine, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà piscine, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la piscine.",
          "Lorsque j'aurai mémorisé piscine, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la piscine.",
          "Puisque piscine est utile, je le révise régulièrement.",
        ],
      } },
    { word: "petit-déjeuner", image: "petit-dejeuner.webp",  article: "le",  gender: "m", definition: ["Repas du matin."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le petit-déjeuner sur le plan.",
          "Demain, je vais chercher le petit-déjeuner.",
          "Quand je voyage, j'utilise souvent le petit-déjeuner.",
          "Ce matin, le guide a montré le petit-déjeuner.",
          "Nous avons demandé où se trouvait le petit-déjeuner.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le petit-déjeuner parce que c'était pratique.",
          "Elle a noté petit-déjeuner dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du petit-déjeuner.",
          "Le groupe a trouvé le petit-déjeuner près de la gare.",
          "Je vais chercher le petit-déjeuner après l'arrivée.",
          "Nous avons associé le petit-déjeuner à une image.",
          "Hier soir, mon frère a vérifié le petit-déjeuner sur internet.",
          "Pendant les vacances, nous utilisions souvent le petit-déjeuner.",
          "Elle a oublié le mot petit-déjeuner pendant l'exercice.",
          "Il va utiliser petit-déjeuner dans sa phrase.",
          "Nous avons trouvé le petit-déjeuner dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser petit-déjeuner.",
          "L'élève a ajouté petit-déjeuner dans sa réponse.",
          "J'ai compris le mot petit-déjeuner pour la première fois.",
          "Ma sœur a choisi le petit-déjeuner pour son exemple.",
          "Ils ont répété petit-déjeuner à voix haute.",
          "Nous allons revoir le petit-déjeuner avec le professeur.",
          "Elle a noté petit-déjeuner pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le petit-déjeuner.",
          "Après la leçon, j'ai utilisé le mot petit-déjeuner dans une phrase.",
          "Demain, je vais apprendre à mieux employer le petit-déjeuner.",
          "Quand je lis le texte, je cherche le sens de petit-déjeuner.",
          "Ce matin, nous avons associé le petit-déjeuner à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec petit-déjeuner.",
          "Le professeur a demandé un exemple avec le petit-déjeuner.",
          "J'ai choisi le petit-déjeuner parce que ce mot était dans la liste.",
          "Nous allons réviser le petit-déjeuner avant l'évaluation.",
          "Mon camarade a expliqué le petit-déjeuner avec ses mots.",
          "J'ai ajouté petit-déjeuner dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le petit-déjeuner semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le petit-déjeuner se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais petit-déjeuner, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà petit-déjeuner, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le petit-déjeuner.",
          "La leçon que nous travaillons utilise petit-déjeuner dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le petit-déjeuner, les élèves prenaient des notes.",
          "Puisque le petit-déjeuner aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé petit-déjeuner, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le petit-déjeuner aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, petit-déjeuner peut donner une information précise.",
          "Le mot dont je parle est petit-déjeuner, que la classe doit retenir.",
          "Tant que tu pratiqueras petit-déjeuner, tu comprendras mieux les dialogues de voyage.",
          "Bien que le petit-déjeuner demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient petit-déjeuner, je penserai au vocabulaire du déplacement.",
          "Bien que le mot petit-déjeuner paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le petit-déjeuner apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le petit-déjeuner, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà petit-déjeuner, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le petit-déjeuner.",
          "Lorsque j'aurai mémorisé petit-déjeuner, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le petit-déjeuner.",
          "Puisque petit-déjeuner est utile, je le révise régulièrement.",
        ],
      } },
    { word: "demi-pension", image: "demi-pension.webp",    article: "la",  gender: "f", definition: ["Formule avec la nuit, le petit-déjeuner et un autre repas."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la demi-pension sur le plan.",
          "Demain, je vais chercher la demi-pension.",
          "Quand je voyage, j'utilise souvent la demi-pension.",
          "Ce matin, le guide a montré la demi-pension.",
          "Nous avons demandé où se trouvait la demi-pension.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la demi-pension parce que c'était pratique.",
          "Elle a noté demi-pension dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la demi-pension.",
          "Le groupe a trouvé la demi-pension près de la gare.",
          "Je vais chercher la demi-pension après l'arrivée.",
          "Nous avons associé la demi-pension à une image.",
          "Hier soir, mon frère a vérifié la demi-pension sur internet.",
          "Pendant les vacances, nous utilisions souvent la demi-pension.",
          "Elle a oublié le mot demi-pension pendant l'exercice.",
          "Il va utiliser demi-pension dans sa phrase.",
          "Nous avons trouvé la demi-pension dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser demi-pension.",
          "L'élève a ajouté demi-pension dans sa réponse.",
          "J'ai compris le mot demi-pension pour la première fois.",
          "Ma sœur a choisi la demi-pension pour son exemple.",
          "Ils ont répété demi-pension à voix haute.",
          "Nous allons revoir la demi-pension avec le professeur.",
          "Elle a noté demi-pension pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la demi-pension.",
          "Après la leçon, j'ai utilisé le mot demi-pension dans une phrase.",
          "Demain, je vais apprendre à mieux employer la demi-pension.",
          "Quand je lis le texte, je cherche le sens de demi-pension.",
          "Ce matin, nous avons associé la demi-pension à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec demi-pension.",
          "Le professeur a demandé un exemple avec la demi-pension.",
          "J'ai choisi la demi-pension parce que ce mot était dans la liste.",
          "Nous allons réviser la demi-pension avant l'évaluation.",
          "Mon camarade a expliqué la demi-pension avec ses mots.",
          "J'ai ajouté demi-pension dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la demi-pension semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la demi-pension se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais demi-pension, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà demi-pension, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la demi-pension.",
          "La leçon que nous travaillons utilise demi-pension dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la demi-pension, les élèves prenaient des notes.",
          "Puisque la demi-pension aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé demi-pension, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la demi-pension aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, demi-pension peut donner une information précise.",
          "Le mot dont je parle est demi-pension, que la classe doit retenir.",
          "Tant que tu pratiqueras demi-pension, tu comprendras mieux les dialogues de voyage.",
          "Bien que la demi-pension demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient demi-pension, je penserai au vocabulaire du déplacement.",
          "Bien que le mot demi-pension paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la demi-pension apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la demi-pension, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà demi-pension, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la demi-pension.",
          "Lorsque j'aurai mémorisé demi-pension, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la demi-pension.",
          "Puisque demi-pension est utile, je le révise régulièrement.",
        ],
      } },
    { word: "réservation", image: "reservation.webp",     article: "la",  gender: "f", definition: ["Action de garder une place, une chambre ou un billet à l’avance."], definitionPivot: { en: "A word used for air travel.", ar: "كلمة تُستعمل في السفر بالطائرة.", fa: "واژه‌ای برای سفر با هواپیما.", pt: "Palavra usada em viagens de avião.", so: "Eray loo isticmaalo safarka diyaaradda.", ti: "ኣብ ጉዕዞ ነፋሪት ዝጥቀሙሉ ቃል።", tr: "Uçak yolculuğunda kullanılan kelime.", ps: "د الوتکې د سفر کلمه.", uk: "Слово для авіаподорожі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la réservation sur le plan.",
          "Demain, je vais chercher la réservation.",
          "Quand je voyage, j'utilise souvent la réservation.",
          "Ce matin, le guide a montré la réservation.",
          "Nous avons demandé où se trouvait la réservation.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la réservation parce que c'était pratique.",
          "Elle a noté réservation dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la réservation.",
          "Le groupe a trouvé la réservation près de la gare.",
          "Je vais chercher la réservation après l'arrivée.",
          "Nous avons associé la réservation à une image.",
          "Hier soir, mon frère a vérifié la réservation sur internet.",
          "Pendant les vacances, nous utilisions souvent la réservation.",
          "Elle a oublié le mot réservation pendant l'exercice.",
          "Il va utiliser réservation dans sa phrase.",
          "Nous avons trouvé la réservation dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser réservation.",
          "L'élève a ajouté réservation dans sa réponse.",
          "J'ai compris le mot réservation pour la première fois.",
          "Ma sœur a choisi la réservation pour son exemple.",
          "Ils ont répété réservation à voix haute.",
          "Nous allons revoir la réservation avec le professeur.",
          "Elle a noté réservation pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la réservation.",
          "Après la leçon, j'ai utilisé le mot réservation dans une phrase.",
          "Demain, je vais apprendre à mieux employer la réservation.",
          "Quand je lis le texte, je cherche le sens de réservation.",
          "Ce matin, nous avons associé la réservation à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec réservation.",
          "Le professeur a demandé un exemple avec la réservation.",
          "J'ai choisi la réservation parce que ce mot était dans la liste.",
          "Nous allons réviser la réservation avant l'évaluation.",
          "Mon camarade a expliqué la réservation avec ses mots.",
          "J'ai ajouté réservation dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la réservation semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la réservation se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais réservation, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà réservation, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la réservation.",
          "La leçon que nous travaillons utilise réservation dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la réservation, les élèves prenaient des notes.",
          "Puisque la réservation aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé réservation, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la réservation aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, réservation peut donner une information précise.",
          "Le mot dont je parle est réservation, que la classe doit retenir.",
          "Tant que tu pratiqueras réservation, tu comprendras mieux les dialogues de voyage.",
          "Bien que la réservation demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient réservation, je penserai au vocabulaire du déplacement.",
          "Bien que le mot réservation paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la réservation apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la réservation, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà réservation, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la réservation.",
          "Lorsque j'aurai mémorisé réservation, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la réservation.",
          "Puisque réservation est utile, je le révise régulièrement.",
        ],
      } },
    { word: "nuit", image: "/vocab/images/V2/nuit.webp",            article: "la",  gender: "f", definition: ["Période entre le soir et le matin ; dans un hôtel, temps passé à dormir sur place."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché la nuit sur le plan.",
          "Demain, je vais chercher la nuit.",
          "Quand je voyage, j'utilise souvent la nuit.",
          "Ce matin, le guide a montré la nuit.",
          "Nous avons demandé où se trouvait la nuit.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi la nuit parce que c'était pratique.",
          "Elle a noté nuit dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de la nuit.",
          "Le groupe a trouvé la nuit près de la gare.",
          "Je vais chercher la nuit après l'arrivée.",
          "Nous avons associé la nuit à une image.",
          "Hier soir, mon frère a vérifié la nuit sur internet.",
          "Pendant les vacances, nous utilisions souvent la nuit.",
          "Elle a oublié le mot nuit pendant l'exercice.",
          "Il va utiliser nuit dans sa phrase.",
          "Nous avons trouvé la nuit dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser nuit.",
          "L'élève a ajouté nuit dans sa réponse.",
          "J'ai compris le mot nuit pour la première fois.",
          "Ma sœur a choisi la nuit pour son exemple.",
          "Ils ont répété nuit à voix haute.",
          "Nous allons revoir la nuit avec le professeur.",
          "Elle a noté nuit pour ne pas l'oublier.",
          "La classe a demandé un exemple avec la nuit.",
          "Après la leçon, j'ai utilisé le mot nuit dans une phrase.",
          "Demain, je vais apprendre à mieux employer la nuit.",
          "Quand je lis le texte, je cherche le sens de nuit.",
          "Ce matin, nous avons associé la nuit à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec nuit.",
          "Le professeur a demandé un exemple avec la nuit.",
          "J'ai choisi la nuit parce que ce mot était dans la liste.",
          "Nous allons réviser la nuit avant l'évaluation.",
          "Mon camarade a expliqué la nuit avec ses mots.",
          "J'ai ajouté nuit dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que la nuit semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme la nuit se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais nuit, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà nuit, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait la nuit.",
          "La leçon que nous travaillons utilise nuit dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait la nuit, les élèves prenaient des notes.",
          "Puisque la nuit aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé nuit, tu pourras demander ton chemin plus naturellement.",
          "Je pense que la nuit aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, nuit peut donner une information précise.",
          "Le mot dont je parle est nuit, que la classe doit retenir.",
          "Tant que tu pratiqueras nuit, tu comprendras mieux les dialogues de voyage.",
          "Bien que la nuit demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient nuit, je penserai au vocabulaire du déplacement.",
          "Bien que le mot nuit paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme la nuit apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien la nuit, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà nuit, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser la nuit.",
          "Lorsque j'aurai mémorisé nuit, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec la nuit.",
          "Puisque nuit est utile, je le révise régulièrement.",
        ],
      } },
    { word: "étage", image: "etage.webp",           article: "l'",  gender: "m", definition: ["Niveau d’un bâtiment."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'étage sur le plan.",
          "Demain, je vais chercher l'étage.",
          "Quand je voyage, j'utilise souvent l'étage.",
          "Ce matin, le guide a montré l'étage.",
          "Nous avons demandé où se trouvait l'étage.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'étage parce que c'était pratique.",
          "Elle a noté étage dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'étage.",
          "Le groupe a trouvé l'étage près de la gare.",
          "Je vais chercher l'étage après l'arrivée.",
          "Nous avons associé l'étage à une image.",
          "Hier soir, mon frère a vérifié l'étage sur internet.",
          "Pendant les vacances, nous utilisions souvent l'étage.",
          "Elle a oublié le mot étage pendant l'exercice.",
          "Il va utiliser étage dans sa phrase.",
          "Nous avons trouvé l'étage dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser étage.",
          "L'élève a ajouté étage dans sa réponse.",
          "J'ai compris le mot étage pour la première fois.",
          "Ma sœur a choisi l'étage pour son exemple.",
          "Ils ont répété étage à voix haute.",
          "Nous allons revoir l'étage avec le professeur.",
          "Elle a noté étage pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'étage.",
          "Après la leçon, j'ai utilisé le mot étage dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'étage.",
          "Quand je lis le texte, je cherche le sens de étage.",
          "Ce matin, nous avons associé l'étage à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec étage.",
          "Le professeur a demandé un exemple avec l'étage.",
          "J'ai choisi l'étage parce que ce mot était dans la liste.",
          "Nous allons réviser l'étage avant l'évaluation.",
          "Mon camarade a expliqué l'étage avec ses mots.",
          "J'ai ajouté étage dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'étage semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'étage se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais étage, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà étage, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'étage.",
          "La leçon que nous travaillons utilise étage dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'étage, les élèves prenaient des notes.",
          "Puisque l'étage aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé étage, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'étage aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, étage peut donner une information précise.",
          "Le mot dont je parle est étage, que la classe doit retenir.",
          "Tant que tu pratiqueras étage, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'étage demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient étage, je penserai au vocabulaire du déplacement.",
          "Bien que le mot étage paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'étage apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'étage, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà étage, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'étage.",
          "Lorsque j'aurai mémorisé étage, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'étage.",
          "Puisque étage est utile, je le révise régulièrement.",
        ],
      } },
    { word: "ascenseur", image: "/vocab/images/V5/ascenseur.webp",       article: "l'",  gender: "m", definition: ["Appareil qui monte et descend entre les étages."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché l'ascenseur sur le plan.",
          "Demain, je vais chercher l'ascenseur.",
          "Quand je voyage, j'utilise souvent l'ascenseur.",
          "Ce matin, le guide a montré l'ascenseur.",
          "Nous avons demandé où se trouvait l'ascenseur.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi l'ascenseur parce que c'était pratique.",
          "Elle a noté ascenseur dans son carnet de voyage.",
          "Avant de partir, nous avons parlé de l'ascenseur.",
          "Le groupe a trouvé l'ascenseur près de la gare.",
          "Je vais chercher l'ascenseur après l'arrivée.",
          "Nous avons associé l'ascenseur à une image.",
          "Hier soir, mon frère a vérifié l'ascenseur sur internet.",
          "Pendant les vacances, nous utilisions souvent l'ascenseur.",
          "Elle a oublié le mot ascenseur pendant l'exercice.",
          "Il va utiliser ascenseur dans sa phrase.",
          "Nous avons trouvé l'ascenseur dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser ascenseur.",
          "L'élève a ajouté ascenseur dans sa réponse.",
          "J'ai compris le mot ascenseur pour la première fois.",
          "Ma sœur a choisi l'ascenseur pour son exemple.",
          "Ils ont répété ascenseur à voix haute.",
          "Nous allons revoir l'ascenseur avec le professeur.",
          "Elle a noté ascenseur pour ne pas l'oublier.",
          "La classe a demandé un exemple avec l'ascenseur.",
          "Après la leçon, j'ai utilisé le mot ascenseur dans une phrase.",
          "Demain, je vais apprendre à mieux employer l'ascenseur.",
          "Quand je lis le texte, je cherche le sens de ascenseur.",
          "Ce matin, nous avons associé l'ascenseur à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec ascenseur.",
          "Le professeur a demandé un exemple avec l'ascenseur.",
          "J'ai choisi l'ascenseur parce que ce mot était dans la liste.",
          "Nous allons réviser l'ascenseur avant l'évaluation.",
          "Mon camarade a expliqué l'ascenseur avec ses mots.",
          "J'ai ajouté ascenseur dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que l'ascenseur semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme l'ascenseur se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais ascenseur, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà ascenseur, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait l'ascenseur.",
          "La leçon que nous travaillons utilise ascenseur dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait l'ascenseur, les élèves prenaient des notes.",
          "Puisque l'ascenseur aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé ascenseur, tu pourras demander ton chemin plus naturellement.",
          "Je pense que l'ascenseur aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, ascenseur peut donner une information précise.",
          "Le mot dont je parle est ascenseur, que la classe doit retenir.",
          "Tant que tu pratiqueras ascenseur, tu comprendras mieux les dialogues de voyage.",
          "Bien que l'ascenseur demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient ascenseur, je penserai au vocabulaire du déplacement.",
          "Bien que le mot ascenseur paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme l'ascenseur apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien l'ascenseur, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà ascenseur, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser l'ascenseur.",
          "Lorsque j'aurai mémorisé ascenseur, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec l'ascenseur.",
          "Puisque ascenseur est utile, je le révise régulièrement.",
        ],
      } },
    { word: "coffre-fort", image: "coffre-fort.webp",     article: "le",  gender: "m", definition: ["Petite boîte solide pour garder des objets importants."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le coffre-fort sur le plan.",
          "Demain, je vais chercher le coffre-fort.",
          "Quand je voyage, j'utilise souvent le coffre-fort.",
          "Ce matin, le guide a montré le coffre-fort.",
          "Nous avons demandé où se trouvait le coffre-fort.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le coffre-fort parce que c'était pratique.",
          "Elle a noté coffre-fort dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du coffre-fort.",
          "Le groupe a trouvé le coffre-fort près de la gare.",
          "Je vais chercher le coffre-fort après l'arrivée.",
          "Nous avons associé le coffre-fort à une image.",
          "Hier soir, mon frère a vérifié le coffre-fort sur internet.",
          "Pendant les vacances, nous utilisions souvent le coffre-fort.",
          "Elle a oublié le mot coffre-fort pendant l'exercice.",
          "Il va utiliser coffre-fort dans sa phrase.",
          "Nous avons trouvé le coffre-fort dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser coffre-fort.",
          "L'élève a ajouté coffre-fort dans sa réponse.",
          "J'ai compris le mot coffre-fort pour la première fois.",
          "Ma sœur a choisi le coffre-fort pour son exemple.",
          "Ils ont répété coffre-fort à voix haute.",
          "Nous allons revoir le coffre-fort avec le professeur.",
          "Elle a noté coffre-fort pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le coffre-fort.",
          "Après la leçon, j'ai utilisé le mot coffre-fort dans une phrase.",
          "Demain, je vais apprendre à mieux employer le coffre-fort.",
          "Quand je lis le texte, je cherche le sens de coffre-fort.",
          "Ce matin, nous avons associé le coffre-fort à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec coffre-fort.",
          "Le professeur a demandé un exemple avec le coffre-fort.",
          "J'ai choisi le coffre-fort parce que ce mot était dans la liste.",
          "Nous allons réviser le coffre-fort avant l'évaluation.",
          "Mon camarade a expliqué le coffre-fort avec ses mots.",
          "J'ai ajouté coffre-fort dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le coffre-fort semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le coffre-fort se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais coffre-fort, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà coffre-fort, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le coffre-fort.",
          "La leçon que nous travaillons utilise coffre-fort dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le coffre-fort, les élèves prenaient des notes.",
          "Puisque le coffre-fort aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé coffre-fort, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le coffre-fort aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, coffre-fort peut donner une information précise.",
          "Le mot dont je parle est coffre-fort, que la classe doit retenir.",
          "Tant que tu pratiqueras coffre-fort, tu comprendras mieux les dialogues de voyage.",
          "Bien que le coffre-fort demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient coffre-fort, je penserai au vocabulaire du déplacement.",
          "Bien que le mot coffre-fort paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le coffre-fort apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le coffre-fort, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà coffre-fort, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le coffre-fort.",
          "Lorsque j'aurai mémorisé coffre-fort, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le coffre-fort.",
          "Puisque coffre-fort est utile, je le révise régulièrement.",
        ],
      } },
    { word: "concierge", image: "concierge.webp",       article: "le",  gender: "m", definition: ["Personne qui aide les clients dans un hôtel ou un immeuble."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le concierge sur le plan.",
          "Demain, je vais chercher le concierge.",
          "Quand je voyage, j'utilise souvent le concierge.",
          "Ce matin, le guide a montré le concierge.",
          "Nous avons demandé où se trouvait le concierge.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le concierge parce que c'était pratique.",
          "Elle a noté concierge dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du concierge.",
          "Le groupe a trouvé le concierge près de la gare.",
          "Je vais chercher le concierge après l'arrivée.",
          "Nous avons associé le concierge à une image.",
          "Hier soir, mon frère a vérifié le concierge sur internet.",
          "Pendant les vacances, nous utilisions souvent le concierge.",
          "Elle a oublié le mot concierge pendant l'exercice.",
          "Il va utiliser concierge dans sa phrase.",
          "Nous avons trouvé le concierge dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser concierge.",
          "L'élève a ajouté concierge dans sa réponse.",
          "J'ai compris le mot concierge pour la première fois.",
          "Ma sœur a choisi le concierge pour son exemple.",
          "Ils ont répété concierge à voix haute.",
          "Nous allons revoir le concierge avec le professeur.",
          "Elle a noté concierge pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le concierge.",
          "Après la leçon, j'ai utilisé le mot concierge dans une phrase.",
          "Demain, je vais apprendre à mieux employer le concierge.",
          "Quand je lis le texte, je cherche le sens de concierge.",
          "Ce matin, nous avons associé le concierge à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec concierge.",
          "Le professeur a demandé un exemple avec le concierge.",
          "J'ai choisi le concierge parce que ce mot était dans la liste.",
          "Nous allons réviser le concierge avant l'évaluation.",
          "Mon camarade a expliqué le concierge avec ses mots.",
          "J'ai ajouté concierge dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le concierge semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le concierge se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais concierge, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà concierge, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le concierge.",
          "La leçon que nous travaillons utilise concierge dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le concierge, les élèves prenaient des notes.",
          "Puisque le concierge aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé concierge, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le concierge aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, concierge peut donner une information précise.",
          "Le mot dont je parle est concierge, que la classe doit retenir.",
          "Tant que tu pratiqueras concierge, tu comprendras mieux les dialogues de voyage.",
          "Bien que le concierge demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient concierge, je penserai au vocabulaire du déplacement.",
          "Bien que le mot concierge paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le concierge apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le concierge, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà concierge, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le concierge.",
          "Lorsque j'aurai mémorisé concierge, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le concierge.",
          "Puisque concierge est utile, je le révise régulièrement.",
        ],
      } },
    { word: "parking", image: "parking.webp",         article: "le",  gender: "m", definition: ["Lieu où l’on gare les voitures."], definitionPivot: { en: "A word used in a hotel.", ar: "كلمة تُستعمل في الفندق.", fa: "واژه‌ای که در هتل استفاده می‌شود.", pt: "Palavra usada num hotel.", so: "Eray hoteel lagu isticmaalo.", ti: "ኣብ ሆቴል ዝጥቀሙሉ ቃል።", tr: "Otelde kullanılan kelime.", ps: "کلمه چې په هوټل کې کارېږي.", uk: "Слово, яке використовують у готелі." }, synonym: [], exampleSentences: {
        a1: [],
        a2: [
          "Hier, j'ai cherché le parking sur le plan.",
          "Demain, je vais chercher le parking.",
          "Quand je voyage, j'utilise souvent le parking.",
          "Ce matin, le guide a montré le parking.",
          "Nous avons demandé où se trouvait le parking.",
          "Ils vont préparer le trajet avant le départ.",
          "J'ai choisi le parking parce que c'était pratique.",
          "Elle a noté parking dans son carnet de voyage.",
          "Avant de partir, nous avons parlé du parking.",
          "Le groupe a trouvé le parking près de la gare.",
          "Je vais chercher le parking après l'arrivée.",
          "Nous avons associé le parking à une image.",
          "Hier soir, mon frère a vérifié le parking sur internet.",
          "Pendant les vacances, nous utilisions souvent le parking.",
          "Elle a oublié le mot parking pendant l'exercice.",
          "Il va utiliser parking dans sa phrase.",
          "Nous avons trouvé le parking dans le dialogue de voyage.",
          "Ce week-end, je vais mémoriser parking.",
          "L'élève a ajouté parking dans sa réponse.",
          "J'ai compris le mot parking pour la première fois.",
          "Ma sœur a choisi le parking pour son exemple.",
          "Ils ont répété parking à voix haute.",
          "Nous allons revoir le parking avec le professeur.",
          "Elle a noté parking pour ne pas l'oublier.",
          "La classe a demandé un exemple avec le parking.",
          "Après la leçon, j'ai utilisé le mot parking dans une phrase.",
          "Demain, je vais apprendre à mieux employer le parking.",
          "Quand je lis le texte, je cherche le sens de parking.",
          "Ce matin, nous avons associé le parking à une image.",
          "Pendant l'exercice, j'ai écrit une phrase avec parking.",
          "Le professeur a demandé un exemple avec le parking.",
          "J'ai choisi le parking parce que ce mot était dans la liste.",
          "Nous allons réviser le parking avant l'évaluation.",
          "Mon camarade a expliqué le parking avec ses mots.",
          "J'ai ajouté parking dans mon carnet de vocabulaire.",
        ],
        b1: [
          "Bien que le parking semble facile à trouver, il vaut mieux vérifier l'adresse avant de partir.",
          "Comme le parking se trouve près du centre, nous pouvons y aller à pied.",
          "Si tu connais parking, tu comprendras mieux les indications pendant le voyage.",
          "Même si je connais déjà parking, je dois encore l'utiliser dans une phrase complète.",
          "Le voyageur, qui cherchait son chemin, a demandé où se trouvait le parking.",
          "La leçon que nous travaillons utilise parking dans plusieurs situations de déplacement.",
          "Pendant que le guide montrait le parking, les élèves prenaient des notes.",
          "Puisque le parking aide à s'orienter, nous l'avons ajouté au plan.",
          "Lorsque tu auras mémorisé parking, tu pourras demander ton chemin plus naturellement.",
          "Je pense que le parking aide les élèves parce que ce mot revient souvent en voyage.",
          "Même quand la phrase est courte, parking peut donner une information précise.",
          "Le mot dont je parle est parking, que la classe doit retenir.",
          "Tant que tu pratiqueras parking, tu comprendras mieux les dialogues de voyage.",
          "Bien que le parking demande peu d'explications, il faut choisir le bon article.",
          "Si l'exercice contient parking, je penserai au vocabulaire du déplacement.",
          "Bien que le mot parking paraisse simple, il faut l'utiliser dans un contexte clair.",
          "Comme le parking apparaît souvent dans cette leçon, je l'ai noté dans mon cahier.",
          "Si je comprends bien le parking, je pourrai l'employer dans une phrase personnelle.",
          "Même si je connais déjà parking, je dois encore le prononcer correctement.",
          "Le professeur, qui veut enrichir notre vocabulaire, nous demande d'utiliser le parking.",
          "Lorsque j'aurai mémorisé parking, je pourrai l'utiliser plus naturellement.",
          "Pendant que les autres lisaient, j'ai cherché un exemple avec le parking.",
          "Puisque parking est utile, je le révise régulièrement.",
        ],
      } },
  ],
  sentences: [
    { sentence: "Il fait une ___ pour deux nuits à l'hôtel.",            answer: "réservation" },
    { sentence: "La ___ vous remettra la clé de votre chambre.",         answer: "réception" },
    { sentence: "Le ___ est servi de 7h à 10h.",                         answer: "petit-déjeuner" },
    { sentence: "Je range mes bijoux dans le ___ de la chambre.",        answer: "coffre-fort" },
    { sentence: "La chambre est au troisième ___, prenez l'ascenseur.",  answer: "étage" },
  ],
};
