import type { OralLevel } from "./speaking-prompts";

export type ArgumentationTopic = {
  theme: string;
  prompt: string;
};

const ARGUMENTATION_TOPICS: Record<OralLevel, ArgumentationTopic[]> = {
  base: [
    { theme: "transports publics", prompt: "Tu vas souvent en bus ou en train.\nDis si tu aimes ou si tu n'aimes pas les transports publics." },
    { theme: "telephone portable", prompt: "Tu as un telephone portable.\nDis si tu l'utilises beaucoup ou peu." },
    { theme: "ecole", prompt: "Tu vas en cours.\nDis si tu aimes l'ecole et pourquoi." },
    { theme: "sport", prompt: "Tu fais parfois du sport.\nDis quel sport tu aimes." },
    { theme: "alimentation", prompt: "Tu manges a la maison ou dehors.\nDis ce que tu preferes." },
    { theme: "travail", prompt: "Tu connais un metier que tu aimes.\nDis lequel et pourquoi." },
    { theme: "logement", prompt: "Tu habites dans un logement.\nDis ce que tu aimes chez toi." },
    { theme: "famille", prompt: "Tu vois ta famille.\nDis pourquoi la famille est importante." },
    { theme: "apprentissage du francais", prompt: "Tu apprends le francais.\nDis si c'est facile ou difficile." },
    { theme: "courses", prompt: "Tu fais parfois les courses.\nDis ou tu vas acheter a manger." },
    { theme: "sante", prompt: "Quand tu es malade, tu vas chez le medecin.\nDis ce que tu fais pour rester en bonne sante." },
    { theme: "argent", prompt: "Tu utilises de l'argent pour acheter des choses.\nDis ce que tu achetes souvent." },
    { theme: "Internet", prompt: "Tu utilises Internet.\nDis pourquoi c'est utile." },
    { theme: "reseaux sociaux", prompt: "Tu connais les reseaux sociaux.\nDis si tu les utilises ou non." },
    { theme: "environnement", prompt: "Tu vois parfois des dechets dans la rue.\nDis ce qu'il faut faire." },
    { theme: "ville", prompt: "Tu habites en ville ou dans un village.\nDis ce que tu preferes." },
    { theme: "temps libre", prompt: "Quand tu as du temps libre, que fais-tu ?\nDis une activite que tu aimes." },
    { theme: "voyage", prompt: "Tu as deja voyage.\nDis ou tu aimerais aller." },
    { theme: "animaux", prompt: "Tu aimes les animaux.\nDis quel animal tu preferes." },
    { theme: "lecture", prompt: "Tu lis parfois.\nDis ce que tu aimes lire." },
    { theme: "cinema", prompt: "Tu regardes des films.\nDis quel genre de film tu aimes." },
    { theme: "voisinage", prompt: "Tu as des voisins.\nDis ce qu'il faut faire pour bien vivre ensemble." },
    { theme: "technologie", prompt: "Tu utilises parfois des appareils.\nDis lequel est le plus utile pour toi." },
    { theme: "egalite", prompt: "Tout le monde doit etre respecte.\nDis pourquoi c'est important." },
    { theme: "regles de vie", prompt: "Il y a des regles a l'ecole ou dans la rue.\nDis une regle importante." },
  ],
  moyen: [
    { theme: "transports publics", prompt: "Certaines personnes preferent prendre les transports publics, d'autres preferent la voiture.\nEt toi, qu'est-ce que tu preferes ? Donne les raisons." },
    { theme: "telephone portable", prompt: "Beaucoup de personnes utilisent leur telephone tous les jours.\nEst-ce utile ou genant pour toi ? Explique pourquoi." },
    { theme: "ecole", prompt: "L'ecole aide a apprendre, mais elle peut aussi etre difficile.\nQu'est-ce qui est important pour toi a l'ecole ?" },
    { theme: "sport", prompt: "Certaines personnes font du sport chaque semaine.\nEt toi, penses-tu que le sport est important ? Pourquoi ?" },
    { theme: "alimentation", prompt: "Manger sainement coute parfois plus cher.\nQue penses-tu de cette idee ?" },
    { theme: "travail", prompt: "Pour choisir un travail, certaines personnes regardent le salaire, d'autres l'ambiance.\nQu'est-ce qui est le plus important pour toi ?" },
    { theme: "logement", prompt: "Certaines personnes preferent vivre en ville, d'autres a la campagne.\nEt toi, ou preferes-tu habiter ?" },
    { theme: "famille", prompt: "La famille peut aider dans les moments difficiles.\nPourquoi la famille est-elle importante pour toi ?" },
    { theme: "apprentissage du francais", prompt: "Apprendre le francais aide a vivre en Suisse.\nQu'est-ce qui t'aide le plus pour apprendre ?" },
    { theme: "courses", prompt: "Faire les courses au marche ou au supermarche, ce n'est pas pareil.\nQu'est-ce que tu preferes ?" },
    { theme: "sante", prompt: "Pour rester en bonne sante, on peut bien manger, dormir et bouger.\nQu'est-ce qui est le plus important selon toi ?" },
    { theme: "argent", prompt: "Certaines personnes economisent, d'autres depensent rapidement.\nEt toi, que fais-tu avec ton argent ?" },
    { theme: "Internet", prompt: "Internet aide a apprendre et a communiquer, mais il peut faire perdre du temps.\nQu'en penses-tu ?" },
    { theme: "reseaux sociaux", prompt: "Les reseaux sociaux permettent de garder contact, mais ils peuvent aussi creer des problemes.\nQuelle est ton opinion ?" },
    { theme: "environnement", prompt: "Proteger l'environnement demande des efforts dans la vie quotidienne.\nQuels gestes sont importants pour toi ?" },
    { theme: "ville", prompt: "Vivre en ville offre beaucoup de services, mais il y a aussi du bruit.\nPrefererais-tu vivre en ville ou a la campagne ?" },
    { theme: "temps libre", prompt: "Le temps libre permet de se reposer ou de voir des amis.\nComment aimes-tu l'utiliser ?" },
    { theme: "voyage", prompt: "Voyager permet de decouvrir d'autres lieux et cultures.\nPourquoi certaines personnes aiment beaucoup voyager ?" },
    { theme: "animaux", prompt: "Avoir un animal demande du temps et de l'argent.\nPenses-tu que c'est une bonne idee ?" },
    { theme: "lecture", prompt: "Lire aide a apprendre des mots et a comprendre le monde.\nAimes-tu lire ? Pourquoi ?" },
    { theme: "cinema", prompt: "Aller au cinema ou regarder un film a la maison, ce n'est pas pareil.\nQu'est-ce que tu preferes ?" },
    { theme: "voisinage", prompt: "Bien vivre avec ses voisins demande du respect.\nQuelles regles sont importantes ?" },
    { theme: "technologie", prompt: "La technologie simplifie certaines choses, mais elle peut aussi isoler.\nQu'en penses-tu ?" },
    { theme: "egalite", prompt: "Les hommes et les femmes doivent avoir les memes chances.\nQu'en penses-tu ?" },
    { theme: "regles de vie", prompt: "Les regles peuvent parfois sembler difficiles, mais elles protegent les personnes.\nEs-tu d'accord ?" },
  ],
  avance: [
    { theme: "transports publics", prompt: "Aujourd'hui, beaucoup de villes encouragent les habitants a utiliser les transports publics plutot que la voiture.\nEtes-vous d'accord avec cette idee ? Donnez votre opinion." },
    { theme: "telephone portable", prompt: "Le telephone portable prend une grande place dans la vie quotidienne.\nSelon vous, faut-il limiter son utilisation ? Argumentez." },
    { theme: "ecole", prompt: "L'ecole doit preparer les eleves a la vie professionnelle et sociale.\nEtes-vous d'accord ? Justifiez votre opinion." },
    { theme: "sport", prompt: "Le sport est souvent presente comme necessaire pour la sante.\nFaut-il encourager davantage les adultes a faire du sport ? Argumentez." },
    { theme: "alimentation", prompt: "Dans notre societe, l'alimentation influence la sante, le budget et l'environnement.\nComment peut-on mieux manger au quotidien ?" },
    { theme: "travail", prompt: "Le travail occupe une grande partie de la vie adulte.\nSelon vous, qu'est-ce qu'un bon emploi aujourd'hui ?" },
    { theme: "logement", prompt: "Le logement devient cher dans beaucoup de regions.\nQuelles solutions pourraient aider les familles a se loger correctement ?" },
    { theme: "famille", prompt: "La place de la famille change selon les cultures et les generations.\nSelon vous, quel role joue la famille aujourd'hui ?" },
    { theme: "apprentissage du francais", prompt: "La maitrise de la langue du pays facilite l'integration sociale et professionnelle.\nComment peut-on mieux soutenir les personnes qui apprennent le francais ?" },
    { theme: "courses", prompt: "Les habitudes de consommation ont des consequences sur l'economie locale et l'environnement.\nFaut-il privilegier les commerces de proximite ?" },
    { theme: "sante", prompt: "La prevention coute souvent moins cher que les soins.\nPensez-vous que les pouvoirs publics devraient investir davantage dans la prevention ?" },
    { theme: "argent", prompt: "L'education financiere est importante pour eviter les difficultes.\nDevrait-elle etre enseignee a l'ecole ? Argumentez." },
    { theme: "Internet", prompt: "Internet transforme le travail, l'ecole et les relations sociales.\nSes avantages sont-ils plus importants que ses dangers ?" },
    { theme: "reseaux sociaux", prompt: "Les reseaux sociaux influencent l'information et l'image de soi.\nFaut-il mieux les reglementer ?" },
    { theme: "environnement", prompt: "La protection de l'environnement impose parfois des contraintes aux citoyens.\nCes contraintes sont-elles necessaires ?" },
    { theme: "ville", prompt: "Les villes doivent concilier logement, transports, securite et qualite de vie.\nQuelle priorite faudrait-il donner selon vous ?" },
    { theme: "temps libre", prompt: "Dans une vie tres occupee, le temps libre devient precieux.\nComment trouver un bon equilibre entre obligations et loisirs ?" },
    { theme: "voyage", prompt: "Le tourisme apporte de l'argent, mais il peut aussi abimer certains lieux.\nComment voyager de maniere responsable ?" },
    { theme: "animaux", prompt: "Les animaux de compagnie apportent du bien-etre, mais impliquent des responsabilites.\nFaut-il mieux encadrer l'adoption d'animaux ?" },
    { theme: "lecture", prompt: "A l'epoque des ecrans, la lecture reste-t-elle importante pour la formation et la pensee critique ?" },
    { theme: "cinema", prompt: "Le cinema peut divertir, informer et faire reflechir.\nSelon vous, les films ont-ils une influence sur la societe ?" },
    { theme: "voisinage", prompt: "Le voisinage peut renforcer la solidarite dans un quartier.\nComment encourager de meilleures relations entre voisins ?" },
    { theme: "technologie", prompt: "La technologie evolue tres vite et change nos metiers.\nDevons-nous nous adapter a tout prix ?" },
    { theme: "egalite", prompt: "Malgre les progres, les inegalites existent encore dans le travail et la societe.\nQuelles mesures seraient utiles ?" },
    { theme: "regles de vie", prompt: "Une societe a besoin de regles, mais aussi de liberte.\nComment trouver le bon equilibre ?" },
  ],
};

export function randomArgumentationTopic(level: OralLevel): ArgumentationTopic {
  const pool = ARGUMENTATION_TOPICS[level] ?? ARGUMENTATION_TOPICS.base;
  return pool[Math.floor(Math.random() * pool.length)]!;
}
