import { buildPool, type COMultiQuestion } from "./co-questions-helpers";

/** CO avancé scolaire / B1 — radios (exercices 15 à 17). */

export const SCOLAIRE_AVANCE_RADIO_15 = buildPool("avance", "scolaire-radio-15", [
  {
    id: "sar15-q1",
    textQ: "Combien de temps a réellement duré la pause de M. Pokora, selon lui ?",
    text: ["2 mois", "1 an", "2 ans"],
    textC: 0,
    img: ["2 mois", "1 an", "2 ans"],
    imgC: 0,
    fillQ: "Pendant sa pause, il a quand même créé ___ titres.",
    fill: "16",
    fillA: ["16", "seize"],
  },
  {
    id: "sar15-q2",
    textQ: "Combien de titres compte le nouvel album de M. Pokora ?",
    text: ["12 titres", "16 titres", "20 titres"],
    textC: 1,
    img: ["12", "16", "20"],
    imgC: 1,
    fillQ: "Son album précédent « My Way » a vendu plus de 600 000 ___ .",
    fill: "exemplaires",
    fillA: ["exemplaires", "exemplaire", "copies"],
  },
  {
    id: "sar15-q3",
    textQ: "L'idée de son nouvel album lui est venue…",
    text: ["En voyageant en Égypte", "En regardant la télévision", "En lisant une bande dessinée de super-héros"],
    textC: 1,
    img: ["Égypte", "Télévision", "BD super-héros"],
    imgC: 1,
    fillQ: "Il regardait un documentaire sur les ___ .",
    fill: "pyramides",
    fillA: ["pyramides", "pyramide"],
  },
  {
    id: "sar15-q4",
    textQ: "Citez deux effets spéciaux présents dans le concert.",
    text: ["Pluie et neige artificielles", "Feux d'artifice et lasers", "Fumée et projecteurs seulement"],
    textC: 1,
    img: ["Pluie et neige", "Feux et lasers", "Fumée"],
    imgC: 1,
    fillQ: "Il y a aussi beaucoup de ___ sur scène.",
    fill: "danse",
    fillA: ["danse", "danser"],
  },
  {
    id: "sar15-q5",
    textQ: "Qu'est-ce qui manquait à M. Pokora ?",
    text: ["La danse", "Le théâtre", "Les films futuristes"],
    textC: 0,
    img: ["Danse", "Théâtre", "Films"],
    imgC: 0,
    fillQ: "Les décors de concert sont très ___ .",
    fill: "impressionnants",
    fillA: ["impressionnants", "impressionnant", "grands"],
  },
  {
    id: "sar15-q6",
    textQ: "Dans l'album Pyramide, M. Pokora…",
    text: ["Reprend des chansons d'autres chanteurs", "Parle de lui", "Parle de la vie des chanteurs"],
    textC: 1,
    img: ["Reprises", "Parle de lui", "Vie des chanteurs"],
    imgC: 1,
    fillQ: "Il voulait quelque chose de plus ___ .",
    fill: "personnel",
    fillA: ["personnel", "personnelle", "intime"],
  },
  {
    id: "sar15-q7",
    textQ: "Pyramide est…",
    text: ["Le titre de sa chanson préférée", "Le titre de son premier album", "Le titre de l'album et d'une de ses chansons"],
    textC: 2,
    img: ["Chanson préférée", "Premier album", "Album et chanson"],
    imgC: 2,
    fillQ: "L'album imagine un monde un peu ___ .",
    fill: "futuriste",
    fillA: ["futuriste", "fantastique"],
  },
  {
    id: "sar15-q8",
    textQ: "Qu'est-ce qui a aussi inspiré l'album ?",
    text: ["Des films de super-héros", "Un voyage en montagne", "Un concert de jazz"],
    textC: 0,
    img: ["Films super-héros", "Montagne", "Jazz"],
    imgC: 0,
    fillQ: "Il a regardé plusieurs films de ___ .",
    fill: "super-héros",
    fillA: ["super-heros", "super-héros", "heros", "héros"],
  },
  {
    id: "sar15-q9",
    textQ: "Pourquoi M. Pokora a-t-il repris l'écriture après sa pause ?",
    text: ["Parce qu'il s'ennuyait", "Parce qu'il avait un contrat", "Parce qu'il déteste la télévision"],
    textC: 0,
    img: ["Ennui", "Contrat", "Déteste TV"],
    imgC: 0,
    fillQ: "Ne plus rien faire ne lui ___ pas.",
    fill: "ressemblait",
    fillA: ["ressemblait", "correspondait"],
  },
  {
    id: "sar15-q10",
    textQ: "De quoi M. Pokora parle-t-il sans filtre dans Pyramide ?",
    text: ["De ses voyages", "De ses doutes", "Des autres chanteurs"],
    textC: 1,
    img: ["Voyages", "Doutes", "Autres chanteurs"],
    imgC: 1,
    fillQ: "Avant, il chantait longtemps les textes des ___ .",
    fill: "autres",
    fillA: ["autres", "autre"],
  },
  {
    id: "sar15-q11",
    textQ: "Quel classement Pyramide a-t-il atteint ?",
    text: ["Dixième des albums français", "Premier des albums français les plus vendus", "Il n'est pas entré au classement"],
    textC: 1,
    img: ["10e", "1er", "Hors classement"],
    imgC: 1,
    fillQ: "Pendant sa pause, il s'est posé beaucoup de ___ .",
    fill: "questions",
    fillA: ["questions", "question"],
  },
  {
    id: "sar15-q12",
    textQ: "Quelle question M. Pokora s'est-il posée pendant sa pause ?",
    text: ["S'il allait continuer sa carrière de chanteur", "S'il allait déménager", "S'il allait apprendre la danse"],
    textC: 0,
    img: ["Continuer chanteur", "Déménager", "Apprendre danse"],
    imgC: 0,
    fillQ: "Il se demandait ce qu'il dirait s'il ne lui restait que trois ___ .",
    fill: "minutes",
    fillA: ["minutes", "minute"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_16 = buildPool("avance", "scolaire-radio-16", [
  {
    id: "sar16-q1",
    textQ: "Dans cette émission, le journaliste parle de la vie de…",
    text: ["Deux adolescents qui ont des journées différentes", "Deux adolescents qui ont des loisirs différents", "Deux adolescents de pays différents"],
    textC: 0,
    img: ["Journées différentes", "Loisirs différents", "Pays différents"],
    imgC: 0,
    fillQ: "L'émission s'appelle « Graines de ___ ».",
    fill: "jeunes",
    fillA: ["jeunes", "jeune"],
  },
  {
    id: "sar16-q2",
    textQ: "Comment Eddy définit-il sa vie ?",
    text: ["Stressante et bruyante", "Calme et sereine", "Toujours en voyage"],
    textC: 1,
    img: ["Stressante", "Calme et sereine", "Voyage"],
    imgC: 1,
    fillQ: "Eddy dit que c'est parfois trop ___ .",
    fill: "calme",
    fillA: ["calme", "serin", "serein"],
  },
  {
    id: "sar16-q3",
    textQ: "Où habite Béa ?",
    text: ["Dans une petite ville de Bretagne", "Au cœur d'une grande île", "Dans une grande ville"],
    textC: 2,
    img: ["Petite ville Bretagne", "Grande île", "Grande ville"],
    imgC: 2,
    fillQ: "Béa définit sa vie avec les mots stress et quotidien ___ .",
    fill: "rempli",
    fillA: ["rempli", "plein", "charge"],
  },
  {
    id: "sar16-q4",
    textQ: "Comment Eddy va-t-il au collège le matin ?",
    text: ["En bus", "En bateau", "À vélo"],
    textC: 1,
    img: ["Bus", "Bateau", "Vélo"],
    imgC: 1,
    fillQ: "Il n'y a pas de collège sur son ___ .",
    fill: "île",
    fillA: ["ile", "île"],
  },
  {
    id: "sar16-q5",
    textQ: "Combien d'habitants compte l'île d'Eddy ?",
    text: ["Une centaine", "Un millier", "Dix mille"],
    textC: 0,
    img: ["100", "1000", "10000"],
    imgC: 0,
    fillQ: "Les jeunes sur l'île sont très ___ .",
    fill: "peu",
    fillA: ["peu", "peu nombreux"],
  },
  {
    id: "sar16-q6",
    textQ: "Que fait Béa le week-end ?",
    text: ["Elle reste seule à la maison", "Elle sort beaucoup avec ses amis", "Elle étudie toute la journée"],
    textC: 1,
    img: ["Seule", "Sort avec amis", "Étudie"],
    imgC: 1,
    fillQ: "Elle ne passe pas un samedi sans voir ses ___ .",
    fill: "amis",
    fillA: ["amis", "copains", "copines"],
  },
  {
    id: "sar16-q7",
    textQ: "Pourquoi Eddy aime-t-il le trajet du soir en bateau ?",
    text: ["Pour faire ses devoirs", "Pour le bon air de la mer", "Pour regarder la télévision"],
    textC: 1,
    img: ["Devoirs", "Air de la mer", "Télévision"],
    imgC: 1,
    fillQ: "Il aime surtout cela quand arrivent les beaux ___ .",
    fill: "jours",
    fillA: ["jours", "jour"],
  },
  {
    id: "sar16-q8",
    textQ: "Que manque-t-il sur l'île d'Eddy ?",
    text: ["Des plages", "Cinéma, spectacles et shopping", "Des restaurants"],
    textC: 1,
    img: ["Plages", "Cinéma et shopping", "Restaurants"],
    imgC: 1,
    fillQ: "Le soir, il n'y a pas grand-chose à ___ .",
    fill: "faire",
    fillA: ["faire"],
  },
  {
    id: "sar16-q9",
    textQ: "Béa et Eddy aimeraient-ils échanger leur quotidien ?",
    text: ["Non, jamais", "Oui, mais pas pour la vie", "Oui, pour toujours"],
    textC: 1,
    img: ["Jamais", "Oui mais pas pour la vie", "Pour toujours"],
    imgC: 1,
    fillQ: "Béa accompagne le matin son petit ___ à l'école.",
    fill: "frère",
    fillA: ["frere", "frère"],
  },
  {
    id: "sar16-q10",
    textQ: "Combien de temps met Béa pour aller au lycée ?",
    text: ["Dix minutes", "Presque une heure", "Deux heures"],
    textC: 1,
    img: ["10 min", "1 heure", "2 heures"],
    imgC: 1,
    fillQ: "Il y a beaucoup de ___ dans la ville.",
    fill: "trafic",
    fillA: ["trafic", "circulation", "embouteillages"],
  },
  {
    id: "sar16-q11",
    textQ: "Quand l'île d'Eddy est-elle plus animée ?",
    text: ["En hiver", "En été", "Au printemps seulement"],
    textC: 1,
    img: ["Hiver", "Été", "Printemps"],
    imgC: 1,
    fillQ: "L'hiver sur l'île, c'est très très ___ .",
    fill: "calme",
    fillA: ["calme", "silencieux"],
  },
  {
    id: "sar16-q12",
    textQ: "Qu'est-ce que Béa peut faire le week-end en ville ?",
    text: ["Seulement ses devoirs", "Bowling, pizzeria et boutiques", "Rester au lycée"],
    textC: 1,
    img: ["Devoirs", "Bowling et sorties", "Lycée"],
    imgC: 1,
    fillQ: "Eddy apprécie aussi la ___ sur l'île.",
    fill: "solitude",
    fillA: ["solitude", "calme"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_17 = buildPool("avance", "scolaire-radio-17", [
  {
    id: "sar17-q1",
    textQ: "Quel type de danse fait Julia ?",
    text: ["Classique", "Moderne", "Contemporaine"],
    textC: 2,
    img: ["Classique", "Moderne", "Contemporaine"],
    imgC: 2,
    fillQ: "Elle suit une formation en danse ___ .",
    fill: "contemporaine",
    fillA: ["contemporaine", "moderne"],
  },
  {
    id: "sar17-q2",
    textQ: "Comment Julia se prépare-t-elle à sa carrière de danseuse ?",
    text: ["En regardant la télévision", "Avec une formation au conservatoire", "En jouant au théâtre"],
    textC: 1,
    img: ["Télévision", "Conservatoire", "Théâtre"],
    imgC: 1,
    fillQ: "Elle se forme dans une école de ___ .",
    fill: "danse",
    fillA: ["danse"],
  },
  {
    id: "sar17-q3",
    textQ: "Comment se sent Julia lorsqu'elle danse devant un public ?",
    text: ["Elle a peur", "Elle se sent très bien", "Elle est nerveuse"],
    textC: 1,
    img: ["Peur", "Très bien", "Nerveuse"],
    imgC: 1,
    fillQ: "Quand le feeling passe avec le public, c'est comme un ___ .",
    fill: "jeu",
    fillA: ["jeu"],
  },
  {
    id: "sar17-q4",
    textQ: "Comment la danse a changé son corps ?",
    text: ["Elle est très musclée", "Elle a beaucoup grandi", "Elle ne grandit presque plus"],
    textC: 2,
    img: ["Musclée", "Beaucoup grandi", "Ne grandit plus"],
    imgC: 2,
    fillQ: "La danse a arrêté totalement sa ___ .",
    fill: "croissance",
    fillA: ["croissance", "taille"],
  },
  {
    id: "sar17-q5",
    textQ: "Quels sont les avantages de la carrière de danseuse ? (Plusieurs réponses possibles.)",
    text: ["Un salaire très élevé", "Voyager et avoir des projets différents", "Ne jamais s'entraîner"],
    textC: 1,
    img: ["Salaire élevé", "Voyager", "Pas d'entraînement"],
    imgC: 1,
    fillQ: "Chaque jour est différent et c'est ___ .",
    fill: "enrichissant",
    fillA: ["enrichissant", "enrichissante", "interessant", "intéressant"],
  },
  {
    id: "sar17-q6",
    textQ: "Depuis quand Julia danse-t-elle ?",
    text: ["Depuis 3 ans", "Depuis 10 ans", "Depuis 15 ans"],
    textC: 1,
    img: ["3 ans", "10 ans", "15 ans"],
    imgC: 1,
    fillQ: "Elle danse depuis qu'elle a ___ ans.",
    fill: "trois",
    fillA: ["trois", "3"],
  },
  {
    id: "sar17-q7",
    textQ: "D'après Julia, que faut-il améliorer dans la carrière de danseuse ?",
    text: ["Il faudrait moins voyager", "Les danseuses devraient être mieux payées", "La carrière devrait être plus courte"],
    textC: 1,
    img: ["Moins voyager", "Mieux payées", "Plus courte"],
    imgC: 1,
    fillQ: "Les salaires sont très ___ en général.",
    fill: "bas",
    fillA: ["bas", "basse", "faibles", "faible"],
  },
  {
    id: "sar17-q8",
    textQ: "Que faut-il faire pour garder l'attention du public ?",
    text: ["Parler très fort", "Le surprendre et rester naturel", "Éviter de le regarder"],
    textC: 1,
    img: ["Parler fort", "Surprendre", "Éviter regard"],
    imgC: 1,
    fillQ: "Il faut réussir à garder son ___ .",
    fill: "attention",
    fillA: ["attention"],
  },
  {
    id: "sar17-q9",
    textQ: "Pourquoi Julia veut-elle être chorégraphe ?",
    text: ["Elle veut diriger des danseurs", "Elle ne veut plus danser", "Elle veut transmettre des messages"],
    textC: 2,
    img: ["Diriger", "Ne plus danser", "Transmettre messages"],
    imgC: 2,
    fillQ: "Elle veut faire passer ses ___ .",
    fill: "idées",
    fillA: ["idees", "idées", "messages"],
  },
  {
    id: "sar17-q10",
    textQ: "Comment Julia définit-elle la danse ?",
    text: ["Un sport sans effort", "Un jeu de mouvements", "Une simple promenade"],
    textC: 1,
    img: ["Sans effort", "Jeu de mouvements", "Promenade"],
    imgC: 1,
    fillQ: "La danse est aussi un ___ .",
    fill: "sport",
    fillA: ["sport"],
  },
  {
    id: "sar17-q11",
    textQ: "Pourquoi le corps s'étire moins en danse contemporaine ?",
    text: ["Parce qu'on danse au sol", "Parce qu'on ne danse jamais", "Parce qu'il n'y a pas de musique"],
    textC: 0,
    img: ["Danse au sol", "Ne danse pas", "Pas de musique"],
    imgC: 0,
    fillQ: "En danse classique, le corps s'étire ___ .",
    fill: "plus",
    fillA: ["plus", "davantage"],
  },
  {
    id: "sar17-q12",
    textQ: "Qu'est-ce qui est difficile dans le parcours de danseur ?",
    text: ["Il ne change jamais", "Ça peut s'arrêter du jour au lendemain", "On ne voyage jamais"],
    textC: 1,
    img: ["Ne change pas", "Arrêt soudain", "Pas de voyage"],
    imgC: 1,
    fillQ: "Sur scène, le moment est ___ pour Julia.",
    fill: "magique",
    fillA: ["magique", "incroyable", "super"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_18 = buildPool("avance", "scolaire-radio-18", [
  {
    id: "sar18-q1",
    textQ: "Le thème de cette émission est…",
    text: ["L'identité et le look chez les jeunes", "L'image des jeunes sur Internet", "Le changement permanent de la mode"],
    textC: 0,
    img: ["Identité et look", "Image Internet", "Mode"],
    imgC: 0,
    fillQ: "Ce soir, on parle du ___ vestimentaire.",
    fill: "look",
    fillA: ["look", "style"],
  },
  {
    id: "sar18-q2",
    textQ: "Élodie et Guillaume…",
    text: ["Ont la même opinion", "Ont une opinion différente", "N'ont pas d'opinion"],
    textC: 1,
    img: ["Même opinion", "Opinion différente", "Pas d'opinion"],
    imgC: 1,
    fillQ: "Guillaume n'est pas ___ avec Élodie.",
    fill: "d'accord",
    fillA: ["d'accord", "daccord"],
  },
  {
    id: "sar18-q3",
    textQ: "Que cherche Élodie ?",
    text: ["À appartenir à un groupe", "À être elle-même sans look particulier", "À copier la mode punk"],
    textC: 1,
    img: ["Groupe", "Être elle-même", "Mode punk"],
    imgC: 1,
    fillQ: "Elle veut être ___ , tout simplement.",
    fill: "elle-même",
    fillA: ["elle-meme", "elle-même", "moi-meme", "moi-même"],
  },
  {
    id: "sar18-q4",
    textQ: "Pourquoi Guillaume veut-il garder son look ?",
    text: ["Il pense que c'est son identité", "Il n'aime aucun autre look", "Il a toujours eu ce look"],
    textC: 0,
    img: ["Identité", "Pas autre look", "Toujours eu"],
    imgC: 0,
    fillQ: "Pour lui, c'est son ___ .",
    fill: "identité",
    fillA: ["identite", "identité"],
  },
  {
    id: "sar18-q5",
    textQ: "Quel style de look Guillaume évoque-t-il ?",
    text: ["Classique", "Punk", "Sportif"],
    textC: 1,
    img: ["Classique", "Punk", "Sportif"],
    imgC: 1,
    fillQ: "Il dit qu'il ne sera pas ___ toute sa vie.",
    fill: "punk",
    fillA: ["punk"],
  },
  {
    id: "sar18-q6",
    textQ: "Guillaume imagine que plus tard il sera…",
    text: ["Toujours le même", "Peut-être différent", "Comme son père"],
    textC: 1,
    img: ["Toujours pareil", "Peut-être différent", "Comme père"],
    imgC: 1,
    fillQ: "Peut-être un jour, il changera de ___ .",
    fill: "style",
    fillA: ["style", "mode", "look"],
  },
  {
    id: "sar18-q7",
    textQ: "Du point de vue de Guillaume…",
    text: ["Tout le monde fait partie d'un groupe", "Faire partie d'un groupe n'a pas d'importance", "Quand on a un look, c'est pour la vie"],
    textC: 0,
    img: ["Toujours un groupe", "Pas important", "Pour la vie"],
    imgC: 0,
    fillQ: "Même quand on veut être « ___ », on appartient à un groupe.",
    fill: "neutre",
    fillA: ["neutre"],
  },
  {
    id: "sar18-q8",
    textQ: "Que pense Élodie sur l'appartenance à un groupe ?",
    text: ["Il faut absolument un groupe", "On n'a pas besoin d'un groupe pour exister", "Seuls les punks ont une identité"],
    textC: 1,
    img: ["Faut un groupe", "Pas besoin", "Seuls punks"],
    imgC: 1,
    fillQ: "On n'a pas besoin de faire partie d'un ___ pour exister.",
    fill: "groupe",
    fillA: ["groupe"],
  },
  {
    id: "sar18-q9",
    textQ: "Quelle importance Élodie donne-t-elle au look ?",
    text: ["Une importance capitale", "Strictement aucune", "Seulement pour les fêtes"],
    textC: 1,
    img: ["Capitale", "Aucune", "Fêtes seulement"],
    imgC: 1,
    fillQ: "Elle ne cherche pas à avoir un look ___ .",
    fill: "précis",
    fillA: ["precis", "précis", "particulier"],
  },
  {
    id: "sar18-q10",
    textQ: "Si Guillaume changeait de look, que craint-il ?",
    text: ["De perdre ses amis uniquement", "Que les gens le regardent différemment", "De ne plus pouvoir sortir"],
    textC: 1,
    img: ["Perdre amis", "Regard différent", "Ne plus sortir"],
    imgC: 1,
    fillQ: "Il faudrait qu'il s'___ comme il est.",
    fill: "accepte",
    fillA: ["accepte"],
  },
  {
    id: "sar18-q11",
    textQ: "Pourquoi Guillaume fait-il attention à son image ?",
    text: ["Par obligation parentale", "Parce que c'est important pour lui", "Pour ressembler à Élodie"],
    textC: 1,
    img: ["Obligation", "Important pour lui", "Ressembler Élodie"],
    imgC: 1,
    fillQ: "Il veut garder son ___ .",
    fill: "style",
    fillA: ["style", "look", "image"],
  },
  {
    id: "sar18-q12",
    textQ: "Que répond Guillaume à Élodie sur les groupes « neutres » ?",
    text: ["Ils n'existent pas", "C'est aussi un groupe", "C'est mieux que le punk"],
    textC: 1,
    img: ["N'existent pas", "Aussi un groupe", "Mieux que punk"],
    imgC: 1,
    fillQ: "Ceux qui ne veulent appartenir à aucun groupe font partie d'un groupe ___ .",
    fill: "aussi",
    fillA: ["aussi", "egalement", "également"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_19 = buildPool("avance", "scolaire-radio-19", [
  {
    id: "sar19-q1",
    textQ: "Cette émission présente des livres pour…",
    text: ["Les enfants de moins de 10 ans", "Les adolescents", "Les adultes"],
    textC: 1,
    img: ["-10 ans", "Adolescents", "Adultes"],
    imgC: 1,
    fillQ: "L'émission s'appelle La bibliothèque des ___ .",
    fill: "ados",
    fillA: ["ados"],
  },
  {
    id: "sar19-q2",
    textQ: "Mathieu Sylvander…",
    text: ["Est l'invité de l'émission", "Est le journaliste", "Est l'auteur du livre présenté"],
    textC: 2,
    img: ["Invité", "Journaliste", "Auteur"],
    imgC: 2,
    fillQ: "Le roman s'appelle « Comme un ___ ».",
    fill: "orage",
    fillA: ["orage"],
  },
  {
    id: "sar19-q3",
    textQ: "Où se déroule l'histoire ?",
    text: ["Dans une ville", "À la campagne", "À la montagne"],
    textC: 2,
    img: ["Ville", "Campagne", "Montagne"],
    imgC: 2,
    fillQ: "L'histoire commence par un gros ___ d'été.",
    fill: "orage",
    fillA: ["orage"],
  },
  {
    id: "sar19-q4",
    textQ: "Au début de l'histoire, les enfants sont…",
    text: ["Seuls", "Avec leur mère", "Avec des éducateurs"],
    textC: 1,
    img: ["Seuls", "Avec mère", "Éducateurs"],
    imgC: 1,
    fillQ: "La mère est un peu plus ___ .",
    fill: "loin",
    fillA: ["loin"],
  },
  {
    id: "sar19-q5",
    textQ: "Quel est le métier de la mère ?",
    text: ["Elle est guide de haute montagne", "Elle est médecin", "Elle gère un gîte en montagne"],
    textC: 2,
    img: ["Guide", "Médecin", "Gîte"],
    imgC: 2,
    fillQ: "Elle accueille des touristes dans son ___ .",
    fill: "gîte",
    fillA: ["gite", "gîte"],
  },
  {
    id: "sar19-q6",
    textQ: "Citez un problème que les enfants devront résoudre.",
    text: ["Trouver de vraies chaussures", "Apprendre à nager", "Acheter un train"],
    textC: 0,
    img: ["Chaussures", "Nager", "Train"],
    imgC: 0,
    fillQ: "Kevin ne peut pas continuer à marcher en ___ .",
    fill: "pantoufles",
    fillA: ["pantoufles", "pantoufle"],
  },
  {
    id: "sar19-q7",
    textQ: "D'après l'invitée, ce roman est très…",
    text: ["Tendre", "Drôle", "Triste"],
    textC: 0,
    img: ["Tendre", "Drôle", "Triste"],
    imgC: 0,
    fillQ: "C'est une histoire sur les relations inter___ .",
    fill: "générationnelles",
    fillA: ["generationnelles", "générationnelles"],
  },
  {
    id: "sar19-q8",
    textQ: "Kevin est-il un enfant ?",
    text: ["Oui, un petit garçon", "Non, c'est un homme âgé", "Oui, un adolescent"],
    textC: 1,
    img: ["Petit garçon", "Homme âgé", "Adolescent"],
    imgC: 1,
    fillQ: "Il porte un ___ et fume la pipe.",
    fill: "dentier",
    fillA: ["dentier"],
  },
  {
    id: "sar19-q9",
    textQ: "Qui est hébergé dans le gîte en ce moment ?",
    text: ["Des scouts", "Des personnes à mobilité réduite", "Des étudiants"],
    textC: 1,
    img: ["Scouts", "Mobilité réduite", "Étudiants"],
    imgC: 1,
    fillQ: "Un groupe de touristes est ___ dans le gîte.",
    fill: "hébergé",
    fillA: ["heberge", "hébergé"],
  },
  {
    id: "sar19-q10",
    textQ: "Comment le livre surprend-il le lecteur au sujet de Kevin ?",
    text: ["Kevin est un animal", "On découvre qu'il n'est pas un enfant", "Kevin ne parle pas"],
    textC: 1,
    img: ["Animal", "Pas un enfant", "Ne parle pas"],
    imgC: 1,
    fillQ: "Certains détails font poser des questions sur son ___ .",
    fill: "âge",
    fillA: ["age", "âge"],
  },
  {
    id: "sar19-q11",
    textQ: "Quel accessoire Kevin porte-t-il de façon amusante ?",
    text: ["Des bottes de ski", "Des pantoufles à carreaux", "Un casque de vélo"],
    textC: 1,
    img: ["Bottes", "Pantoufles", "Casque"],
    imgC: 1,
    fillQ: "Sa chemise et sa casquette sont aussi à ___ .",
    fill: "carreaux",
    fillA: ["carreaux", "carreau"],
  },
  {
    id: "sar19-q12",
    textQ: "Le ton général du roman est plutôt…",
    text: ["Effrayant", "Tendre avec quelques scènes drôles", "Uniquement comique"],
    textC: 1,
    img: ["Effrayant", "Tendre et drôle", "Comique"],
    imgC: 1,
    fillQ: "Une jolie ___ naît entre l'homme et les enfants.",
    fill: "complicité",
    fillA: ["complicite", "complicité"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_20 = buildPool("avance", "scolaire-radio-20", [
  {
    id: "sar20-q1",
    textQ: "La journée sans tabac a lieu…",
    text: ["Tous les ans partout dans le monde", "3 fois par an en France", "Tous les 3 ans en France"],
    textC: 0,
    img: ["Mondial annuel", "3×/an France", "3 ans France"],
    imgC: 0,
    fillQ: "C'est la journée ___ tabac.",
    fill: "sans",
    fillA: ["sans"],
  },
  {
    id: "sar20-q2",
    textQ: "Combien de Français fument ?",
    text: ["La moitié", "Plus de la moitié de la population", "Moins de la moitié"],
    textC: 2,
    img: ["Moitié", "Plus de moitié", "Moins de moitié"],
    imgC: 2,
    fillQ: "En France, ___ de la moitié de la population fume encore.",
    fill: "moins",
    fillA: ["moins"],
  },
  {
    id: "sar20-q3",
    textQ: "Quel est le but de cette journée ?",
    text: ["Informer les gens qui fument", "Culpabiliser les fumeurs", "Dénoncer l'industrie du tabac"],
    textC: 0,
    img: ["Informer", "Culpabiliser", "Dénoncer industrie"],
    imgC: 0,
    fillQ: "On informe sur les dangers du ___ .",
    fill: "tabac",
    fillA: ["tabac", "cigarette"],
  },
  {
    id: "sar20-q4",
    textQ: "Qu'est-ce qui est le plus difficile, d'après le journaliste ?",
    text: ["Arrêter de fumer", "Ne pas recommencer", "Se protéger des fumeurs"],
    textC: 1,
    img: ["Arrêter", "Ne pas recommencer", "Se protéger"],
    imgC: 1,
    fillQ: "Le plus dur, c'est de ne pas ___ .",
    fill: "recommencer",
    fillA: ["recommencer", "rechuter"],
  },
  {
    id: "sar20-q5",
    textQ: "Que faut-il éviter de faire pour ne pas recommencer à fumer ?",
    text: ["De sortir, d'aller à des fêtes", "De boire du café", "De fréquenter des personnes qui fument"],
    textC: 0,
    img: ["Fêtes", "Café", "Fumeurs"],
    imgC: 0,
    fillQ: "Il ne faut pas boire de ___ non plus.",
    fill: "café",
    fillA: ["cafe", "café"],
  },
  {
    id: "sar20-q6",
    textQ: "Selon le médecin, l'arrêt du tabac est…",
    text: ["Seulement psychologique", "Lié à la dépendance", "Lié à la psychologie et à la dépendance"],
    textC: 2,
    img: ["Psychologique", "Dépendance", "Les deux"],
    imgC: 2,
    fillQ: "Il faut souvent de l'___ pour arrêter.",
    fill: "aide",
    fillA: ["aide", "courage"],
  },
  {
    id: "sar20-q7",
    textQ: "Selon la journaliste, arrêter de fumer a un autre avantage, lequel ?",
    text: ["Dépenser moins d'argent", "Avoir une meilleure haleine", "Vivre plus longtemps"],
    textC: 0,
    img: ["Moins d'argent", "Haleine", "Vivre longtemps"],
    imgC: 0,
    fillQ: "Le tabac ___ cher.",
    fill: "coûte",
    fillA: ["coute", "coûte"],
  },
  {
    id: "sar20-q8",
    textQ: "Pourquoi éviter le café quand on arrête de fumer ?",
    text: ["Parce qu'il donne envie d'une cigarette", "Parce qu'il est interdit", "Parce qu'il rend malade"],
    textC: 0,
    img: ["Envie cigarette", "Interdit", "Malade"],
    imgC: 0,
    fillQ: "Le café peut donner ___ d'une cigarette.",
    fill: "envie",
    fillA: ["envie"],
  },
  {
    id: "sar20-q9",
    textQ: "Que conseille-t-on aux personnes qui veulent arrêter ?",
    text: ["Fumer moins seulement", "Éviter les situations où l'on fume", "Acheter des cigarettes light"],
    textC: 1,
    img: ["Fumer moins", "Éviter situations", "Cigarettes light"],
    imgC: 1,
    fillQ: "Il faut éviter de fréquenter des personnes qui ___ .",
    fill: "fument",
    fillA: ["fument", "fume"],
  },
  {
    id: "sar20-q10",
    textQ: "Combien peut-on économiser en arrêtant de fumer ?",
    text: ["Rien du tout", "Plusieurs centaines d'euros par an", "Quelques euros par mois seulement"],
    textC: 1,
    img: ["Rien", "Centaines €/an", "Quelques €"],
    imgC: 1,
    fillQ: "On peut ___ beaucoup d'argent.",
    fill: "économiser",
    fillA: ["economiser", "économiser", "gagner"],
  },
  {
    id: "sar20-q11",
    textQ: "Quel est le premier défi pour un fumeur ?",
    text: ["Trouver un médecin", "Arrêter de fumer", "Changer de travail"],
    textC: 1,
    img: ["Médecin", "Arrêter", "Travail"],
    imgC: 1,
    fillQ: "Arrêter de fumer, c'est ___ .",
    fill: "difficile",
    fillA: ["difficile", "dur"],
  },
  {
    id: "sar20-q12",
    textQ: "Sur quoi porte surtout l'information de la journée sans tabac ?",
    text: ["Les prix des cigarettes", "Les dangers du tabac", "Les nouvelles marques"],
    textC: 1,
    img: ["Prix", "Dangers", "Marques"],
    imgC: 1,
    fillQ: "La journée aide aussi les fumeurs à ___ .",
    fill: "arrêter",
    fillA: ["arreter", "arrêter"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_21 = buildPool("avance", "scolaire-radio-21", [
  {
    id: "sar21-q1",
    textQ: "De quel type de jeu vidéo parle-t-on ?",
    text: ["Un jeu de course", "Un jeu de football", "Un jeu de stratégie"],
    textC: 1,
    img: ["Course", "Football", "Stratégie"],
    imgC: 1,
    fillQ: "Les développeurs ont tenu une conférence de ___ .",
    fill: "presse",
    fillA: ["presse"],
  },
  {
    id: "sar21-q2",
    textQ: "Lors de la conférence, les développeurs ont parlé…",
    text: ["Des modifications du jeu", "De la concurrence", "Des nouvelles consoles de jeu vidéo"],
    textC: 0,
    img: ["Modifications", "Concurrence", "Consoles"],
    imgC: 0,
    fillQ: "Ils ont surtout parlé des ___ apportées au jeu.",
    fill: "modifications",
    fillA: ["modifications", "modification", "changements"],
  },
  {
    id: "sar21-q3",
    textQ: "Combien de ventes pendant la première semaine ?",
    text: ["1 million", "Plus de 10 millions", "100 000"],
    textC: 1,
    img: ["1 M", "10 M+", "100 k"],
    imgC: 1,
    fillQ: "Depuis le lancement, on compte ___ millions de ventes.",
    fill: "25",
    fillA: ["25", "vingt-cinq"],
  },
  {
    id: "sar21-q4",
    textQ: "Combien de parties ont été jouées sur Internet ?",
    text: ["1 million", "10 millions", "Plus de 100 millions"],
    textC: 2,
    img: ["1 M", "10 M", "100 M+"],
    imgC: 2,
    fillQ: "Plus de 100 millions de parties ont été jouées sur ___ .",
    fill: "Internet",
    fillA: ["internet", "Internet", "ligne", "en ligne"],
  },
  {
    id: "sar21-q5",
    textQ: "La nouvelle version du jeu devrait…",
    text: ["Beaucoup ressembler à l'ancienne version", "Être assez différente de l'ancienne version", "Être très différente de l'ancienne version"],
    textC: 1,
    img: ["Ressemble", "Assez différente", "Très différente"],
    imgC: 1,
    fillQ: "La nouvelle version sera assez ___ de l'ancienne.",
    fill: "différente",
    fillA: ["differente", "différente"],
  },
  {
    id: "sar21-q6",
    textQ: "Les créateurs du jeu ont voulu…",
    text: ["Faire courir les joueurs plus vite", "Créer davantage de joueurs et d'équipes", "Rendre les actions des personnages plus réalistes"],
    textC: 2,
    img: ["Plus vite", "Plus d'équipes", "Plus réaliste"],
    imgC: 2,
    fillQ: "Les joueurs passent le ballon de façon plus ___ .",
    fill: "naturelle",
    fillA: ["naturelle", "naturel", "realiste", "réaliste"],
  },
  {
    id: "sar21-q7",
    textQ: "Quelle amélioration annonce le journaliste ?",
    text: ["Le graphisme est meilleur", "L'animation est meilleure", "Le prix est plus bas"],
    textC: 0,
    img: ["Graphisme", "Animation", "Prix"],
    imgC: 0,
    fillQ: "Les stades et les visages sont plus ___ .",
    fill: "beaux",
    fillA: ["beaux", "belles", "jolis"],
  },
  {
    id: "sar21-q8",
    textQ: "Quels éléments du jeu sont plus fluides ?",
    text: ["Les menus seulement", "Les mouvements", "Les commentaires"],
    textC: 1,
    img: ["Menus", "Mouvements", "Commentaires"],
    imgC: 1,
    fillQ: "Les mouvements sont plus ___ qu'avant.",
    fill: "fluides",
    fillA: ["fluides", "fluide"],
  },
  {
    id: "sar21-q9",
    textQ: "Les chiffres de vente sont…",
    text: ["Décevants", "Impressionnants", "Inconnus"],
    textC: 1,
    img: ["Décevants", "Impressionnants", "Inconnus"],
    imgC: 1,
    fillQ: "Pendant la première semaine, les ventes sont très ___ .",
    fill: "fortes",
    fillA: ["fortes", "hautes", "importantes"],
  },
  {
    id: "sar21-q10",
    textQ: "Que font les personnages de façon plus réaliste ?",
    text: ["Ils parlent plus", "Ils courent, tirent et passent le ballon", "Ils changent de sport"],
    textC: 1,
    img: ["Parlent", "Courent et tirent", "Changent sport"],
    imgC: 1,
    fillQ: "Les actions des personnages sont plus ___ .",
    fill: "réalistes",
    fillA: ["realistes", "réalistes"],
  },
  {
    id: "sar21-q11",
    textQ: "Quand a eu lieu la conférence ?",
    text: ["Aujourd'hui", "Hier", "La semaine dernière"],
    textC: 1,
    img: ["Aujourd'hui", "Hier", "Semaine dernière"],
    imgC: 1,
    fillQ: "C'était une grande conférence de ___ .",
    fill: "presse",
    fillA: ["presse"],
  },
  {
    id: "sar21-q12",
    textQ: "Qu'est-ce qui est amélioré visuellement dans le jeu ?",
    text: ["Seulement les maillots", "Les stades, les visages et les mouvements", "Uniquement le ballon"],
    textC: 1,
    img: ["Maillots", "Stades et visages", "Ballon"],
    imgC: 1,
    fillQ: "Le ___ est plus beau et plus fluide.",
    fill: "graphisme",
    fillA: ["graphisme", "graphique"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_22 = buildPool("avance", "scolaire-radio-22", [
  {
    id: "sar22-q1",
    textQ: "La zoothérapie à travers la compagnie des animaux peut aider à diminuer le stress…",
    text: ["De personnes qui travaillent trop", "D'adolescents angoissés", "De personnes qui sont seules"],
    textC: 2,
    img: ["Travail", "Ados angoissés", "Personnes seules"],
    imgC: 2,
    fillQ: "On parle aujourd'hui de ___ .",
    fill: "zoothérapie",
    fillA: ["zoothérapie", "zoo therapie"],
  },
  {
    id: "sar22-q2",
    textQ: "Que permet la complicité avec un animal ?",
    text: ["De gagner de l'argent", "De se confier sans craindre le jugement", "D'éviter l'école"],
    textC: 1,
    img: ["Argent", "Se confier", "Éviter école"],
    imgC: 1,
    fillQ: "On peut se confier sans craindre le ___ des autres.",
    fill: "jugement",
    fillA: ["jugement"],
  },
  {
    id: "sar22-q3",
    textQ: "Quelle est la différence entre l'animal et l'homme ?",
    text: ["L'animal est plus fidèle que l'homme", "L'animal est moins affectueux que l'homme", "L'animal ne donne pas d'appréciation"],
    textC: 2,
    img: ["Plus fidèle", "Moins affectueux", "Pas d'appréciation"],
    imgC: 2,
    fillQ: "L'animal n'___ pas.",
    fill: "évalue",
    fillA: ["evalue", "évalue", "juge"],
  },
  {
    id: "sar22-q4",
    textQ: "Qu'est-ce qui aide à se concentrer ?",
    text: ["Communiquer avec un animal", "Promener un animal", "Caresser un animal"],
    textC: 0,
    img: ["Communiquer", "Promener", "Caresser"],
    imgC: 0,
    fillQ: "Cela aide à se concentrer sur le moment ___ .",
    fill: "présent",
    fillA: ["present", "présent"],
  },
  {
    id: "sar22-q5",
    textQ: "Citez deux avantages de la compagnie d'un animal pour les enfants.",
    text: ["Confiance en soi et calme", "Richesse et célébrité", "Vitesse et force"],
    textC: 0,
    img: ["Confiance et calme", "Richesse", "Vitesse"],
    imgC: 0,
    fillQ: "La présence d'un animal développe la confiance en ___ .",
    fill: "soi",
    fillA: ["soi"],
  },
  {
    id: "sar22-q6",
    textQ: "Avec quel animal la zoothérapie fonctionne le mieux ?",
    text: ["Le chien", "Le chat", "Avec n'importe quel animal"],
    textC: 2,
    img: ["Chien", "Chat", "N'importe quel"],
    imgC: 2,
    fillQ: "Le ___ est souvent utilisé car il est très sociable.",
    fill: "chien",
    fillA: ["chien"],
  },
  {
    id: "sar22-q7",
    textQ: "Le ronronnement du chat et le caresser ont des effets positifs, lesquels ?",
    text: ["Ils rendent plus nerveux", "Ils détendent et réduisent l'anxiété", "Ils empêchent de dormir"],
    textC: 1,
    img: ["Nerveux", "Détendent", "Empêchent dormir"],
    imgC: 1,
    fillQ: "Caresser un chat ___ l'anxiété.",
    fill: "réduit",
    fillA: ["reduit", "réduit", "diminue"],
  },
  {
    id: "sar22-q8",
    textQ: "Pourquoi le chien est-il souvent utilisé ?",
    text: ["Parce qu'il est très sociable", "Parce qu'il est le plus grand", "Parce qu'il ne mange rien"],
    textC: 0,
    img: ["Sociable", "Grand", "Ne mange rien"],
    imgC: 0,
    fillQ: "Le chien est très ___ .",
    fill: "sociable",
    fillA: ["sociable"],
  },
  {
    id: "sar22-q9",
    textQ: "Chez qui la zoothérapie peut-elle réduire le stress ?",
    text: ["Uniquement chez les enfants", "Chez des personnes seules et des adolescents angoissés", "Seulement chez les médecins"],
    textC: 1,
    img: ["Enfants seuls", "Seuls et ados", "Médecins"],
    imgC: 1,
    fillQ: "Elle aide à diminuer le ___ .",
    fill: "stress",
    fillA: ["stress"],
  },
  {
    id: "sar22-q10",
    textQ: "Qu'apporte un animal aux enfants en plus de la confiance ?",
    text: ["Du calme", "De la colère", "De la fatigue"],
    textC: 0,
    img: ["Calme", "Colère", "Fatigue"],
    imgC: 0,
    fillQ: "Un animal apporte aussi du ___ .",
    fill: "calme",
    fillA: ["calme", "serenite", "sérénité"],
  },
  {
    id: "sar22-q11",
    textQ: "Pourquoi parle-t-on facilement à un animal ?",
    text: ["Parce qu'il répond toujours", "Parce qu'il ne juge pas", "Parce qu'il connaît tout"],
    textC: 1,
    img: ["Répond", "Ne juge pas", "Connaît tout"],
    imgC: 1,
    fillQ: "L'animal ne donne pas d'___ .",
    fill: "appréciation",
    fillA: ["appreciation", "appréciation"],
  },
  {
    id: "sar22-q12",
    textQ: "Quel effet le ronronnement du chat produit-il ?",
    text: ["Il agresse", "Il détend", "Il fait peur"],
    textC: 1,
    img: ["Agresse", "Détend", "Fait peur"],
    imgC: 1,
    fillQ: "Le ronronnement du chat a des effets ___ .",
    fill: "positifs",
    fillA: ["positifs", "positif", "benefiques", "bénéfiques"],
  },
]);

export const SCOLAIRE_AVANCE_RADIO_23 = buildPool("avance", "scolaire-radio-23", [
  {
    id: "sar23-q1",
    textQ: "Que dénonce-t-on dans ce bulletin ?",
    text: ["La transformation des aliments par les industriels", "Le manque d'information sur les produits transformés", "L'indifférence des consommateurs à la manipulation des aliments"],
    textC: 0,
    img: ["Transformation", "Manque info", "Indifférence"],
    imgC: 0,
    fillQ: "On dénonce la ___ des aliments.",
    fill: "transformation",
    fillA: ["transformation"],
  },
  {
    id: "sar23-q2",
    textQ: "« Le goût s'invente dans des éprouvettes » signifie que…",
    text: ["On vend des aliments dans des petits tubes", "Le goût des aliments est de plus en plus artificiel", "On apprend le goût aux enfants dès leur naissance"],
    textC: 1,
    img: ["Petits tubes", "Artificiel", "Apprendre goût"],
    imgC: 1,
    fillQ: "Le goût est de plus en plus ___ .",
    fill: "artificiel",
    fillA: ["artificiel", "artificielle"],
  },
  {
    id: "sar23-q3",
    textQ: "Pourquoi ajoute-t-on du sucre dans les produits industriels ?",
    text: ["Pour que les gens aient toujours envie de les manger", "Pour les gens qui souffrent du manque de sucre", "Pour que les aliments soient moins acides"],
    textC: 0,
    img: ["Toujours envie", "Manque sucre", "Moins acides"],
    imgC: 0,
    fillQ: "Le sucre donne toujours ___ de manger.",
    fill: "envie",
    fillA: ["envie"],
  },
  {
    id: "sar23-q4",
    textQ: "On transforme le goût en ajoutant du sucre mais aussi en ajoutant quels éléments ?",
    text: ["Du sel, des matières grasses et des arômes", "De l'eau et du lait seulement", "Des vitamines uniquement"],
    textC: 0,
    img: ["Sel et arômes", "Eau et lait", "Vitamines"],
    imgC: 0,
    fillQ: "On ajoute aussi du ___ et des arômes.",
    fill: "sel",
    fillA: ["sel"],
  },
  {
    id: "sar23-q5",
    textQ: "Que risque-t-on si on mange trop d'aliments transformés ?",
    text: ["Rien de grave", "Des problèmes de santé comme le surpoids", "De devenir plus sportif"],
    textC: 1,
    img: ["Rien", "Surpoids", "Plus sportif"],
    imgC: 1,
    fillQ: "On risque des problèmes de ___ .",
    fill: "santé",
    fillA: ["sante", "santé", "surpoids"],
  },
  {
    id: "sar23-q6",
    textQ: "Que font les consommateurs pour résister à ce phénomène ?",
    text: ["Ils achètent des produits biologiques", "Ils cultivent leurs propres légumes", "Ils font un régime"],
    textC: 0,
    img: ["Bio", "Cultivent légumes", "Régime"],
    imgC: 0,
    fillQ: "Certains cultivent aussi leurs propres ___ .",
    fill: "légumes",
    fillA: ["legumes", "légumes"],
  },
  {
    id: "sar23-q7",
    textQ: "En conclusion, l'auteur veut dire que…",
    text: ["Si on veut bien manger on peut, c'est nous qui décidons", "Finalement les produits industriels ne sont pas tous mauvais", "Les laboratoires auront toujours plus de pouvoir sur notre alimentation"],
    textC: 0,
    img: ["Nous décidons", "Pas tous mauvais", "Labos puissants"],
    imgC: 0,
    fillQ: "C'est nous qui décidons de ce que nous mettons dans notre ___ .",
    fill: "assiette",
    fillA: ["assiette"],
  },
  {
    id: "sar23-q8",
    textQ: "Pourquoi les industriels ajoutent-ils des arômes ?",
    text: ["Pour rendre le goût artificiel et attractif", "Pour conserver les vitamines", "Pour réduire le prix"],
    textC: 0,
    img: ["Goût attractif", "Vitamines", "Prix"],
    imgC: 0,
    fillQ: "On transforme le goût avec du sucre, du sel et des matières ___ .",
    fill: "grasses",
    fillA: ["grasses", "grasse"],
  },
  {
    id: "sar23-q9",
    textQ: "Quelle attitude adoptent de plus en plus de consommateurs ?",
    text: ["Ils mangent plus de produits transformés", "Ils achètent bio ou cultivent leurs légumes", "Ils arrêtent de manger"],
    textC: 1,
    img: ["Plus transformés", "Bio ou jardin", "Arrêtent manger"],
    imgC: 1,
    fillQ: "Ils achètent des produits ___ .",
    fill: "biologiques",
    fillA: ["biologiques", "bio"],
  },
  {
    id: "sar23-q10",
    textQ: "Que signifie l'expression sur les éprouvettes ?",
    text: ["Le goût est créé artificiellement en laboratoire", "Les aliments sont vendus en pharmacie", "Les enfants font des expériences"],
    textC: 0,
    img: ["Laboratoire", "Pharmacie", "Expériences"],
    imgC: 0,
    fillQ: "Le goût s'invente dans des ___ .",
    fill: "éprouvettes",
    fillA: ["eprouvettes", "éprouvettes"],
  },
  {
    id: "sar23-q11",
    textQ: "Qui est responsable de nos choix alimentaires selon l'auteur ?",
    text: ["Les laboratoires", "Les industriels", "Nous-mêmes"],
    textC: 2,
    img: ["Laboratoires", "Industriels", "Nous"],
    imgC: 2,
    fillQ: "Si on veut bien manger, on ___ .",
    fill: "peut",
    fillA: ["peut"],
  },
  {
    id: "sar23-q12",
    textQ: "Quel est l'objectif principal du bulletin ?",
    text: ["Faire de la publicité", "Dénoncer la manipulation des aliments industriels", "Vendre des éprouvettes"],
    textC: 1,
    img: ["Publicité", "Dénoncer", "Vendre"],
    imgC: 1,
    fillQ: "Les industriels ___ beaucoup les aliments.",
    fill: "transforment",
    fillA: ["transforment", "modifient"],
  },
]);

export const SCOLAIRE_AVANCE_RADIOS_BOOK: Record<string, COMultiQuestion[]> = {
  "avance-scolaire-radio-15": SCOLAIRE_AVANCE_RADIO_15,
  "avance-scolaire-radio-16": SCOLAIRE_AVANCE_RADIO_16,
  "avance-scolaire-radio-17": SCOLAIRE_AVANCE_RADIO_17,
  "avance-scolaire-radio-18": SCOLAIRE_AVANCE_RADIO_18,
  "avance-scolaire-radio-19": SCOLAIRE_AVANCE_RADIO_19,
  "avance-scolaire-radio-20": SCOLAIRE_AVANCE_RADIO_20,
  "avance-scolaire-radio-21": SCOLAIRE_AVANCE_RADIO_21,
  "avance-scolaire-radio-22": SCOLAIRE_AVANCE_RADIO_22,
  "avance-scolaire-radio-23": SCOLAIRE_AVANCE_RADIO_23,
};
