import { buildPool, type COMultiQuestion } from "./co-questions-helpers";

/** CO avancé scolaire / B1 — radios (exercices 15 à 17). */

export const SCOLAIRE_AVANCE_RADIO_15 = buildPool("avance", "scolaire-radio-15", [
  {
    id: "sar15-q1",
    textQ: "Combien de temps a réellement duré la pause de M. Pokora, selon lui ?",
    text: ["2 mois", "1 an", "2 ans"],
    textC: 0,
    img: ["2 mois", "1 an", "2 ans"],
    imgC: 0,
    fillQ: "Pendant sa pause, il a quand même créé ___ titres.",
    fill: "16",
    fillA: ["16", "seize"],
  },
  {
    id: "sar15-q2",
    textQ: "Combien de titres compte le nouvel album de M. Pokora ?",
    text: ["12 titres", "16 titres", "20 titres"],
    textC: 1,
    img: ["12", "16", "20"],
    imgC: 1,
    fillQ: "Son album précédent « My Way » a vendu plus de 600 000 ___ .",
    fill: "exemplaires",
    fillA: ["exemplaires", "exemplaire", "copies"],
  },
  {
    id: "sar15-q3",
    textQ: "L'idée de son nouvel album lui est venue…",
    text: ["En voyageant en Égypte", "En regardant la télévision", "En lisant une bande dessinée de super-héros"],
    textC: 1,
    img: ["Égypte", "Télévision", "BD super-héros"],
    imgC: 1,
    fillQ: "Il regardait un documentaire sur les ___ .",
    fill: "pyramides",
    fillA: ["pyramides", "pyramide"],
  },
  {
    id: "sar15-q4",
    textQ: "Citez deux effets spéciaux présents dans le concert.",
    text: ["Pluie et neige artificielles", "Feux d'artifice et lasers", "Fumée et projecteurs seulement"],
    textC: 1,
    img: ["Pluie et neige", "Feux et lasers", "Fumée"],
    imgC: 1,
    fillQ: "Il y a aussi beaucoup de ___ sur scène.",
    fill: "danse",
    fillA: ["danse", "danser"],
  },
  {
    id: "sar15-q5",
    textQ: "Qu'est-ce qui manquait à M. Pokora ?",
    text: ["La danse", "Le théâtre", "Les films futuristes"],
    textC: 0,
    img: ["Danse", "Théâtre", "Films"],
    imgC: 0,
    fillQ: "Les décors de concert sont très ___ .",
    fill: "impressionnants",
    fillA: ["impressionnants", "impressionnant", "grands"],
  },
  {
    id: "sar15-q6",
    textQ: "Dans l'album Pyramide, M. Pokora…",
    text: ["Reprend des chansons d'autres chanteurs", "Parle de lui", "Parle de la vie des chanteurs"],
    textC: 1,
    img: ["Reprises", "Parle de lui", "Vie des chanteurs"],
    imgC: 1,
    fillQ: "Il voulait quelque chose de plus ___ .",
    fill: "personnel",
    fillA: ["personnel", "personnelle", "intime"],
  },
  {
    id: "sar15-q7",
    textQ: "Pyramide est…",
    text: ["Le titre de sa chanson préférée", "Le titre de son premier album", "Le titre de l'album et d'une de ses chansons"],
    textC: 2,
    img: ["Chanson préférée", "Premier album", "Album et chanson"],
    imgC: 2,
    fillQ: "L'album imagine un monde un peu ___ .",
    fill: "futuriste",
    fillA: ["futuriste", "fantastique"],
  },
  {
    id: "sar15-q8",
    textQ: "Qu'est-ce qui a aussi inspiré l'album ?",
    text: ["Des films de super-héros", "Un voyage en montagne", "Un concert de jazz"],
    textC: 0,
    img: ["Films super-héros", "Montagne", "Jazz"],
    imgC: 0,
    fillQ: "Il a regardé plusieurs films de ___ .",
    fill: "super-héros",
    fillA: ["super-heros", "super-héros", "heros", "héros"],
  },
  {
    id: "sar15-q9",
    textQ: "Pourquoi M. Pokora a-t-il repris l'écriture après sa pause ?",
    text: ["Parce qu'il s'ennuyait", "Parce qu'il avait un contrat", "Parce qu'il déteste la télévision"],
    textC: 0,
    img: ["Ennui", "Contrat", "Déteste TV"],
    imgC: 0,
    fillQ: "Ne plus rien faire ne lui ___ pas.",
    fill: "ressemblait",
    fillA: ["ressemblait", "correspondait"],
  },
  {
    id: "sar15-q10",
    textQ: "De quoi M. Pokora parle-t-il sans filtre dans Pyramide ?",
    text: ["De ses voyages", "De ses doutes", "Des autres chanteurs"],
    textC: 1,
    img: ["Voyages", "Doutes", "Autres chanteurs"],
    imgC: 1,
    fillQ: "Avant, il chantait longtemps les textes des ___ .",
    fill: "autres",
    fillA: ["autres", "autre"],
  },
  {
    id: "sar15-q11",
    textQ: "Quel classement Pyramide a-t-il atteint ?",
    text: ["Dixième des albums français", "Premier des albums français les plus vendus", "Il n'est pas entré au classement"],
    textC: 1,
    img: ["10e", "1er", "Hors classement"],
    imgC: 1,
    fillQ: "Pendant sa pause, il s'est posé beaucoup de ___ .",
    fill: "questions",
    fillA: ["questions", "question"],
  },
  {
    id: "sar15-q12",
    textQ: "Quelle question M. Pokora s'est-il posée pendant sa pause ?",
    text: ["S'il allait continuer sa carrière de chanteur", "S'il allait déménager", "S'il allait apprendre la danse"],
    textC: 0,
    img: ["Continuer chanteur", "Déménager", "Apprendre danse"],
    imgC: 0,
    fillQ: "Il se demandait ce qu'il dirait s'il ne lui restait que trois ___ .",
    fill: "minutes",
    fillA: ["minutes", "minute"],
  },
  {
    id: "sar15-q13",
    textQ: "Combien d'exemplaires l'album « My Way » a-t-il vendus ?",
    text: ["Plus de 600 000", "Plus de 100 000", "Plus de 1 million"],
    textC: 0,
    img: ["600 000", "100 000", "1 M"],
    imgC: 0,
    fillQ: "« My Way » a vendu plus de 600 000 ___.",
    fill: "exemplaires",
    fillA: ["exemplaires", "exemplaire"],
  },
  {
    id: "sar15-q14",
    textQ: "Quel type de films M. Pokora a-t-il regardés après le documentaire ?",
    text: ["Des films de super-héros", "Des films d'horreur", "Des comédies romantiques"],
    textC: 0,
    img: ["Super-héros", "Horreur", "Romance"],
    imgC: 0,
    fillQ: "Il a regardé plusieurs films de ___.",
    fill: "super-héros",
    fillA: ["super-heros", "super-héros"],
  },
  {
    id: "sar15-q15",
    textQ: "Pyramide est devenue le titre de l'album et d'une…",
    text: ["Chanson", "Tournée", "Émission de télévision"],
    textC: 0,
    img: ["Chanson", "Tournée", "Télévision"],
    imgC: 0,
    fillQ: "Pyramide, qui est également devenue le titre de l'album et d'une ___.",
    fill: "chanson",
    fillA: ["chanson"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_16 = buildPool("avance", "scolaire-radio-16", [
  {
    id: "sar16-q1",
    textQ: "Dans cette émission, le journaliste parle de la vie de…",
    text: ["Deux adolescents qui ont des journées différentes", "Deux adolescents qui ont des loisirs différents", "Deux adolescents de pays différents"],
    textC: 0,
    img: ["Journées différentes", "Loisirs différents", "Pays différents"],
    imgC: 0,
    fillQ: "L'émission s'appelle « Graines de ___ ».",
    fill: "jeunes",
    fillA: ["jeunes", "jeune"],
  },
  {
    id: "sar16-q2",
    textQ: "Comment Eddy définit-il sa vie ?",
    text: ["Stressante et bruyante", "Calme et sereine", "Toujours en voyage"],
    textC: 1,
    img: ["Stressante", "Calme et sereine", "Voyage"],
    imgC: 1,
    fillQ: "Eddy dit que c'est parfois trop ___ .",
    fill: "calme",
    fillA: ["calme", "serin", "serein"],
  },
  {
    id: "sar16-q3",
    textQ: "Où habite Béa ?",
    text: ["Dans une petite ville de Bretagne", "Au cœur d'une grande île", "Dans une grande ville"],
    textC: 2,
    img: ["Petite ville Bretagne", "Grande île", "Grande ville"],
    imgC: 2,
    fillQ: "Béa définit sa vie avec les mots stress et quotidien ___ .",
    fill: "rempli",
    fillA: ["rempli", "plein", "charge"],
  },
  {
    id: "sar16-q4",
    textQ: "Comment Eddy va-t-il au collège le matin ?",
    text: ["En bus", "En bateau", "À vélo"],
    textC: 1,
    img: ["Bus", "Bateau", "Vélo"],
    imgC: 1,
    fillQ: "Il n'y a pas de collège sur son ___ .",
    fill: "île",
    fillA: ["ile", "île"],
  },
  {
    id: "sar16-q5",
    textQ: "Combien d'habitants compte l'île d'Eddy ?",
    text: ["Une centaine", "Un millier", "Dix mille"],
    textC: 0,
    img: ["100", "1000", "10000"],
    imgC: 0,
    fillQ: "Les jeunes sur l'île sont très ___ .",
    fill: "peu",
    fillA: ["peu", "peu nombreux"],
  },
  {
    id: "sar16-q6",
    textQ: "Que fait Béa le week-end ?",
    text: ["Elle reste seule à la maison", "Elle sort beaucoup avec ses amis", "Elle étudie toute la journée"],
    textC: 1,
    img: ["Seule", "Sort avec amis", "Étudie"],
    imgC: 1,
    fillQ: "Elle ne passe pas un samedi sans voir ses ___ .",
    fill: "amis",
    fillA: ["amis", "copains", "copines"],
  },
  {
    id: "sar16-q7",
    textQ: "Pourquoi Eddy aime-t-il le trajet du soir en bateau ?",
    text: ["Pour faire ses devoirs", "Pour le bon air de la mer", "Pour regarder la télévision"],
    textC: 1,
    img: ["Devoirs", "Air de la mer", "Télévision"],
    imgC: 1,
    fillQ: "Il aime surtout cela quand arrivent les beaux ___ .",
    fill: "jours",
    fillA: ["jours", "jour"],
  },
  {
    id: "sar16-q8",
    textQ: "Que manque-t-il sur l'île d'Eddy ?",
    text: ["Des plages", "Cinéma, spectacles et shopping", "Des restaurants"],
    textC: 1,
    img: ["Plages", "Cinéma et shopping", "Restaurants"],
    imgC: 1,
    fillQ: "Le soir, il n'y a pas grand-chose à ___ .",
    fill: "faire",
    fillA: ["faire"],
  },
  {
    id: "sar16-q9",
    textQ: "Béa et Eddy aimeraient-ils échanger leur quotidien ?",
    text: ["Non, jamais", "Oui, mais pas pour la vie", "Oui, pour toujours"],
    textC: 1,
    img: ["Jamais", "Oui mais pas pour la vie", "Pour toujours"],
    imgC: 1,
    fillQ: "Béa accompagne le matin son petit ___ à l'école.",
    fill: "frère",
    fillA: ["frere", "frère"],
  },
  {
    id: "sar16-q10",
    textQ: "Combien de temps met Béa pour aller au lycée ?",
    text: ["Dix minutes", "Presque une heure", "Deux heures"],
    textC: 1,
    img: ["10 min", "1 heure", "2 heures"],
    imgC: 1,
    fillQ: "Il y a beaucoup de ___ dans la ville.",
    fill: "trafic",
    fillA: ["trafic", "circulation", "embouteillages"],
  },
  {
    id: "sar16-q11",
    textQ: "Quand l'île d'Eddy est-elle plus animée ?",
    text: ["En hiver", "En été", "Au printemps seulement"],
    textC: 1,
    img: ["Hiver", "Été", "Printemps"],
    imgC: 1,
    fillQ: "L'hiver sur l'île, c'est très très ___ .",
    fill: "calme",
    fillA: ["calme", "silencieux"],
  },
  {
    id: "sar16-q12",
    textQ: "Qu'est-ce que Béa peut faire le week-end en ville ?",
    text: ["Seulement ses devoirs", "Bowling, pizzeria et boutiques", "Rester au lycée"],
    textC: 1,
    img: ["Devoirs", "Bowling et sorties", "Lycée"],
    imgC: 1,
    fillQ: "Eddy apprécie aussi la ___ sur l'île.",
    fill: "solitude",
    fillA: ["solitude", "calme"],
  },
  {
    id: "sar16-q13",
    textQ: "Comment Eddy se rend-il au collège le matin ?",
    text: ["En bateau", "En bus", "À vélo"],
    textC: 0,
    img: ["Bateau", "Bus", "Vélo"],
    imgC: 0,
    fillQ: "Le matin, je prends le ___ pour aller à Quiberon.",
    fill: "bateau",
    fillA: ["bateau"],
  },
  {
    id: "sar16-q14",
    textQ: "Combien d'habitants compte environ l'île d'Eddy ?",
    text: ["Une centaine", "Un millier", "Cinq cents"],
    textC: 0,
    img: ["100", "1000", "500"],
    imgC: 0,
    fillQ: "Il n'y a qu'une centaine d'___.",
    fill: "habitants",
    fillA: ["habitants", "habitant"],
  },
  {
    id: "sar16-q15",
    textQ: "Quand l'île est-elle plus animée ?",
    text: ["En été", "En hiver", "Au printemps"],
    textC: 0,
    img: ["Été", "Hiver", "Printemps"],
    imgC: 0,
    fillQ: "On s'amuse bien l'___ par contre.",
    fill: "été",
    fillA: ["ete", "été"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_17 = buildPool("avance", "scolaire-radio-17", [
  {
    id: "sar17-q1",
    textQ: "Quel type de danse fait Julia ?",
    text: ["Classique", "Moderne", "Contemporaine"],
    textC: 2,
    img: ["Classique", "Moderne", "Contemporaine"],
    imgC: 2,
    fillQ: "Elle suit une formation en danse ___ .",
    fill: "contemporaine",
    fillA: ["contemporaine", "moderne"],
  },
  {
    id: "sar17-q2",
    textQ: "Comment Julia se prépare-t-elle à sa carrière de danseuse ?",
    text: ["En regardant la télévision", "Avec une formation au conservatoire", "En jouant au théâtre"],
    textC: 1,
    img: ["Télévision", "Conservatoire", "Théâtre"],
    imgC: 1,
    fillQ: "Elle se forme dans une école de ___ .",
    fill: "danse",
    fillA: ["danse"],
  },
  {
    id: "sar17-q3",
    textQ: "Comment se sent Julia lorsqu'elle danse devant un public ?",
    text: ["Elle a peur", "Elle se sent très bien", "Elle est nerveuse"],
    textC: 1,
    img: ["Peur", "Très bien", "Nerveuse"],
    imgC: 1,
    fillQ: "Quand le feeling passe avec le public, c'est comme un ___ .",
    fill: "jeu",
    fillA: ["jeu"],
  },
  {
    id: "sar17-q4",
    textQ: "Comment la danse a changé son corps ?",
    text: ["Elle est très musclée", "Elle a beaucoup grandi", "Elle ne grandit presque plus"],
    textC: 2,
    img: ["Musclée", "Beaucoup grandi", "Ne grandit plus"],
    imgC: 2,
    fillQ: "La danse a arrêté totalement sa ___ .",
    fill: "croissance",
    fillA: ["croissance", "taille"],
  },
  {
    id: "sar17-q5",
    textQ: "Quels sont les avantages de la carrière de danseuse ? (Plusieurs réponses possibles.)",
    text: ["Un salaire très élevé", "Voyager et avoir des projets différents", "Ne jamais s'entraîner"],
    textC: 1,
    img: ["Salaire élevé", "Voyager", "Pas d'entraînement"],
    imgC: 1,
    fillQ: "Chaque jour est différent et c'est ___ .",
    fill: "enrichissant",
    fillA: ["enrichissant", "enrichissante", "interessant", "intéressant"],
  },
  {
    id: "sar17-q6",
    textQ: "Depuis quand Julia danse-t-elle ?",
    text: ["Depuis 3 ans", "Depuis 10 ans", "Depuis 15 ans"],
    textC: 1,
    img: ["3 ans", "10 ans", "15 ans"],
    imgC: 1,
    fillQ: "Elle danse depuis qu'elle a ___ ans.",
    fill: "trois",
    fillA: ["trois", "3"],
  },
  {
    id: "sar17-q7",
    textQ: "D'après Julia, que faut-il améliorer dans la carrière de danseuse ?",
    text: ["Il faudrait moins voyager", "Les danseuses devraient être mieux payées", "La carrière devrait être plus courte"],
    textC: 1,
    img: ["Moins voyager", "Mieux payées", "Plus courte"],
    imgC: 1,
    fillQ: "Les salaires sont très ___ en général.",
    fill: "bas",
    fillA: ["bas", "basse", "faibles", "faible"],
  },
  {
    id: "sar17-q8",
    textQ: "Que faut-il faire pour garder l'attention du public ?",
    text: ["Parler très fort", "Le surprendre et rester naturel", "Éviter de le regarder"],
    textC: 1,
    img: ["Parler fort", "Surprendre", "Éviter regard"],
    imgC: 1,
    fillQ: "Il faut réussir à garder son ___ .",
    fill: "attention",
    fillA: ["attention"],
  },
  {
    id: "sar17-q9",
    textQ: "Pourquoi Julia veut-elle être chorégraphe ?",
    text: ["Elle veut diriger des danseurs", "Elle ne veut plus danser", "Elle veut transmettre des messages"],
    textC: 2,
    img: ["Diriger", "Ne plus danser", "Transmettre messages"],
    imgC: 2,
    fillQ: "Elle veut faire passer ses ___ .",
    fill: "idées",
    fillA: ["idees", "idées", "messages"],
  },
  {
    id: "sar17-q10",
    textQ: "Comment Julia définit-elle la danse ?",
    text: ["Un sport sans effort", "Un jeu de mouvements", "Une simple promenade"],
    textC: 1,
    img: ["Sans effort", "Jeu de mouvements", "Promenade"],
    imgC: 1,
    fillQ: "La danse est aussi un ___ .",
    fill: "sport",
    fillA: ["sport"],
  },
  {
    id: "sar17-q11",
    textQ: "Pourquoi le corps s'étire moins en danse contemporaine ?",
    text: ["Parce qu'on danse au sol", "Parce qu'on ne danse jamais", "Parce qu'il n'y a pas de musique"],
    textC: 0,
    img: ["Danse au sol", "Ne danse pas", "Pas de musique"],
    imgC: 0,
    fillQ: "En danse classique, le corps s'étire ___ .",
    fill: "plus",
    fillA: ["plus", "davantage"],
  },
  {
    id: "sar17-q12",
    textQ: "Qu'est-ce qui est difficile dans le parcours de danseur ?",
    text: ["Il ne change jamais", "Ça peut s'arrêter du jour au lendemain", "On ne voyage jamais"],
    textC: 1,
    img: ["Ne change pas", "Arrêt soudain", "Pas de voyage"],
    imgC: 1,
    fillQ: "Sur scène, le moment est ___ pour Julia.",
    fill: "magique",
    fillA: ["magique", "incroyable", "super"],
  },
  {
    id: "sar17-q13",
    textQ: "Où Julia suit-elle sa formation en danse contemporaine ?",
    text: ["Au conservatoire", "À l'université", "Dans un lycée"],
    textC: 0,
    img: ["Conservatoire", "Université", "Lycée"],
    imgC: 0,
    fillQ: "Elle suit une formation en danse contemporaine au ___.",
    fill: "conservatoire",
    fillA: ["conservatoire"],
  },
  {
    id: "sar17-q14",
    textQ: "Pourquoi le corps s'étire moins en danse contemporaine ?",
    text: ["Parce qu'on danse au sol", "Parce qu'on saute beaucoup", "Parce qu'on porte des pointes"],
    textC: 0,
    img: ["Au sol", "Sauts", "Pointes"],
    imgC: 0,
    fillQ: "En danse contemporaine on danse au ___.",
    fill: "sol",
    fillA: ["sol"],
  },
  {
    id: "sar17-q15",
    textQ: "Quel métier Julia aimerait-elle exercer plus tard ?",
    text: ["Chorégraphe", "Professeure", "Journaliste"],
    textC: 0,
    img: ["Chorégraphe", "Professeure", "Journaliste"],
    imgC: 0,
    fillQ: "Plus tard, j'aimerais être ___.",
    fill: "chorégraphe",
    fillA: ["choregraphe", "chorégraphe"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_18 = buildPool("avance", "scolaire-radio-18", [
  {
    id: "sar18-q1",
    textQ: "Le thème de cette émission est…",
    text: ["L'identité et le look chez les jeunes", "L'image des jeunes sur Internet", "Le changement permanent de la mode"],
    textC: 0,
    img: ["Identité et look", "Image Internet", "Mode"],
    imgC: 0,
    fillQ: "Ce soir, on parle du ___ vestimentaire.",
    fill: "look",
    fillA: ["look", "style"],
  },
  {
    id: "sar18-q2",
    textQ: "Élodie et Guillaume…",
    text: ["Ont la même opinion", "Ont une opinion différente", "N'ont pas d'opinion"],
    textC: 1,
    img: ["Même opinion", "Opinion différente", "Pas d'opinion"],
    imgC: 1,
    fillQ: "Guillaume n'est pas ___ avec Élodie.",
    fill: "d'accord",
    fillA: ["d'accord", "daccord"],
  },
  {
    id: "sar18-q3",
    textQ: "Que cherche Élodie ?",
    text: ["À appartenir à un groupe", "À être elle-même sans look particulier", "À copier la mode punk"],
    textC: 1,
    img: ["Groupe", "Être elle-même", "Mode punk"],
    imgC: 1,
    fillQ: "Elle veut être ___ , tout simplement.",
    fill: "elle-même",
    fillA: ["elle-meme", "elle-même", "moi-meme", "moi-même"],
  },
  {
    id: "sar18-q4",
    textQ: "Pourquoi Guillaume veut-il garder son look ?",
    text: ["Il pense que c'est son identité", "Il n'aime aucun autre look", "Il a toujours eu ce look"],
    textC: 0,
    img: ["Identité", "Pas autre look", "Toujours eu"],
    imgC: 0,
    fillQ: "Pour lui, c'est son ___ .",
    fill: "identité",
    fillA: ["identite", "identité"],
  },
  {
    id: "sar18-q5",
    textQ: "Quel style de look Guillaume évoque-t-il ?",
    text: ["Classique", "Punk", "Sportif"],
    textC: 1,
    img: ["Classique", "Punk", "Sportif"],
    imgC: 1,
    fillQ: "Il dit qu'il ne sera pas ___ toute sa vie.",
    fill: "punk",
    fillA: ["punk"],
  },
  {
    id: "sar18-q6",
    textQ: "Guillaume imagine que plus tard il sera…",
    text: ["Toujours le même", "Peut-être différent", "Comme son père"],
    textC: 1,
    img: ["Toujours pareil", "Peut-être différent", "Comme père"],
    imgC: 1,
    fillQ: "Peut-être un jour, il changera de ___ .",
    fill: "style",
    fillA: ["style", "mode", "look"],
  },
  {
    id: "sar18-q7",
    textQ: "Du point de vue de Guillaume…",
    text: ["Tout le monde fait partie d'un groupe", "Faire partie d'un groupe n'a pas d'importance", "Quand on a un look, c'est pour la vie"],
    textC: 0,
    img: ["Toujours un groupe", "Pas important", "Pour la vie"],
    imgC: 0,
    fillQ: "Même quand on veut être « ___ », on appartient à un groupe.",
    fill: "neutre",
    fillA: ["neutre"],
  },
  {
    id: "sar18-q8",
    textQ: "Que pense Élodie sur l'appartenance à un groupe ?",
    text: ["Il faut absolument un groupe", "On n'a pas besoin d'un groupe pour exister", "Seuls les punks ont une identité"],
    textC: 1,
    img: ["Faut un groupe", "Pas besoin", "Seuls punks"],
    imgC: 1,
    fillQ: "On n'a pas besoin de faire partie d'un ___ pour exister.",
    fill: "groupe",
    fillA: ["groupe"],
  },
  {
    id: "sar18-q9",
    textQ: "Quelle importance Élodie donne-t-elle au look ?",
    text: ["Une importance capitale", "Strictement aucune", "Seulement pour les fêtes"],
    textC: 1,
    img: ["Capitale", "Aucune", "Fêtes seulement"],
    imgC: 1,
    fillQ: "Elle ne cherche pas à avoir un look ___ .",
    fill: "précis",
    fillA: ["precis", "précis", "particulier"],
  },
  {
    id: "sar18-q10",
    textQ: "Si Guillaume changeait de look, que craint-il ?",
    text: ["De perdre ses amis uniquement", "Que les gens le regardent différemment", "De ne plus pouvoir sortir"],
    textC: 1,
    img: ["Perdre amis", "Regard différent", "Ne plus sortir"],
    imgC: 1,
    fillQ: "Il faudrait qu'il s'___ comme il est.",
    fill: "accepte",
    fillA: ["accepte"],
  },
  {
    id: "sar18-q11",
    textQ: "Pourquoi Guillaume fait-il attention à son image ?",
    text: ["Par obligation parentale", "Parce que c'est important pour lui", "Pour ressembler à Élodie"],
    textC: 1,
    img: ["Obligation", "Important pour lui", "Ressembler Élodie"],
    imgC: 1,
    fillQ: "Il veut garder son ___ .",
    fill: "style",
    fillA: ["style", "look", "image"],
  },
  {
    id: "sar18-q12",
    textQ: "Que répond Guillaume à Élodie sur les groupes « neutres » ?",
    text: ["Ils n'existent pas", "C'est aussi un groupe", "C'est mieux que le punk"],
    textC: 1,
    img: ["N'existent pas", "Aussi un groupe", "Mieux que punk"],
    imgC: 1,
    fillQ: "Ceux qui ne veulent appartenir à aucun groupe font partie d'un groupe ___ .",
    fill: "aussi",
    fillA: ["aussi", "egalement", "également"],
  },
  {
    id: "sar18-q13",
    textQ: "Pour Guillaume, son look vestimentaire représente son…",
    text: ["Identité", "École", "Travail"],
    textC: 0,
    img: ["Identité", "École", "Travail"],
    imgC: 0,
    fillQ: "Pour moi, c'est mon ___.",
    fill: "identité",
    fillA: ["identite", "identité"],
  },
  {
    id: "sar18-q14",
    textQ: "Que veut être Élodie sans suivre un look précis ?",
    text: ["Elle-même", "Comme tout le monde", "Invisible"],
    textC: 0,
    img: ["Elle-même", "Comme tous", "Invisible"],
    imgC: 0,
    fillQ: "Je veux être moi-même, tout ___.",
    fill: "simplement",
    fillA: ["simplement"],
  },
  {
    id: "sar18-q15",
    textQ: "Guillaume pense qu'il y a un âge pour…",
    text: ["Tout", "Rien", "Les études seulement"],
    textC: 0,
    img: ["Tout", "Rien", "Études"],
    imgC: 0,
    fillQ: "Je pense qu'il y a un âge pour ___.",
    fill: "tout",
    fillA: ["tout"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_19 = buildPool("avance", "scolaire-radio-19", [
  {
    id: "sar19-q1",
    textQ: "Cette émission présente des livres pour…",
    text: ["Les enfants de moins de 10 ans", "Les adolescents", "Les adultes"],
    textC: 1,
    img: ["-10 ans", "Adolescents", "Adultes"],
    imgC: 1,
    fillQ: "L'émission s'appelle La bibliothèque des ___ .",
    fill: "ados",
    fillA: ["ados"],
  },
  {
    id: "sar19-q2",
    textQ: "Mathieu Sylvander…",
    text: ["Est l'invité de l'émission", "Est le journaliste", "Est l'auteur du livre présenté"],
    textC: 2,
    img: ["Invité", "Journaliste", "Auteur"],
    imgC: 2,
    fillQ: "Le roman s'appelle « Comme un ___ ».",
    fill: "orage",
    fillA: ["orage"],
  },
  {
    id: "sar19-q3",
    textQ: "Où se déroule l'histoire ?",
    text: ["Dans une ville", "À la campagne", "À la montagne"],
    textC: 2,
    img: ["Ville", "Campagne", "Montagne"],
    imgC: 2,
    fillQ: "L'histoire commence par un gros ___ d'été.",
    fill: "orage",
    fillA: ["orage"],
  },
  {
    id: "sar19-q4",
    textQ: "Au début de l'histoire, les enfants sont…",
    text: ["Seuls", "Avec leur mère", "Avec des éducateurs"],
    textC: 1,
    img: ["Seuls", "Avec mère", "Éducateurs"],
    imgC: 1,
    fillQ: "La mère est un peu plus ___ .",
    fill: "loin",
    fillA: ["loin"],
  },
  {
    id: "sar19-q5",
    textQ: "Quel est le métier de la mère ?",
    text: ["Elle est guide de haute montagne", "Elle est médecin", "Elle gère un gîte en montagne"],
    textC: 2,
    img: ["Guide", "Médecin", "Gîte"],
    imgC: 2,
    fillQ: "Elle accueille des touristes dans son ___ .",
    fill: "gîte",
    fillA: ["gite", "gîte"],
  },
  {
    id: "sar19-q6",
    textQ: "Citez un problème que les enfants devront résoudre.",
    text: ["Trouver de vraies chaussures", "Apprendre à nager", "Acheter un train"],
    textC: 0,
    img: ["Chaussures", "Nager", "Train"],
    imgC: 0,
    fillQ: "Kevin ne peut pas continuer à marcher en ___ .",
    fill: "pantoufles",
    fillA: ["pantoufles", "pantoufle"],
  },
  {
    id: "sar19-q7",
    textQ: "D'après l'invitée, ce roman est très…",
    text: ["Tendre", "Drôle", "Triste"],
    textC: 0,
    img: ["Tendre", "Drôle", "Triste"],
    imgC: 0,
    fillQ: "C'est une histoire sur les relations inter___ .",
    fill: "générationnelles",
    fillA: ["generationnelles", "générationnelles"],
  },
  {
    id: "sar19-q8",
    textQ: "Kevin est-il un enfant ?",
    text: ["Oui, un petit garçon", "Non, c'est un homme âgé", "Oui, un adolescent"],
    textC: 1,
    img: ["Petit garçon", "Homme âgé", "Adolescent"],
    imgC: 1,
    fillQ: "Il porte un ___ et fume la pipe.",
    fill: "dentier",
    fillA: ["dentier"],
  },
  {
    id: "sar19-q9",
    textQ: "Qui est hébergé dans le gîte en ce moment ?",
    text: ["Des scouts", "Des personnes à mobilité réduite", "Des étudiants"],
    textC: 1,
    img: ["Scouts", "Mobilité réduite", "Étudiants"],
    imgC: 1,
    fillQ: "Un groupe de touristes est ___ dans le gîte.",
    fill: "hébergé",
    fillA: ["heberge", "hébergé"],
  },
  {
    id: "sar19-q10",
    textQ: "Comment le livre surprend-il le lecteur au sujet de Kevin ?",
    text: ["Kevin est un animal", "On découvre qu'il n'est pas un enfant", "Kevin ne parle pas"],
    textC: 1,
    img: ["Animal", "Pas un enfant", "Ne parle pas"],
    imgC: 1,
    fillQ: "Certains détails font poser des questions sur son ___ .",
    fill: "âge",
    fillA: ["age", "âge"],
  },
  {
    id: "sar19-q11",
    textQ: "Quel accessoire Kevin porte-t-il de façon amusante ?",
    text: ["Des bottes de ski", "Des pantoufles à carreaux", "Un casque de vélo"],
    textC: 1,
    img: ["Bottes", "Pantoufles", "Casque"],
    imgC: 1,
    fillQ: "Sa chemise et sa casquette sont aussi à ___ .",
    fill: "carreaux",
    fillA: ["carreaux", "carreau"],
  },
  {
    id: "sar19-q12",
    textQ: "Le ton général du roman est plutôt…",
    text: ["Effrayant", "Tendre avec quelques scènes drôles", "Uniquement comique"],
    textC: 1,
    img: ["Effrayant", "Tendre et drôle", "Comique"],
    imgC: 1,
    fillQ: "Une jolie ___ naît entre l'homme et les enfants.",
    fill: "complicité",
    fillA: ["complicite", "complicité"],
  },
  {
    id: "sar19-q13",
    textQ: "À quelle saison commence le roman ?",
    text: ["En été", "En hiver", "Au printemps"],
    textC: 0,
    img: ["Été", "Hiver", "Printemps"],
    imgC: 0,
    fillQ: "Un gros orage d'___, très impressionnant.",
    fill: "été",
    fillA: ["ete", "été"],
  },
  {
    id: "sar19-q14",
    textQ: "Quel accessoire amusant Kevin porte-t-il ?",
    text: ["Des pantoufles à carreaux", "Un chapeau rouge", "Des lunettes vertes"],
    textC: 0,
    img: ["Pantoufles", "Chapeau", "Lunettes"],
    imgC: 0,
    fillQ: "Il portait des pantoufles à ___.",
    fill: "carreaux",
    fillA: ["carreaux", "carreau"],
  },
  {
    id: "sar19-q15",
    textQ: "Quel objet les enfants doivent-ils trouver pour Kevin ?",
    text: ["De vraies chaussures", "Un parapluie", "Un chapeau"],
    textC: 0,
    img: ["Chaussures", "Parapluie", "Chapeau"],
    imgC: 0,
    fillQ: "Trouver de vraies ___ à Kevin.",
    fill: "chaussures",
    fillA: ["chaussures", "chaussure"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_20 = buildPool("avance", "scolaire-radio-20", [
  {
    id: "sar20-q1",
    textQ: "La journée sans tabac a lieu…",
    text: ["Tous les ans partout dans le monde", "3 fois par an en France", "Tous les 3 ans en France"],
    textC: 0,
    img: ["Mondial annuel", "3×/an France", "3 ans France"],
    imgC: 0,
    fillQ: "C'est la journée ___ tabac.",
    fill: "sans",
    fillA: ["sans"],
  },
  {
    id: "sar20-q2",
    textQ: "Combien de Français fument ?",
    text: ["La moitié", "Plus de la moitié de la population", "Moins de la moitié"],
    textC: 2,
    img: ["Moitié", "Plus de moitié", "Moins de moitié"],
    imgC: 2,
    fillQ: "En France, ___ de la moitié de la population fume encore.",
    fill: "moins",
    fillA: ["moins"],
  },
  {
    id: "sar20-q3",
    textQ: "Quel est le but de cette journée ?",
    text: ["Informer les gens qui fument", "Culpabiliser les fumeurs", "Dénoncer l'industrie du tabac"],
    textC: 0,
    img: ["Informer", "Culpabiliser", "Dénoncer industrie"],
    imgC: 0,
    fillQ: "On informe sur les dangers du ___ .",
    fill: "tabac",
    fillA: ["tabac", "cigarette"],
  },
  {
    id: "sar20-q4",
    textQ: "Qu'est-ce qui est le plus difficile, d'après le journaliste ?",
    text: ["Arrêter de fumer", "Ne pas recommencer", "Se protéger des fumeurs"],
    textC: 1,
    img: ["Arrêter", "Ne pas recommencer", "Se protéger"],
    imgC: 1,
    fillQ: "Le plus dur, c'est de ne pas ___ .",
    fill: "recommencer",
    fillA: ["recommencer", "rechuter"],
  },
  {
    id: "sar20-q5",
    textQ: "Que faut-il éviter de faire pour ne pas recommencer à fumer ?",
    text: ["De sortir, d'aller à des fêtes", "De boire du café", "De fréquenter des personnes qui fument"],
    textC: 0,
    img: ["Fêtes", "Café", "Fumeurs"],
    imgC: 0,
    fillQ: "Il ne faut pas boire de ___ non plus.",
    fill: "café",
    fillA: ["cafe", "café"],
  },
  {
    id: "sar20-q6",
    textQ: "Selon le médecin, l'arrêt du tabac est…",
    text: ["Seulement psychologique", "Lié à la dépendance", "Lié à la psychologie et à la dépendance"],
    textC: 2,
    img: ["Psychologique", "Dépendance", "Les deux"],
    imgC: 2,
    fillQ: "Il faut souvent de l'___ pour arrêter.",
    fill: "aide",
    fillA: ["aide", "courage"],
  },
  {
    id: "sar20-q7",
    textQ: "Selon la journaliste, arrêter de fumer a un autre avantage, lequel ?",
    text: ["Dépenser moins d'argent", "Avoir une meilleure haleine", "Vivre plus longtemps"],
    textC: 0,
    img: ["Moins d'argent", "Haleine", "Vivre longtemps"],
    imgC: 0,
    fillQ: "Le tabac ___ cher.",
    fill: "coûte",
    fillA: ["coute", "coûte"],
  },
  {
    id: "sar20-q8",
    textQ: "Pourquoi éviter le café quand on arrête de fumer ?",
    text: ["Parce qu'il donne envie d'une cigarette", "Parce qu'il est interdit", "Parce qu'il rend malade"],
    textC: 0,
    img: ["Envie cigarette", "Interdit", "Malade"],
    imgC: 0,
    fillQ: "Le café peut donner ___ d'une cigarette.",
    fill: "envie",
    fillA: ["envie"],
  },
  {
    id: "sar20-q9",
    textQ: "Que conseille-t-on aux personnes qui veulent arrêter ?",
    text: ["Fumer moins seulement", "Éviter les situations où l'on fume", "Acheter des cigarettes light"],
    textC: 1,
    img: ["Fumer moins", "Éviter situations", "Cigarettes light"],
    imgC: 1,
    fillQ: "Il faut éviter de fréquenter des personnes qui ___ .",
    fill: "fument",
    fillA: ["fument", "fume"],
  },
  {
    id: "sar20-q10",
    textQ: "Combien peut-on économiser en arrêtant de fumer ?",
    text: ["Rien du tout", "Plusieurs centaines d'euros par an", "Quelques euros par mois seulement"],
    textC: 1,
    img: ["Rien", "Centaines €/an", "Quelques €"],
    imgC: 1,
    fillQ: "On peut ___ beaucoup d'argent.",
    fill: "économiser",
    fillA: ["economiser", "économiser", "gagner"],
  },
  {
    id: "sar20-q11",
    textQ: "Quel est le premier défi pour un fumeur ?",
    text: ["Trouver un médecin", "Arrêter de fumer", "Changer de travail"],
    textC: 1,
    img: ["Médecin", "Arrêter", "Travail"],
    imgC: 1,
    fillQ: "Arrêter de fumer, c'est ___ .",
    fill: "difficile",
    fillA: ["difficile", "dur"],
  },
  {
    id: "sar20-q12",
    textQ: "Sur quoi porte surtout l'information de la journée sans tabac ?",
    text: ["Les prix des cigarettes", "Les dangers du tabac", "Les nouvelles marques"],
    textC: 1,
    img: ["Prix", "Dangers", "Marques"],
    imgC: 1,
    fillQ: "La journée aide aussi les fumeurs à ___ .",
    fill: "arrêter",
    fillA: ["arreter", "arrêter"],
  },
  {
    id: "sar20-q13",
    textQ: "En France, quelle part de la population fume encore ?",
    text: ["Moins de la moitié", "Plus de la moitié", "Tout le monde"],
    textC: 0,
    img: ["< 50 %", "> 50 %", "100 %"],
    imgC: 0,
    fillQ: "Moins de la moitié de la population ___ encore.",
    fill: "fume",
    fillA: ["fume"],
  },
  {
    id: "sar20-q14",
    textQ: "Quel avantage financier l'arrêt du tabac apporte-t-il ?",
    text: ["On dépense moins d'argent", "On gagne un salaire", "On reçoit une prime"],
    textC: 0,
    img: ["Économies", "Salaire", "Prime"],
    imgC: 0,
    fillQ: "En arrêtant, on peut ___ plusieurs centaines d'euros par an.",
    fill: "économiser",
    fillA: ["economiser", "économiser"],
  },
  {
    id: "sar20-q15",
    textQ: "De quoi a-t-on souvent besoin pour arrêter de fumer ?",
    text: ["De l'aide", "D'un nouveau travail", "De vacances"],
    textC: 0,
    img: ["Aide", "Travail", "Vacances"],
    imgC: 0,
    fillQ: "Il faut du courage et souvent de l'___.",
    fill: "aide",
    fillA: ["aide"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_21 = buildPool("avance", "scolaire-radio-21", [
  {
    id: "sar21-q1",
    textQ: "De quel type de jeu vidéo parle-t-on ?",
    text: ["Un jeu de course", "Un jeu de football", "Un jeu de stratégie"],
    textC: 1,
    img: ["Course", "Football", "Stratégie"],
    imgC: 1,
    fillQ: "Les développeurs ont tenu une conférence de ___ .",
    fill: "presse",
    fillA: ["presse"],
  },
  {
    id: "sar21-q2",
    textQ: "Lors de la conférence, les développeurs ont parlé…",
    text: ["Des modifications du jeu", "De la concurrence", "Des nouvelles consoles de jeu vidéo"],
    textC: 0,
    img: ["Modifications", "Concurrence", "Consoles"],
    imgC: 0,
    fillQ: "Ils ont surtout parlé des ___ apportées au jeu.",
    fill: "modifications",
    fillA: ["modifications", "modification", "changements"],
  },
  {
    id: "sar21-q3",
    textQ: "Combien de ventes pendant la première semaine ?",
    text: ["1 million", "Plus de 10 millions", "100 000"],
    textC: 1,
    img: ["1 M", "10 M+", "100 k"],
    imgC: 1,
    fillQ: "Depuis le lancement, on compte ___ millions de ventes.",
    fill: "25",
    fillA: ["25", "vingt-cinq"],
  },
  {
    id: "sar21-q4",
    textQ: "Combien de parties ont été jouées sur Internet ?",
    text: ["1 million", "10 millions", "Plus de 100 millions"],
    textC: 2,
    img: ["1 M", "10 M", "100 M+"],
    imgC: 2,
    fillQ: "Plus de 100 millions de parties ont été jouées sur ___ .",
    fill: "Internet",
    fillA: ["internet", "Internet", "ligne", "en ligne"],
  },
  {
    id: "sar21-q5",
    textQ: "La nouvelle version du jeu devrait…",
    text: ["Beaucoup ressembler à l'ancienne version", "Être assez différente de l'ancienne version", "Être très différente de l'ancienne version"],
    textC: 1,
    img: ["Ressemble", "Assez différente", "Très différente"],
    imgC: 1,
    fillQ: "La nouvelle version sera assez ___ de l'ancienne.",
    fill: "différente",
    fillA: ["differente", "différente"],
  },
  {
    id: "sar21-q6",
    textQ: "Les créateurs du jeu ont voulu…",
    text: ["Faire courir les joueurs plus vite", "Créer davantage de joueurs et d'équipes", "Rendre les actions des personnages plus réalistes"],
    textC: 2,
    img: ["Plus vite", "Plus d'équipes", "Plus réaliste"],
    imgC: 2,
    fillQ: "Les joueurs passent le ballon de façon plus ___ .",
    fill: "naturelle",
    fillA: ["naturelle", "naturel", "realiste", "réaliste"],
  },
  {
    id: "sar21-q7",
    textQ: "Quelle amélioration annonce le journaliste ?",
    text: ["Le graphisme est meilleur", "L'animation est meilleure", "Le prix est plus bas"],
    textC: 0,
    img: ["Graphisme", "Animation", "Prix"],
    imgC: 0,
    fillQ: "Les stades et les visages sont plus ___ .",
    fill: "beaux",
    fillA: ["beaux", "belles", "jolis"],
  },
  {
    id: "sar21-q8",
    textQ: "Quels éléments du jeu sont plus fluides ?",
    text: ["Les menus seulement", "Les mouvements", "Les commentaires"],
    textC: 1,
    img: ["Menus", "Mouvements", "Commentaires"],
    imgC: 1,
    fillQ: "Les mouvements sont plus ___ qu'avant.",
    fill: "fluides",
    fillA: ["fluides", "fluide"],
  },
  {
    id: "sar21-q9",
    textQ: "Les chiffres de vente sont…",
    text: ["Décevants", "Impressionnants", "Inconnus"],
    textC: 1,
    img: ["Décevants", "Impressionnants", "Inconnus"],
    imgC: 1,
    fillQ: "Pendant la première semaine, les ventes sont très ___ .",
    fill: "fortes",
    fillA: ["fortes", "hautes", "importantes"],
  },
  {
    id: "sar21-q10",
    textQ: "Que font les personnages de façon plus réaliste ?",
    text: ["Ils parlent plus", "Ils courent, tirent et passent le ballon", "Ils changent de sport"],
    textC: 1,
    img: ["Parlent", "Courent et tirent", "Changent sport"],
    imgC: 1,
    fillQ: "Les actions des personnages sont plus ___ .",
    fill: "réalistes",
    fillA: ["realistes", "réalistes"],
  },
  {
    id: "sar21-q11",
    textQ: "Quand a eu lieu la conférence ?",
    text: ["Aujourd'hui", "Hier", "La semaine dernière"],
    textC: 1,
    img: ["Aujourd'hui", "Hier", "Semaine dernière"],
    imgC: 1,
    fillQ: "C'était une grande conférence de ___ .",
    fill: "presse",
    fillA: ["presse"],
  },
  {
    id: "sar21-q12",
    textQ: "Qu'est-ce qui est amélioré visuellement dans le jeu ?",
    text: ["Seulement les maillots", "Les stades, les visages et les mouvements", "Uniquement le ballon"],
    textC: 1,
    img: ["Maillots", "Stades et visages", "Ballon"],
    imgC: 1,
    fillQ: "Le ___ est plus beau et plus fluide.",
    fill: "graphisme",
    fillA: ["graphisme", "graphique"],
  },
  {
    id: "sar21-q13",
    textQ: "Combien de ventes totales depuis le lancement du jeu ?",
    text: ["25 millions", "10 millions", "100 millions"],
    textC: 0,
    img: ["25 M", "10 M", "100 M"],
    imgC: 0,
    fillQ: "Depuis son lancement, on compte déjà 25 millions de ___.",
    fill: "ventes",
    fillA: ["ventes", "vente"],
  },
  {
    id: "sar21-q14",
    textQ: "Comment les joueurs passent-ils le ballon dans la nouvelle version ?",
    text: ["De façon plus naturelle", "De façon plus lente", "Sans jamais courir"],
    textC: 0,
    img: ["Naturel", "Lent", "Immobile"],
    imgC: 0,
    fillQ: "Les joueurs passent le ballon de façon plus ___.",
    fill: "naturelle",
    fillA: ["naturelle", "naturel"],
  },
  {
    id: "sar21-q15",
    textQ: "Quand la conférence de presse a-t-elle eu lieu ?",
    text: ["Hier", "La semaine dernière", "Demain"],
    textC: 0,
    img: ["Hier", "Semaine passée", "Demain"],
    imgC: 0,
    fillQ: "Hier, les développeurs ont tenu une grande conférence de ___.",
    fill: "presse",
    fillA: ["presse"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_22 = buildPool("avance", "scolaire-radio-22", [
  {
    id: "sar22-q1",
    textQ: "La zoothérapie à travers la compagnie des animaux peut aider à diminuer le stress…",
    text: ["De personnes qui travaillent trop", "D'adolescents angoissés", "De personnes qui sont seules"],
    textC: 2,
    img: ["Travail", "Ados angoissés", "Personnes seules"],
    imgC: 2,
    fillQ: "On parle aujourd'hui de ___ .",
    fill: "zoothérapie",
    fillA: ["zoothérapie", "zoo therapie"],
  },
  {
    id: "sar22-q2",
    textQ: "Que permet la complicité avec un animal ?",
    text: ["De gagner de l'argent", "De se confier sans craindre le jugement", "D'éviter l'école"],
    textC: 1,
    img: ["Argent", "Se confier", "Éviter école"],
    imgC: 1,
    fillQ: "On peut se confier sans craindre le ___ des autres.",
    fill: "jugement",
    fillA: ["jugement"],
  },
  {
    id: "sar22-q3",
    textQ: "Quelle est la différence entre l'animal et l'homme ?",
    text: ["L'animal est plus fidèle que l'homme", "L'animal est moins affectueux que l'homme", "L'animal ne donne pas d'appréciation"],
    textC: 2,
    img: ["Plus fidèle", "Moins affectueux", "Pas d'appréciation"],
    imgC: 2,
    fillQ: "L'animal n'___ pas.",
    fill: "évalue",
    fillA: ["evalue", "évalue", "juge"],
  },
  {
    id: "sar22-q4",
    textQ: "Qu'est-ce qui aide à se concentrer ?",
    text: ["Communiquer avec un animal", "Promener un animal", "Caresser un animal"],
    textC: 0,
    img: ["Communiquer", "Promener", "Caresser"],
    imgC: 0,
    fillQ: "Cela aide à se concentrer sur le moment ___ .",
    fill: "présent",
    fillA: ["present", "présent"],
  },
  {
    id: "sar22-q5",
    textQ: "Citez deux avantages de la compagnie d'un animal pour les enfants.",
    text: ["Confiance en soi et calme", "Richesse et célébrité", "Vitesse et force"],
    textC: 0,
    img: ["Confiance et calme", "Richesse", "Vitesse"],
    imgC: 0,
    fillQ: "La présence d'un animal développe la confiance en ___ .",
    fill: "soi",
    fillA: ["soi"],
  },
  {
    id: "sar22-q6",
    textQ: "Avec quel animal la zoothérapie fonctionne le mieux ?",
    text: ["Le chien", "Le chat", "Avec n'importe quel animal"],
    textC: 2,
    img: ["Chien", "Chat", "N'importe quel"],
    imgC: 2,
    fillQ: "Le ___ est souvent utilisé car il est très sociable.",
    fill: "chien",
    fillA: ["chien"],
  },
  {
    id: "sar22-q7",
    textQ: "Le ronronnement du chat et le caresser ont des effets positifs, lesquels ?",
    text: ["Ils rendent plus nerveux", "Ils détendent et réduisent l'anxiété", "Ils empêchent de dormir"],
    textC: 1,
    img: ["Nerveux", "Détendent", "Empêchent dormir"],
    imgC: 1,
    fillQ: "Caresser un chat ___ l'anxiété.",
    fill: "réduit",
    fillA: ["reduit", "réduit", "diminue"],
  },
  {
    id: "sar22-q8",
    textQ: "Pourquoi le chien est-il souvent utilisé ?",
    text: ["Parce qu'il est très sociable", "Parce qu'il est le plus grand", "Parce qu'il ne mange rien"],
    textC: 0,
    img: ["Sociable", "Grand", "Ne mange rien"],
    imgC: 0,
    fillQ: "Le chien est très ___ .",
    fill: "sociable",
    fillA: ["sociable"],
  },
  {
    id: "sar22-q9",
    textQ: "Chez qui la zoothérapie peut-elle réduire le stress ?",
    text: ["Uniquement chez les enfants", "Chez des personnes seules et des adolescents angoissés", "Seulement chez les médecins"],
    textC: 1,
    img: ["Enfants seuls", "Seuls et ados", "Médecins"],
    imgC: 1,
    fillQ: "Elle aide à diminuer le ___ .",
    fill: "stress",
    fillA: ["stress"],
  },
  {
    id: "sar22-q10",
    textQ: "Qu'apporte un animal aux enfants en plus de la confiance ?",
    text: ["Du calme", "De la colère", "De la fatigue"],
    textC: 0,
    img: ["Calme", "Colère", "Fatigue"],
    imgC: 0,
    fillQ: "Un animal apporte aussi du ___ .",
    fill: "calme",
    fillA: ["calme", "serenite", "sérénité"],
  },
  {
    id: "sar22-q11",
    textQ: "Pourquoi parle-t-on facilement à un animal ?",
    text: ["Parce qu'il répond toujours", "Parce qu'il ne juge pas", "Parce qu'il connaît tout"],
    textC: 1,
    img: ["Répond", "Ne juge pas", "Connaît tout"],
    imgC: 1,
    fillQ: "L'animal ne donne pas d'___ .",
    fill: "appréciation",
    fillA: ["appreciation", "appréciation"],
  },
  {
    id: "sar22-q12",
    textQ: "Quel effet le ronronnement du chat produit-il ?",
    text: ["Il agresse", "Il détend", "Il fait peur"],
    textC: 1,
    img: ["Agresse", "Détend", "Fait peur"],
    imgC: 1,
    fillQ: "Le ronronnement du chat a des effets ___ .",
    fill: "positifs",
    fillA: ["positifs", "positif", "benefiques", "bénéfiques"],
  },
  {
    id: "sar22-q13",
    textQ: "Communiquer avec un animal aide à se concentrer sur le moment…",
    text: ["Présent", "Passé", "Futur"],
    textC: 0,
    img: ["Présent", "Passé", "Futur"],
    imgC: 0,
    fillQ: "Cela aide à se concentrer sur le moment ___.",
    fill: "présent",
    fillA: ["present", "présent"],
  },
  {
    id: "sar22-q14",
    textQ: "Que ne fait pas l'animal, contrairement à l'homme ?",
    text: ["Il n'évalue pas", "Il ne mange pas", "Il ne dort pas"],
    textC: 0,
    img: ["N'évalue pas", "Ne mange pas", "Ne dort pas"],
    imgC: 0,
    fillQ: "L'animal ne donne pas d'___.",
    fill: "appréciation",
    fillA: ["appreciation", "appréciation"],
  },
  {
    id: "sar22-q15",
    textQ: "Quel animal est souvent utilisé en zoothérapie ?",
    text: ["Le chien", "Le poisson", "Le serpent"],
    textC: 0,
    img: ["Chien", "Poisson", "Serpent"],
    imgC: 0,
    fillQ: "Le ___ est souvent utilisé car il est très sociable.",
    fill: "chien",
    fillA: ["chien"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_23 = buildPool("avance", "scolaire-radio-23", [
  {
    id: "sar23-q1",
    textQ: "Que dénonce-t-on dans ce bulletin ?",
    text: ["La transformation des aliments par les industriels", "Le manque d'information sur les produits transformés", "L'indifférence des consommateurs à la manipulation des aliments"],
    textC: 0,
    img: ["Transformation", "Manque info", "Indifférence"],
    imgC: 0,
    fillQ: "On dénonce la ___ des aliments.",
    fill: "transformation",
    fillA: ["transformation"],
  },
  {
    id: "sar23-q2",
    textQ: "« Le goût s'invente dans des éprouvettes » signifie que…",
    text: ["On vend des aliments dans des petits tubes", "Le goût des aliments est de plus en plus artificiel", "On apprend le goût aux enfants dès leur naissance"],
    textC: 1,
    img: ["Petits tubes", "Artificiel", "Apprendre goût"],
    imgC: 1,
    fillQ: "Le goût est de plus en plus ___ .",
    fill: "artificiel",
    fillA: ["artificiel", "artificielle"],
  },
  {
    id: "sar23-q3",
    textQ: "Pourquoi ajoute-t-on du sucre dans les produits industriels ?",
    text: ["Pour que les gens aient toujours envie de les manger", "Pour les gens qui souffrent du manque de sucre", "Pour que les aliments soient moins acides"],
    textC: 0,
    img: ["Toujours envie", "Manque sucre", "Moins acides"],
    imgC: 0,
    fillQ: "Le sucre donne toujours ___ de manger.",
    fill: "envie",
    fillA: ["envie"],
  },
  {
    id: "sar23-q4",
    textQ: "On transforme le goût en ajoutant du sucre mais aussi en ajoutant quels éléments ?",
    text: ["Du sel, des matières grasses et des arômes", "De l'eau et du lait seulement", "Des vitamines uniquement"],
    textC: 0,
    img: ["Sel et arômes", "Eau et lait", "Vitamines"],
    imgC: 0,
    fillQ: "On ajoute aussi du ___ et des arômes.",
    fill: "sel",
    fillA: ["sel"],
  },
  {
    id: "sar23-q5",
    textQ: "Que risque-t-on si on mange trop d'aliments transformés ?",
    text: ["Rien de grave", "Des problèmes de santé comme le surpoids", "De devenir plus sportif"],
    textC: 1,
    img: ["Rien", "Surpoids", "Plus sportif"],
    imgC: 1,
    fillQ: "On risque des problèmes de ___ .",
    fill: "santé",
    fillA: ["sante", "santé", "surpoids"],
  },
  {
    id: "sar23-q6",
    textQ: "Que font les consommateurs pour résister à ce phénomène ?",
    text: ["Ils achètent des produits biologiques", "Ils cultivent leurs propres légumes", "Ils font un régime"],
    textC: 0,
    img: ["Bio", "Cultivent légumes", "Régime"],
    imgC: 0,
    fillQ: "Certains cultivent aussi leurs propres ___ .",
    fill: "légumes",
    fillA: ["legumes", "légumes"],
  },
  {
    id: "sar23-q7",
    textQ: "En conclusion, l'auteur veut dire que…",
    text: ["Si on veut bien manger on peut, c'est nous qui décidons", "Finalement les produits industriels ne sont pas tous mauvais", "Les laboratoires auront toujours plus de pouvoir sur notre alimentation"],
    textC: 0,
    img: ["Nous décidons", "Pas tous mauvais", "Labos puissants"],
    imgC: 0,
    fillQ: "C'est nous qui décidons de ce que nous mettons dans notre ___ .",
    fill: "assiette",
    fillA: ["assiette"],
  },
  {
    id: "sar23-q8",
    textQ: "Pourquoi les industriels ajoutent-ils des arômes ?",
    text: ["Pour rendre le goût artificiel et attractif", "Pour conserver les vitamines", "Pour réduire le prix"],
    textC: 0,
    img: ["Goût attractif", "Vitamines", "Prix"],
    imgC: 0,
    fillQ: "On transforme le goût avec du sucre, du sel et des matières ___ .",
    fill: "grasses",
    fillA: ["grasses", "grasse"],
  },
  {
    id: "sar23-q9",
    textQ: "Quelle attitude adoptent de plus en plus de consommateurs ?",
    text: ["Ils mangent plus de produits transformés", "Ils achètent bio ou cultivent leurs légumes", "Ils arrêtent de manger"],
    textC: 1,
    img: ["Plus transformés", "Bio ou jardin", "Arrêtent manger"],
    imgC: 1,
    fillQ: "Ils achètent des produits ___ .",
    fill: "biologiques",
    fillA: ["biologiques", "bio"],
  },
  {
    id: "sar23-q10",
    textQ: "Que signifie l'expression sur les éprouvettes ?",
    text: ["Le goût est créé artificiellement en laboratoire", "Les aliments sont vendus en pharmacie", "Les enfants font des expériences"],
    textC: 0,
    img: ["Laboratoire", "Pharmacie", "Expériences"],
    imgC: 0,
    fillQ: "Le goût s'invente dans des ___ .",
    fill: "éprouvettes",
    fillA: ["eprouvettes", "éprouvettes"],
  },
  {
    id: "sar23-q11",
    textQ: "Selon l'auteur, que peuvent faire les consommateurs face aux aliments industriels ?",
    text: ["Choisir ce qu'ils mangent", "Rien du tout", "Acheter uniquement des éprouvettes"],
    textC: 0,
    img: ["Choisir", "Rien", "Éprouvettes"],
    imgC: 0,
    fillQ: "L'auteur dit que les consommateurs peuvent ___ leur alimentation.",
    fill: "choisir",
    fillA: ["choisir", "decider", "décider"],
  },
  {
    id: "sar23-q12",
    textQ: "Quel est l'objectif principal du bulletin ?",
    text: ["Faire de la publicité", "Dénoncer la manipulation des aliments industriels", "Vendre des éprouvettes"],
    textC: 1,
    img: ["Publicité", "Dénoncer", "Vendre"],
    imgC: 1,
    fillQ: "Les industriels ___ beaucoup les aliments.",
    fill: "transforment",
    fillA: ["transforment", "modifient"],
  },
  {
    id: "sar23-q13",
    textQ: "Que risque-t-on en mangeant trop d'aliments transformés ?",
    text: ["Le surpoids", "La fatigue uniquement", "Rien de grave"],
    textC: 0,
    img: ["Surpoids", "Fatigue", "Rien"],
    imgC: 0,
    fillQ: "On risque des problèmes de santé comme le ___.",
    fill: "surpoids",
    fillA: ["surpoids"],
  },
  {
    id: "sar23-q14",
    textQ: "Outre le sucre et le sel, que ajoutent les industriels ?",
    text: ["Des matières grasses et des arômes", "De l'eau seulement", "Des vitamines naturelles"],
    textC: 0,
    img: ["Graisses", "Eau", "Vitamines"],
    imgC: 0,
    fillQ: "On transforme le goût en ajoutant du sel, des matières grasses et des ___.",
    fill: "arômes",
    fillA: ["aromes", "arômes"],
  },
  {
    id: "sar23-q15",
    textQ: "Que font certains consommateurs pour mieux manger ?",
    text: ["Ils cultivent leurs propres légumes", "Ils arrêtent de manger", "Ils commandent plus de plats préparés"],
    textC: 0,
    img: ["Cultiver", "Arrêter", "Plats préparés"],
    imgC: 0,
    fillQ: "De plus en plus de consommateurs cultivent leurs propres ___.",
    fill: "légumes",
    fillA: ["legumes", "légumes"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_24 = buildPool("avance", "scolaire-radio-24", [
  {
    id: "sar24-q1",
    textQ: "Quel est le métier de Hub ?",
    text: ["Auteur de roman", "Auteur de bandes dessinées", "Scénariste de dessins animés"],
    textC: 1,
    img: ["Roman", "BD", "Dessins animés"],
    imgC: 1,
    fillQ: "Hub est ___ de bandes dessinées.",
    fill: "auteur",
    fillA: ["auteur", "dessinateur"],
  },
  {
    id: "sar24-q2",
    textQ: "Quel avantage offre cette profession ?",
    text: ["Travailler uniquement en équipe", "Créer ses propres univers et travailler chez soi", "Ne jamais voyager"],
    textC: 1,
    img: ["Équipe", "Liberté créative", "Pas voyager"],
    imgC: 1,
    fillQ: "On peut créer ses propres ___ .",
    fill: "univers",
    fillA: ["univers", "mondes", "histoires"],
  },
  {
    id: "sar24-q3",
    textQ: "Qu'est-ce que Hub essaie de faire ?",
    text: ["Passer plus de temps avec ses amis", "Gagner des prix et des concours", "Travailler avec des artistes reconnus"],
    textC: 2,
    img: ["Amis", "Prix", "Artistes reconnus"],
    imgC: 2,
    fillQ: "Il veut collaborer avec des ___ qu'il admire.",
    fill: "artistes",
    fillA: ["artistes", "coloristes", "scenaristes", "scénaristes"],
  },
  {
    id: "sar24-q4",
    textQ: "Sur quel projet Hub travaille-t-il ?",
    text: ["Un album de science-fiction", "Un roman policier", "Un film d'animation"],
    textC: 0,
    img: ["Science-fiction", "Policier", "Film"],
    imgC: 0,
    fillQ: "Il prépare un album sur un monde ___ .",
    fill: "futuriste",
    fillA: ["futuriste", "futur"],
  },
  {
    id: "sar24-q5",
    textQ: "Pourquoi Hub apprécie-t-il les bandes dessinées franco-belges ?",
    text: ["Parce qu'elles sont toujours courtes", "Parce qu'elles mélangent art et littérature", "Parce qu'elles ne coûtent rien"],
    textC: 1,
    img: ["Courtes", "Art et littérature", "Gratuites"],
    imgC: 1,
    fillQ: "On peut y raconter toutes sortes d'___ .",
    fill: "histoires",
    fillA: ["histoires", "histoire"],
  },
  {
    id: "sar24-q6",
    textQ: "Quel genre d'album Hub prépare-t-il ?",
    text: ["Historique", "Science-fiction", "Romance"],
    textC: 1,
    img: ["Historique", "SF", "Romance"],
    imgC: 1,
    fillQ: "L'album devrait sortir à la fin de l'___ .",
    fill: "année",
    fillA: ["annee", "année"],
  },
  {
    id: "sar24-q7",
    textQ: "Aujourd'hui Hub fait… de dédicaces qu'à ses débuts.",
    text: ["Plus", "Moins", "Autant"],
    textC: 1,
    img: ["Plus", "Moins", "Autant"],
    imgC: 1,
    fillQ: "Il a moins de ___ qu'avant.",
    fill: "temps",
    fillA: ["temps"],
  },
  {
    id: "sar24-q8",
    textQ: "Avec qui Hub aimerait-il collaborer ?",
    text: ["Des scénaristes et coloristes reconnus", "Des sportifs célèbres", "Des politiciens"],
    textC: 0,
    img: ["Scénaristes", "Sportifs", "Politiciens"],
    imgC: 0,
    fillQ: "Il admire des coloristes et des ___ .",
    fill: "scénaristes",
    fillA: ["scenaristes", "scénaristes"],
  },
  {
    id: "sar24-q9",
    textQ: "Quel plaisir Hub garde-t-il lors des dédicaces ?",
    text: ["Vendre plus de livres", "Rencontrer les lecteurs", "Gagner des prix"],
    textC: 1,
    img: ["Vendre", "Rencontrer lecteurs", "Prix"],
    imgC: 1,
    fillQ: "Rencontrer les lecteurs reste un vrai ___ .",
    fill: "plaisir",
    fillA: ["plaisir"],
  },
  {
    id: "sar24-q10",
    textQ: "Pourquoi les BD franco-belges lui plaisent-elles ?",
    text: ["Parce qu'elles ont une tradition riche", "Parce qu'elles n'ont pas d'images", "Parce qu'elles sont interdites aux jeunes"],
    textC: 0,
    img: ["Tradition riche", "Pas d'images", "Interdites"],
    imgC: 0,
    fillQ: "La tradition franco-belge est très ___ .",
    fill: "riche",
    fillA: ["riche"],
  },
  {
    id: "sar24-q11",
    textQ: "Où Hub peut-il travailler selon lui ?",
    text: ["Uniquement en librairie", "Souvent chez lui", "Seulement à l'étranger"],
    textC: 1,
    img: ["Librairie", "Chez lui", "Étranger"],
    imgC: 1,
    fillQ: "Il peut aussi voyager pour rencontrer des ___ .",
    fill: "lecteurs",
    fillA: ["lecteurs", "lecteur", "fans"],
  },
  {
    id: "sar24-q12",
    textQ: "Que combine Hub dans son métier ?",
    text: ["Sport et musique", "Création et rencontres avec le public", "Cuisine et voyage"],
    textC: 1,
    img: ["Sport", "Création et public", "Cuisine"],
    imgC: 1,
    fillQ: "Son métier permet de créer et de ___ .",
    fill: "voyager",
    fillA: ["voyager", "rencontrer"],
  },
  {
    id: "sar24-q13",
    textQ: "Sur quel genre d'album Hub travaille-t-il actuellement ?",
    text: ["Science-fiction", "Policier", "Romance"],
    textC: 0,
    img: ["Science-fiction", "Policier", "Romance"],
    imgC: 0,
    fillQ: "Je prépare un album de ___ pour la fin de l'année.",
    fill: "science-fiction",
    fillA: ["science-fiction", "science fiction"],
  },
  {
    id: "sar24-q14",
    textQ: "Avec quels professionnels Hub aimerait-il collaborer ?",
    text: ["Des coloristes et des scénaristes", "Des cuisiniers", "Des médecins"],
    textC: 0,
    img: ["Artistes BD", "Cuisiniers", "Médecins"],
    imgC: 0,
    fillQ: "J'essaie de travailler avec des artistes reconnus, des coloristes et des ___.",
    fill: "scénaristes",
    fillA: ["scenaristes", "scénaristes"],
  },
  {
    id: "sar24-q15",
    textQ: "Hub fait-il autant de dédicaces qu'au début de sa carrière ?",
    text: ["Non, moins", "Oui, plus", "Il n'en fait jamais"],
    textC: 0,
    img: ["Moins", "Plus", "Jamais"],
    imgC: 0,
    fillQ: "Aujourd'hui j'en fais moins qu'à mes ___.",
    fill: "débuts",
    fillA: ["debuts", "débuts"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_25 = buildPool("avance", "scolaire-radio-25", [
  {
    id: "sar25-q1",
    textQ: "Cette émission traite…",
    text: ["Du problème de surpoids et des solutions possibles", "Des conséquences du surpoids seulement", "Des progrès de la médecine dans ce domaine"],
    textC: 0,
    img: ["Surpoids et solutions", "Conséquences", "Progrès médecine"],
    imgC: 0,
    fillQ: "La professeure Haldig est spécialiste en ___ .",
    fill: "nutrition",
    fillA: ["nutrition"],
  },
  {
    id: "sar25-q2",
    textQ: "Quel est le métier de l'invitée ?",
    text: ["Journaliste", "Spécialiste en nutrition", "Cuisinière"],
    textC: 1,
    img: ["Journaliste", "Nutrition", "Cuisinière"],
    imgC: 1,
    fillQ: "Le surpoids a trois causes ___ .",
    fill: "principales",
    fillA: ["principales", "principale", "majeures"],
  },
  {
    id: "sar25-q3",
    textQ: "Quelles sont les trois causes du surpoids d'après la professeure Haldig ?",
    text: ["Alimentation riche, manque d'activité et stress", "Génétique uniquement", "Manque de sommeil seulement"],
    textC: 0,
    img: ["Alim + activité + stress", "Génétique", "Sommeil"],
    imgC: 0,
    fillQ: "Une cause est le manque d'activité ___ .",
    fill: "physique",
    fillA: ["physique", "sport"],
  },
  {
    id: "sar25-q4",
    textQ: "Actuellement, où observe-t-on une croissance de personnes en surpoids ?",
    text: ["Uniquement en Europe", "Dans de nombreux pays en développement", "Seulement chez les enfants"],
    textC: 1,
    img: ["Europe", "Pays en développement", "Enfants"],
    imgC: 1,
    fillQ: "On observe une forte croissance dans les pays en ___ .",
    fill: "développement",
    fillA: ["developpement", "développement"],
  },
  {
    id: "sar25-q5",
    textQ: "À Ouagadougou, des personnes sont en surpoids à cause…",
    text: ["De la consommation de produits gras et salés seulement", "Du stress causé par les touristes", "D'un changement de consommation alimentaire"],
    textC: 2,
    img: ["Gras et salé", "Stress touristes", "Changement alimentation"],
    imgC: 2,
    fillQ: "Elles mangent plus de produits transformés ___ .",
    fill: "importés",
    fillA: ["importes", "importés"],
  },
  {
    id: "sar25-q6",
    textQ: "Les régimes pour le grand public sont…",
    text: ["Très efficaces", "Complètement inefficaces", "Presque tous inefficaces"],
    textC: 2,
    img: ["Très efficaces", "Inefficaces", "Presque tous inefficaces"],
    imgC: 2,
    fillQ: "Ils promettent des résultats ___ .",
    fill: "rapides",
    fillA: ["rapides", "rapide"],
  },
  {
    id: "sar25-q7",
    textQ: "D'après la professeure Haldig, quelle est une particularité des régimes du commerce ?",
    text: ["Ils sont toujours personnalisés", "Ils ne tiennent pas compte des habitudes de chacun", "Ils sont gratuits"],
    textC: 1,
    img: ["Personnalisés", "Ignorent habitudes", "Gratuits"],
    imgC: 1,
    fillQ: "Ils ne sont pas efficaces à long ___ .",
    fill: "terme",
    fillA: ["terme"],
  },
  {
    id: "sar25-q8",
    textQ: "Le traitement de la professeure Haldig…",
    text: ["Interdit tous les aliments", "S'adapte aux habitudes culturelles et familiales", "Propose une recette miracle"],
    textC: 1,
    img: ["Interdit tout", "Adapte habitudes", "Recette miracle"],
    imgC: 1,
    fillQ: "Il aide aussi les patients à connaître leurs ___ alimentaires.",
    fill: "besoins",
    fillA: ["besoins", "besoin"],
  },
  {
    id: "sar25-q9",
    textQ: "Que fait la professeure Haldig avec ses patients ?",
    text: ["Elle leur interdit tout", "Elle les aide à réapprendre à manger équilibré", "Elle leur vend des produits"],
    textC: 1,
    img: ["Interdit tout", "Réapprendre manger", "Vend produits"],
    imgC: 1,
    fillQ: "On ne ___ pas tout.",
    fill: "interdit",
    fillA: ["interdit"],
  },
  {
    id: "sar25-q10",
    textQ: "Quelle cause de surpoids est liée au mode de vie moderne ?",
    text: ["Trop de sport", "Alimentation trop riche", "Trop de légumes"],
    textC: 1,
    img: ["Trop sport", "Alim riche", "Trop légumes"],
    imgC: 1,
    fillQ: "Le ___ peut aussi provoquer du surpoids.",
    fill: "stress",
    fillA: ["stress"],
  },
  {
    id: "sar25-q11",
    textQ: "Pourquoi les régimes grand public échouent-ils souvent ?",
    text: ["Parce qu'ils sont trop lents", "Parce qu'ils ignorent les habitudes personnelles", "Parce qu'ils sont gratuits"],
    textC: 1,
    img: ["Trop lents", "Ignorent habitudes", "Gratuits"],
    imgC: 1,
    fillQ: "Chaque personne a des habitudes ___ .",
    fill: "différentes",
    fillA: ["differentes", "différentes"],
  },
  {
    id: "sar25-q12",
    textQ: "Quelle approche la professeure Haldig privilégie-t-elle ?",
    text: ["Une méthode identique pour tous", "Une méthode adaptée à chaque patient", "Aucun suivi"],
    textC: 1,
    img: ["Identique", "Adaptée", "Aucun suivi"],
    imgC: 1,
    fillQ: "Le traitement tient compte de la culture et de la ___ .",
    fill: "famille",
    fillA: ["famille", "familial"],
  },
  {
    id: "sar25-q13",
    textQ: "Pourquoi les régimes du commerce échouent-ils souvent ?",
    text: ["Ils promettent des résultats rapides", "Ils sont gratuits", "Ils durent trop longtemps"],
    textC: 0,
    img: ["Rapides", "Gratuits", "Longs"],
    imgC: 0,
    fillQ: "Ils promettent des résultats ___ mais ne tiennent pas compte des habitudes.",
    fill: "rapides",
    fillA: ["rapides", "rapide"],
  },
  {
    id: "sar25-q14",
    textQ: "À quoi s'adapte le traitement de la professeure Haldig ?",
    text: ["Aux habitudes culturelles et familiales", "À la mode", "Aux médicaments"],
    textC: 0,
    img: ["Habitudes", "Mode", "Médicaments"],
    imgC: 0,
    fillQ: "Mon traitement s'adapte aux habitudes culturelles et ___.",
    fill: "familiales",
    fillA: ["familiales", "familiale"],
  },
  {
    id: "sar25-q15",
    textQ: "Que réapprennent les patients avec la méthode de la professeure ?",
    text: ["À manger équilibré", "À jeûner", "À éviter tous les repas"],
    textC: 0,
    img: ["Équilibré", "Jeûner", "Éviter"],
    imgC: 0,
    fillQ: "On n'interdit pas tout, on réapprend à manger ___.",
    fill: "équilibré",
    fillA: ["equilibre", "équilibré"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_26 = buildPool("avance", "scolaire-radio-26", [
  {
    id: "sar26-q1",
    textQ: "Aujourd'hui, les vacances d'été consistent surtout à…",
    text: ["Rester à la maison pour se reposer", "Rester à la maison pour étudier", "Partir puis étudier"],
    textC: 2,
    img: ["Repos maison", "Étudier maison", "Partir puis étudier"],
    imgC: 2,
    fillQ: "Les vacances ont beaucoup ___ .",
    fill: "changé",
    fillA: ["change", "changé"],
  },
  {
    id: "sar26-q2",
    textQ: "Citez deux possibilités de vacances chez les jeunes.",
    text: ["Colonies et séjours linguistiques", "Examen et punition", "Télévision et jeux seulement"],
    textC: 0,
    img: ["Colonies et séjours", "Examen", "TV et jeux"],
    imgC: 0,
    fillQ: "Il y a aussi les camps ___ et les jobs d'été.",
    fill: "sportifs",
    fillA: ["sportifs", "sportif"],
  },
  {
    id: "sar26-q3",
    textQ: "D'après certains parents, qu'est-ce qui permet aux enfants de développer leur autonomie ?",
    text: ["Rester toujours avec la famille", "Partir seul ou en groupe sans la famille", "Ne jamais voyager"],
    textC: 1,
    img: ["Avec famille", "Sans famille", "Ne pas voyager"],
    imgC: 1,
    fillQ: "Partir sans la famille aide à développer l'___ .",
    fill: "autonomie",
    fillA: ["autonomie", "independance", "indépendance"],
  },
  {
    id: "sar26-q4",
    textQ: "Comment étudient les jeunes pendant l'été ?",
    text: ["Avec les cahiers de vacances ou des cours de révision", "Tout seuls sans support", "Uniquement avec leurs parents"],
    textC: 0,
    img: ["Cahiers de vacances", "Seuls", "Parents"],
    imgC: 0,
    fillQ: "Beaucoup suivent des cours de ___ .",
    fill: "révision",
    fillA: ["revision", "révision"],
  },
  {
    id: "sar26-q5",
    textQ: "Que peuvent faire les jeunes qui ont besoin d'indépendance et de découvrir une autre culture ?",
    text: ["Rester chez eux", "Partir en échange scolaire ou séjour linguistique", "Arrêter l'école"],
    textC: 1,
    img: ["Rester", "Échange linguistique", "Arrêter école"],
    imgC: 1,
    fillQ: "Ils peuvent partir en séjour ___ .",
    fill: "linguistique",
    fillA: ["linguistique"],
  },
  {
    id: "sar26-q6",
    textQ: "Quand étudient-ils souvent pendant l'été ?",
    text: ["Avant la rentrée", "Pendant Noël", "Jamais"],
    textC: 0,
    img: ["Avant rentrée", "Noël", "Jamais"],
    imgC: 0,
    fillQ: "Ils étudient un peu avant la ___ .",
    fill: "rentrée",
    fillA: ["rentree", "rentrée"],
  },
  {
    id: "sar26-q7",
    textQ: "Quel type de séjour permet de découvrir une autre culture ?",
    text: ["Échange scolaire", "Repos à la maison", "Travail en usine"],
    textC: 0,
    img: ["Échange", "Repos", "Usine"],
    imgC: 0,
    fillQ: "Un échange scolaire permet de découvrir une autre ___ .",
    fill: "culture",
    fillA: ["culture"],
  },
  {
    id: "sar26-q8",
    textQ: "Pourquoi les parents envoient-ils leurs enfants en colonie ?",
    text: ["Pour développer l'autonomie", "Pour punir", "Pour éviter l'école"],
    textC: 0,
    img: ["Autonomie", "Punir", "Éviter école"],
    imgC: 0,
    fillQ: "Les colonies font partie des nombreuses ___ .",
    fill: "possibilités",
    fillA: ["possibilites", "possibilités"],
  },
  {
    id: "sar26-q9",
    textQ: "Quel support d'apprentissage est mentionné pour l'été ?",
    text: ["Cahiers de vacances", "Dictionnaires uniquement", "Aucun support"],
    textC: 0,
    img: ["Cahiers", "Dictionnaires", "Aucun"],
    imgC: 0,
    fillQ: "Les jeunes utilisent des cahiers de ___ .",
    fill: "vacances",
    fillA: ["vacances"],
  },
  {
    id: "sar26-q10",
    textQ: "Que peuvent faire certains jeunes pour gagner de l'argent l'été ?",
    text: ["Un job d'été", "Rien", "Vendre leur école"],
    textC: 0,
    img: ["Job d'été", "Rien", "Vendre école"],
    imgC: 0,
    fillQ: "Certains font un ___ d'été.",
    fill: "job",
    fillA: ["job", "travail", "emploi"],
  },
  {
    id: "sar26-q11",
    textQ: "Les vacances modernes combinent souvent…",
    text: ["Voyage et étude", "Sommeil et télévision", "Travail et punition"],
    textC: 0,
    img: ["Voyage et étude", "Sommeil TV", "Travail punition"],
    imgC: 0,
    fillQ: "On part en voyage puis on ___ un peu.",
    fill: "étudie",
    fillA: ["etudie", "étudie", "travaille"],
  },
  {
    id: "sar26-q12",
    textQ: "Quel objectif ont les séjours linguistiques ?",
    text: ["Apprendre une langue et découvrir une culture", "Ne plus aller à l'école", "Regarder la télévision"],
    textC: 0,
    img: ["Langue et culture", "Pas école", "Télévision"],
    imgC: 0,
    fillQ: "Ils recherchent l'indépendance et une autre ___ .",
    fill: "culture",
    fillA: ["culture"],
  },
  {
    id: "sar26-q13",
    textQ: "Quel travail d'été certains jeunes peuvent-ils faire ?",
    text: ["Un job d'été", "Un stage obligatoire", "Un concours"],
    textC: 0,
    img: ["Job", "Stage", "Concours"],
    imgC: 0,
    fillQ: "Les possibilités sont nombreuses : colonies, séjours linguistiques, camps sportifs ou jobs d'___.",
    fill: "été",
    fillA: ["ete", "été"],
  },
  {
    id: "sar26-q14",
    textQ: "Avec quoi certains jeunes travaillent-ils pendant les vacances ?",
    text: ["Les cahiers de vacances", "Des jeux vidéo", "Des bandes dessinées"],
    textC: 0,
    img: ["Cahiers", "Jeux", "BD"],
    imgC: 0,
    fillQ: "Beaucoup travaillent avec les cahiers de ___.",
    fill: "vacances",
    fillA: ["vacances"],
  },
  {
    id: "sar26-q15",
    textQ: "Partir sans la famille peut aider les enfants à développer leur…",
    text: ["Autonomie", "Timidité", "Paresse"],
    textC: 0,
    img: ["Autonomie", "Timidité", "Paresse"],
    imgC: 0,
    fillQ: "Partir seul permet aux enfants de développer leur ___.",
    fill: "autonomie",
    fillA: ["autonomie"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_27 = buildPool("avance", "scolaire-radio-27", [
  {
    id: "sar27-q1",
    textQ: "À quel public est destinée cette émission ?",
    text: ["Aux adolescents", "Aux retraités", "Aux enfants"],
    textC: 0,
    img: ["Adolescents", "Retraités", "Enfants"],
    imgC: 0,
    fillQ: "L'émission est destinée aux ___.",
    fill: "ados",
    fillA: ["ados", "adolescents", "jeunes"],
  },
  {
    id: "sar27-q2",
    textQ: "D'après les sondages, quel est le loisir préféré des filles ?",
    text: ["Les activités artistiques", "Les activités sportives", "Les sorties entre amies"],
    textC: 2,
    img: ["Artistique", "Sport", "Sorties amies"],
    imgC: 2,
    fillQ: "Les filles aiment surtout sortir entre ___ .",
    fill: "amies",
    fillA: ["amies", "copines"],
  },
  {
    id: "sar27-q3",
    textQ: "Quel sport Myriam pratique-t-elle ?",
    text: ["Le ballet", "La gymnastique", "Le tennis"],
    textC: 1,
    img: ["Ballet", "Gymnastique", "Tennis"],
    imgC: 1,
    fillQ: "Elle a arrêté le ___ et le piano.",
    fill: "ballet",
    fillA: ["ballet", "danse"],
  },
  {
    id: "sar27-q4",
    textQ: "Pourquoi Myriam a-t-elle arrêté certaines activités ?",
    text: ["Les activités coûtaient trop cher", "C'est une décision de ses parents seulement", "Elle voulait avoir plus de temps libre"],
    textC: 0,
    img: ["Trop cher", "Parents", "Temps libre"],
    imgC: 0,
    fillQ: "Les activités prenaient tout son temps ___ .",
    fill: "libre",
    fillA: ["libre"],
  },
  {
    id: "sar27-q5",
    textQ: "Pourquoi Christopher dit-il que le tennis n'est pas un loisir ?",
    text: ["Parce qu'on l'a obligé à pratiquer", "Parce que c'est trop difficile", "Parce qu'il doit faire de la compétition"],
    textC: 2,
    img: ["Obligé", "Difficile", "Compétition"],
    imgC: 2,
    fillQ: "Il doit s'___ et jouer des matchs.",
    fill: "entraîner",
    fillA: ["entrainer", "entraîner"],
  },
  {
    id: "sar27-q6",
    textQ: "Pour Myriam, la journée idéale est…",
    text: ["Ne rien faire et se reposer chez elle", "Regarder des films avec ses amis", "Sortir et voir ses copains"],
    textC: 2,
    img: ["Rien faire", "Films", "Sortir copains"],
    imgC: 2,
    fillQ: "Elle aimerait aller en ville ou au ___ .",
    fill: "cinéma",
    fillA: ["cinema", "cinéma"],
  },
  {
    id: "sar27-q7",
    textQ: "Christopher voudrait pouvoir passer une journée…",
    text: ["Qui ne serait pas du tout programmée", "Sans ses parents, seulement avec des amis", "Tranquille et tout seul"],
    textC: 0,
    img: ["Non programmée", "Sans parents", "Seul"],
    imgC: 0,
    fillQ: "Il ne veut ni entraînement ni ___ .",
    fill: "cours",
    fillA: ["cours", "cour"],
  },
  {
    id: "sar27-q8",
    textQ: "À quel âge Christopher a-t-il commencé le tennis ?",
    text: ["Très jeune", "À 18 ans", "L'année dernière seulement"],
    textC: 0,
    img: ["Très jeune", "18 ans", "L'an dernier"],
    imgC: 0,
    fillQ: "On l'a inscrit très ___ .",
    fill: "jeune",
    fillA: ["jeune", "tot"],
  },
  {
    id: "sar27-q9",
    textQ: "Quelles activités Myriam a-t-elle abandonnées ?",
    text: ["Ballet et piano", "Football et natation", "Lecture et dessin"],
    textC: 0,
    img: ["Ballet et piano", "Foot et natation", "Lecture"],
    imgC: 0,
    fillQ: "Elle garde la ___ .",
    fill: "gymnastique",
    fillA: ["gymnastique", "gym"],
  },
  {
    id: "sar27-q10",
    textQ: "Pourquoi Christopher n'appelle-t-il pas le tennis un loisir ?",
    text: ["Parce qu'il doit compétitionner", "Parce qu'il déteste le sport", "Parce qu'il n'a pas de raquette"],
    textC: 0,
    img: ["Compétition", "Déteste sport", "Pas raquette"],
    imgC: 0,
    fillQ: "Le tennis est devenu une ___ pour lui.",
    fill: "obligation",
    fillA: ["obligation", "contrainte"],
  },
  {
    id: "sar27-q11",
    textQ: "Que veut faire Myriam avec ses copains ?",
    text: ["Rester enfermée", "Sortir en ville", "Dormir toute la journée"],
    textC: 1,
    img: ["Enfermée", "Sortir", "Dormir"],
    imgC: 1,
    fillQ: "Sa journée idéale, c'est de ___ .",
    fill: "sortir",
    fillA: ["sortir"],
  },
  {
    id: "sar27-q12",
    textQ: "Quel problème Christopher dénonce-t-il ?",
    text: ["Un emploi du temps trop chargé", "Le manque de nourriture", "L'absence d'amis"],
    textC: 0,
    img: ["Emploi du temps", "Nourriture", "Pas d'amis"],
    imgC: 0,
    fillQ: "Il rêve d'une journée sans ___ .",
    fill: "programme",
    fillA: ["programme", "planning", "horaire"],
  },
  {
    id: "sar27-q13",
    textQ: "Quelles activités Myriam a-t-elle arrêtées ?",
    text: ["Le ballet et le piano", "Le tennis et le piano", "La gymnastique et le chant"],
    textC: 0,
    img: ["Ballet et piano", "Tennis", "Gym et chant"],
    imgC: 0,
    fillQ: "J'ai arrêté le ballet et le ___.",
    fill: "piano",
    fillA: ["piano"],
  },
  {
    id: "sar27-q14",
    textQ: "Comment Christopher pratique-t-il le tennis ?",
    text: ["En compétition", "Comme loisir uniquement", "Une fois par an"],
    textC: 0,
    img: ["Compétition", "Loisir", "Rarement"],
    imgC: 0,
    fillQ: "Je fais du tennis en ___.",
    fill: "compétition",
    fillA: ["competition", "compétition"],
  },
  {
    id: "sar27-q15",
    textQ: "À quelle fréquence Myriam voit-elle ses amis le week-end ?",
    text: ["Chaque samedi", "Une fois par mois", "Jamais"],
    textC: 0,
    img: ["Chaque samedi", "1×/mois", "Jamais"],
    imgC: 0,
    fillQ: "Je ne passe pas un samedi sans voir mes ___.",
    fill: "amis",
    fillA: ["amis", "ami"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_28 = buildPool("avance", "scolaire-radio-28", [
  {
    id: "sar28-q1",
    textQ: "Le projet de loi sur l'anonymat est…",
    text: ["Une certitude", "Une possibilité", "Une fausse information"],
    textC: 1,
    img: ["Certitude", "Possibilité", "Fausse info"],
    imgC: 1,
    fillQ: "Le projet est discuté au ___ .",
    fill: "parlement",
    fillA: ["parlement", "Parlement"],
  },
  {
    id: "sar28-q2",
    textQ: "Quelle est la spécialité de Stéphanie Blanchard ?",
    text: ["La psychologie des internautes", "Les comportements des adolescents", "Les jeux vidéo en ligne"],
    textC: 1,
    img: ["Psychologie", "Comportements ados", "Jeux vidéo"],
    imgC: 1,
    fillQ: "Elle étudie les adolescents sur le ___ .",
    fill: "web",
    fillA: ["web", "internet", "Internet"],
  },
  {
    id: "sar28-q3",
    textQ: "D'après Stéphanie Blanchard, les gens cachent leur identité sur les réseaux sociaux…",
    text: ["Par manque de courage", "Pour ne pas mêler vie privée et professionnelle", "Pour montrer une meilleure image d'eux"],
    textC: 1,
    img: ["Manque courage", "Vie privée/pro", "Meilleure image"],
    imgC: 1,
    fillQ: "Ils séparent vie privée et vie ___ .",
    fill: "professionnelle",
    fillA: ["professionnelle", "pro"],
  },
  {
    id: "sar28-q4",
    textQ: "D'après Hervé Lacroix, l'anonymat…",
    text: ["Facilite et encourage souvent la violence", "Diminue la violence", "Est toujours synonyme de violence"],
    textC: 0,
    img: ["Encourage violence", "Diminue violence", "Toujours violence"],
    imgC: 0,
    fillQ: "L'anonymat peut encourager la violence en ___ .",
    fill: "ligne",
    fillA: ["ligne", "ligne"],
  },
  {
    id: "sar28-q5",
    textQ: "Quelle est l'opinion de Hervé Lacroix ?",
    text: ["Il faut interdire l'anonymat sur Internet", "Il faut condamner plus souvent les actes violents", "Il faut donner des moyens aux gens de se défendre en ligne"],
    textC: 2,
    img: ["Interdire", "Condamner", "Moyens de défense"],
    imgC: 2,
    fillQ: "Il faut aider les gens à se ___ en ligne.",
    fill: "défendre",
    fillA: ["defendre", "défendre", "proteger", "protéger"],
  },
  {
    id: "sar28-q6",
    textQ: "À la fin de l'émission, Stéphanie Blanchard parle des anonymes…",
    text: ["Par nécessité", "Par esprit de contradiction", "Par envie"],
    textC: 0,
    img: ["Nécessité", "Contradiction", "Envie"],
    imgC: 0,
    fillQ: "Certains restent anonymes pour ___ des violences.",
    fill: "dénoncer",
    fillA: ["denoncer", "dénoncer"],
  },
  {
    id: "sar28-q7",
    textQ: "Que permet notamment l'anonymat pour ces personnes ?",
    text: ["De trouver un emploi", "De dénoncer des violences", "De faire de la publicité cachée"],
    textC: 1,
    img: ["Emploi", "Dénoncer violences", "Publicité"],
    imgC: 1,
    fillQ: "Ils peuvent parler plus ___ .",
    fill: "librement",
    fillA: ["librement", "libre"],
  },
  {
    id: "sar28-q8",
    textQ: "Que pense Stéphanie Blanchard de l'interdiction totale ?",
    text: ["Elle est d'accord", "Elle n'est pas d'accord pour tout interdire", "Elle n'a pas d'avis"],
    textC: 1,
    img: ["D'accord", "Pas tout interdire", "Pas d'avis"],
    imgC: 1,
    fillQ: "Elle ne veut pas ___ l'anonymat complètement.",
    fill: "interdire",
    fillA: ["interdire", "supprimer"],
  },
  {
    id: "sar28-q9",
    textQ: "Quel risque Hervé Lacroix associe-t-il à l'anonymat ?",
    text: ["La violence en ligne", "La perte d'emploi", "L'interdiction d'Internet"],
    textC: 0,
    img: ["Violence", "Emploi", "Interdiction"],
    imgC: 0,
    fillQ: "L'anonymat ___ la violence.",
    fill: "facilite",
    fillA: ["facilite", "facilite", "encourage"],
  },
  {
    id: "sar28-q10",
    textQ: "Pourquoi certains utilisent-ils l'anonymat selon Stéphanie Blanchard ?",
    text: ["Pour éviter les représailles", "Pour devenir célèbres", "Pour vendre des produits"],
    textC: 0,
    img: ["Éviter représailles", "Célébrité", "Vendre"],
    imgC: 0,
    fillQ: "Ils veulent parler sans risquer de ___ .",
    fill: "représailles",
    fillA: ["represailles", "représailles", "danger"],
  },
  {
    id: "sar28-q11",
    textQ: "Quel est le métier de Hervé Lacroix ?",
    text: ["Expert en sécurité numérique", "Professeure de français", "Styliste"],
    textC: 0,
    img: ["Sécurité numérique", "Prof français", "Styliste"],
    imgC: 0,
    fillQ: "Il est expert en sécurité ___ .",
    fill: "numérique",
    fillA: ["numerique", "numérique"],
  },
  {
    id: "sar28-q12",
    textQ: "Quel débat oppose les deux invités ?",
    text: ["Le prix d'Internet", "L'anonymat : danger ou protection", "Les jeux vidéo"],
    textC: 1,
    img: ["Prix Internet", "Anonymat", "Jeux vidéo"],
    imgC: 1,
    fillQ: "Le débat porte sur l'___ sur Internet.",
    fill: "anonymat",
    fillA: ["anonymat"],
  },
  {
    id: "sar28-q13",
    textQ: "D'après Hervé Lacroix, l'anonymat encourage souvent…",
    text: ["La violence en ligne", "La lecture", "Le sport"],
    textC: 0,
    img: ["Violence", "Lecture", "Sport"],
    imgC: 0,
    fillQ: "L'anonymat facilite et encourage souvent la violence en ___.",
    fill: "ligne",
    fillA: ["ligne"],
  },
  {
    id: "sar28-q14",
    textQ: "Quelle est la spécialité de Stéphanie Blanchard ?",
    text: ["Les comportements des adolescents sur le web", "La mode", "La cuisine"],
    textC: 0,
    img: ["Ados et web", "Mode", "Cuisine"],
    imgC: 0,
    fillQ: "Spécialiste des comportements des adolescents sur le ___.",
    fill: "web",
    fillA: ["web", "internet"],
  },
  {
    id: "sar28-q15",
    textQ: "Que conseille Hervé Lacroix de donner aux internautes ?",
    text: ["Des moyens de se défendre", "Des interdictions totales", "Des jeux vidéo"],
    textC: 0,
    img: ["Défense", "Interdictions", "Jeux"],
    imgC: 0,
    fillQ: "Il faut surtout donner aux gens des moyens de se ___.",
    fill: "défendre",
    fillA: ["defendre", "défendre"],
  }
]);

export const SCOLAIRE_AVANCE_RADIO_29 = buildPool("avance", "scolaire-radio-29", [
  {
    id: "sar29-q1",
    textQ: "Où a lieu l'interview ?",
    text: ["Au domicile de la styliste", "Dans un grand atelier de couture", "Dans un studio de télévision"],
    textC: 2,
    img: ["Domicile", "Atelier", "Studio TV"],
    imgC: 2,
    fillQ: "L'interview se passe en ___ .",
    fill: "télévision",
    fillA: ["television", "télévision", "studio"],
  },
  {
    id: "sar29-q2",
    textQ: "Pourquoi Anne-Laure a choisi d'être styliste ?",
    text: ["Parce que sa mère était couturière", "Parce qu'elle a toujours aimé faire des vêtements", "Parce qu'elle regardait souvent des défilés"],
    textC: 1,
    img: ["Mère couturière", "Aimé vêtements", "Défilés"],
    imgC: 1,
    fillQ: "Elle aime créer des formes et des ___ .",
    fill: "couleurs",
    fillA: ["couleurs", "couleur"],
  },
  {
    id: "sar29-q3",
    textQ: "Qu'est-ce qui a aidé Anne-Laure dans sa carrière ?",
    text: ["Les visites chez une amie couturière", "Elle a fait des rencontres intéressantes", "Ses années d'apprentissage chez une styliste"],
    textC: 2,
    img: ["Visites amie", "Rencontres", "Apprentissage"],
    imgC: 2,
    fillQ: "Elle a passé des années d'___ chez une styliste.",
    fill: "apprentissage",
    fillA: ["apprentissage", "stage"],
  },
  {
    id: "sar29-q4",
    textQ: "Quelle est la différence entre un styliste et un couturier ?",
    text: ["Le couturier doit faire plus d'études", "Le styliste devient plus facilement célèbre", "Le styliste est un artiste plus libre de créer"],
    textC: 2,
    img: ["Plus d'études", "Plus célèbre", "Plus libre"],
    imgC: 2,
    fillQ: "Le couturier réalise les ___ avec précision.",
    fill: "modèles",
    fillA: ["modeles", "modèles"],
  },
  {
    id: "sar29-q5",
    textQ: "Anne-Laure fait des expositions et des défilés pour…",
    text: ["Faire connaître son travail", "Connaître d'autres stylistes", "Copier ce que font les autres"],
    textC: 0,
    img: ["Faire connaître", "Rencontrer stylistes", "Copier"],
    imgC: 0,
    fillQ: "Elle veut faire connaître ses ___ .",
    fill: "créations",
    fillA: ["creations", "créations", "collections"],
  },
  {
    id: "sar29-q6",
    textQ: "Quelles sont les conséquences de ses défilés ?",
    text: ["On parle de sa créativité dans les médias", "Les personnes lui passent des commandes", "D'autres créateurs lui demandent de collaborer"],
    textC: 1,
    img: ["Médias", "Commandes", "Collaboration"],
    imgC: 1,
    fillQ: "Sa ___ est parfois commentée dans les médias.",
    fill: "créativité",
    fillA: ["creativite", "créativité"],
  },
  {
    id: "sar29-q7",
    textQ: "Comment doit être un styliste pour avoir des clients ?",
    text: ["Il doit s'adapter et avoir envie de travailler", "Il doit appliquer de bons prix", "Il doit être fidèle à ses clients"],
    textC: 0,
    img: ["S'adapter", "Bons prix", "Fidèle"],
    imgC: 0,
    fillQ: "C'est un métier ___ .",
    fill: "exigeant",
    fillA: ["exigeant", "difficile", "dur"],
  },
  {
    id: "sar29-q8",
    textQ: "Que crée principalement un styliste ?",
    text: ["Des collections et des formes", "Des voitures", "Des plats cuisinés"],
    textC: 0,
    img: ["Collections", "Voitures", "Plats"],
    imgC: 0,
    fillQ: "Le styliste imagine les ___ .",
    fill: "collections",
    fillA: ["collections", "collection"],
  },
  {
    id: "sar29-q9",
    textQ: "Pourquoi Anne-Laure organise-t-elle des défilés ?",
    text: ["Pour se faire connaître", "Pour arrêter la mode", "Pour voyager gratuitement"],
    textC: 0,
    img: ["Se faire connaître", "Arrêter mode", "Voyager"],
    imgC: 0,
    fillQ: "Après un défilé, elle peut recevoir des ___ .",
    fill: "commandes",
    fillA: ["commandes", "commande"],
  },
  {
    id: "sar29-q10",
    textQ: "Quelle qualité professionnelle Anne-Laure cite-t-elle ?",
    text: ["S'adapter aux demandes des clients", "Ne jamais travailler", "Copier les autres"],
    textC: 0,
    img: ["S'adapter", "Ne pas travailler", "Copier"],
    imgC: 0,
    fillQ: "Il faut avoir envie de ___ .",
    fill: "travailler",
    fillA: ["travailler"],
  },
  {
    id: "sar29-q11",
    textQ: "Quel métier réalise les vêtements avec précision ?",
    text: ["Styliste", "Couturier", "Journaliste"],
    textC: 1,
    img: ["Styliste", "Couturier", "Journaliste"],
    imgC: 1,
    fillQ: "Le styliste est plus libre de ___ .",
    fill: "créer",
    fillA: ["creer", "créer"],
  },
  {
    id: "sar29-q12",
    textQ: "Quel avantage un défilé peut-il apporter ?",
    text: ["Des commandes de clients", "Un examen scolaire", "Un voyage obligatoire"],
    textC: 0,
    img: ["Commandes", "Examen", "Voyage"],
    imgC: 0,
    fillQ: "Les médias parlent parfois de son ___ .",
    fill: "travail",
    fillA: ["travail", "talent"],
  },
  {
    id: "sar29-q13",
    textQ: "Quelle formation Anne-Laure a-t-elle suivie ?",
    text: ["Des années d'apprentissage", "Des études de médecine", "Un cursus de droit"],
    textC: 0,
    img: ["Apprentissage", "Médecine", "Droit"],
    imgC: 0,
    fillQ: "J'ai aussi passé des années d'___.",
    fill: "apprentissage",
    fillA: ["apprentissage"],
  },
  {
    id: "sar29-q14",
    textQ: "Qui réalise souvent les modèles avec précision ?",
    text: ["Le couturier", "Le styliste", "Le client"],
    textC: 0,
    img: ["Couturier", "Styliste", "Client"],
    imgC: 0,
    fillQ: "Le couturier réalise souvent les modèles avec ___.",
    fill: "précision",
    fillA: ["precision", "précision"],
  },
  {
    id: "sar29-q15",
    textQ: "Que peuvent faire certaines personnes après un défilé d'Anne-Laure ?",
    text: ["Lui passer des commandes", "Devenir mannequins", "Fermer son atelier"],
    textC: 0,
    img: ["Commandes", "Mannequins", "Fermer"],
    imgC: 0,
    fillQ: "Des personnes me passent parfois des ___.",
    fill: "commandes",
    fillA: ["commandes", "commande"],
  }
]);

export const SCOLAIRE_AVANCE_RADIOS_BOOK: Record<string, COMultiQuestion[]> = {
  "avance-scolaire-radio-15": SCOLAIRE_AVANCE_RADIO_15,
  "avance-scolaire-radio-16": SCOLAIRE_AVANCE_RADIO_16,
  "avance-scolaire-radio-17": SCOLAIRE_AVANCE_RADIO_17,
  "avance-scolaire-radio-18": SCOLAIRE_AVANCE_RADIO_18,
  "avance-scolaire-radio-19": SCOLAIRE_AVANCE_RADIO_19,
  "avance-scolaire-radio-20": SCOLAIRE_AVANCE_RADIO_20,
  "avance-scolaire-radio-21": SCOLAIRE_AVANCE_RADIO_21,
  "avance-scolaire-radio-22": SCOLAIRE_AVANCE_RADIO_22,
  "avance-scolaire-radio-23": SCOLAIRE_AVANCE_RADIO_23,
  "avance-scolaire-radio-24": SCOLAIRE_AVANCE_RADIO_24,
  "avance-scolaire-radio-25": SCOLAIRE_AVANCE_RADIO_25,
  "avance-scolaire-radio-26": SCOLAIRE_AVANCE_RADIO_26,
  "avance-scolaire-radio-27": SCOLAIRE_AVANCE_RADIO_27,
  "avance-scolaire-radio-28": SCOLAIRE_AVANCE_RADIO_28,
  "avance-scolaire-radio-29": SCOLAIRE_AVANCE_RADIO_29,
};
