import { buildPool, type COMultiQuestion } from "./co-questions-helpers";

/** CO avancé scolaire / B1 — annonces (exercices 30 à 36). */

export const SCOLAIRE_AVANCE_ANNONCE_30 = buildPool("avance", "scolaire-annonce-30", [
  {
    id: "saa30-q1",
    textQ: "Dans quelle ville se trouve le cinéma Le Studio ?",
    text: ["À Tours", "À Paris", "À Lyon"],
    textC: 0,
    img: ["Tours", "Paris", "Lyon"],
    imgC: 0,
    fillQ: "Le cinéma se trouve à ___ .",
    fill: "Tours",
    fillA: ["tours"],
  },
  {
    id: "saa30-q2",
    textQ: "Jusqu'à quelle heure le cinéma est-il ouvert ?",
    text: ["À 22 h", "À minuit", "À 20 h"],
    textC: 1,
    img: ["22 h", "Minuit", "20 h"],
    imgC: 1,
    fillQ: "Le Studio est ouvert jusqu'à ___ .",
    fill: "minuit",
    fillA: ["minuit", "00h"],
  },
  {
    id: "saa30-q3",
    textQ: "Qui a réalisé le film Hors norme ?",
    text: ["Olivier Nakache", "Alexis Michalik", "Matthias Malzieux"],
    textC: 0,
    img: ["Nakache", "Michalik", "Malzieux"],
    imgC: 0,
    fillQ: "Hors norme est une comédie d'Olivier ___ .",
    fill: "Nakache",
    fillA: ["nakache"],
  },
  {
    id: "saa30-q4",
    textQ: "De quoi parle le film Hors norme ?",
    text: ["D'enfants et adolescents autistes", "D'un voyage en mer", "D'une guerre"],
    textC: 0,
    img: ["Autisme", "Mer", "Guerre"],
    imgC: 0,
    fillQ: "Bruno et Malik encadrent des enfants ___ .",
    fill: "autistes",
    fillA: ["autiste", "autistes"],
  },
  {
    id: "saa30-q5",
    textQ: "Quel est le titre de la pièce qu'Edmond écrit ?",
    text: ["Cyrano de Bergerac", "Le Cid", "Phèdre"],
    textC: 0,
    img: ["Cyrano", "Le Cid", "Phèdre"],
    imgC: 0,
    fillQ: "Edmond n'a pour l'instant que le titre : ___ de Bergerac.",
    fill: "Cyrano",
    fillA: ["cyrano"],
  },
  {
    id: "saa30-q6",
    textQ: "Dans Une sirène à Paris, qui est Lula ?",
    text: ["Une sirène", "Une journaliste", "Une professeure"],
    textC: 0,
    img: ["Sirène", "Journaliste", "Professeure"],
    imgC: 0,
    fillQ: "Lula est une jolie ___ .",
    fill: "sirène",
    fillA: ["sirene", "sirène"],
  },
  {
    id: "saa30-q7",
    textQ: "Où vit Gaspar dans Une sirène à Paris ?",
    text: ["Sur une péniche au bord de la Seine", "À la montagne", "Dans un château"],
    textC: 0,
    img: ["Péniche", "Montagne", "Château"],
    imgC: 0,
    fillQ: "Gaspar habite sur la péniche ___ Power.",
    fill: "Flower",
    fillA: ["flower"],
  },
  {
    id: "saa30-q8",
    textQ: "Combien de minutes dure le film Edmond ?",
    text: ["142 minutes", "153 minutes", "155 minutes"],
    textC: 1,
    img: ["142", "153", "155"],
    imgC: 1,
    fillQ: "Edmond dure ___ minutes.",
    fill: "153",
    fillA: ["153", "cent cinquante-trois"],
  },
  {
    id: "saa30-q9",
    textQ: "À quelle époque se situe le film Edmond ?",
    text: ["En 1897", "En 1997", "Au Moyen Âge"],
    textC: 0,
    img: ["1897", "1997", "Moyen Âge"],
    imgC: 0,
    fillQ: "L'histoire se passe en décembre ___ .",
    fill: "1897",
    fillA: ["1897"],
  },
  {
    id: "saa30-q10",
    textQ: "Quel site Internet est mentionné ?",
    text: ["www.lestudiotours.com", "www.cinema.fr", "www.allocine.com"],
    textC: 0,
    img: ["Site Studio", "Cinema.fr", "Allociné"],
    imgC: 0,
    fillQ: "Les horaires sont sur le site www.lestudiotours.___",
    fill: "com",
    fillA: ["com"],
  },
  {
    id: "saa30-q11",
    textQ: "Quel genre est Une sirène à Paris ?",
    text: ["Film fantastique", "Comédie historique", "Documentaire"],
    textC: 0,
    img: ["Fantastique", "Historique", "Documentaire"],
    imgC: 0,
    fillQ: "C'est un film ___ et un drame.",
    fill: "fantastique",
    fillA: ["fantastique"],
  },
  {
    id: "saa30-q12",
    textQ: "À partir de quelle heure le cinéma ouvre-t-il ?",
    text: ["12 heures", "14 heures", "16 heures"],
    textC: 1,
    img: ["12 h", "14 h", "16 h"],
    imgC: 1,
    fillQ: "Le Studio ouvre tous les jours à ___ heures.",
    fill: "14",
    fillA: ["14", "quatorze"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_31 = buildPool("avance", "scolaire-annonce-31", [
  {
    id: "saa31-q1",
    textQ: "Quel appareil le couple veut-il acheter ?",
    text: ["Une machine à laver", "Un four", "Un réfrigérateur"],
    textC: 0,
    img: ["Machine à laver", "Four", "Réfrigérateur"],
    imgC: 0,
    fillQ: "Ils veulent acheter une machine à ___ .",
    fill: "laver",
    fillA: ["laver"],
  },
  {
    id: "saa31-q2",
    textQ: "Comment s'appelle le magasin ?",
    text: ["Tout Pacher", "Carrefour", "Leclerc"],
    textC: 0,
    img: ["Tout Pacher", "Carrefour", "Leclerc"],
    imgC: 0,
    fillQ: "Les promos sont chez ___ Pacher.",
    fill: "Tout",
    fillA: ["tout"],
  },
  {
    id: "saa31-q3",
    textQ: "Quelle réduction sur les jeux vidéo ?",
    text: ["10 %", "20 %", "30 %"],
    textC: 2,
    img: ["10 %", "20 %", "30 %"],
    imgC: 2,
    fillQ: "Les jeux vidéo sont à ___ % de réduction.",
    fill: "30",
    fillA: ["30", "trente"],
  },
  {
    id: "saa31-q4",
    textQ: "Jusqu'à quelle heure le magasin est-il ouvert ?",
    text: ["20 h", "21 h", "22 h"],
    textC: 1,
    img: ["20 h", "21 h", "22 h"],
    imgC: 1,
    fillQ: "Le magasin ouvre jusqu'à ___ heures.",
    fill: "21",
    fillA: ["21", "vingt-et-une"],
  },
  {
    id: "saa31-q5",
    textQ: "Quelle réduction sur la téléphonie ?",
    text: ["5 %", "10 %", "30 %"],
    textC: 1,
    img: ["5 %", "10 %", "30 %"],
    imgC: 1,
    fillQ: "La téléphonie est à ___ % de réduction.",
    fill: "10",
    fillA: ["10", "dix"],
  },
  {
    id: "saa31-q6",
    textQ: "Quel est le montant minimum d'achat pour le concours ?",
    text: ["10 euros", "20 euros", "50 euros"],
    textC: 1,
    img: ["10 €", "20 €", "50 €"],
    imgC: 1,
    fillQ: "Il faut acheter pour un minimum de ___ euros.",
    fill: "20",
    fillA: ["20", "vingt"],
  },
  {
    id: "saa31-q7",
    textQ: "Quel est le lot principal du concours ?",
    text: ["5 jours dans un centre de remise en forme", "Une machine à laver", "Un ordinateur"],
    textC: 0,
    img: ["Spa", "Machine", "Ordinateur"],
    imgC: 0,
    fillQ: "On peut gagner cinq jours dans un centre de remise en ___ .",
    fill: "forme",
    fillA: ["forme"],
  },
  {
    id: "saa31-q8",
    textQ: "À partir de quelle date commence le concours ?",
    text: ["Le 1er juillet", "Le 10 juillet", "Le 1er août"],
    textC: 1,
    img: ["1er juillet", "10 juillet", "1er août"],
    imgC: 1,
    fillQ: "Le concours commence le ___ juillet.",
    fill: "10",
    fillA: ["10", "dix"],
  },
  {
    id: "saa31-q9",
    textQ: "Peut-on remplir plusieurs bulletins de concours ?",
    text: ["Non", "Oui, sans limite", "Oui, deux maximum"],
    textC: 0,
    img: ["Non", "Oui illimité", "Deux max"],
    imgC: 0,
    fillQ: "Il n'est pas possible de remplir plusieurs ___ .",
    fill: "bulletins",
    fillA: ["bulletin", "bulletins"],
  },
  {
    id: "saa31-q10",
    textQ: "De combien de jours la promotion a-t-elle été prolongée ?",
    text: ["Un jour", "Deux jours", "Une semaine"],
    textC: 1,
    img: ["1 jour", "2 jours", "1 semaine"],
    imgC: 1,
    fillQ: "La promotion est prolongée de deux ___ .",
    fill: "jours",
    fillA: ["jour", "jours"],
  },
  {
    id: "saa31-q11",
    textQ: "Quelle réduction sur l'électroménager et les ordinateurs ?",
    text: ["10 %", "20 %", "30 %"],
    textC: 1,
    img: ["10 %", "20 %", "30 %"],
    imgC: 1,
    fillQ: "L'électroménager est à ___ % de réduction.",
    fill: "20",
    fillA: ["20", "vingt"],
  },
  {
    id: "saa31-q12",
    textQ: "Où déposer le bulletin de concours ?",
    text: ["Dans la boîte à la sortie", "Par courriel", "Au rayon jeux vidéo"],
    textC: 0,
    img: ["Sortie", "Courriel", "Jeux vidéo"],
    imgC: 0,
    fillQ: "Il faut insérer le bulletin dans la boîte à la ___ du magasin.",
    fill: "sortie",
    fillA: ["sortie"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_32 = buildPool("avance", "scolaire-annonce-32", [
  {
    id: "saa32-q1",
    textQ: "De quoi parle l'émission ?",
    text: ["De l'alimentation à l'école", "Du sport scolaire", "Des vacances"],
    textC: 0,
    img: ["Cantine", "Sport", "Vacances"],
    imgC: 0,
    fillQ: "Le sujet est l'alimentation à l'___ .",
    fill: "école",
    fillA: ["ecole", "école"],
  },
  {
    id: "saa32-q2",
    textQ: "Que impose la loi française aux cantines ?",
    text: ["Un repas végétarien par semaine", "Deux desserts par jour", "Uniquement du bio"],
    textC: 0,
    img: ["Végétarien", "Desserts", "Bio"],
    imgC: 0,
    fillQ: "La loi impose un repas ___ par semaine.",
    fill: "végétarien",
    fillA: ["vegetarien", "végétarien"],
  },
  {
    id: "saa32-q3",
    textQ: "Comment s'appelle l'école de M. Chary ?",
    text: ["Saint-Exupéry", "Victor Hugo", "Marie Curie"],
    textC: 0,
    img: ["Saint-Exupéry", "Victor Hugo", "Marie Curie"],
    imgC: 0,
    fillQ: "M. Chary dirige l'école Saint-___ .",
    fill: "Exupéry",
    fillA: ["exupery", "exupéry"],
  },
  {
    id: "saa32-q4",
    textQ: "Dans quelle ville est l'école ?",
    text: ["À Rouen", "À Paris", "À Lyon"],
    textC: 0,
    img: ["Rouen", "Paris", "Lyon"],
    imgC: 0,
    fillQ: "L'école est à ___ .",
    fill: "Rouen",
    fillA: ["rouen"],
  },
  {
    id: "saa32-q5",
    textQ: "Quel menu est le plus choisi par les enfants ?",
    text: ["Le menu avec viande", "Le menu végétarien", "Le menu sans poisson"],
    textC: 0,
    img: ["Viande", "Végétarien", "Sans poisson"],
    imgC: 0,
    fillQ: "La consommation principale reste les menus avec de la ___ .",
    fill: "viande",
    fillA: ["viande"],
  },
  {
    id: "saa32-q6",
    textQ: "Quel plat végétarien avait été peu apprécié ?",
    text: ["Des lasagnes", "Une soupe", "Une salade"],
    textC: 0,
    img: ["Lasagnes", "Soupe", "Salade"],
    imgC: 0,
    fillQ: "Les lasagnes ___ avaient été peu goûtées.",
    fill: "végétariennes",
    fillA: ["vegetariennes", "végétariennes"],
  },
  {
    id: "saa32-q7",
    textQ: "Quel pourcentage de produits bio et locaux ?",
    text: ["32 %", "62 %", "92 %"],
    textC: 1,
    img: ["32 %", "62 %", "92 %"],
    imgC: 1,
    fillQ: "La cuisine centrale utilise ___ % de produits bio et locaux.",
    fill: "62",
    fillA: ["62", "soixante-deux"],
  },
  {
    id: "saa32-q8",
    textQ: "Combien de repas sont servis chaque jour à Rouen ?",
    text: ["Plus de 1 000", "Plus de 10 000", "Plus de 100 000"],
    textC: 1,
    img: ["1 000", "10 000", "100 000"],
    imgC: 1,
    fillQ: "Plus de ___ 000 repas sont servis chaque jour.",
    fill: "10",
    fillA: ["10", "dix"],
  },
  {
    id: "saa32-q9",
    textQ: "Quel pourcentage de produits frais ?",
    text: ["62 %", "92 %", "3 %"],
    textC: 1,
    img: ["62 %", "92 %", "3 %"],
    imgC: 1,
    fillQ: "Il y a ___ % de produits frais.",
    fill: "92",
    fillA: ["92", "quatre-vingt-douze"],
  },
  {
    id: "saa32-q10",
    textQ: "Pour qui la cantine reste-t-elle problématique ?",
    text: ["Les enfants végétaliens", "Les enfants allergiques au gluten", "Les enfants sportifs"],
    textC: 0,
    img: ["Végétaliens", "Gluten", "Sportifs"],
    imgC: 0,
    fillQ: "C'est problématique pour les enfants ___ .",
    fill: "végétaliens",
    fillA: ["vegetaliens", "végétaliens"],
  },
  {
    id: "saa32-q11",
    textQ: "Que propose l'école chaque jour depuis la rentrée ?",
    text: ["Un repas avec viande et un sans viande", "Uniquement du poisson", "Uniquement des légumes"],
    textC: 0,
    img: ["Viande et sans viande", "Poisson", "Légumes"],
    imgC: 0,
    fillQ: "Il y a un repas avec viande et un autre sans ___ .",
    fill: "viande",
    fillA: ["viande"],
  },
  {
    id: "saa32-q12",
    textQ: "Quel pourcentage de surgelés ?",
    text: ["3 %", "10 %", "30 %"],
    textC: 0,
    img: ["3 %", "10 %", "30 %"],
    imgC: 0,
    fillQ: "Il y a ___ % de produits surgelés.",
    fill: "3",
    fillA: ["3", "trois"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_33 = buildPool("avance", "scolaire-annonce-33", [
  {
    id: "saa33-q1",
    textQ: "Où peut-on faire signer ses albums ?",
    text: ["Dans le salon Open Space", "À la mairie", "Au cinéma"],
    textC: 0,
    img: ["Open Space", "Mairie", "Cinéma"],
    imgC: 0,
    fillQ: "Les dédicaces sont dans le salon ___ Space.",
    fill: "Open",
    fillA: ["open"],
  },
  {
    id: "saa33-q2",
    textQ: "À quelle heure commence le spectacle de danse asiatique ?",
    text: ["14 h", "15 h", "18 h"],
    textC: 1,
    img: ["14 h", "15 h", "18 h"],
    imgC: 1,
    fillQ: "Le spectacle de danse est à ___ heures.",
    fill: "15",
    fillA: ["15", "quinze"],
  },
  {
    id: "saa33-q3",
    textQ: "D'où viennent les artistes de danse ?",
    text: ["Du Japon", "De Chine", "De Corée"],
    textC: 0,
    img: ["Japon", "Chine", "Corée"],
    imgC: 0,
    fillQ: "Les artistes viennent du ___ .",
    fill: "Japon",
    fillA: ["japon"],
  },
  {
    id: "saa33-q4",
    textQ: "Comment s'appelle l'espace de rencontre des professionnels de la BD ?",
    text: ["Le carré en BD", "Le salon du livre", "La médiathèque"],
    textC: 0,
    img: ["Carré BD", "Salon livre", "Médiathèque"],
    imgC: 0,
    fillQ: "Le ___ en BD est ouvert à partir de 18 heures.",
    fill: "carré",
    fillA: ["carre", "carré"],
  },
  {
    id: "saa33-q5",
    textQ: "Comment s'appelle l'atelier de dessin collectif ?",
    text: ["Dessine ton histoire", "Dessine ta ville", "Dessine ton école"],
    textC: 0,
    img: ["Ton histoire", "Ta ville", "Ton école"],
    imgC: 0,
    fillQ: "L'événement s'appelle « Dessine ton ___ ».",
    fill: "histoire",
    fillA: ["histoire"],
  },
  {
    id: "saa33-q6",
    textQ: "Combien de personnes maximum par session d'atelier ?",
    text: ["Cinq", "Huit", "Dix"],
    textC: 1,
    img: ["5", "8", "10"],
    imgC: 1,
    fillQ: "Les places sont limitées à ___ personnes par session.",
    fill: "huit",
    fillA: ["8", "huit"],
  },
  {
    id: "saa33-q7",
    textQ: "À quelles heures ont lieu les sessions d'atelier ?",
    text: ["À 18 h et 20 h", "À 19 h et 21 h", "À 15 h et 17 h"],
    textC: 1,
    img: ["18 h et 20 h", "19 h et 21 h", "15 h et 17 h"],
    imgC: 1,
    fillQ: "Il y a une session à 19 heures et une autre à ___ heures.",
    fill: "21",
    fillA: ["21", "vingt-et-une"],
  },
  {
    id: "saa33-q8",
    textQ: "Combien d'ordinateurs sont disponibles pour le dessin collectif ?",
    text: ["Cinq", "Dix", "Vingt"],
    textC: 1,
    img: ["5", "10", "20"],
    imgC: 1,
    fillQ: "Il y a ___ ordinateurs reliés à une table de dessin.",
    fill: "dix",
    fillA: ["10", "dix"],
  },
  {
    id: "saa33-q9",
    textQ: "Pour qui est le concours de BD demain ?",
    text: ["Les lycéens et étudiants en art plastique", "Les enfants de primaire", "Les professeurs"],
    textC: 0,
    img: ["Lycéens", "Primaire", "Professeurs"],
    imgC: 0,
    fillQ: "Le concours est pour les lycéens et les étudiants en art ___ .",
    fill: "plastique",
    fillA: ["plastique"],
  },
  {
    id: "saa33-q10",
    textQ: "Combien de jours dure le festival ?",
    text: ["Deux jours", "Trois jours", "Une semaine"],
    textC: 1,
    img: ["2 jours", "3 jours", "1 semaine"],
    imgC: 1,
    fillQ: "Le festival dure ___ jours.",
    fill: "trois",
    fillA: ["3", "trois"],
  },
  {
    id: "saa33-q11",
    textQ: "De quoi la maison d'édition est-elle spécialisée ?",
    text: ["Du manga japonais", "Des romans policiers", "De la cuisine"],
    textC: 0,
    img: ["Manga", "Policier", "Cuisine"],
    imgC: 0,
    fillQ: "Elle est spécialisée en manga ___ .",
    fill: "japonais",
    fillA: ["japonais"],
  },
  {
    id: "saa33-q12",
    textQ: "À quelle heure est le concours demain ?",
    text: ["À 12 h", "À 15 h", "À 18 h"],
    textC: 1,
    img: ["12 h", "15 h", "18 h"],
    imgC: 1,
    fillQ: "Rendez-vous demain à ___ heures.",
    fill: "15",
    fillA: ["15", "quinze"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_34 = buildPool("avance", "scolaire-annonce-34", [
  {
    id: "saa34-q1",
    textQ: "Comment s'appelle le parc d'attractions ?",
    text: ["Walibi", "Disneyland", "Astérix"],
    textC: 0,
    img: ["Walibi", "Disneyland", "Astérix"],
    imgC: 0,
    fillQ: "Le parc s'appelle ___ .",
    fill: "Walibi",
    fillA: ["walibi"],
  },
  {
    id: "saa34-q2",
    textQ: "Combien d'attractions propose le parc ?",
    text: ["25", "35", "50"],
    textC: 1,
    img: ["25", "35", "50"],
    imgC: 1,
    fillQ: "Il y a ___ attractions.",
    fill: "35",
    fillA: ["35", "trente-cinq"],
  },
  {
    id: "saa34-q3",
    textQ: "Comment s'appelle le nouveau simulateur ?",
    text: ["X-MAD-3D", "X-MAC-2D", "VR-MAX"],
    textC: 0,
    img: ["X-MAD-3D", "X-MAC-2D", "VR-MAX"],
    imgC: 0,
    fillQ: "Le simulateur s'appelle X-___-3D.",
    fill: "MAD",
    fillA: ["mad", "MAD"],
  },
  {
    id: "saa34-q4",
    textQ: "À partir de quel âge l'attraction Adrénaline est-elle interdite ?",
    text: ["Moins de 10 ans", "Moins de 12 ans", "Moins de 16 ans"],
    textC: 1,
    img: ["10 ans", "12 ans", "16 ans"],
    imgC: 1,
    fillQ: "L'attraction est interdite aux moins de ___ ans.",
    fill: "douze",
    fillA: ["12", "douze"],
  },
  {
    id: "saa34-q5",
    textQ: "À quelle hauteur l'attraction Adrénaline propulse-t-elle ?",
    text: ["Plus de 20 mètres", "Plus de 30 mètres", "Plus de 50 mètres"],
    textC: 1,
    img: ["20 m", "30 m", "50 m"],
    imgC: 1,
    fillQ: "On est propulsé à plus de ___ mètres d'altitude.",
    fill: "trente",
    fillA: ["30", "trente"],
  },
  {
    id: "saa34-q6",
    textQ: "À quelle heure commence le spectacle de magie ?",
    text: ["12 h", "14 h", "16 h"],
    textC: 1,
    img: ["12 h", "14 h", "16 h"],
    imgC: 1,
    fillQ: "Le spectacle de magie est à ___ heures.",
    fill: "14",
    fillA: ["14", "quatorze"],
  },
  {
    id: "saa34-q7",
    textQ: "À quelle heure commence le spectacle du soir au bord du lac ?",
    text: ["20 h 30", "21 h 30", "22 h 30"],
    textC: 1,
    img: ["20 h 30", "21 h 30", "22 h 30"],
    imgC: 1,
    fillQ: "Le spectacle du soir commence à ___ h 30.",
    fill: "21",
    fillA: ["21", "vingt-et-une"],
  },
  {
    id: "saa34-q8",
    textQ: "Combien coûtent les menus à la cafétéria ?",
    text: ["6,50 euros", "8,50 euros", "12 euros"],
    textC: 1,
    img: ["6,50 €", "8,50 €", "12 €"],
    imgC: 1,
    fillQ: "Les menus sont à 8,___ euros.",
    fill: "50",
    fillA: ["50", "8,50", "8.50"],
  },
  {
    id: "saa34-q9",
    textQ: "Comment s'appelle le snack pour les petites faims ?",
    text: ["Mini Loop", "Maxi Snack", "Quick Bite"],
    textC: 0,
    img: ["Mini Loop", "Maxi Snack", "Quick Bite"],
    imgC: 0,
    fillQ: "Le snack s'appelle ___ Loop.",
    fill: "Mini",
    fillA: ["mini"],
  },
  {
    id: "saa34-q10",
    textQ: "Combien de spectacles extraordinaires sont proposés ?",
    text: ["Deux", "Trois", "Cinq"],
    textC: 1,
    img: ["2", "3", "5"],
    imgC: 1,
    fillQ: "Il y a trois ___ extraordinaires.",
    fill: "spectacles",
    fillA: ["spectacle", "spectacles"],
  },
  {
    id: "saa34-q11",
    textQ: "Jusqu'à quelle heure la cafétéria est-elle ouverte ?",
    text: ["20 h 45", "21 h 45", "22 h 45"],
    textC: 1,
    img: ["20 h 45", "21 h 45", "22 h 45"],
    imgC: 1,
    fillQ: "La cafétéria ferme à 21 h ___ .",
    fill: "45",
    fillA: ["45"],
  },
  {
    id: "saa34-q12",
    textQ: "Comment s'appelle le spectacle lumineux du soir ?",
    text: ["Show et lumière", "Nuit magique", "Lac enchanté"],
    textC: 0,
    img: ["Show et lumière", "Nuit magique", "Lac enchanté"],
    imgC: 0,
    fillQ: "Le spectacle s'appelle « Show et ___ ».",
    fill: "lumière",
    fillA: ["lumiere", "lumière"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_35 = buildPool("avance", "scolaire-annonce-35", [
  {
    id: "saa35-q1",
    textQ: "Quelle chanteuse est interviewée ?",
    text: ["Angèle", "Stromae", "Louane"],
    textC: 0,
    img: ["Angèle", "Stromae", "Louane"],
    imgC: 0,
    fillQ: "L'invitée s'appelle ___ .",
    fill: "Angèle",
    fillA: ["angele", "angèle"],
  },
  {
    id: "saa35-q2",
    textQ: "Dans combien de catégories Angèle est-elle nommée aux Victoires de la musique ?",
    text: ["Deux", "Trois", "Cinq"],
    textC: 1,
    img: ["2", "3", "5"],
    imgC: 1,
    fillQ: "Elle est nommée dans ___ catégories.",
    fill: "trois",
    fillA: ["3", "trois"],
  },
  {
    id: "saa35-q3",
    textQ: "Combien de grands concerts Angèle donne-t-elle en février ?",
    text: ["Deux", "Quatre", "Six"],
    textC: 1,
    img: ["2", "4", "6"],
    imgC: 1,
    fillQ: "Elle donne ___ grands concerts.",
    fill: "quatre",
    fillA: ["4", "quatre"],
  },
  {
    id: "saa35-q4",
    textQ: "Que va faire Angèle après sa tournée ?",
    text: ["Des festivals", "Une pause totale", "Un film"],
    textC: 0,
    img: ["Festivals", "Pause", "Film"],
    imgC: 0,
    fillQ: "Elle va faire des ___ .",
    fill: "festivals",
    fillA: ["festival", "festivals"],
  },
  {
    id: "saa35-q5",
    textQ: "Où Angèle va-t-elle passer plus de temps ?",
    text: ["À Bruxelles", "À Paris", "À Londres"],
    textC: 0,
    img: ["Bruxelles", "Paris", "Londres"],
    imgC: 0,
    fillQ: "Elle va passer plus de temps à ___ .",
    fill: "Bruxelles",
    fillA: ["bruxelles"],
  },
  {
    id: "saa35-q6",
    textQ: "Sur quel réseau Angèle a-t-elle commencé à se faire connaître ?",
    text: ["Instagram", "TikTok", "Facebook"],
    textC: 0,
    img: ["Instagram", "TikTok", "Facebook"],
    imgC: 0,
    fillQ: "Elle a commencé sur ___ .",
    fill: "Instagram",
    fillA: ["instagram"],
  },
  {
    id: "saa35-q7",
    textQ: "Il y a combien de temps qu'Angèle a commencé sur Instagram ?",
    text: ["Un an", "Trois ans", "Dix ans"],
    textC: 1,
    img: ["1 an", "3 ans", "10 ans"],
    imgC: 1,
    fillQ: "C'était il y a ___ ans.",
    fill: "trois",
    fillA: ["3", "trois"],
  },
  {
    id: "saa35-q8",
    textQ: "Devant combien de personnes Angèle va-t-elle chanter ?",
    text: ["2 000", "20 000", "200 000"],
    textC: 1,
    img: ["2 000", "20 000", "200 000"],
    imgC: 1,
    fillQ: "Elle chantera devant vingt ___ personnes.",
    fill: "mille",
    fillA: ["mille", "000", "20000"],
  },
  {
    id: "saa35-q9",
    textQ: "Quel métier exerce le frère d'Angèle ?",
    text: ["Rappeur", "Professeur", "Médecin"],
    textC: 0,
    img: ["Rappeur", "Professeur", "Médecin"],
    imgC: 0,
    fillQ: "Son frère est ___ .",
    fill: "rappeur",
    fillA: ["rappeur", "chanteur"],
  },
  {
    id: "saa35-q10",
    textQ: "En quelle année Angèle a-t-elle été en tête des ventes ?",
    text: ["2017", "2019", "2021"],
    textC: 1,
    img: ["2017", "2019", "2021"],
    imgC: 1,
    fillQ: "Elle a été en tête des ventes en ___ .",
    fill: "2019",
    fillA: ["2019"],
  },
  {
    id: "saa35-q11",
    textQ: "Quelles qualités le travail d'artiste exige-t-il selon Angèle ?",
    text: ["Sérieux et rigueur", "Chance seulement", "Paresse"],
    textC: 0,
    img: ["Sérieux", "Chance", "Paresse"],
    imgC: 0,
    fillQ: "Le travail demande énormément de sérieux et de ___ .",
    fill: "rigueur",
    fillA: ["rigueur"],
  },
  {
    id: "saa35-q12",
    textQ: "Quels sont les jours des concerts en février ?",
    text: ["Les 18, 19, 20 et 21", "Les 1, 2, 3 et 4", "Les 10, 11, 12 et 13"],
    textC: 0,
    img: ["18-21", "1-4", "10-13"],
    imgC: 0,
    fillQ: "Les concerts ont lieu les 18, 19, 20 et ___ février.",
    fill: "21",
    fillA: ["21", "vingt-et-un"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCE_36 = buildPool("avance", "scolaire-annonce-36", [
  {
    id: "saa36-q1",
    textQ: "De quoi parle cette annonce ?",
    text: ["Des légumes bio", "Des voitures", "Des vêtements"],
    textC: 0,
    img: ["Légumes bio", "Voitures", "Vêtements"],
    imgC: 0,
    fillQ: "L'annonce parle de légumes ___ .",
    fill: "bio",
    fillA: ["bio", "biologiques"],
  },
  {
    id: "saa36-q2",
    textQ: "Faut-il éplucher les légumes bio selon l'annonce ?",
    text: ["Non", "Oui, toujours", "Oui, sauf les carottes"],
    textC: 0,
    img: ["Non", "Oui", "Carottes"],
    imgC: 0,
    fillQ: "Les légumes bio se mangent sans les ___ .",
    fill: "éplucher",
    fillA: ["eplucher", "éplucher"],
  },
  {
    id: "saa36-q3",
    textQ: "Où se concentrent les vitamines ?",
    text: ["Sous la peau", "Dans les graines", "Dans l'eau de cuisson"],
    textC: 0,
    img: ["Sous la peau", "Graines", "Eau"],
    imgC: 0,
    fillQ: "Les vitamines sont sous la ___ .",
    fill: "peau",
    fillA: ["peau"],
  },
  {
    id: "saa36-q4",
    textQ: "De combien la qualité nutritionnelle du bio est-elle supérieure ?",
    text: ["10 %", "30 %", "50 %"],
    textC: 1,
    img: ["10 %", "30 %", "50 %"],
    imgC: 1,
    fillQ: "Le bio a une qualité nutritionnelle supérieure de ___ %.",
    fill: "30",
    fillA: ["30", "trente"],
  },
  {
    id: "saa36-q5",
    textQ: "Quel légume est cité en exemple ?",
    text: ["Les courgettes", "Les tomates", "Les carottes"],
    textC: 0,
    img: ["Courgettes", "Tomates", "Carottes"],
    imgC: 0,
    fillQ: "Six ___ biologiques coûtent 2,40 euros.",
    fill: "courgettes",
    fillA: ["courgette", "courgettes"],
  },
  {
    id: "saa36-q6",
    textQ: "Combien coûtent six courgettes bio chez l'annonceur ?",
    text: ["1,95 euro", "2,40 euros", "3,50 euros"],
    textC: 1,
    img: ["1,95 €", "2,40 €", "3,50 €"],
    imgC: 1,
    fillQ: "Six courgettes coûtent ___ euros.",
    fill: "2,40",
    fillA: ["2.40", "2,40", "2 euros 40"],
  },
  {
    id: "saa36-q7",
    textQ: "Combien coûtent six courgettes dans une grande surface ?",
    text: ["1,95 euro", "2,40 euros", "2,95 euros"],
    textC: 0,
    img: ["1,95 €", "2,40 €", "2,95 €"],
    imgC: 0,
    fillQ: "En grande surface, elles coûtent 1,___ euro.",
    fill: "95",
    fillA: ["95", "1,95", "1.95"],
  },
  {
    id: "saa36-q8",
    textQ: "Que favorise l'agriculture bio sans produits chimiques ?",
    text: ["La biodiversité", "La pollution", "Le bruit"],
    textC: 0,
    img: ["Biodiversité", "Pollution", "Bruit"],
    imgC: 0,
    fillQ: "Le bio favorise la ___ .",
    fill: "biodiversité",
    fillA: ["biodiversite", "biodiversité"],
  },
  {
    id: "saa36-q9",
    textQ: "À quoi compare-t-on les aliments bio ?",
    text: ["À l'agriculture conventionnelle", "À la restauration rapide", "Aux plats surgelés"],
    textC: 0,
    img: ["Conventionnelle", "Fast-food", "Surgelés"],
    imgC: 0,
    fillQ: "Le bio est comparé à l'agriculture ___ .",
    fill: "conventionnelle",
    fillA: ["conventionnelle"],
  },
  {
    id: "saa36-q10",
    textQ: "Que contiennent aussi les légumes sous la peau ?",
    text: ["Des minéraux", "Du sucre", "Du sel"],
    textC: 0,
    img: ["Minéraux", "Sucre", "Sel"],
    imgC: 0,
    fillQ: "Sous la peau se concentrent aussi les ___ .",
    fill: "minéraux",
    fillA: ["mineraux", "minéraux"],
  },
  {
    id: "saa36-q11",
    textQ: "Combien de courgettes sont mentionnées ?",
    text: ["Quatre", "Six", "Huit"],
    textC: 1,
    img: ["4", "6", "8"],
    imgC: 1,
    fillQ: "L'annonce cite ___ courgettes biologiques.",
    fill: "six",
    fillA: ["6", "six"],
  },
  {
    id: "saa36-q12",
    textQ: "Où acheter les légumes selon l'annonce ?",
    text: ["Chez l'annonceur (marché/producteur)", "À l'étranger", "En ligne seulement"],
    textC: 0,
    img: ["Chez nous", "Étranger", "En ligne"],
    imgC: 0,
    fillQ: "Les légumes sont à acheter chez ___ .",
    fill: "nous",
    fillA: ["nous", "moi"],
  },
]);

export const SCOLAIRE_AVANCE_ANNONCES_BOOK: Record<string, COMultiQuestion[]> = {
  "avance-scolaire-annonce-30": SCOLAIRE_AVANCE_ANNONCE_30,
  "avance-scolaire-annonce-31": SCOLAIRE_AVANCE_ANNONCE_31,
  "avance-scolaire-annonce-32": SCOLAIRE_AVANCE_ANNONCE_32,
  "avance-scolaire-annonce-33": SCOLAIRE_AVANCE_ANNONCE_33,
  "avance-scolaire-annonce-34": SCOLAIRE_AVANCE_ANNONCE_34,
  "avance-scolaire-annonce-35": SCOLAIRE_AVANCE_ANNONCE_35,
  "avance-scolaire-annonce-36": SCOLAIRE_AVANCE_ANNONCE_36,
};
