import { buildPool, type COMultiQuestion } from "./co-questions-helpers";

/** CO moyen scolaire — exercices radio 34, 35, 50 à 55. */

export const SCOLAIRE_MOYEN_RADIO_34 = buildPool("moyen", "scolaire-radio-34", [
  {
    id: "smr34-q1",
    textQ: "Quel sport pratique Julien ?",
    text: ["Le surf", "Le ski", "Le vélo"],
    textC: 0,
    img: ["Surf", "Ski", "Vélo"],
    imgC: 0,
    fillQ: "Julien fait de la compétition de ___.",
    fill: "surf",
    fillA: ["surf"],
  },
  {
    id: "smr34-q2",
    textQ: "Comment suit-il ses cours ?",
    text: ["Par correspondance", "À l'école le matin", "Le week-end seulement"],
    textC: 0,
    img: ["Correspondance", "École le matin", "Week-end"],
    imgC: 0,
    fillQ: "Il est en cours par ___.",
    fill: "correspondance",
    fillA: ["correspondance"],
  },
  {
    id: "smr34-q3",
    textQ: "Qu'est-ce qui est le plus difficile pour lui ?",
    text: ["L'entraînement physique intense", "Les études", "Les voyages"],
    textC: 0,
    img: ["Entraînement", "Études", "Voyage"],
    imgC: 0,
    fillQ: "L'entraînement physique est très ___.",
    fill: "intense",
    fillA: ["intense"],
  },
  {
    id: "smr34-q4",
    textQ: "Où a-t-il des compétitions le mois prochain ?",
    text: ["À l'étranger", "En France", "Dans sa région"],
    textC: 0,
    img: ["Océan", "France", "Région"],
    imgC: 0,
    fillQ: "Il a des compétitions le mois ___.",
    fill: "prochain",
    fillA: ["prochain", "prochaine"],
  },
  {
    id: "smr34-q5",
    textQ: "Dans quelle classe est-il ?",
    text: ["En seconde", "En première", "En terminale"],
    textC: 0,
    img: ["Seconde", "Première", "Terminale"],
    imgC: 0,
    fillQ: "Il est en ___.",
    fill: "seconde",
    fillA: ["seconde", "2nde"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_35 = buildPool("moyen", "scolaire-radio-35", [
  {
    id: "smr35-q1",
    textQ: "De quoi parle l'émission ?",
    text: ["De l'alimentation des adolescents", "Du sport à l'école", "Des vacances"],
    textC: 0,
    img: ["Alimentation", "Sport", "Vacances"],
    imgC: 0,
    fillQ: "L'émission parle de l'___ des adolescents.",
    fill: "alimentation",
    fillA: ["alimentation"],
  },
  {
    id: "smr35-q2",
    textQ: "Quel est le plat préféré de l'adolescent interviewé ?",
    text: ["La pizza", "Le hamburger-frites", "Les pâtes"],
    textC: 0,
    img: ["Pizza", "Hamburger", "Pâtes"],
    imgC: 0,
    fillQ: "Son plat préféré, c'est la ___.",
    fill: "pizza",
    fillA: ["pizza"],
  },
  {
    id: "smr35-q3",
    textQ: "Quels légumes mange-t-il régulièrement ?",
    text: ["De la salade", "Des carottes", "Des tomates"],
    textC: 0,
    img: ["Salade", "Carottes", "Tomates"],
    imgC: 0,
    fillQ: "Avec ses parents, on mange tous les jours de la ___.",
    fill: "salade",
    fillA: ["salade"],
  },
  {
    id: "smr35-q4",
    textQ: "Quels fruits n'aime-t-il pas ?",
    text: ["Les pommes et les poires", "Les fraises", "Les bananes"],
    textC: 0,
    img: ["Pommes et poires", "Fraises", "Bananes"],
    imgC: 0,
    fillQ: "Il n'aime pas les pommes ni les ___.",
    fill: "poires",
    fillA: ["poires", "poire"],
  },
  {
    id: "smr35-q5",
    textQ: "Que prend-il au petit-déjeuner ?",
    text: ["Du pain avec du chocolat et du lait", "Des céréales", "Un jus d'orange"],
    textC: 0,
    img: ["Pain et chocolat", "Céréales", "Jus d'orange"],
    imgC: 0,
    fillQ: "Au petit-déjeuner, il prend du pain avec du ___ et du lait.",
    fill: "chocolat",
    fillA: ["chocolat"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_50 = buildPool("moyen", "scolaire-radio-50", [
  {
    id: "smr50-q1",
    textQ: "Document 1 : quel temps fait-il aujourd'hui ?",
    text: ["Il pleut.", "Il fait froid.", "Il y a du soleil."],
    textC: 0,
    img: ["Pluie", "Froid", "Soleil"],
    imgC: 0,
    fillQ: "Il fait chaud mais il y a des nuages ___.",
    fill: "gris",
    fillA: ["gris", "grises"],
  },
  {
    id: "smr50-q2",
    textQ: "Document 1 : que faut-il pour demain ?",
    text: ["Un parapluie", "Un pull", "Des lunettes de soleil"],
    textC: 1,
    img: ["Parapluie", "Pull", "Lunettes"],
    imgC: 1,
    fillQ: "Demain, prévoyez les ___.",
    fill: "pulls",
    fillA: ["pulls", "pull"],
  },
  {
    id: "smr50-q3",
    textQ: "Document 2 : que devez-vous apporter pour le pique-nique ?",
    text: ["Des boissons", "De la vaisselle", "Des sandwichs"],
    textC: 1,
    img: ["Boisson", "Assiette", "Sandwich"],
    imgC: 1,
    fillQ: "Apportez vos assiettes et des couverts ___.",
    fill: "jetables",
    fillA: ["jetables", "jetable"],
  },
  {
    id: "smr50-q4",
    textQ: "Document 2 : où pouvez-vous manger ?",
    text: ["Sur l'herbe du parc", "Sur un banc", "Sur les tables de pique-nique"],
    textC: 2,
    img: ["Parc", "Banc", "Table"],
    imgC: 2,
    fillQ: "Le pique-nique est au parc des ___.",
    fill: "Fleurs",
    fillA: ["fleurs"],
  },
  {
    id: "smr50-q5",
    textQ: "Document 3 : quel est le métier de Saïa ?",
    text: ["Actrice", "Écrivaine", "Chanteuse"],
    textC: 2,
    img: ["Microphone", "Livre", "Guitare"],
    imgC: 0,
    fillQ: "Saïa sort un nouvel ___.",
    fill: "album",
    fillA: ["album"],
  },
  {
    id: "smr50-q6",
    textQ: "Document 3 : que faut-il faire pour gagner une invitation ?",
    text: ["Envoyer un message", "Remplir un document", "Répondre à des questions"],
    textC: 0,
    img: ["Téléphone", "Document", "Question"],
    imgC: 0,
    fillQ: "Il faut envoyer le mot SAÏA par ___.",
    fill: "SMS",
    fillA: ["sms", "SMS"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_51 = buildPool("moyen", "scolaire-radio-51", [
  {
    id: "smr51-q1",
    textQ: "Document 1 : le site BlaBlaLang est…",
    text: ["Gratuit", "Payant", "Très cher"],
    textC: 0,
    img: ["Maison", "Argent", "Avion"],
    imgC: 0,
    fillQ: "On peut loger un voyageur ___.",
    fill: "gratuitement",
    fillA: ["gratuitement", "gratis"],
  },
  {
    id: "smr51-q2",
    textQ: "Document 1 : où dort le voyageur ?",
    text: ["À l'hôtel", "Dans une auberge", "Chez des gens"],
    textC: 2,
    img: ["Hôtel", "Maison", "Tente"],
    imgC: 1,
    fillQ: "On peut parler avec lui dans sa ___.",
    fill: "langue",
    fillA: ["langue"],
  },
  {
    id: "smr51-q3",
    textQ: "Document 2 : à quel étage se trouve le restaurant ?",
    text: ["Au premier", "Au deuxième", "Au troisième"],
    textC: 1,
    img: ["1er étage", "2e étage", "3e étage"],
    imgC: 1,
    fillQ: "Le restaurant est au ___ étage de la Tour Eiffel.",
    fill: "deuxième",
    fillA: ["deuxieme", "deuxième", "2e", "2"],
  },
  {
    id: "smr51-q4",
    textQ: "Document 2 : le restaurant ferme à quelle heure le soir ?",
    text: ["À 21 h 00", "À 21 h 30", "À 22 h 30"],
    textC: 1,
    img: ["21 h", "21 h 30", "22 h 30"],
    imgC: 1,
    fillQ: "Le restaurant ouvre de midi à ___ h 30.",
    fill: "13h30",
    fillA: ["13 h 30", "13h30", "13:30"],
  },
  {
    id: "smr51-q5",
    textQ: "Document 3 : quelle est l'autre profession du chef Martin ?",
    text: ["Comédien", "Journaliste", "Chanteur"],
    textC: 0,
    img: ["Cinéma", "Journal", "Microphone"],
    imgC: 0,
    fillQ: "L'émission de cuisine est à ___ heures.",
    fill: "18h",
    fillA: ["18 h", "18h", "18h00"],
  },
  {
    id: "smr51-q6",
    textQ: "Document 3 : quelle recette allez-vous découvrir dans cet atelier ?",
    text: ["Une tarte aux fruits", "Un poulet rôti", "Un poisson grillé"],
    textC: 0,
    img: ["Tarte", "Poulet", "Poisson"],
    imgC: 0,
    fillQ: "Le chef donne des conseils pour cuisiner des plats ___.",
    fill: "sucrés",
    fillA: ["sucres", "sucrés"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_52 = buildPool("moyen", "scolaire-radio-52", [
  {
    id: "smr52-q1",
    textQ: "Le centre sportif se trouve…",
    text: ["À l'est", "À l'ouest", "Au centre"],
    textC: 1,
    img: ["Sport", "Piscine", "Stade"],
    imgC: 0,
    fillQ: "Un nouveau centre ___ va ouvrir.",
    fill: "sportif",
    fillA: ["sportif"],
  },
  {
    id: "smr52-q2",
    textQ: "Au centre sportif La Plaine, vous pourrez…",
    text: ["Faire du sport", "Voir des compétitions", "Participer à des événements"],
    textC: 0,
    img: ["Sport", "Football", "Course"],
    imgC: 0,
    fillQ: "On peut y pratiquer de nombreux ___.",
    fill: "sports",
    fillA: ["sports", "sport"],
  },
  {
    id: "smr52-q3",
    textQ: "Quel jour le centre sera-t-il fermé ?",
    text: ["Le lundi", "Le mardi", "Le dimanche"],
    textC: 0,
    img: ["Lundi", "Mardi", "Dimanche"],
    imgC: 0,
    fillQ: "Le centre est ouvert du mardi au ___.",
    fill: "dimanche",
    fillA: ["dimanche"],
  },
  {
    id: "smr52-q4",
    textQ: "Le matin, le centre ouvrira à…",
    text: ["8 h", "9 h", "10 h"],
    textC: 1,
    img: ["8 h", "9 h", "10 h"],
    imgC: 1,
    fillQ: "Le centre est ouvert de 9 heures à ___ heures.",
    fill: "21h",
    fillA: ["21 h", "21h", "21h00"],
  },
  {
    id: "smr52-q5",
    textQ: "Vous pouvez demander votre carte d'abonné le…",
    text: ["Mardi 6 mai", "Vendredi 9 mai", "Samedi 10 mai"],
    textC: 2,
    img: ["Carte", "Sport", "Calendrier"],
    imgC: 0,
    fillQ: "Venez le jour de l'___ pour l'abonnement réduit.",
    fill: "ouverture",
    fillA: ["ouverture"],
  },
  {
    id: "smr52-q6",
    textQ: "Quelles informations pourrez-vous avoir le jour de l'ouverture ?",
    text: ["Les horaires des cours", "Le calendrier des matchs", "Les tarifs"],
    textC: 2,
    img: ["Horaire", "Calendrier", "Tarif"],
    imgC: 2,
    fillQ: "Les clubs donnent des informations sur les ___ des cours.",
    fill: "horaires",
    fillA: ["horaires", "horaire"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_53 = buildPool("moyen", "scolaire-radio-53", [
  {
    id: "smr53-q1",
    textQ: "Document 1 : de quel musée parle-t-on ?",
    text: ["Le musée du jeu", "Le musée du sport", "Le musée des jeux de société"],
    textC: 0,
    img: ["Jeu", "Football", "Échecs"],
    imgC: 0,
    fillQ: "Le musée du ___ vidéo vous attend.",
    fill: "jeu",
    fillA: ["jeu"],
  },
  {
    id: "smr53-q2",
    textQ: "Document 1 : les activités proposées se terminent à…",
    text: ["18 h", "19 h", "20 h"],
    textC: 0,
    img: ["18 h", "19 h", "20 h"],
    imgC: 0,
    fillQ: "L'animation est de 10 heures à ___ heures.",
    fill: "18h",
    fillA: ["18 h", "18h", "18h00"],
  },
  {
    id: "smr53-q3",
    textQ: "Document 2 : l'intervenante va parler du sport…",
    text: ["À l'école", "Dans la rue", "À la maison"],
    textC: 2,
    img: ["École", "Rue", "Maison"],
    imgC: 2,
    fillQ: "On peut rester en forme en faisant du sport chez ___.",
    fill: "soi",
    fillA: ["soi"],
  },
  {
    id: "smr53-q4",
    textQ: "Document 2 : de quoi avez-vous besoin ?",
    text: ["Une bouteille d'eau", "Des haltères", "Une serviette"],
    textC: 0,
    img: ["Eau", "Haltère", "Serviette"],
    imgC: 0,
    fillQ: "Il faut un tapis de gym et de la ___.",
    fill: "musique",
    fillA: ["musique"],
  },
  {
    id: "smr53-q5",
    textQ: "Document 3 : le salon Inde Culture ferme plus tôt…",
    text: ["Vendredi", "Samedi", "Dimanche"],
    textC: 1,
    img: ["Vendredi", "Samedi", "Dimanche"],
    imgC: 1,
    fillQ: "L'entrée du salon est à ___ euros.",
    fill: "10",
    fillA: ["10", "dix"],
  },
  {
    id: "smr53-q6",
    textQ: "Document 3 : vous devez payer pour…",
    text: ["Manger", "Voir un film", "Entrer au salon"],
    textC: 2,
    img: ["Repas", "Cinéma", "Entrée"],
    imgC: 2,
    fillQ: "Ensuite, les films sont ___.",
    fill: "gratuits",
    fillA: ["gratuits", "gratuit"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_54 = buildPool("moyen", "scolaire-radio-54", [
  {
    id: "smr54-q1",
    textQ: "À quelle heure est le concert de David Guetta ?",
    text: ["À 19 h", "À 21 h", "À 23 h"],
    textC: 1,
    img: ["19 h", "21 h", "23 h"],
    imgC: 1,
    fillQ: "Le concert commence samedi à ___ heures.",
    fill: "21h",
    fillA: ["21 h", "21h", "21h00"],
  },
  {
    id: "smr54-q2",
    textQ: "Combien coûte l'entrée ?",
    text: ["35 euros", "55 euros", "75 euros"],
    textC: 1,
    img: ["35 euros", "55 euros", "75 euros"],
    imgC: 1,
    fillQ: "Le prix de l'entrée est de ___ euros.",
    fill: "55",
    fillA: ["55", "cinquante-cinq"],
  },
  {
    id: "smr54-q3",
    textQ: "Le concert de jazz est à…",
    text: ["Nice", "Paris", "Toulouse"],
    textC: 0,
    img: ["Plage", "Tour", "Stade"],
    imgC: 0,
    fillQ: "Le concert de jazz est ___.",
    fill: "gratuit",
    fillA: ["gratuit", "gratuite"],
  },
  {
    id: "smr54-q4",
    textQ: "Où a lieu le concert de jazz ?",
    text: ["Dans l'hôtel Negresco", "En face de l'hôtel Negresco", "Sur la terrasse de l'hôtel Negresco"],
    textC: 1,
    img: ["Hôtel", "Plage", "Promenade"],
    imgC: 1,
    fillQ: "Le concert de jazz est sur la ___.",
    fill: "plage",
    fillA: ["plage"],
  },
  {
    id: "smr54-q5",
    textQ: "Quel est le genre musical du concert à Toulouse ?",
    text: ["Du rock", "Du jazz", "De la musique classique"],
    textC: 0,
    img: ["Rock", "Jazz", "Piano"],
    imgC: 0,
    fillQ: "Le groupe Dionysos joue de la musique ___.",
    fill: "rock",
    fillA: ["rock"],
  },
  {
    id: "smr54-q6",
    textQ: "Où a lieu le concert de David Guetta ?",
    text: ["À Bercy", "À la Grande Halle", "Sur la promenade des Anglais"],
    textC: 0,
    img: ["Concert", "Salle", "Plage"],
    imgC: 0,
    fillQ: "L'événement le plus important est un grand ___.",
    fill: "concert",
    fillA: ["concert"],
  },
]);

export const SCOLAIRE_MOYEN_RADIO_55 = buildPool("moyen", "scolaire-radio-55", [
  {
    id: "smr55-q1",
    textQ: "Document 1 : combien de Français ont un tatouage ?",
    text: ["1 sur 5", "1 sur 10", "1 sur 20"],
    textC: 0,
    img: ["Tatouage", "Livre", "Photo"],
    imgC: 0,
    fillQ: "Le salon du ___ a lieu à Paris.",
    fill: "tatouage",
    fillA: ["tatouage"],
  },
  {
    id: "smr55-q2",
    textQ: "Document 1 : en général, les personnes qui aiment les tatouages sont…",
    text: ["Les adolescents", "Les jeunes adultes", "Les adultes plus âgés"],
    textC: 1,
    img: ["Adolescent", "Jeune", "Adulte"],
    imgC: 1,
    fillQ: "Un Français sur cinq est ___.",
    fill: "tatoué",
    fillA: ["tatoue", "tatoué"],
  },
  {
    id: "smr55-q3",
    textQ: "Document 2 : où est-ce que l'application TikTok est utilisée ?",
    text: ["En France", "En Europe", "Dans le monde"],
    textC: 2,
    img: ["France", "Europe", "Monde"],
    imgC: 2,
    fillQ: "Les jeunes peuvent partager des clips ___.",
    fill: "vidéo",
    fillA: ["video", "vidéo"],
  },
  {
    id: "smr55-q4",
    textQ: "Document 2 : quelle activité est possible avec TikTok ?",
    text: ["Créer des vidéos", "Regarder des films", "Créer des chansons"],
    textC: 0,
    img: ["Vidéo", "Cinéma", "Musique"],
    imgC: 0,
    fillQ: "TikTok est utilisé par des ___ de 13 à 24 ans.",
    fill: "adolescents",
    fillA: ["adolescents", "adolescent"],
  },
  {
    id: "smr55-q5",
    textQ: "Document 3 : la fête de la ville a lieu…",
    text: ["Tous les mois", "Deux fois par an", "Tous les ans"],
    textC: 2,
    img: ["Mois", "Année", "Semaine"],
    imgC: 2,
    fillQ: "On peut écouter des ___ dans les rues.",
    fill: "concerts",
    fillA: ["concerts", "concert"],
  },
  {
    id: "smr55-q6",
    textQ: "Document 3 : où peut-on écouter de la musique ?",
    text: ["Dans une salle de concert", "Dans un stade", "Dans les rues"],
    textC: 2,
    img: ["Concert", "Stade", "Rue"],
    imgC: 2,
    fillQ: "Une ___ est installée sur la place centrale.",
    fill: "discothèque",
    fillA: ["discotheque", "discothèque"],
  },
]);

export const SCOLAIRE_MOYEN_RADIOS_BOOK: Record<string, COMultiQuestion[]> = {
  "moyen-scolaire-radio-34": SCOLAIRE_MOYEN_RADIO_34,
  "moyen-scolaire-radio-35": SCOLAIRE_MOYEN_RADIO_35,
  "moyen-scolaire-radio-50": SCOLAIRE_MOYEN_RADIO_50,
  "moyen-scolaire-radio-51": SCOLAIRE_MOYEN_RADIO_51,
  "moyen-scolaire-radio-52": SCOLAIRE_MOYEN_RADIO_52,
  "moyen-scolaire-radio-53": SCOLAIRE_MOYEN_RADIO_53,
  "moyen-scolaire-radio-54": SCOLAIRE_MOYEN_RADIO_54,
  "moyen-scolaire-radio-55": SCOLAIRE_MOYEN_RADIO_55,
};
