import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_127 = `- C'est à qui ? Madame ?
- Non, c'est à moi… Bonjour, deux croissants s'il vous plaît !
- Et avec ceci ?
- Une baguette… Je voudrais aussi une tarte au citron.
- Une tarte pour combien ?
- Pour six.
- Ce sera tout ?
- Vous faites des crêpes ?
- Non, désolée.
- Alors c'est tout.
- 17,30 € s'il vous plaît. Par carte ?
- Oui, sans contact. Au revoir !
- Merci monsieur. Bonne journée !`;

const POOL_127 = buildExpressPool("e4-3-127", [
  q({
    id: "127-q1",
    textQ: "Où se passe la scène ?",
    text: ["À la boulangerie", "Au restaurant", "À la pharmacie"],
    textC: 0,
    img: ["boulangerie", "restaurant", "pharmacie"],
    imgC: 0,
    fillQ: "Le client achète des croissants et une baguette à la _________.",
    fill: "boulangerie",
    vfQ: "La scène se passe dans une boulangerie.",
    vfC: 0,
  }),
  q({
    id: "127-q2",
    textQ: "Combien de croissants le client achète-t-il ?",
    text: ["Deux", "Quatre", "Six"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Bonjour, _________ croissants s'il vous plaît !",
    fill: "deux",
    fillA: ["2"],
    vfQ: "Le client achète quatre croissants.",
    vfC: 1,
  }),
  q({
    id: "127-q3",
    textQ: "Quelle tarte le client choisit-il ?",
    text: ["Une tarte au citron", "Une tarte aux fraises", "Une tarte aux pommes"],
    textC: 0,
    img: ["citron", "fraise", "pomme"],
    imgC: 0,
    fillQ: "Je voudrais aussi une tarte au _________.",
    fill: "citron",
    vfQ: "Le client choisit une tarte aux pommes.",
    vfC: 1,
  }),
  q({
    id: "127-q4",
    textQ: "Pour combien de personnes est la tarte ?",
    text: ["Pour six", "Pour quatre", "Pour huit"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Une tarte pour combien ? — Pour _________.",
    fill: "six",
    fillA: ["6"],
    vfQ: "La tarte est pour six personnes.",
    vfC: 0,
  }),
  q({
    id: "127-q5",
    textQ: "Est-ce que la boulangerie fait des crêpes ?",
    text: ["Non", "Oui, tous les jours", "Oui, le week-end"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous faites des _________ ? — Non, désolée.",
    fill: "crêpes",
    fillA: ["crepes"],
    vfQ: "La boulangerie vend des crêpes.",
    vfC: 1,
  }),
  q({
    id: "127-q6",
    textQ: "Combien paie le client ?",
    text: ["17,30 €", "13,70 €", "17,90 €"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ euros trente, s'il vous plaît.",
    fill: "dix-sept",
    fillA: ["17"],
    vfQ: "Le client paie 17,30 €.",
    vfC: 0,
  }),
  q({
    id: "127-q7",
    textQ: "Comment le client paie-t-il ?",
    text: ["Par carte", "En espèces", "Par chèque"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Par _________ ? — Oui, sans contact.",
    fill: "carte",
    vfQ: "Le client paie en espèces.",
    vfC: 1,
  }),
  q({
    id: "127-q8",
    textQ: "Qu'est-ce que le client achète avec les croissants ?",
    text: ["Une baguette", "Un pain au chocolat", "Un macaron"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Et avec ceci ? — Une _________.",
    fill: "baguette",
    vfQ: "Le client commande aussi un café.",
    vfC: 2,
  }),
]);

const TR_133 = `Vous adorez les croissants du Macaron doré ? Venez découvrir maintenant leurs tartes aux fruits, leurs gâteaux, leurs crêpes bretonnes, leurs macarons et leurs éclairs au café. Venez nombreux !`;

const POOL_133 = buildExpressPool("e4-3-133", [
  q({
    id: "133-q1",
    textQ: "Qu'est-ce que les clients adorent déjà ?",
    text: ["Les croissants", "Les macarons", "Les gâteaux"],
    textC: 0,
    img: ["croissant", "macaron", "gâteau"],
    imgC: 0,
    fillQ: "Vous adorez les _________ du Macaron doré ?",
    fill: "croissants",
    vfQ: "Les clients adorent déjà les croissants du Macaron doré.",
    vfC: 0,
  }),
  q({
    id: "133-q2",
    textQ: "Qu'est-ce qu'on peut découvrir maintenant ?",
    text: ["Des tartes aux fruits et des gâteaux", "Des pizzas et des sandwichs", "Des glaces et des bonbons"],
    textC: 0,
    img: ["tarte", "pizza", "glace"],
    imgC: 0,
    fillQ: "Venez découvrir maintenant leurs tartes aux _________.",
    fill: "fruits",
    vfQ: "On peut maintenant découvrir des tartes aux fruits.",
    vfC: 0,
  }),
  q({
    id: "133-q3",
    textQ: "Quelles crêpes sont proposées ?",
    text: ["Des crêpes bretonnes", "Des crêpes au chocolat", "Des crêpes au sucre"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Leurs crêpes _________ et leurs macarons.",
    fill: "bretonnes",
    vfQ: "La pâtisserie propose des crêpes bretonnes.",
    vfC: 0,
  }),
  q({
    id: "133-q4",
    textQ: "À quoi sont les éclairs ?",
    text: ["Au café", "Au chocolat", "À la vanille"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Leurs macarons et leurs éclairs au _________.",
    fill: "café",
    fillA: ["cafe"],
    vfQ: "Les éclairs sont au chocolat.",
    vfC: 1,
  }),
  q({
    id: "133-q5",
    textQ: "Quel type de message est-ce ?",
    text: ["Une publicité", "Un message personnel", "Une recette"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Venez _________ !",
    fill: "nombreux",
    vfQ: "C'est un message pour un ami.",
    vfC: 1,
  }),
  q({
    id: "133-q6",
    textQ: "Est-ce que les prix sont annoncés ?",
    text: ["Non", "Oui, pour les tartes", "Oui, pour tout"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Venez _________ maintenant leurs tartes aux fruits.",
    fill: "découvrir",
    fillA: ["decouvrir"],
    vfQ: "Les croissants du Macaron doré coûtent deux euros.",
    vfC: 2,
  }),
]);

const TR_134 = `- Chérie, j'achète quoi ?
- Deux baguettes, deux croissants…
- Des pains au chocolat ?
- Oui, un pain au chocolat, mais pas de pain aux raisins.
- D'accord !`;

const POOL_134 = buildExpressPool("e4-3-134", [
  q({
    id: "134-q1",
    textQ: "Que demande l'homme à sa femme ?",
    text: ["Ce qu'il doit acheter", "L'heure du dîner", "Où est la boulangerie"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Chérie, j'_________ quoi ?",
    fill: "achète",
    fillA: ["achete"],
    vfQ: "L'homme demande ce qu'il doit acheter.",
    vfC: 0,
  }),
  q({
    id: "134-q2",
    textQ: "Combien de baguettes faut-il acheter ?",
    text: ["Deux", "Une", "Trois"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ baguettes, deux croissants…",
    fill: "deux",
    fillA: ["2"],
    vfQ: "Il faut acheter trois baguettes.",
    vfC: 1,
  }),
  q({
    id: "134-q3",
    textQ: "Qu'est-ce qu'il faut acheter avec les baguettes ?",
    text: ["Des croissants", "Des macarons", "Des tartes"],
    textC: 0,
    img: ["croissant", "macaron", "gâteau"],
    imgC: 0,
    fillQ: "Deux baguettes, deux _________…",
    fill: "croissants",
    vfQ: "Il faut aussi acheter deux croissants.",
    vfC: 0,
  }),
  q({
    id: "134-q4",
    textQ: "Combien de pains au chocolat la femme veut-elle ?",
    text: ["Un seul", "Deux", "Aucun"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Oui, un pain au _________.",
    fill: "chocolat",
    vfQ: "La femme veut deux pains au chocolat.",
    vfC: 1,
  }),
  q({
    id: "134-q5",
    textQ: "Qu'est-ce que la femme ne veut pas ?",
    text: ["De pain aux raisins", "De pain au chocolat", "De croissants"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Mais pas de pain aux _________.",
    fill: "raisins",
    vfQ: "La femme ne veut pas de pain aux raisins.",
    vfC: 0,
  }),
]);

const TR_135 = `Salut Léa ! C'est maman. Tu connais la pâtisserie Le Macaron doré ? Ils font de super gâteaux maintenant. Pour ton anniversaire, je peux acheter le gâteau chez eux. Rappelle-moi. Bisous.`;

const POOL_135 = buildExpressPool("e4-3-135", [
  q({
    id: "135-q1",
    textQ: "De qui est ce message ?",
    text: ["De la mère de Léa", "De la sœur de Léa", "D'une amie de Léa"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Salut Léa ! C'est _________.",
    fill: "maman",
    vfQ: "C'est la maman de Léa qui laisse le message.",
    vfC: 0,
  }),
  q({
    id: "135-q2",
    textQ: "De quel commerce parle la maman ?",
    text: ["D'une pâtisserie", "D'une pizzeria", "D'une pharmacie"],
    textC: 0,
    img: ["gâteau", "pizzeria", "pharmacien"],
    imgC: 0,
    fillQ: "Tu connais la _________ Le Macaron doré ?",
    fill: "pâtisserie",
    fillA: ["patisserie"],
    vfQ: "La maman parle d'une pharmacie.",
    vfC: 1,
  }),
  q({
    id: "135-q3",
    textQ: "Comment sont les gâteaux de cette pâtisserie ?",
    text: ["Super", "Ordinaires", "Trop chers"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Ils font de super _________ maintenant.",
    fill: "gâteaux",
    fillA: ["gateaux"],
    vfQ: "La pâtisserie fait de super gâteaux.",
    vfC: 0,
  }),
  q({
    id: "135-q4",
    textQ: "Pour quelle occasion la maman veut-elle acheter un gâteau ?",
    text: ["Pour un anniversaire", "Pour un mariage", "Pour Noël"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Pour ton _________, je peux acheter le gâteau chez eux.",
    fill: "anniversaire",
    vfQ: "Le gâteau est pour un mariage.",
    vfC: 1,
  }),
  q({
    id: "135-q5",
    textQ: "Que doit faire Léa ?",
    text: ["Rappeler sa mère", "Aller à la pâtisserie", "Acheter le gâteau"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________-moi. Bisous.",
    fill: "rappelle",
    vfQ: "La maman demande à Léa de la rappeler.",
    vfC: 0,
  }),
  q({
    id: "135-q6",
    textQ: "Quand a lieu l'anniversaire de Léa ?",
    text: ["Ce n'est pas dit", "Demain", "Le mois prochain"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je peux acheter le _________ chez eux.",
    fill: "gâteau",
    fillA: ["gateau"],
    vfQ: "L'anniversaire de Léa est demain.",
    vfC: 2,
  }),
]);

const TR_136 = `- Aujourd'hui, écoutons la recette du sandwich « Le Bocase ».
- C'est très simple. Dans une demi-baguette, mettez beaucoup de beurre, un œuf dur, 150 g de fromage, trois tranches de tomates avec un peu de sel et un morceau de poulet.`;

const POOL_136 = buildExpressPool("e4-3-136", [
  q({
    id: "136-q1",
    textQ: "De quoi parle cet enregistrement ?",
    text: ["D'une recette de sandwich", "D'un menu de restaurant", "D'une liste de courses"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Écoutons la recette du _________ « Le Bocase ».",
    fill: "sandwich",
    vfQ: "C'est la recette d'un sandwich.",
    vfC: 0,
  }),
  q({
    id: "136-q2",
    textQ: "Dans quoi met-on les ingrédients ?",
    text: ["Dans une demi-baguette", "Dans un pain de mie", "Dans un croissant"],
    textC: 0,
    img: ["baguette", "pain", "croissant"],
    imgC: 0,
    fillQ: "Dans une demi-_________, mettez beaucoup de beurre.",
    fill: "baguette",
    vfQ: "La recette se prépare dans un croissant.",
    vfC: 1,
  }),
  q({
    id: "136-q3",
    textQ: "Quelle quantité de fromage faut-il ?",
    text: ["150 g", "50 g", "250 g"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Il faut _________ g de fromage.",
    fill: "150",
    fillA: ["cent cinquante"],
    vfQ: "Il faut 250 g de fromage.",
    vfC: 1,
  }),
  q({
    id: "136-q4",
    textQ: "Combien de tranches de tomates faut-il ?",
    text: ["Trois", "Deux", "Cinq"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ tranches de tomates avec un peu de sel.",
    fill: "trois",
    fillA: ["3"],
    vfQ: "Il faut trois tranches de tomates.",
    vfC: 0,
  }),
  q({
    id: "136-q5",
    textQ: "Quelle viande met-on dans le sandwich ?",
    text: ["Du poulet", "Du bœuf", "Du jambon"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Et un morceau de _________.",
    fill: "poulet",
    vfQ: "Le sandwich « Le Bocase » se mange chaud.",
    vfC: 2,
  }),
  q({
    id: "136-q6",
    textQ: "Qu'est-ce qu'on met en grande quantité ?",
    text: ["Du beurre", "Du fromage", "De la tomate"],
    textC: 0,
    img: ["beurre", "fromage", "tomate"],
    imgC: 0,
    fillQ: "Mettez beaucoup de _________.",
    fill: "beurre",
    vfQ: "On met beaucoup de beurre dans le sandwich.",
    vfC: 0,
  }),
  q({
    id: "136-q7",
    textQ: "Quel œuf faut-il pour la recette ?",
    text: ["Un œuf dur", "Un œuf au plat", "Un œuf à la coque"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Il faut aussi un _________ dur.",
    fill: "œuf",
    fillA: ["oeuf"],
    vfQ: "Il faut deux œufs durs.",
    vfC: 1,
  }),
  q({
    id: "136-q8",
    textQ: "Est-ce que la recette est difficile ?",
    text: ["Non, elle est très simple", "Oui, très difficile", "Oui, assez difficile"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "C'est très _________.",
    fill: "simple",
    vfQ: "La recette du sandwich est très simple.",
    vfC: 0,
  }),
]);

const TR_137 = `- C'est à qui ? Monsieur ?
- Non, c'est à moi.
- Bonjour madame, vous désirez ?
- Bonjour, vous avez des sandwichs ?
- Oui, bien sûr, au saumon, au poulet, végétarien. On a aussi des formules déjeuner.
- Ah, qu'est-ce qu'il y a dans une formule ?
- Un sandwich, une boisson et une part de tarte ou un éclair
- Parfait, une formule s'il vous plaît ! Avec un sandwich végétarien et une part de tarte aux pommes.
- Et comme boisson ?
- Un jus d'orange s'il vous plaît.
- Voilà… Et avec ceci ?
- Ce sera tout, merci.`;

const POOL_137 = buildExpressPool("e4-3-137", [
  q({
    id: "137-q1",
    textQ: "Qu'est-ce que la cliente demande d'abord ?",
    text: ["S'il y a des sandwichs", "S'il y a des salades", "S'il y a des pizzas"],
    textC: 0,
    img: ["sandwich", "salade", "pizza"],
    imgC: 0,
    fillQ: "Bonjour, vous avez des _________ ?",
    fill: "sandwichs",
    fillA: ["sandwich", "sandwiches"],
    vfQ: "La cliente demande s'il y a des sandwichs.",
    vfC: 0,
  }),
  q({
    id: "137-q2",
    textQ: "Quelles sortes de sandwichs y a-t-il ?",
    text: ["Au saumon, au poulet et végétarien", "Au jambon, au fromage et au thon", "Au bœuf, au porc et à la dinde"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Au saumon, au _________, végétarien.",
    fill: "poulet",
    vfQ: "Il y a des sandwichs au saumon.",
    vfC: 0,
  }),
  q({
    id: "137-q3",
    textQ: "Qu'est-ce qu'il y a dans une formule ?",
    text: ["Un sandwich, une boisson et un dessert", "Un sandwich et un café seulement", "Une salade et une boisson"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Un sandwich, une _________ et une part de tarte ou un éclair.",
    fill: "boisson",
    vfQ: "La formule contient un sandwich, une boisson et un dessert.",
    vfC: 0,
  }),
  q({
    id: "137-q4",
    textQ: "Quel sandwich la cliente choisit-elle ?",
    text: ["Le sandwich végétarien", "Le sandwich au saumon", "Le sandwich au poulet"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Avec un sandwich _________.",
    fill: "végétarien",
    fillA: ["vegetarien"],
    vfQ: "La cliente choisit le sandwich au saumon.",
    vfC: 1,
  }),
  q({
    id: "137-q5",
    textQ: "Quel dessert la cliente prend-elle ?",
    text: ["Une part de tarte aux pommes", "Un éclair au café", "Un macaron"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Et une part de tarte aux _________.",
    fill: "pommes",
    vfQ: "La cliente prend un éclair au café.",
    vfC: 1,
  }),
  q({
    id: "137-q6",
    textQ: "Que boit la cliente ?",
    text: ["Un jus d'orange", "Un café", "Une eau gazeuse"],
    textC: 0,
    img: ["jus d'orange", "café", "eau"],
    imgC: 0,
    fillQ: "Un _________ d'orange s'il vous plaît.",
    fill: "jus",
    vfQ: "La cliente boit un jus d'orange.",
    vfC: 0,
  }),
  q({
    id: "137-q7",
    textQ: "Combien coûte la formule ?",
    text: ["Ce n'est pas dit", "Dix euros", "Huit euros"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Ce sera _________, merci.",
    fill: "tout",
    vfQ: "La formule coûte dix euros.",
    vfC: 2,
  }),
]);

export const E4_3_TRAINING: ExpressListeningAudio[] = [
{
  id: "e4-3-127",
  audioSrc: A1(127),
  audioLabel: "Audio 127",
  transcript: TR_127,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_127,
  questionCount: 3,
},
{
  id: "e4-3-133",
  audioSrc: A1(133),
  audioLabel: "Audio 133",
  transcript: TR_133,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_133,
  questionCount: 3,
},
{
  id: "e4-3-134",
  audioSrc: A1(134),
  audioLabel: "Audio 134",
  transcript: TR_134,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_134,
  questionCount: 3,
},
{
  id: "e4-3-135",
  audioSrc: A1(135),
  audioLabel: "Audio 135",
  transcript: TR_135,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_135,
  questionCount: 3,
}
];

export const E4_3_EVAL: ExpressListeningAudio[] = [
{
  id: "e4-3-136",
  audioSrc: A1(136),
  audioLabel: "Audio 136",
  transcript: TR_136,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_136,
  questionCount: 3,
},
{
  id: "e4-3-137",
  audioSrc: A1(137),
  audioLabel: "Audio 137",
  transcript: TR_137,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_137,
  questionCount: 3,
}
];
