import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_038 = `- Regarde mamie, j'ai des photos de mon nouvel appartement à Annecy !
- C'est un studio ?
- Non, un appartement…
- Montre-moi… Oh ! C'est grand et très lumineux !
- Oui, il y a un salon, une chambre et une cuisine équipée. Et puis je n'aime pas les appartements sombres.
- Il y a un balcon ?
- Oui, on peut manger sur le balcon !
- La salle de bains est grande ?
- Non, elle est petite, mais les toilettes sont très grandes.
- C'est à quel étage ?
- Au 3e.
- L'immeuble est ancien ?
- Non, il est neuf !
- Et c'est où ?
- C'est dans un quartier calme, au centre-ville.`;

const POOL_038 = buildExpressPool("e2-1-038", [
  q({
    id: "038-q1",
    textQ: "De quel logement la personne montre-t-elle des photos ?",
    text: ["D'un appartement", "D'un studio", "D'une maison"],
    textC: 0,
    imgQ: "Que montre la personne à sa mamie ?",
    img: ["photo", "télévision", "livre"],
    imgC: 0,
    fillQ: "Ce n'est pas un studio, c'est un _________.",
    fill: "appartement",
    vfQ: "La personne montre des photos de son nouvel appartement.",
    vfC: 0,
  }),
  q({
    id: "038-q2",
    textQ: "Comment est l'appartement ?",
    text: ["Grand et lumineux", "Petit et sombre", "Vieux et bruyant"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Oh ! C'est grand et très _________ !",
    fill: "lumineux",
    vfQ: "L'appartement est sombre.",
    vfC: 1,
  }),
  q({
    id: "038-q3",
    textQ: "Où peut-on manger dans l'appartement ?",
    text: ["Sur le balcon", "Dans la cuisine", "Dans le salon"],
    textC: 0,
    img: ["balcon", "cuisine", "salon"],
    imgC: 0,
    fillQ: "On peut manger sur le _________ !",
    fill: "balcon",
    vfQ: "On peut manger sur le balcon.",
    vfC: 0,
  }),
  q({
    id: "038-q4",
    textQ: "Comment est la salle de bains ?",
    text: ["Petite", "Grande", "Moyenne"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Elle est petite, mais les toilettes sont très _________.",
    fill: "grandes",
    vfQ: "Les toilettes sont très petites.",
    vfC: 1,
  }),
  q({
    id: "038-q5",
    textQ: "À quel étage est l'appartement ?",
    text: ["Au 3e", "Au 1er", "Au 5e"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "L'appartement est au _________ étage.",
    fill: "3e",
    fillA: ["3", "troisième", "troisieme"],
    vfQ: "L'appartement est au rez-de-chaussée.",
    vfC: 1,
  }),
  q({
    id: "038-q6",
    textQ: "Où se trouve l'appartement ?",
    text: ["Dans un quartier calme du centre-ville", "Dans un quartier bruyant", "À la campagne"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "C'est dans un quartier _________, au centre-ville.",
    fill: "calme",
    vfQ: "Le loyer de l'appartement est mentionné dans la conversation.",
    vfC: 2,
  }),
  q({
    id: "038-q7",
    textQ: "Est-ce que l'immeuble est ancien ?",
    text: ["Non, il est neuf", "Oui, très ancien", "On ne sait pas"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "L'immeuble n'est pas ancien, il est _________ !",
    fill: "neuf",
    vfQ: "L'immeuble est neuf.",
    vfC: 0,
  }),
]);

const TR_044 = `Vous voulez habiter dans un quartier calme ? Venez visiter les pièces lumineuses des studios avec terrasse et des appartements de 4 pièces de notre immeuble avec jardin. Nous sommes ouverts…`;

const POOL_044 = buildExpressPool("e2-1-044", [
  q({
    id: "044-q1",
    textQ: "Qu'est-ce que la publicité propose de visiter ?",
    text: ["Des studios et des appartements", "Des maisons et des châteaux", "Des bureaux et des magasins"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Venez visiter les studios et les _________.",
    fill: "appartements",
    vfQ: "La publicité propose des studios et des appartements.",
    vfC: 0,
  }),
  q({
    id: "044-q2",
    textQ: "Comment est le quartier ?",
    text: ["Calme", "Bruyant", "Animé"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous voulez habiter dans un quartier _________ ?",
    fill: "calme",
    vfQ: "Le quartier est très bruyant.",
    vfC: 1,
  }),
  q({
    id: "044-q3",
    textQ: "Quel logement a une terrasse ?",
    text: ["Un studio", "Une maison", "Un hôtel"],
    textC: 0,
    img: ["studio", "maison", "hôtel"],
    imgC: 0,
    fillQ: "Venez visiter les studios avec _________.",
    fill: "terrasse",
    vfQ: "Les studios ont une terrasse.",
    vfC: 0,
  }),
  q({
    id: "044-q4",
    textQ: "Combien de pièces ont les appartements ?",
    text: ["Quatre", "Deux", "Six"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Des appartements de _________ pièces.",
    fill: "quatre",
    fillA: ["4"],
    vfQ: "Les appartements ont deux pièces.",
    vfC: 1,
  }),
  q({
    id: "044-q5",
    textQ: "Comment sont les pièces ?",
    text: ["Lumineuses", "Sombres", "Très petites"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Venez visiter les pièces _________.",
    fill: "lumineuses",
    vfQ: "Les pièces sont sombres.",
    vfC: 1,
  }),
  q({
    id: "044-q6",
    textQ: "Qu'est-ce qu'il y a avec l'immeuble ?",
    text: ["Un jardin", "Une piscine", "Un parking"],
    textC: 0,
    img: ["parc", "piscine", "voiture"],
    imgC: 0,
    fillQ: "Notre immeuble avec _________.",
    fill: "jardin",
    vfQ: "Le prix des logements est donné dans la publicité.",
    vfC: 2,
  }),
]);

const TR_045 = `Nous sommes aujourd'hui dans la maison de Victor Hugo au 6 place des Vosges à Paris et nous allons visiter ensemble le salon rouge, le petit salon et la chambre.`;

const POOL_045 = buildExpressPool("e2-1-045", [
  q({
    id: "045-q1",
    textQ: "Que visite-t-on aujourd'hui ?",
    text: ["La maison d'un écrivain", "Un château", "Une école"],
    textC: 0,
    imgQ: "Quel lieu visite-t-on aujourd'hui ?",
    img: ["maison", "château", "usine"],
    imgC: 0,
    fillQ: "Nous sommes dans la _________ de Victor Hugo.",
    fill: "maison",
    vfQ: "On visite la maison de Victor Hugo.",
    vfC: 0,
  }),
  q({
    id: "045-q2",
    textQ: "Quelles pièces va-t-on visiter ?",
    text: ["Les salons et la chambre", "La cuisine et la salle de bains", "Le garage et la cave"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous allons visiter le salon rouge, le petit salon et la _________.",
    fill: "chambre",
    vfQ: "On va visiter la cuisine.",
    vfC: 1,
  }),
  q({
    id: "045-q3",
    textQ: "De quelle couleur est le grand salon ?",
    text: ["Rouge", "Bleu", "Vert"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "On visite le salon _________ et le petit salon.",
    fill: "rouge",
    vfQ: "Le grand salon est bleu.",
    vfC: 1,
  }),
  q({
    id: "045-q4",
    textQ: "Comment va-t-on visiter la maison ?",
    text: ["Ensemble", "Seul", "En courant"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous allons visiter _________ le salon rouge.",
    fill: "ensemble",
    vfQ: "On visite la maison ensemble.",
    vfC: 0,
  }),
  q({
    id: "045-q5",
    textQ: "Quand a lieu la visite ?",
    text: ["Aujourd'hui", "Demain", "Dimanche prochain"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous sommes _________ dans la maison de Victor Hugo.",
    fill: "aujourd'hui",
    fillA: ["aujourdhui", "aujourd hui"],
    vfQ: "La durée de la visite est mentionnée dans l'annonce.",
    vfC: 2,
  }),
]);

const TR_046 = `- Tu habites au 3e ?
- Non, au rez-de-chaussée, dans un studio.
- Il est bien ?
- Non, la pièce est petite, sombre et la cuisine n'est pas équipée.`;

const POOL_046 = buildExpressPool("e2-1-046", [
  q({
    id: "046-q1",
    textQ: "Dans quel logement habite la personne ?",
    text: ["Dans un studio", "Dans une maison", "Dans un château"],
    textC: 0,
    img: ["studio", "maison", "château"],
    imgC: 0,
    fillQ: "J'habite dans un _________.",
    fill: "studio",
    vfQ: "La personne habite dans un studio.",
    vfC: 0,
  }),
  q({
    id: "046-q2",
    textQ: "À quel étage habite la personne ?",
    text: ["Au rez-de-chaussée", "Au 3e étage", "Au 5e étage"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Non, j'habite au _________.",
    fill: "rez-de-chaussée",
    fillA: ["rez de chaussée", "rez-de-chaussee", "rez de chaussee"],
    vfQ: "La personne habite au 3e étage.",
    vfC: 1,
  }),
  q({
    id: "046-q3",
    textQ: "Comment est la pièce du studio ?",
    text: ["Petite et sombre", "Grande et lumineuse", "Neuve et moderne"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "La pièce est petite et _________.",
    fill: "sombre",
    vfQ: "La pièce du studio est sombre.",
    vfC: 0,
  }),
  q({
    id: "046-q4",
    textQ: "Est-ce que la cuisine est équipée ?",
    text: ["Non", "Oui", "Il n'y a pas de cuisine"],
    textC: 0,
    imgQ: "Quelle pièce du studio n'est pas équipée ?",
    img: ["four", "baignoire", "fauteuil"],
    imgC: 0,
    fillQ: "La cuisine n'est pas _________.",
    fill: "équipée",
    fillA: ["equipee", "équipee", "equipée"],
    vfQ: "La cuisine du studio est équipée.",
    vfC: 1,
  }),
  q({
    id: "046-q5",
    textQ: "Que pense la personne de son studio ?",
    text: ["Il n'est pas bien", "Il est très bien", "Il est parfait"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Il est bien ? — _________, la pièce est petite.",
    fill: "non",
    vfQ: "Le prix du studio est mentionné dans le dialogue.",
    vfC: 2,
  }),
]);

const TR_047 = `Bonjour Marion, c'est Alice ! J'habite maintenant dans un immeuble neuf au 4e étage, à Toulon. Voici mon adresse : 10, place de la Liberté, 83000 Toulon. À bientôt !`;

const POOL_047 = buildExpressPool("e2-1-047", [
  q({
    id: "047-q1",
    textQ: "Pourquoi Alice appelle-t-elle Marion ?",
    text: ["Elle a un nouveau logement", "Elle vend sa maison", "Elle cherche un studio"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "J'habite _________ dans un immeuble neuf.",
    fill: "maintenant",
    vfQ: "Alice a un nouveau logement.",
    vfC: 0,
  }),
  q({
    id: "047-q2",
    textQ: "Comment est l'immeuble d'Alice ?",
    text: ["Neuf", "Ancien", "Sale"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "J'habite dans un immeuble _________.",
    fill: "neuf",
    vfQ: "L'immeuble d'Alice est ancien.",
    vfC: 1,
  }),
  q({
    id: "047-q3",
    textQ: "À quel étage habite Alice ?",
    text: ["Au 4e", "Au 1er", "Au 10e"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "J'habite au _________ étage.",
    fill: "4e",
    fillA: ["4", "quatrième", "quatrieme"],
    vfQ: "Alice habite au rez-de-chaussée.",
    vfC: 1,
  }),
  q({
    id: "047-q4",
    textQ: "Comment Alice donne-t-elle de ses nouvelles ?",
    text: ["Par un message téléphonique", "Par une lettre", "Par un e-mail"],
    textC: 0,
    img: ["téléphone", "facteur", "ordinateur"],
    imgC: 0,
    fillQ: "À _________ !",
    fill: "bientôt",
    fillA: ["bientot"],
    vfQ: "Alice laisse un message téléphonique.",
    vfC: 0,
  }),
  q({
    id: "047-q5",
    textQ: "À qui Alice téléphone-t-elle ?",
    text: ["À une amie", "À un plombier", "À un médecin"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Alice téléphone à une _________.",
    fill: "amie",
    vfQ: "Le loyer de l'appartement d'Alice est mentionné dans le message.",
    vfC: 2,
  }),
]);

const TR_048 = `- Bonjour monsieur, je cherche un appartement dans un immeuble calme.
- Très bien. Et vous habitez où maintenant ?
- J'habite boulevard des Charmes et il y a beaucoup de bruit.
- C'est vrai. Vous voulez combien de pièces ?
- Nous sommes un couple avec 2 enfants…
- Et vous voulez 2 ou 3 chambres ?
- 3 chambres, c'est bien. Et… une cuisine équipée et des pièces lumineuses !
- Bien sûr ! Vous préférez un appartement à l'étage avec une terrasse ou au rez-de-chaussée avec un jardin ?
- Un appartement avec un jardin ? C'est super ! Nous avons un chien.
- Vous êtes libre aujourd'hui pour visiter un appartement ?`;

const POOL_048 = buildExpressPool("e2-1-048", [
  q({
    id: "048-q1",
    textQ: "Que cherche la personne ?",
    text: ["Un appartement dans un immeuble calme", "Une maison à la campagne", "Un studio pour étudiant"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je cherche un appartement dans un immeuble _________.",
    fill: "calme",
    vfQ: "La personne cherche un appartement calme.",
    vfC: 0,
  }),
  q({
    id: "048-q2",
    textQ: "Pourquoi la personne veut-elle déménager ?",
    text: ["Il y a beaucoup de bruit chez elle", "Son loyer est trop cher", "Son appartement est trop grand"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Il y a beaucoup de _________.",
    fill: "bruit",
    vfQ: "Le logement actuel de la personne est calme.",
    vfC: 1,
  }),
  q({
    id: "048-q3",
    textQ: "Combien d'enfants a le couple ?",
    text: ["Deux", "Trois", "Quatre"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous sommes un couple avec _________ enfants.",
    fill: "deux",
    fillA: ["2"],
    vfQ: "Le couple a trois enfants.",
    vfC: 1,
  }),
  q({
    id: "048-q4",
    textQ: "Combien de chambres veut la famille ?",
    text: ["Trois", "Deux", "Cinq"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ chambres, c'est bien.",
    fill: "trois",
    fillA: ["3"],
    vfQ: "La famille veut trois chambres.",
    vfC: 0,
  }),
  q({
    id: "048-q5",
    textQ: "Quel animal a la famille ?",
    text: ["Un chien", "Un chat", "Un oiseau"],
    textC: 0,
    img: ["chien", "chat", "oiseau"],
    imgC: 0,
    fillQ: "C'est super ! Nous avons un _________.",
    fill: "chien",
    vfQ: "La famille a un chat.",
    vfC: 1,
  }),
  q({
    id: "048-q6",
    textQ: "Qu'est-ce que la famille préfère ?",
    text: ["Un appartement avec un jardin", "Un appartement avec une terrasse", "Un appartement avec un garage"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Un appartement avec un _________ ? C'est super !",
    fill: "jardin",
    vfQ: "La famille préfère un appartement avec un jardin.",
    vfC: 0,
  }),
  q({
    id: "048-q7",
    textQ: "Qu'est-ce que la cliente veut aussi ?",
    text: ["Une cuisine équipée et des pièces lumineuses", "Une piscine et un garage", "Un balcon et une cave"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Une cuisine équipée et des pièces _________ !",
    fill: "lumineuses",
    vfQ: "La cliente veut une cuisine équipée.",
    vfC: 0,
  }),
  q({
    id: "048-q8",
    textQ: "Que demande l'agent à la fin ?",
    text: ["Si la personne est libre pour une visite", "Si la personne a un animal", "Si la personne veut vendre"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous êtes libre aujourd'hui pour _________ un appartement ?",
    fill: "visiter",
    vfQ: "Le prix de l'appartement est mentionné dans le dialogue.",
    vfC: 2,
  }),
]);

export const E2_1_TRAINING: ExpressListeningAudio[] = [
{
  id: "e2-1-038",
  audioSrc: A1(38),
  audioLabel: "Audio 038",
  transcript: TR_038,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_038,
  questionCount: 5,
},
{
  id: "e2-1-044",
  audioSrc: A1(44),
  audioLabel: "Audio 044",
  transcript: TR_044,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_044,
  questionCount: 5,
},
{
  id: "e2-1-045",
  audioSrc: A1(45),
  audioLabel: "Audio 045",
  transcript: TR_045,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_045,
  questionCount: 5,
},
{
  id: "e2-1-046",
  audioSrc: A1(46),
  audioLabel: "Audio 046",
  transcript: TR_046,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_046,
  questionCount: 5,
}
];

export const E2_1_EVAL: ExpressListeningAudio[] = [
{
  id: "e2-1-047",
  audioSrc: A1(47),
  audioLabel: "Audio 047",
  transcript: TR_047,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_047,
  questionCount: 5,
},
{
  id: "e2-1-048",
  audioSrc: A1(48),
  audioLabel: "Audio 048",
  transcript: TR_048,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_048,
  questionCount: 5,
}
];
