import type { CommunicationLesson } from "./express-types";

export const EXPRESSION_E1_1: CommunicationLesson = {
  id: "PE-1",
  code: "PE.1",
  title: "Base",
  theory: [
    { type: "heading", text: "Rédiger un texte simple et clair" },
    { type: "plain", text: "Avant d'écrire, il faut se poser trois questions essentielles." },
    {
      type: "numbered",
      items: [
        "À qui est-ce que j'écris ?",
        "Pourquoi est-ce que j'écris ?",
        "Quelles informations dois-je donner ?",
      ],
    },
    { type: "heading", text: "Ce qu'il faut faire" },
    { type: "highlight", title: "1. Comprendre", items: [] },
    { type: "plain", text: "Lire la consigne deux fois et entourer les mots importants." },
    { type: "highlight", title: "2. Préparer", items: [] },
    { type: "plain", text: "Noter les idées principales avec des mots-clés." },
    { type: "highlight", title: "3. Organiser", items: [] },
    { type: "plain", text: "Mettre les idées dans un ordre logique." },
    { type: "highlight", title: "4. Rédiger", items: [] },
    { type: "plain", text: "Écrire des phrases courtes avec un sujet et un verbe." },
    { type: "highlight", title: "5. Relire", items: [] },
    { type: "plain", text: "Vérifier les majuscules, les points et les mots oubliés." },
    { type: "heading", text: "Construire le texte" },
    { type: "highlight", title: "1. Au début", items: [] },
    { type: "plain", text: "Saluer et annoncer le sujet." },
    { type: "section", text: "Bonjour Sara, je t'écris pour t'inviter." },
    { type: "highlight", title: "2. Au milieu", items: [] },
    { type: "plain", text: "Donner les informations utiles selon la situation de l'énoncé." },
    { type: "section", text: "La fête est samedi à 15 heures chez moi." },
    { type: "highlight", title: "3. À la fin", items: [] },
    { type: "plain", text: "Saluter et signer." },
    { type: "section", text: "J'espère que tu peux venir. À bientôt !" },
    { type: "heading", text: "Éléments à connaître" },
    { type: "plain", text: "Il faut utiliser surtout le présent. Chaque phrase commence par une majuscule et finit avec un point." },
    { type: "highlight", title: "À éviter", items: [] },
    { type: "section", text: "écrire une seule phrase très longue\noublier la consigne\nutiliser des mots dont on ne connaît pas le sens." },
  ],
  exercises: [],
  writingLevel: "base",
};

export const EXPRESSION_E1_2: CommunicationLesson = {
  id: "PE-2",
  code: "PE.2",
  title: "Moyen",
  theory: [
    { type: "heading", text: "Développer et organiser ses idées" },
    { type: "plain", text: "Avant d'écrire, il faut se poser trois questions essentielles." },
    {
      type: "numbered",
      items: [
        "À qui est-ce que j'écris ?",
        "Pourquoi est-ce que j'écris ?",
        "Quelles informations dois-je donner ?",
      ],
    },
    { type: "heading", text: "Ce qu'il faut faire" },
    { type: "highlight", title: "1. Comprendre", items: [] },
    { type: "plain", text: "Lire la consigne deux fois et entourer les mots importants." },
    { type: "highlight", title: "2. Préparer", items: [] },
    { type: "plain", text: "Noter les idées principales avec des mots-clés." },
    { type: "highlight", title: "3. Organiser", items: [] },
    { type: "plain", text: "Mettre les idées dans un ordre logique." },
    { type: "highlight", title: "4. Rédiger", items: [] },
    { type: "plain", text: "Écrire des phrases claires avec un sujet, un verbe et des informations utiles." },
    { type: "highlight", title: "5. Relire", items: [] },
    { type: "plain", text: "Vérifier les majuscules, les points, les accords et les mots oubliés." },
    { type: "heading", text: "Construire le texte" },
    { type: "highlight", title: "Introduction", items: [] },
    { type: "plain", text: "Quel est le sujet et pourquoi est-il important ?" },
    { type: "highlight", title: "Développement", items: [] },
    { type: "plain", text: "Quels faits, détails ou exemples expliquent mon idée ?" },
    { type: "highlight", title: "Conclusion", items: [] },
    { type: "plain", text: "Quel est mon bilan, mon avis ou ma demande ?" },
    { type: "heading", text: "Éléments à connaître" },
    { type: "plain", text: "Raconter avec le passé composé et décrire avec l'imparfait. Parler d'un projet avec le futur proche ou le futur simple. Exprimer son opinion avec à mon avis, je pense que, selon moi." },
    { type: "heading", text: "Rendre le texte cohérent" },
    { type: "plain", text: "Il faut organiser le texte avec des connecteurs : d'abord, ensuite, puis, enfin, cependant, donc..." },
    { type: "highlight", title: "Ajouter", items: [] },
    { type: "section", text: "de plus, aussi, également." },
    { type: "highlight", title: "Expliquer", items: [] },
    { type: "section", text: "parce que, car, en effet." },
    { type: "highlight", title: "Opposer", items: [] },
    { type: "section", text: "mais, pourtant, cependant." },
    { type: "highlight", title: "Conclure", items: [] },
    { type: "section", text: "donc, finalement, pour conclure." },
  ],
  exercises: [],
  writingLevel: "moyen",
};

export const EXPRESSION_E1_3: CommunicationLesson = {
  id: "PE-3",
  code: "PE.3",
  title: "Avancé",
  theory: [
    { type: "heading", text: "Construire un texte développé et convaincant" },
    { type: "plain", text: "Avant d'écrire, il faut se poser trois questions essentielles." },
    {
      type: "numbered",
      items: [
        "À qui est-ce que j'écris ?",
        "Pourquoi est-ce que j'écris ?",
        "Quelles informations dois-je donner ?",
      ],
    },
    { type: "heading", text: "Ce qu'il faut faire" },
    { type: "highlight", title: "1. Comprendre", items: [] },
    { type: "plain", text: "Lire la consigne deux fois et identifier le sujet, le destinataire et le but du texte." },
    { type: "highlight", title: "2. Préparer", items: [] },
    { type: "plain", text: "Noter les idées principales, les exemples et les connecteurs utiles." },
    { type: "highlight", title: "3. Organiser", items: [] },
    { type: "plain", text: "Classer les idées dans un ordre logique avant de rédiger." },
    { type: "highlight", title: "4. Rédiger", items: [] },
    { type: "plain", text: "Développer chaque idée avec une explication et un exemple précis." },
    { type: "highlight", title: "5. Relire", items: [] },
    { type: "plain", text: "Vérifier la cohérence, les temps, les accords, les pronoms et les répétitions." },
    { type: "highlight", title: "Objectifs possibles", items: [] },
    { type: "section", text: "Informer avec des faits exacts et bien organisés.\nRaconter en donnant un contexte, des événements et un bilan.\nArgumenter avec une opinion, des raisons et des exemples.\nConvaincre en tenant compte du lecteur et des objections possibles." },
    { type: "heading", text: "Construire le texte" },
    { type: "highlight", title: "Introduction", items: [] },
    { type: "plain", text: "Présenter le thème, le contexte et la question principale." },
    { type: "highlight", title: "Argument 1", items: [] },
    { type: "plain", text: "Annoncer une idée, l'expliquer et donner un exemple précis." },
    { type: "highlight", title: "Argument 2", items: [] },
    { type: "plain", text: "Ajouter ou nuancer avec un nouveau point de vue." },
    { type: "highlight", title: "Conclusion", items: [] },
    { type: "plain", text: "Résumer sans répéter et proposer une ouverture ou une solution." },
    { type: "heading", text: "Éléments à connaître" },
    { type: "plain", text: "Varier les phrases simples et complexes. Choisir un registre cohérent et reprendre les idées avec des pronoms ou des synonymes. Nuancer avec certes, toutefois, en revanche, même si, bien que... Exprimer la cause et la conséquence avec puisque, grâce à, à cause de, par conséquent..." },
    { type: "heading", text: "Rédaction d'une lettre" },
    { type: "plain", text: "Une lettre administrative ou formelle doit être claire, précise et courtoise. Il faut éviter les phrases trop longues, les répétitions et les formules familières." },
    {
      type: "table",
      headers: ["Vous écrivez pour...", "Formule possible"],
      rows: [
        ["réclamer", "Suite à votre annonce du..."],
        ["exprimer un regret", "J'ai le plaisir de... / Je regrette de..."],
        ["répondre à une annonce", "Je me vois obligé(e) de rejeter..."],
        ["réagir à une information", "Il m'est malheureusement impossible, pour des raisons personnelles, de..."],
        ["refuser", "Je vous serais reconnaissant(e) de bien vouloir..."],
        ["proposer", "Je vous prie de bien vouloir, dans les plus brefs délais..."],
        ["demander quelque chose", "Je me permets de vous écrire pour vous dire que..."],
        ["protester", "Je suis surpris(e) d'apprendre que..."],
      ],
    },
    {
      type: "table",
      headers: ["Situation", "Formule d'appel", "Formule de politesse"],
      rows: [
        ["Personne inconnue ou officielle", "Monsieur, Madame,", "Veuillez agréer l'expression de mes salutations distinguées."],
        ["Direction ou service", "Madame, Monsieur,", "Veuillez agréer mes salutations distinguées."],
        ["Personne connue", "Cher Monsieur, / Chère Madame,", "Je vous prie de recevoir mes salutations cordiales."],
        ["Relation amicale", "Cher ami, / Chère amie,", "Je t'adresse mes amitiés."],
        ["Directeur ou directrice", "Monsieur le Directeur, / Madame la Directrice,", "Veuillez recevoir mes salutations respectueuses."],
        ["Message de soutien", "Madame, Monsieur,", "Veuillez croire en toute ma sympathie."],
      ],
    },
    { type: "heading", text: "Disposition de la lettre" },
    { type: "plain", text: "Lorsque vous rédigez une lettre officielle, placez les informations dans un ordre fixe. Cette disposition aide le lecteur à comprendre rapidement qui écrit, à qui, pourquoi et avec quelles pièces jointes." },
    {
      type: "numbered",
      items: [
        "Votre nom et votre adresse.",
        "Le nom et l'adresse de la personne ou du service destinataire.",
        "Le lieu et la date.",
        "Les références utiles si vous répondez à une lettre.",
        "L'objet de la lettre.",
        "Le corps de la lettre : introduction, explications, demande ou argumentation.",
        "La formule de politesse.",
        "Votre signature.",
      ],
    },
    { type: "heading", text: "Erreurs à éviter" },
    { type: "section", text: "écrire sans objet clair\nmélanger le registre familier et formel\noublier la formule d'appel ou la formule de politesse\nfaire des phrases trop longues\najouter des informations hors sujet" },
  ],
  exercises: [],
  writingLevel: "avance",
};
