import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_116 = `- Bonjour, c'est pour déjeuner ?
- Oui, vous avez une table pour deux ?
- Ici. Voici le menu du jour.
- Tu prends du poisson ou de la viande ?
- Mais, je suis végétarien !
- C'est vrai ! Tu ne manges pas de viande, pas de poisson. Une salade ?
- D'accord.
- Et tu bois quoi ?
- Pas d'alcool, je bois de l'eau.
- Je peux prendre votre commande ?
- Alors… une salade chinoise, un steak-frites et deux tartes aux fraises.
- Qu'est-ce que vous buvez ?
- Une carafe d'eau s'il vous plaît.
- Tout va bien ?
- Oui, c'est excellent !
- L'addition s'il vous plaît !
- On laisse un pourboire ?
- Oui, bien sûr !`;

const POOL_116 = buildExpressPool("e4-2-116", [
  q({
    id: "116-q1",
    textQ: "Où se passe la conversation ?",
    text: ["Au restaurant", "À la boulangerie", "Au supermarché"],
    textC: 0,
    img: ["restaurant", "boulangerie", "supermarché"],
    imgC: 0,
    fillQ: "Bonjour, c'est pour _________ ?",
    fill: "déjeuner",
    fillA: ["dejeuner"],
    vfQ: "Les clients viennent pour déjeuner.",
    vfC: 0,
  }),
  q({
    id: "116-q2",
    textQ: "Pour combien de personnes est la table ?",
    text: ["Pour deux", "Pour quatre", "Pour six"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous avez une table pour _________ ?",
    fill: "deux",
    fillA: ["2"],
    vfQ: "La table est pour quatre personnes.",
    vfC: 1,
  }),
  q({
    id: "116-q3",
    textQ: "Pourquoi l'un des clients ne mange-t-il pas de viande ?",
    text: ["Il est végétarien", "Il n'a pas faim", "Il est malade"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Mais, je suis _________ !",
    fill: "végétarien",
    fillA: ["vegetarien"],
    vfQ: "Un des clients est végétarien.",
    vfC: 0,
  }),
  q({
    id: "116-q4",
    textQ: "Que mange le client végétarien ?",
    text: ["Une salade", "Un steak", "Du poisson"],
    textC: 0,
    img: ["salade", "viande", "poisson"],
    imgC: 0,
    fillQ: "Tu ne manges pas de viande… Une _________ ?",
    fill: "salade",
    vfQ: "Le client végétarien prend du poisson.",
    vfC: 1,
  }),
  q({
    id: "116-q5",
    textQ: "Que boit le client végétarien ?",
    text: ["De l'eau", "Du vin", "Du café"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Pas d'alcool, je bois de l'_________.",
    fill: "eau",
    vfQ: "Le client végétarien boit de l'alcool.",
    vfC: 1,
  }),
  q({
    id: "116-q6",
    textQ: "Quel dessert les clients commandent-ils ?",
    text: ["Deux tartes aux fraises", "Deux glaces au chocolat", "Deux parts de gâteau"],
    textC: 0,
    img: ["tarte", "glace", "gâteau"],
    imgC: 0,
    fillQ: "Un steak-frites et deux tartes aux _________.",
    fill: "fraises",
    vfQ: "Les tartes aux fraises coûtent cinq euros.",
    vfC: 2,
  }),
  q({
    id: "116-q7",
    textQ: "Comment les clients trouvent-ils le repas ?",
    text: ["Excellent", "Correct", "Mauvais"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Tout va bien ? — Oui, c'est _________ !",
    fill: "excellent",
    vfQ: "Les clients trouvent le repas excellent.",
    vfC: 0,
  }),
  q({
    id: "116-q8",
    textQ: "Est-ce que les clients laissent un pourboire ?",
    text: ["Oui", "Non", "On ne sait pas"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "On laisse un _________ ? — Oui, bien sûr !",
    fill: "pourboire",
    vfQ: "Les clients ne laissent pas de pourboire.",
    vfC: 1,
  }),
]);

const TR_122 = `Je déjeune tous les jours chez Jeanne. Les plats et les desserts sont excellents. Il y a toujours deux entrées avec des légumes délicieux. En été, ils servent aussi des glaces à la fraise.`;

const POOL_122 = buildExpressPool("e4-2-122", [
  q({
    id: "122-q1",
    textQ: "Quand la personne déjeune-t-elle chez Jeanne ?",
    text: ["Tous les jours", "Une fois par semaine", "Une fois par mois"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je déjeune tous les _________ chez Jeanne.",
    fill: "jours",
    vfQ: "La personne déjeune chez Jeanne tous les jours.",
    vfC: 0,
  }),
  q({
    id: "122-q2",
    textQ: "Comment sont les plats et les desserts ?",
    text: ["Excellents", "Corrects", "Mauvais"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Les plats et les desserts sont _________.",
    fill: "excellents",
    vfQ: "Les desserts ne sont pas bons.",
    vfC: 1,
  }),
  q({
    id: "122-q3",
    textQ: "Combien d'entrées y a-t-il toujours ?",
    text: ["Deux", "Trois", "Quatre"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Il y a toujours _________ entrées.",
    fill: "deux",
    fillA: ["2"],
    vfQ: "Il y a toujours trois entrées.",
    vfC: 1,
  }),
  q({
    id: "122-q4",
    textQ: "Avec quoi sont préparées les entrées ?",
    text: ["Avec des légumes", "Avec du poisson", "Avec du fromage"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Deux entrées avec des _________ délicieux.",
    fill: "légumes",
    fillA: ["legumes"],
    vfQ: "Les légumes des entrées sont délicieux.",
    vfC: 0,
  }),
  q({
    id: "122-q5",
    textQ: "Que sert le restaurant en été ?",
    text: ["Des glaces à la fraise", "Des crêpes au chocolat", "Des tartes au citron"],
    textC: 0,
    img: ["glace", "crêpe", "tarte"],
    imgC: 0,
    fillQ: "En été, ils servent aussi des glaces à la _________.",
    fill: "fraise",
    vfQ: "Les glaces à la fraise sont servies en hiver.",
    vfC: 1,
  }),
  q({
    id: "122-q6",
    textQ: "Combien coûte le déjeuner chez Jeanne ?",
    text: ["Ce n'est pas dit", "Dix euros", "Vingt euros"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Les _________ et les desserts sont excellents.",
    fill: "plats",
    vfQ: "Le déjeuner chez Jeanne coûte dix euros.",
    vfC: 2,
  }),
]);

const TR_123 = `- Délidéli, bonjour, je peux prendre votre commande ?
- Oui, bonjour ! Je voudrais un menu Roma avec une salade italienne et des pâtes aux légumes.
- D'accord, donnez-moi votre adresse.`;

const POOL_123 = buildExpressPool("e4-2-123", [
  q({
    id: "123-q1",
    textQ: "Que fait le client ?",
    text: ["Il commande un repas", "Il réserve une table", "Il demande l'addition"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je peux prendre votre _________ ?",
    fill: "commande",
    vfQ: "Le client commande un repas.",
    vfC: 0,
  }),
  q({
    id: "123-q2",
    textQ: "Quel menu le client choisit-il ?",
    text: ["Le menu Roma", "Le menu Atlantique", "Le menu du jour"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je voudrais un _________ Roma.",
    fill: "menu",
    vfQ: "Le client choisit le menu du jour.",
    vfC: 1,
  }),
  q({
    id: "123-q3",
    textQ: "Qu'est-ce que le client commande avec le menu ?",
    text: ["Une salade et des pâtes", "Une pizza et des frites", "Un sandwich et une soupe"],
    textC: 0,
    img: ["salade", "pizza", "sandwich"],
    imgC: 0,
    fillQ: "Avec une _________ italienne et des pâtes aux légumes.",
    fill: "salade",
    vfQ: "Le client commande une pizza.",
    vfC: 1,
  }),
  q({
    id: "123-q4",
    textQ: "Comment sont préparées les pâtes ?",
    text: ["Aux légumes", "Au poulet", "Au fromage"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Et des pâtes aux _________.",
    fill: "légumes",
    fillA: ["legumes"],
    vfQ: "Les pâtes sont aux légumes.",
    vfC: 0,
  }),
  q({
    id: "123-q5",
    textQ: "Que demande l'employé à la fin ?",
    text: ["L'adresse du client", "Le nom du client", "L'âge du client"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Oui, bonjour ! Je _________ un menu Roma.",
    fill: "voudrais",
    vfQ: "À la fin, l'employé demande l'adresse du client.",
    vfC: 0,
  }),
]);

const TR_124 = `- Bonjour messieurs-dames, voici une table pour quatre. Aujourd'hui pour le déjeuner, le chef vous propose un menu spécial « Atlantique » avec du poisson et des petits légumes.`;

const POOL_124 = buildExpressPool("e4-2-124", [
  q({
    id: "124-q1",
    textQ: "Pour combien de personnes est la table ?",
    text: ["Pour quatre", "Pour deux", "Pour huit"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Voici une table pour _________.",
    fill: "quatre",
    fillA: ["4"],
    vfQ: "La table est pour deux personnes.",
    vfC: 1,
  }),
  q({
    id: "124-q2",
    textQ: "Pour quel repas le menu spécial est-il proposé ?",
    text: ["Pour le déjeuner", "Pour le dîner", "Pour le petit-déjeuner"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Aujourd'hui pour le _________, le chef vous propose un menu spécial.",
    fill: "déjeuner",
    fillA: ["dejeuner"],
    vfQ: "Le menu spécial est proposé pour le dîner.",
    vfC: 1,
  }),
  q({
    id: "124-q3",
    textQ: "Qu'est-ce qu'il y a dans le menu « Atlantique » ?",
    text: ["Du poisson et des petits légumes", "De la viande et des frites", "Des pâtes et de la salade"],
    textC: 0,
    img: ["poisson", "viande", "pâtes"],
    imgC: 0,
    fillQ: "Un menu spécial « Atlantique » avec du _________ et des petits légumes.",
    fill: "poisson",
    vfQ: "Le menu « Atlantique » est un menu avec du poisson.",
    vfC: 0,
  }),
  q({
    id: "124-q4",
    textQ: "Qui propose le menu spécial ?",
    text: ["Le chef", "La serveuse", "Le client"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Le _________ vous propose un menu spécial.",
    fill: "chef",
    vfQ: "C'est le chef qui propose le menu spécial.",
    vfC: 0,
  }),
  q({
    id: "124-q5",
    textQ: "Quand ce menu spécial est-il proposé ?",
    text: ["Aujourd'hui", "Demain", "Ce week-end"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ pour le déjeuner, le chef vous propose un menu spécial.",
    fill: "aujourd'hui",
    fillA: ["aujourdhui", "aujourd hui"],
    vfQ: "Le menu spécial est proposé aujourd'hui.",
    vfC: 0,
  }),
  q({
    id: "124-q6",
    textQ: "Combien coûte le menu « Atlantique » ?",
    text: ["Ce n'est pas dit", "Quinze euros", "Vingt euros"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Le chef vous propose un _________ spécial « Atlantique ».",
    fill: "menu",
    vfQ: "Le menu « Atlantique » coûte vingt euros.",
    vfC: 2,
  }),
]);

const TR_125 = `Nous recevons beaucoup de questions sur le pourboire en France. C'est simple : le pourboire n'est pas obligatoire, mais si vous voulez, vous pouvez laisser environ 5 % de votre addition.`;

const POOL_125 = buildExpressPool("e4-2-125", [
  q({
    id: "125-q1",
    textQ: "De quoi parle cet enregistrement ?",
    text: ["Du pourboire", "Des menus du jour", "Des horaires d'ouverture"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous recevons beaucoup de questions sur le _________.",
    fill: "pourboire",
    vfQ: "L'enregistrement parle du pourboire en France.",
    vfC: 0,
  }),
  q({
    id: "125-q2",
    textQ: "Est-ce que le pourboire est obligatoire ?",
    text: ["Non", "Oui", "Seulement le soir"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Le pourboire n'est pas _________.",
    fill: "obligatoire",
    vfQ: "Le pourboire est obligatoire.",
    vfC: 1,
  }),
  q({
    id: "125-q3",
    textQ: "Combien peut-on laisser de pourboire ?",
    text: ["Environ 5 % de l'addition", "Environ 20 % de l'addition", "Environ 50 % de l'addition"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous pouvez laisser environ _________ % de votre addition.",
    fill: "cinq",
    fillA: ["5"],
    vfQ: "On peut laisser environ 5 % de l'addition.",
    vfC: 0,
  }),
  q({
    id: "125-q4",
    textQ: "Qui décide de laisser un pourboire ?",
    text: ["Le client", "Le serveur", "Le cuisinier"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Si vous _________, vous pouvez laisser un pourboire.",
    fill: "voulez",
    vfQ: "C'est le serveur qui décide du pourboire.",
    vfC: 1,
  }),
  q({
    id: "125-q5",
    textQ: "Où laisse-t-on généralement un pourboire ?",
    text: ["Au restaurant", "À la boulangerie", "Au supermarché"],
    textC: 0,
    img: ["restaurant", "boulangerie", "supermarché"],
    imgC: 0,
    fillQ: "Vous pouvez laisser environ 5 % de votre _________.",
    fill: "addition",
    vfQ: "Le pourboire se calcule sur l'addition.",
    vfC: 0,
  }),
  q({
    id: "125-q6",
    textQ: "Pourquoi parle-t-on du pourboire aujourd'hui ?",
    text: ["Beaucoup de personnes posent la question", "C'est une nouvelle loi", "Les serveurs le demandent"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous recevons beaucoup de _________ sur le pourboire en France.",
    fill: "questions",
    vfQ: "Le pourboire se laisse seulement dans les cafés.",
    vfC: 2,
  }),
]);

const TR_126 = `- Bonjour, nous avons une réservation pour huit.
- Ah oui, voici une table pour huit. Je vous apporte le menu.
- Je prends votre commande ?
- Oui, nous prenons huit menus, huit entrées et huit plats, mais pas de dessert.
- Est-ce que vous prenez du fromage ?
- Non, pas de fromage.
- Et qu'est-ce que vous buvez ? Du vin ?
- Non, pas de vin. Trois jus d'orange, une eau gazeuse, un jus de tomate et une carafe d'eau.`;

const POOL_126 = buildExpressPool("e4-2-126", [
  q({
    id: "126-q1",
    textQ: "Pour combien de personnes est la réservation ?",
    text: ["Pour huit", "Pour six", "Pour quatre"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Nous avons une réservation pour _________.",
    fill: "huit",
    fillA: ["8"],
    vfQ: "La réservation est pour six personnes.",
    vfC: 1,
  }),
  q({
    id: "126-q2",
    textQ: "Qu'est-ce que le serveur apporte ?",
    text: ["Le menu", "L'addition", "Les boissons"],
    textC: 0,
    img: ["menu", "addition", "boisson"],
    imgC: 0,
    fillQ: "Je vous apporte le _________.",
    fill: "menu",
    vfQ: "Le serveur apporte le menu.",
    vfC: 0,
  }),
  q({
    id: "126-q3",
    textQ: "Est-ce que les clients prennent un dessert ?",
    text: ["Non", "Oui, huit desserts", "Oui, un seul dessert"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Huit entrées et huit plats, mais pas de _________.",
    fill: "dessert",
    vfQ: "Les clients prennent huit desserts.",
    vfC: 1,
  }),
  q({
    id: "126-q4",
    textQ: "Est-ce que les clients prennent du fromage ?",
    text: ["Non", "Oui, un plateau", "Oui, avec le dessert"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Non, pas de _________.",
    fill: "fromage",
    vfQ: "Les clients ne prennent pas de fromage.",
    vfC: 0,
  }),
  q({
    id: "126-q5",
    textQ: "Que boivent les clients ?",
    text: ["Des jus et de l'eau", "Du vin", "Du café"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Non, pas de _________. Trois jus d'orange…",
    fill: "vin",
    vfQ: "Les clients boivent du vin.",
    vfC: 1,
  }),
  q({
    id: "126-q6",
    textQ: "Combien de jus d'orange commandent-ils ?",
    text: ["Trois", "Deux", "Huit"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "_________ jus d'orange, une eau gazeuse et un jus de tomate.",
    fill: "trois",
    fillA: ["3"],
    vfQ: "Ils commandent trois jus d'orange.",
    vfC: 0,
  }),
  q({
    id: "126-q7",
    textQ: "Quel plat les clients choisissent-ils ?",
    text: ["On ne le sait pas", "Du poisson", "Du steak"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Ils commandent aussi une eau _________.",
    fill: "gazeuse",
    vfQ: "Les clients mangent du poisson.",
    vfC: 2,
  }),
]);

export const E4_2_TRAINING: ExpressListeningAudio[] = [
{
  id: "e4-2-116",
  audioSrc: A1(116),
  audioLabel: "Audio 116",
  transcript: TR_116,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_116,
  questionCount: 5,
},
{
  id: "e4-2-122",
  audioSrc: A1(122),
  audioLabel: "Audio 122",
  transcript: TR_122,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_122,
  questionCount: 5,
},
{
  id: "e4-2-123",
  audioSrc: A1(123),
  audioLabel: "Audio 123",
  transcript: TR_123,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_123,
  questionCount: 5,
},
{
  id: "e4-2-124",
  audioSrc: A1(124),
  audioLabel: "Audio 124",
  transcript: TR_124,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_124,
  questionCount: 5,
}
];

export const E4_2_EVAL: ExpressListeningAudio[] = [
{
  id: "e4-2-125",
  audioSrc: A1(125),
  audioLabel: "Audio 125",
  transcript: TR_125,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_125,
  questionCount: 5,
},
{
  id: "e4-2-126",
  audioSrc: A1(126),
  audioLabel: "Audio 126",
  transcript: TR_126,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_126,
  questionCount: 5,
}
];
