import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_171 = `- Alors Marianne, pourquoi tu ne prends pas le train ?
- J'adore le covoiturage. Les conducteurs et les passagers sont sympas et les voitures confortables… mais il n'y a pas de voiture-bar !
- Et toi Antoine, tu n'aimes pas le train ?
- Si, mais les billets sont trop chers et il y a souvent du retard. Et quand il y a une grève, les trains sont annulés !
- Claire, tu voyages toujours en voiture, toi ?
- Non, quand le trajet est long, je prends le train. Je réserve une place côté fenêtre et je dors !
- Et vous achetez vos billets sur l'appli de la SNCF ?
- Oui, c'est simple et pratique.`;

const POOL_171 = buildExpressPool("e6-2-171", [
  q({
    id: "171-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Marianne", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Marianne",
  }),
  q({
    id: "171-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Les", "Marie", "Paul"],
    textC: 0,
    img: ["Les", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Les",
  }),
  q({
    id: "171-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Antoine", "Marie", "Paul"],
    textC: 0,
    img: ["Antoine", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Antoine",
  }),
  q({
    id: "171-q4",
    format: "vf",
    textQ: "Le train est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Le train est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "171-q5",
    format: "vf",
    textQ: "Alors Marianne, pourquoi tu ne prends pas le train",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Alors Marianne, pourquoi tu ne prends pas le train",
    vfC: 0,
  }),
  q({
    id: "171-q6",
    format: "vf",
    textQ: "Alors Marianne, pourquoi tu prends pas le train",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Alors Marianne, pourquoi tu prends pas le train",
    vfC: 1,
  }),
  q({
    id: "171-q7",
    format: "vf",
    textQ: "J'adore le covoiturage",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "J'adore le covoiturage",
    vfC: 0,
  }),
  q({
    id: "171-q8",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  })
]);

const TR_177 = `Mesdames, messieurs, bonjour. La vitesse de notre TGV est maintenant de 300 km/h. L'arrivée en gare de Bordeaux est prévue à 11 h 02, avec un retard de 5 minutes. La SNCF vous souhaite un excellent voyage.`;

const POOL_177 = buildExpressPool("e6-2-177", [
  q({
    id: "177-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Mesdames", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Mesdames",
  }),
  q({
    id: "177-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Bordeaux", "Marie", "Paul"],
    textC: 0,
    img: ["Bordeaux", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Bordeaux",
  }),
  q({
    id: "177-q3",
    format: "fill",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["300", "10 heures", "20 €"],
    textC: 0,
    img: ["300", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "Quel chiffre ou horaire est cité : _________.",
    fill: "300",
  }),
  q({
    id: "177-q4",
    format: "vf",
    textQ: "11 h 02 est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "11 h 02 est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "177-q5",
    format: "vf",
    textQ: "Mesdames, messieurs, bonjour",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Mesdames, messieurs, bonjour",
    vfC: 0,
  }),
  q({
    id: "177-q6",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "177-q7",
    format: "vf",
    textQ: "La vitesse de notre TGV est maintenant de 300 km/h",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "La vitesse de notre TGV est maintenant de 300 km/h",
    vfC: 0,
  }),
  q({
    id: "177-q8",
    format: "vf",
    textQ: "L'arrivée en gare de Bordeaux est prévue à 11 h 02, avec un retard de 5 minutes",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "L'arrivée en gare de Bordeaux est prévue à 11 h 02, avec un retard de 5 minutes",
    vfC: 0,
  })
]);

const TR_178 = `Pour les vacances, pensez au covoiturage avec l'application Covoit'. Choisissez votre trajet, votre horaire et votre conducteur. Réservez et payez. Voyager avec Covoit, c'est simple !`;

const POOL_178 = buildExpressPool("e6-2-178", [
  q({
    id: "178-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Covoit", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Covoit",
  }),
  q({
    id: "178-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Choisissez", "Marie", "Paul"],
    textC: 0,
    img: ["Choisissez", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Choisissez",
  }),
  q({
    id: "178-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Réservez", "Marie", "Paul"],
    textC: 0,
    img: ["Réservez", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Réservez",
  }),
  q({
    id: "178-q4",
    format: "vf",
    textQ: "Pour les vacances, pensez au covoiturage avec l'application Covoit'",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Pour les vacances, pensez au covoiturage avec l'application Covoit'",
    vfC: 0,
  }),
  q({
    id: "178-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "178-q6",
    format: "vf",
    textQ: "Choisissez votre trajet, votre horaire et votre conducteur",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Choisissez votre trajet, votre horaire et votre conducteur",
    vfC: 0,
  }),
  q({
    id: "178-q7",
    format: "vf",
    textQ: "Réservez et payez",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Réservez et payez",
    vfC: 0,
  }),
  q({
    id: "178-q8",
    format: "vf",
    textQ: "Voyager avec Covoit, c'est simple",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Voyager avec Covoit, c'est simple",
    vfC: 0,
  })
]);

const TR_179 = `- Pardon madame, j'ai la place 46, côté fenêtre, voiture 4.
- Attendez, je regarde mon billet… Oh, excusez-moi ! J'ai la place 46, c'est aussi une fenêtre, mais dans la voiture 5.`;

const POOL_179 = buildExpressPool("e6-2-179", [
  q({
    id: "179-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Attendez", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Attendez",
  }),
  q({
    id: "179-q2",
    format: "image",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["46", "10 heures", "20 €"],
    textC: 0,
    img: ["46", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "_________",
    fill: "46",
  }),
  q({
    id: "179-q3",
    format: "vf",
    textQ: "Pardon madame, j'ai la place 46, côté fenêtre, voiture 4",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Pardon madame, j'ai la place 46, côté fenêtre, voiture 4",
    vfC: 0,
  }),
  q({
    id: "179-q4",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "179-q5",
    format: "vf",
    textQ: "Attendez, je regarde mon billet… Oh, excusez-moi",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Attendez, je regarde mon billet… Oh, excusez-moi",
    vfC: 0,
  }),
  q({
    id: "179-q6",
    format: "vf",
    textQ: "J'ai la place 46, c'est aussi une fenêtre, mais dans la voiture 5",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "J'ai la place 46, c'est aussi une fenêtre, mais dans la voiture 5",
    vfC: 0,
  }),
  q({
    id: "179-q7",
    format: "vf",
    textQ: "J'ai la place 46, c'est aussi ufenêtre, mais dans la voiture 5",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "J'ai la place 46, c'est aussi ufenêtre, mais dans la voiture 5",
    vfC: 1,
  })
]);

const TR_180 = `Salut Paul ! Finalement je ne fais pas de covoiturage pour mon trajet Strasbourg-Nice, c'est trop long. Je prends le TGV de 6 heures samedi. Le billet est à 20 € seulement.`;

const POOL_180 = buildExpressPool("e6-2-180", [
  q({
    id: "180-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Paul", "Marie", "Sophie"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Paul",
  }),
  q({
    id: "180-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Finalement", "Marie", "Paul"],
    textC: 0,
    img: ["Finalement", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Finalement",
  }),
  q({
    id: "180-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Strasbourg-", "Marie", "Paul"],
    textC: 0,
    img: ["Strasbourg-", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Strasbourg-",
  }),
  q({
    id: "180-q4",
    format: "vf",
    textQ: "20 est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "20 est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "180-q5",
    format: "vf",
    textQ: "Finalement je ne fais pas de covoiturage pour mon trajet Strasbourg-Nice, c'est trop long",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Finalement je ne fais pas de covoiturage pour mon trajet Strasbourg-Nice, c'est trop long",
    vfC: 0,
  }),
  q({
    id: "180-q6",
    format: "vf",
    textQ: "Finalement je fais pas de covoiturage pour mon trajet Strasbourg-Nice, c'est trop long",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Finalement je fais pas de covoiturage pour mon trajet Strasbourg-Nice, c'est trop long",
    vfC: 1,
  }),
  q({
    id: "180-q7",
    format: "vf",
    textQ: "Je prends le TGV de 6 heures samedi",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Je prends le TGV de 6 heures samedi",
    vfC: 0,
  }),
  q({
    id: "180-q8",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  })
]);

const TR_181 = `- Bonjour monsieur, je voudrais le prix d'un billet Marseille-Lyon, le 2 décembre, s'il vous plaît.
- Vous voulez un aller-retour ou un aller simple ?
- Un aller simple.
- Et vous voulez partir le matin ou l'après-midi ?
- Tôt le matin s'il vous plaît.
- Vous avez un TER à 6 h avec une arrivée à Lyon à 9 h 45. Le billet est à 49 €.
- Oh là là, c'est trop long…
- Oui, le trajet dure 3 h 45 et il y a 13 arrêts.
- Il n'y a pas de TGV ?
- Si, vous avez le TGV de 9 h 35. Il arrive à 11 h 20. Le trajet dure 1 h 45 et il y a 2 arrêts. Mais le billet est à 67 €.
- Merci beaucoup monsieur.`;

const POOL_181 = buildExpressPool("e6-2-181", [
  q({
    id: "181-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Marseille-", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Marseille-",
  }),
  q({
    id: "181-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Lyon", "Marie", "Paul"],
    textC: 0,
    img: ["Lyon", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Lyon",
  }),
  q({
    id: "181-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Tôt", "Marie", "Paul"],
    textC: 0,
    img: ["Tôt", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Tôt",
  }),
  q({
    id: "181-q4",
    format: "vf",
    textQ: "6 h est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "6 h est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "181-q5",
    format: "text",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["9 h 45", "10 heures", "20 €"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "9 h 45",
  }),
  q({
    id: "181-q6",
    format: "image",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["49", "10 heures", "20 €"],
    textC: 0,
    img: ["49", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "_________",
    fill: "49",
  }),
  q({
    id: "181-q7",
    format: "vf",
    textQ: "Bonjour monsieur, je voudrais le prix d'un billet Marseille-Lyon, le 2 décembre, s'il v…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour monsieur, je voudrais le prix d'un billet Marseille-Lyon, le 2 décembre, s'il v…",
    vfC: 0,
  }),
  q({
    id: "181-q8",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  })
]);

export const E6_2_TRAINING: ExpressListeningAudio[] = [
{
  id: "e6-2-171",
  audioSrc: A1(171),
  audioLabel: "Audio 171",
  transcript: TR_171,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_171,
  questionCount: 4,
},
{
  id: "e6-2-177",
  audioSrc: A1(177),
  audioLabel: "Audio 177",
  transcript: TR_177,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_177,
  questionCount: 4,
},
{
  id: "e6-2-178",
  audioSrc: A1(178),
  audioLabel: "Audio 178",
  transcript: TR_178,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_178,
  questionCount: 4,
},
{
  id: "e6-2-179",
  audioSrc: A1(179),
  audioLabel: "Audio 179",
  transcript: TR_179,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_179,
  questionCount: 4,
}
];

export const E6_2_EVAL: ExpressListeningAudio[] = [
{
  id: "e6-2-180",
  audioSrc: A1(180),
  audioLabel: "Audio 180",
  transcript: TR_180,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_180,
  questionCount: 4,
},
{
  id: "e6-2-181",
  audioSrc: A1(181),
  audioLabel: "Audio 181",
  transcript: TR_181,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_181,
  questionCount: 4,
}
];
