import {
  readingPoolExercise,
  type CommunicationExercise,
  type ExpressPoDialogue,
  type ExpressPePrompt,
} from "./express-types";
import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";

function q(item: ExpressRawQ): ExpressRawQ {
  return item;
}

/* ── Compréhension écrite — E8.1 Bilan A1 (e-mail d'une amie) ─────────────── */

const CE_TEXT = `Bonjour Léa,

Comment vas-tu ? Moi, tout va bien ! J'habite dans un appartement grand et lumineux. Il a une belle terrasse. Le quartier est calme et les voisins sont sympas.
Je travaille comme serveuse dans un restaurant italien. Je commence à 10 heures et je finis tard. Le lundi, le restaurant est fermé : je me repose !
En juillet, je pars en vacances. Je pars deux semaines au Portugal avec mon frère. On prend le train, c'est plus simple que l'avion.
Viens me voir bientôt ! Samedi, il y a un festival de musique au bord du lac.

À bientôt,
Emma`;

const CE_POOL = buildExpressPool("e8-1-ce", [
  q({
    id: "ce-q1",
    textQ: "Comment est l'appartement d'Emma ?",
    text: ["Grand et lumineux", "Petit et sombre", "Vieux et bruyant"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "J'habite dans un appartement grand et _________.",
    fill: "lumineux",
    vfQ: "L'appartement d'Emma a une belle terrasse.",
    vfC: 0,
  }),
  q({
    id: "ce-q2",
    textQ: "Comment sont les voisins d'Emma ?",
    text: ["Sympas", "Désagréables", "Bruyants"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Le quartier est calme et les voisins sont _________.",
    fill: "sympas",
    vfQ: "Le quartier d'Emma est très bruyant.",
    vfC: 1,
  }),
  q({
    id: "ce-q3",
    textQ: "Quel est le travail d'Emma ?",
    text: ["Serveuse", "Cuisinière", "Fleuriste"],
    textC: 0,
    img: ["serveuse", "cuisinier", "fleuriste"],
    imgC: 0,
    fillQ: "Je travaille comme _________ dans un restaurant italien.",
    fill: "serveuse",
    vfQ: "Emma travaille dans un restaurant italien.",
    vfC: 0,
  }),
  q({
    id: "ce-q4",
    textQ: "Quel jour Emma se repose-t-elle ?",
    text: ["Le lundi", "Le samedi", "Le dimanche"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Le lundi, le restaurant est _________ : je me repose !",
    fill: "fermé",
    fillA: ["ferme"],
    vfQ: "Emma finit son travail tôt le soir.",
    vfC: 1,
  }),
  q({
    id: "ce-q5",
    textQ: "Combien de temps durent les vacances d'Emma ?",
    text: ["Deux semaines", "Une semaine", "Un mois"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je pars _________ semaines au Portugal avec mon frère.",
    fill: "deux",
    fillA: ["2"],
    vfQ: "Emma part un mois en vacances.",
    vfC: 1,
  }),
  q({
    id: "ce-q6",
    textQ: "Comment Emma voyage-t-elle jusqu'au Portugal ?",
    text: ["En train", "En avion", "En bus"],
    textC: 0,
    img: ["train", "avion", "bus"],
    imgC: 0,
    fillQ: "On prend le _________, c'est plus simple que l'avion.",
    fill: "train",
    vfQ: "Pour Emma, le train est plus simple que l'avion.",
    vfC: 0,
  }),
  q({
    id: "ce-q7",
    textQ: "Qu'est-ce qu'il y a samedi au bord du lac ?",
    text: ["Un festival de musique", "Un match de football", "Un marché"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Samedi, il y a un festival de _________ au bord du lac.",
    fill: "musique",
    vfQ: "Le prix du billet du festival est indiqué dans l'e-mail.",
    vfC: 2,
  }),
  q({
    id: "ce-q8",
    textQ: "Avec qui Emma part-elle en vacances ?",
    text: ["Avec son frère", "Avec sa sœur", "Avec ses parents"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Je pars deux semaines au Portugal avec mon _________.",
    fill: "frère",
    fillA: ["frere"],
    vfQ: "Emma invite Léa à venir la voir.",
    vfC: 0,
  }),
]);

export const E8_1_CE: CommunicationExercise = readingPoolExercise({
  id: "e8-1-ce",
  readingText: CE_TEXT,
  questionPool: CE_POOL,
});

/* ── Production orale — dialogues à jouer (bilan des thèmes A1) ────────────── */

const AMI = { title: "L'ami", vous: "l'ami / l'amie" };

export const E8_1_PO: ExpressPoDialogue[] = [
  {
    id: "e8-1-po-1",
    title: "Se présenter à un nouveau collègue",
    context: "C'est votre premier jour de travail. Vous rencontrez un collègue.",
    roleA: { title: "Le collègue", vous: "le collègue / la collègue" },
    roleB: { title: "Le nouveau", vous: "le nouveau / la nouvelle" },
    lines: [
      { role: "A", text: "Bonjour ! Tu es nouveau ici ?" },
      { role: "B", text: "Oui, c'est mon premier jour. Je m'appelle Sami." },
      { role: "A", text: "Enchanté, Sami ! Tu viens d'où ?" },
      { role: "B", text: "Je viens de Tunisie, mais j'habite ici depuis un an." },
      { role: "A", text: "Super ! Et tu habites près d'ici ?" },
      { role: "B", text: "Oui, à dix minutes à pied. Et toi, tu travailles ici depuis longtemps ?" },
      { role: "A", text: "Depuis trois ans. Viens, je te montre le bureau." },
      { role: "B", text: "Merci, c'est très gentil !" },
      { role: "A", text: "Enchanté(e) de te connaître !" },
      { role: "B", text: "Moi aussi. À tout à l'heure !" },
],
  },
  {
    id: "e8-1-po-2",
    title: "Présenter un ami",
    context: "Vous êtes dans la rue avec un ami. Vous voyez une amie et vous la présentez.",
    roleA: AMI,
    roleB: { title: "L'autre ami", vous: "l'autre ami / l'autre amie" },
    lines: [
      { role: "A", text: "Regarde, c'est mon amie Rosa, là-bas !" },
      { role: "B", text: "La jeune femme rousse ? Elle est française ?" },
      { role: "A", text: "Non, elle est brésilienne. Elle est mariée et elle a un fils." },
      { role: "B", text: "Ah oui ? Il a quel âge, son fils ?" },
      { role: "A", text: "Il a un an. Il est adorable !" },
      { role: "B", text: "On invite Rosa à notre apéro samedi ?" },
      { role: "A", text: "Bonne idée ! Je lui demande tout de suite." },
      { role: "B", text: "Parfait, à samedi alors !" },
      { role: "A", text: "Ravi(e) de faire votre connaissance." },
      { role: "B", text: "Moi aussi. À bientôt !" },
],
  },
  {
    id: "e8-1-po-3",
    title: "Au restaurant",
    context: "Vous déjeunez dans un restaurant. Vous commandez votre repas.",
    roleA: { title: "Le serveur", vous: "le serveur / la serveuse" },
    roleB: { title: "Le client", vous: "le client / la cliente" },
    lines: [
      { role: "A", text: "Bonjour ! Vous avez choisi ?" },
      { role: "B", text: "Oui, je voudrais la quiche aux légumes, s'il vous plaît." },
      { role: "A", text: "Très bien. Et comme boisson ?" },
      { role: "B", text: "Une eau minérale, s'il vous plaît. Je suis végétarien, il n'y a pas de viande dans la quiche ?" },
      { role: "A", text: "Non, c'est une quiche aux légumes seulement." },
      { role: "B", text: "Parfait. Et comme dessert, qu'est-ce que vous avez ?" },
      { role: "A", text: "Une tarte aux pommes ou une glace." },
      { role: "B", text: "La tarte aux pommes, merci !" },
      { role: "A", text: "Ravi(e) de faire votre connaissance." },
      { role: "B", text: "Moi aussi. À bientôt !" },
],
  },
  {
    id: "e8-1-po-4",
    title: "Dans un magasin de vêtements",
    context: "C'est bientôt l'hiver. Vous cherchez un pull et une écharpe.",
    roleA: { title: "Le vendeur", vous: "le vendeur / la vendeuse" },
    roleB: { title: "Le client", vous: "le client / la cliente" },
    lines: [
      { role: "A", text: "Bonjour, je peux vous aider ?" },
      { role: "B", text: "Oui, je cherche un pull en laine pour l'hiver." },
      { role: "A", text: "Quelle taille faites-vous ?" },
      { role: "B", text: "Du M. Vous avez aussi des écharpes ?" },
      { role: "A", text: "Oui, les écharpes sont là-bas, à côté des bonnets." },
      { role: "B", text: "Super. Ce pull bleu, il coûte combien ?" },
      { role: "A", text: "Quarante francs. La cabine est au fond pour l'essayer." },
      { role: "B", text: "Merci, je vais l'essayer !" },
      { role: "A", text: "Ravi(e) de faire votre connaissance." },
      { role: "B", text: "Moi aussi. À bientôt !" },
],
  },
  {
    id: "e8-1-po-5",
    title: "Malade au téléphone",
    context: "Vous êtes malade et vous téléphonez à une collègue pour dire que vous ne venez pas travailler.",
    roleA: { title: "La collègue", vous: "le collègue / la collègue" },
    roleB: { title: "Le malade", vous: "le malade / la malade" },
    lines: [
      { role: "A", text: "Allô ? Tu es où ? On commence bientôt !" },
      { role: "B", text: "Je suis à la maison, je suis malade. Je ne peux pas venir aujourd'hui." },
      { role: "A", text: "Ah bon ! Qu'est-ce que tu as ?" },
      { role: "B", text: "J'ai mal à la gorge, je tousse et j'ai de la fièvre." },
      { role: "A", text: "Alors c'est peut-être la grippe. Tu dois voir un médecin !" },
      { role: "B", text: "Oui, j'ai un rendez-vous cet après-midi." },
      { role: "A", text: "Bien. Repose-toi et donne-moi des nouvelles !" },
      { role: "B", text: "Merci, tu es très sympa. À bientôt !" },
      { role: "A", text: "D'accord, je vous appelle si besoin." },
      { role: "B", text: "Très bien. Au revoir !" },
],
  },
  {
    id: "e8-1-po-6",
    title: "Acheter un billet de train",
    context: "Vous partez en voyage et vous achetez un billet à la gare.",
    roleA: { title: "L'employé", vous: "l'employé / l'employée" },
    roleB: { title: "Le voyageur", vous: "le voyageur / la voyageuse" },
    lines: [
      { role: "A", text: "Bonjour, je vous écoute." },
      { role: "B", text: "Bonjour, je voudrais un billet pour Lyon, s'il vous plaît." },
      { role: "A", text: "Pour quand ?" },
      { role: "B", text: "Pour samedi matin. Le trajet est direct ?" },
      { role: "A", text: "Non, il faut changer une fois. Le voyage dure trois heures." },
      { role: "B", text: "D'accord. Et le billet coûte combien ?" },
      { role: "A", text: "Cinquante francs en deuxième classe." },
      { role: "B", text: "Très bien, je le prends. Merci !" },
      { role: "A", text: "Ravi(e) de faire votre connaissance." },
      { role: "B", text: "Moi aussi. À bientôt !" },
],
  },
  {
    id: "e8-1-po-7",
    title: "Un problème dans l'appartement",
    context: "Il y a une fuite d'eau dans votre salle de bains. Vous appelez le propriétaire.",
    roleA: { title: "Le propriétaire", vous: "le propriétaire / la propriétaire" },
    roleB: { title: "Le locataire", vous: "le locataire / la locataire" },
    lines: [
      { role: "A", text: "Allô, bonjour ! Je vous écoute." },
      { role: "B", text: "Bonjour, c'est votre locataire. Il y a une fuite d'eau dans la salle de bains." },
      { role: "A", text: "Ah bon ? Depuis quand ?" },
      { role: "B", text: "Depuis ce matin. Et les toilettes sont bouchées aussi." },
      { role: "A", text: "D'accord, j'appelle le plombier tout de suite." },
      { role: "B", text: "Merci. Il peut venir aujourd'hui ?" },
      { role: "A", text: "Oui, cet après-midi vers 15 heures. Vous êtes à la maison ?" },
      { role: "B", text: "Oui, je suis là. Merci beaucoup !" },
      { role: "A", text: "Ravi(e) de faire votre connaissance." },
      { role: "B", text: "Moi aussi. À bientôt !" },
],
  },
  {
    id: "e8-1-po-8",
    title: "Le premier jour au restaurant",
    context: "Vous êtes le nouveau serveur. Une collègue vous explique la journée de travail.",
    roleA: { title: "La collègue", vous: "le collègue / la collègue" },
    roleB: { title: "Le nouveau serveur", vous: "le serveur / la serveuse" },
    lines: [
      { role: "A", text: "Bienvenue ! Tu es le nouveau serveur ?" },
      { role: "B", text: "Oui, bonjour ! On commence à quelle heure le matin ?" },
      { role: "A", text: "À 10 heures. D'abord, on prend un café avec les collègues." },
      { role: "B", text: "Et après, qu'est-ce qu'on fait ?" },
      { role: "A", text: "On prépare les tables pour le déjeuner." },
      { role: "B", text: "D'accord. Et le soir, on finit à quelle heure ?" },
      { role: "A", text: "Vers 23 heures. Mais le lundi, le restaurant est fermé." },
      { role: "B", text: "Parfait, merci pour les explications !" },
      { role: "A", text: "Enchanté(e) de te connaître !" },
      { role: "B", text: "Moi aussi. À tout à l'heure !" },
],
  },
  {
    id: "e8-1-po-9",
    title: "Inviter un ami à un festival",
    context: "Il y a un festival de musique ce week-end. Vous invitez un ami.",
    roleA: AMI,
    roleB: { title: "L'ami invité", vous: "l'ami / l'amie" },
    lines: [
      { role: "A", text: "Salut ! Tu fais quoi ce week-end ?" },
      { role: "B", text: "Rien de spécial. Pourquoi ?" },
      { role: "A", text: "Il y a un festival de musique au bord du lac. Tu viens avec moi ?" },
      { role: "B", text: "Bonne idée ! C'est quel jour ?" },
      { role: "A", text: "Samedi soir. Il y a des concerts à partir de 18 heures." },
      { role: "B", text: "Super ! On y va comment ?" },
      { role: "A", text: "En bus, il y a un arrêt juste devant l'entrée." },
      { role: "B", text: "Parfait, à samedi alors !" },
      { role: "A", text: "Parfait. Je vous remercie." },
      { role: "B", text: "De rien. Bonne journée !" },
],
  },
  {
    id: "e8-1-po-10",
    title: "Parler de ses vacances",
    context: "Vous discutez avec une amie de vos projets pour l'été.",
    roleA: AMI,
    roleB: { title: "L'autre ami", vous: "l'ami / l'amie" },
    lines: [
      { role: "A", text: "Alors, tu fais quoi cet été ?" },
      { role: "B", text: "En juillet, je pars deux semaines en Corse avec ma famille." },
      { role: "A", text: "Génial ! Vous allez à l'hôtel ?" },
      { role: "B", text: "Non, on fait du camping. Les enfants adorent ça." },
      { role: "A", text: "Et qu'est-ce que vous allez faire là-bas ?" },
      { role: "B", text: "De l'escalade et de la natation. Et toi, tu pars où ?" },
      { role: "A", text: "Je vais à un festival de musique à la montagne, quatre jours." },
      { role: "B", text: "Super ! Bonnes vacances alors !" },
      { role: "A", text: "Parfait, merci pour l'accueil." },
      { role: "B", text: "Avec plaisir. Bon séjour !" },
],
  },
];

/* ── Production écrite — consignes (A1 : 50 mots minimum) ─────────────────── */

const PE_MIN = 50;
const PE_MAX = 120;

export const E8_1_PE: ExpressPePrompt[] = [
  {
    id: "e8-1-pe-1",
    title: "Se présenter à un correspondant",
    situation: "Vous avez un nouveau correspondant français. Vous lui écrivez pour la première fois.",
    instruction: "Présentez-vous : votre nom, votre nationalité, votre famille et ce que vous aimez faire.",
    points: ["Qui vous êtes", "Votre famille", "Ce que vous aimez faire"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-2",
    title: "Décrire son logement",
    situation: "Vous venez d'emménager dans un nouvel appartement. Vous écrivez à un ami.",
    instruction: "Décrivez votre appartement : les pièces, le quartier et les voisins.",
    points: ["Les pièces de l'appartement", "Le quartier", "Les voisins"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-3",
    title: "Raconter sa journée de travail",
    situation: "Un ami vous demande comment se passe votre nouveau travail.",
    instruction: "Racontez votre journée de travail : les horaires, ce que vous faites et le jour de repos.",
    points: ["Les horaires", "Vos activités au travail", "Le jour de repos"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-4",
    title: "Message d'excuse — malade",
    situation: "Vous êtes malade et vous ne pouvez pas aller travailler aujourd'hui.",
    instruction: "Écrivez un message à votre chef : excusez-vous, décrivez vos symptômes et dites quand vous revenez.",
    points: ["L'excuse", "Vos symptômes", "La date de retour"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-5",
    title: "Raconter une journée en ville",
    situation: "Samedi, vous avez passé la journée en ville : magasins, restaurant, promenade.",
    instruction: "Racontez votre journée à un ami : où vous êtes allé(e), ce que vous avez acheté et ce que vous avez mangé.",
    points: ["Les magasins visités", "Vos achats", "Le repas"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-6",
    title: "Décrire sa famille",
    situation: "Votre correspondant veut connaître votre famille.",
    instruction: "Décrivez votre famille : qui sont les personnes, leur âge et leur travail ou leurs études.",
    points: ["Les personnes de la famille", "Leur âge", "Leur travail ou leurs études"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-7",
    title: "Invitation à une fête",
    situation: "Vous organisez un apéro chez vous samedi soir.",
    instruction: "Écrivez un message d'invitation à vos amis : le jour, l'heure, l'adresse et ce qu'il faut apporter.",
    points: ["Le jour et l'heure", "L'adresse", "Ce qu'il faut apporter"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-8",
    title: "Projets de vacances",
    situation: "Cet été, vous partez en vacances avec votre famille ou vos amis.",
    instruction: "Décrivez vos projets : la destination, le transport et les activités prévues.",
    points: ["La destination et la durée", "Le transport", "Les activités"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-9",
    title: "Raconter un voyage en train",
    situation: "Le week-end dernier, vous avez pris le train pour visiter une autre ville.",
    instruction: "Racontez votre voyage : l'achat du billet, le trajet et ce que vous avez fait là-bas.",
    points: ["L'achat du billet", "Le trajet", "Vos activités sur place"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e8-1-pe-10",
    title: "Décrire son quartier",
    situation: "Un ami veut venir habiter dans votre quartier et vous pose des questions.",
    instruction: "Décrivez votre quartier : les magasins, les transports et ce que vous aimez ici.",
    points: ["Les magasins", "Les transports", "Ce que vous aimez"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
];
