import { buildListeningAudio, type FixedQ } from "./express-lesson-factory";

const qs = (prefix: string, items: Omit<FixedQ, "id">[]): FixedQ[] =>
  items.map((item, i) => ({ ...item, id: `${prefix}-q${i + 1}` }));

export const E14_1_TRAINING: ReturnType<typeof buildListeningAudio>[] = [];

export const E14_1_EVAL = [
  buildListeningAudio({
    id: "e14-1-195",
    level: "A2",
    num: 195,
    transcript: `- Maman, nous venons de signer le bail pour le nouvel appartement !
- Dans le quartier de la gare. On emménage le mois prochain.`,
    questions: qs("195", [
      {
        textQ: "Que vient de signer la personne ?",
        text: ["Un bail", "Un contrat de travail", "Un chèque"],
        textC: 0,
        fillQ: "Nous venons de signer le _________ pour le nouvel appartement !",
        fill: "bail",
        vfQ: "La personne vient de signer un bail.",
        vfC: 0,
      },
      {
        textQ: "Pour quel logement le bail est-il signé ?",
        text: ["Un nouvel appartement", "Une nouvelle maison", "Un studio d'étudiant"],
        textC: 0,
        fillQ: "Nous avons signé le bail pour le nouvel _________ !",
        fill: "appartement",
        vfQ: "La famille a acheté l'appartement.",
        vfC: 1,
      },
      {
        textQ: "Où se trouve le nouvel appartement ?",
        text: ["Dans le quartier de la gare", "Près du parc", "À côté de la piscine"],
        textC: 0,
        img: ["train", "parc", "piscine"],
        imgC: 0,
        vfQ: "L'appartement se trouve dans le quartier de la gare.",
        vfC: 0,
      },
      {
        textQ: "Quand la famille va-t-elle emménager ?",
        text: ["Le mois prochain", "La semaine prochaine", "L'année prochaine"],
        textC: 0,
        fillQ: "On emménage le mois _________.",
        fill: "prochain",
        vfQ: "Ils emménagent la semaine prochaine.",
        vfC: 1,
      },
      {
        textQ: "À qui la personne annonce-t-elle la nouvelle ?",
        text: ["À sa mère", "À son frère", "À sa voisine"],
        textC: 0,
        fillQ: "_________, nous venons de signer le bail !",
        fill: "Maman",
        fillA: ["maman"],
        vfQ: "La personne annonce la nouvelle à sa mère.",
        vfC: 0,
      },
      {
        textQ: "Est-ce que le prix du loyer est indiqué ?",
        text: ["Non, il n'est pas indiqué", "Oui, 800 euros par mois", "Oui, 1 200 euros par mois"],
        textC: 0,
        vfQ: "Le montant du loyer est mentionné dans le dialogue.",
        vfC: 2,
      },
    ]),
  }),
  buildListeningAudio({
    id: "e14-1-196",
    level: "A2",
    num: 196,
    transcript: `- Dorothée, bienvenue. Je m'occupe d'une association de quartier.
- Pour s'engager, appelez la Maison des associations.`,
    questions: qs("196", [
      {
        textQ: "De quoi s'occupe la personne qui accueille Dorothée ?",
        text: ["D'une association de quartier", "D'un club de sport", "D'une école de musique"],
        textC: 0,
        fillQ: "Je m'occupe d'une _________ de quartier.",
        fill: "association",
        vfQ: "La personne s'occupe d'une association de quartier.",
        vfC: 0,
      },
      {
        textQ: "Comment peut-on s'engager dans l'association ?",
        text: ["Il faut téléphoner", "Il faut envoyer un courrier", "Il faut passer à la bibliothèque"],
        textC: 0,
        img: ["téléphone", "enveloppe", "bibliothèque"],
        imgC: 0,
        fillQ: "Pour s'engager, _________ la Maison des associations.",
        fill: "appelez",
        fillA: ["appeler"],
        vfQ: "Pour s'engager, il faut envoyer un courrier.",
        vfC: 1,
      },
      {
        textQ: "Qui faut-il appeler pour s'engager ?",
        text: ["La Maison des associations", "La mairie", "La bibliothèque"],
        textC: 0,
        vfQ: "Il faut contacter la Maison des associations.",
        vfC: 0,
      },
      {
        textQ: "Que dit la personne pour accueillir Dorothée ?",
        text: ["Bienvenue", "Bon voyage", "Bonne nuit"],
        textC: 0,
        fillQ: "Dorothée, _________ !",
        fill: "bienvenue",
        vfQ: "Dorothée est accueillie avec le mot « bienvenue ».",
        vfC: 0,
      },
      {
        textQ: "Est-ce que les activités de l'association sont décrites ?",
        text: ["Non, elles ne sont pas décrites", "Oui, il s'agit de sport", "Oui, il s'agit de cuisine"],
        textC: 0,
        vfQ: "Le dialogue décrit les activités de l'association.",
        vfC: 2,
      },
      {
        textQ: "Qui souhaite la bienvenue à Dorothée ?",
        text: ["La personne qui s'occupe de l'association", "Le maire du quartier", "Un voisin de Dorothée"],
        textC: 0,
        vfQ: "C'est le maire qui accueille Dorothée.",
        vfC: 1,
      },
    ]),
  }),
  buildListeningAudio({
    id: "e14-1-197",
    level: "A2",
    num: 197,
    transcript: `- Salut Louise ! Tu vas faire quoi ce week-end ?
- Un cours de cuisine, puis une promenade à vélo.`,
    questions: qs("197", [
      {
        textQ: "Quand Louise a-t-elle prévu ses activités ?",
        text: ["Ce week-end", "Ce soir", "Pendant les vacances"],
        textC: 0,
        fillQ: "Tu vas faire quoi ce _________ ?",
        fill: "week-end",
        fillA: ["weekend", "week end"],
        vfQ: "Les activités de Louise sont prévues pour le week-end.",
        vfC: 0,
      },
      {
        textQ: "Quel cours Louise va-t-elle suivre ?",
        text: ["Un cours de cuisine", "Un cours de danse", "Un cours de dessin"],
        textC: 0,
        img: ["cuisine", "danse", "dessin"],
        imgC: 0,
        fillQ: "Un cours de _________, puis une promenade à vélo.",
        fill: "cuisine",
        vfQ: "Louise va suivre un cours de danse.",
        vfC: 1,
      },
      {
        textQ: "Comment Louise fera-t-elle sa promenade ?",
        text: ["À vélo", "À pied", "En voiture"],
        textC: 0,
        img: ["vélo", "pied", "voiture"],
        imgC: 0,
        fillQ: "Puis une promenade à _________.",
        fill: "vélo",
        vfQ: "Louise fera une promenade à vélo.",
        vfC: 0,
      },
      {
        textQ: "Que fera Louise en premier ?",
        text: ["Le cours de cuisine", "La promenade à vélo", "Les courses au marché"],
        textC: 0,
        vfQ: "La promenade à vélo a lieu avant le cours de cuisine.",
        vfC: 1,
      },
      {
        textQ: "Combien d'activités Louise prévoit-elle ?",
        text: ["Deux", "Une", "Trois"],
        textC: 0,
        fillQ: "Louise prévoit _________ activités pour le week-end.",
        fill: "deux",
        fillA: ["2"],
        vfQ: "Louise prévoit deux activités pour le week-end.",
        vfC: 0,
      },
      {
        textQ: "Sait-on avec qui Louise fera sa promenade ?",
        text: ["Non, ce n'est pas précisé", "Oui, avec sa sœur", "Oui, avec un ami"],
        textC: 0,
        vfQ: "Louise fera sa promenade avec sa sœur.",
        vfC: 2,
      },
    ]),
  }),
  buildListeningAudio({
    id: "e14-1-198",
    level: "A2",
    num: 198,
    transcript: `- Catherine, salut ! Tu as bonne mine !
- Oui, je fais du sport et je mange mieux.`,
    questions: qs("198", [
      {
        textQ: "Quel compliment Catherine reçoit-elle ?",
        text: ["Elle a bonne mine", "Elle a une belle robe", "Elle a une jolie coiffure"],
        textC: 0,
        fillQ: "Catherine, salut ! Tu as bonne _________ !",
        fill: "mine",
        vfQ: "L'amie trouve que Catherine a bonne mine.",
        vfC: 0,
      },
      {
        textQ: "Que fait Catherine pour être en forme ?",
        text: ["Du sport", "Du théâtre", "De la peinture"],
        textC: 0,
        img: ["sport", "théâtre", "peinture"],
        imgC: 0,
        fillQ: "Oui, je fais du _________ et je mange mieux.",
        fill: "sport",
        vfQ: "Catherine fait du théâtre pour être en forme.",
        vfC: 1,
      },
      {
        textQ: "Comment Catherine mange-t-elle maintenant ?",
        text: ["Mieux qu'avant", "Moins bien qu'avant", "Comme avant"],
        textC: 0,
        fillQ: "Je fais du sport et je mange _________.",
        fill: "mieux",
        vfQ: "Catherine mange mieux qu'avant.",
        vfC: 0,
      },
      {
        textQ: "Combien de bonnes habitudes Catherine mentionne-t-elle ?",
        text: ["Deux", "Une", "Trois"],
        textC: 0,
        fillQ: "Catherine mentionne _________ bonnes habitudes.",
        fill: "deux",
        fillA: ["2"],
        vfQ: "Catherine mentionne trois bonnes habitudes.",
        vfC: 1,
      },
      {
        textQ: "Est-ce que Catherine confirme qu'elle va bien ?",
        text: ["Oui", "Non", "Elle ne répond pas"],
        textC: 0,
        vfQ: "Catherine répond « oui » au compliment.",
        vfC: 0,
      },
      {
        textQ: "Quel sport Catherine pratique-t-elle exactement ?",
        text: ["Ce n'est pas précisé", "La natation", "Le tennis"],
        textC: 0,
        vfQ: "Catherine fait de la natation.",
        vfC: 2,
      },
    ]),
  }),
  buildListeningAudio({
    id: "e14-1-199",
    level: "A2",
    num: 199,
    transcript: `- Dimitri ! J'ai enfin trouvé un CDI chez Bricomania !
- Bravo ! Tu commences lundi prochain.`,
    questions: qs("199", [
      {
        textQ: "Quelle bonne nouvelle la personne annonce-t-elle à Dimitri ?",
        text: ["Elle a trouvé un travail", "Elle a acheté une maison", "Elle a gagné une course"],
        textC: 0,
        img: ["travail", "maison", "course"],
        imgC: 0,
        vfQ: "La personne annonce qu'elle a trouvé un travail.",
        vfC: 0,
      },
      {
        textQ: "Quel type de contrat la personne a-t-elle trouvé ?",
        text: ["Un CDI", "Un CDD", "Un stage"],
        textC: 0,
        fillQ: "J'ai enfin trouvé un _________ chez Bricomania !",
        fill: "CDI",
        fillA: ["cdi"],
        vfQ: "La personne a trouvé un stage.",
        vfC: 1,
      },
      {
        textQ: "Comment Dimitri réagit-il à la nouvelle ?",
        text: ["Il dit « Bravo »", "Il est déçu", "Il ne répond pas"],
        textC: 0,
        fillQ: "_________ ! Tu commences lundi prochain.",
        fill: "Bravo",
        fillA: ["bravo"],
        vfQ: "Dimitri félicite la personne.",
        vfC: 0,
      },
      {
        textQ: "Quand commence le nouveau travail ?",
        text: ["Lundi prochain", "Mardi prochain", "Le mois prochain"],
        textC: 0,
        fillQ: "Tu commences _________ prochain.",
        fill: "lundi",
        vfQ: "Le travail commence mardi prochain.",
        vfC: 1,
      },
      {
        textQ: "Que montre le mot « enfin » dans l'annonce ?",
        text: ["La recherche a été longue", "Le travail est facile", "Le magasin est loin"],
        textC: 0,
        vfQ: "La personne cherchait un travail depuis longtemps.",
        vfC: 0,
      },
      {
        textQ: "Est-ce que le salaire du nouveau poste est mentionné ?",
        text: ["Non, il n'est pas mentionné", "Oui, 2 000 euros par mois", "Oui, le salaire minimum"],
        textC: 0,
        vfQ: "Le salaire du poste est mentionné dans le dialogue.",
        vfC: 2,
      },
    ]),
  }),
];
