import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_205 = `- Ah, il fait beau aujourd'hui ! On joue au tennis ?
- Ah non ! Je déteste le tennis ! On peut faire du VTT.
- Mais il fait trop chaud pour faire du vélo !!
- Mais non ! Il fait 20 °C, c'est parfait pour faire du vélo en montagne !
- Pff… je préfère faire de l'escalade.
- L'escalade au printemps ou en automne, d'accord ! Mais en été, avec le soleil, non merci !
- Alors faisons de la voile sur le lac ou louons un canoé-kayak !
- Écoute, aujourd'hui, moi je fais du vélo et demain, on fait ce que tu veux !
- Tu n'es pas sympa… Et puis regarde la météo, demain il pleut et il fait froid !`;

const POOL_205 = buildExpressPool("e7-2-205", [
  q({
    id: "205-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Mais", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Mais",
  }),
  q({
    id: "205-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Pff", "Marie", "Paul"],
    textC: 0,
    img: ["Pff", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Pff",
  }),
  q({
    id: "205-q3",
    format: "fill",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["20", "10 heures", "20 €"],
    textC: 0,
    img: ["20", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "Quel chiffre ou horaire est cité : _________.",
    fill: "20",
  }),
  q({
    id: "205-q4",
    format: "vf",
    textQ: "Ah, il fait beau aujourd'hui",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Ah, il fait beau aujourd'hui",
    vfC: 0,
  }),
  q({
    id: "205-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "205-q6",
    format: "vf",
    textQ: "On joue au tennis",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "On joue au tennis",
    vfC: 0,
  }),
  q({
    id: "205-q7",
    format: "vf",
    textQ: "Je déteste le tennis",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Je déteste le tennis",
    vfC: 0,
  }),
  q({
    id: "205-q8",
    format: "vf",
    textQ: "On peut faire du VTT",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "On peut faire du VTT",
    vfC: 0,
  })
]);

const TR_211 = `Et voici la météo de ce jour de printemps. À Paris, temps beau et chaud. À Bordeaux, nuages et vent. À Strasbourg, pluie et vent. À Nice, du soleil et 32 °C. Et enfin à Lille, 12 °C et des nuages.`;

const POOL_211 = buildExpressPool("e7-2-211", [
  q({
    id: "211-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Paris", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Paris",
  }),
  q({
    id: "211-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Bordeaux", "Marie", "Paul"],
    textC: 0,
    img: ["Bordeaux", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Bordeaux",
  }),
  q({
    id: "211-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Strasbourg", "Marie", "Paul"],
    textC: 0,
    img: ["Strasbourg", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Strasbourg",
  }),
  q({
    id: "211-q4",
    format: "vf",
    textQ: "32 est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "32 est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "211-q5",
    format: "text",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["12", "10 heures", "20 €"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "12",
  }),
  q({
    id: "211-q6",
    format: "vf",
    textQ: "Et voici la météo de ce jour de printemps",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Et voici la météo de ce jour de printemps",
    vfC: 0,
  }),
  q({
    id: "211-q7",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "211-q8",
    format: "vf",
    textQ: "À Paris, temps beau et chaud",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "À Paris, temps beau et chaud",
    vfC: 0,
  })
]);

const TR_212 = `Et maintenant, parlons des vacances d'hiver ! Il fait froid, il neige et les pistes ouvrent ce week-end dans les Alpes ! Préparez votre luge, vos skis ou votre surf !`;

const POOL_212 = buildExpressPool("e7-2-212", [
  q({
    id: "212-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Alpes", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Alpes",
  }),
  q({
    id: "212-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Préparez", "Marie", "Paul"],
    textC: 0,
    img: ["Préparez", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Préparez",
  }),
  q({
    id: "212-q3",
    format: "vf",
    textQ: "Et maintenant, parlons des vacances d'hiver",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Et maintenant, parlons des vacances d'hiver",
    vfC: 0,
  }),
  q({
    id: "212-q4",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "212-q5",
    format: "vf",
    textQ: "Il fait froid, il neige et les pistes ouvrent ce week-end dans les Alpes",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Il fait froid, il neige et les pistes ouvrent ce week-end dans les Alpes",
    vfC: 0,
  }),
  q({
    id: "212-q6",
    format: "vf",
    textQ: "Préparez votre luge, vos skis ou votre surf",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Préparez votre luge, vos skis ou votre surf",
    vfC: 0,
  })
]);

const TR_213 = `50 % des Français font du sport pendant les vacances d'été : natation, randonnée, vélo ou VTT. Les jeunes aiment faire du canoé-kayak. Les adultes font plutôt de la voile et de la natation.`;

const POOL_213 = buildExpressPool("e7-2-213", [
  q({
    id: "213-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Français", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Français",
  }),
  q({
    id: "213-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Les", "Marie", "Paul"],
    textC: 0,
    img: ["Les", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Les",
  }),
  q({
    id: "213-q3",
    format: "fill",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["50", "10 heures", "20 €"],
    textC: 0,
    img: ["50", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "Quel chiffre ou horaire est cité : _________.",
    fill: "50",
  }),
  q({
    id: "213-q4",
    format: "vf",
    textQ: "50 % des Français font du sport pendant les vacances d'été : natation, randonnée, vélo …",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "50 % des Français font du sport pendant les vacances d'été : natation, randonnée, vélo …",
    vfC: 0,
  }),
  q({
    id: "213-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "213-q6",
    format: "vf",
    textQ: "Les jeunes aiment faire du canoé-kayak",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Les jeunes aiment faire du canoé-kayak",
    vfC: 0,
  }),
  q({
    id: "213-q7",
    format: "vf",
    textQ: "Les adultes font plutôt de la voile et de la natation",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Les adultes font plutôt de la voile et de la natation",
    vfC: 0,
  })
]);

const TR_214 = `Allo Léa ? C'est maman. Écoute, pour notre week-end à la montagne, je réserve 6 activités : VTT pour Bertrand, tennis pour Tom et toi, canyoning pour Robin, voile pour papa et escalade pour moi. Ça te va ?`;

const POOL_214 = buildExpressPool("e7-2-214", [
  q({
    id: "214-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Léa", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Léa",
  }),
  q({
    id: "214-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Bertrand", "Marie", "Paul"],
    textC: 0,
    img: ["Bertrand", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Bertrand",
  }),
  q({
    id: "214-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Tom", "Marie", "Paul"],
    textC: 0,
    img: ["Tom", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Tom",
  }),
  q({
    id: "214-q4",
    format: "vf",
    textQ: "Écoute, pour notre week-end à la montagne, je réserve 6 activités : VTT pour Bertrand, …",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Écoute, pour notre week-end à la montagne, je réserve 6 activités : VTT pour Bertrand, …",
    vfC: 0,
  }),
  q({
    id: "214-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "214-q6",
    format: "image",
    textQ: "L'enregistrement contient-il un dialogue ?",
    text: ["Oui", "Non", "On ne sait pas"],
    textC: 0,
    img: ["Homme", "Femme", "Enfant"],
    imgC: 0,
    fillQ: "C'est un enregistrement _________.",
    fill: "oral",
    vfQ: "C'est un enregistrement audio.",
    vfC: 0,
  })
]);

const TR_215 = `- Bonjour madame, il ne fait pas très beau aujourd'hui et je voudrais savoir quelles activités vous proposez.
- Ce matin, il ne pleut pas et je peux vous proposer une sortie en canoé-kayak à 10 heures ou un cours de voile à 11 heures. Les deux activités durent 2 heures.
- Je peux vous proposer aussi un cours d'escalade à 11 heures. Il dure 2 heures aussi.
- Ah oui ! C'est bien l'escalade, non ?
- Oui c'est très bien, mais nous ne savons pas faire d'escalade !
- Il y a un cours pour les débutants, vous voulez vous inscrire ?
- Oui s'il vous plaît !`;

const POOL_215 = buildExpressPool("e7-2-215", [
  q({
    id: "215-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Les", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Les",
  }),
  q({
    id: "215-q2",
    format: "image",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["10", "10 heures", "20 €"],
    textC: 0,
    img: ["10", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "_________",
    fill: "10",
  }),
  q({
    id: "215-q3",
    format: "fill",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["11", "10 heures", "20 €"],
    textC: 0,
    img: ["11", "10 heures", "20 €"],
    imgC: 0,
    fillQ: "Quel chiffre ou horaire est cité : _________.",
    fill: "11",
  }),
  q({
    id: "215-q4",
    format: "vf",
    textQ: "Bonjour madame, il ne fait pas très beau aujourd'hui et je voudrais savoir quelles acti…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour madame, il ne fait pas très beau aujourd'hui et je voudrais savoir quelles acti…",
    vfC: 0,
  }),
  q({
    id: "215-q5",
    format: "vf",
    textQ: "Bonjour madame, il fait pas très beau aujourd'hui et je voudrais savoir quelles acti…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Bonjour madame, il fait pas très beau aujourd'hui et je voudrais savoir quelles acti…",
    vfC: 1,
  }),
  q({
    id: "215-q6",
    format: "vf",
    textQ: "Ce matin, il ne pleut pas et je peux vous proposer une sortie en canoé-kayak à 10 heure…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Ce matin, il ne pleut pas et je peux vous proposer une sortie en canoé-kayak à 10 heure…",
    vfC: 0,
  }),
  q({
    id: "215-q7",
    format: "vf",
    textQ: "Ce matin, il pleut pas et je peux vous proposer une sortie en canoé-kayak à 10 heure…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Ce matin, il pleut pas et je peux vous proposer une sortie en canoé-kayak à 10 heure…",
    vfC: 1,
  }),
  q({
    id: "215-q8",
    format: "vf",
    textQ: "Les deux activités durent 2 heures",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Les deux activités durent 2 heures",
    vfC: 0,
  })
]);

export const E7_2_TRAINING: ExpressListeningAudio[] = [
{
  id: "e7-2-205",
  audioSrc: A1(205),
  audioLabel: "Audio 205",
  transcript: TR_205,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_205,
  questionCount: 4,
},
{
  id: "e7-2-211",
  audioSrc: A1(211),
  audioLabel: "Audio 211",
  transcript: TR_211,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_211,
  questionCount: 4,
},
{
  id: "e7-2-212",
  audioSrc: A1(212),
  audioLabel: "Audio 212",
  transcript: TR_212,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_212,
  questionCount: 4,
},
{
  id: "e7-2-213",
  audioSrc: A1(213),
  audioLabel: "Audio 213",
  transcript: TR_213,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_213,
  questionCount: 4,
}
];

export const E7_2_EVAL: ExpressListeningAudio[] = [
{
  id: "e7-2-214",
  audioSrc: A1(214),
  audioLabel: "Audio 214",
  transcript: TR_214,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_214,
  questionCount: 4,
},
{
  id: "e7-2-215",
  audioSrc: A1(215),
  audioLabel: "Audio 215",
  transcript: TR_215,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_215,
  questionCount: 4,
}
];
