import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";
import type { ExpressListeningAudio } from "./express-e1-1-listening";
import { A1 } from "./express-lesson-factory";

function q(item: ExpressRawQ): ExpressRawQ { return item; }

const TR_182 = `- Bonjour madame, quelle est votre destination ?
- Bonjour, je vais à Bruxelles.
- Bien… le vol à destination de Bruxelles, départ 7 h 15… Votre passeport s'il vous plaît.
- J'ai ma carte d'identité. Et voici une copie de mon billet électronique.
- Très bien. Vous avez des bagages à enregistrer ?
- Non, j'ai seulement une valise cabine et mon sac à main.
- Voici votre carte d'embarquement. Vous avez le siège 28F.
- C'est bien côté hublot ?
- Oui. L'embarquement commence à 6 h 45.
- Je ne vois pas la porte d'embarquement sur la carte !
- C'est normal. La porte n'est pas encore indiquée. Vous devez regarder sur le tableau des départs.
- Merci monsieur !
- Bon séjour en Belgique !`;

const POOL_182 = buildExpressPool("e6-3-182", [
  q({
    id: "182-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Bruxelles", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Bruxelles",
  }),
  q({
    id: "182-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Bien", "Marie", "Paul"],
    textC: 0,
    img: ["Bien", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Bien",
  }),
  q({
    id: "182-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Votre", "Marie", "Paul"],
    textC: 0,
    img: ["Votre", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Votre",
  }),
  q({
    id: "182-q4",
    format: "vf",
    textQ: "7 h 15 est mentionné dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "7 h 15 est mentionné dans l'audio.",
    vfC: 0,
  }),
  q({
    id: "182-q5",
    format: "text",
    textQ: "Quel chiffre ou horaire est cité ?",
    text: ["6 h 45", "10 heures", "20 €"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "6 h 45",
  }),
  q({
    id: "182-q6",
    format: "vf",
    textQ: "Bonjour madame, quelle est votre destination",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour madame, quelle est votre destination",
    vfC: 0,
  }),
  q({
    id: "182-q7",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "182-q8",
    format: "vf",
    textQ: "Bonjour, je vais à Bruxelles",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour, je vais à Bruxelles",
    vfC: 0,
  })
]);

const TR_188 = `Mesdames et messieurs, votre attention s'il vous plaît. Les passagers du vol AF416 à destination de Porto sont invités à se présenter porte d'embarquement B6 avec leur passeport.`;

const POOL_188 = buildExpressPool("e6-3-188", [
  q({
    id: "188-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Mesdames", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Mesdames",
  }),
  q({
    id: "188-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Les", "Marie", "Paul"],
    textC: 0,
    img: ["Les", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Les",
  }),
  q({
    id: "188-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Porto", "Marie", "Paul"],
    textC: 0,
    img: ["Porto", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Porto",
  }),
  q({
    id: "188-q4",
    format: "vf",
    textQ: "Mesdames et messieurs, votre attention s'il vous plaît",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Mesdames et messieurs, votre attention s'il vous plaît",
    vfC: 0,
  }),
  q({
    id: "188-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "188-q6",
    format: "vf",
    textQ: "Les passagers du vol AF416 à destination de Porto sont invités à se présenter porte d'e…",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Les passagers du vol AF416 à destination de Porto sont invités à se présenter porte d'e…",
    vfC: 0,
  })
]);

const TR_189 = `- Bonjour, votre passeport s'il vous plaît. Quelle est votre destination ?
- Bonjour. Je vais aux États-Unis, un vol direct à destination de Boston.
- Vous avez un visa ?
- Oui bien sûr, voilà.
- Très bien. Bon vol.`;

const POOL_189 = buildExpressPool("e6-3-189", [
  q({
    id: "189-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["États-", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "États-",
  }),
  q({
    id: "189-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Unis", "Marie", "Paul"],
    textC: 0,
    img: ["Unis", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Unis",
  }),
  q({
    id: "189-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Boston", "Marie", "Paul"],
    textC: 0,
    img: ["Boston", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Boston",
  }),
  q({
    id: "189-q4",
    format: "vf",
    textQ: "Bonjour, votre passeport s'il vous plaît",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour, votre passeport s'il vous plaît",
    vfC: 0,
  }),
  q({
    id: "189-q5",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "189-q6",
    format: "vf",
    textQ: "Quelle est votre destination",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Quelle est votre destination",
    vfC: 0,
  }),
  q({
    id: "189-q7",
    format: "vf",
    textQ: "Je vais aux États-Unis, un vol direct à destination de Boston",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Je vais aux États-Unis, un vol direct à destination de Boston",
    vfC: 0,
  }),
  q({
    id: "189-q8",
    format: "vf",
    textQ: "Vous avez un visa",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Vous avez un visa",
    vfC: 0,
  })
]);

const TR_190 = `- Pardon monsieur, je ne trouve pas ma valise sur le tapis 4.
- Votre numéro de vol est le KL173 ?
- Oui. Je viens d'Amsterdam.
- Tous les bagages sont ici. Vous devez aller au service bagages.`;

const POOL_190 = buildExpressPool("e6-3-190", [
  q({
    id: "190-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Votre", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Votre",
  }),
  q({
    id: "190-q2",
    format: "image",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Amsterdam", "Marie", "Paul"],
    textC: 0,
    img: ["Amsterdam", "Marie", "Paul"],
    imgC: 0,
    fillQ: "_________",
    fill: "Amsterdam",
  }),
  q({
    id: "190-q3",
    format: "fill",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Tous", "Marie", "Paul"],
    textC: 0,
    img: ["Tous", "Marie", "Paul"],
    imgC: 0,
    fillQ: "Quel nom entendez-vous dans l'audio : _________.",
    fill: "Tous",
  }),
  q({
    id: "190-q4",
    format: "vf",
    textQ: "Pardon monsieur, je ne trouve pas ma valise sur le tapis 4",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Pardon monsieur, je ne trouve pas ma valise sur le tapis 4",
    vfC: 0,
  }),
  q({
    id: "190-q5",
    format: "vf",
    textQ: "Pardon monsieur, je trouve pas ma valise sur le tapis 4",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Pardon monsieur, je trouve pas ma valise sur le tapis 4",
    vfC: 1,
  }),
  q({
    id: "190-q6",
    format: "vf",
    textQ: "Votre numéro de vol est le KL173",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Votre numéro de vol est le KL173",
    vfC: 0,
  }),
  q({
    id: "190-q7",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "190-q8",
    format: "vf",
    textQ: "Je viens d'Amsterdam",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Je viens d'Amsterdam",
    vfC: 0,
  })
]);

const TR_191 = `- Chloé, tu as déjà ta carte d'embarquement ?
- Non, je dois aller au comptoir d'enregistrement. J'ai deux valises à enregistrer.
- Tu dois arriver à l'aéroport 2 heures avant le départ alors !`;

const POOL_191 = buildExpressPool("e6-3-191", [
  q({
    id: "191-q1",
    format: "text",
    textQ: "Quel nom entendez-vous dans l'audio ?",
    text: ["Chloé", "Marie", "Paul"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "_________",
    fill: "Chloé",
  }),
  q({
    id: "191-q2",
    format: "vf",
    textQ: "Chloé, tu as déjà ta carte d'embarquement",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Chloé, tu as déjà ta carte d'embarquement",
    vfC: 0,
  }),
  q({
    id: "191-q3",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "191-q4",
    format: "vf",
    textQ: "Non, je dois aller au comptoir d'enregistrement",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Non, je dois aller au comptoir d'enregistrement",
    vfC: 0,
  }),
  q({
    id: "191-q5",
    format: "vf",
    textQ: "J'ai deux valises à enregistrer",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "J'ai deux valises à enregistrer",
    vfC: 0,
  }),
  q({
    id: "191-q6",
    format: "vf",
    textQ: "Tu dois arriver à l'aéroport 2 heures avant le départ alors",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Tu dois arriver à l'aéroport 2 heures avant le départ alors",
    vfC: 0,
  })
]);

const TR_192 = `- Bonjour, votre passeport et votre carte d'embarquement s'il vous plaît.
- Voilà.
- C'est votre bagage monsieur ? Vous avez un ordinateur dans le sac ?
- Non, mon ordinateur est ici, avec ma trousse de toilette.
- C'est votre valise monsieur ? Vous pouvez l'ouvrir s'il vous plaît !
- Oui, bien sûr.
- C'est une bouteille d'eau ? C'est interdit, vous savez ?
- Ah oui, désolé !
- Très bien. Je vous souhaite un bon vol monsieur`;

const POOL_192 = buildExpressPool("e6-3-192", [
  q({
    id: "192-q1",
    format: "vf",
    textQ: "Bonjour, votre passeport et votre carte d'embarquement s'il vous plaît",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Bonjour, votre passeport et votre carte d'embarquement s'il vous plaît",
    vfC: 0,
  }),
  q({
    id: "192-q2",
    format: "vf",
    textQ: "Il n'y a aucune information dans l'audio.",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 1,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Faux",
    vfQ: "Il n'y a aucune information dans l'audio.",
    vfC: 1,
  }),
  q({
    id: "192-q3",
    format: "vf",
    textQ: "C'est votre bagage monsieur",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "C'est votre bagage monsieur",
    vfC: 0,
  }),
  q({
    id: "192-q4",
    format: "vf",
    textQ: "Vous avez un ordinateur dans le sac",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Vous avez un ordinateur dans le sac",
    vfC: 0,
  }),
  q({
    id: "192-q5",
    format: "vf",
    textQ: "Non, mon ordinateur est ici, avec ma trousse de toilette",
    text: ["Vrai", "Faux", "On ne sait pas"],
    textC: 0,
    img: ["Maison", "Téléphone", "Carte"],
    imgC: 0,
    fillQ: "Réponse : _________.",
    fill: "Vrai",
    vfQ: "Non, mon ordinateur est ici, avec ma trousse de toilette",
    vfC: 0,
  }),
  q({
    id: "192-q6",
    format: "image",
    textQ: "L'enregistrement contient-il un dialogue ?",
    text: ["Oui", "Non", "On ne sait pas"],
    textC: 0,
    img: ["Homme", "Femme", "Enfant"],
    imgC: 0,
    fillQ: "C'est un enregistrement _________.",
    fill: "oral",
    vfQ: "C'est un enregistrement audio.",
    vfC: 0,
  })
]);

export const E6_3_TRAINING: ExpressListeningAudio[] = [
{
  id: "e6-3-182",
  audioSrc: A1(182),
  audioLabel: "Audio 182",
  transcript: TR_182,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_182,
  questionCount: 4,
},
{
  id: "e6-3-188",
  audioSrc: A1(188),
  audioLabel: "Audio 188",
  transcript: TR_188,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_188,
  questionCount: 4,
},
{
  id: "e6-3-189",
  audioSrc: A1(189),
  audioLabel: "Audio 189",
  transcript: TR_189,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_189,
  questionCount: 4,
},
{
  id: "e6-3-190",
  audioSrc: A1(190),
  audioLabel: "Audio 190",
  transcript: TR_190,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_190,
  questionCount: 4,
}
];

export const E6_3_EVAL: ExpressListeningAudio[] = [
{
  id: "e6-3-191",
  audioSrc: A1(191),
  audioLabel: "Audio 191",
  transcript: TR_191,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_191,
  questionCount: 4,
},
{
  id: "e6-3-192",
  audioSrc: A1(192),
  audioLabel: "Audio 192",
  transcript: TR_192,
  instruction: "Écoutez l'enregistrement et répondez aux questions.",
  pool: POOL_192,
  questionCount: 4,
}
];
