import {
  readingPoolExercise,
  type CommunicationExercise,
  type ExpressPoDialogue,
  type ExpressPePrompt,
} from "./express-types";
import { buildExpressPool, type ExpressRawQ } from "./express-listening-helpers";

function q(item: ExpressRawQ): ExpressRawQ {
  return item;
}

/* ── Compréhension écrite — E1.3 Inviter à une fête ────────────────────────── */

const CE_TEXT = `Invitation — Fête d'anniversaire

Chers voisins,
Samedi 14 juin, nous organisons une fête pour les 30 ans de Karim. C'est un apéro dans le jardin, derrière l'immeuble.
La fête commence à 18 heures et finit vers 23 heures. Nous préparons un grand buffet : salades, pizzas et boissons fraîches.
Vous pouvez apporter quelque chose pour le dessert : un gâteau, une tarte ou une salade de fruits.
Attention : la fête est annulée s'il pleut. Merci de répondre avant mercredi.
À samedi !
Karim et Julie`;

const CE_POOL = buildExpressPool("e1-3-ce", [
  q({
    id: "ce-q1",
    textQ: "Qu'est-ce que Karim et Julie organisent ?",
    text: ["Une fête d'anniversaire", "Un pique-nique", "Un repas au restaurant"],
    textC: 0,
    img: ["anniversaire", "pique-nique", "restaurant"],
    imgC: 0,
    fillQ: "Nous organisons une _________ pour les 30 ans de Karim.",
    fill: "fête",
    fillA: ["fete"],
    vfQ: "La fête est pour un anniversaire.",
    vfC: 0,
  }),
  q({
    id: "ce-q2",
    textQ: "Où se passe la fête ?",
    text: ["Dans le jardin", "Dans un restaurant", "Dans la salle des fêtes"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "C'est un apéro dans le _________, derrière l'immeuble.",
    fill: "jardin",
    vfQ: "La fête se passe dans un restaurant.",
    vfC: 1,
  }),
  q({
    id: "ce-q3",
    textQ: "À quelle heure la fête commence-t-elle ?",
    text: ["À 18 heures", "À 20 heures", "À 23 heures"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "La fête commence à _________ heures.",
    fill: "18",
    fillA: ["dix-huit"],
    vfQ: "La fête finit vers 23 heures.",
    vfC: 0,
  }),
  q({
    id: "ce-q4",
    textQ: "Qu'est-ce que les invités peuvent apporter ?",
    text: ["Quelque chose pour le dessert", "Des salades", "Des boissons"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Vous pouvez apporter un gâteau, une tarte ou une salade de _________.",
    fill: "fruits",
    vfQ: "Les invités doivent apporter les boissons.",
    vfC: 1,
  }),
  q({
    id: "ce-q5",
    textQ: "Que se passe-t-il s'il pleut ?",
    text: ["La fête est annulée", "La fête est dans le salon", "La fête commence plus tard"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "La fête est _________ s'il pleut.",
    fill: "annulée",
    fillA: ["annulee"],
    vfQ: "S'il pleut, la fête est annulée.",
    vfC: 0,
  }),
  q({
    id: "ce-q6",
    textQ: "Quand faut-il répondre à l'invitation ?",
    text: ["Avant mercredi", "Avant samedi", "Avant dimanche"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "Merci de répondre avant _________.",
    fill: "mercredi",
    vfQ: "Il faut répondre avant vendredi.",
    vfC: 1,
  }),
  q({
    id: "ce-q7",
    textQ: "Quel anniversaire Karim fête-t-il ?",
    text: ["Ses 30 ans", "Ses 20 ans", "Ses 40 ans"],
    textC: 0,
    img: ["", "", ""],
    imgC: 0,
    fillQ: "C'est une fête pour les _________ ans de Karim.",
    fill: "30",
    fillA: ["trente"],
    vfQ: "Le message dit combien d'invités viennent à la fête.",
    vfC: 2,
  }),
  q({
    id: "ce-q8",
    textQ: "Qu'est-ce qu'il y a au buffet ?",
    text: [
      "Des salades, des pizzas et des boissons",
      "Des sandwichs et des gâteaux",
      "Du fromage et du pain",
    ],
    textC: 0,
    img: ["pizza", "sandwich", "fromage"],
    imgC: 0,
    fillQ: "Nous préparons un grand _________.",
    fill: "buffet",
    vfQ: "Il y a des pizzas au buffet.",
    vfC: 0,
  }),
]);

export const E1_3_CE: CommunicationExercise = readingPoolExercise({
  id: "e1-3-ce",
  readingText: CE_TEXT,
  questionPool: CE_POOL,
});

/* ── Production orale — dialogues à jouer (thème invitation) ───────────────── */

export const E1_3_PO: ExpressPoDialogue[] = [
  {
    id: "e1-3-po-1",
    title: "Inviter à son anniversaire",
    context: "C'est bientôt votre anniversaire. Vous invitez un ami à votre fête.",
    roleA: { title: "Celui qui invite", vous: "celui / celle qui invite" },
    roleB: { title: "L'ami invité", vous: "l'ami invité / l'amie invitée" },
    lines: [
      { role: "A", text: "Salut Léo ! Samedi, c'est mon anniversaire." },
      { role: "B", text: "Ah super ! Tu fais une fête ?" },
      { role: "A", text: "Oui, j'organise une fête chez moi. Je t'invite !" },
      { role: "B", text: "Avec plaisir ! C'est à quelle heure ?" },
      { role: "A", text: "À 19 heures. On mange, on danse, on écoute de la musique." },
      { role: "B", text: "Génial ! J'apporte quelque chose ?" },
      { role: "A", text: "Oui, une boisson si tu veux." },
      { role: "B", text: "D'accord ! À samedi alors !" },
    ],
  },
  {
    id: "e1-3-po-2",
    title: "Désolé, je ne suis pas libre",
    context: "Un ami vous invite à un apéro, mais vous n'êtes pas libre ce jour-là.",
    roleA: { title: "Celui qui invite", vous: "celui / celle qui invite" },
    roleB: { title: "L'ami occupé", vous: "l'ami occupé / l'amie occupée" },
    lines: [
      { role: "A", text: "Coucou ! Tu es libre vendredi soir ?" },
      { role: "B", text: "Vendredi ? Non, désolé, je ne suis pas libre." },
      { role: "A", text: "Dommage ! J'organise un apéro avec les amis du cours." },
      { role: "B", text: "Vendredi, je travaille jusqu'à 22 heures." },
      { role: "A", text: "Et samedi, tu peux ?" },
      { role: "B", text: "Oui, samedi je suis libre !" },
      { role: "A", text: "Alors on fait l'apéro samedi à 18 heures." },
      { role: "B", text: "Parfait, merci pour l'invitation !" },
    ],
  },
  {
    id: "e1-3-po-3",
    title: "L'heure et le lieu",
    context: "Vous êtes invité(e) à une fête et vous demandez les détails à un ami.",
    roleA: { title: "L'ami informé", vous: "l'ami / l'amie qui connaît les détails" },
    roleB: { title: "L'invité", vous: "l'invité / l'invitée" },
    lines: [
      { role: "A", text: "Tu viens à la fête de Nadia samedi ?" },
      { role: "B", text: "Oui ! Mais c'est où exactement ?" },
      { role: "A", text: "C'est chez elle, au 8 rue des Tilleuls." },
      { role: "B", text: "Et ça commence à quelle heure ?" },
      { role: "A", text: "À 20 heures. Mais tu peux arriver plus tard." },
      { role: "B", text: "Ça finit tard ?" },
      { role: "A", text: "Vers minuit, je pense." },
      { role: "B", text: "Super, alors à samedi !" },
    ],
  },
  {
    id: "e1-3-po-4",
    title: "J'apporte quelque chose ?",
    context: "Vous êtes invité(e) à un apéro et vous proposez d'apporter quelque chose.",
    roleA: { title: "L'hôtesse", vous: "l'hôte / l'hôtesse" },
    roleB: { title: "L'invité", vous: "l'invité / l'invitée" },
    lines: [
      { role: "A", text: "Je suis contente, tu viens à mon apéro dimanche !" },
      { role: "B", text: "Oui ! Qu'est-ce que j'apporte ?" },
      { role: "A", text: "Rien, c'est bon ! J'ai tout préparé." },
      { role: "B", text: "Mais si, je veux apporter quelque chose !" },
      { role: "A", text: "Bon, d'accord… Quelque chose pour le dessert alors." },
      { role: "B", text: "Un gâteau au chocolat, ça va ?" },
      { role: "A", text: "Oh oui, super idée ! Tout le monde adore ça." },
      { role: "B", text: "Parfait, je fais mon gâteau samedi soir." },
    ],
  },
  {
    id: "e1-3-po-5",
    title: "Inviter les voisins",
    context: "Vous organisez un apéro dans le jardin et vous invitez vos voisins.",
    roleA: { title: "Celui qui invite", vous: "le voisin / la voisine qui invite" },
    roleB: { title: "Le voisin invité", vous: "le voisin invité / la voisine invitée" },
    lines: [
      { role: "A", text: "Bonjour ! Samedi, nous organisons un apéro dans le jardin." },
      { role: "B", text: "Ah, c'est gentil ! C'est pour une occasion spéciale ?" },
      { role: "A", text: "Oui, les dix ans de notre fille. Vous êtes libres ?" },
      { role: "B", text: "Samedi… oui, nous sommes libres !" },
      { role: "A", text: "Super ! Venez avec vos enfants, bien sûr." },
      { role: "B", text: "Merci ! On apporte quelque chose à boire ?" },
      { role: "A", text: "Volontiers, un jus de fruits par exemple." },
      { role: "B", text: "D'accord ! À samedi, et merci pour l'invitation !" },
    ],
  },
  {
    id: "e1-3-po-6",
    title: "Confirmer par téléphone",
    context: "Vous téléphonez à un ami pour confirmer votre venue à sa fête.",
    roleA: { title: "Celle qui organise", vous: "celui / celle qui organise" },
    roleB: { title: "L'invité", vous: "l'invité / l'invitée" },
    lines: [
      { role: "A", text: "Allô Sami ? C'est Ines !" },
      { role: "B", text: "Salut Ines ! Ça va ?" },
      { role: "A", text: "Oui ! Je t'appelle pour la fête de vendredi. Tu viens ?" },
      { role: "B", text: "Oui, je viens ! Avec ma femme, c'est possible ?" },
      { role: "A", text: "Bien sûr ! Plus on est nombreux, mieux c'est." },
      { role: "B", text: "On arrive vers 19 heures 30, ça va ?" },
      { role: "A", text: "C'est parfait. N'oubliez pas : c'est au troisième étage !" },
      { role: "B", text: "Pas de problème. À vendredi !" },
    ],
  },
  {
    id: "e1-3-po-7",
    title: "Annuler : je suis malade",
    context: "Vous êtes malade et vous ne pouvez pas aller à la fête de ce soir.",
    roleA: { title: "L'invité malade", vous: "l'invité malade / l'invitée malade" },
    roleB: { title: "Celle qui organise", vous: "celui / celle qui organise" },
    lines: [
      { role: "A", text: "Allô Marie ? C'est Tom." },
      { role: "B", text: "Salut Tom ! Tu es prêt pour la fête de ce soir ?" },
      { role: "A", text: "Justement, non… Je suis désolé, je suis malade." },
      { role: "B", text: "Oh non ! Qu'est-ce que tu as ?" },
      { role: "A", text: "J'ai de la fièvre et mal à la gorge. Je reste à la maison." },
      { role: "B", text: "Repose-toi bien alors. C'est dommage !" },
      { role: "A", text: "Oui, vraiment désolé. Bonne fête à tous !" },
      { role: "B", text: "Merci. Soigne-toi bien et à bientôt !" },
    ],
  },
  {
    id: "e1-3-po-8",
    title: "La fête de départ",
    context: "Une collègue quitte l'entreprise. Vous organisez une petite fête avec un collègue.",
    roleA: { title: "Le premier collègue", vous: "le collègue / la collègue" },
    roleB: { title: "Le deuxième collègue", vous: "le collègue / la collègue" },
    lines: [
      { role: "A", text: "Tu sais, Paula quitte l'entreprise à la fin du mois." },
      { role: "B", text: "Oui, c'est triste ! On organise quelque chose ?" },
      { role: "A", text: "Oui, une petite fête jeudi à midi, à la cafétéria." },
      { role: "B", text: "Bonne idée ! Qu'est-ce qu'on prépare ?" },
      { role: "A", text: "Chacun apporte un plat. Moi, je fais une quiche." },
      { role: "B", text: "Alors moi, j'apporte une salade et du pain." },
      { role: "A", text: "Parfait. Et on achète un cadeau ensemble ?" },
      { role: "B", text: "Oui ! Je demande aux collègues demain." },
    ],
  },
  {
    id: "e1-3-po-9",
    title: "Organiser un pique-nique",
    context: "Vous organisez un pique-nique au bord du lac avec un ami.",
    roleA: { title: "Le premier ami", vous: "l'ami / l'amie" },
    roleB: { title: "Le deuxième ami", vous: "l'ami / l'amie" },
    lines: [
      { role: "A", text: "Dimanche, on fait un pique-nique au bord du lac ?" },
      { role: "B", text: "Oh oui, bonne idée ! On invite qui ?" },
      { role: "A", text: "Leila, Marco et leurs enfants. Ça te va ?" },
      { role: "B", text: "Parfait ! Qu'est-ce qu'on apporte ?" },
      { role: "A", text: "Moi, j'apporte des sandwichs et des fruits." },
      { role: "B", text: "Alors moi, je prends les boissons et un gâteau." },
      { role: "A", text: "Super. Rendez-vous à midi au parking du lac ?" },
      { role: "B", text: "D'accord ! Et s'il pleut, on fait ça chez moi." },
    ],
  },
  {
    id: "e1-3-po-10",
    title: "Répondre à une invitation",
    context: "Vous avez reçu une invitation pour samedi et vous en parlez avec un ami.",
    roleA: { title: "Le premier invité", vous: "l'invité / l'invitée" },
    roleB: { title: "Le deuxième invité", vous: "l'invité / l'invitée" },
    lines: [
      { role: "A", text: "Tu as reçu l'invitation de Hugo pour samedi ?" },
      { role: "B", text: "Oui ! C'est une fête pour son nouveau travail, non ?" },
      { role: "A", text: "Exactement. Tu vas répondre quoi ?" },
      { role: "B", text: "Je viens, bien sûr ! Et toi ?" },
      { role: "A", text: "Moi aussi. Il faut répondre avant jeudi." },
      { role: "B", text: "Ah oui ? Alors j'envoie un message ce soir." },
      { role: "A", text: "On peut y aller ensemble, si tu veux." },
      { role: "B", text: "Bonne idée ! Rendez-vous chez moi à 18 heures." },
    ],
  },
];

/* ── Production écrite — consignes (A1 : 50 mots minimum) ─────────────────── */

const PE_MIN = 50;
const PE_MAX = 120;

export const E1_3_PE: ExpressPePrompt[] = [
  {
    id: "e1-3-pe-1",
    title: "La carte d'invitation",
    situation: "Vous organisez une fête d'anniversaire et vous écrivez l'invitation pour vos amis.",
    instruction: "Écrivez l'invitation : dites l'occasion, le jour, l'heure et le lieu de la fête.",
    points: ["L'occasion de la fête", "Le jour et l'heure", "Le lieu"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-2",
    title: "Répondre : oui !",
    situation: "Un ami vous invite à sa fête samedi. Vous êtes libre et très content(e).",
    instruction: "Répondez au message : remerciez, confirmez votre venue et demandez ce que vous pouvez apporter.",
    points: ["Le remerciement", "La confirmation", "Une question sur ce qu'il faut apporter"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-3",
    title: "Désolé, pas libre",
    situation: "Une amie vous invite à un apéro vendredi, mais vous n'êtes pas libre.",
    instruction: "Répondez : excusez-vous, expliquez pourquoi vous n'êtes pas libre et proposez une autre date.",
    points: ["L'excuse", "La raison", "Une autre date"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-4",
    title: "Un mot pour les voisins",
    situation: "Vous organisez un apéro dans le jardin de l'immeuble et vous invitez tous les voisins.",
    instruction: "Écrivez le mot pour le hall : l'occasion, le jour et l'heure, et ce que les voisins peuvent apporter.",
    points: ["L'occasion", "Le jour et l'heure", "Ce qu'on peut apporter"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-5",
    title: "Le pique-nique",
    situation: "Vous organisez un pique-nique dimanche avec vos amis du cours de français.",
    instruction: "Écrivez un message au groupe : le lieu et l'heure, qui apporte quoi, et le plan s'il pleut.",
    points: ["Le lieu et l'heure", "Qui apporte quoi", "Le plan s'il pleut"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-6",
    title: "Demander des détails",
    situation: "Vous avez reçu une invitation, mais il manque l'heure et le lieu.",
    instruction: "Répondez au message : remerciez et posez trois questions sur la fête.",
    points: ["Le remerciement", "Une question sur l'heure et le lieu", "Une question sur ce qu'il faut apporter"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-7",
    title: "Annuler la fête",
    situation: "Vous êtes malade et vous devez annuler la fête prévue chez vous samedi.",
    instruction: "Écrivez un message à vos invités : annoncez l'annulation, expliquez pourquoi et proposez une nouvelle date.",
    points: ["L'annulation", "La raison", "Une nouvelle date"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-8",
    title: "Merci pour la fête",
    situation: "Hier, vous êtes allé(e) à une super fête chez une amie.",
    instruction: "Écrivez un message de remerciement : ce que vous avez aimé, un bon moment de la soirée et une invitation chez vous.",
    points: ["Le remerciement", "Un bon moment de la soirée", "Une invitation chez vous"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-9",
    title: "Organiser le buffet",
    situation: "Pour la fête de la classe, chaque personne apporte quelque chose pour le buffet.",
    instruction: "Écrivez un message au groupe : proposez une organisation, dites ce que vous apportez et posez une question.",
    points: ["L'organisation du buffet", "Ce que vous apportez", "Une question au groupe"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
  {
    id: "e1-3-pe-10",
    title: "Raconter la fête",
    situation: "Un ami n'a pas pu venir à la fête de samedi. Il veut tout savoir.",
    instruction: "Racontez la fête : où c'était, qui était là et ce que vous avez mangé et fait.",
    points: ["Le lieu", "Les invités", "Ce que vous avez mangé et fait"],
    minWords: PE_MIN,
    maxWords: PE_MAX,
  },
];
