export type OralSituation = {
  id: string;
  level: "base" | "moyen";
  image: string;
  alt: string;
  imageDescription: string;
  dialogueContext: string;
  dialoguePrompts: string[];
};

const ORAL_SITUATIONS: OralSituation[] = [
  // ——— A1 (base) ———
  {
    id: "a1-ecole",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-l-ecole.webp",
    alt: "À l'école",
    imageDescription: "Un adulte parle avec un professeur à l'école.",
    dialogueContext: "Vous allez à l'école pour parler d'un problème simple. Vous saluez et posez une question.",
    dialoguePrompts: ["Bonjour, qu'est-ce que je peux faire pour vous ?", "Votre enfant est dans quelle classe ?", "Quel est le problème ?", "Vous avez une pièce d'identité ?"],
  },
  {
    id: "a1-hotel",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-l-hotel.webp",
    alt: "À l'hôtel",
    imageDescription: "Une personne arrive à la réception d'un hôtel.",
    dialogueContext: "Vous réservez une chambre à l'hôtel. Vous dites votre nom et demandez le prix.",
    dialoguePrompts: ["Bonjour, vous avez une réservation ?", "Pour combien de nuits ?", "Vous voulez une chambre pour combien de personnes ?", "Vous payez comment ?"],
  },
  {
    id: "a1-bibliotheque",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-la-bibliotheque.webp",
    alt: "À la bibliothèque",
    imageDescription: "Une personne cherche un livre à la bibliothèque.",
    dialogueContext: "Vous allez à la bibliothèque pour prendre un livre. Vous demandez où se trouvent les livres.",
    dialoguePrompts: ["Bonjour, je peux vous aider ?", "Quel type de livre cherchez-vous ?", "Avez-vous une carte de bibliothèque ?", "Vous savez jusqu'à quand vous pouvez garder le livre ?"],
  },
  {
    id: "a1-boucherie",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-la-boucherie.webp",
    alt: "À la boucherie",
    imageDescription: "Un client commande de la viande à la boucherie.",
    dialogueContext: "Vous allez à la boucherie. Vous demandez un morceau de viande et son prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous désirez ?", "Quelle quantité voulez-vous ?", "C'est pour cuisiner comment ?", "Vous payez comment ?"],
  },
  {
    id: "a1-boulangerie",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-la-boulangerie.webp",
    alt: "À la boulangerie",
    imageDescription: "Un client achète du pain à la boulangerie.",
    dialogueContext: "Vous allez à la boulangerie acheter du pain. Vous demandez le prix et payez.",
    dialoguePrompts: ["Bonjour, qu'est-ce qu'il vous faut ?", "Vous voulez quel type de pain ?", "C'est pour combien de personnes ?", "Vous payez en espèces ?"],
  },
  {
    id: "a1-gare",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-la-gare.webp",
    alt: "À la gare",
    imageDescription: "Un voyageur demande un billet à la gare.",
    dialogueContext: "Vous êtes à la gare. Vous achetez un billet simple et demandez le quai.",
    dialoguePrompts: ["Bonjour, où voulez-vous aller ?", "Un aller simple ou aller-retour ?", "À quelle heure voulez-vous partir ?", "Votre billet, s'il vous plaît."],
  },
  {
    id: "a1-poste",
    level: "base",
    image: "/expression/po/A1/PO.A1_A-la-poste.webp",
    alt: "À la poste",
    imageDescription: "Une personne envoie un colis à la poste.",
    dialogueContext: "Vous allez à la poste pour envoyer une lettre ou un colis. Vous demandez le prix.",
    dialoguePrompts: ["Bonjour, que puis-je faire pour vous ?", "C'est une lettre ou un colis ?", "Quelle est la destination ?", "Vous voulez un reçu ?"],
  },
  {
    id: "a1-accident-velo",
    level: "base",
    image: "/expression/po/A1/PO.A1_Accident-velo.webp",
    alt: "Accident de vélo",
    imageDescription: "Une personne est tombée de son vélo.",
    dialogueContext: "Vous avez eu un petit accident avec votre vélo. Vous expliquez ce qui s'est passé.",
    dialoguePrompts: ["Qu'est-ce qui s'est passé ?", "Vous êtes blessé ?", "Où avez-vous mal ?", "Voulez-vous appeler les secours ?"],
  },
  {
    id: "a1-arret-bus",
    level: "base",
    image: "/expression/po/A1/PO.A1_Arret-de-bus.webp",
    alt: "À l'arrêt de bus",
    imageDescription: "Des personnes attendent le bus à un arrêt.",
    dialogueContext: "Vous attendez le bus. Vous demandez à quelqu'un quel bus prendre pour aller quelque part.",
    dialoguePrompts: ["Excusez-moi, quel bus va au centre-ville ?", "C'est loin d'ici ?", "Il passe souvent ?", "Merci beaucoup !"],
  },
  {
    id: "a1-cafe",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-cafe.webp",
    alt: "Au café",
    imageDescription: "Un client commande au café.",
    dialogueContext: "Vous entrez dans un café. Vous commandez une boisson et payez.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous prenez ?", "Avec du lait ou du sucre ?", "Vous consommez ici ou à emporter ?", "Ça fait combien ?"],
  },
  {
    id: "a1-cinema",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-cinema.webp",
    alt: "Au cinéma",
    imageDescription: "Une personne achète un ticket au cinéma.",
    dialogueContext: "Vous allez au cinéma. Vous achetez une place et demandez l'horaire du film.",
    dialoguePrompts: ["Bonjour, quel film vous intéresse ?", "Pour quelle heure ?", "Combien de places ?", "Vous avez une carte de réduction ?"],
  },
  {
    id: "a1-commissariat",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-commissariat.webp",
    alt: "Au commissariat",
    imageDescription: "Une personne parle à un agent de police au commissariat.",
    dialogueContext: "Vous avez perdu quelque chose. Vous allez au commissariat pour le déclarer.",
    dialoguePrompts: ["Bonjour, que voulez-vous signaler ?", "Qu'avez-vous perdu ?", "Où et quand l'avez-vous perdu ?", "Votre nom et adresse, s'il vous plaît ?"],
  },
  {
    id: "a1-marche",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-marche.webp",
    alt: "Au marché",
    imageDescription: "Une personne achète des légumes au marché.",
    dialogueContext: "Vous êtes au marché. Vous achetez des fruits ou des légumes et demandez le prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce qu'il vous faut ?", "Combien de kilos ?", "Vous voulez aussi des tomates ?", "C'est tout ?"],
  },
  {
    id: "a1-restaurant",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-restaurant.webp",
    alt: "Au restaurant",
    imageDescription: "Un client commande un repas au restaurant.",
    dialogueContext: "Vous êtes au restaurant. Vous regardez le menu et commandez votre repas.",
    dialoguePrompts: ["Bonjour, vous avez choisi ?", "Qu'est-ce que vous prenez comme plat principal ?", "Et comme boisson ?", "Vous voulez un dessert ?"],
  },
  {
    id: "a1-urgence",
    level: "base",
    image: "/expression/po/A1/PO.A1_Au-urgence.webp",
    alt: "Aux urgences",
    imageDescription: "Une personne arrive aux urgences de l'hôpital.",
    dialogueContext: "Vous allez aux urgences car vous avez mal. Vous expliquez votre problème.",
    dialoguePrompts: ["Qu'est-ce qui ne va pas ?", "Depuis quand avez-vous mal ?", "Vous avez de la fièvre ?", "Avez-vous votre carte d'assurance ?"],
  },
  {
    id: "a1-coiffeur",
    level: "base",
    image: "/expression/po/A1/PO.A1_Chez-le-coiffeur.webp",
    alt: "Chez le coiffeur",
    imageDescription: "Une personne chez le coiffeur pour une coupe simple.",
    dialogueContext: "Vous allez chez le coiffeur. Vous demandez une coupe simple.",
    dialoguePrompts: ["Bonjour, qu'est-ce que je vous fais ?", "Vous voulez couper combien ?", "Vous voulez aussi un shampoing ?", "C'est tout ce que vous voulez ?"],
  },
  {
    id: "a1-docteur",
    level: "base",
    image: "/expression/po/A1/PO.A1_Chez-le-docteur.webp",
    alt: "Chez le docteur",
    imageDescription: "Un patient consulte un médecin.",
    dialogueContext: "Vous n'êtes pas bien. Vous allez chez le docteur et expliquez vos symptômes simples.",
    dialoguePrompts: ["Bonjour, qu'est-ce qui ne va pas ?", "Où avez-vous mal ?", "Depuis quand ?", "Vous avez de la fièvre ?"],
  },
  {
    id: "a1-pediatre",
    level: "base",
    image: "/expression/po/A1/PO.A1_Chez-le-pediatre.webp",
    alt: "Chez le pédiatre",
    imageDescription: "Un parent avec son enfant chez le pédiatre.",
    dialogueContext: "Votre enfant est malade. Vous allez chez le pédiatre et décrivez les symptômes.",
    dialoguePrompts: ["Bonjour, qu'est-ce qui ne va pas chez votre enfant ?", "Quel âge a-t-il ?", "Il a de la fièvre ?", "Depuis combien de temps est-il malade ?"],
  },
  {
    id: "a1-controle-train",
    level: "base",
    image: "/expression/po/A1/PO.A1_Controle-train.webp",
    alt: "Contrôle dans le train",
    imageDescription: "Un contrôleur vérifie les billets dans le train.",
    dialogueContext: "Vous êtes dans le train. Le contrôleur vérifie votre billet.",
    dialoguePrompts: ["Votre billet, s'il vous plaît.", "Où allez-vous ?", "Vous avez un abonnement ?", "Merci, bon voyage."],
  },
  {
    id: "a1-coupure-courant",
    level: "base",
    image: "/expression/po/A1/PO.A1_Coupure-courant.webp",
    alt: "Coupure de courant",
    imageDescription: "Une personne téléphone pour signaler une panne d'électricité.",
    dialogueContext: "Il n'y a plus d'électricité chez vous. Vous téléphonez pour signaler la panne.",
    dialoguePrompts: ["Allô, bonjour. Quel est votre problème ?", "Quelle est votre adresse ?", "Depuis combien de temps n'avez-vous plus d'électricité ?", "D'autres voisins ont le même problème ?"],
  },
  {
    id: "a1-fuite-eau",
    level: "base",
    image: "/expression/po/A1/PO.A1_Fuite-d-eau.webp",
    alt: "Fuite d'eau",
    imageDescription: "Il y a une fuite d'eau dans un appartement.",
    dialogueContext: "Il y a une fuite d'eau chez vous. Vous téléphonez pour demander de l'aide.",
    dialoguePrompts: ["Bonjour, que se passe-t-il ?", "Où est la fuite ?", "Avez-vous fermé l'eau ?", "À quelle adresse êtes-vous ?"],
  },
  {
    id: "a1-inscription-club",
    level: "base",
    image: "/expression/po/A1/PO.A1_Inscription-club.webp",
    alt: "Inscription à un club",
    imageDescription: "Une personne s'inscrit dans un club de sport ou de loisirs.",
    dialogueContext: "Vous voulez vous inscrire dans un club. Vous demandez les informations de base.",
    dialoguePrompts: ["Bonjour, quelle activité vous intéresse ?", "Quel jour êtes-vous libre ?", "Vous avez déjà fait cette activité ?", "Il faut apporter quelque chose ?"],
  },
  {
    id: "a1-magasin-chaussure",
    level: "base",
    image: "/expression/po/A1/PO.A1_Magasin-chaussure.webp",
    alt: "Magasin de chaussures",
    imageDescription: "Un client essaie des chaussures dans un magasin.",
    dialogueContext: "Vous cherchez des chaussures. Vous demandez votre pointure et essayez une paire.",
    dialoguePrompts: ["Bonjour, je peux vous aider ?", "Quelle est votre pointure ?", "Vous voulez quelle couleur ?", "Est-ce que vous voulez les essayer ?"],
  },
  {
    id: "a1-magasin-vetement",
    level: "base",
    image: "/expression/po/A1/PO.A1_Magasin-vetement.webp",
    alt: "Magasin de vêtements",
    imageDescription: "Une personne choisit des vêtements dans un magasin.",
    dialogueContext: "Vous cherchez un vêtement. Vous demandez votre taille et le prix.",
    dialoguePrompts: ["Bonjour, vous cherchez quelque chose ?", "Quelle taille faites-vous ?", "Quelle couleur vous plaît ?", "Vous voulez l'essayer ?"],
  },
  {
    id: "a1-mot-de-passe",
    level: "base",
    image: "/expression/po/A1/PO.A1_Mot-de-passe-oublie.webp",
    alt: "Mot de passe oublié",
    imageDescription: "Une personne demande de l'aide pour un mot de passe oublié.",
    dialogueContext: "Vous avez oublié votre mot de passe. Vous téléphonez pour demander de l'aide.",
    dialoguePrompts: ["Allô, bonjour. C'est pour quel service ?", "Quel est votre nom d'utilisateur ?", "Vous voulez réinitialiser votre mot de passe ?", "Vous avez reçu un code par SMS ?"],
  },
  {
    id: "a1-rendez-vous",
    level: "base",
    image: "/expression/po/A1/PO.A1_Prendre-rendez-vous.webp",
    alt: "Prendre rendez-vous",
    imageDescription: "Une personne téléphone pour prendre un rendez-vous.",
    dialogueContext: "Vous téléphonez pour prendre un rendez-vous simple. Vous donnez votre nom et choisissez un jour.",
    dialoguePrompts: ["Bonjour, c'est pour un rendez-vous ?", "Quel est votre nom ?", "Vous êtes disponible quel jour ?", "À quelle heure ?"],
  },
  {
    id: "a1-logement",
    level: "base",
    image: "/expression/po/A1/PO.A1_Recherche-logement.webp",
    alt: "Recherche de logement",
    imageDescription: "Une personne cherche un appartement.",
    dialogueContext: "Vous cherchez un appartement. Vous posez des questions simples sur le loyer et la taille.",
    dialoguePrompts: ["Bonjour, vous cherchez quel type de logement ?", "Combien de pièces voulez-vous ?", "Quel loyer maximum pouvez-vous payer ?", "Quand pouvez-vous visiter ?"],
  },
  {
    id: "a1-permis",
    level: "base",
    image: "/expression/po/A1/PO.A1_Renouveller-permis.webp",
    alt: "Renouveler le permis",
    imageDescription: "Une personne renouvelle son permis de séjour.",
    dialogueContext: "Vous devez renouveler votre permis. Vous demandez les documents nécessaires.",
    dialoguePrompts: ["Bonjour, qu'est-ce que je peux faire pour vous ?", "Votre permis est valable jusqu'à quand ?", "Avez-vous vos documents d'identité ?", "Vous devez prendre un rendez-vous."],
  },
  {
    id: "a1-telephone-docteur",
    level: "base",
    image: "/expression/po/A1/PO.A1_Telephone-docteur.webp",
    alt: "Téléphone au docteur",
    imageDescription: "Une personne téléphone au cabinet médical.",
    dialogueContext: "Vous téléphonez chez le docteur car vous êtes malade. Vous expliquez votre problème.",
    dialoguePrompts: ["Cabinet médical, bonjour.", "Qu'est-ce qui ne va pas ?", "Depuis quand avez-vous ces symptômes ?", "Vous pouvez venir aujourd'hui ?"],
  },
  {
    id: "a1-hopital",
    level: "base",
    image: "/expression/po/A1/PO.A1_Visite-hopital.webp",
    alt: "Visite à l'hôpital",
    imageDescription: "Une personne visite quelqu'un à l'hôpital.",
    dialogueContext: "Vous venez voir quelqu'un à l'hôpital. Vous demandez où se trouve la chambre.",
    dialoguePrompts: ["Bonjour, vous venez pour qui ?", "Quelle est votre relation avec le patient ?", "Avez-vous une pièce d'identité ?", "La chambre est au 3e étage."],
  },

  // ——— A2-B1 (moyen et avancé) ———
  {
    id: "medecin",
    level: "moyen",
    image: "/expression/po/A2-B1/PO-Medecin.webp",
    alt: "Une consultation chez le médecin",
    imageDescription: "Une personne consulte un médecin dans son cabinet.",
    dialogueContext: "Vous ne vous sentez pas bien. Vous consultez un médecin et vous décrivez vos symptômes, leur durée et les médicaments que vous prenez.",
    dialoguePrompts: ["Bonjour, qu'est-ce qui vous amène ?", "Depuis quand avez-vous ces symptômes ?", "Avez-vous de la fièvre ou des douleurs ?", "Prenez-vous déjà un médicament ?"],
  },
  {
    id: "accident",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Accident.webp",
    alt: "Un accident de la circulation",
    imageDescription: "Un accident vient de se produire dans la rue.",
    dialogueContext: "Vous avez été témoin d'un accident. Vous téléphonez aux secours et vous expliquez le lieu, ce qui s'est passé et l'état des personnes.",
    dialoguePrompts: ["Services d'urgence, que s'est-il passé ?", "Où se trouve exactement l'accident ?", "Combien de personnes sont blessées ?", "La circulation est-elle bloquée ?"],
  },
  {
    id: "bibliotheque",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Bibliotheque.webp",
    alt: "Une bibliothèque",
    imageDescription: "Des personnes cherchent et consultent des livres dans une bibliothèque.",
    dialogueContext: "Vous souhaitez vous inscrire à la bibliothèque. Vous demandez les conditions, les horaires et la durée des prêts.",
    dialoguePrompts: ["Bonjour, que puis-je faire pour vous ?", "Habitez-vous dans la commune ?", "Quels types de documents voulez-vous emprunter ?", "Avez-vous besoin d'informations sur nos horaires ?"],
  },
  {
    id: "boucherie",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Boucherie.webp",
    alt: "Une boucherie",
    imageDescription: "Un client commande des produits dans une boucherie.",
    dialogueContext: "Vous préparez un repas et vous allez à la boucherie. Vous demandez conseil sur la viande, la quantité, le prix et la préparation.",
    dialoguePrompts: ["Bonjour, qu'est-ce que je vous sers ?", "Pour combien de personnes cuisinez-vous ?", "Vous préférez une viande à cuire rapidement ?", "Est-ce que je vous la prépare en tranches ?"],
  },
  {
    id: "boulangerie",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Boulangerie.webp",
    alt: "Une boulangerie",
    imageDescription: "Une cliente choisit du pain et des pâtisseries dans une boulangerie.",
    dialogueContext: "Vous organisez un petit déjeuner pour plusieurs personnes. Vous commandez du pain et des viennoiseries et vous demandez les prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous désirez ?", "Combien de personnes serez-vous ?", "Voulez-vous aussi des croissants ?", "Vous payez par carte ou en espèces ?"],
  },
  {
    id: "bus",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Bus.webp",
    alt: "Un arrêt de bus",
    imageDescription: "Des voyageurs attendent un bus à un arrêt.",
    dialogueContext: "Vous devez vous rendre dans un quartier que vous ne connaissez pas. Vous demandez au conducteur le trajet, l'arrêt et le prix du billet.",
    dialoguePrompts: ["Bonjour, où souhaitez-vous aller ?", "Avez-vous déjà un billet ?", "Voulez-vous un aller simple ou un aller-retour ?", "Savez-vous à quel arrêt descendre ?"],
  },
  {
    id: "cafe",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Cafe.webp",
    alt: "Un café",
    imageDescription: "Des clients prennent une boisson dans un café.",
    dialogueContext: "Vous entrez dans un café et vous commandez une boisson et quelque chose à manger. Vous demandez aussi le prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous prenez ?", "Vous désirez manger quelque chose ?", "Vous consommez ici ou à emporter ?", "Puis-je vous apporter autre chose ?"],
  },
  {
    id: "chaussure",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Chaussure.webp",
    alt: "Un magasin de chaussures",
    imageDescription: "Une personne essaie des chaussures dans un magasin.",
    dialogueContext: "Vous cherchez des chaussures. Vous précisez votre pointure, votre budget et l'usage prévu, puis vous demandez à essayer un modèle.",
    dialoguePrompts: ["Bonjour, quel type de chaussures cherchez-vous ?", "Quelle est votre pointure ?", "Quel est votre budget ?", "Voulez-vous essayer cette paire ?"],
  },
  {
    id: "cinema",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Cinema.webp",
    alt: "Le guichet d'un cinéma",
    imageDescription: "Des personnes choisissent un film au cinéma.",
    dialogueContext: "Vous êtes en Suisse et vous voulez voir un film. Au cinéma, vous demandez au vendeur des renseignements sur les films du moment, leur genre, leur durée, les horaires et le prix.",
    dialoguePrompts: ["Bonjour, quel genre de film souhaitez-vous voir ?", "Préférez-vous un film en français ou en version originale ?", "À quelle heure voulez-vous commencer la séance ?", "Bénéficiez-vous d'une réduction ?"],
  },
  {
    id: "club",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Club.webp",
    alt: "Un club de loisirs",
    imageDescription: "Des personnes participent à une activité dans un club.",
    dialogueContext: "Vous souhaitez rejoindre un club. Vous demandez quelles activités sont proposées, les horaires, le matériel nécessaire et le prix de l'inscription.",
    dialoguePrompts: ["Bonjour, quelle activité vous intéresse ?", "Avez-vous déjà pratiqué cette activité ?", "Quels jours êtes-vous disponible ?", "Souhaitez-vous faire une séance d'essai ?"],
  },
  {
    id: "coiffeur",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Coiffeur.webp",
    alt: "Un salon de coiffure",
    imageDescription: "Une cliente explique la coupe souhaitée à une coiffeuse.",
    dialogueContext: "Vous allez chez le coiffeur. Vous décrivez la coupe souhaitée et vous demandez la durée et le prix du service.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous souhaitez faire aujourd'hui ?", "Quelle longueur voulez-vous garder ?", "Voulez-vous aussi un shampoing ?", "Avez-vous une heure à laquelle vous devez partir ?"],
  },
  {
    id: "ecole",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Ecole.webp",
    alt: "L'accueil d'une école",
    imageDescription: "Un adulte demande des renseignements à l'accueil d'une école.",
    dialogueContext: "Vous voulez inscrire votre enfant dans une école. Vous demandez les documents nécessaires, les horaires et l'organisation des cours.",
    dialoguePrompts: ["Bonjour, pour quelle classe souhaitez-vous une inscription ?", "Votre enfant était-il déjà scolarisé en Suisse ?", "Avez-vous apporté ses documents ?", "Avez-vous besoin d'un accueil parascolaire ?"],
  },
  {
    id: "fuite",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Fuite.webp",
    alt: "Une fuite d'eau dans un logement",
    imageDescription: "Une fuite d'eau provoque des dégâts dans un logement.",
    dialogueContext: "Vous constatez une fuite d'eau chez vous. Vous appelez la régie ou un plombier et vous décrivez l'urgence et les dégâts.",
    dialoguePrompts: ["Bonjour, où se trouve la fuite ?", "Depuis quand l'eau coule-t-elle ?", "Avez-vous fermé l'arrivée d'eau ?", "Y a-t-il des dégâts chez vos voisins ?"],
  },
  {
    id: "gare",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Gare.webp",
    alt: "Le guichet d'une gare",
    imageDescription: "Un voyageur demande un renseignement au guichet d'une gare.",
    dialogueContext: "Vous préparez un voyage en train. Vous demandez les horaires, les correspondances, le quai et le prix du billet.",
    dialoguePrompts: ["Bonjour, quelle est votre destination ?", "Quand souhaitez-vous voyager ?", "Voulez-vous un aller simple ou un aller-retour ?", "Avez-vous un abonnement demi-tarif ?"],
  },
  {
    id: "hopital",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Hopital.webp",
    alt: "L'accueil d'un hôpital",
    imageDescription: "Une personne se présente à l'accueil d'un hôpital.",
    dialogueContext: "Vous accompagnez un proche à l'hôpital. Vous expliquez la situation et demandez où aller, combien de temps attendre et quels documents présenter.",
    dialoguePrompts: ["Bonjour, est-ce une urgence ?", "Quels symptômes présente la personne ?", "Avez-vous sa carte d'assurance ?", "Pouvez-vous patienter dans la salle d'attente ?"],
  },
  {
    id: "immobilier",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Immobilier.webp",
    alt: "Une agence immobilière",
    imageDescription: "Une personne cherche un logement dans une agence immobilière.",
    dialogueContext: "Vous cherchez un appartement. Vous précisez la ville, le nombre de pièces, votre budget et la date d'entrée souhaitée.",
    dialoguePrompts: ["Bonjour, quel type de logement recherchez-vous ?", "Dans quelle région souhaitez-vous habiter ?", "Quel loyer maximum pouvez-vous payer ?", "Quand voulez-vous emménager ?"],
  },
  {
    id: "pediatre",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Pediatre.webp",
    alt: "Une consultation chez le pédiatre",
    imageDescription: "Un parent consulte un pédiatre avec son enfant.",
    dialogueContext: "Votre enfant est malade. Vous téléphonez au pédiatre, décrivez les symptômes et demandez un rendez-vous rapide.",
    dialoguePrompts: ["Bonjour, quel âge a votre enfant ?", "Quels symptômes a-t-il ?", "Depuis quand est-il malade ?", "Pouvez-vous venir cet après-midi ?"],
  },
  {
    id: "pharmacie",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Pharmacie.webp",
    alt: "Une pharmacie",
    imageDescription: "Une personne demande conseil à une pharmacienne.",
    dialogueContext: "Vous avez un problème de santé léger. À la pharmacie, vous décrivez vos symptômes et demandez un produit, son prix et son utilisation.",
    dialoguePrompts: ["Bonjour, quels sont vos symptômes ?", "Depuis combien de temps les avez-vous ?", "Avez-vous des allergies ?", "Prenez-vous d'autres médicaments ?"],
  },
  {
    id: "police",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Police.webp",
    alt: "Un poste de police",
    imageDescription: "Une personne fait une déclaration dans un poste de police.",
    dialogueContext: "Vous avez perdu ou vous vous êtes fait voler un objet. Vous allez à la police et vous racontez les circonstances en décrivant précisément l'objet.",
    dialoguePrompts: ["Bonjour, que voulez-vous déclarer ?", "Où et quand cela s'est-il passé ?", "Pouvez-vous décrire l'objet ?", "Avez-vous un justificatif ou une photo ?"],
  },
  {
    id: "rendez-vous",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_RendezVous.webp",
    alt: "Une prise de rendez-vous",
    imageDescription: "Une personne téléphone pour fixer un rendez-vous.",
    dialogueContext: "Vous téléphonez pour prendre ou déplacer un rendez-vous. Vous expliquez la raison et proposez vos disponibilités.",
    dialoguePrompts: ["Bonjour, pour quel service appelez-vous ?", "Souhaitez-vous un nouveau rendez-vous ?", "Quels jours êtes-vous disponible ?", "Puis-je avoir votre nom et votre numéro ?"],
  },
  {
    id: "restaurant",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Restaurant.webp",
    alt: "Un restaurant",
    imageDescription: "Des clients commandent un repas dans un restaurant.",
    dialogueContext: "Vous êtes au restaurant. Vous demandez des renseignements sur les plats, signalez une préférence alimentaire et commandez votre repas.",
    dialoguePrompts: ["Bonjour, avez-vous choisi ?", "Souhaitez-vous connaître le plat du jour ?", "Avez-vous des allergies alimentaires ?", "Que voulez-vous boire ?"],
  },
  {
    id: "telephone",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Telephone.webp",
    alt: "Un appel téléphonique à un médecin",
    imageDescription: "Une personne téléphone à un médecin pour parler d'un problème de santé.",
    dialogueContext: "Vous ne vous sentez pas bien et vous téléphonez au cabinet médical. Vous décrivez vos symptômes, dites depuis quand vous les avez et demandez un rendez-vous.",
    dialoguePrompts: ["Cabinet médical, bonjour. Que puis-je faire pour vous ?", "Quels symptômes avez-vous ?", "Depuis quand ne vous sentez-vous pas bien ?", "Êtes-vous disponible aujourd'hui pour un rendez-vous ?"],
  },
  {
    id: "train",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Train.webp",
    alt: "Un train en gare",
    imageDescription: "Un train attend les voyageurs dans une gare suisse.",
    dialogueContext: "Vous êtes à Lausanne et vous voulez prendre le train pour Sion. Vous demandez à l'employé des CFF le prix et les réductions, la durée du trajet, les horaires et les correspondances.",
    dialoguePrompts: ["Bonjour, quand souhaitez-vous partir pour Sion ?", "Avez-vous un abonnement demi-tarif ?", "Voulez-vous un aller simple ou un aller-retour ?", "Préférez-vous le trajet le plus rapide ?"],
  },
  {
    id: "travail",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Travail.webp",
    alt: "Un entretien de travail",
    imageDescription: "Une personne participe à un entretien professionnel.",
    dialogueContext: "Vous passez un entretien d'embauche. Vous présentez votre expérience, vos compétences, vos disponibilités et vos motivations.",
    dialoguePrompts: ["Pouvez-vous vous présenter ?", "Quelle expérience avez-vous dans ce domaine ?", "Pourquoi souhaitez-vous travailler avec nous ?", "Quand pourriez-vous commencer ?"],
  },
  {
    id: "vetement",
    level: "moyen",
    image: "/expression/po/A2-B1/PO_Vetement.webp",
    alt: "Un magasin de vêtements",
    imageDescription: "Une personne choisit des vêtements dans un magasin.",
    dialogueContext: "Vous cherchez un vêtement pour une occasion particulière. Vous précisez la taille, la couleur, le budget et demandez à l'essayer.",
    dialoguePrompts: ["Bonjour, que recherchez-vous ?", "Quelle taille portez-vous ?", "Quelle couleur préférez-vous ?", "Voulez-vous l'essayer en cabine ?"],
  },
];

export function randomOralSituation(level: "base" | "moyen" | "avance"): OralSituation {
  const pool = ORAL_SITUATIONS.filter((s) =>
    level === "base" ? s.level === "base" : s.level === "moyen"
  );
  return pool[Math.floor(Math.random() * pool.length)]!;
}
