export type OralSituation = {
  id: string;
  image: string;
  alt: string;
  imageDescription: string;
  dialogueContext: string;
  dialoguePrompts: string[];
};

const ORAL_SITUATIONS: OralSituation[] = [
  {
    id: "medecin",
    image: "/expression/po/PO-Medecin.webp",
    alt: "Une consultation chez le médecin",
    imageDescription: "Une personne consulte un médecin dans son cabinet.",
    dialogueContext: "Vous ne vous sentez pas bien. Vous consultez un médecin et vous décrivez vos symptômes, leur durée et les médicaments que vous prenez.",
    dialoguePrompts: ["Bonjour, qu'est-ce qui vous amène ?", "Depuis quand avez-vous ces symptômes ?", "Avez-vous de la fièvre ou des douleurs ?", "Prenez-vous déjà un médicament ?"],
  },
  {
    id: "accident",
    image: "/expression/po/PO_Accident.webp",
    alt: "Un accident de la circulation",
    imageDescription: "Un accident vient de se produire dans la rue.",
    dialogueContext: "Vous avez été témoin d'un accident. Vous téléphonez aux secours et vous expliquez le lieu, ce qui s'est passé et l'état des personnes.",
    dialoguePrompts: ["Services d'urgence, que s'est-il passé ?", "Où se trouve exactement l'accident ?", "Combien de personnes sont blessées ?", "La circulation est-elle bloquée ?"],
  },
  {
    id: "bibliotheque",
    image: "/expression/po/PO_Bibliotheque.webp",
    alt: "Une bibliothèque",
    imageDescription: "Des personnes cherchent et consultent des livres dans une bibliothèque.",
    dialogueContext: "Vous souhaitez vous inscrire à la bibliothèque. Vous demandez les conditions, les horaires et la durée des prêts.",
    dialoguePrompts: ["Bonjour, que puis-je faire pour vous ?", "Habitez-vous dans la commune ?", "Quels types de documents voulez-vous emprunter ?", "Avez-vous besoin d'informations sur nos horaires ?"],
  },
  {
    id: "boucherie",
    image: "/expression/po/PO_Boucherie.webp",
    alt: "Une boucherie",
    imageDescription: "Un client commande des produits dans une boucherie.",
    dialogueContext: "Vous préparez un repas et vous allez à la boucherie. Vous demandez conseil sur la viande, la quantité, le prix et la préparation.",
    dialoguePrompts: ["Bonjour, qu'est-ce que je vous sers ?", "Pour combien de personnes cuisinez-vous ?", "Vous préférez une viande à cuire rapidement ?", "Est-ce que je vous la prépare en tranches ?"],
  },
  {
    id: "boulangerie",
    image: "/expression/po/PO_Boulangerie.webp",
    alt: "Une boulangerie",
    imageDescription: "Une cliente choisit du pain et des pâtisseries dans une boulangerie.",
    dialogueContext: "Vous organisez un petit déjeuner pour plusieurs personnes. Vous commandez du pain et des viennoiseries et vous demandez les prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous désirez ?", "Combien de personnes serez-vous ?", "Voulez-vous aussi des croissants ?", "Vous payez par carte ou en espèces ?"],
  },
  {
    id: "bus",
    image: "/expression/po/PO_Bus.webp",
    alt: "Un arrêt de bus",
    imageDescription: "Des voyageurs attendent un bus à un arrêt.",
    dialogueContext: "Vous devez vous rendre dans un quartier que vous ne connaissez pas. Vous demandez au conducteur le trajet, l'arrêt et le prix du billet.",
    dialoguePrompts: ["Bonjour, où souhaitez-vous aller ?", "Avez-vous déjà un billet ?", "Voulez-vous un aller simple ou un aller-retour ?", "Savez-vous à quel arrêt descendre ?"],
  },
  {
    id: "cafe",
    image: "/expression/po/PO_Cafe.webp",
    alt: "Un café",
    imageDescription: "Des clients prennent une boisson dans un café.",
    dialogueContext: "Vous entrez dans un café et vous commandez une boisson et quelque chose à manger. Vous demandez aussi le prix.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous prenez ?", "Vous désirez manger quelque chose ?", "Vous consommez ici ou à emporter ?", "Puis-je vous apporter autre chose ?"],
  },
  {
    id: "chaussure",
    image: "/expression/po/PO_Chaussure.webp",
    alt: "Un magasin de chaussures",
    imageDescription: "Une personne essaie des chaussures dans un magasin.",
    dialogueContext: "Vous cherchez des chaussures. Vous précisez votre pointure, votre budget et l'usage prévu, puis vous demandez à essayer un modèle.",
    dialoguePrompts: ["Bonjour, quel type de chaussures cherchez-vous ?", "Quelle est votre pointure ?", "Quel est votre budget ?", "Voulez-vous essayer cette paire ?"],
  },
  {
    id: "cinema",
    image: "/expression/po/PO_Cinema.webp",
    alt: "Le guichet d'un cinéma",
    imageDescription: "Des personnes choisissent un film au cinéma.",
    dialogueContext: "Vous êtes en Suisse et vous voulez voir un film. Au cinéma, vous demandez au vendeur des renseignements sur les films du moment, leur genre, leur durée, les horaires et le prix.",
    dialoguePrompts: ["Bonjour, quel genre de film souhaitez-vous voir ?", "Préférez-vous un film en français ou en version originale ?", "À quelle heure voulez-vous commencer la séance ?", "Bénéficiez-vous d'une réduction ?"],
  },
  {
    id: "club",
    image: "/expression/po/PO_Club.webp",
    alt: "Un club de loisirs",
    imageDescription: "Des personnes participent à une activité dans un club.",
    dialogueContext: "Vous souhaitez rejoindre un club. Vous demandez quelles activités sont proposées, les horaires, le matériel nécessaire et le prix de l'inscription.",
    dialoguePrompts: ["Bonjour, quelle activité vous intéresse ?", "Avez-vous déjà pratiqué cette activité ?", "Quels jours êtes-vous disponible ?", "Souhaitez-vous faire une séance d'essai ?"],
  },
  {
    id: "coiffeur",
    image: "/expression/po/PO_Coiffeur.webp",
    alt: "Un salon de coiffure",
    imageDescription: "Une cliente explique la coupe souhaitée à une coiffeuse.",
    dialogueContext: "Vous allez chez le coiffeur. Vous décrivez la coupe souhaitée et vous demandez la durée et le prix du service.",
    dialoguePrompts: ["Bonjour, qu'est-ce que vous souhaitez faire aujourd'hui ?", "Quelle longueur voulez-vous garder ?", "Voulez-vous aussi un shampoing ?", "Avez-vous une heure à laquelle vous devez partir ?"],
  },
  {
    id: "ecole",
    image: "/expression/po/PO_Ecole.webp",
    alt: "L'accueil d'une école",
    imageDescription: "Un adulte demande des renseignements à l'accueil d'une école.",
    dialogueContext: "Vous voulez inscrire votre enfant dans une école. Vous demandez les documents nécessaires, les horaires et l'organisation des cours.",
    dialoguePrompts: ["Bonjour, pour quelle classe souhaitez-vous une inscription ?", "Votre enfant était-il déjà scolarisé en Suisse ?", "Avez-vous apporté ses documents ?", "Avez-vous besoin d'un accueil parascolaire ?"],
  },
  {
    id: "fuite",
    image: "/expression/po/PO_Fuite.webp",
    alt: "Une fuite d'eau dans un logement",
    imageDescription: "Une fuite d'eau provoque des dégâts dans un logement.",
    dialogueContext: "Vous constatez une fuite d'eau chez vous. Vous appelez la régie ou un plombier et vous décrivez l'urgence et les dégâts.",
    dialoguePrompts: ["Bonjour, où se trouve la fuite ?", "Depuis quand l'eau coule-t-elle ?", "Avez-vous fermé l'arrivée d'eau ?", "Y a-t-il des dégâts chez vos voisins ?"],
  },
  {
    id: "gare",
    image: "/expression/po/PO_Gare.webp",
    alt: "Le guichet d'une gare",
    imageDescription: "Un voyageur demande un renseignement au guichet d'une gare.",
    dialogueContext: "Vous préparez un voyage en train. Vous demandez les horaires, les correspondances, le quai et le prix du billet.",
    dialoguePrompts: ["Bonjour, quelle est votre destination ?", "Quand souhaitez-vous voyager ?", "Voulez-vous un aller simple ou un aller-retour ?", "Avez-vous un abonnement demi-tarif ?"],
  },
  {
    id: "hopital",
    image: "/expression/po/PO_Hopital.webp",
    alt: "L'accueil d'un hôpital",
    imageDescription: "Une personne se présente à l'accueil d'un hôpital.",
    dialogueContext: "Vous accompagnez un proche à l'hôpital. Vous expliquez la situation et demandez où aller, combien de temps attendre et quels documents présenter.",
    dialoguePrompts: ["Bonjour, est-ce une urgence ?", "Quels symptômes présente la personne ?", "Avez-vous sa carte d'assurance ?", "Pouvez-vous patienter dans la salle d'attente ?"],
  },
  {
    id: "immobilier",
    image: "/expression/po/PO_Immobilier.webp",
    alt: "Une agence immobilière",
    imageDescription: "Une personne cherche un logement dans une agence immobilière.",
    dialogueContext: "Vous cherchez un appartement. Vous précisez la ville, le nombre de pièces, votre budget et la date d'entrée souhaitée.",
    dialoguePrompts: ["Bonjour, quel type de logement recherchez-vous ?", "Dans quelle région souhaitez-vous habiter ?", "Quel loyer maximum pouvez-vous payer ?", "Quand voulez-vous emménager ?"],
  },
  {
    id: "pediatre",
    image: "/expression/po/PO_Pediatre.webp",
    alt: "Une consultation chez le pédiatre",
    imageDescription: "Un parent consulte un pédiatre avec son enfant.",
    dialogueContext: "Votre enfant est malade. Vous téléphonez au pédiatre, décrivez les symptômes et demandez un rendez-vous rapide.",
    dialoguePrompts: ["Bonjour, quel âge a votre enfant ?", "Quels symptômes a-t-il ?", "Depuis quand est-il malade ?", "Pouvez-vous venir cet après-midi ?"],
  },
  {
    id: "pharmacie",
    image: "/expression/po/PO_Pharmacie.webp",
    alt: "Une pharmacie",
    imageDescription: "Une personne demande conseil à une pharmacienne.",
    dialogueContext: "Vous avez un problème de santé léger. À la pharmacie, vous décrivez vos symptômes et demandez un produit, son prix et son utilisation.",
    dialoguePrompts: ["Bonjour, quels sont vos symptômes ?", "Depuis combien de temps les avez-vous ?", "Avez-vous des allergies ?", "Prenez-vous d'autres médicaments ?"],
  },
  {
    id: "police",
    image: "/expression/po/PO_Police.webp",
    alt: "Un poste de police",
    imageDescription: "Une personne fait une déclaration dans un poste de police.",
    dialogueContext: "Vous avez perdu ou vous vous êtes fait voler un objet. Vous allez à la police et vous racontez les circonstances en décrivant précisément l'objet.",
    dialoguePrompts: ["Bonjour, que voulez-vous déclarer ?", "Où et quand cela s'est-il passé ?", "Pouvez-vous décrire l'objet ?", "Avez-vous un justificatif ou une photo ?"],
  },
  {
    id: "rendez-vous",
    image: "/expression/po/PO_RendezVous.webp",
    alt: "Une prise de rendez-vous",
    imageDescription: "Une personne téléphone pour fixer un rendez-vous.",
    dialogueContext: "Vous téléphonez pour prendre ou déplacer un rendez-vous. Vous expliquez la raison et proposez vos disponibilités.",
    dialoguePrompts: ["Bonjour, pour quel service appelez-vous ?", "Souhaitez-vous un nouveau rendez-vous ?", "Quels jours êtes-vous disponible ?", "Puis-je avoir votre nom et votre numéro ?"],
  },
  {
    id: "restaurant",
    image: "/expression/po/PO_Restaurant.webp",
    alt: "Un restaurant",
    imageDescription: "Des clients commandent un repas dans un restaurant.",
    dialogueContext: "Vous êtes au restaurant. Vous demandez des renseignements sur les plats, signalez une préférence alimentaire et commandez votre repas.",
    dialoguePrompts: ["Bonjour, avez-vous choisi ?", "Souhaitez-vous connaître le plat du jour ?", "Avez-vous des allergies alimentaires ?", "Que voulez-vous boire ?"],
  },
  {
    id: "telephone",
    image: "/expression/po/PO_Telephone.webp",
    alt: "Un appel téléphonique à un médecin",
    imageDescription: "Une personne téléphone à un médecin pour parler d'un problème de santé.",
    dialogueContext: "Vous ne vous sentez pas bien et vous téléphonez au cabinet médical. Vous décrivez vos symptômes, dites depuis quand vous les avez et demandez un rendez-vous.",
    dialoguePrompts: ["Cabinet médical, bonjour. Que puis-je faire pour vous ?", "Quels symptômes avez-vous ?", "Depuis quand ne vous sentez-vous pas bien ?", "Êtes-vous disponible aujourd'hui pour un rendez-vous ?"],
  },
  {
    id: "train",
    image: "/expression/po/PO_Train.webp",
    alt: "Un train en gare",
    imageDescription: "Un train attend les voyageurs dans une gare suisse.",
    dialogueContext: "Vous êtes à Lausanne et vous voulez prendre le train pour Sion. Vous demandez à l'employé des CFF le prix et les réductions, la durée du trajet, les horaires et les correspondances.",
    dialoguePrompts: ["Bonjour, quand souhaitez-vous partir pour Sion ?", "Avez-vous un abonnement demi-tarif ?", "Voulez-vous un aller simple ou un aller-retour ?", "Préférez-vous le trajet le plus rapide ?"],
  },
  {
    id: "travail",
    image: "/expression/po/PO_Travail.webp",
    alt: "Un entretien de travail",
    imageDescription: "Une personne participe à un entretien professionnel.",
    dialogueContext: "Vous passez un entretien d'embauche. Vous présentez votre expérience, vos compétences, vos disponibilités et vos motivations.",
    dialoguePrompts: ["Pouvez-vous vous présenter ?", "Quelle expérience avez-vous dans ce domaine ?", "Pourquoi souhaitez-vous travailler avec nous ?", "Quand pourriez-vous commencer ?"],
  },
  {
    id: "vetement",
    image: "/expression/po/PO_Vetement.webp",
    alt: "Un magasin de vêtements",
    imageDescription: "Une personne choisit des vêtements dans un magasin.",
    dialogueContext: "Vous cherchez un vêtement pour une occasion particulière. Vous précisez la taille, la couleur, le budget et demandez à l'essayer.",
    dialoguePrompts: ["Bonjour, que recherchez-vous ?", "Quelle taille portez-vous ?", "Quelle couleur préférez-vous ?", "Voulez-vous l'essayer en cabine ?"],
  },
];

export function randomOralSituation(): OralSituation {
  return ORAL_SITUATIONS[Math.floor(Math.random() * ORAL_SITUATIONS.length)]!;
}
